import { siteConfig } from "./site";

export type LegalSection = {
  id: string;
  title: string;
  paragraphs: string[];
  bullets?: string[];
};

function withSite(text: string) {
  return text
    .replaceAll("{siteName}", siteConfig.name)
    .replaceAll("{siteUrl}", siteConfig.url)
    .replaceAll("{contactEmail}", siteConfig.contactEmail)
    .replaceAll("{lastUpdated}", siteConfig.legalLastUpdated)
    .replaceAll("{checkoutProvider}", siteConfig.checkoutProvider)
    .replaceAll("{checkoutSeller}", siteConfig.checkoutSeller);
}

function sections(input: LegalSection[]): LegalSection[] {
  return input.map((section) => ({
    ...section,
    paragraphs: section.paragraphs.map(withSite),
    bullets: section.bullets?.map(withSite),
  }));
}

export const privacySections = sections([
  {
    id: "overview",
    title: "Overview",
    paragraphs: [
      "{siteName} publishes digital study products at {siteUrl}. This Privacy Policy explains what information we collect when you visit the website, how we use it, and what choices you have.",
    ],
  },
  {
    id: "controller",
    title: "Who is responsible",
    paragraphs: [
      "The website operator for {siteName} is the publisher identified on the Contact page. For purchase and payment processing, checkout is handled by {checkoutProvider} on behalf of {checkoutSeller}.",
      "If you have privacy questions or requests, contact us at {contactEmail}.",
    ],
  },
  {
    id: "collect",
    title: "Information we collect",
    paragraphs: ["We collect limited technical and usage information to operate and improve the website."],
    bullets: [
      "Page and funnel events such as page views, section views, and checkout clicks.",
      "Google Analytics page and interaction data when you accept analytics cookies.",
      "Ahrefs Analytics traffic and page view data when you accept analytics cookies.",
      "Technical metadata such as browser user agent, page path, and referrer URL when events are sent.",
      "Cookie consent preference stored in your browser local storage.",
      "Server logs generated by hosting infrastructure for security and reliability.",
    ],
  },
  {
    id: "no-account",
    title: "Information we do not collect on this site",
    paragraphs: [
      "The public website does not require account registration and does not ask for your name, postal address, or payment details. Payment information is collected directly by {checkoutProvider} during checkout.",
    ],
  },
  {
    id: "use",
    title: "How we use information",
    paragraphs: ["We use collected information for the following purposes:"],
    bullets: [
      "Measuring landing page performance and checkout intent.",
      "Debugging technical issues and protecting the service from abuse.",
      "Improving product pages and documentation.",
      "Responding to support or privacy requests you send to us.",
    ],
  },
  {
    id: "legal-basis",
    title: "Legal bases for processing",
    paragraphs: [
      "Where applicable privacy law requires a legal basis, we rely on consent for optional analytics, legitimate interests for essential site operation and security, and contractual necessity when responding to support requests related to a purchase.",
    ],
  },
  {
    id: "sharing",
    title: "Sharing and third parties",
    paragraphs: [
      "We do not sell personal information. We share data only with service providers needed to run the website and with third parties you choose to interact with.",
    ],
    bullets: [
      "{checkoutProvider} when you click through to purchase a product.",
      "Google when you accept analytics cookies and Google Analytics is loaded.",
      "Ahrefs when you accept analytics cookies and Ahrefs Analytics is loaded.",
      "Hosting, deployment, and infrastructure providers that process server logs.",
      "Authorities or advisers if required by law or to protect legal rights.",
    ],
  },
  {
    id: "retention",
    title: "Retention",
    paragraphs: [
      "Analytics events may be stored temporarily in server memory and logs for operational review. Retention periods depend on hosting log settings and internal analytics tooling. Contact us if you need details about current retention.",
    ],
  },
  {
    id: "rights",
    title: "Your rights",
    paragraphs: [
      "Depending on your location, you may have rights to access, correct, delete, restrict, or object to processing of your personal information, and to withdraw consent where processing is consent-based.",
      "To exercise these rights, email {contactEmail}. We may need to verify your request.",
    ],
  },
  {
    id: "international",
    title: "International transfers",
    paragraphs: [
      "Our hosting and checkout providers may process data in countries other than your own. Where required, we rely on appropriate safeguards provided by those vendors.",
    ],
  },
  {
    id: "children",
    title: "Children",
    paragraphs: [
      "Our products are intended for exam candidates and professional learners. The site is not directed to children under 16, and we do not knowingly collect personal information from children.",
    ],
  },
  {
    id: "changes",
    title: "Changes to this policy",
    paragraphs: [
      "We may update this Privacy Policy from time to time. The latest version will always be posted on this page with an updated date.",
    ],
  },
]);

export const termsSections = sections([
  {
    id: "agreement",
    title: "Agreement",
    paragraphs: [
      "By accessing {siteUrl}, you agree to these Terms of Service. If you do not agree, do not use the website or purchase products linked from it.",
    ],
  },
  {
    id: "products",
    title: "Products and delivery",
    paragraphs: [
      "{siteName} sells digital study materials such as Anki flashcard decks. Products are delivered electronically after successful checkout on {checkoutProvider}.",
      "Product descriptions, card counts, formats, and pricing on the website are provided for information. The checkout page on {checkoutProvider} is authoritative for the final purchase price and delivery flow.",
    ],
  },
  {
    id: "license",
    title: "License and acceptable use",
    paragraphs: ["When you purchase a digital deck, you receive a personal, non-exclusive, non-transferable license to use the files for your own exam preparation."],
    bullets: [
      "You may not redistribute, resell, publicly share, or republish purchased deck files.",
      "You may not use the materials to imply endorsement by CFA Institute or any exam body.",
      "You may not scrape, reverse engineer, or bulk extract content to create competing products.",
    ],
  },
  {
    id: "disclaimer",
    title: "Educational disclaimer",
    paragraphs: [
      "{siteName} is an independent publisher. Our materials are supplementary study aids and do not replace official curriculum, learning outcomes, practice exams, or professional advice.",
      "CFA Institute does not endorse, promote, or warrant our products. CFA and Chartered Financial Analyst are trademarks owned by CFA Institute.",
    ],
  },
  {
    id: "payments",
    title: "Payments, taxes, and refunds",
    paragraphs: [
      "Payments are processed by {checkoutProvider}. Applicable taxes, invoices, receipts, and refund eligibility are handled according to {checkoutProvider}'s terms and the product listing at checkout.",
      "If you have a billing or delivery issue, use your {checkoutProvider} receipt and support flow first, then contact us at {contactEmail} if you still need help.",
    ],
  },
  {
    id: "availability",
    title: "Availability and changes",
    paragraphs: [
      "We may update product pages, pricing, sample content, or site features at any time. We do not guarantee uninterrupted access to the website or that every description will remain unchanged after purchase.",
    ],
  },
  {
    id: "warranty",
    title: "Disclaimer of warranties",
    paragraphs: [
      "The website and digital products are provided on an as-is and as-available basis to the fullest extent permitted by law. We do not warrant that use of the materials will result in exam success or error-free operation.",
    ],
  },
  {
    id: "liability",
    title: "Limitation of liability",
    paragraphs: [
      "To the fullest extent permitted by law, {siteName} and its operator will not be liable for indirect, incidental, special, consequential, or punitive damages, or for loss of profits, data, or exam outcomes arising from use of the website or purchased materials.",
      "Nothing in these terms limits rights that cannot be excluded under mandatory consumer protection law.",
    ],
  },
  {
    id: "ip",
    title: "Intellectual property",
    paragraphs: [
      "All website content, branding, deck structure, and original card content are owned by the publisher or its licensors. Trademarks of third parties remain the property of their respective owners.",
    ],
  },
  {
    id: "termination",
    title: "Suspension",
    paragraphs: [
      "We may restrict access to the website if we reasonably believe a user is abusing the service, infringing intellectual property, or attempting to disrupt site operations.",
    ],
  },
  {
    id: "changes",
    title: "Changes to these terms",
    paragraphs: [
      "We may revise these Terms of Service by posting an updated version on this page. Continued use of the website after changes become effective constitutes acceptance of the revised terms.",
    ],
  },
  {
    id: "contact",
    title: "Contact",
    paragraphs: ["Questions about these terms can be sent to {contactEmail}."],
  },
]);

export const cookieSections = sections([
  {
    id: "overview",
    title: "Overview",
    paragraphs: [
      "This Cookie Policy explains how {siteName} uses cookies, local storage, and similar technologies on {siteUrl}.",
    ],
  },
  {
    id: "what",
    title: "What technologies we use",
    paragraphs: [
      "Cookies are small text files stored in your browser. We also use browser local storage to remember your cookie preference. Some analytics on this site are sent through first-party requests rather than traditional third-party ad cookies.",
    ],
  },
  {
    id: "categories",
    title: "Categories of technologies",
    paragraphs: ["We group technologies into the following categories:"],
    bullets: [
      "Strictly necessary: required to remember your cookie consent choice.",
      "Analytics: optional Google Analytics, Ahrefs Analytics, and first-party usage events that help us understand page performance and checkout intent.",
      "Third-party checkout: technologies that may be set when you open {checkoutProvider} to complete a purchase.",
    ],
  },
  {
    id: "table",
    title: "Technologies in use on this site",
    paragraphs: ["The following table describes the main technologies currently used on {siteUrl}:"],
    bullets: [
      "uniprep2go_cookie_consent (local storage, strictly necessary): stores accepted or rejected analytics preference until you clear site data.",
      "Google Analytics cookies such as _ga and _ga_* (analytics, optional): used to measure site usage when you accept analytics cookies. Measurement ID: G-NDF8PVD7N3.",
      "Ahrefs Analytics script (analytics, optional): loads from analytics.ahrefs.com with site key X11yI8gl/4QXmr55ol2GlA when you accept analytics cookies.",
      "First-party analytics events (analytics, optional): page views, section views, and checkout click events sent to /api/events when you accept analytics cookies.",
      "{checkoutProvider} checkout pages (third-party): may set their own cookies or storage when you leave our site to purchase a product.",
    ],
  },
  {
    id: "choices",
    title: "Your choices",
    paragraphs: [
      "When you first visit the site, you can accept or reject optional analytics cookies using the banner. You can also change your browser settings to block or delete cookies and local storage.",
      "Rejecting analytics cookies means we will not load Google Analytics, Ahrefs Analytics, or send optional funnel analytics events from your browser.",
    ],
  },
  {
    id: "browser",
    title: "Browser controls",
    paragraphs: [
      "Most browsers allow you to manage cookies and site data through privacy settings. Clearing site data for {siteUrl} will remove your stored consent preference and show the banner again.",
    ],
  },
  {
    id: "changes",
    title: "Changes",
    paragraphs: [
      "If we add new cookies or tracking technologies, we will update this page and, where required, request consent again.",
    ],
  },
  {
    id: "contact",
    title: "Contact",
    paragraphs: ["Questions about cookies or analytics can be sent to {contactEmail}."],
  },
]);

export const contactSections = sections([
  {
    id: "general",
    title: "General contact",
    paragraphs: [
      "For questions about {siteName}, product content, website issues, privacy requests, or legal notices, email {contactEmail}.",
    ],
  },
  {
    id: "purchases",
    title: "Purchases and delivery",
    paragraphs: [
      "Checkout, payment, receipts, download access, and refund requests are handled through {checkoutProvider}. If you already purchased a deck, use the receipt and support options provided by {checkoutProvider} first.",
      "If you still need help after checking {checkoutProvider}, contact us at {contactEmail} with your order email and product name.",
    ],
  },
  {
    id: "privacy",
    title: "Privacy and data requests",
    paragraphs: [
      "To request access, correction, or deletion of personal information processed by this website, email {contactEmail} with the subject line Privacy Request.",
    ],
  },
  {
    id: "response",
    title: "Response time",
    paragraphs: [
      "We aim to respond to legitimate support and privacy requests within 3 business days.",
    ],
  },
]);
