const BOT_USER_AGENT_PATTERNS = [
  /bot/i,
  /spider/i,
  /crawl/i,
  /slurp/i,
  /mediapartners-google/i,
  /googlebot/i,
  /bingbot/i,
  /yandex/i,
  /baiduspider/i,
  /duckduckbot/i,
  /facebookexternalhit/i,
  /meta-externalagent/i,
  /twitterbot/i,
  /linkedinbot/i,
  /whatsapp/i,
  /telegrambot/i,
  /discordbot/i,
  /slackbot/i,
  /applebot/i,
  /semrush/i,
  /ahrefs/i,
  /mj12bot/i,
  /dotbot/i,
  /petalbot/i,
  /bytespider/i,
  /headless/i,
  /phantomjs/i,
  /puppeteer/i,
  /playwright/i,
  /selenium/i,
  /lighthouse/i,
  /pagespeed/i,
  /pingdom/i,
  /uptimerobot/i,
  /statuscake/i,
  /gtmetrix/i,
  /screaming frog/i,
  /\bwget\b/i,
  /\bcurl\//i,
  /python-requests/i,
  /go-http-client/i,
  /libwww-perl/i,
  /httpclient/i,
  /scrapy/i,
  /gptbot/i,
  /chatgpt-user/i,
  /oai-searchbot/i,
  /claudebot/i,
  /claude-web/i,
  /anthropic-ai/i,
  /perplexitybot/i,
  /perplexity-user/i,
  /cohere-ai/i,
  /amazonbot/i,
  /ccbot/i,
  /google-extended/i,
  /applebot-extended/i,
  /vercelbot/i,
  /vercel-screenshot/i,
  /uniprep2go-/i,
] as const;

export function isBotUserAgent(userAgent: string | null | undefined) {
  const normalized = userAgent?.trim();

  if (!normalized) {
    return false;
  }

  return BOT_USER_AGENT_PATTERNS.some((pattern) => pattern.test(normalized));
}
