/** AAPC CPC — 40 curated MCQs */
export const topics = {
  "coding-guidelines": [
    [
      "ICD-10-CM codes are used primarily to report:",
      "Diagnoses and symptoms/reasons for the encounter",
      ["Only CPT surgical procedures", "Only anesthesia time units", "Place of service exclusively"],
      "ICD-10-CM classifies diseases/symptoms; CPT/HCPCS report services/procedures/supplies.",
      [
        "CPT is procedures/services.",
        "Anesthesia uses CPT + time/modifiers concepts.",
        "POS is a claim field, not diagnosis coding.",
      ],
      "easy",
    ],
    [
      "When a definitive diagnosis is established after workup, outpatient coding generally reports:",
      "The confirmed diagnosis rather than the previously suspected rule-out alone when confirmed",
      ["Only 'rule out cancer' forever", "Signs/symptoms instead of confirmed DX always", "No diagnosis codes"],
      "Outpatient rules differ from inpatient uncertain diagnosis rules; code confirmed conditions to the highest specificity supported.",
      [
        "Do not code uncertain outpatient diagnoses as if confirmed.",
        "Symptoms used when no confirmed DX.",
        "Claims need diagnosis codes.",
      ],
      "hard",
    ],
    [
      "CPT Category I codes generally describe:",
      "Established medical services and procedures widely performed",
      ["Emerging technologies only as Category III", "Temporary national codes only as HCPCS G/Q always", "Dental CDT exclusively"],
      "Category I are main CPT services; Category III are emerging; HCPCS Level II covers many supplies/drugs/services.",
      [
        "Cat III are temporary emerging.",
        "HCPCS II is separate system.",
        "CDT is dental.",
      ],
      "easy",
    ],
    [
      "NEC in ICD-10-CM means:",
      "Not elsewhere classified — other specified when a more precise code is unavailable",
      ["Not enough caffeine", "Never ever code", "Non-exempt condition always"],
      "NEC/NOS conventions guide residual code selection when documentation specificity is limited or classification lacks detail.",
      [
        "Silly expansion.",
        "Codes are assigned when supported.",
        "NEC is a classification convention.",
      ],
      "medium",
    ],
    [
      "A combination code is used when:",
      "A single code captures a condition and its manifestation/associated condition as directed",
      ["Two unrelated visits are merged illegally", "Modifiers replace all diagnosis coding", "Place of service is 22"],
      "Guidelines instruct use of combination codes when available rather than multiple codes unnecessarily.",
      [
        "Visits aren't combined via DX combo rules that way.",
        "Modifiers adjust services.",
        "POS 22 is outpatient hospital.",
      ],
      "medium",
    ],
    [
      "Sequencing the principal/first-listed diagnosis should reflect:",
      "The main reason for the encounter/admission per guidelines",
      ["The code that pays the most always regardless of documentation", "Alphabetical first code in the book", "The patient's favorite diagnosis"],
      "Code sequencing follows official guidelines and documentation—not reimbursement maximization schemes.",
      [
        "Upcoding/sequencing for payment only is noncompliant.",
        "Alpha order isn't sequencing.",
        "Patient preference isn't coding rule.",
      ],
      "easy",
    ],
    [
      "CPT guidelines and notes at section/heading levels are:",
      "Instructional and must be followed for correct coding",
      ["Optional suggestions only", "Relevant only to ICD-10-PCS", "Used solely for dental claims"],
      "Parenthetical notes, includes/excludes-type instructions, and section guidelines control code use.",
      [
        "They are not optional.",
        "PCS is inpatient procedures.",
        "Dental uses CDT primarily.",
      ],
      "easy",
    ],
    [
      "External cause codes (V00–Y99 concepts) are used to:",
      "Provide information about how an injury/poisoning occurred, when required/assigned",
      ["Replace all diagnosis codes on every claim", "Report only E/M services", "Indicate POS"],
      "External causes supplement injury coding; they do not replace the injury diagnosis.",
      [
        "They supplement, not replace.",
        "E/M is CPT.",
        "POS is separate.",
      ],
      "medium",
    ],
    [
      "Laterality in ICD-10-CM means coding must capture:",
      "Left, right, or bilateral when the classification provides those options and documentation supports them",
      ["Only unspecified always if paid better", "No side information ever", "Provider specialty only"],
      "Choose the most specific laterality code supported; unspecified if not documented.",
      [
        "Don't pick unspecified to manipulate payment.",
        "Laterality exists in many codes.",
        "Specialty isn't laterality.",
      ],
      "easy",
    ],
    [
      "What is the purpose of the Alphabetic Index and Tabular List process in ICD-10-CM?",
      "Locate a candidate code in the Index, then verify and complete coding in the Tabular List",
      ["Use only the Index and never the Tabular", "Use only Google without books/guidelines", "Assign CPT from the ICD Index"],
      "Never code from the Index alone; Tabular instructions control final assignment.",
      [
        "Tabular verification is mandatory.",
        "Official classification required.",
        "ICD Index is not for CPT.",
      ],
      "medium",
    ]
  ],
  "evaluation-management": [
    [
      "Office/outpatient E/M level selection (current AMA framework) is based primarily on:",
      "Medical decision making or total time on the date of the encounter, per guidelines",
      ["Only the number of bullet exam elements from 1995 forever exclusively", "Patient age only", "Whether the patient brought cookies"],
      "Since 2021 office E/M revisions, MDM or time drives levels; older exam-bullet counting is not the current office paradigm.",
      [
        "1995/97 exam scoring is largely superseded for office/outpatient.",
        "Age alone doesn't set level.",
        "Cookies irrelevant.",
      ],
      "medium",
    ],
    [
      "New patient vs established patient for E/M depends on whether the patient has received face-to-face professional services from the same group/specialty within:",
      "The past three years",
      ["The past three days only", "Ten years always", "Never—everyone is always new"],
      "CPT defines established as seen by same specialty/group within 3 years (with nuances).",
      [
        "Three days is wrong.",
        "Ten years is wrong.",
        "Distinction exists.",
      ],
      "easy",
    ],
    [
      "Medical Decision Making complexity considers:",
      "Number/complexity of problems, data reviewed/analyzed, and risk of management",
      ["Only the font size of the note", "Only how long the patient waited", "Whether the waiting room was full"],
      "MDM elements are problems, data, and risk under AMA E/M methodology.",
      [
        "Formatting irrelevant.",
        "Wait time isn't MDM.",
        "Census isn't MDM.",
      ],
      "easy",
    ],
    [
      "Time-based office E/M coding includes:",
      "Total time on the date of the encounter spent on the patient's care (including non-face-to-face), per CPT rules",
      ["Only the minute the provider entered the room", "Staff coffee breaks", "Time spent by the patient driving"],
      "Counseling/coordination and other activities on that date may count when using time, per definitions.",
      [
        "Door-entry instant is incomplete.",
        "Breaks aren't patient care time.",
        "Patient drive time doesn't count.",
      ],
      "hard",
    ],
    [
      "A preventive medicine E/M visit is distinct from a problem-oriented visit because it:",
      "Focuses on routine preventive evaluation appropriate to age/risk rather than a chief complaint problem management primarily",
      ["Always uses critical care codes", "Is reported with only anesthesia codes", "Never requires a diagnosis code"],
      "Preventive visits use preventive CPT codes; significant separately identifiable problem E/M may be reported with modifier 25 when supported.",
      [
        "Critical care is different.",
        "Anesthesia is separate.",
        "Diagnosis/Z codes still used.",
      ],
      "medium",
    ],
    [
      "Modifier 25 indicates:",
      "Significant, separately identifiable E/M service by the same physician on the same day as a procedure",
      ["Bilateral procedure", "Reduced services", "Repeat procedure by another physician"],
      "Modifier 25 appends to the E/M, not the procedure, when documentation supports separateness.",
      [
        "50 is bilateral.",
        "52 is reduced.",
        "77 is repeat by another.",
      ],
      "medium",
    ],
    [
      "Critical care coding requires:",
      "High-complexity decision making for critically ill/injured patients with specific time thresholds and organ system failure risk",
      ["Any brief hallway chat", "Only suture removal", "Well-child care"],
      "Critical care is a defined CPT service with time and clinical criteria—not ordinary E/M.",
      [
        "Hallway chat isn't critical care.",
        "Suture removal is minor.",
        "Well-child is preventive.",
      ],
      "hard",
    ],
    [
      "Consultation codes vs transfer of care: a consultation conceptually involves:",
      "Advice/opinion requested by another provider, with report back (payer policies vary widely on consult codes)",
      ["Always taking over complete care without request", "Only emergency intubation", "Only nursing facility discharge"],
      "Many payers (notably Medicare historically) limit consult coding; understand request/render/report concepts and current payer rules.",
      [
        "Transfer of care differs from consult.",
        "Intubation is procedure.",
        "NF discharge has its own E/M.",
      ],
      "hard",
    ],
    [
      "Place of service code on a claim identifies:",
      "Where the service was rendered (e.g., office, outpatient hospital, ED)",
      ["The diagnosis family only", "The modifier list", "NPI taxonomy exclusively"],
      "POS affects payment and must match the service setting.",
      [
        "DX are separate fields.",
        "Modifiers are separate.",
        "Taxonomy is provider classification.",
      ],
      "easy",
    ],
    [
      "When billing an E/M with a minor procedure the same day, documentation should show:",
      "The E/M is significant and separately identifiable beyond the usual pre/post work of the procedure if both are billed",
      ["No history or MDM for the E/M portion ever", "That the procedure was not performed", "Only a cloned note from another patient"],
      "Payers scrutinize same-day E/M + procedure; modifier 25 and solid documentation are key.",
      [
        "E/M needs support.",
        "Procedure must have been done if billed.",
        "Cloning wrong-patient notes is fraud risk.",
      ],
      "medium",
    ]
  ],
  "surgery-anesthesia": [
    [
      "The surgical package (global surgery) typically includes:",
      "Local infiltration, certain related E/M, and routine postoperative care within the global period as defined",
      ["All unrelated surgeries for 10 years", "Only the anesthesia code", "Never any follow-up visits"],
      "CPT surgical package and payer global periods define what is bundled vs separately reportable.",
      [
        "Unrelated services may be separate.",
        "Anesthesia often separate.",
        "Post-op visits in global are often bundled.",
      ],
      "medium",
    ],
    [
      "Modifier 78 indicates:",
      "Unplanned return to the OR for a related procedure during the postoperative period",
      ["Staged/related procedure by same physician (58)", "Unrelated procedure in postop (79)", "Bilateral (50)"],
      "Know 58/78/79 distinctions for returns during global periods.",
      [
        "58 is staged/planned more extensive etc.",
        "79 is unrelated.",
        "50 is bilateral.",
      ],
      "hard",
    ],
    [
      "NCCI edits primarily exist to:",
      "Prevent improper reporting of services that should not be billed together",
      ["Increase RVUs automatically", "Replace ICD-10 guidelines", "Assign anesthesia ASAs"],
      "NCCI PTP edits and MUEs control unbundling; modifiers may bypass when clinically appropriate (e.g., 59/X{EPSU}).",
      [
        "Edits limit improper payment.",
        "ICD guidelines remain.",
        "Anesthesia has separate concepts.",
      ],
      "medium",
    ],
    [
      "Anesthesia coding typically uses:",
      "CPT anesthesia codes with base units + time units + modifying units (payer rules)",
      ["Only E/M office codes", "Only ICD procedure codes on professional claims always", "Dental prophy codes"],
      "Anesthesia payment formulas combine base and time; physical status/qualifying circumstances may apply.",
      [
        "E/M isn't anesthesia billing.",
        "PCS is inpatient hospital procedures.",
        "Dental prophy is dental.",
      ],
      "medium",
    ],
    [
      "Modifier 51 is used for:",
      "Multiple procedures performed at the same session by the same provider (when applicable)",
      ["Assistant surgeon", "Bilateral only", "Decision for surgery"],
      "Multiple procedure reductions often apply; some codes are modifier 51 exempt.",
      [
        "80/82 assistant surgery.",
        "50 bilateral.",
        "57 decision for surgery on E/M.",
      ],
      "medium",
    ],
    [
      "Separate procedure designation in CPT means:",
      "The code is usually component of a larger service and not reported in addition when integral",
      ["It must always be billed with every surgery", "It replaces anesthesia", "It is never payable under any circumstance"],
      "If performed alone for a distinct reason, a 'separate procedure' may be reportable; otherwise bundled.",
      [
        "Not always add-on.",
        "Anesthesia separate.",
        "Payable when truly separate/sole.",
      ],
      "hard",
    ],
    [
      "Wound repair coding selection depends mainly on:",
      "Complexity (simple/intermediate/complex), length, and location",
      ["Only patient insurance plan name", "Only the suture brand", "Time of day only"],
      "Add lengths of same classification/anatomic grouping per CPT rules; intermediate includes layered closure etc.",
      [
        "Payer name doesn't choose complexity.",
        "Brand irrelevant.",
        "Time of day irrelevant.",
      ],
      "easy",
    ],
    [
      "Global surgical periods commonly used by Medicare concepts include:",
      "0-day, 10-day, and 90-day globals depending on the procedure",
      ["Only 365-day globals for every code", "No postoperative period ever", "Globals apply only to pathology"],
      "Minor procedures often 0/10; major often 90—verify each code.",
      [
        "Not universally 365.",
        "Globals exist for many surgeries.",
        "Pathology has different concepts.",
      ],
      "easy",
    ],
    [
      "Assistant surgeon modifiers (e.g., 80) indicate:",
      "Another surgeon assists the primary surgeon when medically necessary and allowed",
      ["The patient assisted scrub tech", "Bilateral surgery", "Reduced anesthesia time only"],
      "Documentation must support necessity; payer assistant policies vary (including PA/NP assisting modifiers).",
      [
        "Patient isn't assistant surgeon.",
        "50 is bilateral.",
        "Anesthesia time differs.",
      ],
      "medium",
    ],
    [
      "Add-on codes in CPT are identified by:",
      "A '+' symbol and are never reported as stand-alone primary codes",
      ["Being listed only in ICD-10-CM", "Always requiring modifier 51", "Only applying to DME"],
      "Add-on codes are reported in addition to a primary code; modifier 51 is typically not used on add-ons.",
      [
        "They're CPT convention.",
        "51 usually not appended to add-ons.",
        "Not only DME.",
      ],
      "medium",
    ]
  ],
  "compliance-billing": [
    [
      " Upcoding is:",
      "Reporting a higher-level service than documented/supported",
      ["Reporting a lower level than performed intentionally always as the definition", "Using the correct code", "Appending a correct modifier"],
      "Upcoding is a compliance/fraud risk; downcoding underreports services.",
      [
        "That's downcoding/under coding concepts.",
        "Correct coding is compliant.",
        "Proper modifiers are fine.",
      ],
      "easy",
    ],
    [
      "The False Claims Act targets:",
      "Knowingly submitting false or fraudulent claims to the government",
      ["Honest clerical corrections via timely voids/replacements", "Patient thank-you cards", "Scheduling reminders"],
      "Knowledge includes deliberate ignorance/reckless disregard in FCA jurisprudence—compliance programs matter.",
      [
        "Good-faith corrections differ.",
        "Courtesy cards fine.",
        "Reminders fine.",
      ],
      "medium",
    ],
    [
      "HIPAA privacy rules govern:",
      "Protected health information use and disclosure",
      ["Only CPT relative value units", "Only OSHA sharps logs", "Federal highway speed limits"],
      "Covered entities must safeguard PHI; minimum necessary and patient rights apply.",
      [
        "RVUs are payment.",
        "OSHA is safety.",
        "Speed limits are traffic.",
      ],
      "easy",
    ],
    [
      "HCPCS Level II codes commonly report:",
      "Drugs, supplies, DME, and certain services not in CPT",
      ["ICD diagnoses", "Only inpatient ICD-10-PCS", "Only anesthesia base units"],
      "A-codes, J-codes, etc., are Level II examples used on claims with CPT as applicable.",
      [
        "Diagnoses are ICD.",
        "PCS is hospital inpatient procedures.",
        "Anesthesia base is CPT anesthesia methodology.",
      ],
      "easy",
    ],
    [
      "ABN (Advance Beneficiary Notice) is used when:",
      "A provider believes Medicare may deny a service as not reasonable/necessary and the beneficiary may be liable",
      ["Medicaid always pays 100%", "A service is always covered without issue", "The patient is under age 1 always"],
      "ABN shifts financial liability for expected denials when properly executed for Medicare Part B situations.",
      [
        "Not a Medicaid payment guarantee.",
        "Covered services don't need ABN for that reason.",
        "Age unrelated generally.",
      ],
      "hard",
    ],
    [
      "National Provider Identifier (NPI) is:",
      "A unique identification number for covered health care providers",
      ["A diagnosis code", "A place of service code", "A patient's SSN replacement on all public posts"],
      "NPIs identify providers on claims; do not confuse with taxonomy or PIN legacy systems.",
      [
        "DX are ICD.",
        "POS is two-digit setting.",
        "SSNs must not be publicly posted.",
      ],
      "easy",
    ],
    [
      "Unbundling means:",
      "Billing component codes separately when a comprehensive code includes them, contrary to rules",
      ["Using a panel code correctly", "Following NCCI", "Reporting one inclusive code properly"],
      "Unbundling to increase payment violates NCCI/CPT inclusive coding principles.",
      [
        "Correct panel use is fine.",
        "Following NCCI is compliant.",
        "Inclusive coding is proper.",
      ],
      "medium",
    ],
    [
      "Medical necessity means:",
      "Services are reasonable and necessary for diagnosis/treatment per payer coverage criteria",
      ["Any service a patient requests for convenience only always payable", "The most expensive option always", "Services without documentation"],
      "Coverage policies/LCDs/NCDs define necessity; documentation must support it.",
      [
        "Convenience isn't automatic necessity.",
        "Cost ≠ necessity.",
        "No documentation fails audits.",
      ],
      "easy",
    ],
    [
      "A compliance program commonly includes:",
      "Policies, training, auditing, and a process to report/respond to issues",
      ["Encouraging silent upcoding goals", "Destroying records after one week always", "Sharing passwords among all staff"],
      "OIG seven-element concepts emphasize prevention and detection of fraud/abuse.",
      [
        "Upcoding goals are illegal.",
        "Retention schedules are longer.",
        "Password sharing breaks security.",
      ],
      "medium",
    ],
    [
      "Modifier 59 (or X{EPSU}) is used to indicate:",
      "A distinct procedural service not normally reported together, when criteria are met",
      ["Bilateral surgery", "Assistant surgeon", "Increased E/M complexity automatically"],
      "Use distinct-service modifiers only with documentation; overuse is an audit target.",
      [
        "50 bilateral.",
        "80 assistant.",
        "E/M complexity isn't 59.",
      ],
      "hard",
    ]
  ],
};
