/** ARDMS SPI — 40 curated MCQs */
export const topics = {
  "physics-basics": [
    [
      "Ultrasound is defined as sound with frequency:",
      "Greater than 20 kHz (above human hearing)",
      ["Less than 20 Hz only", "Exactly equal to audible midrange always", "Only ionizing gamma energy"],
      "Diagnostic ultrasound commonly uses MHz frequencies.",
      [
        "<20 Hz is infrasound.",
        "Audible is ~20 Hz–20 kHz.",
        "Ultrasound is non-ionizing mechanical waves.",
      ],
      "easy",
    ],
    [
      "Wavelength equals:",
      "Propagation speed divided by frequency (c/f)",
      ["Frequency times period only as wavelength", "Density divided by stiffness only", "PRP times DF"],
      "λ = c/f; higher frequency → shorter wavelength → better axial resolution generally.",
      [
        "f×T = 1, not λ.",
        "Density/stiffness relate to speed.",
        "PRP/DF are pulsed wave timing.",
      ],
      "easy",
    ],
    [
      "Propagation speed is determined primarily by:",
      "Medium stiffness (elasticity) and density",
      ["Only the ultrasound machine brand", "Operator shoe size", "Display brightness alone"],
      "Soft tissue average ~1540 m/s; stiffer media generally faster sound.",
      [
        "Machine assumes speeds.",
        "Operator irrelevant.",
        "Brightness is display.",
      ],
      "medium",
    ],
    [
      "Acoustic impedance (Z) equals:",
      "Density × propagation speed",
      ["Frequency × wavelength", "Power × time only", "Amplitude / 2 always"],
      "Reflection depends on impedance mismatch at boundaries.",
      [
        "fλ = c.",
        "Power×time = energy.",
        "Not amplitude/2 definition.",
      ],
      "medium",
    ],
    [
      "Period and frequency are:",
      "Reciprocals (T = 1/f)",
      ["Unrelated", "Always equal numerically in MHz", "Determined only by the medium, not the source"],
      "Source (transducer) determines frequency/period; medium determines speed.",
      [
        "They are related.",
        "Not numerically equal generally.",
        "Frequency set by source.",
      ],
      "easy",
    ],
    [
      "Power is proportional to amplitude:",
      "Squared (≈ A^2)",
      ["Cubed always only", "To the zeroth power only", "Inversely only always"],
      "Intensity also ∝ A^2; important for bioeffects/output discussions.",
      [
        "Squared is standard relation.",
        "Not zero.",
        "Not purely inverse.",
      ],
      "medium",
    ],
    [
      "Attenuation in soft tissue increases when:",
      "Path length or frequency increases",
      ["Frequency decreases with path fixed always reducing attenuation", "You freeze the image", "Gain is increased (true attenuation change)"],
      "Attenuation coefficient rises with frequency; more depth → more loss.",
      [
        "Lower f penetrates better.",
        "Freeze doesn't change physics.",
        "Gain amplifies display, not true attenuation.",
      ],
      "easy",
    ],
    [
      "The decibel (dB) scale for intensity ratios is:",
      "Logarithmic: 3 dB ≈ factor of 2; 10 dB ≈ factor of 10",
      ["Linear always with 1 dB = 1 Pascal exactly", "Unrelated to ratios", "Only used for ECG"],
      "Know common dB doublings for intensity/amplitude conventions taught in SPI.",
      [
        "dB is log ratio.",
        "It compares ratios.",
        "Used widely in ultrasound.",
      ],
      "hard",
    ],
    [
      "Specular reflection occurs when:",
      "The interface is large and smooth relative to wavelength",
      ["Scatterers are much smaller than wavelength only (Rayleigh)", "There is no impedance mismatch", "Sound stops existing"],
      "Specular reflections are angle-dependent; diffuse scattering from rough surfaces.",
      [
        "Rayleigh is small scatterers.",
        "Mismatch needed for reflection.",
        "Sound continues.",
      ],
      "medium",
    ],
    [
      "Snell's law relates to:",
      "Refraction—bending of the beam when speed changes across an oblique interface",
      ["Only absorption in bone", "Electrical safety grounding", "Doppler packet size exclusively"],
      "Refraction can laterally displace structures (e.g., edge artifacts/duodenum-type teaching cases).",
      [
        "Absorption is different.",
        "Grounding electrical.",
        "Packet size Doppler.",
      ],
      "medium",
    ]
  ],
  "transducers-beam": [
    [
      "Piezoelectric effect means:",
      "Certain materials convert pressure to electricity and vice versa",
      ["Sound creates light only", "Magnets create ultrasound exclusively", "Gel generates frequency"],
      "PZT elements transmit and receive; Curie temperature destroys piezoelectricity if overheated.",
      [
        "Not primarily photoelastic definition here.",
        "Not magnetism definition.",
        "Gel couples sound.",
      ],
      "easy",
    ],
    [
      "Matching layer function is to:",
      "Improve transmission between PZT and tissue by intermediate impedance",
      ["Increase electrical noise intentionally", "Cool the computer CPU", "Eliminate the need for gel always"],
      "Matching layer thickness ~1/4 wavelength design concept.",
      [
        "Noise unwanted.",
        "CPU unrelated.",
        "Gel still used.",
      ],
      "medium",
    ],
    [
      "Backing/damping material mainly:",
      "Shortens spatial pulse length improving axial resolution (at cost of sensitivity)",
      ["Increases ringing forever for better Q", "Sets the imaging depth alone", "Determines blood viscosity"],
      "Low-Q damped transducers for imaging; continuous wave Doppler lightly damped.",
      [
        "Damping reduces ringing.",
        "Depth is timing/PRP related.",
        "Viscosity physiologic.",
      ],
      "medium",
    ],
    [
      "Axial resolution improves with:",
      "Shorter spatial pulse length (higher frequency / more damping)",
      ["Wider beams only", "Lower frequency always", "More cycles in the pulse always"],
      "AR ≈ SPL/2; fewer cycles and shorter λ help.",
      [
        "Lateral related to beam width.",
        "Lower f worsens AR generally.",
        "More cycles lengthen SPL.",
      ],
      "easy",
    ],
    [
      "Lateral resolution is best at the:",
      "Focus (narrowest beam width)",
      ["Fraunhofer far zone always widest", "Extreme sides of a sector far from center always", "Cable connector"],
      "Focusing improves lateral resolution at the focal zone; multiple foci reduce frame rate.",
      [
        "Far zone diverges.",
        "Sector edges may worsen.",
        "Connector unrelated.",
      ],
      "easy",
    ],
    [
      "Linear sequenced arrays create rectangular images by:",
      "Firing groups of elements in sequence across the face",
      ["Mechanical single element rotation only", "Only phased steering without sequencing", "Random element firing without pattern"],
      "Linear = rectangle; convex = blunted sector; phased = sector from small footprint.",
      [
        "Mechanical old sector probes differ.",
        "Phased uses timing delays primarily.",
        "Patterned firing needed.",
      ],
      "medium",
    ],
    [
      "Phased array steering uses:",
      "Minute time delays (phasing) across elements to steer/focus the beam",
      ["Only mechanical motors always", "Changing gel brands", "Adjusting hospital Wi-Fi"],
      "Electronic beam forming enables sector imaging from small probes (cardiac).",
      [
        "Motors in some mechanical transducers historically.",
        "Gel coupling.",
        "Wi-Fi unrelated.",
      ],
      "medium",
    ],
    [
      "Grating lobes are reduced by:",
      "Apodization, subdicing, and tight element spacing concepts",
      ["Increasing output power only as the lobe fix", "Removing the matching layer", "Using no damping"],
      "Grating/side lobes create artifacts and degrade lateral resolution.",
      [
        "Power doesn't remove lobes.",
        "Matching layer needed.",
        "Damping for pulse length.",
      ],
      "hard",
    ],
    [
      "Duty factor is:",
      "Pulse duration divided by pulse repetition period (fraction of time transmitting)",
      ["Always 100% for pulsed imaging", "PRP times PD", "Frame rate times lines"],
      "DF is unitless; CW Doppler DF = 1; imaging DF very small.",
      [
        "Imaging DF << 1.",
        "That's not the definition product for DF.",
        "Frame rate related but not DF definition.",
      ],
      "hard",
    ],
    [
      "Spatial pulse length equals:",
      "Number of cycles × wavelength",
      ["Frequency / period", "PRP × DF only as SPL", "Depth × 13 μs only"],
      "SPL determines axial resolution; PD = n × T.",
      [
        "f = 1/T.",
        "PRP×DF = PD, not SPL.",
        "13 μs/cm-rule is range equation timing.",
      ],
      "easy",
    ]
  ],
  "doppler-hemodynamics": [
    [
      "The Doppler shift is proportional to:",
      "Reflector speed and the cosine of the Doppler angle, and operating frequency",
      ["Only the brightness gain", "Only patient age", "PRF exclusively without velocity"],
      "fd = 2v f0 cosθ / c; angle critical for velocity estimates.",
      [
        "Gain is display.",
        "Age unrelated.",
        "PRF sets aliasing limits.",
      ],
      "easy",
    ],
    [
      "At a Doppler angle of 90°:",
      "Cosine is 0 so no Doppler shift is detected",
      ["Shift is maximum", "Velocity is automatically doubled", "Aliasing disappears magically always"],
      "Avoid 90°; aim for ≤60° for quantitative vascular Doppler when possible.",
      [
        "Max at 0°.",
        "Not auto double.",
        "Aliasing separate issue.",
      ],
      "easy",
    ],
    [
      "Aliasing in pulsed Doppler occurs when:",
      "Nyquist limit is exceeded (shift > PRF/2)",
      ["Wall filter is appropriately set always as definition of aliasing", "CW Doppler is used (CW aliases the same way)", "Gain is too low only"],
      "Fix aliasing by increasing PRF/scale, adjusting baseline, lower f0, shallower sample, or switch to CW.",
      [
        "Wall filter ≠ aliasing definition.",
        "CW does not alias the same (no PRF sampling limit).",
        "Low gain isn't aliasing.",
      ],
      "medium",
    ],
    [
      "Continuous-wave Doppler advantage is:",
      "Ability to measure high velocities without aliasing",
      ["Precise depth range resolution of the source of shift", "No need for two crystals/elements concepts", "Immunity to any angle effects"],
      "CW lacks range resolution; PW has sample volume depth selectivity.",
      [
        "CW lacks range resolution.",
        "CW typically uses two elements.",
        "Angle still matters.",
      ],
      "medium",
    ],
    [
      "Bernoulli equation simplified in echo estimates pressure gradients from:",
      "4v^2 (modified Bernoulli)",
      ["v/4 only", "2v", "PRF × depth"],
      "ΔP ≈ 4v² relates peak velocity to pressure drop across stenoses/valves.",
      [
        "Not v/4.",
        "Not 2v.",
        "PRF/depth Doppler setup.",
      ],
      "hard",
    ],
    [
      "Reynolds number predicts:",
      "Tendency for laminar vs turbulent flow",
      ["Only optical refraction", "Ultrasound frequency", "Frame rate"],
      "High Reynolds (high velocity, large diameter, low viscosity) → turbulence; spectral window fill-in.",
      [
        "Optics separate.",
        "Frequency transducer.",
        "Frame rate imaging.",
      ],
      "medium",
    ],
    [
      "Color Doppler packet size (ensemble length) tradeoff:",
      "Larger packets improve velocity estimates but reduce frame rate",
      ["Larger packets always increase frame rate", "Packet size does not affect color quality", "Packets replace ECG gating needs always"],
      "Color is multi-pulse; compromises among area, depth, packets, and PRF.",
      [
        "Larger packets slow frame rate.",
        "Quality affected.",
        "ECG separate.",
      ],
      "hard",
    ],
    [
      "Wall filters (high-pass) remove:",
      "Low-frequency Doppler shifts from vessel wall/clutter motion",
      ["Only the highest arterial velocities always as their purpose", "ECG signals in the ultrasound machine power cord", "All useful diastolic venous flow by design goal when set optimally always"],
      "Excessive wall filter can wipe out slow flow (e.g., venous/diastolic).",
      [
        "Not for removing peak arterial.",
        "Not electrical ECG filtering definition.",
        "Overfiltering harms slow flow.",
      ],
      "medium",
    ],
    [
      "Power Doppler displays:",
      "Strength/amplitude of Doppler shifts rather than mean velocity/direction primarily",
      ["Exact velocity and direction like spectral with numbers always", "Only CT Hounsfield units", "Aliasing as its main numeric output"],
      "Power Doppler more sensitive to flow presence, less angle dependent, no direction/velocity values like color.",
      [
        "Not quantitative velocity like PW.",
        "Not CT.",
        "Doesn't display aliasing velocities the same.",
      ],
      "easy",
    ],
    [
      "Spectral broadening may indicate:",
      "Turbulent flow or large sample volume encompassing varied velocities",
      ["Perfectly laminar flow with tiny sample always", "Frozen image only", "Absent Doppler shift at 0°"],
      "Fill-in of spectral window suggests turbulence or technical factors.",
      [
        "Laminar has clear window typically.",
        "Freeze unrelated.",
        "0° maximizes shift.",
      ],
      "medium",
    ]
  ],
  "artifacts-safety": [
    [
      "Shadowing artifact occurs distal to:",
      "Highly attenuating/reflecting structures (e.g., calcification, stone, bone)",
      ["Fluid-filled simple cysts primarily as enhancement opposite", "Only gain being too high as true shadow physics", "Doppler angle of 0°"],
      "Useful diagnostically for stones; distinguish from improper TGC.",
      [
        "Cysts cause enhancement.",
        "Gain is technical display.",
        "Angle Doppler.",
      ],
      "easy",
    ],
    [
      "Acoustic enhancement is seen distal to:",
      "Low-attenuating fluid (cysts, bladder)",
      ["Gallstones typically as enhancement", "Bone", "Air/bowel gas typically"],
      "Through-transmission helps confirm cystic nature.",
      [
        "Stones shadow.",
        "Bone shadows.",
        "Gas shadows/scatters.",
      ],
      "easy",
    ],
    [
      "Reverberation artifact appears as:",
      "Multiple equally spaced echoes at increasing depths from strong parallel reflectors",
      ["A mirror image only below the diaphragm always as the only form", "Color aliasing exclusively", "Electrical interference spikes only"],
      "Comet-tail/ring-down are related variants taught in SPI.",
      [
        "Mirror is different artifact.",
        "Aliasing Doppler.",
        "Electrical different.",
      ],
      "medium",
    ],
    [
      "Mirror image artifact commonly occurs around:",
      "Strong reflectors like diaphragm/pleura creating a duplicated structure",
      ["Only inside the transducer cable", "Never in abdominal imaging", "When PRF is zero"],
      "Liver lesions can appear mirrored into lung/base regions.",
      [
        "Cable unrelated.",
        "Common abdominally.",
        "PRF zero not imaging.",
      ],
      "medium",
    ],
    [
      "Side lobe/grating lobe artifacts can create:",
      "False echoes that appear to originate from the main beam path",
      ["Perfectly accurate anatomy always", "Only Doppler shifts without B-mode impact", "Sterility of probes"],
      "Reduce with apodization; recognize as artifact vs real masses.",
      [
        "They reduce accuracy.",
        "Also affect B-mode.",
        "Not about sterility.",
      ],
      "hard",
    ],
    [
      "The ALARA principle means:",
      "Use output exposures As Low As Reasonably Achievable for diagnostic quality",
      ["Always max MI/TI for prettier images", "Ignore thermal indices", "Ultrasound is ionizing so dose like CT"],
      "Monitor MI/TI; reduce power, dwell time, and use appropriate modes.",
      [
        "Max output not ALARA.",
        "TI/MI guide risk.",
        "US non-ionizing.",
      ],
      "easy",
    ],
    [
      "Mechanical index (MI) relates most to risk of:",
      "Cavitation bioeffects",
      ["Only heating in bone exclusively as MI meaning", "Electrical shock", "Laser burns"],
      "TI relates to heating; MI to mechanical/cavitation; contrast agents raise cavitation concern.",
      [
        "TI ~ thermal.",
        "Electrical safety separate.",
        "Laser unrelated.",
      ],
      "medium",
    ],
    [
      "Thermal index (TI) estimates:",
      "Potential tissue heating from ultrasound absorption",
      ["Only the Nyquist limit", "Exact temperature in every voxel always perfectly", "Film badge radiation dose"],
      "TIS/TIB/TIC variants depend on assumptions; minimize dwell especially with bone/fetal concerns.",
      [
        "Nyquist Doppler.",
        "Estimate not perfect map.",
        "Not ionizing film badges.",
      ],
      "medium",
    ],
    [
      "Range ambiguity artifact occurs when:",
      "Echoes from deep structures return after the next pulse is sent (PRP too short)",
      ["Frequency is zero", "Gel is correctly applied", "CW Doppler is range gated precisely"],
      "Reduce by lowering PRF/scale or adjusting depth/timing expectations.",
      [
        "f=0 not imaging.",
        "Gel good practice.",
        "CW lacks PW ranging.",
      ],
      "hard",
    ],
    [
      "Slice thickness artifact can fill in:",
      "Anechoic structures with false echoes from beam elevation thickness",
      ["Only spectral windows in a beneficial way always", "TI displays", "Patient ID fields"],
      "Elevational focusing/1.5D arrays reduce slice thickness artifacts.",
      [
        "Not beneficial fill-in.",
        "TI separate.",
        "ID unrelated.",
      ],
      "medium",
    ]
  ],
};
