/** CRCST — 40 curated MCQs */
export const topics = {
  "decontamination": [
    [
      "The first and most important step in decontamination is:",
      "Cleaning to remove soil/bioburden before disinfection or sterilization",
      ["Sterilizing heavily soiled instruments without cleaning", "Skipping enzymatic detergents always when soil is present", "Using sterile storage wraps as cleaning cloths"],
      "Soil shields microbes from sterilants; cleaning is prerequisite to sterilization.",
      [
        "Sterilization fails on dirty devices.",
        "Enzymatics often help protein soil.",
        "Wraps aren't cleaning tools.",
      ],
      "easy",
    ],
    [
      "PPE in decontamination typically includes:",
      "Fluid-resistant gown, gloves, mask/eye protection, and appropriate footwear controls",
      ["Street clothes only", "Sterile surgical gloves as the only PPE with bare arms", "No eye protection when splashing"],
      "Decontam is the dirtiest area—dress for splash/sharps hazards.",
      [
        "Street clothes contaminate.",
        "Arms need coverage.",
        "Eyes need protection.",
      ],
      "easy",
    ],
    [
      "Manual cleaning scrubbing should be done:",
      "Below the water line to reduce aerosols, using appropriate brushes",
      ["With vigorous spraying upward toward the face", "Using abrasive pads that scratch all surfaces indiscriminately against IFU", "Without following device IFU"],
      "Minimize aerosols; select brushes that contact lumens/crevices without damaging devices.",
      [
        "Upward spray aerosols pathogens.",
        "Scratches create infection niches.",
        "IFU governs cleaning.",
      ],
      "medium",
    ],
    [
      "Lumened devices require:",
      "Brushing and flushing according to IFU, including correct brush diameter",
      ["Only wiping the outside", "No attention to inner channels", "Sterilization without cleaning if lumen is short"],
      "Biofilm in lumens is a major failure point (e.g., endoscopes/complex instruments).",
      [
        "Exterior wipe insufficient.",
        "Channels are critical.",
        "Length doesn't remove cleaning need.",
      ],
      "medium",
    ],
    [
      "Enzymatic detergents are useful because they:",
      "Break down organic soils (protein, fat, carbs) when used at correct temperature/contact time",
      ["Sterilize instruments alone", "Replace rinsing", "Work better if mixed to random strengths"],
      "Follow concentration, temp, and time; rinse thoroughly to remove residues.",
      [
        "Not sterilants alone.",
        "Rinsing required.",
        "Dosing matters.",
      ],
      "easy",
    ],
    [
      "Gross soil should be removed:",
      "As soon as possible at point of use, keeping instruments moist per protocol",
      ["Allowed to dry for days to 'set' soil", "By tossing instruments into sharps containers", "Using sterile saline bags as hammers"],
      "Point-of-use pretreatment prevents hardened soil and corrosion.",
      [
        "Drying hardens soil.",
        "Instruments ≠ sharps disposal route for reusable sets.",
        "Don't damage devices.",
      ],
      "easy",
    ],
    [
      "A negative air pressure relationship is typically maintained in:",
      "The decontamination area relative to clean areas",
      ["The sterile storage as more negative than decontam", "Office break rooms vs OR always as the SPD rule", "The parking lot"],
      "Air flows into decontam so contaminants don't blow into clean prep/sterile areas.",
      [
        "Sterile storage should be positive/clean.",
        "Break rooms not the SPD air design focus.",
        "Parking irrelevant.",
      ],
      "hard",
    ],
    [
      "When receiving loaner instruments, SPD should:",
      "Inspect, clean, and sterilize according to IFU before use—never assume they are ready",
      ["Send straight to OR without processing because they look shiny", "Skip BI monitoring forever for loaners", "Store in decontam uncovered indefinitely"],
      "Loaners are high risk for inadequate processing history.",
      [
        "Shiny ≠ sterile.",
        "Monitoring still applies.",
        "Process promptly.",
      ],
      "medium",
    ],
    [
      "Ultrasonic cavitation cleaning requires:",
      "Degassing, proper dilution, basket loading without overstacking, and rinsing after",
      ["Overloading trays tightly with no solution contact", "Mixing dissimilar metals carelessly causing damage always as best practice", "No manufacturer instructions"],
      "Follow ultrasonic IFU; some devices cannot be ultrasonicated.",
      [
        "Overloading reduces energy delivery.",
        "Galvanic issues possible—follow IFU.",
        "IFU mandatory.",
      ],
      "medium",
    ],
    [
      "Chemical disinfection high-level (HLD) is used for:",
      "Semicritical items that contact mucous membranes when sterilization isn't feasible per Spaulding/IFU",
      ["Critical implants as the preferred permanent substitute for sterilization always", "Environmental floors as sterilant", "Skin antisepsis as surgical sterilant"],
      "Critical items require sterilization; HLD is not a sterilant unless a sterilant cycle/claim applies.",
      [
        "Implants need sterilization.",
        "Floors aren't HLD targets typically.",
        "Skin antisepsis differs.",
      ],
      "hard",
    ]
  ],
  "assembly-packaging": [
    [
      "Instruments should be inspected for:",
      "Cleanliness, function, alignment, corrosion, and completeness before packaging",
      ["Only the count sheet color", "Nothing if they came from washers", "Rust as acceptable for sterile use"],
      "Assembly is a quality checkpoint; repair/replace defective instruments.",
      [
        "Count sheets help but inspection needed.",
        "Washers can fail.",
        "Rusty instruments rejected.",
      ],
      "easy",
    ],
    [
      "Rigid container systems require:",
      "Intact filters/valves/gaskets and correct locking per IFU, with internal CI as required",
      ["Cracked lids accepted if taped heavily", "No filter checks", "Overfilling above rated weight always"],
      "Containers fail if seals/filters compromised; follow load weight limits.",
      [
        "Cracks invalidate.",
        "Filters critical.",
        "Overfilling risks wet packs/failures.",
      ],
      "medium",
    ],
    [
      "Woven/nonwoven wraps should be:",
      "Sized appropriately using sequential wrapping techniques without tenting/strangulation of pack",
      ["Used when soaking wet", "Closed with safety pins through the wrap freely always", "Reusable forever without inspection"],
      "Wrap integrity and technique maintain sterility barrier.",
      [
        "Wet wraps fail.",
        "Pins create holes—use appropriate indicators/tape.",
        "Inspect reusable textiles.",
      ],
      "medium",
    ],
    [
      "Chemical indicators are placed:",
      "In areas of each pack/tray challenging to sterilant penetration per policy/IFU",
      ["Only on the sterilizer wall outside", "Never inside sets", "In the OR after opening only as the sole placement"],
      "Internal CI helps detect sterilant penetration problems inside packs.",
      [
        "External indicators alone insufficient.",
        "Internal placement required typically.",
        "OR check is additional.",
      ],
      "easy",
    ],
    [
      "Count sheets in trays help:",
      "Ensure complete sets and document contents for OR accountability",
      ["Replace cleaning", "Sterilize devices", "Serve as biological indicators"],
      "Incomplete trays delay surgery and risk counts.",
      [
        "Cleaning still needed.",
        "Not sterilants.",
        "BI are spore tests.",
      ],
      "easy",
    ],
    [
      "Instruments with lumens may need:",
      "Moisture/residual water controls and lumen accessories per sterilizer IFU (e.g., wetness management)",
      ["Grease packing inside lumens before sterilizing", "Tape sealing lumen ends closed always", "No special attention"],
      "Steam must contact surfaces; excess water can cause wet packs; some systems use lumen devices.",
      [
        "Grease impedes sterilization.",
        "Sealed ends block steam.",
        "Lumens need attention.",
      ],
      "hard",
    ],
    [
      "Tip protectors are used to:",
      "Protect sharp/delicate tips and may aid sterilant contact if designed permeable",
      ["Block steam intentionally as their purpose", "Replace wrap", "Indicate BI results"],
      "Use protectors validated for sterilization compatibility.",
      [
        "Must not block sterilant improperly.",
        "Wrap still needed.",
        "Not BIs.",
      ],
      "easy",
    ],
    [
      "Tray weight limits exist because overweight trays can cause:",
      "Wet packs, poor drying, and sterilization failures",
      ["Faster cycles always with better kill", "Automatic BI passes", "Sharper scissors"],
      "Follow sterilizer and container IFU for maximum weights.",
      [
        "Overweight harms cycles.",
        "BI unrelated directly.",
        "Function unrelated.",
      ],
      "medium",
    ],
    [
      "Assembly area air quality should be:",
      "Cleaner/positive relative to decontamination, controlled for lint/dust",
      ["More contaminated than decontam", "Open to outside dust winds ideally", "Identical to soiled utility without controls"],
      "Protect clean instruments during assembly/packaging.",
      [
        "Clean > decontam contamination.",
        "Dust harms.",
        "Controls required.",
      ],
      "medium",
    ],
    [
      "Missing instruments identified at assembly should be:",
      "Documented and resolved before sterilization/OR delivery per policy",
      ["Ignored if only one scissor missing in a major set", "Replaced with random unprocessed instruments from decontam floor", "Hidden from OR"],
      "Incomplete sets are patient safety issues.",
      [
        "Major sets need completeness.",
        "Unprocessed replacements unsafe.",
        "Transparency required.",
      ],
      "easy",
    ]
  ],
  "sterilization": [
    [
      "Steam sterilization kills microorganisms primarily by:",
      "Coagulation/denaturation of proteins via moist heat under pressure",
      ["Freezing cells", "Only UV light inside every autoclave load", "Desiccation alone at room temp"],
      "Saturated steam transfers heat efficiently; air removal critical in prevac systems.",
      [
        "Not freezing.",
        "UV not the autoclave mechanism.",
        "Dry room temp not sterilization.",
      ],
      "easy",
    ],
    [
      "Prevacuum sterilizers use a Bowie-Dick type test to detect:",
      "Air removal effectiveness / air leaks in dynamic-air-removal systems",
      ["Exact BI spore species only", "Detergent concentration", "Package aesthetics"],
      "Bowie-Dick is a daily diagnostic for prevac air removal—not a BI.",
      [
        "BI is separate.",
        "Detergent is washers.",
        "Aesthetics irrelevant.",
      ],
      "medium",
    ],
    [
      "Geobacillus stearothermophilus spores are used to monitor:",
      "Steam sterilization biological indicators",
      ["Ethylene oxide exclusively always", "Dry heat only always", "Radiation only"],
      "Match BI organism to sterilant: stearothermophilus for steam; subtilis/niger historically for EO/dry heat variants—know current IFU.",
      [
        "EO uses different spore historically/currently per product.",
        "Dry heat different.",
        "Radiation industrial.",
      ],
      "medium",
    ],
    [
      "A wet pack after steam sterilization should be considered:",
      "Contaminated / not sterile for use; reprocess after investigating cause",
      ["Sterile if cool to touch", "OK if used within 5 minutes always", "Fixed by wiping with a towel and issuing"],
      "Moisture wicks microbes through wraps; find loading/drying/weight causes.",
      [
        "Cool ≠ dry/sterile barrier intact.",
        "Time doesn't fix wicking risk.",
        "Wiping insufficient.",
      ],
      "hard",
    ],
    [
      "Ethylene oxide (EO) sterilization is chosen when:",
      "Devices are heat/moisture sensitive and IFU specifies EO, with aeration afterward",
      ["Immediate use without aeration is always safe", "It is faster than steam for all stainless sets routinely", "No monitoring is needed"],
      "EO is toxic/flammable concerns historically; aeration removes residuals; BI monitoring required.",
      [
        "Aeration mandatory.",
        "Steam preferred for heat-stable.",
        "Monitoring required.",
      ],
      "hard",
    ],
    [
      "Hydrogen peroxide vapor/plasma systems are often used for:",
      "Heat-sensitive devices compatible with the sterilizer IFU",
      ["Linen packs soaked with liquids always", "Powders and oils as ideal loads", "Any device with long dead-end lumens against IFU"],
      "Compatibility lists matter; cellulose/liquids often contraindicated in some systems.",
      [
        "Liquids/cellulose issues common.",
        "Oils/powders incompatible often.",
        "Lumen limits per IFU.",
      ],
      "medium",
    ],
    [
      "Load control/sterility assurance documentation should include:",
      "Cycle parameters, CI/BI results, load contents, and operator identification per policy",
      ["Only the operator's favorite music", "No records to save paper always", "Patient SSN on every sterilizer strip publicly"],
      "Traceability supports recalls and accreditation.",
      [
        "Music irrelevant.",
        "Records required.",
        "Protect privacy—use lot/load IDs appropriately.",
      ],
      "easy",
    ],
    [
      "Implant loads should be:",
      "Quarantined until BI results are known (CDC recommendation concept), when possible",
      ["Released early without BI always as best practice", "Never monitored", "Washed only"],
      "Implants are high risk—await BI before release when feasible.",
      [
        "Early release discouraged for implants.",
        "Monitoring essential.",
        "Cleaning alone insufficient.",
      ],
      "medium",
    ],
    [
      "Superheating in steam sterilization can occur when:",
      "Steam is too dry / dehydrated, reducing sterilizing efficiency",
      ["Packages are correctly moist with saturated steam conditions", "BI passes prove superheating always desirable", "Air is perfectly removed and steam saturated ideally as the definition of superheat"],
      "Saturated steam is required; superheated steam behaves more like dry heat at that temperature.",
      [
        "Saturated steam is desired.",
        "BI pass doesn't define superheat as good.",
        "Proper saturated conditions aren't superheat.",
      ],
      "hard",
    ],
    [
      "Gravity displacement sterilizers remove air by:",
      "Steam entering and forcing cooler air out through a drain passively",
      ["High-speed vacuum pulses always like prevac", "Ultrasonic cavitation", "EO gas"],
      "Gravity cycles need proper loading to avoid air trapping; longer times often than prevac.",
      [
        "Prevac uses vacuum pulses.",
        "Ultrasonic is cleaning.",
        "EO separate modality.",
      ],
      "easy",
    ]
  ],
  "storage-distribution": [
    [
      "Sterile storage should be:",
      "Clean, dry, well-ventilated, above the floor, away from sinks/windows moisture",
      ["Under a leaking sink", "On the floor against traffic dirt", "In decontam next to soak sinks"],
      "Maintain package integrity; positive pressure clean areas preferred.",
      [
        "Moisture contaminates.",
        "Floor storage forbidden typically.",
        "Decontam is dirty.",
      ],
      "easy",
    ],
    [
      "Stock rotation uses:",
      "FIFO (first in, first out) so older sterile packs are used first",
      ["LIFO always as the only sterile storage rule", "Random grab without dates/lot awareness", "Keeping expired event-compromised packs 'just in case'"],
      "FIFO reduces outdates and aging damage.",
      [
        "LIFO risks outdates.",
        "Random risks expired use.",
        "Compromised packs reprocessed/discarded.",
      ],
      "easy",
    ],
    [
      "Before issuing a sterile pack to OR, SPD/user should check:",
      "Integrity of packaging, dryness, indicator response, and expiration/event status",
      ["Only whether the tape is pretty", "Nothing if the cart arrived", "Whether the surgeon likes the color"],
      "At-point inspection is the last safety net.",
      [
        "Aesthetics insufficient.",
        "Arrival ≠ inspection.",
        "Color irrelevant.",
      ],
      "easy",
    ],
    [
      "Transportation of sterile items requires:",
      "Covered/closed carts and clean handling to protect packages",
      ["Open arms stacking packs against scrub tops casually through rain", "Placing packs on the floor of the elevator", "Using decontam case carts without cleaning between soiled/clean roles"],
      "Separate clean/soiled logistics; clean carts between uses.",
      [
        "Exposure contaminates.",
        "Floor is dirty.",
        "Case cart roles must not cross-contaminate.",
      ],
      "medium",
    ],
    [
      "IUSS items transported to OR must be:",
      "Aseptically transferred and used immediately—not stored",
      ["Put on shelves for later cases that week", "Cooled uncovered in a hallway traffic stream", "Placed under sinks"],
      "Immediate-use items aren't inventory stock.",
      [
        "No shelf storage.",
        "Hallway contamination risk.",
        "Sinks moisture risk.",
      ],
      "medium",
    ],
    [
      "Quality assurance in distribution includes:",
      "Tracking loaners, implants, and sterilization lot information for traceability",
      ["Avoiding all documentation", "Discarding BI logs monthly without retention policy", "Handwriting patient secrets on tape publicly"],
      "Traceability enables recalls if BI failures/product issues arise.",
      [
        "Docs required.",
        "Retain per policy/regulation.",
        "Privacy matters.",
      ],
      "easy",
    ],
    [
      "Shelf-life of sterile packs depends heavily on:",
      "Storage conditions and package integrity (event-related) or facility dating policy",
      ["The color of the wrap dye alone", "How loudly the sterilizer beeped", "OR temperature preferences only"],
      "Even with dates, inspect for compromise events.",
      [
        "Dye irrelevant.",
        "Beeps irrelevant.",
        "Storage more than OR preference.",
      ],
      "easy",
    ],
    [
      "If a sterile package is dropped on the floor:",
      "Consider it contaminated and reprocess (unless a validated rigid container IFU says otherwise for specific cases)",
      ["Wipe with sleeve and use", "Use if dropped 'only once'", "Spray with room air freshener"],
      "Floor contact contaminates wraps; rigid containers have specific IFU exceptions sometimes.",
      [
        "Sleeve wipe insufficient.",
        "Once is enough to contaminate.",
        "Air freshener not sterilant.",
      ],
      "medium",
    ],
    [
      "Inventory levels should balance:",
      "Enough stock for procedures without overstocking that leads to damage/outdates",
      ["Zero extras always causing constant IUSS", "Infinite piles blocking sprinklers/air vents", "Storing sterile with soiled"],
      "PAR levels and case cart systems improve OR support.",
      [
        "Chronic IUSS from understock bad.",
        "Overstock damages/fire code issues.",
        "Separation required.",
      ],
      "easy",
    ],
    [
      "Recalls of sterilized loads are initiated when:",
      "BI failure or other sterilizer malfunction potentially affects released items",
      ["A staff member changes haircut", "The coffee pot breaks", "All packages look intact with perfect records and passing BI"],
      "Have a written recall procedure with risk assessment and OR notification.",
      [
        "Haircuts irrelevant.",
        "Coffee irrelevant.",
        "No recall if truly no failure indication.",
      ],
      "medium",
    ]
  ],
};
