/** DANB ICE — 40 curated MCQs */
export const topics = {
  "standard-precautions": [
    [
      "Standard Precautions in dentistry mean staff should:",
      "Treat all blood and body fluids as potentially infectious and use appropriate PPE/hand hygiene",
      ["Use PPE only when a patient discloses HIV", "Wash gloves between patients instead of changing them", "Skip hand hygiene if gloves were worn"],
      "Standard Precautions assume unknown infectious status; gloves do not replace hand hygiene.",
      [
        "Known-status-only PPE is outdated.",
        "Gloves are single-use between patients.",
        "Hand hygiene is required after glove removal.",
      ],
      "easy",
    ],
    [
      "When is an N95 respirator typically indicated in dental settings (concept)?",
      "For procedures/situations with airborne risk per CDC/facility policy (e.g., certain airborne diseases), after fit testing",
      ["For every brief hallway conversation with healthy staff", "Instead of eye protection during splash procedures always", "Only as a fashion accessory"],
      "Respirators are for airborne hazards; splash protection still needs eyewear; fit testing matters.",
      [
        "Routine talk does not require N95.",
        "Eye protection is separate for splashes.",
        "Respirators are PPE, not fashion.",
      ],
      "medium",
    ],
    [
      "Hand hygiene should be performed:",
      "Before donning gloves, after removing gloves, and whenever hands are contaminated",
      ["Only at the end of the workday", "Only if hands look dirty", "Never when using alcohol rubs is banned by all policies always"],
      "Moments for hand hygiene surround glove use and patient care contacts.",
      [
        "Once daily is inadequate.",
        "Invisible contamination matters.",
        "ABHR is often allowed when hands are not soiled.",
      ],
      "easy",
    ],
    [
      "Which PPE combination is most appropriate for a procedure likely to produce splash of blood/saliva?",
      "Gloves, mask, and eye protection (goggles/face shield); gown when soiling of clothing is likely",
      ["Gloves only", "Shoe covers only", "No PPE if the patient rinsed with mouthwash"],
      "Mucous membrane and clothing protection match splash risk.",
      [
        "Hands-only PPE leaves face exposed.",
        "Shoe covers do not protect face/hands.",
        "Mouthwash does not eliminate blood/saliva risk.",
      ],
      "easy",
    ],
    [
      "Utility gloves in instrument processing are worn to:",
      "Protect hands during cleaning of contaminated instruments and handling chemicals",
      ["Replace sterile surgical gloves during surgery", "Be worn home for dishwashing", "Touch charts and phones throughout the clinic day without removal"],
      "Heavy-duty utility gloves protect during decontamination; they are not sterile surgical gloves.",
      [
        "Surgery needs sterile gloves.",
        "Contaminated gloves stay at work.",
        "Cross-contamination to clean areas is improper.",
      ],
      "medium",
    ],
    [
      "Masks should be changed when:",
      "They become wet, soiled, or between patients per protocol",
      ["Once a week regardless of use", "Only if the patient requests a new color", "Never, because moisture improves filtration"],
      "Wet masks lose barrier effectiveness; change based on use/contamination.",
      [
        "Weekly change is inadequate.",
        "Color preference is not the infection-control rule.",
        "Moisture degrades filtration/barrier.",
      ],
      "easy",
    ],
    [
      "Which statement about latex allergy risk reduction is correct?",
      "Use non-latex alternatives when indicated and minimize unnecessary latex powder exposures",
      ["Force latex gloves on known latex-allergic staff", "Powdered latex is always the safest option", "Allergy history is irrelevant in dentistry"],
      "Identify allergies and choose appropriate glove materials.",
      [
        "Known allergy requires alternatives.",
        "Powdered latex increases exposure risk.",
        "Allergy history matters for safety.",
      ],
      "medium",
    ],
    [
      "After removing PPE, the next critical step is usually:",
      "Perform hand hygiene",
      ["Touch your eyes immediately to check vision", "Apply lotion containing contamination from gloves", "Shake gloves vigorously to aerosolize debris"],
      "Hand hygiene after PPE removal reduces self-contamination.",
      [
        "Face touching spreads organisms.",
        "Contaminated lotion is unsafe.",
        "Shaking creates aerosols.",
      ],
      "easy",
    ],
    [
      "Which item is considered a critical instrument (Spaulding) requiring sterilization?",
      "Instruments that penetrate soft tissue or bone (e.g., surgical instruments, scalers that enter sterile areas)",
      ["Intact blood-pressure cuff used on unbroken skin only", "Waiting-room magazines", "Computer keyboards that never contact mucosa"],
      "Critical items contact sterile tissue/vasculature and require sterilization.",
      [
        "BP cuffs are typically noncritical.",
        "Magazines are not patient-care instruments.",
        "Keyboards are environmental surfaces.",
      ],
      "medium",
    ],
    [
      "Semicritical instruments (contact mucous membranes) should be:",
      "Heat-sterilized when heat-tolerant; if heat-sensitive, use high-level disinfection per IFU",
      ["Only wiped with a dry cloth", "Rinsed with water only", "Stored visibly soiled for the next patient"],
      "Semicritical items need sterilization or HLD depending on material tolerance.",
      [
        "Dry wiping is insufficient.",
        "Water rinse is not disinfection/sterilization.",
        "Soiled storage is unacceptable.",
      ],
      "hard",
    ]
  ],
  "instrument-processing": [
    [
      "The correct general sequence for reusable instruments is:",
      "Transport, clean, package, sterilize, store",
      ["Sterilize first, then clean heavily soiled instruments", "Store dirty, then sterilize without cleaning", "Package before removing bioburden"],
      "Cleaning must precede sterilization; soil interferes with sterilization.",
      [
        "Sterilizing dirty instruments fails.",
        "Dirty storage then sterilize skips cleaning.",
        "Packaging dirty items is wrong order.",
      ],
      "easy",
    ],
    [
      "Ultrasonic cleaners are used to:",
      "Remove debris via cavitation before sterilization",
      ["Sterilize instruments to SAL 10^-6 alone", "Disinfect operatory counters as the primary method", "Sharpen burs automatically"],
      "Ultrasonics clean; they do not replace sterilization for critical instruments.",
      [
        "Not a sterilizer by itself.",
        "Counters need surface disinfectants.",
        "Not a sharpener.",
      ],
      "easy",
    ],
    [
      "Instrument cassettes help primarily by:",
      "Keeping sets together and reducing sharps handling injuries during processing",
      ["Eliminating the need for cleaning", "Replacing sterilization indicators", "Allowing mixed clean/dirty storage"],
      "Cassettes improve safety/organization but cleaning/sterilization still required.",
      [
        "Cleaning still required.",
        "Indicators still needed.",
        "Clean/dirty separation remains.",
      ],
      "medium",
    ],
    [
      "Chemical indicators on packages show:",
      "That sterilizing conditions (e.g., temperature/steam exposure parameters the indicator is designed for) were present—not necessarily that every item is sterile alone",
      ["That bioburden is zero with certainty from color change alone", "That the autoclave never needs biologic testing", "Patient blood type"],
      "External/internal chemical indicators are process monitors; biologic indicators verify sterilizer kill.",
      [
        "Color change ≠ absolute sterility proof alone.",
        "BI testing remains required.",
        "Unrelated to blood type.",
      ],
      "medium",
    ],
    [
      "Biological indicators (spore tests) should be used:",
      "At least weekly (and with implantable device loads per CDC) to verify sterilizer lethality",
      ["Never, if chemical indicators are used", "Only once when the sterilizer is purchased", "Instead of cleaning instruments"],
      "CDC recommends routine BI monitoring; implant loads need BI results before use when required.",
      [
        "Chemical indicators do not replace BI.",
        "Ongoing monitoring is required.",
        "Cleaning is separate.",
      ],
      "easy",
    ],
    [
      "A positive spore test (failed BI) should lead to:",
      "Take the sterilizer out of service, recall/reprocess per policy, and do not use loads until failures are resolved",
      ["Ignore it if packages look dry", "Continue using the sterilizer for surgical instruments only", "Switch to cold sterile soak for all critical items indefinitely without investigation"],
      "Failed BI indicates possible sterilization failure—quarantine and investigate.",
      [
        "Appearance is insufficient.",
        "Surgical instruments are highest risk—do not continue.",
        "Investigate root cause; follow IFUs.",
      ],
      "hard",
    ],
    [
      "Flash/immediate-use steam sterilization should be:",
      "Used only for emergencies when no sterile replacement exists—not as a routine convenience",
      ["Used for every instrument to save inventory", "Used for packaged implant trays stored for weeks", "Preferred over cleaning"],
      "IUSS is for urgent situations with strict controls—not routine processing.",
      [
        "Inventory planning should avoid routine IUSS.",
        "IUSS items are for immediate use.",
        "Cleaning still required first.",
      ],
      "hard",
    ],
    [
      "When loading a sterilizer, packages should be:",
      "Arranged to allow steam/air circulation per IFU—not overloaded or stacked to block penetration",
      ["Packed as tightly as possible to maximize count", "Wrapped in aluminum foil as the primary wrap always", "Placed wet into sterile storage immediately without drying when IFU requires dry packages"],
      "Steam must contact all surfaces; follow manufacturer loading instructions.",
      [
        "Overloading causes failures.",
        "Foil is not a standard sterilization wrap system.",
        "Wet packs can wick contamination.",
      ],
      "medium",
    ],
    [
      "Hinged instruments should be processed:",
      "Open/unlocked so sterilant contacts joint surfaces",
      ["Fully closed and clamped tightly always", "Filled with cement before sterilization", "Wrapped while visibly caked with debris"],
      "Open hinges allow steam/chemical contact at joints.",
      [
        "Closed hinges impede sterilant.",
        "Cement blocks cleaning.",
        "Debris prevents sterilization.",
      ],
      "easy",
    ],
    [
      "Which statement about event-related shelf life is correct?",
      "Sterile packages remain usable until an event compromises integrity (tear, moisture, expiration if dated), if storage is proper",
      ["Sterility lasts exactly 24 hours regardless of packaging", "Packages may be stored under sinks in puddles", "Open packages can be resealed with tape for sterile use"],
      "Event-related sterility depends on package integrity and storage conditions.",
      [
        "Time-related policies vary; not universally 24h.",
        "Wet storage contaminates.",
        "Opened packages are not sterile.",
      ],
      "medium",
    ]
  ],
  "environmental": [
    [
      "Clinical contact surfaces should be:",
      "Barrier-protected and/or cleaned and disinfected between patients with an EPA-registered hospital disinfectant",
      ["Left visibly bloody for the next patient as a warning", "Wiped with dry paper only always", "Disinfected once a month if they look clean"],
      "Between-patient surface asepsis prevents cross-infection.",
      [
        "Visible blood must be cleaned.",
        "Dry wiping is insufficient.",
        "Monthly is inadequate.",
      ],
      "easy",
    ],
    [
      "Housekeeping surfaces (floors, walls) typically require:",
      "Routine cleaning; disinfection when contaminated with blood/body fluids per policy",
      ["Sterilization with an autoclave daily", "Critical-item sterile technique for mopping", "No cleaning ever in dental offices"],
      "Housekeeping surfaces are lower risk but still need cleaning and targeted disinfection when soiled.",
      [
        "Floors are not autoclaved.",
        "Mopping is not sterile surgery.",
        "Cleaning is required.",
      ],
      "easy",
    ],
    [
      "Barriers (plastic covers) on light handles should be:",
      "Changed between patients and surfaces cleaned if contamination occurred",
      ["Used for a full week without change", "Left in place when torn and wet with blood", "Considered a substitute for never cleaning under barriers"],
      "Barriers are single-patient; clean underlying surfaces on contamination/scheduled basis per protocol.",
      [
        "Weekly change is inadequate.",
        "Damaged barriers fail.",
        "Cleaning under barriers is still needed periodically/when breached.",
      ],
      "medium",
    ],
    [
      "Dental unit waterlines should deliver water that:",
      "Meets drinking-water standards for routine care (≤500 CFU/mL heterotrophic bacteria as a common benchmark) with monitoring/maintenance",
      ["May be heavily contaminated without concern because saliva is dirtier", "Must be sterile water for all rinsing always without exception in every procedure type", "Should never be flushed"],
      "DUWL maintenance and monitoring reduce biofilm risks; sterile water is required for certain surgical irrigations.",
      [
        "Contamination still matters for patients/staff.",
        "Surgical sterile water rules differ from routine rinsing.",
        "Flushing is part of control.",
      ],
      "hard",
    ],
    [
      "Flushing waterlines at the start of the day and between patients helps:",
      "Reduce planktonic bacteria in the lines",
      ["Sterilize handpieces alone", "Replace the need for sterilizer BI tests", "Eliminate the need for surface disinfection"],
      "Flushing lowers bacterial counts but is only one part of DUWL management.",
      [
        "Handpieces need sterilization.",
        "BI testing remains.",
        "Surfaces still need disinfection.",
      ],
      "medium",
    ],
    [
      "Which waste is typically regulated as medical/biohazard waste in dentistry?",
      "Sharps and items saturated with blood/saliva that drip when compressed, per local regulations",
      ["Office paper recycling mixed with needles", "Uncontaminated paper towels from hand drying always as red-bag waste in all jurisdictions", "Food wrappers from the break room"],
      "Regulated waste definitions are specific—sharps and saturated infectious items; follow local rules.",
      [
        "Needles do not go in paper recycling.",
        "Clean paper towels are usually not red-bag.",
        "Food waste is not clinical regulated waste.",
      ],
      "medium",
    ],
    [
      "Extracted teeth with amalgam should be:",
      "Handled as potential biohazard and amalgam-containing waste per EPA/state rules—not incinerated as ordinary trash in ways that vaporize mercury improperly",
      ["Flushed into the city sewer routinely", "Given to children as toys without disinfection discussion", "Autoclaved in a manner that may vaporize mercury without proper controls"],
      "Amalgam/mercury disposal has special environmental rules; treated teeth may be returned under policies.",
      [
        "Sewer disposal is improper.",
        "Unsafe for children.",
        "Heat can release mercury—follow guidance.",
      ],
      "hard",
    ],
    [
      "Spill cleanup of blood on a clinical surface should include:",
      "PPE, absorbent removal of bulk soil, then EPA-registered disinfectant with correct contact time",
      ["Dry sweeping only", "Alcohol wipe for one second always regardless of product IFU", "No cleaning if the next patient is waiting"],
      "Clean then disinfect with proper wet time.",
      [
        "Dry sweeping aerosolizes.",
        "Contact time matters.",
        "Turnover pressure does not justify skipping IPC.",
      ],
      "easy",
    ],
    [
      "Which statement about disinfection vs sterilization is correct?",
      "Disinfection reduces pathogens on surfaces/items; sterilization destroys all microbial life including spores (within process capability)",
      ["They are identical terms", "Disinfection always kills all spores on critical instruments", "Sterilization is only for floors"],
      "Spaulding and CDC distinguish disinfection levels from sterilization.",
      [
        "Not identical.",
        "Many disinfectants do not kill spores reliably.",
        "Sterilization is for instruments/devices.",
      ],
      "easy",
    ],
    [
      "Operatory cleanup between patients should prioritize:",
      "Removing barriers, cleaning/disinfecting clinical contact surfaces, and managing sharps/waste safely",
      ["Only emptying the trash once a week", "Mopping sterile fields into the autoclave", "Spraying disinfectant into the air as fog for every room without surface wipe when IFU requires wipe methods"],
      "Systematic between-patient IPC protects the next patient.",
      [
        "Weekly trash is insufficient alone.",
        "Mopping ≠ sterile processing.",
        "Follow product IFU—many need surface wet contact.",
      ],
      "medium",
    ]
  ],
  "occupational": [
    [
      "OSHA's Bloodborne Pathogens Standard requires employers to:",
      "Establish an exposure control plan, offer HBV vaccination, provide PPE, and train employees",
      ["Ban all gloves to save money", "Require employees to buy their own sharps containers from home", "Eliminate handwashing sinks"],
      "BBP Standard mandates plans, engineering/work controls, PPE, vaccine offer, and training.",
      [
        "PPE is required.",
        "Employers provide sharps disposal.",
        "Handwashing facilities are required.",
      ],
      "easy",
    ],
    [
      "After a needlestick from a used instrument, the employee should:",
      "Wash the site, report immediately, and follow post-exposure evaluation/prophylaxis protocols",
      ["Hide the injury to avoid paperwork", "Apply concentrated acid into the wound", "Finish the day of surgery first without reporting"],
      "Timely reporting enables PEP decisions and documentation.",
      [
        "Concealment delays care.",
        "Acids worsen injury.",
        "Delays risk missing PEP windows.",
      ],
      "easy",
    ],
    [
      "Hepatitis B vaccination for at-risk dental employees is:",
      "Offered by the employer at no cost under OSHA BBP rules",
      ["Optional for employers to ignore entirely without documentation pathways", "Required to be paid fully by the employee always", "Unnecessary because HBV has no occupational risk in dentistry"],
      "Employers must offer HBV vaccine; declination forms exist if refused.",
      [
        "Employers cannot simply ignore the offer requirement.",
        "Vaccine is employer-paid when offered under OSHA.",
        "HBV is a classic dental occupational risk.",
      ],
      "easy",
    ],
    [
      "Safety Data Sheets (SDS) provide:",
      "Hazard information and safe handling/PPE guidance for chemicals",
      ["Patient appointment histories", "DEA schedules for controlled drugs only", "Sterilizer BI spore counts automatically"],
      "HazCom requires accessible SDS for hazardous chemicals used in the office.",
      [
        "Not a chart.",
        "Not DEA scheduling.",
        "Not sterilizer monitoring records.",
      ],
      "easy",
    ],
    [
      "Which is a work-practice control?",
      "Recapping only with a one-handed scoop technique or safer method—not two-handed recapping",
      ["Installing a sharps container (engineering)", "Writing the exposure control plan (admin document alone without practice)", "Choosing wall paint color"],
      "Work-practice controls change how tasks are performed to reduce exposure.",
      [
        "Containers are engineering controls.",
        "Plans are administrative; practices enact them.",
        "Paint is unrelated.",
      ],
      "medium",
    ],
    [
      "Eye wash stations should be:",
      "Available, accessible, and flushed/maintained per requirements when corrosive chemicals are used",
      ["Locked in a distant closet without signage", "Filled with soda as irrigant", "Optional if bottled water exists somewhere in town"],
      "Prompt irrigation capability is required for chemical exposures.",
      [
        "Access delayed defeats purpose.",
        "Use proper potable/eye wash fluid.",
        "On-site access matters.",
      ],
      "medium",
    ],
    [
      "Nitrous oxide occupational exposure is reduced by:",
      "Scavenging systems, equipment checks, and appropriate ventilation/work practices",
      ["Running nitrous in unventilated closets for fun", "Disabling scavengers to save gas", "Holding the mask loosely near staff faces all day"],
      "Scavenging and maintenance protect staff from chronic N2O exposure.",
      [
        "Unventilated use increases exposure.",
        "Scavengers should function.",
        "Leaks expose staff.",
      ],
      "medium",
    ],
    [
      "Which training topic is required under OSHA BBP for dental employees with exposure risk?",
      "Modes of transmission, PPE use, exposure response, and engineering/work-practice controls",
      ["Only marketing scripts for whitening upsells", "Only how to brew coffee", "Optional silent self-study with no documentation ever"],
      "BBP training covers exposure prevention and response; employers document training.",
      [
        "Marketing is not BBP training.",
        "Coffee is unrelated.",
        "Training must be provided/documented.",
      ],
      "easy",
    ],
    [
      "Regulated medical waste containers should be:",
      "Labeled/color-coded, closable, and suitable to contain contents without leakage",
      ["Unlabeled clear bags mixed with lunch trash", "Overfilled past the fill line routinely", "Emptied by hand sorting needles"],
      "Proper containers prevent injury and illegal disposal.",
      [
        "Labeling/separation is required.",
        "Overfilling causes spills/sticks.",
        "Never hand-sort needles.",
      ],
      "easy",
    ],
    [
      "Which statement about tuberculosis infection control in dentistry is correct?",
      "Patients with infectious TB should have elective care deferred; urgent care uses airborne precautions/referral as appropriate",
      ["TB is never a concern because dentistry uses gloves", "Coughing patients should wait in a crowded lobby indefinitely without masking policies", "N95 use is never relevant"],
      "Airborne TB requires special handling beyond Standard Precautions alone.",
      [
        "Gloves do not stop airborne TB.",
        "Triage/masking reduces exposure.",
        "Respirators may be required.",
      ],
      "hard",
    ]
  ],
};
