/** Five additional rows per topic (questions 011–015) for Wave 1 health banks. */
/** @typedef {[string, string, string[], string, string[], string]} Row */

/** @type {Record<string, Record<string, Row[]>>} */
export const extras = {
  "nha-ccma-readiness-check": {
    "clinical-patient-care": [
      [
        "When administering an intradermal TB skin test (Mantoux), the CMA should expect to see:",
        "A small wheal (bleb) form under the skin if the injection is placed correctly",
        ["Immediate muscle twitching in the deltoid", "Blood return in the syringe barrel as with IV push", "No skin change because ID injections never raise a wheal"],
        "Correct intradermal placement produces a pale wheal; absence of a wheal suggests the dose was too deep/subcutaneous.",
        ["Deltoid IM is a different route.", "ID tests are not IV injections.", "A wheal is the expected local finding."],
        "medium",
      ],
      [
        "Which action is appropriate before applying a Holter monitor (concept)?",
        "Educate the patient on keeping a symptom/activity diary and not getting the unit wet per instructions",
        ["Tell the patient to swim daily with the monitor on", "Remove all electrodes after one hour routinely", "Have the patient MRI the same day without notifying staff"],
        "Ambulatory monitors require diary use and device care; water and MRI can damage equipment or risk safety.",
        ["Water exposure typically damages the unit.", "Holter studies last longer than one hour.", "MRI is contraindicated with many monitors."],
        "medium",
      ],
      [
        "A patient with diabetes reports feeling sweaty, shaky, and confused. Capillary glucose is low. The CMA should:",
        "Follow hypoglycemia protocol (e.g., glucose source if able to swallow) and notify the provider/nurse",
        ["Give insulin immediately to correct the low reading", "Encourage vigorous exercise until symptoms pass", "Ignore symptoms because confusion is normal"],
        "Hypoglycemia requires prompt carbohydrate treatment per protocol and clinical escalation—not more insulin.",
        ["Insulin worsens hypoglycemia.", "Exercise can worsen lows.", "Neuro symptoms need action."],
        "hard",
      ],
      [
        "Proper ear irrigation technique for cerumen (when ordered) includes:",
        "Using body-temperature solution and aiming the stream toward the canal wall, not directly at the tympanic membrane",
        ["Using ice-cold water forcefully at the eardrum", "Inserting the tip until it touches the tympanic membrane", "Irrigating if the patient has a known perforated eardrum without checking orders"],
        "Warm solution and angled stream reduce vertigo/trauma; perforation is often a contraindication.",
        ["Cold water can cause severe vertigo.", "Deep contact risks TM injury.", "Perforation needs provider guidance."],
        "hard",
      ],
      [
        "When collecting a throat culture swab, the CMA should:",
        "Swab the tonsillar pillars/posterior pharynx while avoiding the tongue and teeth as much as possible",
        ["Only swab the inner cheek for strep testing", "Touch the swab to the lips then the container rim", "Have the patient eat a large meal immediately before to coat the pharynx"],
        "Target inflamed pharyngeal areas; contamination from tongue/food reduces culture quality.",
        ["Cheek swab misses pharyngeal organisms.", "Rim contamination ruins specimens.", "Food residue contaminates."],
        "easy",
      ],
    ],
    "phlebotomy-ekg": [
      [
        "Which tube additive is typically associated with EDTA lavender-top collections?",
        "An anticoagulant used for CBC and related hematology tests",
        ["Clot activator only for chemistry serum always", "Sodium citrate for PT/INR exclusively in lavender tops", "No additive—lavender tops are plain red"],
        "EDTA anticoagulates whole blood for hematology; citrate is light blue; serum tubes differ.",
        ["Many chemistry tests use serum/plasma tubes, not EDTA CBC tubes.", "Citrate is light blue.", "Lavender contains EDTA."],
        "easy",
      ],
      [
        "Lead II on a standard ECG typically views the heart's electrical activity between:",
        "The right arm and left leg electrodes",
        ["V1 and V6 only", "Both earlobes exclusively", "The umbilicus and left scapula"],
        "Limb lead II is RA (−) to LL (+); precordial leads are chest positions.",
        ["V leads are precordial.", "Earlobes are not standard limb lead sites.", "Those landmarks are not Lead II."],
        "medium",
      ],
      [
        "If a patient develops syncope during venipuncture, the CMA should:",
        "Remove the needle, protect the patient from injury, and follow syncope/first-aid protocol",
        ["Continue filling all tubes while the patient is unconscious", "Have the patient stand immediately to restore blood pressure", "Leave the room to find the chart first"],
        "Stop the procedure, prevent falls/injury, and get help per protocol.",
        ["Do not continue invasive procedures on an unresponsive patient.", "Standing risks injury.", "Patient safety comes before chart retrieval."],
        "easy",
      ],
      [
        "Which statement about plasma vs serum is correct?",
        "Plasma is the liquid portion of anticoagulated blood; serum is after clotting without anticoagulant",
        ["Serum always contains fibrinogen like plasma", "Plasma is only obtained from capillary heel sticks", "They are identical terms with no lab distinction"],
        "Anticoagulated tubes yield plasma; clot tubes yield serum after centrifugation.",
        ["Serum lacks fibrinogen consumed in the clot.", "Venous anticoagulated draws commonly yield plasma.", "Labs distinguish plasma vs serum."],
        "medium",
      ],
      [
        "A wandering baseline on an ECG is often improved by:",
        "Cleaning skin, securing electrodes, and checking for loose leads or patient movement/cable tension",
        ["Removing the ground electrode permanently", "Asking the patient to cough continuously", "Setting the machine to defibrillate"],
        "Poor contact and motion cause baseline wander; fix skin prep and lead security.",
        ["Ground/reference connections are needed.", "Coughing worsens artifact.", "Defibrillation is not an ECG quality fix."],
        "medium",
      ],
    ],
    "safety-infection": [
      [
        "Droplet precautions (concept) typically require:",
        "A surgical mask when working within close range of the patient, plus Standard Precautions",
        ["An N95 for every common cold without assessment", "No mask if the patient covers their mouth sometimes", "Only shoe covers"],
        "Droplet pathogens need mask protection at close range; respirator use follows airborne rules/assessment.",
        ["Not every illness requires N95.", "Inconsistent covering is insufficient.", "Shoe covers do not stop droplets."],
        "medium",
      ],
      [
        "Which statement about multi-dose vials is correct?",
        "Use aseptic technique, dating/beyond-use rules per policy, and never combine leftover contents into other vials",
        ["Share one syringe across multiple vials and patients", "Leave needles inserted in the vial septum between uses", "Store opened vials in unlabeled coat pockets"],
        "Aseptic access and labeling prevent contamination and medication errors.",
        ["Syringe sharing transmits infection.", "In-place needles contaminate vials.", "Unlabeled pocket storage is unsafe."],
        "hard",
      ],
      [
        "Surgical asepsis differs from medical asepsis in that surgical asepsis:",
        "Aims to eliminate all microorganisms from an area/object (sterile technique)",
        ["Only reduces microbes on hands with social handwashing", "Allows nonsterile items on a sterile field", "Is identical to Standard Precautions alone"],
        "Sterile technique seeks absence of microbes for invasive procedures; medical asepsis reduces them.",
        ["Social handwashing is medical asepsis level.", "Nonsterile items contaminate fields.", "Standard Precautions are not full sterile technique."],
        "medium",
      ],
      [
        "When is it appropriate to use an alcohol-based hand rub?",
        "When hands are not visibly soiled and the product is indicated by policy for the pathogens involved",
        ["When hands are heavily contaminated with blood without washing first", "After caring for a patient with known C. difficile if soap/water is required by policy—prefer rub only", "Instead of removing gloves between patients"],
        "ABHR is for clean hands in many situations; soap/water is needed for visible soil and certain spores per policy.",
        ["Visible blood needs soap/water washing.", "Spore-forming organisms often require soap/water.", "Gloves are changed; hygiene still required."],
        "hard",
      ],
      [
        "A sterile package's sterility is considered compromised if:",
        "It is wet, torn, expired, or has a broken seal/indicator failure",
        ["It was stored on a clean shelf within date with intact seals", "The chemical indicator shows an acceptable change per IFU", "It was opened in a controlled sterile field and used immediately as intended"],
        "Moisture, damage, expiration, and failed indicators mean do not use.",
        ["Proper storage supports sterility.", "Acceptable indicators support use.", "Correct immediate use is the point of sterile supplies."],
        "easy",
      ],
    ],
    "admin-communication": [
      [
        "Which is the best example of a closed-ended question for clarifying a symptom timeline?",
        "Did the chest pain start today?",
        ["Tell me everything about your life story.", "How does that make you feel in a poetic sense?", "Why are you always late?"],
        "Closed questions elicit yes/no or brief facts useful for triage details; open questions gather narrative.",
        ["That is open-ended and broad.", "Not a clinical clarifying closed question.", "Judgmental and unhelpful."],
        "easy",
      ],
      [
        "When documenting in an EHR, the CMA should avoid:",
        "Using another user's login credentials to enter notes",
        ["Using approved abbreviations listed in facility policy", "Recording vital signs at the time measured", "Correcting errors per amendment policy"],
        "Shared logins destroy audit integrity and violate security policy.",
        ["Approved abbreviations are acceptable.", "Timely vitals are required.", "Proper corrections are allowed."],
        "easy",
      ],
      [
        "A patient requests that no family members receive health information. The CMA should:",
        "Document the restriction per policy and honor it unless a legal exception applies",
        ["Tell the spouse everything anyway for convenience", "Post the request on the waiting-room board", "Ignore the request because families always decide"],
        "Patients may restrict disclosures; document and follow privacy rules.",
        ["Unauthorized disclosure violates HIPAA.", "Public posting is a breach.", "Competent adults control their PHI."],
        "medium",
      ],
      [
        "Which task is typically within CMA scope regarding prescriptions?",
        "Calling in or transmitting refills only as directed by a licensed provider and permitted by law/policy",
        ["Independently starting a new controlled substance prescription", "Changing antibiotic dose based on personal judgment", "Advising patients to stop all home meds without an order"],
        "MAs may assist with communication of provider orders within legal limits—not independent prescribing.",
        ["Controlled prescribing is a licensed-provider act.", "Dose changes need orders.", "Stopping meds needs clinician direction."],
        "hard",
      ],
      [
        "Active listening in clinical communication includes:",
        "Paraphrasing key points and clarifying understanding without interrupting constantly",
        ["Checking email while the patient talks", "Finishing every sentence for the patient", "Dismissing concerns as overreactions"],
        "Active listening confirms understanding and builds trust.",
        ["Divided attention blocks listening.", "Constant interruption hinders history.", "Dismissal harms rapport and safety."],
        "easy",
      ],
    ],
  },

  "nremt-emt-readiness-check": {
    "airway-respiration": [
      [
        "A patient with severe asthma is wheezing less than before and becoming drowsy with poor air movement. This most likely indicates:",
        "Worsening obstruction and impending respiratory failure",
        ["Complete recovery", "That nebulizer therapy is no longer needed ever", "A primary psychiatric emergency only"],
        "Silent chest/fatigue with drowsiness signals exhaustion and failure—support ventilation and ALS.",
        ["Less wheezing can mean less air movement, not cure.", "Treatment escalation is needed.", "Airway/breathing failure is medical."],
        "hard",
      ],
      [
        "The preferred method to open the airway of a trauma patient with possible c-spine injury is:",
        "Jaw-thrust maneuver while maintaining manual cervical stabilization",
        ["Head-tilt/chin-lift without spinal precautions", "Flexing the neck fully forward", "Placing a pillow under the head aggressively"],
        "Jaw-thrust minimizes cervical movement in trauma airway opening.",
        ["Head-tilt may move the cervical spine.", "Flexion is harmful in c-spine injury.", "Pillows can flex/extend the neck improperly."],
        "medium",
      ],
      [
        "Adequate adult ventilation rate with a BVM for a patient with a pulse (general guideline concept) is approximately:",
        "About 1 breath every 5–6 seconds (roughly 10–12/min), enough to produce visible chest rise",
        ["60 breaths per minute as fast as possible", "One breath every 30 seconds only", "No ventilation if SpO2 is unknown"],
        "Avoid hyperventilation; deliver breaths that produce chest rise at an appropriate rate.",
        ["Excessive rates harm hemodynamics.", "Too slow is inadequate.", "Support breathing based on assessment."],
        "medium",
      ],
      [
        "Suctioning an adult patient's airway should be limited to approximately:",
        "No more than about 15 seconds per attempt while monitoring oxygenation",
        ["Several continuous minutes without pause", "Only after the patient is fully cyanotic", "Never, because suction removes oxygen permanently"],
        "Brief suction clears the airway; prolonged suction worsens hypoxia—reoxygenate between attempts.",
        ["Long continuous suction causes hypoxia.", "Do not wait for severe cyanosis.", "Suction is indicated for secretions/vomitus."],
        "easy",
      ],
      [
        "A nonrebreather mask is most appropriate when:",
        "A breathing patient needs high-concentration oxygen and can tolerate the mask",
        ["The patient is apneic and needs artificial ventilation", "The patient requires precise low-flow FiO2 titration only like a Venturi without assessment", "You want to withhold oxygen from hypoxia"],
        "NRB delivers high FiO2 to spontaneously breathing patients; apneic patients need BVM/advanced airway support.",
        ["Apnea requires positive-pressure ventilation.", "NRB is high-flow/high FiO2, not precision low-flow alone.", "Hypoxia needs oxygen."],
        "easy",
      ],
    ],
    "cardiology-resuscitation": [
      [
        "High-quality adult CPR compression depth is generally:",
        "At least 2 inches (5 cm) with full chest recoil",
        ["Less than 1 cm to avoid injury always", "As deep as possible through the spine", "Only enough to move clothing"],
        "Adequate depth and recoil improve coronary perfusion; excessive unsafe force is not the goal—meet guideline depth.",
        ["Too shallow is ineffective.", "Compressing through the spine is harmful.", "Clothing movement is not a depth measure."],
        "easy",
      ],
      [
        "After an AED delivers a shock, the EMT should next:",
        "Resume CPR immediately for about 2 minutes (or until prompted), then reanalyze",
        ["Check a pulse for a full 3 minutes before any compressions", "Turn off the AED permanently", "Give the patient water"],
        "Post-shock CPR minimizes interruptions; AEDs prompt the next analyze cycle.",
        ["Long pulse checks delay CPR.", "Keep the AED attached/ready.", "Oral intake is inappropriate in arrest."],
        "easy",
      ],
      [
        "Which finding is most consistent with right-sided heart failure?",
        "Peripheral edema and jugular venous distention",
        ["Only unilateral wheezes from a foreign body", "Isolated ankle sprain", "Normal exam with marathon tolerance suddenly"],
        "Systemic venous congestion signs suggest right-sided failure; correlate with history.",
        ["Foreign body is airway.", "Sprain is trauma.", "Sudden severe limitation needs evaluation—not 'normal'."],
        "medium",
      ],
      [
        "Aspirin is given in suspected ACS (per protocol) primarily because it:",
        "Inhibits platelet aggregation and may reduce clot progression",
        ["Dissolves established fibrin clots like fibrinolytics in the field always", "Raises blood sugar", "Replaces the need for EMS transport"],
        "Antiplatelet effect is the early ACS benefit; fibrinolytics/PCI are separate hospital decisions.",
        ["EMTs do not give field fibrinolytics as aspirin’s role.", "Aspirin is not a glucose agent.", "Transport remains essential."],
        "medium",
      ],
      [
        "A patient with a VAD (ventricular assist device) is unresponsive and pulseless by usual means. The EMT should:",
        "Follow local VAD/cardiac arrest protocols (often CPR if indicated) and contact medical direction/device coordinator resources",
        ["Assume death without assessment because VADs prevent all emergencies", "Defibrillate by placing pads only on the device driveline", "Give oral nitroglycerin"],
        "VAD patients need specialized protocols; lack of palpable pulse may be expected—use device assessment cues and local rules.",
        ["VAD patients still have emergencies.", "Pads go on skin per AED/manual guidance, not on drivelines.", "Unresponsive patients do not take oral NTG."],
        "hard",
      ],
    ],
    "trauma": [
      [
        "A patient with a penetrating chest wound develops worsening dyspnea and JVD. You should suspect:",
        "Tension pneumothorax physiology and support ABC/ALS per protocol",
        ["Isolated ankle sprain", "Hyperventilation syndrome only", "Food poisoning"],
        "Penetrating chest trauma with distress/JVD raises tension pneumothorax concern—rapid transport/ALS.",
        ["Not an ankle injury pattern.", "Do not dismiss as anxiety.", "GI illness does not explain this trauma pattern."],
        "hard",
      ],
      [
        "For an evisceration, appropriate EMT care includes:",
        "Cover with a moist sterile dressing and occlusive covering as trained; do not push organs back",
        ["Replace organs firmly into the abdomen at the scene", "Wipe organs with alcohol pads aggressively", "Give the patient a large meal"],
        "Keep organs moist and protected; reduction is a surgical task.",
        ["Do not replace eviscerated organs in the field.", "Harsh chemicals injure tissue.", "NPO for likely surgery."],
        "medium",
      ],
      [
        "A traction splint is generally indicated for:",
        "Isolated midshaft femur fracture without contraindications per protocol",
        ["Pelvic fracture as the only treatment", "Open skull fracture", "Suspected cervical spine injury alone"],
        "Traction splints stabilize midshaft femurs when criteria are met; pelvis/spine need other care.",
        ["Pelvis needs binder/stabilization strategies, not classic traction splint as sole care.", "Skull injuries need different management.", "C-spine needs immobilization strategies."],
        "medium",
      ],
      [
        "Cushing's triad (late increased ICP sign) includes:",
        "Hypertension, bradycardia, and irregular respirations",
        ["Hypotension, tachycardia, and warm dry skin only", "Fever, rash, and joint pain only", "Polyuria, polydipsia, polyphagia only"],
        "Rising ICP can produce hypertension with reflex bradycardia and abnormal breathing.",
        ["That pattern fits shock more than Cushing.", "Those are infectious/inflammatory clues.", "Those are hyperglycemia clues."],
        "hard",
      ],
      [
        "When managing an amputation, you should:",
        "Control bleeding, care for the stump, and transport the part wrapped cool/dry per protocol (not directly on ice)",
        ["Place the part in water to soak", "Throw the part away to reduce scene time", "Apply a tourniquet to the amputated part instead of the stump"],
        "Save the part properly for possible reimplantation while prioritizing life-threatening hemorrhage.",
        ["Soaking damages tissue.", "Preserve the part.", "Tourniquet goes on the residual limb as indicated."],
        "easy",
      ],
    ],
    "medical-ops": [
      [
        "Which patient is the highest triage priority in a multi-casualty incident (START concept)?",
        "An unresponsive patient with inadequate breathing after airway positioning attempts fail",
        ["A walking wounded patient with a minor laceration", "A patient with an isolated finger sprain who is ambulatory", "A deceased patient with dependent lividity and obvious mortal injuries"],
        "Immediate (red) patients have life threats; expectant/dead and minor walking wounded are lower priority.",
        ["Walking wounded are delayed/minor.", "Ambulatory minor injuries are low acuity.", "Expectant/dead are not treated first in MCI triage."],
        "medium",
      ],
      [
        "Oral glucose is indicated for a diabetic patient who:",
        "Is hypoglycemic (or suspected) and can protect their airway/swallow",
        ["Is unresponsive with no gag reflex", "Has hyperglycemia with Kussmaul respirations only", "Has a known allergy to glucose and refuses care"],
        "Oral sugar requires intact airway protective reflexes; unresponsive patients need other glucose routes/ALS.",
        ["Aspiration risk if unable to swallow.", "Hyperglycemia needs different care.", "Allergy/refusal blocks administration."],
        "easy",
      ],
      [
        "A patient with suspected stroke within the window should be transported:",
        "Promptly to an appropriate stroke-capable facility with prenotification when possible",
        ["Home for observation only", "To the farthest hospital to avoid busy EDs", "After waiting several hours to see if symptoms resolve"],
        "Time-sensitive stroke care needs rapid transport and hospital alert.",
        ["Home observation delays care.", "Closest appropriate facility matters.", "Waiting wastes the treatment window."],
        "easy",
      ],
      [
        "Which is a common early sign of compensated shock?",
        "Tachycardia with cool, pale, diaphoretic skin while blood pressure is still near normal",
        ["Bradycardia with flushed dry skin and hypertension always", "Normal mentation with bounding pulses and no distress always", "Isolated pruritus without vital changes"],
        "Compensation often raises HR and causes vasoconstriction signs before hypotension appears.",
        ["That pattern is not classic hypovolemic compensation.", "Shock often alters mentation/perfusion later.", "Itching alone is not shock."],
        "medium",
      ],
      [
        "When documenting a patient refusal, the EMT should:",
        "Ensure the patient is informed of risks, is competent, document thoroughly, and involve medical direction per protocol",
        ["Have a minor sibling sign for an adult without authority", "Skip explaining risks to save time", "Force treatment after a competent informed refusal"],
        "Informed refusal requires capacity, risk disclosure, and solid documentation.",
        ["Wrong signature authority is invalid.", "Risks must be explained.", "Competent refusals are respected within law/protocol."],
        "hard",
      ],
    ],
  },

  "nha-cpt-phlebotomy-readiness-check": {
    "circulatory-anatomy": [
      [
        "Which vessel returns deoxygenated blood from the head/arms region toward the heart?",
        "Superior vena cava (via venous pathways from upper body)",
        ["Pulmonary vein from the lungs to the left atrium as a systemic vein from the arm", "Aorta as a vein", "Coronary sinus as the antecubital draw site"],
        "Upper-body systemic venous return reaches the right atrium via the SVC; pulmonary veins carry oxygenated blood.",
        ["Pulmonary veins are not arm venipuncture anatomy.", "Aorta is arterial.", "Coronary sinus is cardiac venous drainage, not AC draw."],
        "medium",
      ],
      [
        "The antecubital fossa commonly used for venipuncture contains:",
        "Median cubital, cephalic, and basilic veins as common options",
        ["Only arteries and no veins", "Only lymphatic ducts suitable for vacuum tubes", "The spinal cord"],
        "Phlebotomists select among AC veins based on accessibility and safety (basilic near nerves/brachial artery).",
        ["Veins are the target.", "Lymphatics are not routine blood draw sites.", "Spinal cord is not in the AC fossa."],
        "easy",
      ],
      [
        "Which statement about capillaries is correct?",
        "They are microscopic vessels where exchange of gases/nutrients occurs and are the source of dermal puncture blood mixtures",
        ["They are the largest arteries in the body", "They contain only valves like large veins always", "They are never involved in heel-stick specimens"],
        "Capillary beds enable exchange; skin punctures collect capillary blood (with interstitial/arterial mix).",
        ["Aorta is a large artery.", "Capillaries lack the valve anatomy of veins.", "Heel sticks are capillary collections."],
        "easy",
      ],
      [
        "Blood pressure is highest in which vessel type under normal physiology?",
        "Arteries (especially aorta/large arteries)",
        ["Veins of the foot", "Capillaries of the skin only", "Lymphatic capillaries"],
        "Arterial pressure is highest; veins are low-pressure capacitance vessels.",
        ["Venous pressure is much lower.", "Capillary pressure is lower than arterial.", "Lymphatics are not systemic arterial pressure."],
        "easy",
      ],
      [
        "The basilic vein is often considered higher risk for venipuncture because it lies near:",
        "The brachial artery and median nerve",
        ["Only the Achilles tendon", "The trachea", "The femoral head exclusively"],
        "Medial AC anatomy places basilic near artery/nerve—use caution or choose safer veins first.",
        ["Achilles is ankle.", "Trachea is neck.", "Femoral head is hip."],
        "medium",
      ],
    ],
    "collection-equipment": [
      [
        "A butterfly (winged infusion) set is most helpful when:",
        "Drawing from small/fragile veins or hand veins with better control",
        ["Replacing the need for patient identification", "Drawing arterial blood gases without training", "Avoiding order of draw rules"],
        "Butterflies aid difficult veins; ID and order of draw still apply; ABGs need specialized training.",
        ["ID is always required.", "ABG is arterial skillset.", "Order of draw still matters."],
        "easy",
      ],
      [
        "Which needle gauge has a larger lumen?",
        "18-gauge (smaller gauge number = larger diameter)",
        ["25-gauge compared with 18-gauge", "Gauge number equal to lumen size directly", "30-gauge is always preferred for blood bank units"],
        "Lower gauge numbers are larger bores; very small gauges increase hemolysis risk for some tests.",
        ["25G is smaller lumen than 18G.", "Gauge is inverse to diameter.", "Blood bank often uses larger-bore needles."],
        "medium",
      ],
      [
        "Serum separator tubes (SST, often gold/tiger) typically:",
        "Contain clot activator and gel for serum chemistry after clotting/centrifugation",
        ["Contain EDTA for CBC", "Contain sodium citrate for PT/INR", "Must never be inverted after draw"],
        "SST yields serum for many chemistry tests; invert gently to mix clot activator.",
        ["EDTA is lavender.", "Citrate is light blue.", "Inversion mixes additives properly."],
        "easy",
      ],
      [
        "A gray-top tube with sodium fluoride/potassium oxalate is commonly used for:",
        "Glucose testing when glycolysis inhibition is needed",
        ["CBC only", "Coagulation PT/INR only", "Blood cultures exclusively"],
        "Fluoride inhibits glycolysis; gray tops are classic glucose/alcohol (policy) tubes—not CBC/coag/cultures.",
        ["CBC is EDTA.", "Coag is citrate.", "Cultures use dedicated bottles."],
        "medium",
      ],
      [
        "When using a syringe draw transferred to evacuated tubes, the phlebotomist should:",
        "Transfer using a transfer device—never force blood into tubes by removing stoppers with the needle tip in an unsafe way",
        ["Squirt blood forcefully into tubes with the needle uncapped toward coworkers", "Recap the needle with two hands then puncture stoppers blindly", "Discard the order of draw because syringe draws are exempt"],
        "Safety transfer devices prevent needlesticks; order of draw still applies when filling tubes.",
        ["Unsafe spraying risks exposure.", "Two-handed recapping is hazardous.", "Order of draw still matters."],
        "hard",
      ],
    ],
    "specimen-handling": [
      [
        "Cold agglutinins specimens often require:",
        "Keeping the specimen warm (body temperature) as directed until processing",
        ["Freezing immediately at −70°C at the bedside always", "Leaving on ice for 24 hours without order", "Shaking until frothy"],
        "Cold agglutinins can precipitate in the cold—follow warm-handling instructions.",
        ["Not a routine deep-freeze bedside step.", "Ice may be wrong for this test.", "Frothing damages specimen."],
        "hard",
      ],
      [
        "Which analyte is commonly elevated by prolonged fist clenching/pumping during venipuncture?",
        "Potassium (and other muscle-related changes)",
        ["Only urine specific gravity", "Only CSF glucose", "Room air oxygen percent"],
        "Muscle activity can raise potassium and affect other results—avoid pumping.",
        ["Not a urine test effect.", "Not CSF.", "Not atmospheric O2."],
        "medium",
      ],
      [
        "Bilirubin specimens are often protected from light because light can:",
        "Degrade bilirubin and falsely lower results",
        ["Increase WBC count mechanically", "Sterilize the specimen completely", "Convert serum to plasma"],
        "Light-sensitive analytes need amber tubes/wraps as specified.",
        ["Light does not raise WBC via that mechanism.", "Light does not sterilize blood tubes.", "Serum/plasma depends on clotting/anticoagulant."],
        "easy",
      ],
      [
        "A specimen rejected for improper labeling should be:",
        "Recollected with correct bedside labeling per policy—do not relabel another patient's tube casually",
        ["Relabeled in the lab based on guesswork", "Poured into a correctly labeled empty tube from a different patient", "Reported as normal without testing"],
        "Mislabeled specimens are patient-safety events; recollect rather than guess.",
        ["Guessing causes wrong-patient results.", "Transfer between patients is dangerous.", "Do not invent results."],
        "easy",
      ],
      [
        "Which statement about blood culture collection is correct?",
        "Cleanse the site thoroughly with appropriate antiseptic and fill bottles to correct volumes without touching sterile bottle tops with nonsterile items",
        ["Palpate the site heavily with a nonsterile finger after final prep without reprepping", "Collect through a contaminated IV line always as first choice", "Shake bottles with the butterfly needle still attached in midair"],
        "Aseptic prep and correct volume maximize pathogen recovery and minimize contamination.",
        ["Repalpating contaminates the site.", "Peripheral draws are preferred when possible.", "Unsafe handling risks sticks/contamination."],
        "hard",
      ],
    ],
    "safety-patient": [
      [
        "Which patient should generally not have a venipuncture in the arm on the same side as a mastectomy with lymph node dissection (without provider approval)?",
        "A patient with lymphedema risk on that side—prefer the opposite arm per policy",
        ["Any patient who ate breakfast", "Any patient under age 50 automatically", "Only patients with green eyes"],
        "Avoid compromised lymphatic drainage arms unless cleared—reduces infection/lymphedema risk.",
        ["Food intake is a fasting issue, not mastectomy side rule.", "Age alone is not the rule.", "Eye color is irrelevant."],
        "medium",
      ],
      [
        "The best site for an infant heel stick is generally:",
        "The lateral or medial plantar surface of the heel—avoid the center/back of the heel",
        ["The center of the heel pad deeply", "The fingers of a newborn exclusively for all tests", "The antecubital fossa with a 15G needle routinely"],
        "Approved heel regions reduce calcaneal injury risk; deep central punctures can injure bone.",
        ["Central heel risks osteomyelitis/calcaneus injury.", "Fingers may be used later but heel is common in neonates.", "Large AC needles are inappropriate for infants."],
        "medium",
      ],
      [
        "Transmission-based precautions for a patient with suspected TB include:",
        "Airborne precautions with appropriate respirator and room controls per facility policy",
        ["No PPE if the patient is coughing into a tissue sometimes", "Contact gown only without respiratory protection", "Shoe covers as the sole control"],
        "TB requires airborne precautions beyond Standard Precautions alone.",
        ["Tissues alone are insufficient for staff protection.", "Gowns do not replace respirators for airborne TB.", "Shoe covers are not the key control."],
        "easy",
      ],
      [
        "A patient refuses a blood draw after education. The phlebotomist should:",
        "Respect the refusal, notify the appropriate clinician/nurse, and document per policy",
        ["Hold the patient down to obtain the sample", "Draw anyway because the doctor ordered it", "Fabricate results"],
        "Competent refusal must be honored; coercion is assault and unethical.",
        ["Forcing care is illegal/unethical.", "Orders do not override refusal capacity rules.", "Falsifying results is fraud."],
        "easy",
      ],
      [
        "Which action reduces needlestick risk most effectively?",
        "Using engineered sharps safety devices and disposing immediately in sharps containers without two-handed recapping",
        ["Passing uncapped needles hand-to-hand routinely", "Leaving sharps on the bed for housekeeping", "Bending needles before disposal"],
        "Safety devices + immediate disposal are core OSHA-aligned practices.",
        ["Hand-to-hand passing causes injuries.", "Loose sharps injure others.", "Bending is prohibited."],
        "easy",
      ],
    ],
  },

  "nha-cpct-readiness-check": {
    "patient-care": [
      [
        "When measuring a patient's weight, the PCT should:",
        "Zero/balance the scale, have the patient wear similar clothing/shoes per protocol, and record accurately",
        ["Estimate from the previous month without measuring", "Ask the patient to hold a full backpack on the scale", "Round all weights to the nearest 50 pounds"],
        "Accurate weights guide fluid/medication decisions; technique matters.",
        ["Estimates are not ordered measurements.", "Extra items falsify weight.", "Excessive rounding loses clinical value."],
        "easy",
      ],
      [
        "A patient with dysphagia is at increased risk for:",
        "Aspiration during eating/drinking",
        ["Improved marathon performance", "Automatic immunity to pneumonia", "Faster wound healing always"],
        "Swallowing difficulty raises aspiration and pneumonia risk—follow thickened liquids/feeding precautions.",
        ["Dysphagia does not improve athletics.", "Aspiration risk can worsen pulmonary infection risk.", "Nutrition issues may impair healing."],
        "easy",
      ],
      [
        "Which is the safest way to identify a patient before care?",
        "Use two identifiers (e.g., name and date of birth) and match the wristband/order",
        ["Ask 'Are you Mr. Smith?' and accept a nod from across the room", "Use room number only", "Skip ID for familiar patients"],
        "Active two-identifier verification prevents wrong-patient errors.",
        ["Leading yes/no questions are unsafe.", "Room numbers change.", "Familiarity does not replace ID."],
        "easy",
      ],
      [
        "When making an occupied bed, the PCT should:",
        "Maintain side-rail safety, keep the patient covered for dignity/warmth, and use good body mechanics",
        ["Pull the patient by the arms across the bed without help when heavy", "Leave the patient on the floor briefly to change linens faster", "Remove all rails and walk away for supplies"],
        "Occupied bedmaking prioritizes safety, privacy, and ergonomics; get help for dependent patients.",
        ["Arm-pulling injures patients/staff.", "Floor placement is dangerous.", "Abandonment/fall risk."],
        "medium",
      ],
      [
        "Range-of-motion exercises should be performed:",
        "As ordered, supporting joints, and stopping if pain/resistance indicates harm",
        ["Past the point of severe pain to 'loosen' joints forcibly", "Only on unstable fractures without orders", "By twisting the neck abruptly in all patients"],
        "ROM is gentle and order-based; force causes injury.",
        ["Painful forcing is harmful.", "Fractures need specific orders.", "Aggressive neck ROM is dangerous."],
        "medium",
      ],
    ],
    "safety-infection": [
      [
        "The PCT finds a frayed electrical cord on a device. The correct action is:",
        "Remove it from service, tag/report per policy, and do not use until repaired",
        ["Wrap with tape and continue using", "Ignore if the device still powers on", "Place in water to test insulation"],
        "Damaged cords are fire/shock hazards—out of service until fixed.",
        ["Tape is not a repair.", "Functioning ≠ safe.", "Water increases shock risk."],
        "easy",
      ],
      [
        "Which is correct about bed alarms for fall-risk patients?",
        "They are adjuncts—respond promptly and continue other fall precautions",
        ["They replace the need for rounding or safe environment", "They allow side rails to be left down with the bed high always", "They authorize restraints without orders"],
        "Alarms support but do not replace comprehensive fall prevention.",
        ["Rounding/environment still matter.", "High beds and down rails increase falls.", "Restraints need orders/assessment."],
        "medium",
      ],
      [
        "When a chemical spill occurs, the PCT should:",
        "Protect self/others, follow SDS/spill protocol, and report—do not clean unknown chemicals casually",
        ["Wipe with bare hands immediately", "Pour the chemical into the sink without identification", "Ignore small spills of unknown agents"],
        "SDS-guided response prevents injury; unknown chemicals need proper handling.",
        ["Bare-hand contact risks burns/toxicity.", "Improper disposal is hazardous.", "Even small unknown spills matter."],
        "medium",
      ],
      [
        "Proper use of a gait belt includes:",
        "Applying snugly at the waist over clothing and holding the belt to guide/support—not lifting by the belt alone for heavy dependent transfers without help",
        ["Placing it around the patient's neck", "Using it to yank the patient upward by the arms", "Skipping the belt for all unsteady patients to save time"],
        "Gait belts aid safe ambulation/transfers with proper technique and adequate assistance.",
        ["Neck placement can choke.", "Arm yanking injures shoulders.", "Unsteady patients often need the belt."],
        "easy",
      ],
      [
        "Which PPE sequence concept is correct after caring for a patient on contact precautions?",
        "Remove contaminated PPE carefully to avoid self-contamination, then perform hand hygiene",
        ["Remove gloves and immediately touch your face before hygiene", "Wear the same gown to the cafeteria", "Skip hand hygiene because gloves were used"],
        "PPE removal order and hand hygiene prevent self-contamination and spread.",
        ["Face touching spreads organisms.", "Gowns are not worn outside care areas.", "Hygiene is required after glove removal."],
        "easy",
      ],
    ],
    "phlebotomy-ekg": [
      [
        "Before performing a capillary glucose check, the PCT should:",
        "Verify the order/protocol, identify the patient, and ensure the meter/strips are appropriate and in date",
        ["Use expired strips if the bottle is not empty", "Skip cleaning the finger if it looks clean", "Share lancets between patients after wiping with alcohol"],
        "POCT accuracy and safety depend on ID, valid supplies, and skin prep; lancets are single-use.",
        ["Expired strips give bad results.", "Cleaning reduces contamination.", "Lancet sharing transmits bloodborne pathogens."],
        "easy",
      ],
      [
        "Which ECG artifact is commonly caused by patient shivering?",
        "Somatic tremor artifact",
        ["Exact 60-cycle flatline only from good contact", "Normal PQRST with perfect baseline always", "Printer paper jam exclusively"],
        "Muscle tremor creates irregular fine artifact; warm/support the patient and ensure contact.",
        ["60-cycle is electrical interference pattern.", "Tremor is not a normal tracing.", "Paper jams are mechanical."],
        "medium",
      ],
      [
        "When collecting a urine specimen for culture, the PCT should instruct the patient (clean-catch) to:",
        "Cleanse as directed, void a small amount, then collect midstream into a sterile container",
        ["Collect from a bedpan that sat open overnight", "Add toilet paper into the cup for absorption", "Touch the inside of the sterile lid freely"],
        "Midstream clean-catch into a sterile container reduces contamination.",
        ["Stale open containers contaminate.", "Paper contaminates.", "Lid interior must stay sterile."],
        "easy",
      ],
      [
        "A PCT notices the IV site is swollen, cool, and pale with pain. The PCT should:",
        "Stop involving the site per scope—do not adjust rates—and report immediately to the nurse",
        ["Speed the IV rate to flush the swelling", "Ignore it until the end of shift", "Remove the IV catheter independently if not trained/authorized"],
        "Infiltration signs need prompt nursing notification; PCT scope limits invasive IV actions.",
        ["Faster rates worsen infiltration.", "Delay harms tissue.", "Removal requires authorization/training."],
        "hard",
      ],
      [
        "For a routine 12-lead ECG, V4 is placed at:",
        "Fifth intercostal space, midclavicular line (left)",
        ["Fourth intercostal space right sternal border", "Directly on the right hip", "On the left scapula only"],
        "V4 is 5th ICS MCL; V1 is 4th ICS right sternal border.",
        ["That is V1.", "Hip is incorrect.", "Scapula is incorrect for V4."],
        "medium",
      ],
    ],
    "professional-practice": [
      [
        "A visitor asks for details about a patient's diagnosis. The PCT should:",
        "Decline to share PHI and direct them to the appropriate authorized process/nurse",
        ["Share the full chart because they brought flowers", "Whisper the diagnosis in the hallway", "Post an update on the unit social page"],
        "PHI disclosure requires authorization/care-team need-to-know.",
        ["Gifts do not authorize PHI access.", "Hallway talk is improper.", "Social posts are breaches."],
        "easy",
      ],
      [
        "Which behavior demonstrates professional boundaries?",
        "Keeping relationships therapeutic and not exchanging personal romantic advances with patients",
        ["Accepting large cash gifts secretly for preferential care", "Sharing home address and inviting patients over alone", "Posting patient photos for likes"],
        "Boundaries protect patients and staff; dual relationships and social media PHI are prohibited.",
        ["Secret gifts/preferential care is unethical.", "Personal invitations blur boundaries.", "Photos are PHI."],
        "medium",
      ],
      [
        "If the PCT makes a documentation error, the correct approach is:",
        "Correct it according to facility policy (e.g., amendment) without erasing the original improperly",
        ["White-out the entry completely so it cannot be read", "Delete the entire chart", "Blame another PCT in a falsified note"],
        "Transparent corrections maintain legal integrity of the record.",
        ["Obliterating entries is improper.", "Deleting charts is misconduct.", "Falsification is fraud."],
        "easy",
      ],
      [
        "Team communication using SBAR typically includes:",
        "Situation, Background, Assessment, and Recommendation/Request",
        ["Only jokes to reduce stress", "Only the patient's room color", "Silent assumptions without speaking up"],
        "SBAR structures clear handoffs and escalation.",
        ["Humor is not a substitute structure.", "Irrelevant details omit clinical content.", "Silence harms safety."],
        "medium",
      ],
      [
        "Workplace violence from a threatening visitor should lead the PCT to:",
        "Prioritize safety, remove self/patients from harm if possible, and call security/follow facility response",
        ["Argue alone in a secluded area", "Ignore credible threats", "Retaliate physically as first response when escape is possible"],
        "Safety systems and de-escalation/security response protect everyone.",
        ["Isolation increases risk.", "Threats need reporting/response.", "Escape/security first when possible."],
        "hard",
      ],
    ],
  },

  "nha-excpt-readiness-check": {
    pharmacology: [
      [
        "Which drug class is omeprazole typically associated with?",
        "Proton pump inhibitor used to reduce gastric acid",
        ["Loop diuretic for acute pulmonary edema", "Short-acting insulin for DKA only", "Opioid antitussive"],
        "Omeprazole is a PPI for GERD/ulcer acid suppression—not a diuretic, insulin, or opioid.",
        ["Furosemide is a loop diuretic.", "Insulins are different agents.", "Codeine-type antitussives are opioids."],
        "easy",
      ],
      [
        "A common serious adverse effect to counsel about with warfarin is:",
        "Bleeding/bruising risk and need for INR monitoring/drug-diet interactions",
        ["Bright orange urine as the therapeutic goal", "Complete absence of any interaction potential", "Immediate cure of infections"],
        "Warfarin anticoagulation requires bleeding vigilance and interaction awareness.",
        ["Orange urine is not the goal (phenazopyridine colors urine).", "Many interactions exist.", "Warfarin is not an antibiotic."],
        "medium",
      ],
      [
        "Which medication is a short-acting beta-2 agonist used for acute bronchospasm?",
        "Albuterol",
        ["Montelukast as a rescue inhaler identical to albuterol", "Fluticasone nasal spray for sudden severe asthma attack as sole rescue", "Metformin"],
        "Albuterol is the classic SABA rescue; controllers/other classes are not equivalent acute rescue.",
        ["Montelukast is not a SABA rescue inhaler.", "ICS/nasal steroids are not acute rescue alone.", "Metformin is for diabetes."],
        "easy",
      ],
      [
        "ACE inhibitors (e.g., lisinopril) are commonly associated with which adverse effect?",
        "Dry cough (and risk of hyperkalemia/angioedema)",
        ["Orange skin discoloration as intended therapy", "Opioid withdrawal syndrome", "Immediate hypoglycemia in all non-diabetics"],
        "ACEI cough and angioedema/hyperkalemia are key counseling/monitoring points.",
        ["Not an intended pigment effect.", "Not opioid-related.", "Hypoglycemia is not the classic ACEI effect."],
        "medium",
      ],
      [
        "Which statement about narrow therapeutic index drugs is correct?",
        "Small dose/level changes can cause toxicity or loss of efficacy—extra verification is critical",
        ["They never require refills counseling", "They are always OTC", "Counting is unnecessary because errors cannot harm"],
        "NTI drugs (e.g., digoxin, warfarin, levothyroxine nuances) need careful dosing accuracy.",
        ["Counseling still matters.", "Many NTI drugs are Rx-only.", "Errors can be severe."],
        "hard",
      ],
    ],
    "federal-law": [
      [
        "Under federal controlled substance schedules, Schedule II drugs:",
        "Have high abuse potential and generally cannot be refilled; require compliant prescriptions",
        ["May be sold OTC without limits", "Have no medical use in the U.S. (like Schedule I)", "Can be refilled five times in six months like many Schedule IV examples without restriction differences"],
        "C-II drugs have strict ordering/refill rules distinct from III–V; Schedule I has no accepted medical use federally.",
        ["C-II are not OTC.", "C-II have accepted use under strict control.", "Refill rules differ from III–V."],
        "medium",
      ],
      [
        "The Combat Methamphetamine Epidemic Act restricts retail sales of:",
        "Pseudoephedrine/ephedrine/phenylpropanolamine products with ID/log and quantity limits",
        ["All topical hydrocortisone 0.5%", "Insulin vials exclusively", "Normal saline flushes only"],
        "CMEA targets precursor chemicals used to make methamphetamine.",
        ["Hydrocortisone is not the CMEA focus.", "Insulin has other rules.", "Saline is not a CMEA precursor control."],
        "easy",
      ],
      [
        "Which is a key purpose of the FDA regarding medications?",
        "Overseeing safety/effectiveness of drugs/devices and regulating labeling/manufacturing standards",
        ["Setting all state Medicaid reimbursement rates exclusively", "Licensing individual pharmacy technicians in every state", "Operating community pharmacies for retail profit"],
        "FDA regulates drug products; state boards license personnel; CMS/states handle much reimbursement.",
        ["Reimbursement is not FDA's core role.", "Tech licensing is state-based.", "FDA is not a retail pharmacy chain."],
        "easy",
      ],
      [
        "HIPAA in the pharmacy setting requires staff to:",
        "Use/disclose PHI only for permitted purposes and safeguard records/conversations",
        ["Discuss therapies loudly using full names in the waiting area for convenience", "Sell patient medication lists to marketers freely", "Post prescription details on personal social media for education"],
        "Minimum necessary and privacy safeguards apply in pharmacies.",
        ["Public discussion is improper.", "Sale of PHI is illegal.", "Social posts are breaches."],
        "easy",
      ],
      [
        "A valid prescription for a controlled substance generally must include:",
        "Patient name, drug name/strength, quantity, directions, date, and prescriber information/signature as required by law",
        ["Only the drug name with no patient identity", "A nickname for the prescriber without NPI/DEA when required", "Quantity written as 'as much as you want' without a numeric amount when a quantity is required"],
        "Controlled Rx elements are tightly specified federally/state; incomplete Rxs cannot be filled as-is.",
        ["Patient identity is required.", "Prescriber identifiers matter for controlled Rx.", "Quantities must be clear."],
        "medium",
      ],
    ],
    "order-entry": [
      [
        "The sig 'i tab po bid prn pain' means:",
        "Take one tablet by mouth twice daily as needed for pain",
        ["Inject two tablets weekly", "Take one tablet in each eye at bedtime only", "Apply topically four times daily"],
        "po=by mouth, bid=twice daily, prn=as needed.",
        ["Not an injection sig.", "Eye sigs use ou/od/os language.", "Topical would specify application site."],
        "easy",
      ],
      [
        "A prescription is written for a medication with a serious allergy listed in the profile. The technician should:",
        "Alert the pharmacist before dispensing—do not override silently",
        ["Delete the allergy to clear the alert", "Dispense a full course anyway to avoid delay without notice", "Tell the patient allergies do not matter for oral drugs"],
        "Allergy alerts require pharmacist clinical judgment.",
        ["Deleting allergies falsifies the record.", "Silent overrides risk harm.", "Oral drugs can cause allergies."],
        "easy",
      ],
      [
        "Which is the best practice when the directions are unclear on a new Rx?",
        "Clarify with the pharmacist/prescriber before dispensing",
        ["Guess the most common directions for that drug", "Leave the label blank", "Use another patient's directions"],
        "Ambiguous sigs are a top error source—clarify.",
        ["Guessing causes wrong use.", "Blank labels are unacceptable.", "Wrong-patient directions are dangerous."],
        "easy",
      ],
      [
        "DAW codes communicate:",
        "Dispense-as-written / product selection intents affecting generic substitution",
        ["Only the patient's favorite color", "DEA schedule automatically", "Beyond-use dating for compounds only"],
        "DAW indicates whether substitution is allowed/required for billing/product choice.",
        ["Color is irrelevant.", "Schedules are separate.", "BUD is compounding stability."],
        "medium",
      ],
      [
        "When entering a pediatric liquid dose, a critical safety step is:",
        "Verify weight-based calculations and units (mg vs mL) with the pharmacist as required",
        ["Assume mg and mL are always identical numbers", "Round up aggressively to the next bottle size without checking dose", "Ignore decimal points because children tolerate errors"],
        "Unit mix-ups and decimal errors are major pediatric risks.",
        ["mg ≠ mL.", "Rounding without clinical check is unsafe.", "Children are more vulnerable to dosing errors."],
        "hard",
      ],
    ],
    "dispensing-practice": [
      [
        "The final check before dispensing should verify:",
        "Right patient, drug, strength, quantity, directions, and appropriate packaging/labels",
        ["Only the bag color", "That the cheapest drug was substituted without reviewing alerts", "That pills were touched with bare hands after floor contact"],
        "The five/seven rights style check prevents dispensing errors.",
        ["Bag color is irrelevant.", "Alert review matters.", "Contaminated pills must not be dispensed."],
        "easy",
      ],
      [
        "Which statement about counting trays/spatulas is correct?",
        "Clean them to prevent cross-contamination, especially after allergens like penicillin/sulfa per policy",
        ["Never clean trays because residue improves adherence", "Use the same tray immediately after hazardous powders without decontamination", "Lick the spatula to remove powder"],
        "Tray contamination can cause allergic exposures and mix-ups.",
        ["Residue is a contamination risk.", "Hazardous residue needs proper cleaning.", "Licking is unsanitary."],
        "medium",
      ],
      [
        "Unit-dose packaging in hospitals is intended to:",
        "Provide individually labeled doses to reduce errors and support tracking",
        ["Remove all labeling to speed nurses", "Allow sharing leftover doses between patients freely", "Eliminate the need for pharmacist oversight"],
        "Unit dose improves safety and accountability.",
        ["Labels are essential.", "Sharing doses is improper.", "Pharmacy oversight remains."],
        "easy",
      ],
      [
        "For nonsterile compounding, beyond-use dating should be:",
        "Assigned using USP guidance and formula documentation—not arbitrary distant dates",
        ["Always set to 10 years for creams", "Ignored if the product looks fine", "Copied from an unrelated manufacturer's bottle without assessment"],
        "BUD depends on formulation/water content/storage per USP standards and policies.",
        ["Decade-long BUD is inappropriate.", "Appearance alone is insufficient.", "Wrong BUD sources cause instability risks."],
        "hard",
      ],
      [
        "When reconstituting an antibiotic suspension, the technician should:",
        "Use the correct diluent volume, mix thoroughly, and label with BUD/storage/shake well as required",
        ["Add tap water estimated by eye without measuring", "Omit the shake-well auxiliary label always", "Store all reconstitutions in the freezer unless told otherwise"],
        "Accurate reconstitution and labeling ensure dose accuracy and stability.",
        ["Unmeasured diluent causes wrong concentration.", "Shake-well is often required.", "Freezing can destroy suspensions."],
        "medium",
      ],
    ],
  },

  "danb-ice-readiness-check": {
    "standard-precautions": [
      [
        "When should facial hair be considered regarding respirator fit?",
        "Facial hair that interferes with the seal can prevent proper respirator fit",
        ["Beards always improve N95 seal", "Fit testing is unnecessary if you have a beard", "Only eyewear fit matters for airborne precautions"],
        "A tight face seal is required for respirator effectiveness; hair in the seal zone compromises fit.",
        ["Beards often break the seal.", "Fit testing remains required when respirators are used.", "Airborne precautions need respiratory protection."],
        "medium",
      ],
      [
        "Which practice reduces contamination when handling charts/computers during patient care?",
        "Remove gloves and perform hand hygiene before touching clean office equipment, or use barrier/protocol workflows",
        ["Touch keyboards with bloody gloves routinely", "Place contaminated instruments on the keyboard temporarily", "Lick fingers to turn pages"],
        "Separate dirty clinical tasks from clean administrative surfaces.",
        ["Bloody gloves contaminate electronics.", "Instruments do not belong on keyboards.", "Licking spreads microbes."],
        "easy",
      ],
      [
        "Parenteral exposure (needlestick) risk is reduced by:",
        "Using safety devices, one-handed scoop only if recapping is unavoidable, and immediate sharps disposal",
        ["Passing uncapped needles during four-handed transfer without protocols", "Bending sharps before trash disposal", "Leaving burs/needles on brackets for later"],
        "Engineering controls and safe handling prevent percutaneous injuries.",
        ["Unsafe passes cause sticks.", "Bending/trash disposal is prohibited.", "Loose sharps injure others."],
        "easy",
      ],
      [
        "Which statement about saliva ejectors and backflow is correct?",
        "Patients should not close lips tightly around the ejector tip in a way that can create backflow risk; follow CDC guidance",
        ["Backflow is impossible in all systems", "Encourage patients to seal tightly and suck forcefully on the tip", "Reuse disposable tips between patients after rinsing"],
        "Backflow can occur with certain suction behaviors; tips are single-patient use.",
        ["Backflow risk is recognized.", "Forceful sealing can increase risk.", "Disposable tips are not shared."],
        "hard",
      ],
      [
        "Eye protection should be worn:",
        "For procedures with splash/spatter risk and cleaned/disinfected between patients per protocol",
        ["Only for whitening shade selection", "Never over prescription glasses even if gaps exist", "Shared face shields without cleaning between users"],
        "Splash risk defines eyewear use; clean between patients; prescription lenses alone may not seal.",
        ["Many procedures create spatter beyond cosmetics.", "Gaps leave exposure routes.", "Shared unclean shields transmit microbes."],
        "medium",
      ],
    ],
    "instrument-processing": [
      [
        "Dental handpieces that are heat-tolerant should be:",
        "Cleaned and heat-sterilized between patients per CDC",
        ["Wiped only with alcohol and reused on the next patient as sufficient for all handpieces", "Never sterilized because heat always destroys all handpieces without exception", "Shared without barrier or sterilization if the patient is a family member"],
        "CDC expects sterilization of dental handpieces between patients when heat-tolerant.",
        ["Wipe-only is insufficient for handpieces.", "Many handpieces are designed for sterilization per IFU.", "Family status does not change IPC rules."],
        "easy",
      ],
      [
        "Cold sterile (high-level disinfectant) soak solutions:",
        "Must be used with correct concentration, contact time, and monitoring—and do not replace heat sterilization for heat-tolerant critical items when sterilization is required",
        ["Sterilize any instrument in 10 seconds regardless of label", "Can be diluted by eye each morning", "Are safe to use as hand sanitizer"],
        "Follow IFU for HLD; prefer heat sterilization for heat-tolerant critical/semicritical items.",
        ["Contact times are longer/specific.", "Concentration must be accurate.", "HLD chemicals are not hand rubs."],
        "hard",
      ],
      [
        "Instrument washers/disinfectors, when used, still require:",
        "Correct loading, detergent/IFU compliance, and verification that cleaning was effective before sterilization packaging",
        ["No inspection because machines never fail", "Skipping packaging after the washer because washer = sterilizer", "Placing cardboard waste inside the chamber for cushioning"],
        "Mechanical cleaning aids processing but inspection/packaging/sterilization remain.",
        ["Failures/soil can occur.", "Washers are not sterilizers.", "Foreign materials disrupt cycles."],
        "medium",
      ],
      [
        "Which packaging material practice is correct?",
        "Use FDA-cleared wraps/pouches suitable for the sterilizer type and seal pouches correctly without writing puncture marks over the item area improperly",
        ["Reuse single-use pouches after opening", "Close pouches with safety pins through the paper", "Wrap with cloth napkins from the break room"],
        "Validated packaging systems maintain sterility barriers.",
        ["Single-use pouches are not reused.", "Pins perforate barriers.", "Nonvalidated textiles are improper."],
        "easy",
      ],
      [
        "If a sterile pouch is dropped on a dirty floor, you should:",
        "Consider it contaminated and reprocess (do not use)",
        ["Wipe the outside and use it for surgery", "Blow on it and open to the field", "Place it in the warmer and use if dry"],
        "Dropped packages are compromised—reprocess.",
        ["External wipe does not restore sterility assurance.", "Blowing contaminates.", "Warming does not fix contamination."],
        "easy",
      ],
    ],
    environmental: [
      [
        "Impression materials contaminated with saliva/blood should be:",
        "Rinsed/cleaned and disinfected per material IFU before lab transport",
        ["Sent to the lab dripping without disinfection", "Heat-sterilized in an autoclave for all alginate types always", "Soaked in undiluted bleach for days regardless of IFU"],
        "Disinfect impressions without damaging them; follow manufacturer guidance.",
        ["Labs need disinfected impressions.", "Not all materials tolerate autoclave.", "Harsh soaks can ruin impressions and are unsafe."],
        "medium",
      ],
      [
        "Which is an engineering control example in dentistry?",
        "Sharps containers and devices with engineered sharps injury protection",
        ["Reminding staff verbally only", "Hoping patients disclose infections", "Posting a motivational poster only"],
        "Engineering controls remove hazards at the source; work-practice and admin controls differ.",
        ["Verbal reminders are admin/work-practice supports.", "Disclosure is unreliable alone.", "Posters are not engineering controls."],
        "easy",
      ],
      [
        "Vacuum lines/traps in dental units should be maintained because:",
        "Biofilm and debris accumulate and can affect suction performance and contamination control",
        ["They are sterile for life after installation", "Maintenance voids infection control forever", "Traps never need cleaning"],
        "Regular maintenance/cleaning chemicals per IFU support function and hygiene.",
        ["Not sterile for life.", "Maintenance supports IPC.", "Traps need service."],
        "medium",
      ],
      [
        "When using surface barriers on difficult-to-clean controls, you should still:",
        "Clean and disinfect the surface at the end of the day or when barrier fails/contamination suspected",
        ["Never clean under barriers at any time", "Reuse torn barriers after taping", "Place barriers over visible blood without cleaning first"],
        "Barriers reduce but do not eliminate the need for surface cleaning protocols.",
        ["Underlying surfaces need periodic cleaning.", "Torn barriers fail.", "Clean soil before disinfecting/re-barrier."],
        "hard",
      ],
      [
        "Which practice is appropriate for digital radiography sensors?",
        "Use plastic barriers and clean/disinfect the sensor per manufacturer instructions between patients",
        ["Autoclave all sensors regardless of IFU", "Use bare sensors in consecutive mouths without barriers", "Soak sensors in glutaraldehyde overnight against IFU"],
        "Sensors are often heat-sensitive—barriers + intermediate disinfection per IFU.",
        ["Many sensors cannot be autoclaved.", "Bare multi-patient use is improper.", "Harsh soaks can destroy sensors."],
        "medium",
      ],
    ],
    occupational: [
      [
        "Employers must provide PPE that is:",
        "Appropriate, accessible, and cleaned/laundered/disposed per hazard—at no cost to employees for BBP PPE",
        ["Purchased only by employees as a condition of hiring always", "Optional if employees sign a waiver to work barehanded with blood", "Fashion-matched even if it lacks protective ratings"],
        "OSHA requires employer-provided PPE for occupational exposures.",
        ["Employer provides BBP PPE.", "Waivers do not void BBP duties.", "Protection rating matters more than fashion."],
        "medium",
      ],
      [
        "Which is an example of an administrative control?",
        "Policies for early patient triage of airborne illness and scheduling to reduce exposures",
        ["A sharps container on the wall", "One-handed scoop technique", "Utility gloves material thickness"],
        "Administrative controls are policies/procedures; engineering and work-practice differ.",
        ["Container = engineering.", "Scoop = work practice.", "Glove material = PPE."],
        "hard",
      ],
      [
        "Mercury hygiene for amalgam includes:",
        "Using precapsulated amalgam, appropriate traps/separators as required, and avoiding skin contact/heating scrap improperly",
        ["Heating scrap amalgam with an open flame in the operatory for fun", "Vacuuming spilled mercury with a household vacuum", "Storing scrap in an open cup on the windowsill"],
        "Mercury vapor control and proper scrap storage protect staff/environment.",
        ["Heating increases vapor.", "Household vacuums aerosolize mercury.", "Closed labeled containers are required."],
        "hard",
      ],
      [
        "Which record is typically associated with OSHA BBP compliance?",
        "Employee training records and exposure incident documentation (with confidentiality protections)",
        ["Patient whitening shade preferences only", "Only the office Spotify playlist", "Competitor fee schedules"],
        "Training and exposure records support compliance and follow-up care.",
        ["Shade prefs are clinical cosmetics.", "Playlists are unrelated.", "Fees are business data."],
        "easy",
      ],
      [
        "If a sterilizer is under repair after failures, the practice should:",
        "Use alternative sterilized instrument sources/processes and not deliver critical care with unsterile instruments",
        ["Continue surgery with unprocessed instruments", "Wipe surgical elevators with alcohol only and proceed as sterile", "Ask patients to bring instruments from home"],
        "Patient safety requires sterile critical instruments—delay/refer if necessary.",
        ["Unsterile surgery is unacceptable.", "Alcohol wipe ≠ sterilization for critical items.", "Home instruments are not a control plan."],
        "medium",
      ],
    ],
  },

  "nremt-paramedic-readiness-check": {
    "airway-critical": [
      [
        "RSI (rapid sequence intubation) preparation should always include:",
        "Equipment readiness for failed airway (BVM, suction, extraglottic/surgical backup) and confirmation plan",
        ["No suction because it slows the attempt", "Only one laryngoscope blade with no backup", "Skipping preoxygenation to save time"],
        "Airway attempts need oxygenation strategy and failure pathway ready.",
        ["Suction is essential.", "Backup devices/blades matter.", "Preoxygenation extends safe apnea time."],
        "hard",
      ],
      [
        "Waveform capnography after intubation primarily helps confirm:",
        "Tracheal placement and ongoing ventilation effectiveness/CO2 elimination",
        ["Exact hemoglobin level", "Blood type", "Intracranial pressure numerically"],
        "Persistent ETCO2 waveform supports tracheal tube placement and monitors ventilation.",
        ["Hb needs labs/oximetry context differently.", "Blood type is lab testing.", "ICP is not directly ETCO2."],
        "medium",
      ],
      [
        "A patient with status asthmaticus may benefit from which ventilation concept?",
        "Allowing adequate expiratory time and avoiding excessive rates that cause auto-PEEP",
        ["Hyperventilating at 40 breaths/min continuously", "Withholding oxygen to stimulate breathing", "Forcing inspiration only without expiration"],
        "Obstructive disease needs time to exhale; stacked breaths cause hypotension/pneumothorax risk.",
        ["High rates worsen air trapping.", "Oxygen is needed for hypoxia.", "Expiration must occur."],
        "hard",
      ],
      [
        "Needle cricothyrotomy/surgical airway is considered when:",
        "You cannot oxygenate/ventilate and cannot intubate (CICO) per protocol",
        ["The patient has a mild sore throat only", "SpO2 is 98% on room air with clear speech", "As a first step before basic airway opening"],
        "Front-of-neck access is a last-resort failed airway intervention.",
        ["Mild URI is not an indication.", "Adequate breathing needs no surgical airway.", "Basic maneuvers come first."],
        "medium",
      ],
      [
        "Positive-pressure ventilation in a hypotensive patient can worsen BP because it:",
        "Increases intrathoracic pressure and may reduce venous return",
        ["Always increases preload dramatically", "Removes all catecholamines from blood", "Converts asystole to sinus rhythm automatically"],
        "Excessive ventilation/PPv can drop preload—use appropriate rates/volumes and treat shock.",
        ["It often decreases preload.", "It does not strip catecholamines that way.", "Ventilation alone does not pace asystole."],
        "hard",
      ],
    ],
    cardiology: [
      [
        "For stable narrow-complex SVT (per ACLS concepts), initial medication often considered is:",
        "Adenosine (when vagal maneuvers fail/are inappropriate), per current protocol",
        ["Immediate unsynchronized defibrillation at max energy as first step if stable with a pulse", "Oral digoxin crushed in the field always", "High-dose insulin as first-line SVT drug"],
        "Stable SVT algorithms use vagal maneuvers/adenosine; unstable patients may need synchronized cardioversion.",
        ["Unsynchronized defib is for VF/pulseless VT.", "Oral digoxin is not typical field SVT first-line.", "Insulin is for other toxicology/metabolic care."],
        "medium",
      ],
      [
        "Synchronized cardioversion is preferred over unsynchronized defibrillation when:",
        "The patient has a pulse with an unstable tachyarrhythmia requiring shock",
        ["The monitor shows fine VF without pulse", "Asystole is present", "The patient is awake and stable with sinus rhythm"],
        "Synchronization avoids T-wave shock in organized rhythms with pulses; VF needs defib.",
        ["Pulseless VF → defibrillate.", "Asystole is not a shockable rhythm.", "Stable sinus needs no cardioversion."],
        "easy",
      ],
      [
        "STEMI recognition on 12-lead should prompt:",
        "Rapid transport/activation of PCI-capable pathways and ACS care bundle per protocol",
        ["Discharge home with advice to rest", "Waiting for outpatient stress testing next month before EMS care", "Giving all patients oral antibiotics"],
        "Time-to-reperfusion matters; prenotify STEMI systems of care.",
        ["Home discharge is inappropriate.", "Delay harms myocardium.", "Antibiotics are not STEMI therapy."],
        "easy",
      ],
      [
        "Hyperkalemia ECG changes may include:",
        "Peaked T waves and widened QRS progressing toward sine-wave/VT risk",
        ["Delta waves pathognomonic only for hypokalemia", "U waves as the only possible finding always", "Normal ECG guaranteed until cardiac arrest"],
        "Rising K+ alters repolarization/conduction—treat per protocol (calcium, shifts, etc.).",
        ["Delta waves relate to WPW patterns.", "U waves more classic hypokalemia.", "ECG can change before arrest."],
        "hard",
      ],
      [
        "ROSC care priorities include:",
        "Support ABCs, optimize oxygenation/ventilation carefully, treat hypotension, and consider targeted temperature/PCI indications per protocol",
        ["Stopping all monitoring because the pulse returned", "Hyperventilating to ETCO2 of 10 mmHg routinely", "Giving unrestricted oral fluids immediately in comatose patients"],
        "Post-arrest care prevents secondary brain/heart injury.",
        ["Monitoring continues.", "Hyperventilation is harmful.", "Airway protection precludes oral intake."],
        "medium",
      ],
    ],
    "trauma-medical": [
      [
        "Tranexamic acid (TXA) in trauma (when used per protocol) is intended to:",
        "Reduce bleeding by inhibiting fibrinolysis in selected hemorrhagic patients within time windows",
        ["Reverse warfarin like PCC/vitamin K", "Replace blood typing", "Treat anaphylaxis as epinephrine does"],
        "TXA is antifibrinolytic adjunct—not a warfarin reversal agent or epinephrine substitute.",
        ["Warfarin reversal differs.", "Typing/crossmatch still needed for transfusion.", "Anaphylaxis needs epinephrine."],
        "medium",
      ],
      [
        "A burn patient with suspected inhalation injury may show:",
        "Hoarseness, stridor, facial burns, or carbonaceous sputum—airway may worsen",
        ["Only ankle edema without respiratory signs", "Guaranteed normal airway for 24 hours", "Isolated urinary retention as the hallmark"],
        "Early airway assessment/management is critical because edema progresses.",
        ["Not an ankle-edema hallmark.", "Airways can deteriorate.", "Urinary retention is not the classic sign."],
        "medium",
      ],
      [
        "For suspected tension pneumothorax with hemodynamic collapse, paramedic management may include:",
        "Needle thoracostomy/decompression in the correct site per protocol plus support ABCs",
        ["High-dose furosemide as first-line", "Oral antibiotics only", "Trendelenburg and observation without airway/oxygen support"],
        "Tension physiology needs decompression and ventilation/oxygenation support.",
        ["Diuretics are for fluid overload, not tension PTX.", "Antibiotics are not immediate therapy.", "Shock needs active intervention."],
        "hard",
      ],
      [
        "Sepsis alert criteria often include:",
        "Suspected infection plus signs of hypoperfusion/organ dysfunction (e.g., hypotension, altered mentation, elevated lactate when available)",
        ["Isolated well-controlled seasonal allergies", "Stable vitals with minor bruise only", "Hyperglycemia alone without infection concern always"],
        "Early recognition and fluids/pressors/antibiotics (hospital) improve outcomes—prenotify when protocols exist.",
        ["Allergies ≠ sepsis.", "Minor trauma alone is not sepsis.", "Glucose alone is nonspecific."],
        "easy",
      ],
      [
        "Tricyclic antidepressant overdose toxicity may feature:",
        "Wide-complex dysrhythmias and seizures—sodium bicarbonate per protocol for wide QRS/toxicity",
        ["Pathognomonic opioid pinpoint pupils reversed only by flumazenil", "Isolated hypoglycemia treated only with glucagon always", "Mandatory calcium channel blocker infusion as first antidote"],
        "TCA sodium-channel blockade → wide QRS; bicarb is a key therapy; flumazenil is for benzos (caution).",
        ["Opioid toxidrome differs; flumazenil is not TCA antidote.", "TCA tox is not primarily a glucagon hypoglycemia pathway.", "CCB infusion is not the TCA antidote."],
        "hard",
      ],
    ],
    "ops-special": [
      [
        "When operating on an MCI with START triage, a walking patient is generally tagged:",
        "Minor (green) unless later reassessment changes priority",
        ["Immediate red automatically", "Expectant black automatically", "Dead without assessment"],
        "Ambulatory patients are initially minor; re-triage as needed.",
        ["Not automatically immediate.", "Not automatically expectant.", "Walking ≠ dead."],
        "easy",
      ],
      [
        "Neonatal resuscitation prioritizes:",
        "Warming, airway positioning/clearing, and effective ventilation before extensive medication focus",
        ["Immediate adult-dose epinephrine IO as first step always", "Oral feeding before drying", "Ignoring temperature"],
        "Most newborns respond to airway/ventilation and thermal care; meds follow algorithms.",
        ["Meds come after ventilation steps when indicated.", "Feeding is not NRP first step.", "Hypothermia worsens outcomes."],
        "medium",
      ],
      [
        "A pregnant patient of ~28 weeks in cardiac arrest should receive:",
        "High-quality CPR with left uterine displacement and prioritization of maternal resuscitation/airway",
        ["No chest compressions to protect the fetus", "Only transport without CPR if arrest continues", "Abdominal thrusts instead of compressions"],
        "Maternal circulation is fetal circulation—CPR with uterine displacement is key; peri-mortem cesarean is a hospital consideration.",
        ["Withholding CPR harms both.", "CPR continues during care/transport decisions.", "Thrusts are not a substitute for CPR."],
        "hard",
      ],
      [
        "Landing zone safety for helicopter EMS includes:",
        "Securing hazards, marking a clear zone, and protecting eyes/ears from rotor wash—approach only when signaled",
        ["Running under the tail rotor to save time", "Approaching from the uphill side of a slope near blades", "Carrying tall IV poles upright into the rotor disk"],
        "Rotor hazards kill—controlled approach after crew signals.",
        ["Tail rotor is deadly.", "Uphill approach brings you into blades.", "Tall objects strike rotors."],
        "easy",
      ],
      [
        "Which statement about documentation in EMS is correct?",
        "The PCR should be accurate, timely, and complete enough to support continuity of care and legal review",
        ["Alter vitals later to match expected norms", "Omit refusals to avoid paperwork", "Copy another patient's narrative to save time"],
        "Truthful documentation protects patients and providers.",
        ["Falsifying vitals is fraud.", "Refusals must be documented.", "Wrong-patient copy is dangerous."],
        "easy",
      ],
    ],
  },
};
