/** MBLEx — 40 curated MCQs */
export const topics = {
  "anatomy-physiology": [
    [
      "Which tissue type contracts to produce movement?",
      "Muscle tissue",
      ["Epithelial tissue only", "Nervous tissue only as the contractile fiber", "Blood plasma only"],
      "Muscle tissue (skeletal, cardiac, smooth) specializes in contraction; nerve tissue conducts impulses.",
      [
        "Epithelium covers/lines/secretes.",
        "Nervous tissue signals contraction.",
        "Plasma is fluid matrix.",
      ],
      "easy",
    ],
    [
      "The sagittal plane divides the body into:",
      "Left and right portions",
      ["Superior and inferior portions only", "Anterior and posterior portions only", "Oblique skin layers only"],
      "Sagittal = left/right; frontal/coronal = anterior/posterior; transverse = superior/inferior.",
      [
        "That is transverse.",
        "That is frontal/coronal.",
        "Not a cardinal plane definition.",
      ],
      "easy",
    ],
    [
      "Synovial joints are characterized by:",
      "A joint cavity with synovial fluid and articular cartilage",
      ["No movement possible (synarthrosis always)", "Being only sutures of the skull", "Lacking a capsule always"],
      "Diathroses/synovial joints are freely movable with cavity/fluid; sutures are fibrous synarthroses.",
      [
        "Many synovial joints move freely.",
        "Skull sutures are fibrous.",
        "Synovial joints have capsules.",
      ],
      "medium",
    ],
    [
      "The primary pacemaker of the heart is the:",
      "Sinoatrial (SA) node",
      ["AV bundle only without SA role", "Purkinje fibers as the normal primary pacemaker", "Tricuspid valve"],
      "SA node initiates sinus rhythm; AV node delays; Purkinje fibers distribute ventricular depolarization.",
      [
        "AV node is secondary/backup.",
        "Purkinje are terminal conduction.",
        "Valves aren't pacemakers.",
      ],
      "easy",
    ],
    [
      "Which organelle is the primary site of ATP production via aerobic respiration?",
      "Mitochondria",
      ["Ribosomes only", "Golgi apparatus only", "Lysosomes only"],
      "Mitochondria perform oxidative phosphorylation; ribosomes make protein; Golgi packages; lysosomes digest.",
      [
        "Ribosomes: protein synthesis.",
        "Golgi: packaging/modification.",
        "Lysosomes: hydrolysis.",
      ],
      "easy",
    ],
    [
      "The dermis is primarily composed of:",
      "Dense irregular connective tissue with collagen and elastin",
      ["Simple squamous epithelium only", "Compact bone", "Myelin sheaths"],
      "Skin: epidermis (epithelium) over dermis (CT); hypodermis is mostly adipose.",
      [
        "Epidermis is epithelial.",
        "Bone is skeletal tissue.",
        "Myelin is nervous insulation.",
      ],
      "medium",
    ],
    [
      "Insulin is produced by the:",
      "Pancreatic beta cells",
      ["Adrenal medulla exclusively", "Posterior pituitary exclusively", "Thyroid C cells exclusively"],
      "Beta cells secrete insulin; alpha cells glucagon; adrenal medulla catecholamines; posterior pituitary ADH/oxytocin.",
      [
        "Medulla: epi/norepi.",
        "Posterior pituitary: ADH/oxytocin.",
        "C cells: calcitonin.",
      ],
      "medium",
    ],
    [
      "A motor unit consists of:",
      "A motor neuron and the muscle fibers it innervates",
      ["Only a sensory receptor", "A ligament and a bursa", "Two bones and a suture"],
      "Motor unit recruitment grades force; small units for fine control.",
      [
        "Sensory units differ.",
        "Ligament/bursa are passive structures.",
        "Sutures are joints.",
      ],
      "easy",
    ],
    [
      "Lymphatic vessels help:",
      "Return interstitial fluid to the bloodstream and support immune function",
      ["Pump arterial blood from the left ventricle", "Produce bile", "Store urine"],
      "Lymph capillaries collect fluid; lymph nodes filter; bile is hepatic; urine is urinary.",
      [
        "Arterial pumping is heart/vessels.",
        "Bile from liver.",
        "Urine in bladder.",
      ],
      "easy",
    ],
    [
      "Homeostasis refers to:",
      "Maintenance of a relatively stable internal environment",
      ["Only disease processes", "Complete absence of feedback", "Growth of a tumor exclusively"],
      "Negative feedback commonly stabilizes variables like temperature and blood glucose.",
      [
        "Homeostasis opposes disease instability.",
        "Feedback is central.",
        "Tumors disrupt homeostasis.",
      ],
      "easy",
    ]
  ],
  "kinesiology": [
    [
      "An agonist muscle is the:",
      "Prime mover primarily responsible for a given action",
      ["Muscle that only stabilizes without ever moving", "Bone landmark only", "Sensory nerve exclusively"],
      "Agonist produces movement; antagonist opposes; synergist assists; stabilizer fixates.",
      [
        "Stabilizers fixate.",
        "Landmarks are bony.",
        "Nerves innervate.",
      ],
      "easy",
    ],
    [
      "Isometric contraction means:",
      "Muscle tension increases without changing muscle length",
      ["Muscle shortens with constant tension only (concentric definition)", "Muscle lengthens under tension only (eccentric)", "No motor units activate"],
      "Isometric = same length; concentric shortens; eccentric lengthens under load.",
      [
        "That is concentric.",
        "That is eccentric.",
        "Motor units activate to produce tension.",
      ],
      "easy",
    ],
    [
      "Flexion generally:",
      "Decreases the angle between bones at a joint",
      ["Increases the angle (extension)", "Moves a limb away from midline (abduction)", "Turns the palm posteriorly (pronation specific)"],
      "Flexion/extension, abduction/adduction, rotation, and circumduction are fundamental actions.",
      [
        "Extension increases angle.",
        "Abduction is away from midline.",
        "Pronation is forearm/foot action.",
      ],
      "easy",
    ],
    [
      "Lordosis refers to:",
      "An exaggerated anterior curvature of the lumbar (or cervical) spine",
      ["Lateral curvature (scoliosis)", "Exaggerated thoracic posterior curve only (kyphosis)", "Fusion of sutures"],
      "Hyperlordosis increases lumbar curve; kyphosis increases thoracic convexity posteriorly; scoliosis is lateral.",
      [
        "Scoliosis is lateral.",
        "Kyphosis is thoracic posterior exaggeration.",
        "Suture fusion is cranial.",
      ],
      "medium",
    ],
    [
      "Carpal tunnel syndrome involves compression of the:",
      "Median nerve at the wrist",
      ["Sciatic nerve at the ankle always", "Optic nerve", "Vagus nerve in the stomach only"],
      "Median nerve compression under flexor retinaculum causes thumb/index/middle paresthesias.",
      [
        "Sciatic is lower limb.",
        "Optic is vision.",
        "Vagus is autonomic cranial.",
      ],
      "medium",
    ],
    [
      "Adhesive capsulitis (frozen shoulder) is characterized by:",
      "Progressive glenohumeral stiffness and pain with capsular restriction",
      ["Only ankle inversion sprain", "Only plantar fasciitis", "Hypermobile shoulder always without stiffness"],
      "Frozen shoulder limits ROM in a capsular pattern; massage approaches are cautious/indicated by stage.",
      [
        "Ankle sprain differs.",
        "Plantar fasciitis is foot.",
        "Frozen shoulder reduces mobility.",
      ],
      "medium",
    ],
    [
      "Tendinitis differs from tendinosis in that tendinitis implies:",
      "Inflammation of a tendon (acute inflammatory concept), whereas tendinosis is degenerative",
      ["Complete bone fracture", "Only nerve transection", "Always identical meanings with no distinction taught"],
      "Modern language often uses tendinopathy; exam content may distinguish inflammatory vs degenerative tendon pathology.",
      [
        "Fracture is bone.",
        "Nerve cut is neurotmesis concepts.",
        "Distinction is taught in many outlines.",
      ],
      "hard",
    ],
    [
      "The iliotibial (IT) band can contribute to lateral knee pain associated with:",
      "IT band friction syndrome near the lateral femoral epicondyle",
      ["Medial plantar nerve entrapment only", "Otitis media", "Appendicitis exclusively"],
      "Repetitive flexion/extension can irritate tissues under the IT band at the lateral knee.",
      [
        "Different nerve/site.",
        "Ear infection.",
        "Abdominal surgical emergency.",
      ],
      "medium",
    ],
    [
      "A strain involves injury to:",
      "Muscle or tendon",
      ["Ligament only (sprain)", "Bone only (fracture)", "Skin only (abrasion)"],
      "Sprain = ligament; strain = musculotendinous unit—classic kinesiology distinction.",
      [
        "Sprain is ligament.",
        "Fracture is bone.",
        "Abrasion is skin.",
      ],
      "easy",
    ],
    [
      "Proprioceptors contribute to:",
      "Sense of body position and movement",
      ["Only taste", "Only color vision", "Hormone secretion by the thyroid exclusively"],
      "Muscle spindles and Golgi tendon organs provide proprioceptive feedback for coordination.",
      [
        "Taste is gustation.",
        "Vision photoreceptors.",
        "Thyroid is endocrine.",
      ],
      "easy",
    ]
  ],
  "assessment-treatment": [
    [
      "Informed consent for massage therapy should include:",
      "Nature of treatment, benefits/risks, alternatives, and voluntary agreement",
      ["No explanation if the client smiles", "Pressure to continue when the client withdraws consent", "Guarantees of curing disease"],
      "Consent is ongoing; clients may modify or withdraw consent at any time.",
      [
        "Explanation is still required.",
        "Withdrawal must be honored.",
        "No cure guarantees for MT.",
      ],
      "easy",
    ],
    [
      "A relative contraindication means:",
      "Treatment may proceed with modification/caution or physician clearance depending on presentation",
      ["Absolute ban with no exceptions ever in all cases by definition of 'relative'", "No assessment is needed", "Only insurance billing codes matter"],
      "Absolute contraindications prohibit treatment; relative require adaptation.",
      [
        "Absolute = do not treat that area/condition as defined.",
        "Assessment is essential.",
        "Clinical safety > billing.",
      ],
      "medium",
    ],
    [
      "SOAP documentation: the 'A' stands for:",
      "Assessment (therapist's clinical impression)",
      ["Anatomy only", "Appointment time only", "Advertising plan"],
      "S = subjective, O = objective, A = assessment, P = plan.",
      [
        "Anatomy may appear in notes but A = assessment.",
        "Time is scheduling.",
        "Ads aren't SOAP.",
      ],
      "easy",
    ],
    [
      "Endangerment sites are areas where:",
      "Underlying structures (nerves, vessels, viscera) warrant caution or avoidance of deep pressure",
      ["Only aromatherapy is allowed", "Bone cannot exist", "Clients prefer deepest pressure always"],
      "Examples include anterior neck, axilla, abdomen—use caution appropriate to training/laws.",
      [
        "Endangerment is about structures, not aromas.",
        "Bones exist throughout.",
        "Deep pressure may be contraindicated.",
      ],
      "easy",
    ],
    [
      "Effleurage strokes are typically:",
      "Gliding strokes used to apply lubricant and warm tissue",
      ["Percussive tapotement only", "Joint mobilization high-velocity thrusts only", "Needling"],
      "Swedish categories: effleurage, petrissage, friction, tapotement, vibration.",
      [
        "Tapotement is percussion.",
        "HVLA is chiropractic/osteopathic scope issues.",
        "Needling is not classic Swedish MT.",
      ],
      "easy",
    ],
    [
      "Deep transverse friction is often used to:",
      "Mobilize scar tissue/adhesions in tendons or ligaments with caution",
      ["Replace all cardiovascular exercise prescriptions by MTs illegally", "Diagnose cancer", "Perform spinal adjustments"],
      "Cyriax-type friction is specific and can be uncomfortable; screen contraindications.",
      [
        "Exercise prescription limits by scope.",
        "MT does not diagnose cancer.",
        "Adjustments outside MT scope generally.",
      ],
      "medium",
    ],
    [
      "If a client reports sudden unexplained weight loss and night pain, the therapist should:",
      "Refer to a physician; do not treat as simple musculoskeletal without clearance when red flags present",
      ["Ignore red flags and use deeper pressure", "Diagnose malignancy definitively", "Increase session length to three hours immediately"],
      "Red flags warrant medical referral rather than aggressive massage assumptions.",
      [
        "Ignoring red flags is unsafe.",
        "Diagnosis is physician role.",
        "Longer sessions don't address red flags.",
      ],
      "hard",
    ],
    [
      "Local contraindication for a region with acute DVT signs means:",
      "Avoid massage to the affected limb and seek urgent medical evaluation",
      ["Perform deep stripping on the calf vigorously", "Apply ice massage aggressively over the clot suspicion without referral", "Ignore swelling and heat"],
      "Suspected DVT is an absolute local/systemic emergency referral situation—no distal massage that could embolize.",
      [
        "Deep work is dangerous.",
        "Ice without referral delays care.",
        "Classic DVT signs need ER/MD.",
      ],
      "hard",
    ],
    [
      "Postural assessment commonly observes:",
      "Alignment of landmarks from multiple views for asymmetries",
      ["Only blood lab panels", "Only dental occlusion charts", "Only ECG waveforms"],
      "Plumb line landmarks help identify imbalances informing treatment planning.",
      [
        "Labs are medical.",
        "Dental is dentistry.",
        "ECG is cardiac.",
      ],
      "easy",
    ],
    [
      "Stretching should be avoided or modified when:",
      "Acute inflammation, instability, or client pain responses indicate tissue protection needs",
      ["The client is relaxed with full clearance and healthy tissues always as the only time to avoid", "Lubricant is hypoallergenic", "Music is playing"],
      "Respect pain, healing stages, and joint stability; ballistic stretching can be risky.",
      [
        "Healthy cleared clients may stretch appropriately.",
        "Lubricant type ≠ stretch contraindication alone.",
        "Music irrelevant.",
      ],
      "medium",
    ]
  ],
  "ethics-business": [
    [
      "Client confidentiality requires that therapists:",
      "Protect private health information and disclose only with consent or legal requirement",
      ["Share stories with names at parties", "Post client conditions on social media", "Sell client lists without consent"],
      "Ethics and HIPAA-like privacy expectations apply to health information in practice settings.",
      [
        "Named gossip breaches confidentiality.",
        "Social posts breach privacy.",
        "Selling lists is unethical/illegal often.",
      ],
      "easy",
    ],
    [
      "Dual relationships become unethical when they:",
      "Impair professional judgment or risk exploitation of the client",
      ["Never matter in any circumstance", "Are required by law always", "Only involve written SOAP notes"],
      "Maintain boundaries; friendships/business deals with clients can create conflicts.",
      [
        "Boundaries always matter.",
        "Not legally required dual roles.",
        "SOAP is documentation, not dual relationship.",
      ],
      "medium",
    ],
    [
      "Sexual misconduct in massage therapy includes:",
      "Any sexualized behavior or contact with a client; it is prohibited",
      ["Optional if both joke about it", "Allowed after one session", "Required for deep tissue"],
      "Zero tolerance: sexual activity with clients violates ethics/law; draping and professionalism protect safety.",
      [
        "Jokes don't authorize misconduct.",
        "Timing doesn't authorize.",
        "Modality never requires sexual contact.",
      ],
      "easy",
    ],
    [
      "Scope of practice means therapists should:",
      "Perform only techniques/services allowed by education and state law",
      ["Prescribe controlled drugs", "Adjust spines as chiropractors without licensure", "Interpret radiographic diagnoses definitively"],
      "Stay within MT scope; refer medical issues out.",
      [
        "Prescribing needs medical license.",
        "Chiropractic requires that license.",
        "Radiology diagnosis is physician/radiologist.",
      ],
      "easy",
    ],
    [
      "Informed refusal means:",
      "A client may decline any part of treatment without coercion",
      ["The therapist may force a technique for the client's 'own good'", "Consent cannot be withdrawn mid-session", "Refusal voids all confidentiality"],
      "Autonomy includes refusing techniques, areas, or sessions.",
      [
        "Force is unethical.",
        "Consent is ongoing/withdrawable.",
        "Privacy remains.",
      ],
      "easy",
    ],
    [
      "Accurate financial records and receipts help with:",
      "Taxes, legal compliance, and transparent client business relationships",
      ["Hiding cash income illegally", "Avoiding any appointment records", "Guaranteeing clinical outcomes"],
      "Business ethics include honest billing and recordkeeping.",
      [
        "Tax evasion is illegal.",
        "Records are needed.",
        "Outcomes aren't guaranteed by receipts.",
      ],
      "medium",
    ],
    [
      "When advertising credentials, a therapist should:",
      "Use only titles/credentials legally earned and not imply medical licensure falsely",
      ["Claim to be an MD without a degree", "Guarantee curing cancer with massage", "Use another therapist's license number"],
      "Truthful advertising is an ethics/legal requirement.",
      [
        "False MD claim is fraud.",
        "Cure claims are illegal/unethical.",
        "License misuse is illegal.",
      ],
      "easy",
    ],
    [
      "Power differential in the therapeutic relationship means:",
      "The therapist holds greater power/influence and must not exploit the client",
      ["Clients always hold all clinical power with no vulnerability", "Power is irrelevant ethically", "Only landlords have power differentials"],
      "Clients are vulnerable when undressed/in pain; maintain professional boundaries.",
      [
        "Clients are vulnerable.",
        "Ethics centers on this.",
        "Therapy has its own power dynamics.",
      ],
      "medium",
    ],
    [
      "A conflict of interest example is:",
      "Selling expensive unnecessary supplements for personal profit under pressure tactics",
      ["Referring to a physician for red flags", "Keeping SOAP notes secure", "Washing linens between clients"],
      "Exploitation for financial gain violates ethics; referrals and hygiene are proper.",
      [
        "Appropriate referral is ethical.",
        "Security is ethical.",
        "Hygiene is standard.",
      ],
      "medium",
    ],
    [
      "Mandatory reporting duties (where applicable by law) may require reporting:",
      "Suspected child/elder abuse according to state statutes",
      ["Client preference for lavender oil", "Normal delayed onset muscle soreness only", "Favorite sports team"],
      "Know state-mandated reporter obligations; they override ordinary confidentiality in specified cases.",
      [
        "Oil preference isn't reportable.",
        "DOMS isn't abuse.",
        "Sports irrelevant.",
      ],
      "hard",
    ]
  ],
};
