/** NBSTSA CST — 40 curated MCQs */
export const topics = {
  "perioperative": [
    [
      "The surgical technologist in the scrub role is primarily responsible for:",
      "Maintaining the sterile field and anticipating instrument needs",
      ["Administering anesthesia drugs", "Obtaining informed consent", "Signing the operative consent as the surgeon"],
      "CSTs manage sterile technique and instrumentation under surgeon direction; consent/anesthesia are others' roles.",
      [
        "Anesthesia providers give anesthesia.",
        "Surgeon/provider obtains consent.",
        "Surgeon signs consents appropriately.",
      ],
      "easy",
    ],
    [
      "Timeout (Universal Protocol) verifies:",
      "Correct patient, site/side, and procedure before incision",
      ["Only the preference card vendor", "Lunch orders", "Staff parking assignments"],
      "Joint Commission Universal Protocol prevents wrong-site surgery.",
      [
        "Cards help setup but aren't timeout.",
        "Lunch irrelevant.",
        "Parking irrelevant.",
      ],
      "easy",
    ],
    [
      "Preoperative skin prep aims to:",
      "Reduce transient/resident microbes at the incision site",
      ["Sterilize skin to SAL 10^-6 permanently", "Replace hand antisepsis for the scrubbed team", "Remove all hair by shaving against the grain always as required"],
      "Skin cannot be sterilized; antiseptics reduce flora; clippers preferred over razors when hair removal needed.",
      [
        "Skin not sterile permanently.",
        "Team still scrubs.",
        "Avoid traumatic shaving.",
      ],
      "medium",
    ],
    [
      "Trendelenburg position places the patient:",
      "Head down, feet elevated",
      ["Sitting fully upright only", "Prone jackknife only", "Lateral kidney only"],
      "Know common positions: supine, prone, lithotomy, lateral, Fowler, Trendelenburg/reverse.",
      [
        "Upright is Fowler/sitting.",
        "Jackknife is Kraske variant.",
        "Kidney is lateral flexed.",
      ],
      "easy",
    ],
    [
      "A safety strap is typically placed:",
      "Proximal to the knees on supine patients (policy-dependent) securing without tourniquet effect",
      ["Across the chest tightly restricting ventilation always as best", "Only on the uninvolved arm loosely dangling off the bed", "Not used if the patient is NPO"],
      "Prevent falls while protecting nerves/skin/ventilation.",
      [
        "Chest constriction harms breathing.",
        "Secure all extremities properly.",
        "NPO unrelated to straps.",
      ],
      "medium",
    ],
    [
      "The sterile field is established when:",
      "Sterile drapes/packs are opened and arranged with aseptic technique",
      ["The patient enters the hospital lobby", "Anesthesia starts the IV", "Housekeeping mopped last night"],
      "Once created, protect continuously until procedure end.",
      [
        "Lobby not sterile field.",
        "IV start unsterile area typically.",
        "Environmental cleaning ≠ sterile field.",
      ],
      "easy",
    ],
    [
      "Surgical conscience means:",
      "Honestly acknowledging breaks in sterile technique and correcting them",
      ["Hiding contamination to avoid conflict", "Only following technique when observed", "Blaming circulators for all breaks without self-check"],
      "Patient safety requires reporting contamination even if personally responsible.",
      [
        "Hiding endangers patients.",
        "Technique always required.",
        "Accountability is shared/honest.",
      ],
      "easy",
    ],
    [
      "Counts are performed to prevent:",
      "Retained surgical items (sponges, sharps, instruments)",
      ["Incorrect CPT coding primarily", "Hypothermia only", "Wrong blood type only"],
      "Initial, additional item, closure, and final counts per policy; document discrepancies.",
      [
        "Coding separate.",
        "Warming prevents hypothermia.",
        "Blood bank verifies type.",
      ],
      "easy",
    ],
    [
      "Malignant hyperthermia is triggered in susceptible patients by:",
      "Certain anesthetics/succinylcholine—CST should know emergency MH cart/roles",
      ["Local lidocaine infiltration only always as classic trigger", "Alcohol skin prep alone", "Cotton drapes"],
      "MH crisis needs dantrolene and team response; scrub may help with sterile needs/cooling support per role.",
      [
        "Volatile agents/succ are classic.",
        "Prep not MH trigger.",
        "Drapes unrelated.",
      ],
      "hard",
    ],
    [
      "NPO status primarily reduces risk of:",
      "Aspiration under anesthesia",
      ["Surgical site infection from skin flora exclusively as NPO purpose", "Malignant hyperthermia", "Wrong-site surgery"],
      "Follow anesthesia NPO guidelines; meds with sips per orders.",
      [
        "SSI related more to asepsis/antibiotics.",
        "MH genetic/anesthetic.",
        "Timeout prevents wrong site.",
      ],
      "easy",
    ]
  ],
  "asepsis-sterile": [
    [
      "Sterile technique principle: when in doubt,",
      "Consider it contaminated",
      ["Use it anyway if pressed for time", "Ask the patient to decide sterility", "Flame it with a lighter in OR"],
      "Replace/ re-glove/ re-drape as indicated rather than risk SSI.",
      [
        "Time pressure ≠ excuse.",
        "Patients can't assess sterility.",
        "Open flame hazardous/not sterile practice.",
      ],
      "easy",
    ],
    [
      "The sterile gown is considered sterile from:",
      "Chest to sterile field level / gloved hands to elbows anteriorly (classic teaching), not the back",
      ["The entire back including neck ties area always", "Below the waist including gown hem dragging", "Under the arms in the axilla as most sterile zone"],
      "Backs, below waist, and axillae are not considered sterile.",
      [
        "Back unsterile.",
        "Below waist unsterile.",
        "Axilla unsterile.",
      ],
      "medium",
    ],
    [
      "Passing a sterile basin of saline across a sterile field: if it drips onto the field,",
      "The wet area is contaminated by strike-through risk and must be handled per protocol (cover/replace)",
      ["Moisture always improves sterility", "Ignore because saline is sterile so the field stays sterile forever", "Blot with a nonsterile towel from the circulator directly onto implants"],
      "Wicking through drapes contaminates; manage wet spots appropriately.",
      [
        "Moisture risks contamination.",
        "Sterile liquid can still wick microbes from below.",
        "Nonsterile blotting contaminates.",
      ],
      "hard",
    ],
    [
      "Opening a sterile peel pack: the circulator should:",
      "Peel edges back without touching contents, presenting to scrub",
      ["Touch the inside of the pack freely", "Toss instruments onto the field from across the room", "Open onto a wet contaminated surface"],
      "Present items aseptically; scrub takes without contamination.",
      [
        "Inside is sterile.",
        "Tossing risks contamination/damage.",
        "Wet contaminated surfaces ruin packs.",
      ],
      "easy",
    ],
    [
      "Gloving method where circulator assists after gowning is:",
      "Assisted gloving; closed gloving is done with hands inside gown cuffs",
      ["Open gloving only used for urinary catheters never for other tasks", "No-glove technique", "Double-gloving is illegal"],
      "Know open, closed, and assisted gloving; double-gloving reduces puncture risk.",
      [
        "Open gloving used for procedures without full gown sometimes.",
        "Gloves required.",
        "Double-gloving recommended often.",
      ],
      "medium",
    ],
    [
      "Flash sterilization / IUSS of an instrument dropped midcase should be:",
      "Avoided when possible; if used, follow IFU and aseptic delivery for immediate use",
      ["Routinely preferred for all instruments every case", "Used to build inventory for tomorrow", "Performed without cleaning the dropped item"],
      "Dropped items need cleaning then sterilization; IUSS not for convenience storage.",
      [
        "Not routine preferred.",
        "Not for storage.",
        "Cleaning required.",
      ],
      "medium",
    ],
    [
      "Surgical scrub antiseptics are applied to:",
      "Hands and forearms for the timed/counted method per product IFU before gowning",
      ["Only fingertips for two seconds", "The patient's abdomen as the scrub tech scrub", "Hair only"],
      "Waterless surgical hand rubs also used per IFU after washing when indicated.",
      [
        "Full scrub contact needed.",
        "Patient prep is separate.",
        "Hair covers separate.",
      ],
      "easy",
    ],
    [
      "Event-related sterility means packages remain sterile until:",
      "Compromised by tears, moisture, or improper handling/storage",
      ["Exactly 48 hours in all hospitals always by national law", "They change color", "The surgeon arrives"],
      "Inspect before opening; facility policies may still use dating.",
      [
        "Not universally fixed 48h law.",
        "Color may be indicators not event definition.",
        "Arrival irrelevant.",
      ],
      "medium",
    ],
    [
      "Airborne contamination control in OR includes:",
      "Positive pressure, HEPA filtration, and minimizing traffic/talking over field",
      ["Negative pressure like decontam as the OR standard", "Prop doors open to the hallway always", "Shaking linen over the field"],
      "Laminar/conventional systems reduce SSI risk with discipline.",
      [
        "OR positive vs corridor.",
        "Closed doors maintain pressure.",
        "Linen shaking sheds particles.",
      ],
      "easy",
    ],
    [
      "If a CST's glove is punctured during surgery, they should:",
      "Step away from the field and re-glove (and change gown if indicated) using sterile technique",
      ["Continue and mention it after closing only", "Remove both gloves and continue barehanded briefly", "Ask anesthesia to suture the glove"],
      "Immediate correction protects patient and self; double-glove helps detect punctures.",
      [
        "Delay increases exposure.",
        "Barehanded forbidden.",
        "Anesthesia isn't glove repair.",
      ],
      "easy",
    ]
  ],
  "anatomy-surg": [
    [
      "The gallbladder is located in the:",
      "Right upper quadrant, undersurface of the liver",
      ["Left lower quadrant only", "Mediastinum", "Popliteal fossa"],
      "Cholecystectomy addresses RUQ anatomy; know triangle of Calot concepts at high level.",
      [
        "LLQ different organs.",
        "Mediastinum thoracic.",
        "Popliteal behind knee.",
      ],
      "easy",
    ],
    [
      "The appendix typically arises from the:",
      "Cecum",
      ["Stomach fundus", "Sigmoid only always", "Duodenal bulb"],
      "McBurney's point landmark for appendectomy positioning/incision planning.",
      [
        "Stomach separate.",
        "Sigmoid left colon.",
        "Duodenum proximal small bowel.",
      ],
      "easy",
    ],
    [
      "Hernias involve:",
      "Protrusion of tissue/organ through a defect in the cavity wall",
      ["Only bone fractures", "Only skin rashes", "Kidney stones exclusively"],
      "Know inguinal, femoral, umbilical, incisional types and mesh repair concepts.",
      [
        "Ortho fractures differ.",
        "Derm rashes differ.",
        "Urolithiasis differs.",
      ],
      "easy",
    ],
    [
      "The common bile duct drains bile into the:",
      "Duodenum (via ampulla of Vater typically)",
      ["Ileum directly", "Bladder", "Left atrium"],
      "CBDE/ERCP anatomy relevant to biliary surgery complications.",
      [
        "Ileum distal bowel.",
        "Urinary bladder.",
        "Heart chamber.",
      ],
      "medium",
    ],
    [
      "Laparoscopic insufflation commonly uses:",
      "CO2 to create pneumoperitoneum",
      ["100% nitrogen always only", "Helium exclusively required", "Room air preferred for fire safety always"],
      "CO2 is soluble/excretable; watch physiologic effects (hypercarbia, vagal responses).",
      [
        "N2 less common.",
        "Helium sometimes special cases.",
        "Room air not preferred standard.",
      ],
      "medium",
    ],
    [
      "The thyroid gland sits:",
      "Anterior to the trachea in the neck",
      ["Inside the cranial vault", "Posterior to the kidneys only", "Within the scrotum"],
      "Recurrent laryngeal nerve and parathyroids are critical structures in thyroidectomy.",
      [
        "Brain location wrong.",
        "Adrenals/kidneys different.",
        "Gonads different.",
      ],
      "easy",
    ],
    [
      "Wound classification 'Class III' generally indicates:",
      "Contaminated (open/fresh accidental or major break in sterile technique/spillage)",
      ["Clean elective under ideal conditions (Class I)", "Clean-contaminated (Class II)", "Dirty/infected with old trauma/pus (Class IV)"],
      "Classification guides antibiotic expectations and SSI risk counseling.",
      [
        "I = clean.",
        "II = clean-contaminated.",
        "IV = dirty/infected.",
      ],
      "hard",
    ],
    [
      "Hemostasis methods include:",
      "Clamps, ligatures, electrosurgery, clips, and topical agents",
      ["Only antibiotics", "Only Trendelenburg", "Only counting sponges without vessel control"],
      "CST anticipates suture ties, energy devices, and clip appliers.",
      [
        "Antibiotics ≠ hemostasis.",
        "Positioning adjunct.",
        "Counts prevent retention not bleeding control alone.",
      ],
      "easy",
    ],
    [
      "The meniscus is found in the:",
      "Knee joint",
      ["Eyeball lens only", "Liver lobule", "Middle ear ossicles only as 'meniscus'"],
      "Arthroscopic meniscectomy/repair is common ortho CST knowledge.",
      [
        "Lens different.",
        "Liver different.",
        "Ossicles different.",
      ],
      "easy",
    ],
    [
      "Dehiscence means:",
      "Separation of wound edges",
      ["Excessive scar keloid only", "Complete sterile technique", "Normal primary intention healing without issue"],
      "Evisceration is protrusion of viscera—surgical emergency.",
      [
        "Keloid is hypertrophic scar.",
        "Opposite of failure.",
        "Dehiscence is a complication.",
      ],
      "medium",
    ]
  ],
  "equipment-safety": [
    [
      "Monopolar electrosurgery requires:",
      "An active electrode and a dispersive (return) pad with good contact",
      ["No return pad ever", "Alcohol pooling under the pad intentionally", "Activation while touching the OR table metal with the active tip casually"],
      "Pad placement on well-vascularized muscle, avoid scars/implants/bony prominences per policy; prevent alternate site burns.",
      [
        "Return path needed for monopolar.",
        "Flammable prep hazards.",
        "Table contact risks burns.",
      ],
      "medium",
    ],
    [
      "Bipolar electrosurgery current path is:",
      "Between the two tines of the forceps—no dispersive pad required",
      ["Through the dispersive pad always like monopolar", "Only through the anesthesia machine", "Unable to coagulate vessels"],
      "Bipolar useful near nerves/wet fields with localized current.",
      [
        "No pad for bipolar.",
        "Anesthesia machine not the path.",
        "It does coagulate.",
      ],
      "easy",
    ],
    [
      "Laser safety includes:",
      "Eyewear specific to wavelength, controlled access, and nonreflective precautions",
      ["Staring into the beam to aim better", "Alcohol prep puddles left during activation", "Paper drapes ignited as a teaching tool"],
      "Fire/eye/plume hazards; use wet drapes/smoke evacuation as indicated.",
      [
        "Never stare into beam.",
        "Fire risk with alcohol.",
        "Don't ignite drapes.",
      ],
      "medium",
    ],
    [
      "Pneumatic tourniquet overinflation/time excess risks:",
      "Nerve injury, ischemia, and tissue damage",
      ["Improved sensation always", "Mandatory hypothermia", "Sterile field contamination automatically"],
      "Document times; exsanguinate appropriately; notify team of duration.",
      [
        "Injures nerves.",
        "Warming separate issue.",
        "Not automatic contamination.",
      ],
      "medium",
    ],
    [
      "Radiation safety for fluoroscopy uses:",
      "Time, distance, and shielding (lead)",
      ["Standing closer to increase dose for better images as a safety rule", "Lead aprons left outside always during cases", "Holding continuous fluoro without reason"],
      "CST may wear dosimeters/aprons; hands out of beam.",
      [
        "Distance decreases dose.",
        "Wear shielding.",
        "Minimize fluoro time.",
      ],
      "easy",
    ],
    [
      "A malfunctioning OR table should be:",
      "Reported and removed from service until repaired—not used 'carefully'",
      ["Used if the case is already booked", "Kicked to make it work", "Covered with extra sheets to hide faults"],
      "Equipment failure can cause crush/fall/positioning injuries.",
      [
        "Safety > schedule.",
        "Force damages more.",
        "Hiding faults dangerous.",
      ],
      "easy",
    ],
    [
      "Surgical plume from electrosurgery/laser should be:",
      "Evacuated with appropriate smoke evacuation systems",
      ["Inhaled freely as harmless steam always", "Directed toward the sterile corridor for ventilation", "Ignored per outdated myths"],
      "Plume can contain toxins/particles; PPE and evacuation protect staff.",
      [
        "Not harmless.",
        "Don't spread to hall.",
        "Modern standards require control.",
      ],
      "medium",
    ],
    [
      "Implantable electronic devices (e.g., pacemakers) require caution with:",
      "Monopolar electrosurgery—coordinate with anesthesia/cardiology protocols",
      ["Bipolar only ever banned in all cases worldwide", "No energy devices ever for any surgery", "MRI in the OR routinely midcase"],
      "Use bipolar when possible, short bursts, pad placement strategies per protocol.",
      [
        "Bipolar often preferred/safer relative.",
        "Energy often still needed with precautions.",
        "MRI not midcase OR routine.",
      ],
      "hard",
    ],
    [
      "Sharps safety on the field includes:",
      "Neutral zone/no-hands passing techniques and proper sharps containers",
      ["Recapping suture needles with two hands toward the body", "Hiding sharps in sponges", "Leaving loaded needle holders facing up toward eyes casually"],
      "OSHA and AORN-aligned practices reduce sticks.",
      [
        "Two-handed recapping risky.",
        "Sharps in sponges cause RSI/counts errors.",
        "Point away/safe park.",
      ],
      "easy",
    ],
    [
      "If a count is incorrect, the team should:",
      "Notify surgeon, recount, search wound/field/trash per policy, and obtain imaging if unresolved",
      ["Close quickly to finish on time", "Assume it fell on the floor and ignore", "Alter count sheet to match without search"],
      "Never falsify counts; retained items are never events.",
      [
        "Time pressure ≠ close over discrepancy.",
        "Must reconcile.",
        "Falsifying is misconduct.",
      ],
      "easy",
    ]
  ],
};
