/** NHA ExCPT — 40 curated MCQs */
export const topics = {
  "pharmacology": [
    [
      "A drug's generic name is:",
      "The official nonproprietary name (e.g., ibuprofen)",
      ["Always the brand name like Advil only", "The NDC package code only", "The DEA schedule number only"],
      "Generic names identify the active ingredient; brands are proprietary.",
      [
        "Brand ≠ generic.",
        "NDC identifies package/labeler/product.",
        "Schedules are controlled substance classes.",
      ],
      "easy",
    ],
    [
      "Pharmacokinetics primarily studies:",
      "ADME: absorption, distribution, metabolism, and excretion",
      ["Only drug pricing", "Only tablet colors", "Only pharmacy floor plans"],
      "PK describes what the body does to the drug; PD is what the drug does to the body.",
      [
        "Pricing is business.",
        "Color is imprint ID aid.",
        "Layout is operations.",
      ],
      "easy",
    ],
    [
      "An antagonist drug:",
      "Blocks or diminishes agonist activity at a receptor",
      ["Always increases receptor activation maximally", "Is only a vitamin", "Cannot bind any receptor"],
      "Antagonists occupy receptors without activating them (or block activation pathways).",
      [
        "That describes agonists.",
        "Vitamins vary.",
        "Antagonists do bind/block.",
      ],
      "medium",
    ],
    [
      "Which route typically has the fastest onset?",
      "Intravenous (IV)",
      ["Oral tablets", "Transdermal patches", "Rectal suppositories generally faster than IV"],
      "IV delivers drug directly to bloodstream; oral undergoes absorption/first-pass often.",
      [
        "Oral slower/variable.",
        "Patches are slow/steady.",
        "Rectal not faster than IV.",
      ],
      "easy",
    ],
    [
      "ACE inhibitors are commonly associated with which side effect?",
      "Dry cough (and risk of hyperkalemia/angioedema)",
      ["Orange urine only as the hallmark", "Tendon rupture as the primary class effect like fluoroquinolones", "Serotonin syndrome exclusively"],
      "ACEI cough from bradykinin; monitor K+ and angioedema warning.",
      [
        "Orange urine more rifampin-type teaching.",
        "Tendon risk: FQs.",
        "Serotonin syndrome: MAOI/SSRI combos.",
      ],
      "medium",
    ],
    [
      "Warfarin anticoagulation is monitored with:",
      "INR (derived from PT)",
      ["Only aPTT always as the sole warfarin test", "HbA1c", "TSH only"],
      "Warfarin affects vitamin K–dependent factors monitored by PT/INR; heparin often aPTT/anti-Xa.",
      [
        "aPTT more heparin pathway classic.",
        "A1c is diabetes.",
        "TSH is thyroid.",
      ],
      "medium",
    ],
    [
      "A bacteriostatic antibiotic:",
      "Inhibits bacterial growth/reproduction without necessarily killing immediately",
      ["Always sterilizes blood instantly", "Is an antiviral only", "Raises blood glucose as its antimicrobial mechanism"],
      "Bactericidal kills; bacteriostatic inhibits—host immunity helps clear infection.",
      [
        "Not instant sterilization definition.",
        "Antibiotics target bacteria.",
        "Glucose unrelated to mechanism.",
      ],
      "easy",
    ],
    [
      "NSAIDs can increase risk of:",
      "GI bleeding and kidney injury, especially in high-risk patients",
      ["Improved platelet function always", "Cure of all infections", "Lowering INR when combined with warfarin always safely"],
      "NSAIDs inhibit COX; caution with ulcers, CKD, and anticoagulants.",
      [
        "They impair platelets ( esp. aspirin irreversible).",
        "Not antibiotics.",
        "Often increase bleeding risk with warfarin.",
      ],
      "medium",
    ],
    [
      "Insulin is used to treat:",
      "Diabetes mellitus by promoting glucose uptake/storage",
      ["Hypothyroidism as first-line", "Bacterial pneumonia as monotherapy", "Vitamin B12 deficiency primarily"],
      "Insulin lowers blood glucose; different types have different onsets/peaks.",
      [
        "Hypothyroid: levothyroxine.",
        "Pneumonia: antibiotics.",
        "B12: replacement.",
      ],
      "easy",
    ],
    [
      "A narrow therapeutic index drug requires:",
      "Careful dosing and often therapeutic drug monitoring",
      ["No monitoring ever", "OTC self-titration freely for all ages", "Mixing all doses into one weekly megadose always"],
      "Examples often include warfarin, digoxin, lithium, phenytoin—small level changes matter.",
      [
        "Monitoring common.",
        "Not casual OTC titration.",
        "Megadoses dangerous.",
      ],
      "hard",
    ]
  ],
  "federal-law": [
    [
      "Controlled substance schedules (I–V) are established under the:",
      "Controlled Substances Act enforced by the DEA",
      ["FDA food menu labeling only", "USP compounding chapters only", "OSHA bloodborne pathogen standard only"],
      "DEA schedules reflect abuse potential/accepted medical use; C-I has no accepted medical use in US.",
      [
        "FDA regulates drugs/devices/food differently.",
        "USP standards for quality/compounding.",
        "OSHA is workplace safety.",
      ],
      "easy",
    ],
    [
      "A Schedule II prescription refill rule is generally:",
      "No refills; a new prescription is required for each fill (with limited emergency exceptions)",
      ["Unlimited refills for 3 years", "Five refills in 6 months like some C-III/IV rules", "Refills without any prescription"],
      "C-II cannot be refilled; C-III/IV often up to 5 refills in 6 months.",
      [
        "No multi-year unlimited.",
        "That's III/IV pattern.",
        "Rx required.",
      ],
      "medium",
    ],
    [
      "Pseudoephedrine sales restrictions relate to:",
      "Combat Methamphetamine Epidemic Act (CMEA) daily/monthly limits and logbook/ID requirements",
      ["Only child-resistant caps on all OTC vitamins forever as the sole rule", "DEA Schedule I listing of pseudoephedrine", "Ban on all cold medicines nationwide"],
      "CMEA regulates ephedrine/pseudoephedrine/PPA sales behind counter with limits.",
      [
        "CRC is PPPA separate topic.",
        "PSE is not CI.",
        "Cold meds still sold with limits.",
      ],
      "medium",
    ],
    [
      "OBRA '90 is associated with requiring:",
      "Prospective drug utilization review and offer to counsel Medicaid patients (and influenced counseling standards)",
      ["Only DEA form 222 for all OTCs", "Elimination of patient profiles", "Mandatory mail-order only"],
      "OBRA '90 drove DUR and counseling offer requirements especially for Medicaid.",
      [
        "222 is C-II ordering.",
        "Profiles are kept.",
        "Mail-order not mandated by OBRA alone.",
      ],
      "hard",
    ],
    [
      "DEA Form 222 is used to:",
      "Order Schedule I/II controlled substances",
      ["Report all HIPAA breaches", "File state board renewals only", "Document immunization administration only"],
      "222 (or CSOS electronic) orders C-I/II; Form 106 reports theft/loss; 41 for destruction.",
      [
        "HIPAA is HHS/OCR.",
        "Board renewals differ.",
        "Immunizations documented elsewhere.",
      ],
      "medium",
    ],
    [
      "Child-resistant packaging is required under the:",
      "Poison Prevention Packaging Act (PPPA) for many oral Rx/OTC products with exceptions",
      ["Sherman Antitrust Act", "Fair Labor Standards Act only", "Americans with Disabilities Act only as packaging law"],
      "PPPA aims to reduce pediatric poisonings; easy-open may be requested with documentation.",
      [
        "Antitrust is competition.",
        "FLSA is wages/hours.",
        "ADA is disability rights.",
      ],
      "easy",
    ],
    [
      "HIPAA in pharmacy practice primarily protects:",
      "Patient PHI from improper use/disclosure",
      ["Drug acquisition costs only", "Technician lunch breaks only", "DEA schedule decisions"],
      "Minimum necessary and secure handling of prescriptions/profiles apply.",
      [
        "Costs are business.",
        "Breaks are labor.",
        "DEA schedules controlled substances.",
      ],
      "easy",
    ],
    [
      "FDA recalls: a Class I recall means:",
      "Reasonable probability of serious adverse health consequences or death",
      ["Unlikely to cause adverse health consequences (Class III concept)", "Only labeling misspelling with no risk ever", "A DEA diversion audit"],
      "Class I most serious; Class II temporary/reversible remote probability; Class III unlikely.",
      [
        "That is Class III.",
        "Minor labeling may be III.",
        "Recall ≠ DEA audit.",
      ],
      "medium",
    ],
    [
      "Who may legally prescribe controlled substances?",
      "DEA-registered practitioners acting within scope/state law",
      ["Any pharmacy cashier", "Unlicensed friends with pads", "Manufacturers' sales reps for patients directly always"],
      "Prescribers need authority and DEA registration for controlled Rx.",
      [
        "Cashiers don't prescribe.",
        "Unlicensed prescribing illegal.",
        "Reps don't prescribe for patients.",
      ],
      "easy",
    ],
    [
      "Medication Guides (MedGuides) are FDA-required when:",
      "Certain drugs have serious risks needing patient information each dispensing as specified",
      ["All topical cosmetics", "Only hospital floor stock saline", "Never for any outpatient Rx"],
      "MedGuides are part of REMS/labeling risk communication for select drugs.",
      [
        "Cosmetics differ.",
        "Saline not typical MedGuide focus.",
        "Outpatient MedGuides exist for listed drugs.",
      ],
      "hard",
    ]
  ],
  "order-entry": [
    [
      "DAW 1 typically indicates:",
      "Substitution not allowed by prescriber (dispense as written)",
      ["Patient requests brand when substitution allowed (often DAW 2)", "Pharmacist selects brand arbitrarily without codes", "OTC status"],
      "DAW codes communicate product selection intent for claims.",
      [
        "DAW 2 often patient requested brand.",
        "Codes are standardized.",
        "OTC ≠ DAW.",
      ],
      "medium",
    ],
    [
      "A sig of 'i po bid prn pain' means:",
      "Take one by mouth twice daily as needed for pain",
      ["Inject two intramuscularly weekly", "Instill in both eyes at bedtime only", "Apply topically once monthly"],
      "i=1, po=by mouth, bid=twice daily, prn=as needed.",
      [
        "Not IM weekly.",
        "Eyes would be ou/od/os gtt.",
        "Topical monthly wrong.",
      ],
      "easy",
    ],
    [
      "When a prescription is missing the strength and multiple exist, the technician should:",
      "Clarify with the pharmacist/prescriber before processing",
      ["Guess the most common strength", "Pick the highest strength for faster effect", "Omit strength on the label"],
      "Ambiguities require clarification to prevent errors.",
      [
        "Guessing is dangerous.",
        "Highest strength risky.",
        "Labels need correct strength.",
      ],
      "easy",
    ],
    [
      "Tall Man lettering is used to:",
      "Distinguish look-alike drug names (e.g., hydrALAZINE vs hydrOXYzine)",
      ["Indicate controlled schedules", "Show AWP pricing", "Mark refrigeration only"],
      "ISMP/FDA tall man lettering reduces selection errors.",
      [
        "Schedules are C-II etc.",
        "Pricing separate.",
        "Fridge stickers differ.",
      ],
      "easy",
    ],
    [
      "e-Prescribing controlled substances (EPCS) requires:",
      "Identity-proofed prescribers and certified EPCS systems meeting DEA requirements",
      ["Any email from an unknown address", "Text messages without security", "Verbal only forever for all C-II"],
      "EPCS has specific security controls; verbal C-II limited to emergencies with follow-up.",
      [
        "Insecure email insufficient.",
        "Unsecured texts insufficient.",
        "Emergency verbal has strict limits.",
      ],
      "hard",
    ],
    [
      "Days' supply calculation requires:",
      "Quantity dispensed and directions (dose × frequency) to compute duration",
      ["Only the patient's age", "Only the color of tablets", "Only the NPI"],
      "Insurance adjudication often rejects wrong days' supply.",
      [
        "Age alone insufficient.",
        "Color irrelevant.",
        "NPI is provider ID.",
      ],
      "easy",
    ],
    [
      "A therapeutic duplication alert during DUR means:",
      "Two drugs with the same therapeutic effect/class may be overlapping inappropriately",
      ["The patient is allergic to inactive dye only always", "The drug is OTC", "The SIG is perfect"],
      "Pharmacists evaluate duplication alerts (e.g., two NSAIDs).",
      [
        "Allergy is different DUR message.",
        "OTC status separate.",
        "SIG issues differ.",
      ],
      "medium",
    ],
    [
      "NDC numbers identify:",
      "Labeler, product, and package size (10–11 digit formats)",
      ["Patient MRN only", "DEA registrant only", "ICD-10 diagnosis only"],
      "NDCs are central to product selection and billing.",
      [
        "MRN is patient.",
        "DEA is registrant.",
        "ICD is diagnosis.",
      ],
      "easy",
    ],
    [
      "Prior authorization (PA) is needed when:",
      "A payer requires approval before covering a medication under plan rules",
      ["The drug is always OTC candy", "The pharmacist wants a lunch break", "NDC is valid and preferred with open coverage"],
      "PA workflows involve clinical criteria submissions; technicians assist with process under pharmacist oversight.",
      [
        "OTC candy not PA drugs.",
        "Breaks unrelated.",
        "Preferred covered drugs may not need PA.",
      ],
      "easy",
    ],
    [
      "Auxiliary labels should:",
      "Reinforce key warnings (e.g., take with food, may cause drowsiness) without replacing counseling",
      ["Contradict the prescription directions intentionally", "Replace the need for a prescription label", "List unrelated diagnoses"],
      "Aux labels support safe use; pharmacist counseling remains important.",
      [
        "Never contradict Rx.",
        "Primary label still required.",
        "Diagnoses on aux labels inappropriate.",
      ],
      "medium",
    ]
  ],
  "dispensing-practice": [
    [
      "The 'five rights' of medication administration/dispensing emphasize right:",
      "Patient, drug, dose, route, and time (plus documentation/education concepts)",
      ["Price, parking, posters, pens, and phones", "Color, shape, taste, smell, and sound only", "Only the right shelf"],
      "Verification prevents wrong-patient/wrong-drug errors.",
      [
        "Business items irrelevant.",
        "Physical descriptors aid checks but aren't the five rights.",
        "Shelf location insufficient.",
      ],
      "easy",
    ],
    [
      "Beyond-use dating for a nonsterile compounded aqueous oral liquid (USP general concepts) is often:",
      "14 days refrigerated when otherwise stable/appropriate (classic teaching default unless literature differs)",
      ["3 years always", "Indefinite at room temp always", "1 hour always like sterile immediate use only"],
      "USP <795> BUDs depend on water activity/type; know common exam defaults and that manufacturer/stability data can modify.",
      [
        "3 years is commercial packaged often.",
        "Not indefinite.",
        "1 hour is different sterile concept.",
      ],
      "hard",
    ],
    [
      "Sterile compounding PPE typically includes:",
      "Hair cover, face mask, gown, sterile gloves (and eye cover as required) with proper garbing order",
      ["Street clothes only inside the PEC", "Jewelry encouraged on hands", "No hand hygiene before gloves"],
      "USP <797> garbing and aseptic technique protect CSPs from contamination.",
      [
        "Street clothes shed particles.",
        "Jewelry sheds/tears gloves.",
        "Hand hygiene required.",
      ],
      "medium",
    ],
    [
      "A laminar airflow workbench's critical principle is:",
      "First air (uninterrupted HEPA-filtered air) must contact critical sites",
      ["Blocking HEPA airflow with large objects permanently is ideal", "Talking across open sterile vials is encouraged", "Cleaning is optional weekly only"],
      "Don't obstruct first air; clean with appropriate agents (often sterile IPA) frequently.",
      [
        "Obstruction contaminates.",
        "Talking sheds particles.",
        "Cleaning is frequent/required.",
      ],
      "hard",
    ],
    [
      "Unit-dose packaging in hospitals helps:",
      "Reduce errors and track doses to administration time",
      ["Eliminate the need for pharmacist checks always", "Allow unlabeled meds", "Mix all patients' meds in one cup routinely"],
      "Unit dose supports safety; verification still required.",
      [
        "Checks still needed.",
        "Labels required.",
        "Multi-patient mixing dangerous.",
      ],
      "easy",
    ],
    [
      "When counting controlled substances on a tray, best practice includes:",
      "Double-counting and documenting perpetual inventory per policy",
      ["Estimating quantities visually only for C-II", "Leaving stock bottles unlocked in public waiting areas", "Sharing biometric safe access casually"],
      "C-II perpetual inventory and secure storage are critical.",
      [
        "Estimates invite diversion errors.",
        "Public access improper.",
        "Access control required.",
      ],
      "medium",
    ],
    [
      "Eye drops should be labeled/administered with care to:",
      "Avoid contamination of the dropper tip and follow which eye (OD/OS/OU)",
      ["Touch the tip firmly to the cornea each time as required", "Share bottles between unrelated patients routinely", "Store frozen solid always"],
      "Aseptic handling and correct laterality matter.",
      [
        "Tip contact contaminates/injures.",
        "Sharing risks infection.",
        "Freezing often damages.",
      ],
      "easy",
    ],
    [
      "If a dispensing error is discovered after the patient left, the technician should:",
      "Notify the pharmacist immediately so patient can be contacted and error corrected per policy",
      ["Hide the error", "Blame the patient", "Wait until annual inventory"],
      "Rapid disclosure/mitigation protects patients and is an ethical/legal duty.",
      [
        "Hiding worsens harm/liability.",
        "Patient blame inappropriate.",
        "Delay dangerous.",
      ],
      "easy",
    ],
    [
      "Refrigerated medications generally should be stored at approximately:",
      "2–8°C (36–46°F) unless the label specifies otherwise",
      ["−20°C freezer for all refrigerated labels", "37°C incubator", "Room temperature always if fridge is full"],
      "Monitor fridge logs; do not use food fridges improperly; vaccines have strict rules.",
      [
        "Freezer is colder than refrigerated.",
        "Body temp too warm.",
        "Don't leave fridge items at room temp contrary to label.",
      ],
      "medium",
    ],
    [
      "Hazardous drug handling (USP <800> concepts) includes:",
      "Using appropriate PPE and containment when compounding/handling HDs",
      ["Crushing chemo tablets unprotected on the retail counter", "Pregnant staff handling HDs without protections when policies restrict", "Disposing HD waste in regular paper recycle"],
      "NIOSH HD lists and <800> protect workers/environment.",
      [
        "Unprotected crushing creates exposure.",
        "Pregnancy precautions exist.",
        "HD waste has special streams.",
      ],
      "hard",
    ]
  ],
};
