/** NHA CPCT/A — 40 curated MCQs */
export const topics = {
  "patient-care": [
    [
      "When assisting a patient with ambulation who is weak on one side, the PCT should typically walk:",
      "On the patient's weak side to provide support",
      ["Far ahead without contact", "Only on the strong side never supporting the weak side", "Behind by 20 feet silently"],
      "Support the weak side and use gait belt per protocol; match pace and use assistive devices ordered.",
      [
        "Abandonment risk if too far.",
        "Weak side needs support.",
        "Too far behind loses control.",
      ],
      "easy",
    ],
    [
      "Active range of motion (ROM) means:",
      "The patient moves the joint independently",
      ["The PCT moves the joint fully for a passive patient always as the definition of active", "No movement occurs", "Only therapist-performed continuous passive motion machine always"],
      "Active = patient powered; passive = staff moves limb; active-assist is shared.",
      [
        "That describes passive ROM.",
        "ROM implies movement.",
        "CPM is a device modality.",
      ],
      "easy",
    ],
    [
      "When making an occupied bed, a key principle is:",
      "Keep the patient covered and use side rails/safety measures per policy while changing linen",
      ["Pull all linen off leaving the patient fully exposed in a cold hallway", "Leave wrinkles under pressure points", "Disconnect call light permanently"],
      "Dignity, warmth, and skin protection matter during occupied bedmaking.",
      [
        "Exposure harms dignity/temperature.",
        "Wrinkles promote skin breakdown.",
        "Call light must remain accessible.",
      ],
      "medium",
    ],
    [
      "Intake and output (I&O) documentation should include:",
      "Oral fluids, IV fluids as applicable, urine, and other measurable outputs per protocol",
      ["Only solid food weight guesses", "Only the PCT's water intake", "Television volume"],
      "Accurate I&O informs fluid balance assessment for the care team.",
      [
        "Solids aren't typical I&O fluid metrics.",
        "Staff intake irrelevant.",
        "TV irrelevant.",
      ],
      "easy",
    ],
    [
      "Fowler's position is:",
      "Head of bed elevated (commonly 45–60°) for comfort/breathing/eating",
      ["Flat supine only", "Prone with face down only", "Trendelenburg with head down only"],
      "Semi-Fowler's is lower elevation; High-Fowler's near 90°—used for dyspnea/meals.",
      [
        "Supine is flat.",
        "Prone is face down.",
        "Trendelenburg is head down.",
      ],
      "easy",
    ],
    [
      "When feeding a patient at risk for aspiration, the PCT should:",
      "Keep head elevated, offer small bites, and ensure swallowing before next bite per protocol",
      ["Have the patient fully supine while feeding quickly", "Mix all pills in hot coffee without orders", "Leave trays without opening containers for dependent patients and leave"],
      "Aspiration precautions require positioning and pacing; report coughing/wet voice.",
      [
        "Supine feeding increases aspiration.",
        "Meds need orders/nurse.",
        "Dependent patients need assistance.",
      ],
      "medium",
    ],
    [
      "Indwelling urinary catheter care includes:",
      "Keeping the drainage bag below bladder level and peri-care per protocol without kinking tubing",
      ["Raising the bag above the bladder routinely", "Disconnecting the closed system casually daily", "Using the drainage spout to refill water pitchers"],
      "Closed system and gravity drainage reduce UTI risk; never use bag for drinking water.",
      [
        "Bag above bladder causes reflux.",
        "Breaks in system increase infection.",
        "Contamination hazard.",
      ],
      "medium",
    ],
    [
      "Pressure injury prevention includes:",
      "Repositioning on schedule, skin inspection, and keeping skin clean/dry",
      ["Massaging reddened bony areas vigorously always", "Leaving patients in wet linen", "Using donut cushions that concentrate pressure as best practice always"],
      "Relieve pressure; avoid massage over reddened areas; manage moisture.",
      [
        "Massage over erythema can worsen injury.",
        "Moisture macerates skin.",
        "Donuts can increase edge pressure.",
      ],
      "easy",
    ],
    [
      "When measuring weight on a standing scale, the PCT should:",
      "Balance/zero the scale, assist safely, and record with footwear standards per policy",
      ["Estimate without a scale if busy", "Have the patient hold a heavy backpack", "Skip documenting units"],
      "Accurate weights guide medication and fluid decisions.",
      [
        "Estimates inadequate.",
        "Extra items falsify weight.",
        "Units required.",
      ],
      "easy",
    ],
    [
      "Oral care for an unconscious patient requires:",
      "Lateral position as appropriate, suction available per protocol, and gentle mouth care to prevent aspiration",
      ["Supine flat with large water boluses", "Skipping oral care entirely for days", "Using oil-based swabs in a way that risks aspiration without training"],
      "Airway protection is critical during unconscious oral hygiene.",
      [
        "Flat + water risks aspiration.",
        "Oral care still needed.",
        "Unsafe techniques harm lungs.",
      ],
      "hard",
    ]
  ],
  "safety-infection": [
    [
      "The first step in using a fire extinguisher is often taught as:",
      "Pull the pin (PASS: Pull, Aim, Squeeze, Sweep)",
      ["Spray people first", "Hide the extinguisher", "Open all windows and leave gas on"],
      "PASS acronym guides extinguisher use; RACE guides overall fire response (Rescue/Alarm/Contain/Extinguish-Evacuate).",
      [
        "Don't spray people as first step.",
        "Need accessible extinguisher.",
        "Gas should be controlled per protocol.",
      ],
      "easy",
    ],
    [
      "Hand hygiene with alcohol-based rub is appropriate when:",
      "Hands are not visibly soiled and facility policy allows it",
      ["Hands are covered in blood without washing first", "Caring for C. difficile when soap/water is required by policy and you skip washing", "After using the restroom without any hand cleaning"],
      "Visible soil/certain organisms need soap and water; otherwise ABHR is often preferred for convenience/efficacy.",
      [
        "Bloody hands need soap/water washing.",
        "Spore-forming organisms often need soap/water.",
        "Restroom requires hygiene.",
      ],
      "medium",
    ],
    [
      "Contact precautions typically require:",
      "Gown and gloves for contact with the patient/environment as indicated",
      ["N95 for every contact patient always without airborne indication", "No PPE ever", "Sterile surgical scrub for entering the hallway only"],
      "MRSA/VRE-type contact precautions use gown/gloves; airborne needs respirator/room controls.",
      [
        "N95 is airborne/respirator situations.",
        "PPE is required.",
        "Hallway scrub alone insufficient.",
      ],
      "easy",
    ],
    [
      "A gait belt is used to:",
      "Assist transfer/ambulation safely by providing a secure hold",
      ["Restrain a patient in bed continuously without orders", "Replace wheelchairs forever", "Lift patients by the belt alone overhead"],
      "Gait belts aid guided assistance; restraints need orders/protocols.",
      [
        "Continuous restraint use is regulated.",
        "Wheelchairs still used.",
        "Improper lifting injures staff/patients.",
      ],
      "easy",
    ],
    [
      "When a patient is falling, the PCT should generally:",
      "Guide the patient to the floor safely controlling the descent if possible, then call for help",
      ["Try to catch them mid-air alone with twisting back flexion", "Run away without assistance", "Pull their arms upward sharply"],
      "Protect the head and ease down; don't sacrifice your back with unsafe catches.",
      [
        "Unsafe catch causes dual injury.",
        "Abandonment worsens outcomes.",
        "Arm yank injures shoulders.",
      ],
      "medium",
    ],
    [
      "Sharps should be disposed of in:",
      "Puncture-resistant sharps containers",
      ["Regular trash bags", "Recycled paper bins", "Patient meal trays"],
      "Never recap with two hands; fill only to fill line.",
      [
        "Trash risks needlesticks.",
        "Paper recycling wrong.",
        "Meal trays contaminate food services.",
      ],
      "easy",
    ],
    [
      "Restraint use requires:",
      "A provider order (except true emergencies per policy) and frequent monitoring/documentation",
      ["PCT independent indefinite application without order", "Tying restraints to side rails in a hazardous way", "No circulation checks"],
      "Restraints are last resort; monitor skin, toileting, circulation, and attempt alternatives.",
      [
        "Orders/policies govern.",
        "Unsafe tying causes injury.",
        "Circulation checks mandatory.",
      ],
      "hard",
    ],
    [
      "The most effective way to prevent spread of pathogens between patients is:",
      "Hand hygiene and correct PPE use",
      ["Wearing the same gloves for all patients all day", "Shaking linen into the air", "Leaving bedpans uncleaned"],
      "Hand hygiene is #1; change gloves between patients.",
      [
        "Glove reuse spreads pathogens.",
        "Aerosolizing linen spreads microbes.",
        "Dirty equipment contaminates.",
      ],
      "easy",
    ],
    [
      "RACE in fire safety stands for:",
      "Rescue, Alarm, Confine/Contain, Extinguish/Evacuate",
      ["Run, Argue, Cry, Exit", "Remove All Care Equipment first always before patients", "Radio, Assess, Coffee, Eat"],
      "Prioritize people, alarm, contain smoke/fire, then extinguish if small/safe or evacuate.",
      [
        "Silly mnemonic.",
        "Patients before equipment.",
        "Not a break mnemonic.",
      ],
      "easy",
    ],
    [
      "Standard Precautions apply to:",
      "All patients, regardless of known infection status",
      ["Only patients with documented HIV", "Only ICU patients", "Only visitors"],
      "Assume blood/body fluids are potentially infectious for everyone.",
      [
        "Known status not required.",
        "All settings/patients.",
        "Staff use precautions with patients.",
      ],
      "easy",
    ]
  ],
  "phlebotomy-ekg": [
    [
      "The correct patient identification process before a draw/EKG includes:",
      "Using two identifiers (e.g., name and DOB) matching the order/wristband",
      ["Room number alone", "Bed card nickname alone", "Skipping ID if 'you know them'"],
      "Two identifiers prevent wrong-patient procedures.",
      [
        "Room numbers change.",
        "Nicknames insufficient.",
        "Familiarity ≠ ID.",
      ],
      "easy",
    ],
    [
      "Lavender EDTA tubes are commonly used for:",
      "CBC/hematology testing",
      ["Coagulation PT/INR as first choice", "Glucose gray-top exclusively as the EDTA use", "Blood cultures as the primary bottle type"],
      "EDTA preserves cellular elements for CBC; coag uses citrate; gray for glucose glycolysis inhibition; cultures use special bottles.",
      [
        "Coag is light blue citrate.",
        "Gray is fluoride.",
        "Cultures are bottles/SPS.",
      ],
      "easy",
    ],
    [
      "After needle removal, activate safety and apply pressure to:",
      "Prevent hematoma and stop bleeding",
      ["Increase arterial spurting", "Eliminate the need for labeling", "Cause hemoconcentration intentionally"],
      "Adequate pressure/time reduces bruising; label at bedside.",
      [
        "Pressure stops bleeding.",
        "Labeling still required.",
        "Hemoconcentration is a preanalytical error.",
      ],
      "easy",
    ],
    [
      "For a routine 12-lead EKG, V4 is placed at:",
      "Fifth intercostal space, midclavicular line",
      ["Fourth ICS right sternal border (V1)", "Second ICS midaxillary", "Over the umbilicus"],
      "Know V1–V6 landmarks; limb leads on limbs (or torso per protocol when needed).",
      [
        "That is V1.",
        "Incorrect ICS/line.",
        "Umbilicus wrong.",
      ],
      "medium",
    ],
    [
      "Artifact from patient shivering on EKG is reduced by:",
      "Warming the patient and ensuring relaxed muscles/good electrode contact",
      ["Having them jog in place", "Removing all electrodes", "Recording only during seizures intentionally"],
      "Somatic tremor creates fuzzy baseline; comfort helps.",
      [
        "Exercise increases artifact.",
        "Electrodes required.",
        "Seizures worsen artifact.",
      ],
      "medium",
    ],
    [
      "Order of draw is intended to prevent:",
      "Additive carryover between tubes",
      ["Patient identification", "Need for gloves", "Vein selection"],
      "Follow CLSI order; invert tubes gently to mix additives.",
      [
        "ID is separate step.",
        "Gloves still required.",
        "Vein selection separate.",
      ],
      "easy",
    ],
    [
      "A tourniquet left on too long may cause:",
      "Hemoconcentration and falsely elevated analytes",
      ["Improved sterility of the site automatically", "Lower all lab values always", "Sterile urine"],
      "Limit tourniquet time (~1 minute) before access.",
      [
        "Doesn't sterilize.",
        "Many values rise, not all fall.",
        "Urine unrelated.",
      ],
      "medium",
    ],
    [
      "If a patient is allergic to adhesive, for EKG the PCT should:",
      "Use alternative electrodes/skins preps per policy and document allergy",
      ["Force standard adhesives anyway", "Skip the EKG without notifying nurse/provider when ordered", "Place electrodes on top of thick lotion without cleaning"],
      "Allergy adaptations maintain test quality and skin integrity.",
      [
        "Forcing adhesives harms skin.",
        "Escalate rather than skip silently.",
        "Lotion increases artifact.",
      ],
      "easy",
    ],
    [
      "Capillary puncture in adults is often performed on:",
      "The side of the middle or ring finger",
      ["The thumb tip always preferred", "The index finger tip center exclusively as best practice", "The palm center"],
      "Avoid thumb/index often due to callus/use; use lateral fingertip pulp.",
      [
        "Thumb more callused.",
        "Index often avoided.",
        "Palm not standard capillary site.",
      ],
      "medium",
    ],
    [
      "Syncope during phlebotomy: first actions include:",
      "Stop the draw and protect the patient from injury (lower head/supine)",
      ["Continue filling tubes while they seize/faint", "Have them stand immediately", "Leave them alone to get coffee"],
      "Safety first; notify nurse/provider as needed.",
      [
        "Stop the procedure.",
        "Standing worsens syncope.",
        "Don't abandon.",
      ],
      "easy",
    ]
  ],
  "professional-practice": [
    [
      "A PCT is asked to perform a task outside their training/facility scope. They should:",
      "Refuse politely and inform the nurse/supervisor so it can be reassigned",
      ["Attempt it secretly", "Document that they did it without doing it", "Ask a visitor to do it"],
      "Stay within scope; patient safety requires trained personnel.",
      [
        "Secret attempts risk harm.",
        "False documentation is fraud.",
        "Visitors aren't staff.",
      ],
      "easy",
    ],
    [
      "HIPAA requires PCTs to:",
      "Access only the minimum necessary PHI for their job duties",
      ["Read all celebrity charts for curiosity", "Discuss patients in elevators loudly", "Post patient photos without authorization"],
      "Curiosity viewing and gossip are violations.",
      [
        "Curiosity is prohibited.",
        "Public discussion breaches privacy.",
        "Photos need authorization.",
      ],
      "easy",
    ],
    [
      "Therapeutic communication includes:",
      "Open-ended questions, empathy, and clarifying without judging",
      ["Belittling fears", "False reassurance that 'nothing is wrong' when symptoms exist", "Interrupting constantly"],
      "Support emotional safety while gathering accurate information.",
      [
        "Belittling harms trust.",
        "False reassurance blocks reporting.",
        "Interruptions block expression.",
      ],
      "easy",
    ],
    [
      "Chain of command means:",
      "Report issues to the immediate supervisor/nurse per facility structure",
      ["Call the media first always", "Only talk to the CEO for every linen request", "Ignore problems"],
      "Escalate clinical/safety concerns through proper channels promptly.",
      [
        "Media first violates policy/privacy.",
        "Right level of chain for the issue.",
        "Ignoring harms patients.",
      ],
      "easy",
    ],
    [
      "Cultural sensitivity includes:",
      "Respecting beliefs/preferences and using interpreters when language barriers exist",
      ["Forcing eye contact if culturally uncomfortable", "Speaking louder English only as the sole strategy", "Mocking rituals"],
      "Qualified interpreters beat family translation for clinical accuracy when possible.",
      [
        "Eye contact norms vary.",
        "Louder ≠ clearer language access.",
        "Mockery unethical.",
      ],
      "medium",
    ],
    [
      "If you make a documentation error, you should:",
      "Correct per facility policy (e.g., single line, initial, date)—never erase obliterating entries",
      ["Use white-out heavily and rewrite history", "Delete the entire record quietly", "Blame another PCT in the note without facts"],
      "Legal records must show transparent corrections.",
      [
        "White-out is improper.",
        "Deleting records is misconduct.",
        "False blame is unethical.",
      ],
      "medium",
    ],
    [
      "Patient rights include:",
      "Privacy, respectful care, and involvement in care decisions as applicable",
      ["Unlimited access to other patients' records", "Right to abuse staff without limits", "Right to demand untrained staff perform surgery"],
      "Rights come with responsibilities; staff also deserve safety.",
      [
        "Others' records are private.",
        "Abuse not a right.",
        "Surgery needs licensed practitioners.",
      ],
      "easy",
    ],
    [
      "A conflict with a coworker should be handled by:",
      "Addressing privately and professionally, then involving supervisor if unresolved/safety issue",
      ["Yelling at the nurses' station", "Posting complaints on social media with patient details", "Sabotaging their assignments"],
      "Professional conflict resolution protects teamwork and patients.",
      [
        "Public yelling unprofessional.",
        "Social media with PHI illegal.",
        "Sabotage is misconduct.",
      ],
      "easy",
    ],
    [
      "Incident reports are used to:",
      "Document unusual events for quality improvement and risk management—not typically filed in the patient chart as the progress note substitute",
      ["Punish patients publicly", "Replace all clinical charting forever", "Be shared on TikTok"],
      "Follow facility policy on what goes in chart vs incident system.",
      [
        "Not public punishment.",
        "Clinical charting still required.",
        "Social sharing prohibited.",
      ],
      "hard",
    ],
    [
      "Professional appearance and punctuality matter because they:",
      "Support patient trust, infection control, and team reliability",
      ["Have no impact on care", "Replace the need for skills", "Allow skipping hand hygiene"],
      "Uniforms, ID badges, and short nails often relate to safety policies.",
      [
        "Impact is real.",
        "Skills still essential.",
        "Hygiene still required.",
      ],
      "easy",
    ]
  ],
};
