/** NHA CCMA — 40 curated MCQs */
export const topics = {
  "clinical-patient-care": [
    [
      "Which site is generally preferred for an adult intramuscular injection of a routine vaccine dose?",
      "Deltoid muscle (upper arm) when volume is appropriate",
      ["Gluteus maximus without landmarking", "Subcutaneous tissue of the abdomen only", "Intravenous antecubital vein"],
      "For many adult IM vaccines, the deltoid is preferred when the volume fits; proper landmarking avoids nerves/vessels. Route must match the order.",
      [
        "Dorsogluteal without landmarks risks sciatic nerve injury and is often avoided.",
        "Abdomen is a common SQ site, not the default IM vaccine site.",
        "IV is a different route requiring specific authorization/training.",
      ],
      "easy",
    ],
    [
      "When measuring an adult oral temperature with an electronic probe, the CMA should:",
      "Place the probe under the tongue in the posterior sublingual pocket and wait for the signal",
      ["Place the probe against the forehead without skin contact", "Insert the probe into the ear canal for oral readings", "Leave the probe in ice water first"],
      "Oral electronic thermometers read from the sublingual pocket; technique differs for tympanic/temporal devices.",
      [
        "Forehead readings use temporal methods, not oral probes.",
        "Ear probes are tympanic, not oral.",
        "Ice water would falsify the reading.",
      ],
      "easy",
    ],
    [
      "Which vital sign change most urgently suggests possible orthostatic hypotension when a patient stands?",
      "A significant drop in blood pressure with dizziness on standing",
      ["A slight rise in temperature after walking", "Unchanged pulse and BP with no symptoms", "Increased respiratory rate only after laughing"],
      "Orthostatic hypotension is a drop in BP (often with HR rise) on standing, risking syncope—assist and report per protocol.",
      [
        "Mild activity temperature change is not orthostasis.",
        "No change without symptoms is not orthostatic hypotension.",
        "Laugh-related breathing changes are not the definition.",
      ],
      "medium",
    ],
    [
      "Proper technique for adult blood pressure measurement includes:",
      "Using a cuff with bladder width/length appropriate for arm circumference, arm at heart level",
      ["Using the smallest cuff available for all adults", "Taking BP over thick clothing for comfort", "Supporting the arm below heart level"],
      "Wrong cuff size and arm position cause inaccurate BP; follow standard technique.",
      [
        "Too-small cuffs falsely elevate readings.",
        "Clothing can distort measurements.",
        "Arm below heart level can raise readings.",
      ],
      "medium",
    ],
    [
      "When assisting with a clean-catch midstream urine collection, the CMA should instruct the patient to:",
      "Cleanse the area as directed, void a small amount, then collect midstream in a sterile container",
      ["Collect the first few drops only into a nonsterile cup", "Add soap to the specimen to reduce bacteria", "Fill the container from a bedpan that sat overnight"],
      "Midstream clean-catch reduces contamination for culture/UA; sterile container and proper cleansing matter.",
      [
        "First drops are more contaminated.",
        "Soap ruins the specimen.",
        "Stale bedpan urine is unacceptable for culture.",
      ],
      "easy",
    ],
    [
      "Which action is correct when applying a 12-lead ECG electrodes (text concepts)?",
      "Place limb and precordial electrodes on clean, dry skin at standard anatomic locations",
      ["Place all six chest leads on the left scapula", "Apply electrodes over thick lotion without cleaning", "Put V1–V6 in a random order for variety"],
      "Accurate ECG placement requires correct landmarks and good skin contact; lotion and wrong sites distort tracings.",
      [
        "Scapular placement is incorrect for standard precordial leads.",
        "Lotion increases artifact.",
        "Lead order/sites are standardized.",
      ],
      "medium",
    ],
    [
      "A patient reports an allergy to penicillin before an injection. The CMA should:",
      "Hold the medication and notify the provider/nurse per protocol before giving it",
      ["Give a half dose to test tolerance", "Document the allergy after giving the full dose", "Substitute any antibiotic available in the cabinet"],
      "Allergies must be verified and escalated; MAs do not independently change or challenge allergies.",
      [
        "Partial doses are still dangerous challenges.",
        "Documenting after exposure is unsafe.",
        "Substitution requires a provider order.",
      ],
      "easy",
    ],
    [
      "Which statement about pulse oximetry is correct?",
      "It estimates oxygen saturation and can be affected by poor perfusion, nail polish, or motion",
      ["It directly measures arterial blood pH", "It replaces the need for any vital signs", "Nail polish always improves accuracy"],
      "SpO2 is a useful estimate but has limitations; interpret with clinical context.",
      [
        "pH requires blood gas analysis.",
        "Other vitals remain necessary.",
        "Dark nail polish can impair readings.",
      ],
      "medium",
    ],
    [
      "For a subcutaneous insulin injection, an appropriate general site rotation principle is:",
      "Rotate sites systematically within approved areas to reduce lipodystrophy",
      ["Use the exact same puncture point every day", "Always inject IM into the deltoid for insulin", "Inject through clothing to save time"],
      "Site rotation prevents tissue changes that alter absorption; insulin is typically SQ, not IM, unless specifically ordered.",
      [
        "Same point causes tissue damage.",
        "Insulin is usually SQ.",
        "Injecting through clothing is improper.",
      ],
      "medium",
    ],
    [
      "When performing adult height/weight for BMI screening, the CMA should:",
      "Use calibrated scales, remove heavy outerwear/shoes per protocol, and record accurately",
      ["Estimate weight from the last visit without measuring", "Ask the patient to hold a heavy bag on the scale", "Round all weights to the nearest 20 pounds"],
      "Accurate anthropometrics require proper technique and calibrated equipment for clinical decisions.",
      [
        "Estimates are not acceptable for ordered measurements.",
        "Extra items falsify weight.",
        "Excessive rounding loses clinical value.",
      ],
      "easy",
    ],
  ],
  "phlebotomy-ekg": [
    [
      "The recommended order of draw for venipuncture (CLSI concept) is designed primarily to:",
      "Prevent additive carryover that can alter test results",
      ["Speed up clotting in every tube equally", "Eliminate the need for patient identification", "Allow reuse of needles between patients"],
      "Order of draw reduces cross-contamination of additives between tubes that could skew chemistry/coag results.",
      [
        "Order of draw is about contamination, not universal clotting speed.",
        "Patient ID is still mandatory.",
        "Needle reuse is never acceptable.",
      ],
      "medium",
    ],
    [
      "Which vein in the antecubital area is often preferred for venipuncture when accessible?",
      "Median cubital vein",
      ["Femoral vein", "Jugular vein", "Dorsal pedis artery"],
      "Median cubital is typically well anchored and accessible; arteries and central veins are not routine ambulatory phlebotomy sites.",
      [
        "Femoral access is advanced/emergency.",
        "Jugular is not routine outpatient phlebotomy.",
        "Arteries are not used for standard venipuncture.",
      ],
      "easy",
    ],
    [
      "After withdrawing the needle from a venipuncture, the CMA should immediately:",
      "Activate the safety device and apply pressure with gauze per protocol",
      ["Recap the needle using two hands", "Leave the tube uncapped on the counter", "Shake a coagulation tube vigorously for 30 seconds"],
      "Safety activation and hemostasis prevent needlesticks and hematomas; coag tubes are gently inverted, not shaken.",
      [
        "Two-handed recapping is a classic needlestick risk.",
        "Open tubes risk contamination/spills.",
        "Vigorous shaking can hemolyze/activate specimens.",
      ],
      "easy",
    ],
    [
      "A light-blue top tube (sodium citrate) for coagulation testing must be:",
      "Filled to the correct volume for the proper blood-to-additive ratio",
      ["Underfilled intentionally to save time", "Used only for CBC testing", "Frozen solid before transport always"],
      "Citrate tubes require full fill for accurate PT/INR/aPTT; underfilling falsely prolongs results.",
      [
        "Underfilling invalidates coag tests.",
        "CBC uses EDTA (lavender), not light blue.",
        "Routine coag is not frozen solid before all transports.",
      ],
      "hard",
    ],
    [
      "Which ECG lead placement statement is correct for V1?",
      "Fourth intercostal space at the right sternal border",
      ["Fifth intercostal space midclavicular line left", "Second intercostal space left midaxillary line", "Directly over the umbilicus"],
      "V1 is 4th ICS right sternal border; V4 is 5th ICS midclavicular; incorrect placement changes morphology.",
      [
        "That describes V4, not V1.",
        "That is not standard V1.",
        "Umbilicus is unrelated to precordial leads.",
      ],
      "medium",
    ],
    [
      "Muscle tremor artifact on an ECG is best reduced by:",
      "Ensuring the patient is warm, supported, and relaxed with good electrode contact",
      ["Increasing paper speed only", "Removing all limb leads", "Having the patient exercise during the tracing"],
      "Somatic tremor from shivering/tension creates artifact; comfort and contact improve quality.",
      [
        "Paper speed does not remove tremor source.",
        "Limb leads are required for a 12-lead.",
        "Exercise increases artifact.",
      ],
      "medium",
    ],
    [
      "Hemolysis of a blood specimen is most often caused by:",
      "Traumatic draws, undersized needles with excessive force, or vigorous shaking",
      ["Using a sterile needle", "Proper gentle inversions", "Correct tourniquet time under 1 minute"],
      "Rough handling and technique errors rupture RBCs, altering potassium and other analytes.",
      [
        "Sterility alone does not cause hemolysis.",
        "Gentle inversions are correct technique.",
        "Short tourniquet time helps prevent issues.",
      ],
      "easy",
    ],
    [
      "Before drawing blood, the most critical patient safety step is:",
      "Positive patient identification using two identifiers",
      ["Asking only the room number", "Labeling tubes before approaching the patient", "Skipping the order review if busy"],
      "Wrong-patient draws are serious errors; use name + DOB (or facility policy) and match the order.",
      [
        "Room number alone is insufficient.",
        "Tubes should be labeled at the bedside after draw per policy.",
        "Order review prevents wrong tests/patients.",
      ],
      "easy",
    ],
    [
      "A tourniquet left on longer than one minute can cause:",
      "Hemoconcentration and altered laboratory values",
      ["Increased specimen sterility", "Automatic clotting factor activation that always helps coag tests", "Lower potassium from dilution only"],
      "Prolonged tourniquet time concentrates blood components and can elevate analytes such as potassium.",
      [
        "It does not improve sterility.",
        "It can harm coag/chemistry accuracy.",
        "Potassium often rises with hemoconcentration/hemolysis, not simple dilution.",
      ],
      "hard",
    ],
    [
      "Which statement about capillary (fingerstick) collection is correct?",
      "Wipe away the first drop when protocol requires and avoid milking the finger excessively",
      ["Use the thumb as the preferred adult site always", "Milk the finger forcefully to get a large sample", "Collect into citrate light-blue microtubes for routine glucose only"],
      "Excessive milking introduces tissue fluid; site selection and first-drop rules follow protocol for accurate POCT/lab results.",
      [
        "Thumbs are thicker/callused and usually avoided.",
        "Milking dilutes/contaminates the sample.",
        "Glucose POCT uses appropriate devices/strips, not coag citrate tubes.",
      ],
      "medium",
    ],
  ],
  "safety-infection": [
    [
      "Standard Precautions mean that healthcare workers should:",
      "Assume all blood and body fluids may be infectious and use appropriate barriers",
      ["Use PPE only for patients with known HIV", "Wash gloves instead of changing them between patients", "Skip hand hygiene if gloves were worn"],
      "Standard Precautions protect against unrecognized infection; gloves do not replace hand hygiene.",
      [
        "Known-status-only PPE is outdated practice.",
        "Gloves are single-use between patients.",
        "Hand hygiene is still required after glove removal.",
      ],
      "easy",
    ],
    [
      "The most important action to prevent healthcare-associated infection is:",
      "Performing hand hygiene at appropriate moments",
      ["Wearing jewelry under gloves for grip", "Using the same gown all day for every patient", "Disabling sharps containers to save space"],
      "Hand hygiene is the cornerstone of infection prevention in clinical settings.",
      [
        "Jewelry harbors microbes and tears gloves.",
        "Gowns are changed per policy/patient.",
        "Sharps containers must remain available and functional.",
      ],
      "easy",
    ],
    [
      "A contaminated needle should be disposed of by:",
      "Placing it immediately into a puncture-resistant sharps container without recapping",
      ["Bending it carefully then placing in the trash", "Recapping with two hands then pocketing it", "Leaving it on the mayo stand for housekeeping"],
      "OSHA-aligned practice: no two-handed recapping; immediate sharps disposal prevents needlesticks.",
      [
        "Bending and trash disposal is prohibited.",
        "Two-handed recapping is high risk.",
        "Leaving sharps out endangers others.",
      ],
      "easy",
    ],
    [
      "Which PPE item is most critical when there is a risk of splash to the eyes?",
      "Eye protection (goggles or face shield)",
      ["Shoe covers only", "A cloth scarf", "Sterile gloves without any face protection"],
      "Mucous membrane exposure requires eye/face protection appropriate to the task.",
      [
        "Shoe covers do not protect eyes.",
        "Scarves are not PPE.",
        "Gloves alone do not protect eyes.",
      ],
      "easy",
    ],
    [
      "Airborne precautions (concept) are used for diseases such as measles/TB and typically require:",
      "A fit-tested respirator (e.g., N95) and appropriate room controls per facility policy",
      ["No mask if the patient is asymptomatic", "Surgical mask only for the patient and none for staff", "Gloves as the only PPE"],
      "Airborne pathogens need respiratory protection and engineering controls beyond Standard Precautions alone.",
      [
        "Asymptomatic status does not remove airborne rules when indicated.",
        "Staff need appropriate respirators for airborne diseases.",
        "Gloves alone are insufficient.",
      ],
      "medium",
    ],
    [
      "When cleaning an exam room between patients, the CMA should:",
      "Disinfect high-touch surfaces with EPA-registered product per contact time instructions",
      ["Wipe once with plain water only", "Skip surfaces that look clean", "Spray disinfectant and immediately seat the next patient without wait time"],
      "Effective disinfection requires correct product and wet contact time; appearance alone is unreliable.",
      [
        "Water alone is not disinfection.",
        "Invisible contamination is common.",
        "Contact time matters for kill claims.",
      ],
      "medium",
    ],
    [
      "If a CMA sustains a needlestick from a used needle, the first priority is:",
      "Wash the site, report immediately, and follow occupational exposure protocol",
      ["Hide the incident to avoid paperwork", "Finish all scheduled patients first", "Apply bleach into the wound"],
      "Prompt washing, reporting, and evaluation enable timely prophylaxis and documentation.",
      [
        "Concealment delays care and violates policy.",
        "Delay risks missing treatment windows.",
        "Harsh chemicals can worsen tissue injury.",
      ],
      "easy",
    ],
    [
      "Which statement about sterile fields is correct?",
      "If sterility is in doubt, consider it contaminated",
      ["Talking and reaching over the field is always encouraged", "Wet sterile fields remain sterile indefinitely", "Nonsterile items may rest on the sterile drape briefly"],
      "Aseptic principle: when in doubt, replace; moisture and nonsterile contact contaminate fields.",
      [
        "Talking/reaching shed particles onto the field.",
        "Wicking moisture contaminates.",
        "Nonsterile contact contaminates immediately.",
      ],
      "medium",
    ],
    [
      "Biohazardous regulated medical waste (sharps/saturated blood items) should be:",
      "Placed in labeled biohazard containers appropriate to the waste type",
      ["Mixed into regular office paper recycling", "Taken home for disposal", "Flushed into public restrooms"],
      "OSHA/CDC-aligned practice uses designated biohazard disposal streams.",
      [
        "Recycling streams are not for biohazard sharps/blood.",
        "Home disposal is illegal/unsafe.",
        "Flushing biohazard waste is improper.",
      ],
      "easy",
    ],
    [
      "Contact precautions are primarily intended to prevent transmission via:",
      "Direct or indirect contact with the patient or contaminated surfaces",
      ["Only long-range airborne spread across buildings", "Foodborne illness exclusively", "Radiation exposure"],
      "Contact precautions add gown/gloves and dedicated equipment for organisms spread by touch.",
      [
        "Airborne is a different precaution category.",
        "Foodborne control is separate.",
        "Radiation is not an infectious contact issue.",
      ],
      "medium",
    ],
  ],
  "admin-communication": [
    [
      "Under HIPAA, protected health information (PHI) may be disclosed without authorization when:",
      "Required for treatment, payment, or healthcare operations within allowed rules, or as otherwise permitted/required by law",
      ["Posted to social media for education if names are nicknames", "Shared with any friend who asks politely", "Sold to marketers without patient knowledge"],
      "TPO and other legal permissions exist, but casual/social disclosures are prohibited.",
      [
        "Social media PHI disclosures are violations.",
        "Friends are not in the care team by default.",
        "Sale of PHI without authorization is illegal.",
      ],
      "medium",
    ],
    [
      "When scheduling a patient who needs fasting labs, the CMA should:",
      "Communicate fasting requirements and appointment timing clearly before the visit",
      ["Omit instructions to avoid scaring the patient", "Tell them to eat a large meal immediately before labs", "Schedule without checking order requirements"],
      "Clear prep instructions prevent cancelled draws and inaccurate results.",
      [
        "Withholding instructions causes failures.",
        "Eating before fasting labs invalidates tests.",
        "Order review is required for proper prep.",
      ],
      "easy",
    ],
    [
      "A patient is angry about wait time. The most professional first response is:",
      "Acknowledge the frustration, apologize for the wait, and offer realistic updates/help",
      ["Argue that other patients matter more", "Ignore them until they calm down fully", "Raise your voice to match theirs"],
      "Therapeutic communication uses empathy and information without escalating conflict.",
      [
        "Arguing worsens conflict.",
        "Ignoring can increase agitation.",
        "Matching anger unprofessionally escalates.",
      ],
      "easy",
    ],
    [
      "Which is an example of proper EHR documentation practice?",
      "Enter objective, timely, accurate notes using approved abbreviations only",
      ["Backdate entries to make the chart look complete", "Copy-paste another patient's note without review", "Delete unfavorable vital signs permanently"],
      "Documentation must be truthful, timely, and patient-specific; falsification is illegal/unethical.",
      [
        "Backdating is fraudulent.",
        "Wrong-patient copy-paste is a serious error.",
        "Altering clinical data is misconduct.",
      ],
      "medium",
    ],
    [
      "Informed consent for a procedure means the patient:",
      "Understands risks, benefits, and alternatives and agrees voluntarily",
      ["Signs any form without explanation", "Is coerced by staff to avoid delays", "Has a family member sign when the patient is competent and refuses"],
      "Consent requires comprehension and voluntariness; competent adults decide for themselves.",
      [
        "Signature without information is not informed consent.",
        "Coercion invalidates consent.",
        "Competent refusals must be respected and escalated appropriately.",
      ],
      "medium",
    ],
    [
      "When verifying insurance eligibility, the CMA should:",
      "Confirm coverage/benefits as directed and communicate patient financial responsibility per policy",
      ["Guarantee that all services will be paid 100%", "Ignore referral requirements", "Bill a different patient's insurance to get payment"],
      "Eligibility checks reduce denials; guarantees and fraudulent billing are improper.",
      [
        "Staff should not guarantee payment.",
        "Referrals/authorizations matter for coverage.",
        "Using another patient's insurance is fraud.",
      ],
      "easy",
    ],
    [
      "Which telephone triage action is within a typical CMA scope?",
      "Follow office protocols to gather information and escalate urgent symptoms to licensed clinicians",
      ["Diagnose chest pain as anxiety and advise no care", "Prescribe antibiotics over the phone", "Cancel a provider's urgent referral independently"],
      "MAs use protocols and escalate; diagnosis and prescribing are licensed-provider functions.",
      [
        "Diagnosing is outside CMA scope.",
        "Prescribing is not CMA scope.",
        "Clinical referral changes need clinician direction.",
      ],
      "hard",
    ],
    [
      "A release of medical records to a third party generally requires:",
      "A valid patient authorization unless a legal exception applies",
      ["Only a verbal okay from any caller", "Provider preference without patient knowledge", "Payment of a bribe to records staff"],
      "HIPAA requires appropriate authorization or permitted disclosure pathways before releasing records.",
      [
        "Caller verbal requests are insufficient alone.",
        "Patients control many disclosures.",
        "Bribes are illegal.",
      ],
      "easy",
    ],
    [
      "Cultural humility in patient communication includes:",
      "Asking respectfully about needs/preferences and avoiding assumptions",
      ["Speaking only slang to seem friendly", "Refusing interpreters when language barriers exist", "Mocking traditional remedies"],
      "Respectful inquiry and qualified interpretation improve safety and trust.",
      [
        "Slang can confuse and disrespect.",
        "Interpreters are required for effective communication when needed.",
        "Mockery is unethical.",
      ],
      "easy",
    ],
    [
      "Which is the correct action if you notice another staff member accessing charts without a job-related need?",
      "Report the privacy incident per facility policy",
      ["Ask them for gossip details from the chart", "Ignore it because they are senior", "Post about it on social media with patient initials"],
      "Curiosity viewing is a HIPAA violation; report through proper channels without further disclosure.",
      [
        "Participating worsens the breach.",
        "Seniority does not authorize snooping.",
        "Social posts create additional breaches.",
      ],
      "medium",
    ],
  ],
};
