/** NHA CMAA — 40 curated MCQs */
export const topics = {
  "scheduling-front": [
    [
      "When scheduling a new patient appointment, the CMAA should collect:",
      "Demographics, insurance info, chief reason for visit, and provider/time needs",
      ["Only the patient's favorite color", "No callback number", "Diagnosis codes invented without a provider"],
      "Complete intake reduces denials and no-shows; MAs/admins don't invent diagnoses.",
      [
        "Color irrelevant.",
        "Need contact info.",
        "Coding needs clinical documentation.",
      ],
      "easy",
    ],
    [
      "A matrix/template in scheduling is used to:",
      "Block times for visit types, procedures, and provider preferences",
      ["Bill insurance automatically without claims", "Replace the need for patient names", "Store PHI on public social media"],
      "Templates improve flow (physicals vs acute slots, catch-up time).",
      [
        "Billing is separate.",
        "Names still required.",
        "PHI not for social media.",
      ],
      "easy",
    ],
    [
      "Double-booking may be appropriate when:",
      "Two patients can be seen in overlapping slots planned for short visits/provider workflow",
      ["Used randomly without clinical judgment causing chronic backlog", "Patients are never informed of delays", "It replaces triage of urgent needs"],
      "Intentional overlap differs from chaotic overbooking; communicate wait times.",
      [
        "Random overload harms care.",
        "Communication required.",
        "Urgency still triaged.",
      ],
      "medium",
    ],
    [
      "When a patient arrives late, the CMAA should:",
      "Follow office policy—possibly reschedule or fit in without disrupting critical care",
      ["Refuse all future care permanently without policy", "Argue at the front desk loudly with PHI details", "Skip checking them in entirely while they wait indefinitely without update"],
      "Policies balance fairness and access; maintain professionalism/privacy.",
      [
        "Permanent bans need proper process.",
        "Loud PHI breaches privacy.",
        "Updates/customer service matter.",
      ],
      "easy",
    ],
    [
      "Referral scheduling often requires verifying:",
      "Insurance authorization/referral numbers and specialist network status",
      ["Only the referring doctor's hobbies", "That no records are sent ever", "Cash prices for the specialist without patient consent discussions when relevant finances apply—skip all verification"],
      "Missing auth causes denials; collect/send needed clinical records.",
      [
        "Hobbies irrelevant.",
        "Records usually needed.",
        "Eligibility/auth verification is core.",
      ],
      "medium",
    ],
    [
      "Wave scheduling means:",
      "Several patients scheduled at the same hour and seen in arrival/order workflow",
      ["One patient per day only", "No appointments—walk-ins only always", "Random cancellation of all new patients"],
      "Wave/modified wave are classic office scheduling methods taught in admin programs.",
      [
        "Not one per day.",
        "Walk-in systems differ.",
        "Not cancellation schemes.",
      ],
      "medium",
    ],
    [
      "An encounter form/superbill is used to:",
      "Capture services/procedures/diagnoses for billing from the visit",
      ["Replace the medical record entirely", "Serve as a controlled substance Rx pad always", "Check out library books"],
      "Superbills feed claim creation; documentation must still support codes.",
      [
        "EHR/chart remains legal record.",
        "Not a DEA Rx form inherently.",
        "Not library.",
      ],
      "easy",
    ],
    [
      "When handling a phone triage-type call about chest pain, the CMAA should:",
      "Follow emergency protocols—advise calling 911/ER per script and escalate immediately",
      ["Schedule a visit in three months without escalation", "Diagnose GERD confidently", "Ignore because they are not clinical"],
      "Admin staff use protocols; life-threat symptoms get emergency direction.",
      [
        "Delay dangerous.",
        "Don't diagnose.",
        "Escalation is required.",
      ],
      "easy",
    ],
    [
      "No-show policies should be:",
      "Applied consistently, documented, and explained in patient communications",
      ["Used to publicly shame patients in the waiting room", "Different for every staff mood", "Hidden from patients entirely always"],
      "Clear policies reduce conflict and support continuity.",
      [
        "Public shame unethical/HIPAA risk.",
        "Consistency matters.",
        "Patients should know expectations.",
      ],
      "medium",
    ],
    [
      "Cluster scheduling groups:",
      "Similar appointments together (e.g., all physicals in a block)",
      ["All emergency surgeries in the lobby", "No like appointments ever", "Only billing calls at midnight without staffing"],
      "Clustering improves efficiency for rooms/equipment/staffing.",
      [
        "Emergencies need appropriate settings.",
        "Clustering is the definition.",
        "Staffing must match.",
      ],
      "easy",
    ]
  ],
  "medical-records": [
    [
      "The legal health record is best described as:",
      "Documentation of care used for clinical, legal, and billing purposes under retention rules",
      ["Only sticky notes never entered", "The waiting room sign-in clipboard as the full chart", "Social media messages exclusively"],
      "Entries should be timely, accurate, authenticated, and complete.",
      [
        "Sticky notes inadequate alone.",
        "Sign-in isn't the full record.",
        "Social media not the legal record.",
      ],
      "easy",
    ],
    [
      "HIPAA allows PHI disclosure without authorization for:",
      "Treatment, payment, and healthcare operations (TPO) under the Privacy Rule",
      ["Marketing sale of PHI without limits always", "Public gossip", "Employer curiosity without involvement"],
      "Minimum necessary applies to many payment/operations uses; treatment has nuances.",
      [
        "Marketing often needs auth.",
        "Gossip prohibited.",
        "Employers generally need authorization/other legal basis.",
      ],
      "medium",
    ],
    [
      "A valid authorization to release records generally includes:",
      "Who, what, to whom, purpose, expiration, and signature/date elements",
      ["Only a verbal 'sure' from an unknown caller", "Provider initials alone forever", "Blank unsigned forms filled later by staff creatively"],
      "Defective authorizations should be rejected/fixed before release.",
      [
        "Caller verbal insufficient alone.",
        "Need proper patient/personal representative signature.",
        "No creative backdating.",
      ],
      "medium",
    ],
    [
      "Correcting an EHR error should follow policy such as:",
      "Addendum/correction that preserves the original entry (no obliteration)",
      ["Deleting the encounter entirely to hide the mistake", "Altering another clinician's note silently", "Inserting false times"],
      "Audit trails track changes; honesty protects legal integrity.",
      [
        "Deletion to hide is misconduct.",
        "Don't alter others' notes improperly.",
        "False times fraudulent.",
      ],
      "easy",
    ],
    [
      "ROI (release of information) turnaround should:",
      "Follow federal/state timelines and facility procedures with tracking logs",
      ["Ignore urgent care continuum needs always", "Release entire charts to anyone paying cash without checks", "Mail records to unverified addresses casually"],
      "Verify identity/authority; account for sensitive records (psych/HIV/substance) special rules.",
      [
        "Urgent TPO pathways exist.",
        "Identity/authority required.",
        "Address verification matters.",
      ],
      "hard",
    ],
    [
      "The Notice of Privacy Practices (NPP) is provided to:",
      "Patients to explain uses of PHI and patient rights, with acknowledgment efforts",
      ["Only pharmaceutical sales reps", "No one—it's optional wallpaper", "Competitors for marketing lists"],
      "Covered entities must make NPP available and retain acknowledgments when required.",
      [
        "Not for drug reps as the patient duty.",
        "Required, not optional.",
        "Not a marketing list tool.",
      ],
      "easy",
    ],
    [
      "Minimum necessary standard means:",
      "Limit PHI access/use/disclosure to the least needed for the purpose (with treatment exceptions nuances)",
      ["Everyone in the building may read all charts", "Reception must memorize full psychiatric notes", "Billers need full psychotherapy process notes always"],
      "Role-based access implements minimum necessary.",
      [
        "Open access violates HIPAA.",
        "Reception needs scheduling-minimum.",
        "Specially protected notes have extra limits.",
      ],
      "medium",
    ],
    [
      "Retention of adult medical records is:",
      "Governed by state law and payer/accreditation policies (often years beyond last visit)",
      ["One week maximum always nationwide", "Destroyed immediately after each visit always", "Kept forever in the front desk drawer unlocked with no policy"],
      "Know that retention varies; follow the strictest applicable rule/policy.",
      [
        "One week too short generally.",
        "Immediate destruction improper.",
        "Secure storage required.",
      ],
      "hard",
    ],
    [
      "A personal representative for an adult patient is typically:",
      "Someone with legal authority (e.g., healthcare power of attorney) as defined by law",
      ["Any coworker", "A journalist", "Anyone who knows the patient's birthday"],
      "Verify authority before discussing PHI or obtaining authorizations.",
      [
        "Coworkers lack authority by default.",
        "Press has no right.",
        "DOB knowledge ≠ authority.",
      ],
      "easy",
    ],
    [
      "Faxing PHI safely includes:",
      "Verifying numbers, using cover sheets, and placing machines in secure areas",
      ["Faxing to wrong numbers without verification routinely", "Posting faxes on public boards", "Disabling transmission audits always"],
      "Misdirected faxes are common breaches—confirm before send.",
      [
        "Verification prevents breaches.",
        "Public posting is disclosure.",
        "Audits help investigate.",
      ],
      "easy",
    ]
  ],
  "billing-coding-basics": [
    [
      "CPT codes primarily describe:",
      "Procedures and services performed",
      ["Diagnoses only", "Drug NDCs only", "Place of service only"],
      "ICD-10-CM = diagnoses; CPT/HCPCS = services/supplies.",
      [
        "Diagnoses are ICD.",
        "NDC identifies drugs.",
        "POS is a claim field.",
      ],
      "easy",
    ],
    [
      "A claim denial for 'timely filing' means:",
      "The claim was submitted after the payer's deadline",
      ["The patient was on time for the visit", "The provider's license expired that day always as the only meaning", "CPT and ICD mismatched only"],
      "Track filing limits; appeal/correct within payer rules.",
      [
        "Appointment punctuality unrelated.",
        "License issues different denial.",
        "Code mismatch is another denial reason.",
      ],
      "easy",
    ],
    [
      "Coordination of benefits (COB) determines:",
      "Which insurance pays first when a patient has multiple coverages",
      ["Which exam room to use", "The provider's lunch break", "Whether SOAP notes are required"],
      "Primary vs secondary billing order prevents overpayment.",
      [
        "Rooms unrelated.",
        "Lunch unrelated.",
        "Docs always required clinically.",
      ],
      "medium",
    ],
    [
      "An Advanced Beneficiary Notice (ABN) relates to:",
      "Medicare situations where a service may not be covered and patient may be financially liable",
      ["Always guaranteeing Medicaid payment", "Workers' comp exclusive remedy only", "Dental cleanings exclusively worldwide"],
      "Proper ABN issuance matters before the service when required.",
      [
        "Not a Medicaid guarantee.",
        "Different systems.",
        "Not only dental.",
      ],
      "medium",
    ],
    [
      "ICD-10-CM codes should be selected based on:",
      "Provider documentation to the highest specificity supported",
      ["Whichever code pays most regardless of documentation", "Patient preference for scary-sounding diseases", "Random codebook pages"],
      "Codes must be supported; upcoding is fraud risk.",
      [
        "Payment-driven coding noncompliant.",
        "Patients don't pick DX codes.",
        "Random improper.",
      ],
      "easy",
    ],
    [
      "A clean claim is one that:",
      "Has complete/accurate data enabling payer processing without pending for missing info",
      ["Is printed on green paper only", "Contains no diagnosis", "Uses nickname instead of legal name always"],
      "Front-desk data quality (subscriber ID, DOB, NPI, POS) drives clean claims.",
      [
        "Paper color irrelevant.",
        "Diagnosis required generally.",
        "Legal names/IDs needed.",
      ],
      "easy",
    ],
    [
      "Day sheet/accounts receivable concepts help the office track:",
      "Charges, payments, adjustments, and outstanding balances",
      ["Only clinical vitals", "Sterilizer BI results", "Employee blood titers only"],
      "Posting accuracy prevents billing disputes.",
      [
        "Vitals clinical.",
        "BI is SPD/dental.",
        "Titers occupational health.",
      ],
      "easy",
    ],
    [
      "Modifier 25 is used when:",
      "A significant, separately identifiable E/M is billed same day as a procedure",
      ["Bilateral surgery", "Assistant surgeon", "Repeat lab test only"],
      "Documentation must support separateness from the procedure's inherent E/M.",
      [
        "50 bilateral.",
        "80 assistant.",
        "91 repeat clinical diagnostic lab.",
      ],
      "hard",
    ],
    [
      "Patient statements should:",
      "Clearly show dates of service, charges, payments, and amount due with appeal/question contacts",
      ["Include other patients' balances 'for comparison'", "Hide the provider NPI forever when required on claims differently—confuse patients intentionally", "Threaten violence"],
      "Transparent billing is ethical and often regulated by state rules.",
      [
        "Others' PHI forbidden.",
        "Don't intentionally confuse.",
        "Threats illegal.",
      ],
      "easy",
    ],
    [
      "Preauthorization differs from precertification discussions in that both generally mean:",
      "Payer approval processes required before certain services for coverage",
      ["A guarantee of payment in all cases without meeting terms", "Only a clinical consent form", "An OSHA requirement"],
      "Auth doesn't always guarantee final payment if eligibility/medical necessity fails.",
      [
        "Not absolute guarantee.",
        "Consent is separate.",
        "OSHA is safety.",
      ],
      "medium",
    ]
  ],
  "communication-ethics": [
    [
      "Active listening includes:",
      "Paraphrasing, clarifying, and attending to verbal/nonverbal cues",
      ["Interrupting with solutions immediately always", "Looking only at the computer never the patient", "Finishing every sentence for the patient"],
      "Builds rapport and reduces errors in intake.",
      [
        "Interruptions block info.",
        "Eye contact/attention matters culturally appropriately.",
        "Don't overtake their narrative.",
      ],
      "easy",
    ],
    [
      "If a patient is hostile, the CMAA should:",
      "Stay calm, set boundaries, ensure safety, and involve supervisor/security as needed",
      ["Match their insults", "Reveal another patient's information to distract them", "Lock them in a room alone without protocol"],
      "De-escalation and safety first; document incidents.",
      [
        "Insults escalate.",
        "PHI bait is illegal.",
        "Unsafe confinement risks.",
      ],
      "medium",
    ],
    [
      "Empathy differs from sympathy in that empathy:",
      "Seeks to understand the patient's feelings/perspective without necessarily sharing the same emotion",
      ["Means diagnosing their disease", "Requires sharing PHI of similar patients", "Is unprofessional always"],
      "Empathic statements validate experience; remain professional boundaries.",
      [
        "Not diagnosing.",
        "Don't share others' PHI.",
        "Empathy is professional.",
      ],
      "easy",
    ],
    [
      "Ethics of confidentiality means:",
      "Not discussing patient information with unauthorized persons",
      ["Sharing charts with friends for learning without approval", "Posting de-identified funny cases that are actually identifiable", "Selling celebrity visit rumors"],
      "Even 'interesting cases' need authorization or proper de-identification standards.",
      [
        "Friends unauthorized.",
        "Inadequate de-ID fails.",
        "Rumors unethical/illegal.",
      ],
      "easy",
    ],
    [
      "When cultural/language barriers exist, best practice is:",
      "Use qualified interpreters rather than minor children when possible",
      ["Speak louder English only", "Guess medical terms in mime for consent", "Skip informed intake questions"],
      "Language access improves safety and compliance with requirements.",
      [
        "Volume ≠ translation.",
        "Mime inadequate for consent.",
        "Intake still needed.",
      ],
      "medium",
    ],
    [
      "Professional boundaries include:",
      "Avoiding dual relationships that exploit patients and keeping communications appropriate",
      ["Becoming business partners with every patient casually", "Dating patients while they are under active care as best practice", "Accepting lavish gifts that influence scheduling unfairly"],
      "Follow office policies on gifts/relationships.",
      [
        "Dual relationships risky.",
        "Dating patients unethical generally.",
        "Gift policies prevent favoritism.",
      ],
      "medium",
    ],
    [
      "If you overhear coworkers gossiping about a patient's STI, you should:",
      "Remind them of privacy rules and report per policy if needed",
      ["Join in with more details", "Post it anonymously online", "Ignore repeated systemic violations forever"],
      "Everyone is responsible for the privacy culture.",
      [
        "Joining worsens breach.",
        "Online posting is a breach.",
        "Systemic issues need reporting.",
      ],
      "easy",
    ],
    [
      "Informed consent discussions are primarily the responsibility of:",
      "The provider performing the procedure, with CMAA supporting forms/logistics",
      ["The front desk diagnosing risks independently", "The billing company alone", "A pharmaceutical sales rep"],
      "Admin staff witness/organize consents but don't replace clinician disclosure.",
      [
        "Front desk doesn't give clinical informed consent alone.",
        "Billing ≠ consent.",
        "Reps don't consent patients.",
      ],
      "easy",
    ],
    [
      "Customer service recovery after a registration error should include:",
      "Apology, correction, and prevention steps without blaming the patient unfairly",
      ["Hiding the error in claims", "Charging an 'embarrassment fee'", "Yelling that the patient filled forms wrong only"],
      "Service recovery rebuilds trust and reduces complaints/reviews fallout.",
      [
        "Hiding creates compliance risk.",
        "Fees punitive/unethical.",
        "Shared responsibility, professional tone.",
      ],
      "medium",
    ],
    [
      "Workplace harassment should be:",
      "Reported per HR policy; patients and staff deserve a respectful environment",
      ["Accepted as 'just joking' always", "Retaliated against reporters", "Filmed and posted publicly with PHI"],
      "Follow zero-tolerance procedures; protect reporters from retaliation.",
      [
        "Jokes can be harassment.",
        "Retaliation prohibited.",
        "Public posting worsens harm/privacy.",
      ],
      "easy",
    ]
  ],
};
