/** NREMT EMT — 40 curated MCQs */
export const topics = {
  "airway-respiration": [
    [
      "What is the most reliable immediate indicator that bag-valve-mask ventilations are effective?",
      "Visible chest rise with each ventilation",
      ["Gurgling sounds only",
      "Patient ability to speak full sentences during BVM",
      "Cyanosis becoming deeper"],
      "Adequate BVM produces chest rise and improved oxygenation indicators; speaking during BVM means the seal/technique is wrong.",
      [
        "Gurgling suggests secretions needing suction.",
        "Patients cannot speak full sentences during proper BVM seal.",
        "Worsening cyanosis means inadequate ventilation.",
      ],
      "easy",
    ],
    [
      "An adult patient with suspected opioid overdose is unresponsive with slow, shallow respirations. After scene safety and airway opening, the priority intervention is:",
      "Support ventilation with BVM/oxygen and consider naloxone per protocol",
      ["Encourage the patient to walk it off",
      "Give oral fluids",
      "Apply a tourniquet to both arms"],
      "Respiratory depression drives opioid morbidity; ventilate and reverse per protocol.",
      [
        "Ambulation worsens hypoxia risk.",
        "Oral fluids risk aspiration.",
        "Tourniquets are for hemorrhage, not overdose.",
      ],
      "medium",
    ],
    [
      "Which oxygen delivery device typically provides the highest FiO2 for a spontaneously breathing patient when used correctly?",
      "Nonrebreather mask at adequate flow",
      ["Nasal cannula at 1 L/min",
      "Simple face mask at 2 L/min",
      "Room air only"],
      "A properly flushed nonrebreather at high flow delivers high FiO2 versus low-flow nasal cannula.",
      [
        "1 L NC provides low FiO2.",
        "2 L is inadequate for a simple mask and still lower than NRB.",
        "Room air is ~21% oxygen.",
      ],
      "easy",
    ],
    [
      "Stridor in an upper-airway obstruction patient suggests:",
      "Partial obstruction at or above the larynx producing high-pitched inspiratory sound",
      ["Normal quiet breathing",
      "Only lower-lobe pneumonia",
      "Cardiac tamponade exclusively"],
      "Stridor is a hallmark of upper airway narrowing and is an emergency warning sign.",
      [
        "Quiet breathing is not stridor.",
        "Pneumonia causes other sounds.",
        "Tamponade presents with shock/Beck-type findings, not stridor.",
      ],
      "medium",
    ],
    [
      "When suctioning an adult airway, a key safety limit is:",
      "Limit suction attempts to about 15 seconds and preoxygenate as able",
      ["Suction continuously for several minutes without pause",
      "Never suction if vomit is present",
      "Suction only after intubation in all cases"],
      "Prolonged suction causes hypoxia; clear the airway in brief attempts.",
      [
        "Long continuous suction desaturates patients.",
        "Vomit is a primary indication to suction.",
        "BLS suction may be needed before advanced airway.",
      ],
      "medium",
    ],
    [
      "The head-tilt/chin-lift is generally avoided in trauma patients because:",
      "It may worsen cervical spine injury; use jaw-thrust when indicated",
      ["It always causes vomiting",
      "It increases blood pressure too much",
      "It is illegal in all EMS systems"],
      "Suspected c-spine injury warrants jaw-thrust with spinal motion restriction considerations.",
      [
        "Vomiting is not the primary reason.",
        "BP effect is not the rationale.",
        "It is standard for medical unresponsiveness without trauma concern.",
      ],
      "easy",
    ],
    [
      "Wheezing is most commonly associated with:",
      "Lower airway bronchoconstriction such as asthma/COPD exacerbations",
      ["Complete apnea",
      "Only pneumothorax",
      "Hyperglycemia alone"],
      "Expiratory wheeze reflects narrowed lower airways; still assess for other causes.",
      [
        "Apnea has no breath sounds of wheeze.",
        "Pneumothorax may decrease sounds unilaterally.",
        "Glucose disorders do not directly cause wheeze.",
      ],
      "easy",
    ],
    [
      "A patient with inadequate breathing should receive:",
      "Assisted positive-pressure ventilation (e.g., BVM) rather than passive oxygen alone",
      ["Only a nasal cannula regardless of effort",
      "No airway interventions until hospital",
      "Abdominal thrusts if they can speak clearly"],
      "Inadequate rate/depth needs assisted ventilation; oxygen alone does not ventilate.",
      [
        "NC cannot fix apnea/near-apnea.",
        "Delays worsen hypoxia.",
        "Speaking patients are not complete airway obstruction candidates for thrusts.",
      ],
      "medium",
    ],
    [
      "CPAP in EMS (when indicated and available) primarily helps patients with:",
      "Respiratory distress from conditions like CHF/pulmonary edema by stenting airways and improving oxygenation",
      ["Complete airway obstruction from a foreign body",
      "Cardiac arrest without breathing",
      "Unresponsive patients without a pulse"],
      "CPAP requires a spontaneously breathing cooperative patient; not for arrest or complete obstruction.",
      [
        "FBAO needs removal maneuvers.",
        "Arrest needs CPR/ventilation.",
        "Pulseless patients need resuscitation, not CPAP.",
      ],
      "hard",
    ],
    [
      "Cyanosis indicates:",
      "Significant hypoxemia and need for urgent airway/oxygen/ventilation assessment",
      ["Always perfect oxygenation",
      "Only anemia with normal oxygen",
      "Hyperthermia exclusively"],
      "Central cyanosis is a late, serious sign of poor oxygenation.",
      [
        "It means poor oxygenation.",
        "Anemia can limit cyanosis visibility.",
        "Fever alone is not cyanosis.",
      ],
      "easy",
    ]
  ],
  "cardiology-resuscitation": [
    [
      "For an unresponsive adult with no normal breathing and no pulse, the immediate action is:",
      "Begin high-quality CPR and apply AED as soon as available",
      ["Give two minutes of detailed history first",
      "Wait for ALS before any compressions",
      "Check blood glucose before CPR"],
      "Cardiac arrest care prioritizes compressions and early defibrillation.",
      [
        "History can wait.",
        "BLS CPR must not wait for ALS.",
        "Glucose checks delay CPR.",
      ],
      "easy",
    ],
    [
      "High-quality adult CPR compression depth is approximately:",
      "At least 2 inches (5 cm) while allowing full chest recoil",
      ["0.5 inch only",
      "4–5 inches every compression",
      "No depth target exists"],
      "AHA-aligned adult depth is at least 2 inches with full recoil and adequate rate.",
      [
        "0.5 inch is inadequate.",
        "Excessive depth risks injury without benefit targets.",
        "Depth targets are defined.",
      ],
      "easy",
    ],
    [
      "An AED advises a shock. You should:",
      "Ensure no one is touching the patient, deliver the shock, then immediately resume CPR",
      ["Check a pulse for a full minute before shocking",
      "Turn the AED off and start driving",
      "Place the pads over a medication patch without removing it"],
      "Clear, shock, then immediate CPR minimizes interruptions.",
      [
        "Long pulse checks delay defibrillation.",
        "Transport without resus is wrong.",
        "Remove patches and wipe residue before pads.",
      ],
      "medium",
    ],
    [
      "Aspirin is given in suspected ACS (per protocol) primarily because it:",
      "Inhibits platelet aggregation and may limit clot progression",
      ["Instantly dissolves all coronary plaques",
      "Raises blood sugar for energy",
      "Replaces the need for EMS transport"],
      "Antiplatelet effect of aspirin is a key early ACS treatment when not contraindicated.",
      [
        "It does not dissolve plaques instantly.",
        "It is not a glucose therapy.",
        "Transport remains essential.",
      ],
      "medium",
    ],
    [
      "Nitroglycerin is contraindicated when:",
      "The patient has used a PDE-5 inhibitor recently or has hypotension per protocol",
      ["The patient has chest pain",
      "Systolic BP is 150 mm Hg",
      "The patient is on aspirin"],
      "Nitroglycerin can cause profound hypotension with PDE-5 drugs or low BP.",
      [
        "Chest pain is an indication when allowed.",
        "150 systolic is not a typical contraindication.",
        "Aspirin is often co-administered.",
      ],
      "hard",
    ],
    [
      "Right-sided heart failure commonly presents with:",
      "Peripheral edema and JVD from systemic congestion",
      ["Only left-sided crackles with no edema ever",
      "Hypoglycemia as the primary sign",
      "Stridor"],
      "Right-sided failure backs up into the systemic veins; left-sided often causes pulmonary edema.",
      [
        "Left failure more often causes pulmonary findings.",
        "Glucose is unrelated as primary HF sign.",
        "Stridor is airway.",
      ],
      "medium",
    ],
    [
      "During CPR, the compression-to-ventilation ratio for adult 1-rescuer BLS is:",
      "30:2",
      ["15:2 only for all adults",
      "5:1",
      "100:0 always"],
      "Adult BLS uses 30 compressions to 2 breaths for 1 or 2 rescuers without advanced airway.",
      [
        "15:2 is pediatric 2-rescuer classic ratio context.",
        "5:1 is outdated.",
        "Continuous compressions apply with advanced airway.",
      ],
      "easy",
    ],
    [
      "Return of spontaneous circulation (ROSC) is suggested by:",
      "Return of organized pulse/signs of circulation after arrest care",
      ["Asystole on the monitor",
      "Absence of any end-tidal CO2 forever",
      "Fixed dilated pupils only"],
      "ROSC means circulation returns; continue post-arrest support and transport.",
      [
        "Asystole is arrest rhythm.",
        "ETCO2 often rises with ROSC.",
        "Pupils alone are unreliable.",
      ],
      "easy",
    ],
    [
      "Chest pain described as pressure with radiation to the arm/jaw in an adult should be treated as:",
      "Possible acute coronary syndrome until proven otherwise",
      ["Always simple muscle strain",
      "Only anxiety in men under 70",
      "A reason to refuse oxygen forever"],
      "Classic ACS symptoms warrant prompt EMS cardiac protocols.",
      [
        "Musculoskeletal is diagnosis of exclusion.",
        "ACS occurs across ages/sexes with varied presentations.",
        "Oxygen is protocol-based, not forever refused.",
      ],
      "easy",
    ],
    [
      "Automated external defibrillation is indicated for:",
      "Pulseless ventricular fibrillation / pulseless ventricular tachycardia (shockable rhythms)",
      ["All patients with sinus bradycardia and a strong pulse",
      "Every stable patient with chest pain",
      "Conscious patients with normal mentation and pulse"],
      "AEDs shock shockable arrest rhythms; pulsed patients are not defibrillated.",
      [
        "Bradycardia with pulse needs other care.",
        "Stable chest pain is not AED shock.",
        "Conscious pulsed patients are not defibrillated.",
      ],
      "medium",
    ]
  ],
  "trauma": [
    [
      "The primary survey in trauma follows which priority concept?",
      "Find and fix life threats to airway, breathing, and circulation first",
      ["Complete SAMPLE history before any exam",
      "Splint every fracture before airway care",
      "Transport only after full secondary survey always"],
      "XABC/ABC priorities address immediate killers first.",
      [
        "History follows life threats.",
        "Airway precedes orthopedic detail.",
        "Load-and-go may interrupt full secondary survey.",
      ],
      "easy",
    ],
    [
      "A sucking chest wound (open pneumothorax) is initially managed by:",
      "Occlusive dressing sealed on three sides (or commercial chest seal) per protocol",
      ["Deep abdominal thrusts",
      "Removing the occlusive dressing after each breath forever",
      "Encouraging the patient to lie prone flat always"],
      "Three-sided occlusive dressing can prevent air entry while allowing escape; monitor for tension.",
      [
        "Heimlich is for FBAO.",
        "Indiscriminate removal without indication is wrong.",
        "Positioning is individualized; prone is not default.",
      ],
      "hard",
    ],
    [
      "External arterial bleeding that is life-threatening should be controlled by:",
      "Direct pressure and tourniquet use when indicated for extremities",
      ["Ice packs alone",
      "Trendelenburg position only",
      "Warm compresses and observation"],
      "Massive hemorrhage control is a top trauma priority; tourniquets save lives in extremity bleeding.",
      [
        "Ice is insufficient for arterial spurting.",
        "Position alone does not stop arterial bleeding.",
        "Observation delays care.",
      ],
      "easy",
    ],
    [
      "A patient with paradoxical chest wall movement after blunt trauma likely has:",
      "Flail chest",
      ["Simple ankle sprain",
      "Isolated nosebleed",
      "Migraine headache"],
      "Flail segment moves paradoxically and impairs ventilation; stabilize and support breathing.",
      [
        "Ankle sprain is orthopedic distal.",
        "Epistaxis is nasal.",
        "Migraine is medical.",
      ],
      "medium",
    ],
    [
      "For a suspected pelvic fracture with shock, EMS should:",
      "Avoid log-rolling excessively, stabilize pelvis per protocol, and treat for shock",
      ["Have the patient walk to assess stability",
      "Rock the pelvis repeatedly to confirm fracture",
      "Apply ice and discharge on scene"],
      "Pelvic fractures can cause massive bleeding; minimize movement and stabilize.",
      [
        "Walking worsens hemorrhage.",
        "Rocking is harmful.",
        "Scene discharge is inappropriate.",
      ],
      "medium",
    ],
    [
      "Burn severity estimation in the field commonly uses:",
      "Rule of Nines (or age-appropriate alternative) for BSA percentage",
      ["Only the patient's subjective pain score",
      "Pupil size exclusively",
      "Blood glucose only"],
      "TBSA estimation guides fluid/transport decisions along with depth and location.",
      [
        "Pain alone underestimates severity.",
        "Pupils are neuro.",
        "Glucose is metabolic.",
      ],
      "easy",
    ],
    [
      "A penetrating object impaled in the thigh should generally be:",
      "Stabilized in place and not removed in the field unless it interferes with CPR/airway",
      ["Removed immediately to reduce infection",
      "Twisted out to free clothing",
      "Cut flush with the skin always"],
      "Impaled objects may tamponade bleeding; stabilize for transport unless removal is required for resuscitation.",
      [
        "Field removal can cause hemorrhage.",
        "Twisting increases damage.",
        "Cutting flush still leaves the object and may worsen control issues.",
      ],
      "medium",
    ],
    [
      "Cushing's triad (late increased ICP sign) includes:",
      "Hypertension, bradycardia, and irregular respirations",
      ["Hypotension, tachycardia, and fever only",
      "Hypoglycemia, polyuria, polydipsia",
      "Wheezing, hives, and stridor"],
      "Cushing response is a late brain herniation warning; manage airway and rapid transport.",
      [
        "That pattern fits other shock/infection states.",
        "That is diabetes symptoms.",
        "That is anaphylaxis.",
      ],
      "hard",
    ],
    [
      "Spinal motion restriction is most clearly indicated when:",
      "Mechanism and exam suggest possible spinal injury (e.g., high-risk MOI with midline tenderness/neuro deficits)",
      ["Every patient with a hangnail",
      "Only patients under age 10",
      "Never in modern EMS"],
      "Selective spinal precautions follow protocol based on MOI and findings.",
      [
        "Minor injuries without risk factors do not mandate full SMR.",
        "Age alone is not the rule.",
        "SMR remains indicated when criteria met.",
      ],
      "medium",
    ],
    [
      "Evisceration management includes:",
      "Cover protruding organs with moist sterile dressing and occlusive cover; do not push back inside",
      ["Replace organs firmly into the abdomen on scene",
      "Apply a dry adhesive bandage tightly over organs",
      "Give the patient food and water"],
      "Keep organs moist and protected; replacement is a surgical task.",
      [
        "Pushing organs back can worsen injury/contamination.",
        "Dry tight dressings damage tissue.",
        "NPO for likely surgery.",
      ],
      "medium",
    ]
  ],
  "medical-ops": [
    [
      "SAMPLE history stands for:",
      "Signs/Symptoms, Allergies, Medications, Past history, Last oral intake, Events",
      ["Saturation, Airway, Medications, Pulse, LOC, ECG",
      "Stroke, Asthma, MI, PE, Lung, ED",
      "Scene, Ambulance, Medic, Patient, Landing, Exit"],
      "SAMPLE structures medical history gathering.",
      [
        "That mix is not SAMPLE.",
        "Disease list is not SAMPLE.",
        "Operations mnemonic is wrong.",
      ],
      "easy",
    ],
    [
      "OPQRST is primarily used to assess:",
      "Pain/symptom characteristics (Onset, Provocation, Quality, Radiation, Severity, Time)",
      ["Trauma scene hazards only",
      "Only pediatric developmental milestones",
      "Ambulance maintenance schedules"],
      "OPQRST fleshes out the chief complaint symptom profile.",
      [
        "Scene hazards use other mnemonics.",
        "Milestones are pediatric development.",
        "Fleet maintenance is unrelated.",
      ],
      "easy",
    ],
    [
      "A patient with stroke-like symptoms should be transported with priority on:",
      "Rapid transport to an appropriate stroke-capable facility within time windows",
      ["Waiting on scene for symptoms to resolve for hours",
      "Giving oral aspirin crushed in juice always",
      "Encouraging ambulation upstairs for assessment"],
      "Time-sensitive stroke care needs rapid identification and transport; avoid delays and unsafe oral meds if swallow uncertain.",
      [
        "Time loss worsens outcomes.",
        "Aspirin is not routine for suspected stroke in field like ACS.",
        "Ambulation risks falls.",
      ],
      "medium",
    ],
    [
      "Hypoglycemia in a conscious patient who can swallow may be treated with:",
      "Oral glucose per protocol",
      ["Insulin injection by EMT basic without protocol",
      "Large IV potassium bolus",
      "Withholding all sugar indefinitely"],
      "Oral glucose is standard for symptomatic hypoglycemia when airway is protected.",
      [
        "EMT scope/protocols vary; insulin is not typical BLS.",
        "Potassium is dangerous/inappropriate.",
        "Sugar is the treatment.",
      ],
      "easy",
    ],
    [
      "Anaphylaxis treatment priority medication in EMS protocols is typically:",
      "Epinephrine",
      ["Oral antihistamine only as sole therapy",
      "Aspirin",
      "Nitroglycerin"],
      "IM epinephrine is first-line for anaphylaxis; antihistamines are adjuncts.",
      [
        "Antihistamines alone are insufficient for anaphylaxis.",
        "Aspirin is ACS care.",
        "Nitro is not anaphylaxis care.",
      ],
      "easy",
    ],
    [
      "Which best describes implied consent?",
      "Unresponsive or impaired patients are treated under assumption they would want life-saving care",
      ["Any bystander can refuse care for an adult patient",
      "Consent is never needed in EMS",
      "Minors always refuse for themselves in all states"],
      "Implied consent covers emergency care when a patient cannot decide; competent adults may refuse.",
      [
        "Bystanders cannot refuse for competent adults.",
        "Consent concepts still apply.",
        "Minor consent rules are specific/complex.",
      ],
      "medium",
    ],
    [
      "During extrication, the EMS provider's first responsibility is:",
      "Scene safety and personal protective measures before patient access",
      ["Entering an unstable vehicle immediately without assessment",
      "Turning off traffic lights citywide",
      "Pronouncing death before arrival"],
      "Rescuer safety enables sustained patient care; hazards must be controlled.",
      [
        "Rushing into unstable scenes creates more victims.",
        "Traffic control is coordinated, not citywide light control by EMT.",
        "Death pronouncement rules vary and follow assessment.",
      ],
      "easy",
    ],
    [
      "A DNR order is generally valid when:",
      "It meets local legal requirements and is presented/verified per protocol",
      ["A neighbor says the patient 'wouldn't want care' without documentation",
      "The patient is awake and requesting full treatment",
      "Any faded tattoo that says DNR"],
      "Follow legal advance directives/DNR documentation; honor patient wishes when they request care and are competent.",
      [
        "Hearsay is insufficient.",
        "Competent requests for care supersede outdated assumptions.",
        "Tattoos are not reliable legal DNRs.",
      ],
      "hard",
    ],
    [
      "Seizure management priorities include:",
      "Protect from injury, maintain airway, and time the seizure; do not force objects into the mouth",
      ["Place a spoon between the teeth",
      "Restrain arms rigidly to the bed frame",
      "Give oral water during convulsions"],
      "Protective positioning and airway support; never insert objects into the mouth.",
      [
        "Spoons cause dental/airway injury.",
        "Rigid restraint risks injury.",
        "Oral intake during seizure risks aspiration.",
      ],
      "easy",
    ],
    [
      "Which statement about ambulance emergency driving is correct?",
      "Lights/sirens do not guarantee right-of-way; drive with due regard for safety",
      ["Red lights allow running any red signal at full speed without slowing",
      "Seat belts are optional for providers in the back",
      "Speed limits never apply to EMS"],
      "Emergency privilege requires due regard; crashes during response harm everyone.",
      [
        "Intersections still require caution.",
        "Restraints protect providers.",
        "Traffic laws still constrain unsafe driving.",
      ],
      "medium",
    ]
  ],
};
