/** VTNE — 40 curated MCQs */
export const topics = {
  "pharmacy-pharm": [
    [
      "Which statement about drug withdrawal times in food animals is correct?",
      "Observe labeled withdrawal periods so residues clear before slaughter/milk use",
      ["Withdrawal times can be ignored if the animal looks healthy", "Any human drug may be used without restrictions in cattle", "Withdrawal applies only to topical shampoos"],
      "FARAD/label guidance protects the food supply; ELDU has extra rules in food animals.",
      [
        "Health appearance ≠ residue clearance.",
        "Human drugs restricted especially in food animals.",
        "Systemic drugs also have withdrawals.",
      ],
      "medium",
    ],
    [
      "A drug with a narrow therapeutic index means:",
      "Toxic dose is close to effective dose—dose carefully and monitor",
      ["It is always OTC safe at any dose", "Overdose is impossible", "It has no side effects"],
      "Examples in vet med teaching often include digoxin, some chemo agents—precision matters.",
      [
        "Not freely OTC megadosing.",
        "Overdose possible.",
        "Side effects exist.",
      ],
      "easy",
    ],
    [
      "Bioavailability is lower for many oral drugs in ruminants sometimes because:",
      "Rumen microbes/pH can degrade or bind drugs",
      ["Ruminants never have livers", "IV and oral are always identical", "They lack GI tracts"],
      "Species differences drive route/dose selection.",
      [
        "They have livers.",
        "IV bioavailability is 100% by definition.",
        "GI present/complex.",
      ],
      "hard",
    ],
    [
      "Controlled substances in veterinary practice require:",
      "Secure storage, logged use, and DEA compliance",
      ["Open shelf in the lobby", "No records if used in-hospital", "Sharing vials with other clinics informally without logs"],
      "Like human pharmacies, diversion control is mandatory.",
      [
        "Public access improper.",
        "Records required.",
        "Informal sharing breaks accountability.",
      ],
      "easy",
    ],
    [
      "Which route typically provides the most rapid onset?",
      "IV",
      ["SQ", "Transdermal", "Oral in a full stomach"],
      "IV for emergencies (e.g., anticonvulsants, emergency drugs) when access available.",
      [
        "SQ slower.",
        "Transdermal slow/variable.",
        "Oral slower/variable.",
      ],
      "easy",
    ],
    [
      "NSAID toxicity in dogs commonly involves:",
      "GI ulceration and renal injury risks",
      ["Only ototoxicity like aminoglycosides exclusively", "Keratoconjunctivitis sicca only like sulfa exclusivity", "Bone marrow suppression only like estrogen exclusivity"],
      "Never stack NSAIDs with steroids casually; ensure hydration/dosing by weight.",
      [
        "Aminoglycosides: ear/kidney.",
        "Sulfas: KCS risk teaching.",
        "Estrogens: marrow concerns.",
      ],
      "medium",
    ],
    [
      "Insulin syringes are typically marked in:",
      "Units matching insulin concentration (U-100 common)",
      ["Tablespoons", "PSI", "French catheter size"],
      "Match syringe to insulin concentration to avoid fatal dosing errors.",
      [
        "Not volume cooking measures.",
        "PSI pressure.",
        "French is diameter.",
      ],
      "easy",
    ],
    [
      "Cat acetaminophen (paracetamol) exposure is dangerous because cats lack:",
      "Adequate glucuronidation pathways—toxicity can be fatal",
      ["Any red blood cells", "Lungs", "Kidneys always"],
      "Acetaminophen causes methemoglobinemia/hepatotoxicity in cats—emergency.",
      [
        "They have RBCs.",
        "They have lungs.",
        "They have kidneys.",
      ],
      "medium",
    ],
    [
      "Therapeutic drug monitoring is most useful when:",
      "Drugs have narrow indices or variable kinetics (e.g., phenobarbital, digoxin concepts)",
      ["All topical flea preventives always", "Saline flushes", "Bandage changes"],
      "Serum levels guide dose adjustments with clinical signs.",
      [
        "Many topicals not TDM.",
        "Saline not a TDM drug.",
        "Bandages not pharmacology labs.",
      ],
      "medium",
    ],
    [
      "Compounded medications should be used when:",
      "No suitable approved formulation exists and a veterinarian directs legitimate compounding",
      ["To copy approved drugs cheaply for food animals against guidance always", "As unregulated OTC for any species online without VCPR", "To avoid all labeling"],
      "VCPR and quality/regulatory limits apply; caution with compounded sterile products.",
      [
        "Copying approved drugs for cost can be illegal/inappropriate.",
        "VCPR required.",
        "Labels needed.",
      ],
      "hard",
    ]
  ],
  "surgical-nursing": [
    [
      "Preanesthetic fasting in healthy adult dogs typically aims to:",
      "Reduce regurgitation/aspiration risk under anesthesia",
      ["Cause dangerous hypoglycemia intentionally as the goal", "Eliminate need for IV catheters", "Sterilize the bowel completely"],
      "Protocols vary by age/species (neonates/hypoglycemia risk); follow DVM orders.",
      [
        "Avoid excessive fasting in small/young.",
        "Catheters still used.",
        "Bowel not sterilized by NPO.",
      ],
      "easy",
    ],
    [
      "ASA physical status classification estimates:",
      "Anesthetic risk based on systemic disease severity",
      ["Only coat color", "Surgical instrument counts", "Client credit score"],
      "ASA I–V (+E emergency) guides planning/monitoring intensity.",
      [
        "Color irrelevant.",
        "Counts separate.",
        "Finances separate.",
      ],
      "easy",
    ],
    [
      "Pulse oximetry estimates:",
      "Hemoglobin oxygen saturation and pulse rate",
      ["Exact PaO2 always", "Blood glucose", "ETCO2 precisely"],
      "SpO2 can read falsely with poor perfusion/pigment/motion; confirm clinically.",
      [
        "PaO2 needs blood gas.",
        "Glucose separate.",
        "ETCO2 is capnography.",
      ],
      "easy",
    ],
    [
      "Capnography (ETCO2) helps assess:",
      "Ventilation adequacy and circuit integrity",
      ["Only kidney function", "PCV/TS only", "Wound class"],
      "Sudden ETCO2 drop may mean extubation/arrest/disconnect; high ETCO2 hypoventilation.",
      [
        "Renal labs different.",
        "PCV/TS hematology/hydration.",
        "Wound class SSI.",
      ],
      "medium",
    ],
    [
      "Surgical instrument sterilization for critical items requires:",
      "Cleaning then autoclave/appropriate sterilization with monitoring",
      ["Alcohol wipe only as sterilization", "Rinsing with tap water only", "Flash without cleaning as routine for implants"],
      "Same Spaulding logic as human SPD; BI monitoring best practice.",
      [
        "Alcohol disinfects not sterilizes reliably for critical.",
        "Tap water not sterilant.",
        "IUSS rules apply.",
      ],
      "medium",
    ],
    [
      "Aseptic skin prep for surgery commonly uses:",
      "Chlorhexidine or iodophor scrub patterns outward from incision site",
      ["Dirty clippers wiped once across the site as sufficient prep", "Hydrogen peroxide as the gold-standard residual antiseptic always", "No prep if fur looks clean"],
      "Clippers for hair removal; contact time matters; avoid harsh alcohols pooling with lasers/cautery.",
      [
        "Dirty clippers contaminate.",
        "H2O2 limited residual/antisepsis role.",
        "Prep always needed.",
      ],
      "easy",
    ],
    [
      "Pain scoring postoperatively should be:",
      "Performed with validated scales and treated per veterinarian orders",
      ["Ignored because animals hide pain always as a reason to withhold analgesics", "Done only once a week", "Based solely on client Facebook posts"],
      "Multimodal analgesia common; reassess after interventions.",
      [
        "Hiding pain means assess carefully, not withhold.",
        "Frequent reassessment.",
        "Client input helps but staff assess.",
      ],
      "easy",
    ],
    [
      "Extubation readiness in dogs often includes:",
      "Return of swallowing reflex (species differences apply—cats often earlier)",
      ["Complete absence of any reflexes forever", "Only after 24 hours always", "When the soda lime is purple only"],
      "Know species differences and brachycephalic risks (delay extubation carefully).",
      [
        "Reflexes needed.",
        "Not fixed 24h.",
        "CO2 absorbent color is circuit maintenance.",
      ],
      "medium",
    ],
    [
      "Surgical wound dehiscence risk increases with:",
      "Infection, tension, poor nutrition, and self-trauma",
      ["Elizabethan collars used properly", "Appropriate activity restriction", "Good aseptic technique"],
      "E-collars and activity control protect closures.",
      [
        "E-collars help.",
        "Rest helps.",
        "Asepsis helps.",
      ],
      "easy",
    ],
    [
      "Malignant hyperthermia-like crises under anesthesia are rare but demand:",
      "Discontinue triggers, hyperventilate with O2, cool, and DVM-directed emergency drugs",
      ["Add more halothane immediately", "Cover with heavy blankets to warm further", "Ignore rising ETCO2/temperature"],
      "Recognize hot/rigid/hypercarbic patients; team response.",
      [
        "Stop triggers.",
        "Cool not heat.",
        "Rising CO2/temp are clues.",
      ],
      "hard",
    ]
  ],
  "diagnostics": [
    [
      "PCV/TS (or TP) together help evaluate:",
      "Red cell mass and plasma protein/hydration status",
      ["Only liver enzymes", "Only coagulation times", "Only blood type"],
      "High PCV+TS suggests dehydration; high PCV with normal TS may suggest other causes.",
      [
        "Chemistry enzymes separate.",
        "Coag separate.",
        "Typing separate.",
      ],
      "easy",
    ],
    [
      "A left shift on CBC refers to:",
      "Increased immature neutrophils (bands) suggesting inflammation/infection",
      ["Increased reticulocytes only", "Low platelets only", "Elevated bile acids only"],
      "Toxic change and left shift guide infection urgency.",
      [
        "Reticulocytes = regeneration RBC.",
        "Thrombocytopenia separate.",
        "Bile acids liver function.",
      ],
      "medium",
    ],
    [
      "Azotemia with isosthenuria suggests:",
      "Renal inability to concentrate—renal azotemia more likely than simple prerenal",
      ["Always prerenal dehydration with maximal concentration", "Only post-renal obstruction never renal", "Normal kidney function"],
      "Interpret BUN/crea with USG; prerenal often hypersthenuric if kidneys work.",
      [
        "Prerenal concentrates urine typically.",
        "Post-renal has other clues.",
        "Not normal.",
      ],
      "hard",
    ],
    [
      "SNAP/ELISA in-clinic tests require:",
      "Following timing/temperature instructions and reading within the window",
      ["Reading results the next day always for accuracy", "Using expired kits freely", "Skipping controls"],
      "False results from protocol deviations are common.",
      [
        "Delayed reading invalid.",
        "Expired unreliable.",
        "Controls verify kits.",
      ],
      "easy",
    ],
    [
      "Cytology of an ear swab with Malassezia shows:",
      "Budding yeast (peanut/footprint shapes) with inflammatory debris often",
      ["Only gram-negative rods exclusively always", "Adult fleas", "Urine crystals"],
      "Common in canine otitis; treat underlying allergies too.",
      [
        "Bacteria may co-exist but yeast distinctive.",
        "Fleas external parasites.",
        "Crystals urine.",
      ],
      "easy",
    ],
    [
      "Radiographic technique: increasing kVp primarily:",
      "Increases beam penetrability/contrast scale changes (more penetration)",
      ["Only changes number of x-ray photons like mAs solely", "Eliminates need for collimation", "Removes need for PPE"],
      "mAs ≈ quantity; kVp ≈ quality/penetration; ALARA still applies.",
      [
        "mAs quantity.",
        "Collimate always.",
        "PPE still required.",
      ],
      "medium",
    ],
    [
      "A blood sample for glucose in a non-separator tube left on clot too long may:",
      "Show falsely decreased glucose due to cell metabolism",
      ["Always raise glucose dramatically", "Have no effect ever", "Convert to ketones only in the syringe label"],
      "Use proper tubes/timing; fluoride tubes inhibit glycolysis when delayed.",
      [
        "Glucose falls, not rises.",
        "Effect is real.",
        "Label ≠ biochemistry.",
      ],
      "medium",
    ],
    [
      "USG is measured with a:",
      "Refractometer (ideally) calibrated with distilled water",
      ["Thermometer", "Pulse oximeter", "Doppler blood pressure cuff only"],
      "Interpret hydration/renal concentrating ability with chemistries.",
      [
        "Temp separate.",
        "SpO2 separate.",
        "BP separate.",
      ],
      "easy",
    ],
    [
      "Crossmatching is performed to:",
      "Detect serological incompatibility before transfusion",
      ["Replace blood typing in all species always without typing", "Diagnose ringworm", "Measure PCV only"],
      "Cats have naturally occurring alloantibodies—type before transfusing; crossmatch also important.",
      [
        "Typing still critical especially cats.",
        "DTM/Wood's for dermatophytes.",
        "PCV separate.",
      ],
      "medium",
    ],
    [
      "Ketones on urine dipstick in a diabetic animal suggest:",
      "Possible DKA risk—needs prompt veterinary assessment",
      ["Perfect diabetic control always", "Only dehydration without significance ever", "Lab error only always"],
      "Dipsticks detect acetoacetate more than beta-hydroxybutyrate—clinical correlation needed.",
      [
        "Ketones concerning.",
        "Can be significant.",
        "Not always error.",
      ],
      "easy",
    ]
  ],
  "animal-care": [
    [
      "Proper dog lifting for a mid-sized patient typically uses:",
      "Support chest and hindquarters close to your body with team help if needed",
      ["Lift by the front limbs only", "Scruff and hang", "One-handed ear lift"],
      "Protect staff backs and animal joints; use muzzles/sedation when indicated by DVM for fractious pets.",
      [
        "Limb-only lifts injure.",
        "Scruffing dogs inappropriate generally.",
        "Ears fragile/cruel.",
      ],
      "easy",
    ],
    [
      "Feline restraint with a towel ('purrito') helps:",
      "Limit limb movement while reducing stress for procedures",
      ["Replace all analgesia needs", "Allow unprotected face near a biting cat without caution", "Substitute for rabies vaccination laws"],
      "Minimize struggle; consider chemical restraint when needed.",
      [
        "Still need pain control.",
        "Face bites possible.",
        "Vaccines legal/public health.",
      ],
      "easy",
    ],
    [
      "Core canine vaccines commonly include:",
      "DA2PP (distemper, adenovirus, parvovirus) and rabies (per guidelines/law)",
      ["Only Lyme always as the sole core vaccine", "Only influenza always as core everywhere", "No vaccines are ever core"],
      "Lifestyle non-core (Lepto, Bordetella, etc.) based on risk; AAHA guidelines evolve.",
      [
        "Lyme often non-core/risk-based.",
        "CIV risk-based.",
        "Cores exist.",
      ],
      "medium",
    ],
    [
      "Dental prophylaxis polishing after scaling is done to:",
      "Smooth enamel micro-etching and slow plaque reattachment",
      ["Remove all enamel intentionally", "Replace systemic antibiotics always", "Cure periodontal bone loss overnight"],
      "Probe/chart teeth; dental rads often needed for full assessment.",
      [
        "Don't strip enamel.",
        "Antibiotics adjunctive/not replacement.",
        "Bone loss needs perio therapy.",
      ],
      "medium",
    ],
    [
      "Thoracic radiograph inspiration timing aims to:",
      "Take exposure at peak inspiration for lung detail",
      ["Always expose at full expiration only for lungs", "Ignore motion", "Use lowest mA with massive motion blur intentionally"],
      "Sedation/positioning aids quality; collimate and shield when possible.",
      [
        "Expiration used for some tracheal collapse comparisons but lungs prefer inspiration.",
        "Minimize motion.",
        "Technique + stillness.",
      ],
      "easy",
    ],
    [
      "Neonatal orphan puppies need:",
      "Warmth, appropriate milk replacer, and frequent feeding—not cow's milk as ideal",
      ["Free-choice adult dry food day one", "Ice baths for stimulation", "No elimination assistance ever"],
      "Stimulate urination/defecation; monitor weight gain; aseptic bottle hygiene.",
      [
        "Adult food inappropriate.",
        "Keep warm not iced.",
        "Stimulate elimination.",
      ],
      "medium",
    ],
    [
      "Zoonotic concern with pregnant staff and litter boxes involves:",
      "Toxoplasma gondii oocysts in cat feces—delegate litter duty when possible",
      ["Canine parvovirus infecting humans commonly as the pregnancy issue", "Heartworm microfilariae in humans via litter", "Kennel cough obligate human pregnancy pathogen from boxes"],
      "Toxoplasmosis education and hygiene matter; many infections foodborne too.",
      [
        "Parvo not a human pregnancy classic from litter.",
        "Heartworm vector mosquitoes.",
        "Kennel cough not litter Toxoplasma story.",
      ],
      "hard",
    ],
    [
      "Ear canal anatomy relevant to cleaning: the vertical canal leads to the:",
      "Horizontal canal then tympanic membrane",
      ["Stomach via Eustachian only as cleaning path", "Nasal turbinates directly", "Urinary bladder"],
      "Know tympanic membrane risk—don't soak ruptured ears with inappropriate cleaners.",
      [
        "Not GI path for cleaning.",
        "Not nasal.",
        "Not urinary.",
      ],
      "easy",
    ],
    [
      "Fluid therapy 'maintenance' rates approximate (dogs teaching ballpark):",
      "About 40–60 mL/kg/day (formula variations exist—follow DVM orders)",
      ["1 L/kg/hour always", "No water ever for azotemic patients as policy", "Maintenance equals shock rates"],
      "Shock boluses are larger/aliased differently; calculate carefully by weight/species.",
      [
        "1 L/kg/hr lethal-range absurd.",
        "Azotemic often need fluids.",
        "Shock ≠ maintenance.",
      ],
      "hard",
    ],
    [
      "Proper hospital isolation for parvovirus suspects includes:",
      "Dedicated PPE, disinfection with appropriate parvocidal agents, and traffic control",
      ["Housing next to neonatal puppies without barriers", "Using quaternary ammonium alone always assuming full parvo kill without checking label", "No hand hygiene between patients"],
      "Non-enveloped viruses need correct disinfectants (e.g., accelerated H2O2/bleach per label).",
      [
        "Neonates highly susceptible.",
        "Check disinfectant claims.",
        "Hygiene mandatory.",
      ],
      "medium",
    ]
  ],
};
