#!/usr/bin/env python3
"""Luxembourg Vivre ensemble mock bank — official 10/20/10 module split.

Facts mirror luxembourg_vivre_ensemble_cards.py (Constitution of 1 July 2023,
RGD of 7 April 2017, guichet.lu, STATEC 2026). Session: 40 questions / 60 min,
10 rights · 20 institutions · 10 history & EU, sampled per module.

Row: (difficulty, prompt, correct, explanation, (distractor, why), ×3)
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

SLUG = "luxembourg-vivre-ensemble-readiness-check"
OUT = Path(__file__).resolve().parents[2] / "src/data/mock-exams" / f"{SLUG}.json"
SOURCE_NOTE = (
    "UniPrep2Go original Luxembourg Vivre ensemble question aligned to the official modules "
    "(Constitution of 1 July 2023; règlement grand-ducal of 7 April 2017). Not official SFA material."
)
DIFF = {"e": "easy", "m": "medium", "h": "hard"}

RIGHTS = [
    ("m", "Selon la Constitution de 2023, par quel principe s’ouvre le chapitre des droits fondamentaux ?",
     "La dignité humaine est inviolable",
     "Le chapitre sur les droits fondamentaux commence par la dignité humaine ; les autres droits et libertés en découlent.",
     ("Le droit de propriété est sacré", "La propriété est protégée plus loin dans le texte, mais ce n’est pas le principe d’ouverture."),
     ("La souveraineté appartient au Grand-Duc", "La souveraineté réside dans la Nation — et ce n’est pas un droit fondamental."),
     ("Le travail est un devoir pour chacun", "Le droit au travail est un objectif de l’État, pas le principe d’ouverture.")),
    ("m", "Que prévoit la Constitution luxembourgeoise au sujet de l’égalité entre les femmes et les hommes ?",
     "Ils sont égaux en droits et en devoirs",
     "La Constitution proclame l’égalité des femmes et des hommes et charge l’État de promouvoir activement cette égalité.",
     ("L’égalité ne vaut que dans l’emploi public", "L’égalité est générale ; elle n’est pas limitée à la fonction publique."),
     ("L’égalité relève seulement du Code du travail", "Elle est inscrite dans la Constitution elle-même, au-dessus des lois."),
     ("L’égalité ne concerne que les Luxembourgeois", "Le principe d’égalité femmes-hommes ne dépend pas de la nationalité.")),
    ("e", "Une personne non luxembourgeoise présente sur le territoire bénéficie-t-elle d’une protection constitutionnelle ?",
     "Oui, de la protection accordée aux personnes et aux biens",
     "Toute personne non luxembourgeoise sur le territoire est protégée dans sa personne et ses biens, sauf exceptions prévues par la loi.",
     ("Non, seuls les Luxembourgeois sont protégés", "La Constitution protège aussi les non-Luxembourgeois présents au pays."),
     ("Oui, mais seulement les citoyens de l’UE", "La protection ne se limite pas aux citoyens européens."),
     ("Oui, mais seulement après cinq ans de résidence", "Aucune durée de résidence n’est exigée pour cette protection.")),
    ("e", "La peine de mort peut-elle être prononcée au Luxembourg selon la Constitution ?",
     "Non, elle est interdite, comme la torture",
     "La Constitution interdit la peine de mort, la torture et les peines ou traitements inhumains et dégradants.",
     ("Oui, pour les crimes de guerre uniquement", "Aucune exception : la peine de mort est interdite sans réserve."),
     ("Oui, si une loi votée par la Chambre l’autorise", "Une loi ne peut pas rétablir ce que la Constitution interdit."),
     ("Non, sauf pendant l’état de crise", "L’état de crise ne permet pas de suspendre cette interdiction.")),
    ("m", "Dans quel délai une personne arrêtée doit-elle recevoir l’ordonnance motivée du juge ?",
     "Au plus tard dans les 24 heures",
     "Hors flagrant délit, l’ordonnance motivée du juge est signifiée au moment de l’arrestation ou au plus tard dans les 24 heures.",
     ("Au plus tard dans les 72 heures", "Le délai constitutionnel est de 24 heures, pas 72."),
     ("Dans un délai d’une semaine", "Une semaine serait bien trop long : la Constitution fixe 24 heures."),
     ("Aucun délai n’est fixé", "La Constitution fixe expressément un délai de 24 heures.")),
    ("m", "Peut-on être condamné pour un acte qui n’était pas interdit par la loi au moment des faits ?",
     "Non : pas d’infraction ni de peine sans loi",
     "Principe de légalité : on ne peut être puni que pour un acte déjà interdit par la loi au moment où il a été commis.",
     ("Oui, si la nouvelle loi est plus sévère", "Une loi pénale plus sévère ne s’applique pas aux faits passés."),
     ("Oui, si le juge estime l’acte immoral", "Le juge ne peut pas créer d’infraction : seule la loi le peut."),
     ("Oui, pendant cinq ans après les faits", "Aucun délai ne permet de punir un acte qui n’était pas interdit.")),
    ("m", "La liberté d’expression est-elle absolue au Luxembourg ?",
     "Non : elle est garantie, mais les abus sont punissables",
     "La liberté d’expression est garantie ; on répond toutefois des abus comme la diffamation ou l’incitation à la haine.",
     ("Oui, aucune limite n’est possible", "La loi sanctionne les abus (diffamation, incitation à la haine)."),
     ("Non, toute critique du gouvernement est interdite", "Critiquer le gouvernement est protégé par la liberté d’expression."),
     ("Oui, mais seulement pour les journalistes", "La liberté d’expression appartient à tous, pas à la seule presse.")),
    ("e", "La Constitution luxembourgeoise permet-elle d’instaurer une censure de la presse ?",
     "Non, la censure est interdite",
     "La Constitution garantit la liberté de la presse et interdit la censure ; les abus (diffamation, par exemple) sont sanctionnés après coup par les juges, jamais par un contrôle préalable.",
     ("Oui, pendant les campagnes électorales", "Aucune période ne permet la censure."),
     ("Oui, sur décision du Grand-Duc", "Le Grand-Duc n’a aucun pouvoir de censure."),
     ("Oui, pour les médias étrangers", "L’interdiction de la censure vaut pour tous les médias.")),
    ("m", "Que garantit exactement la liberté de religion au Luxembourg ?",
     "Pratiquer une religion, en changer ou n’en avoir aucune",
     "La liberté de conscience et de religion inclut le droit de ne pas avoir de religion et d’en changer.",
     ("Pratiquer uniquement la religion catholique", "Il n’y a pas de religion obligatoire ; toutes les convictions sont libres."),
     ("Pratiquer seulement un culte reconnu par l’État", "La liberté de religion ne dépend pas d’une reconnaissance officielle."),
     ("Pratiquer en privé, jamais en public", "Le culte public est libre, dans le respect de la loi.")),
    ("h", "Quelle est la relation entre les Églises et l’État selon la Constitution de 2023 ?",
     "Les Églises sont séparées de l’État",
     "Les Églises et communautés religieuses sont séparées de l’État ; des conventions peuvent régler leurs relations.",
     ("Le catholicisme est religion d’État", "Le Luxembourg n’a pas de religion d’État."),
     ("L’État nomme les évêques et les imams", "Séparation oblige : l’État ne nomme pas les ministres des cultes."),
     ("Les cultes sont interdits dans l’espace public", "La liberté de culte, y compris publique, est garantie.")),
    ("e", "À quelles conditions la Constitution garantit-elle le droit de se réunir ?",
     "Paisiblement et sans armes",
     "Le droit de réunion est garanti pour les réunions paisibles et sans armes ; les rassemblements en plein air restent soumis aux lois de police.",
     ("Avec l’autorisation préalable du Grand-Duc", "Aucune autorisation du Grand-Duc n’est requise."),
     ("Uniquement dans des lieux privés", "On peut aussi se réunir en public, dans le respect des lois de police."),
     ("Seulement pendant les campagnes électorales", "Le droit de réunion vaut toute l’année.")),
    ("m", "Combien de signatures une pétition publique doit-elle réunir pour être débattue à la Chambre des Députés ?",
     "5 500 signatures en 42 jours",
     "Une pétition publique qui réunit 5 500 signatures en 42 jours donne lieu à un débat public à la Chambre.",
     ("1 000 signatures en 30 jours", "Le seuil est de 5 500 signatures, pas 1 000."),
     ("12 500 signatures en 6 mois", "12 500 est le seuil de l’initiative législative citoyenne, pas de la pétition."),
     ("50 000 signatures en un an", "Le seuil réel est bien plus bas : 5 500 en 42 jours.")),
    ("m", "Que protège la Constitution en matière de vie privée ?",
     "Le domicile, les communications et les données personnelles",
     "La Constitution garantit l’inviolabilité du domicile, le secret des communications et la protection des données personnelles.",
     ("Uniquement le domicile des propriétaires", "Le domicile est protégé que l’on soit propriétaire ou locataire."),
     ("Uniquement les lettres envoyées par la poste", "Toutes les communications sont protégées, pas seulement le courrier."),
     ("Rien : la vie privée relève du seul Code civil", "La vie privée est protégée par la Constitution elle-même.")),
    ("m", "Dans quel cas une personne peut-elle être privée de sa propriété ?",
     "Pour utilité publique, contre une juste indemnité",
     "L’expropriation n’est possible que pour cause d’utilité publique et moyennant une juste indemnité, dans les cas prévus par la loi.",
     ("Sur simple décision du bourgmestre", "Le bourgmestre ne peut pas exproprier de sa propre autorité."),
     ("Jamais, en aucune circonstance", "L’expropriation pour utilité publique existe, avec indemnité."),
     ("En cas de dette fiscale, sans indemnité", "Une privation de propriété sans indemnité est contraire à la Constitution.")),
    ("e", "L’enseignement public fondamental et secondaire est-il payant au Luxembourg ?",
     "Non, il est gratuit",
     "L’enseignement public fondamental et secondaire est gratuit pour tous les enfants scolarisés au Luxembourg.",
     ("Oui, pour les enfants de nationalité étrangère", "La gratuité ne dépend pas de la nationalité."),
     ("Oui, des frais annuels s’appliquent à tous", "L’école publique ne facture pas de frais de scolarité."),
     ("Seul l’enseignement fondamental est gratuit", "Le secondaire public est aussi gratuit.")),
    ("m", "Jusqu’à quel âge l’obligation scolaire est-elle progressivement étendue depuis la rentrée 2026 ?",
     "18 ans",
     "L’obligation scolaire, auparavant fixée à 16 ans, est étendue progressivement jusqu’à 18 ans depuis la rentrée 2026.",
     ("16 ans", "16 ans était l’ancienne limite, avant la réforme."),
     ("15 ans", "15 ans n’a jamais été la limite actuelle au Luxembourg."),
     ("21 ans", "La nouvelle limite est 18 ans, pas 21.")),
    ("e", "Les salariés au Luxembourg disposent-ils du droit de grève et de la liberté syndicale ?",
     "Oui, dans le cadre de la loi",
     "La Constitution garantit la liberté syndicale et le droit de grève, exercés dans le cadre prévu par la loi.",
     ("Non, la grève est interdite", "Le droit de grève est reconnu."),
     ("Seulement les fonctionnaires", "Ces droits concernent tous les salariés."),
     ("Seulement avec l’accord du Premier ministre", "Aucune autorisation gouvernementale n’est exigée.")),
    ("h", "Quels objectifs sociaux l’État doit-il poursuivre selon la Constitution de 2023 ?",
     "Travail, vie digne et accès à un logement approprié",
     "La Constitution fixe des objectifs à valeur constitutionnelle : droit au travail, vie digne et accès à un logement approprié.",
     ("Un revenu identique pour tous les habitants", "La Constitution ne prévoit pas de revenu égal pour tous."),
     ("Un logement en propriété pour chaque famille", "L’objectif est l’accès à un logement approprié, pas la propriété."),
     ("Un emploi à vie dans la fonction publique", "Le droit au travail ne garantit pas un emploi public.")),
    ("h", "Quelle place la Constitution de 2023 donne-t-elle à l’environnement ?",
     "L’État protège l’environnement, le climat et le bien-être animal",
     "Parmi les objectifs de l’État : protéger l’environnement et le climat et veiller au bien-être des animaux, êtres sensibles.",
     ("Aucune : c’est une compétence communale", "L’environnement figure bien dans la Constitution."),
     ("Elle interdit toute activité industrielle", "La Constitution fixe des objectifs, pas une interdiction de l’industrie."),
     ("Elle confie l’environnement à l’UE seule", "L’État luxembourgeois reste tenu par cet objectif.")),
    ("m", "L’affiliation à la sécurité sociale (maladie, pension, accident) est-elle facultative ?",
     "Non, elle est obligatoire",
     "L’affiliation est obligatoire pour les salariés comme pour les indépendants qui travaillent au Luxembourg.",
     ("Oui, chacun choisit une assurance privée", "L’assurance sociale publique est obligatoire."),
     ("Obligatoire seulement pour les fonctionnaires", "Salariés du privé et indépendants sont aussi affiliés."),
     ("Obligatoire après cinq ans de résidence", "L’affiliation commence avec l’activité, sans délai de résidence.")),
    ("e", "Le mariage entre deux personnes de même sexe est-il possible au Luxembourg ?",
     "Oui, depuis 2015, adoption comprise",
     "Le mariage est ouvert aux couples de même sexe depuis 2015, avec les mêmes droits, y compris l’adoption.",
     ("Non, seul le partenariat est possible", "Le mariage est ouvert à tous les couples depuis 2015."),
     ("Oui, mais sans droit à l’adoption", "L’adoption est permise aux couples mariés de même sexe."),
     ("Non, la Constitution l’interdit", "Rien dans la Constitution n’interdit ce mariage.")),
    ("e", "Comment la loi luxembourgeoise traite-t-elle le mariage forcé ?",
     "Il est interdit et puni",
     "Le mariage exige le libre consentement des deux époux ; forcer quelqu’un à se marier est une infraction pénale.",
     ("Il est toléré si les familles sont d’accord", "Seul compte le consentement des époux eux-mêmes."),
     ("Il est valable s’il est célébré à l’étranger", "Un mariage forcé n’est pas valable, où qu’il soit célébré."),
     ("Il est seulement déconseillé", "C’est une infraction, pas une simple recommandation.")),
    ("m", "En cas de violence domestique, quelle mesure la police peut-elle prendre ?",
     "Expulser l’auteur du domicile pour 14 jours",
     "Avec l’autorisation du procureur d’État, la police peut expulser l’auteur du domicile pour 14 jours afin de protéger la victime.",
     ("Expulser l’auteur pour 48 heures sur décision du bourgmestre", "La durée est de 14 jours et l’autorisation vient du procureur."),
     ("Proposer seulement une médiation familiale", "La violence domestique est une infraction, pas une affaire privée."),
     ("Attendre une plainte écrite de la victime", "La police peut agir sans plainte écrite préalable.")),
    ("m", "Quelle institution aide les personnes qui s’estiment victimes de discrimination ?",
     "Le Centre pour l’égalité de traitement (CET)",
     "Le CET informe et accompagne les victimes de discrimination (origine, sexe, religion, handicap, âge…).",
     ("La Cour des comptes", "Elle contrôle les finances publiques, pas la discrimination."),
     ("La Chambre de commerce", "C’est une chambre professionnelle des entreprises."),
     ("Le Conseil d’État", "Il donne des avis sur les lois, il n’aide pas les victimes.")),
    ("h", "Quel ombudsman défend spécifiquement les droits des enfants et des jeunes ?",
     "L’OKAJU",
     "L’OKAJU (Ombudsman fir Kanner a Jugendlecher) veille au respect des droits de l’enfant ; enfants, parents et professionnels peuvent le saisir gratuitement.",
     ("Le Médiateur du Grand-Duché", "Le Médiateur traite les réclamations contre l’administration en général."),
     ("La CCDH", "La CCDH conseille le gouvernement sur les droits humains en général."),
     ("L’ONE", "L’Office national de l’enfance organise l’aide à l’enfance, ce n’est pas un ombudsman.")),
    ("h", "Quel organe conseille le gouvernement en matière de droits humains ?",
     "La Commission consultative des droits de l’Homme",
     "La CCDH est l’institution nationale des droits de l’Homme : elle conseille le gouvernement et la Chambre.",
     ("Le Centre pour l’égalité de traitement", "Le CET se concentre sur l’aide aux victimes de discrimination."),
     ("La Cour constitutionnelle", "Elle juge la constitutionnalité des lois ; elle ne conseille pas."),
     ("L’OKAJU", "L’OKAJU est dédié aux droits des enfants.")),
    ("e", "Qui peut voter aux élections législatives au Luxembourg ?",
     "Les Luxembourgeois d’au moins 18 ans",
     "Seuls les citoyens luxembourgeois âgés d’au moins 18 ans votent aux élections législatives ; les étrangers inscrits votent aux communales (et aux européennes pour les citoyens de l’UE).",
     ("Tous les résidents majeurs", "Les résidents étrangers ne votent pas aux législatives."),
     ("Les Luxembourgeois dès 16 ans", "L’âge du vote est 18 ans."),
     ("Les citoyens de l’UE résidents inscrits", "Ils votent aux communales et européennes, pas aux législatives.")),
    ("m", "Le vote est-il obligatoire au Luxembourg ?",
     "Oui, pour les inscrits ; dispense dès 75 ans",
     "Le vote est obligatoire pour tous les électeurs inscrits ; les électeurs de plus de 75 ans en sont dispensés.",
     ("Non, il est facultatif", "Le vote est obligatoire pour les inscrits."),
     ("Oui, mais seulement aux communales", "L’obligation vaut pour toutes les élections où l’on est inscrit."),
     ("Oui, sans aucune dispense", "Une dispense existe à partir de 75 ans.")),
    ("m", "Un résident étranger peut-il voter aux élections communales ?",
     "Oui, s’il est majeur et inscrit sur les listes",
     "Depuis 2023, aucune durée minimale de résidence n’est exigée : il suffit d’être majeur et inscrit sur les listes électorales.",
     ("Non, jamais", "Les étrangers inscrits votent aux communales."),
     ("Oui, après cinq ans de résidence", "La condition de résidence a été supprimée en 2023."),
     ("Oui, seulement s’il est citoyen de l’UE", "Les ressortissants hors UE peuvent aussi voter aux communales.")),
    ("m", "Qui peut voter aux élections européennes au Luxembourg ?",
     "Les Luxembourgeois et les citoyens de l’UE inscrits",
     "Les citoyens de l’UE résidant au Luxembourg peuvent s’inscrire pour y voter aux européennes, comme les Luxembourgeois.",
     ("Tous les résidents, quelle que soit leur nationalité", "Les ressortissants hors UE ne votent pas aux européennes."),
     ("Seulement les Luxembourgeois", "Les citoyens de l’UE résidents peuvent aussi voter."),
     ("Seulement les fonctionnaires européens", "Le droit de vote ne dépend pas de l’emploi.")),
    ("h", "Lors du référendum de 2015, qu’ont décidé les électeurs sur le vote des étrangers aux législatives ?",
     "Ils l’ont rejeté à environ 78 %",
     "En 2015, environ 78 % des votants ont rejeté le droit de vote des résidents étrangers aux élections législatives.",
     ("Ils l’ont accepté à environ 60 %", "La proposition a été nettement rejetée."),
     ("Ils l’ont accepté pour les citoyens de l’UE", "Aucune variante n’a été adoptée."),
     ("Le référendum a été annulé", "Le référendum a bien eu lieu, le 7 juin 2015.")),
    ("m", "Le droit d’asile est-il garanti par la Constitution luxembourgeoise ?",
     "Oui, dans les conditions fixées par la loi",
     "La Constitution garantit le droit d’asile ; la loi en fixe les conditions et la procédure, et l’ONA héberge les demandeurs de protection internationale.",
     ("Non, il relève seulement du droit européen", "Il figure aussi dans la Constitution luxembourgeoise."),
     ("Seulement pour les citoyens européens", "Les citoyens de l’UE ne demandent pas l’asile entre États membres."),
     ("Non, il a été supprimé en 2023", "La Constitution de 2023 le garantit expressément.")),
    ("h", "Les emplois publics sont-ils ouverts aux non-Luxembourgeois ?",
     "En principe oui, sauf ceux liés à la puissance publique",
     "Les emplois publics sont ouverts en principe ; la loi peut réserver aux Luxembourgeois ceux qui touchent à l’exercice de la puissance publique.",
     ("Non, ils sont tous réservés aux Luxembourgeois", "La plupart des emplois publics sont ouverts aux étrangers."),
     ("Oui, sans aucune exception", "Certains postes de puissance publique peuvent être réservés."),
     ("Seulement aux travailleurs frontaliers", "Le critère est la nature du poste, pas le lieu de résidence.")),
    ("m", "Quelle loi permet de s’adresser à l’administration en luxembourgeois, en français ou en allemand ?",
     "La loi du 24 février 1984 sur le régime des langues",
     "La loi de 1984 fait du luxembourgeois la langue nationale et permet d’écrire à l’administration dans l’une des trois langues.",
     ("La loi de 2017 sur la nationalité", "Cette loi règle l’acquisition de la nationalité, pas les langues administratives."),
     ("Le traité de Londres de 1867", "Ce traité concerne la neutralité, pas les langues."),
     ("Le règlement grand-ducal de 2017 sur Vivre ensemble", "Il organise le cours et l’examen, pas le régime des langues.")),
    ("e", "Comment se déroule le vote lors des élections au Luxembourg ?",
     "Le vote est libre et secret",
     "Le suffrage est universel, libre et secret : personne ne peut connaître ni imposer le choix de l’électeur.",
     ("À main levée dans chaque commune", "Le vote se fait à bulletin secret."),
     ("Publiquement, sur une liste signée", "Le secret du vote est garanti."),
     ("Uniquement par vote électronique", "On vote au bureau de vote ou par correspondance.")),
    ("e", "Quel texte garantit les droits fondamentaux et les libertés publiques au Luxembourg ?",
     "La Constitution",
     "Les droits fondamentaux sont inscrits dans la Constitution, entièrement refondue et entrée en vigueur le 1er juillet 2023.",
     ("Le Code civil", "Le Code civil règle les rapports privés, pas les droits fondamentaux."),
     ("Le règlement de la Chambre des Députés", "Il organise le travail du parlement."),
     ("La loi communale", "Elle organise les communes.")),
    ("m", "Quels droits la Constitution reconnaît-elle spécifiquement aux enfants ?",
     "Leur intérêt prime et ils peuvent exprimer leur opinion",
     "L’intérêt de l’enfant est pris en considération de manière primordiale, et l’enfant peut exprimer librement son opinion.",
     ("Le droit de vote dès 12 ans", "Le droit de vote commence à 18 ans."),
     ("L’autorité exclusive du père sur l’enfant", "Les parents sont égaux ; c’est l’intérêt de l’enfant qui prime."),
     ("Aucun droit propre avant 18 ans", "Les enfants ont des droits propres garantis par la Constitution.")),
    ("e", "Quels grands devoirs s’imposent aux personnes qui vivent au Luxembourg ?",
     "Respecter les lois, payer ses impôts, scolariser ses enfants",
     "Droits et devoirs vont ensemble : respect des lois, contribution fiscale, obligation scolaire, et vote pour les inscrits.",
     ("Parler luxembourgeois en public", "Aucune loi n’impose une langue dans la vie privée ou publique."),
     ("Adhérer à un parti politique", "L’adhésion à un parti est libre, jamais obligatoire."),
     ("Effectuer un service militaire", "Le service militaire obligatoire a été aboli en 1967.")),
    ("m", "Quels principes protègent toute personne poursuivie devant un tribunal ?",
     "La présomption d’innocence et les droits de la défense",
     "Toute personne est présumée innocente jusqu’à sa condamnation et a le droit de se défendre, avec un avocat.",
     ("La présomption de culpabilité jusqu’au procès", "C’est l’inverse : la présomption d’innocence."),
     ("Un jugement toujours à huis clos", "Les audiences sont en principe publiques."),
     ("L’interdiction de l’avocat en première instance", "Le droit à un avocat fait partie des droits de la défense.")),
    ("m", "Qu’est-ce que l’assistance judiciaire au Luxembourg ?",
     "La prise en charge des frais de justice des personnes aux revenus insuffisants",
     "L’assistance judiciaire paie les frais d’avocat et de procédure de ceux qui n’en ont pas les moyens, pour garantir l’accès au juge.",
     ("Une aide administrative réservée aux juges", "Elle aide les justiciables, pas les magistrats."),
     ("Un service de police de proximité", "Ce n’est pas un service de police."),
     ("Une assurance privée obligatoire", "C’est une aide publique, sous conditions de ressources.")),
    ("m", "Quel rôle la Constitution reconnaît-elle aux partis politiques ?",
     "Ils concourent à la formation de la volonté populaire",
     "Les partis concourent à la formation de la volonté populaire et à l’expression du suffrage universel.",
     ("Aucun : ils ne sont pas mentionnés", "La Constitution de 2023 les mentionne expressément."),
     ("Un seul parti est autorisé", "Le pluralisme politique est garanti."),
     ("Ils nomment directement les ministres", "C’est le Grand-Duc qui nomme les ministres, selon le résultat des élections.")),
    ("m", "Que protège la liberté d’association au Luxembourg ?",
     "Le droit de créer ou de rejoindre une association, un parti ou un syndicat",
     "Chacun peut librement fonder une association ou y adhérer — et nul ne peut être forcé d’en faire partie.",
     ("L’obligation d’adhérer à un syndicat", "L’adhésion est libre, jamais obligatoire."),
     ("Seulement les associations sportives", "La liberté vaut pour tout type d’association licite."),
     ("Seulement avec une autorisation communale", "Aucune autorisation préalable n’est requise.")),
]

INSTITUTIONS = [
    ("e", "Comment l’article 1er de la Constitution définit-il le Grand-Duché de Luxembourg ?",
     "Un État démocratique, libre, indépendant et indivisible",
     "L’article 1er pose les quatre caractères de l’État : démocratique, libre, indépendant et indivisible.",
     ("Un État fédéral composé de cantons autonomes", "Le Luxembourg est un État unitaire ; les cantons n’ont pas d’autonomie politique."),
     ("Une province autonome du Benelux", "Le Luxembourg est un État souverain."),
     ("Une république parlementaire", "Le Luxembourg est une monarchie constitutionnelle.")),
    ("e", "Quelle est la forme de l’État luxembourgeois selon la Constitution ?",
     "Une démocratie parlementaire sous forme de monarchie constitutionnelle",
     "Le Grand-Duc est chef de l’État, mais le pouvoir est exercé dans le cadre d’une démocratie parlementaire.",
     ("Une monarchie absolue", "Les pouvoirs du Grand-Duc sont limités par la Constitution."),
     ("Une république présidentielle", "Il n’y a pas de président de la République."),
     ("Une confédération de communes", "Le Luxembourg est un État unitaire.")),
    ("m", "Où réside la souveraineté selon la Constitution luxembourgeoise ?",
     "Dans la Nation",
     "La souveraineté réside dans la Nation, dont émanent tous les pouvoirs de l’État ; le Grand-Duc exerce ses fonctions au nom de la Nation, sans détenir la souveraineté.",
     ("Dans la personne du Grand-Duc", "Le Grand-Duc exerce des fonctions constitutionnelles ; la souveraineté appartient à la Nation."),
     ("Dans le gouvernement", "Le gouvernement exerce le pouvoir exécutif, il ne détient pas la souveraineté."),
     ("Dans l’Union européenne", "L’UE exerce des compétences transférées, pas la souveraineté nationale.")),
    ("m", "Quel principe répartit les pouvoirs législatif, exécutif et judiciaire au Luxembourg ?",
     "La séparation des pouvoirs",
     "Le législatif (Chambre), l’exécutif (Grand-Duc et gouvernement) et le judiciaire (tribunaux) sont séparés et se contrôlent.",
     ("La concentration des pouvoirs chez le Grand-Duc", "Le Grand-Duc n’exerce aucun pouvoir seul."),
     ("La subordination des juges au gouvernement", "Les juges sont indépendants."),
     ("La fusion du parlement et du gouvernement", "La Chambre contrôle le gouvernement, elle ne se confond pas avec lui.")),
    ("e", "Qui est le chef de l’État du Grand-Duché de Luxembourg ?",
     "Le Grand-Duc",
     "Le Grand-Duc est le chef de l’État et le symbole de l’unité et de l’indépendance nationales ; le gouvernement, lui, est dirigé par le Premier ministre.",
     ("Le Premier ministre", "Le Premier ministre dirige le gouvernement ; il n’est pas chef de l’État."),
     ("Le président de la Chambre des Députés", "Il préside le parlement."),
     ("Le président du Conseil d’État", "Il dirige un organe consultatif.")),
    ("m", "Qui est le Grand-Duc actuel du Luxembourg, et depuis quand ?",
     "Guillaume, depuis le 3 octobre 2025",
     "Le Grand-Duc Henri, qui régnait depuis 2000, a abdiqué en faveur de son fils Guillaume, qui règne depuis le 3 octobre 2025.",
     ("Henri, depuis 2000", "Henri a régné de 2000 à 2025, puis a abdiqué."),
     ("Jean, depuis 1964", "Jean a régné de 1964 à 2000."),
     ("Charlotte, depuis 1919", "Charlotte a régné de 1919 à 1964.")),
    ("m", "À quelle dynastie appartient la famille grand-ducale ?",
     "La maison de Nassau (branche Nassau-Weilburg)",
     "La fonction de chef de l’État est héréditaire dans la descendance d’Adolphe de Nassau, Grand-Duc depuis 1890.",
     ("La maison de Habsbourg", "Les Habsbourg ont régné sur le Luxembourg sous l’Ancien Régime, pas aujourd’hui."),
     ("La maison de Bourbon", "Les Bourbon sont liés à la France et à l’Espagne ; la famille grand-ducale descend d’Adolphe de Nassau."),
     ("La maison d’Orange-Nassau", "Orange-Nassau est la maison royale néerlandaise ; l’union personnelle a pris fin en 1890.")),
    ("m", "Devant quelle institution le Grand-Duc prête-t-il serment lors de son accession au trône ?",
     "La Chambre des Députés",
     "Le Grand-Duc prête serment devant la Chambre des Députés de respecter la Constitution et les lois ; c’est la Chambre qui représente le pays.",
     ("Le Conseil d’État", "Le Conseil d’État est consultatif ; le serment se prête devant la Chambre."),
     ("La Cour constitutionnelle", "La Cour ne reçoit pas le serment du Grand-Duc."),
     ("L’archevêque de Luxembourg", "L’État est séparé des Églises ; le serment est constitutionnel.")),
    ("m", "Pourquoi un membre du gouvernement contresigne-t-il les actes du Grand-Duc ?",
     "Parce que le ministre en assume la responsabilité politique",
     "Le Grand-Duc n’est pas politiquement responsable : le ministre qui contresigne répond de l’acte devant la Chambre.",
     ("Pour vérifier la signature du Grand-Duc", "Le contreseing est une question de responsabilité, pas d’authenticité."),
     ("Parce que le ministre peut annuler l’acte", "Le ministre ne peut pas annuler un acte déjà pris."),
     ("Parce que c’est une simple tradition sans effet", "Le contreseing a une portée constitutionnelle.")),
    ("m", "Que fait le Grand-Duc une fois qu’une loi a été votée par la Chambre des Députés ?",
     "Il la promulgue dans les trois mois",
     "Depuis la réforme de 2009, le Grand-Duc promulgue les lois ; il ne les « sanctionne » plus et ne peut donc pas les bloquer.",
     ("Il la sanctionne ou la rejette librement", "Le droit de sanction a été supprimé en 2009."),
     ("Il la soumet obligatoirement à référendum", "Le référendum n’est pas automatique."),
     ("Il la renvoie au Conseil d’État pour un vote", "Le Conseil d’État ne vote pas les lois.")),
    ("h", "Le Grand-Duc peut-il encore empêcher l’entrée en vigueur d’une loi votée par la Chambre ?",
     "Non, il n’a plus de droit de sanction depuis 2009",
     "Après le refus du Grand-Duc Henri de sanctionner la loi sur l’euthanasie, la Constitution a été révisée en 2009 : il promulgue sans pouvoir bloquer.",
     ("Oui, s’il refuse de la signer", "Ce refus n’est plus possible depuis 2009."),
     ("Oui, avec l’accord du Conseil d’État", "Le Conseil d’État n’a pas de droit de veto non plus."),
     ("Oui, pour les lois budgétaires uniquement", "Aucun type de loi n’échappe à la promulgation obligatoire.")),
    ("m", "Quand un traité international signé par le Luxembourg produit-il ses effets ?",
     "Après son approbation par une loi",
     "Le Grand-Duc fait les traités, mais ils n’ont d’effet qu’après avoir été approuvés par une loi et publiés.",
     ("Dès la signature du Grand-Duc", "L’approbation par la Chambre est indispensable."),
     ("Après un avis de la Commission européenne", "La Commission n’approuve pas les traités luxembourgeois."),
     ("Après un référendum obligatoire", "Le référendum n’est pas requis pour les traités.")),
    ("m", "En quoi consiste le droit de grâce du Grand-Duc ?",
     "Remettre ou réduire les peines prononcées par les juges",
     "Le droit de grâce permet au Grand-Duc de remettre ou de réduire une peine ; il n’annule pas la condamnation, qui reste inscrite.",
     ("Annuler un jugement et rejuger l’affaire", "La grâce n’efface pas la décision de justice."),
     ("Dispenser un citoyen de payer ses impôts", "La grâce concerne les peines, pas l’impôt."),
     ("Accorder la nationalité sans conditions", "La nationalité relève d’une procédure légale distincte.")),
    ("h", "Que peut faire l’exécutif en cas de crise nationale grave ?",
     "Déclarer l’état de crise, limité à 10 jours sans loi",
     "L’état de crise permet des mesures urgentes ; au-delà de 10 jours, une loi votée aux 2/3 doit le prolonger, pour 3 mois au plus.",
     ("Suspendre la Constitution sans limite de durée", "L’état de crise est limité dans le temps et contrôlé par la Chambre."),
     ("Dissoudre la Chambre des Députés sans élections", "Des élections restent obligatoires en cas de dissolution."),
     ("Transférer tous les pouvoirs à l’armée", "Aucune disposition ne prévoit un tel transfert.")),
    ("e", "Qui dirige le gouvernement luxembourgeois ?",
     "Le Premier ministre",
     "Le Premier ministre dirige et coordonne l’action du gouvernement ; il est nommé par le Grand-Duc en fonction de la majorité à la Chambre.",
     ("Le Grand-Duc", "Le Grand-Duc est chef de l’État, pas chef du gouvernement."),
     ("Le président de la Chambre des Députés", "Il préside le parlement."),
     ("Le bourgmestre de la Ville de Luxembourg", "Il dirige une commune.")),
    ("m", "Qui est Premier ministre du Luxembourg depuis novembre 2023 ?",
     "Luc Frieden",
     "Après les élections d’octobre 2023, Luc Frieden (CSV) dirige un gouvernement CSV-DP ; il a succédé à Xavier Bettel (DP).",
     ("Xavier Bettel", "Xavier Bettel a été Premier ministre de 2013 à 2023."),
     ("Jean-Claude Juncker", "Jean-Claude Juncker a été Premier ministre de 1995 à 2013."),
     ("Jacques Santer", "Jacques Santer a été Premier ministre de 1984 à 1995.")),
    ("m", "Comment le gouvernement luxembourgeois est-il formé après des élections législatives ?",
     "Le Grand-Duc nomme le Premier ministre et les ministres selon le résultat des élections",
     "Le Grand-Duc nomme le gouvernement en tenant compte de la majorité issue des élections à la Chambre.",
     ("Les électeurs élisent directement le Premier ministre", "Il n’y a pas d’élection directe du Premier ministre."),
     ("Le Conseil d’État désigne les ministres", "Le Conseil d’État n’intervient pas dans la formation du gouvernement."),
     ("Les bourgmestres élisent les ministres", "Les communes ne participent pas à cette nomination.")),
    ("e", "Devant quelle institution le gouvernement luxembourgeois est-il politiquement responsable ?",
     "La Chambre des Députés",
     "Le gouvernement doit avoir la confiance de la Chambre ; celle-ci peut voter la censure, ce qui peut conduire à des élections anticipées.",
     ("Le Conseil d’État", "Le Conseil d’État est consultatif et ne contrôle pas le gouvernement."),
     ("Le Grand-Duc seul", "La responsabilité politique s’exerce devant la Chambre."),
     ("La Cour constitutionnelle", "Elle contrôle les lois, pas la politique du gouvernement.")),
    ("h", "Dans quels cas des élections législatives anticipées peuvent-elles avoir lieu ?",
     "Si la Chambre refuse la confiance ou vote la censure, ou si le gouvernement démissionne avec son accord",
     "La Constitution de 2023 encadre la dissolution : elle n’est possible qu’après une crise de confiance entre Chambre et gouvernement.",
     ("À tout moment, sur simple décision du Grand-Duc", "La dissolution n’est plus laissée à la seule initiative du Grand-Duc."),
     ("Chaque fois qu’un ministre démissionne", "La démission d’un seul ministre ne provoque pas d’élections."),
     ("Sur demande de 1 000 électeurs", "Aucune initiative citoyenne ne permet de dissoudre la Chambre.")),
    ("e", "Comment s’appelle le parlement du Grand-Duché de Luxembourg ?",
     "La Chambre des Députés",
     "La Chambre des Députés est l’unique assemblée parlementaire du pays ; ses 60 membres votent les lois et contrôlent le gouvernement.",
     ("L’Assemblée nationale", "C’est le nom du parlement français."),
     ("Le Sénat grand-ducal", "Le Luxembourg n’a pas de Sénat."),
     ("Le Conseil d’État", "Le Conseil d’État est un organe consultatif, pas le parlement.")),
    ("m", "Le parlement luxembourgeois comporte-t-il une seconde chambre, comme un Sénat ?",
     "Non, il est monocaméral",
     "Le parlement est monocaméral ; le Conseil d’État joue un rôle consultatif, sans être une seconde chambre.",
     ("Oui, le Conseil d’État est un Sénat élu", "Le Conseil d’État n’est pas élu et ne vote pas les lois."),
     ("Oui, une chambre des communes", "Il n’existe pas de chambre représentant les communes."),
     ("Oui, une chambre réservée aux nobles", "Aucune chambre haute n’existe au Luxembourg.")),
    ("e", "Combien de députés siègent à la Chambre des Députés du Luxembourg ?",
     "60 députés",
     "La Chambre compte 60 députés, élus pour 5 ans dans quatre circonscriptions (Sud, Centre, Nord, Est).",
     ("100 députés", "Le chiffre 100 correspond aux communes, pas aux députés."),
     ("40 députés", "Le chiffre 40 correspond aux questions de l’examen."),
     ("21 députés", "21 est le nombre de membres du Conseil d’État.")),
    ("e", "Pour quelle durée les députés luxembourgeois sont-ils élus ?",
     "5 ans",
     "Les élections législatives ont lieu tous les 5 ans, sauf élections anticipées ; les conseils communaux, eux, sont élus pour 6 ans.",
     ("6 ans", "6 ans est la durée du mandat des conseillers communaux."),
     ("4 ans", "Le mandat des députés est de 5 ans."),
     ("7 ans", "Aucun mandat électif luxembourgeois ne dure 7 ans.")),
    ("m", "Combien de circonscriptions électorales existe-t-il pour les élections législatives ?",
     "4 : Sud, Centre, Nord et Est",
     "Les 60 sièges sont répartis entre quatre circonscriptions : Sud, Centre, Nord et Est — qui regroupent les 12 cantons.",
     ("12, une par canton", "Les 12 cantons sont regroupés en 4 circonscriptions."),
     ("1 seule pour tout le pays", "Il y a quatre circonscriptions."),
     ("100, une par commune", "Les communes ne sont pas des circonscriptions législatives.")),
    ("h", "Quels cantons forment la circonscription électorale Sud ?",
     "Esch-sur-Alzette et Capellen",
     "La circonscription Sud, la plus peuplée, regroupe les cantons d’Esch-sur-Alzette et de Capellen ; elle élit le plus grand nombre de députés.",
     ("Luxembourg et Mersch", "Ces cantons forment la circonscription Centre."),
     ("Diekirch et Clervaux", "Ces cantons font partie de la circonscription Nord."),
     ("Grevenmacher et Remich", "Ces cantons font partie de la circonscription Est.")),
    ("m", "Quel mode de scrutin s’applique aux élections législatives luxembourgeoises ?",
     "La représentation proportionnelle, avec panachage possible",
     "L’électeur peut voter pour une liste entière ou répartir ses voix entre candidats de listes différentes (panachage).",
     ("Le scrutin majoritaire à deux tours", "C’est le système français, pas luxembourgeois."),
     ("Le tirage au sort des députés", "Les députés sont élus."),
     ("L’élection indirecte par les communes", "Les députés sont élus directement.")),
    ("m", "Quelles conditions faut-il remplir pour être élu député au Luxembourg ?",
     "Être luxembourgeois, avoir 18 ans et être domicilié au pays",
     "Pour être éligible à la Chambre, il faut être luxembourgeois, âgé d’au moins 18 ans et domicilié au Luxembourg.",
     ("Avoir 25 ans et un diplôme universitaire", "Il n’y a ni condition de diplôme ni âge de 25 ans."),
     ("Résider au pays depuis 10 ans, quelle que soit la nationalité", "La nationalité luxembourgeoise est requise."),
     ("Être membre d’une commune depuis 6 ans", "Aucun mandat communal préalable n’est exigé.")),
    ("m", "Peut-on être à la fois député et membre du gouvernement au Luxembourg ?",
     "Non, les deux fonctions sont incompatibles",
     "Un député nommé ministre quitte la Chambre : le mandat est incompatible avec le gouvernement et avec le Conseil d’État.",
     ("Oui, c’est la règle pour tous les ministres", "L’incompatibilité est expressément prévue."),
     ("Oui, mais seulement pour le Premier ministre", "L’incompatibilité vaut pour tout membre du gouvernement."),
     ("Oui, pendant la première année", "Il n’existe pas de période de cumul autorisée.")),
    ("e", "Quelles sont les principales missions de la Chambre des Députés ?",
     "Voter les lois et le budget, et contrôler le gouvernement",
     "La Chambre légifère, vote chaque année le budget et les impôts, et contrôle l’action du gouvernement.",
     ("Nommer les juges et les bourgmestres", "Ces nominations ne relèvent pas de la Chambre."),
     ("Donner un avis sur les lois du Conseil d’État", "C’est le Conseil d’État qui donne des avis sur les textes."),
     ("Commander l’armée", "L’armée relève du gouvernement ; la Chambre autorise seulement les opérations à l’étranger.")),
    ("m", "Qui peut prendre l’initiative d’une loi au Luxembourg ?",
     "Le gouvernement (projet) ou un député (proposition)",
     "Un texte déposé par le gouvernement est un projet de loi ; déposé par un député, c’est une proposition de loi.",
     ("Seul le Grand-Duc", "L’initiative appartient au gouvernement et aux députés."),
     ("Seul le Conseil d’État", "Le Conseil d’État donne son avis, il ne dépose pas de loi."),
     ("Seuls les bourgmestres", "Les communes adoptent des règlements communaux, pas des lois.")),
    ("h", "Que permet l’initiative législative citoyenne prévue par la Constitution de 2023 ?",
     "Une proposition de loi portée par 125 électeurs et soutenue par 12 500",
     "Un comité de 125 électeurs peut porter une proposition de loi ; avec au moins 12 500 soutiens, elle est examinée par la Chambre.",
     ("Abroger une loi par simple pétition de 5 500 signatures", "5 500 signatures ouvrent un débat de pétition, pas une abrogation."),
     ("Révoquer un ministre par 1 000 signatures", "Aucune procédure citoyenne ne révoque un ministre."),
     ("Dissoudre la Chambre avec 50 000 signatures", "Les citoyens ne peuvent pas dissoudre la Chambre.")),
    ("m", "À quelle majorité les lois ordinaires sont-elles adoptées par la Chambre des Députés ?",
     "À la majorité absolue des suffrages",
     "Les lois sont votées à la majorité absolue des suffrages exprimés, par vote nominal ; la majorité des 2/3 est réservée à la révision de la Constitution et à certaines lois.",
     ("À l’unanimité des 60 députés", "L’unanimité n’est pas exigée."),
     ("À la majorité des deux tiers", "Les 2/3 sont requis pour réviser la Constitution, pas pour une loi ordinaire."),
     ("Par tirage au sort en cas de doute", "Le vote est décisif, il n’y a pas de tirage.")),
    ("e", "Qui préside les séances de la Chambre des Députés ?",
     "Le président de la Chambre, élu par les députés",
     "Les députés élisent leur président, qui dirige les débats en séance plénière et représente la Chambre.",
     ("Le Premier ministre", "Le Premier ministre siège au banc du gouvernement, il ne préside pas la Chambre."),
     ("Le Grand-Duc", "Le Grand-Duc ne siège pas à la Chambre."),
     ("Le président du Conseil d’État", "Il préside un autre organe.")),
    ("m", "Comment les députés contrôlent-ils l’action des ministres ?",
     "Par des questions parlementaires, des interpellations et des motions",
     "Questions écrites et orales, heures d’actualité, interpellations et motions permettent à la Chambre de contrôler le gouvernement.",
     ("En annulant les arrêtés ministériels", "L’annulation d’actes relève des juridictions administratives."),
     ("En nommant les hauts fonctionnaires", "Les nominations relèvent de l’exécutif."),
     ("En jugeant les ministres eux-mêmes", "La Chambre contrôle politiquement ; elle ne juge pas.")),
    ("h", "Quand la Chambre des Députés doit-elle instituer une commission d’enquête ?",
     "Lorsqu’au moins un tiers des députés le demande",
     "La Constitution de 2023 renforce la minorité : un tiers des députés suffit pour imposer une commission d’enquête.",
     ("Seulement si le gouvernement l’accepte", "Le gouvernement ne peut pas bloquer la commission."),
     ("À l’unanimité des députés", "Un tiers des députés suffit."),
     ("Sur décision du Conseil d’État", "Le Conseil d’État n’intervient pas.")),
    ("m", "Un député peut-il être poursuivi pour une opinion exprimée à la Chambre ?",
     "Non, pas pour les opinions et votes émis dans l’exercice de son mandat",
     "L’immunité parlementaire protège la liberté des débats : aucun député ne peut être poursuivi pour ses opinions ou votes au parlement.",
     ("Oui, comme n’importe quel citoyen", "L’immunité protège ses opinions et votes parlementaires."),
     ("Oui, si le gouvernement le demande", "Le gouvernement ne peut pas lever cette protection."),
     ("Non, et il ne peut jamais être poursuivi pour rien", "L’immunité ne couvre pas les infractions sans lien avec le mandat.")),
    ("m", "Le gouvernement peut-il engager l’armée luxembourgeoise dans une opération à l’étranger sans le parlement ?",
     "Non, il faut l’autorisation de la Chambre",
     "Une guerre ou une opération militaire à l’étranger exige l’autorisation préalable de la Chambre des Députés.",
     ("Oui, sur simple décision du Premier ministre", "L’autorisation de la Chambre est obligatoire."),
     ("Oui, si l’OTAN le demande", "Une demande de l’OTAN ne remplace pas l’autorisation de la Chambre."),
     ("Oui, avec l’avis du Conseil d’État", "L’avis du Conseil d’État ne suffit pas.")),
    ("e", "Quel est le rôle principal du Conseil d’État luxembourgeois ?",
     "Donner un avis sur les projets de loi et les règlements",
     "Le Conseil d’État examine les textes et rend des avis (notamment « oppositions formelles ») avant le vote à la Chambre.",
     ("Voter les lois avec la Chambre", "Il ne vote pas les lois : il donne un avis."),
     ("Juger les litiges administratifs", "Depuis 1996, ce rôle revient au tribunal et à la Cour administrative."),
     ("Diriger le gouvernement", "Le gouvernement est dirigé par le Premier ministre.")),
    ("h", "Le Conseil d’État luxembourgeois vote-t-il les lois comme une seconde chambre ?",
     "Non, il donne un avis ; seule la Chambre vote",
     "C’est un piège classique : le Conseil d’État est consultatif. La Chambre des Députés est la seule assemblée qui vote les lois.",
     ("Oui, chaque loi doit être votée par les deux assemblées", "Le Conseil d’État ne vote pas les lois."),
     ("Oui, seulement pour le budget", "Le budget est voté par la seule Chambre."),
     ("Oui, il a un droit de veto définitif", "Le Conseil d’État n’a pas de veto définitif.")),
    ("m", "Combien de membres compte le Conseil d’État luxembourgeois ?",
     "21 conseillers",
     "Le Conseil d’État se compose de 21 conseillers d’État ; il donne des avis sur les textes mais ne vote pas les lois.",
     ("60 conseillers", "60 est le nombre de députés."),
     ("12 conseillers", "12 est le nombre de cantons."),
     ("9 conseillers", "9 est le nombre de membres de la Cour constitutionnelle.")),
    ("h", "Qu’est-ce que le « second vote constitutionnel » d’une loi ?",
     "Un second vote après au moins 3 mois, sauf dispense accordée avec l’accord du Conseil d’État",
     "Toute loi est soumise à un second vote après au moins trois mois, sauf si la Chambre en dispense avec l’accord du Conseil d’État — ce qui est fréquent.",
     ("Un vote du peuple après la Chambre", "Ce n’est pas un référendum."),
     ("Un vote du Conseil d’État après la Chambre", "Le Conseil d’État ne vote pas la loi."),
     ("Un nouveau vote après chaque élection", "Le second vote concerne chaque loi, pas les élections.")),
    ("h", "Comment révise-t-on la Constitution luxembourgeoise ?",
     "Deux votes de la Chambre aux 2/3, à au moins 3 mois d’intervalle",
     "La révision exige deux votes identiques à la majorité des 2/3, espacés d’au moins trois mois ; un référendum peut remplacer le second vote.",
     ("Par un simple vote à la majorité absolue", "La majorité absolue suffit pour une loi, pas pour la Constitution."),
     ("Par décret du Grand-Duc", "Le Grand-Duc ne peut pas réviser seul la Constitution."),
     ("Par décision de la Cour constitutionnelle", "La Cour contrôle les lois, elle ne révise pas la Constitution.")),
    ("m", "Que contrôle la Cour constitutionnelle du Luxembourg ?",
     "La conformité des lois à la Constitution",
     "La Cour constitutionnelle (9 membres) vérifie si une loi respecte la Constitution ; elle est saisie par un juge, à titre préjudiciel.",
     ("La régularité des comptes de l’État", "C’est le rôle de la Cour des comptes."),
     ("Les décisions des communes", "Les actes communaux relèvent des juridictions administratives."),
     ("La conformité des lois au droit européen", "Ce contrôle relève des juges ordinaires et de la CJUE.")),
    ("h", "Un citoyen peut-il saisir directement la Cour constitutionnelle ?",
     "Non : elle est saisie par un juge, au cours d’un procès",
     "La Cour est saisie par une juridiction qui lui pose une question préjudicielle sur la constitutionnalité d’une loi.",
     ("Oui, par simple lettre", "Aucun recours direct individuel n’existe."),
     ("Oui, avec 5 500 signatures", "5 500 signatures concernent les pétitions à la Chambre."),
     ("Oui, par l’intermédiaire de sa commune", "Les communes ne transmettent pas de recours à la Cour.")),
    ("m", "Quel est le rôle de la Cour des comptes du Luxembourg ?",
     "Contrôler la gestion financière de l’État",
     "La Cour des comptes contrôle l’utilisation des deniers publics et fait rapport à la Chambre ; à ne pas confondre avec la Cour des comptes européenne.",
     ("Juger les délits financiers", "Les délits relèvent des juridictions pénales."),
     ("Fixer les impôts", "Les impôts sont votés par la Chambre."),
     ("Contrôler les finances de l’UE", "C’est le rôle de la Cour des comptes européenne, installée elle aussi à Luxembourg.")),
    ("m", "À qui peut-on s’adresser pour une réclamation contre une administration de l’État ?",
     "Au Médiateur (ombudsman)",
     "Le Médiateur, rattaché à la Chambre des Députés, traite gratuitement les réclamations contre les administrations.",
     ("À la Cour constitutionnelle", "La Cour ne reçoit pas de réclamations individuelles."),
     ("Au Grand-Duc en audience privée", "Ce n’est pas une voie de réclamation prévue."),
     ("À la Chambre de commerce", "C’est une chambre professionnelle des entreprises.")),
    ("m", "Quelle langue la Constitution désigne-t-elle comme langue du Grand-Duché ?",
     "Le luxembourgeois",
     "La Constitution de 2023 dispose que la langue du Grand-Duché est le luxembourgeois ; la loi règle l’emploi des langues.",
     ("Le français", "Le français est la langue de la législation, pas « la langue du Grand-Duché »."),
     ("L’allemand", "L’allemand est une langue administrative, pas la langue désignée par la Constitution."),
     ("L’anglais", "L’anglais n’a pas de statut officiel.")),
    ("m", "Dans quelle langue les lois luxembourgeoises sont-elles rédigées ?",
     "En français",
     "Le français est la langue de la législation : seul le texte français des lois fait foi, même si le luxembourgeois est la langue nationale.",
     ("En luxembourgeois", "Le luxembourgeois est la langue nationale, mais les lois sont en français."),
     ("En allemand", "L’allemand est langue administrative, pas langue de la législation."),
     ("Dans les trois langues à égalité", "Seul le texte français fait foi.")),
    ("e", "Quelles sont les trois langues administratives et judiciaires du Luxembourg ?",
     "Le luxembourgeois, le français et l’allemand",
     "Selon la loi de 1984, on peut utiliser le luxembourgeois, le français ou l’allemand devant l’administration et la justice.",
     ("Le français, l’allemand et l’anglais", "L’anglais n’est pas une langue administrative officielle."),
     ("Le luxembourgeois, le français et le néerlandais", "Le néerlandais n’a pas de statut au Luxembourg."),
     ("Le luxembourgeois, l’allemand et le portugais", "Le portugais est très parlé mais n’est pas langue administrative.")),
    ("e", "Combien de cantons compte le Grand-Duché de Luxembourg ?",
     "12 cantons",
     "Le pays est divisé en 12 cantons, regroupés en 4 circonscriptions électorales ; il compte par ailleurs 100 communes.",
     ("4 cantons", "4 est le nombre de circonscriptions électorales."),
     ("100 cantons", "100 est le nombre de communes."),
     ("3 cantons", "Les trois anciens districts ont été supprimés en 2015.")),
    ("e", "Où se trouvent le palais grand-ducal et la résidence de la famille grand-ducale ?",
     "Palais à Luxembourg-Ville, résidence au château de Berg",
     "Le palais grand-ducal de la capitale sert aux fonctions officielles ; la famille réside au château de Berg, à Colmar-Berg.",
     ("Palais à Vianden, résidence à Echternach", "Le château de Vianden est un monument, pas la résidence."),
     ("Palais et résidence à Esch-sur-Alzette", "Esch-sur-Alzette n’accueille ni le palais ni la résidence."),
     ("Palais à Bruxelles, résidence à Luxembourg", "Bruxelles est la capitale belge.")),
    ("e", "Quel est le titre de l’hymne national luxembourgeois ?",
     "« Ons Heemecht »",
     "« Ons Heemecht » (Notre patrie) est l’hymne national ; « De Wilhelmus » est l’hymne de la famille grand-ducale, joué en sa présence.",
     ("« De Wilhelmus »", "« De Wilhelmus » est l’hymne grand-ducal, joué pour la famille régnante."),
     ("« La Brabançonne »", "C’est l’hymne belge."),
     ("« Mir wëlle bleiwe wat mir sinn »", "C’est la devise nationale, pas l’hymne.")),
    ("m", "Quelles sont les couleurs du drapeau national luxembourgeois ?",
     "Rouge, blanc et bleu clair, en bandes horizontales",
     "Le drapeau est rouge-blanc-bleu clair, à bandes horizontales ; le lion rouge figure sur le pavillon civil et les armoiries.",
     ("Rouge, blanc et bleu, en bandes verticales", "Ce sont les bandes verticales du drapeau français."),
     ("Rouge, blanc et bleu foncé, comme les Pays-Bas", "Le bleu luxembourgeois est plus clair et le drapeau est plus allongé."),
     ("Noir, jaune et rouge", "Ce sont les couleurs belges.")),
    ("m", "Quelle est la devise nationale du Luxembourg ?",
     "« Mir wëlle bleiwe wat mir sinn »",
     "La devise « Mir wëlle bleiwe wat mir sinn » signifie « Nous voulons rester ce que nous sommes » ; elle exprime l’attachement à l’indépendance.",
     ("« Ons Heemecht »", "C’est le titre de l’hymne national."),
     ("« L’union fait la force »", "C’est la devise de la Belgique."),
     ("« Je maintiendrai »", "C’est la devise des Pays-Bas.")),
    ("e", "À quelle date célèbre-t-on la fête nationale luxembourgeoise ?",
     "Le 23 juin",
     "La fête nationale célèbre officiellement l’anniversaire du Grand-Duc, fixé au 23 juin quelle que soit sa date de naissance réelle.",
     ("Le 14 juillet", "C’est la fête nationale française."),
     ("Le 21 juillet", "C’est la fête nationale belge."),
     ("Le 1er juillet", "Le 1er juillet 2023 est la date d’entrée en vigueur de la nouvelle Constitution.")),
    ("m", "Le service militaire est-il obligatoire au Luxembourg ?",
     "Non, il a été aboli en 1967",
     "L’Armée luxembourgeoise est composée de volontaires depuis l’abolition du service militaire obligatoire en 1967.",
     ("Oui, pour tous les hommes de 18 ans", "Le service obligatoire n’existe plus."),
     ("Oui, pour les nouveaux citoyens naturalisés", "La naturalisation n’entraîne aucun service militaire."),
     ("Il a été rétabli en 2023", "Il n’a pas été rétabli.")),
    ("m", "Par quels actes le gouvernement fait-il exécuter les lois ?",
     "Par des règlements grand-ducaux",
     "Les règlements grand-ducaux précisent l’application des lois ; ils sont soumis à l’avis du Conseil d’État.",
     ("Par des arrêts de la Cour de cassation", "Les arrêts tranchent des litiges, ils n’exécutent pas les lois."),
     ("Par des pétitions publiques", "Les pétitions sont un droit des citoyens."),
     ("Par des règlements communaux", "Ils concernent la commune, pas l’exécution des lois nationales.")),
    ("m", "Où les lois luxembourgeoises sont-elles publiées officiellement ?",
     "Au Journal officiel (legilux.lu)",
     "Une loi n’est obligatoire qu’après sa publication au Journal officiel du Grand-Duché, consultable sur legilux.lu.",
     ("Sur guichet.lu uniquement", "guichet.lu explique les démarches ; la publication officielle se fait au Journal officiel."),
     ("Dans le quotidien de chaque commune", "Il n’y a pas de publication communale des lois."),
     ("Au Journal officiel de l’UE", "Celui-ci publie le droit européen, pas les lois nationales.")),
    ("m", "Quels organes représentent les milieux professionnels et donnent leur avis sur les projets de loi ?",
     "Les chambres professionnelles",
     "Chambre de commerce, Chambre des métiers, Chambre des salariés, Chambre d’agriculture et Chambre des fonctionnaires rendent des avis.",
     ("Les syndicats intercommunaux", "Ils gèrent des services communaux comme l’eau ou les déchets."),
     ("Les justices de paix", "Ce sont des juridictions de premier degré."),
     ("Les commissions consultatives communales", "Elles agissent au niveau local, pas sur les lois nationales.")),
    ("h", "Lequel de ces partis est représenté à la Chambre des Députés depuis les élections de 2023 ?",
     "Les Piraten",
     "Depuis 2023 siègent notamment CSV, DP, LSAP, ADR, déi gréng, Piraten et déi Lénk ; le CSV et le DP forment la majorité gouvernementale.",
     ("Le Parti socialiste français", "C’est un parti français."),
     ("La CDU", "C’est un parti allemand ; son équivalent luxembourgeois est le CSV."),
     ("Le Vlaams Belang", "C’est un parti flamand de Belgique.")),
    ("m", "Quel ministère est chargé du vivre-ensemble interculturel et de l’accueil ?",
     "Le ministère de la Famille, des Solidarités, du Vivre ensemble et de l’Accueil",
     "Ce ministère pilote la politique du vivre-ensemble, le pacte citoyen et l’accueil des demandeurs de protection.",
     ("Le ministère de la Justice", "Il traite les dossiers de nationalité, pas le vivre-ensemble."),
     ("Le ministère des Finances", "Il gère le budget et la fiscalité."),
     ("Le ministère de la Défense", "Il gère l’armée.")),
    ("m", "Quel est le rôle de l’Office national de l’accueil (ONA) ?",
     "Accueillir et héberger les demandeurs de protection internationale",
     "L’ONA organise l’accueil et l’hébergement des demandeurs de protection internationale ; il dépend du ministère chargé du vivre-ensemble et de l’accueil.",
     ("Délivrer les passeports", "Les passeports relèvent du Bureau des passeports."),
     ("Organiser l’examen Vivre ensemble", "L’examen est organisé par le SFA."),
     ("Accueillir les touristes", "Le tourisme relève d’autres organismes.")),
    ("m", "Qu’est-ce que le pacte citoyen du vivre-ensemble interculturel (Biergerpakt) ?",
     "Un engagement volontaire ouvert à tout adulte qui vit ou travaille au Luxembourg",
     "Créé par la loi du 23 août 2023, il a remplacé le contrat d’accueil et d’intégration (CAI) ; son module de 6 heures sur le Luxembourg dispense du module histoire du cours Vivre ensemble.",
     ("Un examen obligatoire pour tous les résidents", "Le pacte est volontaire."),
     ("Un contrat de travail pour les frontaliers", "Ce n’est pas un contrat de travail."),
     ("Un passeport réservé aux Luxembourgeois", "Le pacte est ouvert à tous les adultes, de toutes nationalités.")),
    ("e", "Combien de communes compte le Grand-Duché de Luxembourg ?",
     "100 communes",
     "Après plusieurs fusions, le Luxembourg compte 100 communes ; chacune a son conseil communal élu pour 6 ans.",
     ("12 communes", "12 est le nombre de cantons."),
     ("102 communes", "Ce chiffre date d’avant les dernières fusions de communes."),
     ("60 communes", "60 est le nombre de députés.")),
    ("m", "Quel statut la Constitution donne-t-elle aux communes ?",
     "Des collectivités autonomes dotées de la personnalité juridique",
     "Les communes gèrent leurs intérêts propres par leurs organes élus, sous la tutelle du ministre des Affaires intérieures.",
     ("De simples services du ministère", "Les communes sont autonomes, avec leurs propres organes élus."),
     ("Des États fédérés", "Le Luxembourg n’est pas un État fédéral."),
     ("Des associations privées", "Les communes sont des collectivités publiques.")),
    ("m", "Quels sont les organes d’une commune luxembourgeoise ?",
     "Le conseil communal, le collège des bourgmestre et échevins, et le bourgmestre",
     "Le conseil communal délibère ; le collège échevinal exécute ; le bourgmestre préside et assure l’ordre public.",
     ("Le préfet, le sous-préfet et le maire", "Ce sont des institutions françaises."),
     ("Le Conseil d’État et la Chambre", "Ce sont des institutions nationales."),
     ("Le gouverneur et le parlement régional", "Le Luxembourg n’a pas de régions.")),
    ("e", "Pour quelle durée le conseil communal est-il élu ?",
     "6 ans",
     "Les élections communales ont lieu tous les 6 ans (les dernières en juin 2023) ; les étrangers inscrits peuvent y voter.",
     ("5 ans", "5 ans est la durée du mandat des députés."),
     ("4 ans", "Le mandat communal dure 6 ans."),
     ("10 ans", "Aucun mandat électif ne dure 10 ans.")),
    ("m", "Le nombre de conseillers communaux est-il le même dans toutes les communes ?",
     "Non : de 7 à 19 selon la population, 27 à Luxembourg-Ville",
     "La taille du conseil dépend de la population (de 7 à 19 membres) ; la Ville de Luxembourg compte 27 conseillers.",
     ("Oui, 11 conseillers partout", "Le nombre varie selon la population."),
     ("Oui, 60 conseillers comme la Chambre", "60 est le nombre de députés."),
     ("Non, il est fixé librement par le bourgmestre", "La loi fixe le nombre selon la population.")),
    ("h", "Quel mode de scrutin s’applique aux élections communales ?",
     "Majoritaire sous 3 000 habitants, proportionnel au-delà",
     "Les petites communes votent au scrutin majoritaire ; à partir de 3 000 habitants, la proportionnelle s’applique.",
     ("Proportionnel dans toutes les communes", "Les communes de moins de 3 000 habitants votent au scrutin majoritaire."),
     ("Tirage au sort parmi les volontaires", "Les conseillers sont élus."),
     ("Élection par le Conseil d’État", "Le conseil communal est élu directement par les électeurs.")),
    ("e", "Quel organe vote le budget d’une commune luxembourgeoise ?",
     "Le conseil communal",
     "Le conseil communal vote le budget, les règlements communaux et les taxes communales ; le collège échevinal les exécute.",
     ("Le bourgmestre seul", "Le bourgmestre préside, mais le vote revient au conseil."),
     ("La Chambre des Députés", "Elle vote le budget de l’État, pas celui des communes."),
     ("Le ministre des Finances", "Les communes votent leur propre budget.")),
    ("m", "Quel organe forme l’exécutif communal au Luxembourg ?",
     "Le collège des bourgmestre et échevins",
     "Le collège échevinal (bourgmestre et échevins) exécute les décisions du conseil et gère les affaires courantes de la commune.",
     ("Le conseil communal", "Le conseil délibère ; l’exécution revient au collège."),
     ("La commission du vivre-ensemble", "C’est une commission consultative."),
     ("Le syndicat intercommunal", "Il gère un service commun à plusieurs communes.")),
    ("h", "Comment le bourgmestre est-il nommé au Luxembourg ?",
     "Par le Grand-Duc, parmi les conseillers élus",
     "Le Grand-Duc nomme le bourgmestre parmi les conseillers communaux, sur présentation de la majorité du conseil.",
     ("Il est élu directement par les habitants", "Il n’y a pas d’élection directe du bourgmestre."),
     ("Il est nommé par le Premier ministre", "La nomination revient au Grand-Duc."),
     ("Il est tiré au sort parmi les échevins", "Aucun tirage au sort n’est prévu.")),
    ("m", "Quel est le rôle du bourgmestre dans une commune ?",
     "Présider le conseil et le collège, être officier de l’état civil, veiller à l’ordre public",
     "Le bourgmestre préside les organes communaux, célèbre les mariages comme officier de l’état civil et assure la police locale.",
     ("Juger les petits délits de la commune", "Juger relève des tribunaux, pas du bourgmestre."),
     ("Voter les lois communales à la Chambre", "Les communes n’adoptent pas de lois."),
     ("Commander l’armée locale", "Il n’existe pas d’armée communale.")),
    ("m", "Quelles compétences relèvent typiquement d’une commune luxembourgeoise ?",
     "État civil, écoles fondamentales, eau, déchets, urbanisme",
     "Les communes gèrent l’état civil, l’enseignement fondamental, l’eau, les déchets, l’urbanisme et la voirie.",
     ("Défense nationale et diplomatie", "Ce sont des compétences de l’État."),
     ("Monnaie et politique bancaire", "La monnaie relève de l’UE (euro) et de l’État."),
     ("Justice pénale et prisons", "La justice est une compétence de l’État.")),
    ("h", "Quel ministre exerce la tutelle administrative sur les communes ?",
     "Le ministre des Affaires intérieures",
     "Le ministre des Affaires intérieures contrôle la légalité de certains actes communaux, sans diriger les communes, qui restent autonomes.",
     ("Le ministre de la Justice", "Il s’occupe notamment de la nationalité et des tribunaux."),
     ("Le ministre des Affaires étrangères", "Il s’occupe des relations internationales."),
     ("Le ministre de la Famille", "Il pilote le vivre-ensemble, pas la tutelle des communes.")),
    ("e", "Faut-il se déclarer à la commune en arrivant vivre au Luxembourg ?",
     "Oui, l’inscription au registre de la population est obligatoire",
     "Toute personne qui s’installe doit s’inscrire au registre de la population de sa commune de résidence.",
     ("Non, seulement en cas d’achat immobilier", "L’inscription est obligatoire pour tous les résidents."),
     ("Seulement pour les ressortissants hors UE", "Les citoyens de l’UE doivent aussi s’inscrire."),
     ("Seulement après 5 ans de résidence", "L’inscription se fait dès l’arrivée.")),
    ("m", "Quel organe communal favorise la participation des résidents de toutes nationalités ?",
     "La commission communale du vivre-ensemble interculturel (CCVEI)",
     "Chaque commune a une commission consultative du vivre-ensemble interculturel, ouverte aux Luxembourgeois comme aux étrangers.",
     ("Le Conseil d’État", "C’est un organe national consultatif sur les lois."),
     ("La Cour des comptes", "Elle contrôle les finances de l’État."),
     ("Le collège des bourgmestre et échevins", "C’est l’exécutif communal, pas un organe de participation.")),
    ("m", "Comment les communes coopèrent-elles pour gérer certains services comme l’eau ou les déchets ?",
     "Par des syndicats intercommunaux",
     "Les syndicats intercommunaux permettent à plusieurs communes de gérer ensemble un service public, comme l’eau potable ou le traitement des déchets.",
     ("Par des chambres professionnelles", "Elles représentent des professions, pas des communes."),
     ("Par des traités internationaux", "La coopération entre communes luxembourgeoises relève du droit interne."),
     ("En fusionnant obligatoirement chaque année", "Les fusions sont volontaires et rares.")),
    ("e", "Où demande-t-on sa carte d’identité luxembourgeoise ?",
     "À la commune de résidence",
     "La carte d’identité luxembourgeoise se demande auprès de l’administration communale du lieu de résidence.",
     ("À la Chambre des Députés", "La Chambre n’a pas de mission administrative de ce type."),
     ("Au Conseil d’État", "C’est un organe consultatif."),
     ("À l’ambassade de Belgique", "C’est un document luxembourgeois, délivré au Luxembourg.")),
    ("m", "Quels sont les deux ordres de juridictions au Luxembourg ?",
     "L’ordre judiciaire et l’ordre administratif",
     "Les juridictions judiciaires tranchent les affaires civiles et pénales ; les juridictions administratives, les litiges avec l’administration.",
     ("L’ordre fédéral et l’ordre cantonal", "Le Luxembourg n’est pas un État fédéral."),
     ("L’ordre religieux et l’ordre civil", "Les tribunaux religieux n’ont aucun pouvoir juridictionnel."),
     ("L’ordre communal et l’ordre national", "Les communes n’ont pas de tribunaux propres.")),
    ("h", "Combien de justices de paix existe-t-il au Luxembourg, et où ?",
     "3 : Luxembourg, Esch-sur-Alzette et Diekirch",
     "Les trois justices de paix (Luxembourg, Esch-sur-Alzette, Diekirch) jugent les petits litiges civils et certaines contraventions.",
     ("2 : Luxembourg et Diekirch", "Ce sont les deux tribunaux d’arrondissement."),
     ("12, une par canton", "Il n’y a que trois justices de paix."),
     ("1 seule, à Luxembourg-Ville", "Il en existe trois.")),
    ("h", "Combien de tribunaux d’arrondissement compte le Luxembourg ?",
     "2 : Luxembourg et Diekirch",
     "Les deux tribunaux d’arrondissement (Luxembourg et Diekirch) sont les juridictions de droit commun de premier degré.",
     ("3 : Luxembourg, Esch et Diekirch", "Ce sont les trois justices de paix."),
     ("4, un par circonscription", "Les circonscriptions sont électorales, pas judiciaires."),
     ("1 seul, à Kirchberg", "Il en existe deux.")),
    ("h", "Quelles juridictions forment la Cour supérieure de justice ?",
     "La Cour d’appel et la Cour de cassation",
     "Dans l’ordre judiciaire, la Cour d’appel juge en appel et la Cour de cassation vérifie l’application du droit.",
     ("La Cour constitutionnelle et la Cour des comptes", "Ce sont des institutions distinctes."),
     ("Le tribunal et la Cour administrative", "Ils forment l’ordre administratif."),
     ("La CJUE et la Cour européenne des droits de l’homme", "Ce sont des juridictions européennes.")),
    ("m", "Quelles juridictions tranchent les litiges entre un citoyen et l’administration ?",
     "Le tribunal administratif et la Cour administrative",
     "Le tribunal administratif juge en premier ressort, la Cour administrative en appel ; le Conseil d’État n’a plus ce rôle depuis 1996.",
     ("La justice de paix et le tribunal d’arrondissement", "Ils relèvent de l’ordre judiciaire."),
     ("Le Conseil d’État depuis 1996", "Le Conseil d’État a perdu sa fonction juridictionnelle en 1996."),
     ("La Chambre des Députés", "La Chambre ne juge pas les litiges.")),
    ("m", "Les juges luxembourgeois sont-ils indépendants du gouvernement ?",
     "Oui, les juges du siège sont indépendants et inamovibles",
     "L’indépendance des juges est garantie par la Constitution ; le Conseil national de la justice veille au bon fonctionnement de la justice depuis 2023.",
     ("Non, ils reçoivent des instructions du ministre", "Les juges du siège ne reçoivent aucune instruction."),
     ("Non, ils sont élus chaque année par la Chambre", "Les juges ne sont pas élus par la Chambre."),
     ("Oui, mais le Premier ministre peut les révoquer", "Les juges sont inamovibles.")),
    ("h", "Quel organe veille depuis 2023 au bon fonctionnement de la justice ?",
     "Le Conseil national de la justice",
     "Créé avec la Constitution de 2023, le Conseil national de la justice propose les nominations des magistrats et veille à l’indépendance de la justice.",
     ("La Cour des comptes", "Elle contrôle les finances publiques."),
     ("Le Médiateur", "Le Médiateur traite les réclamations contre l’administration."),
     ("Le Conseil d’État", "Le Conseil d’État donne des avis législatifs.")),
    ("m", "Quel est le rôle du ministère public (parquet) ?",
     "Poursuivre les infractions au nom de la société",
     "Le procureur d’État décide des poursuites pénales et défend l’intérêt général devant les tribunaux ; ce sont les juges du siège qui jugent.",
     ("Défendre les accusés", "La défense est assurée par les avocats."),
     ("Rédiger les lois", "Les lois sont préparées par le gouvernement et votées par la Chambre."),
     ("Juger les affaires civiles", "Le parquet poursuit ; ce sont les juges qui jugent.")),
]

HISTORY = [
    ("e", "Que s’est-il passé en 963, date retenue comme naissance de Luxembourg ?",
     "Le comte Sigefroi acquiert le château de Lucilinburhuc",
     "En 963, le comte Sigefroi acquiert le rocher du Bock et son château, noyau de la future ville de Luxembourg.",
     ("La signature de la première Constitution", "La première Constitution date de 1841."),
     ("L’indépendance reconnue par l’Europe", "L’indépendance est reconnue en 1839."),
     ("La fondation de l’Union européenne", "L’UE date de 1993.")),
    ("m", "Quel rôle la maison de Luxembourg a-t-elle joué au Moyen Âge ?",
     "Elle a donné des empereurs au Saint-Empire, dont Henri VII et Charles IV",
     "Aux XIVe et XVe siècles, la maison de Luxembourg fournit des rois de Bohême et des empereurs du Saint-Empire romain germanique.",
     ("Elle a fondé le royaume de France", "Le royaume de France n’a pas été fondé par les Luxembourg."),
     ("Elle a régné sur l’Espagne", "L’Espagne n’a pas été gouvernée par la maison de Luxembourg."),
     ("Elle a conquis l’Angleterre en 1066", "C’est Guillaume le Conquérant, duc de Normandie.")),
    ("m", "Qui était Jean l’Aveugle, figure de l’histoire luxembourgeoise ?",
     "Comte de Luxembourg et roi de Bohême, mort à Crécy en 1346",
     "Jean l’Aveugle combattit aux côtés du roi de France et mourut à la bataille de Crécy, pendant la guerre de Cent Ans.",
     ("Le premier Grand-Duc de Nassau", "Le premier Grand-Duc de la dynastie Nassau est Adolphe (1890)."),
     ("Le fondateur de la CECA", "La CECA est liée à Robert Schuman et Jean Monnet."),
     ("Un Premier ministre de l’après-guerre", "Jean l’Aveugle vécut au XIVe siècle.")),
    ("m", "Pourquoi surnommait-on Luxembourg le « Gibraltar du Nord » ?",
     "Pour sa forteresse, l’une des plus puissantes d’Europe",
     "La forteresse, sans cesse renforcée par les puissances successives, fut démantelée après le traité de Londres de 1867.",
     ("Pour son port maritime", "Le Luxembourg n’a pas d’accès à la mer."),
     ("Pour son climat méditerranéen", "Le surnom vient de la forteresse, pas du climat."),
     ("Parce qu’il appartenait au Royaume-Uni", "Le Luxembourg n’a jamais été britannique.")),
    ("h", "Que devient le Luxembourg sous la Révolution française, à partir de 1795 ?",
     "Il est annexé par la France comme département des Forêts",
     "Annexé en 1795, le Luxembourg devient le département des Forêts jusqu’à la chute de Napoléon ; le Congrès de Vienne crée ensuite le Grand-Duché (1815).",
     ("Il devient une république indépendante", "Il est annexé, pas indépendant."),
     ("Il est rattaché à la Prusse", "Le rattachement est français, pas prussien."),
     ("Il devient Grand-Duché", "Le Grand-Duché naît en 1815, au Congrès de Vienne.")),
    ("m", "Que décide le Congrès de Vienne en 1815 pour le Luxembourg ?",
     "Il devient Grand-Duché, en union personnelle avec le roi des Pays-Bas",
     "Le Congrès de Vienne crée le Grand-Duché et le confie au roi des Pays-Bas, qui en est aussi Grand-Duc.",
     ("Il devient une province française", "La période française prend fin en 1815."),
     ("Il obtient sa pleine indépendance", "L’indépendance est reconnue en 1839."),
     ("Il est partagé entre la France et la Prusse", "Le Grand-Duché est créé comme entité propre.")),
    ("m", "Que décide le traité de Londres de 1839 ?",
     "L’indépendance du Grand-Duché, avec la perte de sa partie occidentale au profit de la Belgique",
     "Le traité de 1839 reconnaît l’indépendance et fixe les frontières actuelles ; la partie wallonne devient la province belge de Luxembourg.",
     ("La neutralité perpétuelle du pays", "La neutralité est décidée en 1867."),
     ("Le démantèlement de la forteresse", "Le démantèlement est décidé en 1867."),
     ("L’entrée dans le Zollverein", "L’adhésion au Zollverein date de 1842.")),
    ("m", "Quelle union douanière le Luxembourg rejoint-il en 1842 ?",
     "Le Zollverein, union douanière allemande",
     "Le Luxembourg fait partie du Zollverein de 1842 à 1918, ce qui favorise son industrialisation ; il se tourne ensuite vers la Belgique (UEBL, 1921).",
     ("Le Benelux", "Le Benelux est créé en 1944."),
     ("L’Union économique belgo-luxembourgeoise", "L’UEBL date de 1921."),
     ("La Communauté économique européenne", "La CEE date de 1957.")),
    ("h", "Le traité de Londres de 1867 a-t-il donné son indépendance au Luxembourg ?",
     "Non : il impose la neutralité et le démantèlement de la forteresse",
     "Piège fréquent : l’indépendance est reconnue en 1839 ; 1867 garantit la neutralité perpétuelle et fait démanteler la forteresse.",
     ("Oui, c’est la date de l’indépendance", "L’indépendance date de 1839."),
     ("Oui, et il crée le Grand-Duché", "Le Grand-Duché existe depuis 1815."),
     ("Non, il rattache le pays à la France", "Le Luxembourg reste indépendant et neutre.")),
    ("m", "Jusqu’à quand dure l’union personnelle du Luxembourg avec les Pays-Bas ?",
     "Jusqu’en 1890",
     "À la mort de Guillaume III en 1890, la couronne passe à Adolphe de Nassau-Weilburg : le Luxembourg a sa propre dynastie.",
     ("Jusqu’en 1839", "1839 est l’année de la reconnaissance de l’indépendance, pas de la fin de l’union personnelle."),
     ("Jusqu’en 1867", "1867 est l’année du traité de neutralité."),
     ("Jusqu’en 1919", "En 1919, un référendum confirme la monarchie.")),
    ("m", "Quelle industrie a fait la richesse du sud du Luxembourg à partir de la fin du XIXe siècle ?",
     "La sidérurgie, grâce au minerai de fer (la « minette »)",
     "Le minerai de fer du Sud a fait naître une puissante sidérurgie, autour d’Esch-sur-Alzette notamment.",
     ("La pêche en mer du Nord", "Le Luxembourg n’a pas d’accès à la mer."),
     ("L’industrie textile", "Le moteur du Sud était la sidérurgie."),
     ("L’extraction du pétrole", "Il n’y a pas de pétrole au Luxembourg.")),
    ("h", "Qui a été la première Grande-Duchesse régnante du Luxembourg ?",
     "Marie-Adélaïde (1912–1919)",
     "Marie-Adélaïde règne de 1912 à 1919 ; contestée pour son attitude pendant l’occupation allemande, elle abdique en faveur de sa sœur Charlotte.",
     ("Charlotte (1919–1964)", "Charlotte succède à sa sœur Marie-Adélaïde."),
     ("Maria Teresa", "Maria Teresa est l’épouse du Grand-Duc Henri, pas une souveraine."),
     ("Joséphine-Charlotte", "Elle était l’épouse du Grand-Duc Jean.")),
    ("m", "Quelle est la situation du Luxembourg pendant la Première Guerre mondiale ?",
     "Il est occupé par l’Allemagne malgré sa neutralité",
     "De 1914 à 1918, le Luxembourg neutre est occupé par l’armée allemande ; la neutralité garantie en 1867 n’a pas été respectée.",
     ("Il reste libre et non occupé", "Le pays est occupé malgré sa neutralité."),
     ("Il est occupé par la France", "L’occupant est allemand."),
     ("Il combat aux côtés de l’Allemagne", "Le Luxembourg, neutre, ne combat pas.")),
    ("m", "Quelles grandes réformes démocratiques datent de 1919 ?",
     "Le suffrage universel, dont le vote des femmes, et un référendum confirmant la monarchie",
     "En 1919, la Constitution introduit le suffrage universel (hommes et femmes) ; le référendum maintient la dynastie avec Charlotte.",
     ("L’abolition de la monarchie", "Le référendum de 1919 confirme la monarchie."),
     ("L’entrée dans l’Union européenne", "L’UE n’existe qu’à partir de 1993."),
     ("L’adoption de l’euro", "L’euro date de 1999.")),
    ("m", "Quelle union économique le Luxembourg forme-t-il avec la Belgique en 1921 ?",
     "L’Union économique belgo-luxembourgeoise (UEBL)",
     "Après la sortie du Zollverein, le Luxembourg s’associe à la Belgique dans l’UEBL (union monétaire et douanière).",
     ("Le Benelux", "Le Benelux est signé en 1944."),
     ("La CECA", "La CECA date de 1951."),
     ("La zone euro", "La zone euro démarre en 1999.")),
    ("e", "Combien de temps la Grande-Duchesse Charlotte a-t-elle régné ?",
     "De 1919 à 1964",
     "Charlotte règne 45 ans ; symbole de la résistance pendant la guerre, elle abdique en 1964 en faveur de son fils Jean.",
     ("De 1890 à 1912", "Ce sont les règnes d’Adolphe et de Guillaume IV."),
     ("De 1964 à 2000", "C’est le règne de Jean."),
     ("De 2000 à 2025", "C’est le règne d’Henri.")),
    ("m", "Quand l’Allemagne nazie envahit-elle le Luxembourg ?",
     "Le 10 mai 1940",
     "Le 10 mai 1940, la Wehrmacht envahit le Luxembourg, la Belgique et les Pays-Bas ; la Grande-Duchesse et le gouvernement partent en exil.",
     ("Le 1er septembre 1939", "C’est l’invasion de la Pologne."),
     ("Le 6 juin 1944", "C’est le débarquement de Normandie."),
     ("Le 10 septembre 1944", "C’est la date de la libération de la capitale.")),
    ("m", "Où la Grande-Duchesse Charlotte et le gouvernement passent-ils la Seconde Guerre mondiale ?",
     "En exil, principalement à Londres",
     "Depuis Londres, Charlotte s’adresse aux Luxembourgeois par la radio de la BBC et incarne la résistance.",
     ("Au château de Berg, sous l’occupation", "La Grande-Duchesse quitte le pays en 1940."),
     ("À Berlin", "Le gouvernement refuse de collaborer avec l’occupant."),
     ("En Suisse neutre, sans activité politique", "Le gouvernement en exil reste actif, principalement depuis Londres.")),
    ("h", "Contre quoi la grève générale de 1942 est-elle dirigée ?",
     "Contre l’enrôlement de force des jeunes Luxembourgeois dans l’armée allemande",
     "En août 1942, l’annonce de l’incorporation de force provoque une grève générale, durement réprimée par l’occupant.",
     ("Contre la hausse des impôts communaux", "La grève vise une mesure de l’occupant nazi."),
     ("Contre l’adhésion à la CECA", "La CECA n’existe pas encore."),
     ("Contre la fermeture des mines en 1970", "La crise sidérurgique survient dans les années 1970.")),
    ("m", "Quand la capitale du Luxembourg est-elle libérée pendant la Seconde Guerre mondiale ?",
     "Le 10 septembre 1944",
     "Les troupes américaines libèrent la capitale le 10 septembre 1944 ; le Nord souffre encore de la bataille des Ardennes.",
     ("Le 8 mai 1945", "C’est la capitulation allemande, pas la libération de la capitale."),
     ("Le 11 novembre 1918", "C’est l’armistice de la Première Guerre mondiale."),
     ("Le 10 mai 1940", "C’est la date de l’invasion allemande.")),
    ("m", "Quand le Luxembourg abandonne-t-il officiellement sa neutralité ?",
     "En 1948, avant de fonder l’OTAN en 1949",
     "La révision constitutionnelle de 1948 supprime la neutralité ; le Luxembourg est membre fondateur de l’OTAN en 1949.",
     ("En 1867", "C’est la date où la neutralité est imposée."),
     ("En 1990", "La neutralité est abandonnée bien plus tôt."),
     ("Jamais, il est toujours neutre", "Le Luxembourg est membre de l’OTAN depuis 1949.")),
    ("m", "Quel accord douanier est signé à Londres en 1944 par le Luxembourg et ses voisins ?",
     "L’union douanière Benelux",
     "Signé à Londres en 1944 par les gouvernements en exil, le Benelux (Belgique, Pays-Bas, Luxembourg) entre en vigueur en 1948.",
     ("Le traité de Rome", "Le traité de Rome date de 1957."),
     ("Les accords de Schengen", "Schengen date de 1985."),
     ("Le Zollverein", "Le Luxembourg quitte le Zollverein en 1918.")),
    ("h", "Quelle crise a donné naissance au modèle luxembourgeois de la « Tripartite » ?",
     "La crise de la sidérurgie des années 1970",
     "Gouvernement, patronat et syndicats négocient ensemble pour gérer la crise sidérurgique sans conflit social majeur.",
     ("La crise financière de 2008", "La Tripartite existe depuis les années 1970."),
     ("La Seconde Guerre mondiale", "La Tripartite naît en temps de paix, face à la crise de l’acier."),
     ("La pandémie de 2020", "Le modèle est bien plus ancien.")),
    ("m", "Quelles immigrations ont particulièrement marqué l’histoire du Luxembourg ?",
     "L’immigration italienne, puis portugaise",
     "Les Italiens viennent travailler dans la sidérurgie ; les Portugais arrivent en nombre à partir des années 1960.",
     ("L’immigration japonaise, puis chinoise", "Ces immigrations sont restées limitées."),
     ("L’immigration suédoise, puis norvégienne", "Ce ne sont pas des immigrations historiques majeures au Luxembourg."),
     ("Aucune, le pays a peu d’étrangers", "Près de la moitié des résidents sont étrangers.")),
    ("m", "Quels Premiers ministres luxembourgeois ont marqué la construction européenne d’après-guerre ?",
     "Joseph Bech et Pierre Werner",
     "Joseph Bech est un père fondateur de l’Europe ; Pierre Werner a conçu le premier plan d’union monétaire (1970).",
     ("Luc Frieden et Xavier Bettel", "Ce sont des Premiers ministres récents."),
     ("Konrad Adenauer et Charles de Gaulle", "Ce sont des dirigeants allemand et français."),
     ("Winston Churchill et Paul-Henri Spaak", "Ce sont des dirigeants britannique et belge.")),
    ("e", "Quand la nouvelle Constitution luxembourgeoise est-elle entrée en vigueur ?",
     "Le 1er juillet 2023",
     "Refondue en profondeur, la Constitution entrée en vigueur le 1er juillet 2023 remplace le texte de 1868 révisé.",
     ("Le 23 juin 2000", "Le 23 juin est la fête nationale ; 2000 marque l’accession d’Henri."),
     ("Le 1er janvier 1999", "C’est le lancement de l’euro."),
     ("Le 3 octobre 2025", "C’est l’accession au trône du Grand-Duc Guillaume.")),
    ("m", "Quel homme d’État né à Luxembourg est considéré comme un père fondateur de l’Europe ?",
     "Robert Schuman",
     "Né à Luxembourg en 1886, Robert Schuman, ministre français, propose en 1950 la mise en commun du charbon et de l’acier (déclaration Schuman).",
     ("Jean Monnet", "Jean Monnet est un Français né à Cognac."),
     ("Konrad Adenauer", "Adenauer est né à Cologne, en Allemagne."),
     ("Paul-Henri Spaak", "Spaak est belge.")),
    ("m", "Quel rôle Luxembourg a-t-il joué dans la CECA ?",
     "Siège de la Haute Autorité à partir de 1952",
     "La Haute Autorité de la Communauté européenne du charbon et de l’acier, présidée par Jean Monnet, s’installe à Luxembourg en 1952.",
     ("Le pays refuse d’y adhérer", "Le Luxembourg est l’un des six fondateurs."),
     ("Il rejoint la CECA en 1973", "Il est membre dès la fondation."),
     ("Il accueille le Parlement européen en séance plénière", "Les sessions plénières se tiennent à Strasbourg.")),
    ("e", "Quel traité de 1957 le Luxembourg signe-t-il comme pays fondateur de la CEE ?",
     "Le traité de Rome",
     "Le traité de Rome de 1957 crée la Communauté économique européenne entre les Six, dont le Luxembourg.",
     ("Le traité de Maastricht", "Maastricht crée l’Union européenne en 1992/1993."),
     ("Le traité de Lisbonne", "Lisbonne date de 2007."),
     ("Le traité de Londres", "Les traités de Londres de 1839 et 1867 concernent l’indépendance et la neutralité.")),
    ("m", "Que permet l’article 5 de la Constitution luxembourgeoise en matière européenne ?",
     "La participation à l’intégration européenne et le transfert de compétences",
     "La Constitution autorise le Luxembourg à participer à l’Union européenne et à lui transférer l’exercice de certaines compétences.",
     ("La sortie automatique de l’UE en cas de crise", "Aucune sortie automatique n’est prévue."),
     ("L’interdiction de tout traité européen", "La Constitution favorise au contraire l’intégration."),
     ("La soumission du Grand-Duc au Parlement européen", "Le Parlement européen n’a pas d’autorité sur le Grand-Duc.")),
    ("e", "Quand et où les accords de Schengen ont-ils été signés ?",
     "En 1985, à Schengen, au Luxembourg",
     "Les accords sont signés en 1985 sur un bateau sur la Moselle, près du village luxembourgeois de Schengen.",
     ("En 1992, à Maastricht", "Maastricht est le traité sur l’Union européenne."),
     ("En 1957, à Rome", "Rome est le traité de la CEE."),
     ("En 2007, à Lisbonne", "Lisbonne est un traité de réforme de l’UE.")),
    ("m", "Depuis quand le Luxembourg utilise-t-il l’euro ?",
     "Depuis 1999 ; pièces et billets depuis 2002",
     "L’euro remplace le franc luxembourgeois comme monnaie en 1999 ; les pièces et billets circulent depuis 2002.",
     ("Depuis 1957", "1957 est l’année du traité de Rome."),
     ("Depuis 1985", "1985 est l’année des accords de Schengen."),
     ("Depuis 2010", "Le Luxembourg fait partie de la zone euro dès son lancement.")),
    ("m", "Quels Luxembourgeois ont présidé la Commission européenne ?",
     "Gaston Thorn, Jacques Santer et Jean-Claude Juncker",
     "Trois Luxembourgeois ont présidé la Commission : Thorn (1981–1985), Santer (1995–1999) et Juncker (2014–2019).",
     ("Robert Schuman et Joseph Bech", "Ils sont pères fondateurs, mais n’ont pas présidé la Commission."),
     ("Luc Frieden et Xavier Bettel", "Ce sont des Premiers ministres luxembourgeois."),
     ("Pierre Werner et Jean Monnet", "Werner a été Premier ministre ; Monnet, français, a présidé la Haute Autorité.")),
    ("m", "Quelles institutions européennes ont leur siège à Luxembourg ?",
     "La Cour de justice de l’UE, la BEI, la Cour des comptes européenne et le Secrétariat général du Parlement européen",
     "Luxembourg est l’une des trois capitales européennes, avec Bruxelles et Strasbourg ; la BCE, elle, siège à Francfort.",
     ("La Banque centrale européenne", "La BCE siège à Francfort."),
     ("La Commission européenne et le Conseil européen", "Ils siègent à Bruxelles."),
     ("Le Parlement européen en séance plénière", "Les sessions plénières se tiennent à Strasbourg.")),
    ("m", "Quel est le rôle de la Cour de justice de l’Union européenne, installée à Luxembourg ?",
     "Veiller à l’interprétation et à l’application uniformes du droit de l’UE",
     "La CJUE garantit que le droit européen est interprété et appliqué de la même façon dans tous les États membres.",
     ("Juger les crimes contre l’humanité", "C’est le rôle de la Cour pénale internationale."),
     ("Protéger les droits de l’homme du Conseil de l’Europe", "C’est la Cour européenne des droits de l’homme, à Strasbourg."),
     ("Fixer les taux d’intérêt de l’euro", "C’est la BCE, à Francfort.")),
    ("m", "Combien de députés européens le Luxembourg élit-il ?",
     "6",
     "Le Luxembourg élit 6 députés au Parlement européen, le minimum prévu par les traités ; Luxembourgeois et citoyens de l’UE inscrits votent.",
     ("60", "60 est le nombre de députés à la Chambre des Députés."),
     ("12", "12 est le nombre de cantons."),
     ("21", "21 est le nombre de membres du Conseil d’État.")),
    ("h", "Quels mois le Conseil de l’Union européenne se réunit-il à Luxembourg ?",
     "En avril, juin et octobre",
     "Le Conseil de l’UE siège à Bruxelles, mais ses réunions d’avril, juin et octobre se tiennent à Luxembourg.",
     ("Jamais, il se réunit uniquement à Bruxelles", "Trois sessions par an ont lieu à Luxembourg."),
     ("Chaque mois de l’année", "Seules les sessions d’avril, juin et octobre ont lieu à Luxembourg."),
     ("Uniquement en décembre", "Les mois concernés sont avril, juin et octobre.")),
    ("m", "Qu’est-ce que la Grande Région dont fait partie le Luxembourg ?",
     "Une coopération transfrontalière avec la Lorraine, la Sarre, la Rhénanie-Palatinat et la Wallonie",
     "La Grande Région organise la coopération dans un espace où vivent de nombreux travailleurs frontaliers.",
     ("Une nouvelle province de l’UE", "Ce n’est pas une entité politique de l’UE."),
     ("Le nom du Benelux élargi", "Le Benelux réunit la Belgique, les Pays-Bas et le Luxembourg."),
     ("La région du nord du Luxembourg", "Le nord du pays s’appelle l’Oesling.")),
    ("e", "Depuis quand le Luxembourg fait-il partie de l’Union européenne ?",
     "Depuis sa création en 1993, après avoir fondé les Communautés européennes",
     "Membre fondateur de la CECA (1951) et de la CEE (1957), le Luxembourg est membre de l’UE dès sa création par le traité de Maastricht.",
     ("Depuis l’élargissement de 2004", "2004 concerne notamment les pays d’Europe centrale."),
     ("Depuis 1973, avec le Royaume-Uni", "Le Luxembourg est fondateur, bien avant 1973."),
     ("Il n’est pas membre de l’UE", "Le Luxembourg est membre fondateur.")),
]

MODULES = [
    ("droits-fondamentaux", RIGHTS),
    ("institutions", INSTITUTIONS),
    ("histoire-europe", HISTORY),
]


def build() -> list[dict]:
    out: list[dict] = []
    seen: set[str] = set()
    pos = 0
    letters = "abcd"
    for topic, items in MODULES:
        for n, (diff, prompt, correct, expl, *wrong) in enumerate(items, 1):
            assert prompt not in seen, prompt
            seen.add(prompt)
            assert len(prompt) >= 40, prompt
            assert len(wrong) == 3
            texts = [w[0] for w in wrong]
            assert len({correct, *texts}) == 4, prompt
            # spread keys evenly: rotate correct slot, shuffle distractors by prompt hash
            slot = pos % 4
            pos += 1
            h = int(hashlib.md5(prompt.encode()).hexdigest(), 16)
            order = sorted(range(3), key=lambda i: (h >> (i * 8)) & 0xFF)
            wrong_sorted = [wrong[i] for i in order]
            options, dist = [], {}
            wi = 0
            for i, letter in enumerate(letters):
                if i == slot:
                    options.append({"id": letter, "text": correct})
                else:
                    text, why = wrong_sorted[wi]
                    wi += 1
                    options.append({"id": letter, "text": text})
                    dist[letter] = why
            out.append({
                "id": f"{SLUG}-{topic}-{n:03d}",
                "examSlug": SLUG,
                "topicId": topic,
                "prompt": prompt,
                "options": options,
                "correctOptionId": letters[slot],
                "explanation": expl,
                "distractorExplanations": dist,
                "difficulty": DIFF[diff],
                "sourceNote": SOURCE_NOTE,
            })
    return out


def main() -> None:
    bank = build()
    OUT.write_text(json.dumps(bank, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    counts = {t: sum(1 for q in bank if q["topicId"] == t) for t, _ in MODULES}
    keys = {k: sum(1 for q in bank if q["correctOptionId"] == k) for k in "abcd"}
    print(f"{len(bank)} questions → {OUT}")
    print("per module:", counts)
    print("keys:", keys)


if __name__ == "__main__":
    main()
