import type { MockExamTaxonomy } from "./types";

export const wave4TaxonomyEntries: Record<string, MockExamTaxonomy> = {
  "al-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Alabama real estate", "AL RE", "Alabama real estate exam"] },
  "ak-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Alaska real estate", "AK RE", "Alaska real estate exam"] },
  "ar-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Arkansas real estate", "AR RE", "Arkansas real estate exam"] },
  "ct-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Connecticut real estate", "CT RE", "Connecticut real estate exam"] },
  "de-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Delaware real estate", "DE RE", "Delaware real estate exam"] },
  "hi-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Hawaii real estate", "HI RE", "Hawaii real estate exam"] },
  "id-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Idaho real estate", "ID RE", "Idaho real estate exam"] },
  "in-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Indiana real estate", "IN RE", "Indiana real estate exam"] },
  "ia-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Iowa real estate", "IA RE", "Iowa real estate exam"] },
  "ks-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Kansas real estate", "KS RE", "Kansas real estate exam"] },
  "ky-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Kentucky real estate", "KY RE", "Kentucky real estate exam"] },
  "la-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Louisiana real estate", "LA RE", "Louisiana real estate exam"] },
  "me-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Maine real estate", "ME RE", "Maine real estate exam"] },
  "md-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Maryland real estate", "MD RE", "Maryland real estate exam"] },
  "mn-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Minnesota real estate", "MN RE", "Minnesota real estate exam"] },
  "ms-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Mississippi real estate", "MS RE", "Mississippi real estate exam"] },
  "mo-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Missouri real estate", "MO RE", "Missouri real estate exam"] },
  "mt-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Montana real estate", "MT RE", "Montana real estate exam"] },
  "ne-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Nebraska real estate", "NE RE", "Nebraska real estate exam"] },
  "nv-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Nevada real estate", "NV RE", "Nevada real estate exam"] },
  "nh-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["New Hampshire real estate", "NH RE", "New Hampshire real estate exam"] },
  "nm-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["New Mexico real estate", "NM RE", "New Mexico real estate exam"] },
  "nd-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["North Dakota real estate", "ND RE", "North Dakota real estate exam"] },
  "ok-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Oklahoma real estate", "OK RE", "Oklahoma real estate exam"] },
  "or-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Oregon real estate", "OR RE", "Oregon real estate exam"] },
  "ri-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Rhode Island real estate", "RI RE", "Rhode Island real estate exam"] },
  "sc-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["South Carolina real estate", "SC RE", "South Carolina real estate exam"] },
  "sd-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["South Dakota real estate", "SD RE", "South Dakota real estate exam"] },
  "tn-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Tennessee real estate", "TN RE", "Tennessee real estate exam"] },
  "ut-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Utah real estate", "UT RE", "Utah real estate exam"] },
  "vt-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Vermont real estate", "VT RE", "Vermont real estate exam"] },
  "wv-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["West Virginia real estate", "WV RE", "West Virginia real estate exam"] },
  "wi-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Wisconsin real estate", "WI RE", "Wisconsin real estate exam"] },
  "wy-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Wyoming real estate", "WY RE", "Wyoming real estate exam"] },
  "series-79-readiness-check": { verticalId: "licensing", familyId: "finra", searchAliases: ["Series 79", "Investment Banking Representative"] },
  "cfp-certification-readiness-check": { verticalId: "finance", familyId: "cfp", searchAliases: ["CFP exam", "Certified Financial Planner"] },
  "life-health-insurance-readiness-check": { verticalId: "licensing", familyId: "insurance", searchAliases: ["life and health insurance exam", "life health producer"] },
  "praxis-elementary-education-readiness-check": { verticalId: "education", familyId: "praxis", searchAliases: ["Praxis 5001", "elementary education praxis"] },
  "praxis-special-education-readiness-check": { verticalId: "education", familyId: "praxis", searchAliases: ["Praxis Special Education", "sped praxis"] },
  "water-treatment-operator-1-readiness-check": { verticalId: "trades", familyId: "water", searchAliases: ["water treatment operator exam", "drinking water operator"] },
  "electrical-journeyman-readiness-check": { verticalId: "trades", familyId: "electrical", searchAliases: ["journeyman electrician exam", "electrician license test"] },
  "plumbing-journeyman-readiness-check": { verticalId: "trades", familyId: "plumbing", searchAliases: ["journeyman plumber exam", "plumbing license test"] },
  "nremt-emr-readiness-check": { verticalId: "ems", familyId: "nremt", searchAliases: ["EMR exam", "NREMT EMR", "emergency medical responder"] },
  "pharmacy-technician-excpt-readiness-check": { verticalId: "allied-health", familyId: "nha", searchAliases: ["ExCPT", "NHA pharmacy technician"] },
  "armed-security-officer-readiness-check": { verticalId: "licensing", familyId: "security", searchAliases: ["armed security guard exam", "armed guard card"] },
  "medical-billing-specialist-readiness-check": { verticalId: "health-admin", familyId: "coding", searchAliases: ["medical billing specialist exam", "CBCS"] },
  "veterinary-technician-vtne-readiness-check": { verticalId: "veterinary", familyId: "vtne", searchAliases: ["VTNE", "veterinary technician exam"] },
  "shrm-scp-readiness-check": { verticalId: "licensing", familyId: "hr", searchAliases: ["SHRM-SCP", "SHRM senior certified professional"] },
  "series-99-readiness-check": { verticalId: "licensing", familyId: "finra", searchAliases: ["Series 99", "Operations Professional"] },
  "medicare-counseling-readiness-check": { verticalId: "health-admin", familyId: "coding", searchAliases: ["SHIP counselor", "Medicare counseling exam", "SHIP certification"] },
};

