import type { MockExamConfig } from "./types";
import {
  fourNicheTopics,
  nicheWaitlistConfig,
  NICHE_SESSION_QUESTIONS,
} from "./niche-readiness";

/** Wave 4 — 50 bankless waitlist niches (indexed SEO + notify CTA). */
export const wave4MockExamConfigs: MockExamConfig[] = [
  nicheWaitlistConfig({
    slug: "al-real-estate-readiness-check",
    title: "Alabama Real Estate Readiness Check",
    shortTitle: "Alabama Real Estate",
    linkedDeckSlug: "al-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "al-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Alabama Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Alabama Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Alabama Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Alabama real estate", "AL RE", "Alabama real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "ak-real-estate-readiness-check",
    title: "Alaska Real Estate Readiness Check",
    shortTitle: "Alaska Real Estate",
    linkedDeckSlug: "ak-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "ak-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Alaska Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Alaska Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Alaska Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Alaska real estate", "AK RE", "Alaska real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "ar-real-estate-readiness-check",
    title: "Arkansas Real Estate Readiness Check",
    shortTitle: "Arkansas Real Estate",
    linkedDeckSlug: "ar-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "ar-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Arkansas Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Arkansas Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Arkansas Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Arkansas real estate", "AR RE", "Arkansas real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "ct-real-estate-readiness-check",
    title: "Connecticut Real Estate Readiness Check",
    shortTitle: "Connecticut Real Estate",
    linkedDeckSlug: "ct-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "ct-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Connecticut Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Connecticut Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Connecticut Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Connecticut real estate", "CT RE", "Connecticut real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "de-real-estate-readiness-check",
    title: "Delaware Real Estate Readiness Check",
    shortTitle: "Delaware Real Estate",
    linkedDeckSlug: "de-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "de-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Delaware Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Delaware Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Delaware Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Delaware real estate", "DE RE", "Delaware real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "hi-real-estate-readiness-check",
    title: "Hawaii Real Estate Readiness Check",
    shortTitle: "Hawaii Real Estate",
    linkedDeckSlug: "hi-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "hi-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Hawaii Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Hawaii Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Hawaii Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Hawaii real estate", "HI RE", "Hawaii real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "id-real-estate-readiness-check",
    title: "Idaho Real Estate Readiness Check",
    shortTitle: "Idaho Real Estate",
    linkedDeckSlug: "id-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "id-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Idaho Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Idaho Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Idaho Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Idaho real estate", "ID RE", "Idaho real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "in-real-estate-readiness-check",
    title: "Indiana Real Estate Readiness Check",
    shortTitle: "Indiana Real Estate",
    linkedDeckSlug: "in-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "in-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Indiana Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Indiana Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Indiana Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Indiana real estate", "IN RE", "Indiana real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "ia-real-estate-readiness-check",
    title: "Iowa Real Estate Readiness Check",
    shortTitle: "Iowa Real Estate",
    linkedDeckSlug: "ia-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "ia-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Iowa Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Iowa Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Iowa Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Iowa real estate", "IA RE", "Iowa real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "ks-real-estate-readiness-check",
    title: "Kansas Real Estate Readiness Check",
    shortTitle: "Kansas Real Estate",
    linkedDeckSlug: "ks-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "ks-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Kansas Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Kansas Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Kansas Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Kansas real estate", "KS RE", "Kansas real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "ky-real-estate-readiness-check",
    title: "Kentucky Real Estate Readiness Check",
    shortTitle: "Kentucky Real Estate",
    linkedDeckSlug: "ky-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "ky-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Kentucky Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Kentucky Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Kentucky Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Kentucky real estate", "KY RE", "Kentucky real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "la-real-estate-readiness-check",
    title: "Louisiana Real Estate Readiness Check",
    shortTitle: "Louisiana Real Estate",
    linkedDeckSlug: "la-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "la-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Louisiana Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Louisiana Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Louisiana Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Louisiana real estate", "LA RE", "Louisiana real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "me-real-estate-readiness-check",
    title: "Maine Real Estate Readiness Check",
    shortTitle: "Maine Real Estate",
    linkedDeckSlug: "me-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "me-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Maine Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Maine Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Maine Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Maine real estate", "ME RE", "Maine real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "md-real-estate-readiness-check",
    title: "Maryland Real Estate Readiness Check",
    shortTitle: "Maryland Real Estate",
    linkedDeckSlug: "md-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "md-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Maryland Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Maryland Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Maryland Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Maryland real estate", "MD RE", "Maryland real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "mn-real-estate-readiness-check",
    title: "Minnesota Real Estate Readiness Check",
    shortTitle: "Minnesota Real Estate",
    linkedDeckSlug: "mn-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "mn-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Minnesota Commerce Department themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Minnesota Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Minnesota Commerce Department",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Minnesota real estate", "MN RE", "Minnesota real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "ms-real-estate-readiness-check",
    title: "Mississippi Real Estate Readiness Check",
    shortTitle: "Mississippi Real Estate",
    linkedDeckSlug: "ms-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "ms-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Mississippi Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Mississippi Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Mississippi Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Mississippi real estate", "MS RE", "Mississippi real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "mo-real-estate-readiness-check",
    title: "Missouri Real Estate Readiness Check",
    shortTitle: "Missouri Real Estate",
    linkedDeckSlug: "mo-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "mo-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Missouri Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Missouri Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Missouri Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Missouri real estate", "MO RE", "Missouri real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "mt-real-estate-readiness-check",
    title: "Montana Real Estate Readiness Check",
    shortTitle: "Montana Real Estate",
    linkedDeckSlug: "mt-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "mt-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Montana Board of Realty Regulation themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Montana Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Montana Board of Realty Regulation",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Montana real estate", "MT RE", "Montana real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "ne-real-estate-readiness-check",
    title: "Nebraska Real Estate Readiness Check",
    shortTitle: "Nebraska Real Estate",
    linkedDeckSlug: "ne-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "ne-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Nebraska Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Nebraska Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Nebraska Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Nebraska real estate", "NE RE", "Nebraska real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "nv-real-estate-readiness-check",
    title: "Nevada Real Estate Readiness Check",
    shortTitle: "Nevada Real Estate",
    linkedDeckSlug: "nv-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "nv-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Nevada Real Estate Division themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Nevada Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Nevada Real Estate Division",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Nevada real estate", "NV RE", "Nevada real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "nh-real-estate-readiness-check",
    title: "New Hampshire Real Estate Readiness Check",
    shortTitle: "New Hampshire Real Estate",
    linkedDeckSlug: "nh-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "nh-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to New Hampshire Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free New Hampshire Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "New Hampshire Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["New Hampshire real estate", "NH RE", "New Hampshire real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "nm-real-estate-readiness-check",
    title: "New Mexico Real Estate Readiness Check",
    shortTitle: "New Mexico Real Estate",
    linkedDeckSlug: "nm-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "nm-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to New Mexico Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free New Mexico Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "New Mexico Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["New Mexico real estate", "NM RE", "New Mexico real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "nd-real-estate-readiness-check",
    title: "North Dakota Real Estate Readiness Check",
    shortTitle: "North Dakota Real Estate",
    linkedDeckSlug: "nd-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "nd-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to North Dakota Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free North Dakota Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "North Dakota Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["North Dakota real estate", "ND RE", "North Dakota real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "ok-real-estate-readiness-check",
    title: "Oklahoma Real Estate Readiness Check",
    shortTitle: "Oklahoma Real Estate",
    linkedDeckSlug: "ok-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "ok-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Oklahoma Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Oklahoma Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Oklahoma Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Oklahoma real estate", "OK RE", "Oklahoma real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "or-real-estate-readiness-check",
    title: "Oregon Real Estate Readiness Check",
    shortTitle: "Oregon Real Estate",
    linkedDeckSlug: "or-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "or-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Oregon Real Estate Agency themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Oregon Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Oregon Real Estate Agency",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Oregon real estate", "OR RE", "Oregon real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "ri-real-estate-readiness-check",
    title: "Rhode Island Real Estate Readiness Check",
    shortTitle: "Rhode Island Real Estate",
    linkedDeckSlug: "ri-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "ri-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Rhode Island Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Rhode Island Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Rhode Island Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Rhode Island real estate", "RI RE", "Rhode Island real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "sc-real-estate-readiness-check",
    title: "South Carolina Real Estate Readiness Check",
    shortTitle: "South Carolina Real Estate",
    linkedDeckSlug: "sc-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "sc-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to South Carolina Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free South Carolina Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "South Carolina Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["South Carolina real estate", "SC RE", "South Carolina real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "sd-real-estate-readiness-check",
    title: "South Dakota Real Estate Readiness Check",
    shortTitle: "South Dakota Real Estate",
    linkedDeckSlug: "sd-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "sd-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to South Dakota Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free South Dakota Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "South Dakota Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["South Dakota real estate", "SD RE", "South Dakota real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "tn-real-estate-readiness-check",
    title: "Tennessee Real Estate Readiness Check",
    shortTitle: "Tennessee Real Estate",
    linkedDeckSlug: "tn-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "tn-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Tennessee Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Tennessee Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Tennessee Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Tennessee real estate", "TN RE", "Tennessee real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "ut-real-estate-readiness-check",
    title: "Utah Real Estate Readiness Check",
    shortTitle: "Utah Real Estate",
    linkedDeckSlug: "ut-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "ut-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Utah Division of Real Estate themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Utah Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Utah Division of Real Estate",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Utah real estate", "UT RE", "Utah real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "vt-real-estate-readiness-check",
    title: "Vermont Real Estate Readiness Check",
    shortTitle: "Vermont Real Estate",
    linkedDeckSlug: "vt-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "vt-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Vermont Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Vermont Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Vermont Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Vermont real estate", "VT RE", "Vermont real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "wv-real-estate-readiness-check",
    title: "West Virginia Real Estate Readiness Check",
    shortTitle: "West Virginia Real Estate",
    linkedDeckSlug: "wv-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "wv-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to West Virginia Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free West Virginia Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "West Virginia Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["West Virginia real estate", "WV RE", "West Virginia real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "wi-real-estate-readiness-check",
    title: "Wisconsin Real Estate Readiness Check",
    shortTitle: "Wisconsin Real Estate",
    linkedDeckSlug: "wi-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "wi-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Wisconsin Real Estate Examining Board themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Wisconsin Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Wisconsin Real Estate Examining Board",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Wisconsin real estate", "WI RE", "Wisconsin real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "wy-real-estate-readiness-check",
    title: "Wyoming Real Estate Readiness Check",
    shortTitle: "Wyoming Real Estate",
    linkedDeckSlug: "wy-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "wy-license-law", label: "State license law" }
    ]),
    officialSourceNote: "Mapped to Wyoming Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Wyoming Real Estate practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "Wyoming Real Estate Commission",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Wyoming real estate", "WY RE", "Wyoming real estate exam"],
  }),
  nicheWaitlistConfig({
    slug: "series-79-readiness-check",
    title: "Series 79 Readiness Check",
    shortTitle: "Series 79",
    linkedDeckSlug: "series-79-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "valuation", label: "Valuation & analysis" },
      { id: "mna", label: "M&A process" },
      { id: "products", label: "IB products & markets" },
      { id: "regulations", label: "Regulations & ethics" }
    ]),
    officialSourceNote: "Mapped to FINRA themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Series 79 practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "FINRA",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Series 79", "Investment Banking Representative"],
  }),
  nicheWaitlistConfig({
    slug: "cfp-certification-readiness-check",
    title: "CFP Certification Readiness Check",
    shortTitle: "CFP Certification",
    linkedDeckSlug: "cfp-certification-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "planning", label: "Financial planning process" },
      { id: "investments", label: "Investment planning" },
      { id: "tax-estate", label: "Tax & estate" },
      { id: "retirement-risk", label: "Retirement & risk" }
    ]),
    officialSourceNote: "Mapped to CFP Board themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free CFP Certification practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "CFP Board",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["CFP exam", "Certified Financial Planner"],
  }),
  nicheWaitlistConfig({
    slug: "life-health-insurance-readiness-check",
    title: "Life & Health Insurance Readiness Check",
    shortTitle: "Life & Health Insurance",
    linkedDeckSlug: "life-health-insurance-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "life", label: "Life insurance products" },
      { id: "health", label: "Health & accident" },
      { id: "law", label: "Insurance law & ethics" },
      { id: "underwriting", label: "Underwriting & claims" }
    ]),
    officialSourceNote: "Mapped to State insurance departments themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Life & Health Insurance practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "State insurance departments",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["life and health insurance exam", "life health producer"],
  }),
  nicheWaitlistConfig({
    slug: "praxis-elementary-education-readiness-check",
    title: "Praxis Elementary Education Readiness Check",
    shortTitle: "Praxis Elementary Education",
    linkedDeckSlug: "praxis-elementary-education-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "reading", label: "Reading & language arts" },
      { id: "math", label: "Mathematics" },
      { id: "social", label: "Social studies" },
      { id: "science", label: "Science" }
    ]),
    officialSourceNote: "Mapped to ETS themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Praxis Elementary Education practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "ETS",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Praxis 5001", "elementary education praxis"],
  }),
  nicheWaitlistConfig({
    slug: "praxis-special-education-readiness-check",
    title: "Praxis Special Education Readiness Check",
    shortTitle: "Praxis Special Education",
    linkedDeckSlug: "praxis-special-education-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "development", label: "Development & learning" },
      { id: "planning", label: "Planning & instruction" },
      { id: "assessment", label: "Assessment" },
      { id: "foundations", label: "Foundations & professional practice" }
    ]),
    officialSourceNote: "Mapped to ETS themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Praxis Special Education practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "ETS",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Praxis Special Education", "sped praxis"],
  }),
  nicheWaitlistConfig({
    slug: "water-treatment-operator-1-readiness-check",
    title: "Water Treatment Operator 1 Readiness Check",
    shortTitle: "Water Treatment Operator 1",
    linkedDeckSlug: "water-treatment-operator-1-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "treatment", label: "Treatment processes" },
      { id: "labs", label: "Labs & monitoring" },
      { id: "safety", label: "Safety & equipment" },
      { id: "regs", label: "Regs & reporting" }
    ]),
    officialSourceNote: "Mapped to State drinking water operator boards themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Water Treatment Operator 1 practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "State drinking water operator boards",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["water treatment operator exam", "drinking water operator"],
  }),
  nicheWaitlistConfig({
    slug: "electrical-journeyman-readiness-check",
    title: "Electrical Journeyman Readiness Check",
    shortTitle: "Electrical Journeyman",
    linkedDeckSlug: "electrical-journeyman-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "nec", label: "NEC theory" },
      { id: "wiring", label: "Wiring methods" },
      { id: "services", label: "Services & feeders" },
      { id: "safety", label: "Safety & motors" }
    ]),
    officialSourceNote: "Mapped to State electrical boards themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Electrical Journeyman practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "State electrical boards",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["journeyman electrician exam", "electrician license test"],
  }),
  nicheWaitlistConfig({
    slug: "plumbing-journeyman-readiness-check",
    title: "Plumbing Journeyman Readiness Check",
    shortTitle: "Plumbing Journeyman",
    linkedDeckSlug: "plumbing-journeyman-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "dwv", label: "DWV systems" },
      { id: "water", label: "Water supply" },
      { id: "fixtures", label: "Fixtures & appliances" },
      { id: "code", label: "Code & safety" }
    ]),
    officialSourceNote: "Mapped to State plumbing boards themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Plumbing Journeyman practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "State plumbing boards",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["journeyman plumber exam", "plumbing license test"],
  }),
  nicheWaitlistConfig({
    slug: "nremt-emr-readiness-check",
    title: "NREMT EMR Readiness Check",
    shortTitle: "NREMT EMR",
    linkedDeckSlug: "nremt-emr-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "airway", label: "Airway & oxygenation" },
      { id: "trauma", label: "Trauma & bleeding" },
      { id: "medical", label: "Medical emergencies" },
      { id: "ops", label: "EMS operations" }
    ]),
    officialSourceNote: "Mapped to NREMT themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free NREMT EMR practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "NREMT",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["EMR exam", "NREMT EMR", "emergency medical responder"],
  }),
  nicheWaitlistConfig({
    slug: "pharmacy-technician-excpt-readiness-check",
    title: "ExCPT Pharmacy Technician Readiness Check",
    shortTitle: "ExCPT Pharmacy Technician",
    linkedDeckSlug: "pharmacy-technician-excpt-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "orders", label: "Orders & dispensing" },
      { id: "inventory", label: "Inventory & storage" },
      { id: "safety", label: "Safety & quality" },
      { id: "law", label: "Law & ethics" }
    ]),
    officialSourceNote: "Mapped to NHA themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free ExCPT Pharmacy Technician practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "NHA",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["ExCPT", "NHA pharmacy technician"],
  }),
  nicheWaitlistConfig({
    slug: "armed-security-officer-readiness-check",
    title: "Armed Security Officer Readiness Check",
    shortTitle: "Armed Security Officer",
    linkedDeckSlug: "armed-security-officer-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "law", label: "Use of force & law" },
      { id: "weapons", label: "Weapons safety" },
      { id: "patrol", label: "Patrol & emergencies" },
      { id: "ethics", label: "Ethics & professionalism" }
    ]),
    officialSourceNote: "Mapped to State security licensing boards themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Armed Security Officer practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "State security licensing boards",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["armed security guard exam", "armed guard card"],
  }),
  nicheWaitlistConfig({
    slug: "medical-billing-specialist-readiness-check",
    title: "Medical Billing Specialist Readiness Check",
    shortTitle: "Medical Billing Specialist",
    linkedDeckSlug: "medical-billing-specialist-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "claims", label: "Claims process" },
      { id: "coding-awareness", label: "Coding awareness" },
      { id: "payers", label: "Payer rules" },
      { id: "compliance", label: "Compliance" }
    ]),
    officialSourceNote: "Mapped to NHA / billing cert themes themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Medical Billing Specialist practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "NHA / billing cert themes",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["medical billing specialist exam", "CBCS"],
  }),
  nicheWaitlistConfig({
    slug: "veterinary-technician-vtne-readiness-check",
    title: "VTNE Readiness Check",
    shortTitle: "VTNE",
    linkedDeckSlug: "veterinary-technician-vtne-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "pharm", label: "Pharmacy & pharmacology" },
      { id: "nursing", label: "Nursing care" },
      { id: "diagnostics", label: "Diagnostics" },
      { id: "surgery-dentistry", label: "Surgery & dentistry" }
    ]),
    officialSourceNote: "Mapped to AAVSB themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free VTNE practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "AAVSB",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["VTNE", "veterinary technician exam"],
  }),
  nicheWaitlistConfig({
    slug: "shrm-scp-readiness-check",
    title: "SHRM-SCP Readiness Check",
    shortTitle: "SHRM-SCP",
    linkedDeckSlug: "shrm-scp-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "people", label: "People" },
      { id: "organization", label: "Organization" },
      { id: "workplace", label: "Workplace" },
      { id: "leadership", label: "Leadership & navigation" }
    ]),
    officialSourceNote: "Mapped to SHRM themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free SHRM-SCP practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "SHRM",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["SHRM-SCP", "SHRM senior certified professional"],
  }),
  nicheWaitlistConfig({
    slug: "series-99-readiness-check",
    title: "Series 99 Readiness Check",
    shortTitle: "Series 99",
    linkedDeckSlug: "series-99-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "ops", label: "Operations" },
      { id: "regs", label: "Regulations" },
      { id: "books", label: "Books & records" },
      { id: "risk", label: "Risk & control" }
    ]),
    officialSourceNote: "Mapped to FINRA themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free Series 99 practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "FINRA",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["Series 99", "Operations Professional"],
  }),
  nicheWaitlistConfig({
    slug: "medicare-counseling-readiness-check",
    title: "SHIP Medicare Counseling Readiness Check",
    shortTitle: "SHIP Medicare Counseling",
    linkedDeckSlug: "medicare-counseling-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "medicare", label: "Medicare basics" },
      { id: "rights", label: "Rights & appeals" },
      { id: "fraud", label: "Fraud & abuse" },
      { id: "counseling", label: "Counseling skills" }
    ]),
    officialSourceNote: "Mapped to State Health Insurance Assistance Programs themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free SHIP Medicare Counseling practice test coming soon \u2014 exam guide, topic outline, and notify when the timed readiness check launches.",
    examBody: "State Health Insurance Assistance Programs",
    questionSourceNote: "Wave 4 waitlist — timed bank coming soon.",
    searchAliases: ["SHIP counselor", "Medicare counseling exam", "SHIP certification"],
  }),
];

export const wave4MockSlugs = wave4MockExamConfigs.map((c) => c.slug);

