import type { MockExamConfig } from "./types";
import {
  fourNicheTopics,
  nicheReadinessConfig,
  NICHE_SESSION_QUESTIONS,
} from "./niche-readiness";

/** Wave 3 — 60 additional text-only US niche readiness checks. */
export const wave3MockExamConfigs: MockExamConfig[] = [
  nicheReadinessConfig({
    slug: "az-real-estate-readiness-check",
    title: "Arizona Real Estate Readiness Check",
    shortTitle: "Arizona Real Estate",
    linkedDeckSlug: "az-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership & land use" },
      { id: "finance-appraisal", label: "Finance & appraisal" },
      { id: "az-license-law", label: "Arizona license law" }
    ]),
    officialSourceNote: "Mapped to Arizona Department of Real Estate themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Arizona Real Estate readiness check with topic scoring.",
    examBody: "Arizona Department of Real Estate",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["Arizona real estate", "AZ RE"],
  }),
  nicheReadinessConfig({
    slug: "ga-real-estate-readiness-check",
    title: "Georgia Real Estate Readiness Check",
    shortTitle: "Georgia Real Estate",
    linkedDeckSlug: "ga-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "ga-license-law", label: "Georgia license law" }
    ]),
    officialSourceNote: "Mapped to Georgia Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Georgia Real Estate readiness check with topic scoring.",
    examBody: "Georgia Real Estate Commission",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["Georgia real estate", "GA RE"],
  }),
  nicheReadinessConfig({
    slug: "il-real-estate-readiness-check",
    title: "Illinois Real Estate Readiness Check",
    shortTitle: "Illinois Real Estate",
    linkedDeckSlug: "il-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & disclosure" },
      { id: "property-ownership", label: "Ownership & transfer" },
      { id: "finance-math", label: "Finance & math" },
      { id: "il-license-law", label: "Illinois license law" }
    ]),
    officialSourceNote: "Mapped to IDFPR themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Illinois Real Estate readiness check with topic scoring.",
    examBody: "IDFPR",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["Illinois real estate", "IL RE"],
  }),
  nicheReadinessConfig({
    slug: "oh-real-estate-readiness-check",
    title: "Ohio Real Estate Readiness Check",
    shortTitle: "Ohio Real Estate",
    linkedDeckSlug: "oh-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property interests" },
      { id: "finance-appraisal", label: "Finance & appraisal" },
      { id: "oh-license-law", label: "Ohio license law" }
    ]),
    officialSourceNote: "Mapped to Ohio Division of Real Estate themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Ohio Real Estate readiness check with topic scoring.",
    examBody: "Ohio Division of Real Estate",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["Ohio real estate", "OH RE"],
  }),
  nicheReadinessConfig({
    slug: "pa-real-estate-readiness-check",
    title: "Pennsylvania Real Estate Readiness Check",
    shortTitle: "Pennsylvania Real Estate",
    linkedDeckSlug: "pa-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Ownership & deeds" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "pa-license-law", label: "Pennsylvania license law" }
    ]),
    officialSourceNote: "Mapped to Pennsylvania Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Pennsylvania Real Estate readiness check with topic scoring.",
    examBody: "Pennsylvania Real Estate Commission",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["Pennsylvania real estate", "PA RE"],
  }),
  nicheReadinessConfig({
    slug: "nc-real-estate-readiness-check",
    title: "North Carolina Real Estate Readiness Check",
    shortTitle: "North Carolina Real Estate",
    linkedDeckSlug: "nc-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Property ownership" },
      { id: "finance-math", label: "Finance & math" },
      { id: "nc-license-law", label: "North Carolina license law" }
    ]),
    officialSourceNote: "Mapped to NCREC themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question North Carolina Real Estate readiness check with topic scoring.",
    examBody: "NCREC",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["North Carolina real estate", "NC RE"],
  }),
  nicheReadinessConfig({
    slug: "va-real-estate-readiness-check",
    title: "Virginia Real Estate Readiness Check",
    shortTitle: "Virginia Real Estate",
    linkedDeckSlug: "va-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Ownership & land use" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "va-license-law", label: "Virginia license law" }
    ]),
    officialSourceNote: "Mapped to Virginia DPOR themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Virginia Real Estate readiness check with topic scoring.",
    examBody: "Virginia DPOR",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["Virginia real estate", "VA RE"],
  }),
  nicheReadinessConfig({
    slug: "wa-real-estate-readiness-check",
    title: "Washington Real Estate Readiness Check",
    shortTitle: "Washington Real Estate",
    linkedDeckSlug: "wa-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Ownership & land use" },
      { id: "finance-appraisal", label: "Finance & appraisal" },
      { id: "wa-license-law", label: "Washington license law" }
    ]),
    officialSourceNote: "Mapped to Washington DOL themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Washington Real Estate readiness check with topic scoring.",
    examBody: "Washington DOL",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["Washington real estate", "WA RE"],
  }),
  nicheReadinessConfig({
    slug: "co-real-estate-readiness-check",
    title: "Colorado Real Estate Readiness Check",
    shortTitle: "Colorado Real Estate",
    linkedDeckSlug: "co-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Ownership & conveyancing" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "co-license-law", label: "Colorado license law" }
    ]),
    officialSourceNote: "Mapped to Colorado Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Colorado Real Estate readiness check with topic scoring.",
    examBody: "Colorado Real Estate Commission",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["Colorado real estate", "CO RE"],
  }),
  nicheReadinessConfig({
    slug: "nj-real-estate-readiness-check",
    title: "New Jersey Real Estate Readiness Check",
    shortTitle: "New Jersey Real Estate",
    linkedDeckSlug: "nj-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & ethics" },
      { id: "property-ownership", label: "Ownership & leases" },
      { id: "finance-math", label: "Finance & math" },
      { id: "nj-license-law", label: "New Jersey license law" }
    ]),
    officialSourceNote: "Mapped to New Jersey Real Estate Commission themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question New Jersey Real Estate readiness check with topic scoring.",
    examBody: "New Jersey Real Estate Commission",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["New Jersey real estate", "NJ RE"],
  }),
  nicheReadinessConfig({
    slug: "ma-real-estate-readiness-check",
    title: "Massachusetts Real Estate Readiness Check",
    shortTitle: "Massachusetts Real Estate",
    linkedDeckSlug: "ma-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Ownership & transfer" },
      { id: "finance-closing", label: "Finance & closing" },
      { id: "ma-license-law", label: "Massachusetts license law" }
    ]),
    officialSourceNote: "Mapped to Massachusetts Board of Registration themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Massachusetts Real Estate readiness check with topic scoring.",
    examBody: "Massachusetts Board of Registration",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["Massachusetts real estate", "MA RE"],
  }),
  nicheReadinessConfig({
    slug: "mi-real-estate-readiness-check",
    title: "Michigan Real Estate Readiness Check",
    shortTitle: "Michigan Real Estate",
    linkedDeckSlug: "mi-real-estate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "agency-law", label: "Agency & contracts" },
      { id: "property-ownership", label: "Ownership & land use" },
      { id: "finance-appraisal", label: "Finance & appraisal" },
      { id: "mi-license-law", label: "Michigan license law" }
    ]),
    officialSourceNote: "Mapped to Michigan LARA themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Michigan Real Estate readiness check with topic scoring.",
    examBody: "Michigan LARA",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["Michigan real estate", "MI RE"],
  }),
  nicheReadinessConfig({
    slug: "cdl-air-brakes-readiness-check",
    title: "CDL Air Brakes Readiness Check",
    shortTitle: "CDL Air Brakes",
    linkedDeckSlug: "cdl-air-brakes-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "systems", label: "Air brake systems" },
      { id: "inspection", label: "Inspections & tests" },
      { id: "operation", label: "Safe operation" },
      { id: "failures", label: "Failures & emergencies" }
    ]),
    officialSourceNote: "Mapped to State DMV / FMCSA themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question CDL Air Brakes readiness check with topic scoring.",
    examBody: "State DMV / FMCSA",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["CDL air brakes", "air brake endorsement"],
  }),
  nicheReadinessConfig({
    slug: "cdl-combination-readiness-check",
    title: "CDL Combination Vehicles Readiness Check",
    shortTitle: "CDL Combination Vehicles",
    linkedDeckSlug: "cdl-combination-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "coupling", label: "Coupling & uncoupling" },
      { id: "handling", label: "Combination handling" },
      { id: "inspection", label: "Combination inspection" },
      { id: "safety", label: "Rollover & jackknife prevention" }
    ]),
    officialSourceNote: "Mapped to State DMV / FMCSA themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question CDL Combination Vehicles readiness check with topic scoring.",
    examBody: "State DMV / FMCSA",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["CDL combination", "Class A combination"],
  }),
  nicheReadinessConfig({
    slug: "cdl-doubles-triples-readiness-check",
    title: "CDL Doubles/Triples Readiness Check",
    shortTitle: "CDL Doubles/Triples",
    linkedDeckSlug: "cdl-doubles-triples-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "coupling", label: "Doubles coupling" },
      { id: "handling", label: "Handling doubles/triples" },
      { id: "inspection", label: "Inspection points" },
      { id: "safety", label: "Safety & limitations" }
    ]),
    officialSourceNote: "Mapped to State DMV / FMCSA themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question CDL Doubles/Triples readiness check with topic scoring.",
    examBody: "State DMV / FMCSA",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["CDL doubles", "triples endorsement", "T endorsement"],
  }),
  nicheReadinessConfig({
    slug: "cdl-tankers-readiness-check",
    title: "CDL Tank Vehicles Readiness Check",
    shortTitle: "CDL Tank Vehicles",
    linkedDeckSlug: "cdl-tankers-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "liquid-surge", label: "Liquid surge" },
      { id: "loading", label: "Loading & baffles" },
      { id: "driving", label: "Tank driving techniques" },
      { id: "emergency", label: "Emergencies & leaks" }
    ]),
    officialSourceNote: "Mapped to State DMV / FMCSA themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question CDL Tank Vehicles readiness check with topic scoring.",
    examBody: "State DMV / FMCSA",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["CDL tanker", "N endorsement", "tank vehicles"],
  }),
  nicheReadinessConfig({
    slug: "nclex-rn-readiness-check",
    title: "NCLEX-RN Readiness Check",
    shortTitle: "NCLEX-RN",
    linkedDeckSlug: "nclex-rn-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "safe-care", label: "Safe & effective care" },
      { id: "health-promo", label: "Health promotion" },
      { id: "psychosocial", label: "Psychosocial integrity" },
      { id: "physio", label: "Physiological integrity" }
    ]),
    officialSourceNote: "Mapped to NCSBN themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question NCLEX-RN readiness check with topic scoring.",
    examBody: "NCSBN",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["NCLEX-RN", "RN license exam"],
  }),
  nicheReadinessConfig({
    slug: "medication-aide-readiness-check",
    title: "Medication Aide Readiness Check",
    shortTitle: "Medication Aide",
    linkedDeckSlug: "medication-aide-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "rights", label: "Six rights & orders" },
      { id: "routes", label: "Routes & forms" },
      { id: "safety", label: "Safety & side effects" },
      { id: "docs", label: "Documentation & scope" }
    ]),
    officialSourceNote: "Mapped to State nurse aide / medication aide boards themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Medication Aide readiness check with topic scoring.",
    examBody: "State nurse aide / medication aide boards",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["medication aide", "CMA med aide"],
  }),
  nicheReadinessConfig({
    slug: "home-health-aide-readiness-check",
    title: "Home Health Aide Readiness Check",
    shortTitle: "Home Health Aide",
    linkedDeckSlug: "home-health-aide-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "adls", label: "ADLs & personal care" },
      { id: "safety", label: "Home safety & infection" },
      { id: "obs", label: "Observation & reporting" },
      { id: "ethics", label: "Ethics & boundaries" }
    ]),
    officialSourceNote: "Mapped to State / federal HHA training standards themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Home Health Aide readiness check with topic scoring.",
    examBody: "State / federal HHA training standards",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["home health aide", "HHA exam"],
  }),
  nicheReadinessConfig({
    slug: "rbt-behavior-technician-readiness-check",
    title: "RBT Readiness Check",
    shortTitle: "RBT",
    linkedDeckSlug: "rbt-behavior-technician-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "measurement", label: "Measurement" },
      { id: "assessment", label: "Assessment support" },
      { id: "skill-acq", label: "Skill acquisition" },
      { id: "ethics", label: "Ethics & professionalism" }
    ]),
    officialSourceNote: "Mapped to BACB themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question RBT readiness check with topic scoring.",
    examBody: "BACB",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["RBT", "registered behavior technician"],
  }),
  nicheReadinessConfig({
    slug: "amt-rma-readiness-check",
    title: "AMT RMA Readiness Check",
    shortTitle: "AMT RMA",
    linkedDeckSlug: "amt-rma-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "clinical", label: "Clinical procedures" },
      { id: "admin", label: "Administrative" },
      { id: "anatomy", label: "Anatomy & terminology" },
      { id: "law-ethics", label: "Law & ethics" }
    ]),
    officialSourceNote: "Mapped to American Medical Technologists themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question AMT RMA readiness check with topic scoring.",
    examBody: "American Medical Technologists",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["RMA", "AMT RMA", "registered medical assistant"],
  }),
  nicheReadinessConfig({
    slug: "ascp-mlt-readiness-check",
    title: "ASCP MLT Readiness Check",
    shortTitle: "ASCP MLT",
    linkedDeckSlug: "ascp-mlt-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "blood-bank", label: "Blood bank" },
      { id: "chemistry", label: "Chemistry" },
      { id: "hematology", label: "Hematology" },
      { id: "micro", label: "Microbiology" }
    ]),
    officialSourceNote: "Mapped to ASCP Board of Certification themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question ASCP MLT readiness check with topic scoring.",
    examBody: "ASCP Board of Certification",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["MLT", "ASCP MLT", "medical lab technician"],
  }),
  nicheReadinessConfig({
    slug: "aapc-ccs-readiness-check",
    title: "AAPC / AHIMA CCS-style Coding Readiness Check",
    shortTitle: "AAPC / AHIMA CCS-style Coding",
    linkedDeckSlug: "aapc-ccs-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "icd", label: "ICD diagnosis coding" },
      { id: "pcs", label: "ICD-10-PCS concepts" },
      { id: "guidelines", label: "Coding guidelines" },
      { id: "compliance", label: "Compliance & CDI" }
    ]),
    officialSourceNote: "Mapped to AHIMA / inpatient coding themes themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question AAPC / AHIMA CCS-style Coding readiness check with topic scoring.",
    examBody: "AHIMA / inpatient coding themes",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["CCS", "inpatient coding", "AHIMA CCS"],
  }),
  nicheReadinessConfig({
    slug: "medical-scribe-readiness-check",
    title: "Medical Scribe Readiness Check",
    shortTitle: "Medical Scribe",
    linkedDeckSlug: "medical-scribe-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "documentation", label: "Clinical documentation" },
      { id: "terminology", label: "Terminology" },
      { id: "workflow", label: "EHR workflow" },
      { id: "compliance", label: "Privacy & compliance" }
    ]),
    officialSourceNote: "Mapped to Employer / ACMSS-style scribe competencies themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Medical Scribe readiness check with topic scoring.",
    examBody: "Employer / ACMSS-style scribe competencies",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["medical scribe", "scribe certification"],
  }),
  nicheReadinessConfig({
    slug: "nremt-aemt-readiness-check",
    title: "NREMT AEMT Readiness Check",
    shortTitle: "NREMT AEMT",
    linkedDeckSlug: "nremt-aemt-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "airway", label: "Advanced airway" },
      { id: "pharm", label: "Pharmacology" },
      { id: "medical", label: "Medical emergencies" },
      { id: "trauma", label: "Trauma & ops" }
    ]),
    officialSourceNote: "Mapped to NREMT themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question NREMT AEMT readiness check with topic scoring.",
    examBody: "NREMT",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["AEMT", "NREMT AEMT", "advanced EMT"],
  }),
  nicheReadinessConfig({
    slug: "physical-therapy-aide-readiness-check",
    title: "Physical Therapy Aide Readiness Check",
    shortTitle: "Physical Therapy Aide",
    linkedDeckSlug: "physical-therapy-aide-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "modalities", label: "Modalities assist" },
      { id: "safety", label: "Safety & transfers" },
      { id: "anatomy", label: "Basic anatomy" },
      { id: "ethics", label: "Ethics & scope" }
    ]),
    officialSourceNote: "Mapped to Employer / state PT aide rules themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Physical Therapy Aide readiness check with topic scoring.",
    examBody: "Employer / state PT aide rules",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["PT aide", "physical therapy aide"],
  }),
  nicheReadinessConfig({
    slug: "aspt-phlebotomy-readiness-check",
    title: "ASPT Phlebotomy Readiness Check",
    shortTitle: "ASPT Phlebotomy",
    linkedDeckSlug: "aspt-phlebotomy-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "venipuncture", label: "Venipuncture" },
      { id: "tubes", label: "Order of draw & tubes" },
      { id: "safety", label: "Safety & infection" },
      { id: "processing", label: "Processing & QA" }
    ]),
    officialSourceNote: "Mapped to ASPT themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question ASPT Phlebotomy readiness check with topic scoring.",
    examBody: "ASPT",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["ASPT", "phlebotomy technician"],
  }),
  nicheReadinessConfig({
    slug: "abo-optician-readiness-check",
    title: "ABO Optician Readiness Check",
    shortTitle: "ABO Optician",
    linkedDeckSlug: "abo-optician-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "optics", label: "Basic optics" },
      { id: "lenses", label: "Lenses & materials" },
      { id: "fitting", label: "Fitting & adjustments" },
      { id: "instruments", label: "Instruments & regulations" }
    ]),
    officialSourceNote: "Mapped to American Board of Opticianry themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question ABO Optician readiness check with topic scoring.",
    examBody: "American Board of Opticianry",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["ABO", "optician exam", "ABO-NCLE"],
  }),
  nicheReadinessConfig({
    slug: "acsm-cpt-readiness-check",
    title: "ACSM CPT Readiness Check",
    shortTitle: "ACSM CPT",
    linkedDeckSlug: "acsm-cpt-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "assessment", label: "Client assessment" },
      { id: "programming", label: "Exercise programming" },
      { id: "science", label: "Exercise science" },
      { id: "behavior", label: "Behavior & safety" }
    ]),
    officialSourceNote: "Mapped to ACSM themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question ACSM CPT readiness check with topic scoring.",
    examBody: "ACSM",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["ACSM CPT", "ACSM personal trainer"],
  }),
  nicheReadinessConfig({
    slug: "nsca-cpt-readiness-check",
    title: "NSCA-CPT Readiness Check",
    shortTitle: "NSCA-CPT",
    linkedDeckSlug: "nsca-cpt-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "assessment", label: "Assessment" },
      { id: "program-design", label: "Program design" },
      { id: "technique", label: "Exercise technique" },
      { id: "safety", label: "Safety & client consult" }
    ]),
    officialSourceNote: "Mapped to NSCA themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question NSCA-CPT readiness check with topic scoring.",
    examBody: "NSCA",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["NSCA-CPT", "NSCA personal trainer"],
  }),
  nicheReadinessConfig({
    slug: "precision-nutrition-l1-readiness-check",
    title: "Precision Nutrition L1 Readiness Check",
    shortTitle: "Precision Nutrition L1",
    linkedDeckSlug: "precision-nutrition-l1-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "coaching", label: "Client coaching" },
      { id: "nutrition-sci", label: "Nutrition science" },
      { id: "habits", label: "Habit change" },
      { id: "scopes", label: "Scope & ethics" }
    ]),
    officialSourceNote: "Mapped to Precision Nutrition themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Precision Nutrition L1 readiness check with topic scoring.",
    examBody: "Precision Nutrition",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["Precision Nutrition", "PN Level 1"],
  }),
  nicheReadinessConfig({
    slug: "cscs-nsca-readiness-check",
    title: "NSCA CSCS Readiness Check",
    shortTitle: "NSCA CSCS",
    linkedDeckSlug: "cscs-nsca-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "exercise-sci", label: "Exercise science" },
      { id: "nutrition", label: "Nutrition" },
      { id: "program-design", label: "Program design" },
      { id: "organization", label: "Organization & admin" }
    ]),
    officialSourceNote: "Mapped to NSCA themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question NSCA CSCS readiness check with topic scoring.",
    examBody: "NSCA",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["CSCS", "NSCA CSCS", "strength coach"],
  }),
  nicheReadinessConfig({
    slug: "nail-technician-state-readiness-check",
    title: "Nail Technician Readiness Check",
    shortTitle: "Nail Technician",
    linkedDeckSlug: "nail-technician-state-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "infection", label: "Infection control" },
      { id: "nail-anatomy", label: "Nail anatomy" },
      { id: "services", label: "Manicure/pedicure services" },
      { id: "chemistry", label: "Products & chemistry" }
    ]),
    officialSourceNote: "Mapped to State cosmetology boards themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Nail Technician readiness check with topic scoring.",
    examBody: "State cosmetology boards",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["nail tech exam", "manicurist license"],
  }),
  nicheReadinessConfig({
    slug: "barber-state-readiness-check",
    title: "Barber Readiness Check",
    shortTitle: "Barber",
    linkedDeckSlug: "barber-state-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "infection", label: "Infection control" },
      { id: "cutting", label: "Cutting & shaving" },
      { id: "chemistry", label: "Chemical services" },
      { id: "laws", label: "State laws & safety" }
    ]),
    officialSourceNote: "Mapped to State barber boards themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Barber readiness check with topic scoring.",
    examBody: "State barber boards",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["barber exam", "barber license"],
  }),
  nicheReadinessConfig({
    slug: "aswb-bachelors-readiness-check",
    title: "ASWB Bachelors Readiness Check",
    shortTitle: "ASWB Bachelors",
    linkedDeckSlug: "aswb-bachelors-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "hgb", label: "Human development" },
      { id: "assessment", label: "Assessment" },
      { id: "intervention", label: "Intervention" },
      { id: "ethics", label: "Ethics & law" }
    ]),
    officialSourceNote: "Mapped to ASWB themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question ASWB Bachelors readiness check with topic scoring.",
    examBody: "ASWB",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["ASWB Bachelors", "LSW exam"],
  }),
  nicheReadinessConfig({
    slug: "aswb-clinical-readiness-check",
    title: "ASWB Clinical Readiness Check",
    shortTitle: "ASWB Clinical",
    linkedDeckSlug: "aswb-clinical-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "assessment", label: "Clinical assessment" },
      { id: "diagnosis", label: "Diagnosis concepts" },
      { id: "psychotherapy", label: "Psychotherapy" },
      { id: "ethics", label: "Ethics & law" }
    ]),
    officialSourceNote: "Mapped to ASWB themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question ASWB Clinical readiness check with topic scoring.",
    examBody: "ASWB",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["ASWB Clinical", "LCSW exam"],
  }),
  nicheReadinessConfig({
    slug: "shrm-cp-readiness-check",
    title: "SHRM-CP Readiness Check",
    shortTitle: "SHRM-CP",
    linkedDeckSlug: "shrm-cp-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "people", label: "People" },
      { id: "organization", label: "Organization" },
      { id: "workplace", label: "Workplace" },
      { id: "strategy", label: "Behavioral competencies" }
    ]),
    officialSourceNote: "Mapped to SHRM themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question SHRM-CP readiness check with topic scoring.",
    examBody: "SHRM",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["SHRM-CP", "SHRM certified professional"],
  }),
  nicheReadinessConfig({
    slug: "phr-hrci-readiness-check",
    title: "PHR Readiness Check",
    shortTitle: "PHR",
    linkedDeckSlug: "phr-hrci-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "talent", label: "Talent management" },
      { id: "employee-rel", label: "Employee relations" },
      { id: "comp-ben", label: "Compensation & benefits" },
      { id: "compliance", label: "Compliance & risk" }
    ]),
    officialSourceNote: "Mapped to HRCI themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question PHR readiness check with topic scoring.",
    examBody: "HRCI",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["PHR", "HRCI PHR"],
  }),
  nicheReadinessConfig({
    slug: "capm-readiness-check",
    title: "CAPM Readiness Check",
    shortTitle: "CAPM",
    linkedDeckSlug: "capm-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "framework", label: "Project framework" },
      { id: "process", label: "Process groups" },
      { id: "predictive", label: "Predictive methods" },
      { id: "agile", label: "Agile & business analysis" }
    ]),
    officialSourceNote: "Mapped to PMI themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question CAPM readiness check with topic scoring.",
    examBody: "PMI",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["CAPM", "PMI CAPM"],
  }),
  nicheReadinessConfig({
    slug: "six-sigma-green-belt-readiness-check",
    title: "Six Sigma Green Belt Readiness Check",
    shortTitle: "Six Sigma Green Belt",
    linkedDeckSlug: "six-sigma-green-belt-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "dmaic", label: "DMAIC" },
      { id: "measure", label: "Measure & MSA" },
      { id: "analyze", label: "Analyze" },
      { id: "improve-control", label: "Improve & control" }
    ]),
    officialSourceNote: "Mapped to ASQ / IASSC-style bodies themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Six Sigma Green Belt readiness check with topic scoring.",
    examBody: "ASQ / IASSC-style bodies",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["Six Sigma Green Belt", "CSSGB"],
  }),
  nicheReadinessConfig({
    slug: "enrolled-agent-readiness-check",
    title: "IRS Enrolled Agent Readiness Check",
    shortTitle: "IRS Enrolled Agent",
    linkedDeckSlug: "enrolled-agent-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "individuals", label: "Individuals" },
      { id: "businesses", label: "Businesses" },
      { id: "representation", label: "Representation" },
      { id: "practices", label: "Practices & procedures" }
    ]),
    officialSourceNote: "Mapped to IRS themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question IRS Enrolled Agent readiness check with topic scoring.",
    examBody: "IRS",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["enrolled agent", "EA exam", "SEE"],
  }),
  nicheReadinessConfig({
    slug: "series-65-readiness-check",
    title: "Series 65 Readiness Check",
    shortTitle: "Series 65",
    linkedDeckSlug: "series-65-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "economics", label: "Economics & analysis" },
      { id: "products", label: "Investment products" },
      { id: "client", label: "Client recommendations" },
      { id: "ethics", label: "Laws & ethics" }
    ]),
    officialSourceNote: "Mapped to NASAA / FINRA delivery themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Series 65 readiness check with topic scoring.",
    examBody: "NASAA / FINRA delivery",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["Series 65", "investment adviser exam"],
  }),
  nicheReadinessConfig({
    slug: "series-66-readiness-check",
    title: "Series 66 Readiness Check",
    shortTitle: "Series 66",
    linkedDeckSlug: "series-66-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "products", label: "Investment products" },
      { id: "recommendations", label: "Recommendations" },
      { id: "state-law", label: "State laws" },
      { id: "ethics", label: "Ethics & supervision" }
    ]),
    officialSourceNote: "Mapped to NASAA / FINRA delivery themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Series 66 readiness check with topic scoring.",
    examBody: "NASAA / FINRA delivery",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["Series 66", "65+63 combo"],
  }),
  nicheReadinessConfig({
    slug: "series-6-readiness-check",
    title: "Series 6 Readiness Check",
    shortTitle: "Series 6",
    linkedDeckSlug: "series-6-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "products", label: "Investment company products" },
      { id: "retirement", label: "Retirement & insurance" },
      { id: "suitability", label: "Suitability" },
      { id: "regulations", label: "Regulations" }
    ]),
    officialSourceNote: "Mapped to FINRA themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Series 6 readiness check with topic scoring.",
    examBody: "FINRA",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["Series 6", "investment company products"],
  }),
  nicheReadinessConfig({
    slug: "praxis-core-readiness-check",
    title: "Praxis Core Readiness Check",
    shortTitle: "Praxis Core",
    linkedDeckSlug: "praxis-core-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "reading", label: "Reading" },
      { id: "writing", label: "Writing" },
      { id: "math", label: "Mathematics" },
      { id: "test-strat", label: "Academic skills strategy" }
    ]),
    officialSourceNote: "Mapped to ETS themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Praxis Core readiness check with topic scoring.",
    examBody: "ETS",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["Praxis Core", "Praxis I"],
  }),
  nicheReadinessConfig({
    slug: "parapro-readiness-check",
    title: "ParaPro Readiness Check",
    shortTitle: "ParaPro",
    linkedDeckSlug: "parapro-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "reading", label: "Reading skills" },
      { id: "writing", label: "Writing skills" },
      { id: "math", label: "Math skills" },
      { id: "application", label: "Classroom application" }
    ]),
    officialSourceNote: "Mapped to ETS themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question ParaPro readiness check with topic scoring.",
    examBody: "ETS",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["ParaPro", "paraprofessional exam"],
  }),
  nicheReadinessConfig({
    slug: "unarmed-security-officer-readiness-check",
    title: "Unarmed Security Officer Readiness Check",
    shortTitle: "Unarmed Security Officer",
    linkedDeckSlug: "unarmed-security-officer-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "law", label: "Law & liability" },
      { id: "patrol", label: "Patrol & observation" },
      { id: "emergency", label: "Emergencies" },
      { id: "ethics", label: "Ethics & report writing" }
    ]),
    officialSourceNote: "Mapped to State security licensing boards themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Unarmed Security Officer readiness check with topic scoring.",
    examBody: "State security licensing boards",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["security officer exam", "unarmed guard card"],
  }),
  nicheReadinessConfig({
    slug: "alcohol-server-readiness-check",
    title: "Alcohol Server Readiness Check",
    shortTitle: "Alcohol Server",
    linkedDeckSlug: "alcohol-server-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "laws", label: "Alcohol laws" },
      { id: "intoxication", label: "Intoxication signs" },
      { id: "id-check", label: "ID checking" },
      { id: "intervention", label: "Intervention" }
    ]),
    officialSourceNote: "Mapped to State alcohol server / TIPS-style programs themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Alcohol Server readiness check with topic scoring.",
    examBody: "State alcohol server / TIPS-style programs",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["alcohol server", "TIPS", "Responsible Beverage"],
  }),
  nicheReadinessConfig({
    slug: "notary-public-readiness-check",
    title: "Notary Public Readiness Check",
    shortTitle: "Notary Public",
    linkedDeckSlug: "notary-public-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "duties", label: "Notarial duties" },
      { id: "id-journals", label: "ID & journals" },
      { id: "certificates", label: "Certificates" },
      { id: "misconduct", label: "Misconduct & liability" }
    ]),
    officialSourceNote: "Mapped to State notary commissioning offices themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Notary Public readiness check with topic scoring.",
    examBody: "State notary commissioning offices",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["notary exam", "notary public"],
  }),
  nicheReadinessConfig({
    slug: "forklift-operator-readiness-check",
    title: "Forklift Operator Readiness Check",
    shortTitle: "Forklift Operator",
    linkedDeckSlug: "forklift-operator-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "stability", label: "Stability triangle" },
      { id: "inspection", label: "Inspection" },
      { id: "operation", label: "Safe operation" },
      { id: "pedestrians", label: "Pedestrians & loads" }
    ]),
    officialSourceNote: "Mapped to OSHA powered industrial trucks themes themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Forklift Operator readiness check with topic scoring.",
    examBody: "OSHA powered industrial trucks themes",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["forklift certification", "PIT operator"],
  }),
  nicheReadinessConfig({
    slug: "osha-10-general-readiness-check",
    title: "OSHA 10 General Industry Readiness Check",
    shortTitle: "OSHA 10 General Industry",
    linkedDeckSlug: "osha-10-general-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "intro", label: "Intro to OSHA" },
      { id: "walking", label: "Walking-working surfaces" },
      { id: "hazcom", label: "Hazard communication" },
      { id: "ppe-electrical", label: "PPE & electrical" }
    ]),
    officialSourceNote: "Mapped to OSHA Outreach / general industry themes themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question OSHA 10 General Industry readiness check with topic scoring.",
    examBody: "OSHA Outreach / general industry themes",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["OSHA 10", "OSHA 10 general industry"],
  }),
  nicheReadinessConfig({
    slug: "nate-core-readiness-check",
    title: "NATE Core Readiness Check",
    shortTitle: "NATE Core",
    linkedDeckSlug: "nate-core-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "safety", label: "Safety" },
      { id: "tools", label: "Tools & math" },
      { id: "electrical", label: "Electrical basics" },
      { id: "soft-skills", label: "Soft skills & ethics" }
    ]),
    officialSourceNote: "Mapped to NATE themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question NATE Core readiness check with topic scoring.",
    examBody: "NATE",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["NATE Core", "HVAC NATE"],
  }),
  nicheReadinessConfig({
    slug: "servsafe-food-handler-readiness-check",
    title: "ServSafe Food Handler Readiness Check",
    shortTitle: "ServSafe Food Handler",
    linkedDeckSlug: "servsafe-food-handler-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "contamination", label: "Contamination" },
      { id: "hygiene", label: "Personal hygiene" },
      { id: "time-temp", label: "Time & temperature" },
      { id: "cleaning", label: "Cleaning & allergens" }
    ]),
    officialSourceNote: "Mapped to National Restaurant Association themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question ServSafe Food Handler readiness check with topic scoring.",
    examBody: "National Restaurant Association",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["ServSafe Food Handler", "food handler card"],
  }),
  nicheReadinessConfig({
    slug: "first-aid-cpr-readiness-check",
    title: "First Aid / CPR Cognitive Readiness Check",
    shortTitle: "First Aid / CPR Cognitive",
    linkedDeckSlug: "first-aid-cpr-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "cpr", label: "CPR & AED" },
      { id: "bleeding", label: "Bleeding & shock" },
      { id: "medical", label: "Medical emergencies" },
      { id: "injury", label: "Injury & environment" }
    ]),
    officialSourceNote: "Mapped to AHA / Red Cross-style first aid themes themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question First Aid / CPR Cognitive readiness check with topic scoring.",
    examBody: "AHA / Red Cross-style first aid themes",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["first aid practice test", "CPR first aid"],
  }),
  nicheReadinessConfig({
    slug: "mortgage-loan-originator-readiness-check",
    title: "SAFE MLO Readiness Check",
    shortTitle: "SAFE MLO",
    linkedDeckSlug: "mortgage-loan-originator-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "origination", label: "Origination process" },
      { id: "products", label: "Mortgage products" },
      { id: "fed-law", label: "Federal law" },
      { id: "ethics", label: "Ethics & Uniform State Content" }
    ]),
    officialSourceNote: "Mapped to NMLS / SAFE MLO themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question SAFE MLO readiness check with topic scoring.",
    examBody: "NMLS / SAFE MLO",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["SAFE MLO", "NMLS exam", "mortgage loan originator"],
  }),
  nicheReadinessConfig({
    slug: "wastewater-operator-1-readiness-check",
    title: "Wastewater Operator Level 1 Readiness Check",
    shortTitle: "Wastewater Operator Level 1",
    linkedDeckSlug: "wastewater-operator-1-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "process", label: "Treatment processes" },
      { id: "safety", label: "Safety & confined space" },
      { id: "labs", label: "Labs & sampling" },
      { id: "regs", label: "Regs & reporting" }
    ]),
    officialSourceNote: "Mapped to State wastewater operator boards themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Wastewater Operator Level 1 readiness check with topic scoring.",
    examBody: "State wastewater operator boards",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["wastewater operator", "WW operator exam"],
  }),
  nicheReadinessConfig({
    slug: "real-estate-appraiser-readiness-check",
    title: "Real Estate Appraiser Readiness Check",
    shortTitle: "Real Estate Appraiser",
    linkedDeckSlug: "real-estate-appraiser-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "uspaps", label: "USPAP concepts" },
      { id: "approaches", label: "Valuation approaches" },
      { id: "math", label: "Appraisal math" },
      { id: "ethics", label: "Ethics & reporting" }
    ]),
    officialSourceNote: "Mapped to AQB / state appraiser boards themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Real Estate Appraiser readiness check with topic scoring.",
    examBody: "AQB / state appraiser boards",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["appraiser exam", "AQB national"],
  }),
  nicheReadinessConfig({
    slug: "funeral-service-arts-readiness-check",
    title: "Funeral Service Arts Readiness Check",
    shortTitle: "Funeral Service Arts",
    linkedDeckSlug: "funeral-service-arts-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "mortuary", label: "Mortuary sciences arts" },
      { id: "law", label: "Funeral service law" },
      { id: "psychology", label: "Grief & psychology" },
      { id: "business", label: "Funeral home business" }
    ]),
    officialSourceNote: "Mapped to The Conference (NBE) themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Funeral Service Arts readiness check with topic scoring.",
    examBody: "The Conference (NBE)",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["NBE Arts", "funeral director exam"],
  }),
  nicheReadinessConfig({
    slug: "nabcep-associate-readiness-check",
    title: "NABCEP Associate Readiness Check",
    shortTitle: "NABCEP Associate",
    linkedDeckSlug: "nabcep-associate-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "pv-basics", label: "PV system basics" },
      { id: "safety", label: "Electrical safety" },
      { id: "design", label: "System components" },
      { id: "codes", label: "Codes & applications" }
    ]),
    officialSourceNote: "Mapped to NABCEP themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question NABCEP Associate readiness check with topic scoring.",
    examBody: "NABCEP",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["NABCEP Associate", "PV Associate"],
  }),
  nicheReadinessConfig({
    slug: "veterinary-assistant-readiness-check",
    title: "Veterinary Assistant Readiness Check",
    shortTitle: "Veterinary Assistant",
    linkedDeckSlug: "veterinary-assistant-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "restraint", label: "Animal restraint" },
      { id: "nursing", label: "Nursing assist" },
      { id: "hospital", label: "Hospital procedures" },
      { id: "safety", label: "Safety & zoonosis" }
    ]),
    officialSourceNote: "Mapped to NAVTA / employer VA competencies themes. Independent UniPrep2Go readiness check — not an official exam.",
    description: "Free 60-question Veterinary Assistant readiness check with topic scoring.",
    examBody: "NAVTA / employer VA competencies",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 3).",
    searchAliases: ["veterinary assistant", "AVA"],
  }),
];

export const wave3MockSlugs = wave3MockExamConfigs.map((c) => c.slug);

