import type { MockExamConfig } from "./types";
import {
  fourNicheTopics,
  nicheReadinessConfig,
  NICHE_SESSION_QUESTIONS,
} from "./niche-readiness";

/**
 * Wave 2 — next 23 text-only mocks from the 50-cert roadmap.
 * Skipped (image-heavy): arrt-ct, arrt-mri, ardms-abd, ardms-obgyn, arrt-mammography
 * (+ wave1 skips: nha-cet-ekg, arrt-radiography, danb-rhs)
 * Deferred: wastewater-1, ascp-mlt
 */
export const wave2MockExamConfigs: MockExamConfig[] = [
  nicheReadinessConfig({
    slug: "nha-cbcs-readiness-check",
    title: "NHA CBCS Billing & Coding Specialist Readiness Check",
    shortTitle: "NHA CBCS",
    linkedDeckSlug: "nha-cbcs-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "coding-guidelines", label: "Coding guidelines & ICD/CPT concepts" },
      { id: "claims-reimbursement", label: "Claims & reimbursement" },
      { id: "compliance-privacy", label: "Compliance, HIPAA & fraud" },
      { id: "revenue-cycle", label: "Revenue cycle & front office" },
    ]),
    officialSourceNote: "Mapped to NHA CBCS themes. Not an NHA certification exam.",
    description:
      "Free 60-question NHA CBCS readiness check for medical billing and coding specialist candidates.",
    examBody: "NHA",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "ccht-dialysis-readiness-check",
    title: "NNCC CCHT Dialysis Technician Readiness Check",
    shortTitle: "CCHT Dialysis",
    linkedDeckSlug: "ccht-dialysis-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "dialysis-principles", label: "Dialysis principles & machines" },
      { id: "patient-care", label: "Patient care & complications" },
      { id: "water-infection", label: "Water treatment & infection control" },
      { id: "safety-docs", label: "Safety, docs & professional practice" },
    ]),
    officialSourceNote: "Mapped to NNCC CCHT knowledge themes. Not an NNCC exam.",
    description: "Free 60-question CCHT dialysis technician readiness check.",
    examBody: "NNCC",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "aha-bls-provider-readiness-check",
    title: "AHA BLS Provider Cognitive Readiness Check",
    shortTitle: "AHA BLS Provider",
    linkedDeckSlug: "aha-bls-provider-anki-deck",
    durationMinutes: 45,
    questionCount: NICHE_SESSION_QUESTIONS,
    passPercent: 84,
    topics: fourNicheTopics(
      [
        { id: "adult-cpr", label: "Adult CPR & AED" },
        { id: "child-infant", label: "Child & infant CPR" },
        { id: "choking-opioid", label: "Choking & opioid emergency" },
        { id: "team-special", label: "Team dynamics & special situations" },
      ],
      84,
    ),
    officialSourceNote:
      "Cognitive-only BLS concepts aligned to AHA themes. Skills still required in-person. Not an AHA course card.",
    description:
      "Free 60-question AHA BLS Provider cognitive readiness check (not a substitute for skills testing).",
    examBody: "American Heart Association",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "nnaap-cna-readiness-check",
    title: "NNAAP CNA Knowledge Readiness Check",
    shortTitle: "NNAAP CNA",
    linkedDeckSlug: "nnaap-cna-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "adls-safety", label: "ADLs, mobility & safety" },
      { id: "infection-vitals", label: "Infection control & vitals" },
      { id: "psychosocial", label: "Psychosocial & communication" },
      { id: "role-rights", label: "Role, rights & reporting" },
    ]),
    officialSourceNote:
      "National nurse aide knowledge themes (state packs vary). Not a state NNAAP exam.",
    description: "Free 60-question CNA knowledge readiness check for nurse aide candidates.",
    examBody: "Credentia / state NNAAP",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "cosmetology-state-readiness-check",
    title: "NIC Cosmetology Theory Readiness Check",
    shortTitle: "Cosmetology Theory",
    linkedDeckSlug: "cosmetology-state-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "science-safety", label: "Scientific concepts & safety" },
      { id: "hair-services", label: "Hair care & services" },
      { id: "skin-nails", label: "Skin & nail services" },
      { id: "laws-salon", label: "Laws, infection control & salon" },
    ]),
    officialSourceNote: "NIC-style theory themes. State boards vary. Not a PSI/NIC exam.",
    description: "Free 60-question cosmetology theory readiness check (NIC-style).",
    examBody: "NIC / PSI / state board",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "nclex-pn-readiness-check",
    title: "NCLEX-PN Readiness Check",
    shortTitle: "NCLEX-PN",
    linkedDeckSlug: "nclex-pn-anki-deck",
    durationMinutes: 90,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "safe-care", label: "Safe & effective care" },
      { id: "health-promo", label: "Health promotion & maintenance" },
      { id: "psychosocial", label: "Psychosocial integrity" },
      { id: "physio", label: "Physiological integrity" },
    ]),
    officialSourceNote: "Client-needs style PN readiness diagnostic. Not an NCSBN NCLEX exam.",
    description: "Free 60-question NCLEX-PN readiness check with client-needs scoring.",
    examBody: "NCSBN",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "nasm-cpt-readiness-check",
    title: "NASM CPT Readiness Check",
    shortTitle: "NASM CPT",
    linkedDeckSlug: "nasm-cpt-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "basics-anatomy", label: "Basic anatomy & OPT model" },
      { id: "assessment", label: "Assessment & movement" },
      { id: "program-design", label: "Program design & modalities" },
      { id: "nutrition-biz", label: "Nutrition, behavior & business" },
    ]),
    officialSourceNote: "Mapped to NASM CPT knowledge domains. Not a NASM exam.",
    description: "Free 60-question NASM CPT readiness check for personal trainer candidates.",
    examBody: "NASM",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "esthetician-state-readiness-check",
    title: "NIC Esthetician Theory Readiness Check",
    shortTitle: "Esthetician Theory",
    linkedDeckSlug: "esthetician-state-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "skin-science", label: "Skin science & disorders" },
      { id: "treatments", label: "Facials, machines & treatments" },
      { id: "infection-safety", label: "Infection control & safety" },
      { id: "laws-business", label: "Laws & professional practice" },
    ]),
    officialSourceNote: "NIC-style esthetician theory themes. Not a state board exam.",
    description: "Free 60-question esthetician theory readiness check.",
    examBody: "NIC / state board",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "cdl-hazmat-readiness-check",
    title: "CDL HazMat Endorsement Readiness Check",
    shortTitle: "CDL HazMat",
    linkedDeckSlug: "cdl-hazmat-anki-deck",
    durationMinutes: 60,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "classes-placards", label: "Classes, placards & shipping papers" },
      { id: "loading-segregation", label: "Loading, segregation & bulk" },
      { id: "driving-emergencies", label: "Driving & emergencies" },
      { id: "security-rules", label: "Security awareness & rules" },
    ]),
    officialSourceNote: "FMCSA HazMat endorsement knowledge themes. Not a TSA/DMV exam.",
    description: "Free 60-question CDL HazMat endorsement readiness check.",
    examBody: "TSA / state DMV",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "aswb-masters-readiness-check",
    title: "ASWB Masters Social Work Readiness Check",
    shortTitle: "ASWB Masters",
    linkedDeckSlug: "aswb-masters-anki-deck",
    durationMinutes: 90,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "human-dev", label: "Human development & diversity" },
      { id: "assessment", label: "Assessment & intervention" },
      { id: "ethics", label: "Ethics & professional relationships" },
      { id: "practice", label: "Practice management & policy" },
    ]),
    officialSourceNote: "ASWB Masters content outline themes. Not an ASWB exam.",
    description: "Free 60-question ASWB Masters readiness check for LMSW candidates.",
    examBody: "ASWB",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "cdl-passenger-readiness-check",
    title: "CDL Passenger (P) Endorsement Readiness Check",
    shortTitle: "CDL Passenger",
    linkedDeckSlug: "cdl-passenger-anki-deck",
    durationMinutes: 50,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "vehicle-inspection", label: "Vehicle inspection & systems" },
      { id: "loading-passengers", label: "Loading & passenger safety" },
      { id: "driving-rail", label: "Driving, railroad & emergencies" },
      { id: "prohibited", label: "Prohibited practices & rules" },
    ]),
    officialSourceNote: "FMCSA passenger endorsement themes. Not a state DMV exam.",
    description: "Free 60-question CDL Passenger (P) endorsement readiness check.",
    examBody: "State DMV / FMCSA",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "issa-cpt-readiness-check",
    title: "ISSA CPT Readiness Check",
    shortTitle: "ISSA CPT",
    linkedDeckSlug: "issa-cpt-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "anatomy-phys", label: "Anatomy & physiology" },
      { id: "training", label: "Training principles & programming" },
      { id: "special-pops", label: "Special populations & assessment" },
      { id: "nutrition-biz", label: "Nutrition, behavior & business" },
    ]),
    officialSourceNote: "ISSA CPT knowledge themes. Not an ISSA exam.",
    description: "Free 60-question ISSA CPT readiness check.",
    examBody: "ISSA",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "ny-real-estate-readiness-check",
    title: "New York Real Estate Salesperson Readiness Check",
    shortTitle: "NY Real Estate",
    linkedDeckSlug: "ny-real-estate-anki-deck",
    durationMinutes: 90,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "license-law", label: "License law & DOS rules" },
      { id: "contracts-agency", label: "Contracts, agency & fair housing" },
      { id: "finance-valuation", label: "Finance, valuation & closing" },
      { id: "property-practice", label: "Property, land use & practice" },
    ]),
    officialSourceNote: "NY DOS salesperson knowledge themes. Not a New York licensing exam.",
    description: "Free 60-question New York real estate salesperson readiness check.",
    examBody: "NY DOS",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "cda-childcare-readiness-check",
    title: "CDA Child Development Associate Readiness Check",
    shortTitle: "CDA Childcare",
    linkedDeckSlug: "cda-childcare-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "safe-healthy", label: "Safe & healthy learning" },
      { id: "physical-cog", label: "Physical & cognitive development" },
      { id: "social-communication", label: "Social, emotional & communication" },
      { id: "families-professional", label: "Families & professional practice" },
    ]),
    officialSourceNote: "CDA competency themes. Not a Council CDA exam.",
    description: "Free 60-question CDA childcare readiness check.",
    examBody: "Council for Professional Recognition",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "ace-cpt-readiness-check",
    title: "ACE CPT Readiness Check",
    shortTitle: "ACE CPT",
    linkedDeckSlug: "ace-cpt-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "client-interview", label: "Client interviewing & screening" },
      { id: "program-design", label: "Program design & progression" },
      { id: "instruction", label: "Instruction & spotting" },
      { id: "professional", label: "Professional conduct & business" },
    ]),
    officialSourceNote: "ACE CPT domain themes. Not an ACE exam.",
    description: "Free 60-question ACE CPT readiness check.",
    examBody: "ACE",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "cdl-school-bus-readiness-check",
    title: "CDL School Bus (S) Endorsement Readiness Check",
    shortTitle: "CDL School Bus",
    linkedDeckSlug: "cdl-school-bus-anki-deck",
    durationMinutes: 50,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "vehicle-equipment", label: "Vehicle & equipment" },
      { id: "loading-unloading", label: "Loading, unloading & railroad" },
      { id: "student-management", label: "Student management & emergencies" },
      { id: "rules", label: "School bus rules & prohibited acts" },
    ]),
    officialSourceNote: "FMCSA school bus endorsement themes. Not a state DMV exam.",
    description: "Free 60-question CDL School Bus (S) endorsement readiness check.",
    examBody: "State DMV / FMCSA",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "nbrc-tmc-readiness-check",
    title: "NBRC TMC Respiratory Therapist Readiness Check",
    shortTitle: "NBRC TMC",
    linkedDeckSlug: "nbrc-tmc-anki-deck",
    durationMinutes: 90,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "patient-data", label: "Patient data evaluation" },
      { id: "equipment", label: "Equipment & quality control" },
      { id: "therapeutics", label: "Therapeutics & interventions" },
      { id: "emergency", label: "Emergency & special procedures" },
    ]),
    officialSourceNote: "NBRC TMC content themes. Not an NBRC exam.",
    description: "Free 60-question NBRC TMC readiness check for respiratory therapy candidates.",
    examBody: "NBRC",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "pest-control-applicator-readiness-check",
    title: "Structural Pest Control Applicator Readiness Check",
    shortTitle: "Pest Control Applicator",
    linkedDeckSlug: "pest-control-applicator-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "pests-id", label: "Pest identification & biology" },
      { id: "pesticides", label: "Pesticides, labels & IPM" },
      { id: "application-safety", label: "Application & applicator safety" },
      { id: "laws", label: "Laws, storage & environment" },
    ]),
    officialSourceNote: "State structural applicator knowledge themes. Not a state exam.",
    description: "Free 60-question structural pest control applicator readiness check.",
    examBody: "State agriculture department",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "aama-cma-readiness-check",
    title: "AAMA CMA Medical Assistant Readiness Check",
    shortTitle: "AAMA CMA",
    linkedDeckSlug: "aama-cma-anki-deck",
    durationMinutes: 90,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "clinical", label: "Clinical procedures" },
      { id: "anatomy-pharm", label: "Anatomy & pharmacology basics" },
      { id: "admin", label: "Administrative procedures" },
      { id: "law-ethics", label: "Law, ethics & safety" },
    ]),
    officialSourceNote: "AAMA CMA exam content themes. Not an AAMA certification exam.",
    description: "Free 60-question AAMA CMA readiness check for medical assistant candidates.",
    examBody: "AAMA",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "danb-gc-readiness-check",
    title: "DANB GC General Chairside Readiness Check",
    shortTitle: "DANB GC",
    linkedDeckSlug: "danb-gc-anki-deck",
    durationMinutes: 75,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "chairside", label: "Chairside assisting" },
      { id: "materials", label: "Dental materials & lab" },
      { id: "patient-care", label: "Patient care & prevention" },
      { id: "office", label: "Office operations & ethics" },
    ]),
    officialSourceNote: "DANB GC / CDA pathway themes. Not a DANB exam.",
    description: "Free 60-question DANB General Chairside readiness check.",
    examBody: "DANB",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "nbdhe-readiness-check",
    title: "NBDHE Dental Hygiene Readiness Check",
    shortTitle: "NBDHE",
    linkedDeckSlug: "nbdhe-anki-deck",
    durationMinutes: 90,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "sci-foundations", label: "Scientific foundations" },
      { id: "assessment", label: "Assessment & diagnosis" },
      { id: "planning-impl", label: "Planning & implementation" },
      { id: "eval-ethics", label: "Evaluation, ethics & community" },
    ]),
    officialSourceNote: "NBDHE content themes (text). Not a JCNDE/ADA exam.",
    description: "Free 60-question NBDHE dental hygiene readiness check.",
    examBody: "JCNDE / ADA",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "ascp-mls-readiness-check",
    title: "ASCP MLS Medical Lab Scientist Readiness Check",
    shortTitle: "ASCP MLS",
    linkedDeckSlug: "ascp-mls-anki-deck",
    durationMinutes: 90,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "blood-bank", label: "Blood bank" },
      { id: "chemistry", label: "Chemistry" },
      { id: "hematology", label: "Hematology & hemostasis" },
      { id: "micro-immuno", label: "Microbiology & immunology" },
    ]),
    officialSourceNote: "ASCP BOC MLS content themes. Not an ASCP exam.",
    description: "Free 60-question ASCP MLS readiness check.",
    examBody: "ASCP BOC",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
  nicheReadinessConfig({
    slug: "rd-exam-readiness-check",
    title: "CDR Registered Dietitian Exam Readiness Check",
    shortTitle: "RD Exam",
    linkedDeckSlug: "rd-exam-anki-deck",
    durationMinutes: 90,
    questionCount: NICHE_SESSION_QUESTIONS,
    topics: fourNicheTopics([
      { id: "principles", label: "Principles of dietetics" },
      { id: "nutrition-care", label: "Nutrition care for individuals" },
      { id: "foodservice", label: "Foodservice systems" },
      { id: "management", label: "Management & population" },
    ]),
    officialSourceNote: "CDR RD exam domain themes. Not a CDR exam.",
    description: "Free 60-question Registered Dietitian exam readiness check.",
    examBody: "CDR / Academy of Nutrition",
    questionSourceNote: "Original UniPrep2Go local bank (Wave 2).",
  }),
];

export const wave2MockSlugs = wave2MockExamConfigs.map((c) => c.slug);

export const WAVE2_SKIPPED_NEED_IMAGES = [
  "arrt-ct",
  "arrt-mri",
  "ardms-abd",
  "ardms-obgyn",
  "arrt-mammography",
] as const;
