import type { MockExamTaxonomy, MockVerticalId } from "./types";

type Wave3TaxonomyEntry = MockExamTaxonomy & { verticalId: MockVerticalId };

export const wave3TaxonomyEntries: Record<string, Wave3TaxonomyEntry> = {
  "az-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Arizona real estate", "AZ RE"] },
  "ga-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Georgia real estate", "GA RE"] },
  "il-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Illinois real estate", "IL RE"] },
  "oh-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Ohio real estate", "OH RE"] },
  "pa-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Pennsylvania real estate", "PA RE"] },
  "nc-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["North Carolina real estate", "NC RE"] },
  "va-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Virginia real estate", "VA RE"] },
  "wa-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Washington real estate", "WA RE"] },
  "co-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Colorado real estate", "CO RE"] },
  "nj-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["New Jersey real estate", "NJ RE"] },
  "ma-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Massachusetts real estate", "MA RE"] },
  "mi-real-estate-readiness-check": { verticalId: "real-estate", familyId: "state-re", searchAliases: ["Michigan real estate", "MI RE"] },
  "cdl-air-brakes-readiness-check": { verticalId: "transport", familyId: "cdl-endorsements", searchAliases: ["CDL air brakes", "air brake endorsement"] },
  "cdl-combination-readiness-check": { verticalId: "transport", familyId: "cdl-endorsements", searchAliases: ["CDL combination", "Class A combination"] },
  "cdl-doubles-triples-readiness-check": { verticalId: "transport", familyId: "cdl-endorsements", searchAliases: ["CDL doubles", "triples endorsement", "T endorsement"] },
  "cdl-tankers-readiness-check": { verticalId: "transport", familyId: "cdl-endorsements", searchAliases: ["CDL tanker", "N endorsement", "tank vehicles"] },
  "nclex-rn-readiness-check": { verticalId: "nursing", familyId: "rn-licensure", searchAliases: ["NCLEX-RN", "RN license exam"] },
  "medication-aide-readiness-check": { verticalId: "nursing", familyId: "med-aide", searchAliases: ["medication aide", "CMA med aide"] },
  "home-health-aide-readiness-check": { verticalId: "nursing", familyId: "hha", searchAliases: ["home health aide", "HHA exam"] },
  "rbt-behavior-technician-readiness-check": { verticalId: "allied-health", familyId: "aba", searchAliases: ["RBT", "registered behavior technician"] },
  "amt-rma-readiness-check": { verticalId: "allied-health", familyId: "aama", searchAliases: ["RMA", "AMT RMA", "registered medical assistant"] },
  "ascp-mlt-readiness-check": { verticalId: "lab", familyId: "ascp", searchAliases: ["MLT", "ASCP MLT", "medical lab technician"] },
  "aapc-ccs-readiness-check": { verticalId: "health-admin", familyId: "coding", searchAliases: ["CCS", "inpatient coding", "AHIMA CCS"] },
  "medical-scribe-readiness-check": { verticalId: "allied-health", familyId: "scribe", searchAliases: ["medical scribe", "scribe certification"] },
  "nremt-aemt-readiness-check": { verticalId: "ems", familyId: "nremt", searchAliases: ["AEMT", "NREMT AEMT", "advanced EMT"] },
  "physical-therapy-aide-readiness-check": { verticalId: "allied-health", familyId: "rehab-aide", searchAliases: ["PT aide", "physical therapy aide"] },
  "aspt-phlebotomy-readiness-check": { verticalId: "allied-health", familyId: "nha", searchAliases: ["ASPT", "phlebotomy technician"] },
  "abo-optician-readiness-check": { verticalId: "allied-health", familyId: "optician", searchAliases: ["ABO", "optician exam", "ABO-NCLE"] },
  "acsm-cpt-readiness-check": { verticalId: "fitness", familyId: "cpt", searchAliases: ["ACSM CPT", "ACSM personal trainer"] },
  "nsca-cpt-readiness-check": { verticalId: "fitness", familyId: "cpt", searchAliases: ["NSCA-CPT", "NSCA personal trainer"] },
  "precision-nutrition-l1-readiness-check": { verticalId: "fitness", familyId: "nutrition-coach", searchAliases: ["Precision Nutrition", "PN Level 1"] },
  "cscs-nsca-readiness-check": { verticalId: "fitness", familyId: "cscs", searchAliases: ["CSCS", "NSCA CSCS", "strength coach"] },
  "nail-technician-state-readiness-check": { verticalId: "beauty", familyId: "nails", searchAliases: ["nail tech exam", "manicurist license"] },
  "barber-state-readiness-check": { verticalId: "beauty", familyId: "barber", searchAliases: ["barber exam", "barber license"] },
  "aswb-bachelors-readiness-check": { verticalId: "social-work", familyId: "aswb", searchAliases: ["ASWB Bachelors", "LSW exam"] },
  "aswb-clinical-readiness-check": { verticalId: "social-work", familyId: "aswb", searchAliases: ["ASWB Clinical", "LCSW exam"] },
  "shrm-cp-readiness-check": { verticalId: "licensing", familyId: "hr", searchAliases: ["SHRM-CP", "SHRM certified professional"] },
  "phr-hrci-readiness-check": { verticalId: "licensing", familyId: "hr", searchAliases: ["PHR", "HRCI PHR"] },
  "capm-readiness-check": { verticalId: "building", familyId: "pmp", searchAliases: ["CAPM", "PMI CAPM"] },
  "six-sigma-green-belt-readiness-check": { verticalId: "building", familyId: "six-sigma", searchAliases: ["Six Sigma Green Belt", "CSSGB"] },
  "enrolled-agent-readiness-check": { verticalId: "finance", familyId: "tax", searchAliases: ["enrolled agent", "EA exam", "SEE"] },
  "series-65-readiness-check": { verticalId: "licensing", familyId: "finra", searchAliases: ["Series 65", "investment adviser exam"] },
  "series-66-readiness-check": { verticalId: "licensing", familyId: "finra", searchAliases: ["Series 66", "65+63 combo"] },
  "series-6-readiness-check": { verticalId: "licensing", familyId: "finra", searchAliases: ["Series 6", "investment company products"] },
  "praxis-core-readiness-check": { verticalId: "education", familyId: "praxis", searchAliases: ["Praxis Core", "Praxis I"] },
  "parapro-readiness-check": { verticalId: "education", familyId: "parapro", searchAliases: ["ParaPro", "paraprofessional exam"] },
  "unarmed-security-officer-readiness-check": { verticalId: "licensing", familyId: "security", searchAliases: ["security officer exam", "unarmed guard card"] },
  "alcohol-server-readiness-check": { verticalId: "licensing", familyId: "food-safety", searchAliases: ["alcohol server", "TIPS", "Responsible Beverage"] },
  "notary-public-readiness-check": { verticalId: "licensing", familyId: "notary", searchAliases: ["notary exam", "notary public"] },
  "forklift-operator-readiness-check": { verticalId: "trades", familyId: "osha", searchAliases: ["forklift certification", "PIT operator"] },
  "osha-10-general-readiness-check": { verticalId: "trades", familyId: "osha", searchAliases: ["OSHA 10", "OSHA 10 general industry"] },
  "nate-core-readiness-check": { verticalId: "trades", familyId: "hvac", searchAliases: ["NATE Core", "HVAC NATE"] },
  "servsafe-food-handler-readiness-check": { verticalId: "licensing", familyId: "food-safety", searchAliases: ["ServSafe Food Handler", "food handler card"] },
  "first-aid-cpr-readiness-check": { verticalId: "cpr", familyId: "aha", searchAliases: ["first aid practice test", "CPR first aid"] },
  "mortgage-loan-originator-readiness-check": { verticalId: "real-estate", familyId: "mlo", searchAliases: ["SAFE MLO", "NMLS exam", "mortgage loan originator"] },
  "wastewater-operator-1-readiness-check": { verticalId: "trades", familyId: "water", searchAliases: ["wastewater operator", "WW operator exam"] },
  "real-estate-appraiser-readiness-check": { verticalId: "real-estate", familyId: "appraisal", searchAliases: ["appraiser exam", "AQB national"] },
  "funeral-service-arts-readiness-check": { verticalId: "licensing", familyId: "funeral", searchAliases: ["NBE Arts", "funeral director exam"] },
  "nabcep-associate-readiness-check": { verticalId: "trades", familyId: "solar", searchAliases: ["NABCEP Associate", "PV Associate"] },
  "veterinary-assistant-readiness-check": { verticalId: "veterinary", familyId: "vet-assistant", searchAliases: ["veterinary assistant", "AVA"] },
};
