from __future__ import annotations

from ._common import pack


def build() -> list[dict]:
    e = "aama-cma-readiness-check"
    qs: list[dict] = []

    qs += pack(e, "clinical", [
        ("Which site is generally preferred for an adult intramuscular vaccine injection when volume is appropriate?",
         {"a": "Deltoid muscle with proper landmarking", "b": "Dorsogluteal site without landmarks", "c": "Subcutaneous abdomen only", "d": "Antecubital vein"},
         "a", "The deltoid is preferred for many adult IM vaccines when volume fits; landmarking avoids nerves and vessels.",
         {"b": "Dorsogluteal injections without landmarks risk sciatic injury and are often avoided.", "c": "Abdomen is a common SQ site, not the default IM vaccine site.", "d": "IV is a different route requiring specific authorization."}, "easy"),
        ("When measuring an adult oral temperature with an electronic probe, the medical assistant should:",
         {"a": "Place the probe on the forehead without contact", "b": "Place the probe in the posterior sublingual pocket and wait for the signal", "c": "Insert the probe into the ear canal for oral readings", "d": "Leave the probe in ice water first"},
         "b", "Oral electronic thermometers read from the sublingual pocket; tympanic and temporal devices use different techniques.",
         {"a": "Forehead readings use temporal methods, not oral probes.", "c": "Ear probes are tympanic, not oral.", "d": "Ice water would falsify the reading."}, "easy"),
        ("Which change most urgently suggests orthostatic hypotension when a patient stands?",
         {"a": "Slight temperature rise after walking", "b": "Significant drop in blood pressure with dizziness on standing", "c": "Unchanged pulse and BP with no symptoms", "d": "Mild increase in respiratory rate only"},
         "b", "Orthostatic hypotension is a drop in BP (often with dizziness/syncope risk) on standing; report and assist safety.",
         {"a": "Temperature change is not the hallmark of orthostasis.", "c": "No change with no symptoms does not indicate orthostasis.", "d": "Isolated mild tachypnea is nonspecific."}, "medium"),
        ("Before performing venipuncture, the CMA should first:",
         {"a": "Apply the tourniquet for 5 minutes", "b": "Identify the patient using two identifiers and verify the order", "c": "Slap the arm vigorously to raise veins", "d": "Recap used needles for reuse"},
         "b", "Patient identification with two identifiers and order verification are foundational safety steps before any invasive procedure.",
         {"a": "Prolonged tourniquet time can alter results and cause injury.", "c": "Slapping is unprofessional and can injure tissue.", "d": "Needles are single-use; never reuse or improperly recap."}, "easy"),
        ("A patient reports a latex allergy. When preparing for a procedure that requires gloves, the CMA should:",
         {"a": "Use powdered latex gloves carefully", "b": "Use non-latex gloves per facility protocol", "c": "Skip gloves if hands are washed", "d": "Use latex and rinse afterward"},
         "b", "Known latex allergy requires non-latex products to prevent allergic reactions.",
         {"a": "Powdered latex increases exposure risk.", "c": "Gloves are still required for BBP protection when indicated.", "d": "Rinsing does not make latex safe for allergic patients."}, "easy"),
        ("Which action is correct when obtaining a capillary blood glucose sample?",
         {"a": "Milk the finger vigorously from tip to base", "b": "Wipe away the first drop and use a subsequent drop per device instructions", "c": "Use the thumb as the preferred adult site", "d": "Reuse the lancet for the same patient later that day"},
         "b", "Many protocols discard the first drop to reduce tissue fluid contamination; follow meter instructions and never reuse lancets.",
         {"a": "Excessive milking can dilute the sample with tissue fluid.", "c": "Sides of the fingertip are preferred; thumbs are less common.", "d": "Lancets are single-use."}, "medium"),
        ("During a 12-lead ECG, the V4 electrode is placed at the:",
         {"a": "4th intercostal space, right sternal border", "b": "5th intercostal space, midclavicular line", "c": "2nd intercostal space, left sternal border", "d": "Midaxillary line at the umbilicus"},
         "b", "V4 is at the 5th ICS midclavicular line; correct placement is essential for interpretable tracings.",
         {"a": "That describes V1.", "c": "That is not a standard V4 landmark.", "d": "V6 is midaxillary at the V4–V5 level, not at the umbilicus."}, "medium"),
        ("A patient begins to feel faint during blood draw. The safest immediate action is to:",
         {"a": "Continue filling remaining tubes quickly", "b": "Remove the needle, apply pressure, lower the head, and call for help as needed", "c": "Have the patient stand and walk", "d": "Leave the patient alone to rest"},
         "b", "Stop the procedure safely, protect the patient from injury, and support circulation; do not leave a syncope-risk patient alone.",
         {"a": "Continuing risks injury if the patient loses consciousness.", "c": "Standing increases fall risk.", "d": "Unsupervised rest is unsafe during vasovagal episodes."}, "medium"),
        ("Which statement about sterile field maintenance is correct?",
         {"a": "Turning your back to a sterile field is acceptable if you return quickly", "b": "Items below waist level are considered contaminated", "c": "Talking over a sterile field does not increase contamination risk", "d": "Wet sterile packages remain sterile indefinitely"},
         "b", "Sterile technique treats items below the waist (and out of sight/wet packages) as contaminated.",
         {"a": "Turning away breaks observation of the field.", "c": "Talking/coughing can contaminate the field.", "d": "Moisture can wick contamination through packaging."}, "medium"),
        ("When irrigating an adult ear with cerumen, the CMA should generally:",
         {"a": "Aim the stream directly at the tympanic membrane at high pressure", "b": "Use body-temperature solution and aim along the canal wall per provider order/protocol", "c": "Use ice-cold water to dissolve wax faster", "d": "Proceed despite recent ear surgery without checking orders"},
         "b", "Warm (body-temperature) irrigation aimed along the canal reduces dizziness/injury risk; contraindications must be screened.",
         {"a": "High-pressure direct TM irrigation can cause injury.", "c": "Cold water can provoke vertigo.", "d": "Recent surgery/perforation are common contraindications."}, "hard"),
        ("Pulse oximetry readings may be falsely low when the patient has:",
         {"a": "Warm well-perfused fingers", "b": "Nail polish or poor peripheral perfusion", "c": "Normal hemoglobin and room air", "d": "A correctly sized sensor on a warm ear lobe"},
         "b", "Poor perfusion, cold extremities, motion, and dark nail polish can impair SpO2 accuracy.",
         {"a": "Good perfusion improves accuracy.", "c": "Those conditions support more reliable readings.", "d": "Proper sensor placement improves accuracy."}, "easy"),
        ("Which is the correct sequence for donning PPE when contact/droplet precautions are ordered (typical clinic sequence)?",
         {"a": "Gloves, then gown, then mask", "b": "Gown, mask/respirator as indicated, eye protection if needed, then gloves", "c": "Mask only, skip gloves for brief contact", "d": "Gloves first, then remove gown over gloved hands"},
         "b", "Standard sequences put gown and respiratory/eye protection on before gloves so gloves go on last over gown cuffs.",
         {"a": "Gloves should be last so they cover gown cuffs.", "c": "Gloves are required for contact with body fluids/contaminated surfaces.", "d": "That sequence is incorrect for donning."}, "medium"),
        ("A wound culture swab should be collected from:",
         {"a": "Intact surrounding skin only", "b": "The deepest cleanest portion of the wound after removing surface debris per protocol", "c": "Dried exudate on the dressing alone", "d": "Any random surface without cleaning"},
         "b", "Culture accuracy improves when surface contaminants are cleared and the active wound bed is sampled per protocol.",
         {"a": "Intact skin does not represent wound pathogens.", "c": "Dressings may not reflect current wound flora.", "d": "Unprepared sampling increases contamination."}, "hard"),
        ("When assisting with a Papanicolaou (Pap) specimen, the CMA's role typically includes:",
         {"a": "Interpreting cytology results for the patient", "b": "Labeling specimens correctly and preparing the patient per protocol", "c": "Prescribing follow-up medications", "d": "Discarding the requisition to protect privacy"},
         "b", "Assistants prepare patients, assist the provider, and ensure accurate labeling/requisitions; diagnosis and prescribing are outside MA scope.",
         {"a": "Result interpretation is a provider responsibility.", "c": "Prescribing is not within MA scope.", "d": "Requisitions are required for proper processing."}, "easy"),
        ("Which intramuscular injection angle is generally used for a typical adult IM injection?",
         {"a": "10–15 degrees", "b": "45 degrees only", "c": "90 degrees", "d": "180 degrees parallel to skin"},
         "c", "IM injections are typically given at 90 degrees into muscle; SQ is often ~45–90 depending on technique/needle length.",
         {"a": "10–15 degrees is intradermal.", "b": "45 degrees is more typical of some SQ techniques.", "d": "Parallel injection is not a standard IM angle."}, "easy"),
    ])

    qs += pack(e, "anatomy-pharm", [
        ("Which organ system is primarily responsible for gas exchange?",
         {"a": "Digestive", "b": "Respiratory", "c": "Integumentary", "d": "Reproductive"},
         "b", "The respiratory system exchanges oxygen and carbon dioxide in the lungs.",
         {"a": "Digestive absorbs nutrients.", "c": "Skin protects and regulates temperature.", "d": "Reproductive supports reproduction."}, "easy"),
        ("The sinoatrial (SA) node is located in the:",
         {"a": "Left ventricle apex", "b": "Right atrium", "c": "Pulmonary artery", "d": "Aortic arch only"},
         "b", "The SA node in the right atrium is the heart's primary pacemaker.",
         {"a": "The apex is ventricular myocardium, not the SA node.", "c": "The pulmonary artery carries blood to the lungs.", "d": "The aortic arch is not the SA node location."}, "easy"),
        ("Which drug class is commonly used first-line for many patients with hypertension?",
         {"a": "Antihistamines", "b": "ACE inhibitors, ARBs, thiazide diuretics, or calcium channel blockers (per guidelines/provider)", "c": "Antifungals", "d": "Topical anesthetics"},
         "b", "Common first-line antihypertensives include ACEI/ARB, thiazides, and CCBs depending on patient factors.",
         {"a": "Antihistamines treat allergy symptoms.", "c": "Antifungals treat fungal infections.", "d": "Topical anesthetics numb skin locally."}, "medium"),
        ("Nitroglycerin for angina is commonly administered:",
         {"a": "As an intramuscular injection into the deltoid only", "b": "Sublingually for rapid absorption when ordered", "c": "Into the ear canal", "d": "As a rectal suppository for all chest pain"},
         "b", "Sublingual nitroglycerin is used for rapid transmucosal absorption in angina protocols under provider direction.",
         {"a": "IM is not the usual acute angina route for NTG.", "c": "Otic route is for ear medications.", "d": "Rectal is not the standard acute angina route."}, "medium"),
        ("Which blood vessel carries oxygenated blood from the lungs to the left atrium?",
         {"a": "Pulmonary artery", "b": "Pulmonary veins", "c": "Superior vena cava", "d": "Coronary sinus only"},
         "b", "Pulmonary veins return oxygenated blood to the left atrium.",
         {"a": "Pulmonary arteries carry deoxygenated blood to the lungs.", "c": "SVC returns systemic venous blood to the right atrium.", "d": "Coronary sinus drains cardiac venous blood."}, "easy"),
        ("A patient taking warfarin should be educated that which substance can increase bleeding risk when interacting with therapy?",
         {"a": "Consistent leafy greens alone always raise INR immediately", "b": "Certain antibiotics and NSAIDs can increase bleeding risk; report changes to the provider", "c": "Acetaminophen never interacts with any drug", "d": "All vitamins are contraindicated forever"},
         "b", "Warfarin has many interactions; antibiotics and NSAIDs can raise bleeding risk. Diet vitamin K consistency also matters.",
         {"a": "Vitamin K intake should be consistent; sudden large changes matter more than 'always raise INR immediately.'", "c": "High-dose acetaminophen can affect INR in some cases; 'never' is unsafe.", "d": "Not all vitamins are forbidden; management is individualized."}, "hard"),
        ("Insulin is primarily produced by the:",
         {"a": "Adrenal medulla", "b": "Pancreatic beta cells", "c": "Thyroid follicles", "d": "Posterior pituitary"},
         "b", "Beta cells of the islets of Langerhans produce insulin.",
         {"a": "Adrenal medulla produces catecholamines.", "c": "Thyroid produces T3/T4 and calcitonin.", "d": "Posterior pituitary releases ADH and oxytocin."}, "easy"),
        ("Which schedule classification indicates the highest abuse potential among controlled substances that still have accepted medical use in the U.S.?",
         {"a": "Schedule V", "b": "Schedule IV", "c": "Schedule II", "d": "OTC vitamins"},
         "c", "Schedule II drugs have high abuse potential with accepted medical use (e.g., many opioids, stimulants).",
         {"a": "Schedule V has lower relative abuse potential.", "b": "Schedule IV is lower than II.", "d": "Vitamins are not scheduled controlled substances."}, "medium"),
        ("The anatomical term 'proximal' means:",
         {"a": "Farther from the trunk or point of origin", "b": "Closer to the trunk or point of origin", "c": "Toward the midline only", "d": "Toward the feet only"},
         "b", "Proximal means nearer to the trunk/origin; distal means farther.",
         {"a": "That defines distal.", "c": "Toward midline is medial.", "d": "Toward the feet is inferior/caudal."}, "easy"),
        ("Albuterol is classified primarily as a:",
         {"a": "Beta-2 agonist bronchodilator", "b": "Loop diuretic", "c": "Anticoagulant", "d": "Proton pump inhibitor"},
         "a", "Albuterol relaxes bronchial smooth muscle via beta-2 agonism for asthma/COPD rescue use.",
         {"b": "Loop diuretics increase urine output (e.g., furosemide).", "c": "Anticoagulants reduce clotting.", "d": "PPIs reduce gastric acid."}, "medium"),
        ("Which electrolyte imbalance is classically associated with peaked T waves on ECG?",
         {"a": "Hypokalemia", "b": "Hyperkalemia", "c": "Hyponatremia", "d": "Hypocalcemia only"},
         "b", "Hyperkalemia can cause peaked T waves and dangerous arrhythmias.",
         {"a": "Hypokalemia more often causes U waves/flattened T waves.", "c": "Sodium disorders have different presentations.", "d": "Hypocalcemia affects QT interval differently."}, "hard"),
        ("The gallbladder's primary function is to:",
         {"a": "Produce insulin", "b": "Store and concentrate bile", "c": "Filter blood urea", "d": "Pump systemic blood"},
         "b", "The gallbladder stores and concentrates bile produced by the liver.",
         {"a": "Insulin is from the pancreas.", "c": "Kidneys filter urea.", "d": "The heart pumps blood."}, "easy"),
        ("Which route provides the slowest onset for most medications compared with IV?",
         {"a": "Intravenous", "b": "Intramuscular", "c": "Oral (enteral)", "d": "Inhalation of a rapid-acting bronchodilator"},
         "c", "Oral absorption is generally slower than parenteral/IV routes due to GI absorption and first-pass effects.",
         {"a": "IV has the fastest onset.", "b": "IM is faster than typical oral.", "d": "Inhaled albuterol acts quickly locally/systemically for airway effect."}, "medium"),
        ("Epinephrine auto-injectors for anaphylaxis are typically given:",
         {"a": "Subcutaneously into the abdomen only", "b": "Intramuscularly into the mid-outer thigh", "c": "Intravenously by the patient at home", "d": "Orally as a chewable tablet"},
         "b", "Epinephrine auto-injectors are designed for IM injection into the anterolateral thigh.",
         {"a": "IM thigh is preferred over SQ abdomen for auto-injectors.", "c": "Patients do not self-administer IV epinephrine at home.", "d": "Oral epinephrine is not used for anaphylaxis rescue."}, "medium"),
        ("Which cranial nerve is tested when asking a patient to shrug the shoulders against resistance?",
         {"a": "CN I (olfactory)", "b": "CN XI (accessory)", "c": "CN II (optic)", "d": "CN VIII (vestibulocochlear)"},
         "b", "CN XI innervates trapezius/sternocleidomastoid; shoulder shrug tests accessory nerve function.",
         {"a": "CN I is smell.", "c": "CN II is vision.", "d": "CN VIII is hearing/balance."}, "hard"),
    ])

    qs += pack(e, "admin", [
        ("Which is the best example of using two patient identifiers?",
         {"a": "Room number and bed location only", "b": "Full name and date of birth", "c": "Insurance company name alone", "d": "Physician's last name"},
         "b", "Name plus DOB (or MRN) are standard identifiers; room number alone is unreliable.",
         {"a": "Location can change and is not a patient identifier.", "c": "Payer name does not uniquely identify the patient.", "d": "Provider name identifies the clinician, not the patient."}, "easy"),
        ("In ICD-10-CM coding, codes primarily describe:",
         {"a": "Physician work RVUs only", "b": "Diagnoses and reasons for encounter", "c": "Supply inventory SKUs", "d": "Employee payroll categories"},
         "b", "ICD-10-CM is the diagnosis coding system used to report conditions and encounter reasons.",
         {"a": "RVUs relate to payment valuation, not ICD purpose.", "c": "Inventory is not ICD.", "d": "Payroll is unrelated."}, "easy"),
        ("CPT codes are used primarily to report:",
         {"a": "Patient race and ethnicity", "b": "Procedures and services performed", "c": "Hospital room colors", "d": "Lab reference ranges"},
         "b", "CPT reports procedures/services for billing and documentation linkage.",
         {"a": "Demographics are not CPT.", "c": "Facility aesthetics are unrelated.", "d": "Reference ranges are lab data."}, "easy"),
        ("When scheduling a patient who needs a fasting lipid panel, the CMA should:",
         {"a": "Instruct overnight fasting per protocol and confirm instructions", "b": "Tell the patient to eat a large breakfast before the draw", "c": "Skip preparation instructions to save time", "d": "Schedule immediately after a holiday meal"},
         "a", "Fasting labs require clear preparation instructions to avoid invalid results and repeat visits.",
         {"b": "Food can alter lipid results.", "c": "Omitting prep causes errors.", "d": "Post-meal timing may invalidate fasting requirements."}, "easy"),
        ("A claim is denied as 'not medically necessary.' The most appropriate first administrative step is to:",
         {"a": "Ignore the denial", "b": "Review documentation and payer policy, then follow appeal/correction procedures", "c": "Bill the patient double immediately", "d": "Change the diagnosis randomly to get paid"},
         "b", "Denials require review of documentation/medical necessity criteria and proper appeal or correction workflows.",
         {"a": "Ignoring loses revenue and care continuity.", "c": "Double billing is inappropriate.", "d": "Falsifying diagnoses is fraud."}, "medium"),
        ("Which document authorizes release of protected health information to a third party?",
         {"a": "Blank sticky note", "b": "Valid patient authorization meeting HIPAA requirements", "c": "Verbal hallway rumor", "d": "Insurance card photocopy alone without authorization when not otherwise permitted"},
         "b", "HIPAA requires a valid authorization (or another permitted use/disclosure) before releasing PHI to many third parties.",
         {"a": "Informal notes are insufficient.", "c": "Rumors are not authorization.", "d": "Having a card does not equal authorization for all disclosures."}, "medium"),
        ("The advance beneficiary notice (ABN) is used in Medicare contexts to:",
         {"a": "Guarantee payment for all services", "b": "Notify a beneficiary that Medicare may not pay for a service and that they may be financially responsible", "c": "Replace informed consent for surgery", "d": "Enroll providers in Medicaid"},
         "b", "ABNs inform Medicare beneficiaries about potential noncoverage and financial responsibility before certain services.",
         {"a": "ABN does not guarantee payment.", "c": "Consent is separate.", "d": "ABN is not Medicaid enrollment."}, "hard"),
        ("Which filing system organizes charts alphabetically by last name?",
         {"a": "Numeric terminal digit only", "b": "Alphabetic filing", "c": "Color coding by birthday month alone", "d": "Random stack filing"},
         "b", "Alphabetic systems file by patient name; numeric systems use numbers.",
         {"a": "Terminal digit is numeric.", "c": "Color coding may assist but is not alphabetic filing itself.", "d": "Random stacks are not a system."}, "easy"),
        ("When verifying insurance eligibility, the CMA should typically confirm:",
         {"a": "Coverage active dates, plan type, and referral/authorization needs", "b": "Only the patient's favorite pharmacy", "c": "The provider's personal email password", "d": "Whether the waiting room TV works"},
         "a", "Eligibility checks focus on active coverage, benefits, and authorization/referral requirements.",
         {"b": "Pharmacy preference is secondary.", "c": "Passwords are unrelated and confidential.", "d": "Facility amenities are unrelated."}, "easy"),
        ("A superbill (encounter form) is primarily used to:",
         {"a": "Document sterile technique steps", "b": "Capture diagnoses and services for billing from the visit", "c": "Replace the entire EHR forever", "d": "Serve as a prescription pad for controlled substances"},
         "b", "Superbills list common diagnoses/procedures to support charge capture for the encounter.",
         {"a": "Sterile technique is clinical documentation.", "c": "It supplements billing capture, not replaces the EHR.", "d": "It is not a controlled-substance prescription form."}, "medium"),
        ("Which telephone triage action is appropriate for a CMA?",
         {"a": "Diagnose chest pain as anxiety and advise waiting a week", "b": "Follow written protocols and escalate urgent symptoms to a licensed clinician", "c": "Prescribe antibiotics over the phone", "d": "Tell all callers to go to the ER regardless of symptoms"},
         "b", "MAs use approved protocols and escalate; they do not independently diagnose or prescribe.",
         {"a": "Diagnosing and delaying care for possible cardiac symptoms is unsafe.", "c": "Prescribing is outside MA scope.", "d": "Blanket ER advice is not protocol-based triage."}, "medium"),
        ("Accounts receivable aging reports help the office:",
         {"a": "Track unpaid claims/balances by how long they have been outstanding", "b": "Measure patient height and weight", "c": "Schedule surgeries", "d": "Calibrate ECG machines"},
         "a", "AR aging categorizes outstanding balances by time buckets to prioritize follow-up.",
         {"b": "Vitals are clinical.", "c": "Scheduling is a different function.", "d": "Calibration is clinical equipment maintenance."}, "medium"),
        ("Which is the most appropriate way to correct a paper chart error?",
         {"a": "Erase completely with white-out", "b": "Draw a single line through the error, initial, date, and write the correction", "c": "Rip out the page", "d": "Write over the words until unreadable"},
         "b", "Legal medical records require transparent corrections: single line, initials/date, no obliteration.",
         {"a": "White-out obscures the original entry.", "c": "Removing pages destroys the record.", "d": "Overwriting makes the record illegible/suspicious."}, "easy"),
        ("Prior authorization is typically required when:",
         {"a": "A payer requires approval before covering certain services or medications", "b": "A patient pays cash for all OTC items", "c": "Staff buy office supplies", "d": "A provider takes lunch"},
         "a", "Prior auth is payer approval before selected services/drugs are covered.",
         {"b": "Cash OTC purchases do not need payer prior auth.", "c": "Office purchasing is internal.", "d": "Breaks are unrelated."}, "easy"),
        ("Which statement about referral management is correct?",
         {"a": "Referrals are never needed in managed care", "b": "Many HMO plans require referrals/authorizations before specialty care", "c": "Referrals replace medical records", "d": "Patients can always self-refer under every plan without review"},
         "b", "Managed care plans often require referrals or authorizations for specialty services.",
         {"a": "Many plans do require them.", "c": "Referrals authorize care pathways; they do not replace records.", "d": "Plan rules vary; many restrict self-referral."}, "medium"),
    ])

    qs += pack(e, "law-ethics", [
        ("HIPAA's Privacy Rule primarily protects:",
         {"a": "Clinic parking spaces", "b": "Protected health information (PHI)", "c": "Vendor lunch menus", "d": "Public weather data"},
         "b", "HIPAA Privacy Rule governs use and disclosure of PHI.",
         {"a": "Parking is unrelated.", "c": "Menus are not PHI.", "d": "Weather is public information."}, "easy"),
        ("Informed consent requires that the patient:",
         {"a": "Be told risks, benefits, and alternatives in understandable terms and agree voluntarily", "b": "Sign any form without explanation", "c": "Be coerced if they hesitate", "d": "Receive no opportunity for questions"},
         "a", "Informed consent is voluntary agreement after adequate disclosure and opportunity for questions.",
         {"b": "A signature without understanding is inadequate.", "c": "Coercion invalidates consent.", "d": "Questions are part of the process."}, "easy"),
        ("Which situation is reportable as suspected child abuse in most U.S. jurisdictions for mandated reporters?",
         {"a": "A child with unexplained patterned bruises and inconsistent history", "b": "A child who prefers vegetables", "c": "A child late to one appointment without other concerns", "d": "A child who dislikes blood draws"},
         "a", "Mandated reporters must report reasonable suspicion of abuse/neglect; patterned injuries with inconsistent history are classic red flags.",
         {"b": "Food preference is not abuse.", "c": "A single late visit alone is not abuse.", "d": "Fear of procedures is common."}, "medium"),
        ("OSHA Bloodborne Pathogens Standard requires employers to:",
         {"a": "Provide training, PPE, and an exposure control plan", "b": "Ban all hand hygiene", "c": "Require staff to pay for all PPE personally", "d": "Ignore needle-stick injuries"},
         "a", "OSHA BBP standards mandate exposure control plans, training, PPE, and post-exposure processes.",
         {"b": "Hand hygiene is required.", "c": "Employers must provide necessary PPE.", "d": "Exposures must be evaluated and followed up."}, "easy"),
        ("A medical assistant may not:",
         {"a": "Take vital signs under supervision/protocol", "b": "Independently diagnose disease and prescribe medication", "c": "Schedule appointments", "d": "Perform CLIA-waived tests if trained and authorized"},
         "b", "Diagnosis and prescribing are licensed-provider functions outside MA scope.",
         {"a": "Vitals are common MA duties.", "c": "Scheduling is administrative within role.", "d": "CLIA-waived testing is often within trained MA scope."}, "easy"),
        ("Which best describes 'negligence' in a healthcare malpractice context?",
         {"a": "Failure to meet the standard of care causing harm", "b": "Any patient dissatisfaction", "c": "A successful treatment outcome", "d": "Following evidence-based protocols perfectly"},
         "a", "Negligence is breach of duty (standard of care) that proximately causes damages.",
         {"b": "Dissatisfaction alone is not negligence.", "c": "Good outcomes are not negligence.", "d": "Meeting standards helps prevent negligence claims."}, "medium"),
        ("A living will typically:",
         {"a": "Assigns a healthcare proxy only", "b": "States wishes about life-sustaining treatment if the patient cannot communicate", "c": "Transfers real estate ownership", "d": "Authorizes staff to ignore DNR tattoos only"},
         "b", "Living wills document preferences for end-of-life/life-sustaining care when the patient lacks capacity.",
         {"a": "Healthcare proxy/POA is a separate directive (though often paired).", "c": "Property transfer is estate planning, not a living will.", "d": "Facility policies govern DNR orders; tattoos alone are unreliable."}, "medium"),
        ("Which action violates patient confidentiality?",
         {"a": "Discussing a case with the care team for treatment", "b": "Posting a patient's diagnosis on social media", "c": "Filing records securely", "d": "Verifying identity before releasing results"},
         "b", "Public disclosure of PHI on social media is a confidentiality/HIPAA breach.",
         {"a": "Treatment-related sharing with the care team is permitted.", "c": "Secure filing protects privacy.", "d": "Identity verification protects against wrongful disclosure."}, "easy"),
        ("CLIA categorizes tests; a CLIA-waived test is generally:",
         {"a": "So complex that only pathologists may perform it", "b": "Simple with low risk of erroneous results when directions are followed", "c": "Illegal in physician offices", "d": "Always requiring a full microbiology lab"},
         "b", "Waived tests are simple, low-risk methods cleared for waived status when manufacturer instructions are followed.",
         {"a": "High-complexity tests need more stringent personnel standards.", "c": "Many waived tests are done in offices.", "d": "Micro labs perform complex testing; not all waived tests need that."}, "medium"),
        ("Which is an example of battery in clinical care?",
         {"a": "Performing a procedure after valid informed consent", "b": "Touching or treating a patient without consent", "c": "Documenting vital signs accurately", "d": "Offering a chaperone"},
         "b", "Battery is intentional unauthorized touching; consent is key.",
         {"a": "Consented care is not battery.", "c": "Accurate documentation is appropriate.", "d": "Chaperones support safety/comfort."}, "medium"),
        ("Standard Precautions assume that:",
         {"a": "Only visibly ill patients pose risk", "b": "Blood and certain body fluids of all patients may be infectious", "c": "Gloves are never needed", "d": "Hand hygiene is optional after glove removal"},
         "b", "Standard Precautions treat all patients' blood/body fluids as potentially infectious.",
         {"a": "Asymptomatic patients can transmit infection.", "c": "PPE is used based on anticipated exposure.", "d": "Hand hygiene is required after glove removal."}, "easy"),
        ("A 'Good Samaritan' statute typically protects:",
         {"a": "Reckless intentional harm", "b": "Reasonable emergency aid given in good faith outside a duty-to-treat setting (varies by state)", "c": "Billing fraud", "d": "Falsifying medical records"},
         "b", "Good Samaritan laws generally shield good-faith emergency helpers acting reasonably; they do not cover intentional misconduct or fraud.",
         {"a": "Recklessness/intentional harm is not protected.", "c": "Fraud is criminal.", "d": "Falsification is illegal."}, "hard"),
        ("Which statement about minors and consent is generally true in the U.S.?",
         {"a": "Parents/guardians usually consent for minors, with specific exceptions (e.g., certain reproductive/mental health laws varying by state)", "b": "Minors always consent for all surgeries alone in every state", "c": "Consent is never needed for minors", "d": "Teachers always consent for school-age children in clinics"},
         "a", "Parental/guardian consent is usual, but state laws create exceptions for emancipated minors and certain sensitive services.",
         {"b": "Not universally true for all care.", "c": "Consent is still required from an authorized person.", "d": "Teachers are not default healthcare decision-makers."}, "hard"),
        ("An incident report should be:",
         {"a": "Filed objectively, promptly, and per facility policy without blaming language in the medical record narrative", "b": "Posted in the waiting room", "c": "Destroyed immediately", "d": "Used as a public press release"},
         "a", "Incident reports document facts for risk management; they are handled per policy and are not public notices.",
         {"b": "Public posting breaches privacy.", "c": "Destruction may violate policy/law.", "d": "Press release is inappropriate."}, "medium"),
        ("Which best reflects ethical principles of autonomy?",
         {"a": "Forcing treatment despite informed refusal when the patient has capacity", "b": "Respecting a capacitated patient's informed decisions about care", "c": "Hiding risks to improve compliance", "d": "Making decisions solely to maximize clinic revenue"},
         "b", "Autonomy respects informed patients' rights to accept or refuse care.",
         {"a": "Forcing care against capacitated refusal violates autonomy.", "c": "Withholding risks undermines informed consent.", "d": "Revenue alone is not an ethical care principle."}, "easy"),
    ])
    return qs
