from __future__ import annotations

from ._common import pack


def build() -> list[dict]:
    e = "ascp-mls-readiness-check"
    qs: list[dict] = []

    qs += pack(e, "blood-bank", [
        ("Forward typing determines:",
         {"a": "Antibodies in serum only", "b": "ABO antigens on red cells using anti-A and anti-B reagents", "c": "Rh genotype by DNA only", "d": "Platelet count"},
         "b", "Forward (cell) typing detects A/B antigens on patient RBCs.",
         {"a": "That is reverse typing.", "c": "Serology types phenotype primarily.", "d": "Hematology test."}, "easy"),
        ("Reverse typing uses:",
         {"a": "Patient red cells + anti-A/B", "b": "Patient serum/plasma + A1 and B reagent cells", "c": "Only saline without cells", "d": "Anti-D only"},
         "b", "Reverse typing confirms ABO by detecting expected isoagglutinins.",
         {"a": "Forward typing.", "c": "Needs reagent cells.", "d": "Rh typing uses anti-D."}, "easy"),
        ("The Rh(D) typing discrepancy most concerning for a woman of childbearing potential is:",
         {"a": "Clear-cut D-positive", "b": "Weak D / discrepant D that may require further testing per policy", "c": "ABO identical results", "d": "Negative antibody screen with known history of no transfusion"},
         "b", "Weak D interpretation affects RhIG and transfusion decisions; follow current AABB/lab policy.",
         {"a": "Straightforward.", "c": "Expected consistency.", "d": "Less urgent than D discrepancy."}, "medium"),
        ("An antibody screen detects:",
         {"a": "Unexpected RBC antibodies using screening cells", "b": "Only ABO antibodies", "c": "HIV antigen exclusively", "d": "Serum glucose"},
         "a", "Antibody screens use O screening cells to detect alloantibodies clinically significant for transfusion.",
         {"b": "ABO is typed separately.", "c": "Infectious disease testing differs.", "d": "Chemistry."}, "easy"),
        ("The antiglobulin (AHG) phase is critical because:",
         {"a": "It detects IgG antibodies that may not agglutinate in saline", "b": "It measures hemoglobin directly", "c": "It replaces forward typing", "d": "It sterilizes blood units"},
         "a", "AHG bridges IgG-sensitized RBCs for visible agglutination (IAT).",
         {"b": "Hematology.", "c": "ABO typing separate.", "d": "Not sterilization."}, "medium"),
        ("A major crossmatch primarily tests:",
         {"a": "Donor serum vs patient cells", "b": "Patient serum/plasma vs donor red cells", "c": "Patient cells vs patient serum only", "d": "Platelet compatibility only"},
         "b", "Major XM: recipient antibodies against donor RBCs.",
         {"a": "Minor XM (less used routinely now).", "c": "Autocontrol.", "d": "Platelets different."}, "easy"),
        ("Which antibody is most associated with severe hemolytic disease of the fetus/newborn historically?",
         {"a": "Anti-D", "b": "Anti-Leb", "c": "Anti-P1 that is cold and clinically insignificant always", "d": "Anti-M always clinically insignificant without exception"},
         "a", "Anti-D is the classic cause of severe HDFN; RhIG prevents alloimmunization.",
         {"b": "Lewis usually not clinically significant for HDN.", "c": "Many cold antibodies insignificant.", "d": "Most anti-M insignificant but not absolute framing for this stem."}, "medium"),
        ("Fresh frozen plasma (FFP) is indicated primarily to:",
         {"a": "Raise hemoglobin in anemia without coagulopathy", "b": "Replace multiple clotting factors in coagulopathy when indicated", "c": "Treat iron deficiency alone", "d": "Provide platelets exclusively"},
         "b", "FFP provides plasma coagulation factors; not a first-line O2-carrying product.",
         {"a": "RBCs treat anemia.", "c": "Iron therapy/RBCs as indicated.", "d": "Platelet units for thrombocytopenia."}, "medium"),
        ("A unit labeled CMV-safe for at-risk neonates is often:",
         {"a": "Leukoreduced and/or CMV-seronegative per policy", "b": "Never irradiated", "c": "Always whole blood only", "d": "Stored at 37°C"},
         "a", "Leukoreduction/CMV-seronegative strategies reduce CMV transmission risk.",
         {"b": "Irradiation prevents TA-GVHD in selected patients.", "c": "Components vary.", "d": "RBCs stored refrigerated."}, "hard"),
        ("In ABO discrepancy with weaker-than-expected reverse reactions in elderly patients, consider:",
         {"a": "Hypogammaglobulinemia / weak isoagglutinins", "b": "That reverse typing is never needed", "c": "Automatic group AB without testing", "d": "Ignoring all discrepancies"},
         "a", "Weak reverse reactions can reflect low antibody titers; resolve before transfusion.",
         {"b": "Reverse typing is standard for confirmation.", "c": "Unsafe assumption.", "d": "Must resolve."}, "hard"),
        ("Rh immune globulin (RhIG) is given to Rh-negative mothers to:",
         {"a": "Prevent formation of anti-D after exposure to D-positive RBCs", "b": "Treat already formed high-titer anti-D as the sole therapy always", "c": "Convert Rh-negative RBCs to Rh-positive", "d": "Replace FFP"},
         "a", "RhIG suppresses anti-D alloimmunization when indicated (antenatal/postpartum/etc.).",
         {"b": "Does not erase established alloimmunization as sole concept.", "c": "Cannot change phenotype.", "d": "Different product."}, "easy"),
        ("A positive DAT (direct antiglobulin test) indicates:",
         {"a": "In vivo coating of RBCs with IgG and/or complement", "b": "Always a laboratory labeling error only", "c": "Normal finding in all healthy donors", "d": "Elevated serum sodium"},
         "a", "DAT detects immunoglobulin/complement already bound to patient RBCs.",
         {"b": "May be true immune hemolysis.", "c": "Usually negative in healthy people.", "d": "Chemistry."}, "medium"),
        ("Emergency uncrossmatched blood for a bleeding unknown patient is typically:",
         {"a": "Group AB plasma and AB RBCs always first", "b": "Group O RBCs (often O-negative for women of childbearing potential per policy)", "c": "Any random unit without documentation", "d": "Platelets only"},
         "b", "O RBCs are universal donor red cells in emergencies; Rh choice follows policy/risk.",
         {"a": "AB plasma is universal plasma; RBCs differ.", "c": "Traceability required.", "d": "Not for RBC oxygen delivery."}, "medium"),
        ("Antibody identification panel interpretation requires:",
         {"a": "Ignoring dosage and phase reactions", "b": "Ruling out antibodies using negative reactions and considering phase, dosage, and patient history", "c": "Selecting the first antibody listed alphabetically", "d": "Never performing an autocontrol"},
         "b", "Systematic rule-outs and clinical correlation identify alloantibodies.",
         {"a": "Dosage/phase matter.", "c": "Not a method.", "d": "Autocontrol helps detect autoantibodies."}, "hard"),
        ("Leukoreduction of RBC units primarily reduces risk of:",
         {"a": "Febrile nonhemolytic transfusion reactions and CMV transmission (and HLA alloimmunization)", "b": "Iron overload completely", "c": "All allergic reactions forever", "d": "ABO mismatches"},
         "a", "Removing WBCs decreases FNHTR, CMV risk, and alloimmunization risk.",
         {"b": "Iron overload still possible with chronic transfusion.", "c": "Allergic reactions often plasma protein related.", "d": "ABO compatibility still required."}, "medium"),
    ])

    qs += pack(e, "chemistry", [
        ("Elevated serum creatinine most directly suggests:",
         {"a": "Improved GFR always", "b": "Reduced glomerular filtration / impaired kidney function", "c": "Acute hepatitis specifically", "d": "Hyperthyroidism only"},
         "b", "Creatinine rises when GFR falls (with caveats of muscle mass/assay).",
         {"a": "Opposite.", "c": "Liver enzymes more specific for hepatitis.", "d": "Thyroid tests differ."}, "easy"),
        ("Hyponatremia means:",
         {"a": "Low serum sodium", "b": "High serum sodium", "c": "Low serum potassium", "d": "High serum calcium"},
         "a", "Hypo- = low; Na+ is sodium.",
         {"b": "Hypernatremia.", "c": "Hypokalemia.", "d": "Hypercalcemia."}, "easy"),
        ("Which analyte is a sensitive marker of hepatocellular injury?",
         {"a": "ALT (and AST)", "b": "Amylase exclusively for liver", "c": "Troponin I for hepatocytes", "d": "PSA"},
         "a", "ALT/AST rise with hepatocyte damage; ALT more liver-specific.",
         {"b": "Amylase more pancreas/salivary.", "c": "Troponin is cardiac.", "d": "Prostate marker."}, "easy"),
        ("HbA1c reflects average glycemia over approximately:",
         {"a": "1 day", "b": "2–3 months", "c": "10 years", "d": "1 hour postprandial only"},
         "b", "A1c correlates with RBC lifespan ~120 days; clinically ~2–3 months average glucose.",
         {"a": "Too short.", "c": "Too long.", "d": "OGTT/postprandial differ."}, "easy"),
        ("A critically high potassium result should first prompt:",
         {"a": "Immediate reporting after checking for hemolysis/sample integrity and clinical correlation per protocol", "b": "Discarding without notification", "c": "Waiting a week", "d": "Averaging with yesterday's result silently"},
         "a",
         "Critical values require rapid verification for preanalytics (hemolysis falsely ↑K+) and clinician notification.",
         {"b": "Must communicate criticals — discarding without notification is unsafe.", "c": "Delay harms patients.", "d": "Silent averaging is improper."}, "medium"),
        ("Lipemic specimens can interfere with assays mainly by:",
         {"a": "Improving all spectrophotometric accuracy", "b": "Causing turbidity/volume displacement errors in some methods", "c": "Increasing sodium by flame photometry always beneficially", "d": "Eliminating the need for QC"},
         "b", "Lipemia causes optical and sometimes electrolyte artifacts; ultracentrifugation/clearing may help.",
         {"a": "Worsens many optical assays.", "c": "Interference is problematic.", "d": "QC still required."}, "medium"),
        ("CK-MB and troponin are used primarily to evaluate:",
         {"a": "Myocardial injury", "b": "Renal tubular acidosis only", "c": "Bone turnover exclusively", "d": "Thyroid nodules"},
         "a", "Cardiac troponins (and historically CK-MB) mark myocardial injury.",
         {"b": "Electrolytes/ABG help RTA.", "c": "ALP/CTX etc. for bone.", "d": "Thyroid imaging/labs."}, "easy"),
        ("Anion gap metabolic acidosis is suggested by low bicarbonate with elevated anion gap; a common cause is:",
         {"a": "Lactic acidosis or ketoacidosis", "b": "Vomiting-induced metabolic alkalosis", "c": "Hyperchloremic normal gap only always", "d": "Respiratory alkalosis alone"},
         "a", "HAGMA causes include lactate, ketones, toxins (MUDPILES/GOLDMARK mnemonics).",
         {"b": "Vomiting → alkalosis.", "c": "Different pattern (NAGMA).", "d": "Respiratory process."}, "hard"),
        ("Bilirubin fractionation: elevated conjugated (direct) bilirubin suggests:",
         {"a": "Hepatic excretion defect / cholestasis or hepatocellular conjugated hyperbilirubinemia", "b": "Only hemolysis with purely unconjugated rise always", "c": "Normal neonatal physiologic jaundice exclusively always conjugated", "d": "Laboratory impossibility"},
         "a", "Conjugated hyperbilirubinemia points to hepatic/cholestatic pathways; hemolysis raises unconjugated.",
         {"b": "Hemolysis → unconjugated.", "c": "Physiologic neonatal often unconjugated.", "d": "Common pattern."}, "medium"),
        ("TSH is typically high in:",
         {"a": "Primary hypothyroidism", "b": "Primary hyperthyroidism", "c": "All euthyroid patients", "d": "Factitious thyrotoxicosis from excess T4 always low-normal only without exception"},
         "a", "Primary hypo: low thyroid hormones → high TSH.",
         {"b": "Primary hyper: TSH suppressed.", "c": "Euthyroid TSH normal.", "d": "Excess exogenous hormone suppresses TSH."}, "medium"),
        ("Serum osmolality is most contributed by:",
         {"a": "Sodium, glucose, and urea (BUN)", "b": "Albumin only", "c": "Calcium only", "d": "Iron only"},
         "a", "Calculated osm ≈ 2Na + glucose/18 + BUN/2.8 (conventional units).",
         {"b": "Colloid oncotic pressure more than osmoles count.", "c": "Minor osmoles.", "d": "Trace."}, "medium"),
        ("A glucose sample left unseparated on cells at room temperature for hours may show:",
         {"a": "Falsely increased glucose due to glycolysis", "b": "Falsely decreased glucose due to glycolysis", "c": "No change ever", "d": "Conversion to sodium"},
         "b", "Cellular glycolysis consumes glucose unless fluoride tubes/prompt separation used.",
         {"a": "Opposite direction.", "c": "Changes occur.", "d": "Nonsense."}, "easy"),
        ("Elevated ALP with elevated GGT suggests:",
         {"a": "Hepatic/biliary source of ALP more than bone alone", "b": "Pure bone source certainty", "c": "Always normal pregnancy only", "d": "Cardiac troponin elevation"},
         "a", "GGT supports hepatic origin of ALP elevation; bone ALP lacks GGT rise.",
         {"b": "Bone ALP usually normal GGT.", "c": "Pregnancy ALP can rise (placental) with context.", "d": "Different markers."}, "hard"),
        ("Therapeutic drug monitoring trough levels are drawn:",
         {"a": "Just before the next dose", "b": "At peak random anytime without protocol", "c": "One week after stopping therapy always", "d": "Only from arterial blood"},
         "a", "Troughs assess minimum concentration before redosing for many drugs.",
         {"b": "Peaks are timed post-dose.", "c": "Not trough definition.", "d": "Usually venous."}, "medium"),
        ("Hyperkalemia ECG risk makes lab-clinician communication urgent because K+ > ~6–6.5 mEq/L can cause:",
         {"a": "Peaked T waves and arrhythmias", "b": "Only bradycardia from hypokalemia", "c": "Pathognomonic ST elevation MI always", "d": "No cardiac effects"},
         "a", "Severe hyperkalemia is cardiotoxic; critical notification is mandatory.",
         {"b": "Hypokalemia has other ECG changes.", "c": "Not equivalent to STEMI criteria.", "d": "Cardiac effects are key."}, "easy"),
    ])

    qs += pack(e, "hematology", [
        ("Mean corpuscular volume (MCV) classifies anemias as:",
         {"a": "Microcytic, normocytic, or macrocytic", "b": "Only hypochromic always", "c": "Platelet size exclusively", "d": "Clotting factor levels"},
         "a", "MCV is the RBC size index used in anemia workups.",
         {"b": "MCHC relates to chromia.", "c": "MPV is platelets.", "d": "Coag assays."}, "easy"),
        ("Iron deficiency anemia typically shows:",
         {"a": "High MCV and high ferritin", "b": "Low MCV, low ferritin, high TIBC", "c": "High ferritin and low TIBC always like anemia of chronic disease pattern", "d": "Normal iron studies always"},
         "b", "IDA: microcytic hypochromic with low ferritin/iron and elevated TIBC.",
         {"a": "Opposite pattern.", "c": "ACD often low TIBC/high ferritin.", "d": "Abnormal in IDA."}, "medium"),
        ("Schistocytes on peripheral smear suggest:",
         {"a": "Microangiopathic hemolytic process", "b": "Iron overload exclusively", "c": "Normal newborn smear always", "d": "Vitamin C toxicity"},
         "a", "Fragmented RBCs occur in MAHA (DIC, TTP, HUS, mechanical valves, etc.).",
         {"b": "Different findings.", "c": "Not normal.", "d": "Unrelated."}, "medium"),
        ("A left shift in the WBC differential refers to:",
         {"a": "Increased immature neutrophils (bands/metas) in circulation", "b": "Increased lymphocytes only always", "c": "Decreased WBC count definitionally", "d": "Eosinopenia only"},
         "a", "Left shift indicates myeloid immaturity often with infection/inflammation.",
         {"b": "Lymphocytosis different.", "c": "Count may be high or low.", "d": "Different lineage."}, "easy"),
        ("PT/INR primarily monitors:",
         {"a": "Extrinsic pathway / warfarin therapy", "b": "Intrinsic pathway only / heparin exclusively", "c": "Platelet aggregation only", "d": "Fibrin degradation exclusively without PT"},
         "a", "PT/INR assesses factors VII pathway and warfarin effect.",
         {"b": "aPTT more for heparin/intrinsic.", "c": "Platelet function tests differ.", "d": "FDPs/D-dimer separate."}, "easy"),
        ("aPTT prolongation with normal PT may indicate:",
         {"a": "Factor VIII/IX deficiency or heparin effect (among other intrinsic pathway issues)", "b": "Isolated factor VII deficiency only", "c": "Always vitamin K deficiency alone exclusively", "d": "Normal hemostasis certainty"},
         "a", "Intrinsic pathway defects and unfractionated heparin prolong aPTT more than PT.",
         {"b": "VII prolongs PT.", "c": "Vit K affects II, VII, IX, X — both PT/aPTT can rise.", "d": "Abnormal result."}, "hard"),
        ("D-dimer elevation indicates:",
         {"a": "Fibrin formation and fibrinolysis have occurred (nonspecific)", "b": "Certain absence of thrombosis always", "c": "Only liver synthetic failure specifically", "d": "Iron deficiency"},
         "a", "D-dimer is sensitive but not specific; used to help exclude VTE when pretest probability low.",
         {"b": "Elevation has many causes.", "c": "Not specific.", "d": "Unrelated."}, "medium"),
        ("Hemoglobin electrophoresis is useful to diagnose:",
         {"a": "Hemoglobinopathies such as sickle cell disease/trait", "b": "Acute bacterial meningitis exclusively", "c": "Myocardial infarction", "d": "Hypothyroidism"},
         "a", "Separates Hb variants (S, C, A2, F, etc.).",
         {"b": "CSF studies.", "c": "Troponin.", "d": "TSH/FT4."}, "easy"),
        ("Reticulocyte count rises when:",
         {"a": "Bone marrow increases RBC production (e.g., response to hemolysis/blood loss after iron available)", "b": "Marrow fails completely with no stress", "c": "Only in iron deficiency without treatment ever", "d": "Platelets clump"},
         "a", "Reticulocytosis marks marrow response to anemia.",
         {"b": "Aplastic processes have low retics.", "c": "IDA retics low until iron repleted.", "d": "Platelet artifact."}, "medium"),
        ("EDTA as anticoagulant in CBC tubes works by:",
         {"a": "Chelating calcium", "b": "Activating thrombin", "c": "Providing tissue factor", "d": "Lysing all WBCs intentionally for RBC count only"},
         "a", "EDTA binds Ca2+ to prevent clotting for hematology counts.",
         {"b": "Opposite of anticoagulation.", "c": "Would promote clotting.", "d": "WBCs preserved for differential."}, "easy"),
        ("Pseudothrombocytopenia due to EDTA is suspected when:",
         {"a": "Platelet clumps are seen on smear and count is higher in citrate tube", "b": "True DIC is proven by smear alone without labs", "c": "MCV is high", "d": "INR is 1.0"},
         "a", "EDTA-dependent antibodies clump platelets in vitro; recollect in citrate.",
         {"b": "Need clinical/lab correlation for DIC.", "c": "RBC index.", "d": "Coag normal doesn't explain."}, "hard"),
        ("Hypersegmented neutrophils are classically associated with:",
         {"a": "B12/folate deficiency", "b": "Iron deficiency exclusively", "c": "Acute blood loss only", "d": "Aspirin therapy specifically"},
         "a", "Megaloblastic anemias show hypersegmented PMNs.",
         {"b": "Microcytic anemia pattern.", "c": "Normocytic often.", "d": "Not classic for hypersegmentation."}, "medium"),
        ("Primary hemostasis involves mainly:",
         {"a": "Platelet adhesion/aggregation and vessel wall", "b": "Vitamin K–dependent factor cascade only", "c": "Fibrinolysis exclusively", "d": "Complement cascade only"},
         "a", "Primary hemostasis = platelets + endothelium; secondary = coagulation factors → fibrin.",
         {"b": "Secondary hemostasis.", "c": "Clot breakdown.", "d": "Innate immunity."}, "easy"),
        ("Blasts on peripheral smear in an adult with cytopenias most urgently suggest:",
         {"a": "Possible acute leukemia requiring prompt hematopathology workup", "b": "Normal finding in all adults", "c": "Only viral URI", "d": "Iron deficiency certainty"},
         "a", "Circulating blasts warrant urgent evaluation for acute leukemia.",
         {"b": "Abnormal.", "c": "Not explained by simple URI.", "d": "Different smear."}, "medium"),
        ("ESR is a nonspecific marker that rises with:",
         {"a": "Inflammation (also anemia, pregnancy, etc.)", "b": "Only myocardial infarction specifically", "c": "Decreased fibrinogen always", "d": "Dehydration causing polycythemia exclusively"},
         "a", "ESR increases with acute-phase proteins/rouleaux; nonspecific.",
         {"b": "Troponin for MI.", "c": "Low fibrinogen can lower ESR.", "d": "Polycythemia may lower ESR."}, "easy"),
    ])

    qs += pack(e, "micro-immuno", [
        ("Gram-positive organisms stain:",
         {"a": "Purple/blue due to thick peptidoglycan retaining crystal violet", "b": "Pink/red because of outer membrane only", "c": "Green with acid-fast only", "d": "Colorless always"},
         "a", "Crystal violet–iodine complex is retained in Gram-positive walls.",
         {"b": "Gram-negatives take safranin counterstain.", "c": "AFB use different stains.", "d": "They take stain."}, "easy"),
        ("Catalase test differentiates:",
         {"a": "Staphylococcus (positive) from Streptococcus (negative)", "b": "All Gram-negatives from each other", "c": "Viruses from fungi", "d": "Mycobacteria species definitively alone"},
         "a", "Staphylococci are catalase-positive; streptococci/enterococci catalase-negative.",
         {"b": "Need other tests.", "c": "Different methods.", "d": "Needs more ID methods."}, "easy"),
        ("A positive coagulase test is characteristic of:",
         {"a": "Staphylococcus aureus", "b": "Staphylococcus epidermidis typically", "c": "Streptococcus pyogenes", "d": "Escherichia coli"},
         "a", "S. aureus is coagulase-positive (with rare exceptions).",
         {"b": "CoNS are coagulase-negative.", "c": "Strep.", "d": "GNB."}, "easy"),
        ("Acid-fast staining is used for:",
         {"a": "Mycobacterium species", "b": "All streptococci", "c": "Influenza virus particles in light microscopy routinely", "d": "Plasmodium only with Gram stain"},
         "a", "Mycolic acids retain carbol fuchsin in AFB stains.",
         {"b": "Gram stain.", "c": "Viruses need other methods.", "d": "Malaria uses Giemsa; not Gram AFB concept."}, "easy"),
        ("ELISA immunoassays detect antigen or antibody using:",
         {"a": "Enzyme-labeled conjugates producing a measurable color/signal", "b": "Only Gram stain", "c": "Flame photometry of sodium", "d": "Westergren pipettes exclusively"},
         "a", "ELISA uses enzyme-substrate systems for sensitive Ag/Ab detection.",
         {"b": "Microscopy.", "c": "Electrolytes.", "d": "ESR method."}, "medium"),
        ("Zone of inhibition in Kirby-Bauer testing indicates:",
         {"a": "Antimicrobial activity against the organism under standardized conditions", "b": "That the drug is toxic to humans", "c": "Exact MIC in µg/mL without charts", "d": "Viral load"},
         "a", "Disk diffusion zones are interpreted with CLSI breakpoints; MIC needs dilution methods.",
         {"b": "In vitro activity ≠ host toxicity.", "c": "Zones correlate but aren't MIC numbers.", "d": "Molecular/viral assays."}, "medium"),
        ("Which organism is an obligate intracellular bacterium causing atypical pneumonia, detected often by NAAT/serology rather than routine sputum culture?",
         {"a": "Mycoplasma pneumoniae", "b": "Staphylococcus aureus", "c": "Pseudomonas aeruginosa on MacConkey as lactose fermenter always", "d": "Candida albicans"},
         "a", "M. pneumoniae lacks cell wall; not seen on Gram stain; diagnosed by PCR/serology.",
         {"b": "Grows on routine media.", "c": "Pseudomonas is oxidase+ nonfermenter.", "d": "Yeast."}, "hard"),
        ("IgM antibodies typically indicate:",
         {"a": "Recent/primary immune response (often)", "b": "Only remote immunity years later exclusively", "c": "No immune response", "d": "Complement protein C3 level"},
         "a", "IgM rises early; IgG indicates later/past exposure (context-dependent).",
         {"b": "IgG more for remote.", "c": "Opposite.", "d": "Different analyte."}, "easy"),
        ("Blood culture contamination is suggested by:",
         {"a": "Single bottle growth of skin flora (e.g., CoNS) with mismatched clinical picture", "b": "Multiple sets growing the same Gram-negative rod in a septic patient", "c": "Growth of E. coli in all bottles with pyelonephritis", "d": "S. aureus in multiple sets with endocarditis signs"},
         "a", "Common contaminants appear in single sets; true pathogens often repeatedly isolated with compatible clinic.",
         {"b": "Likely true bacteremia.", "c": "True infection pattern.", "d": "True infection pattern."}, "medium"),
        ("Selective media such as MacConkey agar are designed to:",
         {"a": "Inhibit Gram-positives and differentiate lactose fermentation among Gram-negatives", "b": "Grow only viruses", "c": "Kill all Gram-negatives", "d": "Measure antibody titers"},
         "a", "Bile salts/crystal violet select for GNB; lactose fermentation shows pink colonies.",
         {"b": "Cell culture/molecular for viruses.", "c": "GNB grow.", "d": "Serology."}, "easy"),
        ("Western blot / immunoblot historically confirmed:",
         {"a": "Specific antibodies to separated protein antigens (e.g., older HIV algorithms)", "b": "Serum sodium", "c": "Gram stain morphology", "d": "ESR"},
         "a", "Immunoblots detect Ab reactivity to specific proteins after separation.",
         {"b": "Chemistry.", "c": "Microscopy.", "d": "Inflammation marker."}, "medium"),
        ("Type I hypersensitivity is mediated primarily by:",
         {"a": "IgE", "b": "IgG only against basement membrane", "c": "IgA secretory only", "d": "IgD exclusively"},
         "a", "Immediate hypersensitivity (anaphylaxis/allergy) is IgE-mast cell mediated.",
         {"b": "Type II examples differ.", "c": "Mucosal immunity.", "d": "B-cell receptor role, not classic type I effector."}, "medium"),
        ("Clostridioides difficile infection laboratory diagnosis commonly uses:",
         {"a": "Stool testing for toxins and/or toxin gene NAAT per algorithm", "b": "Throat culture on blood agar only", "c": "Urine dipstick nitrite", "d": "Blood smear for parasites"},
         "a", "Labs use GDH/toxin EIA ± NAAT algorithms on unformed stool.",
         {"b": "Wrong specimen/pathogen approach.", "c": "UTI screen.", "d": "Different."}, "medium"),
        ("Quality control for antimicrobial susceptibility testing requires:",
         {"a": "Testing appropriate ATCC control strains with acceptable ranges", "b": "Skipping controls if busy", "c": "Using expired disks routinely", "d": "Interpreting zones without standards"},
         "a", "CLSI QC with reference strains validates method performance.",
         {"b": "QC is mandatory.", "c": "Expired reagents invalid.", "d": "Breakpoints required."}, "easy"),
        ("India ink or cryptococcal antigen testing is used for:",
         {"a": "Cryptococcus neoformans/gattii in CSF/serum contexts", "b": "Group A strep pharyngitis exclusively", "c": "Malaria thick smears only", "d": "TB PCR exclusively"},
         "a", "Capsule visualization/antigen assays support cryptococcal meningitis diagnosis.",
         {"b": "Rapid strep/culture.", "c": "Giemsa smears.", "d": "Different pathogens."}, "hard"),
    ])
    return qs
