from __future__ import annotations

from ._common import pack


def build() -> list[dict]:
    e = "danb-gc-readiness-check"
    qs: list[dict] = []

    qs += pack(e, "chairside", [
        ("The dental assistant's primary role during four-handed dentistry is to:",
         {"a": "Diagnose caries independently", "b": "Transfer instruments and maintain a clear field so the operator works efficiently", "c": "Prescribe antibiotics", "d": "Perform irreversible procedures without supervision"},
         "b", "Chairside assisting supports the operator with instrument transfer, isolation, and field maintenance within permitted scope.",
         {"a": "Diagnosis is a dentist responsibility.", "c": "Prescribing is not within DA scope.", "d": "Irreversible procedures require dentist performance/authorization per state law."}, "easy"),
        ("When transferring a hinged instrument using the single-handed transfer, the assistant typically:",
         {"a": "Passes it tip-first toward the operator's palm", "b": "Delivers it so the operator can grasp the handle in working position", "c": "Throws it onto the tray", "d": "Holds it by the working end only"},
         "b", "Transfers should present the handle for secure grasp in the correct orientation, reducing eye/hand injury risk.",
         {"a": "Tips toward the palm risk injury.", "c": "Throwing is unsafe.", "d": "Grasping the working end contaminates/dulls instruments and risks injury."}, "medium"),
        ("Rubber dam isolation primarily helps by:",
         {"a": "Increasing saliva contamination of the field", "b": "Improving visibility, moisture control, and airway protection from small objects", "c": "Eliminating the need for local anesthesia", "d": "Replacing radiographs"},
         "b", "Rubber dam isolates the tooth, controls moisture, and reduces aspiration/swallowing risk.",
         {"a": "It decreases contamination.", "c": "Anesthesia needs are separate.", "d": "Imaging remains necessary when indicated."}, "easy"),
        ("The HVE (high-volume evacuator) tip should generally be positioned:",
         {"a": "As far from the tooth as possible", "b": "Close to the tooth being treated, bevel facing the tooth/working area, without blocking vision", "c": "Inside the patient's throat", "d": "Only on the opposing arch always"},
         "b", "Proper HVE placement captures spray/debris at the source while preserving access and soft-tissue protection.",
         {"a": "Distance reduces suction effectiveness.", "c": "Deep throat placement risks injury/gagging.", "d": "Placement follows the working tooth."}, "medium"),
        ("Before seating a patient for restorative care, the assistant should:",
         {"a": "Skip medical history updates", "b": "Review medical history/allergies and confirm the planned procedure", "c": "Assume no changes since last decade", "d": "Start drilling immediately"},
         "b", "Updated medical history and confirmation of the plan support safety (allergies, meds, contraindications).",
         {"a": "History must be current.", "c": "Health status changes.", "d": "Preparation and consent come first."}, "easy"),
        ("Which instrument is commonly used to carve amalgam after condensation?",
         {"a": "Explorer only", "b": "Cleoid-discoid carver or similar amalgam carvers", "c": "Cement spatula for enamel etching", "d": "Periodontal probe for occlusion only"},
         "b", "Amalgam carvers (cleoid-discoid, Hollenback) shape anatomy after condensation.",
         {"a": "Explorers detect caries/margins, not primary carving.", "c": "Spatulas mix materials.", "d": "Probes measure periodontal depths."}, "medium"),
        ("During local anesthesia, the dental assistant's supportive role may include:",
         {"a": "Selecting the anesthetic type independently for all patients", "b": "Preparing the syringe, aspirating assistance per protocol, and monitoring the patient", "c": "Injecting anesthetic in every state without training", "d": "Ignoring signs of syncope"},
         "b", "Assistants prepare and support within state-allowed duties and watch for adverse reactions.",
         {"a": "Drug selection is the dentist's responsibility.", "c": "Injection privileges vary by state and training.", "d": "Syncope requires prompt response."}, "medium"),
        ("The correct order for basic instrument transfer zones places the transfer zone:",
         {"a": "Behind the patient's head only", "b": "Across the patient's chest/near the chin area where operator and assistant exchange instruments", "c": "On the floor", "d": "Outside the operatory"},
         "b", "The transfer zone is typically over the patient's chest near the chin for safe exchanges.",
         {"a": "Static zone is behind/beside.", "c": "Floor is contaminated/unsafe.", "d": "Transfers occur at chairside."}, "easy"),
        ("Matrix bands are used primarily to:",
         {"a": "Whiten enamel", "b": "Provide a temporary wall for proximal restorations during placement", "c": "Replace missing teeth permanently", "d": "Measure probing depths"},
         "b", "Matrices restore proximal contour and containment while restorative material sets.",
         {"a": "Whitening uses bleaching agents.", "c": "Prostheses replace teeth.", "d": "Probing uses periodontal probes."}, "easy"),
        ("If a patient begins coughing forcefully while supine during a procedure, the assistant should first:",
         {"a": "Ignore it and continue", "b": "Stop, clear the airway/field, upright or turn the patient as needed, and summon help if distress persists", "c": "Increase water spray", "d": "Place more cotton rolls deeper into the throat"},
         "b", "Airway protection and patient positioning take priority when coughing/choking risk appears.",
         {"a": "Ignoring risks aspiration.", "c": "More water worsens choking risk.", "d": "Deep packing can obstruct the airway."}, "hard"),
        ("A tofflemire retainer is associated with:",
         {"a": "Orthodontic wire bending only", "b": "Holding a matrix band for Class II restorations", "c": "Vitalometry", "d": "Ultrasonic scaling exclusively"},
         "b", "Universal (Tofflemire) retainers stabilize circumferential matrix bands.",
         {"a": "Ortho uses different pliers/wires.", "c": "Pulp testing is separate.", "d": "Scalers remove deposits."}, "medium"),
        ("Chairside, the assistant should maintain the oral cavity field by:",
         {"a": "Allowing continuous pooling of saliva at the site", "b": "Using suction, retraction, and isolation appropriate to the procedure", "c": "Turning off HVE for composite to 'keep it wet'", "d": "Never retracting the tongue/cheek"},
         "b", "Moisture control and soft-tissue retraction are core chairside functions.",
         {"a": "Pooling contaminates restorations.", "c": "Composites need dry fields; HVE still manages spray/debris appropriately.", "d": "Retraction protects tissues and improves access."}, "easy"),
        ("Which bur is generally used for initial cavity outline in high-speed handpieces?",
         {"a": "Straight fissure or pear/round carbide burs designed for cavity preparation", "b": "Polishing cup only", "c": "Endodontic file", "d": "Prophy angle brush exclusively"},
         "a", "Operative burs (pear, round, fissure) cut enamel/dentin for outline form.",
         {"b": "Cups polish.", "c": "Files clean canals.", "d": "Brushes polish/clean."}, "medium"),
        ("When assisting during crown preparation, cord packing is used to:",
         {"a": "Increase bleeding intentionally without purpose", "b": "Gently retract gingiva for margin access/impression quality when indicated", "c": "Replace local anesthetic", "d": "Etch enamel"},
         "b", "Retraction cord helps expose margins for prep finishing and impressions.",
         {"a": "Bleeding control is desired, not increased bleeding.", "c": "Anesthesia is pharmacologic.", "d": "Etchant is separate."}, "medium"),
        ("A dental dam clamp is selected based primarily on:",
         {"a": "Tooth morphology and stability needs for the tooth being isolated", "b": "Patient shoe size", "c": "Operatory wall color", "d": "Insurance plan only"},
         "a", "Clamp jaws/wings are chosen to fit the tooth's cervical anatomy securely without trauma.",
         {"b": "Irrelevant.", "c": "Irrelevant.", "d": "Clinical fit drives selection."}, "hard"),
    ])

    qs += pack(e, "materials", [
        ("Amalgam capsules should be triturated:",
         {"a": "By hand mixing powder with saliva", "b": "According to manufacturer time/speed settings", "c": "For at least 10 minutes always", "d": "Until the material boils"},
         "b", "Proper trituration follows manufacturer parameters for strength and handling.",
         {"a": "Saliva contamination ruins material.", "c": "Overtrituration harms properties.", "d": "Boiling is not a criterion."}, "easy"),
        ("Composite resin polymerization is commonly initiated by:",
         {"a": "Cold sterile water only", "b": "Visible-light curing units of appropriate wavelength/intensity", "c": "Open flame in the mouth", "d": "Ultrasonic scalers"},
         "b", "Light-cured composites polymerize under curing lights matched to the photoinitiator.",
         {"a": "Water does not cure composite.", "c": "Flame is dangerous and inappropriate.", "d": "Scalers remove calculus."}, "easy"),
        ("Zinc oxide–eugenol (ZOE) cement is often used as:",
         {"a": "A final esthetic veneer material", "b": "A temporary cement or sedative base/temporary filling in selected cases", "c": "An acid etchant", "d": "A fluoride varnish exclusively"},
         "b", "ZOE has sedative properties and is used for temporary cementation/restorations (with eugenol caveats for composites).",
         {"a": "Not an esthetic definitive veneer.", "c": "Etchants are acids like phosphoric acid.", "d": "Fluoride varnish is different."}, "medium"),
        ("Acid etching enamel before composite bonding primarily:",
         {"a": "Creates microscopic irregularities to improve micromechanical retention", "b": "Kills the pulp instantly in all cases", "c": "Polishes the restoration", "d": "Replaces the need for isolation"},
         "a", "Phosphoric acid etch creates a microporous enamel surface for resin penetration.",
         {"b": "Proper etch does not 'kill the pulp instantly.'", "c": "Polishing is finishing.", "d": "Isolation remains critical."}, "easy"),
        ("Alginate impressions should be poured:",
         {"a": "Days later after complete dehydration", "b": "Promptly, ideally soon after removal, and kept moist if brief delay is unavoidable", "c": "Only after freezing solid", "d": "Never; alginate cannot be poured"},
         "b", "Alginate is dimensionally unstable with syneresis/imbibition; pour soon and store properly if delayed briefly.",
         {"a": "Drying distorts the impression.", "c": "Freezing is not standard.", "d": "Alginate is routinely poured in stone."}, "medium"),
        ("Gypsum products: dental stone generally differs from plaster by:",
         {"a": "Being weaker and more porous always", "b": "Having lower water/powder ratio needs and greater strength (Type III stone vs plaster)", "c": "Being edible", "d": "Polymerizing with blue light"},
         "b", "Stone particles require less water and produce stronger casts than plaster.",
         {"a": "Stone is stronger than plaster.", "c": "Not for ingestion.", "d": "Gypsum sets chemically with water, not light."}, "medium"),
        ("Glass ionomer cement advantages include:",
         {"a": "No fluoride release ever", "b": "Chemical adhesion to tooth structure and fluoride release", "c": "Unlimited working time in all products", "d": "Superior esthetics to all ceramics always"},
         "b", "GICs bond chemically and release fluoride; useful for selected restorations/bases/cements.",
         {"a": "Fluoride release is a known property.", "c": "Working times are limited.", "d": "Ceramics often surpass GIC esthetics."}, "medium"),
        ("A bite registration material is used to:",
         {"a": "Record occlusal relationship between arches", "b": "Etch dentin", "c": "Sterilize handpieces", "d": "Measure pocket depths"},
         "a", "Bite registrations capture interocclusal relationships for mounting/lab work.",
         {"b": "Etching is bonding.", "c": "Sterilization is infection control.", "d": "Probing measures perio status."}, "easy"),
        ("Polysulfide impression materials typically require:",
         {"a": "No mixing of base/catalyst", "b": "Base and catalyst mixed to a uniform color per instructions", "c": "Light curing only", "d": "Mixing with alginate powder"},
         "b", "Elastomeric polysulfides are two-paste systems mixed to homogeneity.",
         {"a": "They require mixing.", "c": "They set chemically, not by dental curing light.", "d": "Do not mix with alginate."}, "hard"),
        ("Calcium hydroxide liners are placed primarily to:",
         {"a": "Stimulate reparative dentin / protect pulp in deep preparations when indicated", "b": "Whiten teeth overnight", "c": "Replace missing cusps permanently alone", "d": "Serve as final occlusal enamel"},
         "a", "Ca(OH)2 liners are used for pulp protection/indirect-direct pulp capping strategies as indicated.",
         {"b": "Not a whitening agent for that purpose.", "c": "Structural replacement needs restorative materials.", "d": "Not final enamel."}, "medium"),
        ("Temporary crowns should:",
         {"a": "Have open margins and high occlusion to 'settle in'", "b": "Protect the preparation, maintain contacts/occlusion reasonably, and be cemented temporarily", "c": "Be left out overnight routinely", "d": "Never be adjusted"},
         "b", "Provisionals protect pulp/periodontium, maintain space and function until final delivery.",
         {"a": "Open margins and hyperocclusion harm tissues/TMJ comfort.", "c": "Leaving them out risks sensitivity/movement.", "d": "Adjustments are often needed."}, "easy"),
        ("Which metal is a major component of traditional dental amalgam alloy powder?",
         {"a": "Pure gold only", "b": "Silver (with tin, copper, etc.)", "c": "Titanium dioxide exclusively", "d": "Aluminum foil"},
         "b", "Amalgam alloys are primarily silver-tin based with copper and other metals, mixed with mercury.",
         {"a": "Gold is for cast restorations/foils historically.", "c": "TiO2 is not amalgam alloy.", "d": "Aluminum foil is not dental amalgam."}, "medium"),
        ("Polyvinyl siloxane (PVS) impressions are valued because they:",
         {"a": "Have poor dimensional stability", "b": "Offer excellent dimensional stability and detail reproduction", "c": "Must be poured within 30 seconds always", "d": "Cannot be used for crowns"},
         "b", "Addition silicones (PVS) are highly accurate and stable for delayed pours/multiple pours per product guidance.",
         {"a": "Stability is a strength.", "c": "They allow longer pour windows than alginate.", "d": "Widely used for crowns/bridges."}, "easy"),
        ("Eugenol can interfere with:",
         {"a": "Composite resin polymerization/bonding if contaminated", "b": "Glass mixing bowls only", "c": "Patient breathing always", "d": "X-ray film speed permanently"},
         "a", "Eugenol residues can inhibit resin polymerization; avoid under composites when contraindicated.",
         {"b": "Bowls are unaffected in that sense.", "c": "Not a universal respiratory toxin at dental use levels in this framing.", "d": "Unrelated to film speed."}, "hard"),
        ("Finishing and polishing amalgam restorations too early can:",
         {"a": "Improve strength immediately always", "b": "Damage the restoration because final set strength develops over time", "c": "Convert amalgam to composite", "d": "Eliminate mercury content entirely"},
         "b", "Amalgam continues to harden after placement; premature aggressive polishing can weaken margins.",
         {"a": "Early finishing can harm, not help strength.", "c": "Materials do not convert.", "d": "Polishing does not remove all mercury."}, "medium"),
    ])

    qs += pack(e, "patient-care", [
        ("The most effective way to prevent dental caries at home is typically:",
         {"a": "Avoiding all dental visits forever", "b": "Daily fluoride toothpaste use, plaque control, and limiting frequent sugar exposures", "c": "Rinsing with soda after meals", "d": "Brushing only once per month"},
         "b", "Fluoride, mechanical plaque removal, and diet control are core caries prevention strategies.",
         {"a": "Professional care remains important.", "c": "Soda increases caries risk.", "d": "Infrequent brushing fails plaque control."}, "easy"),
        ("Dental floss is primarily used to:",
         {"a": "Clean interproximal surfaces where brushes may not reach", "b": "Replace all toothbrushing", "c": "Etch enamel", "d": "Take radiographs"},
         "a", "Floss/interdental cleaners disrupt proximal plaque biofilm.",
         {"b": "Brushing is still required.", "c": "Etching is clinical.", "d": "Imaging is separate."}, "easy"),
        ("A patient with uncontrolled angina in the chair who develops chest pain should:",
         {"a": "Continue elective care without pause", "b": "Stop treatment, follow emergency protocol (NTG if prescribed/protocol, oxygen/EMS as indicated)", "c": "Be given a large meal immediately", "d": "Be placed in Trendelenburg and ignored"},
         "b", "Chest pain is a medical emergency pathway: stop dentistry and activate emergency response per training.",
         {"a": "Elective care must stop.", "c": "Food is inappropriate.", "d": "Ignoring is unsafe; positioning depends on protocol."}, "medium"),
        ("Oral cancer screening in the dental office includes:",
         {"a": "Ignoring white/red patches", "b": "Extraoral and intraoral soft-tissue examination and referral of suspicious lesions", "c": "Only asking about tooth color", "d": "Refusing to look under the tongue"},
         "b", "Systematic soft-tissue exam and timely referral are standard prevention roles.",
         {"a": "Lesions need evaluation.", "c": "Soft tissues matter beyond esthetics.", "d": "Tongue/floor of mouth are high-risk sites."}, "easy"),
        ("For a patient with a latex allergy, the team should:",
         {"a": "Use latex gloves carefully", "b": "Use non-latex gloves and avoid latex products in the operatory", "c": "Increase latex exposure to desensitize during the visit", "d": "Ignore the allergy if the patient 'seems fine'"},
         "b", "Elimination of latex products prevents allergic reactions.",
         {"a": "Latex is contraindicated.", "c": "Desensitization is not a chairside tactic.", "d": "Allergies must be respected."}, "easy"),
        ("Topical fluoride varnish is commonly applied to:",
         {"a": "Reduce caries risk on enamel surfaces per protocol", "b": "Dissolve amalgam fillings", "c": "Replace sealants always", "d": "Sterilize instruments"},
         "a", "Fluoride varnish remineralizes and reduces caries incidence, especially in higher-risk patients.",
         {"b": "It does not dissolve amalgam.", "c": "Sealants are separate preventive services.", "d": "Not a sterilant."}, "easy"),
        ("Pit and fissure sealants are most beneficial for:",
         {"a": "Smooth root surfaces only", "b": "Caries-susceptible pits and fissures of posterior teeth when indicated", "c": "Edentulous ridges", "d": "Tongue cleaning"},
         "b", "Sealants physically protect deep occlusal anatomy from biofilm acids.",
         {"a": "Roots may need other therapies.", "c": "No enamel pits there.", "d": "Unrelated."}, "medium"),
        ("A patient on warfarin needing extraction planning should:",
         {"a": "Always stop warfarin the night before without physician input", "b": "Have medical consultation regarding bleeding risk and INR management as indicated", "c": "Be told anticoagulants never affect dentistry", "d": "Receive aspirin immediately before surgery"},
         "b", "Anticoagulation management requires coordination; do not unilaterally stop meds.",
         {"a": "Abrupt cessation can cause thrombosis.", "c": "Bleeding risk is real.", "d": "Aspirin adds antiplatelet effect inappropriately here."}, "hard"),
        ("Proper toothbrushing technique teaching emphasizes:",
         {"a": "Aggressive horizontal scrubbing at the gingival margin only", "b": "Gentle angled bristles at the gingival margin (e.g., Bass-type) covering all surfaces", "c": "Brushing only the biting surfaces", "d": "Using a hard brush as forcefully as possible"},
         "b", "Effective plaque removal with minimal trauma uses proper angulation and gentle pressure.",
         {"a": "Aggressive scrubbing causes recession/abrasion.", "c": "Facial/lingual/interproximal matter.", "d": "Hard forceful brushing injures tissues."}, "easy"),
        ("Xerostomia increases caries risk because:",
         {"a": "Saliva normally buffers acids and aids remineralization", "b": "Dry mouth kills all bacteria instantly", "c": "Fluoride becomes toxic only then", "d": "Enamel becomes thicker"},
         "a", "Reduced saliva impairs buffering, clearance, and remineralization.",
         {"b": "Dry mouth does not sterilize the mouth.", "c": "Fluoride remains beneficial when used properly.", "d": "Enamel does not thicken from xerostomia."}, "medium"),
        ("For pediatric behavior guidance, tell-show-do means:",
         {"a": "Threatening the child", "b": "Explaining, demonstrating on a model/finger, then performing the step", "c": "Skipping explanation to save time", "d": "Showing radiographs only"},
         "b", "Tell-show-do reduces anxiety through predictable, stepwise communication.",
         {"a": "Threats are inappropriate.", "c": "Explanation builds cooperation.", "d": "Incomplete description of the method."}, "easy"),
        ("A medical emergency kit in the dental office should include, at minimum, items such as:",
         {"a": "Only cotton rolls", "b": "Oxygen and emergency medications per ADA/office protocol (e.g., epinephrine, antihistamine, etc.)", "c": "No medications ever", "d": "Expired drugs exclusively"},
         "b", "Offices maintain oxygen and emergency drugs matched to anticipated emergencies and training.",
         {"a": "Insufficient for medical emergencies.", "c": "Medications are part of readiness.", "d": "Expired drugs are unsafe."}, "medium"),
        ("Pregnancy considerations in dentistry include:",
         {"a": "Elective care timing discussion and avoiding unnecessary radiographs; urgent care as needed with shielding", "b": "Never treating dental infections", "c": "Doubling radiation without apron", "d": "Stopping all oral hygiene"},
         "a", "Coordinate timing, use ALARA with shielding, and treat infection to protect mother/fetus.",
         {"b": "Infections should be managed.", "c": "Violates radiation safety.", "d": "Hygiene remains essential."}, "hard"),
        ("The primary etiology of periodontal disease is:",
         {"a": "Dental biofilm (plaque) and host response", "b": "Toothbrush color", "c": "Wearing lipstick", "d": "Drinking water with any minerals"},
         "a", "Bacterial biofilm initiates inflammation modulated by host factors.",
         {"b": "Irrelevant.", "c": "Irrelevant.", "d": "Minerals in water are not the primary cause."}, "easy"),
        ("Postoperative extraction instructions commonly include:",
         {"a": "Rinsing vigorously immediately every 5 minutes for an hour", "b": "Biting on gauze, avoiding straws/smoking, and soft diet as instructed", "c": "Exercising the socket with a toothpick hourly", "d": "Taking someone else's opioid prescription"},
         "b", "Clot protection (no suction/smoking), pressure hemostasis, and diet guidance reduce dry socket/bleeding risks.",
         {"a": "Early vigorous rinsing can dislodge the clot.", "c": "Trauma to the socket is harmful.", "d": "Sharing controlled substances is illegal/unsafe."}, "medium"),
    ])

    qs += pack(e, "office", [
        ("Patient records in a dental office must be:",
         {"a": "Left in the reception lobby overnight", "b": "Kept confidential and secured per HIPAA and office policy", "c": "Posted on social media for marketing", "d": "Shared with any caller who asks"},
         "b", "Dental records contain PHI requiring safeguards and authorized disclosures only.",
         {"a": "Unsecured records breach privacy.", "c": "Public posting is prohibited.", "d": "Identity verification/authorization required."}, "easy"),
        ("Informed consent for dental treatment should document:",
         {"a": "Risks, benefits, alternatives, and patient agreement", "b": "Only the fee", "c": "Staff lunch preferences", "d": "Nothing in writing ever"},
         "a", "Consent conversations cover material risks/benefits/alternatives and voluntary agreement.",
         {"b": "Fees alone are insufficient.", "c": "Irrelevant.", "d": "Documentation supports legal/ethical care."}, "easy"),
        ("Which is an example of a legal expanded function that varies by state?",
         {"a": "Diagnosing oral pathology as a dentist", "b": "Coronal polishing or sealant placement by qualified auxiliaries where permitted", "c": "Writing Schedule II prescriptions", "d": "Owning the dental license of the dentist"},
         "b", "Expanded functions (polish, sealants, etc.) depend on state practice acts and credentials.",
         {"a": "Diagnosis remains a dentist function.", "c": "Prescribing is dentist/physician scope.", "d": "Licenses are not transferable that way."}, "medium"),
        ("Appointment scheduling that leaves adequate time for complex procedures helps primarily to:",
         {"a": "Increase rushed incomplete care", "b": "Support quality care and reduce stress/errors", "c": "Guarantee no-shows", "d": "Eliminate the need for consent"},
         "b", "Realistic scheduling improves outcomes and safety.",
         {"a": "Rushing harms quality.", "c": "Unrelated.", "d": "Consent remains required."}, "easy"),
        ("OSHA Hazard Communication in the dental office includes:",
         {"a": "Ignoring Safety Data Sheets", "b": "Maintaining SDS access and labeling for hazardous chemicals", "c": "Storing acids unlabeled in soda bottles", "d": "Training only once every 20 years without updates"},
         "b", "HazCom requires SDS, labels, and training for chemical hazards.",
         {"a": "SDS must be accessible.", "c": "Mislabeling is dangerous/illegal.", "d": "Training is ongoing/as required."}, "medium"),
        ("Sterilization monitoring should include:",
         {"a": "Visual inspection only forever", "b": "Mechanical, chemical, and biological (spore) monitoring per CDC guidance", "c": "Never checking autoclaves", "d": "Wiping instruments with alcohol as the sole sterilant for critical items"},
         "b", "Multi-level monitoring verifies sterilizer performance; spore tests are essential.",
         {"a": "Visual alone is insufficient.", "c": "Monitoring is mandatory for safety.", "d": "Critical instruments require sterilization, not just disinfection."}, "medium"),
        ("A patient refuses radiographs. The office should:",
         {"a": "Force the exposures", "b": "Explain risks/benefits/limitations, document refusal, and determine if care can proceed safely", "c": "Fabricate fake images", "d": "Dismiss the concern as unimportant without discussion"},
         "b", "Respect autonomy with informed refusal documentation; some care may be deferred if unsafe without imaging.",
         {"a": "Force violates consent.", "c": "Fraudulent imaging is unethical/illegal.", "d": "Education is required."}, "hard"),
        ("Inventory control for nitrous oxide includes:",
         {"a": "Leaving tanks unsecured in public hallways", "b": "Securing cylinders, checking connections for leaks, and following scavenger system protocols", "c": "Using damaged regulators", "d": "Storing oxygen and fuel gases together unsafely"},
         "b", "Compressed gas safety and scavenging protect patients and staff.",
         {"a": "Unsecured tanks are hazardous.", "c": "Damaged equipment must be removed from service.", "d": "Incompatible storage is unsafe."}, "medium"),
        ("Which coding system is commonly used for reporting dental procedures?",
         {"a": "CDT codes", "b": "ZIP codes only", "c": "ICD alone for every dental procedure without CDT", "d": "UPC grocery barcodes"},
         "a", "ADA CDT codes report dental procedures for billing/documentation.",
         {"b": "ZIP is geographic.", "c": "Medical ICD may apply in some cases but CDT is dental procedure coding.", "d": "Retail barcodes are unrelated."}, "easy"),
        ("Professional ethics require that patient fees and treatment plans be:",
         {"a": "Hidden until after irreversible treatment", "b": "Discussed clearly before treatment when feasible", "c": "Based solely on the patient's appearance", "d": "Changed randomly after treatment without notice when not permitted"},
         "b", "Transparency about planned care and costs supports informed decisions.",
         {"a": "Surprise fees undermine trust/consent.", "c": "Discriminatory pricing is unethical.", "d": "Unauthorized changes are improper."}, "easy"),
        ("If a sterilization pouch indicator fails to change, the assistant should:",
         {"a": "Still use the instruments", "b": "Not use the load; reprocess and investigate per protocol", "c": "Wipe instruments and seat the patient", "d": "Ignore chemical indicators forever"},
         "b", "Failed indicators mean the load is not considered sterile.",
         {"a": "Unsafe.", "c": "Disinfection ≠ sterilization for critical items.", "d": "Indicators are required checks."}, "medium"),
        ("Recall systems in dentistry primarily help:",
         {"a": "Schedule preventive visits and periodontal maintenance", "b": "Cancel all future care", "c": "Replace home care entirely", "d": "Bill for services not rendered"},
         "a", "Recalls support ongoing prevention and disease control.",
         {"b": "Opposite of purpose.", "c": "Home care remains essential.", "d": "Billing for non-rendered care is fraud."}, "easy"),
        ("Cross-contamination is best prevented by:",
         {"a": "Using the same gloves for multiple patients", "b": "Hand hygiene, PPE changes, surface barriers, and instrument sterilization between patients", "c": "Never cleaning the operatory", "d": "Sharing needles after wiping"},
         "b", "Standard infection-control chains interrupt pathogen transmission.",
         {"a": "Gloves are single-patient.", "c": "Cleaning is required.", "d": "Needles are single-use."}, "easy"),
        ("Which statement about dental office HIPAA training is correct?",
         {"a": "Only the dentist needs any privacy awareness", "b": "Workforce members with PHI access need training appropriate to their roles", "c": "HIPAA never applies to dentistry", "d": "Passwords may be shared freely"},
         "b", "Covered dental entities must train workforce on privacy/security policies.",
         {"a": "All PHI handlers need training.", "c": "Dental PHI is covered.", "d": "Credential sharing is prohibited."}, "medium"),
        ("A patient complaint about rude staff should be handled by:",
         {"a": "Ignoring it", "b": "Listening, documenting, and following office resolution/escalation policy professionally", "c": "Arguing publicly in the waiting room", "d": "Altering the chart to hide the visit"},
         "b", "Professional complaint handling protects relationships and risk management.",
         {"a": "Ignored complaints escalate.", "c": "Public arguments breach professionalism/privacy.", "d": "Chart falsification is illegal."}, "hard"),
    ])
    return qs
