from __future__ import annotations

from ._common import pack


def build() -> list[dict]:
    e = "nbdhe-readiness-check"
    qs: list[dict] = []

    qs += pack(e, "sci-foundations", [
        ("Dental biofilm is best described as:",
         {"a": "A sterile salivary film only", "b": "A structured microbial community embedded in an extracellular matrix on teeth", "c": "Pure calcium phosphate crystals", "d": "Only food debris without bacteria"},
         "b", "Biofilm is a living microbial community in a matrix that drives caries and periodontal disease.",
         {"a": "Pellicle forms first but biofilm is microbial.", "c": "Mineral is calculus when calcified.", "d": "Bacteria are essential."}, "easy"),
        ("Streptococcus mutans contributes to caries mainly by:",
         {"a": "Producing acid from fermentable carbohydrates", "b": "Neutralizing plaque pH always", "c": "Forming enamel proteins", "d": "Increasing salivary flow dramatically"},
         "a", "Acidogenic/aciduric organisms like S. mutans demineralize enamel when sugars are frequent.",
         {"b": "They lower pH.", "c": "They do not form enamel matrix.", "d": "They do not meaningfully increase saliva."}, "easy"),
        ("Cementum covers:",
         {"a": "Crown enamel only", "b": "Anatomic root surface", "c": "Pulp chamber entirely as enamel", "d": "Gingival epithelium"},
         "b", "Cementum covers the root and anchors periodontal ligament fibers.",
         {"a": "Enamel covers the crown.", "c": "Pulp is soft tissue.", "d": "Epithelium is soft tissue."}, "easy"),
        ("The periodontal ligament's primary functions include:",
         {"a": "Producing enamel rods", "b": "Supporting the tooth, sensory input, and nutrient supply to cementum/bone interface", "c": "Forming amalgam", "d": "Secreting insulin"},
         "b", "PDL attaches tooth to bone, cushions forces, and provides proprioception/nutrition.",
         {"a": "Ameloblasts form enamel (developmental).", "c": "Amalgam is restorative.", "d": "Irrelevant."}, "medium"),
        ("Fluoride's caries-preventive mechanisms include:",
         {"a": "Making enamel more acid-soluble", "b": "Enhancing remineralization and inhibiting demineralization/bacterial enzymes", "c": "Eliminating the need for oral hygiene", "d": "Dissolving sealants immediately"},
         "b", "Fluoride favors fluorapatite-like mineral and can inhibit bacterial metabolism.",
         {"a": "It decreases solubility.", "c": "Hygiene remains essential.", "d": "Does not dissolve sealants as intended use."}, "easy"),
        ("IgA in saliva primarily contributes to:",
         {"a": "Systemic anaphylaxis only", "b": "Mucosal immune defense against oral microbes", "c": "Enamel maturation in adults", "d": "Formation of dental pulp stones always"},
         "b", "Secretory IgA is a key mucosal antibody in saliva.",
         {"a": "IgE is associated with type I hypersensitivity.", "c": "Not IgA's role.", "d": "Unrelated."}, "medium"),
        ("Which vitamin deficiency is classically linked to scurvy and impaired connective tissue?",
         {"a": "Vitamin C", "b": "Vitamin K only for enamel", "c": "Vitamin D as the sole cause of gingivitis always", "d": "Vitamin B12 for enamel rods"},
         "a", "Vitamin C is required for collagen synthesis; deficiency causes scurvy with gingival bleeding.",
         {"b": "Vit K relates to clotting factors.", "c": "Gingivitis is primarily biofilm-driven.", "d": "B12 deficiency causes other systemic signs."}, "medium"),
        ("The first permanent tooth to erupt in many children is often the:",
         {"a": "Maxillary canine", "b": "Mandibular first molar (around age 6)", "c": "Third molar at age 3", "d": "Maxillary lateral at birth"},
         "b", "Mandibular first permanent molars commonly erupt ~6 years (with lower centrals also early).",
         {"a": "Canines erupt later.", "c": "Third molars are late teens/adults.", "d": "Natal teeth are uncommon exceptions."}, "easy"),
        ("Calculus is:",
         {"a": "Mineralized dental biofilm", "b": "Pure salivary amylase crystals", "c": "Orthodontic wire residue only", "d": "Always sterile hydroxyapatite without microbes historically"},
         "a", "Calculus is calcified plaque that retains a rough surface for more biofilm.",
         {"b": "Not amylase crystals.", "c": "Not limited to ortho.", "d": "It harbors biofilm."}, "easy"),
        ("Dentin is produced by:",
         {"a": "Ameloblasts", "b": "Odontoblasts", "c": "Osteoclasts only", "d": "Cementoblasts exclusively for enamel"},
         "b", "Odontoblasts form dentin throughout life (primary/secondary/tertiary).",
         {"a": "Ameloblasts form enamel.", "c": "Osteoclasts resorb bone.", "d": "Cementoblasts form cementum."}, "easy"),
        ("Aerobic bacteria generally:",
         {"a": "Require oxygen for growth", "b": "Grow only without any oxygen", "c": "Are identical to viruses", "d": "Cannot exist in the oral cavity"},
         "a", "Aerobes need O2; anaerobes grow without O2; facultatives can do either.",
         {"b": "That describes obligate anaerobes.", "c": "Bacteria ≠ viruses.", "d": "Oral flora includes aerobes/anaerobes."}, "easy"),
        ("The critical pH at which enamel begins to demineralize is approximately:",
         {"a": "7.5", "b": "5.5 (approximate)", "c": "2.0 always exactly for all teeth", "d": "9.0"},
         "b", "Enamel demineralization commonly cited near pH ~5.5 (varies with fluoride/mineral).",
         {"a": "Neutral/alkaline favors remineralization.", "c": "Overstated absolute.", "d": "Alkaline does not demineralize enamel."}, "medium"),
        ("Leukocytes in gingival crevicular fluid primarily function to:",
         {"a": "Form enamel", "b": "Provide host defense against periodontal pathogens", "c": "Calcify plaque into gold", "d": "Produce salivary amylase"},
         "b", "PMNs and other leukocytes are key innate defenses in the sulcus.",
         {"a": "Not formative for enamel.", "c": "Nonsense.", "d": "Amylase is salivary gland product."}, "medium"),
        ("Which cranial nerve provides taste to the anterior two-thirds of the tongue?",
         {"a": "CN I", "b": "CN VII (chorda tympani)", "c": "CN XI", "d": "CN II"},
         "b", "Facial nerve via chorda tympani carries taste from anterior 2/3 tongue.",
         {"a": "Olfactory is smell.", "c": "Accessory is motor to SCM/trapezius.", "d": "Optic is vision."}, "hard"),
        ("Tertiary (reparative) dentin forms in response to:",
         {"a": "Pulp irritation such as caries or trauma", "b": "Toothbrush color changes", "c": "Wearing lipstick", "d": "Drinking room-temperature water once"},
         "a", "Odontoblasts/pulp respond to injury by depositing protective tertiary dentin.",
         {"b": "Irrelevant.", "c": "Irrelevant.", "d": "Not a stimulus for tertiary dentin."}, "medium"),
    ])

    qs += pack(e, "assessment", [
        ("Bleeding on probing most directly indicates:",
         {"a": "Perfect periodontal health always", "b": "Inflammation of gingival tissues", "c": "Only enamel caries", "d": "Successful implant osseointegration"},
         "b", "BOP is a clinical sign of gingival inflammation.",
         {"a": "Health shows little/no BOP.", "c": "Caries is hard-tissue disease.", "d": "Unrelated directly."}, "easy"),
        ("A periodontal probe measures:",
         {"a": "Caries depth in enamel only", "b": "Sulcus/pocket depth from gingival margin to junctional epithelium attachment level estimate", "c": "Pulp vitality exclusively", "d": "Salivary flow rate in mL/min precisely"},
         "b", "Probing depths assess periodontal pocketing as part of perio charting.",
         {"a": "Explorers/radiographs assess caries differently.", "c": "Vitality uses thermal/electric tests.", "d": "Sialometry measures flow."}, "easy"),
        ("Clinical attachment loss (CAL) requires knowledge of:",
         {"a": "Only tooth shade", "b": "Probing depth and position of the gingival margin relative to the CEJ", "c": "Patient's favorite floss flavor", "d": "Operatory temperature alone"},
         "b", "CAL = probing depth adjusted for gingival margin position vs CEJ.",
         {"a": "Shade is esthetic.", "c": "Irrelevant.", "d": "Irrelevant."}, "medium"),
        ("Furcation involvement class II generally means:",
         {"a": "No bone loss in furcation", "b": "Partial penetration into the furcation; probe does not pass through", "c": "Through-and-through furcation", "d": "Enamel pearl only"},
         "b", "Glickman II is cul-de-sac involvement; III is through-and-through.",
         {"a": "That is class I minimal/early or none.", "c": "That is class III.", "d": "Developmental anomaly, not furcation class."}, "hard"),
        ("Mobility grade 3 typically indicates:",
         {"a": "No movement", "b": "Severe mobility, often depressible in the socket", "c": "Physiologic mobility only", "d": "Movement of the TMJ disc only"},
         "b", "Grade 3 mobility is severe, including vertical depressibility.",
         {"a": "Grade 0.", "c": "Normal slight mobility.", "d": "Different joint assessment."}, "medium"),
        ("Which radiograph is most useful for detecting interproximal caries in posterior teeth?",
         {"a": "Panoramic alone always", "b": "Bitewing radiographs", "c": "Occlusal film of the chin only", "d": "Cephalometric for caries exclusively"},
         "b", "Bitewings best visualize posterior proximal contacts for caries.",
         {"a": "Panos have less proximal caries detail.", "c": "Occlusals serve other purposes.", "d": "Cephs are ortho/skeletal."}, "easy"),
        ("Gingival recession is measured as:",
         {"a": "Distance from CEJ to gingival margin when margin is apical to CEJ", "b": "Pocket depth only", "c": "Enamel thickness", "d": "Pulp chamber width"},
         "a", "Recession exposes root; quantified from CEJ to margin.",
         {"b": "PD alone misses recession contribution to CAL.", "c": "Not recession.", "d": "Not recession."}, "medium"),
        ("A black hairy tongue appearance is most associated with:",
         {"a": "Elongation of filiform papillae with pigment/debris", "b": "Enamel hypoplasia of molars", "c": "Pulp necrosis exclusively", "d": "Leukemia pathognomonically always"},
         "a", "Hairy tongue is hypertrophied filiform papillae with staining; often benign with predisposing factors.",
         {"b": "Different developmental defect.", "c": "Pulp status separate.", "d": "Not pathognomonic for leukemia."}, "medium"),
        ("Fremitus in dental assessment refers to:",
         {"a": "Tooth vibration/mobility palpable under occlusal function", "b": "Salivary duct stone only", "c": "Tongue-tie", "d": "A type of sealant"},
         "a", "Fremitus indicates occlusal trauma-related movement on function.",
         {"b": "Sialolithiasis is different.", "c": "Ankyloglossia.", "d": "Unrelated."}, "hard"),
        ("ASA physical status classification helps the hygienist:",
         {"a": "Choose toothpaste flavor", "b": "Estimate medical risk for dental care and need for modifications/consultation", "c": "Determine CDT codes automatically", "d": "Measure pocket depths"},
         "b", "ASA PS stratifies systemic risk for safe care planning.",
         {"a": "Irrelevant.", "c": "Coding is separate.", "d": "Probing is clinical measurement."}, "easy"),
        ("Pseudopockets are characterized by:",
         {"a": "Increased probing depth due to gingival enlargement without apical migration of attachment", "b": "Always severe CAL", "c": "Only occurring on implants", "d": "Enamel caries"},
         "a", "Gingival hyperplasia can deepen sulci without true attachment loss.",
         {"b": "True pockets involve attachment loss.", "c": "Can occur on natural teeth.", "d": "Hard tissue disease."}, "hard"),
        ("The best instrument to detect supragingival calculus visually/tactilely often includes:",
         {"a": "A periodontal probe and explorer with air drying", "b": "A curing light only", "c": "A matrix band", "d": "A prophy angle without assessment"},
         "a", "Explorers and dried surfaces reveal calculus; probes chart perio status.",
         {"b": "Curing lights polymerize resin.", "c": "Matrices for restorations.", "d": "Polishing without assessment misses deposits."}, "easy"),
        ("Attrition is tooth wear from:",
         {"a": "Tooth-to-tooth contact", "b": "Acidic dissolution only", "c": "Aggressive toothbrushing abrasion exclusively", "d": "Dental floss cuts only"},
         "a", "Attrition is occlusal/incisal wear from opposing teeth; erosion is chemical; abrasion is mechanical foreign objects.",
         {"b": "Erosion.", "c": "Abrasion.", "d": "Not the definition of attrition."}, "medium"),
        ("A positive percussion test (pain on tapping) suggests:",
         {"a": "Possible periapical inflammation", "b": "Healthy pulp with certainty", "c": "Only gingival health", "d": "Perfect osseointegration"},
         "a", "Percussion sensitivity often indicates apical PDL inflammation.",
         {"b": "Does not confirm pulp health.", "c": "Different tissues.", "d": "Unrelated."}, "medium"),
        ("When assessing tobacco use history, the hygienist should:",
         {"a": "Avoid asking to save time", "b": "Document type/amount/duration and provide cessation resources as indicated", "c": "Recommend increasing use before scaling", "d": "Assume all patients never used tobacco"},
         "b", "Tobacco assessment is essential for perio risk and oral cancer screening counseling.",
         {"a": "Missed risk factor.", "c": "Harmful advice.", "d": "Assumption is unsafe."}, "easy"),
    ])

    qs += pack(e, "planning-impl", [
        ("The primary objective of nonsurgical periodontal therapy is to:",
         {"a": "Eliminate all teeth prophylactically", "b": "Reduce biofilm and calculus to resolve inflammation and facilitate healing", "c": "Place large amalgams on all molars", "d": "Avoid patient education"},
         "b", "Scaling/root planing and hygiene aim to control infection and inflammation.",
         {"a": "Extraction is not primary NSPT goal.", "c": "Restorative is separate.", "d": "Education is central."}, "easy"),
        ("Ultrasonic instrumentation advantages include:",
         {"a": "No need for water coolant", "b": "Efficient calculus removal with lavage and less repetitive strain than hand scaling alone in many cases", "c": "Complete replacement of radiographs", "d": "Sterilizing the pocket permanently after one pass"},
         "b", "Power scalers remove deposits efficiently with irrigation; hand instruments still have roles.",
         {"a": "Water cools and lavages.", "c": "Imaging remains separate.", "d": "Biofilm returns without maintenance."}, "medium"),
        ("Gracey curets are area-specific because:",
         {"a": "They have one cutting edge offset for specific tooth surfaces", "b": "They cut enamel only", "c": "They are used exclusively for amalgam carving", "d": "They cannot be sharpened"},
         "a", "Graceys have a single usable cutting edge and shank designs for designated surfaces.",
         {"b": "They instrument root/cementum/calculus.", "c": "Carvers are restorative.", "d": "They require sharpening."}, "medium"),
        ("Local delivery antimicrobials (e.g., chips/gels) are considered when:",
         {"a": "All patients regardless of diagnosis", "b": "Selected residual deep pockets after thorough debridement as adjuncts", "c": "Replacing all mechanical therapy forever", "d": "Treating enamel hypoplasia"},
         "b", "Local antimicrobials adjunct selected nonresponding sites after mechanical therapy.",
         {"a": "Not universal first-line alone.", "c": "Mechanical therapy remains foundation.", "d": "Wrong indication."}, "hard"),
        ("Sharpening curets maintains:",
         {"a": "A dull rounded toe intentionally", "b": "A sharp cutting edge for efficient calculus removal with less lateral pressure", "c": "Only the painted handle color", "d": "Sterility without autoclaving"},
         "b", "Sharp instruments improve tactile sense and reduce force/trauma.",
         {"a": "Dull edges burnish calculus.", "c": "Cosmetic only.", "d": "Sharpening ≠ sterilization."}, "easy"),
        ("Selective polishing means:",
         {"a": "Polish every tooth aggressively every visit always", "b": "Polish only stained/plaque-retentive areas as needed, avoiding unnecessary enamel removal", "c": "Never remove extrinsic stain", "d": "Use pumice on implants with steel cups only"},
         "b", "Evidence-based polishing is selective to preserve tooth structure/fluoride-rich enamel.",
         {"a": "Overpolishing can remove fluoride-rich enamel.", "c": "Stain removal may be indicated.", "d": "Implants need compatible nonabrasive protocols."}, "medium"),
        ("Fluoride varnish after scaling is placed to:",
         {"a": "Increase caries risk", "b": "Aid remineralization and reduce sensitivity/caries risk when indicated", "c": "Replace periodontal charting", "d": "Etch dentin for sealants only"},
         "b", "Professionally applied fluoride supports prevention and hypersensitivity management.",
         {"a": "Opposite effect.", "c": "Charting is assessment.", "d": "Different procedure."}, "easy"),
        ("For a patient with asthma who uses an inhaler, a reasonable care modification is:",
         {"a": "Confiscate the inhaler", "b": "Ensure inhaler availability, reduce aerosols/stress, and confirm medical stability", "c": "Use the strongest scents possible", "d": "Schedule only when wheezing severely"},
         "b", "Keep rescue meds available and minimize triggers; defer elective care if unstable.",
         {"a": "Inhaler must be accessible.", "c": "Strong scents can trigger.", "d": "Unstable patients need medical management first."}, "medium"),
        ("Root planing aims to:",
         {"a": "Create glassy root surfaces by removing cementum excessively as the only goal historically overemphasized", "b": "Remove calculus and endotoxin-contaminated cementum sufficiently to allow tissue healing (modern conservative approach)", "c": "Cut enamel rods for sealants", "d": "Extract the tooth roots"},
         "b", "Modern root planing focuses on deposit removal and biocompatible root surfaces, not aggressive cementum removal.",
         {"a": "Over-instrumentation is discouraged.", "c": "Wrong procedure.", "d": "Not extraction."}, "hard"),
        ("Air polishing with glycine or erythritol powders is often preferred subgingivally because:",
         {"a": "Sodium bicarbonate is always gentler on root cementum", "b": "Finer low-abrasive powders are less damaging to root surfaces/implants than traditional bicarb in many protocols", "c": "They sterilize bone", "d": "They replace antibiotics always"},
         "b", "Low-abrasive powders support biofilm management with less root damage than coarse bicarb.",
         {"a": "Bicarb is more abrasive on roots.", "c": "Not sterilization of bone.", "d": "Not antibiotic replacement."}, "hard"),
        ("Oral hygiene instruction should be:",
         {"a": "Generic and never demonstrated", "b": "Individualized, demonstrated, and evaluated for patient skill", "c": "Provided only after periodontitis reaches stage IV", "d": "Limited to mouthwash advertising"},
         "b", "Effective OHI is personalized with teach-back and device selection.",
         {"a": "Demonstration improves outcomes.", "c": "Prevention starts early.", "d": "Mechanical plaque control is primary."}, "easy"),
        ("When using local anesthesia for scaling, aspiration is performed to:",
         {"a": "Increase injection pain", "b": "Reduce risk of intravascular injection", "c": "Mix anesthetic with blood intentionally", "d": "Sharpen the needle"},
         "b", "Aspiration helps detect vessel entry before depositing anesthetic.",
         {"a": "Opposite intent.", "c": "Not the goal.", "d": "Unrelated."}, "easy"),
        ("Implant maintenance instrumentation should avoid:",
         {"a": "Plastic/compatible scalers and low-abrasive powders as indicated", "b": "Stainless steel curets that scratch titanium surfaces", "c": "Assessing peri-implant probing carefully", "d": "Reviewing home care"},
         "b", "Metal instruments can roughen implant surfaces and promote biofilm.",
         {"a": "Compatible instruments are preferred.", "c": "Assessment is required.", "d": "Home care is essential."}, "medium"),
        ("Desensitizing agents (e.g., potassium nitrate, fluoride) work by:",
         {"a": "Increasing dentinal tubule fluid flow always", "b": "Occluding tubules or altering nerve excitability to reduce hypersensitivity", "c": "Removing enamel completely", "d": "Killing the pulp intentionally"},
         "b", "Sensitivity products block tubules or calm pulpal nerve response.",
         {"a": "Hydrodynamic theory links flow to pain; agents reduce it.", "c": "Harmful.", "d": "Not the goal."}, "medium"),
        ("A treatment plan for gingivitis typically emphasizes:",
         {"a": "Immediate full-mouth extraction", "b": "Biofilm control, professional debridement, and reevaluation", "c": "Systemic chemotherapy for all cases", "d": "Ignoring bleeding"},
         "b", "Gingivitis is reversible with plaque control and debridement.",
         {"a": "Excessive.", "c": "Not indicated for routine gingivitis.", "d": "Bleeding guides therapy."}, "easy"),
    ])

    qs += pack(e, "eval-ethics", [
        ("After nonsurgical periodontal therapy, reevaluation is typically scheduled to:",
         {"a": "Assess tissue response and residual pocketing for further care decisions", "b": "Avoid measuring anything again", "c": "Guarantee disease never returns", "d": "Replace the medical history permanently"},
         "a", "Reevaluation guides maintenance vs further therapy needs.",
         {"b": "Measurements are essential.", "c": "Maintenance is lifelong for many.", "d": "History still updates."}, "easy"),
        ("Periodontal maintenance intervals are commonly:",
         {"a": "Every 10 years for all patients", "b": "Individualized, often 3–4 months for periodontitis patients", "c": "Only when the patient has pain", "d": "Never needed after one cleaning"},
         "b", "Risk-based maintenance (often 3–4 months) supports long-term stability.",
         {"a": "Too infrequent for perio patients.", "c": "Pain is a late sign.", "d": "Ongoing care needed."}, "medium"),
        ("Informed consent for periodontal therapy must include:",
         {"a": "Risks, benefits, alternatives, and expected outcomes in understandable language", "b": "Only the brand of floss", "c": "A guarantee of cure", "d": "No opportunity for questions"},
         "a", "Ethical/legal consent requires disclosure and voluntary agreement.",
         {"b": "Insufficient.", "c": "Guarantees are inappropriate.", "d": "Questions are required."}, "easy"),
        ("A hygienist who practices outside the state practice act is:",
         {"a": "Demonstrating best practice always", "b": "Engaging in illegal practice that risks license and patient safety", "c": "Exempt from all laws", "d": "Only a billing issue"},
         "b", "Scope of practice is legally defined; exceeding it is illegal and unsafe.",
         {"a": "Not best practice.", "c": "Laws apply.", "d": "It is a legal/clinical issue."}, "easy"),
        ("Confidentiality requires that a hygienist:",
         {"a": "Discuss patients in elevators loudly", "b": "Share PHI only for treatment/payment/operations or with authorization as permitted", "c": "Post before/after photos without consent", "d": "Leave charts open in waiting rooms"},
         "b", "HIPAA and ethics limit PHI disclosures.",
         {"a": "Impermissible.", "c": "Needs authorization.", "d": "Unsecured PHI breach."}, "easy"),
        ("Community water fluoridation is considered:",
         {"a": "A population-level caries prevention measure supported by public health evidence", "b": "A cause of rampant caries", "c": "Illegal in all U.S. states", "d": "Useful only for adults over 80"},
         "a", "Water fluoridation is a major public health prevention strategy.",
         {"b": "It prevents caries.", "c": "Widely implemented where adopted.", "d": "Benefits children and adults."}, "medium"),
        ("When evaluating sealant retention at recall, failure indicated by:",
         {"a": "Intact sealant margins", "b": "Partial/complete loss or catch with explorer indicating need for repair/replacement", "c": "Shiny cured surface only", "d": "Patient preference for gum flavor"},
         "b", "Lost or leaking sealants need repair to restore protection.",
         {"a": "Intact is success.", "c": "Appearance alone may miss defects.", "d": "Irrelevant."}, "medium"),
        ("Cultural competence in dental hygiene care includes:",
         {"a": "Ignoring language barriers", "b": "Adapting communication and care respectfully to patient cultural needs", "c": "Assuming all patients share identical beliefs", "d": "Refusing interpreters when needed"},
         "b", "Culturally responsive care improves understanding and outcomes.",
         {"a": "Barriers must be addressed.", "c": "Beliefs vary.", "d": "Interpreters support informed care."}, "easy"),
        ("A true negative screening test result means:",
         {"a": "Disease present, test negative", "b": "Disease absent, test negative", "c": "Disease present, test positive", "d": "Test invalid always"},
         "b", "True negative: correctly identifies non-disease.",
         {"a": "False negative.", "c": "True positive.", "d": "Not the definition."}, "hard"),
        ("Index used for community caries experience in permanent teeth is often:",
         {"a": "DMFT/DMFS", "b": "BMI only", "c": "INR", "d": "HbA1c exclusively"},
         "a", "DMFT/S measures decayed, missing, filled teeth/surfaces.",
         {"b": "Body mass index.", "c": "Coagulation.", "d": "Glycemic control."}, "medium"),
        ("If a patient declines a recommended radiograph, the hygienist should:",
         {"a": "Proceed with radiation anyway", "b": "Explain rationale/risks of refusal, document, and inform the dentist; modify care as needed", "c": "Fabricate a chart entry of images taken", "d": "Discharge without any discussion"},
         "b", "Respect autonomy with informed refusal and appropriate care adjustments.",
         {"a": "Violates consent.", "c": "Fraud.", "d": "Education/documentation required."}, "medium"),
        ("Evaluation of oral hygiene effectiveness is best done by:",
         {"a": "Asking only 'Do you brush?' without observation", "b": "Plaque scores/disclosing and skill demonstration review", "c": "Never looking at the teeth", "d": "Measuring only tooth shade"},
         "b", "Objective plaque assessment and coachable feedback improve outcomes.",
         {"a": "Self-report is insufficient alone.", "c": "Assessment required.", "d": "Shade ≠ hygiene."}, "easy"),
        ("Nonmaleficence in dental ethics means:",
         {"a": "Do no harm / minimize harm", "b": "Maximize profit only", "c": "Always treat without consent", "d": "Hide adverse events"},
         "a", "Nonmaleficence obligates avoiding unnecessary harm.",
         {"b": "Not an ethical principle definition.", "c": "Violates autonomy.", "d": "Transparency required."}, "easy"),
        ("A hygienist suspects intimate partner violence. The appropriate action is to:",
         {"a": "Ignore injuries", "b": "Follow state reporting laws, document objectively, and provide resources/referrals per protocol", "c": "Confront the alleged abuser in the waiting room", "d": "Post suspicions online"},
         "b", "Safety, documentation, legal mandates, and resources guide response.",
         {"a": "Unsafe/unethical.", "c": "Can escalate danger.", "d": "Breaches privacy."}, "hard"),
        ("Success of periodontal therapy is best judged by:",
         {"a": "Patient compliments alone", "b": "Reduced BOP, improved attachment/probing trends, and controllable biofilm", "c": "Whiter teeth only", "d": "Speed of the appointment"},
         "b", "Clinical periodontal parameters and inflammation control define therapeutic success.",
         {"a": "Subjective only.", "c": "Esthetics ≠ perio health.", "d": "Speed is not an outcome metric."}, "medium"),
    ])
    return qs
