from __future__ import annotations

from ._common import pack


def build() -> list[dict]:
    e = "rd-exam-readiness-check"
    qs: list[dict] = []

    qs += pack(e, "principles", [
        ("Which macronutrient provides approximately 4 kcal/g?",
         {"a": "Alcohol", "b": "Carbohydrate and protein", "c": "Fat", "d": "Water"},
         "b", "Carbohydrate and protein yield ~4 kcal/g; fat ~9; alcohol ~7; water 0.",
         {"a": "Alcohol ~7 kcal/g.", "c": "Fat ~9 kcal/g.", "d": "Water provides no calories."}, "easy"),
        ("The RDA is defined as:",
         {"a": "Average daily intake sufficient to meet nutrient needs of nearly all (97–98%) healthy individuals in a group", "b": "Minimum intake to prevent death only", "c": "Upper limit before toxicity for all nutrients identically", "d": "A restaurant portion size standard"},
         "a", "RDA covers nearly all healthy people in a life-stage/sex group; AI used when RDA cannot be set.",
         {"b": "Too low a standard.", "c": "That resembles UL concept, not RDA.", "d": "Unrelated."}, "easy"),
        ("Which lipoprotein is primarily responsible for reverse cholesterol transport to the liver?",
         {"a": "LDL", "b": "HDL", "c": "Chylomicrons only", "d": "VLDL only"},
         "b", "HDL participates in reverse cholesterol transport; LDL delivers cholesterol to tissues.",
         {"a": "LDL is atherogenic forward transport.", "c": "Chylomicrons carry dietary TG.", "d": "VLDL carries endogenous TG."}, "medium"),
        ("Nitrogen balance is roughly equilibrium when:",
         {"a": "Protein intake nitrogen equals nitrogen losses", "b": "Only carbohydrate is consumed", "c": "Fat intake is zero", "d": "Water intake is high"},
         "a", "N balance ≈ intake − (urine/feces/misc losses); equilibrium in maintenance.",
         {"b": "CHO lacks nitrogen.", "c": "Fat lacks N.", "d": "Hydration ≠ N balance."}, "medium"),
        ("Which vitamin is fat-soluble?",
         {"a": "Vitamin C", "b": "Vitamin A", "c": "Thiamin", "d": "Folate"},
         "b", "Fat-soluble: A, D, E, K; water-soluble: B vitamins and C.",
         {"a": "Water-soluble.", "c": "Water-soluble B1.", "d": "Water-soluble B9."}, "easy"),
        ("Glycogen is stored primarily in:",
         {"a": "Adipose only", "b": "Liver and skeletal muscle", "c": "Bone cortex", "d": "Hair shafts"},
         "b", "Liver glycogen maintains blood glucose; muscle glycogen fuels local work.",
         {"a": "Adipose stores TG.", "c": "Bone mineral storage differs.", "d": "Not glycogen stores."}, "easy"),
        ("The glycemic index ranks foods by:",
         {"a": "Protein quality score", "b": "Blood glucose response relative to a reference carbohydrate", "c": "Sodium content only", "d": "Vitamin D content"},
         "b", "GI compares postprandial glucose AUC to a reference (glucose/white bread).",
         {"a": "PDCAAS/DIAAS for protein.", "c": "Mineral content separate.", "d": "Micronutrient separate."}, "medium"),
        ("Which amino acids are essential for adults?",
         {"a": "Alanine and glutamate only", "b": "Leucine, lysine, and other indispensable amino acids that must come from diet", "c": "All amino acids are nonessential", "d": "Only glycine"},
         "b", "Indispensable AAs (e.g., Leu, Lys, Met, Thr, Trp, Phe, Val, Ile, His) must be dietary.",
         {"a": "Those are dispensable.", "c": "False.", "d": "Glycine is dispensable."}, "medium"),
        ("Basal metabolic rate (BMR) is most strongly influenced by:",
         {"a": "Hair color", "b": "Lean body mass", "c": "Favorite cuisine", "d": "Shoe size alone"},
         "b", "Fat-free mass is the largest determinant of resting energy expenditure.",
         {"a": "Irrelevant.", "c": "Irrelevant.", "d": "Proxy at best, not causal."}, "easy"),
        ("Which mineral is a major intracellular cation?",
         {"a": "Sodium", "b": "Potassium", "c": "Chloride only extracellular exclusively without exception", "d": "Iodine as the main ICF cation"},
         "b", "K+ dominates intracellular fluid; Na+ extracellular.",
         {"a": "Main ECF cation.", "c": "Cl− is major ECF anion.", "d": "Iodine is a trace element for thyroid."}, "easy"),
        ("Transamination of amino acids requires which vitamin cofactor?",
         {"a": "Vitamin B6 (PLP)", "b": "Vitamin C only", "c": "Vitamin K only", "d": "Vitamin E only"},
         "a", "Pyridoxal phosphate is essential for aminotransferase reactions.",
         {"b": "Antioxidant/collagen roles.", "c": "Clotting factors.", "d": "Antioxidant lipid protection."}, "hard"),
        ("Dietary Reference Intake Tolerable Upper Intake Level (UL) indicates:",
         {"a": "Highest usual intake unlikely to pose risk of adverse effects for most people", "b": "Recommended therapeutic megadose for disease", "c": "Minimum to prevent deficiency", "d": "Athletic doping threshold"},
         "a", "UL guides safe upper habitual intake from food/supplements.",
         {"b": "Not a treatment dose.", "c": "That is closer to EAR/RDA concepts.", "d": "Unrelated."}, "medium"),
        ("Which statement about soluble fiber is correct?",
         {"a": "It may help lower LDL cholesterol and blunt postprandial glucose", "b": "It has no effect on lipids or glucose", "c": "It is identical to elemental calcium", "d": "It increases heme iron absorption always"},
         "a", "Viscous soluble fibers (oats, barley, psyllium) can improve lipids/glycemia.",
         {"b": "Evidence supports benefits.", "c": "Different nutrient.", "d": "Phytates/polyphenols may inhibit nonheme iron."}, "medium"),
        ("Ketone bodies increase when:",
         {"a": "Carbohydrate availability is very low and fat oxidation rises (e.g., fasting, low-CHO diets)", "b": "Protein intake is zero and CHO is abundant", "c": "Water intake doubles", "d": "Vitamin C is supplemented"},
         "a", "Low insulin/CHO leads to hepatic ketogenesis from fatty acids.",
         {"b": "Abundant CHO suppresses ketosis.", "c": "Hydration unrelated directly.", "d": "Unrelated."}, "easy"),
        ("Which assessment method estimates body fat using density principles historically?",
         {"a": "Hydrostatic weighing", "b": "24-hour diet recall alone", "c": "Blood pressure cuff", "d": "Urine dipstick"},
         "a", "Underwater weighing estimates body density to derive %fat (with assumptions).",
         {"b": "Dietary intake method.", "c": "Cardiovascular vital.", "d": "Urinalysis."}, "hard"),
    ])

    qs += pack(e, "nutrition-care", [
        ("The Nutrition Care Process steps in order are:",
         {"a": "Intervention, assessment, diagnosis, monitoring", "b": "Assessment, nutrition diagnosis, intervention, monitoring/evaluation", "c": "Billing, coding, collection, appeal", "d": "Screening only forever"},
         "b", "AND NCP: ADIME — assess, diagnose, intervene, monitor/evaluate.",
         {"a": "Wrong order.", "c": "Administrative cycle.", "d": "Screening precedes full NCP but is not the whole process."}, "easy"),
        ("A PES statement includes:",
         {"a": "Problem, Etiology, Signs/Symptoms", "b": "Price, Expense, Salary", "c": "Protein, Energy, Sodium only always", "d": "Physician, EMT, Surgeon"},
         "a", "Nutrition diagnoses are written as PES statements.",
         {"b": "Nonsense.", "c": "Nutrients may appear in signs but PES is structured differently.", "d": "Roles unrelated."}, "easy"),
        ("For a patient with diabetes, medical nutrition therapy commonly emphasizes:",
         {"a": "Consistent carbohydrate intake pattern individualized to meds/activity", "b": "Complete elimination of all carbohydrates forever for every patient", "c": "Unlimited sugar-sweetened beverages", "d": "Avoiding all dietary fiber"},
         "a", "Individualized CHO distribution and quality support glycemic control.",
         {"b": "Not required for all; sustainability matters.", "c": "SSBs worsen glycemia.", "d": "Fiber is beneficial."}, "easy"),
        ("In chronic kidney disease stage 5 on hemodialysis, protein recommendations are generally:",
         {"a": "Lower than pre-dialysis restrictions always without assessment", "b": "Higher than typical pre-dialysis needs to account for dialytic losses (individualized)", "c": "Zero protein", "d": "Identical to acute gout diet only"},
         "b", "HD patients often need ~1.0–1.2+ g/kg protein (per KDOQI/individualization) vs lower pre-dialysis sometimes.",
         {"a": "Often opposite direction vs pre-dialysis.", "c": "Unsafe.", "d": "Different disease."}, "hard"),
        ("Refeeding syndrome risk is highest when:",
         {"a": "Aggressively refeeding a severely malnourished patient, causing shifts of P, K, Mg", "b": "Giving water only to a well-nourished athlete", "c": "Using the Mediterranean diet in healthy adults", "d": "Taking a daily multivitamin at RDA levels"},
         "a", "Insulin-driven uptake of electrolytes/phosphate can cause life-threatening hypophosphatemia.",
         {"b": "Low risk.", "c": "Healthy pattern.", "d": "Usual MVI risk low."}, "medium"),
        ("A clear liquid diet typically includes:",
         {"a": "Broth, gelatin, clear juices, tea/coffee without cream", "b": "Steak and potatoes", "c": "Whole nuts", "d": "Ice cream sundaes as the definition"},
         "a", "Clear liquids leave minimal residue and are transparent at room temperature.",
         {"b": "Regular diet.", "c": "Not clear liquid.", "d": "Full liquids/soft may include dairy desserts."}, "easy"),
        ("BMI of 32 kg/m² is classified as:",
         {"a": "Underweight", "b": "Obesity class I", "c": "Normal weight", "d": "Severe thinness exclusively"},
         "b", "BMI 30–34.9 = obesity class I (adult standard).",
         {"a": "<18.5.", "c": "18.5–24.9.", "d": "Not applicable."}, "easy"),
        ("Enteral nutrition is preferred over parenteral when:",
         {"a": "The GI tract is functional and accessible", "b": "The gut is completely nonfunctional and inaccessible", "c": "Only for vitamin K deficiency IM shots", "d": "Patient refuses all tubes and IV and oral intake is adequate"},
         "a", "If the gut works, use it — EN supports mucosal integrity and has fewer infectious complications than PN generally.",
         {"b": "Indication for PN.", "c": "Wrong modality framing.", "d": "Oral diet preferred if adequate."}, "medium"),
        ("Which finding supports a diagnosis of malnutrition using AND/ASPEN characteristics?",
         {"a": "Unintentional weight loss, loss of muscle/fat, fluid accumulation, reduced intake/energy", "b": "High albumin alone always proving excellent nutrition", "c": "Normal intake and stable weight with high fitness", "d": "Preferred dessert choice"},
         "a", "Malnutrition diagnosis uses clinical characteristics (intake, weight, muscle/fat, fluid, function), not albumin alone.",
         {"b": "Albumin is a poor standalone nutrition marker (acute phase).", "c": "Not malnutrition.", "d": "Irrelevant."}, "medium"),
        ("For heart failure with fluid retention, MNT often includes:",
         {"a": "Sodium restriction individualized and fluid management as indicated", "b": "High sodium convenience foods liberally", "c": "Encouraging 10 L fluid/day routinely", "d": "Eliminating all potassium-rich foods always"},
         "a", "Na± fluid restriction and diet quality support volume control with meds.",
         {"b": "Worsens retention.", "c": "May worsen overload.", "d": "K+ management depends on drugs/renal function."}, "medium"),
        ("Celiac disease requires lifelong avoidance of:",
         {"a": "Gluten (wheat, barley, rye)", "b": "All carbohydrates", "c": "All fats", "d": "Lactose only as the sole treatment"},
         "a", "Gluten-free diet is the primary therapy for celiac disease.",
         {"b": "Unnecessary.", "c": "Unnecessary.", "d": "Secondary lactose intolerance may occur but gluten free is core."}, "easy"),
        ("A nutrition-focused physical exam may assess:",
         {"a": "Temporal wasting, orbital fat pads, muscle at clavicle/shoulder, edema", "b": "Only serum sodium", "c": "Only insurance status", "d": "Only food preferences without exam"},
         "a", "NFPE evaluates fat/muscle stores and fluid clinically.",
         {"b": "Lab, not NFPE.", "c": "Admin.", "d": "Incomplete."}, "medium"),
        ("Dumping syndrome dietary management often includes:",
         {"a": "Small frequent meals, limit simple sugars, separate liquids from solids", "b": "Large high-sugar liquids with meals", "c": "Drinking 1 L juice with every meal", "d": "Lying flat never after meals as the only advice without diet change"},
         "a", "Slower transit strategies reduce osmotic fluid shifts after gastric surgery.",
         {"b": "Provokes dumping.", "c": "Provokes dumping.", "d": "Positioning may help but diet is central."}, "hard"),
        ("Indirect calorimetry estimates energy expenditure by measuring:",
         {"a": "Oxygen consumption and carbon dioxide production", "b": "Urine ketones only", "c": "Skinfold calipers only", "d": "Food frequency questionnaires only"},
         "a", "REE from VO2/VCO2 via Weir equation principles.",
         {"b": "Metabolic state clue only.", "c": "Body composition method.", "d": "Intake method."}, "hard"),
        ("In pressure injury healing, nutrition priorities often include:",
         {"a": "Adequate energy and protein, correct deficiencies, manage hydration", "b": "Severe protein restriction for all patients", "c": "Vitamin A megadoses without assessment always", "d": "NPO indefinitely"},
         "a", "Wound healing needs calories, protein, micronutrients, and hydration individualized.",
         {"b": "Opposite usually.", "c": "Toxicity risk; assess first.", "d": "Feeding needed if gut works."}, "easy"),
    ])

    qs += pack(e, "foodservice", [
        ("HACCP focuses on:",
         {"a": "Identifying critical control points to prevent food safety hazards", "b": "Menu esthetics only", "c": "Employee uniforms fashion", "d": "Raising food temperatures into the danger zone intentionally"},
         "a", "HACCP is a preventive food safety system built around CCPs and critical limits.",
         {"b": "Not primary focus.", "c": "Irrelevant.", "d": "Danger zone promotes pathogens."}, "easy"),
        ("The temperature danger zone for bacterial growth is commonly cited as:",
         {"a": "41–135°F (5–57°C)", "b": "0–10°F", "c": "Above 165°F only as danger", "d": "Frozen solid at 0°F as danger zone"},
         "a", "US food code danger zone ~41–135°F; minimize time in range.",
         {"b": "Freezing slows growth.", "c": "Cooking temps kill pathogens.", "d": "Freezing is for preservation."}, "easy"),
        ("FIFO inventory means:",
         {"a": "First in, first out — older stock used first", "b": "First in, forever stored", "c": "Fill in for others randomly", "d": "Freeze immediately, forget order"},
         "a", "FIFO rotates stock to reduce spoilage/expiration risk.",
         {"b": "Opposite of good control.", "c": "Not the acronym meaning.", "d": "Not FIFO."}, "easy"),
        ("A standardized recipe is important because it:",
         {"a": "Ensures consistent yield, quality, cost, and nutrient content", "b": "Prevents any cooking", "c": "Eliminates the need for receiving checks", "d": "Replaces sanitation SOPs"},
         "a", "Standardization supports quality, costing, and allergen/nutrition accuracy.",
         {"b": "Recipes guide cooking.", "c": "Receiving still needed.", "d": "Sanitation separate."}, "easy"),
        ("Cross-contamination is best prevented by:",
         {"a": "Using the same cutting board for raw chicken then salad greens without cleaning", "b": "Separating raw and ready-to-eat foods and sanitizing surfaces/equipment", "c": "Storing raw meat above ready-to-eat foods in the fridge", "d": "Wiping hands on apron instead of washing"},
         "b", "Separation, cleaning/sanitizing, and hand hygiene prevent pathogen transfer.",
         {"a": "Classic contamination route.", "c": "Drip risk — store raw below RTE.", "d": "Inadequate hygiene."}, "medium"),
        ("Cook-chill food production involves:",
         {"a": "Cooking, rapid chilling, refrigerated storage, then rethermalization for service", "b": "Serving all food raw always", "c": "Holding food at 100°F for days", "d": "Skipping temperature logs"},
         "a", "Cook-chill is a cook–rapid cool–store–reheat system used in many healthcare FSDs.",
         {"b": "Not accurate.", "c": "Danger zone abuse.", "d": "Logs required."}, "medium"),
        ("Which is an example of a critical control point for poultry?",
         {"a": "Cooking to a safe internal temperature (e.g., 165°F) verified by thermometer", "b": "Choosing plate color", "c": "Menu font size", "d": "Tray pad design only"},
         "a", "Pathogen kill step at cooking is a classic CCP.",
         {"b": "Not a hazard control.", "c": "Not CCP.", "d": "Not CCP."}, "easy"),
        ("Food cost percentage is calculated as:",
         {"a": "(Cost of food used / foodsales revenue) × 100", "b": "Labor hours × wage only", "c": "Census × tray factor without cost", "d": "Number of recipes on file"},
         "a", "Food cost % = food cost ÷ sales (or equivalent revenue base).",
         {"b": "Labor cost metric.", "c": "Production forecasting.", "d": "Inventory count of recipes."}, "medium"),
        ("A cycle menu helps foodservice by:",
         {"a": "Repeating a planned set of menus over a period to streamline purchasing and production", "b": "Serving identical meals every day forever without variation planning", "c": "Eliminating allergen identification", "d": "Avoiding production sheets"},
         "a", "Cycle menus balance variety with operational efficiency.",
         {"b": "Cycles include planned variation.", "c": "Allergens still managed.", "d": "Production sheets still used."}, "easy"),
        ("Calibrated food thermometers should be checked using:",
         {"a": "Ice-point (32°F) and/or boiling-point methods as appropriate", "b": "Guessing by touch", "c": "Room air only without reference", "d": "Never — factory forever accurate"},
         "a", "Calibration verification ensures accurate CCP monitoring.",
         {"b": "Unsafe.", "c": "No reference standard.", "d": "Drift occurs."}, "medium"),
        ("Modified texture diets (e.g., IDDSI) are used to:",
         {"a": "Match food/drink textures to swallowing safety needs", "b": "Increase choking risk intentionally", "c": "Replace speech therapy forever", "d": "Eliminate all protein"},
         "a", "Texture modification supports safe swallowing with interdisciplinary dysphagia care.",
         {"b": "Opposite goal.", "c": "SLP collaboration continues.", "d": "Nutrition still required."}, "easy"),
        ("Receiving criteria for refrigerated potentially hazardous foods include:",
         {"a": "Accepting if ≤41°F (or per code) with intact packaging and proper dating", "b": "Accepting warm deliveries without temperature checks", "c": "Accepting dented swollen cans of low-acid food without question", "d": "Storing deliveries on the floor in the hallway"},
         "a", "Temperature, integrity, and dating checks protect safety/quality.",
         {"b": "Reject temperature abuse.", "c": "Botulism risk signs — reject.", "d": "Sanitation violation."}, "medium"),
        ("Plate waste studies help managers:",
         {"a": "Evaluate acceptance and adjust menus/portions", "b": "Ignore patient preferences", "c": "Increase overproduction intentionally", "d": "Eliminate sanitation"},
         "a", "Waste analysis informs forecasting, palatability, and cost control.",
         {"b": "Opposite of QI.", "c": "Increases cost/waste.", "d": "Unrelated."}, "easy"),
        ("Which pathogen is commonly associated with undercooked ground beef and severe illness including HUS risk?",
         {"a": "Shiga toxin–producing E. coli (e.g., O157:H7)", "b": "Norovirus only from beef fat", "c": "Clostridium botulinum from fresh lettuce always", "d": "Rhinovirus"},
         "a", "STEC from undercooked ground beef is a classic outbreak pathogen.",
         {"b": "Norovirus is viral, often person-to-person/ready-to-eat.", "c": "Botulism from anaerobic improperly canned foods.", "d": "Respiratory virus."}, "hard"),
        ("Batch cooking close to service time primarily helps:",
         {"a": "Maintain quality and reduce holding time in the danger zone", "b": "Maximize bacterial growth", "c": "Eliminate the need for recipes", "d": "Avoid temperature monitoring"},
         "a", "Just-in-time production preserves sensory quality and safety.",
         {"b": "Opposite.", "c": "Recipes still needed.", "d": "Monitoring still required."}, "medium"),
    ])

    qs += pack(e, "management", [
        ("A policy differs from a procedure in that a policy:",
         {"a": "States guiding principles/rules; procedures detail how to carry them out", "b": "Lists exact minute-by-minute steps only", "c": "Is never written", "d": "Replaces all job descriptions"},
         "a", "Policies = what/why; procedures = how.",
         {"b": "That is procedure territory.", "c": "Should be documented.", "d": "JD separate."}, "easy"),
        ("Span of control refers to:",
         {"a": "Number of employees a manager directly supervises effectively", "b": "Square footage of the kitchen only", "c": "Number of menu cycles", "d": "Food cost percentage target alone"},
         "a", "Span of control affects supervision quality and org structure.",
         {"b": "Facility size.", "c": "Menu planning.", "d": "Financial KPI."}, "easy"),
        ("Which leadership style involves employees in decision-making?",
         {"a": "Autocratic only", "b": "Participative/democratic", "c": "Laissez-faire with zero guidance always as identical to participative", "d": "Transactional punishment only"},
         "b", "Participative leaders seek input while retaining accountability.",
         {"a": "Manager decides alone.", "c": "Laissez-faire is hands-off; not the same.", "d": "Narrow view of transactional leadership."}, "medium"),
        ("A break-even point analysis identifies:",
         {"a": "Sales volume where total revenue equals total costs", "b": "Only the most popular entrée", "c": "Staffing ratios mandated by OSHA for all hospitals identically", "d": "The pH of sanitizer"},
         "a", "BEP = fixed costs / contribution margin per unit (conceptually).",
         {"b": "Popularity index separate.", "c": "Not break-even definition.", "d": "Sanitation chemistry."}, "medium"),
        ("Performance appraisal should be based primarily on:",
         {"a": "Documented job-related standards and observed performance", "b": "Personal friendship only", "c": "Employee age alone", "d": "Rumors without facts"},
         "a", "Fair appraisal uses objective criteria tied to the job description.",
         {"b": "Bias.", "c": "Discriminatory.", "d": "Unreliable/unfair."}, "easy"),
        ("Which federal law addresses unpaid leave for qualifying family/medical reasons (eligible employees)?",
         {"a": "FMLA", "b": "HACCP", "c": "DRI", "d": "IDDSI"},
         "a", "Family and Medical Leave Act provides job-protected unpaid leave when eligibility met.",
         {"b": "Food safety system.", "c": "Nutrient standards.", "d": "Texture framework."}, "easy"),
        ("A capital budget typically covers:",
         {"a": "Major equipment and facility investments with multi-year value", "b": "Daily produce orders only", "c": "Hourly wages for one shift only", "d": "Paper napkin purchases exclusively"},
         "a", "Capital expenditures are significant long-lived assets; operating budgets cover day-to-day.",
         {"b": "Operating expense.", "c": "Operating labor.", "d": "Operating supply."}, "medium"),
        ("Quality improvement PDSA cycles stand for:",
         {"a": "Plan-Do-Study-Act", "b": "Purchase-Deliver-Serve-Audit only in receiving", "c": "Protein-Dairy-Sodium-Alcohol", "d": "Policy-Discipline-Suspend-Arrest"},
         "a", "PDSA is a structured QI method for testing changes.",
         {"b": "Not the acronym.", "c": "Nutrients.", "d": "Not QI."}, "easy"),
        ("In community nutrition, a needs assessment primarily:",
         {"a": "Identifies health/nutrition problems, resources, and priorities in a population", "b": "Cooks meals for one patient", "c": "Calibrates a single thermometer", "d": "Writes one PES for an inpatient only"},
         "a", "Community assessment guides program planning and resource allocation.",
         {"b": "Clinical foodservice task.", "c": "FSD task.", "d": "Clinical NCP."}, "medium"),
        ("Which marketing concept focuses on long-term customer relationships and value?",
         {"a": "Relationship/marketing orientation beyond one-time sales", "b": "Ignoring customer feedback", "c": "Producing only what is convenient regardless of need", "d": "Price dumping as the sole strategy forever"},
         "a", "Customer-focused marketing builds retention through value and service.",
         {"b": "Opposite.", "c": "Production orientation.", "d": "Unsustainable alone."}, "medium"),
        ("Equal Employment Opportunity principles prohibit:",
         {"a": "Employment decisions based on protected classes such as race, sex, religion (per law)", "b": "Hiring based on bona fide job qualifications", "c": "Documenting performance objectively", "d": "Posting job requirements related to essential functions"},
         "a", "EEO laws bar discrimination on protected characteristics.",
         {"b": "BQFs are allowed.", "c": "Appropriate management.", "d": "Essential functions framing is appropriate under ADA concepts."}, "hard"),
        ("A Gantt chart is used in management to:",
         {"a": "Schedule project tasks over time", "b": "Measure blood glucose", "c": "Calculate BMI", "d": "Identify bacteria on agar"},
         "a", "Gantt charts visualize task timelines and dependencies.",
         {"b": "Clinical.", "c": "Anthropometrics.", "d": "Microbiology."}, "easy"),
        ("Delegation is most effective when the manager:",
         {"a": "Assigns authority with clear expectations and follows up appropriately", "b": "Dumps tasks without resources or clarity", "c": "Never checks progress", "d": "Delegates confidential legal decisions they must personally own without briefing"},
         "a", "Effective delegation matches task, authority, resources, and accountability.",
         {"b": "Sets up failure.", "c": "Abdicates responsibility.", "d": "Some duties are non-delegable."}, "medium"),
        ("WIC is a public program that primarily provides:",
         {"a": "Nutrition education and supplemental foods for eligible women, infants, and children", "b": "Medicare Part D exclusively", "c": "Inpatient TPN for all adults", "d": "OSHA inspections of restaurants only"},
         "a", "WIC serves pregnant/postpartum women and children at nutrition risk with foods/education/referrals.",
         {"b": "Drug coverage different program.", "c": "Clinical PN separate.", "d": "Different agency functions."}, "easy"),
        ("Outcome evaluation of a community nutrition program measures:",
         {"a": "Whether objectives/changes in knowledge, behavior, or health status were achieved", "b": "Only how many flyers were printed without impact", "c": "Kitchen hood CFM exclusively", "d": "Employee locker counts"},
         "a", "Outcome evaluation assesses effectiveness against stated goals; process evaluation tracks activities.",
         {"b": "Process/output metric alone.", "c": "Facility engineering.", "d": "Irrelevant."}, "hard"),
    ])
    return qs
