#!/usr/bin/env python3
"""Write credential-correct NATE Core and Wastewater Operator 1 banks.

Replaces sibling remaps in ops. Writes /tmp/{slug}-fixed.json. Does not touch git.
"""

from __future__ import annotations

import json
from pathlib import Path

KEYS = "abcd"


def build(slug: str, rows: list[tuple[str, str, str, str, str, str, str]]) -> list[dict]:
    questions = []
    for index, (topic, prompt, correct, w1, w2, w3, why) in enumerate(rows):
        key = KEYS[index % 4]
        wrongs = [w1, w2, w3]
        options = []
        distractors: dict[str, str] = {}
        wi = 0
        for letter in KEYS:
            if letter == key:
                options.append({"id": letter, "text": correct})
            else:
                text = wrongs[wi]
                wi += 1
                options.append({"id": letter, "text": text})
                distractors[letter] = (
                    f"“{text}” does not answer “{prompt}”. That is a neighboring process, "
                    f"the drinking-water/electrical sibling, or an extreme never/always. "
                    f"The matching answer is: {correct}."
                )
        questions.append(
            {
                "id": f"{slug}-{topic}-{index + 1:03d}",
                "examSlug": slug,
                "topicId": topic,
                "prompt": prompt,
                "options": options,
                "correctOptionId": key,
                "explanation": (
                    f"{why} This item asks: “{prompt}”. The matching answer is: {correct}. "
                    "Independent UniPrep diagnostic — not an official NATE or state operator paper."
                ),
                "distractorExplanations": distractors,
                "difficulty": "medium",
                "sourceNote": "Ops P0 rewrite 2026-09-21: replaced sibling-remap bank with credential-matched items.",
            }
        )
    return questions


NATE = [
    ("safety", "Before opening an HVAC electrical panel for repair, the technician should first:",
     "Lock out and tag out power and verify zero energy with a meter",
     "Rely on the thermostat being off", "Pull only the disconnect and leave the panel live",
     "Wear cotton gloves and keep the circuit energized",
     "NATE Core safety is lockout/tagout plus a proved-dead meter check, not a thermostat-off shortcut."),
    ("safety", "When brazing a refrigerant line, the safest purge practice is:",
     "Flow dry nitrogen through the tubing while heating",
     "Leave the system open to shop air", "Purge with oxygen to speed the braze",
     "Skip purge if the joint looks clean",
     "Nitrogen displacement keeps oxides out of the circuit and avoids an oxygen-fed fire."),
    ("safety", "Recovering refrigerant before opening a charged circuit is required because:",
     "Venting regulated refrigerants to atmosphere is illegal and unsafe",
     "Recovery is optional if the charge is under 5 lb", "R-410A may be vented if the job is residential",
     "A vacuum pump alone satisfies EPA recovery rules",
     "EPA Section 608 requires recovery; a vacuum pump is not a substitute for a recovery machine."),
    ("safety", "A strong rotten-egg or sewer odor at a gas furnace calls for:",
     "Shut the gas, ventilate, and treat it as a leak until proved otherwise",
     "Light the burners to burn the odorant off", "Increase manifold pressure to clear the line",
     "Ignore it if the flame looks blue",
     "Mercaptan odor means leak protocol: no ignition sources until the area is safe."),
    ("safety", "Confined-space work in an attic or crawl with a gas appliance requires:",
     "Combustion air, CO awareness, and an exit plan before starting",
     "Sealing all vents to raise temperature", "Running the furnace with the access panel off indefinitely",
     "Using gasoline to prime a wet floor",
     "NATE safety includes combustion air and carbon monoxide, not sealing a space tighter."),
    ("safety", "A capacitor that is cracked or bulging should be:",
     "Replaced with the specified MFD and voltage rating after discharge",
     "Taped and left in service", "Jumped with a screwdriver while energized",
     "Replaced with any higher MFD 'for more torque'",
     "A failed capacitor is a replace-to-spec part after it is discharged; oversized MFD overheats the motor."),
    ("safety", "When recovering R-410A, the technician should use:",
     "A recovery machine and tank rated for R-410A pressures",
     "An R-22-only tank because the fittings look similar", "A cardboard box as a temporary receiver",
     "The condensate drain as a recovery path",
     "R-410A runs much higher pressure than R-22; equipment must be rated for it."),
    ("safety", "An extension cord on a wet rooftop for a condensing unit should be:",
     "Avoided; use a GFCI-protected, outdoor-rated cord only if temporary power is required",
     "Any indoor lamp cord", "A damaged cord taped at the nick",
     "A three-to-two cheater plug",
     "Wet locations need GFCI and outdoor-rated cord — not indoor zip cord."),
    ("safety", "If a heat-pump outdoor unit is iced solid in winter, first:",
     "Check defrost control, sensors, and airflow before adding charge",
     "Add refrigerant until ice melts", "Pour boiling water over the compressor",
     "Bypass the high-pressure switch permanently",
     "Ice is usually airflow or defrost, not an automatic undercharge."),
    ("safety", "A spark near an open gasoline container in a garage while charging a unit is:",
     "An ignition hazard — remove fuels and ventilate before work",
     "Acceptable if the unit is 410A", "Fine if the tech is wearing safety glasses",
     "Required to warm the oil",
     "Flammable vapors plus electrical work is a fire/explosion risk."),
    ("safety", "Personal protective equipment for recovery and brazing typically includes:",
     "Eye protection, gloves, and burn protection as the task requires",
     "Sandals and a short-sleeve shirt only", "A wool scarf in the blower wheel",
     "No PPE if the job is under 30 minutes",
     "NATE Core expects task-matched PPE, not dressing down for speed."),
    ("safety", "A disconnect within sight of an outdoor condensing unit is used to:",
     "Isolate the equipment so it can be serviced without remote re-energizing",
     "Increase SEER", "Replace the thermostat",
     "Hold the filter-drier",
     "The local disconnect is a service isolation device, not an efficiency control."),
    ("safety", "If flame rollout trips on a gas furnace, the technician should:",
     "Stop, find the blockage or heat-exchanger/vent problem, then reset only after repair",
     "Tape the rollout switch closed", "Raise gas pressure to blow the restriction out",
     "Disable the inducer",
     "Rollout means flame left the heat exchanger — find cause, do not defeat the switch."),
    ("safety", "Empty refrigerant cylinders should be stored:",
     "Capped, upright, and within their pressure rating, away from heat",
     "Open to atmosphere in the truck bed", "On their side next to the torch",
     "Filled with water to 'make them safe'",
     "Cylinders stay capped and protected; they are still pressure vessels."),
    ("safety", "A micron gauge during evacuation is primarily for:",
     "Confirming the system is dry and leak-tight at a deep vacuum",
     "Measuring superheat in heating mode", "Setting gas manifold pressure",
     "Reading condensate pH",
     "Microns measure evacuation quality, not gas pressure or superheat."),
    ("tools", "A typical target for a deep vacuum before charging a burned-out system is about:",
     "500 microns or lower, with a decay test that holds",
     "30 psig on the low side", "14.7 psia shop air",
     "A 2-minute pump-down with no gauge",
     "Industry practice is a deep vacuum plus decay, not a brief pump-down."),
    ("tools", "Superheat is measured as:",
     "Suction-line temperature minus saturated suction temperature",
     "Head pressure minus suction pressure", "Return-air wet bulb only",
     "Gas manifold pressure in inches WC",
     "Superheat is the temperature rise above saturation in the suction line."),
    ("tools", "Subcooling is measured as:",
     "Saturated condensing temperature minus liquid-line temperature",
     "Supply-air dry bulb minus outdoor dry bulb", "Compressor amps times volts",
     "The difference between R and C at the thermostat",
     "Subcooling is how much the liquid is cooled below condensing saturation."),
    ("tools", "A digital manifold or gauge set with a temperature clamp is used to:",
     "Convert pressures to saturation and compute superheat or subcooling",
     "Measure duct static only", "Set inducer RPM",
     "Calibrate a CO detector",
     "Pressure-to-temperature conversion is how techs get SH/SC."),
    ("tools", "A manometer on a gas furnace typically reads:",
     "Manifold or inlet gas pressure in inches of water column",
     "Refrigerant microns", "SEER2",
     "Filter MERV",
     "Gas pressure is an inches-WC measurement, not a refrigerant vacuum."),
    ("tools", "Total external static pressure (TESP) is measured:",
     "Across the air handler, supply plus return, with the blower running",
     "Only at the outdoor unit service ports", "On the gas valve outlet with burners off",
     "With the filter removed and doors off only",
     "TESP is a blower/duct restriction measurement on the air side."),
    ("tools", "A rule-of-thumb residential airflow target is about:",
     "400 CFM per ton, verified by temperature split or static, not guessed",
     "40 CFM per ton", "4,000 CFM per ton on every system",
     "Zero airflow in heating",
     "400 CFM/ton is a starting point — confirm with instruments."),
    ("tools", "A clamp-on ammeter on a compressor is used to:",
     "Compare running amps to the RLA/FLA nameplate under load",
     "Measure microns", "Set TXV superheat directly in °F without temperature",
     "Read gas WC",
     "Current draw is compared to the motor nameplate, not used as a micron gauge."),
    ("tools", "A psychrometer or Bluetooth psychrometric probe is for:",
     "Wet-bulb/dry-bulb or enthalpy to diagnose airflow and capacity",
     "Finding a buried gas leak with soap only", "Setting spark-gap on an igniter",
     "Measuring recovery tank weight",
     "Psychrometrics diagnose air-side performance."),
    ("tools", "A recovery cylinder must be filled by:",
     "Weight, staying under the cylinder’s rated fill limit",
     "Sight until liquid pours from the vapor valve", "Guessing from frost on the tank",
     "Filling to 100% liquid with no vapor space",
     "Overfilling a recovery tank is a rupture risk — use a scale."),
    ("tools", "An analog or digital megohmmeter on a compressor is used to:",
     "Check winding insulation resistance to ground after a burnout",
     "Set defrost time", "Measure duct R-value",
     "Read filter pressure drop in microns",
     "Megohm readings judge winding insulation, not defrost clocks."),
    ("tools", "A temperature split (return vs supply) that is far too low on a cooling system often means:",
     "Low airflow or an undercharged/underperforming coil — measure before adding gas",
     "The heat exchanger is cracked", "The condensate trap is optional",
     "The reversing valve is a gas valve",
     "A small split is an air-side or capacity problem, not an automatic gas-furnace fault."),
    ("tools", "When weighing in a factory charge after a repair, the technician should:",
     "Evacuate, then weigh the nameplate charge adjusted for line-set length",
     "Charge until the suction line frosts to the compressor", "Add vapor until the sight glass is empty",
     "Copy last year’s invoice without weighing",
     "Weigh-in after a proper vacuum is the accurate residential method."),
    ("tools", "A dual-port manometer across a coil or filter reads:",
     "Pressure drop that signals restriction or dirty media",
     "Refrigerant subcooling in psig", "Gas orifice drill size",
     "Compressor oil acidity",
     "Air-side pressure drop is how you prove a dirty filter or coil."),
    ("tools", "Pipe-thread sealant on a gas cock should be:",
     "A listed gas-rated compound or tape, used on the correct threads",
     "Motor oil", "Refrigerant POE oil",
     "Duct mastic on the flare",
     "Gas joints need listed sealant, not HVAC oil or mastic."),
    ("electrical", "A run capacitor is sized by:",
     "The motor’s specified microfarads and a voltage rating at or above the circuit",
     "Any higher MFD to 'help start'", "The breaker amp rating only",
     "The thermostat wire color",
     "Capacitors are matched to the motor label, not oversized for luck."),
    ("electrical", "A 24-volt control transformer that overheats often indicates:",
     "A shorted control circuit, stuck relay, or overloaded VA",
     "A dirty condensate switch that is open as designed", "Correct low-voltage operation",
     "A megohm reading of infinity",
     "Hot transformers mean too much current on the 24 V side."),
    ("electrical", "On a typical gas furnace, the induced-draft motor usually runs:",
     "Before ignition to prove venting, then through the cycle as designed",
     "Only after the burners have been on for 10 minutes", "Instead of the blower forever",
     "Only when the air conditioner calls",
     "The inducer proves draft before trial-for-ignition."),
    ("electrical", "A contactor with badly pitted points should be:",
     "Replaced; pitted contacts add resistance and drop voltage to the compressor",
     "Filed weekly as routine maintenance forever", "Jumpered with a nail",
     "Ignored if the unit still starts sometimes",
     "Pitted contacts are a replace item, not a permanent field repair."),
    ("electrical", "A start capacitor is typically in the circuit:",
     "Only during start, dropped out by a relay or PTC once the motor is up",
     "In series with the run winding at all times like a run capacitor",
     "Across R and C at the thermostat", "In the gas valve coil",
     "Start capacitors are momentary; leaving them in circuit cooks them."),
    ("electrical", "A typical heat-pump reversing valve is energized:",
     "In one mode (often cooling) depending on the OEM — check the wiring diagram",
     "Only when the defrost board is unplugged", "By 240 V from the compressor run capacitor",
     "Never; it is a mechanical gas valve",
     "O/B strategy is OEM-specific — read the diagram."),
    ("electrical", "If a furnace control flashes a pressure-switch fault, first check:",
     "Inducer, vent/intake, and the hose to the switch — not the gas valve first",
     "The outdoor TXV only", "The recovery machine oil",
     "The thermostat C-wire color preference",
     "Pressure-switch faults are venting/inducer problems until proved otherwise."),
    ("electrical", "A clamp meter showing locked-rotor amps that do not drop means:",
     "The compressor or fan motor is not starting — stop and diagnose mechanical/electrical start",
     "Normal run for every scroll", "A successful defrost",
     "The capacitor is optional",
     "LRA that never falls is a failed start, not a running load."),
    ("electrical", "Thermostat R and C are:",
     "24 V hot and common for the control circuit",
     "120 V line and neutral from the disconnect", "The two legs of 240 V to the compressor",
     "The gas manifold taps",
     "R/C are low-voltage control, not line voltage."),
    ("electrical", "A floating (ungrounded) 24 V transformer secondary should still:",
     "Follow the OEM grounding/C connection so safeties and Wi-Fi stats work",
     "Be bonded to the refrigerant suction line", "Share a ground with the recovery tank",
     "Never have a C terminal",
     "Modern controls need a defined common; follow the furnace schematic."),
    ("electrical", "An outdoor unit that hums but will not start often has:",
     "A failed start/run capacitor or a seized compressor",
     "A dirty return filter only, with no electrical test needed", "A reversed liquid-line drier installed backwards as the only cause",
     "Too much insulation on the suction line",
     "Hum-no-start is classic capacitor or mechanically stuck compressor."),
    ("electrical", "A heat-pump defrost board typically terminates defrost when:",
     "The outdoor coil reaches the termination temperature or a time limit",
     "The indoor thermostat is set to 90 °F", "The homeowner presses FAN only",
     "The gas furnace rollout opens",
     "Defrost is coil-temperature or time based, not a room-stat comfort setting."),
    ("electrical", "ECM blower motors are usually commanded by:",
     "A control signal (PWM, serial, or 24 V taps) plus a correct line-voltage feed",
     "A start capacitor only", "Gas manifold pressure",
     "The micron gauge",
     "ECMs need the OEM control signal, not a PSC start capacitor."),
    ("electrical", "If a new thermostat has no C-wire and Wi-Fi drops, the clean fix is:",
     "Add a common or an approved power extender per the furnace and stat docs",
     "Tape R to C", "Feed 120 V to the thermostat R terminal",
     "Disable all safeties",
     "Power-stealing stats fail without a real common — do not put line voltage on R."),
    ("electrical", "A fused disconnect at the condensing unit should be sized:",
     "Per the unit nameplate maximum fuse/breaker, not an arbitrary 60 A",
     "Always 15 A regardless of RLA", "Always 100 A for 3-ton units",
     "Unfused only, even if the nameplate requires a fuse",
     "Nameplate Max fuse / HACR breaker is the rule."),
    ("soft-skills", "When a customer asks to 'just add a pound of 410A' with no measurements, the technician should:",
     "Diagnose with gauges, temperatures, and airflow before changing charge",
     "Add the pound to keep the review five stars", "Vent a pound first so the add is even",
     "Refuse all diagnostics and leave",
     "NATE ethics: charge is a measured decision, not a courtesy pound."),
    ("soft-skills", "Documenting model, serial, pressures, temps, and what was replaced matters because:",
     "The next tech and the warranty need a traceable service record",
     "Paperwork is optional if cash is paid", "Only the invoice total is required by EPA",
     "Serial numbers must be hidden from the owner",
     "Good tickets protect the customer, the shop, and the warranty."),
    ("soft-skills", "If you cannot finish a no-cool call the same day, you should:",
     "Leave the system safe, explain options and price, and schedule the follow-up",
     "Bypass the high-pressure switch so they have AC overnight", "Tell them to run space heaters in August",
     "Take the disconnect home so no one else works on it",
     "Leave it safe and communicate — do not defeat safeties."),
    ("soft-skills", "An EPA 608 card is required to:",
     "Buy and handle regulated refrigerants and perform recovery",
     "Pull a state electrical journeyman license", "Operate a municipal wastewater plant",
     "Sell gas furnaces without any other credential",
     "608 is refrigerant handling, not an electrician or operator license."),
    ("soft-skills", "Up-selling a new system is appropriate when:",
     "The existing equipment is unsafe or uneconomic and the facts are shown to the owner",
     "Every service call, regardless of a simple capacitor fix", "The customer is elderly and confused",
     "You need to hit a monthly quota and the unit is new",
     "Recommendations follow condition and safety, not quota pressure."),
    ("soft-skills", "Customer-owned pictures of a cracked heat exchanger should lead you to:",
     "Inspect, confirm, shut the furnace down if unsafe, and document in writing",
     "Ignore them because photos are never valid", "Tape the crack and relight",
     "Raise gas pressure to hide the crack",
     "A confirmed cracked exchanger is a shutdown and replace conversation."),
    ("soft-skills", "When two techs disagree on a charge, the professional move is:",
     "Re-measure SH/SC, airflow, and nameplate together before adding more gas",
     "Add charge until both are tired", "Argue in front of the customer about competence",
     "Vent the system to start over",
     "Re-measure beats ego and extra refrigerant."),
    ("soft-skills", "A homeowner wants the filter removed 'for more airflow' permanently. You should:",
     "Explain coil/blower damage and IAQ risk and leave a proper filter in place",
     "Remove it and wish them luck", "Cut a hole in the return instead",
     "Spray perfume in the return",
     "Filters protect the equipment; removal is not a performance upgrade."),
    ("soft-skills", "If you damage a customer’s floor, you should:",
     "Tell the shop and the customer immediately and follow company claim policy",
     "Leave quietly and deny it later", "Hide it under a rug",
     "Bill the customer for the damage as a diagnostic fee",
     "Own the mistake the same day."),
    ("soft-skills", "Sharing a customer’s thermostat PIN on social media is:",
     "A privacy failure — never post customer credentials or addresses",
     "Good marketing", "Required by NATE",
     "Fine if you blur the brand logo only",
     "Customer data stays off social media."),
    ("soft-skills", "A 'no heat' call that is actually a tripped breaker should still include:",
     "Finding why it tripped before resetting forever and walking away",
     "Resetting twice a day as the repair", "Replacing the furnace on the first trip",
     "Telling the customer breakers never trip for a reason",
     "Breakers trip for a cause — find the load or short."),
    ("soft-skills", "When quoting a compressor, the estimate should:",
     "Include recovery, drier, evacuation, start components, and labor — not just the part",
     "List only the compressor SKU", "Omit recovery because it is free",
     "Promise a 20-year compressor warranty you do not have",
     "A complete quote prevents callbacks and angry invoices."),
    ("soft-skills", "If you are not licensed for a gas-line resize the job needs, you should:",
     "Stop and bring in a licensed plumber or fitter",
     "Do it anyway after hours", "Use fridge tubing",
     "Skip the permit because it is a service call",
     "Work inside your license and call the right trade."),
    ("soft-skills", "NATE Core is best described as:",
     "An industry knowledge exam for HVAC installation and service fundamentals — not a state license by itself",
     "A replacement for a journeyman electrician license", "A drinking-water operator certificate",
     "An EPA 608 Type I card only",
     "NATE is a certification exam; licenses are still state-issued."),
    ("soft-skills", "Leaving a job site includes:",
     "Reinstalling panels, removing scraps, and confirming the system runs in the called mode",
     "Leaving the blower door off for 'better airflow'", "Leaving gauges on the ports overnight",
     "Taking the thermostat so they call you back",
     "Finish means safe, assembled, and demonstrated."),
]

WASTEWATER = [
    ("process", "Primary clarification mainly removes:",
     "Settleable solids and floating scum before biological treatment",
     "Dissolved nitrate to zero", "Cryptosporidium cysts only, like a drinking-water filter",
     "All BOD in one pass",
     "Primary tanks take settleable solids and scum; soluble BOD goes to secondary."),
    ("process", "In activated sludge, mixed liquor suspended solids (MLSS) are:",
     "The biomass and solids circulating in the aeration tank",
     "The grit in the headworks channel only", "Finished drinking-water turbidity",
     "The chlorine residual in the clearwell",
     "MLSS is the aeration-tank inventory, not a potable-water clearwell number."),
    ("process", "A high sludge volume index (SVI) usually means:",
     "The mixed liquor settles poorly and may not compact in the clarifier",
     "The plant is producing bottled water", "Grit removal is optional",
     "The NPDES permit is automatically met",
     "High SVI is a settling/bulking problem, not a drinking-water win."),
    ("process", "Return activated sludge (RAS) is pumped to:",
     "Return settled biomass from the clarifier to the aeration tank",
     "The potable distribution system", "The raw-water intake of a drinking-water plant",
     "The storm-sewer overflow only",
     "RAS keeps the aeration tank seeded; it is not sent to drinking water."),
    ("process", "Waste activated sludge (WAS) is used to:",
     "Control solids retention time by removing excess biomass",
     "Increase drinking-water fluoride", "Bypass the headworks",
     "Replace the need for aeration",
     "WAS is how operators hold SRT; it is not a fluoride feed."),
    ("process", "A typical food-to-microorganism (F/M) ratio is:",
     "The organic load fed relative to the biomass under aeration",
     "The ratio of fecal coliform to turbidity in a clearwell",
     "Gas manifold pressure divided by WC",
     "The NEC fill calculation for a box",
     "F/M is an activated-sludge loading ratio."),
    ("process", "A trickling filter treats wastewater by:",
     "Passing flow over media so attached biofilm oxidizes organics",
     "Membrane filtration to drinking-water RO standards", "Only chlorinating raw sewage",
     "Settling grit with no biology",
     "Trickling filters are attached-growth secondary treatment."),
    ("process", "Anaerobic digesters commonly produce:",
     "Methane-rich biogas plus a more stable sludge",
     "Potable water meeting the TCR", "R-410A refrigerant",
     "Finished sand-filter effluent for the clearwell",
     "Digesters stabilize sludge and make biogas, not drinking water."),
    ("process", "Secondary (final) clarifiers after aeration are meant to:",
     "Settle biomass so a clear effluent can go to disinfection",
     "Mix raw sewage with potable water", "Add fluoride",
     "Store recovered refrigerant",
     "Final clarifiers separate MLSS from secondary effluent."),
    ("process", "Nitrification in a wastewater plant converts:",
     "Ammonia to nitrite and then nitrate under aeration",
     "Nitrate to fluoride", "BOD to chlorine residual",
     "MLSS to drinking-water alkalinity only",
     "Nitrification is aerobic ammonia oxidation — a wastewater process goal."),
    ("process", "Denitrification in an anoxic zone converts nitrate to:",
     "Nitrogen gas, reducing total nitrogen in the effluent",
     "Free chlorine", "Potable hardness",
     "Grit",
     "Anoxic denitrification is a BNR step, not chlorination."),
    ("process", "A bar screen at the headworks removes:",
     "Rags and large debris that would damage pumps",
     "Dissolved phosphate", "Finished-water THMs",
     "Compressor oil",
     "Preliminary treatment is mechanical debris removal."),
    ("process", "Grit chambers are designed to settle:",
     "Heavy inorganic grit (sand, eggshells) while keeping organics in suspension",
     "MLSS from the aeration tank", "Only oil and grease as scum",
     "Cryptosporidium to drinking-water log credits",
     "Grit is inorganic; organics should stay in process flow."),
    ("process", "A rotating biological contactor (RBC) is:",
     "Attached-growth media shafts that rotate through wastewater",
     "A drinking-water flocculator paddle", "A gas furnace inducer",
     "A recovery machine",
     "RBCs are a secondary attached-growth process."),
    ("process", "Pond/lagoon treatment relies mainly on:",
     "Long detention, algae, and bacteria to stabilize organics",
     "High-rate sand filtration to a clearwell", "NEC box fill",
     "TXV superheat",
     "Lagoons are long-HRT biological systems, not potable filters."),
    ("safety", "Hydrogen sulfide in a wet well is dangerous because it is:",
     "Toxic, flammable, and can deaden smell at high concentration",
     "A required drinking-water residual", "Harmless if the flame is blue",
     "The same as oxygen",
     "H2S kills and explodes; do not trust a faded odor."),
    ("safety", "Entering a pump station wet well is usually:",
     "A confined-space entry with atmosphere testing, ventilation, and a rescue plan",
     "A casual walk-in if the hatch is open", "Allowed without a meter if you hold your breath",
     "The same as walking a filter gallery at a WTP",
     "Wet wells are permit-required confined spaces."),
    ("safety", "A combustible-gas meter in a digester gallery is used to:",
     "Warn of methane before a spark or entry",
     "Measure effluent BOD", "Set a furnace manifold",
     "Read MLSS",
     "Methane plus ignition is an explosion hazard."),
    ("safety", "Chlorine gas leak response at a wastewater plant starts with:",
     "Upwind evacuation, SCBA-trained responders, and the emergency plan",
     "Spraying water into the ton container valve for fun", "Holding your breath and closing valves by feel",
     "Using the leak as disinfection for the office",
     "Cl2 leaks are immediately dangerous — plan and PPE first."),
    ("safety", "A lockout on a screw press or clarifier drive must:",
     "Isolate energy and hold a personal lock before reaching into moving parts",
     "Be a note on the whiteboard only", "Wait until after someone is caught in the flight",
     "Apply only to drinking-water high-service pumps",
     "LOTO is the same principle on any rotating equipment."),
    ("safety", "Fall protection on a clarifier bridge is required because:",
     "Open water and moving equipment can kill a slip",
     "Bridges are never slippery", "OSHA stops at the headworks",
     "Operators jump in to sample",
     "Bridges need rails/PFAS discipline — do not treat them as sidewalks."),
    ("safety", "An oxygen-deficient atmosphere in a manhole is often from:",
     "Displacement by other gases or biological oxygen demand in the sewer",
     "Too much potable chlorine residual", "A good aeration basin",
     "Outdoor wind",
     "Sewers consume and displace oxygen — test before entry."),
    ("safety", "UV disinfection modules should be serviced:",
     "De-energized, with eye/skin protection against UV and electrical lockout",
     "While looking into an energized lamp to check blue light", "With wet hands on 480 V",
     "By pouring bleach on the lamps",
     "UV and line voltage both injure — isolate first."),
    ("safety", "A sudden floating blanket on an anaerobic digester may signal:",
     "Foaming or a process upset — stay off the cover and follow the SOP",
     "A good time to walk the cover without gas checks", "That methane is gone",
     "That the plant is now a WTP",
     "Digester covers and foam are gas and fall hazards."),
    ("safety", "Hearing protection is needed around:",
     "Blowers, pumps, and generators that exceed the plant’s noise policy",
     "Only the lab autoclave", "Never, because plants are quiet",
     "Only if the public is touring",
     "Blower rooms routinely exceed 85 dBA."),
    ("safety", "A chemical splash of polymer or hypochlorite requires:",
     "Eyewash/shower and the SDS-directed first aid",
     "Neutralizing with the opposite chemical in your eyes", "Waiting to see if it burns tomorrow",
     "A coffee rinse",
     "SDS plus eyewash — do not home-brew chemistry in a face."),
    ("safety", "Traffic control around an open manhole in the street is:",
     "Required so the public and the crew are not hit",
     "Optional if the work is under 10 minutes", "Handled by leaving the truck in drive",
     "Only for drinking-water main breaks",
     "Collection-system work is still a work zone."),
    ("safety", "If an operator feels dizzy over a wet well, they should:",
     "Leave immediately and treat it as an atmosphere emergency",
     "Climb down to 'get used to it'", "Light a cigarette to test for methane",
     "Close the hatch from inside",
     "Dizziness is leave-now, not climb-down."),
    ("safety", "Stored sodium hypochlorite should be:",
     "In compatible tanks, away from acids that would release chlorine gas",
     "Mixed with fuel oil for winter", "Kept in a food fridge",
     "Poured into the storm drain to 'disinfect the creek'",
     "Hypo plus acid makes Cl2 gas."),
    ("safety", "A bypass pump on a force-main repair needs:",
     "Secondary containment and spill response for sewage",
     "Discharge to the nearest playground", "No plugs or hoses because gravity is enough",
     "Potable-water cross-connection without a backflow preventer",
     "Bypasses still handle sewage — contain it."),
    ("labs", "A 5-day BOD test is incubated at:",
     "20 °C for five days, measuring oxygen used by microbes",
     "100 °C to sterilize the bottle", "4 °C in the dark only, with no incubation",
     "Room temperature for 20 minutes",
     "Standard BOD5 is 20 °C / 5 days."),
    ("labs", "TSS is measured by:",
     "Filtering a known volume and drying/weighing the residue",
     "A pocket conductivity pen only", "Taste",
     "A micron gauge",
     "TSS is a gravimetric filter test."),
    ("labs", "A grab sample is appropriate when:",
     "The parameter changes fast or the permit specifies a grab (for example, pH or residual)",
     "You want a 24-hour flow-weighted composite for BOD but grab anyway",
     "The analyst is on vacation",
     "You are sampling a drinking-water TCR routine site",
     "Match sample type to the parameter and the permit."),
    ("labs", "A flow-weighted composite is used for:",
     "Parameters like BOD or TSS that should represent the day’s load",
     "Instant pH only", "A single wet-well sniff",
     "Refrigerant type",
     "Composites represent load over time."),
    ("labs", "Settleometer / 30-minute settleability helps operators:",
     "See how the mixed liquor will behave in the clarifier",
     "Measure drinking-water Langelier index", "Set a TXV",
     "Read NEC table 310.16",
     "Settleometers are an activated-sludge tool."),
    ("labs", "A dissolved-oxygen probe in the aeration tank is used to:",
     "Keep enough oxygen for the biomass without wasting blower kWh",
     "Measure chlorine gas in a ton container", "Read static pressure",
     "Prove a heat-exchanger crack",
     "Process DO is an aeration setpoint, not a refrigerant test."),
    ("labs", "Fecal coliform or E. coli on final effluent is a:",
     "Disinfection-performance and permit-limit test for wastewater discharge",
     "Total Coliform Rule monthly 5% drinking-water distribution test",
     "MLSS measurement", "Gas WC reading",
     "Effluent bacteria limits are NPDES, not the drinking-water TCR."),
    ("labs", "A chain-of-custody form is needed when:",
     "Samples leave the collector for a lab or enforcement use",
     "You rinse a probe in the sink", "You change a blower oil",
     "You reset a PLC",
     "COC is legal/traceability, not optional paperwork."),
    ("labs", "Holding time and preservation (for example, H2SO4 on some nutrients) exist so:",
     "The result still represents the process when the lab runs it",
     "The bottle looks official", "Operators can skip ice",
     "Permits can be ignored",
     "Wrong preservation voids the result."),
    ("labs", "A calibration of a pH meter uses:",
     "At least two buffers that bracket the expected sample",
     "Tap water once a year", "The last BOD bottle",
     "A refrigerant temperature-pressure chart",
     "Bracketed buffers are the standard."),
    ("labs", "Mixed-liquor volatile suspended solids (MLVSS) estimate:",
     "The organic/active fraction of the aeration solids",
     "Grit mass only", "Finished-water hardness",
     "Screenings volume",
     "MLVSS is the volatile (mostly biomass) part of MLSS."),
    ("labs", "A sudden jump in influent COD with no flow change can mean:",
     "A slug of industrial or septage load — hunt the source",
     "The BOD incubator failed high", "A good trickling-filter sloughing only",
     "That RAS should be turned off forever",
     "COD spikes are often collection-system dumps."),
    ("labs", "Microscopic exam of mixed liquor is used to:",
     "Spot filaments, protozoa, and floc quality that explain SVI problems",
     "Count Cryptosporidium for a SWTR bin", "Grade sand for a rapid sand filter",
     "Identify refrigerant oil",
     "Microscopy is an activated-sludge diagnostic."),
    ("labs", "A split sample or duplicate is run to:",
     "Check laboratory precision",
     "Increase MLSS on purpose", "Satisfy a drinking-water lead-and-copper tap sample",
     "Calibrate a manometer",
     "Duplicates are a QC check."),
    ("labs", "Temperature of a BOD incubator that drifts to 25 °C will:",
     "Bias the BOD high because microbes work faster",
     "Have no effect", "Turn the test into a TSS",
     "Satisfy a vacuum decay",
     "BOD is temperature-sensitive — 20 °C is the method."),
    ("regs", "An NPDES permit for a wastewater plant sets:",
     "Discharge limits, monitoring, and reporting for the effluent to waters of the U.S.",
     "The Total Coliform Rule for a distribution system", "NEC dwelling receptacle spacing",
     "NATE Core passing scores",
     "NPDES is the wastewater discharge permit, not drinking-water TCR."),
    ("regs", "A sanitary-sewer overflow (SSO) typically must be:",
     "Stopped, contained if possible, and reported per the permit and state rules",
     "Ignored if it rains", "Pumped into a storm drain with no record",
     "Called a drinking-water main break",
     "SSOs are reportable sewage releases."),
    ("regs", "Bypassing secondary treatment without authorization is:",
     "A permit violation unless the permit explicitly allows a documented bypass",
     "Standard weekend practice", "Required during every storm",
     "The same as a filter backwash at a WTP",
     "Unauthorized bypasses are enforcement bait."),
    ("regs", "Land-applying biosolids requires:",
     "Meeting pathogen, vector-attraction, and metal limits for the chosen class",
     "Dumping wet sludge in a creek", "Mixing with potable water and serving it",
     "No records if the field is rural",
     "40 CFR 503-style rules still apply at the state level."),
    ("regs", "A discharge monitoring report (DMR) is:",
     "The periodic report of permit sample results to the regulator",
     "An HVAC invoice", "A NATE score report",
     "A drinking-water CCR consumer confidence report",
     "DMRs are wastewater permit reports; CCRs are drinking water."),
    ("regs", "Combined sewer overflows (CSOs), where they still exist, are:",
     "Permitted or being eliminated wet-weather discharges of mixed sewage and stormwater",
     "Drinking-water storage tanks", "Primary clarifiers",
     "Anaerobic gas flares",
     "CSOs are a wet-weather collection issue, not a WTP process."),
    ("regs", "An operator’s certificate is typically:",
     "Required by the state to be in responsible charge of a classified plant",
     "The same document as NATE Core", "An EPA 608 card",
     "Optional if the plant is under 1 MGD everywhere",
     "State boards license operators; NATE does not."),
    ("regs", "Fats, oils, and grease (FOG) programs exist to:",
     "Keep collection systems and plants from clogging and overflowing",
     "Flavor effluent", "Meet a fluoride MCL",
     "Lubricate a compressor",
     "FOG is a pretreatment/collection control."),
    ("regs", "Industrial pretreatment programs are meant to:",
     "Keep toxic slugs from killing the biology or passing through to the river",
     "Add extra BOD on purpose", "Replace the need for a headworks",
     "Treat the river with chlorine at the outfall only",
     "Pretreatment protects the POTW and the permit."),
    ("regs", "If a fecal coliform result is over the weekly permit limit, the operator should:",
     "Verify disinfection, re-sample as required, and report honestly",
     "Dilute the bottle with distilled water", "Throw the result away",
     "Call it a TCR distribution hit",
     "Fix the process and report — do not cook the sample."),
    ("regs", "Stormwater that is not part of a combined system should:",
     "Stay out of the sanitary sewer to avoid hydraulic overload",
     "Be piped into the aeration tank on purpose every rain", "Replace RAS",
     "Be used as potable water",
     "I&I and illegal storm connections blow plants out."),
    ("regs", "A whole-effluent toxicity (WET) test looks at:",
     "Whether the effluent is toxic to test organisms, not just conventional pollutants",
     "Only pH in the aeration tank", "Only MLSS color",
     "Only drinking-water lead",
     "WET is a biological permit test."),
    ("regs", "Records for permit samples are usually kept:",
     "For the period the permit and state require — often three years or more",
     "Until the shift ends", "Only if the result passed",
     "On a personal phone with no backup",
     "Retention is a permit condition."),
    ("regs", "Signing a DMR as the responsible operator means:",
     "You are stating the data are true and complete to the best of your knowledge",
     "You can invent numbers if the lab is late", "The plant met every goal forever",
     "NPDES no longer applies",
     "False statements on DMRs are a federal offense."),
    ("regs", "This UniPrep wastewater mock is:",
     "An independent 60-question diagnostic — not a state operator exam form",
     "The official ABC standardized exam", "A drinking-water Grade 1 paper",
     "A NATE Core HVAC test",
     "Honesty: we are not the licensing board."),
]


def main() -> None:
    nate = build("nate-core-readiness-check", NATE)
    ww = build("wastewater-operator-1-readiness-check", WASTEWATER)
    for slug, questions in (
        ("nate-core-readiness-check", nate),
        ("wastewater-operator-1-readiness-check", ww),
    ):
        if len(questions) != 60:
            raise SystemExit(f"{slug} has {len(questions)} questions")
        path = Path(f"/tmp/{slug}-fixed.json")
        path.write_text(json.dumps(questions, ensure_ascii=False, indent=2) + "\n")
        print(json.dumps({"slug": slug, "n": len(questions), "output": str(path)}))


if __name__ == "__main__":
    main()
