#!/usr/bin/env python3
"""P1 remaps batch B: PHR, unarmed security, Praxis Core, ASWB B/C, ASCP MLT."""

from p1_remap_lib import build

PHR = [
    ("talent", "A job analysis should produce:", "Tasks, KSAs, and working conditions — not a personality roast", "A vibes list only", "The CEO's hobbies", "A SHRM competency copy-paste with no job", "HRCI work starts from the job."),
    ("talent", "A structured interview is better than an unstructured chat because it:", "Compares candidates on the same job-related questions", "Lets the hiring manager ramble", "Asks about kids first", "Ignores KSAs", "Structure reduces noise."),
    ("talent", "A BFOQ is:", "A rare, legally allowed sex/religion/national-origin requirement that is essential to the job", "Any manager preference", "A way to avoid older workers", "A wellness perk", "BFOQ is narrow."),
    ("talent", "Adverse impact in selection is spotted with:", "A statistical look at pass rates by protected class, then a validity defense if needed", "Gut feel", "A vibe check", "Ignoring the numbers if the VP likes the test", "4/5ths is a screen, not the whole law."),
    ("talent", "Onboarding should include:", "Role, tools, compliance, and a 30-day check — not a handbook toss", "A scavenger hunt only", "No manager time", "A noncompete lecture as the only hour", "Time-to-productivity is a metric."),
    ("talent", "A reliability problem in a test means:", "Scores bounce — you cannot trust the rank order", "The test is automatically valid", "EEO is satisfied", "It predicts performance perfectly", "Reliable ≠ valid."),
    ("talent", "Content validity for a work sample means:", "The sample mirrors important job tasks", "It feels hard", "It is cheap", "It is in English", "Match the work."),
    ("talent", "A RIF selection list should be:", "Job-related and documented, not a secret 'attitude' sort", "Whoever is on PTO", "Older workers first as a rule", "The diversity committee's friends last as a rule", "Document the criteria."),
    ("talent", "Internal mobility works when:", "Postings are real and managers do not hide roles", "Every job is a friend hire only", "Nobody can apply", "HR never looks at skills", "Make the market internal."),
    ("talent", "A realistic job preview is used to:", "Cut early turnover by telling the hard parts too", "Only sell sunshine", "Hide the night shift", "Replace the job description", "Honesty is a filter."),
    ("talent", "I-9 completion is:", "Section 1 by day 1, documents timed — not 'whenever payroll remembers'", "Optional for citizens", "A personality test", "Done after 90 days always", "IRCA timing is real."),
    ("talent", "A noncompete that is statewide for a junior clerk is often:", "Hard to defend — reasonableness matters", "Automatically valid everywhere", "An EEO charge by itself", "A BFOQ", "Draft with counsel."),
    ("talent", "Succession planning is:", "Identifying and developing backups for critical roles", "A birthday calendar", "Only for interns", "A replacement for recruiting forever", "Critical roles first."),
    ("talent", "An assessment center is:", "Multiple job-like exercises rated on competencies", "A picnic", "A single unstructured lunch", "A drug test", "See them work."),
    ("talent", "This PHR mock is:", "Independent HRCI-style practice — not the official PHR and not SHRM-CP", "The SHRM exam form", "A state barber test", "An NCLEX", "Different body."),
    ("employee-rel", "A documented coaching conversation should:", "State the gap, the expectation, and the follow-up date", "Be a hallway roast", "Be hidden from the employee", "Quote rumors only", "Write the facts."),
    ("employee-rel", "Progressive discipline is skipped when:", "The conduct is egregious and policy allows summary action", "You are in a bad mood", "They used PTO", "They are in a protected class as a reason to skip facts", "Severity can jump steps."),
    ("employee-rel", "Weingarten rights (union, private sector) are about:", "A union employee's request for a rep in an investigatory interview", "Every employee in America always", "A lunch break", "FMLA", "Know the setting."),
    ("employee-rel", "An investigation of harassment should:", "Be prompt, impartial, and documented — not a gossip circle", "Wait a year", "Be run by the accused", "Be posted on Slack", "Process protects everyone."),
    ("employee-rel", "At-will still does not allow:", "Firing for a discriminatory or retaliatory reason", "Any firing ever", "Layoffs", "A documented performance fire", "At-will ≠ illegal reason."),
    ("employee-rel", "A last-chance agreement is:", "A written final boundary before termination", "A raise", "A promotion", "A wellness perk", "Make the last chance real."),
    ("employee-rel", "Skip-level meetings help when:", "They surface issues without undermining the manager as policy", "They become a complaint dump with no process", "They replace all 1:1s", "HR never hears the themes", "Design them."),
    ("employee-rel", "A grievance procedure in a union shop is:", "The contractual path — do not freelance a different process", "Optional if busy", "A suggestion box", "The same as at-will coaching", "Follow the CBA."),
    ("employee-rel", "Employee engagement pulse scores matter if you:", "Act on a few drivers and close the loop", "File them", "Punish low scorers", "Change the vendor yearly with no action", "Surveys without action breed cynicism."),
    ("employee-rel", "A workplace romance policy is meant to:", "Manage conflicts and harassment risk, not ban all friendship", "Spy on homes", "Replace harassment training", "Be unwritten", "Disclose reporting lines."),
    ("employee-rel", "Insubordination is:", "A clear refusal of a lawful work order", "A question in a meeting", "Using PTO", "A disability request", "Define it tightly."),
    ("employee-rel", "A reduction in force meeting should include:", "The business reason, the date, and the benefits/WARN pieces that apply", "A joke about age", "No written follow-up", "A demand for an instant signature on a waiver with no time", "Older Workers Act timing exists."),
    ("employee-rel", "Peer mediation is a bad fit for:", "Harassment or violence — use investigation", "A small style clash", "A missed email tone", "A scheduling mix-up", "Do not mediate abuse."),
    ("employee-rel", "Attendance point systems fail when they:", "Punish protected leave the same as no-call no-show", "Count extras", "Are written", "Are explained", "FMLA/ADA/USERRA carve-outs."),
    ("employee-rel", "A resignation should be:", "Confirmed in writing with last day and access cutoff", "Ignored", "Turned into a termination to be spiteful without facts", "Posted as a meme", "Close the loop."),
    ("comp-ben", "A compensable factor in a point-factor job eval is:", "A job-related dimension like skill, effort, responsibility, conditions", "The incumbent's hair", "Who the manager likes", "The last raise date only", "Evaluate the job."),
    ("comp-ben", "FLSA overtime for a nonexempt is:", "1.5× after 40 hours in the workweek (usual federal rule)", "Optional", "Never", "Only if they ask nicely", "Hours are hours."),
    ("comp-ben", "An exempt EAP employee still must:", "Meet duties and salary tests — a title is not enough", "Just have 'manager' on a card", "Never get a salary", "Be paid only in tips", "Duties tests matter."),
    ("comp-ben", "A compa-ratio of 0.80 means:", "Pay is at 80% of range midpoint — a signal, not a crime by itself", "They are overpaid 80%", "FLSA exempt", "A BFOQ", "Read the range."),
    ("comp-ben", "Lead-the-market pay is chosen when:", "You need scarce talent and can fund it", "You always want to be cheapest", "HR is bored", "The union asked for a picnic", "Strategy first."),
    ("comp-ben", "A bonus that is discretionary is:", "Not a guaranteed wage in the same way a promised commission may be", "Always non-taxable", "Overtime-proof automatically", "A BFOQ", "Labels need legal review."),
    ("comp-ben", "COBRA is about:", "Continuation of group health after qualifying events, at a cost", "A pension formula", "A stock option", "Workers' comp medical-only forever", "Qualifying events."),
    ("comp-ben", "ERISA fiduciary duty on a 401(k) includes:", "Prudent process and fees that can be explained", "Picking meme stocks for fun", "Hiding the SPD", "Forcing a loan", "Process over bets."),
    ("comp-ben", "An SPD must be:", "Understandable and given on the ERISA timeline", "A 200-page joke", "Optional", "Only on the CEO's desk", "Participants get the SPD."),
    ("comp-ben", "A wellness program that is too coercive can:", "Create ADA/GINA/HIPAA problems", "Only help", "Replace health insurance illegally as the only plan with no rules", "Be ignored by counsel always", "Incentives have caps and notices."),
    ("comp-ben", "Prevailing wage / Davis-Bacon (when it applies) is:", "A mandated rate on covered public work — not a vibe", "Optional overtime", "A 401(k) match", "FMLA", "Know if you are covered."),
    ("comp-ben", "A total rewards statement is useful to:", "Show pay plus benefits value", "Replace the W-2", "Hide deductions", "Set FLSA status", "Communicate the package."),
    ("comp-ben", "Shift differential is:", "Extra pay for less desirable hours, if you offer it", "A BFOQ", "Overtime by itself always", "A pension", "Define it in policy."),
    ("comp-ben", "Imputed income on a benefit means:", "The IRS may tax a portion — payroll has to get it right", "It is free forever", "It is illegal", "It is FMLA", "Tax is part of benefits."),
    ("comp-ben", "A clawback on a bonus after fraud is:", "A contract/policy tool — draft it before you need it", "Illegal always", "FMLA", "A BFOQ", "Write it first."),
    ("compliance", "Title VII covers:", "Race, color, religion, sex, national origin — and the case law on harassment/retaliation", "Only age", "Only disability", "Only veterans", "Know the statute."),
    ("compliance", "ADA interactive process is:", "A dialogue about reasonable accommodation, not a one-letter deny", "Ignoring the request", "Firing first", "A wellness contest", "Talk, then decide."),
    ("compliance", "FMLA eligible employee typically needs:", "12 months, 1250 hours, and a covered employer size — then a qualifying reason", "One week on the job", "A manager title only", "A union card only", "Do the math."),
    ("compliance", "A Form 300 log is:", "OSHA recordkeeping for work-related injuries that meet the criteria", "A 401(k) form", "An I-9", "A W-4", "Recordables have tests."),
    ("compliance", "USERRA requires:", "Reemployment rights after uniformed service as the statute says", "Firing reservists to be safe", "No notice ever from the employee as your only policy", "A wellness race", "Military leave is federal."),
    ("compliance", "A negligent-hire risk is highest when you:", "Skip a reasonable check for a role with foreseeable harm", "Do a job-related background check", "Ask about KSAs", "Use a work sample", "Duty of care."),
    ("compliance", "GINA limits:", "Genetic information in employment decisions", "All family photos on a desk", "FMLA", "Overtime", "Do not collect genetic data to hire."),
    ("compliance", "A privacy misstep is emailing:", "A spreadsheet of SSNs to the wrong vendor", "A public job ad", "A handbook link", "A holiday note", "Minimum necessary."),
    ("compliance", "Pay transparency laws (where they exist) can require:", "Posting ranges and not retaliating for pay talk", "Hiding all ranges", "A BFOQ", "A 401(k) loan", "State law stacks on federal."),
    ("compliance", "An EEO-1 (when you must file) is:", "A demographic report to the EEOC on the timeline", "A suggestion box", "Optional for a 10,000-person federal contractor always", "A W-2", "Know if you file."),
    ("compliance", "A workplace safety complaint to OSHA that is real should not be met with:", "Retaliation", "A fix", "An investigation", "Better guarding", "Section 11(c)."),
    ("compliance", "Record retention for I-9s is:", "The statutory later-of rule — not 'until the drawer is full'", "Forever in email only", "One week", "Never", "Count the years."),
    ("compliance", "A handbook disclaimer should say:", "The handbook is not a contract (where you want at-will preserved)", "Employment is guaranteed for life", "Policies never change", "HR is optional", "Words create contracts."),
    ("compliance", "If state law is stricter than federal on sick leave:", "Follow the stricter rule that applies", "Follow only federal", "Ignore both", "Ask the internet poll", "Floor vs ceiling."),
    ("compliance", "Attorney-client on an investigation is:", "Not a reason to skip a fair process for the employee", "A way to never document", "A BFOQ", "FMLA", "Privilege is not a people-process."),
]

UNARMED = [
    ("law", "An unarmed officer's use of force must be:", "The minimum needed to defend or detain as state law and post orders allow — no firearm", "A punch first", "A citizen's arrest for every trespass rumor", "A chase onto a freeway as policy", "Unarmed ≠ no law."),
    ("law", "A citizen's arrest, where allowed, generally needs:", "A crime committed in your presence or the state's exact rule — not a hunch", "A vibe", "A manager's gossip", "Any unpaid invoice", "Know your state."),
    ("law", "Trespass after a clear withdraw-of-consent is:", "A reason to call police if they will not leave — not a beating", "A shooting decision", "A tax issue", "Ignored always", "Ask, document, escalate."),
    ("law", "Detention of a suspected shoplifter should follow:", "Post orders and probable-cause standards — short, documented, no interrogation theater", "A back-room confession plan", "A strip search by you", "A 3-hour hold 'to teach them'", "You are not the detective."),
    ("law", "Miranda warnings are:", "A police interrogation issue — do not play cop on a recorded interview you should not run", "Required before you say hello", "A parking ticket", "A fire code", "Stay in your lane."),
    ("law", "An unarmed post does not include:", "Carrying a firearm or acting as armed", "A radio", "A flashlight", "Access control", "The license class is the weapon class."),
    ("law", "Use-of-force reporting is required when:", "You put hands on someone or they are injured — write it that shift", "You waved", "You unlocked a door", "You drank coffee", "If it would look like force on camera, write it."),
    ("law", "A search of a purse by an unarmed officer is:", "Usually a no unless policy, consent, or a very specific retail rule applies", "Always OK", "The same as TSA", "A medical exam", "Fourth-amendment analog + policy."),
    ("law", "Liability is highest when you:", "Leave your post and something foreseeable happens, or you use illegal force", "Write an accurate report", "Call 911", "Hold a door", "Foreseeability."),
    ("law", "An underage drinker on a licensed site is:", "A document-and-manager/police issue — you do not 'teach them' with pain", "A reason to drive them home in your car against policy", "Ignored", "A federal tax case you prosecute", "Alcohol posts have rules."),
    ("law", "Confidential client information you hear on post is:", "Not for social media or friends", "Public", "A podcast", "Fine if funny", "The site owns the secret."),
    ("law", "A 'no weapons' unarmed site means you:", "Do not bring a personal gun to 'be safe'", "Hide a gun in the backpack", "Share a gun with a coworker", "Store a rifle in the trunk as a plan you tell no one and still carry the post", "The license is the rule."),
    ("law", "False imprisonment risk appears when you:", "Block an exit with no legal basis", "Ask someone to wait for police on a good detention", "Call 911", "Write a report", "Doors + no cause."),
    ("law", "Serving process or being a bounty hunter is:", "Not your unarmed guard job", "A side hustle on post", "Required", "The same as access control", "Different license."),
    ("law", "This unarmed mock is:", "Independent practice — not a state guard card exam and not an armed course", "An armed firearms qual", "A PHR test", "NATE Core", "No gun content as the job."),
    ("patrol", "A good patrol is:", "Irregular enough to be unpredictable, with eyes up — not the same loop on your phone", "A chair by the door only", "A race", "A nap", "See and be seen."),
    ("patrol", "The first thing on a dark stairwell is:", "Lighting and a radio check — not a hero search alone if policy says two", "Turning off your light to sneak", "Leaving the door propped with a rock forever", "Ignoring the alarm", "Light is a tool."),
    ("patrol", "Access control means:", "Badges and tailgating, not a wave-through for 'a face you know' when policy says badge", "Propping the server-room door", "Giving your badge away", "No visitor log ever", "One person, one badge."),
    ("patrol", "A door found unsecure is:", "Secured if safe, documented, and reported — not ignored", "A selfie", "Propped more", "Left for days", "Close it and write it."),
    ("patrol", "CCTV is for:", "Review and deterrence — you still walk; cameras do not smell smoke", "Replacing all patrols always", "Entertainment", "Public TikTok", "Eyes plus feet."),
    ("patrol", "A utility closet alarm at 03:00 is:", "Approached with caution and backup as orders say", "Kicked in alone for fun", "Ignored as 'always false'", "A reason to shut off fire panel zones", "Treat it as real until it is not."),
    ("patrol", "Weather on an outdoor post means:", "More slips and more HVAC/roof issues — slow down", "A reason to leave the site unmanned against orders", "No radio", "Sunglasses at night only", "Conditions change the risk."),
    ("patrol", "A package left at a door that looks wrong is:", "A bomb-procedure / do-not-touch issue if that is the SOP", "Kicked down the hall", "Opened for curiosity", "Taken home", "Unattended items have a script."),
    ("patrol", "Keys you sign out are:", "On your person or in the box — never 'under the mat'", "Shared on a hook labeled 'spare'", "Photographed for Instagram", "Lent to a stranger", "Key control is the job."),
    ("patrol", "A fire door wedged open should be:", "Closed and reported — wedges kill egress", "Ignored because it is hot", "Tied more firmly", "Used as a patrol route marker", "Life safety first."),
    ("patrol", "Lighting out in a lot is:", "A work order and extra patrol, not 'fine'", "A reason to turn off the rest of the lights", "Ignored", "A photography project", "CPTED is light."),
    ("patrol", "Your notebook should have:", "Times, names, and facts — not jokes about the client", "Doodles of the receptionist", "Passwords", "Nothing", "If it is not written, it did not happen."),
    ("patrol", "A contractor without a badge after hours is:", "Stopped and verified — not waved because they have a toolbag", "Tackled", "Ignored", "Given master keys", "Challenge kindly."),
    ("patrol", "Foot patrol on ice requires:", "Shorter steps and reporting the ice", "A sprint", "Sneakers with no tread as a flex", "No radio so your hands are free to fall", "Do not add a casualty."),
    ("patrol", "The 'observe and report' motto still includes:", "Calling police when there is a crime in progress", "Filming only for clout", "Leaving a robbery to finish your loop", "A speech about the Constitution to the suspect", "Call early."),
    ("emergency", "Fire alarm with smoke showing:", "Evacuate per plan, close doors if safe, meet the fire dept — do not silence and walk away", "Reset the panel to stop the noise first always", "Use the elevator with the crowd", "Hide", "Alarm + smoke = out."),
    ("emergency", "A medical emergency on post:", "911, AED if trained, crowd control — you are not the ER", "A tourniquet on the neck for a faint", "A wait-and-see for chest pain", "A photo", "BLS + scene."),
    ("emergency", "An active threat when you are unarmed:", "Run/hide/help others as trained — you do not hunt with a flashlight as a gun", "Clear rooms like a SWAT film", "Live-stream", "Lock the doors from the outside on people who need to flee if that traps them against the plan", "Unarmed response is avoidance and information."),
    ("emergency", "A bomb threat call is:", "Kept on the line if possible, notes taken, supervisor/police — do not pull the fire alarm as a joke", "Yelled across the lobby", "Ignored", "A Twitter post", "Checklist the call."),
    ("emergency", "Power failure on a high-rise post:", "Check emergency lighting, elevators, and the generator plan", "Leave the site", "Use candles in a closet", "Reset fire pumps randomly", "Blackout SOP."),
    ("emergency", "A chemical smell in a lab dock:", "Do not become a victim — isolate, evacuate as trained, call specialists", "Sniff closer", "Hose it with no SDS", "Ignore", "HAZMAT is not a mop job."),
    ("emergency", "Crowd surge at a gate:", "Widen, communicate, call for more staff — do not shove the front line as a joke", "Lock everyone in a tighter space", "Turn off lights to 'calm' them", "Leave the post", "Crowds kill."),
    ("emergency", "A missing child report in a mall:", "Code/description, exits, cameras — not a 20-minute debate", "A PA joke", "Ignore", "A search of the child's social only", "Minutes matter."),
    ("emergency", "Weather siren / tornado:", "Move people to the marked shelter area", "To the windows", "To the roof", "To their cars as the first idea", "Lowest interior."),
    ("emergency", "Elevator entrapment:", "Call the service/fire number, talk calmly — do not pry doors as a hero", "A YouTube rescue", "Cut the cables", "Leave them overnight without a call", "Trained techs."),
    ("emergency", "A spill of blood in the lobby:", "PPE and the bloodborne kit — not a dry mop only", "A visitor to clean it", "Ignore", "A photo for the group chat", "BBP."),
    ("emergency", "Radio failure in an emergency:", "Use the backup phone list — do not go dark", "Yell only", "Leave", "A personal livestream as the official channel", "Redundancy."),
    ("emergency", "A hostage rumor you cannot confirm:", "Distance, call police, stop other traffic into the area", "Walk in to 'talk them down'", "A TikTok", "A fire alarm pull to mix the crowd into it", "Do not add bodies."),
    ("emergency", "After any major event:", "A written timeline while it is fresh", "A nap only", "A deleted camera request", "A joke on the client's review page", "Debrief on paper."),
    ("emergency", "AED cabinet alarm going off with no patient:", "Check it — stolen AEDs are a thing", "Ignore", "Take the AED home", "Silence and walk away without looking", "That box matters."),
    ("ethics", "A report is late when:", "You wait until next week to write a use-of-force", "You finish it before you leave", "You include times", "You use plain words", "Same-shift writing."),
    ("ethics", "Sleeping on an overnight post is:", "A firing and a liability", "Fine if quiet", "Training", "Required", "You are the detection."),
    ("ethics", "Accepting $200 to 'not see' a truck is:", "A crime and a fireable", "A tip", "Client service", "Optional", "Integrity is the product."),
    ("ethics", "Posting the client's badge printer on Instagram is:", "A security breach", "Marketing", "Required", "Fine if funny", "Do not leak the site."),
    ("ethics", "A biased stop of only one race of visitors is:", "Discrimination and a lawsuit", "Good profiling", "Required", "A joke", "Behavior, not identity."),
    ("ethics", "Falsifying a DAR (daily activity report) is:", "Fraud", "Efficiency", "Training", "Optional", "Lies on paper are evidence."),
    ("ethics", "Dating a coworker on the same overnight pair needs:", "Disclosure per policy — fatigue and favoritism are real", "A secret in the CCTV room", "A shared password", "Nothing", "Tell HR/supervisor."),
    ("ethics", "Using the client's forklift 'for fun' is:", "Outside the post and a safety crime waiting", "Training", "A perk", "Fine after 2 a.m.", "Stay in the job description."),
    ("ethics", "A lost radio is:", "Reported immediately", "Hidden", "Sold", "Replaced with a phone scanner illegally", "Comms are controlled."),
    ("ethics", "Off-duty you still should not:", "Talk about the client's incoming shipment on a podcast", "Exist", "Have friends", "Use your own car", "The NDA follows you."),
    ("ethics", "A supervisor tells you to delete camera footage of a fall:", "You refuse and escalate — that is evidence", "You delete it", "You laugh", "You post it", "Spoliation."),
    ("ethics", "Uniforms on the ride home that advertise a bank's armed look when you are unarmed can:", "Confuse the public — follow the uniform policy", "Help you get discounts", "Replace the license", "Be a firearm", "You represent the site."),
    ("ethics", "Helping police with a lawful request is:", "Yes, within policy — you are not their suspect-interrogator", "A no always", "A reason to leave the post empty against orders with no call", "A livestream", "Cooperate, stay in lane."),
    ("ethics", "A 'favor' of unlocking a suite for someone without ID is:", "How losses happen", "Customer service gold", "Required", "Fine if they smile", "Verify."),
    ("ethics", "Continuing education / relicensing is:", "Your problem on the calendar — an expired card is a stop-work", "Optional if the site likes you", "The client's HR", "A firearm qual if you are unarmed", "The card is the job."),
]

CORE = [
    ("reading", "The main idea of a passage is:", "The central claim the author develops, not a side example", "The first adjective", "A word you do not know", "The longest sentence always", "Praxis Core reading is main idea."),
    ("reading", "A supporting detail is used to:", "Explain or prove the main idea", "Replace the thesis", "Be ignored", "Only decorate", "Details serve the claim."),
    ("reading", "An inference is:", "A conclusion backed by the text but not stated outright", "A wild guess", "The author's bio", "A math formula", "Stay inside the passage."),
    ("reading", "The author's tone in a critical review is often:", "Evaluative — look at charged verbs and qualifiers", "Always joyful", "Always neutral", "A graph", "Tone is word choice."),
    ("reading", "A vocabulary-in-context item wants:", "The meaning that fits this sentence, not the first dictionary line", "A rhyme", "A synonym from another subject", "A guess from the stem only", "Context wins."),
    ("reading", "Compare-and-contrast structure signals:", "Similarities and differences between two things", "Pure chronology", "A single definition", "A recipe only", "Look for however/unlike."),
    ("reading", "A cause-effect passage explains:", "Why something happened or what it produced", "A list with no links", "A poem's meter only", "A map", "Because/therefore."),
    ("reading", "When two passages disagree, you should:", "Identify the exact point of difference", "Pick the longer one", "Average them", "Ignore both", "Paired passages."),
    ("reading", "A primary source in a history excerpt is:", "From the time, by a participant or witness", "A modern textbook summary only", "A blog about the textbook", "A vocab list", "Know primary vs secondary."),
    ("reading", "An argument's weakest evidence is often:", "An anecdote treated as proof of a general rule", "A relevant statistic", "A defined term", "A clear warrant", "Spot the leap."),
    ("reading", "A footnote is used to:", "Credit a source or add a narrow aside", "Change the main idea secretly", "Replace the title", "Be the thesis", "Use it if the item asks."),
    ("reading", "Skimming is useful to:", "Map structure before close reading the item's lines", "Skip the passage forever", "Read only the answers first as a lifestyle", "Memorize every date", "Budget time."),
    ("reading", "A graph in a Core-style set is:", "Evidence you must read as carefully as prose", "Decoration", "Always the opposite of the text", "A writing prompt only", "Quantitative literacy."),
    ("reading", "If an answer is true in the world but not in the passage:", "It is wrong for this test", "It is right", "It is a writing error", "It is math", "Passage is the universe."),
    ("reading", "This Praxis Core mock is:", "Independent academic-skills practice — not elementary pedagogy and not the official ETS form", "Praxis Elementary Education", "A barber exam", "ASWB", "Core ≠ K–6 methods."),
    ("writing", "A thesis should be:", "A debatable, specific claim", "A dictionary definition only", "A question with no stand", "A quote with no comment", "Take a position."),
    ("writing", "Subject-verb agreement fails in:", "'The list of items are' when list is the subject", "'The dogs run'", "'She sings'", "'They were'", "Find the true subject."),
    ("writing", "A comma splice is:", "Two independents joined by only a comma", "A list comma", "An appositive done right", "A question mark", "Use a period, semicolon, or conjunction."),
    ("writing", "Pronoun-antecedent error: 'Every student must bring their pencil' is debated; on many Core keys you should:", "Prefer a singular rewrite (his or her / the students / they with a plural noun) as the item wants", "Leave a mismatch on purpose", "Use you for every noun", "Drop the noun", "Match number."),
    ("writing", "A modifier is misplaced when:", "It sits next to the wrong noun ('Walking to school, the backpack...')", "It is an adverb next to its verb", "It is a title", "It is a number", "Attach the phrase."),
    ("writing", "Parallelism wants:", "The same grammatical shape in a list", "Random forms", "Only adjectives then a clause then a verb as a style", "No list ever", "to swim, to bike, to run."),
    ("writing", "Its vs it's:", "It's = it is; its = possession", "The reverse", "They are the same", "Its' is standard", "Apostrophe = contraction here."),
    ("writing", "A topic sentence usually:", "Opens the paragraph with the paragraph's point", "Hides at the end always", "Is a citation only", "Is a graph", "Readers need a signpost."),
    ("writing", "Revision for concision deletes:", "Empty intensifiers and doubled words", "The thesis", "All examples", "The title", "Cut the fat."),
    ("writing", "A research citation is needed when:", "You use someone else's words or distinctive facts", "You write your own obvious definition of a dog", "You breathe", "You title the essay", "Give credit."),
    ("writing", "Passive voice is a problem when:", "It hides the actor you should name", "It is used for a methods sentence on purpose", "It is a comma", "It is a thesis", "Choose agency."),
    ("writing", "A fragment is:", "A dependent piece punctuated as a sentence", "A full independent clause", "A title", "A number", "Add a base clause."),
    ("writing", "Wordiness: 'due to the fact that' should become:", "Because", "Albeit", "Whereas in as much", "Etcetera and so on thusly", "Simple beats puffed."),
    ("writing", "An argumentative essay needs:", "Claim, reasons, evidence, and a response to a counterpoint", "Only stories", "Only insults", "Only a title", "Core writing is argument."),
    ("writing", "Affect vs effect in usual use:", "Affect is the verb; effect is the noun", "The reverse always", "They are interchangeable", "Both are prepositions", "Most school keys use this pair."),
    ("math", "A ratio 3:4 compared to a whole of 28 is:", "12 and 16 (3/7 and 4/7 of 28)", "3 and 4", "7 and 21", "28 and 28", "Parts sum to the whole."),
    ("math", "Percent of: 15% of 80 is:", "12", "15", "80", "1.5", "0.15 × 80."),
    ("math", "A linear equation 2x + 6 = 18 gives x =", "6", "12", "3", "24", "Subtract 6, divide by 2."),
    ("math", "The slope between (1, 2) and (3, 8) is:", "3", "2", "1/3", "6", "Rise 6, run 2."),
    ("math", "A proportional word problem that doubles time at the same rate:", "Doubles distance", "Halves distance", "Squares distance", "Leaves distance", "d = rt."),
    ("math", "The mean of 4, 6, 10 is:", "6.67 approximately (20/3)", "4", "10", "20", "Sum over count."),
    ("math", "The median of 2, 9, 3 is:", "3", "2", "9", "4.67", "Order first: 2,3,9."),
    ("math", "A right triangle 3-4-? hypotenuse is:", "5", "7", "12", "1", "Pythagorean triple."),
    ("math", "Area of a rectangle 5 by 8 is:", "40", "13", "26", "80", "lw."),
    ("math", "A probability of 1 red in 4 equal marbles is:", "1/4", "4", "3/4 as the red chance", "1", "Favorable over total."),
    ("math", "Scientific notation 3.2 × 10^3 is:", "3200", "32", "0.0032", "3.2", "Move the point."),
    ("math", "An inequality  -2x > 8  reverses when you:", "Divide by −2, so x < −4", "Keep x > −4", "Get x > 4", "Get x = 8", "Flip the sign."),
    ("math", "A unit conversion 2 hours to minutes is:", "120", "2", "60", "24", "× 60."),
    ("math", "The volume of a box 2×3×4 is:", "24", "9", "18", "14", "lwh."),
    ("math", "A scatterplot with points rising to the right shows:", "A positive association", "Zero association only", "A circle", "A negative perfect line always", "Read the trend."),
    ("test-strat", "On a timed Core section you should:", "Answer easy items first and mark hard ones to return", "Sit on item 1 for 20 minutes", "Leave blanks as a lifestyle", "Read every passage twice aloud", "Score = attempted right."),
    ("test-strat", "A calculator (where allowed) is for:", "Arithmetic you already set up — not a substitute for the relationship", "Guessing", "Reading", "Writing the essay", "Setup then compute."),
    ("test-strat", "Eliminating two wrong reading choices is useful because:", "You raise the odds on the remaining pair", "The test penalizes thinking", "You should pick at random first", "Passages do not matter", "Process of elimination."),
    ("test-strat", "If two writing answers both 'sound fine':", "Apply a named rule (agreement, comma, parallel)", "Pick the longer", "Pick the fancier word", "Skip", "Rules beat ear."),
    ("test-strat", "A figure in math that is 'not drawn to scale' means:", "Do not measure with your pencil — use the given numbers", "Trust the picture's lengths", "Ignore the text", "Assume a square", "Read the caption."),
    ("test-strat", "Anxiety on the essay is handled by:", "A 1-minute outline of claim + two reasons", "No plan", "A story with no claim", "Copying the prompt as the essay", "Structure calms."),
    ("test-strat", "A trap in percent increase is:", "Adding the percent to 100 incorrectly or using the wrong base", "Using the original as the base correctly", "A ratio", "A median", "Ask 'percent of what?'"),
    ("test-strat", "When a reading item says 'according to the passage':", "Quote-level support is required", "Use outside knowledge", "Use the title only", "Use the longest option", "According to = text."),
    ("test-strat", "Guessing on Core (no wrong-answer penalty typical of Praxis):", "Fill something — a blank cannot be right", "Leave it", "Bubble two answers", "Argue with the proctor", "Answer every item."),
    ("test-strat", "A multi-step math item should be:", "Rewritten as small equations, not a mental pile", "Rushed in one line of hash marks", "Skipped if it has two sentences", "Answered from the figure only", "Show the chain."),
    ("test-strat", "Transfer errors happen when you:", "Copy the wrong bubble — check the number", "Read carefully", "Eliminate", "Outline", "Grid matches the stem."),
    ("test-strat", "If time is almost gone on reading:", "Short items and graphs first, then leftover long prose", "Start a new 8-paragraph passage slowly", "Erase all answers", "Nap", "Triage."),
    ("test-strat", "Reviewing a flagged algebra item, first re-read:", "What the question asked (solve vs evaluate vs simplify)", "Only the choices", "The previous passage", "The essay prompt", "Question type."),
    ("test-strat", "A 'best' answer in reading means:", "The most complete, passage-faithful option — not a true-but-narrow aside", "The meanest tone", "The first option", "Outside trivia", "Best ≠ true in life."),
    ("test-strat", "Praxis Core is not:", "A test of classroom management or lesson plans — that is other Praxis titles", "Reading", "Writing", "Math", "Do not study elementary methods here."),
]

def aswb_b():
    return [
        ("hgb", "Erikson's stage for a typical toddler is:", "Autonomy vs shame/doubt", "Integrity vs despair", "Identity vs role confusion only as a toddler", "Generativity vs stagnation", "Bachelors still tests HBSE."),
        ("hgb", "A genogram is used to:", "Map family patterns across generations", "Bill Medicaid", "Replace consent", "Diagnose bipolar as a bachelor-only act in every state", "Picture the system."),
        ("hgb", "Maslow's hierarchy is a:", "Motivational model — not a diagnosis", "DSM code", "Legal test", "Budget form", "Use it lightly."),
        ("hgb", "A child who witnesses domestic violence may show:", "Regression, anxiety, or school changes — assess safety first", "Automatic sociopathy you can label forever", "No effects ever", "A reason to skip CPS rules", "Safety + development."),
        ("hgb", "Cultural humility means:", "You do not assume your norms are the client's", "You memorize one festival and stop", "You ignore culture", "You diagnose culture as a disorder", "Ask, do not impose."),
        ("hgb", "A life-course perspective looks at:", "Linked lives and timing of events, not a single snapshot", "Only the presenting problem minute", "Only income", "Only the DSM page", "Time matters."),
        ("hgb", "Attachment disruption in foster care suggests:", "Predictable caregiving and no extra placement moves if you can help it", "More surprise moves", "Ignoring the child", "A personality insult", "Stability is treatment."),
        ("hgb", "A strengths perspective starts with:", "What the client can use, not only deficits", "A label first", "Your theory first", "A lecture", "Bachelors voice is strengths + systems."),
        ("hgb", "Oppression at a macro level includes:", "Policy and structural barriers, not only one rude clerk", "A single compliment", "A genogram box", "A SOAP line only", "Person-in-environment."),
        ("hgb", "Typical adolescent risk screening includes:", "Safety, substances, and supports — not a joke", "Only grades", "Only dress code", "A full psychoanalytic training analysis", "HEADSS-style thinking."),
        ("hgb", "Grief after a death is:", "Often wavy, not a fixed five-step homework", "A personality disorder instantly", "Ignored if they smile once", "A reason to withhold resources", "Normalize + assess risk."),
        ("hgb", "Disability is understood in a social model as:", "Barriers in the environment, not only the body", "A moral failing", "Untreatable always", "A reason to skip ADA ideas", "Environment disables."),
        ("hgb", "A crisis is defined by:", "The client's experience of overwhelm, not your calm Tuesday", "A missed bus only always", "A diagnosis code requirement", "A court date only", "Start where the client is."),
        ("hgb", "Human trafficking red flags include:", "Controlling companion and no documents — follow protocol, do not freelance a rescue", "A messy backpack", "Being quiet", "Poverty alone as proof", "Protocol over heroics."),
        ("hgb", "This ASWB Bachelors mock is:", "Independent generalist practice — not the Clinical exam and not ASWB's form", "LCSW clinical", "PHR", "Praxis Core", "Level matters."),
        ("assessment", "A biopsychosocial assessment gathers:", "Body, mind, and environment — not only a diagnosis label", "A single adjective", "Only income", "Only the DSM", "Generalist assessment."),
        ("assessment", "The first interview priority with intimate-partner violence is:", "Safety planning and privacy — not couples counseling in the same room as a first move", "A joint session immediately", "A lecture", "A genogram art project only", "Safety first."),
        ("assessment", "Collateral information is:", "Other sources the client consents to — not gossip", "Facebook stalking as the plan", "A diagnosis", "A court order always", "Consent the collaterals."),
        ("assessment", "A mental-status observation you can make as a BSW is:", "Appearance, affect, and orientation — you still do not over-diagnose", "A full differential", "A prescription", "A CT read", "Observe, do not play psychiatrist."),
        ("assessment", "Risk of harm to self is assessed by:", "Ideation, plan, means, intent — then act on the level", "A vibe", "Ignoring it to be polite", "A personality insult", "Ask directly."),
        ("assessment", "A ecomap shows:", "Supports and stressors around the client", "Only ancestors", "A budget", "A lesson plan", "Systems on one page."),
        ("assessment", "Involuntary hold decisions are:", "Statute- and supervisor-driven — not a solo BSW hobby", "A Facebook poll", "Always the client's parent", "A quiz", "Know your state's duty."),
        ("assessment", "Substance use screening is:", "Standard questions, then referral — not a moral inventory", "A surprise urine you demand as a BSW office hobby", "Ignored", "A diagnosis of 'addict' in the first minute", "Screen + refer."),
        ("assessment", "A client's theory of the problem is:", "Data — start there even if you also see systems", "Wrong if not DSM", "Ignored", "A lie by definition", "Join first."),
        ("assessment", "Mandated reporting of child abuse is:", "A legal duty when you have reasonable suspicion — you do not 'investigate' like police", "Optional if the family is nice", "A therapy topic only", "Delayed for rapport forever", "Report, then support."),
        ("assessment", "A release of information must be:", "Specific and signed — not a hallway yes", "A vibe", "Forever for all topics", "Verbal to a neighbor", "HIPAA/state rules."),
        ("assessment", "Food, housing, and benefits are:", "Part of assessment — concrete needs are clinical too", "Someone else's problem always", "A diagnosis", "Optional fluff", "Case management is Bachelors core."),
        ("assessment", "A Mini-Cog or clock draw, if you use it, is:", "A screen, not a dementia diagnosis you enter as fact", "A full neuropsych", "A toy", "A court test", "Screens refer."),
        ("assessment", "When language is a barrier you:", "Get a qualified interpreter — not a child", "Use the abuser as interpreter in IPV", "Guess", "Speak louder in English", "Interpreters."),
        ("assessment", "A good Bachelors problem statement is:", "Observable and in the client's words plus context", "A roast", "A DSM dump", "A novel", "Clear and shared."),
        ("intervention", "Case management is:", "Linking, coordinating, and following resources", "Long-term psychoanalysis you invent", "A prescription", "Ignoring the housing waitlist", "Broker + advocate."),
        ("intervention", "A SMART goal for a BSW case is:", "Specific and time-bound ('apply to two apartments by Friday')", "Feel better someday", "Become enlightened", "The worker's goal only", "Goals you can see."),
        ("intervention", "Partializing a problem means:", "Breaking an overwhelm into steps", "Ignoring half the family", "Diagnosing half a code", "Closing the case", "One slice at a time."),
        ("intervention", "Advocacy at the mezzo level might be:", "A support group or a school meeting, not only a one-to-one", "A Supreme Court brief as your first BSW task always", "A silent shrug", "A secret file", "Levels of practice."),
        ("intervention", "Termination is planned when:", "Goals are met or the service ends — not a disappearing act", "You are bored", "They miss one call", "The grant feels long", "Goodbye is a skill."),
        ("intervention", "A warm handoff is:", "An introduced referral, not a paper with a number", "A cold fax only", "A lecture", "A closed door", "People connect to people."),
        ("intervention", "Motivational interviewing spirit is:", "Partnership and evocation, not a lecture on willpower", "Confrontation first", "Advice piling", "Silence only", "Even BSW can use the spirit."),
        ("intervention", "Crisis intervention first:", "Stabilize and support, then problem-solve", "A genogram in hour one of an overdose", "A life story", "A court report only", "Safety, then story."),
        ("intervention", "Group work as a BSW often is:", "Psychoeducation or support, not unstructured therapy you are not trained to run", "A process group with no supervisor", "A party", "A lecture with no interaction", "Stay in training."),
        ("intervention", "Broker role means:", "You know the resource map and the eligibility", "You invent services", "You pay their rent from your pocket as policy", "You diagnose", "Concrete help."),
        ("intervention", "If a client no-shows, you:", "Outreach per policy — barriers first, not a character attack", "Close same day with a roast", "Call their employer and disclose", "Show up at their job", "Assume transportation and shame."),
        ("intervention", "Home visit safety includes:", "Telling the office where you are and reading the room", "Going unannounced at night as a rule", "Going alone into a known violent situation against policy", "Posting the address", "Your safety is ethical too."),
        ("intervention", "Documentation of an intervention should say:", "What you did and what the client did, not 'provided therapy'", "A novel", "Nothing", "A diagnosis you are not making", "Bachelors language is services, not fake LCSW."),
        ("intervention", "Empowerment practice means:", "The client chooses among real options", "You choose for them always", "You withhold resources to teach a lesson", "You lecture", "Power with, not over."),
        ("intervention", "A discharge summary includes:", "What was tried, what is open, and who is next", "Gossip", "Nothing if they were 'difficult'", "Your political views", "The next worker can start."),
        ("ethics", "Self-determination is limited when:", "There is serious foreseeable harm — you still maximize choice inside safety", "They disagree with you", "They are poor", "They are young-looking", "NASW + law."),
        ("ethics", "Dual relationships that harm are:", "Avoided or managed with supervision — not a secret friendship that is also casework", "Required", "Always illegal in every coffee shop", "A billing code", "Power plus personal."),
        ("ethics", "Confidentiality is broken when:", "Duty to warn/protect or a mandate applies — not when a coworker is curious", "They told a joke", "They used a swear", "They missed a session", "Minimum necessary."),
        ("ethics", "Informed consent includes:", "What you will do, limits of privacy, and that they can refuse", "A signature with no talk", "A surprise recording", "A hidden intern", "No surprises."),
        ("ethics", "Competence means:", "You do not practice a method you were not trained in", "You try EMDR from a video as a BSW", "You diagnose rare syndromes for fun", "You ignore supervision", "Stay in training."),
        ("ethics", "A gift of $400 from a client is:", "A boundary issue — follow agency policy, usually decline", "A raise", "Required", "Fine if cash", "Money changes the work."),
        ("ethics", "Records requests go through:", "Agency policy and the law — not a text-photo of the chart", "Your personal Gmail", "A hallway yes", "A spouse always", "The record is the agency's."),
        ("ethics", "Social media 'friend' requests from current clients are:", "Usually a no", "Required engagement", "A treatment plan", "A release", "Keep the frame."),
        ("ethics", "When laws and ethics tension, you:", "Seek supervision and counsel — do not freelance a crime", "Pick Twitter", "Pick the easier", "Hide the file", "Process the conflict."),
        ("ethics", "Cultural competence is not:", "A single CE and a stereotype", "Asking", "Interpreters", "Humility", "Stereotypes fail."),
        ("ethics", "Billing for a visit that did not happen is:", "Fraud", "Teamwork", "A wash", "Advocacy", "Truth in the record."),
        ("ethics", "A supervisor who asks you to hide a mandated report:", "Is asking you to break the law — escalate", "Is mentoring", "Is optional ethics", "Is a dual relationship only", "Reports are not optional."),
        ("ethics", "Self-care is ethical because:", "Impaired workers harm clients", "It is a spa day requirement", "It replaces competence", "It is billed to the client", "You are the instrument."),
        ("ethics", "Research participants in an agency study need:", "Voluntary informed consent", "A forced survey to keep benefits", "No explanation", "A hidden control group of clients who asked not to be in research", "Consent is not a perk."),
        ("ethics", "The NASW Code is:", "A guide — your state law still binds", "A replacement for statutes", "Optional poetry", "A DSM", "Code + law."),
    ]

def aswb_c():
    return [
        ("assessment", "A clinical mental-status exam includes:", "Appearance, speech, mood/affect, thought, cognition, insight/judgment", "Only a smile", "Only income", "A lesson plan", "Clinical assessment is structured."),
        ("assessment", "Differential diagnosis means:", "Ruling in and out competing disorders with history and MSE", "Picking the first code in the book", "Ignoring medical causes", "A vibe", "Think medically too."),
        ("assessment", "A mental-status finding of loose associations is more consistent with:", "A thought-disorder process than with uncomplicated grief", "A sprained ankle", "A housing waitlist", "A BSW brokerage note only", "Link sign to hypothesis."),
        ("assessment", "Personality-disorder hypotheses need:", "Pervasive, stable patterns — not one bad week", "A single fight", "A missed session", "Poverty", "Duration and pervasiveness."),
        ("assessment", "Substance-induced mood symptoms require:", "A timeline of use vs mood", "Ignoring tox", "A personality insult", "Immediate BPD", "Sequence the use."),
        ("assessment", "Trauma assessment should include:", "Safety now, dissociation, and not forcing a narrative", "A full exposure in session one as a rule", "A joke", "A couples ambush", "Stabilize first."),
        ("assessment", "A suicide risk formulation includes:", "Risk and protective factors plus a plan for the next hours", "A one-word 'low' with no why", "A personality roast", "A wait-and-see with a loaded gun at home and no action", "Formulate, then act."),
        ("assessment", "Collateral from a psychiatrist is used to:", "Reconcile meds and history — with a release", "Replace your MSE", "Gossip", "A diagnosis you rubber-stamp unread", "Integrate."),
        ("assessment", "Malingering vs factitious vs conversion is a:", "Clinical differential, not a moral snap", "A joke", "Always malingering if they want a letter", "Always conversion if they cry", "Function of the symptom."),
        ("assessment", "A cognitive screen that is failed is:", "A reason for further eval, not a dementia stamp you treat as final", "A full neuropsych", "Ignored", "A custody decision by itself", "Screens refer."),
        ("assessment", "Cultural formulation asks:", "How the client names the problem and what help looks like", "Your stereotype", "Only English idioms", "A code first", "DSM cultural sections exist for a reason."),
        ("assessment", "A personality inventory you are not trained to interpret should be:", "Left to someone who is — or you get the training", "Used as a party game", "The only data", "Posted", "Competence."),
        ("assessment", "Sleep, appetite, and energy are:", "Vegetative signs that belong in a mood workup", "Optional color", "Only for inpatient", "A BSW housing item only", "Neurovegetative."),
        ("assessment", "A first psychotic break history must include:", "Medical, substance, and timeline — not only 'schizophrenia' at minute ten", "A life sentence label", "No family history", "No safety plan", "First episode is medical until not."),
        ("assessment", "This ASWB Clinical mock is:", "Independent LCSW-style practice — not Bachelors case management and not ASWB's form", "LSW only", "PHR", "Praxis", "Level is clinical."),
        ("diagnosis", "A major depressive episode requires:", "The DSM duration and symptom count — not a sad afternoon", "One tear", "A bad grade", "Poverty as the code", "Criteria, not vibes."),
        ("diagnosis", "Mania vs hypomania is separated by:", "Severity, duration, and impairment/hospitalization — not your excitement", "Shopping once", "A good mood", "Caffeine only always", "Know the line."),
        ("diagnosis", "Panic attack ≠ panic disorder until:", "The worry about attacks or change in behavior is there as criteria say", "One attack in a crowd", "A fast heart at the gym once", "A personality label", "Syndrome vs event."),
        ("diagnosis", "PTSD requires:", "A qualifying trauma plus the cluster pattern, not 'I was stressed at work'", "Any annoyance", "A single nightmare with no other clusters", "A fight with a coworker", "Criterion A is not optional."),
        ("diagnosis", "OCD is:", "Obsessions and/or compulsions that are time-consuming or impairing", "Liking a tidy desk", "A joke about hand gel", "Psychosis", "Ego-dystonic loops."),
        ("diagnosis", "A personality disorder is not diagnosed from:", "A single crisis week", "A long pattern across contexts", "Impairment", "Early onset typical of the type", "Need the pattern."),
        ("diagnosis", "Schizophrenia spectrum work includes:", "Duration, symptom types, and ruling out substances/medical", "A quirky teen", "Poverty", "A single voice when fevered only, as the lifelong code", "Time and type."),
        ("diagnosis", "An adjustment disorder is:", "A marked response to a stressor that is not another full disorder", "A personality", "Bipolar I", "Malingering by default", "Stressor-linked."),
        ("diagnosis", "Neurodevelopmental vs trauma-related attention problems:", "Need history — do not rubber-stamp ADHD in a newly unsafe teen without thinking", "Are identical", "Never overlap", "Are always malingering", "Developmental timeline."),
        ("diagnosis", "A rule-out medical note is there because:", "Thyroid, sleep apnea, and substances mimic psychiatry", "Doctors are optional", "Codes need more letters", "Insurance likes Latin", "Body first."),
        ("diagnosis", "Comorbidity means:", "Two (or more) disorders, not sloppy double-coding of the same symptoms", "A personality insult", "A billing trick only", "A couple in therapy", "Do not double dip the same insomnia."),
        ("diagnosis", "Z-codes / psychosocial problems are:", "Real and should be recorded — housing is not 'just axis IV nostalgia'", "Fake", "A diagnosis of psychosis", "Optional always", "Context is clinical."),
        ("diagnosis", "Provisional is used when:", "You think it is X but need more time", "You are sure", "You are joking", "You want to hide uncertainty forever without a plan", "Name the uncertainty."),
        ("diagnosis", "Severity specifiers exist to:", "Describe impairment, not to moralize", "Raise fees only", "Replace criteria", "Skip the interview", "Mild/mod/severe is data."),
        ("diagnosis", "You do not give a client a surprise personality-disorder label in the lobby because:", "It is stigmatizing, often wrong, and not how you share a formulation", "They asked for coffee", "It is funny", "Insurance requires a public reading", "Formulation is a conversation."),
        ("psychotherapy", "A CBT thought record is for:", "Linking situation, thought, feeling, and a reframe", "Free association only", "EMDR as a BSW", "A genogram only", "Cognitive work is structured."),
        ("psychotherapy", "Exposure for anxiety requires:", "A hierarchy and consent — not flooding a phobia on a dare", "Avoidance as the plan", "A surprise snake", "Medication only as your sole tool always", "Collaborative exposure."),
        ("psychotherapy", "Transference is:", "Feelings toward you that belong partly to older relationships — you use it, you do not punish it", "A reason to fire them in shame", "Always sexual", "A billing code", "Use, don't act out."),
        ("psychotherapy", "Countertransference is:", "Your feelings — supervision, not a dual relationship", "Always love", "Ignored if you are senior", "Shared on a podcast", "Get a consult."),
        ("psychotherapy", "MI rolling with resistance means:", "You do not argue for change while they argue against it", "You lecture harder", "You diagnose defiance", "You end the case", "Dance, don't wrestle."),
        ("psychotherapy", "A behavioral activation plan for depression is:", "Scheduled valued activity, not 'cheer up'", "A surprise party", "A confrontation", "A personality label", "Action before mood."),
        ("psychotherapy", "DBT skills you might use (if trained) include:", "Distress tolerance and emotion regulation — not a personality insult", "A roast", "A surprise exposure", "A silent stare only", "Skills, then processing."),
        ("psychotherapy", "Termination in psychotherapy is:", "Processed, not a text that says 'bye'", "A no-show close with no letter", "A dual relationship start", "A Facebook friend request as the ritual", "The last phase is treatment."),
        ("psychotherapy", "Homework in CBT fails when:", "It is vague or shaming", "It is specific and reviewed", "It is collaborative", "It is small", "Review it or it dies."),
        ("psychotherapy", "A rupture in alliance is handled by:", "Naming it and repairing, not pretending", "Ending without talk", "A dual coffee date", "A diagnosis of NPD in the room as revenge", "Rupture-repair is the work."),
        ("psychotherapy", "EMDR, PE, or CPT for PTSD should be:", "Provided only if you are trained — else refer", "Tried from a thread", "A first-session flood", "A couples ambush", "Competence."),
        ("psychotherapy", "Family therapy is the unit of:", "The system — not a secret individual alliance that sabotages the work without a frame", "One identified patient you roast to the others", "A lecture", "A genogram only with no talk", "Contract the frame."),
        ("psychotherapy", "Telehealth therapy still needs:", "Privacy, emergency address, and licensure where the client sits", "A coffee shop table", "A dual-state guess", "No crisis plan", "The client location is the license."),
        ("psychotherapy", "Interpreters in therapy should be:", "Professionals, not children", "Family who also abuse", "Skipped", "Your bilingual friend on speaker in a store", "The frame includes language."),
        ("psychotherapy", "You do not use therapy to:", "Meet your own needs for friendship or attraction", "Help the client", "Keep records", "Get supervision", "The relationship is for them."),
        ("ethics", "Duty to warn/protect (Tarasoff-type) is:", "A jurisdiction-specific duty when there is a serious threat to an identifiable victim", "A brain dump to the town paper", "Optional if you like the client", "A BSW only rule", "Know your state."),
        ("ethics", "A subpoena for records is:", "Handled with counsel and the minimum required — not a full chart dump in email", "A hallway yes", "Ignored always", "Posted", "Legal + privilege."),
        ("ethics", "Sexual dual relationships with current clients are:", "Prohibited", "A grey area if they initiate", "Fine after two sessions", "A treatment", "Never."),
        ("ethics", "Bartering is:", "Usually unwise; if allowed, it is documented and not exploitive", "Required", "Always illegal in every café", "A dual-free zone always", "Power + money."),
        ("ethics", "Clinical notes vs psychotherapy notes (HIPAA):", "Know which you keep and how a request works in your setting", "They are the same always", "You can hide illegal acts in 'psych notes'", "No notes is safest", "Two buckets."),
        ("ethics", "An impaired colleague who is seeing clients drunk is:", "A duty-to-act / report situation — clients are at risk", "A private joke", "Fine if they are 'gifted'", "Your blackmail", "Protect the public."),
        ("ethics", "Informed consent for a high-risk exposure includes:", "What will happen, risks, and the stop rule", "A surprise", "A waiver that they cannot leave", "A hidden camera", "No surprises."),
        ("ethics", "A Google search of a client is:", "An ethics issue unless there is a safety reason you document", "Required stalking", "Fine for gossip", "A dual relationship fix", "Curiosity is not a reason."),
        ("ethics", "When a couple asks you to testify in their custody fight after seeing you jointly:", "You have a role conflict — get consult; you are not their hired gun by default", "Pick a favorite", "Write a surprise affidavit", "Read the notes on TV", "Forensic vs treatment."),
        ("ethics", "Fees and no-shows should be:", "In the informed consent, not a surprise bill-as-revenge", "Invented weekly", "Hidden", "A dual gift card", "Money is clinical."),
        ("ethics", "Competence in a new modality requires:", "Training and supervision, not a weekend badge as mastery", "A podcast", "A vibe", "A client to practice on uninformed", "Do not practice on them."),
        ("ethics", "A client who is also your student's parent is:", "A multiple relationship to manage or decline", "Ideal", "Required in small towns with no thought", "A research subject automatically", "Name it."),
        ("ethics", "Retaining records follows:", "State and HIPAA timelines — not your closet space", "Until you move", "One week", "Forever on a personal laptop with no encryption as a plan", "Retention + security."),
        ("ethics", "If ethics and a supervisor's illegal order conflict:", "You do not break the law — escalate", "You obey", "You hide", "You post", "Clients and law win."),
        ("ethics", "The Clinical exam still sits under:", "The same NASW/state board duties plus a deeper diagnostic/treatment frame", "No ethics", "Only Bachelors brokerage", "PHR", "Ethics scale with power."),
    ]

MLT = [
    ("blood-bank", "A critically high potassium on a hemolyzed chemistry tube should first prompt:", "A recollection — do not treat the hemolysis as the patient's K", "Immediate calcium gluconate you order as an MLT", "A crossmatch", "A blood culture", "Preanalytical first."),
    ("blood-bank", "Forward typing detects:", "Antigens on the red cells with known antibodies", "Antibodies in serum only", "DAT only", "Kleihauer", "A + D cells."),
    ("blood-bank", "Reverse typing uses:", "Patient serum/plasma plus A1 and B cells", "Anti-A and anti-B on cells only", "A DAT", "An elution first always", "Reverse confirms."),
    ("blood-bank", "A type A patient should reverse as:", "4+ with B cells, negative with A1 cells (typical)", "4+ with both", "Negative with both always if they are A", "Only with O cells", "Landsteiner."),
    ("blood-bank", "The AHG phase is used because:", "It detects IgG that does not agglutinate in saline", "It measures sodium", "It is a gram stain", "It is a PT/INR", "Coombs."),
    ("blood-bank", "An antibody screen is for:", "Unexpected red-cell antibodies in the patient", "A CBC", "A culture", "A BMP", "Screen before crossmatch."),
    ("blood-bank", "A DAT positive on a newborn may indicate:", "Maternal IgG on baby cells — HDFN workup", "A clean bill", "A potassium", "A UA", "DAT is not a toy."),
    ("blood-bank", "RhIG is considered when:", "An Rh-negative mother is at risk of forming anti-D", "The mother is D-positive and unsensitized as a routine", "A man has a CBC", "A urine dip", "Protect the next pregnancy."),
    ("blood-bank", "A unit for transfusion must be:", "Clerically identical at the bedside — the MLT's issue check is not optional", "Issued by memory", "Unlabeled if busy", "Warmed in a microwave as policy", "Clerical error kills."),
    ("blood-bank", "FFP is stored:", "Frozen, then thawed per procedure — not as a fridge RBC", "At 37 °C for weeks", "In the chemistry freezer unlabeled", "At room temp for a month", "Product, temperature, time."),
    ("blood-bank", "A crossmatch incompatibility in AHG means:", "Do not issue that unit — investigate", "Issue anyway if they are crashing without a protocol", "Ignore", "Give platelets instead as a guess", "Incompatible is a stop."),
    ("blood-bank", "Platelets are stored:", "With agitation at room temp for their dating", "Frozen like FFP always", "At 1–6 °C like RBCs always", "In a pocket", "Know storage."),
    ("blood-bank", "An emergency uncrossmatched O-neg (or group-specific per protocol) is:", "A physician-released emergency — still document", "A routine", "An MLT hobby", "A chemistry add-on", "Protocol + signature."),
    ("blood-bank", "A transfusion reaction workup starts with:", "Clerical check and a DAT / visual hemolysis per SOP — stop the unit", "A lecture", "Ignoring fever", "Giving the rest of the unit faster", "Stop, then work up."),
    ("blood-bank", "This MLT mock is:", "Independent technician-level lab practice — not the MLS exam form and not ASCP's test", "MLS only", "PHR", "NATE", "Same benches, technician items."),
    ("chemistry", "A hemolyzed specimen falsely raises:", "Potassium and LD among others", "Sodium only as a decrease always", "TSH as a diagnosis", "Blood type", "Know the interferent."),
    ("chemistry", "A fasting glucose of 55 mg/dL in an outpatient should be:", "Called as a critical if that is your list — do not wait for the next courier story", "Filed", "Repeated next year only", "A blood bank type", "Criticals have times."),
    ("chemistry", "Troponin is used for:", "Myocardial injury workup — timing matters", "A UA", "A type and screen", "A culture", "Serial troponins."),
    ("chemistry", "A bilirubin on a light-exposed baby tube may be:", "Falsely low — protect from light", "Falsely high always", "A type", "A gram stain", "Photosensitive analytes."),
    ("chemistry", "eGFR is estimated from:", "Creatinine (and age/sex as the equation uses) — not a vibes GFR", "A dipstick only", "A DAT", "A PT", "Know the equation inputs."),
    ("chemistry", "A lipemic sample can:", "Interfere with spectrophotometric assays — ultracentrifuge or comment per SOP", "Change ABO antigens", "Sterilize the tube", "Replace QC", "Lipemia is preanalytical."),
    ("chemistry", "HbA1c reflects:", "Weeks of glucose exposure, not this morning's donut alone", "A spot glucose only", "A blood gas", "A culture", "Glycation window."),
    ("chemistry", "An anion gap is:", "Na − (Cl + HCO3) as your lab calculates", "A liver enzyme", "A blood type", "A culture media", "Gap is arithmetic."),
    ("chemistry", "A chemistry analyzer flag for clot means:", "Do not report — recast or recollect", "Report anyway", "Dilute with water", "Call it a type A", "Flags are stops."),
    ("chemistry", "Quality control that is out 1-3s on a Westgard think might be:", "A random error — follow the SOP, do not hide the point", "A reason to skip QC for a week", "A blood bank elution", "A gram stain", "QC before patients."),
    ("chemistry", "Ammonia specimens are often:", "On ice and assayed fast", "Left on a warm window", "A 24-hour room-temp wait as ideal", "A stool card", "Labile."),
    ("chemistry", "A delta check on creatinine that jumps overnight may be:", "Wrong patient or IV fluid mix-up — investigate", "Ignored", "Always a miracle recovery", "A type change", "Deltas catch ID errors."),
    ("chemistry", "Therapeutic drug levels need:", "The draw time relative to the dose", "A random anytime with no note", "A DAT", "A culture", "Peak/trough."),
    ("chemistry", "Point-of-care glucose that does not match the patient should be:", "Repeated and correlated — do not treat a strip error", "Trusted blindly", "A type and screen", "A stool", "Correlate."),
    ("chemistry", "A panic calcium is called to:", "The licensed caregiver on the list — read back", "The janitor", "Voicemail only as your only try", "A family member as the official", "Read-back."),
    ("hematology", "A CBC flag for blasts is:", "A smear review — do not auto-release if SOP says hold", "Ignored", "A chemistry add", "A type A", "Morphology still matters."),
    ("hematology", "MCV high with anemia suggests:", "A macrocytic picture (B12/folate/liver/marrow) — not a micro iron story", "Iron deficiency as the first tale", "A normal smear always", "A blood type", "Use the indices."),
    ("hematology", "A platelet clump on EDTA can:", "Falsely lower the count — citrate recollect as SOP", "Be ignored", "Raise the WBC always as the only effect", "Change ABO", "Pseudothrombocytopenia."),
    ("hematology", "An ESR is:", "A nonspecific inflammation marker, not a diagnosis", "A culture", "A type", "A glucose", "Nonspecific."),
    ("hematology", "A malaria smear is:", "Thick and thin, timed — not a casual Wright glance as 'negative' without looking", "A BMP", "A UA", "A DAT only", "Look at the film."),
    ("hematology", "INR is used to:", "Monitor warfarin-style anticoagulation as the clinician ordered", "Type blood", "Culture urine", "Measure K", "PT/INR."),
    ("hematology", "A clotted CBC tube is:", "Rejected", "Run anyway", "Warmed and forced", "Pooled with another patient", "Clots wreck counts."),
    ("hematology", "Reticulocyte count helps tell:", "Whether the marrow is answering an anemia", "The ABO group", "The gram stain", "The BMP", "Production vs loss."),
    ("hematology", "A differential with 40% eos in a traveler may need:", "A path review / parasite thought — not auto-file", "A type and screen only", "Ignored", "A glucose", "Uncommon diffs get eyes."),
    ("hematology", "D-dimer is:", "A fibrin-degradation marker with huge negative-predictive use in the right pretest", "A blood type", "A culture", "A UA", "Pretest probability."),
    ("hematology", "A body-fluid count should be:", "Done as a sterile, timed, labeled procedure — not a leftover syringe in a pocket", "Guessed", "Pooled", "Left overnight on a radiator", "Fluids are STAT-ish."),
    ("hematology", "Sickle solubility tests:", "Screen — they do not replace electrophoresis when you need a type", "Are a CBC", "Are a DAT", "Are a culture", "Know reflex."),
    ("hematology", "A critical WBC of 1.0 with fever is:", "Called — neutropenia is an emergency for the clinician", "Filed at leisure", "A type", "A stool", "Criticals."),
    ("hematology", "Smear stain too blue/pink means:", "Fix the stain, do not invent morphology", "Report blasts for fun", "A chemistry", "A type", "Stain quality."),
    ("hematology", "The MLT role on a hematology line is:", "Validating flags and knowing when a smear/path review is required", "Making the oncology plan", "Ignoring deltas", "Signing out a bone-marrow consult as attending", "Technician judgment is real."),
    ("micro", "A blood culture that is drawn through a dirty port is:", "A contaminant risk — redo the draw right", "Gold standard", "A chemistry", "A type", "Prep the skin."),
    ("micro", "Gram-positive cocci in clusters from a wound are:", "Staph-like until identified — not a 'strep throat' story", "Always C. diff", "A fungus only", "A blood type", "Morphology first."),
    ("micro", "C. difficile testing is on:", "Loose stool, not a formed 'just in case' as many algorithms say", "A BMP", "A type", "A CBC", "Right specimen."),
    ("micro", "Acid-fast stain is for:", "Mycobacteria suspicions — not a routine throat", "A UA dip", "A DAT", "A glucose", "AFB has a reason."),
    ("micro", "A CSF with organisms on Gram stain is:", "A critical call — do not wait for the full ID to notify", "A routine Monday", "A type and screen", "A stool", "Minutes."),
    ("micro", "Kirby-Bauer / AST QC that fails means:", "Do not report patient AST from that run", "Report anyway", "Dilute the disks with water", "Call it susceptible across the board", "QC gates reports."),
    ("micro", "A stool culture in a patient hospitalized 5 days with new diarrhea is often:", "Not a community Salmonella hunt — think C. diff per protocol", "A throat screen", "A type", "A CBC", "Healthcare vs community."),
    ("micro", "Viral transport for a PCR must be:", "The right swab and media — a dry wood swab can kill the test", "A random cotton ball", "A chemistry gold top", "A bag of air", "Collection is the test."),
    ("micro", "A positive blood culture gram stain is called to:", "The caregiver with organism morphology — read back", "The cafeteria", "Voicemail only as your single try on a septic patient", "A family member as official", "Call it."),
    ("micro", "India ink / CrAg is in the thought process for:", "Cryptococcus in the right host — not a strep screen", "A UA", "A type", "A BMP", "Yeast in CSF."),
    ("micro", "Anaerobic culture needs:", "Proper transport — a dry swab sitting 6 hours is a waste", "A post card", "A frozen BMP", "A DAT", "Oxygen kills anaerobes."),
    ("micro", "MRSA PCR on a nares swab is:", "A colonization/infection-control tool, not a blood culture", "A type and screen", "A glucose", "A UA", "Know the question the test answers."),
    ("micro", "A plate with mixed skin flora on a poorly collected wound is:", "Likely contamination — comment, do not over-work garbage", "A reason to ID 12 organisms as pathogens", "A blood bank problem", "A CBC", "Specimen quality."),
    ("micro", "Biosafety for a possible Brucella plate is:", "Do not sniff plates; work in the right cabinet", "A deep sniff for 'grape'", "A bench joke", "A lunch companion", "Do not inhale the unknown."),
    ("micro", "The MLT does not:", "Choose the patient's antibiotic as the attending", "Do a Gram stain", "Call a critical", "Reject a bad specimen", "Stay in the bench role."),
]


def main() -> None:
    build("phr-hrci-readiness-check", PHR, "HRCI PHR")
    build("unarmed-security-officer-readiness-check", UNARMED, "unarmed guard")
    build("praxis-core-readiness-check", CORE, "Praxis Core")
    build("aswb-bachelors-readiness-check", aswb_b(), "ASWB Bachelors")
    build("aswb-clinical-readiness-check", aswb_c(), "ASWB Clinical")
    build("ascp-mlt-readiness-check", MLT, "ASCP MLT")


if __name__ == "__main__":
    main()
