#!/usr/bin/env python3
"""P1 remaps batch A: barber, nails, PT aide, med aide, first aid, PN, NSCA-CPT."""

from p1_remap_lib import build

BARBER = [
    ("infection", "Between clients, a barber must:", "Clean and disinfect tools that contacted skin or blood", "Wipe clippers on a cape and reuse", "Rinse shears in the shampoo bowl only", "Store dirty blades in the station drawer", "State boards treat clippers and blades as disinfectable implements."),
    ("infection", "A nick that draws blood requires:", "Stop, glove, use antiseptic, and discard contaminated disposables", "Continue the shave and wipe later", "Blow on the cut", "Use the same towel on the next client", "Blood exposure is a stop-and-disinfect event."),
    ("infection", "A wet sanitizer or EPA-registered disinfectant is for:", "Nonporous implements after cleaning debris off", "Skin as an aftershave", "Capes between every haircut without washing", "Floors only", "Disinfectant follows cleaning; it is not a leave-on skin product."),
    ("infection", "Porous items such as a neck strip should be:", "Single-use and discarded", "Disinfected and reused all day", "Shared if they look clean", "Washed with shampoo only", "Porous single-use items cannot be disinfected reliably."),
    ("infection", "Clipper blades after a faded haircut should be:", "Brushed, then disinfected per the label contact time", "Sprayed and used immediately while wet on the next neck", "Wiped with a dry towel only", "Left in a closed bag overnight dirty", "Contact time on the disinfectant label matters."),
    ("infection", "A client with open scalp sores should be:", "Referred out; do not cut over broken skin", "Shaved closest to 'clean' the area", "Covered with powder and faded", "Ignored if they signed a waiver", "Broken skin is outside a routine barber service."),
    ("infection", "Handwashing at the shop is required:", "Before service and after any blood or chemical contact", "Once a week", "Only if the client asks", "Instead of disinfectant on tools", "Hands and tools are separate controls."),
    ("infection", "A covered soiled-linen hamper exists so:", "Used towels are not piled on the station", "Towels can be reused on two clients", "Capes never get washed", "Neck strips can dry and return to service", "Soiled linens stay contained."),
    ("infection", "Quats or hospital-grade disinfectant must sit:", "For the full listed contact time on a pre-cleaned tool", "For one second as a mist", "Until it evaporates on the skin", "In a coffee cup at the register", "Contact time is the kill step."),
    ("infection", "A strop used only on a clean razor is:", "Kept clean and not a substitute for disinfection of a soiled blade", "How you disinfect after a blood nick", "Shared as a face towel", "Stored in the dumpster", "Leather strops are not EPA disinfection."),
    ("infection", "Shop floors with hair should be:", "Swept so hair is not tracked into the next service", "Left until closing always", "Blown toward the waiting area", "Used as a dry mop for blood", "Hair control is part of sanitation."),
    ("infection", "An autoclave, where a shop uses one, is for:", "Sterilizing approved metal implements after cleaning", "Warming shaving cream", "Drying towels", "Storing clipper oil", "Heat sterilization is not a cream warmer."),
    ("infection", "If a disinfectant is cloudy or past expiration:", "Replace it; do not guess the concentration", "Add more water to stretch it", "Use it only on combs", "Save it for blood spills", "Spent solution does not disinfect."),
    ("infection", "A barber with weeping dermatitis on the hands should:", "Not perform services until cleared or gloved per board rules", "Work faster to finish the book", "Use extra talc", "Have the client hold the clipper", "Infectious hand conditions stop service."),
    ("infection", "This UniPrep barber mock is:", "An independent diagnostic — not a state board written exam", "The official NIC barber form", "A nail-tech exam", "A cosmetology colorist paper", "Honesty: we are not the board."),
    ("cutting", "A taper fade is built by:", "Blending clipper lengths from short to long with no shelf", "One guard on the entire head", "Shaving the scalp bald only", "Color filler on porous ends", "Fades are clipper-over-comb and guard blending."),
    ("cutting", "Clipper-over-comb is used to:", "Remove bulk and blend without a hard line", "Apply relaxer", "Strop a straight razor", "Set a perm rod", "It is a cutting technique, not a chemical service."),
    ("cutting", "A straight-razor shave along the grain first is meant to:", "Reduce irritation before a closer pass", "Replace disinfection", "Thin a wig", "Apply haircolor", "With-the-grain is the safer first pass."),
    ("cutting", "A neckline should be:", "Crisp, even, and appropriate to the agreed style", "Burned in with a lighter", "Cut with nail nippers", "Ignored if the fade is good", "The neckline finishes the cut."),
    ("cutting", "Shear-over-comb on top is for:", "Soft texture and length control", "Disinfecting shears", "Shaving a beard dry", "Mixing developer", "Shears control top length, not sanitation."),
    ("cutting", "Cross-checking a haircut means:", "Looking at the cut from another angle or section to catch holes", "Charging twice", "Skipping the fade", "Using a hot towel only", "Cross-check is quality control."),
    ("cutting", "A bald fade that nicks the skin is usually from:", "A blade too aggressive or a dry, rushed pass", "Too much conditioner", "A wide-tooth comb only", "Leaving a #4 guard on", "Skin fades need control, not speed."),
    ("cutting", "Beard lining with a trimmer should:", "Follow bone structure and the client's requested line", "Shave into the neck rash", "Use a dull rusty blade", "Skip a comb", "Lines are design choices on clean skin."),
    ("cutting", "Thinning shears are for:", "Removing bulk without losing the outline", "Cutting a child's bangs as the only shear", "Opening bottles", "Shaving necks", "They texture; they do not replace cutting shears."),
    ("cutting", "A hot-towel lather shave includes:", "Softening hair and skin before the razor", "Dry shaving against the grain first always", "No drape", "Using the towel on two faces", "Towels prep the hair; they are single-client."),
    ("cutting", "Clipper guards are numbered so:", "You can repeat a length", "They replace disinfection", "Higher numbers always mean shorter hair", "They measure ounces of product", "Guards are length tools."),
    ("cutting", "A hard part is created by:", "Cutting or shaving a clean part line the client asked for", "A foil highlight", "A nail art brush", "A perm solution", "Hard parts are cut lines, not color."),
    ("cutting", "When blending a beard into a skin fade, avoid:", "A dark shelf where the beard meets the cheek fade", "Using any oil", "Asking the client how low", "A mirror check", "The join is the hard part of a beard fade."),
    ("cutting", "A client's cowlick at the crown is handled by:", "Cutting with the growth pattern, not against it blindly", "Shaving the crown bald always", "Ignoring growth", "Coloring it darker only", "Growth pattern drives the cut."),
    ("cutting", "Outlining the temple should:", "Match both sides and the agreed tightness", "Be freehand different every time with no check", "Use a razor on a mole", "Skip if busy", "Symmetry is the job."),
    ("chemistry", "Barber chemical services (relaxer, color, texture) require:", "A patch or strand test when the product and board require it", "Guessing the volume of developer", "Using kitchen bleach", "Skipping gloves", "Chemicals are not 'just a cut'."),
    ("chemistry", "A relaxer cream on the scalp that burns should be:", "Rinsed immediately per the manufacturer's emergency steps", "Covered with more product", "Left on to 'process through'", "Neutralized with haircolor", "Burning is a rinse-now event."),
    ("chemistry", "Hydrogen peroxide developer is for:", "Oxidative color or bleach systems as labeled", "Disinfecting clippers", "Drinking", "Thinning shears", "Developer is a color oxidizer."),
    ("chemistry", "A client wanting a bald-black dye on a grey beard should be told:", "Skin staining and allergy risk — follow the beard-color directions", "Any boxed dye is fine on skin", "Use relaxer instead", "Skip a stain barrier", "Beard color is a skin-adjacent chemical."),
    ("chemistry", "Neutralizing a thio relaxer is done to:", "Stop the straightening process and rebuild bonds as directed", "Add more waving lotion", "Skip shampoo", "Set a hard part", "Neutralizer is a required step, not optional."),
    ("chemistry", "Aniline-derivative tint on lashes or brows is:", "Prohibited in most shops — not a barber brow service", "A standard fade finish", "Safer than shampoo", "Required by OSHA for clippers", "Eye-area aniline tints are a classic board fail."),
    ("chemistry", "A patch test is typically read:", "After the time the manufacturer and board specify, often 24–48 hours", "While the client is in the chair for a fade", "Never", "After six months", "Allergy tests need time."),
    ("chemistry", "Mixing two brands of relaxer 'to make it stronger' is:", "Outside the label — a chemical injury risk", "Best practice", "Required for coarse hair", "How you disinfect", "Do not improvise caustic mixtures."),
    ("chemistry", "After a chemical service, metal implements that touched product should be:", "Cleaned and disinfected before the next client", "Wiped on a cape", "Left sticky", "Used to cut a child's bangs immediately", "Product residue is still contamination."),
    ("chemistry", "A client on minoxidil who wants a close shave should be:", "Asked about skin sensitivity; shave gently or defer if inflamed", "Shaved raw to 'help the drug'", "Given relaxer", "Ignored", "Medications change skin tolerance."),
    ("chemistry", "Alcohol-based aftershave on freshly nicked skin can:", "Sting and delay clotting — treat the nick first", "Replace disinfectant on tools", "Sterilize the razor", "Lighten a fade", "Skin first, fragrance later."),
    ("chemistry", "A texture service that overprocessed the hair needs:", "A gentle reconstructive plan, not more chemical", "Another full relaxer same day", "A razor shave of the damage only", "Bleach", "Stop the chemical assault."),
    ("chemistry", "MSDS/SDS in the shop is for:", "Looking up first aid and handling for a product", "Client entertainment", "Tax forms", "Clipper oil recipes only", "SDS is the emergency sheet."),
    ("chemistry", "Gloves during color or relaxer protect:", "The barber's skin from repeated chemical exposure", "The clipper motor", "The cape from hair", "The cash drawer", "PPE is for the licensee too."),
    ("chemistry", "A 'natural' henna sold for beards may still:", "Stain skin and trigger allergy — treat it as a chemical", "Be food", "Disinfect tools", "Replace a taper", "Plant dyes are still chemicals on skin."),
    ("laws", "A barber license must be:", "Current and displayed as the board requires", "Lent to an apprentice for the weekend", "Optional if you only fade", "Replaced by a nail license", "The license is personal and posted."),
    ("laws", "An unlicensed person in the shop may not:", "Perform paid haircuts or shaves", "Sweep hair", "Book appointments", "Wash towels", "Unlicensed practice is the board's core charge."),
    ("laws", "Client records for chemical services should include:", "Date, service, and any test or incident notes the board expects", "Credit-card CVV", "Home Wi-Fi password", "Nothing", "Document what you did."),
    ("laws", "A minor in the chair generally needs:", "A parent/guardian as state law requires for services or photos", "No communication", "A relaxer by default", "A shared razor with an adult", "Minors have extra consent rules."),
    ("laws", "Advertising as an MD or 'scalp surgeon' without a license is:", "Prohibited misleading advertising", "Fine if the fade is good", "Required for balding clients", "A sanitation rule", "Scope includes how you advertise."),
    ("laws", "A shop inspection can result in:", "Fines or closure for sanitation or licensing failures", "A free haircut for the inspector", "Automatic pass if music is playing", "Only a nail-tech citation", "Boards inspect barber shops."),
    ("laws", "Continuing education, where required, is:", "Needed to renew on time", "Optional forever", "Satisfied by Instagram", "The same as a nail CE course always", "Meet your state's hours."),
    ("laws", "Refusing service because of a client's race is:", "Unlawful discrimination", "Shop prerogative", "A sanitation rule", "Required by the board", "Public-accommodation law applies."),
    ("laws", "A booth renter is still:", "Responsible for their license and station sanitation", "Exempt from disinfection", "Allowed to use an expired license", "A medical doctor", "Independent contractor ≠ unlicensed."),
    ("laws", "Using a straight razor where the state requires a separate endorsement means:", "Get the endorsement or do not offer that shave", "Ignore it on Sundays", "Use a kitchen knife", "Have the client sign a waiver only", "Endorsements are real."),
    ("laws", "Tips do not replace:", "Sales tax or shop policies on reporting, where they apply", "Disinfection", "A license", "A drape", "Money handling is still regulated."),
    ("laws", "Photographing a client for social media requires:", "Consent — especially for faces of minors", "No permission ever", "Only a fade", "A relaxer first", "Likeness needs consent."),
    ("laws", "If you know a coworker is unlicensed and cutting:", "You can be pulled into a shop violation — report per board rules", "Cover for them", "Split the chair", "Call it an internship automatically", "The shop shares risk."),
    ("laws", "A mobile or event cut still needs:", "A license and sanitation you can prove", "No tools cleaned", "A borrowed license photo", "Only Venmo", "The board follows the service, not the building."),
    ("laws", "Closing a shop for the night includes:", "Securing chemicals and leaving implements not sitting in dirty water", "Leaving razors in the sink", "Propping the door", "Sharing the till code on a sticky note by the door", "Close-out is part of safety."),
]

NAIL = [
    ("infection", "Implements that draw blood on a nail service must be:", "Removed from service, cleaned, and disinfected or discarded if porous", "Wiped on the towel and reused", "Rinsed in the pedicure bowl", "Given to the client as a souvenir", "Blood on a file is a contamination event."),
    ("infection", "A porous nail file that is worn or bloodied is:", "Discarded", "Soaked in quats and reused for a month", "Washed with soap only", "Shared between toes and fingers all day", "Porous files are single-client when soiled."),
    ("infection", "Pedicure basins between clients need:", "Cleaning and disinfection of jets/filters per board and manufacturer", "A splash of shampoo", "A candle", "Nothing if the water looks clear", "Whirlpool pipes grow biofilm."),
    ("infection", "Nippers used on a hangnail should be:", "Cleaned of debris, then fully disinfected", "Dipped for one second", "Wiped on the client's sock", "Stored in a purse", "Metal tools follow clean-then-disinfect."),
    ("infection", "Gloves during a pedicure protect:", "The tech from fungi and chemicals, and the client from your skin flora", "Only the polish bottle", "The lamp", "The cash wrap", "Gloves are standard on feet."),
    ("infection", "A client with suspected nail fungus should be:", "Referred to a physician; do not push a 'fungus bit'", "Filed aggressively to 'air it out'", "Covered with thick acrylic", "Soaked in bleach", "Diagnosis and treatment of infection is not a nail-tech scope."),
    ("infection", "Single-use toe separators are:", "Discarded after the client", "Washed and reused", "Shared if sprayed", "Used as files", "Foam is porous."),
    ("infection", "UV/LED lamps do not:", "Replace disinfection of metal tools", "Cure some gels as designed", "Need a clean surface", "Matter at all", "Lamps cure product; they do not sterilize nippers."),
    ("infection", "Handwashing is required:", "Before and after each client and after glove removal", "Monthly", "Only after lunch", "Instead of basin disinfection", "Hands ≠ tubs."),
    ("infection", "A covered sharps or discard plan is needed for:", "Used blades, bits, and bloody disposables", "Extra polish", "Magazines", "Cotton that is clean", "Sharps and blood go in the right container."),
    ("infection", "Metal bits on an e-file after a fill should be:", "Brushed, then disinfected or sterilized as the board allows", "Left caked with product", "Wiped on a sponge and reused instantly", "Shared wet", "Bits contact the nail plate."),
    ("infection", "If disinfectant in the jar is cloudy:", "Change it", "Add water", "Use it on skin", "Save it for pedicures only", "Cloudy solution is spent."),
    ("infection", "A wart on a client's foot means:", "Do not work over it; refer out", "Cut it out with nippers", "Sand it off with a coarse bit", "Cover with glitter", "Warts are infectious."),
    ("infection", "Clean towels for each pedicure exist so:", "Skin cells and fungus are not shared", "The shop looks expensive", "You can skip disinfectant", "Bowls never need cleaning", "Linens are single-client."),
    ("infection", "This nail mock is:", "Independent UniPrep practice — not a state board written", "The official NIC nails form", "A barber fade exam", "A PHR test", "We are not the board."),
    ("nail-anatomy", "The nail plate is:", "The visible hard keratin you file and enhance", "Living dermis", "Only the cuticle skin", "The matrix bone", "You service the plate, not live tissue."),
    ("nail-anatomy", "The matrix is:", "The growth area under the proximal fold", "The free edge only", "A type of acrylic", "The e-file bit", "Damage to the matrix changes the new nail."),
    ("nail-anatomy", "The hyponychium is:", "The seal under the free edge", "The lunula paint", "A gel brand", "The wrist", "That seal keeps pathogens out."),
    ("nail-anatomy", "Onycholysis is:", "Separation of plate from bed — do not pry it tighter with product", "A healthy pink bed", "A cuticle oil", "A French smile line", "Separated nails need caution, not more leverage."),
    ("nail-anatomy", "The eponychium is:", "Living skin at the base — do not cut live tissue", "Dead cuticle only", "The toe bone", "A primer", "Cutting live skin is a wound."),
    ("nail-anatomy", "A blue-black nail after trauma may be:", "A bruise under the plate — refer if severe or painful", "A candidate for tight acrylic immediately", "Always a fungus", "Normal gel stain only", "Trauma can hide injury."),
    ("nail-anatomy", "Beau's lines are:", "Horizontal ridges after illness or trauma", "A polish color", "An e-file speed", "A disinfectant", "They grow out with the plate."),
    ("nail-anatomy", "The nail bed is:", "The skin under the plate rich in blood vessels", "The file grit", "The lamp wattage", "The monomer", "You do not grind into the bed."),
    ("nail-anatomy", "Paronychia looks like:", "Red, swollen skin around the nail — refer, do not push product", "A perfect cuticle", "Dry callus only", "A French tip", "Infection is medical."),
    ("nail-anatomy", "A pterygium in nails refers to:", "Abnormal skin adhesion on the plate — do not rip it", "A toe separator", "A base coat", "A drill bit", "Never tear living tissue."),
    ("nail-anatomy", "The free edge is:", "The part that extends past the finger — safe to file", "The matrix", "Live cuticle", "The tendon", "Length lives on the free edge."),
    ("nail-anatomy", "Yellow staining from polish is:", "Usually cosmetic; fungus is a different picture and needs referral", "Always onychomycosis", "Cured by bleach soaks at home you prescribe", "A reason to cut the matrix", "Do not diagnose fungus from stain alone."),
    ("nail-anatomy", "Ingrown toenails that are inflamed should be:", "Left to a medical professional", "Dug out with a bit", "Covered with acrylic to 'train' the nail", "Ignored", "Inflamed ingrowns are not a salon repair."),
    ("nail-anatomy", "Keratin is:", "The protein of hair and nails", "A monomer", "A UV bulb", "A board fee", "You are filing keratin."),
    ("nail-anatomy", "A client's thin, peeling nails after gel removal often mean:", "Over-filing or forced soak-off damaged the plate", "They need a coarser bit", "The matrix died", "Skip base coat forever", "Most 'weak nails' are tech-caused."),
    ("services", "A basic manicure order is:", "Sanitize, shape, cuticle work as allowed, nourish, polish if requested", "Nip live skin first", "E-file into the bed", "Skip wash", "Wash and shape before paint."),
    ("services", "Soaking nails before clipping cuticles:", "Softens only dead tissue you are allowed to remove", "Lets you cut the eponychium freely", "Replaces disinfectant", "Cures gel", "Soak ≠ license to cut live skin."),
    ("services", "Gel polish must be:", "Applied thin and cured per the lamp and product", "Slathered thick so it never wrinkles", "Air-dried like lacquer always", "Mixed with monomer", "Cure times are not suggestions."),
    ("services", "Soak-off of gel should:", "Use the product's method — do not grind the plate raw", "Use a 100-grit on the bed", "Rip enhancements off dry", "Use a barber razor", "Removal is where techs wreck nails."),
    ("services", "A fill (rebalance) is for:", "Regrowth at the cuticle area of an enhancement", "A pedicure massage only", "Disinfection", "Haircolor", "Fills follow growth, not a full rip-off every time."),
    ("services", "Primer or bonder is used to:", "Help enhancement adhesion on a prepared plate", "Disinfect the bowl", "Replace washing", "Treat fungus", "Adhesion products are not medicine."),
    ("services", "An e-file on the natural plate should:", "Stay light, with the correct bit and RPM — no heat spike", "Be used like a belt sander", "Go under the hyponychium", "Replace all hand filing always", "Heat and pressure mean you are in the bed."),
    ("services", "A French manicure smile line is:", "A design on the free edge, not a medical term", "The lunula anatomy test", "A fungus sign", "A relaxer", "It is polish art."),
    ("services", "Massage during a pedicure should avoid:", "Broken skin, varicose-vein issues the client flags, and deep work you are not trained for", "Any lotion", "Asking about pressure", "The calf if the client wants it and it is allowed", "Aides stay in comfort massage, not PT."),
    ("services", "Trimming toenails is generally:", "Straight across to reduce ingrowns", "Rounded deep into corners", "Done with a hair shear", "Skipped if they paid for gel", "Shape prevents ingrowns."),
    ("services", "A client who wants 'as short as the bed' on toes should hear:", "Cutting into the groove risks injury and infection", "Yes, nip the bed", "Use a drill into the hyponychium", "Apply acrylic in the sulcus", "Leave a safe free edge."),
    ("services", "Lifting enhancement product is a place for:", "Water and microbes — remove and rebalance, do not just glue the gap", "More glitter", "Ignoring it", "A pedicure jet", "Lifts become greenies."),
    ("services", "Monomer liquid should be:", "Used in a well-ventilated area with the lid managed", "Heated on a stove", "Dumped in the sink", "Used as cuticle oil", "MMA/EMA vapors and disposal matter."),
    ("services", "A nail art brush is:", "Cleaned of product; it is not a sanitizer", "Used on multiple dirty nails then the next client with no clean", "A medical instrument", "A barber strop", "Art tools still get dirty."),
    ("services", "If a client is pregnant and asks about services, you should:", "Follow product labels and not give medical advice", "Guarantee all monomers are risk-free", "Refuse all lotion", "Prescribe a medication", "Stay in cosmetic scope."),
    ("chemistry", "MMA (methyl methacrylate) liquid is:", "Banned or heavily restricted for nails in many states", "The safest monomer", "A disinfectant", "Food-grade", "Know your state's MMA rule."),
    ("chemistry", "EMA acrylic systems require:", "Correct liquid-to-powder ratio so the bead is workable, not wet-runny", "Water as liquid", "Bleach as powder", "No ventilation", "Ratio is the chemistry."),
    ("chemistry", "A primer that is corrosive can:", "Burn skin if it runs off the plate", "Be used as a drink", "Disinfect nippers", "Replace soap", "Keep acid primer on the keratin."),
    ("chemistry", "Acetone soak-off should be:", "Timed and buffered so skin is not macerated raw", "All-day bags", "Boiling", "Mixed with relaxer", "Acetone is aggressive."),
    ("chemistry", "LED vs UV cure depends on:", "The gel's photoinitiators matching the lamp", "The shop paint color", "The board fee", "Clipper guards", "Wrong lamp = undercure."),
    ("chemistry", "Undercured gel can cause:", "Allergy and peeling — cure fully, do not leave a wet layer as 'style'", "Stronger nails", "Disinfection", "Faster fills only with no downside", "Contact dermatitis is a real gel risk."),
    ("chemistry", "Cuticle oil is:", "A conditioner for skin and plate, not a disinfectant", "An EPA sporicidal", "A monomer", "A lamp", "Oil does not kill microbes."),
    ("chemistry", "Mixing random glitter into a sealed gel system can:", "Change cure and cause lifting or allergy", "Improve disinfection", "Replace primer always", "Be required by the board", "Stay in the tested system."),
    ("chemistry", "A strong monomer smell means:", "Ventilate and cap the liquid — do not ignore vapors", "The product is weak", "Open more windows by heating it", "Drink water only", "Vapor control is part of the job."),
    ("chemistry", "Nail dehydrator is for:", "Removing oil from the plate before enhancement", "Treating athlete's foot", "Disinfecting feet", "Thinning blood", "Prep chemistry ≠ medicine."),
    ("chemistry", "If a client reports itching after acrylic, you should:", "Stop the service path that caused it and suggest medical evaluation", "Apply more product to seal it", "Use stronger primer", "Ignore it as normal", "Allergy gets worse with more monomer."),
    ("chemistry", "Store chemicals:", "Labeled, upright, away from heat and kids", "Under the sink unlabeled", "In soda bottles", "In the pedicure bowl", "Hazcom still applies."),
    ("chemistry", "SDS sheets in a nail salon cover:", "Monomers, primers, acetone, and disinfectants", "Only magazines", "Tax IDs", "Hair relaxers you do not use", "Know the products on your station."),
    ("chemistry", "A '3-free' or '5-free' polish claim means:", "Certain chemicals were left out — it is not a medical claim you should inflate", "The polish disinfects", "No ventilation needed", "FDA drug approval", "Marketing ≠ pharmacology."),
    ("chemistry", "Never use household bleach as:", "A routine nail soak or 'fungus treatment' you prescribe", "A possible hard-surface cleaner if the label and board allow, separately", "A monomer", "A base coat", "Do not practice medicine with bleach."),
]

def more(topic_items):
    return topic_items

PTA = [
    ("modalities", "A PT aide may typically:", "Prepare the treatment area and assist as the PT/PTA directs", "Change the plan of care independently", "Progress exercises past the written plan", "Diagnose a meniscus tear", "Aides work under direction, not as the clinician."),
    ("modalities", "Setting up a hot pack usually includes:", "Checking skin, layers, and timer as trained — not inventing a new temperature", "Placing the pack on bare skin for an hour", "Using the microwave on the patient's phone", "Leaving the patient unattended against policy", "Moist heat has layer and time rules."),
    ("modalities", "A cold pack on acute swelling is:", "Applied with a barrier and time limit as the clinician ordered", "Strapped all night by the aide's choice", "Used on insensate skin freely", "A replacement for the evaluation", "Cryotherapy still has contraindications."),
    ("modalities", "Ultrasound parameters are:", "Set and changed by the licensed clinician, not the aide", "Guessed by the aide to 'go deeper'", "Always 3 MHz on bone", "A home-massage setting", "US is a skilled modality."),
    ("modalities", "Electrical stimulation pads are placed:", "Exactly where the PT/PTA specified after skin check", "On broken skin to 'wake it up'", "Over a pacemaker if it saves time", "By the patient in the lobby", "E-stim placement is ordered."),
    ("modalities", "A traction table setup by an aide is:", "Hardware and comfort prep — the clinician sets dose", "A chance to increase pounds for a better story", "Done while the patient sleeps unmonitored if policy forbids it", "Used for every neck pain automatically", "Dose is skilled."),
    ("modalities", "Paraffin is contraindicated when:", "The skin is open or sensation is unreliable — flag the clinician", "The patient is bored", "It is winter", "The wax is warm", "Open skin + wax is an infection burn risk."),
    ("modalities", "Cleaning a modality between patients includes:", "Manufacturer-approved disinfection of surfaces and straps", "A dry towel wave", "Spraying the patient's face", "Skipping if they were 'just stretching'", "Shared equipment is a fomite."),
    ("modalities", "If a patient says a hot pack is burning:", "Remove it and get the clinician — do not tell them to wait it out", "Add another layer of heat", "Turn it up", "Ignore it", "Burn complaints stop the modality."),
    ("modalities", "An ice massage is stopped if:", "The patient reports no sensation or skin looks wrong — alert the clinician", "They laugh", "Five seconds have passed always", "The aide is tired", "Loss of sensation is a warning."),
    ("modalities", "Aides do not:", "Interpret outcome measures to change the diagnosis", "Bring linen", "Guard as taught", "Set a chair", "Interpretation is skilled."),
    ("modalities", "Hydrocollator packs need:", "Enough terry layers; never a dripping pack on bare skin", "Zero layers for 'better heat'", "Plastic wrap as the only layer always", "Overnight unsupervised on a contracture", "Burns are the #1 aide heat error."),
    ("modalities", "A TENS unit the patient owns:", "Is not reprogrammed by the aide beyond what policy allows", "Should have leads placed in the mouth", "Replaces PT", "Is thrown out", "Personal devices stay in policy."),
    ("modalities", "Documenting a modality the aide helped with should:", "State what you set up and what the clinician did, honestly", "Claim you progressed the plan", "Omit a burn", "Copy yesterday's note blindly if it is wrong", "Truthful assist notes."),
    ("modalities", "This PT aide mock is:", "Independent practice — not a PT or PTA license exam", "The NPTE", "An MBLEx massage exam", "A CNA skills video", "Different credential."),
    ("safety", "A gait belt is used to:", "Assist a transfer or gait as trained, not to lift by the arms", "Tie a patient to a chair all day", "Replace the PT evaluation", "Diagnose weakness", "Belts are assistive, not restraints by default."),
    ("safety", "Before a sit-to-stand you should:", "Lock the wheelchair or bed, explain, and use the helper devices ordered", "Pull on the patient's neck", "Leave the chair unlocked 'for speed'", "Skip non-skid shoes", "Locks and cues prevent falls."),
    ("safety", "A patient who feels faint during standing should:", "Sit or be lowered safely and the clinician notified", "Be walked faster", "Drink a protein shake you prescribed", "Be left alone in the parallel bars", "Syncope is an emergency path."),
    ("safety", "Standard precautions mean:", "Gloves and hygiene when contact with body fluids is possible", "Never washing hands", "One pair of gloves all day on every patient", "Bare hands in a draining wound", "Assume fluids are risky."),
    ("safety", "A wet floor in the gym is:", "A fall hazard — dry it and mark it", "A balance exercise", "Ignored", "The patient's problem", "Environment is part of safety."),
    ("safety", "Guarding on stairs as trained includes:", "Staying where you can control a fall, not scrolling your phone", "Walking ten steps ahead", "Holding only the chart", "Pushing from above unsafely", "Positioning is the skill you were shown."),
    ("safety", "A patient with a new total hip and a posterior precaution:", "Must follow the clinician's listed motion limits — the aide does not invent ROM", "Should sit in a deep couch because it is soft", "Can cross legs if they want", "Does not need a raised seat if ordered", "Precautions are written."),
    ("safety", "Oxygen tubing under a walker can:", "Trip the patient — manage lines", "Be yanked to 'test flow'", "Be ignored", "Replace the gait belt", "Lines are part of the transfer."),
    ("safety", "If you are not trained on a lift (Hoyer):", "Do not operate it — get trained staff", "Guess the sling size", "Use a bedsheet as a sling", "Have the family run it unsupervised against policy", "Lifts kill when misused."),
    ("safety", "A patient who is NWB on a leg:", "Does not put that foot down — the aide does not 'try a little weight'", "Can toe-touch if they insist", "Should hop unsupervised", "Can discard the walker", "Weight-bearing is an order."),
    ("safety", "Hand hygiene after removing gloves is:", "Required", "Optional", "Rude", "Replaced by lotion only", "Gloves are not magic."),
    ("safety", "A seizure in the gym:", "Protect from injury, time it, get help — do not put objects in the mouth", "Hold them down hard", "Walk it off", "Give water during the clonic phase", "First aid, then clinician/911 per policy."),
    ("safety", "Sharps from a diabetic patient:", "Go in a sharps container, not the trash", "Are recapped by mouth", "Go in your pocket", "Are a souvenir", "Sharps rules still apply."),
    ("safety", "Privacy during a transfer means:", "Close the curtain or door as appropriate", "Announce their diagnosis in the hallway", "Post the note on Instagram", "Skip the gown", "Dignity is safety too."),
    ("safety", "If a patient falls:", "Stay and get help per policy; do not haul them up alone if you were told not to", "Leave to finish lunch", "Blame them in the lobby", "Change the note to 'no fall'", "Falls are reported."),
    ("anatomy", "The quadriceps primarily:", "Extend the knee", "Flex the elbow", "Plantarflex the ankle only", "Rotate the neck", "Aides need basic muscle actions."),
    ("anatomy", "The rotator cuff muscles stabilize:", "The shoulder", "The kneecap only", "The jaw", "The lumbar disc as a single muscle", "Cuff = glenohumeral stability."),
    ("anatomy", "Dorsiflexion is:", "Toes toward the shin", "Pointing the toes down", "Knee bending", "Hip circling", "Ankle vocabulary shows up in cues."),
    ("anatomy", "The femur is:", "The thigh bone", "A wrist bone", "A toe bone", "The kneecap", "Do not mix long bones."),
    ("anatomy", "A contracture is:", "A stiff, shortened soft-tissue limitation", "A normal warm-up", "A modality brand", "A billing code for massage", "Positioning fights contractures."),
    ("anatomy", "NWB means:", "No weight through that limb", "Full sport play", "Only stairs", "Weight as tolerated without an order change", "Abbreviations must be exact."),
    ("anatomy", "The ACL is at the:", "Knee", "Ear", "Thumb IP joint only", "Heel pad", "Common orthopedic vocab."),
    ("anatomy", "Supine is:", "Lying on the back", "Lying face down", "Sitting", "Standing on toes", "Position words drive transfers."),
    ("anatomy", "The lumbar spine is:", "The low back", "The neck", "The skull", "The wrist", "Log-roll cues use this."),
    ("anatomy", "Edema is:", "Swelling", "A fever only", "A bone bruise name", "A brace brand", "You observe and report swelling, not diagnose DVT."),
    ("anatomy", "A pressure injury risk area includes:", "Sacrum, heels, and other bony prominences", "Only the hair", "The palms always equally", "The tongue", "Repositioning is an aide task."),
    ("anatomy", "Pronation of the forearm is:", "Palm down", "Palm up", "Shoulder shrug", "Ankle hop", "Cueing uses this."),
    ("anatomy", "The patella is:", "The kneecap", "A neck vertebra", "The heel", "A rib", "Basic bony landmarks."),
    ("anatomy", "Atrophy means:", "Loss of muscle bulk", "A new muscle", "A modality", "A legal form", "You may observe; the PT explains why."),
    ("anatomy", "Bilateral means:", "Both sides", "One side", "The head only", "The left hand only", "Notes use this word."),
    ("ethics", "A PT aide's scope does not include:", "Interpreting the evaluation or changing the plan of care", "Preparing the table", "Walking a patient as directed", "Cleaning", "Scope is the whole job."),
    ("ethics", "If a patient asks 'am I getting better?' the aide should:", "Defer progress opinions to the PT/PTA", "Guarantee a full recovery", "Change the exercises", "Quote a WebMD diagnosis", "Prognosis is skilled."),
    ("ethics", "Dating a current patient is:", "A boundary violation — follow clinic policy and stop the dual relationship", "A benefit", "Required", "Fine if they tip", "Power imbalance."),
    ("ethics", "Photographing a patient's scar for your socials is:", "A HIPAA/privacy problem without a proper authorization", "Good marketing", "Always allowed", "Fine if you blur the face only and still show the chart sticker", "PHI is more than a face."),
    ("ethics", "A family member asks for the diagnosis in the lobby:", "Do not discuss PHI there — point them to the clinician and a private space", "Announce it", "Hand them the full chart", "Text it", "Minimum necessary + privacy."),
    ("ethics", "Accepting a large cash gift from a patient:", "Follow clinic ethics — usually decline or report", "Always keep it quietly", "Raise your rate on the spot", "Share only with the front desk", "Gifts are a policy issue."),
    ("ethics", "Documenting an exercise the patient did not do is:", "Falsification", "Helpful", "Required for billing if they paid", "A wash", "Never invent reps."),
    ("ethics", "If you are asked to 'just do ultrasound' with no PT in the building against the law:", "Refuse — that is unlicensed practice", "Do it for cash", "Turn the intensity to zero and pretend", "Have the tech next door order it", "No licensee, no skilled modality."),
    ("ethics", "A patient's religion that limits Saturday visits means:", "Accommodate scheduling; do not mock", "Force Saturday", "Charge extra for beliefs", "Write a psych diagnosis", "Respect is not optional."),
    ("ethics", "Restraint use by an aide:", "Only as policy and a lawful order allow — not for convenience", "Whenever they stand", "As punishment", "Instead of a call bell", "Restraints are regulated."),
    ("ethics", "If you injure a patient:", "Report immediately; do not hide it", "Wait to see if they sue", "Alter the note", "Blame the PT on Instagram", "Incident reports protect the next patient too."),
    ("ethics", "Working while impaired is:", "A safety and ethics failure", "Fine if you know the gym", "Required overtime", "A patient problem", "Impairment ends the shift."),
    ("ethics", "An aide may translate medical consent if:", "Policy and language skill allow — do not guess legal terms", "They took Spanish 1", "The patient is rushing", "Always, even if untrained", "Bad translation is a consent defect."),
    ("ethics", "Gossip about a 'difficult' patient in the elevator is:", "A privacy breach", "Team building", "Allowed if no name... with a unique rare disease", "Required", "Elevators have ears."),
    ("ethics", "The licensed PT is responsible for:", "The plan of care; the aide does not replace that license", "Nothing once an aide is hired", "Only payroll", "Massage CE", "Know who holds the license."),
]

MED = [
    ("rights", "The six rights of medication include:", "Right person, drug, dose, route, time, and documentation", "Right color of the pill only", "Right room number if the name is close", "Right family member signing", "All six, every pass."),
    ("rights", "If the MAR and the label disagree, the aide should:", "Stop and get a licensed nurse to clarify — do not guess", "Give the prettier label", "Give both", "Skip documentation", "Discrepancy = hold."),
    ("rights", "A resident who says 'that's not my pill' should:", "Have the dose held and the nurse notified", "Be talked into swallowing", "Have it hidden in dessert against policy", "Be marked as refused later if they take it", "The resident is a safety check."),
    ("rights", "Crushing a medication is allowed only when:", "The order and the drug form allow crush — never crush XL/enteric without authority", "You are in a hurry", "The resident prefers applesauce always", "The tablet is large", "Some forms must stay intact."),
    ("rights", "A PRN pain med requires:", "The reason and the response documented per the order", "A second secret dose", "Sharing with a roommate", "No note if it worked", "PRN is not a candy bowl."),
    ("rights", "Identifying the resident uses:", "The facility's two identifiers, not 'the lady in 12'", "Room number only", "A visitor's word only", "Hair color", "Two IDs."),
    ("rights", "A medication aide does not:", "Take a new phone order for a controlled drug if the state forbids it", "Pass meds already on the MAR as trained", "Document a refusal", "Wash hands", "New orders are a nurse/provider act in most states."),
    ("rights", "Giving a drug late because you were chatting is:", "A timing error — report per policy", "Fine within the shift", "The resident's fault", "Uncharted on purpose", "Time is a right."),
    ("rights", "A look-alike / sound-alike pair should be:", "Separated and double-checked, not grabbed by memory", "Stored mixed to save space", "Given together always", "Labeled with marker on the tablet", "LASA errors are classic."),
    ("rights", "Self-administration by a resident happens only:", "If the care plan and law allow, with the checks required", "Whenever they ask", "If they hide pills", "Instead of the MAR", "Self-admin is a planned privilege."),
    ("rights", "An expired drug on the cart is:", "Removed from use", "Given if it looks fine", "Split with another cart", "Crushed to hide the date", "Expiration is a hard stop."),
    ("rights", "The right route for an ear drop is:", "The ear, as ordered — not the eye because the bottles look alike", "Either eye", "IV", "A nebulizer by default", "Route errors blind people."),
    ("rights", "If you are not sure you already gave a dose:", "Do not double-dose — check the MAR and the nurse", "Give again to be safe", "Skip the next three", "Ask the roommate", "Uncertainty is a hold."),
    ("rights", "Holding a med for a low blood pressure when ordered that way means:", "You follow the parameter and notify as written", "You give it anyway", "You change the parameter", "You hide the vital", "Parameters are part of the order."),
    ("rights", "This med-aide mock is:", "Independent practice — not a CNA skills or nursing-board exam form", "The NCLEX", "A gait-belt CNA clone", "A PHR test", "Different job than CNA mobility."),
    ("routes", "Sublingual means:", "Under the tongue until dissolved — not swallowed whole", "In the ear", "In the eye", "On the skin as a cream", "SL is not PO."),
    ("routes", "An enteric-coated tablet should not be:", "Crushed or chewed", "Given with water if allowed whole", "Held if NPO as ordered", "Documented", "EC is a coating for a reason."),
    ("routes", "A transdermal patch is applied to:", "Clean, dry, intact skin, dated, old patch removed", "Hairy wet skin over the old patch", "The same site forever without looking", "The chart only", "Old + new patches stack dose."),
    ("routes", "Eye drops: the aide should:", "Avoid touching the dropper to the eye and wait between different drops as trained", "Aim at the cornea from a foot away", "Share a bottle between roommates", "Use the ear bottle", "Technique prevents infection."),
    ("routes", "Inhalers need:", "A shake/prime if the product requires it and a slow breath as taught", "A swallow of the canister", "No rinse after steroid if the protocol says rinse", "Sharing spacers dirty", "Device technique is the dose."),
    ("routes", "A rectal suppository is:", "Unwrapped and inserted as trained, with privacy", "Crushed in juice", "Given SL", "Left in the foil", "Route is rectal."),
    ("routes", "Buccal means:", "Between cheek and gum", "In the IV", "In the nose only", "Crushed in coffee", "Do not swallow immediately."),
    ("routes", "A liquid oral med is measured with:", "An oral syringe or marked cup, not a kitchen spoon", "A coffee mug guess", "The bottle cap", "A syringe meant for injection used in the vein by the aide", "Oral syringes stay oral."),
    ("routes", "Topical cream is:", "A thin layer on intact skin as ordered, not a sandwich spread", "Eaten", "Put in the eye unless it is ophthalmic", "Shared finger-to-jar-to-next-resident", "No double-dipping jars."),
    ("routes", "A gastrostomy-tube med, if the aide is allowed, requires:", "Flush and form as the nurse's procedure states — not all pills crush", "A dry pill stuffed in the tube", "Cola as the only flush always", "No placement check when policy requires one", "Tubes clog and misplace."),
    ("routes", "Nasal spray is aimed:", "As the product says, usually not straight up the septum with a hard blast", "Into the eye", "Down the throat as a drink", "Shared with a cold going around the unit", "Technique + no sharing."),
    ("routes", "An IM injection is:", "Usually outside medication-aide scope — do not improvise", "A good place to start practicing", "The same as eye drops", "Fine if the resident asks", "Know your state's allowed routes."),
    ("routes", "Time-release capsules should not be:", "Opened and sprinkled unless the label says they may", "Given whole if that is the order", "Held when NPO", "Documented", "Opening XR dumps the dose."),
    ("routes", "Otic (ear) drops in an adult are often given with:", "The pinna pulled as trained for that age", "The dropper jammed deep", "The same bottle in both residents' ears without wipe rules", "A tablet in the canal", "Age changes the pinna cue."),
    ("routes", "NPO except meds means:", "Follow the exact order — not a full breakfast", "A buffet", "Skip all meds automatically", "Ice cream only", "NPO has versions."),
    ("safety", "A resident drowsy after a new opioid should be:", "Monitored and the nurse told — do not give another sedative on your own", "Given extra at bedtime for 'sleep'", "Left without a call bell", "Walked in the parking lot alone", "Sedation stacks."),
    ("safety", "Warfarin plus a new antibiotic on the MAR is a reason to:", "Alert the nurse — interactions are not the aide's to shrug off", "Double the warfarin", "Stop the antibiotic secretly", "Give extra spinach as an order", "Flags go to the nurse."),
    ("safety", "Insulin, if you are not signed off to give it:", "Is not yours to draw", "Can be guessed in units", "Is a vitamin", "Goes in the ear", "High-alert drug."),
    ("safety", "A rash after a new antibiotic is:", "Held and reported as a possible allergy", "Covered with lotion and given again", "Ignored", "A reason to give a bigger dose", "Allergy can escalate."),
    ("safety", "Controlled-count discrepancy means:", "Stop and report — do not 'fix' the book later", "Borrow from another cart", "Ignore one missing oxycodone", "Ask the resident to forget it", "Counts are legal."),
    ("safety", "Fall risk after a night blood-pressure drug means:", "Safety measures and reporting dizziness, not a secret extra pill", "A dark room with no call light", "Socks without traction", "Leaving the bed high", "Meds change fall risk."),
    ("safety", "Crushing a chemo tablet on the open cart is:", "A hazardous-drug problem — follow the special procedure or don't", "Fine if you hold your breath", "Required", "A CNA gait-belt skill", "HD drugs have USP rules."),
    ("safety", "A resident in pain who wants a roommate's leftover oxycodone:", "Is a no — only their ordered drug", "A kindness", "Fine if you document later", "OK once", "Never share controlleds."),
    ("safety", "Hand hygiene before a med pass is:", "Required", "Optional if you know them", "Replaced by gloves all day without washing", "Rude", "You touch the pills."),
    ("safety", "A crushed med in applesauce must be:", "Given to that one resident, not a shared cup", "Pre-mixed for the hallway", "Left on the table", "Fed to two people", "One cup, one person."),
    ("safety", "If you drop a tablet on the floor:", "Discard per policy and get a replacement — do not blow it off and give it", "Give it", "Put it back in the blister", "Split it with the next dose", "Floor pills are dirty."),
    ("safety", "Beers-list drugs in older adults are:", "A reason the nurse/pharmacist watches — you still give only as ordered", "Yours to discontinue", "Vitamins", "Always IM", "You report side effects; you do not deprescribe."),
    ("safety", "A resident choking on a pill needs:", "Emergency response — do not leave them", "Another tablet immediately", "A laugh", "Water forced into a closed airway", "Airway first."),
    ("safety", "Storage of the med cart includes:", "Locked when out of your sight", "Open in the dining room", "Keys on a hook in the hall", "Residents helping themselves", "Diversion starts with an open cart."),
    ("safety", "An adverse effect vs a mild expected side effect:", "When in doubt, report — do not wait for 'bad enough'", "Never report nausea", "Chart only if they code", "Ask Facebook", "Reporting is cheap; silence is not."),
    ("docs", "Documentation happens:", "After the drug is taken, not before you walk in the room", "The night before", "By a coworker who was not there", "Never for PRNs", "Chart what occurred."),
    ("docs", "A refusal is charted as:", "Refused, with the nurse notified as required — not a secret skip", "Given", "Crushed in secret", "Omitted from the MAR", "Refusals are data."),
    ("docs", "Late entry on the MAR must be:", "Honest and timed as a late entry, not backdated as on-time", "Written as 0800 if it was 1100", "Erased with white-out only", "Ignored", "Falsifying time is a legal issue."),
    ("docs", "The aide does not document:", "A new medical diagnosis they invented", "A refusal they witnessed", "A pulse they took if allowed", "A hold they did", "Stay in what you did."),
    ("docs", "A wasted narcotic needs:", "A witness and the form your facility uses", "A toilet flush with no count", "Your pocket", "A story", "Waste is two-person."),
    ("docs", "If the eMAR is down, you:", "Use the downtime paper process — you do not skip the pass", "Wait until Monday", "Give from memory only", "Send everyone home", "Downtime procedures exist."),
    ("docs", "Allergy listed as 'codeine → rash' means:", "You still check every pass and report a new reaction", "You can give morphine without telling anyone if you feel like it", "Allergies expire", "Ignore it for cough syrups that contain it", "Allergies stay visible."),
    ("docs", "A med error you made should be:", "Reported at once so the resident can be checked", "Hidden", "Blamed on the night shift always", "Fixed by giving a second wrong dose", "Residents come first."),
    ("docs", "Scope: teaching a new diagnosis in depth is:", "The nurse or provider's job", "Yours if you watched a video", "A CNA transfer skill", "Optional charting of a gait belt", "Teach-back of a disease is not a med-aide add-on."),
    ("docs", "Leaving the MAR open on a table in the lobby is:", "A privacy and diversion risk", "Fine", "Required", "How families learn", "PHI on a cart in public is a breach."),
    ("docs", "A family asks 'what pills is dad on?'", "Follow facility privacy rules — do not recite the MAR in the hall", "Read the whole list loudly", "Hand them the narcotic keys", "Text a photo of the cart", "Privacy + the nurse."),
    ("docs", "Counts at shift change protect:", "Residents and your license", "Only the pharmacy's feelings", "No one", "The kitchen", "Start the shift with a clean count."),
    ("docs", "If you are not competent on a device (insulin pen):", "Do not use it — get training or the nurse", "Guess", "Let the resident teach you mid-dose", "Skip insulin and not tell anyone", "Competence is a right too."),
    ("docs", "Copying another aide's initials is:", "Fraud", "Teamwork", "Required", "A late entry", "Your name is your license."),
    ("docs", "The purpose of the MAR is:", "The legal record of what was given", "A shopping list", "Optional scrap paper", "A CNA bath sheet", "If it is not charted, it is not proved."),
]

def first_aid():
    return [
        ("cpr", "Adult compression depth is at least:", "2 inches (5 cm) on the center of the chest", "Half an inch", "4 inches on the throat", "Fingertips on the abdomen", "Depth plus recoil."),
        ("cpr", "The adult compression rate is:", "100–120 per minute", "40 per minute", "200 per minute", "One every 10 seconds", "Rate is a range."),
        ("cpr", "Allow full chest recoil so:", "The heart can refill", "You can rest your phone", "The AED charges slower", "Breaths are skipped forever", "Lean back, do not spring-rest on the chest."),
        ("cpr", "When an AED arrives:", "Turn it on and follow the prompts; bare the chest", "Put the pads over a wet metal necklace without looking", "Wait for a doctor only", "Shock while touching the patient", "AED first, clear, shock if advised."),
        ("cpr", "If the AED says no shock:", "Resume CPR immediately", "Stop care", "Shake the box", "Give aspirin into an unresponsive airway", "No shock ≠ no CPR."),
        ("cpr", "A drowning unresponsive adult still needs:", "CPR starting with compressions (and breaths as trained) after a safe remove", "Only walking it off", "Abdominal thrusts only forever", "No AED ever", "Hypoxia does not cancel AED."),
        ("cpr", "Infant compressions use:", "Two fingers or two thumbs encircling, as trained — not adult full palms on the gut", "A fist on the face", "The heel on the neck", "No depth", "Infants are not small adults."),
        ("cpr", "A bag-mask or mouth shield is used to:", "Give breaths with less exposure", "Replace compressions", "Shock the patient", "Measure blood pressure", "Barrier + breath."),
        ("cpr", "Switch compressors about every:", "2 minutes or when the AED analyzes, to fight fatigue", "20 minutes", "Never", "Every compression", "Fatigue wrecks depth."),
        ("cpr", "Do not use an AED in a puddle without:", "Moving to a reasonably dry area and drying the chest", "Throwing the AED in the water", "Holding the patient in the pool", "Skipping pads", "Water + shock is a scene problem."),
        ("cpr", "Agonal gasps mean:", "Start CPR — that is not normal breathing", "They are fine", "Give food", "Walk them to the car", "Gasps are a code."),
        ("cpr", "Phone first vs CPR first in an adult sudden collapse you did not see:", "Follow your training path — get AED/911 into the plan fast", "Never call", "Only film it", "Wait for family consensus", "Early AED saves."),
        ("cpr", "Pacemaker or patch on the chest:", "Place pads at least an inch away; do not put a pad on a medicine patch", "Pad directly on the bulge", "Skip AED", "Rip the pacemaker out", "Work around devices."),
        ("cpr", "Pregnant patient in arrest:", "CPR with a left uterine displacement as trained — do not skip compressions", "Only sit them up", "No AED", "Wait for obstetrics only", "Mom's circulation is the fetal hope."),
        ("cpr", "You stop CPR when:", "A trained team takes over, an obvious fatal injury, or you are too exhausted and no one can continue", "You get bored", "A bystander says they saw a twitch 20 minutes ago and you leave", "The phone battery dies", "Have a reason."),
        ("bleeding", "Life-threatening limb bleeding is treated with:", "Direct pressure, then a tourniquet if trained and needed", "A loose decorative scarf", "Ice only", "Aspirin", "Pressure → pack → TQ."),
        ("bleeding", "A tourniquet goes:", "High on the limb, not over a joint, and is not loosened as a game", "On the neck", "On the forehead", "Loose enough to slide off", "Tight and timed."),
        ("bleeding", "A nosebleed in a person on warfarin who will not stop:", "Pinch, lean forward, and get medical help if it keeps pouring", "Tilt the head back so they swallow it", "Pack with newspaper", "Give another blood thinner", "Forward + pinch."),
        ("bleeding", "Shock from bleeding looks like:", "Pale, sweaty, anxious, weak pulse — keep warm and get ALS", "Flushed and joking only", "A reason to give them a beer", "Ignore thirst and walk them far", "Hypovolemia is an emergency."),
        ("bleeding", "An impaled object is:", "Stabilized, not pulled in the field unless it blocks the airway", "Yanked for photos", "Pushed deeper", "Used as a handle", "Stabilize in place."),
        ("bleeding", "A severed finger is:", "Wrapped, bagged dry then on ice — not in water, go with the patient", "Thrown out", "Put in tap water loose", "Left at the shop", "Replant starts with the part."),
        ("bleeding", "Internal bleeding after a car crash may show:", "Pain, rigidity, or shock with little external blood", "A paper cut only", "No need for 911 if they can talk", "A reason to feed them", "Mechanism matters."),
        ("bleeding", "Gloves for bleeding are:", "Standard", "Optional if you know them", "Replaced by a plastic bag on your head", "Rude", "Their blood is not yours to wear."),
        ("bleeding", "A scalp bleed that looks huge:", "Still gets pressure — scalps bleed a lot; watch the neck/c-spine if the mechanism is trauma", "Is ignored", "Needs a tourniquet on the neck", "Means no 911", "Scalp ≠ always minor."),
        ("bleeding", "A puncture to the chest that bubbles:", "Seal as trained (occlusive) and get ALS — this is not a band-aid job", "Give water", "Walk it off", "Pack with cotton from a pillow", "Sucking chest wounds are ALS."),
        ("bleeding", "After a tourniquet you write:", "The time it went on", "A poem", "Nothing", "A fake earlier time", "Time of TQ."),
        ("bleeding", "A child with a nosebleed who is crying:", "Pinch and calm — do not have them lie flat swallowing blood", "Tilt back", "Stuff tissues in the throat", "Give aspirin", "Kids still lean forward."),
        ("bleeding", "You find a pool of blood and no patient:", "Scene safety first, then search/call — do not slip in it", "Run in blindly", "Mop first and leave", "Taste it", "Scene safety."),
        ("bleeding", "A bleeding disorder patient needs:", "Faster escalation — pressure still first", "No pressure", "Aspirin for pain freely", "A delay to look up rare diseases for an hour", "Pressure does not wait."),
        ("bleeding", "Embedded gravel in a road-rash bleed:", "Do not carve it out in the parking lot; control bleed and get care", "Scrub with a wire brush", "Ignore tetanus risk forever", "Glue it with super glue as your plan of record", "Gross debridement is clinical."),
        ("medical", "An EpiPen is used for:", "Anaphylaxis — inject as trained and call 911", "Mild itch you are unsure about, as a first party trick", "Chest pain from stairs", "A sprain", "Airway swell + epi."),
        ("medical", "A person with known diabetes who is shaky and sweaty but awake:", "Give fast sugar if they can swallow safely", "Give insulin from their bag if you are untrained", "Give diet soda only and leave", "Start CPR", "Hypoglycemia looks drunk."),
        ("medical", "Unresponsive and breathing after a possible opioid OD:", "911, airway, naloxone if you are equipped and trained", "A slap only", "Leave them on their back vomiting", "Give more opioid", "Naloxone + recovery position if they breathe."),
        ("medical", "Stroke signs (FAST) mean:", "Note the time and get emergency care — do not give them a full meal to 'test'", "Have them sleep it off", "Give aspirin if you are unsure it is a bleed", "Drive 3 hours to their usual clinic", "Time is brain."),
        ("medical", "Chest pain that may be cardiac:", "Have them rest, 911, aspirin if your protocol and they can swallow", "A walk to test it", "A big meal", "Ignore in women because they are 'anxious'", "Women's MI is under-called."),
        ("medical", "A seizure that lasts more than 5 minutes:", "Is status — 911, protect the head, nothing in the mouth", "Hold them rigid", "Pour water on the face as the only step", "Leave", "Time the seizure."),
        ("medical", "Asthma with one-word sentences:", "Help with their own inhaler as trained and get ALS if they are tiring", "A paper bag", "Lie them flat with no inhaler", "Give food", "Work of breathing is the clue."),
        ("medical", "Fainting in a hot church:", "Lower them, legs up if no trauma, check breathing", "Sit them on a high stool", "Give ammonia under an unresponsive face as the only plan", "Crowd in with no air", "Syncope first aid is position + airway."),
        ("medical", "A bee sting with hives and wheeze is:", "Anaphylaxis until proven otherwise", "A sprain", "Only ice forever", "A reason to wait 2 hours", "Skin + airway."),
        ("medical", "Someone drunk and vomiting:", "Recovery position if they have a pulse and you cannot protect the airway sitting", "Leave them on their back", "Give more alcohol", "Ignore head injury from the fall", "Aspiration kills."),
        ("medical", "Low blood sugar unresponsive:", "Do not pour juice in the mouth — 911 and glucagon if trained", "Force a sandwich", "Insulin", "Walk them", "Unresponsive + oral sugar = aspiration."),
        ("medical", "A panic attack vs asthma can look alike; you:", "Treat the ABCs you see and get help if breathing is failing", "Yell at them to stop", "Paper-bag a person who is already blue", "Diagnose in the field as official", "You are not the ED."),
        ("medical", "Heat stroke (hot, altered) needs:", "Aggressive cooling and 911 — not just a sip of water on a bench", "More football practice", "A sweatshirt", "Salt tablets only and return to play", "CNS change = emergency."),
        ("medical", "Poison swallowed by a child:", "Poison control / 911 — do not invent an emetic", "Ipecac always", "Milk until they burst", "Wait overnight", "PCC has the script."),
        ("medical", "This first-aid mock is:", "Cognitive practice — not an AHA course card", "The BLS Provider exam form", "A med-aide MAR test", "NATE Core", "Different product."),
        ("injury", "A suspected broken forearm is:", "Splinted in the position found if you are trained, pulse checked", "Yanked straight for photos", "Used as a crutch", "Ignored if they can wiggle a finger", "PMS before and after."),
        ("injury", "A possible spinal injury after a dive:", "Manual stabilization, 911 — do not sit them up to 'see'", "A log-roll party without a plan", "A walk to the car", "A neck crack by a bystander", "C-spine is scene discipline."),
        ("injury", "A burn that is large or on the face/hands/genitals:", "Cool with water, cover, 911 — no toothpaste", "Butter", "Ice packed until frozen", "Pop all blisters for fun", "Cool water, then care."),
        ("injury", "A chemical burn to the eye is:", "Long rinse and emergency care", "A single wipe", "A neutralizing acid you mix", "A patch and wait a week", "Minutes of irrigation."),
        ("injury", "Frostbite is:", "Rewarmed gently; do not rub snow on it", "Beaten with a stick", "Thawed over an open flame", "Ignored", "Gentle warmth."),
        ("injury", "A sprain vs strain in first aid is treated with:", "Rest, ice, compression, elevation as appropriate — still get care if they cannot bear weight", "A full marathon", "Heat immediately on a fresh tear if your training says ice first", "Walking it off on a numb foot", "RICE/POLICE variants."),
        ("injury", "A tooth knocked out:", "Pick it up by the crown, keep it moist as trained, see a dentist fast", "Scrub the root clean", "Let it dry on the dash", "Put it in a tissue in a hot car", "Time and the periodontal ligament."),
        ("injury", "An open fracture with bone showing:", "Cover, control bleed, do not push bone back", "Reduce it in the parking lot", "A tourniquet on the neck", "Walk them", "Open = emergency."),
        ("injury", "A tick found attached:", "Pull straight with tweezers as public-health guidance says; save the tick if told", "Burn it with a match on the skin", "Twist until the head stays", "Ignore fever later", "Straight pull."),
        ("injury", "Hypothermia mild (shivering, awake):", "Dry, insulate, warm drinks if they can swallow", "A cold hose", "Alcohol 'to warm up'", "More wind", "Stop the heat loss."),
        ("injury", "A puncture from a rusty nail:", "Wash, cover, and urgent care for tetanus status — do not ignore", "Suck the wound", "A tight arterial TQ for a pinprick", "Dirt packed in 'to clot'", "Tetanus is a shot question."),
        ("injury", "An amputation still attached by skin:", "Treat as a partial amp — do not complete it", "Cut it off to bag it", "A photo first for 10 minutes", "A handshake with the stump", "Leave the bridge."),
        ("injury", "A fishhook in a finger with the barb buried:", "Leave it and get care unless you are trained on the advance-and-cut method", "Yank against the barb", "A magnet", "Ignore it", "Barbs catch."),
        ("injury", "Lightning scene safety means:", "The storm can still hit — move to safer ground after the immediate reverse-triage of the pulseless", "Stand under the tallest tree to help", "Lie in a puddle", "Ignore multiple victims", "Reverse triage is a lightning oddity."),
        ("injury", "You are not a clinician when you:", "Invent a diagnosis or withhold 911 to 'not embarrass them'", "Call 911", "Use gloves", "Ask consent from an awake person", "First aid is a bridge."),
    ]

PN = [
    ("coaching", "A PN partner's first job is usually to:", "Help the client build awareness and small actions, not write a 12-week contest diet on day one", "Prescribe insulin", "Diagnose celiac on a quiz", "Replace their physician", "Coaching before a meal plan dump."),
    ("coaching", "If a client says they 'failed' the weekend, you:", "Get curious about what happened — skip the shame lecture", "Yell", "Add 1000 kcal of cardio punishment", "Discharge them for one pizza", "Data, not drama."),
    ("coaching", "Outcome-based decision making means:", "Change the next action based on what the client actually did and how they feel/perform", "Never change the plan", "Copy a celebrity meal", "Add random supplements weekly", "Measure, then adjust."),
    ("coaching", "A good first habit is often:", "One clear, small, repeatable behavior (protein at breakfast, a walk after lunch)", "A 7-day juice fast", "Cutting 1500 kcal overnight", "Weighing every 10 minutes", "Small enough to repeat."),
    ("coaching", "When two habits compete, you:", "Pick the one they can do on a bad day", "Stack seven new rules", "Drop sleep to add more gym", "Shame them into both", "Least friction wins early."),
    ("coaching", "A client who will not track food can still:", "Use plate methods, photos, or one-item checklists", "Be called lazy and dropped", "Be forced onto a spreadsheet", "Need a medical diagnosis from you", "Meet them where they are."),
    ("coaching", "Resistance is often:", "Ambivalence — use better questions, not a lecture", "A reason to insult them", "Proof they need a stricter meal", "A legal problem", "Change talk vs resistance."),
    ("coaching", "A progress photo request should be:", "Optional, private, and consented — never a public before/after without permission", "Posted the same day", "Required to start", "Taken in the locker room secretly", "Body photos are sensitive."),
    ("coaching", "If they miss three check-ins, you:", "Reach out with a short, kind re-onboard — do not ghost or scold", "Publicly call them out", "Add more habits as punishment", "Diagnose depression", "Re-engagement is the skill."),
    ("coaching", "Celebrating a non-scale victory is useful because:", "Behaviors and energy often move before the scale", "The scale is the only truth", "NSVs are fake", "You should hide all wins", "Keep the loop alive."),
    ("coaching", "A 'perfect' week is less useful than:", "An 80–90% week they can repeat", "A Monday restart forever", "A binge-restrict cycle you praise", "A supplement stack", "Consistency > heroics."),
    ("coaching", "Asking 'on a scale of 1–10, how confident?' checks:", "Whether the habit is sized right", "IQ", "Whether they owe you money", "VO2max", "Confidence predicts follow-through."),
    ("coaching", "Talking more than the client in a session usually means:", "You are lecturing, not coaching", "Great value", "They learned more", "You should add slides", "They should speak the change."),
    ("coaching", "A client's partner sabotaging dinners is:", "An environment problem to problem-solve, not a moral failing", "A reason to end the marriage as their coach", "Ignored", "Fixed with more willpower speeches", "Environment eats willpower."),
    ("coaching", "This PN mock is:", "Independent practice — not the official PN L1 exam", "A NASM CPT clone", "A dietetics license", "An RD exam form", "Different credential."),
    ("nutrition-sci", "Protein's coaching job is often to:", "Support satiety and muscle in a deficit", "Replace all carbs forever", "Detox the liver as a cleanse", "Act as a steroid", "Protein is a lever, not magic."),
    ("nutrition-sci", "A calorie deficit explains:", "Most fat loss over time, not a spice detox", "Why sleep never matters", "Why steps never matter", "Why medical conditions never matter", "Energy balance still exists."),
    ("nutrition-sci", "Dietary fat is needed for:", "Hormones, fat-soluble vitamins, and food enjoyment", "Only frying", "Zero if they want abs", "Replacing all protein", "Do not fear dietary fat as a class."),
    ("nutrition-sci", "Carbohydrate is:", "A useful fuel, especially around training — not a toxin", "Poison in fruit", "Only in bread", "Illegal on PN", "PN is not keto-or-bust."),
    ("nutrition-sci", "Fiber mainly helps:", "Satiety and GI regularity", "Steroid synthesis", "Instant six-packs", "Replacing water", "Plants + fiber."),
    ("nutrition-sci", "A food 'allergy' the client self-diagnosed from bloating may be:", "Intolerance, habit, or something medical — you do not confirm IgE", "Always celiac you can clear", "A reason to cut 30 foods at once as day-one homework", "Proof they need ivermectin", "Stay in scope."),
    ("nutrition-sci", "Alcohol is:", "Energy-dense and often a habit trigger", "A micronutrient", "Required for recovery", "Protein", "Count it or it hides."),
    ("nutrition-sci", "Hydration advice that is safe and basic is:", "Regular fluids; pale-yellow urine as a crude check — not gallon-or-die", "IV saline you start", "No water in a cut", "Only juice", "Water is a habit."),
    ("nutrition-sci", "Micronutrients are best covered by:", "A varied diet first, not 20 random pills you sell", "A mystery 'adrenal' spray", "Avoiding all produce", "Only meat", "Food first."),
    ("nutrition-sci", "A sudden 4 lb overnight change is usually:", "Glycogen, sodium, GI content — not 4 lb of fat", "Proof the diet failed forever", "A reason to add thyroid meds you prescribe", "Muscle melted", "Teach water weight."),
    ("nutrition-sci", "RMR is:", "Calories at rest — not a number you invent from an Instagram calculator as medical truth", "The same as TDEE", "Always 800", "Irrelevant", "Estimates are estimates."),
    ("nutrition-sci", "The thermic effect of food is:", "A small part of expenditure, higher for protein", "A fat-burning spice", "Larger than activity always", "A reason to chew ice only", "TEF is real and small."),
    ("nutrition-sci", "A client on a very low-calorie diet who is exhausted:", "May need more food or medical review — not another cut", "Needs more cardio only", "Should add a diuretic you suggest", "Is succeeding", "Symptoms are data."),
    ("nutrition-sci", "Creatine monohydrate, if they ask, is:", "A well-studied supplement you still do not prescribe as a drug", "A steroid", "Required for PN graduation", "Useless for every athlete always", "Stay educational, not a pharmacy."),
    ("nutrition-sci", "A plate method is:", "A visual split of protein, produce, and smart carbs/fats", "A surgical tool", "A CPT 1RM test", "A legal contract", "Simple beats macros for many."),
    ("habits", "Habit stacking means:", "Attach a new action to an existing routine (after coffee, walk)", "Stack five diets", "Only New Year's", "Shame stacking", "Cue is already in the day."),
    ("habits", "The 'bad day' version of a habit should be:", "Even smaller so the streak survives", "Dropped forever", "Doubled", "Hidden from the coach", "Never miss twice, shrink the dose."),
    ("habits", "Environment design example:", "Protein food visible; candy off the counter", "More willpower posters", "A locked fridge with no plan", "Yelling", "Make the default easier."),
    ("habits", "Identity-based change sounds like:", "'I'm someone who cooks on Sundays' plus a tiny proof", "'I suck at food'", "A 30-day shred title only", "A before photo as identity", "Identity follows reps."),
    ("habits", "Sleep as a nutrition habit matters because:", "It changes hunger, training, and adherence", "It is unrelated", "Only models sleep", "You can coach it as a medical apnea clinic", "Ask, then refer sleep medicine if needed."),
    ("habits", "Stress-eating is often:", "A skill gap (pause, protein, walk) not a character flaw", "Fixed by a bigger deficit only", "Ignored", "Treated with a stimulant you recommend", "Skills > labels."),
    ("habits", "A weekly review should ask:", "What worked, what blocked, what's next one change", "Why they are weak", "How to add four supplements", "Whether to fire them", "Short retrospective."),
    ("habits", "Social meals are handled by:", "A plan (protein first, one treat, leave when done) not avoidance forever", "Never eating with humans", "A fight with the in-laws you script as their therapist", "Fasting as punishment after", "Life is the program."),
    ("habits", "Weigh-ins work better when:", "They are a data point among others, not a daily verdict", "Used to shame", "Skipped if up 0.2 lb forever", "Done after a huge meal to 'face reality' only then", "Context the number."),
    ("habits", "A slip is:", "Expected — resume the next meal", "Proof of failure", "A reason to binge more as a rule", "Hidden", "Next meal is the skill."),
    ("habits", "Push notifications that nag hourly usually:", "Get muted — design fewer, better cues", "Create discipline", "Replace coaching", "Are required by PN", "Cue quality."),
    ("habits", "Walking after meals is a habit that:", "Helps glucose and consistency for many clients", "Replaces all lifting always", "Is dangerous for everyone", "Counts as a medical procedure you bill", "Simple activity."),
    ("habits", "Grocery skills beat:", "A PDF of foods they will never cook", "More rules", "A detox tea", "Guessing in the aisle hungry with no list", "Buy what the habit needs."),
    ("habits", "Weekend structure might be:", "One planned meal out + default breakfast, not a 48-hour blackout", "No plan", "A second cut", "A new identity as a party", "Plan the predictable chaos."),
    ("habits", "If a habit is at 2/10 confidence, you:", "Shrink it", "Add two more", "Shame", "Raise the calories burned goal only", "Size to confidence."),
    ("scopes", "A PN coach does not:", "Diagnose disease or deprescribe medication", "Talk about vegetables", "Ask about sleep", "Refer out", "Medical acts stay with clinicians."),
    ("scopes", "A client with a new eating-disorder history should be:", "Referred to qualified care; you do not run their exposure therapy", "Put on a contest prep", "Told to eat less", "Weighed daily in public", "Do no harm."),
    ("scopes", "Supplement sales to a client are an ethics issue when:", "You oversell and under-disclose your cut", "You mention protein food", "You refuse to diagnose", "You refer to an RD", "Disclose and do not pressure."),
    ("scopes", "A Type 1 diabetic's insulin is:", "Managed by their diabetes team — you do not adjust units", "Yours to cut in half on a diet", "A vitamin", "Optional", "Stay out of the pump."),
    ("scopes", "Claiming 'we reverse diabetes' as a guarantee is:", "A medical claim you should not make", "Good ads", "PN dogma", "Safer than referring", "Outcomes are not guaranteed."),
    ("scopes", "Working with minors requires:", "Guardian involvement and extra caution", "A secret plan", "Contest prep", "No food talk", "Youth is a special population."),
    ("scopes", "An RD referral is smart when:", "The case is clinical, complex, or you are out of depth", "The client likes broccoli", "They walked once", "You are bored", "Team sport."),
    ("scopes", "Privacy of food logs means:", "You do not post their diary", "They are public domain", "Fine on Stories if funny", "Shared with their boss", "Logs are intimate."),
    ("scopes", "Scope includes saying:", "'I'm not the right pro for that — here's who is'", "Whatever gets the sale", "A hormone panel read", "A clearance for surgery", "Referrals are competence."),
    ("scopes", "A dual relationship (also their trainer and their bartender) needs:", "Clear boundaries or a decline", "More gossip", "Secret coaching in DMs only", "A family diagnosis", "Conflicts get named."),
    ("scopes", "Guaranteeing a wedding-week weight is:", "Unprofessional", "Standard", "Required", "Safer than a habit plan", "You do not control water or life."),
    ("scopes", "If they ask for a meal to treat cancer:", "Refer to oncology nutrition — do not invent a protocol", "A juice cleanse you found", "Cut all protein", "Add apricot pits", "Oncology is out of scope."),
    ("scopes", "Continuing education matters because:", "Nutrition claims drift; your job is still coaching, not a new license", "You can then prescribe", "CE replaces ethics", "One cert is a medical degree", "Stay updated, stay humble."),
    ("scopes", "Informed consent for coaching includes:", "What you do, what you don't, and that they can stop", "A hidden auto-charge only", "A medical waiver that lets you diagnose", "Nothing written", "Clarity is kindness."),
    ("scopes", "Copying another coach's entire paid program into a client's folder is:", "A copyright and ethics problem", "Fair use always", "Required", "A medical record", "Make your own process."),
]

NSCA = [
    ("assessment", "A preparticipation screen is used to:", "Spot red flags and decide when to refer, not to diagnose disease", "Replace a physician", "Skip on older clients", "Be a 1RM test", "NSCA-CPT screens; it does not diagnose."),
    ("assessment", "A resting heart rate taken after coffee and a sprint is:", "Not a true resting value", "Gold standard", "The same as HRR", "A 1RM", "Control the conditions."),
    ("assessment", "BMI is:", "A population height-weight index, not a complete body-comp diagnosis", "Muscle quality", "VO2max", "Blood pressure", "Use BMI carefully."),
    ("assessment", "A push-up test mainly estimates:", "Upper-body muscular endurance", "Lab VO2max", "1RM squat", "Soleus length only", "Match the test to the quality."),
    ("assessment", "Exertional chest pain during screening means:", "Stop and refer — do not start a 5K test", "Do burpees to test it", "Add caffeine", "Ignore if they are under 40", "Pain on exertion is a stop."),
    ("assessment", "Girth measurements should use:", "Standard landmarks, same tension, similar time of day", "Wherever the tape looks good for Instagram", "A single lifetime measure", "A puffy jacket", "Reliability is the skill."),
    ("assessment", "A sit-and-reach is limited because it:", "Mixes hamstring and low-back and is not a 'healthy spine' diagnosis", "Equals VO2max", "Replaces a 1RM", "Diagnoses disc herniation", "Do not over-read the test."),
    ("assessment", "Blood pressure 162/100 at rest before a session:", "Is a referral/stop situation per your screening rules — not a max-out day", "Is a warm-up cue", "Means add salt", "Is ideal for a 1RM deadlift", "Know your cutoffs."),
    ("assessment", "A 1RM estimate from a 5RM is:", "A prediction with error — not a lab truth", "Exact", "Safer than a screen", "Illegal", "Use charts as estimates."),
    ("assessment", "Body-fat from a cheap handheld BIA can be off because of:", "Hydration, food, and device error", "The client's morals", "Shoe color", "The music", "Treat BIA as a trend, not a verdict."),
    ("assessment", "A movement screen that shows a painful squat means:", "Do not load that pattern — regress or refer", "Add a max squat", "Ignore pain as 'just mobility'", "Diagnose a labral tear", "Painful patterns are not loading candidates."),
    ("assessment", "Informed consent before testing covers:", "What you will do, risks, and that they can stop", "A hidden supplement sale", "A medical diagnosis", "Nothing written", "Consent is part of assessment."),
    ("assessment", "A client on a beta-blocker may show:", "A blunted heart-rate response — do not chase a target HR blindly", "Infinite HR", "No need for RPE", "A reason to skip all screens", "Meds change HR math."),
    ("assessment", "Waist circumference is useful as:", "A central-adiposity risk flag, not a personality score", "VO2", "1RM", "Flexibility", "Central fat is the health signal."),
    ("assessment", "This NSCA-CPT mock is:", "Independent practice — not the official NSCA exam", "A PN L1 clone", "A NASM sales script", "An RD exam", "Different credential."),
    ("program-design", "Progressive overload means:", "A planned increase in demand over time", "Random maxes daily", "Only adding supplements", "Never changing the plan", "Progress is programmed."),
    ("program-design", "A novice strength block often uses:", "Full-body or upper/lower with compound lifts 2–4 days", "Seven body-part 'bro days' and no rest", "Only isolation on day one", "A marathon on the same days as heavy squats always", "Simple frequency wins."),
    ("program-design", "Specificity means:", "The program looks like the goal (strength vs 5K vs hypertrophy)", "Random CrossFit every day for a powerlifter with no reason", "Only biceps for a runner", "Yoga as the only 1RM plan", "Train the quality you want."),
    ("program-design", "A deload is:", "A planned reduction in volume or intensity so the client can recover", "A juice cleanse", "Firing the client", "Adding a second session at 100%", "Deloads are programming, not punishment."),
    ("program-design", "For fat loss, resistance training is there to:", "Keep muscle while a deficit and steps do much of the math", "Replace all calorie awareness", "Be skipped because cardio 'burns more'", "Require a steroid", "Lift in a cut."),
    ("program-design", "Rest intervals for a heavy 5RM squat are typically:", "2–5 minutes, not 15 seconds like a circuit", "Zero", "One breath only", "Tomorrow", "Strength needs rest."),
    ("program-design", "Order of a session usually puts:", "Power/strength compounds before small isolation and long cardio", "Curls first forever", "A 40-minute jog then a max deadlift", "Nothing heavy", "Fatigue order matters."),
    ("program-design", "A client with a goal of a first pull-up needs:", "Hangs, rows, and assisted progressions — not random burpees only", "More bench only", "A deficit to failure", "Keto as the program", "The lift is the program."),
    ("program-design", "Volume is roughly:", "Sets × reps × load (or hard sets) — not Instagram stories", "Only minutes in the gym", "Step count", "Supplements", "Define volume."),
    ("program-design", "An older deconditioned adult should start with:", "Machine or supported patterns and a slower ramp", "A CrossFit Games opener", "Plyometric depth jumps week one", "No strength work", "Dose the start."),
    ("program-design", "Cardio for health can be:", "Most days of moderate work or fewer hard sessions — not zero movement", "Only 5-hour rides", "Replaced by a detox tea", "Skipped if they lift a grocery bag", "Aerobic dose still matters."),
    ("program-design", "If knees hurt on lunges, you:", "Change the pattern or range — do not 'push through' sharp pain", "Add load", "Diagnose a meniscus and operate", "Shame them", "Pain is a program input."),
    ("program-design", "A youth athlete's program should emphasize:", "Skill, variety, and recovery — not a copied advanced split", "1RM every Monday", "Adult contest prep", "Energy drinks", "Kids are not small powerlifters."),
    ("program-design", "Periodization is:", "Planned variation across weeks, not chaos", "Random workouts", "One load forever", "Only for Olympians", "Plan the wave."),
    ("program-design", "Minimum effective dose means:", "Enough to progress without burying the client", "The hardest session on earth", "Zero lifting", "Only cardio", "Do not hero-workout beginners."),
    ("technique", "A squat cue 'knees out' is meant to:", "Keep the knees tracking over the feet, not collapse inward", "Twist the lumbar into pain", "Lift the heels always", "Look at the ceiling only", "Track the knees."),
    ("technique", "A deadlift starting position needs:", "A flat-ish back, bar close, weight mid-foot — not a rounded yank", "A jumper's bounce off the floor with a soft spine as the plan", "A shrug first", "Looking straight down into a phone", "Set the back."),
    ("technique", "A bench press spotter should:", "Help at the sticking point and the unracking, not chest-pass every rep", "Yell only", "Sit on the bar", "Leave for water at a 1RM", "Spotting is a skill."),
    ("technique", "Valgus collapse on a landing is a cue to:", "Coach the knee and hip, or regress — not add height", "Add a weighted vest immediately", "Ignore it", "Diagnose ACL rupture as a CPT", "Control before height."),
    ("technique", "A Romanian deadlift differs from a conventional deadlift mainly in:", "Less knee bend and a hip-hinge emphasis", "Being a curl", "Starting from the floor with a jump", "Using no hip", "Hinge vs squat-pull."),
    ("technique", "A plank is failed when:", "The hips pike or sag past the cue you set", "They sweat", "30 seconds pass on a clock in another room", "They breathe", "Own the position."),
    ("technique", "An overhead press needs:", "A ribcage that is not flung into a giant arch as the only way up", "A max bounce off the belt", "A behind-neck press for every beginner", "No scapular upward rotation", "Earn the overhead."),
    ("technique", "Tempo 3-1-1-0 means:", "About 3 s eccentric, 1 s pause, 1 s concentric", "Three plates", "A 3-mile run", "Rest 31 minutes", "Read tempo codes."),
    ("technique", "A kettlebell swing is primarily a:", "Hip hinge power pattern, not a squat-and-shrug", "Biceps curl", "Behind-the-neck press", "Sit-up", "Hinge fast."),
    ("technique", "If the bar drifts forward on a squat:", "The client is losing mid-foot balance — cue and unload if ugly", "Add 20 kg", "Praise the lean", "Change to a max good morning unplanned", "Bar path is data."),
    ("technique", "A split squat that wobbles hard means:", "Shorten stance or hold support — do not load it", "Add a barbell immediately", "Close the eyes for 'balance'", "Skip the front foot", "Stability before load."),
    ("technique", "Breathing on a heavy squat is often:", "A brace (Valsalva as appropriate) — not a casual exhale at the bottom for a max", "Hyperventilation only", "Held for five minutes after the set", "Irrelevant", "Brace the trunk."),
    ("technique", "A lat pulldown to the chest with control beats:", "Behind-the-neck yanks on a tight shoulder", "A jump on the stack", "A 1RM bounce", "No scapular motion", "Path of the humerus."),
    ("technique", "RPE 8 on a lift means:", "About 2 reps in reserve, not a lifestyle feeling", "Asleep", "A medical pain scale only", "Max heart rate", "Teach RPE."),
    ("technique", "Chalk, belts, and straps are:", "Tools — they do not replace a pattern that is not there", "Cheating always", "Required for warm-ups", "Illegal in all gyms", "Use equipment honestly."),
    ("safety", "A client who is dizzy mid-set should:", "Stop, sit, and be evaluated — not 'one more rep'", "Add ammonia", "Do a max", "Drive home immediately if they look grey", "Dizziness ends the set."),
    ("safety", "Rhabdomyolysis risk rises with:", "Novel extreme volume in a heat-dehydrated client", "A normal novice full-body", "Walking", "A mobility flow", "Do not 'crush' beginners."),
    ("safety", "A pregnant client needs:", "Physician clearance and exercise guidelines — not a max-out challenge", "Supine heavy bench all third trimester without a plan", "A contest cut", "No walking", "Special population."),
    ("safety", "You do not:", "Give a meal plan that treats Type 2 diabetes as a CPT acting as an RD/MD", "Spot a bench", "Regress a lunge", "Refer out", "Scope: training, not medicine."),
    ("safety", "Dropping a deadlift on a busy platform is a risk when:", "People are in the path — control the dump", "The plates are bumper and the area is clear as the gym allows", "You whisper", "You film", "Space management."),
    ("safety", "A torn callus mid-deadlift block:", "May need a downshift and skin care — not more mixed-grip ego", "Means add straps and max anyway", "Is a medical emergency always", "Is ignored until tendon shows", "Skin is a limiter."),
    ("safety", "Caffeine pre-workout in a client with uncontrolled BP:", "Is a reason to be conservative and refer questions to their clinician", "A requirement", "Safer than a screen", "A replacement for sleep", "Stimulants are not free."),
    ("safety", "Emergency action plan includes:", "Who calls EMS, where the AED is, and how you reach parents for a minor", "A vibe", "Your Instagram", "Hoping", "Write the EAP."),
    ("safety", "A child in the gym during an adult session is:", "A supervision and liability problem if they wander the floor", "A free intern", "Allowed under the rack", "Your spotter", "Kids off the platform."),
    ("safety", "Concussion suspicion after a dropped bar near the head:", "Stop, medical evaluation — not 'shake it off' and squat", "More sets", "A protein shake as treatment", "A driving test you administer", "Brain first."),
    ("safety", "Floor hygiene after a bleed from a ripped callus:", "Clean per bloodborne policy", "A dry sweep only", "Leave it", "Ask the next client to wipe it", "Blood is a spill."),
    ("safety", "Dual relationships (dating a client) create:", "A consent and power problem — follow policy", "Better programming always", "A requirement", "Free advertising", "Boundaries."),
    ("safety", "Guaranteeing a 20 lb fat-loss in 14 days is:", "Unethical and often unsafe", "NSCA policy", "Science", "Safer than habits", "No miracle cuts."),
    ("safety", "If you are not competent on Olympic lifts:", "Do not coach a snatch — refer or get educated", "Cue one from TikTok live", "Load it anyway", "Call it a curl", "Competence is safety."),
    ("safety", "Documentation of an incident is:", "Done the same day, factually", "Optional if they seemed fine", "A rant", "Posted online", "Write what happened."),
]


def main() -> None:
    build("barber-state-readiness-check", BARBER, "state barber board")
    build("nail-technician-state-readiness-check", NAIL, "state nail board")
    build("physical-therapy-aide-readiness-check", PTA, "PT aide")
    build("medication-aide-readiness-check", MED, "medication aide")
    build("first-aid-cpr-readiness-check", first_aid(), "first-aid / CPR")
    build("precision-nutrition-l1-readiness-check", PN, "Precision Nutrition")
    build("nsca-cpt-readiness-check", NSCA, "NSCA-CPT")


if __name__ == "__main__":
    main()
