/** AHA BLS Provider cognitive — 60 curated MCQs (15×4) */
export const topics = {
  "adult-cpr": [
    [
      "For an unresponsive adult who is not breathing normally and has no pulse, rescuers should:",
      "Begin high-quality CPR starting with chest compressions and use an AED as soon as available",
      [
        "Wait for advanced providers before any compressions",
        "Give only rescue breaths for 5 minutes first",
        "Check a pulse for at least 30 seconds every cycle without compressing",
      ],
      "Adult cardiac arrest care prioritizes immediate compressions and early defibrillation.",
      [
        "Delay worsens outcomes.",
        "Compression-first (C-A-B) is current adult approach for sudden arrest.",
        "Pulse checks should be brief (≤10 seconds).",
      ],
      "easy",
    ],
    [
      "The recommended adult compression rate is:",
      "100 to 120 compressions per minute",
      [
        "40 to 50 per minute",
        "160 to 180 per minute",
        "As slow as possible to avoid fatigue",
      ],
      "AHA targets 100–120/min with adequate depth and full recoil.",
      [
        "Too slow reduces cardiac output support.",
        "Too fast worsens depth/recoil.",
        "Fatigue is managed by switching compressors ~every 2 minutes.",
      ],
      "easy",
    ],
    [
      "Adult compression depth should be at least:",
      "2 inches (5 cm), not exceeding about 2.4 inches (6 cm)",
      [
        "0.5 inch only",
        "4 inches routinely",
        "Depth does not matter if rate is correct",
      ],
      "Adequate depth is a key high-quality CPR metric; excessive depth can cause injury.",
      [
        "Too shallow is ineffective.",
        "Excessive depth risks trauma.",
        "Depth and rate both matter.",
      ],
      "easy",
    ],
    [
      "Allowing complete chest recoil means:",
      "Letting the chest return to normal position between compressions without leaning",
      [
        "Keeping continuous pressure on the sternum",
        "Bouncing hands off the chest wildly",
        "Compressing only the abdomen",
      ],
      "Leaning reduces venous return; full recoil improves CPR quality.",
      [
        "Leaning impairs refill.",
        "Hands should stay in contact without bouncing off.",
        "Hand position is lower sternum, not abdomen.",
      ],
      "medium",
    ],
    [
      "The compression-to-ventilation ratio for single-rescuer adult CPR (without advanced airway) is:",
      "30:2",
      ["15:2", "5:1", "100:0 always without exception"],
      "Adult CPR uses 30 compressions to 2 breaths for 1 or 2 rescuers before advanced airway.",
      [
        "15:2 is used for 2-rescuer infant/child CPR in many AHA algorithms.",
        "5:1 is outdated.",
        "Compression-only is acceptable for untrained/ unwilling breathers, but trained BLS includes 30:2 when giving breaths.",
      ],
      "easy",
    ],
    [
      "When an AED arrives for an adult in cardiac arrest, you should:",
      "Power on the AED, apply pads, and follow prompts; resume CPR immediately after shock or no-shock advice",
      [
        "Finish a full 10-minute CPR cycle before attaching pads",
        "Wet the chest thoroughly before pad placement for better stick",
        "Place both pads on the abdomen",
      ],
      "Early defibrillation is critical for shockable rhythms; minimize pauses.",
      [
        "Attach ASAP.",
        "Dry the chest; water conducts and may spark.",
        "Standard pad positions are anterolateral (or approved alternative).",
      ],
      "medium",
    ],
    [
      "If the AED advises “no shock,” the rescuer should:",
      "Resume CPR immediately starting with compressions",
      [
        "Stop all care and wait",
        "Shake the patient vigorously for a minute",
        "Remove pads and leave",
      ],
      "No-shock advice still requires high-quality CPR and reassessment per prompts.",
      [
        "Care continues.",
        "Do not delay CPR with prolonged shaking.",
        "Pads stay for analysis cycles.",
      ],
      "easy",
    ],
    [
      "Hand position for adult compressions is:",
      "Heel of one hand on the center of the chest (lower half of sternum), other hand on top",
      [
        "Fingertips on the clavicles",
        "Hands over the upper abdomen only",
        "One hand on each shoulder",
      ],
      "Correct hand position maximizes effective compressions and reduces injury risk.",
      [
        "Clavicles are wrong.",
        "Abdomen is not the compression site.",
        "Shoulders are wrong.",
      ],
      "easy",
    ],
    [
      "To minimize interruption of chest compressions, rescuers should:",
      "Coordinate roles, limit pulse/rhythm checks, and switch compressors efficiently about every 2 minutes",
      [
        "Stop CPR for 1 minute after every 5 compressions",
        "Discuss lunch plans during pauses",
        "Never use an AED because it pauses CPR",
      ],
      "High chest compression fraction improves outcomes; brief planned switches beat long chaotic pauses.",
      [
        "Frequent long stops are harmful.",
        "Unrelated talk during critical pauses is poor teamwork.",
        "AED use is essential despite brief analysis pauses.",
      ],
      "medium",
    ],
    [
      "Rescue breaths for adults should:",
      "Produce visible chest rise over about 1 second each, avoiding excessive ventilation",
      [
        "Be as forceful and fast as possible",
        "Be withheld forever if a pocket mask is unavailable and no alternative exists for a trained willing rescuer—without considering compression-only",
        "Always include 10 breaths without compressions first",
      ],
      "Overventilation increases intrathoracic pressure and decreases venous return.",
      [
        "Forceful/fast breaths are harmful.",
        "Compression-only is preferred if unwilling/unable to ventilate; trained rescuers give breaths with barrier when possible.",
        "Do not delay compressions for prolonged breath-first sequences in sudden adult arrest.",
      ],
      "medium",
    ],
    [
      "For a witnessed adult collapse in a public place with a phone available, an alone rescuer should typically:",
      "Ensure scene safety, check responsiveness/breathing, activate EMS/get AED, then start CPR",
      [
        "Leave for 20 minutes to find a friend before calling",
        "Start by giving abdominal thrusts only",
        "Assume the person is sleeping and walk away",
      ],
      "Rapid EMS activation and AED retrieval are core adult Chain of Survival links.",
      [
        "Delay is harmful.",
        "Abdominal thrusts are for choking, not primary for sudden collapse.",
        "Unresponsiveness needs assessment.",
      ],
      "easy",
    ],
    [
      "If the victim has a medication patch on the chest where an AED pad will go, you should:",
      "Remove the patch and wipe the area dry before applying the pad",
      [
        "Place the pad directly over the patch",
        "Never use an AED if any patch exists anywhere on the body",
        "Burn the patch off with the AED",
      ],
      "Patches can block energy and burn skin; remove and wipe residue.",
      [
        "Do not pad over patches.",
        "AEDs are still used—just clear the pad site.",
        "Do not burn patches.",
      ],
      "medium",
    ],
    [
      "High-quality CPR includes limiting pauses ideally to:",
      "Less than 10 seconds when possible for critical interventions",
      [
        "30–60 seconds routinely for convenience",
        "No compressions until ALS arrives if ALS is 20 minutes away",
        "Pauses after every single compression",
      ],
      "Short pauses preserve coronary perfusion pressure.",
      [
        "Long routine pauses are harmful.",
        "BLS must continue until ALS/relief/ROS C criteria.",
        "Continuous high-quality compressions are the goal.",
      ],
      "hard",
    ],
    [
      "An adult with agonal gasps should be treated as:",
      "Not breathing normally—start CPR if unresponsive and pulseless per assessment",
      [
        "Having effective normal breathing",
        "Only needing a blanket",
        "Ineligible for AED use ever",
      ],
      "Agonal gasps are not adequate breathing and often occur in cardiac arrest.",
      [
        "Gasps ≠ effective ventilation.",
        "Warmth alone does not treat arrest.",
        "AED is indicated in arrest.",
      ],
      "medium",
    ],
    [
      "Team members should switch chest compressors approximately every:",
      "2 minutes (or when prompted by AED/team leader) to reduce fatigue",
      [
        "20 minutes",
        "Every 2 compressions",
        "Never switch once started",
      ],
      "Fatigue quickly degrades depth and rate; planned switches maintain quality.",
      [
        "Too long causes poor CPR.",
        "Too frequent increases interruptions.",
        "Switching is expected.",
      ],
      "easy",
    ],
  ],
  "child-infant": [
    [
      "For child CPR (1 year to puberty), compression depth should be:",
      "About one-third the depth of the chest, approximately 2 inches (5 cm)",
      [
        "Less than 1 cm always",
        "At least 3 inches routinely for all children",
        "Depth is irrelevant in children",
      ],
      "Pediatric depth targets ~⅓ chest depth (~2 inches in children).",
      [
        "Too shallow is ineffective.",
        "Excessive depth risks injury.",
        "Depth matters.",
      ],
      "easy",
    ],
    [
      "Two-rescuer CPR ratio for infants and children (without advanced airway) is commonly:",
      "15:2",
      ["30:2 only forever", "5:1", "50:5"],
      "AHA uses 15:2 for 2-rescuer infant/child CPR; 30:2 for single rescuer.",
      [
        "30:2 is single-rescuer pediatric ratio.",
        "5:1 outdated.",
        "50:5 incorrect.",
      ],
      "medium",
    ],
    [
      "Infant chest compressions may be performed with:",
      "Two fingers (1 rescuer) or two-thumb–encircling hands technique (2 rescuers)",
      [
        "A fist to the face",
        "Heel of both adult hands stacked as for large adults without adaptation",
        "Only abdominal thrusts",
      ],
      "Infant techniques protect the small thorax while generating adequate depth (~1½ inches / 4 cm).",
      [
        "Face trauma is wrong.",
        "Adult two-hand technique is for larger victims.",
        "Abdominal thrusts are not infant CPR compressions.",
      ],
      "easy",
    ],
    [
      "Infant compression depth target is approximately:",
      "1.5 inches (4 cm)",
      ["0.25 inch", "3 inches", "5 inches"],
      "Infants need about 1½ inches / ⅓ chest depth.",
      [
        "Too shallow.",
        "Excessive for infants.",
        "Far too deep.",
      ],
      "easy",
    ],
    [
      "If you are alone and find an unresponsive infant after an unwitnessed collapse, after ~2 minutes of CPR you should:",
      "Activate EMS/get AED if not already done, then continue CPR",
      [
        "Never call EMS for infants",
        "Stop CPR permanently",
        "Only give milk",
      ],
      "Pediatric sequences emphasize brief CPR before leaving to call if alone and collapse unwitnessed; follow current AHA course details for phone/AED steps.",
      [
        "EMS is essential.",
        "Do not stop.",
        "Milk is not resuscitation.",
      ],
      "medium",
    ],
    [
      "For children, cardiac arrest is more often preceded by:",
      "Respiratory problems / hypoxia than primary sudden cardiac causes (though both occur)",
      [
        "Only myocardial infarction identical to older adults always",
        "Hyperthermia treatment with ice baths as first CPR step",
        "Elective skipping of airway support",
      ],
      "Pediatric Chain of Survival emphasizes prevention and oxygenation; still provide compressions for pulseless arrest.",
      [
        "Primary cardiac events are less common but possible.",
        "Ice baths are not the CPR algorithm start.",
        "Airway/ventilation are critical in pediatrics.",
      ],
      "medium",
    ],
    [
      "When using an AED on a child, if pediatric pads/attenuator are unavailable:",
      "Use adult pads; do not let pads touch each other",
      [
        "Never defibrillate a child under any circumstance",
        "Cut adult pads in half",
        "Place both adult pads stacked on the umbilicus",
      ],
      "Adult AEDs may be used if pediatric system unavailable; pad placement must not overlap.",
      [
        "Shockable pediatric rhythms need defibrillation.",
        "Do not modify pads by cutting.",
        "Follow anteroposterior or standard positions as trained.",
      ],
      "hard",
    ],
    [
      "Infant rescue breaths should:",
      "Be gentle enough to produce chest rise, covering mouth and nose with the rescuer’s mouth if using mouth-to-mouth-and-nose",
      [
        "Be maximally forceful",
        "Be avoided for all infants in arrest even by trained rescuers with a barrier",
        "Be given at 40 breaths without compressions first for 10 minutes",
      ],
      "Overventilation is harmful; visible chest rise is the guide.",
      [
        "Force causes gastric inflation/barotrauma.",
        "Trained rescuers provide ventilations in pediatric BLS.",
        "Do not delay compressions with prolonged breath-only periods in arrest.",
      ],
      "medium",
    ],
    [
      "Pulse check location commonly taught for infants is:",
      "Brachial artery",
      ["Radial artery only as first choice", "Popliteal only", "Carotid only as the sole infant site taught"],
      "Brachial pulse is standard for infants; carotid/femoral used in older children.",
      [
        "Radial is difficult in infants.",
        "Popliteal not the standard infant check.",
        "Carotid is more for children/adults.",
      ],
      "easy",
    ],
    [
      "For a child who is unresponsive and not breathing normally but has a pulse ≥60/min with poor perfusion signs, BLS may include:",
      "Rescue breathing with pulse checks, and start compressions if pulse remains <60 with poor perfusion per AHA pediatric guidance",
      [
        "No respiratory support ever",
        "Only abdominal thrusts continuously",
        "Walking the child immediately",
      ],
      "Pediatric bradycardia with poor perfusion is a compression indication even if a pulse is present but too slow.",
      [
        "Ventilation is often critical.",
        "Choking algorithm differs.",
        "Unresponsive children are not ambulated.",
      ],
      "hard",
    ],
    [
      "Two-thumb encircling hands technique for infants is preferred when:",
      "Two rescuers are available",
      [
        "Never preferred",
        "Only for adults",
        "Only during choking with effective cough",
      ],
      "Two-thumb technique generally produces better depth/consistency with two rescuers.",
      [
        "It is preferred for 2-rescuer infant CPR.",
        "Adults use heel-of-hand methods.",
        "Effective cough means observe, not CPR thumbs.",
      ],
      "medium",
    ],
    [
      "Compression rate for infants and children is:",
      "100 to 120 per minute",
      ["60 per minute", "30 per minute", "200 per minute"],
      "Same target rate as adults: 100–120/min.",
      [
        "Too slow.",
        "Far too slow.",
        "Too fast.",
      ],
      "easy",
    ],
    [
      "If a child has a pulse and is breathing adequately after a brief seizure, you should:",
      "Protect airway, place recovery position if appropriate, monitor, and activate EMS as indicated by condition/history",
      [
        "Start chest compressions immediately despite pulse and breathing",
        "Give nothing and leave the child alone prone face-down in water",
        "Force oral fluids while still postictal and unsafe airway",
      ],
      "CPR is for arrest/poor perfusion states; postictal care is supportive with EMS per situation.",
      [
        "Do not compress if adequate pulse/breathing.",
        "Unsafe positioning risks aspiration.",
        "Airway risk precludes forced fluids.",
      ],
      "medium",
    ],
    [
      "For infant CPR landmarking, compressions are delivered:",
      "Just below the nipple line on the sternum",
      [
        "On the xiphoid tip intentionally",
        "On the forehead",
        "On the femur",
      ],
      "Correct landmarking avoids abdominal organ injury.",
      [
        "Avoid the xiphoid tip.",
        "Forehead is for airway positioning, not compressions.",
        "Femur is wrong.",
      ],
      "easy",
    ],
    [
      "Pediatric AED pad placement should:",
      "Follow manufacturer guidance; ensure pads do not touch (use AP placement if needed on small chests)",
      [
        "Overlap pads completely for stronger shock",
        "Place pads on clothing without skin contact",
        "Be skipped if the child is wet without drying attempt",
      ],
      "Pad contact and separation matter for effective, safe defibrillation.",
      [
        "Overlapping is incorrect.",
        "Skin contact required.",
        "Dry the chest; moisture is hazardous.",
      ],
      "medium",
    ],
  ],
  "choking-opioid": [
    [
      "A responsive adult with severe choking (cannot speak/cough effectively) needs:",
      "Abdominal thrusts (Heimlich) until object expels or victim becomes unresponsive",
      [
        "Encourage only weak coughing without intervention when severe",
        "Blind finger sweeps routinely",
        "Immediate AED application while they are still speaking in full sentences",
      ],
      "Severe FBAO requires thrusts; mild obstruction with effective cough—encourage coughing.",
      [
        "Severe obstruction needs action.",
        "Blind sweeps can worsen obstruction.",
        "AED is for cardiac arrest, not talking victims.",
      ],
      "easy",
    ],
    [
      "If a choking adult becomes unresponsive, you should:",
      "Lower to a firm surface, begin CPR, and look for an object in the mouth before breaths when visible",
      [
        "Continue abdominal thrusts on an unresponsive victim upright",
        "Leave to call without starting compressions if alone with a phone on speaker already activated—never start CPR",
        "Pour water into the mouth",
      ],
      "Unresponsive choking transitions to CPR; remove visible objects only—no blind sweeps.",
      [
        "Unresponsive victims get CPR on the ground.",
        "CPR is indicated; use speakerphone if alone.",
        "Water risks aspiration.",
      ],
      "medium",
    ],
    [
      "For a responsive choking infant, the correct sequence includes:",
      "5 back blows followed by 5 chest thrusts, repeating until relieved or unresponsive",
      [
        "Abdominal thrusts as first-line identical to adults",
        "Blind finger sweeps every cycle",
        "Only watching for 10 minutes",
      ],
      "Infant FBAO uses back blows and chest thrusts—not abdominal thrusts.",
      [
        "Abdominal thrusts are not for infants.",
        "No blind sweeps.",
        "Severe choking needs immediate action.",
      ],
      "easy",
    ],
    [
      "Mild airway obstruction with a strong cough should be managed by:",
      "Encouraging continued coughing and monitoring closely",
      [
        "Immediate abdominal thrusts while they are effectively coughing",
        "Starting CPR compressions while they stand and talk",
        "Giving rescue breaths forcefully against resistance",
      ],
      "Do not interfere with effective cough; be ready if it becomes severe.",
      [
        "Thrusts are for severe obstruction.",
        "CPR is for unresponsive/pulseless.",
        "Forced breaths can worsen obstruction.",
      ],
      "easy",
    ],
    [
      "Chest thrusts instead of abdominal thrusts are preferred for choking in:",
      "Pregnant or markedly obese responsive adults (as trained)",
      [
        "All toddlers as the only method ever",
        "Anyone with a mild cough only",
        "Infants using adult Heimlich belts",
      ],
      "Pregnancy/obesity alter landmarking; use chest thrusts per BLS training.",
      [
        "Infants use back blows/chest thrusts sequences.",
        "Mild cough—observe/encourage.",
        "Infants do not use adult Heimlich belts.",
      ],
      "medium",
    ],
    [
      "Suspected opioid overdose with respiratory arrest but a pulse requires:",
      "Rescue breathing/ventilatory support and naloxone per local protocols, plus EMS activation",
      [
        "Chest compressions only with no ventilation consideration",
        "Waiting for the person to wake without calling EMS",
        "Giving syrup of ipecac",
      ],
      "Opioid toxicity causes respiratory depression; support breathing and use naloxone when indicated/available.",
      [
        "Ventilation is critical if pulse present with apnea.",
        "EMS is required.",
        "Ipecac is obsolete/harmful here.",
      ],
      "medium",
    ],
    [
      "If an opioid overdose victim is unresponsive, not breathing normally, and pulseless:",
      "Start CPR and use AED; administer naloxone as soon as available without delaying compressions",
      [
        "Only give naloxone and never compress",
        "Avoid AED because opioids contraindicate shocks",
        "Place in recovery position and leave",
      ],
      "Cardiac arrest care still follows CPR/AED; naloxone is adjunctive, not a reason to skip BLS.",
      [
        "CPR is required if pulseless.",
        "AED is still used for shockable rhythms.",
        "Do not leave an arrest victim.",
      ],
      "medium",
    ],
    [
      "Naloxone (intranasal/autoinjector) in BLS settings is intended to:",
      "Temporarily reverse opioid-induced respiratory depression",
      [
        "Treat hypoglycemia as first-line",
        "Replace the need for EMS",
        "Defibrillate the heart",
      ],
      "Effects may wear off; monitor and be ready to redose per protocol; continue airway support.",
      [
        "Not glucose.",
        "EMS still needed.",
        "Not a defibrillator.",
      ],
      "easy",
    ],
    [
      "After successful naloxone response, the person may:",
      "Become agitated or re-sedate later as naloxone wears off—continue observation/EMS care",
      [
        "Be safely left alone immediately every time",
        "Never need airway monitoring again",
        "Be given more opioids to “balance” naloxone",
      ],
      "Renarcotization is a known risk; observation is mandatory.",
      [
        "Do not leave alone.",
        "Monitoring continues.",
        "Do not give opioids to counter naloxone.",
      ],
      "hard",
    ],
    [
      "A choking child who becomes unresponsive should receive:",
      "CPR with checks for visible objects before breaths",
      [
        "Continued standing Heimlich only",
        "No compressions ever",
        "Blind deep finger sweeps every time",
      ],
      "Same transition to CPR as adults/children when unresponsive from FBAO.",
      [
        "Ground CPR replaces upright thrusts.",
        "Compressions are part of care.",
        "Only remove visible objects.",
      ],
      "medium",
    ],
    [
      "Signs of severe foreign-body airway obstruction include:",
      "Inability to speak, weak/silent cough, cyanosis, universal choking sign",
      [
        "Loud forceful coughing with ability to speak full sentences",
        "Normal skin color and playful talking",
        "Ability to sing loudly",
      ],
      "Differentiate mild vs severe to choose observation vs thrusts.",
      [
        "Effective cough = mild.",
        "Normal talk ≠ severe.",
        "Singing implies airway patent enough for mild category.",
      ],
      "easy",
    ],
    [
      "For pregnant choking victims, hand position for chest thrusts is:",
      "Center of the sternum (same general area as CPR compressions)",
      [
        "Low on the fundus pushing toward the spine only as abdominal Heimlich",
        "On the lumbar spine from behind without chest contact",
        "On the forehead",
      ],
      "Chest thrusts avoid gravid abdomen; follow BLS training details.",
      [
        "Standard abdominal thrusts are problematic in late pregnancy.",
        "Spine pushes are incorrect.",
        "Forehead is wrong.",
      ],
      "hard",
    ],
    [
      "Scene safety with suspected opioid overdose includes:",
      "Awareness of fentanyl exposure myths vs real risks; use PPE as trained and avoid needle sticks",
      [
        "Tasting unknown powders to identify them",
        "Sharing the victim’s pills to confirm opioid type",
        "Ignoring sharps on the ground",
      ],
      "Rescuers protect themselves while providing rapid care; incidental skin contact is not the main panic narrative—avoid mucous membrane/sharps exposure.",
      [
        "Never taste unknowns.",
        "Never take victim’s drugs.",
        "Sharps injure rescuers.",
      ],
      "medium",
    ],
    [
      "High-flow oxygen / advanced airway management beyond BLS scope should be:",
      "Left to trained ALS providers; BLS focuses on basic ventilation and compressions",
      [
        "Performed by any bystander without training",
        "A reason to delay CPR for 15 minutes",
        "Required before calling 911",
      ],
      "Know your scope; high-quality BLS bridges to ALS.",
      [
        "Training required for advanced skills.",
        "Do not delay CPR.",
        "Call EMS early.",
      ],
      "easy",
    ],
    [
      "If abdominal thrusts fail and the adult remains responsive but still severely choking, you should:",
      "Continue cycles of thrusts until the object is expelled or the victim becomes unresponsive",
      [
        "Stop trying after one thrust",
        "Give the victim a large glass of water under pressure",
        "Start AED analysis while they are conscious and upright with a pulse",
      ],
      "Persist with the choking algorithm; prepare to transition to CPR if unresponsiveness occurs.",
      [
        "Multiple thrusts are often needed.",
        "Water is dangerous.",
        "AED is not for conscious choking with pulse.",
      ],
      "medium",
    ],
  ],
  "team-special": [
    [
      "Closed-loop communication means:",
      "The receiver repeats back the order and the sender confirms correctness",
      [
        "Speaking only once without confirmation",
        "Using vague pronouns for all tasks",
        "Silence during resuscitation",
      ],
      "Closed-loop reduces errors in high-stress codes.",
      [
        "Confirmation prevents mishearing.",
        "Clarity beats vagueness.",
        "Clear communication is required.",
      ],
      "easy",
    ],
    [
      "A team leader’s role includes:",
      "Assigning roles, monitoring CPR quality, and summarizing the plan",
      [
        "Performing every task alone without delegation",
        "Discouraging AED use",
        "Ignoring feedback from team members",
      ],
      "Leadership improves coordination and chest compression fraction.",
      [
        "Delegation is essential.",
        "AED is encouraged.",
        "Constructive feedback improves care.",
      ],
      "easy",
    ],
    [
      "Constructive intervention means a team member should:",
      "Speak up clearly if a critical error or unsafe action is about to occur",
      [
        "Remain silent even if compressions are on the abdomen",
        "Wait until after ROSC documentation only",
        "Argue personally without stating the clinical issue",
      ],
      "Safety culture expects respectful challenge of dangerous actions.",
      [
        "Silence harms the patient.",
        "Intervene in real time for critical errors.",
        "Focus on the action, not personality.",
      ],
      "medium",
    ],
    [
      "During CPR with an advanced airway in place, ventilations are typically given:",
      "1 breath every 6 seconds (10/min) with continuous compressions without 30:2 pauses",
      [
        "30:2 forever without change",
        "No ventilations at all",
        "1 breath every 60 seconds only",
      ],
      "Advanced airway allows asynchronous continuous compressions with timed breaths.",
      [
        "30:2 is for no advanced airway.",
        "Ventilations continue.",
        "Every 6 seconds is the adult target.",
      ],
      "hard",
    ],
    [
      "Pregnant patient in cardiac arrest: in addition to high-quality CPR, rescuers should:",
      "Perform manual left uterine displacement to relieve aortocaval compression when the uterus is clinically significant",
      [
        "Avoid AED use entirely in pregnancy",
        "Place the patient fully flat supine without displacement consideration for a large gravid uterus",
        "Delay compressions until obstetricians arrive if ETA is 30 minutes",
      ],
      "LUD improves venous return; defibrillation is still indicated when needed; maternal resuscitation prioritizes CPR.",
      [
        "AED/defibrillation is used in pregnancy.",
        "Gravid uterus can impair CPR without displacement.",
        "Do not delay maternal CPR.",
      ],
      "hard",
    ],
    [
      "If a rescuer is too fatigued to keep correct compression depth, the best action is:",
      "Announce the need to switch and rotate immediately with minimal pause",
      [
        "Continue ineffective compressions silently",
        "Stop the resuscitation permanently",
        "Decrease rate to 40/min to rest",
      ],
      "Teamwork corrects fatigue; pride should not degrade CPR quality.",
      [
        "Ineffective CPR harms outcomes.",
        "Do not abandon care.",
        "Slow rates are incorrect.",
      ],
      "easy",
    ],
    [
      "Using a bag-mask device effectively usually requires:",
      "Proper seal and often two-person technique for better ventilation",
      [
        "Squeezing as hard and fast as possible",
        "No head-tilt/chin-lift or jaw thrust consideration",
        "Placing the mask on the forehead only",
      ],
      "Seal and airway position determine tidal delivery; avoid overventilation.",
      [
        "Overventilation is harmful.",
        "Airway opening maneuvers matter.",
        "Mask covers nose and mouth.",
      ],
      "medium",
    ],
    [
      "When to stop BLS efforts is generally determined by:",
      "Obvious signs of life/ROSC, transfer to ALS, valid DNR orders meeting local rules, or scene becoming unsafe",
      [
        "Personal inconvenience after 1 minute",
        "Family requesting social media posts first",
        "Guessing without assessment that “it’s fine”",
      ],
      "Know local protocols and legal/ethical frameworks for termination/withholding.",
      [
        "1 minute is far too early.",
        "Social media is irrelevant.",
        "Assessment drives decisions.",
      ],
      "medium",
    ],
    [
      "Special situation: victim on a soft bed—for CPR you should:",
      "Move the victim to a firm surface or place a backboard if available",
      [
        "Compress deeply into a soft mattress without concern",
        "Only do breaths on soft surfaces",
        "Avoid CPR because beds forbid it",
      ],
      "Soft surfaces dissipate force; firm support improves compression effectiveness.",
      [
        "Soft surfaces reduce effective depth.",
        "Compressions remain essential.",
        "CPR is performed with surface correction.",
      ],
      "easy",
    ],
    [
      "If the victim has a hairy chest and AED pads will not stick:",
      "Quickly remove hair in the pad area (razor if in kit) so pads adhere, then analyze",
      [
        "Place pads on top of thick hair without contact",
        "Skip AED permanently",
        "Wet hair with oil",
      ],
      "Pad contact is required for AED function; kits often include razors.",
      [
        "Poor contact fails analysis/shock.",
        "Do not skip AED.",
        "Oil worsens adhesion.",
      ],
      "medium",
    ],
    [
      "Water/scene: before AED use on a victim in a wet environment:",
      "Move to a dry area if possible and dry the chest; avoid standing water around rescuers",
      [
        "Apply AED while both rescuer and victim are in a puddle without drying",
        "Never dry the chest",
        "Submerge the AED to ground it",
      ],
      "Reduce shock hazard to rescuers; AEDs are used after reasonable drying/movement.",
      [
        "Standing water risks rescuer shock.",
        "Drying the pad sites matters.",
        "Do not submerge AEDs.",
      ],
      "medium",
    ],
    [
      "Role clarity during a code is improved when each member:",
      "Knows their assignment (compressions, airway, AED, documentation) and stays in lane unless reassigned",
      [
        "All crowd the airway with no compressor",
        "Everyone gives contradictory orders simultaneously",
        "Nobody watches the clock/AED prompts",
      ],
      "Clear roles prevent task fixation and missing compressions.",
      [
        "Someone must compress.",
        "One leader, closed-loop.",
        "Time/AED prompts guide switches.",
      ],
      "easy",
    ],
    [
      "Feedback devices / CPR coaches help teams by:",
      "Prompting rate, depth, recoil, and pauses in real time",
      [
        "Replacing the need for an AED",
        "Diagnosing STEMI on their own as a 12-lead",
        "Eliminating EMS activation",
      ],
      "Quality metrics improve with coaching and feedback tools when available.",
      [
        "AED still required.",
        "Not a diagnostic ECG replacement.",
        "EMS still needed.",
      ],
      "easy",
    ],
    [
      "For a victim with a tracheostomy who needs ventilation, BLS-trained providers should:",
      "Ventilate via the tracheostomy using appropriate interface as trained / per local protocol",
      [
        "Always seal the mouth only and ignore the stoma",
        "Never ventilate tracheostomy patients",
        "Pour liquid into the stoma",
      ],
      "Ventilate the airway the patient has; follow training for stoma ventilation.",
      [
        "Stoma is the airway.",
        "They need ventilation in arrest/respiratory failure.",
        "Do not pour liquids into the airway.",
      ],
      "hard",
    ],
    [
      "After ROSC (return of spontaneous circulation), BLS providers should:",
      "Support airway/breathing, monitor pulse and blood pressure as able, and prepare for transport/ALS care",
      [
        "Stop all monitoring and leave",
        "Immediately give the patient a large meal",
        "Remove AED pads and turn off attention to re-arrest risk",
      ],
      "Re-arrest is common; continue close monitoring and supportive care.",
      [
        "Do not abandon.",
        "NPO/airway risks early after ROSC.",
        "Keep defibrillation capability ready.",
      ],
      "medium",
    ],
  ],
};
