#!/usr/bin/env python3
"""ASWB Masters readiness bank — 60Q."""

from write_helper import write_bank

HUMAN_DEV = [
    (
        "Erikson’s stage for adolescents is commonly described as:",
        "Identity vs. role confusion",
        ["Trust vs. mistrust", "Integrity vs. despair", "Industry vs. inferiority only as adolescence"],
        "Adolescence centers on identity formation; infancy is trust; late life is integrity; school age is industry.",
        [
            "Trust vs. mistrust is infancy.",
            "Integrity vs. despair is late adulthood.",
            "Industry vs. inferiority is school age.",
        ],
        "easy",
    ),
    (
        "Piaget’s formal operational stage is characterized by:",
        "Abstract and hypothetical-deductive reasoning",
        ["Only sensorimotor reflexes", "Only object permanence as the highest skill", "Inability to think about possibilities"],
        "Formal operations enable abstract thought; sensorimotor is infancy; object permanence emerges earlier.",
        [
            "Sensorimotor is earliest stage.",
            "Object permanence is sensorimotor achievement.",
            "Formal ops include hypothetical thinking.",
        ],
        "easy",
    ),
    (
        "A genogram is primarily used to:",
        "Map family relationships, patterns, and intergenerational information",
        ["Measure blood pressure", "Replace all community resource lists", "Score IQ precisely"],
        "Genograms visualize family systems data for assessment and intervention planning.",
        [
            "Vital signs need clinical tools.",
            "Resource lists are separate ecomap/community tools.",
            "IQ testing is psychometric.",
        ],
        "easy",
    ),
    (
        "Cultural humility in practice emphasizes:",
        "Lifelong learning, self-reflection, and redressing power imbalances with clients",
        ["Assuming the worker’s culture is superior", "Memorizing one stereotype per group as sufficient", "Avoiding any discussion of culture"],
        "Cultural humility is process-oriented and anti-oppressive rather than static 'competence' alone.",
        [
            "Superiority contradicts humility.",
            "Stereotypes harm practice.",
            "Culture often matters to meaning and access.",
        ],
        "medium",
    ),
    (
        "Maslow’s hierarchy places which need near the base (most foundational)?",
        "Physiological needs (food, water, shelter)",
        ["Self-actualization as the first survival need", "Esteem needs before breathing", "Aesthetic needs as more basic than safety"],
        "Basic physiological and safety needs generally precede higher growth needs in the classic model.",
        [
            "Self-actualization is highest in the classic pyramid.",
            "Esteem is higher-level.",
            "Aesthetics are higher-level.",
        ],
        "easy",
    ),
    (
        "Intersectionality refers to:",
        "How overlapping social identities (race, gender, class, etc.) shape unique experiences of privilege and oppression",
        ["Only a traffic engineering term in social work theory", "Treating all clients as identical", "Ignoring systemic factors entirely"],
        "Crenshaw’s intersectionality informs assessment of compound inequities.",
        [
            "In SW it is a social theory concept.",
            "Sameness erases identity.",
            "Systems matter.",
        ],
        "medium",
    ),
    (
        "Secure attachment in early childhood is associated with:",
        "A caregiver who is generally responsive and available, supporting exploration with a safe base",
        ["Consistent neglect", "Frightening caregiver behavior as the ideal", "No caregiving relationships"],
        "Secure attachment develops through contingent, sensitive caregiving.",
        [
            "Neglect relates to insecure/disorganized risks.",
            "Frightening care links to disorganization.",
            "Attachment requires caregiving relationships.",
        ],
        "medium",
    ),
    (
        "Which concept describes a community’s ability to recover from adversity?",
        "Resilience (individual, family, or community)",
        ["Learned helplessness as recovery", "Anomie as cohesion", "Object permanence"],
        "Resilience is adaptive capacity after stress; learned helplessness is the opposite pattern.",
        [
            "Learned helplessness impairs agency.",
            "Anomie is normlessness.",
            "Object permanence is cognitive development.",
        ],
        "easy",
    ),
    (
        "Ageism is:",
        "Prejudice or discrimination based on age",
        ["Only racism", "Only sexism", "A type of blood test"],
        "Ageism targets older (or sometimes younger) persons based on age stereotypes.",
        [
            "Racism is race-based.",
            "Sexism is sex/gender-based.",
            "Not a lab test.",
        ],
        "easy",
    ),
    (
        "In systems theory, homeostasis refers to:",
        "A system’s tendency to maintain stability / equilibrium",
        ["Inevitable chaos with no patterns", "Only individual cognition without context", "Termination of all feedback loops"],
        "Families/organizations regulate to preserve familiar patterns—sometimes including dysfunctional ones.",
        [
            "Systems show patterned regulation.",
            "Context is central in systems views.",
            "Feedback loops sustain regulation.",
        ],
        "medium",
    ),
    (
        "Which defense mechanism involves attributing one’s own unacceptable feelings to another?",
        "Projection",
        ["Sublimation", "Altruism as identical to projection", "Suppression as identical to projection"],
        "Projection places internal content onto others; sublimation channels impulses into valued activities.",
        [
            "Sublimation is channeling into acceptable outlets.",
            "Altruism is other-focused helping.",
            "Suppression is conscious postponement.",
        ],
        "hard",
    ),
    (
        "A strengths-based perspective prioritizes:",
        "Client capacities, resources, and aspirations alongside challenges",
        ["Only deficits and pathology labels", "Worker goals imposed without collaboration", "Ignoring environmental resources"],
        "Strengths perspectives balance problems with assets and collaboration.",
        [
            "Deficit-only views miss resources.",
            "Collaboration is key.",
            "Environment often holds resources.",
        ],
        "easy",
    ),
    (
        "Disenfranchised grief refers to:",
        "Grief not socially acknowledged or supported (e.g., stigmatized losses)",
        ["Only grief after legally recognized funerals", "Absence of any emotional reaction forever by definition", "Joy at all losses"],
        "When losses lack recognition, mourning can be complicated by silence and stigma.",
        [
            "Recognition varies; not all grief is publicly supported.",
            "People may grieve without visible affect at times, but that’s not the definition.",
            "Grief is not joy.",
        ],
        "hard",
    ),
    (
        "Person-in-environment (PIE) assessment emphasizes:",
        "Understanding individuals within social, cultural, and environmental contexts",
        ["Diagnosing only via lab values", "Ignoring community factors", "Treating personality as irrelevant always"],
        "PIE is foundational to social work assessment across micro–macro levels.",
        [
            "SW assessment is broader than labs.",
            "Community/context matter.",
            "Personality may be relevant but not isolated from environment.",
        ],
        "medium",
    ),
    (
        "Which statement about human sexuality in practice is most appropriate?",
        "Sexuality is a normal aspect of human development; assess with sensitivity, consent, and cultural awareness",
        ["Never discuss sexual health even when relevant to risk", "Impose the worker’s values as the only moral standard", "Assume all older adults are asexual"],
        "Affirming, nonjudgmental assessment supports health and rights across the lifespan.",
        [
            "Relevant sexual health may be clinically necessary.",
            "Self-determination and ethics limit imposition.",
            "Ageist assumptions are inaccurate.",
        ],
        "medium",
    ),
]

ASSESSMENT = [
    (
        "The first step in the planned change process is typically:",
        "Engagement",
        ["Termination before meeting", "Evaluation without data", "Immediate involuntary commitment for all intakes"],
        "Engage → assess → plan → intervene → evaluate → terminate is a common sequence.",
        [
            "Termination comes later.",
            "Evaluation needs implemented work/data.",
            "Commitment is a specific legal process, not default intake.",
        ],
        "easy",
    ),
    (
        "A mental status exam commonly includes observation of:",
        "Appearance, behavior, mood/affect, thought process/content, cognition, and insight/judgment",
        ["Only credit score", "Only shoe size", "Only employer’s profit margin"],
        "MSE structures clinical observation; it is not a financial audit.",
        [
            "Credit is not MSE.",
            "Anthropometrics alone aren’t MSE.",
            "Business metrics aren’t MSE.",
        ],
        "easy",
    ),
    (
        "Suicidal ideation assessment should include:",
        "Ideation, plan, intent, means, history, protective factors, and safety planning as indicated",
        ["Avoiding the topic to not 'plant ideas' in all cases", "Only asking once in a lifetime", "Promising absolute secrecy even when imminent risk requires action"],
        "Direct, thorough risk assessment saves lives; confidentiality has safety limits.",
        [
            "Asking about suicide is standard and does not create risk in the mythic way.",
            "Risk can change; reassess.",
            "Duty to protect may require action.",
        ],
        "medium",
    ),
    (
        "An ecomap primarily shows:",
        "Connections between a client system and external systems/resources/stressors",
        ["Only DNA sequences", "Only DSM criteria lists", "Only medication half-lives"],
        "Ecomaps visualize environmental supports and demands.",
        [
            "Genetics need labs.",
            "DSM is diagnostic taxonomy.",
            "Pharmacokinetics is medical.",
        ],
        "easy",
    ),
    (
        "Which interviewing skill involves restating the client’s message to confirm understanding?",
        "Paraphrasing / reflective listening",
        ["Advice-giving as the first response always", "Changing the subject abruptly", "Interrupting with personal stories"],
        "Reflection builds rapport and accuracy before problem-solving.",
        [
            "Premature advice can miss the problem.",
            "Topic shifts can feel dismissive.",
            "Worker stories can recenter the worker.",
        ],
        "easy",
    ),
    (
        "A dual diagnosis (co-occurring disorders) assessment means attending to:",
        "Mental health and substance use disorders together",
        ["Only housing without clinical issues", "Only vision screening", "Only dental caries"],
        "Integrated assessment improves treatment planning for co-occurring conditions.",
        [
            "Housing may matter but is not the definition.",
            "Vision is separate.",
            "Dental is separate.",
        ],
        "medium",
    ),
    (
        "Which is an example of an open-ended assessment question?",
        "What have you tried so far to manage the conflict at home?",
        ["Are you married? (yes/no only, with no elaboration sought)", "Date of birth only", "Insurance ID only"],
        "Open questions elicit narrative detail useful for assessment.",
        [
            "Closed questions have a place but yield less depth alone.",
            "DOB is demographic.",
            "Insurance is administrative.",
        ],
        "easy",
    ),
    (
        "Crisis intervention prioritizes:",
        "Safety, stabilization, and linking to supports/resources",
        ["Long-term personality reconstruction as the first hour goal always", "Ignoring imminent danger", "Forced disclosure of all childhood memories immediately"],
        "Crisis work is present-focused and safety-first.",
        [
            "Deep reconstruction is later treatment.",
            "Danger must be addressed.",
            "Forced trauma processing can harm in crisis.",
        ],
        "medium",
    ),
    (
        "Reliability of an assessment instrument refers to:",
        "Consistency of measurement",
        ["Whether it measures the intended construct (validity)", "How popular it is on social media", "The font size only"],
        "Reliability = consistency; validity = accuracy for the construct.",
        [
            "That defines validity.",
            "Popularity ≠ psychometrics.",
            "Formatting ≠ reliability.",
        ],
        "hard",
    ),
    (
        "When assessing intimate partner violence, a social worker should:",
        "Interview partners separately when IPV is a concern and prioritize survivor safety",
        ["Require couples to confront each other immediately in the same room always", "Blame the survivor for staying", "Ignore mandatory reporting laws that apply"],
        "Safety planning and separate interviews reduce retaliation risk; follow law/ethics.",
        [
            "Joint confrontation can escalate danger.",
            "Victim-blaming is unethical.",
            "Legal duties still apply.",
        ],
        "medium",
    ),
    (
        "A behaviorally specific treatment goal should be:",
        "Observable, measurable, and time-framed when possible",
        ["Vague like 'feel better someday'", "Only the worker’s private wish", "Impossible by design"],
        "Measurable goals guide intervention and evaluation.",
        [
            "Vagueness prevents evaluation.",
            "Goals are collaborative.",
            "Goals should be attainable.",
        ],
        "easy",
    ),
    (
        "Which approach explores automatic thoughts and cognitive distortions?",
        "Cognitive behavioral assessment/intervention frameworks",
        ["Only psychoanalytic free association as identical to CBT thought records", "Only wilderness survival training", "Only phlebotomy"],
        "CBT targets links among thoughts, feelings, and behaviors.",
        [
            "Psychodynamic methods differ though both can be useful.",
            "Not a wilderness curriculum.",
            "Not a medical lab skill.",
        ],
        "medium",
    ),
    (
        "Motivational interviewing is especially useful when clients are:",
        "Ambivalent about change",
        ["Already fully committed with no ambivalence ever", "Unconscious under anesthesia", "Seeking only notarization services"],
        "MI elicits change talk and resolves ambivalence collaboratively.",
        [
            "Less needed when already action-ready, though still usable.",
            "Requires conscious participation.",
            "Not a notary function.",
        ],
        "medium",
    ),
    (
        "An example of a mezzo-level intervention is:",
        "Facilitating a support group or intervening with a family/organizational team",
        ["Only lobbying Congress as micro counseling", "Only individual CBT as macro policy", "Writing a national law as a single therapy session"],
        "Mezzo = small groups/families/organizations; micro = individuals; macro = communities/policy.",
        [
            "Lobbying is typically macro.",
            "Individual CBT is micro.",
            "Lawmaking is macro.",
        ],
        "hard",
    ),
    (
        "Collateral contacts in assessment should be pursued:",
        "With appropriate consent/authorization except where law allows limited exceptions",
        ["Always secretly without any legal basis", "Never even with consent", "Only to gossip"],
        "Consent and legal exceptions (e.g., safety) govern collateral information gathering.",
        [
            "Secret gathering can violate ethics/law.",
            "Collateral data can be valuable with consent.",
            "Purpose is assessment/treatment, not gossip.",
        ],
        "easy",
    ),
]

ETHICS = [
    (
        "Self-determination in social work means:",
        "Supporting clients’ rights to make their own choices within legal/ethical limits",
        ["The worker decides all life choices unilaterally", "Ignoring imminent harm risks always", "Forcing values conversion"],
        "Autonomy is balanced with safety, laws, and competing ethical duties.",
        [
            "Paternalism undermines self-determination.",
            "Safety duties can limit confidentiality/autonomy.",
            "Imposing values is unethical.",
        ],
        "easy",
    ),
    (
        "A dual relationship becomes unethical when it:",
        "Risks exploitation, impairs professional judgment, or harms the client",
        ["Is always illegal in every brief community hello", "Never matters in rural areas", "Is required for billing"],
        "NASW ethics caution against harmful dual relationships; context and risk matter.",
        [
            "Not every incidental contact is unethical.",
            "Rural practice needs careful management, not denial.",
            "Billing does not require dual roles.",
        ],
        "medium",
    ),
    (
        "Informed consent requires:",
        "Clear explanation of services, risks/benefits, limits of confidentiality, and voluntary agreement",
        ["Consent after services secretly concluded", "Consent coerced by threats", "No discussion of confidentiality limits"],
        "Consent is ongoing, understandable, and voluntary.",
        [
            "Must precede/ongoing with service.",
            "Coercion invalidates consent.",
            "Limits must be explained.",
        ],
        "easy",
    ),
    (
        "Confidentiality may be broken when:",
        "There is serious foreseeable harm / legal mandates (e.g., abuse reporting, duty to warn/protect as applicable)",
        ["The worker wants to vent to friends", "For marketing testimonials without consent", "Because a neighbor is curious"],
        "Privacy is primary but not absolute under safety and law.",
        [
            "Venting is a breach.",
            "Marketing needs authorization.",
            "Curiosity is insufficient.",
        ],
        "easy",
    ),
    (
        "Competence requires social workers to:",
        "Practice within knowledge/skill limits and seek supervision/training or refer",
        ["Accept every case regardless of skill gaps without support", "Falsify credentials", "Avoid all continuing education"],
        "Ethical practice includes knowing when to refer or obtain consultation.",
        [
            "Skill gaps need remediation/referral.",
            "Credential fraud is unethical/illegal.",
            "CE maintains competence.",
        ],
        "easy",
    ),
    (
        "Bartering for clinical services is generally:",
        "Approached with caution due to conflicts of interest and potential exploitation",
        ["Always the preferred payment method", "Required by NASW for all clients", "Identical to insurance billing always"],
        "Ethics warn that bartering can confuse boundaries and fairness.",
        [
            "Not preferred by default.",
            "Not required.",
            "Different from third-party billing.",
        ],
        "medium",
    ),
    (
        "When a colleague is impaired and clients may be harmed, an ethical response includes:",
        "Addressing concerns through appropriate channels (consult, report as required)",
        ["Ignoring clear impairment indefinitely", "Joining in substance use during sessions", "Destroying records to hide problems"],
        "Client protection and professional accountability are duties.",
        [
            "Ignoring risk is unethical.",
            "Impairment in practice is misconduct.",
            "Record destruction is unethical/illegal.",
        ],
        "medium",
    ),
    (
        "Sexual relationships with current clients are:",
        "Prohibited",
        ["Encouraged as rapport", "Allowed if the client initiates", "Allowed after one session only"],
        "Sexual contact with clients is an ethical bright line due to power differentials.",
        [
            "Not rapport—exploitation risk.",
            "Client initiation does not make it ethical.",
            "Timing within the relationship does not authorize it.",
        ],
        "easy",
    ),
    (
        "Documentation should be:",
        "Accurate, timely, respectful, and limited to relevant information",
        ["Fabricated to improve outcomes metrics", "Full of sarcastic remarks about clients", "Stored publicly online with identifiers"],
        "Records support continuity and accountability; protect dignity and privacy.",
        [
            "Falsification is unethical/illegal.",
            "Respect is required.",
            "Public posting breaches confidentiality.",
        ],
        "easy",
    ),
    (
        "Conflicts of interest should be:",
        "Avoided or disclosed and managed so clients’ interests remain primary",
        ["Hidden to protect the agency brand", "Used to maximize worker profit always", "Ignored in private practice only"],
        "Transparency and client primacy guide conflict management.",
        [
            "Hiding conflicts worsens harm.",
            "Profit cannot override client welfare.",
            "Setting does not erase the duty.",
        ],
        "medium",
    ),
    (
        "Cultural competence/humility ethically requires:",
        "Awareness of bias and adapting practice to clients’ cultures and languages as feasible",
        ["Forcing assimilation as the only goal", "Using interpreters’ minors as primary translators for trauma content routinely", "Mocking clients’ beliefs"],
        "Respectful adaptation and qualified interpretation uphold dignity and access.",
        [
            "Assimilation pressure can be oppressive.",
            "Children as interpreters is inappropriate for sensitive content.",
            "Mockery is unethical.",
        ],
        "hard",
    ),
    (
        "When laws and ethics appear to conflict, social workers should:",
        "Seek supervision/consultation and attempt to resolve while prioritizing ethical principles and legal obligations thoughtfully",
        ["Automatically break the law without consultation always", "Abandon the client immediately without transfer", "Post the dilemma on public social media with names"],
        "Consultation and careful resolution protect clients and the profession.",
        [
            "Unilateral illegal acts are not the default.",
            "Abandonment is unethical.",
            "Public naming breaches privacy.",
        ],
        "hard",
    ),
    (
        "Client access to records is generally:",
        "Supported with limited exceptions (e.g., serious harm from release) per law/ethics",
        ["Never allowed under any circumstance", "Allowed only if the client pays a bribe", "Public to all relatives automatically"],
        "Clients often have rights to records; apply jurisdictional rules and harm exceptions carefully.",
        [
            "Access rights commonly exist.",
            "Bribery is illegal.",
            "Family access needs authorization/exceptions.",
        ],
        "medium",
    ),
    (
        "Providing services via technology requires attention to:",
        "Privacy/security, informed consent for telepractice limits, and licensure jurisdiction",
        ["No consent differences from in-person ever", "Using public unsecured Wi-Fi for therapy without safeguards as best practice", "Practicing in states where you are barred without concern"],
        "Tele-social-work adds privacy and jurisdictional duties.",
        [
            "Telepractice needs specific consent elements.",
            "Security safeguards are required.",
            "Licensure boundaries matter.",
        ],
        "medium",
    ),
    (
        "Advocacy ethics include:",
        "Promoting social justice while accurately representing clients and evidence",
        ["Fabricating statistics to win", "Outing a client’s status without consent for a campaign", "Silencing client voice to favor the agency"],
        "Ethical advocacy is truthful, consent-based, and client-centered.",
        [
            "Dishonesty undermines justice.",
            "Consent/privacy still apply.",
            "Client voice is central.",
        ],
        "easy",
    ),
]

PRACTICE = [
    (
        "Case management primarily focuses on:",
        "Assessing needs and linking/coordinating services across systems",
        ["Only providing psychoanalysis five days a week", "Only performing surgery", "Ignoring community resources"],
        "Case managers broker, coordinate, and monitor services with clients.",
        [
            "Therapy may be adjunct, not the definition.",
            "Surgery is medical.",
            "Resources are central.",
        ],
        "easy",
    ),
    (
        "An interdisciplinary team works best when members:",
        "Share information appropriately, respect roles, and keep the client’s goals central",
        ["Compete to withhold data from each other", "Ignore confidentiality agreements entirely", "Exclude the client from all planning always"],
        "Collaboration improves outcomes; privacy rules still guide sharing.",
        [
            "Withholding harms care.",
            "Sharing must be lawful/appropriate.",
            "Client participation is valued.",
        ],
        "easy",
    ),
    (
        "Utilization review / managed care often requires social workers to:",
        "Document medical necessity and communicate treatment rationale clearly",
        ["Invent diagnoses for payment", "Provide no records ever to payers with authorization", "Abandon documentation standards"],
        "Ethical documentation supports access without fraud.",
        [
            "Fraudulent diagnoses are unethical/illegal.",
            "Authorized disclosures to payers are common.",
            "Standards remain.",
        ],
        "medium",
    ),
    (
        "Which policy analysis question examines who benefits and who bears costs?",
        "Equity / distributional impact analysis",
        ["Only spell-checking a memo", "Only counting pages", "Only choosing a font"],
        "Equity analysis is central to social policy evaluation.",
        [
            "Mechanics ≠ impact analysis.",
            "Length ≠ equity.",
            "Formatting ≠ equity.",
        ],
        "medium",
    ),
    (
        "Burnout prevention for practitioners includes:",
        "Supervision, workload management, self-care, and organizational supports",
        ["Endless overtime without recovery as a badge of honor", "Isolation from all peers forever", "Using substances to cope during sessions"],
        "Sustainable practice protects clients and workers.",
        [
            "Chronic overload worsens burnout.",
            "Peer/supervisory support helps.",
            "Impaired practice is unethical.",
        ],
        "easy",
    ),
    (
        "A process recording is used mainly for:",
        "Supervision and skill development by analyzing interview process",
        ["Billing fraud", "Public entertainment", "Replacing all clinical notes permanently"],
        "Process recordings examine communication patterns for learning.",
        [
            "Not a fraud tool.",
            "Not public content.",
            "Official records remain necessary.",
        ],
        "medium",
    ),
    (
        "Macro practice includes:",
        "Community organizing, policy practice, and program development",
        ["Only individual CBT worksheets", "Only phlebotomy", "Only handwriting analysis"],
        "Macro SW targets systems and structures.",
        [
            "CBT worksheets are micro tools.",
            "Phlebotomy is clinical lab.",
            "Graphology is not SW macro practice.",
        ],
        "easy",
    ),
    (
        "When ending services, ethical termination includes:",
        "Adequate notice when possible, summary of progress, referrals, and processing the ending",
        ["Sudden abandonment without cause or referral when continuation is needed", "Ghosting after conflict with no documentation", "Destroying the chart to prevent follow-up"],
        "Avoid abandonment; support continuity of care.",
        [
            "Abandonment is unethical.",
            "Document and communicate.",
            "Records must be retained per law.",
        ],
        "easy",
    ),
    (
        "Evidence-informed practice integrates:",
        "Best research evidence, clinical expertise, and client preferences/culture",
        ["Only anecdotes from social media influencers", "Only what the agency has always done without question", "Research while ignoring client values"],
        "EIP balances science, expertise, and client context.",
        [
            "Influencers ≠ evidence hierarchy.",
            "Tradition alone is insufficient.",
            "Values/preferences matter.",
        ],
        "medium",
    ),
    (
        "HIPAA primarily concerns:",
        "Privacy and security of protected health information in covered entities",
        ["Setting therapy theoretical orientations", "Issuing social work licenses", "Zoning homeless shelters exclusively"],
        "HIPAA regulates PHI uses/disclosures and safeguards.",
        [
            "Theory choice is professional judgment.",
            "Licensure is state boards.",
            "Zoning is local policy.",
        ],
        "medium",
    ),
    (
        "Program evaluation that focuses on whether outcomes were achieved is:",
        "Outcome / summative evaluation",
        ["Only formative process notes with no outcomes", "A genogram", "A mental status exam"],
        "Summative/outcome evaluation judges results; formative improves implementation.",
        [
            "Process evaluation differs.",
            "Genograms are assessment tools.",
            "MSE is clinical assessment.",
        ],
        "hard",
    ),
    (
        "Advocacy for a client denied benefits may include:",
        "Helping appeal with documentation and navigating administrative processes",
        ["Falsifying disability evidence", "Threatening claims workers with violence", "Impersonating an attorney if unlicensed"],
        "Ethical advocacy uses lawful procedures and accurate information.",
        [
            "Fraud is illegal.",
            "Threats are illegal/unethical.",
            "Unauthorized practice of law is prohibited.",
        ],
        "medium",
    ),
    (
        "Supervision in social work functions to provide:",
        "Administrative oversight, education, and support",
        ["Only friendship without case accountability", "Only punishment without teaching", "Replacement for all ethical standards"],
        "Kadushin/functions of supervision include admin, educational, and supportive roles.",
        [
            "Accountability remains.",
            "Education is central.",
            "Ethics still bind practice.",
        ],
        "easy",
    ),
    (
        "A logic model in program design typically links:",
        "Inputs → activities → outputs → outcomes",
        ["Only staff birthdays", "Only building paint codes", "Random unrelated events with no theory of change"],
        "Logic models make the theory of change explicit for planning/evaluation.",
        [
            "Not a social calendar.",
            "Not facilities décor.",
            "Needs causal/logical links.",
        ],
        "hard",
    ),
    (
        "When agency policy conflicts with client well-being, a social worker should:",
        "Advocate within channels, seek supervision, and pursue ethical remedies without abandoning duties casually",
        ["Silently harm clients to protect the agency", "Quit mid-session without transfer coverage as first step always", "Post PHI publicly to force change"],
        "Ethical resistance uses appropriate advocacy and protects clients.",
        [
            "Client welfare remains primary.",
            "Plan coverage/termination ethically.",
            "PHI exposure is unethical/illegal.",
        ],
        "hard",
    ),
]


def main() -> None:
    write_bank(
        "aswb-masters-readiness-check",
        {
            "human-dev": HUMAN_DEV,
            "assessment": ASSESSMENT,
            "ethics": ETHICS,
            "practice": PRACTICE,
        },
    )


if __name__ == "__main__":
    main()
