#!/usr/bin/env python3
"""CDL Passenger (P) endorsement readiness bank — 60Q."""

from write_helper import write_bank

INSPECTION = [
    (
        "During a pre-trip inspection of a passenger bus, emergency exits must be:",
        "Checked to ensure they open/close properly and warning devices work as required",
        ["Taped shut for the entire route", "Ignored if the bus looks clean", "Removed to save weight"],
        "Emergency exits must be operational and properly identified for evacuation.",
        [
            "Exits must remain usable.",
            "Cleanliness ≠ exit function.",
            "Do not remove required exits.",
        ],
        "easy",
    ),
    (
        "Passenger bus brake checks are critical because:",
        "Stopping distance and passenger safety depend on properly functioning service and parking brakes",
        ["Buses do not use brakes", "Only steering matters on buses", "Brakes are optional under 40 mph"],
        "Air/hydraulic brake systems must meet inspection standards before carrying passengers.",
        [
            "Buses rely on brakes heavily.",
            "Steering and brakes both matter.",
            "Brakes are always required.",
        ],
        "easy",
    ),
    (
        "If an aisle light or interior lighting required for safe passenger movement is out, you should:",
        "Address the defect per out-of-service / company rules before operating with passengers as required",
        ["Carry passengers anyway without concern", "Ask passengers to use phone flashlights as the official fix", "Remove all lighting permanently"],
        "Lighting defects can be OOS items when they impair safe boarding/evacuation.",
        [
            "Safety defects must be fixed.",
            "Passenger phones are not compliance.",
            "Lighting is required for safety.",
        ],
        "medium",
    ),
    (
        "Fire extinguishers on buses must be:",
        "Present, charged/sealed as required, and readily accessible",
        ["Optional decorations", "Stored locked away where no one can reach them in an emergency", "Empty to reduce weight"],
        "Emergency equipment must be ready for immediate use.",
        [
            "Extinguishers are required equipment.",
            "Accessibility matters in fire.",
            "Empty units are useless.",
        ],
        "easy",
    ),
    (
        "A cracked windshield in the driver’s critical vision area is:",
        "A serious defect that may place the vehicle out of service",
        ["Always acceptable if stickers cover the crack", "Only a problem for cars, not buses", "Fixed by dimming the lights"],
        "Vision must be clear; OOS criteria address windshield damage in the sweep area.",
        [
            "Stickers can worsen vision obstruction.",
            "Buses have the same safety need.",
            "Lighting does not repair glass.",
        ],
        "medium",
    ),
    (
        "Wheelchair lift / securement systems, when equipped, should be inspected for:",
        "Proper operation, damage, and required securement belts/devices",
        ["Cosmetic paint only", "Whether they make noise as a pass/fail only", "Ignoring them if unused that morning"],
        "Accessibility equipment must function for passengers who need it.",
        [
            "Function matters more than paint.",
            "Noise alone is incomplete.",
            "Inspect even if not immediately used.",
        ],
        "medium",
    ),
    (
        "Tire inspection on a coach should include:",
        "Tread depth, inflation, cuts/bulges, and dual matching as applicable",
        ["Only tire brand logos", "Only mud on sidewalls as acceptable damage", "Never checking duals"],
        "Tire failures endanger everyone on board; check to standards.",
        [
            "Logos don’t measure safety.",
            "Damage/bulges are defects.",
            "Duals need inspection.",
        ],
        "easy",
    ),
    (
        "Emergency reflectors / warning devices must be:",
        "On board and available to set out during stops/breakdowns as required",
        ["Left at the depot always", "Replaced by verbal shouting only", "Used only for decoration on the dash"],
        "FMCSA requires emergency warning devices for commercial vehicles.",
        [
            "They must travel with the vehicle.",
            "Shouting is not traffic control.",
            "They are safety equipment.",
        ],
        "easy",
    ),
    (
        "Passenger seats and stanchions should be checked for:",
        "Secure mounting and hazardous damage that could injure riders",
        ["Softness only for marketing", "Whether seats recline to beds illegally", "Ignoring loose seats"],
        "Loose seats/handholds are injury hazards in sudden stops.",
        [
            "Security of mounting is key.",
            "Illegal conversions are not the inspection goal.",
            "Loose seats are defects.",
        ],
        "medium",
    ),
    (
        "If the low air pressure warning fails during an air-brake bus check, you should:",
        "Not operate until repaired—warning devices are critical safety systems",
        ["Disable the buzzer and proceed", "Assume gauges alone are always enough without required warnings", "Add air by pumping forever while loaded on the route"],
        "Required warnings must work; do not carry passengers with critical brake defects.",
        [
            "Disabling warnings is illegal/unsafe.",
            "Warnings are required redundancy.",
            "Pumping is not a repair.",
        ],
        "hard",
    ),
    (
        "Baggage doors and exterior compartments should be:",
        "Securely closed/latched so items cannot fall onto the roadway",
        ["Left open for ventilation at highway speed", "Tied with string instead of latches as best practice", "Ignored if empty"],
        "Unsecured doors/baggage create road hazards and damage risk.",
        [
            "Open doors are dangerous.",
            "Proper latches are required.",
            "Inspect closures regardless.",
        ],
        "easy",
    ),
    (
        "Mirrors on a passenger vehicle must be adjusted to:",
        "Provide required views along the sides and to the rear for safe lane changes and backing",
        ["Show only the dashboard", "Be removed to reduce drag", "Point only at the sky"],
        "Proper mirror setup is essential for a long vehicle with limited rearward vision.",
        [
            "Dash view is useless for traffic.",
            "Mirrors are required.",
            "Sky view misses traffic.",
        ],
        "easy",
    ),
    (
        "A first-aid kit on a bus, when required by rules/company policy, should be:",
        "Present and adequately stocked/accessible",
        ["Optional trash", "Locked in an inaccessible trailer not on the bus", "Used as a snack box"],
        "Emergency medical supplies support passenger care until help arrives.",
        [
            "It is safety equipment.",
            "Must be on the vehicle.",
            "Not for food storage.",
        ],
        "medium",
    ),
    (
        "Steering play beyond acceptable limits means:",
        "The vehicle may be unsafe/out of service until corrected",
        ["Better handling on ice", "A reason to drive faster", "No concern on passenger carriers"],
        "Excessive free play impairs control—critical with human cargo.",
        [
            "Loose steering worsens control.",
            "Speed increases risk.",
            "Passenger carriers need tight control.",
        ],
        "medium",
    ),
    (
        "During post-trip inspection of a bus, drivers often note:",
        "New defects, passenger damage, and items left behind that affect the next trip’s safety",
        ["Only radio station presets", "Nothing, because post-trips are never useful", "Only the driver’s lunch preference"],
        "Post-trips catch defects early and protect the next passengers.",
        [
            "Presets aren’t safety defects.",
            "Post-trips are valuable.",
            "Lunch is irrelevant.",
        ],
        "easy",
    ),
]

LOADING = [
    (
        "Standee passengers on buses, when allowed, must:",
        "Remain behind the standee line and not obstruct the driver’s vision or controls",
        ["Stand on the dashboard", "Block emergency exits for comfort", "Sit in the aisle during curves intentionally"],
        "Standee rules protect vision, control access, and evacuation paths.",
        [
            "Dash standing is illegal/unsafe.",
            "Exits must stay clear.",
            "Aisles need to remain usable.",
        ],
        "easy",
    ),
    (
        "Carry-on baggage should be stowed so that it:",
        "Does not block aisles or exits and is secured against falling",
        ["Fills the stairwell completely", "Covers emergency door handles", "Is piled on the driver’s lap"],
        "Unsecured bags become projectiles and block evacuation.",
        [
            "Stairs must remain usable.",
            "Handles must be accessible.",
            "Driver area must stay clear.",
        ],
        "easy",
    ),
    (
        "When assisting elderly or disabled passengers, a driver should:",
        "Allow adequate boarding time and use lifts/securement per training and rules",
        ["Rush them while moving the bus", "Refuse all accessibility equipment use when required", "Secure wheelchairs with bungee cords not designed for the purpose"],
        "Courtesy plus compliant securement protects civil rights and safety.",
        [
            "Never move with unsecured boarders at risk.",
            "Equipment must be used when needed.",
            "Use approved securement systems.",
        ],
        "medium",
    ),
    (
        "The standee line exists to:",
        "Keep passengers from entering the area that would block the driver’s view or access to controls",
        ["Mark where to store fuel", "Indicate the smoking section", "Show where luggage must be thrown"],
        "Forward of the standee line is restricted for safety/visibility.",
        [
            "Not a fuel mark.",
            "Smoking rules differ and are often prohibited.",
            "Not a luggage toss zone.",
        ],
        "easy",
    ),
    (
        "Before departing a stop, the driver should:",
        "Ensure doors are closed, passengers are clear of doorways, and the path is safe",
        ["Pull away while passengers are still in the doorway", "Close doors on limbs intentionally", "Skip mirror checks"],
        "Door entrapment and falls are major bus hazards.",
        [
            "Doorway clearance is mandatory.",
            "Never trap passengers.",
            "Mirrors confirm clearance.",
        ],
        "easy",
    ),
    (
        "Emergency exit paths must remain:",
        "Clear of passengers and baggage",
        ["Blocked by coolers for convenience", "Used as permanent storage for tools", "Roped off so they cannot open"],
        "Evacuation speed depends on clear exits.",
        [
            "Coolers can kill escape time.",
            "Tools don’t belong in exits.",
            "Exits must operate.",
        ],
        "easy",
    ),
    (
        "When loading at a curb, a common safe practice is:",
        "Position the bus close/parallel as appropriate so passengers do not step into traffic",
        ["Stop in the travel lane far from the curb forcing street boarding when a bay exists", "Discharge into active traffic without care", "Encourage j-walking across highways mid-block as policy"],
        "Minimize pedestrian exposure to vehicles.",
        [
            "Curb/bay use reduces exposure.",
            "Traffic-side discharge is hazardous.",
            "Jaywalking is unsafe.",
        ],
        "medium",
    ),
    (
        "Child passengers / school-type operations (when applicable to your service) require extra attention to:",
        "Loading/unloading procedures, crossing rules, and accounting for riders",
        ["Maximum speed in loading zones always", "Ignoring flashers/stop arms where required", "Letting children hang out windows while moving"],
        "Young riders need structured loading safety—know your operation’s rules.",
        [
            "Loading zones need slow/careful movement.",
            "Warning devices matter where equipped/required.",
            "Body outside windows is forbidden.",
        ],
        "medium",
    ),
    (
        "If a passenger is standing in front of an emergency exit door, you should:",
        "Direct them to move so the exit remains usable",
        ["Allow them to block it for the whole trip", "Lock the exit permanently", "Stack luggage against it"],
        "Exits must remain available throughout the trip.",
        [
            "Blocking is unsafe.",
            "Exits must open in emergencies.",
            "Luggage cannot block exits.",
        ],
        "easy",
    ),
    (
        "Proper wheelchair securement typically includes:",
        "Using the vehicle’s approved straps/tiedowns at designated points, brakes set as appropriate, and passenger restraint as required",
        ["Asking the passenger to hold the handrail only with no tiedowns", "Parking brakes on the chair only with no floor attachments", "Facing the chair sideways unsecured in the aisle"],
        "Manufacturers and regs specify securement systems—follow them.",
        [
            "Handrails alone are insufficient.",
            "Chair brakes are not full securement.",
            "Unsecured aisle placement is dangerous.",
        ],
        "hard",
    ),
    (
        "Overcrowding beyond designed capacity is unsafe because:",
        "It blocks aisles/exits, increases tip/weight issues, and slows evacuation",
        ["It improves fuel economy always", "It is required for passenger endorsements", "It reduces stopping distance"],
        "Respect capacity and local rules; never compromise exits.",
        [
            "Weight/drag usually worsen economy.",
            "Endorsements don’t require overcrowding.",
            "More weight increases stopping distance.",
        ],
        "medium",
    ),
    (
        "Announce stops / provide information when needed so that:",
        "Passengers can prepare to exit safely without sudden movement",
        ["Passengers jump up during hard braking surprises", "No one knows the next stop ever", "People gather in the stairwell while the bus is moving at speed as standard"],
        "Communication reduces falls from unexpected motion.",
        [
            "Surprises cause injuries.",
            "Information supports safe alighting.",
            "Stairwells while moving are hazardous.",
        ],
        "medium",
    ),
    (
        "Animals on buses are generally limited to:",
        "Service animals and other animals only as permitted by policy/law",
        ["Any aggressive unrestrained animal anytime", "Livestock in the aisle unbound", "Pets blocking exits without carriers when forbidden"],
        "Follow carrier policy and disability law for service animals.",
        [
            "Aggression endangers riders.",
            "Livestock rules differ—aisles must stay clear.",
            "Exit blockage is forbidden.",
        ],
        "hard",
    ),
    (
        "When passengers are boarding with hot beverages, a safety concern is:",
        "Spills causing burns during acceleration/turns—encourage secure lids/seating",
        ["Hot drinks improve emergency exits", "Spills lubricate the aisle usefully", "Drivers should accelerate harder to cool cups"],
        "Scalds and slip hazards are common; smooth operation helps.",
        [
            "Drinks don’t help exits.",
            "Spills create slips.",
            "Hard accel worsens spills.",
        ],
        "easy",
    ),
    (
        "The driver’s responsibility for passenger management includes:",
        "Reasonable rules enforcement for safety without unnecessary confrontation escalation",
        ["Ignoring fights that block the aisle", "Participating in altercations physically as first response always", "Allowing riding on exterior steps"],
        "Maintain order for safety; use company procedures and law enforcement when needed.",
        [
            "Aisle fights are emergencies.",
            "De-escalate; don’t start violence.",
            "Exterior riding is prohibited.",
        ],
        "medium",
    ),
]

DRIVING_RAIL = [
    (
        "At railroad crossings, buses often must:",
        "Stop, look, and listen as required for passenger vehicles—do not shift gears while crossing",
        ["Race across without stopping when lights are flashing red", "Stop on the tracks to check maps", "Follow a truck so closely you cannot see tracks"],
        "Passenger endorsements emphasize rail-crossing stops and clear tracks before proceeding.",
        [
            "Flashing red means stop.",
            "Never stop on tracks.",
            "Keep enough space to see and stop.",
        ],
        "easy",
    ),
    (
        "If a bus stalls on railroad tracks, the priority is:",
        "Evacuate passengers away from the tracks immediately and then contact authorities",
        ["Stay seated to save time", "Try to push the bus while passengers remain aboard next to an approaching train", "Ignore warning lights"],
        "Life safety first—get people off and away at an angle toward the approaching train’s direction of travel as trained.",
        [
            "Evacuation is urgent.",
            "Passengers must evacuate first.",
            "Warnings mean danger.",
        ],
        "medium",
    ),
    (
        "Smooth operation of a passenger bus matters because:",
        "Sudden starts/stops injure standing passengers and cause falls",
        ["Jerky driving improves comfort", "Passengers prefer being thrown forward", "Smoothness only matters for freight"],
        "Accelerate, brake, and turn smoothly with human cargo.",
        [
            "Jerks cause injuries.",
            "Falls are harmful.",
            "Passengers need smoother rides than freight.",
        ],
        "easy",
    ),
    (
        "When backing a bus is necessary, best practice is:",
        "Use a helper when possible, check mirrors, and back slowly the shortest distance",
        ["Back fast without mirrors", "Rely on horn only without looking", "Back into active pedestrian streams without spotters when available"],
        "Buses have large blind spots; minimize backing.",
        [
            "Speed increases crash risk.",
            "Horn ≠ vision.",
            "Protect pedestrians.",
        ],
        "medium",
    ),
    (
        "In an emergency evacuation of a bus, passengers should:",
        "Use the nearest safe exit and move to a safe assembly area away from traffic/hazards",
        ["Stay inside for photos", "Gather on the roadway centerline", "Return for luggage first during fire"],
        "Evacuation priority is people, not property.",
        [
            "Get out.",
            "Away from traffic.",
            "Luggage can wait/burn.",
        ],
        "easy",
    ),
    (
        "Hydroplaning risk increases with:",
        "Speed and standing water; reduce speed in rain",
        ["Brand-new deep tread making hydroplaning inevitable at 5 mph always", "Dry pavement only", "Using headlights on dry days only as the cause"],
        "Slow down in rain; worn tires worsen hydroplaning.",
        [
            "Good tread helps; speed still matters.",
            "Dry pavement has traction.",
            "Lights aid visibility, not hydroplaning cause.",
        ],
        "medium",
    ),
    (
        "If you must stop on a highway shoulder with passengers, you should:",
        "Activate hazards, set out triangles as required, and keep passengers away from traffic when evacuating",
        ["Leave passengers standing on the travel lane side casually", "Skip warning devices at night", "Turn off all lights to 'hide'"],
        "Visibility and separation from traffic prevent secondary crashes.",
        [
            "Keep people off travel lanes.",
            "Devices are critical at night.",
            "Lights increase conspicuity.",
        ],
        "medium",
    ),
    (
        "Railroad crossing gates that are down mean:",
        "Do not cross—wait until it is safe and gates rise / signals allow",
        ["Drive around gates onto the tracks", "Squeeze under partially lowered gates", "Follow another bus onto tracks when space is tight mid-crossing"],
        "Never drive around gates; ensure enough space to fully clear tracks.",
        [
            "Going around gates is illegal/deadly.",
            "Partial clearance is still blocked.",
            "Don’t commit without space to clear.",
        ],
        "easy",
    ),
    (
        "Passenger comfort on long grades includes managing:",
        "Speed, brakes (avoid fade), and transmission use appropriate to the vehicle",
        ["Riding service brakes continuously without regard to heat", "Neutral coasting down long grades as best practice for air brakes", "Turning engine off downhill"],
        "Control speed early; brake fade endangers everyone aboard.",
        [
            "Continuous braking overheats.",
            "Neutral coasting is dangerous.",
            "Engine helps control speed.",
        ],
        "hard",
    ),
    (
        "In fog, a bus driver should:",
        "Slow down, increase following distance, and use appropriate lighting",
        ["Speed up to exit fog faster always", "Follow the taillights ahead as closely as possible", "Use high beams when they reflect back blinding you"],
        "Reduce speed to visibility; avoid clustering on leaders’ lights.",
        [
            "Speed raises crash risk.",
            "Close following is unsafe.",
            "High beams can worsen glare in fog.",
        ],
        "medium",
    ),
    (
        "If a fight endangers safe operation, the driver should:",
        "Stop in a safe place if needed, protect safety, and call for assistance per policy",
        ["Continue at highway speed while fighting occurs in the aisle", "Join the fight", "Lock emergency exits so no one leaves"],
        "You cannot drive safely amid violence—stop and get help.",
        [
            "Highway speed + chaos = disaster.",
            "Don’t escalate violence.",
            "Exits must remain available.",
        ],
        "hard",
    ),
    (
        "Mirror use before lane changes on a bus is essential because:",
        "Blind spots are large and passengers/vehicles can be hidden along the sides",
        ["Buses have no blind spots", "Turn signals alone move other vehicles", "Lane changes never matter for coaches"],
        "Signal, mirror, blind-spot check, then move gradually.",
        [
            "Blind spots are significant.",
            "Signals don’t clear space alone.",
            "Lane discipline matters.",
        ],
        "easy",
    ),
    (
        "When approaching a drawbridge with a signal requiring a stop (as applicable), you should:",
        "Stop and not cross until it is safe / signal allows",
        ["Cross while the bridge is opening", "Ignore signals if late", "Follow a car closely onto a rising span"],
        "Bridge and rail hazards demand full compliance with signals.",
        [
            "Opening bridges are impassable safely.",
            "Schedule ≠ safety.",
            "Don’t follow onto unsafe spans.",
        ],
        "medium",
    ),
    (
        "Emergency after an evacuation: headcount matters because:",
        "You must account for passengers and report missing persons to responders",
        ["Headcounts are only for hotels", "Once outside, accountability ends", "Only count luggage"],
        "Accountability guides rescue efforts.",
        [
            "Transit emergencies need accountability too.",
            "Keep track until relieved.",
            "People over property.",
        ],
        "easy",
    ),
    (
        "Engine fires require:",
        "Evacuating passengers, using extinguishers if safe/trained, and not opening the hood carelessly to feed oxygen",
        ["Pouring gasoline on the engine", "Keeping everyone seated over the engine", "Driving at high speed to 'blow it out' always"],
        "Life safety and controlled extinguishment beat improvised tactics.",
        [
            "Fuel worsens fire.",
            "Evacuate.",
            "Speed doesn’t safely extinguish engine fires.",
        ],
        "hard",
    ),
]

PROHIBITED = [
    (
        "Fueling a bus with passengers aboard is generally:",
        "Prohibited / unsafe practice—discharge passengers before fueling as required by rules/policy",
        ["Required for time savings", "Allowed if you smoke while fueling", "Encouraged with engines racing"],
        "Fire/explosion risk makes fueling with riders aboard unacceptable in standard CDL teaching.",
        [
            "Time does not override safety rules.",
            "No smoking when fueling.",
            "Racing engines adds hazard.",
        ],
        "easy",
    ),
    (
        "Driving with an open passenger door is:",
        "Prohibited because passengers can fall out",
        ["Allowed at highway speeds for ventilation", "Required in winter", "A substitute for AC"],
        "Doors must be closed while moving (with limited operational exceptions taught carefully).",
        [
            "Never highway with open doors.",
            "Weather doesn’t allow open-door travel.",
            "Use HVAC, not open doors.",
        ],
        "easy",
    ),
    (
        "Talking on a hand-held phone while driving a CMV is:",
        "Generally prohibited under federal/state distracted driving rules for CDL drivers",
        ["Required for safety", "Allowed whenever you feel bored", "Safer than watching the road"],
        "Hands-free restrictions vary, but handheld use is broadly banned for CMV drivers.",
        [
            "Not required.",
            "Boredom ≠ permission.",
            "Eyes/mind on driving.",
        ],
        "easy",
    ),
    (
        "Alcohol possession/use rules for passenger CDL drivers are:",
        "Strict—alcohol misuse endangers passengers and violates FMCSA alcohol rules",
        ["Looser than for freight drivers always", "Allow drinking in the aisle with riders", "Permit driving with open containers for passengers and driver alike casually"],
        "Passenger safety plus federal alcohol testing rules demand zero impairment.",
        [
            "Rules are not looser for passenger ops.",
            "Driver drinking is forbidden.",
            "Open container policies are strict; drivers must not be impaired.",
        ],
        "medium",
    ),
    (
        "Towing or pushing a bus with riders aboard is generally:",
        "Prohibited / highly unsafe",
        ["Standard practice every morning", "Required by endorsement rules", "Safe if done at highway speed"],
        "Mechanical recovery should not expose passengers to uncontrolled motion risks.",
        [
            "Not standard with passengers.",
            "Not required.",
            "Speed worsens danger.",
        ],
        "medium",
    ),
    (
        "Leaving the driver’s seat without securing the bus (brake set, etc.) when passengers are aboard can be:",
        "Unsafe and often prohibited unless proper precautions are taken",
        ["Always required every minute", "Fine if the bus is in gear rolling", "Encouraged during railroad crossings on the tracks"],
        "Prevent rollaways; know attendance/securement rules for your operation.",
        [
            "Not required to leave constantly.",
            "Rolling is dangerous.",
            "Never leave a bus on tracks.",
        ],
        "medium",
    ),
    (
        "Refusing to yield to emergency vehicles is:",
        "Illegal and especially dangerous with a busload of passengers",
        ["Required to stay on schedule", "Optional based on mood", "Only for cars, not buses"],
        "Move right and stop when safe; don’t block intersections.",
        [
            "Schedule yields to emergencies.",
            "Law isn’t optional.",
            "Buses must yield too.",
        ],
        "easy",
    ),
    (
        "Carrying unauthorized hazardous materials on a passenger bus is:",
        "Prohibited / tightly restricted—passenger operations are not general hazmat freighters",
        ["Encouraged to make extra money", "Allowed if unlabeled", "Required for P endorsement practice"],
        "P endorsement knowledge stresses limits on hazardous cargo with passengers.",
        [
            "Don’t freelance hazmat.",
            "Unlabeled hazmat is worse.",
            "Not a training requirement to haul forbidden hazmat.",
        ],
        "hard",
    ),
    (
        "Allowing passengers to ride outside or on steps while moving is:",
        "Prohibited",
        ["Allowed below 20 mph", "A fun tour feature", "Required when the bus is full"],
        "Everyone must be inside the passenger compartment as designed.",
        [
            "Any speed is unsafe outside.",
            "Not entertainment.",
            "Capacity rules don’t allow exterior riding.",
        ],
        "easy",
    ),
    (
        "Falsifying inspection or hours records is:",
        "Illegal and can disqualify drivers",
        ["A best practice for dispatch", "Required if late", "Harmless paperwork art"],
        "Honesty in safety records protects lives and careers.",
        [
            "Fraud is not best practice.",
            "Lateness doesn’t justify fraud.",
            "Paperwork fraud is serious.",
        ],
        "medium",
    ),
    (
        "Excessive speeding in a passenger bus is prohibited because:",
        "Stopping distance and crash severity rise dramatically with speed and load",
        ["Buses stop shorter at higher speeds", "Speed limits never apply to CDL holders", "Passengers cushion impacts usefully"],
        "Obey limits and conditions; human cargo raises stakes.",
        [
            "Stopping distance increases with speed.",
            "CDL holders must obey limits.",
            "Passengers are not crumple zones.",
        ],
        "easy",
    ),
    (
        "Driving while ill or fatigued to the point of unsafe operation is:",
        "Prohibited—out-of-service illness/fatigue rules protect the public",
        ["Heroic and required", "Only a problem for nighttime runs", "Cured by energy drinks alone as compliance"],
        "Fitness for duty includes rest and health.",
        [
            "Heroics don’t make it legal/safe.",
            "Fatigue matters anytime.",
            "Stimulants aren’t a substitute for rest/compliance.",
        ],
        "medium",
    ),
    (
        "Blocking a railroad crossing with a bus because you entered without enough clearance is:",
        "Extremely dangerous and must be avoided by ensuring space to clear fully before starting across",
        ["Acceptable if you honk", "Required when late", "Safe if gates are down behind you"],
        "Never start across unless you can fully clear the tracks.",
        [
            "Honking doesn’t move trains.",
            "Schedule ≠ clearance.",
            "Gates down means stay off.",
        ],
        "hard",
    ),
    (
        "Using radar detectors in a CMV where prohibited is:",
        "Against FMCSA rules for CMVs in interstate commerce",
        ["Required equipment", "A substitute for safe speed", "Mandated by passenger endorsements"],
        "Radar detectors are banned in CMVs federally; drive the limit.",
        [
            "Not required.",
            "Not a safety system.",
            "Not mandated by P tests.",
        ],
        "hard",
    ),
    (
        "Discourteous or reckless maneuvers (e.g., passing on the shoulder with a loaded bus) are:",
        "Unsafe, often illegal, and inconsistent with passenger carrier responsibilities",
        ["Professional driving standards", "Required to make up time", "Encouraged in CDL manuals"],
        "Professional passenger service demands defensive, lawful driving.",
        [
            "Not professional.",
            "Time pressure ≠ permission.",
            "Manuals teach safety, not recklessness.",
        ],
        "easy",
    ),
]


def main() -> None:
    write_bank(
        "cdl-passenger-readiness-check",
        {
            "vehicle-inspection": INSPECTION,
            "loading-passengers": LOADING,
            "driving-rail": DRIVING_RAIL,
            "prohibited": PROHIBITED,
        },
    )


if __name__ == "__main__":
    main()
