#!/usr/bin/env python3
"""CDL HazMat endorsement readiness bank — 60Q."""

from write_helper import write_bank

CLASSES = [
    (
        "Hazard Class 3 covers which materials?",
        "Flammable liquids",
        ["Explosives only (Class 1)", "Gases only (Class 2)", "Corrosives only (Class 8)"],
        "DOT classes: 1 explosives, 2 gases, 3 flammable liquids, 8 corrosives, etc.",
        [
            "Class 1 is explosives.",
            "Class 2 is gases.",
            "Class 8 is corrosives.",
        ],
        "easy",
    ),
    (
        "A placard is primarily used to:",
        "Communicate the hazard of materials on a vehicle to emergency responders and the public",
        ["Replace shipping papers entirely in all cases", "Increase fuel economy", "Act as a vehicle registration sticker"],
        "Placards provide hazard communication; shipping papers remain required documentation.",
        [
            "Shipping papers are still required.",
            "Placards do not improve MPG.",
            "Registration is separate.",
        ],
        "easy",
    ),
    (
        "Where must shipping papers for hazardous materials typically be kept while driving?",
        "Within immediate reach of the driver / readily available (often on the seat or in a holder) when the driver is at the controls",
        ["Locked in an inaccessible trailer toolbox only", "Left at home for safety", "Mailed to the consignee before departure only"],
        "Emergency responders must be able to access shipping papers quickly.",
        [
            "Inaccessible storage defeats emergency use.",
            "Papers must travel with the shipment.",
            "Consignee gets delivery docs; driver needs papers en route.",
        ],
        "easy",
    ),
    (
        "The hazardous materials identification number on shipping papers and placards is commonly a:",
        "Four-digit UN/NA number",
        ["Two-letter state code only", "Driver license number", "Fuel receipt number"],
        "UN/NA numbers identify specific materials for emergency response.",
        [
            "State codes identify jurisdictions.",
            "CDL numbers identify drivers.",
            "Fuel receipts are unrelated.",
        ],
        "easy",
    ),
    (
        "Division 1.1 explosives are characterized as:",
        "Mass explosion hazard",
        ["No hazard whatsoever", "Only combustible solids like Class 4.1 always", "Only infectious substances"],
        "1.1 = mass explosion; other 1.x divisions have different explosive hazards.",
        [
            "Explosives are hazardous.",
            "4.1 is flammable solids.",
            "Division 6.2 is infectious.",
        ],
        "medium",
    ),
    (
        "Which placard color is classically associated with flammable liquids (Class 3)?",
        "Red",
        ["White with black stripes only for all classes", "Blue only for all flammables", "All-green for flammable liquids"],
        "Class 3 flammable placards are red; other classes use different color patterns.",
        [
            "Stripes appear on certain placards (e.g., dangerous when wet variants), not as the Class 3 standard.",
            "Blue is associated with dangerous when wet (4.3) among others.",
            "Green relates to non-flammable gas (2.2).",
        ],
        "medium",
    ),
    (
        "The Emergency Response Guidebook (ERG) is used to:",
        "Provide initial isolation/evacuation and fire/spill guidance for hazmat incidents",
        ["Replace CDL skills testing", "Set fuel tax rates", "Calculate payroll"],
        "ERG guides first responders and drivers on immediate protective actions.",
        [
            "Skills tests are separate.",
            "Tax policy is unrelated.",
            "Payroll is unrelated.",
        ],
        "easy",
    ),
    (
        "A 'Dangerous' placard may be used when:",
        "Non-bulk packages of two or more hazard categories require placarding and table rules allow the dangerous placard instead of multiple placards",
        ["Any single gallon of milk is shipped", "Only when carrying Class 7 exclusively always", "In place of all shipping papers"],
        "Dangerous placard rules are specific aggregation/placarding table exceptions—not a universal substitute.",
        [
            "Foodstuffs generally are not hazmat.",
            "Class 7 has specific radioactive placarding.",
            "Papers are still required.",
        ],
        "hard",
    ),
    (
        "Hazard Class 8 materials are:",
        "Corrosives",
        ["Explosives", "Flammable gases only", "Miscellaneous only (Class 9)"],
        "Class 8 = corrosives; Class 9 = miscellaneous hazardous materials.",
        [
            "Explosives are Class 1.",
            "Flammable gases are Division 2.1.",
            "Class 9 is miscellaneous.",
        ],
        "easy",
    ),
    (
        "On shipping papers, the basic description of a hazardous material generally includes:",
        "Identification number, proper shipping name, hazard class/division, and packing group (when assigned)",
        ["Only the driver’s nickname", "Only the truck color", "Only the fuel brand"],
        "The basic description sequence is standardized for clarity in emergencies.",
        [
            "Nicknames are not shipping descriptions.",
            "Paint color is irrelevant.",
            "Fuel brand is irrelevant.",
        ],
        "medium",
    ),
    (
        "Packing Group I indicates:",
        "Great danger (highest degree of danger among I/II/III when assigned)",
        ["Least danger always", "No hazard", "Radioactivity only"],
        "PG I = high danger; PG II = medium; PG III = minor danger (when packing groups apply).",
        [
            "PG III is lesser danger.",
            "PG assignment implies hazard.",
            "Radioactive materials use Class 7 controls.",
        ],
        "medium",
    ),
    (
        "Which material class includes flammable solids?",
        "Class 4 (e.g., 4.1 flammable solids)",
        ["Class 3 only", "Class 8 only", "Class 2.2 only"],
        "Class 4 covers flammable solids, spontaneously combustible, and dangerous when wet divisions.",
        [
            "Class 3 is flammable liquids.",
            "Class 8 is corrosives.",
            "2.2 is non-flammable gas.",
        ],
        "medium",
    ),
    (
        "A square-on-point display on a package typically indicates:",
        "A hazard warning label for the packaged hazmat",
        ["That the box is empty of all meaning", "That shipping papers are optional", "That the product is always food-grade"],
        "Diamond labels communicate package hazards; vehicle placards are larger related marks.",
        [
            "Labels convey meaning.",
            "Papers remain required when applicable.",
            "Hazmat is not defined as food-grade.",
        ],
        "easy",
    ),
    (
        "Division 2.3 refers to:",
        "Poison (toxic) gases",
        ["Flammable liquids", "Corrosive solids only", "ORM-D consumer commodities only historically as 2.3"],
        "2.1 flammable gas, 2.2 non-flammable gas, 2.3 poison gas.",
        [
            "Flammable liquids are Class 3.",
            "Corrosives are Class 8.",
            "ORM-D was a different limited-quantity concept.",
        ],
        "hard",
    ),
    (
        "Who is responsible for ensuring hazmat is properly classified and described before offering shipment?",
        "The shipper (with carrier responsibilities for acceptance/transport compliance)",
        ["Only random bystanders", "Only fuel station attendants always", "Only weather forecasters"],
        "Shippers classify/package/mark/label/describe; carriers verify before transport and comply en route.",
        [
            "Bystanders are not responsible parties.",
            "Fueling is separate.",
            "Weather is separate.",
        ],
        "medium",
    ),
]

LOADING = [
    (
        "Incompatible hazardous materials must be:",
        "Segregated according to segregation tables so they do not react dangerously if released",
        ["Always mixed to save space", "Stacked with food without barriers when leaking", "Loaded with no regard to class"],
        "Segregation prevents dangerous interactions (e.g., acids with cyanides).",
        [
            "Mixing incompatibles is dangerous.",
            "Food contamination rules are strict.",
            "Class matters for segregation.",
        ],
        "easy",
    ),
    (
        "When loading packages of hazmat, you should:",
        "Protect packages from damage, secure them against movement, and follow orientation marks",
        ["Throw boxes to speed loading", "Ignore 'this side up' arrows", "Place heavy items on fragile hazmat without care"],
        "Package integrity and securement prevent leaks and incidents.",
        [
            "Impact damages packages.",
            "Orientation marks matter.",
            "Crushing causes releases.",
        ],
        "easy",
    ),
    (
        "Cargo heaters / burning heaters around certain hazmat are restricted because:",
        "Heat/ignition sources can trigger fire or explosion with flammables/explosives",
        ["Heat always makes corrosives safer", "Heat removes all placarding duties", "Heat sterilizes Class 7 automatically"],
        "Ignition control is critical near flammables and explosives.",
        [
            "Heat can worsen many hazards.",
            "Placarding rules remain.",
            "Radioactives are not 'sterilized' by heaters.",
        ],
        "medium",
    ),
    (
        "Bulk packages vs non-bulk packages differ primarily by:",
        "Capacity thresholds defined in the HMR (e.g., bulk generally larger capacities)",
        ["Color of the truck only", "Driver age only", "Whether a CDL exists in another state only"],
        "HMR define bulk vs non-bulk by volume/weight capacity criteria.",
        [
            "Paint is irrelevant.",
            "Age is credentialing, not packaging class.",
            "Licensure state is separate.",
        ],
        "medium",
    ),
    (
        "Before loading Class 1 explosives, a driver should ensure:",
        "The vehicle is appropriate, free of ignition hazards, and loaded per quantity/segregation rules",
        ["The trailer is full of loose oily rags next to detonators for cushioning", "Smoking is done inside the cargo area", "Shipping papers are discarded"],
        "Explosives demand strict fire control and compliance.",
        [
            "Ignition sources are forbidden hazards.",
            "No smoking with explosives.",
            "Papers required.",
        ],
        "easy",
    ),
    (
        "Floor of a vehicle used for hazmat should be:",
        "Clean, in good condition, and free of nails/screws that could puncture packages",
        ["Covered in spilled product intentionally", "Soft mud only", "Littered with broken glass for traction"],
        "Puncture and contamination risks must be controlled before loading.",
        [
            "Spills must be cleaned.",
            "Mud is uncontrolled contamination.",
            "Glass damages packages.",
        ],
        "easy",
    ),
    (
        "Segregation of acids and cyanides is critical because together they can:",
        "Release toxic hydrogen cyanide gas",
        ["Form harmless table salt only always", "Cancel each other’s placards legally", "Become Class 9 automatically and safe"],
        "Acid + cyanide can liberate HCN—classic incompatible pair.",
        [
            "Not a neutralization to safety in cargo practice.",
            "Placards don’t cancel chemistry.",
            "Reaction products are not 'safe Class 9'.",
        ],
        "hard",
    ),
    (
        "When loading tanks, manhole covers and valves should be:",
        "Closed and secured per procedures; check for leaks",
        ["Left open for ventilation while driving highway speeds with liquid load always", "Removed and stored at home", "Loosely chained so they rattle"],
        "Containment integrity prevents releases during transit.",
        [
            "Open manholes risk spills/vapors.",
            "Hardware stays with the tank.",
            "Loose fittings leak.",
        ],
        "medium",
    ),
    (
        "Packages labeled 'Toxic' should be loaded:",
        "Away from foodstuffs and per segregation/separation rules",
        ["On top of employee lunches intentionally", "Mixed into the sleeper berth bedding", "Opened to 'air out' while driving"],
        "Poison/toxic materials can contaminate food and living spaces.",
        [
            "Food contamination is prohibited/dangerous.",
            "Sleeper contamination endangers the driver.",
            "Do not open packages in transit.",
        ],
        "medium",
    ),
    (
        "A leaking hazmat package discovered during loading should be:",
        "Not loaded; protect people, contain if trained/safe, and notify appropriate parties",
        ["Loaded quickly to hide the leak", "Punctured more to equalize pressure", "Given to hitchhikers"],
        "Do not accept damaged/leaking packages; follow emergency and carrier procedures.",
        [
            "Hiding leaks is illegal/unsafe.",
            "Worsening damage is wrong.",
            "Public exposure is wrong.",
        ],
        "easy",
    ),
    (
        "For placarded loads, certain railroad crossings require:",
        "Stopping (with exceptions) before crossing, listening, and proceeding only when safe—per hazmat/rail rules taught in CDL manuals",
        ["Racing across without looking", "Never using brakes near tracks", "Turning off flashers required by law for visibility always as the only step"],
        "Placarded loads have heightened rail-crossing precautions in training materials/regs.",
        [
            "Speed without caution is unsafe.",
            "Brakes are needed to stop.",
            "Observation/stop rules are the key control.",
        ],
        "medium",
    ),
    (
        "Doubling up incompatible compressed gas cylinders loosely is unsafe because:",
        "Damaged valves/releases can create fire, asphyxiation, or toxic exposure risks",
        ["Gases always cancel hazards when mixed in cargo", "Cylinders cannot leak by design ever", "Segregation rules never apply to gases"],
        "Secure and segregate gas cylinders; protect valves.",
        [
            "Mixing hazards can worsen outcomes.",
            "Cylinders can fail/leak.",
            "Gas segregation rules exist.",
        ],
        "hard",
    ),
    (
        "Orientation arrows on packages mean:",
        "Keep package upright as marked unless rules allow otherwise",
        ["Turn the package upside down intentionally", "Arrows are decorative only", "Arrows replace UN numbers"],
        "Liquid closures and vents may depend on upright orientation.",
        [
            "Inverting can cause leaks.",
            "Marks are functional.",
            "UN numbers remain required.",
        ],
        "easy",
    ),
    (
        "When carrying hazmat and food products together, you must:",
        "Comply with contamination prevention and separation rules; some combinations are forbidden",
        ["Always place poisons directly on produce", "Ignore all food rules if the trailer is refrigerated", "Use food as absorbent for spills"],
        "Food contamination prohibitions are strict for poisons and certain hazmats.",
        [
            "Direct contact is forbidden/dangerous.",
            "Refrigeration does not waive contamination rules.",
            "Food is not spill absorbent.",
        ],
        "medium",
    ),
    (
        "Securement of hazmat cargo is important because movement can:",
        "Damage packages, open closures, and cause spills or reactions",
        ["Improve classification accuracy", "Remove the need for CDL endorsements", "Automatically upgrade packing groups to safer levels"],
        "Load securement is a core prevention control.",
        [
            "Securement ≠ classification.",
            "Endorsements remain required.",
            "PG does not change from straps.",
        ],
        "easy",
    ),
]

DRIVING = [
    (
        "If hazmat is leaking while you are driving and it is safe to do so, you should:",
        "Park away from people/ignition sources when possible, secure the scene, keep people away, and notify emergency/carrier contacts",
        ["Drive faster to the next city to hide it", "Ignore it if the smell is strong", "Smoke near the leak to test flammability"],
        "Protect life and limit ignition/exposure; use ERG/carrier emergency procedures.",
        [
            "Continuing can worsen release/exposure.",
            "Strong smell may mean danger.",
            "Never introduce ignition.",
        ],
        "easy",
    ),
    (
        "Tire fires on placarded vehicles are dangerous because:",
        "Heat can involve the cargo and cause a larger fire/explosion/toxic release",
        ["Tires cannot burn near hazmat", "Hazmat always extinguishes tire fires", "You should always puncture the cargo tank to cool tires"],
        "Stop/address tire issues early; cargo involvement escalates incidents.",
        [
            "Tires can burn regardless.",
            "Cargo may fuel fire.",
            "Puncturing tanks is extremely dangerous.",
        ],
        "medium",
    ),
    (
        "In a hazmat emergency, the shipping papers and ERG help you:",
        "Identify material hazards and initial protective distances/actions",
        ["Calculate employee bonuses", "Reset the odometer legally", "Cancel environmental laws"],
        "Identification drives correct isolation and notification.",
        [
            "Not HR math.",
            "Not odometer related.",
            "Laws still apply.",
        ],
        "easy",
    ),
    (
        "Parking a vehicle with Division 1.1/1.2 explosives near an open fire is:",
        "Prohibited / extremely unsafe",
        ["Required for warming the load", "Recommended to dry packages", "Allowed if you remain in the sleeper"],
        "Keep explosives away from fire/ignition sources and follow distance/parking rules.",
        [
            "Never warm explosives with open flame.",
            "Drying with fire is insane.",
            "Presence in sleeper does not make it safe.",
        ],
        "easy",
    ),
    (
        "If you break down with hazmat on a highway, you should:",
        "Warn others, set out emergency triangles as required, and call for assistance—do not leave the scene unprotected",
        ["Abandon the vehicle unmarked at night on a curve", "Siphon product onto the roadway to lighten the load", "Invite the public to sample the cargo"],
        "Traffic control and notification reduce secondary crashes and exposures.",
        [
            "Unmarked vehicles cause crashes.",
            "Releasing product is a spill crime/hazard.",
            "Public exposure is wrong.",
        ],
        "medium",
    ),
    (
        "Smoking around Class 3 flammable liquids is:",
        "Forbidden due to ignition risk",
        ["Required before dipping a tank", "Safe if you use matches not lighters", "Encouraged to detect leaks by flame"],
        "No smoking/open flame near flammables.",
        [
            "Never introduce ignition to check tanks casually.",
            "Any flame source is a risk.",
            "Flame testing leaks is dangerous.",
        ],
        "easy",
    ),
    (
        "When contacting emergency responders about a spill, prioritize giving:",
        "Location, material identity/UN number if known, quantity/conditions, and injuries/hazards observed",
        ["Your favorite sports team", "Only the trailer paint code", "A guess without checking papers when papers are available"],
        "Accurate identity and location enable correct response.",
        [
            "Irrelevant personal info wastes time.",
            "Paint code is useless.",
            "Use papers/placards when available.",
        ],
        "medium",
    ),
    (
        "A white 'toxic inhalation hazard' concern means responders should:",
        "Emphasize respiratory protection and isolation downwind per ERG guidance",
        ["Ignore wind direction", "Assume the material is always harmless air", "Use water streams randomly without guidance always"],
        "TIH materials demand atmospheric precautions; follow ERG/specialist advice.",
        [
            "Wind drives vapor travel.",
            "TIH is not harmless.",
            "Tactics must match the material.",
        ],
        "hard",
    ),
    (
        "Fires involving water-reactive materials (4.3) may worsen if you:",
        "Apply water inappropriately, generating flammable/toxic gases",
        ["Only use the correct extinguishing method from guidance", "Evacuate as directed", "Shut off ignition sources when safe"],
        "Water can react violently with some materials—use ERG/specialist methods.",
        [
            "Correct agents are appropriate.",
            "Evacuation is often right.",
            "Ignition control helps.",
        ],
        "hard",
    ),
    (
        "After a minor non-threatening fueling splash of diesel on skin, general first action is:",
        "Remove contaminated clothing as needed and wash skin with soap/water; seek care if irritation persists",
        ["Inject the diesel", "Ignite the clothing to burn it off", "Drink solvent to 'neutralize'"],
        "Decontaminate skin; avoid absurd harmful 'remedies'.",
        [
            "Never inject fuels.",
            "Ignition causes burns.",
            "Do not ingest solvents.",
        ],
        "medium",
    ),
    (
        "Route restrictions for certain hazmat exist to:",
        "Keep high-risk loads away from tunnels, bridges, or densely populated preferred routes as required",
        ["Shorten all deliveries regardless of law", "Avoid weigh stations only for fun", "Eliminate the need for placards"],
        "Follow designated/preferred routes and prohibitions for the material and jurisdiction.",
        [
            "Illegal shortcuts are not allowed.",
            "Weigh rules still apply.",
            "Placards remain required when applicable.",
        ],
        "medium",
    ),
    (
        "If shipping papers and placards disagree, you should:",
        "Not move the shipment until discrepancies are resolved with shipper/carrier procedures",
        ["Always trust the prettier placard and leave", "Invent a new UN number", "Cover placards with duct tape and go"],
        "Identification must be accurate before transport continues.",
        [
            "Resolve conflicts properly.",
            "Never invent IDs.",
            "Covering placards is illegal.",
        ],
        "hard",
    ),
    (
        "Emergency response information on/with shipping papers must be:",
        "Available for the materials transported (e.g., ERG pages or equivalent emergency info)",
        ["Optional poetry", "Only a blank page", "Stored exclusively overseas"],
        "Emergency response information is required to accompany hazmat shipments.",
        [
            "Must be usable emergency info.",
            "Blank pages fail the requirement.",
            "Must be available with the shipment.",
        ],
        "medium",
    ),
    (
        "When evacuating an area for a hazmat release, a key principle is:",
        "Move people upwind / to safe distances per guidance and keep them away from vapors",
        ["Gather crowds at the leak for photos", "Shelter inside the vapor cloud", "Drive through the spill to 'disperse' it"],
        "Protect by distance, wind direction, and denying entry.",
        [
            "Spectators create more victims.",
            "Vapor clouds are dangerous.",
            "Driving through spreads contamination/risk.",
        ],
        "easy",
    ),
    (
        "A driver who discovers a suspected radioactive package with damaged integrity should:",
        "Minimize time near the package, maximize distance/shielding, isolate the area, and notify authorities/carrier",
        ["Open it to inspect the contents closely for a long time", "Carry fragments in a pocket", "Ignore radiation symbols"],
        "Time-distance-shielding and expert response apply to radiological concerns.",
        [
            "Close prolonged inspection increases dose.",
            "Do not pocket contamination.",
            "Symbols must be heeded.",
        ],
        "hard",
    ),
]

SECURITY = [
    (
        "Hazmat security awareness training is required so employees can:",
        "Recognize and reduce security risks such as theft, tampering, or terrorism targeting hazmat",
        ["Ignore suspicious activity", "Disable locks for convenience", "Post tank access codes publicly"],
        "Security plans/awareness reduce intentional misuse of hazardous materials.",
        [
            "Reporting is part of awareness.",
            "Locks protect access.",
            "Public codes defeat security.",
        ],
        "easy",
    ),
    (
        "A suspicious person photographing a chlorine tank terminal for no legitimate reason should prompt:",
        "Reporting to security/law enforcement per site procedures",
        ["Giving them valve keys", "Inviting them into restricted areas", "Helping them climb the tank"],
        "Unusual surveillance of hazmat sites is a reportable security concern.",
        [
            "Never assist unauthorized access.",
            "Restricted areas stay restricted.",
            "Climbing tanks is unauthorized/dangerous.",
        ],
        "easy",
    ),
    (
        "Selective transportation security measures for certain high-risk hazmat include:",
        "Enhanced security plans, attendance/securement, and route/communication practices as required",
        ["Leaving loaded explosives trucks unlocked downtown overnight intentionally", "Removing all seals from high-risk loads for convenience", "Posting shipment schedules of high-risk loads on public social media"],
        "Higher-risk materials trigger stronger security plan requirements.",
        [
            "Unsecured high-risk loads are forbidden practice.",
            "Seals help detect tampering.",
            "Publicizing details increases risk.",
        ],
        "medium",
    ),
    (
        "Enroute security includes:",
        "Minimizing stops, locking vehicles, and being aware of tailing or tampering",
        ["Picking up unknown hitchhikers into the cargo area", "Leaving keys in the ignition at every truck stop", "Discussing load contents loudly with strangers"],
        "Reduce opportunities for theft/hijack of hazmat.",
        [
            "Unknown persons are a risk.",
            "Control keys.",
            "Need-to-know protects information.",
        ],
        "medium",
    ),
    (
        "A broken cargo seal that you did not expect may indicate:",
        "Possible tampering—follow company procedures, document, and report before proceeding blindly",
        ["Automatic proof the load is safer", "A reason to ignore inventory checks", "Permission to remove remaining seals"],
        "Seal integrity is a security control; anomalies need response.",
        [
            "Broken seals raise concern.",
            "Checks matter more, not less.",
            "Do not remove evidence/controls casually.",
        ],
        "medium",
    ),
    (
        "CDL hazmat endorsement generally requires:",
        "TSA security threat assessment / fingerprint-based background check process (as applicable) plus knowledge testing",
        ["Only a verbal promise with no vetting", "No identification documents ever", "Only a forklift wallet card"],
        "Federal security threat assessment is part of hazmat endorsement issuance.",
        [
            "Vetting is required.",
            "ID is required.",
            "Forklift cards are unrelated.",
        ],
        "easy",
    ),
    (
        "Employees should report threats or suspicious purchases of precursors when:",
        "Behavior suggests planning to misuse hazardous materials",
        ["Never, because reporting is discouraged", "Only after an explosion has occurred", "Only if the person is a friend"],
        "Early reporting can prevent incidents; follow company/law enforcement channels.",
        [
            "Reporting is encouraged appropriately.",
            "Prevention beats aftermath.",
            "Relationship does not bar reporting crimes.",
        ],
        "medium",
    ),
    (
        "Access to hazmat storage areas should be:",
        "Limited to authorized personnel with controls (locks, badges, escorts as required)",
        ["Open to the public 24/7", "Shared on a flyer with gate codes", "Available to anyone who asks politely once"],
        "Physical access control is a core security measure.",
        [
            "Public access is inappropriate.",
            "Codes must be protected.",
            "Politeness ≠ authorization.",
        ],
        "easy",
    ),
    (
        "Which communication practice is more secure for high-risk load details?",
        "Need-to-know sharing over secure company channels",
        ["Broadcasting UN numbers and routes on public CB for entertainment", "Posting manifests on public forums", "Texting strangers the gate code"],
        "Limit sensitive logistics details to authorized parties.",
        [
            "Public radio spreads targeting info.",
            "Public posts are insecure.",
            "Gate codes are sensitive.",
        ],
        "hard",
    ),
    (
        "Vehicle attendance requirements for certain explosives/hazmat mean:",
        "Someone qualified may need to attend the vehicle / keep it within view per the specific rule set",
        ["The vehicle can always be abandoned for days with keys in it", "Attendance is never required for any Class 1", "Attendance means watching TV at home while the truck is downtown"],
        "Attendance/surveillance rules reduce theft and unauthorized access—know the material-specific requirements.",
        [
            "Abandonment violates attendance rules.",
            "Some Class 1 loads have strict attendance rules.",
            "Attendance means with the vehicle as defined.",
        ],
        "hard",
    ),
    (
        "If you suspect your placarded load is being followed by an unknown vehicle engaging in hostile surveillance, you should:",
        "Avoid confrontation, note details, and contact law enforcement/carrier security per procedure",
        ["Ram the vehicle immediately as first step always", "Stop in a deserted area to confront them alone", "Hand over the shipping papers to the unknown driver"],
        "Personal safety and reporting beat vigilantism.",
        [
            "Violence escalates danger.",
            "Isolation favors attackers.",
            "Do not surrender docs to unknowns.",
        ],
        "medium",
    ),
    (
        "Tamper-evident devices help by:",
        "Showing whether unauthorized access to cargo may have occurred",
        ["Increasing payload weight illegally", "Replacing driver training", "Eliminating the need for locks entirely"],
        "Seals complement locks; they detect intrusion attempts.",
        [
            "Not a weight scheme.",
            "Training remains required.",
            "Locks still matter.",
        ],
        "easy",
    ),
    (
        "A security plan for hazmat employers typically addresses:",
        "Personnel security, unauthorized access, and en-route security measures",
        ["Only cafeteria menus", "Only paint colors of offices", "Only vacation photos"],
        "Plans systematically reduce risks of theft/misuse.",
        [
            "Menus are irrelevant.",
            "Decor is irrelevant.",
            "Photos are irrelevant.",
        ],
        "medium",
    ),
    (
        "Carrying unauthorized passengers or allowing unknown persons into the cargo area of a hazmat load is:",
        "A serious security and safety violation",
        ["Recommended for hospitality", "Required by placarding rules", "A substitute for shipping papers"],
        "Control of the vehicle and cargo is fundamental security.",
        [
            "Hospitality ≠ security.",
            "Placards do not require strangers aboard.",
            "Papers are separate requirements.",
        ],
        "easy",
    ),
    (
        "Which action best supports both safety and security at delivery?",
        "Verify receiver authorization, check seals/IDs per procedure, and document exceptions",
        ["Leave the trailer unlocked on a street corner for 'whoever claims it'", "Accept a verbal 'I'm from the company' with no verification for high-risk loads", "Remove placards before arrival to avoid attention while still loaded"],
        "Identity verification and documentation prevent diversion.",
        [
            "Uncontrolled delivery enables theft.",
            "Verify identity.",
            "Placards stay until unload rules allow removal.",
        ],
        "hard",
    ),
]


def main() -> None:
    write_bank(
        "cdl-hazmat-readiness-check",
        {
            "classes-placards": CLASSES,
            "loading-segregation": LOADING,
            "driving-emergencies": DRIVING,
            "security-rules": SECURITY,
        },
    )


if __name__ == "__main__":
    main()
