/** NIC Cosmetology theory — 60 curated MCQs (15×4) */
export const topics = {
  "science-safety": [
    [
      "Bacteria that cause disease are called:",
      "Pathogenic",
      ["Nonpathogenic only by definition", "Saprophytes that only help", "Viruses exclusively"],
      "Pathogenic microorganisms cause infection/disease; nonpathogenic are typically harmless or beneficial.",
      [
        "Nonpathogenic are not disease-causing by definition.",
        "Saprophytes live on dead matter; not the term asked.",
        "Bacteria and viruses are different.",
      ],
      "easy",
    ],
    [
      "The body’s first line of defense against infection includes:",
      "Healthy unbroken skin",
      [
        "Ignoring handwashing",
        "Sharing needles in the salon",
        "Working with open bleeding wounds uncovered on clients",
      ],
      "Intact skin is a primary barrier; salon pros protect skin integrity.",
      [
        "Handwashing supports defense.",
        "Sharing needles spreads bloodborne disease.",
        "Open wounds need covering/referral.",
      ],
      "easy",
    ],
    [
      "A disinfectant used in salons must be:",
      "EPA-registered and used according to the label for the claimed pathogens",
      [
        "Any household cleaner sprayed briefly without contact time",
        "Soap and water alone for metal implements that require disinfection",
        "Perfume to mask odors instead of disinfection",
      ],
      "Contact time, concentration, and EPA registration matter for legally proper disinfection.",
      [
        "Insufficient contact time fails disinfection.",
        "Cleaning precedes disinfection; soap alone isn’t hospital-level disinfection for many implements.",
        "Fragrance is not disinfection.",
      ],
      "medium",
    ],
    [
      "Cleaning (sanitation in older wording) differs from disinfection in that cleaning:",
      "Removes visible debris and reduces microbes but does not kill all pathogens like disinfection steps",
      [
        "Always sterilizes to surgical zero",
        "Is illegal in salons",
        "Replaces the need for any disinfectant forever",
      ],
      "Multi-step infection control: clean, then disinfect (or sterilize when required).",
      [
        "Sterilization is a higher process.",
        "Cleaning is required.",
        "Disinfection still needed for many tools.",
      ],
      "medium",
    ],
    [
      "Sterilization:",
      "Destroys all microbial life including spores (typically via autoclave methods in appropriate settings)",
      [
        "Is the same as dusting a station",
        "Is achieved by a quick wipe with alcohol on hair",
        "Means storing tools in an open drawer",
      ],
      "Most salon implements are disinfected rather than sterilized; know the distinction for exams.",
      [
        "Dusting is cleaning.",
        "Alcohol wipe ≠ sterilization.",
        "Open storage can contaminate.",
      ],
      "medium",
    ],
    [
      "OSHA is primarily concerned with:",
      "Workplace safety and health of employees",
      [
        "Setting state cosmetology practical exam scores only",
        "Issuing beauty magazine ratings",
        "Approving haircut fashion trends",
      ],
      "OSHA covers bloodborne pathogens, hazard communication, SDS access, etc.",
      [
        "State boards regulate licensing exams.",
        "Not OSHA’s role.",
        "Not OSHA’s role.",
      ],
      "easy",
    ],
    [
      "A Safety Data Sheet (SDS) provides:",
      "Hazard, handling, and emergency information about chemical products",
      [
        "Client fashion preferences",
        "State board license numbers only",
        "Appointment book templates",
      ],
      "SDS access is required for salon chemicals under Hazard Communication.",
      [
        "Not fashion.",
        "Not license lists.",
        "Not scheduling.",
      ],
      "easy",
    ],
    [
      "pH of hair and skin is generally:",
      "Slightly acidic",
      ["Strongly alkaline like oven cleaner", "Neutral exactly 10", "pH 0 always"],
      "Acid mantle (~4.5–5.5) protects; strong alkalinity swells cuticle.",
      [
        "Strong alkali damages.",
        "pH 10 is alkaline.",
        "pH 0 is extremely acidic.",
      ],
      "easy",
    ],
    [
      "An alkaline permanent wave solution primarily:",
      "Raises cuticle and breaks disulfide bonds to reform a new shape when processed/neutralized properly",
      [
        "Only adds shine without chemical change",
        "Dyes hair permanently with pigment molecules only",
        "Disinfects implements",
      ],
      "Perm chemistry involves reduction of disulfide bonds; neutralization reforms bonds.",
      [
        "Chemical restructuring occurs.",
        "Color is different chemistry.",
        "Not a disinfectant step for tools.",
      ],
      "hard",
    ],
    [
      "Hydrogen peroxide in haircolor developers acts as:",
      "An oxidizing agent that helps swell the cuticle and develop color",
      [
        "A reducing agent identical to thio",
        "A pure conditioner oil",
        "A sterilant for skin",
      ],
      "Volume of developer relates to lift capacity; misuse causes damage/burns.",
      [
        "Thio is a reducer in perms/relaxers contexts differently.",
        "Not merely oil.",
        "Not for skin sterilization.",
      ],
      "medium",
    ],
    [
      "Blood exposure incident procedure includes:",
      "Stop service, glove, clean, apply antiseptic/bandage as appropriate, disinfect station, document per rules",
      [
        "Continue cutting and ignore bleeding",
        "Use the same tissue on multiple clients",
        "Pour leftover color into the wound",
      ],
      "State board blood exposure protocols protect client and licensee.",
      [
        "Must stop and address exposure.",
        "Single-use materials.",
        "Chemicals do not treat wounds.",
      ],
      "medium",
    ],
    [
      "UV sanitizers in salons typically:",
      "Store already cleaned/disinfected tools; they are not a substitute for proper disinfection alone in many rules",
      [
        "Replace EPA disinfection completely in all states always",
        "Sterilize tools in 5 seconds guaranteed",
        "Clean hair off brushes automatically",
      ],
      "Know your state: UV cabinets are often storage, not primary disinfection.",
      [
        "Disinfection chemistry/process still required.",
        "Time/claims vary; not magic sterilization.",
        "Debris must be cleaned manually first.",
      ],
      "hard",
    ],
    [
      "A contraindication means:",
      "A condition that makes a service inadvisable or requires physician referral",
      [
        "A product guaranteed for all clients",
        "A type of shears",
        "A booth rental contract only",
      ],
      "Recognize scalp disease, open sores, infections—do not proceed inappropriately.",
      [
        "Not a guarantee.",
        "Not a tool.",
        "Not a lease.",
      ],
      "easy",
    ],
    [
      "Parasites that can infest the scalp include:",
      "Head lice (pediculosis capitis)",
      ["Healthy terminal hair only", "Keratin protein alone", "Melanin granules"],
      "Infestations are contagious; discontinue service and refer.",
      [
        "Hair itself isn’t a parasite.",
        "Keratin is hair’s protein.",
        "Melanin is pigment.",
      ],
      "easy",
    ],
    [
      "Inhalation of excessive aerosol products is best reduced by:",
      "Adequate ventilation and directed spraying away from faces",
      [
        "Spraying in unventilated closets only",
        "Encouraging deep breaths of concentrate fumes",
        "Ignoring SDS warnings",
      ],
      "Respiratory safety is part of professional practice.",
      [
        "Poor ventilation increases exposure.",
        "Do not inhale concentrates.",
        "Follow SDS.",
      ],
      "easy",
    ],
  ],
  "hair-services": [
    [
      "The hair cuticle is the:",
      "Outer protective layer of overlapping scales",
      [
        "Innermost medullary pith only",
        "Living dermis under the scalp only",
        "Sebaceous gland itself",
      ],
      "Cuticle condition affects shine, porosity, and chemical service outcomes.",
      [
        "Medulla is innermost when present.",
        "Dermis is skin.",
        "Sebaceous glands produce oil.",
      ],
      "easy",
    ],
    [
      "Porosity refers to:",
      "The hair’s ability to absorb moisture",
      [
        "The number of hairs per square inch only",
        "Natural hair color only",
        "Curl pattern exclusively",
      ],
      "Porosity guides chemical timing and product choice.",
      [
        "Density is hairs per area.",
        "Color is pigment.",
        "Curl is pattern/wave.",
      ],
      "easy",
    ],
    [
      "A blunt (one-length) haircut is characterized by:",
      "All hair cut to the same length weight line",
      [
        "Extreme short-to-long layering only",
        "Shaving the scalp entirely",
        "Only razor tapering without a perimeter",
      ],
      "Solid form creates a heavy weight line.",
      [
        "That describes layered forms.",
        "Not a bald shave.",
        "Blunt can be scissor-cut with a clear perimeter.",
      ],
      "easy",
    ],
    [
      "Elevation in haircutting controls:",
      "Layering / the degree of graduation away from the head shape",
      [
        "Only the shampoo brand",
        "Disinfectant contact time",
        "License renewal dates",
      ],
      "0° elevation builds weight; higher elevation removes weight/layers.",
      [
        "Not shampoo.",
        "Not disinfection.",
        "Not licensing admin.",
      ],
      "medium",
    ],
    [
      "Overdirection is used to:",
      "Create length or shape by combing hair away from its natural fall before cutting",
      [
        "Disinfect shears",
        "Measure peroxide volume",
        "Cure scalp ringworm",
      ],
      "Overdirection designs longer perimeters or disconnected shapes.",
      [
        "Not infection control.",
        "Not developer math.",
        "Medical referral for tinea.",
      ],
      "medium",
    ],
    [
      "A patch test (predisposition test) for color is done to:",
      "Check for allergic sensitivity before certain color services",
      [
        "Measure hair density only",
        "Replace shampoo",
        "Determine shears angle",
      ],
      "Required/recommended for many oxidative color services per manufacturer and law.",
      [
        "Not density.",
        "Not cleansing.",
        "Not cutting angles.",
      ],
      "easy",
    ],
    [
      "Demi-permanent color typically:",
      "Deposits tone with little or no lift of natural pigment",
      [
        "Always lightens 4 levels like high-lift bleach",
        "Permanently changes disulfide bonds like a relaxer",
        "Is identical to powdered lightener",
      ],
      "Demi uses low/no ammonia systems for deposit; grey coverage varies by product.",
      [
        "Not strong lift.",
        "Relaxers break bonds differently.",
        "Lightener removes pigment.",
      ],
      "medium",
    ],
    [
      "When lightening virgin hair, a common approach is to:",
      "Apply to mid-lengths/ends first where resistant, then scalp last due to body heat (per product instructions)",
      [
        "Always apply to scalp first and leave longest without regard to heat",
        "Mix lightener with tap water only as universal rule",
        "Skip strand tests always",
      ],
      "Body heat accelerates scalp processing; follow manufacturer instructions.",
      [
        "Scalp often processes faster.",
        "Use correct developer.",
        "Strand tests prevent overprocessing.",
      ],
      "hard",
    ],
    [
      "A relaxer that is too strong or poorly timed can cause:",
      "Hair breakage and scalp burns",
      [
        "Stronger disulfide bonds automatically",
        "Guaranteed healthier cuticles",
        "Sterile tools",
      ],
      "Base application, timing, and smooth tension control risk.",
      [
        "Bonds are broken/reformed carefully—damage occurs if misused.",
        "Overprocessing damages cuticle/cortex.",
        "Not disinfection.",
      ],
      "medium",
    ],
    [
      "Neutralizer in permanent waving:",
      "Rebuilds disulfide bonds in the new shape (oxidation step)",
      [
        "Is optional if the client is in a hurry",
        "Only shampoos without chemical role",
        "Removes all melanin",
      ],
      "Skipping neutralization leaves hair weak and bonds incomplete.",
      [
        "Not optional.",
        "It is a chemical step.",
        "Not a bleach.",
      ],
      "medium",
    ],
    [
      "Texture services should not proceed when:",
      "Scalp has open sores, abrasions, or contagious conditions",
      [
        "Hair is slightly dry",
        "Client wants a trim later",
        "The salon music is soft",
      ],
      "Contraindications protect client health; refer when needed.",
      [
        "Dryness may need conditioning—not absolute stop like infection.",
        "Unrelated.",
        "Unrelated.",
      ],
      "easy",
    ],
    [
      "Slide cutting is generally used to:",
      "Blend and remove bulk with a mobile shear technique",
      [
        "Sterilize the comb",
        "Apply relaxer base",
        "Measure porosity scientifically only",
      ],
      "Texturizing methods include point cutting, notching, slide cutting—use appropriately on suitable hair.",
      [
        "Not disinfection.",
        "Not chemical base.",
        "Not a porosity meter.",
      ],
      "medium",
    ],
    [
      "Guideline in haircutting means:",
      "The first section cut that subsequent sections are matched to",
      [
        "The EPA disinfectant label only",
        "The client consultation card fee",
        "The booth lease clause",
      ],
      "Stationary vs traveling guidelines create different shapes.",
      [
        "Different meaning.",
        "Admin/billing.",
        "Business contract.",
      ],
      "easy",
    ],
    [
      "Highlighting differs from all-over color primarily because it:",
      "Lightens selected strands for dimension rather than a single uniform deposit/lift on all hair",
      [
        "Never uses lightener",
        "Is only done on beards by law",
        "Requires no sectioning",
      ],
      "Foiling/balayage/cap methods isolate strands.",
      [
        "Often uses lightener.",
        "Not beard-only.",
        "Sectioning/placement is key.",
      ],
      "easy",
    ],
    [
      "A binder/filler in color correction may be used to:",
      "Equalize porosity and replace missing underlying pigment before depositing tone",
      [
        "Disinfect shears",
        "Replace shampoo bowls",
        "Cure alopecia areata",
      ],
      "Color correction theory uses fillers to prevent muddy/uneven results on porous hair.",
      [
        "Not infection control.",
        "Not equipment.",
        "Medical hair loss needs referral.",
      ],
      "hard",
    ],
  ],
  "skin-nails": [
    [
      "The epidermis is:",
      "The outermost layer of the skin",
      [
        "The subcutaneous fat only",
        "A type of nail plate fungus exclusively",
        "The salon’s reception desk",
      ],
      "Epidermis includes the stratum corneum barrier important in esthetic services.",
      [
        "Subcutis is deeper.",
        "Fungus is pathology.",
        "Unrelated.",
      ],
      "easy",
    ],
    [
      "A pustule is:",
      "An inflamed papule containing pus",
      [
        "Healthy unbroken skin",
        "A hair cutting angle",
        "A type of shears",
      ],
      "Recognize lesions; do not service contagious or contraindicated conditions.",
      [
        "Not healthy skin.",
        "Not haircutting.",
        "Not a tool.",
      ],
      "easy",
    ],
    [
      "During a basic facial, cleansing is performed to:",
      "Remove makeup, oil, and debris before further steps",
      [
        "Replace extractions of all clients forcefully",
        "Sterilize the dermis surgically",
        "Color the hair",
      ],
      "Follow client skin analysis; avoid contraindicated machines/products.",
      [
        "Extractions are selective/trained.",
        "Facials aren’t surgery.",
        "Wrong service category.",
      ],
      "easy",
    ],
    [
      "Massage movements should generally be directed:",
      "From insertion toward origin for many manipulative strokes on the face (as taught), with appropriate pressure",
      [
        "Random digging into the eye orbits",
        "Across open herpetic lesions",
        "With dirty hands after phone use without hygiene",
      ],
      "Classic theory: manipulate toward origin; never work on contagious lesions.",
      [
        "Eye safety critical.",
        "Herpes is a contraindication.",
        "Hand hygiene required.",
      ],
      "medium",
    ],
    [
      "The nail plate is composed mainly of:",
      "Keratin",
      ["Living fat cells only", "Melanin exclusively", "Calcium metal rods"],
      "Nail is hardened keratin; matrix produces the plate.",
      [
        "Not adipose.",
        "Melanin pigments skin/hair more than nail plate bulk.",
        "Not metal.",
      ],
      "easy",
    ],
    [
      "Onychomycosis is:",
      "A fungal infection of the nail",
      [
        "Healthy nail growth",
        "A hair porosity test",
        "A type of perm rod",
      ],
      "Do not work on infected nails; refer to a physician.",
      [
        "It is disease.",
        "Not porosity.",
        "Not a tool.",
      ],
      "medium",
    ],
    [
      "Before a manicure, implements should be:",
      "Cleaned and disinfected (or disposable single-use) per state board rules",
      [
        "Wiped on the stylist’s pants only",
        "Shared from a contaminated jar of “community tools” without disinfection",
        "Rinsed with soda water only as sterilization",
      ],
      "Nail services have high blood-exposure potential—strict infection control.",
      [
        "Pants wipe is inadequate.",
        "Community dirty tools spread disease.",
        "Soda is not sterilization.",
      ],
      "easy",
    ],
    [
      "Cuticle remover chemicals are generally:",
      "Alkaline products that soften pterygium/cuticle tissue—use carefully and avoid excessive living tissue removal",
      [
        "Strong acids identical to bleach powders",
        "EPA sterilants for skin",
        "Used to lighten hair 4 levels",
      ],
      "Do not cut living tissue illegally/unsafely; many states restrict invasive cuticle cutting.",
      [
        "Different chemistry.",
        "Not for skin sterilization.",
        "Not hair lightener.",
      ],
      "medium",
    ],
    [
      "Acrylic (liquid/powder) nail enhancements require:",
      "Proper ratio, ventilation, and never applying over fungus/infection",
      [
        "Application on wet undried oils for better adhesion always",
        "No dust control ever",
        "Ignoring manufacturer instructions",
      ],
      "Monomer vapor and dust safety matter; enhancement over infection is contraindicated.",
      [
        "Oils impair adhesion; prep is dry/clean.",
        "Control dust/PPE as appropriate.",
        "Follow IFU.",
      ],
      "medium",
    ],
    [
      "A client with inflamed, swollen nail folds (paronychia signs) should be:",
      "Referred for medical evaluation; do not perform invasive nail services",
      [
        "Pushed aggressively into the eponychium",
        "Soaked in shared unclean water then ignored",
        "Covered with acrylic to “seal” infection",
      ],
      "Infection is a stop-service situation.",
      [
        "Aggravates injury.",
        "Shared water spreads pathogens.",
        "Sealing infection worsens it.",
      ],
      "medium",
    ],
    [
      "Hard wax hair removal differs from soft wax in that hard wax typically:",
      "Is applied thicker and removed without a strip when set",
      [
        "Requires a cloth strip identically always",
        "Is used only on scalp perms",
        "Disinfects implements",
      ],
      "Hard wax suits sensitive areas for many estheticians; follow contraindications (retinoids, sunburn, etc.).",
      [
        "Soft wax uses strips.",
        "Not a perm product.",
        "Not disinfection.",
      ],
      "medium",
    ],
    [
      "Tweezing is performed:",
      "In the direction of hair growth with proper skin support and sanitation of tweezers",
      [
        "Across contagious impetigo lesions",
        "With shared tweezers uncleaned between clients",
        "On moles that change rapidly without referral consideration",
      ],
      "Sanitize tweezers between clients; avoid suspicious lesions.",
      [
        "Impetigo is contagious—stop.",
        "Disinfect between clients.",
        "Changing moles need medical referral.",
      ],
      "easy",
    ],
    [
      "Massage is contraindicated when:",
      "Client has contagious skin disease, thrombosis concerns, or other conditions flagged in consultation",
      [
        "Client simply wants relaxation and is healthy",
        "Skin is clean and intact with no red flags",
        "You have completed hygiene and analysis appropriately",
      ],
      "Health history screens for massage contraindications.",
      [
        "Healthy clients may receive massage.",
        "Intact clean skin can be appropriate.",
        "Proper prep supports safe service.",
      ],
      "hard",
    ],
    [
      "The eponychium is:",
      "Living skin at the base of the nail plate (often confused with cuticle)",
      [
        "The free edge tip only",
        "A hair medulla",
        "A disinfectant brand",
      ],
      "Avoid cutting living eponychium; remove only non-living cuticle tissue as allowed by law.",
      [
        "Free edge is distal plate.",
        "Not hair anatomy.",
        "Not a product brand definition.",
      ],
      "hard",
    ],
    [
      "Pedicure basins must be:",
      "Cleaned and disinfected between clients per state rules (including jets/filters if applicable)",
      [
        "Just refilled with fresh water over debris",
        "Shared without disinfection all day",
        "Ignored if the water looks clear",
      ],
      "Whirlpool pedicure spas have been linked to infections when improperly disinfected.",
      [
        "Debris must be removed then disinfected.",
        "Between-client disinfection required.",
        "Appearance ≠ disinfection.",
      ],
      "easy",
    ],
  ],
  "laws-salon": [
    [
      "A cosmetology license generally allows the holder to:",
      "Perform services defined in state law for which they are licensed, in a licensed establishment when required",
      [
        "Practice medicine and prescribe drugs",
        "Ignore all infection-control rules",
        "Work without any license if tipped in cash",
      ],
      "Scope is state-specific; working outside scope risks discipline.",
      [
        "Medical practice is separate.",
        "Infection control is mandatory.",
        "Licensure is required.",
      ],
      "easy",
    ],
    [
      "Practicing with an expired license is:",
      "Illegal / subject to penalties in most jurisdictions",
      [
        "Encouraged to save money",
        "Allowed if the client consents verbally only",
        "Fine if posted on Instagram",
      ],
      "Renew on time; reciprocity rules vary by state.",
      [
        "Not encouraged.",
        "Client consent doesn’t legalize unlicensed practice.",
        "Social media doesn’t authorize practice.",
      ],
      "easy",
    ],
    [
      "Client records for chemical services often should include:",
      "Formulas, processing times, patch test info, and release/consultation notes as required",
      [
        "Other clients’ credit card CVV codes shared openly",
        "Staff Social Security numbers",
        "Nothing—memory is enough legally always",
      ],
      "Documentation protects client and licensee in disputes/allergies.",
      [
        "Protect payment data.",
        "Never store staff SSNs in client cards.",
        "Records matter.",
      ],
      "medium",
    ],
    [
      "Booth rental / independent contractor status means:",
      "You may be responsible for your own taxes, insurance, and compliance as a separate business—know state rules",
      [
        "The salon owner is always your W-2 employer automatically",
        "Licenses are unnecessary",
        "Disinfection is optional for renters",
      ],
      "Misclassification and sanitation responsibilities still apply to the licensee.",
      [
        "IC vs employee depends on facts/law.",
        "License still required.",
        "Infection control still required.",
      ],
      "medium",
    ],
    [
      "Advertising that you can cure skin cancer in the salon would be:",
      "Illegal/unprofessional and outside scope of practice",
      [
        "Standard cosmetology marketing",
        "Required by OSHA",
        "A type of haircut",
      ],
      "Do not make medical claims; refer suspicious lesions.",
      [
        "Not standard.",
        "OSHA doesn’t require false claims.",
        "Not a haircut.",
      ],
      "easy",
    ],
    [
      "Single-use items such as orangewood sticks and disposable files should be:",
      "Discarded after one client",
      [
        "Disinfected and reused indefinitely always",
        "Shared in a community cup",
        "Rinsed and returned to the clean drawer as sterile",
      ],
      "Porous single-use items cannot be properly disinfected for reuse in many rules.",
      [
        "Often prohibited to reuse.",
        "Sharing spreads disease.",
        "Rinse ≠ sterile.",
      ],
      "easy",
    ],
    [
      "A state board inspector may check for:",
      "Proper licensure posting, disinfection practices, and establishment compliance",
      [
        "Your personal streaming passwords",
        "Only the color of the walls regardless of sanitation",
        "Whether tips were reported to friends",
      ],
      "Be inspection-ready every day.",
      [
        "Irrelevant.",
        "Sanitation is central.",
        "Tax issues differ from board sanitation focus.",
      ],
      "easy",
    ],
    [
      "Continuing education requirements:",
      "Vary by state and may be required for license renewal",
      [
        "Never exist in any U.S. state",
        "Replace the need for a primary license",
        "Are set by fashion magazines only",
      ],
      "Know your state’s CE and renewal rules.",
      [
        "Many states require CE.",
        "CE supplements, doesn’t replace licensure.",
        "State boards set rules.",
      ],
      "medium",
    ],
    [
      "Refusal of service is appropriate when:",
      "A contagious condition or contraindication makes the service unsafe/illegal to perform",
      [
        "The client’s protected class status is the sole reason in a discriminatory way",
        "You dislike a client’s music taste only, violating public accommodation unlawfully",
        "You want to keep a deposit without policy after refusing without cause unlawfully",
      ],
      "Safety refusals are valid; unlawful discrimination is not.",
      [
        "Civil rights laws apply to public accommodations.",
        "Taste alone isn’t a safety refusal.",
        "Follow contract/consumer laws ethically.",
      ],
      "hard",
    ],
    [
      "Proper storage of disinfected tools is typically:",
      "In a clean, covered container labeled as clean/disinfected",
      [
        "Loose in an open drawer with used hair and debris",
        "In the employee lunch bag",
        "Soaking overnight in bleach without measuring, unlabeled",
      ],
      "Avoid recontamination after disinfection; follow wet disinfectant label rules.",
      [
        "Open dirty storage contaminates.",
        "Food/tools separation.",
        "Follow concentration/time; labeling matters.",
      ],
      "medium",
    ],
    [
      "Mixing chemicals from different manufacturers without guidance can be dangerous because:",
      "Reactions may release toxic gases or reduce effectiveness unpredictably",
      [
        "It always improves EPA registration",
        "It is required weekly by OSHA",
        "It sterilizes the air",
      ],
      "Follow labels; never mix bleach with ammonia, etc.",
      [
        "Doesn’t improve registration.",
        "Not an OSHA requirement.",
        "Not air sterilization.",
      ],
      "medium",
    ],
    [
      "Informed consent / consultation helps:",
      "Set expectations, reveal allergies/contraindications, and document agreement to the service plan",
      [
        "Eliminate the need for patch tests when required",
        "Allow unlicensed assistants to perform restricted services",
        "Skip disinfection",
      ],
      "Good consultations reduce liability and improve results.",
      [
        "Patch tests still when required.",
        "Licensure rules remain.",
        "Infection control remains.",
      ],
      "easy",
    ],
    [
      "Price advertising that shows a service “from $20” must generally be:",
      "Truthful and not bait-and-switch deceptive under consumer protection principles",
      [
        "Intentionally false to get clients in the door",
        "Hidden in 2-point font only as best practice for deception",
        "Unrelated to ethics",
      ],
      "Professional ethics and laws prohibit deceptive advertising.",
      [
        "False ads are illegal/unethical.",
        "Deception is improper.",
        "Ethics apply.",
      ],
      "hard",
    ],
    [
      "An apprentice/student working on the public typically must:",
      "Be supervised as required by state law and stay within student/apprentice scope",
      [
        "Work unsupervised as a fully licensed professional without credentials",
        "Skip infection control until licensed",
        "Perform medical diagnosis",
      ],
      "Training pathways are regulated; public protection is the goal.",
      [
        "Credentials required for independent practice.",
        "Infection control applies in school clinics too.",
        "No medical diagnosis.",
      ],
      "medium",
    ],
    [
      "If a product is recalled for safety, the salon should:",
      "Stop use, follow recall instructions, and protect clients",
      [
        "Use it up quickly before anyone notices",
        "Relabel it as a different brand",
        "Ignore manufacturer notices",
      ],
      "Consumer safety overrides inventory loss concerns.",
      [
        "Using recalled product is improper.",
        "Relabeling is deceptive/dangerous.",
        "Notices must be heeded.",
      ],
      "easy",
    ],
  ],
};
