#!/usr/bin/env python3
"""Esthetician state/NIC theory readiness bank — 60Q."""

from write_helper import write_bank

SKIN = [
    (
        "Which layer of the epidermis contains melanocytes that produce melanin?",
        "Stratum basale (germinativum)",
        ["Stratum corneum only", "Dermis reticular layer only", "Hypodermis adipose only"],
        "Melanocytes reside primarily in the basal layer; the corneum is dead keratinized cells.",
        [
            "Corneum is outermost dead cells.",
            "Dermis is connective tissue beneath epidermis.",
            "Hypodermis is subcutaneous fat/fascia.",
        ],
        "easy",
    ),
    (
        "Sebaceous glands primarily produce:",
        "Sebum (oil) that helps lubricate skin and hair",
        ["Only eccrine sweat with no lipids", "Only melanin pigment", "Only synovial fluid"],
        "Sebaceous glands secrete sebum into hair follicles; eccrine glands produce sweat.",
        [
            "Eccrine glands are sweat glands.",
            "Melanin is from melanocytes.",
            "Synovial fluid is in joints.",
        ],
        "easy",
    ),
    (
        "Which skin type is characterized by small follicles, tight appearance, and reduced oil?",
        "Dry skin",
        ["Oily skin", "Combination skin only by definition", "Normal skin with balanced sebum always labeled dry"],
        "Dry skin lacks adequate sebum/moisture; oily skin shows larger follicles and shine.",
        [
            "Oily skin has excess sebum.",
            "Combination has mixed zones.",
            "Normal is balanced, not dry.",
        ],
        "easy",
    ),
    (
        "A closed comedo is commonly known as a:",
        "Whitehead",
        ["Open comedo (blackhead)", "Vesicle filled with clear fluid only", "Fissure"],
        "Closed comedones are whiteheads; open comedones oxidize and appear as blackheads.",
        [
            "Blackheads are open comedones.",
            "Vesicles are fluid blisters.",
            "Fissures are cracks in skin.",
        ],
        "easy",
    ),
    (
        "Which UV ray type is most associated with burning and DNA damage at the skin surface?",
        "UVB",
        ["UVA only as the sole burning ray in all texts", "Infrared as UVB", "Visible green light exclusively"],
        "UVB is the primary burning ray; UVA penetrates deeper and contributes to aging/pigment issues.",
        [
            "UVA penetrates deeper; both matter for protection.",
            "Infrared is heat, not UVB.",
            "Visible light is not UVB.",
        ],
        "medium",
    ),
    (
        "Rosacea is best described as:",
        "A chronic inflammatory condition with flushing, visible vessels, and possible papules/pustules—not cured by extraction alone",
        [
            "A contagious bacterial infection identical to impetigo in all clients",
            "Only a temporary sunscreen allergy in every case",
            "A fungal infection cured only by nail clipping",
        ],
        "Rosacea is chronic/inflammatory; triggers and medical care matter; it is not managed like simple comedones only.",
        [
            "Impetigo is a contagious infection; rosacea is not managed the same way.",
            "Not merely sunscreen allergy.",
            "Not a nail fungus.",
        ],
        "medium",
    ),
    (
        "Which lesion is a flat discoloration without elevation or depression?",
        "Macule",
        ["Papule", "Pustule", "Nodule"],
        "Macules are flat; papules are raised; pustules contain pus; nodules are deeper/larger.",
        [
            "Papules are elevated.",
            "Pustules are pus-filled.",
            "Nodules are deeper solid lesions.",
        ],
        "easy",
    ),
    (
        "The dermis contains which of the following?",
        "Collagen, elastin, blood vessels, nerves, and appendages (follicles/glands)",
        ["Only stratum corneum keratin squames", "Only bone marrow", "Only enamel"],
        "Dermis is living connective tissue housing osteoid-like collagen matrix and skin appendages.",
        [
            "Corneum is epidermal.",
            "Bone marrow is skeletal.",
            "Enamel is dental.",
        ],
        "easy",
    ),
    (
        "Hyperpigmentation from sun exposure is primarily related to increased:",
        "Melanin production / melanocyte activity",
        ["Only sebum viscosity with no pigment change", "Only eccrine salt content", "Only nail growth rate"],
        "UV stimulates melanogenesis leading to tanning or dyschromia.",
        [
            "Oil changes are separate from pigment.",
            "Sweat salt is unrelated to tan.",
            "Nails are not the pigment mechanism.",
        ],
        "medium",
    ),
    (
        "Which condition is a contraindication for many aggressive exfoliation / extraction services until cleared?",
        "Active herpes simplex lesion (cold sore) in the treatment area",
        ["Mild dehydrated skin with no lesions", "Client desire for hydration", "Normal skin with SPF use"],
        "Viral lesions can spread; delay services and refer as needed.",
        [
            "Dehydration can often be treated gently.",
            "Hydration goals are common indications.",
            "SPF use is protective, not a contraindication.",
        ],
        "medium",
    ),
    (
        "Albinism involves:",
        "A genetic lack of melanin production leading to very light skin/hair and light sensitivity concerns",
        ["Excess melanin in all cases", "Only overactive sebaceous glands", "Bacterial overgrowth identical to acne vulgaris always"],
        "Albinism is a melanin synthesis disorder; sun protection education is critical.",
        [
            "It is hypopigmentation, not excess melanin.",
            "Not defined by oil glands.",
            "Not the same as acne pathogenesis.",
        ],
        "hard",
    ),
    (
        "Which skin function relates to synthesizing vitamin D with UV exposure?",
        "Absorption / metabolic functions of skin (vitamin D production pathway)",
        ["Only keratinization of nails as vitamin D synthesis", "Only sebum as the vitamin D molecule", "Only lymph nodes inside the epidermis producing vitamin D"],
        "Skin participates in vitamin D synthesis when UVB converts precursors; other listed options are incorrect mechanisms.",
        [
            "Nails do not synthesize vitamin D.",
            "Sebum is not vitamin D.",
            "Lymph nodes are not epidermal vitamin D factories.",
        ],
        "hard",
    ),
    (
        "A pustule contains:",
        "Pus",
        ["Only clear serum always", "Only blood exclusively by definition", "Only keratin plug without inflammation"],
        "Pustules are elevated lesions filled with purulent fluid.",
        [
            "Clear fluid suggests vesicle/bulla.",
            "Blood-filled is hematoma/angioma territory.",
            "Keratin plugs are comedones.",
        ],
        "easy",
    ),
    (
        "Which factor most strongly accelerates extrinsic skin aging?",
        "Chronic unprotected UV exposure (photoaging)",
        ["Drinking water in normal amounts", "Sleeping on a clean pillowcase", "Using gentle cleanser as directed"],
        "Photoaging from UV is a major extrinsic aging driver; healthy habits are protective.",
        [
            "Hydration support is beneficial.",
            "Clean bedding reduces irritation/acne risk.",
            "Gentle cleansing supports barrier.",
        ],
        "medium",
    ),
    (
        "Tinea corporis is:",
        "A fungal (ringworm) infection of the body skin—refer/avoid spreading services as indicated",
        ["A bacterial stye of the eyelid only", "A viral wart caused by HPV exclusively on soles always", "A normal freckle"],
        "Tinea is dermatophyte infection; estheticians should recognize and not treat as cosmetic acne.",
        [
            "Styes are different (hordeolum).",
            "Plantar warts are verruca plantaris.",
            "Freckles are ephelides, not infection.",
        ],
        "hard",
    ),
]

TREATMENTS = [
    (
        "The primary goal of a basic cleansing step in a facial is to:",
        "Remove makeup, oil, and debris to prepare skin for treatment",
        ["Permanently change Fitzpatrick type", "Replace medical diagnosis", "Sterilize the dermis surgically"],
        "Cleansing prepares the skin; it does not alter genetics or replace medical care.",
        [
            "Fitzpatrick type is genetic/response-based.",
            "Diagnosis is medical.",
            "Facials are not surgery.",
        ],
        "easy",
    ),
    (
        "Chemical exfoliation using AHAs primarily works by:",
        "Loosening desmosomal bonds / promoting desquamation of surface corneocytes",
        ["Injecting filler into the dermis", "Cutting hair shafts like a razor", "Removing subcutaneous fat surgically"],
        "AHAs (e.g., glycolic/lactic) encourage surface cell turnover; they are not injectables or surgery.",
        [
            "Fillers are medical procedures.",
            "Razors cut hair, not chemical exfoliation.",
            "Liposuction is surgical.",
        ],
        "medium",
    ),
    (
        "A Wood’s lamp is used in esthetics primarily to:",
        "Analyze pigmentation, oiliness, and certain skin conditions under UV illumination",
        ["Cut tissue", "Measure blood pressure", "Perform electrolysis permanently in one flash"],
        "Wood’s lamp helps visualization; it is not a treatment device for cutting or permanent hair removal alone.",
        [
            "It does not cut.",
            "BP needs a cuff/monitor.",
            "Electrolysis is a different modality.",
        ],
        "medium",
    ),
    (
        "High-frequency (Tesla) current in facial devices is commonly used to:",
        "Create a germicidal / stimulating effect with oxygenating sparking for suitable skin",
        ["Replace all sunscreen needs outdoors", "Diagnose melanoma definitively", "Perform deep laser resurfacing equivalent to ablative CO2"],
        "HF is a modality for suitable clients; it is not diagnosis or ablative laser.",
        [
            "Sunscreen remains necessary.",
            "Cancer diagnosis is medical.",
            "Ablative lasers are medical-grade procedures.",
        ],
        "medium",
    ),
    (
        "During extractions, proper practice includes:",
        "Working only on appropriate lesions with hygiene, gentle technique, and knowing contraindications",
        [
            "Forcing deep cystic lesions aggressively on every client",
            "Extracting active herpetic blisters",
            "Using bare hands without cleansing skin or tools",
        ],
        "Safe extractions require judgment, sanitation, and limits; cysts/herpes need medical care.",
        [
            "Aggressive cystic work risks scarring/infection.",
            "Herpes can spread.",
            "Aseptic technique is required.",
        ],
        "easy",
    ),
    (
        "A clay mask is often chosen for:",
        "Oily/congested skin to absorb excess sebum",
        ["Severely dehydrated mature skin as the only hydrating option always", "Open wounds as a bandage", "Eyeball application"],
        "Clay draws oil; dehydrated skin often prefers hydrating/cream masks.",
        [
            "Dry/dehydrated skin may need humectant masks.",
            "Open wounds are contraindications.",
            "Never apply masks to eyes.",
        ],
        "easy",
    ),
    (
        "Galvanic desincrustation is used to:",
        "Softening sebum/debris (anaphoresis) to aid cleansing of congested skin when appropriate",
        ["Freeze tissue like cryotherapy permanently", "Tattoo pigment into dermis", "Cut hair with electricity as scissors"],
        "Desincrustation uses galvanic polarity effects; it is not cryo, tattooing, or cutting.",
        [
            "Not cryotherapy.",
            "Tattooing is unrelated.",
            "Not a cutting tool.",
        ],
        "hard",
    ),
    (
        "Microdermabrasion physically exfoliates primarily by:",
        "Mechanical abrasion of the stratum corneum with crystals or diamond tip",
        ["Oral antibiotics", "Subcutaneous fat dissolution injections", "Breaking bones"],
        "Microdermabrasion is mechanical surface exfoliation within scope/training limits.",
        [
            "Antibiotics are medications.",
            "Injections are medical.",
            "Not orthopedic.",
        ],
        "easy",
    ),
    (
        "Which product ingredient class is commonly used for hydration by attracting water?",
        "Humectants (e.g., glycerin, hyaluronic acid)",
        ["Only physical sunscreens as humectants", "Only abrasive scrubs as humectants", "Only alcohol denat as a humectant moisturizer"],
        "Humectants bind water; occlusives seal; surfactants cleanse; alcohol can be drying.",
        [
            "Sunscreens protect from UV.",
            "Scrubs exfoliate mechanically.",
            "Drying alcohols are not hydrators.",
        ],
        "medium",
    ),
    (
        "A contraindication for many heat-based facial machines is:",
        "Pregnancy (for certain modalities) / metal implants / pacemakers depending on device—follow manufacturer and law",
        ["Desire for clean skin", "Use of daily moisturizer", "Normal oily T-zone"],
        "Electromagnetic/heat modalities have medical contraindications; always screen.",
        [
            "Cleansing goals are indications.",
            "Moisturizer is routine care.",
            "Oily zones are common treatment targets.",
        ],
        "hard",
    ),
    (
        "Proper order for a basic facial commonly begins with:",
        "Client consultation/skin analysis → cleanse → continue with exfoliation/treatment steps as planned",
        ["Extractions before any consultation", "Mask before removing makeup always", "Toner as the very first step on heavy makeup without cleanse"],
        "Consultation and cleansing set safety and efficacy for subsequent steps.",
        [
            "Consent/analysis first.",
            "Makeup/oil should be removed first.",
            "Cleanse precedes toner typically.",
        ],
        "easy",
    ),
    (
        "LED light therapy in esthetics is generally used for:",
        "Non-thermal photomodulation benefits (e.g., calming/acne-support protocols depending on wavelength) within device guidelines",
        ["Cutting tissue like a scalpel", "Providing SPF 100 coverage outdoors", "Replacing isotretinoin prescriptions"],
        "LED is adjunctive; it is not surgery, sunscreen, or prescription medicine.",
        [
            "Not ablative cutting.",
            "Not sunscreen.",
            "Medications require clinicians.",
        ],
        "medium",
    ),
    (
        "Massage movements in facial should generally be:",
        "Toward lymphatic drainage patterns with appropriate pressure for the client’s skin and contraindications",
        ["Deep tissue bone cracking", "Across open acne lesions aggressively to express all lesions at once without hygiene", "On eyes with heavy friction always"],
        "Esthetic massage is gentle and purposeful; avoid contraindicated areas and poor hygiene.",
        [
            "Bone manipulation is out of scope.",
            "Infected lesions need caution/avoidance.",
            "Eye area needs extreme care.",
        ],
        "medium",
    ),
    (
        "Which statement about chemical peel strength is correct?",
        "Deeper/higher-strength peels increase results and risks; stay within license, training, and manufacturer protocols",
        [
            "Stronger is always safer for home use by any client",
            "Peel percentage alone fully determines safety regardless of pH and formulation",
            "All peels are identical regardless of acid type",
        ],
        "Acid type, pH, vehicle, and layers matter; professional judgment and scope are essential.",
        [
            "Strong peels raise complication risk for untrained use.",
            "Percentage alone is incomplete—pH and formulation also drive strength.",
            "AHAs, BHAs, and TCA peels behave differently.",
        ],
        "hard",
    ),
    (
        "Paraffin masks are often used to:",
        "Provide emollient occlusion and comfort, often for dry skin on face/hands when appropriate",
        ["Treat open contagious infections", "Replace Mohs surgery", "Sterilize implements"],
        "Warm paraffin can hydrate/comfort suitable intact skin; not for infection or medical surgery.",
        [
            "Infection contraindicates.",
            "Mohs is medical oncology/derm surgery.",
            "Sterilization uses approved methods, not paraffin.",
        ],
        "easy",
    ),
]

INFECTION = [
    (
        "The highest level of decontamination that destroys all microbial life including spores is:",
        "Sterilization",
        ["Sanitation with soap only", "Antiseptic on intact skin only", "Dusting with a towel"],
        "Sterilization kills spores; disinfection reduces pathogens on nonliving surfaces but may not kill all spores.",
        [
            "Sanitation reduces debris/microbes but is lower level.",
            "Antiseptics are for living tissue.",
            "Dusting is cleaning at best.",
        ],
        "easy",
    ),
    (
        "Implements that penetrate soft tissue / blood contact typically require:",
        "Sterilization (or single-use disposable) per regulations",
        ["Only a quick wipe with dry paper", "Rinsing in cold water only", "Storage in an open uncovered drawer unclean"],
        "Critical items need sterilization or disposables; follow state board rules.",
        [
            "Dry wipe is insufficient.",
            "Water rinse is not disinfection/sterilization.",
            "Unclean storage recontaminates.",
        ],
        "easy",
    ),
    (
        "Hand washing should occur:",
        "Before and after each client and whenever hands are contaminated",
        ["Only at the end of the week", "Never if gloves are available once", "Only after blood spills, never before services"],
        "Hand hygiene is the foundation of infection control before/after care.",
        [
            "Weekly washing is inadequate.",
            "Gloves do not replace hand hygiene.",
            "Wash before services too.",
        ],
        "easy",
    ),
    (
        "An EPA-registered disinfectant used in the salon must be used:",
        "According to label contact time, dilution, and intended surface use",
        ["Wiped off instantly always regardless of label", "Drunk as a tonic", "Mixed with unknown chemicals for scent"],
        "Efficacy depends on correct use; never ingest or improvise dangerous mixes.",
        [
            "Contact time matters.",
            "Disinfectants are not beverages.",
            "Chemical mixing can create toxins.",
        ],
        "medium",
    ),
    (
        "Which is an example of a single-use (disposable) item?",
        "Cotton rounds / wooden spatulas that cannot be properly disinfected",
        ["Stainless steel comedone extractors designed for sterilization", "Glass dappen dishes that can be disinfected", "Metal tweezers designed for sterilization"],
        "Porous/single-use items are discarded; nonporous tools are cleaned then disinfected/sterilized as required.",
        [
            "Extractors are multiuse if processed correctly.",
            "Glass can be disinfected.",
            "Tweezers are multiuse metal tools.",
        ],
        "medium",
    ),
    (
        "Blood exposure incidents require:",
        "Stop service, don PPE as needed, clean, apply antiseptic/bandage per protocol, disinfect, document, and follow exposure plan",
        [
            "Continue without gloves to finish quickly",
            "Hide the incident without cleaning",
            "Reuse contaminated gauze on the next client",
        ],
        "Exposure control plans protect client and practitioner.",
        [
            "Barrier protection is required.",
            "Documentation/cleanup are mandatory ethically/legally.",
            "Contaminated items are infectious waste/single-use.",
        ],
        "medium",
    ),
    (
        "Quats (quaternary ammonium compounds) are commonly used as:",
        "Disinfectants for nonporous surfaces/tools when formulated and used per label",
        ["Sterilants that always kill spores in 5 seconds on all porous towels", "Hand lotions", "Drink flavoring"],
        "Many salon disinfectants are quat-based; sterilization is a higher process, often autoclave/chemical sterilant under strict rules.",
        [
            "Quats are not reliable sterilants for spores on porous items.",
            "Not moisturizers.",
            "Not for ingestion.",
        ],
        "hard",
    ),
    (
        "A contagious disease that may present with honeycomb crusts around mouth/nose in children is often:",
        "Impetigo (bacterial)—do not perform services; refer",
        ["Ordinary freckles", "Milia only", "Closed comedones exclusively"],
        "Impetigo is contagious; refuse service and refer.",
        [
            "Freckles are not infection.",
            "Milia are keratin cysts.",
            "Comedones are acne lesions, not impetigo.",
        ],
        "medium",
    ),
    (
        "Proper laundry handling for towels includes:",
        "Using closed containers for soiled linens and washing with appropriate detergent/hot water per rules",
        ["Shaking soiled towels vigorously in the treatment room air", "Reusing face towels between clients without washing", "Storing damp dirty towels in open piles overnight"],
        "Linens can harbor microbes; control contamination and wash properly.",
        [
            "Shaking aerosolizes contaminants.",
            "One client per clean towel.",
            "Damp storage breeds microbes.",
        ],
        "easy",
    ),
    (
        "OSHA’s Bloodborne Pathogens Standard is designed to:",
        "Protect workers from occupational exposure to blood and OPIM",
        ["Set retail product prices", "License estheticians instead of the state board", "Regulate only restaurant menus"],
        "BBP rules cover exposure control, PPE, HBV vaccination access, and training in applicable workplaces.",
        [
            "Not a pricing law.",
            "Licensure is state board.",
            "Not food menus.",
        ],
        "medium",
    ),
    (
        "Which practice reduces cross-contamination during product use?",
        "Dispense with clean spatulas/pumps; do not double-dip fingers into jars",
        ["Scoop cream with bare fingers used on previous client", "Blow on product to warm it over an open jar repeatedly", "Share the same disposable sponge between two faces without replacement"],
        "Aseptic dispensing protects product integrity and clients.",
        [
            "Fingers contaminate jars.",
            "Breath adds microbes.",
            "Sponges are single-client/single-use as required.",
        ],
        "easy",
    ),
    (
        "Autoclaves sterilize using:",
        "Steam under pressure (moist heat) for validated time/temperature/pressure",
        ["Cold dry air only at room temperature", "Perfume mist", "UV manicure lamps alone as a guaranteed sterilizer for all metal tools always"],
        "Steam autoclaves are a standard sterilization method when used/validated correctly.",
        [
            "Room air does not sterilize.",
            "Fragrance is irrelevant.",
            "UV lamps are not a substitute autoclave for critical implements.",
        ],
        "hard",
    ),
    (
        "If a disinfectant label contact time is 10 minutes, you should:",
        "Keep items wet with disinfectant for the full 10 minutes",
        ["Wipe dry after 10 seconds", "Rinse immediately after 1 second always", "Ignore the label if busy"],
        "Contact time is required for kill claims.",
        [
            "Seconds are insufficient if label says minutes.",
            "Immediate rinse defeats contact time.",
            "Labels are legal use directions.",
        ],
        "easy",
    ),
    (
        "Which is considered a universal/standard precaution principle?",
        "Treat all blood and body fluids as potentially infectious",
        ["Only treat visibly ill clients as infectious and ignore blood otherwise", "Never wear gloves for extractions involving blood risk", "Recap contaminated needles with two hands toward the body"],
        "Standard precautions assume unknown status; use PPE and safe sharps practices.",
        [
            "Appearance is not a safe filter.",
            "Gloves are indicated for exposure risk.",
            "Unsafe recapping causes sharps injuries.",
        ],
        "medium",
    ),
    (
        "A virucidal disinfectant claim means it is effective against:",
        "Viruses (as stated on the label for listed organisms)",
        ["Only dust", "Only perfume odor", "Only large insects"],
        "Labels specify bactericidal, virucidal, fungicidal claims—use products suited to salon risks.",
        [
            "Dust needs cleaning.",
            "Odor control is not disinfection.",
            "Insects are pest control.",
        ],
        "easy",
    ),
]

LAWS = [
    (
        "Estheticians must practice within:",
        "The scope defined by state law/regulations and their license",
        ["Any medical procedure they watched online", "Prescribing legend drugs freely", "Diagnosing cancer as a final pathology report"],
        "Scope is legal; medical acts require appropriate licensure.",
        [
            "Online videos do not expand license.",
            "Prescribing is for authorized clinicians.",
            "Pathology diagnosis is medical.",
        ],
        "easy",
    ),
    (
        "Informed consent in the treatment room means:",
        "Explaining the service, risks/benefits/alternatives, and obtaining client agreement before proceeding",
        ["Starting peels without discussion to save time", "Assuming consent from a social media like", "Never documenting contraindications"],
        "Consent is a process plus documentation—not silence.",
        [
            "Discussion is required.",
            "Likes are not consent.",
            "Document screening.",
        ],
        "easy",
    ),
    (
        "Client records should be:",
        "Accurate, confidential, and retained according to law/policy",
        ["Posted publicly with full medical history", "Discarded in open trash with identifiers always", "Altered to hide adverse reactions"],
        "Privacy laws and board rules protect records; falsification is unethical/illegal.",
        [
            "PHI must not be public.",
            "Secure disposal required.",
            "Honesty in records is mandatory.",
        ],
        "medium",
    ),
    (
        "A client refuses a recommended extraction. You should:",
        "Respect the refusal, document, and adapt the service appropriately",
        ["Perform it anyway 'for their own good'", "Mock the client publicly", "Refuse all future sunscreen advice out of spite"],
        "Autonomy is central to ethics; do not force services.",
        [
            "Battery/unconsented touching is illegal.",
            "Respect is required.",
            "Spiteful care is unprofessional.",
        ],
        "easy",
    ),
    (
        "Advertising a service as 'Botox' when you are not authorized to inject is:",
        "False/misleading advertising and practicing beyond scope",
        ["Required marketing for all estheticians", "Allowed if the cream is cold", "Acceptable if prices are low"],
        "Use truthful service names; injectables require medical credentials/oversight per law.",
        [
            "Not required—and often illegal if false.",
            "Temperature does not authorize injection claims.",
            "Price does not legalize false claims.",
        ],
        "medium",
    ),
    (
        "Continuing education requirements exist primarily to:",
        "Maintain competency and meet license renewal standards",
        ["Increase product sales commissions only", "Replace all infection control forever after one class", "Allow diagnosis of systemic disease"],
        "CE keeps practitioners current; it does not expand into medicine automatically.",
        [
            "CE is about competence/compliance.",
            "Infection control is ongoing.",
            "Diagnosis remains medical.",
        ],
        "easy",
    ),
    (
        "If state law and employer policy conflict, the esthetician should:",
        "Follow the stricter/legal requirement—never violate the law",
        ["Follow illegal employer orders", "Ignore both", "Ask social media to override the board"],
        "Law controls practice; policies cannot authorize illegal acts.",
        [
            "Illegal orders must be refused.",
            "Standards still apply.",
            "Boards/laws govern, not viral posts.",
        ],
        "hard",
    ),
    (
        "Retail recommendations should be based on:",
        "Client needs, skin analysis, and honest product claims",
        ["Only the highest commission regardless of contraindications", "Fear-based false disease claims", "Guaranteed cure of autoimmune disease"],
        "Ethics require suitability and truthfulness in retail.",
        [
            "Commission alone is not ethical basis.",
            "Scare tactics are unethical.",
            "Cure claims for disease are inappropriate.",
        ],
        "medium",
    ),
    (
        "Working with a communicable skin disease when services are contraindicated can lead to:",
        "License discipline, civil liability, and harm to clients",
        ["Automatic medical degree", "No possible consequences", "Higher UV protection for the room"],
        "Boards discipline unsafe practice; clients can be harmed and sue.",
        [
            "Does not grant MD credentials.",
            "Consequences are real.",
            "Irrelevant to UV.",
        ],
        "medium",
    ),
    (
        "Which is appropriate professional image/conduct?",
        "Clean attire, hygiene, respectful communication, and sober practice",
        ["Providing services while impaired", "Sharing client gossip in the lobby", "Refusing hand hygiene to 'save time'"],
        "Professionalism protects trust and safety.",
        [
            "Impairment endangers clients.",
            "Gossip breaches privacy.",
            "Hygiene is non-negotiable.",
        ],
        "easy",
    ),
    (
        "A patch test before certain chemical services is used to:",
        "Screen for adverse reactions on a small area before full application",
        ["Guarantee zero allergy forever", "Measure blood glucose", "Replace consultation"],
        "Patch tests reduce but do not eliminate risk; consultation remains essential.",
        [
            "No test guarantees lifelong safety.",
            "Not a glucose test.",
            "Consultation still required.",
        ],
        "medium",
    ),
    (
        "Scope-of-practice questions for a new device should be resolved by:",
        "Checking state board rules, manufacturer training, and whether medical oversight is required",
        ["Assuming all spa devices are unrestricted nationwide", "Copying a competitor’s illegal menu", "Using the device on yourself only as legal authorization for clients"],
        "Regulation varies; verify before offering.",
        [
            "Laws differ by state.",
            "Competitors may be noncompliant.",
            "Self-use does not create legal authority.",
        ],
        "hard",
    ),
    (
        "Client confidentiality includes protecting:",
        "Health history, photos, and treatment notes from unauthorized disclosure",
        ["Only the client’s favorite color", "Nothing once they leave the building", "Only unpaid invoices"],
        "Sensitive personal and health information requires safeguarding.",
        [
            "Preferences matter less than PHI/privacy.",
            "Duty continues after the visit.",
            "Financial data also needs care, but health/photos are key examples.",
        ],
        "easy",
    ),
    (
        "Charging for a service not performed is:",
        "Fraudulent/unethical billing",
        ["Standard upselling", "Required by OSHA", "A form of sterilization"],
        "Bill only for delivered services/products agreed upon.",
        [
            "Upselling must still be honest.",
            "OSHA is safety regulation.",
            "Not infection control.",
        ],
        "easy",
    ),
    (
        "When a client has a medical skin condition beyond cosmetic care, the professional response is:",
        "Refer to a licensed physician/dermatologist and avoid unauthorized treatment",
        ["Diagnose and prescribe antibiotics", "Lance cysts surgically without credentials", "Promise a medical cure with a facial"],
        "Referral protects the client and keeps practice legal.",
        [
            "Prescribing is medical.",
            "Surgery is medical.",
            "Facials are not medical cures.",
        ],
        "medium",
    ),
]


def main() -> None:
    # Fix awkward distractor on chemical peel question — rewrite row for clarity
    # (kept accurate teaching in explanation)
    write_bank(
        "esthetician-state-readiness-check",
        {
            "skin-science": SKIN,
            "treatments": TREATMENTS,
            "infection-safety": INFECTION,
            "laws-business": LAWS,
        },
    )


if __name__ == "__main__":
    main()
