#!/usr/bin/env python3
"""ISSA CPT readiness bank — 60Q."""

from write_helper import write_bank

ANATOMY = [
    (
        "Which muscle is the primary agonist for elbow flexion?",
        "Biceps brachii (with brachialis/brachioradialis assistance)",
        ["Triceps brachii", "Gastrocnemius", "Gluteus medius"],
        "Anterior arm flexors bend the elbow; triceps extends it.",
        [
            "Triceps is the primary elbow extensor.",
            "Gastrocnemius plantarflexes the ankle.",
            "Gluteus medius abducts the hip.",
        ],
        "easy",
    ),
    (
        "The axial skeleton primarily includes:",
        "Skull, vertebral column, ribs, and sternum",
        ["Only the femur and tibia", "Only carpal bones", "Only phalanges of the feet"],
        "Axial = central axis; appendicular = limbs and girdles.",
        [
            "Femur/tibia are appendicular.",
            "Carpals are appendicular.",
            "Foot phalanges are appendicular.",
        ],
        "easy",
    ),
    (
        "Which energy pathway dominates a 40-minute steady jog?",
        "Oxidative (aerobic) system",
        ["ATP–PC exclusively for the entire 40 minutes", "Only immediate phosphagen with no oxygen use", "Anaerobic glycolysis as the sole pathway with zero aerobic contribution"],
        "Longer submaximal work relies primarily on aerobic metabolism.",
        [
            "ATP–PC covers only seconds.",
            "Oxygen use rises in prolonged work.",
            "Glycolysis contributes but is not sole for 40 min steady work.",
        ],
        "medium",
    ),
    (
        "A concentric muscle action occurs when:",
        "The muscle shortens while producing force",
        ["The muscle lengthens under load (eccentric)", "Tension is produced with no joint motion (isometric)", "The muscle is completely passive with zero tension"],
        "Concentric = shortening; eccentric = lengthening under tension; isometric = no length change.",
        [
            "That is eccentric.",
            "That is isometric.",
            "Passive tissue is not an active concentric action.",
        ],
        "easy",
    ),
    (
        "Which chamber pumps oxygenated blood into the systemic circulation?",
        "Left ventricle",
        ["Right atrium", "Right ventricle", "Left atrium only as the systemic pump"],
        "Left ventricle ejects to the aorta; right ventricle pumps to the lungs.",
        [
            "Right atrium receives systemic venous blood.",
            "Right ventricle → pulmonary artery.",
            "Left atrium receives pulmonary venous blood; ventricle pumps out.",
        ],
        "easy",
    ),
    (
        "Golgi tendon organs primarily respond to:",
        "Tension / force in the tendon–muscle unit",
        ["Only light touch on skin", "Only vision", "Only blood glucose"],
        "GTOs sense tension and can inhibit agonist force (autogenic inhibition).",
        [
            "Cutaneous receptors sense touch.",
            "Vision is ocular.",
            "Glucose is endocrine/metabolic sensing.",
        ],
        "medium",
    ),
    (
        "Which plane separates the body into anterior and posterior portions?",
        "Frontal (coronal) plane",
        ["Sagittal plane", "Transverse plane", "Oblique fingernail plane"],
        "Frontal = front/back; sagittal = left/right; transverse = top/bottom.",
        [
            "Sagittal is left/right.",
            "Transverse is superior/inferior.",
            "Not a standard anatomical plane name.",
        ],
        "easy",
    ),
    (
        "Type II muscle fibers generally:",
        "Produce higher force/power and fatigue faster than Type I",
        ["Are only slow oxidative fibers", "Cannot hypertrophy", "Exist only in cardiac muscle"],
        "Fast-twitch fibers support power; Type I support endurance.",
        [
            "Type I are slow oxidative.",
            "Type II can hypertrophy.",
            "Skeletal muscle contains Type II fibers.",
        ],
        "medium",
    ),
    (
        "The rotator cuff muscles include:",
        "Supraspinatus, infraspinatus, teres minor, and subscapularis",
        ["Rectus abdominis, obliques, transverse abdominis, erectors only", "Vastus lateralis, medialis, intermedius, rectus femoris only", "Gastrocnemius and soleus only"],
        "SITS muscles stabilize the glenohumeral joint.",
        [
            "Those are core muscles.",
            "Those are quadriceps.",
            "Those are plantarflexors.",
        ],
        "medium",
    ),
    (
        "Stroke volume is:",
        "The amount of blood ejected by the ventricle per beat",
        ["Heart rate only", "Blood pressure diastolic only", "Lung tidal volume"],
        "Cardiac output = HR × SV.",
        [
            "HR is beats per minute.",
            "BP is vascular pressure.",
            "Tidal volume is respiratory.",
        ],
        "easy",
    ),
    (
        "Which joint type is freely movable with a synovial cavity?",
        "Diarthrosis / synovial joint",
        ["Synarthrosis suture only", "Amphiarthrosis as always immovable", "Fibrous joint with no movement ever by definition of all fibrous joints"],
        "Synovial diarthroses move freely; sutures are immovable synarthroses.",
        [
            "Sutures barely move.",
            "Amphiarthroses are slightly movable.",
            "Some fibrous joints allow minimal motion, but not synovial freedom.",
        ],
        "hard",
    ),
    (
        "Kyphosis refers to:",
        "Excessive convex curvature of the thoracic spine (hunching)",
        ["Excessive lumbar extension only (lordosis definition)", "Scoliosis lateral curve only", "Flat feet only"],
        "Kyphosis = thoracic flexion exaggeration; lordosis = lumbar extension exaggeration; scoliosis = lateral.",
        [
            "Lordosis is lumbar hyperlordosis.",
            "Scoliosis is lateral curvature.",
            "Pes planus is foot posture.",
        ],
        "medium",
    ),
    (
        "Which connective tissue connects bone to bone?",
        "Ligament",
        ["Tendon", "Aponeurosis as identical to ligament always", "Myofibril"],
        "Ligaments stabilize joints; tendons attach muscle to bone.",
        [
            "Tendons are muscle-to-bone.",
            "Aponeuroses are sheet-like tendons/fascia.",
            "Myofibrils are intracellular contractile organelles.",
        ],
        "easy",
    ),
    (
        "During inhalation at rest, the diaphragm primarily:",
        "Contracts and descends, increasing thoracic volume",
        ["Relaxes and ascends as the only inhalation action", "Pumps blood like a ventricle", "Flexes the elbow"],
        "Diaphragm contraction expands the thorax; relaxation assists exhalation at rest.",
        [
            "Relaxation is exhalation at rest.",
            "Diaphragm is respiratory, not cardiac pump.",
            "Diaphragm does not move the elbow.",
        ],
        "medium",
    ),
    (
        "The agonist–antagonist relationship for knee extension is primarily:",
        "Quadriceps agonist; hamstrings antagonist",
        ["Hamstrings agonist for extension; quads antagonist", "Only calves as knee extensors", "Only tibialis anterior as knee extensor"],
        "Quads extend the knee; hamstrings flex and can eccentrically control extension.",
        [
            "Hamstrings flex the knee primarily.",
            "Calves act mainly at the ankle.",
            "Tibialis anterior dorsiflexes.",
        ],
        "easy",
    ),
]

TRAINING = [
    (
        "Progressive overload means:",
        "Gradually increasing training stress so adaptation continues",
        ["Never changing load after week one", "Training through sharp joint pain", "Only stretching forever"],
        "Overload can be load, volume, density, or complexity within recovery capacity.",
        [
            "Stagnation follows no progression.",
            "Pain is a warning.",
            "Stretching alone isn’t full overload for strength.",
        ],
        "easy",
    ),
    (
        "A typical hypertrophy repetition range is approximately:",
        "6–12 reps with challenging loads and sufficient volume",
        ["Only 1 rep at 100% every set forever", "Only 50–100 reps with no load ever", "Zero training days"],
        "Moderate reps and volume are classic hypertrophy guidelines.",
        [
            "Constant max singles are strength peaking.",
            "Ultra-high reps shift endurance.",
            "Stimulus is required.",
        ],
        "easy",
    ),
    (
        "Specificity (SAID) principle states that:",
        "Adaptations match the demands imposed on the system",
        ["All training produces identical adaptations", "Cardio alone maximizes 1RM squat always", "Flexibility training alone maximizes VO2max"],
        "Train the quality and pattern you want to improve.",
        [
            "Adaptations differ by stimulus.",
            "Strength needs resistance specificity.",
            "Aerobic work needs aerobic stimulus.",
        ],
        "easy",
    ),
    (
        "Rest intervals for near-maximal strength sets are commonly:",
        "About 2–5 minutes to restore performance",
        ["0–5 seconds always", "One full day between every set", "No rest by definition"],
        "Neural and phosphagen recovery needs longer rests for heavy loads.",
        [
            "Ultra-short rests cut load quality.",
            "Inter-set rest is minutes.",
            "Rest is planned.",
        ],
        "medium",
    ),
    (
        "Periodization organizes training by:",
        "Planned variation of volume/intensity across cycles (micro/meso/macro)",
        ["Random workouts with no plan ever", "Only one exercise for life", "Avoiding all deloads forever"],
        "Periodization manages fatigue and peaks performance.",
        [
            "Planning beats pure randomness for goals.",
            "Variety across qualities is normal.",
            "Deloads manage fatigue.",
        ],
        "medium",
    ),
    (
        "Compound lifts are valuable because they:",
        "Train multiple joints/muscles and allow heavier systemic loading",
        ["Never elevate heart rate", "Only isolate one muscle fiber", "Replace all need for progression"],
        "Squats, hinges, presses, rows build efficient total-body strength.",
        [
            "Compounds often raise HR.",
            "They are multi-muscle.",
            "Progression still required.",
        ],
        "easy",
    ),
    (
        "FITT-VP variables include:",
        "Frequency, Intensity, Time, Type, Volume, Progression",
        ["Only footwear brand", "Only music genre", "Only gym wall color"],
        "FITT-VP structures cardiorespiratory and conditioning prescriptions.",
        [
            "Brand ≠ training dose.",
            "Music ≠ dose.",
            "Decor ≠ dose.",
        ],
        "medium",
    ),
    (
        "Plyometric training emphasizes:",
        "Stretch-shortening cycle power and reactive ability",
        ["Only static stretching holds of 10 minutes", "Only maximal slow isometrics forever", "Only breath-holding contests"],
        "Plyometrics use rapid eccentric–concentric coupling when the client is prepared.",
        [
            "Static stretch is flexibility.",
            "Isometrics lack SSC speed.",
            "Breath holds aren’t plyometrics.",
        ],
        "medium",
    ),
    (
        "A safe general warm-up aims to:",
        "Raise temperature and rehearse movement patterns without excessive fatigue",
        ["Exhaust the client completely before work sets", "Skip entirely before heavy lifting always as best practice", "Replace cool-downs forever"],
        "Warm-ups prepare tissues and the nervous system.",
        [
            "Fatigue impairs performance.",
            "Warm-ups are recommended.",
            "Cool-downs still have a role.",
        ],
        "easy",
    ),
    (
        "Which cue best fits a hip hinge deadlift pattern?",
        "Push hips back, keep a neutral spine, and load the posterior chain",
        ["Round the lumbar spine maximally under load as the goal", "Squat only with vertical shins never hinging", "Shrug the bar with arms only"],
        "Hinge = hip flexion/extension dominance with spinal bracing.",
        [
            "Loaded lumbar flexion is risky as a goal.",
            "Squat and hinge differ.",
            "Arms are hooks, not prime movers.",
        ],
        "medium",
    ),
    (
        "Circuit training is often used to:",
        "Improve conditioning and work capacity with limited rest between exercises",
        ["Maximize absolute 1RM peaking exclusively", "Eliminate all cardiovascular stimulus", "Guarantee hypertrophy better than any other method always"],
        "Circuits trade some max strength specificity for density/conditioning.",
        [
            "1RM peaking needs longer rests/heavy loads.",
            "Circuits often raise HR.",
            "Hypertrophy depends on tension/volume, not circuits alone.",
        ],
        "medium",
    ),
    (
        "Tempo prescription 3-1-2-0 typically means:",
        "3s eccentric, 1s pause, 2s concentric, 0s top pause (example interpretation)",
        ["Random breathing only", "Only rest days", "Miles per hour of running"],
        "Tempos control time under tension and positions.",
        [
            "Not a breathing code alone.",
            "Not rest scheduling.",
            "Not running speed.",
        ],
        "hard",
    ),
    (
        "Detraining occurs when:",
        "Training stimulus is removed long enough that adaptations reverse",
        ["Someone takes one easy deload day forever losing all fitness instantly always", "Hydration increases", "Sleep improves"],
        "Use-it-or-lose-it applies over weeks more than a single easy day.",
        [
            "Short deloads are planned recovery.",
            "Hydration supports performance.",
            "Sleep supports recovery.",
        ],
        "easy",
    ),
    (
        "Unilateral training can help:",
        "Address side-to-side imbalances and challenge stability",
        ["Guarantee perfect symmetry overnight", "Replace all bilateral work forever for powerlifters peaking", "Eliminate the need for coaching"],
        "Split squats/rows complement bilateral lifts.",
        [
            "Adaptations take time.",
            "Bilateral lifts remain valuable.",
            "Coaching still matters.",
        ],
        "medium",
    ),
    (
        "RPE (rate of perceived exertion) is used to:",
        "Autoregulate intensity based on how hard the set feels",
        ["Measure bone density", "Diagnose ACL tears", "Replace all need for load tracking forever without notes"],
        "RPE complements percentages for day-to-day readiness.",
        [
            "BMD needs medical tests.",
            "Diagnosis is clinical.",
            "Logging still helps even with RPE.",
        ],
        "hard",
    ),
]

SPECIAL = [
    (
        "For apparently healthy older adults, resistance training is generally:",
        "Recommended to preserve muscle, bone, and function with appropriate progressions",
        ["Contraindicated for all adults over 50", "Limited to only finger movements forever", "Replaced entirely by bed rest"],
        "Age-appropriate strength training supports independence; screen and progress wisely.",
        [
            "Age alone is not a ban.",
            "Full-body patterns matter.",
            "Bed rest worsens frailty.",
        ],
        "easy",
    ),
    (
        "A pregnant client (uncomplicated) may often continue exercise with:",
        "Physician guidance, avoiding supine late-pregnancy risks as advised, and monitoring warning signs",
        ["Maximal breath-hold isometric straining competitions", "Contact sports collisions as preferred conditioning", "Ignoring dizziness and vaginal bleeding"],
        "Prenatal exercise is often beneficial with medical clearance and modifications.",
        [
            "Avoid dangerous Valsalva extremes.",
            "Collision risk is inappropriate.",
            "Warning signs need medical care.",
        ],
        "medium",
    ),
    (
        "Youth training should emphasize:",
        "Technique, fun, gradual progressions, and age-appropriate loads",
        ["Maximal lifting to failure daily for 8-year-olds as standard", "Adult bodybuilding peaking cycles exclusively", "Ignoring growth-plate pain"],
        "Skill and habits first; supervise closely.",
        [
            "Daily failure is inappropriate.",
            "Kids aren’t small pro bodybuilders.",
            "Pain needs evaluation.",
        ],
        "easy",
    ),
    (
        "Clients with hypertension (controlled, cleared) should generally:",
        "Favor steady breathing, avoid prolonged maximal Valsalva, and progress aerobically/resistance as cleared",
        ["Perform only max isometric holds breath-holding as the plan", "Skip all medical clearance concerns", "Use stimulants liberally pre-workout despite advice"],
        "BP management and breathing strategies matter; follow clinician guidance.",
        [
            "Breath-holds can spike BP.",
            "Clearance/screening matter.",
            "Stimulants may raise BP.",
        ],
        "medium",
    ),
    (
        "For obese clients new to exercise, a practical start is:",
        "Low-impact cardio and foundational resistance with joint-friendly progressions",
        ["Plyometric depth jumps on day one for everyone", "Only fasting without movement as training", "Maximal Olympic lifts without coaching"],
        "Reduce joint stress and build adherence first.",
        [
            "High impact early risks injury.",
            "Movement matters.",
            "Technical lifts need preparation.",
        ],
        "easy",
    ),
    (
        "A functional movement screen / posture assessment helps trainers:",
        "Identify movement limitations and compensation patterns to guide programming",
        ["Diagnose fractures definitively", "Replace medical imaging", "Prescribe antibiotics"],
        "Screens inform training decisions; they are not medical diagnosis.",
        [
            "Fractures need medical care.",
            "Imaging is clinical.",
            "Medications are out of scope.",
        ],
        "medium",
    ),
    (
        "Clients with osteoporosis (cleared) should often avoid:",
        "High-risk spinal flexion/loaded twisting movements that elevate fracture risk (individualize with clinician input)",
        ["All walking forever", "All balance training", "All protein intake"],
        "Emphasize safe loading and fall prevention; modify spinal stress.",
        [
            "Walking is often beneficial.",
            "Balance training reduces falls.",
            "Protein supports tissue.",
        ],
        "hard",
    ),
    (
        "Asthma clients may need:",
        "Extended warm-ups, trigger awareness, and inhaler access per their action plan",
        ["Smoke-filled rooms as warm-up", "Ignoring prescribed inhalers", "Maximal cold dry sprints without prep as first session always"],
        "Coordinate with medical plans; avoid known triggers.",
        [
            "Smoke worsens asthma.",
            "Follow medical plans.",
            "Cold/intense starts can trigger symptoms.",
        ],
        "medium",
    ),
    (
        "Post-rehab clients returning from physical therapy should:",
        "Obtain clearance, respect precautions, and progress under appropriate communication with the care team when needed",
        ["Jump to advanced plyometrics against PT restrictions", "Diagnose surgical failures", "Stop all medical follow-up as soon as gym access begins"],
        "Scope boundaries and gradual loading protect healing tissues.",
        [
            "Honor restrictions.",
            "Diagnosis is medical.",
            "Follow-up may continue.",
        ],
        "medium",
    ),
    (
        "Body composition assessment via skinfolds estimates:",
        "Subcutaneous fat to estimate body fat percentage using equations",
        ["VO2max directly", "Bone mineral density", "Hydration as the only output"],
        "Skinfolds are field estimates with technician error; interpret cautiously.",
        [
            "VO2 needs cardio tests.",
            "BMD needs DXA/medical tests.",
            "Hydration needs other measures.",
        ],
        "easy",
    ),
    (
        "Clients with Type 2 diabetes (cleared) should be taught to:",
        "Monitor for hypo/hyperglycemia signs around exercise and coordinate with their care plan",
        ["Inject insulin doses decided by the trainer", "Skip all medical appointments", "Use exercise to replace all prescribed medication unilaterally"],
        "Trainers support safe activity; medication changes are medical.",
        [
            "Insulin dosing is clinical.",
            "Medical care continues.",
            "Don’t unilaterally stop meds.",
        ],
        "hard",
    ),
    (
        "Balance training for fall-prone older adults should progress from:",
        "Stable bilateral support → narrower bases → perturbations as safe",
        ["Bosu single-leg eyes-closed with loads on day one for frail clients always", "No standing practice ever", "Only seated reading"],
        "Progress challenge gradually with spotting/support.",
        [
            "Advanced unstable work is late-stage.",
            "Standing practice is key.",
            "Reading isn’t balance training.",
        ],
        "medium",
    ),
    (
        "PAR-Q / health screening is used to:",
        "Identify risk factors needing clearance or modification before exercise",
        ["Measure 1RM bench", "Diagnose cancer", "Set retail prices"],
        "Screening reduces adverse-event risk and guides referral.",
        [
            "Strength testing is separate.",
            "Diagnosis is medical.",
            "Pricing is business.",
        ],
        "easy",
    ),
    (
        "For clients with low back pain history (cleared, non-acute), programming often emphasizes:",
        "Neutral-spine bracing, hip hinging competency, and gradual exposure",
        ["Maximal sit-up contests daily immediately", "Complete bed rest forever as the only option", "Ignoring pain red flags like saddle anesthesia"],
        "Movement quality and load management beat aggressive spinal flexion contests; red flags need medical care.",
        [
            "High-rep loaded flexion may aggravate some clients.",
            "Chronic rest worsens deconditioning.",
            "Red flags require referral.",
        ],
        "hard",
    ),
    (
        "Cardiac rehabilitation phase exercise for post-event clients is typically:",
        "Physician-directed with monitoring—trainers must stay in scope and follow clearance",
        ["Unmanaged maximal HIIT on day one post-MI without clearance", "Trainer-prescribed medication changes", "Ignored ECG/symptom warnings"],
        "Post-cardiac clients need medical oversight; CPT roles are supportive within clearance.",
        [
            "Clearance and progression rules are mandatory.",
            "Meds are clinical.",
            "Symptoms need stopping/referral.",
        ],
        "hard",
    ),
]

NUTRITION_BIZ = [
    (
        "Within ISSA/CPT scope, nutrition guidance should be:",
        "General healthy guidelines and referral to RDs for clinical diets",
        ["Medical nutrition therapy for renal failure prescribed by the trainer", "Diagnosing nutrient deficiencies from a glance", "Stopping physician-prescribed meds for weight loss"],
        "Stay in scope; disease-specific diets need licensed clinicians.",
        [
            "MNT is RD/MD territory.",
            "Diagnosis is medical.",
            "Medication changes need the clinician.",
        ],
        "easy",
    ),
    (
        "Which macronutrient provides the most kcal per gram?",
        "Fat (9 kcal/g)",
        ["Carbohydrate (4)", "Protein (4)", "Alcohol-free water (0) as 9 kcal/g"],
        "Fat ≈9 kcal/g; carb/protein ≈4; alcohol ≈7; water 0.",
        [
            "Carb is ~4.",
            "Protein is ~4.",
            "Water has no calories.",
        ],
        "easy",
    ),
    (
        "Adequate protein supports training by:",
        "Providing amino acids for repair and remodeling of muscle tissue",
        ["Replacing all need for resistance training", "Acting as the only fuel in phosphagen metabolism", "Eliminating sleep requirements"],
        "Protein enables adaptation; training stimulus and recovery still required.",
        [
            "Training stimulus remains essential.",
            "Phosphagen uses ATP/PCr.",
            "Sleep remains critical.",
        ],
        "easy",
    ),
    (
        "Behavior change is more likely when goals are:",
        "Specific, measurable, and supported by environmental cues/habits",
        ["Vague and untracked", "Based only on shame", "Changed every hour without review"],
        "Implementation intentions and monitoring improve adherence.",
        [
            "Vagueness undermines action.",
            "Shame harms rapport.",
            "Stable reviewable goals work better.",
        ],
        "medium",
    ),
    (
        "Client confidentiality requires:",
        "Protecting personal health and training information from unauthorized disclosure",
        ["Posting PR videos without consent", "Sharing charts with friends for fun", "Selling email lists of medical histories"],
        "Privacy builds trust and meets ethical/legal expectations.",
        [
            "Consent needed for media.",
            "Gossip is a breach.",
            "Selling PHI is unethical/illegal.",
        ],
        "easy",
    ),
    (
        "A professional CPT business practice includes:",
        "Clear contracts, truthful marketing, and documented scope boundaries",
        ["Guaranteeing 30 lb fat loss in 10 days for every client", "Using someone else’s certification number", "Training without CPR/AED readiness where required"],
        "Integrity and safety systems reduce liability and build reputation.",
        [
            "Unrealistic guarantees are unethical.",
            "Credential fraud is illegal.",
            "Emergency readiness matters.",
        ],
        "medium",
    ),
    (
        "Motivational interviewing spirit includes:",
        "Partnership, acceptance, compassion, and evocation",
        ["Confrontation only", "Ignoring client autonomy", "Lecturing without listening"],
        "MI elicits the client’s own reasons for change.",
        [
            "Pure confrontation often backfires.",
            "Autonomy is central.",
            "Listening is required.",
        ],
        "medium",
    ),
    (
        "Dehydration can impair performance by:",
        "Increasing cardiovascular strain and reducing heat tolerance",
        ["Improving concentration indefinitely", "Increasing plasma volume always", "Removing the need to drink during long hot sessions"],
        "Fluid deficits raise HR and heat illness risk.",
        [
            "Cognition often worsens.",
            "Plasma volume falls with dehydration.",
            "Rehydration strategies matter in heat.",
        ],
        "medium",
    ),
    (
        "Supplements marketed with disease-cure claims should prompt a trainer to:",
        "Avoid disease-treatment claims and refer clients to qualified clinicians; stay evidence-cautious",
        ["Inject clients in the locker room", "Guarantee FDA drug approval for all powders", "Diagnose disease to sell more bottles"],
        "Supplements are not substitutes for medical care; scope limits apply.",
        [
            "Injections are out of scope.",
            "Most supplements aren’t approved drugs.",
            "Diagnosis/sales pressure is unethical.",
        ],
        "hard",
    ),
    (
        "Which is an open-ended coaching question?",
        "What made it easier to hit your steps on the days you succeeded?",
        ["Did you fail again?", "Be quiet and obey.", "Yes or no: you hate vegetables?"],
        "Open questions explore success factors and barriers.",
        [
            "Judgmental closed prompts harm rapport.",
            "Commands reduce autonomy.",
            "Closed questions limit depth.",
        ],
        "easy",
    ),
    (
        "Sleep restriction chronically tends to:",
        "Impair recovery, hormone regulation, and training performance",
        ["Replace all periodization needs beneficially", "Increase deep recovery beyond normal sleep", "Eliminate appetite dysregulation risk"],
        "Sleep is a primary recovery pillar.",
        [
            "Sleep loss is not a periodization strategy.",
            "Recovery worsens.",
            "Appetite often dysregulates.",
        ],
        "medium",
    ),
    (
        "A client wants a meal plan for diagnosed celiac disease. The CPT should:",
        "Refer to an RD/physician for medical nutrition therapy and avoid practicing dietetics beyond scope",
        ["Design a clinical gluten-free medical protocol as MNT", "Order endoscopy", "Adjust prescriptions"],
        "Celiac MNT is clinical; trainers can support general adherence habits after professional guidance.",
        [
            "Clinical MNT is out of scope.",
            "Procedures are medical.",
            "Meds are medical.",
        ],
        "easy",
    ),
    (
        "Liability risk decreases when trainers:",
        "Screen, document, obtain informed consent, and refer red flags",
        ["Ignore chest pain to finish a session package", "Falsify insurance documents", "Exceed scope with medical procedures"],
        "Risk management is proactive and ethical.",
        [
            "Red flags need stop/refer.",
            "Fraud increases risk.",
            "Scope violations increase risk.",
        ],
        "hard",
    ),
    (
        "NEAT (non-exercise activity thermogenesis) refers to:",
        "Calories burned in daily movement outside formal exercise",
        ["Only resting metabolic rate in a coma", "Only TEF from protein", "Only structured HIIT sessions"],
        "Steps, standing, and chores contribute meaningfully to total expenditure.",
        [
            "RMR is separate.",
            "TEF is feeding effect.",
            "HIIT is exercise activity.",
        ],
        "medium",
    ),
    (
        "Ethical advertising for training services should avoid:",
        "Before/after photo manipulation and unverifiable miracle claims",
        ["Honest descriptions of methods and expected process", "Clear pricing", "Accurate credential listing"],
        "Truthful marketing protects consumers and the profession.",
        [
            "Honesty is appropriate.",
            "Clear pricing is professional.",
            "Accurate credentials are required.",
        ],
        "easy",
    ),
]


def main() -> None:
    write_bank(
        "issa-cpt-readiness-check",
        {
            "anatomy-phys": ANATOMY,
            "training": TRAINING,
            "special-pops": SPECIAL,
            "nutrition-biz": NUTRITION_BIZ,
        },
    )


if __name__ == "__main__":
    main()
