/** NCLEX-PN client-needs style — 60 curated MCQs (15×4) */
export const topics = {
  "safe-care": [
    [
      "Before administering a medication, the LPN/LVN should verify:",
      "Right client, drug, dose, route, time, and documentation (plus allergies/assessment as indicated)",
      [
        "Only the room number without identifiers",
        "That a coworker said it was fine without checking the MAR",
        "Color of the pill alone as the sole check",
      ],
      "Rights of medication administration reduce errors; use two identifiers.",
      [
        "Room number is not a unique ID.",
        "Always verify yourself.",
        "Appearance alone is insufficient.",
      ],
      "easy",
    ],
    [
      "A client on fall precautions should have:",
      "Call light in reach, nonskid footwear, bed in low position, and clutter-free path as appropriate",
      [
        "All four side rails up as soft restraints without an order for convenience",
        "Socks with slick soles encouraged for speed",
        "Call light placed across the room to encourage walking alone at night",
      ],
      "Fall prevention is multifactorial; restraints require orders and least-restrictive approach.",
      [
        "Four side rails can be restraint.",
        "Nonskid footwear needed.",
        "Call light must be reachable.",
      ],
      "easy",
    ],
    [
      "When receiving a telephone order, the nurse should:",
      "Write it down and read back to the provider for confirmation per facility policy",
      [
        "Guess incomplete doses without clarifying",
        "Ask a visitor to take the order",
        "Document later from memory after several hours without read-back",
      ],
      "Read-back prevents verbal order errors.",
      [
        "Clarify incomplete orders.",
        "Only licensed staff take orders.",
        "Timely accurate documentation required.",
      ],
      "medium",
    ],
    [
      "Priority action when a fire is discovered in a client room (RACE) begins with:",
      "Rescue/remove clients in immediate danger",
      [
        "Running to post on social media",
        "Collecting personal belongings first for all staff",
        "Ignoring the alarm if it is inconvenient",
      ],
      "RACE: Rescue, Alarm, Contain, Extinguish/Evacuate as trained.",
      [
        "Not social media.",
        "People before property.",
        "Respond to alarms.",
      ],
      "easy",
    ],
    [
      "Proper use of a gait belt includes:",
      "Applying snugly around the waist over clothing and holding underhand while ambulating as appropriate",
      [
        "Using it to lift a client vertically alone from the floor after an unwitnessed fall without assessment",
        "Applying over bare skin tightly enough to bruise intentionally",
        "Attaching it to a wheelchair to drag the client",
      ],
      "Gait belts assist balance; post-fall assessment precedes moving.",
      [
        "Assess injuries first; get help.",
        "Avoid skin injury.",
        "Do not drag.",
      ],
      "medium",
    ],
    [
      "Sterile technique is required for:",
      "Inserting an indwelling urinary catheter (as typically taught)",
      [
        "Taking an oral temperature with a clean probe cover",
        "Feeding a client a meal",
        "Making an unoccupied bed with clean linen",
      ],
      "Invasive procedures that enter sterile body cavities require aseptic/sterile technique.",
      [
        "Clean technique for oral temp.",
        "Feeding uses clean technique.",
        "Bedmaking is clean.",
      ],
      "medium",
    ],
    [
      "A client with a known latex allergy needs:",
      "Latex-free gloves/equipment and allergy communication on the chart/band per policy",
      [
        "Increased latex exposure to desensitize in the hospital without order",
        "No allergy documentation",
        "Powdered latex gloves preferentially",
      ],
      "Allergy prevention is a safety priority.",
      [
        "Do not challenge latex casually.",
        "Document clearly.",
        "Avoid latex products.",
      ],
      "easy",
    ],
    [
      "When prioritizing care using ABC/safety, which client does the LPN see first?",
      "A client with new stridor and difficulty breathing after a procedure",
      [
        "A client requesting a snack refill",
        "A client needing routine linen change",
        "A client asking what time discharge teaching will occur later today",
      ],
      "Airway/breathing threats outrank comfort and routine tasks.",
      [
        "Snack is low priority.",
        "Linen is routine.",
        "Teaching scheduling is lower acuity.",
      ],
      "medium",
    ],
    [
      "Incident reports should be:",
      "Objective, factual, and completed per policy without blaming language in the medical record narrative improperly",
      [
        "Copied into the chart as a punitive essay naming coworkers with speculation",
        "Hidden if no one noticed",
        "Used to threaten clients",
      ],
      "Incident reports improve systems; follow facility documentation rules carefully.",
      [
        "Keep charting factual; follow policy on referencing reports.",
        "Reporting is required.",
        "Not a threat tool.",
      ],
      "hard",
    ],
    [
      "Safe narcotic counts require:",
      "Two authorized nurses verifying discrepancies per policy before end of shift when required",
      [
        "One person discarding leftovers without witness when policy requires witness",
        "Borrowing meds from another client’s drawer",
        "Documenting waste after leaving the unit",
      ],
      "Controlled substance accountability is a legal safety requirement.",
      [
        "Witnessed waste often required.",
        "Never borrow client meds.",
        "Document at time of waste.",
      ],
      "medium",
    ],
    [
      "For a client in contact precautions, the nurse should:",
      "Wear gown and gloves for contact with the client/environment as indicated and dedicate equipment when possible",
      [
        "Skip hand hygiene because gloves were worn",
        "Take the isolation gown to the cafeteria",
        "Share BP cuffs without cleaning when dedicated gear is required",
      ],
      "Transmission-based precautions prevent MDRO spread; hand hygiene after PPE removal.",
      [
        "Hygiene still required.",
        "PPE stays in care area.",
        "Clean/dedicated equipment rules apply.",
      ],
      "easy",
    ],
    [
      "A client refuses a medication. The LPN should:",
      "Explore concerns, educate, withhold as refused, notify the provider/RN per policy, and document",
      [
        "Crush and hide it in food without consent",
        "Force the client’s mouth open",
        "Document as given when it was not",
      ],
      "Informed refusal is a client right; covert meds without consent are unethical/illegal.",
      [
        "Covert administration is improper.",
        "Forcing is assault.",
        "False documentation is fraud.",
      ],
      "medium",
    ],
    [
      "Which action reduces healthcare-associated infection risk with urinary catheters?",
      "Maintain a closed drainage system and keep the bag below bladder level",
      [
        "Routine daily irrigation with tap water for all clients",
        "Disconnect tubing frequently to “rinse”",
        "Place the bag on the abdomen during transport for convenience",
      ],
      "CAUTI prevention bundles emphasize closed systems and dependent drainage.",
      [
        "Avoid unnecessary irrigation.",
        "Don’t break the closed system.",
        "Bag below bladder.",
      ],
      "medium",
    ],
    [
      "When using a fire extinguisher (PASS):",
      "Pull pin, Aim at base, Squeeze, Sweep",
      [
        "Spray toward people’s faces first",
        "Aim at the top of flames only always",
        "Ignore the pin and throw the extinguisher",
      ],
      "PASS is standard extinguisher training.",
      [
        "Never aim at people.",
        "Aim at the base of the fire.",
        "Use properly.",
      ],
      "easy",
    ],
    [
      "Delegation to UAP is appropriate for:",
      "Stable clients’ routine vital signs and hygiene within UAP training",
      [
        "Initial teaching of a complex insulin regimen",
        "Assessment of a new onset chest pain",
        "Titration of IV vasoactive drips",
      ],
      "LPNs/RNs retain assessment, teaching, and unstable client judgment tasks per state NPA.",
      [
        "Teaching is nursing role.",
        "New chest pain needs licensed assessment.",
        "IV vasoactive titration is beyond UAP/typically RN.",
      ],
      "hard",
    ],
  ],
  "health-promo": [
    [
      "Primary prevention aims to:",
      "Prevent disease before it occurs (e.g., immunizations, safety education)",
      [
        "Only provide hospice care",
        "Treat end-stage complications exclusively",
        "Ignore screening recommendations",
      ],
      "Primary = prevention; secondary = screening; tertiary = limit disability.",
      [
        "Hospice is tertiary/supportive.",
        "Treatment of advanced disease is tertiary.",
        "Screening is secondary prevention.",
      ],
      "easy",
    ],
    [
      "A 65-year-old client should be encouraged regarding vaccines to discuss with the provider:",
      "Age-appropriate immunizations such as influenza annually and others per CDC adult schedule",
      [
        "Never receiving any vaccines after age 30",
        "Only childhood vaccines repeated yearly without guidance",
        "Avoiding all preventive care visits",
      ],
      "LPNs reinforce vaccine education; schedules update—refer to current CDC guidance/provider.",
      [
        "Older adults still need vaccines.",
        "Follow adult schedules.",
        "Preventive visits matter.",
      ],
      "easy",
    ],
    [
      "Teaching about sunscreen should include:",
      "Use broad-spectrum SPF as directed, reapply, and seek shade—especially peak UV hours",
      [
        "Sunburn is required for vitamin D and is harmless",
        "Tanning beds are risk-free",
        "Sunscreen makes skin cancer more likely always",
      ],
      "UV protection is skin cancer primary prevention.",
      [
        "Sunburn damages DNA.",
        "Tanning beds increase risk.",
        "Sunscreen reduces risk when used properly.",
      ],
      "easy",
    ],
    [
      "A client with hypertension is learning lifestyle measures. Which teaching point is appropriate?",
      "Reduce sodium intake, maintain healthy weight, exercise as approved, and take meds as prescribed",
      [
        "Stop all medications if you feel well without contacting the provider",
        "Add unlimited salt substitutes without checking potassium risks if on certain meds",
        "Ignore blood pressure checks at home if advised",
      ],
      "Lifestyle + adherence; don’t stop antihypertensives abruptly without guidance.",
      [
        "Don’t stop meds unsupervised.",
        "Some salt substitutes are high in K+.",
        "Monitoring supports control.",
      ],
      "medium",
    ],
    [
      "Prenatal teaching: folic acid is emphasized early to help prevent:",
      "Neural tube defects",
      [
        "Dental caries in the neonate exclusively",
        "Clubbing of adult fingers",
        "Sensorineural hearing loss from cerumen",
      ],
      "Folic acid before/early pregnancy reduces NTD risk.",
      [
        "Not the primary folic acid rationale.",
        "Unrelated.",
        "Unrelated.",
      ],
      "medium",
    ],
    [
      "Safe sleep teaching for infants includes:",
      "Place infant supine on a firm surface without soft bedding/loose blankets",
      [
        "Stomach sleeping with pillows in the crib",
        "Co-sleeping on soft couches as preferred teaching",
        "Bumper pads and stuffed toys filling the crib",
      ],
      "AAP safe sleep: alone, back, crib—reduces SIDS risk.",
      [
        "Prone with soft items increases risk.",
        "Unsafe sleep surfaces are hazardous.",
        "Soft objects increase suffocation risk.",
      ],
      "easy",
    ],
    [
      "Secondary prevention example:",
      "Mammography screening per guidelines",
      [
        "Influenza immunization before flu season",
        "Physical therapy after a completed stroke to maximize function",
        "Wearing a seat belt every time you drive",
      ],
      "Screening detects disease early (secondary). Immunizations and seat belts are primary; rehab after disease is tertiary.",
      [
        "Immunizations are primary prevention.",
        "Rehab after stroke is tertiary prevention.",
        "Seat belts are primary prevention.",
      ],
      "hard",
    ],
    [
      "A client learning breast self-awareness should be taught to report:",
      "New lumps, nipple discharge, skin changes, or persistent breast changes",
      [
        "Only changes that are painful, ignoring painless lumps",
        "Nothing until annual visits even if a hard fixed mass appears",
        "Normal cyclic tenderness as an emergency every month without pattern context",
      ],
      "Painless lumps still need evaluation; know personal baselines.",
      [
        "Painless masses matter.",
        "Prompt evaluation of new masses.",
        "Cyclic changes can be normal—teach patterns vs red flags.",
      ],
      "medium",
    ],
    [
      "Smoking cessation counseling by nurses is important because tobacco use:",
      "Increases risk of cancer, heart disease, stroke, and respiratory disease",
      [
        "Has no health effects",
        "Protects against COPD",
        "Is recommended in pregnancy",
      ],
      "Ask-Advise-Refer style brief interventions are part of health promotion.",
      [
        "Strong causal harms exist.",
        "Tobacco causes COPD risk.",
        "Contraindicated in pregnancy.",
      ],
      "easy",
    ],
    [
      "Growth charts in pediatrics are used to:",
      "Track patterns of weight/height/head circumference over time",
      [
        "Diagnose all genetic diseases alone",
        "Replace immunizations",
        "Determine adult career aptitude",
      ],
      "Trends matter more than single points; report crossing major percentiles per protocol.",
      [
        "Not sole genetic diagnosis.",
        "Vaccines remain essential.",
        "Unrelated to careers.",
      ],
      "easy",
    ],
    [
      "Teaching for a client starting a new exercise program after sedentary lifestyle should include:",
      "Start gradually, get provider clearance if high risk, and stop for chest pain/severe dyspnea",
      [
        "Begin with maximal heavy lifting daily without assessment",
        "Ignore chest pain as normal",
        "Avoid hydration intentionally",
      ],
      "Progressive activity with warning-sign education is safer.",
      [
        "Gradual progression safer.",
        "Chest pain needs evaluation.",
        "Hydrate appropriately.",
      ],
      "medium",
    ],
    [
      "Dental health teaching for preschoolers includes:",
      "Supervised brushing with a rice-grain/smear of fluoride toothpaste as age-appropriate and limiting sugary drinks",
      [
        "Putting the child to bed with a bottle of juice routinely",
        "Never cleaning teeth until age 10",
        "Sharing toothbrushes among siblings",
      ],
      "Early dental habits prevent caries; avoid juice bottles at bedtime.",
      [
        "Bottle juice promotes caries.",
        "Start oral care early.",
        "No sharing brushes.",
      ],
      "medium",
    ],
    [
      "Osteoporosis prevention teaching for older adults often includes:",
      "Weight-bearing exercise as tolerated, calcium/vitamin D per provider, and fall prevention",
      [
        "Complete bedrest to protect bones",
        "Avoiding all dairy/alternatives without plan when deficient",
        "Removing grab bars to encourage independence via risk",
      ],
      "Bone health + fall risk reduction prevents fractures.",
      [
        "Immobility worsens bone loss.",
        "Address deficiencies properly.",
        "Grab bars prevent falls.",
      ],
      "medium",
    ],
    [
      "A client asks when routine colorectal cancer screening often begins for average risk adults (general U.S. guidance knowledge):",
      "Around age 45 for average-risk adults per updated USPSTF-aligned counseling—confirm with provider",
      [
        "Only after age 90",
        "Never if asymptomatic, ever",
        "At age 15 for everyone as colonoscopy mandatory yearly",
      ],
      "Screening ages evolve; nurses teach to follow current guidelines/provider advice (commonly starting mid-40s now).",
      [
        "Far too late as a general rule.",
        "Screening targets asymptomatic average-risk adults.",
        "Yearly colonoscopy from 15 is not standard average-risk guidance.",
      ],
      "hard",
    ],
    [
      "Health literacy–friendly teaching uses:",
      "Plain language, teach-back, and limited key points with written materials at appropriate level",
      [
        "Only medical jargon to sound professional",
        "Long uninterrupted lectures without checking understanding",
        "Assuming all clients read at college level",
      ],
      "Teach-back confirms understanding and improves adherence.",
      [
        "Jargon blocks understanding.",
        "Check understanding.",
        "Assess literacy needs.",
      ],
      "easy",
    ],
  ],
  "psychosocial": [
    [
      "A client says, “I feel like life is not worth living.” Priority nursing action is to:",
      "Ask directly about suicidal ideation and plans and ensure safety/notify the RN-provider per protocol",
      [
        "Change the subject to the weather permanently",
        "Leave the client alone for privacy for several hours without assessment",
        "Promise total confidentiality even if there is an imminent plan",
      ],
      "Direct screening and safety trump avoidance; duty to protect limits confidentiality when harm is imminent.",
      [
        "Do not avoid.",
        "Do not isolate without safety plan.",
        "Safety exceptions to confidentiality apply.",
      ],
      "hard",
    ],
    [
      "Therapeutic communication technique—restating—means:",
      "Repeating the main idea to show listening and encourage clarification",
      [
        "Giving false reassurance “everything will be fine”",
        "Asking “why would you do that?” judgmentally",
        "Talking about your own divorce details extensively",
      ],
      "Restating/reflecting facilitate expression; avoid “why” and false reassurance.",
      [
        "False reassurance blocks feelings.",
        "“Why” feels accusatory.",
        "Keep focus on client.",
      ],
      "easy",
    ],
    [
      "A client with alcohol use disorder is hospitalized for detox. Priority concern early is:",
      "Safety monitoring for withdrawal complications (e.g., seizures, DT risk) per protocol",
      [
        "Scheduling career counseling as the first hour priority over medical monitoring",
        "Allowing unlimited visitors bringing alcohol",
        "Ignoring CIWA/assessment tools ordered",
      ],
      "Physiologic withdrawal can be life-threatening; medical stabilization first.",
      [
        "Psychosocial later once stable.",
        "No alcohol access.",
        "Use ordered withdrawal assessments.",
      ],
      "medium",
    ],
    [
      "Defense mechanism: projection is:",
      "Attributing one’s own unacceptable feelings to others",
      [
        "Returning to earlier developmental behaviors",
        "Consciously deciding to postpone attention to a stressor temporarily (suppression)",
        "Channeling impulses into socially acceptable activity (sublimation)",
      ],
      "Know common defense mechanisms for psychosocial integrity items.",
      [
        "Regression is returning to earlier behaviors.",
        "Suppression is conscious postponement.",
        "Sublimation redirects impulses constructively.",
      ],
      "hard",
    ],
    [
      "For a client with dementia who is agitated at sundown, helpful approaches include:",
      "Calm environment, consistent caregivers, toileting/pain check, and simple reassurance",
      [
        "Arguing about the exact year repeatedly for long periods",
        "Overstimulating with multiple loud activities at once",
        "Using restraints as first-line without assessment",
      ],
      "Address unmet needs; least restrictive measures first.",
      [
        "Arguments escalate.",
        "Overstimulation worsens agitation.",
        "Restraints last resort.",
      ],
      "medium",
    ],
    [
      "Grief that is delayed or inhibited may appear as:",
      "Minimal emotional expression initially with later unexpected distress",
      [
        "Only joyful celebration without any loss context ever",
        "A vital sign value",
        "A type of microorganism",
      ],
      "Recognize complicated grief patterns and support/refer.",
      [
        "Grief varies culturally—but delayed grief is a recognized pattern.",
        "Not a vital sign.",
        "Not a microbe.",
      ],
      "medium",
    ],
    [
      "A client with schizophrenia says, “The TV is telling me to hurt myself.” The nurse should:",
      "Take the command hallucination seriously, assess safety, and report promptly for evaluation",
      [
        "Agree that the TV is a reliable commander",
        "Leave without assessing intent",
        "Whisper about the client in the hallway within earshot",
      ],
      "Command hallucinations require urgent safety assessment.",
      [
        "Don’t reinforce delusions/commands.",
        "Assess immediately.",
        "Maintain privacy/dignity.",
      ],
      "hard",
    ],
    [
      "Anxiety reduction before surgery can be aided by:",
      "Providing clear procedural information and allowing questions",
      [
        "Withholding all information to prevent worry",
        "Making jokes about death in the OR",
        "Skipping consent discussion",
      ],
      "Information reduces fear of the unknown; informed consent remains essential.",
      [
        "Information helps.",
        "Inappropriate humor harms trust.",
        "Consent is required.",
      ],
      "easy",
    ],
    [
      "Domestic violence screening should be conducted:",
      "Privately, with sensitivity, and with knowledge of resources/reporting laws",
      [
        "Only with the partner present translating",
        "As accusations in front of visitors",
        "Never in healthcare settings",
      ],
      "Screen alone; follow mandatory reporting rules for vulnerable populations/state laws.",
      [
        "Partner presence may silence disclosure.",
        "Privacy required.",
        "Healthcare screens routinely.",
      ],
      "medium",
    ],
    [
      "A client with bulimia nervosa after purging needs monitoring for:",
      "Electrolyte imbalances and dental/esophageal injury risks",
      [
        "Only high hemoglobin as the sole issue",
        "Improved enamel strength",
        "Hyperkalemia exclusively always",
      ],
      "Purging risks hypokalemia, alkalosis, enamel erosion—safety priority.",
      [
        "Electrolytes more critical than Hgb alone.",
        "Enamel erodes.",
        "Hypokalemia is the classic concern.",
      ],
      "hard",
    ],
    [
      "Cultural competence includes:",
      "Asking about health beliefs/preferences rather than stereotyping",
      [
        "Assuming all members of a group share identical beliefs",
        "Refusing interpreters to save time",
        "Mocking ritual practices",
      ],
      "Assess individuals; use qualified interpreters.",
      [
        "Avoid stereotypes.",
        "Interpreters improve safety.",
        "Respect practices within safety/law.",
      ],
      "easy",
    ],
    [
      "Milieu therapy refers to:",
      "Using the therapeutic environment and structured interactions to support recovery",
      [
        "Only intramuscular medications",
        "Surgical debridement",
        "Dietary tray color coding alone",
      ],
      "Psychiatric nursing uses milieu as a treatment tool.",
      [
        "Meds may be part of care but aren’t the definition.",
        "Not surgical.",
        "Not just tray colors.",
      ],
      "medium",
    ],
    [
      "When a client is angry and pacing, an appropriate initial approach is:",
      "Maintain safe distance, calm tone, offer to listen, and ensure exit access for staff",
      [
        "Cornering the client in a small room alone",
        "Matching anger with yelling",
        "Touching suddenly from behind",
      ],
      "De-escalation prioritizes safety and respect.",
      [
        "Don’t trap.",
        "Stay calm.",
        "Avoid startling touch.",
      ],
      "easy",
    ],
    [
      "A client facing limb amputation expresses body image disturbance. The nurse should:",
      "Encourage expression of feelings and involve rehab/support resources",
      [
        "Say “at least you’re alive” as the only response and leave",
        "Forbid looking at the site forever",
        "Ignore the topic as unimportant",
      ],
      "Body image work is legitimate psychosocial care.",
      [
        "Toxic positivity blocks processing.",
        "Gradual viewing may be therapeutic with support.",
        "Address psychosocial needs.",
      ],
      "medium",
    ],
    [
      "Confidentiality in mental health settings means:",
      "Protect PHI while explaining limits (harm to self/others, abuse reporting)",
      [
        "Sharing details in the elevator for teaching without need",
        "Posting client stories online anonymized poorly with identifiers",
        "Promising never to report child abuse disclosures",
      ],
      "Tarasoff-type duties and mandated reporting create limits to confidentiality.",
      [
        "No elevator PHI.",
        "No social media PHI.",
        "Abuse reporting is mandatory.",
      ],
      "medium",
    ],
  ],
  "physio": [
    [
      "A client with heart failure has 2+ pitting edema and crackles. Priority nursing action is often to:",
      "Elevate HOB, monitor SpO2/respiratory status, and report changes; administer ordered diuretics/O2 per plan",
      [
        "Encourage large free-water boluses immediately",
        "Place flat supine for comfort only without assessment",
        "Stop all ordered weights and I&O",
      ],
      "Fluid overload threatens gas exchange; follow ABC and orders.",
      [
        "Excess fluid worsens HF.",
        "Upright often helps breathing.",
        "Weights/I&O are essential monitoring.",
      ],
      "medium",
    ],
    [
      "Hypoglycemia in a conscious client who can swallow is treated with:",
      "15 g rapid-acting carbohydrate, recheck per protocol (15-15 rule variants)",
      [
        "IV insulin bolus by the LPN without order",
        "Ignoring diaphoresis and confusion",
        "Exercise immediately without treating glucose",
      ],
      "Treat low glucose first; unresponsive clients need emergency glucagon/IV dextrose per protocol/RN-provider.",
      [
        "Insulin lowers glucose further.",
        "Symptoms need action.",
        "Exercise can worsen hypoglycemia.",
      ],
      "easy",
    ],
    [
      "A client on warfarin should be taught to:",
      "Keep vitamin K intake consistent and report bleeding/bruising; keep INR appointments",
      [
        "Double doses if a meal is missed without guidance",
        "Start high-dose NSAIDs freely for pain without checking interactions",
        "Stop warfarin the day before dental cleaning without telling providers",
      ],
      "Anticoagulation teaching focuses on consistency, bleeding signs, and interaction awareness.",
      [
        "Don’t self-adjust doses.",
        "NSAIDs increase bleed risk.",
        "Coordinate holds with providers.",
      ],
      "medium",
    ],
    [
      "Post-op client with PCA morphine is difficult to arouse with RR 6/min. Priority action:",
      "Stop the PCA/opioids per protocol, support airway/breathing, stimulate, and notify RN/provider; prepare naloxone as ordered",
      [
        "Give another opioid dose for sleep",
        "Leave to finish charting first",
        "Encourage family to press the PCA button repeatedly",
      ],
      "Opioid-induced respiratory depression is an emergency.",
      [
        "More opioid worsens depression.",
        "Stay and intervene.",
        "Only the client presses PCA.",
      ],
      "hard",
    ],
    [
      "Signs of wound infection include:",
      "Increasing redness, warmth, purulent drainage, odor, fever",
      [
        "Approximated edges with scant serous drainage on day 1 only as definitive infection",
        "Normal pruritus of healing without other signs as infection proof",
        "Absent drainage and afebrile state as infection",
      ],
      "Differentiate normal inflammatory healing from infection; report changes.",
      [
        "Early scant serous can be expected.",
        "Itch alone isn’t infection.",
        "Those suggest no infection.",
      ],
      "easy",
    ],
    [
      "A client with COPD should be taught pursed-lip breathing to:",
      "Prolong exhalation and prevent airway collapse/air trapping",
      [
        "Breathe as rapidly as possible at all times",
        "Hold breath for 2 minutes repeatedly",
        "Avoid any controlled breathing techniques",
      ],
      "Pursed-lip breathing improves ventilation patterns in COPD.",
      [
        "Tachypnea worsens trapping.",
        "Long breath holds unsafe.",
        "Techniques are helpful.",
      ],
      "easy",
    ],
    [
      "Potassium chloride IV should never be:",
      "Given as an IV push/bolus",
      [
        "Given as a diluted infusion per policy when ordered",
        "Monitored with labs when replacement is underway",
        "Held when hyperkalemia is present per order",
      ],
      "IVP KCl can cause fatal dysrhythmias; infusions use pumps/dilution rules.",
      [
        "Controlled infusion is the route.",
        "Labs guide therapy.",
        "Hold if high K+.",
      ],
      "hard",
    ],
    [
      "For a client with a cast, report immediately:",
      "Increasing pain, pallor, paresthesia, pulselessness, paralysis (compartment syndrome signs)",
      [
        "Mild itching under the cast without neurovascular change",
        "Ability to wiggle toes with warm pink color",
        "Normal capillary refill <2–3 seconds",
      ],
      "Compartment syndrome is limb-threatening—escalate ASAP.",
      [
        "Mild itch can occur.",
        "Good NV status is reassuring.",
        "Normal CRT is expected.",
      ],
      "medium",
    ],
    [
      "NG tube placement verification before feeding is best confirmed by:",
      "Facility-required method (often x-ray initially; pH/markings per policy)—never by air auscultation alone as sole method",
      [
        "Instilling a large feeding immediately after blind insertion without verification",
        "Asking the roommate if it looks right",
        "Checking only that tape is present",
      ],
      "Misplacement risks aspiration; follow current verification standards.",
      [
        "Verify first.",
        "Roommate opinion invalid.",
        "Tape ≠ correct placement.",
      ],
      "hard",
    ],
    [
      "A client with dehydration may show:",
      "Tachycardia, dry mucous membranes, poor skin turgor, concentrated urine",
      [
        "Bounding pulses and wet crackles as the only dehydration signs",
        "Jugular venous distention as classic dehydration",
        "Polyuria with dilute urine as dehydration hallmark always",
      ],
      "Volume depletion signs guide fluid resuscitation orders and monitoring.",
      [
        "Those suggest fluid overload.",
        "JVD suggests overload/right heart issues.",
        "Oliguria/concentrated urine more typical.",
      ],
      "easy",
    ],
    [
      "Insulin lispro (rapid-acting) should generally be given:",
      "At mealtime / when the tray is present per timing rules (onset ~15 min)",
      [
        "Once weekly only regardless of meals",
        "Without regard to food, then leaving the client NPO for hours intentionally",
        "Mixed freely into IV TPN bags by LPN without protocol",
      ],
      "Match rapid insulin to carbohydrate intake to prevent hypoglycemia.",
      [
        "Meal-related dosing.",
        "Food timing critical.",
        "IV insulin is RN/protocol territory typically.",
      ],
      "medium",
    ],
    [
      "Early hypoxia sign often includes:",
      "Restlessness and tachycardia",
      [
        "Cyanosis as the earliest reliable sign always",
        "Bradypnea as the first change in all clients",
        "Warm dry skin exclusively",
      ],
      "Late signs include cyanosis; act on early mental status/VS changes.",
      [
        "Cyanosis is late.",
        "Often tachypnea first.",
        "Cool/clammy or diaphoresis may occur—not warm dry as classic early hypoxia.",
      ],
      "medium",
    ],
    [
      "A client receiving a blood transfusion develops chills, fever, and back pain. The nurse should:",
      "Stop the transfusion, keep IV line open with NS per protocol, notify provider, and follow transfusion reaction steps",
      [
        "Speed up the transfusion to finish faster",
        "Ignore symptoms for 30 minutes",
        "Give a second unit immediately through the same tubing without evaluation",
      ],
      "Suspect acute hemolytic/febrile reaction—stop blood, maintain access, escalate.",
      [
        "Do not speed up.",
        "Immediate action required.",
        "Don’t add more blood.",
      ],
      "hard",
    ],
    [
      "Left-sided weakness after stroke: nursing care includes:",
      "Approach from the intact side as appropriate, protect the weak side, and use assistive devices per PT plan",
      [
        "Pulling by the weak arm to reposition",
        "Ignoring aspiration risk at meals",
        "Placing food on the weak side of the mouth intentionally without assessment",
      ],
      "Safety and rehab principles guide hemiparesis care; dysphagia screens matter.",
      [
        "Never pull weak/flaccid shoulders.",
        "Aspiration is major risk.",
        "Food placement follows swallow evaluation.",
      ],
      "medium",
    ],
    [
      "Digitalis toxicity warning signs to report include:",
      "Anorexia, nausea, visual changes (halos), and bradycardia/dysrhythmias",
      [
        "Improved appetite only as toxicity",
        "Isolated happiness without physical signs",
        "Hyperactivity with tachycardia exclusively as the classic dig toxicity pattern",
      ],
      "Narrow therapeutic index—monitor apical pulse and labs (K+, dig level) per orders.",
      [
        "GI/visual/cardiac signs are classic.",
        "Not a mood diagnosis.",
        "Bradycardia more classic than isolated tachycardia.",
      ],
      "hard",
    ],
  ],
};
