/** NHA CBCS — 60 curated MCQs (15×4) */
export const topics = {
  "coding-guidelines": [
    [
      "In ICD-10-CM, codes are generally reported to the highest level of specificity supported by documentation. What does that mean?",
      "Use the most detailed valid code that matches the documented diagnosis",
      [
        "Always use three-character category codes only",
        "Round all diagnoses to the nearest body system",
        "Code symptoms instead of confirmed diagnoses whenever possible",
      ],
      "ICD-10-CM guidelines require coding to the highest specificity supported by the record; truncating without reason can cause denials.",
      [
        "Three-character codes are used only when no further subdivision exists.",
        "Body-system rounding is not a coding rule.",
        "When a definitive diagnosis is documented, code it rather than symptoms alone.",
      ],
      "easy",
    ],
    [
      "A provider documents “rule out pneumonia” in an outpatient encounter. How should the coder generally proceed for outpatient ICD-10-CM?",
      "Code the signs/symptoms or confirmed conditions documented; do not code “rule out” as if confirmed",
      [
        "Always assign the pneumonia code as primary",
        "Assign Z00.00 for every rule-out visit",
        "Omit all diagnosis codes until culture returns",
      ],
      "Outpatient guidelines: do not code uncertain diagnoses as if established; code the documented symptoms/findings instead.",
      [
        "Coding unconfirmed conditions as established is incorrect outpatient practice.",
        "Z00.00 is for general adult exams without abnormal findings, not every rule-out.",
        "Claims still need reportable diagnoses based on available documentation.",
      ],
      "medium",
    ],
    [
      "Which CPT concept best describes a procedure that is always included in another procedure and generally not separately reportable?",
      "Bundled / integral component of a more comprehensive service",
      [
        "Add-on code that must stand alone",
        "Unlisted procedure requiring no documentation",
        "Place-of-service modifier only",
      ],
      "NCCI and CPT bundling concepts prevent separate payment for integral components already included in a primary service.",
      [
        "Add-on codes are reported with a primary code, not as standalone bundled services.",
        "Unlisted codes still require documentation and often special reporting.",
        "POS is not the bundling concept.",
      ],
      "medium",
    ],
    [
      "When selecting an E/M office visit level under current AMA CPT guidelines (MDM or time), the coder should primarily rely on:",
      "The provider’s documented medical decision making or total time on the date of the encounter",
      [
        "Only the number of bullets historically used in 1995 exam checklists",
        "The patient’s preference for a higher level",
        "The charge master price alone",
      ],
      "Office/outpatient E/M levels are selected by MDM or total time; outdated bullet counting is not the current standard.",
      [
        "1995/1997 bullet systems are no longer the primary office E/M method.",
        "Patient preference does not set CPT level.",
        "Price is not a coding criterion.",
      ],
      "medium",
    ],
    [
      "A CPT modifier used to indicate a significant, separately identifiable E/M service on the same day as a procedure is:",
      "Modifier 25",
      ["modifier 59", "modifier 26", "modifier 51"],
      "Modifier 25 is used when an E/M is significant and separately identifiable from the procedure on the same day.",
      [
        "59 is for distinct procedural services, not E/M with procedure.",
        "26 indicates professional component.",
        "51 indicates multiple procedures.",
      ],
      "easy",
    ],
    [
      "Which statement about HCPCS Level II codes is correct?",
      "They commonly identify supplies, drugs, and certain services not in CPT",
      [
        "They replace ICD-10-CM for all diagnoses",
        "They are only used for inpatient DRG grouping",
        "They are identical to CPT Category III codes",
      ],
      "HCPCS Level II covers many non-CPT items (DME, drugs, some services) for billing.",
      [
        "Diagnoses remain ICD-10-CM/PCS as applicable.",
        "DRGs use ICD diagnosis/procedure grouping, not HCPCS alone.",
        "Category III CPT codes are temporary CPT tracking codes, not HCPCS II.",
      ],
      "easy",
    ],
    [
      "Sequencing of the principal/first-listed diagnosis should reflect:",
      "The main reason for the encounter/admission as defined by official guidelines",
      [
        "Whichever code pays the highest amount",
        "The alphabetically first diagnosis in the chart",
        "Only chronic conditions, never acute problems",
      ],
      "Official sequencing rules prioritize the condition chiefly responsible for the visit/admission, not payment maximization.",
      [
        "Coding for payment rather than guidelines is noncompliant.",
        "Alphabetical order is not a sequencing rule.",
        "Acute problems often drive sequencing when they are the reason for care.",
      ],
      "medium",
    ],
    [
      "Laterality in ICD-10-CM means the coder should:",
      "Select right, left, bilateral, or unspecified codes when the classification provides them and documentation supports them",
      [
        "Always default to bilateral for any paired organ",
        "Ignore side because payers do not care",
        "Use only unspecified laterality to avoid audits",
      ],
      "When laterality is available and documented, use the specific side; unspecified is used only when documentation lacks detail.",
      [
        "Bilateral is not a default without documentation.",
        "Payers and guidelines expect accurate laterality.",
        "Defaulting to unspecified when detail exists is incorrect.",
      ],
      "easy",
    ],
    [
      "A claim lists a CPT procedure without a diagnosis that supports medical necessity. The most likely result is:",
      "Denial or request for additional documentation for lack of medical necessity link",
      [
        "Automatic upgrade to a higher paying code",
        "Conversion of CPT to ICD-10-PCS by the payer",
        "Immediate fraud conviction without review",
      ],
      "Procedure–diagnosis linkage and medical necessity are core claim requirements; mismatches commonly cause denials.",
      [
        "Payers do not upgrade codes for missing necessity.",
        "Code set conversion is not how necessity denials work.",
        "Denial/review precedes any legal action; do not overstate.",
      ],
      "medium",
    ],
    [
      "Category II CPT codes are primarily used for:",
      "Performance measurement / quality tracking, not typically for payment of the service itself",
      [
        "Replacing all Evaluation and Management codes",
        "Reporting inpatient operating room procedures only",
        "Identifying ambulance mileage exclusively",
      ],
      "Category II codes support quality/performance reporting and are supplemental.",
      [
        "E/M remains Category I.",
        "OR procedures use Category I / ICD-10-PCS as applicable.",
        "Ambulance mileage uses HCPCS, not Category II broadly.",
      ],
      "hard",
    ],
    [
      "When a code description says “separate procedure,” it typically means:",
      "It is usually not reported when performed with a related, more comprehensive procedure in the same area",
      [
        "It must always be billed twice",
        "It can never be reported under any circumstance",
        "It is only for Medicare Advantage plans",
      ],
      "“Separate procedure” designation signals limited separate reporting when a larger related service is performed.",
      [
        "Double billing is not appropriate.",
        "It may be reportable when truly independent/unrelated per rules.",
        "The concept is CPT-wide, not plan-specific.",
      ],
      "hard",
    ],
    [
      "ICD-10-CM Excludes1 notes generally indicate:",
      "The two conditions should not be coded together (mutually exclusive) when the note applies",
      [
        "The codes must always be billed as a pair",
        "The note can be ignored if the charge is high",
        "Only HCPCS is affected",
      ],
      "Excludes1 means not coded together (with limited exceptions noted in guidelines); Excludes2 means not included here but both may be coded if present.",
      [
        "Excludes1 is not a pairing requirement.",
        "Guidelines cannot be ignored for payment.",
        "Excludes notes are ICD-10-CM concepts.",
      ],
      "hard",
    ],
    [
      "For CPT surgery coding, the global surgical package commonly includes:",
      "The procedure and typical related preoperative/postoperative care within the global period, as defined by payer rules",
      [
        "All unrelated E/M visits forever",
        "Only the anesthesia professional fee",
        "Hospital room and board charges coded as CPT",
      ],
      "Global periods bundle routine related pre/post care with the surgery; unrelated services may be separately reportable with modifiers when rules allow.",
      [
        "Unrelated care is not endlessly bundled.",
        "Anesthesia is often billed separately by anesthesia providers.",
        "Facility charges are not the same as CPT surgeon global package.",
      ],
      "medium",
    ],
    [
      "A coder finds conflicting documentation between a progress note and an operative report. Best practice is to:",
      "Query the provider for clarification before final coding when the conflict affects code selection",
      [
        "Always pick the code that reimburses more",
        "Delete the operative report from the record",
        "Code both conflicting diagnoses as primary",
      ],
      "Compliant coding requires resolving conflicts via query/clarification rather than guessing for revenue.",
      [
        "Payment-driven selection is abusive.",
        "Altering records improperly is prohibited.",
        "Two primaries from a conflict is not the fix.",
      ],
      "medium",
    ],
    [
      "Which is true about Z codes (ICD-10-CM factors influencing health status)?",
      "They may be used as primary or secondary per guideline when they describe the reason for the encounter",
      [
        "They are never allowed on any claim",
        "They replace CPT for procedures",
        "They are only for dental claims",
      ],
      "Z codes report encounters for circumstances other than disease/injury and can be first-listed when appropriate (e.g., aftercare, screening).",
      [
        "Z codes are widely used when guidelines support them.",
        "Procedures remain CPT/HCPCS/PCS.",
        "Z codes are not dental-only.",
      ],
      "easy",
    ],
  ],
  "claims-reimbursement": [
    [
      "On a professional CMS-1500 claim, the rendering provider’s NPI is typically reported to identify:",
      "Who performed the service",
      [
        "The patient’s employer tax ID only",
        "The ICD-10 guidelines version",
        "The pharmacy NDC exclusively",
      ],
      "Rendering NPI identifies the clinician who provided the service; billing NPI may differ in group settings.",
      [
        "Employer tax ID is not the rendering NPI purpose.",
        "Guideline version is not an NPI field.",
        "NDCs identify drugs, not rendering clinicians.",
      ],
      "easy",
    ],
    [
      "A clean claim is best described as:",
      "A complete, accurate claim that can be processed without needing additional information for basic adjudication",
      [
        "Any claim submitted twice in one day",
        "A claim missing diagnosis codes on purpose",
        "A claim sent only by fax",
      ],
      "Clean claims reduce delays; they include required data elements and pass initial edits.",
      [
        "Duplicate submission is not “clean.”",
        "Missing required data creates unclean claims.",
        "Submission method alone does not define cleanliness.",
      ],
      "easy",
    ],
    [
      "Coordination of benefits (COB) is needed when:",
      "A patient has more than one active payer and primary/secondary order must be determined",
      [
        "The patient has no insurance",
        "Only cash-pay encounters occur",
        "The provider changes office paint colors",
      ],
      "COB establishes which plan pays first so secondary billing is correct.",
      [
        "Uninsured patients have no COB.",
        "Cash-pay skips insurance COB.",
        "Irrelevant to benefits.",
      ],
      "easy",
    ],
    [
      "An explanation of benefits (EOB) / electronic remittance advice primarily shows:",
      "How the payer adjudicated the claim, including payment, adjustments, and patient responsibility",
      [
        "The provider’s personal credit score",
        "Only the patient’s appointment preferences",
        "A new CPT manual for the year",
      ],
      "EOBs/ERAs communicate payer decisions and amounts; billers use them for posting and appeals.",
      [
        "Credit scores are unrelated.",
        "Scheduling prefs are not remittance data.",
        "Code books are separate publications.",
      ],
      "easy",
    ],
    [
      "A common reason for claim rejection at the clearinghouse level is:",
      "Missing or invalid required data elements (e.g., NPI, DOB, diagnosis pointer)",
      [
        "The patient liking the physician",
        "Correct ICD and CPT linkage with all fields complete",
        "Timely filing within payer limits",
      ],
      "Front-end edits catch format/validity errors before payer adjudication.",
      [
        "Patient satisfaction is not an edit.",
        "Complete accurate claims should pass basic edits.",
        "Timely filing is a payer denial reason later, not a typical clearinghouse format reject.",
      ],
      "medium",
    ],
    [
      "Timely filing limits refer to:",
      "The deadline after the date of service by which a claim must be submitted to the payer",
      [
        "How long a patient may wait in the lobby",
        "The shelf life of paper superbills only",
        "The number of modifiers allowed",
      ],
      "Missing timely filing often causes non-appealable denials; billers track payer-specific deadlines.",
      [
        "Lobby wait is unrelated.",
        "Not limited to paper superbills.",
        "Modifier count is a coding/edit issue.",
      ],
      "easy",
    ],
    [
      "A deductible is:",
      "The amount a patient must pay out of pocket before certain plan benefits pay",
      [
        "The provider’s Medicare participation status",
        "A type of CPT Category III code",
        "The clearinghouse enrollment fee only",
      ],
      "Deductibles are patient cost-sharing features that affect balances after adjudication.",
      [
        "Participation is a provider-payer contract status.",
        "Not a CPT category.",
        "Enrollment fees are administrative, not patient deductibles.",
      ],
      "easy",
    ],
    [
      "When a claim is denied as “not medically necessary,” the biller’s first compliance-oriented step is often to:",
      "Review documentation, coding, and payer policy; correct if needed or appeal with clinical support",
      [
        "Change the diagnosis to whatever pays without documentation",
        "Bill the patient for fraud penalties",
        "Delete the encounter from the EHR",
      ],
      "Appeals and corrections must be documentation-supported; fabricating codes is improper.",
      [
        "Upscoding/diagnosis shopping is abusive.",
        "Patients are not billed “fraud penalties” as a routine AR step.",
        "Deleting encounters improperly is prohibited.",
      ],
      "medium",
    ],
    [
      "Place of service (POS) codes on professional claims indicate:",
      "Where the service was rendered (e.g., office, outpatient hospital, telehealth setting as applicable)",
      [
        "The patient’s home ZIP only for all claims",
        "The ICD-10-CM seventh character",
        "The anesthesia ASA physical status",
      ],
      "POS affects pricing and coverage; it must match the actual setting.",
      [
        "ZIP is address data, not POS.",
        "Seventh characters are diagnosis coding.",
        "ASA status is anesthesia-specific.",
      ],
      "medium",
    ],
    [
      "A National Drug Code (NDC) is most relevant when billing:",
      "Certain drugs/biologicals that payers require with HCPCS drug codes",
      [
        "Routine office visit E/M without medications",
        "ICD-10-CM Z-code screenings only",
        "Ambulance mileage exclusively",
      ],
      "Many payers require NDC detail for injectable/drug claims alongside HCPCS.",
      [
        "Pure E/M without drugs typically needs no NDC.",
        "Z codes are diagnoses, not NDCs.",
        "Mileage uses other HCPCS units.",
      ],
      "medium",
    ],
    [
      "Which action best supports successful secondary payer billing?",
      "Submit the secondary claim with primary EOB/ERA data showing what primary paid and adjusted",
      [
        "Bill secondary first in every case",
        "Ignore COB and bill both as primary duplicates",
        "Omit diagnosis codes on secondary claims",
      ],
      "Secondaries need primary adjudication details to process remaining liability correctly.",
      [
        "Order is determined by COB rules.",
        "Duplicate primary billing creates overpayments/denials.",
        "Diagnoses remain required.",
      ],
      "medium",
    ],
    [
      "An Advance Beneficiary Notice (ABN) in Medicare contexts is used when:",
      "A provider expects Medicare may deny a service as not reasonable/necessary and must inform the beneficiary before furnishing it",
      [
        "Every claim automatically needs an ABN",
        "It replaces the CMS-1500 form",
        "It is only for workers’ compensation",
      ],
      "ABNs shift financial liability appropriately when Medicare denial is expected for certain reasons; improper use can be invalid.",
      [
        "Not required for all services.",
        "ABN is a notice, not a claim form.",
        "It is a Medicare (and similar) concept, not WC-only.",
      ],
      "hard",
    ],
    [
      "Capitation payment models typically mean:",
      "The plan pays a per-member periodic amount; providers manage care within that budget",
      [
        "Every CPT line is paid fee-for-service at full charge",
        "Patients pay the entire billed amount always",
        "ICD codes are no longer reported",
      ],
      "Capitation is prospective PMPM-style payment; claims/encounter data may still be required for tracking.",
      [
        "That describes fee-for-service.",
        "Patients still have cost-shares per plan, not always full charges.",
        "Diagnoses remain important.",
      ],
      "hard",
    ],
    [
      "A frequency limit denial usually indicates:",
      "The service exceeds how often the payer covers it in a time period",
      [
        "The provider’s NPI checksum failed",
        "The patient never had insurance",
        "The claim had no date of service",
      ],
      "Payers set unit/frequency edits (e.g., preventive visits, certain therapies).",
      [
        "NPI issues are different edits.",
        "Uninsured is eligibility, not frequency.",
        "Missing DOS is a separate reject.",
      ],
      "medium",
    ],
    [
      "Which statement about remittance remark/CARC codes is correct?",
      "They explain why payment differs from the charge (denial, CO, PR, etc.)",
      [
        "They replace the need for CPT codes on future claims",
        "They are patient vital signs",
        "They are only printed on superbills",
      ],
      "Claim adjustment reason codes communicate adjudication logic for posting and appeals.",
      [
        "They do not replace CPT.",
        "Not clinical vitals.",
        "They appear on remits, not as superbill content.",
      ],
      "easy",
    ],
  ],
  "compliance-privacy": [
    [
      "Under HIPAA, protected health information (PHI) includes:",
      "Individually identifiable health information held or transmitted by a covered entity/business associate in any form",
      [
        "Only paper charts stored on-site",
        "De-identified data with no identifiers remaining",
        "Publicly posted clinic hours",
      ],
      "PHI covers identifiable health info in electronic, paper, or oral forms when held by covered entities/BAs.",
      [
        "Electronic and oral PHI are also covered.",
        "Properly de-identified data is not PHI.",
        "Hours alone are not PHI.",
      ],
      "easy",
    ],
    [
      "The HIPAA minimum necessary standard generally requires that workforce members:",
      "Access/use/disclose only the PHI needed to perform their job duties",
      [
        "Share full charts with any caller who asks",
        "Post diagnoses on social media for education",
        "Email PHI to personal accounts for convenience",
      ],
      "Minimum necessary limits unnecessary PHI exposure; treatment-related access has specific nuances but curiosity viewing is prohibited.",
      [
        "Verify identity and authority before disclosures.",
        "Social media PHI sharing is a breach risk.",
        "Personal email is typically prohibited.",
      ],
      "easy",
    ],
    [
      "A billing specialist notices a coworker accessing a celebrity patient’s record without a work need. The specialist should:",
      "Report the incident per organizational privacy policy",
      [
        "Ignore it if the coworker is a friend",
        "Access the same record to compare notes",
        "Print the record for home review",
      ],
      "Unauthorized access is a privacy incident; reporting protects patients and the organization.",
      [
        "Friendship does not authorize access.",
        "Additional snooping worsens the violation.",
        "Removing PHI is improper.",
      ],
      "medium",
    ],
    [
      "Upcoding is best defined as:",
      "Reporting a higher-level or more complex service than documentation supports",
      [
        "Using the correct code that matches documentation",
        "Adding a diagnosis pointer on a claim form",
        "Verifying insurance eligibility",
      ],
      "Upcoding is a common fraud/abuse risk when levels or procedures are inflated.",
      [
        "Accurate coding is compliant.",
        "Pointers are normal claim mechanics.",
        "Eligibility checks are appropriate.",
      ],
      "easy",
    ],
    [
      "Unbundling refers to:",
      "Billing component codes separately when a comprehensive code includes them, contrary to rules",
      [
        "Combining unrelated patients onto one claim",
        "Using one diagnosis for multiple encounters correctly",
        "Encrypting email attachments",
      ],
      "Unbundling to increase payment violates NCCI/coding rules when components are not separately reportable.",
      [
        "Each patient needs proper claims.",
        "Diagnosis reuse across encounters can be legitimate.",
        "Encryption is a security control.",
      ],
      "medium",
    ],
    [
      "The False Claims Act risk is heightened when a practice:",
      "Knowingly submits claims that are false or fraudulent for payment",
      [
        "Appeals a denial with supporting records",
        "Documents medical necessity thoroughly",
        "Uses certified EHR audit logs",
      ],
      "Knowingly false claims (including reckless disregard) create FCA exposure; good-faith appeals differ.",
      [
        "Proper appeals are appropriate.",
        "Strong documentation supports compliance.",
        "Audit logs support security/compliance.",
      ],
      "medium",
    ],
    [
      "A valid authorization for non-routine PHI disclosure generally must include:",
      "A description of information, purpose, who may disclose/receive, expiration, and signature",
      [
        "Only the patient’s nickname",
        "A blank form with no purpose stated",
        "The coder’s personal cell number as the recipient",
      ],
      "HIPAA authorization core elements ensure the patient understands and limits the disclosure.",
      [
        "Identity must be clear.",
        "Purpose and specifics are required.",
        "Recipients must be appropriate/identified.",
      ],
      "medium",
    ],
    [
      "Which is an example of a potential HIPAA breach requiring assessment?",
      "A laptop with unencrypted ePHI is stolen from a car",
      [
        "A nurse discusses a patient in a private treatment room with the care team",
        "Filing a claim to the patient’s health plan for treatment payment",
        "Using a fax cover sheet to a known provider number for continuity of care",
      ],
      "Lost/stolen unencrypted devices with ePHI commonly trigger breach risk assessment and possible notification.",
      [
        "Treatment communications among the team are permitted uses.",
        "Payment to health plans is a permitted purpose.",
        "Appropriate care coordination disclosures can be allowed.",
      ],
      "medium",
    ],
    [
      "Stark Law (physician self-referral) generally concerns:",
      "Physician referrals for certain designated health services to entities with which they have financial relationships, subject to exceptions",
      [
        "Only overtime pay for billers",
        "FDA drug manufacturing",
        "State board cosmetology licenses",
      ],
      "Stark is a strict-liability self-referral statute for DHS; billing/coding staff should escalate suspect arrangements.",
      [
        "Wage issues are labor law.",
        "FDA is separate.",
        "Cosmetology is unrelated.",
      ],
      "hard",
    ],
    [
      "Anti-Kickback Statute concerns typically involve:",
      "Offering or receiving remuneration to induce referrals for federal healthcare program business",
      [
        "Normal salary for employed clinicians within fair market value without referral inducement analysis needs never",
        "Patient copay collection as required by plan",
        "Publishing a clinic’s phone number",
      ],
      "AKS is intent-based; improper gifts, sham consulting, or volume-based incentives tied to referrals are high risk.",
      [
        "Bona fide employment can fit safe harbors when structured properly—still not “never analyze.”",
        "Collecting allowed cost-shares is normal.",
        "Public contact info is fine.",
      ],
      "hard",
    ],
    [
      "Business associates under HIPAA are entities that:",
      "Perform functions involving PHI for a covered entity and generally need a BAA",
      [
        "Are always the patient’s family members",
        "Never touch PHI by definition",
        "Only include the IRS",
      ],
      "Billing companies, clearinghouses, and many vendors are BAs and require agreements and safeguards.",
      [
        "Family members are not BAs by default.",
        "BAs do handle PHI.",
        "IRS is not the BA definition.",
      ],
      "easy",
    ],
    [
      "Waiving copays routinely for all insured patients to gain business may create compliance risk because:",
      "It can implicate inducement/beneficiary incentive and payer contract/fraud concerns",
      [
        "Copays are illegal in the United States",
        "HIPAA forbids collecting any money",
        "CPT guidelines ban patient responsibility",
      ],
      "Routine waiver of cost-sharing can be problematic; financial hardship policies should be documented and applied carefully.",
      [
        "Cost-sharing is legal and common.",
        "HIPAA does not ban billing.",
        "CPT does not eliminate patient responsibility.",
      ],
      "hard",
    ],
    [
      "The best practice when emailing claim details containing PHI is to:",
      "Use approved secure methods per policy (encryption/portal) and verify recipients",
      [
        "Send from a personal Gmail to any address",
        "CC public listservs for faster payment",
        "Include full SSN in the subject line",
      ],
      "Security Rule expectations and policies require reasonable safeguards for ePHI in transit.",
      [
        "Personal accounts are typically prohibited.",
        "Public CCs are a breach.",
        "SSNs in subjects are high risk.",
      ],
      "easy",
    ],
    [
      "Qui tam actions related to healthcare fraud allow:",
      "Private persons (whistleblowers) to bring certain False Claims Act cases on behalf of the government",
      [
        "Patients to prescribe controlled substances",
        "Coders to change medical records freely",
        "Payers to skip remittance advice forever",
      ],
      "Whistleblower provisions are a major FCA enforcement pathway; compliance programs encourage internal reporting first.",
      [
        "Prescribing authority is clinical/legal licensure.",
        "Record falsification is prohibited.",
        "Remits remain standard.",
      ],
      "hard",
    ],
    [
      "When a patient requests an accounting of disclosures, the covered entity generally must:",
      "Provide an accounting of certain disclosures as required by the Privacy Rule, with allowed exceptions",
      [
        "Refuse all patient rights requests automatically",
        "Only give accounting to marketers",
        "Post the accounting on Facebook",
      ],
      "Patients have rights to access, amendments (with process), and accounting of certain disclosures.",
      [
        "Patient rights must be honored per HIPAA.",
        "Accounting is for the individual, not marketers.",
        "Public posting would be a violation.",
      ],
      "medium",
    ],
  ],
  "revenue-cycle": [
    [
      "Front-end revenue cycle activities typically include:",
      "Scheduling, registration, insurance verification, and collecting accurate demographics",
      [
        "Only writing off bad debt after years",
        "Appeals after final denial exclusively",
        "Coding the operative report before the patient arrives for a new problem",
      ],
      "Clean data at registration prevents many denials downstream.",
      [
        "Write-offs are back-end.",
        "Appeals are mid/back-end.",
        "You cannot code future undocumented surgeries.",
      ],
      "easy",
    ],
    [
      "Eligibility verification before a visit helps to:",
      "Confirm active coverage, plan rules, and often referral/authorization needs",
      [
        "Guarantee the claim will never deny for any reason",
        "Replace the need for diagnosis coding",
        "Determine the patient’s blood type",
      ],
      "Eligibility reduces surprises but does not eliminate all denial risks (medical necessity, coding, etc.).",
      [
        "Denials can still occur.",
        "Diagnoses remain required.",
        "Blood type is clinical.",
      ],
      "easy",
    ],
    [
      "A referral (in managed care) is typically:",
      "Authorization from a PCP/plan allowing the patient to see a specialist or obtain certain services",
      [
        "The patient’s thank-you card",
        "A CPT modifier for bilateral procedures",
        "The hospital’s charge description master",
      ],
      "Missing referrals/authorizations are common preventable denials in HMO-style plans.",
      [
        "Not a greeting card.",
        "Modifiers are coding tools.",
        "CDM is a pricing/charge list.",
      ],
      "easy",
    ],
    [
      "Charge capture means:",
      "Recording all billable services/supplies provided so they can be coded and billed",
      [
        "Deleting charges to hide productivity",
        "Only collecting copays in cash",
        "Turning off the practice management system",
      ],
      "Missed charges lose revenue; phantom charges create compliance risk—accuracy matters both ways.",
      [
        "Deleting legitimate charges improperly harms revenue integrity.",
        "Copays are only one collection step.",
        "Systems must remain operational for RCM.",
      ],
      "easy",
    ],
    [
      "Days in accounts receivable (A/R) measures:",
      "How long, on average, claims/balances remain unpaid",
      [
        "Patient satisfaction stars only",
        "The number of exam rooms",
        "Vaccine refrigerator temperature",
      ],
      "A/R days is a core RCM KPI; high days may signal denial, follow-up, or posting problems.",
      [
        "Satisfaction is separate.",
        "Room count is operations.",
        "Cold-chain is clinical ops.",
      ],
      "medium",
    ],
    [
      "Patient estimates / good-faith estimates support:",
      "Transparency about expected out-of-pocket costs before or at service",
      [
        "Guaranteed final bills with zero variance always",
        "Elimination of EOBs",
        "Skipping insurance filing forever",
      ],
      "Estimates improve collections and compliance with price transparency expectations; final adjudication may differ.",
      [
        "Estimates can change with clinical reality.",
        "EOBs still issue after claims.",
        "Insured claims are still filed.",
      ],
      "medium",
    ],
    [
      "A denial management workflow should prioritize:",
      "Root-cause analysis, correction, timely appeal/rebill, and prevention at the front end",
      [
        "Resubmitting the identical unclean claim daily forever without review",
        "Writing off every denial immediately without analysis",
        "Ignoring payer policies",
      ],
      "Effective denial management fixes causes and meets appeal deadlines.",
      [
        "Blind resubmits worsen edits.",
        "Blanket write-offs destroy recoverable revenue.",
        "Policies drive successful appeals.",
      ],
      "medium",
    ],
    [
      "Credit balances in patient accounts should be:",
      "Investigated and refunded or corrected per payer/patient rules and law",
      [
        "Kept indefinitely as clinic profit without review",
        "Moved to the physician’s personal account",
        "Ignored if under $10,000 without policy",
      ],
      "Credit balance compliance (including Medicare) requires timely resolution; retaining overpayments is risky.",
      [
        "Keeping overpayments can be improper.",
        "Personal diversion is theft.",
        "Thresholds must follow law/policy—not casual ignore.",
      ],
      "hard",
    ],
    [
      "Which front-desk practice improves point-of-service collections?",
      "Verifying benefits and collecting known copays/outstanding balances per policy before or at visit",
      [
        "Never discussing money with patients",
        "Promising that insurance always pays 100%",
        "Collecting a random amount unrelated to benefits",
      ],
      "Clear communication and accurate benefit knowledge improve POS collections without misrepresentation.",
      [
        "Financial discussions are appropriate and expected.",
        "Guaranteeing 100% payment is often false.",
        "Amounts should match benefits/policy.",
      ],
      "easy",
    ],
    [
      "A charge description master (CDM) / fee schedule alignment issue can cause:",
      "Wrong CPT/HCPCS mapped to charges, leading to billing errors or compliance risk",
      [
        "Improved ICD-10 laterality automatically",
        "HIPAA authorization signatures",
        "Vaccine potency increases",
      ],
      "CDM maintenance is critical so charges map to correct codes and prices.",
      [
        "Laterality is diagnosis coding.",
        "Authorizations are privacy forms.",
        "Not a clinical vaccine effect.",
      ],
      "medium",
    ],
    [
      "Prior authorization failure most often results in:",
      "Denial of payment for the service when the plan required auth and it was not obtained",
      [
        "Automatic increase in E/M level",
        "Conversion to inpatient DRG for all office visits",
        "Deletion of the patient’s demographics",
      ],
      "Many high-cost services need auth; staff should verify before scheduling/performing when required.",
      [
        "Auth issues do not raise E/M.",
        "Office visits are not DRGs.",
        "Demographics remain.",
      ],
      "easy",
    ],
    [
      "Encounter forms / superbills are most useful when they:",
      "Reflect commonly used accurate diagnoses and procedures and are updated with coding changes",
      [
        "List only the highest paying codes regardless of services",
        "Omit diagnoses to save time",
        "Are never reviewed after CPT updates",
      ],
      "Outdated superbills drive wrong coding; they are tools, not substitutes for documentation.",
      [
        "Listing codes for inducement is abusive.",
        "Diagnoses are required.",
        "Annual code updates must be maintained.",
      ],
      "medium",
    ],
    [
      "Soft denials differ from hard denials in that soft denials often:",
      "Can be corrected and resubmitted (e.g., missing info) without a formal appeal",
      [
        "Can never be fixed",
        "Always indicate criminal fraud",
        "Only apply to dental claims",
      ],
      "Understanding denial type guides whether to rebill, appeal, or write off.",
      [
        "Many soft denials are fixable.",
        "Most denials are administrative/clinical coverage—not automatic fraud.",
        "Applies across specialties.",
      ],
      "hard",
    ],
    [
      "Patient statements should generally:",
      "Clearly show balances, insurance pending vs patient responsibility, and payment options",
      [
        "Include other patients’ names for comparison",
        "Hide the dates of service",
        "List staff Social Security numbers",
      ],
      "Clear statements aid collections and reduce call volume; privacy must be maintained.",
      [
        "Other patients’ PHI is a violation.",
        "DOS helps patients recognize services.",
        "Staff SSNs must never appear.",
      ],
      "easy",
    ],
    [
      "Revenue cycle analytics that track top denial reasons help organizations to:",
      "Target training, payer contract issues, and process fixes where losses concentrate",
      [
        "Eliminate the need for coding staff",
        "Stop verifying eligibility",
        "Ignore medical necessity documentation",
      ],
      "Data-driven denial prevention is a hallmark of mature RCM programs.",
      [
        "Coders remain essential.",
        "Eligibility remains critical.",
        "Necessity documentation remains essential.",
      ],
      "medium",
    ],
  ],
};
