/** NNAAP CNA knowledge — 60 curated MCQs (15×4) */
export const topics = {
  "adls-safety": [
    [
      "When transferring a resident from bed to wheelchair, the NA should first:",
      "Lock the wheelchair brakes and ensure nonskid footwear if used",
      [
        "Pull the resident by the arms quickly",
        "Leave the bed at the highest position without explanation",
        "Skip explaining the transfer to save time",
      ],
      "Brakes, footwear, bed height, and clear communication prevent falls.",
      [
        "Arm pulling risks injury.",
        "Safe height and explanation matter.",
        "Explain before moving.",
      ],
      "easy",
    ],
    [
      "The safest way to turn a dependent resident in bed is to:",
      "Use draw sheets/assistance and keep the spine in alignment per care plan",
      [
        "Twist only the shoulders forcefully",
        "Pull by the head of the bed alone",
        "Ask another resident to yank the legs",
      ],
      "Logrolling/assistance protects skin and musculoskeletal injury.",
      [
        "Forceful twisting injures.",
        "Head pulling is unsafe.",
        "Untrained helpers risk harm.",
      ],
      "easy",
    ],
    [
      "A gait belt is used to:",
      "Provide a secure hold to assist ambulation/transfers when appropriate",
      [
        "Restrain a resident in a chair for staff convenience",
        "Lift a resident by the belt alone from the floor after a fall without assessment",
        "Replace the need for footwear",
      ],
      "Gait belts aid safe mobility; they are not punitive restraints.",
      [
        "Improper restraint use is prohibited.",
        "Post-fall assessment comes first.",
        "Footwear still matters.",
      ],
      "easy",
    ],
    [
      "Oral care for an unconscious resident typically includes:",
      "Positioning on the side, using swabs per protocol, and protecting the airway",
      [
        "Giving large gulps of water",
        "Skipping mouth care because they cannot ask",
        "Brushing while fully flat supine with pooling water",
      ],
      "Aspiration precautions guide unconscious oral hygiene.",
      [
        "Large water volumes risk aspiration.",
        "Mouth care is still required.",
        "Side-lying reduces aspiration risk.",
      ],
      "medium",
    ],
    [
      "When dressing a resident with a weak right arm, the NA should:",
      "Put the weaker arm into clothing first and remove it last",
      [
        "Force the weak arm last into tight sleeves roughly",
        "Leave the resident undressed for privacy of staff",
        "Dress the strong side first always as the only rule",
      ],
      "Weak side first when dressing; opposite when undressing—reduces pain/strain.",
      [
        "Rough handling harms.",
        "Dignity requires covering/dressing.",
        "Strong side first is the undressing pattern.",
      ],
      "medium",
    ],
    [
      "To prevent pressure injuries, the NA should:",
      "Reposition immobile residents at least every 2 hours (or per care plan) and keep skin clean/dry",
      [
        "Massage reddened bony areas vigorously",
        "Leave wet linens to “air dry” on the skin",
        "Keep the head of bed at 90° continuously for all residents",
      ],
      "Pressure relief and moisture control are core prevention strategies.",
      [
        "Do not massage reddened areas.",
        "Moisture promotes breakdown.",
        "High Fowler’s increases shear for some; follow plan.",
      ],
      "easy",
    ],
    [
      "A resident is sliding down in bed. The NA should:",
      "Use proper lift/assist techniques and enough help; avoid dragging the skin",
      [
        "Drag by the armpits alone",
        "Yank the ankles",
        "Ignore skin shearing risk",
      ],
      "Shearing contributes to pressure injuries; use draw sheets and teamwork.",
      [
        "Armpit dragging injures.",
        "Ankle yanking is unsafe.",
        "Shear must be minimized.",
      ],
      "medium",
    ],
    [
      "Perineal care should be performed:",
      "From front to back for females, using clean areas of the washcloth, maintaining privacy and dignity",
      [
        "From back to front for females routinely",
        "Without gloves",
        "With the curtain open to the hallway",
      ],
      "Front-to-back reduces UTI risk; standard precautions and privacy apply.",
      [
        "Back-to-front increases contamination.",
        "Gloves are required.",
        "Privacy is required.",
      ],
      "easy",
    ],
    [
      "If a resident starts to fall while ambulating, the NA should:",
      "Control the fall and lower the resident gently to the floor protecting the head, then call for help",
      [
        "Try to catch and carry them alone upright at all costs",
        "Step away so they fall freely",
        "Immediately apply a restraint",
      ],
      "Safe fall techniques reduce injury to resident and NA; then assess and report.",
      [
        "Catching upright often injures both.",
        "Abandonment worsens injury.",
        "Restraints are not the fall response.",
      ],
      "medium",
    ],
    [
      "Range-of-motion exercises should be:",
      "Performed as ordered, supporting joints, stopping if pain occurs, and reporting changes",
      [
        "Forced past the point of severe pain",
        "Skipped permanently if the resident is tired once",
        "Done only on the neck with rapid circling for all residents",
      ],
      "ROM preserves mobility; never force through pain; follow care plan.",
      [
        "Forcing causes injury.",
        "Follow the plan; communicate fatigue.",
        "Neck ROM is cautious/specific—not vigorous for all.",
      ],
      "medium",
    ],
    [
      "A bedpan should be offered:",
      "With privacy, proper positioning, and hand hygiene before/after",
      [
        "While visitors remain at the bedside without asking the resident",
        "Without gloves if the NA is “used to it”",
        "Only once per day regardless of need",
      ],
      "Elimination assistance requires dignity and infection control.",
      [
        "Ask about privacy preferences.",
        "Gloves are required.",
        "Respond to need/orders.",
      ],
      "easy",
    ],
    [
      "When making an occupied bed, the NA should:",
      "Keep the resident covered for privacy/warmth and use side rails per policy for safety during turning",
      [
        "Expose the entire body to the room",
        "Leave the resident on the edge without support",
        "Shake dirty linen in the air in the room",
      ],
      "Occupied bedmaking maintains safety, dignity, and infection control.",
      [
        "Minimize exposure.",
        "Support against falls.",
        "Do not shake linen—spread microbes.",
      ],
      "easy",
    ],
    [
      "Adaptive devices for eating (e.g., built-up utensils) are used to:",
      "Promote independence for residents with limited grip or coordination",
      [
        "Punish slow eaters",
        "Replace all feeding assistance needs automatically without assessment",
        "Allow staff to skip mealtime monitoring for dysphagia risk",
      ],
      "Restorative care supports function; still follow dysphagia precautions.",
      [
        "Not punitive.",
        "Assessment guides use.",
        "Aspiration risk still needs observation.",
      ],
      "medium",
    ],
    [
      "Before helping a resident into the shower, the NA should:",
      "Check water temperature (safely warm), ensure grab bars/nonslip surfaces, and stay within safety guidelines",
      [
        "Use the hottest water available",
        "Leave a confused resident alone behind a locked door",
        "Ignore wet floors",
      ],
      "Burns and falls are major shower risks.",
      [
        "Hot water burns.",
        "Supervision per care plan.",
        "Wet floors cause falls.",
      ],
      "easy",
    ],
    [
      "Elastic stockings (TED hose) should be applied:",
      "On clean dry legs, without wrinkles, as ordered—usually in the morning",
      [
        "Over open draining ulcers without nursing direction",
        "So tight that toes are blue and numb without reporting",
        "Inside out with large wrinkles at the ankles",
      ],
      "Wrinkles and incorrect fit impair circulation; report skin/neurovascular changes.",
      [
        "Open wounds need clinical direction.",
        "Cyanosis/numbness = remove per protocol and report.",
        "Smooth application required.",
      ],
      "hard",
    ],
  ],
  "infection-vitals": [
    [
      "Standard precautions mean the NA should:",
      "Use hand hygiene and appropriate PPE for all residents as indicated",
      [
        "Only wash hands if visibly soiled monthly",
        "Share razors between residents to save cost",
        "Skip gloves for blood contact if in a hurry",
      ],
      "Treat all blood/body fluids as potentially infectious.",
      [
        "Hygiene frequency is high.",
        "Never share personal care items that risk blood exposure.",
        "Gloves for blood are required.",
      ],
      "easy",
    ],
    [
      "The most important measure to prevent infection spread is:",
      "Hand hygiene",
      [
        "Wearing jewelry in the sink",
        "Using the resident’s toothbrush on another person",
        "Leaving bedpans uncleaned",
      ],
      "Hand hygiene is the single most effective infection-control practice.",
      [
        "Jewelry hinders cleaning.",
        "Cross-use spreads pathogens.",
        "Clean equipment matters—but hands are #1.",
      ],
      "easy",
    ],
    [
      "A normal adult oral temperature is approximately:",
      "97.6°F to 99.6°F (about 36.5–37.5°C)",
      ["90°F", "105°F as normal baseline", "82°F"],
      "Know facility normal ranges and report fever/hypothermia promptly.",
      [
        "90°F is hypothermia territory.",
        "105°F is high fever emergency-level concern.",
        "82°F is incompatible with normal oral temps.",
      ],
      "easy",
    ],
    [
      "When counting respirations, the NA should:",
      "Count without telling the resident you are counting breaths, after pulse, noting rate/effort",
      [
        "Ask them to breathe as fast as possible",
        "Count for 2 seconds and multiply by 100",
        "Only count if the resident is talking continuously",
      ],
      "Awareness alters breathing; observe rise/fall for 30–60 seconds per policy.",
      [
        "Do not coach abnormal rates.",
        "Too short an interval is inaccurate.",
        "Talking makes counting hard—wait if needed.",
      ],
      "medium",
    ],
    [
      "A radial pulse is taken at the:",
      "Wrist on the thumb side",
      ["Neck only", "Behind the knee only", "Temple only"],
      "Radial is the common NA pulse site; report irregular/weak pulses.",
      [
        "Carotid is neck—used in emergencies carefully.",
        "Popliteal is behind knee.",
        "Temporal is temple.",
      ],
      "easy",
    ],
    [
      "Which blood pressure reading should be reported immediately as abnormally high for most adults?",
      "188/110 mm Hg in a resident who is symptomatic or per facility thresholds",
      ["110/70 mm Hg in a stable adult", "118/76 mm Hg", "100/60 mm Hg in a baseline low-normal resident"],
      "Know resident baselines and facility report parameters; severe hypertension needs prompt nursing notification.",
      [
        "Often acceptable.",
        "Typically normal.",
        "May be normal for some.",
      ],
      "medium",
    ],
    [
      "Droplet precautions may require the NA to:",
      "Wear a mask when working within close range of the resident as directed",
      [
        "Never wear a mask for influenza-like illness when policy requires it",
        "Leave the door open with no signage when isolation is ordered",
        "Share drinking cups",
      ],
      "Follow the isolation sign and nurse instructions for PPE.",
      [
        "Masks are often required.",
        "Isolation communication matters.",
        "No sharing cups.",
      ],
      "medium",
    ],
    [
      "Dirty linen should be:",
      "Held away from the uniform and placed in appropriate bags; never shaken",
      [
        "Placed on the floor temporarily",
        "Used to wipe spills then returned to the cart",
        "Taken home to wash",
      ],
      "Linen handling prevents environmental contamination.",
      [
        "Floor is contaminated.",
        "Linen is not cleaning rags.",
        "Facility processing only.",
      ],
      "easy",
    ],
    [
      "A pulse oximeter reading is affected when:",
      "Nail polish, poor perfusion, or motion interferes with the sensor",
      [
        "The resident has clean warm fingers and still sensor placement only as a problem always",
        "Hand hygiene is performed correctly as a false low cause",
        "Privacy curtains are closed",
      ],
      "Report unexpected SpO2 values and recheck technique/site.",
      [
        "Good technique improves accuracy.",
        "Hygiene doesn’t falsify SpO2.",
        "Privacy unrelated to the number.",
      ],
      "hard",
    ],
    [
      "Before measuring weight, the NA should:",
      "Balance/zero the scale, use consistent clothing/footwear approach, and assist for safety",
      [
        "Estimate weight to save time always",
        "Weigh while the resident holds a full suitcase undocumented",
        "Skip documenting the value",
      ],
      "Accurate weights guide clinical decisions (heart failure, nutrition).",
      [
        "Do not estimate.",
        "Extra items skew weight.",
        "Always document.",
      ],
      "easy",
    ],
    [
      "Hand hygiene with alcohol-based rub is appropriate when:",
      "Hands are not visibly soiled and facility policy allows it",
      [
        "Hands are covered in feces",
        "Caring for a resident with C. difficile and soap/water is required by policy—you use only alcohol without washing",
        "After touching blood with bare hands without washing opportunity—skip both",
      ],
      "Soap/water for visible soil and spore-forming organisms per policy (e.g., C. diff).",
      [
        "Wash with soap/water when soiled.",
        "C. diff typically needs soap/water.",
        "Blood exposure needs immediate washing and report.",
      ],
      "hard",
    ],
    [
      "When removing PPE, the general principle is:",
      "Remove the most contaminated items first in the order taught, and perform hand hygiene",
      [
        "Touch your face with dirty gloves freely",
        "Reuse gloves between residents by rinsing with water only",
        "Tie used gowns on the overbed table for the next shift",
      ],
      "Correct doffing prevents self-contamination.",
      [
        "Avoid face contamination.",
        "Gloves are single-use between residents.",
        "Dispose/laundry per policy.",
      ],
      "medium",
    ],
    [
      "A respiratory rate of 8 breaths/min in an adult resident is:",
      "Too low (bradypnea)—report promptly",
      ["A normal finding for all adults", "Too high (tachypnea)", "Impossible to measure"],
      "Normal adult RR is often ~12–20; 8 needs nursing evaluation especially with sedation/opioids.",
      [
        "Not normal.",
        "Tachypnea is fast breathing.",
        "It is measurable and urgent.",
      ],
      "medium",
    ],
    [
      "Catheter care by the NA includes:",
      "Cleaning the peri area and catheter tubing as directed, keeping the bag below bladder level, and securing the catheter",
      [
        "Raising the drainage bag above the bladder routinely",
        "Disconnecting the closed system to rinse with tap water daily",
        "Using the catheter bag as a handle to reposition the resident",
      ],
      "Closed system and dependent drainage reduce UTI risk.",
      [
        "Bag above bladder causes reflux.",
        "Do not break closed systems improperly.",
        "Never pull by the bag/tubing.",
      ],
      "medium",
    ],
    [
      "If a sterile dressing pack is opened and left unattended in a dirty area, the NA should:",
      "Consider it contaminated and obtain new supplies per procedure",
      [
        "Use it anyway to avoid waste",
        "Blow on it to “re-sterilize”",
        "Cover with a bath towel and proceed as sterile",
      ],
      "Sterility is absolute—when in doubt, replace.",
      [
        "Waste is secondary to infection risk.",
        "Blowing contaminates more.",
        "Towels are not sterile barriers for that purpose.",
      ],
      "easy",
    ],
  ],
  "psychosocial": [
    [
      "Therapeutic communication includes:",
      "Listening, clarifying, and allowing time for the resident to express feelings",
      [
        "Changing the subject whenever emotions appear",
        "Telling residents their feelings are silly",
        "Talking only about the NA’s personal problems",
      ],
      "Empathy and presence support psychosocial well-being.",
      [
        "Avoidance shuts down communication.",
        "Belittling harms dignity.",
        "Keep focus on the resident.",
      ],
      "easy",
    ],
    [
      "When a resident with dementia asks for her deceased husband, a helpful approach is often to:",
      "Respond with empathy and use redirection/validation techniques per care plan rather than repeated harsh corrections",
      [
        "Force detailed confrontation every time that he is dead",
        "Ignore and walk away silently always",
        "Laugh at the question",
      ],
      "Validation/redirection can reduce distress; follow the care plan and nurse guidance.",
      [
        "Harsh confrontation can escalate agitation.",
        "Ignoring can increase distress.",
        "Laughing is disrespectful.",
      ],
      "medium",
    ],
    [
      "Cultural sensitivity means the NA should:",
      "Respect preferences about food, touch, privacy, and end-of-life customs within facility rules",
      [
        "Impose the NA’s beliefs as the only correct ones",
        "Refuse interpreters when language barriers exist",
        "Mock religious items",
      ],
      "Person-centered care includes cultural humility.",
      [
        "Do not impose beliefs.",
        "Use interpreters per policy.",
        "Respect sacred items.",
      ],
      "easy",
    ],
    [
      "A resident is crying after a difficult phone call. The NA should:",
      "Sit with the resident, offer presence, and ask if they want to talk or have the nurse notified",
      [
        "Say “stop crying, it’s not a big deal”",
        "Leave without acknowledgment",
        "Share the story at the nurses’ station gossip circle",
      ],
      "Emotional support and confidentiality are part of psychosocial care.",
      [
        "Minimizing feelings is harmful.",
        "Acknowledge distress.",
        "Gossip violates privacy.",
      ],
      "easy",
    ],
    [
      "Sexuality in older adults should be:",
      "Respected as a normal human need within consent, privacy, and safety policies",
      [
        "Treated as shameful and mocked",
        "Ignored even when inappropriate public behavior needs redirection",
        "Used as joke material with other residents",
      ],
      "Address inappropriate behavior professionally; support privacy for appropriate consensual expression per policy.",
      [
        "Mockery is abuse.",
        "Public inappropriate acts need calm redirection.",
        "Jokes can be abusive.",
      ],
      "hard",
    ],
    [
      "To help a hearing-impaired resident, the NA should:",
      "Face the resident, speak clearly at a moderate pace, reduce background noise, and use assistive devices",
      [
        "Shout into the bad ear from behind",
        "Chew gum and look away while talking",
        "Avoid written cues when they help",
      ],
      "Communication adaptations reduce isolation.",
      [
        "Shouting distorts speech.",
        "Face them; enunciate.",
        "Written cues can help.",
      ],
      "easy",
    ],
    [
      "Residents with vision loss benefit when the NA:",
      "Identifies self when entering, explains care before touching, and keeps pathways clear",
      [
        "Rearranges furniture often without telling them",
        "Leaves doors half-open as trip hazards without warning",
        "Avoids describing food locations on the tray",
      ],
      "Consistency and verbal cueing support independence and safety.",
      [
        "Sudden changes confuse/injure.",
        "Warn about hazards.",
        "Clock-method tray descriptions help.",
      ],
      "medium",
    ],
    [
      "Agnosia, aphasia, and apraxia are terms often related to:",
      "Neurologic changes that affect recognition, language, and skilled movement—requiring patience and adapted communication",
      [
        "Normal vital sign values",
        "Types of wheelchairs only",
        "Laundry cycles",
      ],
      "Understanding cognitive/communication deficits improves care and reduces agitation.",
      [
        "Not vitals.",
        "Not wheelchair types.",
        "Not laundry.",
      ],
      "hard",
    ],
    [
      "When family members are upset about care, the NA should:",
      "Listen respectfully and involve the nurse/supervisor for concerns beyond the NA role",
      [
        "Argue loudly in the hallway",
        "Promise medical outcomes you cannot control",
        "Discuss other residents’ charts to compare",
      ],
      "Service recovery and escalation maintain trust; stay in scope.",
      [
        "Stay calm/professional.",
        "Do not make false promises.",
        "No PHI comparisons.",
      ],
      "medium",
    ],
    [
      "Loneliness in long-term care may be reduced by:",
      "Encouraging appropriate social activities and meaningful conversation",
      [
        "Leaving the TV on at max volume 24/7 without preference",
        "Restricting all visitors as default punishment",
        "Ignoring the resident’s preferred hobbies",
      ],
      "Psychosocial well-being is a care goal, not optional.",
      [
        "Preferences matter; noise can distress.",
        "Visitation rights exist within rules.",
        "Hobbies support identity.",
      ],
      "easy",
    ],
    [
      "A resident refuses a bath. The best initial NA response is:",
      "Ask about concerns, offer choices (time/type), and report refusal per policy without forcing",
      [
        "Force scrubbing against their will",
        "Withhold meals as punishment",
        "Tell them they are childish",
      ],
      "Consent and dignity apply; negotiate and escalate to the nurse.",
      [
        "Forcing is abuse.",
        "Food punishment is abuse.",
        "Insults are abuse.",
      ],
      "medium",
    ],
    [
      "Reminiscence can be helpful because it:",
      "Supports identity, mood, and cognitive engagement for many older adults",
      [
        "Always worsens dementia instantly",
        "Is forbidden in nursing homes",
        "Replaces all medical treatment",
      ],
      "Life review activities are common psychosocial interventions.",
      [
        "Often beneficial if not distressing.",
        "Allowed and encouraged.",
        "Complements, not replaces, medical care.",
      ],
      "easy",
    ],
    [
      "If a resident makes a sexually inappropriate comment, the NA should:",
      "Set a clear respectful boundary, state the behavior is inappropriate, and report per policy",
      [
        "Respond with flirtation",
        "Shame the resident publicly at mealtime",
        "Ignore repeated harassment without reporting",
      ],
      "Protect yourself and maintain professionalism; facilities have reporting pathways.",
      [
        "Do not encourage.",
        "Public shaming is improper.",
        "Report patterns/harassment.",
      ],
      "medium",
    ],
    [
      "Person-centered care emphasizes:",
      "Knowing the resident’s preferences, routines, and life story to guide daily care",
      [
        "Identical rigid routines for every person with no exceptions ever",
        "Staff convenience as the only schedule driver",
        "Ignoring advance directives",
      ],
      "Individualization improves outcomes and satisfaction.",
      [
        "Flexibility within safety matters.",
        "Resident needs drive care.",
        "Honor legal care preferences.",
      ],
      "easy",
    ],
    [
      "Anxiety before a procedure may be reduced when the NA:",
      "Explains what will happen in simple terms and stays calm and supportive",
      [
        "Withholds all information to “avoid worry”",
        "Uses threats to gain cooperation",
        "Performs care without saying a word while startling the resident",
      ],
      "Information and calm presence reduce fear.",
      [
        "Surprises increase anxiety.",
        "Threats are abusive.",
        "Warn before touch.",
      ],
      "easy",
    ],
  ],
  "role-rights": [
    [
      "Tasks outside the NA’s scope of practice include:",
      "Giving medications (unless state-specific specially trained roles apply) and sterile invasive procedures not delegated legally",
      [
        "Assisting with ADLs",
        "Measuring vital signs as assigned",
        "Making occupied beds",
      ],
      "NAs do not practice nursing/medicine beyond training and legal delegation.",
      [
        "ADLs are core NA work.",
        "Vitals are common NA tasks.",
        "Bedmaking is common.",
      ],
      "easy",
    ],
    [
      "If asked to do something beyond training, the NA should:",
      "Refuse politely and explain, then notify the nurse/supervisor",
      [
        "Attempt it secretly",
        "Ask another NA who is also untrained to do it",
        "Document that it was done when it was not",
      ],
      "Refusal of unsafe assignments protects residents and licensure/certification.",
      [
        "Secret attempts are dangerous.",
        "Untrained peers don’t fix scope.",
        "False documentation is fraud.",
      ],
      "easy",
    ],
    [
      "Residents’ rights include:",
      "Privacy, dignity, freedom from abuse/restraints (except proper orders), and participation in care decisions",
      [
        "Being punished by withholding mail",
        "Having personal funds taken by staff",
        "Forced silence about grievances",
      ],
      "OBRA and facility policies protect resident rights in nursing homes.",
      [
        "Mail rights exist.",
        "Misappropriation is theft/abuse.",
        "Grievance rights exist.",
      ],
      "easy",
    ],
    [
      "An example of neglect is:",
      "Failing to provide needed care such as turning, fluids, or hygiene that results in harm risk",
      [
        "Answering a call light promptly",
        "Reporting a skin tear immediately",
        "Offering toileting assistance",
      ],
      "Neglect is failure to provide goods/services necessary to avoid harm.",
      [
        "Prompt response is good care.",
        "Reporting protects the resident.",
        "Toileting assistance is appropriate.",
      ],
      "medium",
    ],
    [
      "If you suspect abuse, you should:",
      "Report immediately through the required chain/hotline per facility and state law",
      [
        "Wait months to be sure",
        "Confront the abuser alone violently",
        "Post accusations on social media with names",
      ],
      "NAs are mandatory reporters in healthcare settings; timely reporting is required.",
      [
        "Delay risks more harm.",
        "Do not escalate personally with violence.",
        "PHI/defamation issues—use official channels.",
      ],
      "easy",
    ],
    [
      "Confidentiality means:",
      "Sharing resident information only with those who need it to provide care",
      [
        "Discussing residents by name in elevators with visitors present",
        "Posting wound photos online",
        "Leaving charts open in public",
      ],
      "HIPAA and ethics protect PHI.",
      [
        "Public discussion is a breach.",
        "Online photos are breaches.",
        "Secure records.",
      ],
      "easy",
    ],
    [
      "A restraint may be used only when:",
      "Ordered by a provider, used as a last resort with least restriction, and monitored per policy",
      [
        "Applied for staff convenience during breaks",
        "Used to punish wandering",
        "Tied tightly without checking circulation",
      ],
      "Improper restraint use is abuse; know release/check requirements.",
      [
        "Convenience is not justification.",
        "Punishment is forbidden.",
        "Circulation checks are mandatory.",
      ],
      "medium",
    ],
    [
      "Accurate documentation should be:",
      "Objective, timely, legible/electronic-correct, and free of opinions/blame language",
      [
        "Written for tomorrow about today’s care you forgot, inventing details",
        "Full of diagnoses the NA invents",
        "Erased with white-out without following error policy",
      ],
      "If it wasn’t documented, it is hard to prove it was done—never fabricate.",
      [
        "Do not invent.",
        "NAs record observations, not medical diagnoses.",
        "Follow legal correction methods.",
      ],
      "medium",
    ],
    [
      "Call lights should be:",
      "Answered promptly and placed within the resident’s reach",
      [
        "Unplugged to reduce noise",
        "Answered only at end of shift",
        "Given only to private-pay residents",
      ],
      "Access to assistance is a safety and rights issue.",
      [
        "Never disable call systems.",
        "Prompt response required.",
        "All residents get call access.",
      ],
      "easy",
    ],
    [
      "An Ombudsman is:",
      "An advocate who helps residents with complaints and rights issues",
      [
        "The laundry supervisor only",
        "A type of antibiotic",
        "The NA’s personal attorney automatically",
      ],
      "Residents can contact the ombudsman; staff must not retaliate.",
      [
        "Not laundry.",
        "Not a drug.",
        "Not automatically your lawyer.",
      ],
      "medium",
    ],
    [
      "HIPAA training matters for NAs because they:",
      "Handle PHI daily and can cause breaches through talk, records, or devices",
      [
        "Never see any health information",
        "Are exempt from all privacy laws",
        "May sell resident lists for bonuses",
      ],
      "Workforce members are accountable for privacy practices.",
      [
        "NAs see PHI constantly.",
        "No exemption.",
        "Selling PHI is illegal.",
      ],
      "easy",
    ],
    [
      "A resident offers the NA money as a thank-you. The NA should:",
      "Politely refuse gifts of money per policy and thank them verbally",
      [
        "Accept cash secretly",
        "Ask for more",
        "Accept and not report if policy forbids it",
      ],
      "Gift policies prevent exploitation allegations; follow facility rules.",
      [
        "Secret cash is improper.",
        "Do not solicit.",
        "Policy compliance required.",
      ],
      "medium",
    ],
    [
      "Chain of command is used to:",
      "Report problems to the appropriate supervisor so issues are addressed safely",
      [
        "Skip the nurse and only call the newspaper first",
        "Hide errors",
        "Assign blame publicly on social media",
      ],
      "Use internal reporting pathways; emergencies still call for immediate help.",
      [
        "Media is not first-line clinical reporting.",
        "Transparency via proper channels.",
        "Stay professional.",
      ],
      "easy",
    ],
    [
      "Abandonment can occur when the NA:",
      "Leaves an assigned shift/residents without giving report or being relieved",
      [
        "Takes a scheduled break after proper handoff",
        "Calls for help during an emergency",
        "Refuses an unsafe task and stays to cover other duties",
      ],
      "Leaving without relief endangers residents.",
      [
        "Proper breaks are allowed.",
        "Calling for help is appropriate.",
        "Unsafe task refusal with continued coverage differs from walking out.",
      ],
      "hard",
    ],
    [
      "Objective observation example:",
      "“Resident ate 50% of lunch; stated abdominal pain 6/10; vomited 100 mL green fluid.”",
      [
        "“Resident is lazy and faking”",
        "“Resident is nasty”",
        "“Resident wants attention like always”",
      ],
      "Chart facts and quotes; avoid judgmental labels.",
      [
        "Judgmental.",
        "Labeling.",
        "Assumes motive.",
      ],
      "medium",
    ],
  ],
};
