#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "armed-security-officer-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "law", [
        ("Use of force should be guided by:",
         {"a": "Maximum force in all encounters", "b": "Objective reasonableness: force proportional to threat and applied only when necessary", "c": "Officer's personal anger level", "d": "Bystander opinions only"},
         "b", "Legal standards require reasonable, proportional force based on threat and subject behavior.",
         {"a": "Excessive force violates law/policy.", "c": "Emotion is not a legal standard.", "d": "Legal test is objective reasonableness."}, "easy"),
        ("A citizen's arrest by a security officer is generally lawful when:",
         {"a": "Officer personally witnessed a felony or has reasonable belief per state statute", "b": "Officer suspects jaywalking only without statute", "c": "Officer wants to impress supervisor", "d": "Always prohibited for all security"},
         "a", "Citizen's arrest authority varies by state, often for felonies or shoplifting with probable cause.",
         {"b": "Misdemeanor authority depends on state and witnessing.", "c": "Not a legal basis.", "d": "Many states permit limited citizen's arrest."}, "medium"),
        ("Deadly force by a private armed officer is typically justified only when:",
         {"a": "Property theft is suspected without threat to life", "b": "Imminent threat of death or serious bodily harm to self or others per state law", "c": "Trespasser refuses to leave after verbal warning only", "d": "Supervisor is unavailable"},
         "b", "Deadly force is reserved for imminent deadly threats; property alone rarely justifies it.",
         {"a": "Property crimes alone usually do not justify deadly force.", "c": "Simple trespass may not justify deadly force.", "d": "Supervisor presence is not the legal test."}, "hard"),
        ("Trespass after warning on posted private property may allow the officer to:",
         {"a": "Request departure, document, and contact law enforcement; use reasonable force if subject resists lawful removal per policy", "b": "Immediately shoot without warning", "c": "Ignore because trespass is never illegal", "d": "Detain indefinitely without notifying anyone"},
         "a", "Trespass enforcement follows warn, escort, and law enforcement coordination with reasonable force if necessary.",
         {"b": "Deadly force not appropriate for simple trespass.", "c": "Trespass can be criminal/civil violation.", "d": "Detention must be reasonable and lawful."}, "medium"),
        ("The Fourth Amendment relevance to security searches at private workplaces means:",
         {"a": "Government action triggers protection; private employer searches follow policy/consent with limited constitutional claims", "b": "All private searches are unconstitutional always", "c": "Officers may search anyone anytime without rules", "d": "Amendment applies identically to private guards as police everywhere"},
         "a", "Constitutional search limits primarily bind state actors; private searches governed by policy, contract, and state tort law.",
         {"b": "Private searches occur under different rules.", "c": "Policy and consent still matter.", "d": "State action doctrine distinguishes roles."}, "hard"),
        ("Shopkeeper's privilege allows detention of suspected shoplifters when:",
         {"a": "Reasonable cause, reasonable time/method, and for investigation on premises", "b": "Any customer disliked by staff", "c": "Detention for days without police", "d": "Public strip search without policy"},
         "a", "Many states recognize limited detention with reasonable suspicion, manner, and duration.",
         {"b": "Subjective dislike insufficient.", "c": "Duration must be reasonable.", "d": "Strip searches require strict legal/policy limits."}, "medium"),
        ("An officer making a lawful arrest should:",
         {"a": "Inform subject of reason if safe, use reasonable restraint, and transfer to law enforcement promptly", "b": "Use chokehold as first option always", "c": "Search home without warrant automatically", "d": "Accept bribe to release suspect"},
         "a", "Lawful arrest includes explanation when practicable, safe restraint, and timely law enforcement transfer.",
         {"b": "Chokeholds often restricted by policy/law.", "c": "Home searches require warrants/exceptions.", "d": "Bribery is criminal."}, "easy"),
        ("Force continuum training emphasizes:",
         {"a": "Starting with presence/verbal commands and escalating only as threat increases", "b": "Starting with firearm drawn always", "c": "No verbal communication", "d": "Random escalation"},
         "a", "Officers should use lowest effective level: officer presence, verbal, empty-hand, less-lethal, deadly last.",
         {"b": "Firearm is last resort.", "c": "Verbal is first step.", "d": "Escalation must be justified."}, "easy"),
        ("Miranda warnings are required when:",
         {"a": "Subject is in custodial interrogation by law enforcement", "b": "Private security asks routine ID questions on private property always", "c": "Officer says hello", "d": "Never required for police either"},
         "a", "Miranda applies to custodial police interrogation, not typically private security questioning.",
         {"b": "Private security is not Miranda agent generally.", "c": "Not custodial interrogation.", "d": "Miranda applies to police custodial questioning."}, "medium"),
        ("Excessive force claims are evaluated using:",
         {"a": "Totality of circumstances at time force was used", "b": "Hindsight perfect knowledge only", "c": "Officer's unsupported story alone", "d": "Subject's criminal record alone"},
         "a", "Courts assess reasonableness given facts known to officer at moment of force.",
         {"b": "Hindsight is improper standard.", "c": "Evidence beyond officer statement considered.", "d": "Prior record alone does not justify force."}, "medium"),
        ("Open carry on client property where firearms are prohibited should result in:",
         {"a": "Policy-based enforcement, request to leave/store weapon, and law enforcement if noncompliant", "b": "Ignore because all carry is legal everywhere", "c": "Immediate deadly force", "d": "Officer confiscating without policy/law support"},
         "a", "Property owners may restrict firearms; enforcement follows policy and state law with proportional response.",
         {"b": "Private property rules and state law vary.", "c": "Disproportional.", "d": "Confiscation requires legal authority."}, "medium"),
        ("A restraining order served on an employee means the officer should:",
         {"a": "Know terms, enforce exclusion zones, document contacts, and coordinate with HR/law enforcement", "b": "Share order on social media", "c": "Ignore unless officer feels like it", "d": "Arrest protected person automatically"},
         "a", "Officers enforce court orders per terms and site security plan with documentation.",
         {"b": "Privacy and safety require discretion.", "c": "Court orders must be enforced.", "d": "Wrong party arrest is unlawful."}, "medium"),
        ("Immunity for good-faith performance of duties:",
         {"a": "May limit liability when acting within scope and policy, but not for intentional wrongdoing", "b": "Protects all criminal acts", "c": "Eliminates need for training", "d": "Applies only to trespassers"},
         "a", "Qualified/good-faith defenses exist for reasonable actions within authority; not for malice or gross negligence.",
         {"b": "Intentional crimes not protected.", "c": "Training still required.", "d": "Applies to officers' lawful acts."}, "hard"),
        ("Documenting use of force should include:",
         {"a": "Subject behavior, threat, commands given, force used, injuries, witnesses, and medical aid", "b": "Only officer's favorite quote", "c": "No photos or names ever", "d": "Delay report until next month"},
         "a", "Complete timely reports support legal review and accountability.",
         {"b": "Insufficient detail.", "c": "Identifying info and evidence collected per policy.", "d": "Reports should be prompt."}, "easy"),
        ("Off-duty armed officer at mall sees felony in progress. Best practice:",
         {"a": "Call 911, observe safely, intervene only within training/policy and law if imminent harm", "b": "Pursue at high speed without identifying self", "c": "Do nothing because off duty ever", "d": "Shoot to wound property vandal only"},
         "a", "Off-duty response prioritizes notification, identification if engaging, and actions within legal authority.",
         {"b": "Identification and safety critical.", "c": "Good Samaritan/commission rules may apply.", "d": "Property vandalism rarely justifies shooting."}, "hard"),
    ])

    qs += pack(E, "weapons", [
        ("Fundamental firearm safety rules include:",
         {"a": "Treat every gun as loaded, never point at anything not intended to shoot, finger off trigger until ready, know target and beyond", "b": "Assume unloaded until fired once", "c": "Point at coworkers to test reflexes", "d": "Ignore backstop if close range"},
         "a", "Standard four rules prevent negligent discharges and unintended injury.",
         {"b": "Always treat as loaded.", "c": "Never point at people.", "d": "Backstop awareness is essential."}, "easy"),
        ("Before holstering duty weapon after shift inspection, the officer should:",
         {"a": "Verify cleared/unloaded per policy if storing, secure in approved lockbox, and log if required", "b": "Leave loaded on desk overnight", "c": "Store in personal car unlocked glove box on hot day", "d": "Give to unauthorized friend for cleaning"},
         "a", "Weapons storage follows policy: secured, access controlled, documented chain where required.",
         {"b": "Unsecured loaded weapons violate policy.", "c": "Vehicle storage risks theft/heat discharge.", "d": "Unauthorized transfer prohibited."}, "medium"),
        ("A double-feed malfunction is best cleared by:",
         {"a": "Tap-rack-bang only always without assessment", "b": "Stop, point safe, identify malfunction type, and follow trained clearance procedure (often lock slide, strip mag, rack)", "c": "Look down barrel while pulling trigger", "d": "Throw weapon at threat"},
         "b", "Complex malfunctions require proper clearance sequence; muzzle discipline maintained.",
         {"a": "Tap-rack insufficient for double feed.", "c": "Never look down barrel.", "d": "Not a tactic."}, "hard"),
        ("Holster selection for concealed/open duty carry should ensure:",
         {"a": "Full trigger guard coverage and retention appropriate to activity", "b": "Loose nylon with exposed trigger", "c": "Hair trigger modification for speed only", "d": "No retention because speed only matters"},
         "a", "Holster covers trigger guard and provides retention to prevent unauthorized access/discharge.",
         {"b": "Exposed trigger is unsafe.", "c": "Trigger mods increase negligent discharge risk.", "d": "Retention balances access and security."}, "medium"),
        ("Ammunition duty carry should match:",
         {"a": "Manufacturer specifications for firearm and approved duty load by employer", "b": "Cheapest reloads of unknown origin", "c": "Any caliber that fits loosely", "d": "Blanks for deterrence only"},
         "a", "Use factory duty ammunition specified for weapon and department policy.",
         {"b": "Reloads may fail or damage gun.", "c": "Wrong caliber is catastrophic.", "d": "Blanks not for duty carry."}, "easy"),
        ("Officer responds to alarm with rifle slung muzzle-up on single-point sling near face. Safer carry is:",
         {"a": "Muzzle controlled in safe direction with two-point sling and finger off trigger", "b": "Muzzle flagging team members while running", "c": "Finger on trigger during movement", "d": "Swept back and forth while scanning crowds"},
         "a", "Movement requires muzzle awareness, sling control, and trigger discipline.",
         {"b": "Muzzle flagging violates safety.", "c": "Trigger finger indexed until sights on target.", "d": "Sweeping is negligent."}, "medium"),
        ("Weapon retention during physical struggle prioritizes:",
         {"a": "Protect weapon from takeaway, create distance, and call for backup", "b": "Holster while suspect grabs gun", "c": "Drop gun for suspect to pick up", "d": "Turn back to suspect to adjust belt"},
         "a", "Retention techniques and backup prevent arming suspect.",
         {"b": "Holstering during struggle risks access.", "c": "Never surrender weapon.", "d": "Turning away risks takeaway."}, "hard"),
        ("Cleaning firearm after range qualification includes:",
         {"a": "Unload verify, disassemble per manual, clean bore/action, inspect, function check with dummy if policy", "b": "Clean while loaded pointed at mirror", "c": "Use only WD-40 in barrel long term without follow-up", "d": "Skip inspection if it fired today"},
         "a", "Safe cleaning starts verified unloaded with manufacturer maintenance and inspection.",
         {"b": "Loaded cleaning is negligent.", "c": "Improper solvents can damage; follow manual.", "d": "Inspection catches wear."}, "easy"),
        ("Less-lethal options such as OC spray should be deployed when:",
         {"a": "Policy authorizes for active resistance below deadly force threshold with wind/backup considerations", "b": "Subject is passive seated compliant", "c": "Officer is upwind without warning in crowded enclosed space without policy", "d": "As prank on coworker"},
         "a", "OC use requires justification, warning when feasible, contamination awareness, and policy compliance.",
         {"b": "No force on compliant subject.", "c": "Wind/crowd increase risk; needs justification.", "d": "Misuse is assault."}, "medium"),
        ("Loaded chamber indicator and press check purpose:",
         {"a": "Confirm loaded status safely without violating muzzle/trigger rules", "b": "Show off to public", "c": "Replace daily inventory count of bullets in pocket", "d": "Test trigger pull on loaded gun in break room"},
         "a", "Press check verifies status with muzzle in safe direction and finger off trigger.",
         {"b": "Not for display.", "c": "Not inventory method.", "d": "Dry fire rules apply; unsafe in break room."}, "medium"),
        ("Transporting duty weapon to range in personal vehicle requires:",
         {"a": "Unloaded secured case, ammunition separate if policy requires, vehicle locked", "b": "Loaded on passenger seat visible", "c": "Hidden under floor mat loaded", "d": "Shared with unauthorized passenger handling"},
         "a", "Transport follows state law and company policy: secured, limited access.",
         {"b": "Visible loaded weapon increases theft risk.", "c": "Hidden loaded weapon still unsafe/illegal many places.", "d": "Unauthorized handling prohibited."}, "easy"),
        ("If officer discharges weapon accidentally in guard shack with no injury, required actions include:",
         {"a": "Secure scene, render aid if needed, notify supervisor/law enforcement per policy, preserve evidence, complete report", "b": "Hide damage and say nothing", "c": "Leave scene immediately", "d": "Reload and continue without reporting"},
         "a", "Negligent discharge requires immediate reporting, investigation, and remedial training.",
         {"b": "Concealment violates policy/law.", "c": "Leaving abandons duty.", "d": "Must report all discharges."}, "medium"),
        ("Sight picture for defensive shooting typically requires:",
         {"a": "Front sight focus with equal height sights aligned on target (iron sights fundamentals)", "b": "Close eyes and point hip only always", "c": "Look at target blur sights intentionally always at all ranges", "d": "Only laser without training"},
         "a", "Fundamental marksmanship uses front sight focus and proper alignment for accuracy.",
         {"b": "Unaimed fire is inaccurate.", "c": "Sight focus varies by distance/training.", "d": "Laser is adjunct not replacement for fundamentals."}, "medium"),
        ("Armor piercing ammunition at work is generally:",
         {"a": "Prohibited or restricted by policy and law for duty use", "b": "Required standard for all guards", "c": "Preferred for cardboard targets only in office", "d": "Mandated by OSHA for receptionists"},
         "a", "AP ammo often restricted; duty loads selected for stopping power and legal compliance.",
         {"b": "Not standard guard ammo.", "c": "Office not range.", "d": "OSHA does not mandate AP."}, "hard"),
        ("Weapon light activation before identifying target helps:",
         {"a": "Identify friend/foe and legal target while maintaining muzzle discipline", "b": "Blind everyone including allies without identification", "c": "Replace all verbal commands always", "d": "Prove officer has expensive gear"},
         "a", "Positive identification prevents wrongful shootings; light aids ID with rules of engagement.",
         {"b": "Must identify before shooting.", "c": "Verbal still required when feasible.", "d": "Gear not the goal."}, "hard"),
    ])

    qs += pack(E, "patrol", [
        ("During routine patrol, the officer notices an unsecured exterior door after hours. First action:",
         {"a": "Enter alone immediately without reporting", "b": "Secure area if safe, investigate with backup/light, report to control, document", "c": "Ignore because doors open themselves", "d": "Leave site unattended open"},
         "b", "Open doors suggest breach; secure, investigate cautiously with support, document findings.",
         {"a": "Solo entry may be unsafe.", "c": "Requires investigation.", "d": "Leaving open increases loss/risk."}, "easy"),
        ("Effective patrol patterns should be:",
         {"a": "Varied and unpredictable to deter surveillance while covering critical points", "b": "Identical every hour so offenders can time entry", "c": "Only at desk watching TV", "d": "Skipped on holidays because crime stops"},
         "a", "Randomized routes and checkpoint coverage reduce predictable vulnerabilities.",
         {"b": "Predictable patterns aid criminals.", "c": "Static guard misses patrol function.", "d": "Crime continues holidays."}, "easy"),
        ("An alarm activation with unknown cause requires:",
         {"a": "Systematic search of protected area, verify cause, reset only after clearance, log details", "b": "Instant reset without inspection to stop noise", "c": "Disable alarms permanently", "d": "Assume false and go home"},
         "a", "Alarm response follows search procedures, verification, and documentation before reset.",
         {"b": "Reset without search misses intruder.", "c": "Disabling removes protection.", "d": "Assumption unsafe."}, "medium"),
        ("Officer observes person photographing sensitive infrastructure. Appropriate response:",
         {"a": "Approach safely, identify, enforce site policy, notify supervisor/law enforcement if suspicious", "b": "Confiscate phone violently without authority", "c": "Ignore all photography always", "d": "Share security layout to help photographer"},
         "a", "Policy may restrict photography; courteous contact and escalation if threat indicators present.",
         {"b": "Seizure requires legal authority.", "c": "Sensitive sites may restrict.", "d": "Assists adversaries."}, "medium"),
        ("Lost child in mall patrol area. Priority actions:",
         {"a": "Get description, notify control/PA if policy, search immediate area, coordinate with law enforcement", "b": "Tell child to wander alone", "c": "Wait 24 hours", "d": "Post child's full info on public social media with location"},
         "a", "Missing child protocols emphasize quick description broadcast, area search, and LE coordination.",
         {"b": "Unsafe.", "c": "Immediate action required.", "d": "Public social media may endanger; follow policy."}, "easy"),
        ("Vehicle patrol log should record:",
         {"a": "Time, location, observations, incidents, and maintenance issues", "b": "Only odometer if officer remembers", "c": "Personal grocery list", "d": "Nothing; logs optional always"},
         "a", "Detailed logs support accountability, investigations, and maintenance.",
         {"b": "Incomplete records weakens evidence.", "c": "Irrelevant.", "d": "Most employers require logs."}, "easy"),
        ("Key control policy requires:",
         {"a": "Signed issuance, no unauthorized duplication, return at shift end, report lost keys immediately", "b": "Share master keys with contractors freely", "c": "Leave keys in ignition of patrol car overnight", "d": "Duplicate masters at kiosk without approval"},
         "a", "Key accountability prevents unauthorized access; lost keys trigger rekey assessment.",
         {"b": "Contractors get limited keys under policy.", "c": "Keys secured per policy.", "d": "Unauthorized duplication violates security."}, "medium"),
        ("Suspicious package found in lobby. Officer should:",
         {"a": "Evacuate area, deny access, notify bomb squad/supervisor, avoid moving/touching package", "b": "Shake package to hear contents", "c": "Open to identify owner", "d": "Place in trash compactor"},
         "a", "Suspected IED protocols: isolate, evacuate, notify specialists, do not disturb.",
         {"b": "Movement may detonate.", "c": "Opening is dangerous.", "d": "Destruction without assessment is unsafe."}, "medium"),
        ("Parking lot patrol at night uses lighting and:",
         {"a": "360 awareness, flashlight technique, visible presence, and radio check-ins", "b": "Headphones at full volume", "c": "Face only forward ignoring mirrors", "d": "Patrol without communication to test independence"},
         "a", "Night patrol emphasizes visibility, communication, and situational awareness.",
         {"b": "Headphones reduce awareness.", "c": "360 scan required.", "d": "Check-ins maintain safety."}, "easy"),
        ("Access control: tailgating prevention includes:",
         {"a": "Challenge unknown persons, enforce one credential per entry, educate employees", "b": "Hold door open for anyone behind badge holder without verification", "c": "Disable doors during peak hours", "d": "Prop open all secure doors for air"},
         "a", "Anti-tailgating requires verification of each entrant and employee awareness.",
         {"b": "Tailgating bypasses control.", "c": "Doors remain secured.", "d": "Propping defeats access control."}, "medium"),
        ("Incident scene preservation before law enforcement arrives:",
         {"a": "Limit access, note witness contacts, avoid contaminating evidence, brief arriving officers", "b": "Allow crowd to handle items", "c": "Clean blood immediately without photos", "d": "Move everything for aesthetics"},
         "a", "Preserve scene integrity for investigation while providing aid within training.",
         {"b": "Contamination destroys evidence.", "c": "Document before cleanup per policy.", "d": "Movement alters evidence."}, "hard"),
        ("Officer finds coworker sleeping on post. Best action:",
         {"a": "Relieve post safely, notify supervisor, document objectively without confrontation escalation", "b": "Post video publicly with insults", "c": "Leave post unattended too", "d": "Cover up to protect friend always"},
         "a", "Sleeping on post is serious; report through chain of command with factual documentation.",
         {"b": "Public shaming unprofessional.", "c": "Abandoning post violates duty.", "d": "Cover-up enables risk."}, "medium"),
        ("Checkpoint metal detector alarm on visitor. Procedure:",
         {"a": "Secondary screening per policy, maintain courtesy and rights, escalate if prohibited item found", "b": "Assume weapon and use deadly force immediately", "c": "Wave through to avoid delay", "d": "Confiscate wallet without inspection"},
         "a", "Secondary search follows standardized protocol proportionate to alarm.",
         {"b": "Disproportional.", "c": "Security breach.", "d": "Search follows policy."}, "medium"),
        ("Report writing for daily activity log differs from incident report because:",
         {"a": "Daily log summarizes routine patrol; incident report details specific event with witnesses/evidence", "b": "They are identical always", "c": "Incident reports never need times", "d": "Daily logs include officer medical history only"},
         "a", "Incident reports capture who/what/when/where/actions for specific events; logs track routine.",
         {"b": "Different purposes and detail.", "c": "Times critical in incidents.", "d": "Medical history irrelevant."}, "easy"),
        ("Heat illness during outdoor summer patrol is prevented by:",
         {"a": "Hydration, shade breaks, breathable gear, and recognizing early symptoms", "b": "Skipping water to reduce bathroom breaks only", "c": "Heavy wool uniform only", "d": "Ignoring dizziness"},
         "a", "Occupational safety includes hydration, rest, and symptom monitoring.",
         {"b": "Dehydration worsens illness.", "c": "Gear should suit climate.", "d": "Dizziness needs action."}, "easy"),
    ])

    qs += pack(E, "ethics", [
        ("Accepting a bribe from a vendor to ignore theft is:",
         {"a": "Felony/unethical conduct leading to termination and prosecution", "b": "Standard industry practice", "c": "Allowed if under $20", "d": "Required by company handbook"},
         "a", "Bribery and corruption violate law, contract, and professional ethics.",
         {"b": "Illegal and fireable.", "c": "No de minimis exception.", "d": "Handbooks prohibit."}, "easy"),
        ("Officer hears racial slur from colleague toward visitor. Appropriate response:",
         {"a": "Interrupt behavior, report to supervisor/HR per policy, support professional conduct", "b": "Join in to fit in", "c": "Ignore because not your race", "d": "Post visitor name online"},
         "a", "Harassment and bias violate policy; officers must report and maintain inclusive professionalism.",
         {"b": "Participation is misconduct.", "c": "All misconduct should be addressed.", "d": "Privacy violation."}, "medium"),
        ("Conflict of interest occurs when officer:",
         {"a": "Has financial/personal interest affecting impartial performance of duties", "b": "Works scheduled shift only", "c": "Completes training on time", "d": "Wears uniform correctly"},
         "a", "Personal interests must not compromise security decisions (e.g., dating suspect, vendor kickbacks).",
         {"b": "Normal duty.", "c": "Expected.", "d": "Appearance standard."}, "easy"),
        ("De-escalation techniques include:",
         {"a": "Calm voice, active listening, increased distance, offering choices when safe", "b": "Immediate physical takedown for verbal insult", "c": "Mocking subject to assert dominance", "d": "Threatening unlawful harm"},
         "a", "Verbal judo/de-escalation reduces force need through communication and tactical positioning.",
         {"b": "Insults alone rarely justify force.", "c": "Mocking escalates.", "d": "Unlawful threats are misconduct."}, "medium"),
        ("Officer asked to falsify time sheet for absent coworker should:",
         {"a": "Refuse and report attempt per policy", "b": "Agree to be team player", "c": "Alter records quietly", "d": "Demand payment first only"},
         "a", "Fraudulent records violate policy and may be criminal.",
         {"b": "Integrity overrides false teamwork.", "c": "Falsification is fireable.", "d": "Paid fraud still illegal."}, "easy"),
        ("Use of social media on duty should follow:",
         {"a": "Policy prohibiting disclosure of post details, filming security vulnerabilities, or unprofessional posts", "b": "Livestream all badge checks publicly", "c": "Share access codes for tips", "d": "Post client secrets for followers"},
         "a", "Social media policies protect confidential security information and professional image.",
         {"b": "Exposes tactics.", "c": "Security breach.", "d": "Violates contract/confidentiality."}, "medium"),
        ("Officer develops romantic relationship with frequent trespasser under investigation. This is:",
         {"a": "Conflict of interest requiring disclosure and reassignment", "b": "Encouraged to gain intel", "c": "Irrelevant to job", "d": "Mandatory for community policing"},
         "a", "Personal relationships with subjects compromise impartial enforcement.",
         {"b": "Intel must be lawful/policy-based.", "c": "Compromises integrity.", "d": "Not appropriate."}, "hard"),
        ("Whistleblower protection policies generally:",
         {"a": "Encourage reporting illegal/unethical conduct in good faith with anti-retaliation provisions", "b": "Punish all reporters automatically", "c": "Apply only to managers", "d": "Require public defamation first"},
         "a", "Good-faith reporting of violations is protected in many jurisdictions and company policies.",
         {"b": "Retaliation prohibited in good policies.", "c": "All employees may report.", "d": "Defamation not required."}, "medium"),
        ("Officer witnessing excessive force by partner should:",
         {"a": "Intervene if safe, report immediately, document facts objectively", "b": "Help cover story", "c": "Quit silently without report", "d": "Celebrate on social media"},
         "a", "Duty to intervene/report prevents harm and legal liability.",
         {"b": "Cover-up is complicity.", "c": "Reporting still required.", "d": "Unprofessional and risky."}, "hard"),
        ("Gift from grateful shop owner worth $200 during contract renewal should be:",
         {"a": "Declined or disclosed per anti-gratuity policy", "b": "Accepted without disclosure", "c": "Demanded monthly", "d": "Sold online"},
         "a", "Gratuities can imply bias; policies often limit or prohibit gifts from protected parties.",
         {"b": "Creates conflict of interest.", "c": "Extortion.", "d": "Misappropriation."}, "medium"),
        ("Cultural competency means:",
         {"a": "Respecting diverse backgrounds while enforcing rules consistently and professionally", "b": "Enforcing rules differently by race", "c": "Ignoring harassment if cultural excuse claimed", "d": "Refusing service to all non-English speakers always"},
         "a", "Professional respect and equal enforcement without bias or harassment.",
         {"b": "Discriminatory enforcement illegal.", "c": "Harassment never excused.", "d": "Language access may be required reasonably."}, "easy"),
        ("Officer mental health stress after shooting should:",
         {"a": "Use EAP/critical incident debrief resources per policy", "b": "Bottle up forever as toughness", "c": "Self-medicate with alcohol on post", "d": "Ignore policy support"},
         "a", "Post-incident support improves recovery and job performance.",
         {"b": "Suppressing trauma harmful.", "c": "Intoxication on duty prohibited.", "d": "Resources exist for reason."}, "medium"),
        ("Integrity test: supervisor asks to backdate patrol log. Officer should:",
         {"a": "Refuse falsification and report if necessary through ethics channel", "b": "Comply because supervisor always right legally", "c": "Backdate only on Fridays", "d": "Delete all logs instead"},
         "a", "Unlawful orders are not valid; falsifying records is misconduct.",
         {"b": "Illegal orders must be refused.", "c": "Partial fraud still fraud.", "d": "Destruction also misconduct."}, "easy"),
        ("Impartial enforcement requires:",
         {"a": "Applying site rules equally regardless of status, unless policy provides lawful exception", "b": "VIP exemption from all rules always", "c": "Targeting disliked employees", "d": "Ignoring violations by friends"},
         "a", "Selective enforcement erodes trust and may be discriminatory.",
         {"b": "VIP policies must be written/lawful.", "c": "Bias illegal/unethical.", "d": "Nepotism violates ethics."}, "medium"),
        ("Code of conduct acknowledgment means officer agrees to:",
         {"a": "Follow policies on honesty, confidentiality, force, appearance, and reporting violations", "b": "Ignore updates after signing once", "c": "Share passwords for convenience", "d": "Use position for personal side business exploiting access"},
         "a", "Codes define expected behavior including ongoing compliance and updates.",
         {"b": "Policies evolve; continued compliance required.", "c": "Password sharing prohibited.", "d": "Exploiting access is corruption."}, "easy"),
    ])

    assert len(qs) == 60
    return qs


if __name__ == "__main__":
    from _common import write_bank
    write_bank("armed-security-officer-readiness-check", build())
