#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "cfp-certification-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "planning", [
        ("The CFP Board's financial planning process begins with:",
         {"a": "Product selection before understanding goals", "b": "Establishing and defining the client-planner relationship and gathering data", "c": "Immediate implementation without analysis", "d": "Tax filing only"},
         "b", "Planning starts with engagement, goals, and qualitative/quantitative data.",
         {"a": "Products follow analysis.", "c": "Analysis precedes implementation.", "d": "Tax is one component."}, "easy"),
        ("An Investment Policy Statement (IPS) should document:",
         {"a": "Only the planner's commission schedule", "b": "Goals, constraints, risk tolerance, and asset allocation guidelines", "c": "Guaranteed investment returns", "d": "Client Social Security number only"},
         "b", "IPS captures objectives, constraints, and strategic allocation framework.",
         {"a": "Compensation disclosed elsewhere.", "c": "Returns cannot be guaranteed.", "d": "Much broader than one data point."}, "easy"),
        ("Liquidity needs for a client with three months until a home purchase suggest:",
         {"a": "Aggressive small-cap equity concentration", "b": "Capital preservation and readily accessible funds", "c": "Illiquid private equity lockups", "d": "Maximum leverage in volatile assets"},
         "b", "Short horizons require safety and liquidity over return maximization.",
         {"a": "High volatility risk.", "c": "Illiquid.", "d": "Inappropriate risk."}, "medium"),
        ("Human capital in financial planning refers to:",
         {"a": "The present value of future earned income from work/skills", "b": "Only physical real estate owned", "c": "Collectible art inventory", "d": "Corporate bond holdings exclusively"},
         "a", "Human capital is an economic asset representing earning ability.",
         {"b": "Financial/real assets.", "c": "Different asset class.", "d": "Too narrow."}, "medium"),
        ("A client's risk tolerance assessment should consider:",
         {"a": "Only chronological age using a fixed formula", "b": "Willingness and ability to bear risk plus time horizon and goals", "c": "Only the planner's preferred fund family", "d": "Ignoring liquidity needs entirely"},
         "b", "Risk profiling integrates subjective willingness and objective ability.",
         {"a": "Age alone is insufficient.", "c": "Conflict of interest.", "d": "Liquidity is essential."}, "easy"),
        ("Monte Carlo simulation in planning is used to:",
         {"a": "Model probability of outcomes across varying market assumptions", "b": "Guarantee a single retirement date with certainty", "c": "Eliminate all market risk", "d": "Replace the need for an emergency fund"},
         "a", "Monte Carlo shows range of outcomes given input distributions.",
         {"b": "Probabilistic, not guaranteed.", "c": "Risk remains.", "d": "Emergency fund still needed."}, "medium"),
        ("The balance sheet in a financial plan lists:",
         {"a": "Assets, liabilities, and net worth at a point in time", "b": "Only monthly grocery expenses", "c": "Future income tax brackets exclusively", "d": "Stock analyst ratings"},
         "a", "Balance sheet is a snapshot of financial position.",
         {"b": "Cash flow item.", "c": "Tax planning tool.", "d": "Unrelated."}, "easy"),
        ("A special needs trust is often used to:",
         {"a": "Provide for a disabled beneficiary without disqualifying public benefits", "b": "Avoid all estate taxes automatically for everyone", "c": "Replace life insurance entirely always", "d": "Eliminate the need for a will"},
         "a", "Properly structured SNTs can preserve means-tested benefits eligibility.",
         {"b": "Tax planning varies.", "c": "Insurance may complement.", "d": "Estate documents still needed."}, "hard"),
        ("Cash flow analysis identifies:",
         {"a": "Sources and uses of cash over time to fund goals", "b": "Only historical stock prices", "c": "Corporate earnings per share", "d": "Federal Reserve meeting dates exclusively"},
         "a", "Cash flow planning matches income/expenses to objectives.",
         {"b": "Investment data.", "c": "Corporate metric.", "d": "Macro calendar."}, "easy"),
        ("Education planning with a 529 plan offers potential benefits including:",
         {"a": "Tax-free qualified withdrawals for education in many cases", "b": "Unlimited annual contributions with no gift tax rules ever", "c": "FDIC insurance on equity subaccounts", "d": "Penalty-free use for any purpose always"},
         "a", "529 qualified withdrawals are federally tax-free; state benefits vary.",
         {"b": "Gift tax and plan limits apply.", "c": "Investments aren't FDIC.", "d": "Non-qualified withdrawals may incur tax/penalty."}, "medium"),
        ("A durable power of attorney for finances allows:",
         {"a": "An agent to manage financial matters if the principal becomes incapacitated", "b": "Automatic probate avoidance for all assets always", "c": "The agent to change the principal's will unilaterally", "d": "Only healthcare decisions"},
         "a", "Durable POA survives incapacity; scope is defined in document.",
         {"b": "POA doesn't replace will or avoid all probate.", "c": "Will changes require principal capacity typically.", "d": "Healthcare POA is separate."}, "medium"),
        ("The time value of money concept means:",
         {"a": "A dollar today is worth more than a dollar received later", "b": "Inflation never affects purchasing power", "c": "All future cash flows are equal regardless of timing", "d": "Interest rates are irrelevant to planning"},
         "a", "Money has earning potential; timing affects value.",
         {"b": "Inflation erodes purchasing power.", "c": "Timing matters.", "d": "Rates are central."}, "easy"),
        ("Goal prioritization in planning should:",
         {"a": "Rank objectives by importance, urgency, and feasibility", "b": "Ignore client-stated priorities", "c": "Focus only on the planner's revenue targets", "d": "Eliminate insurance needs always"},
         "a", "Prioritization aligns limited resources to client values.",
         {"b": "Client-centered process.", "c": "Conflict of interest.", "d": "Insurance may be essential."}, "easy"),
        ("A net worth statement showing negative net worth indicates:",
         {"a": "Liabilities exceed assets", "b": "The client has no debt", "c": "Guaranteed bankruptcy immediately", "d": "Tax-exempt status automatically"},
         "a", "Negative net worth = total liabilities > total assets.",
         {"b": "Opposite.", "c": "Solvency depends on cash flow too.", "d": "Unrelated."}, "easy"),
        ("Behavioral coaching in financial planning addresses:",
         {"a": "Biases like loss aversion and recency that affect decisions", "b": "Only technical bond duration math", "c": "Medical diagnosis of clients", "d": "Securities registration requirements exclusively"},
         "a", "Behavioral finance helps clients stick to plans despite biases.",
         {"b": "Technical but not behavioral coaching.", "c": "Outside planner scope.", "d": "Regulatory topic."}, "medium"),
    ])

    qs += pack(E, "investments", [
        ("Modern Portfolio Theory suggests diversification can reduce:",
         {"a": "Unsystematic (company-specific) risk", "b": "All market risk completely", "c": "Inflation risk to zero", "d": "The need for an IPS"},
         "a", "Diversification reduces idiosyncratic risk; market risk remains.",
         {"b": "Systematic risk persists.", "c": "Inflation still matters.", "d": "IPS still valuable."}, "easy"),
        ("A stock's beta of 1.5 historically suggests:",
         {"a": "Lower volatility than the market", "b": "About 50% more sensitivity to market moves than the market", "c": "Zero correlation with the market", "d": "Risk-free returns"},
         "b", "Beta > 1 indicates higher systematic risk than the market.",
         {"a": "Beta < 1.", "c": "Correlated if beta defined.", "d": "Equities aren't risk-free."}, "easy"),
        ("Tax-loss harvesting involves:",
         {"a": "Selling losing positions to offset capital gains, subject to wash-sale rules", "b": "Avoiding all taxes illegally", "c": "Buying identical securities within 30 days to claim loss always", "d": "Only trading municipal bonds in IRAs for tax benefit"},
         "a", "Harvesting realizes losses to offset gains; wash-sale disallows superficial losses.",
         {"b": "Must comply with tax law.", "c": "Wash sale blocks loss if repurchased within 30 days.", "d": "Muni tax exemption wasted in IRA."}, "medium"),
        ("Asset location strategy places:",
         {"a": "Tax-inefficient assets in tax-advantaged accounts when appropriate", "b": "All assets randomly across accounts", "c": "High-turnover funds only in taxable accounts always", "d": "Municipal bonds inside traditional IRAs for maximum benefit"},
         "b", "Location optimizes after-tax returns across account types.",
         {"a": "Random ignores tax efficiency.", "c": "Often opposite: tax-efficient in taxable.", "d": "Muni exemption wasted in tax-deferred IRA."}, "hard"),
        ("Standard deviation in portfolio analysis measures:",
         {"a": "Historical volatility of returns", "b": "Guaranteed future returns", "c": "Dividend yield only", "d": "Credit rating of the issuer exclusively"},
         "a", "Standard deviation quantifies dispersion/volatility of returns.",
         {"b": "Past metric, not guarantee.", "c": "Different measure.", "d": "Fixed income concept."}, "easy"),
        ("An index fund typically aims to:",
         {"a": "Replicate the performance of a benchmark index before fees", "b": "Beat the index by 5% every year guaranteed", "c": "Hold a single stock only", "d": "Avoid all market exposure"},
         "a", "Index funds passively track benchmarks with low turnover.",
         {"b": "No guarantee of outperformance.", "c": "Diversified basket.", "d": "Full market exposure."}, "easy"),
        ("Duration of a bond portfolio primarily measures sensitivity to:",
         {"a": "Interest rate changes", "b": "Stock market beta only", "c": "Currency exchange rates exclusively in all cases", "d": "Corporate earnings surprises only"},
         "a", "Duration estimates price change for a given rate shift.",
         {"b": "Equity metric.", "c": "May matter for foreign bonds but duration is rate sensitivity.", "d": "Equity event."}, "medium"),
        ("Rebalancing a strategic allocation typically involves:",
         {"a": "Selling overweight assets and buying underweight to restore targets", "b": "Abandoning the IPS permanently", "c": "Concentrating in last year's best performer only", "d": "Never reviewing the portfolio"},
         "a", "Rebalancing maintains risk profile after market drift.",
         {"b": "Discipline requires IPS adherence.", "c": "Chasing performance is risky.", "d": "Periodic review needed."}, "easy"),
        ("A Roth IRA conversion moves funds from:",
         {"a": "Traditional/pre-tax IRA to Roth, creating taxable income in conversion year", "b": "Taxable brokerage to checking with no tax ever", "c": "529 plan to HSA without limits always", "d": "Pension to Social Security automatically"},
         "a", "Conversions trigger tax on converted amounts; future Roth growth may be tax-free.",
         {"b": "Taxable events differ.", "c": "Different accounts/rules.", "d": "Separate systems."}, "medium"),
        ("Sharpe ratio compares:",
         {"a": "Excess return per unit of total risk (standard deviation)", "b": "Dividend yield to bond coupon only", "c": "P/E to P/B exclusively", "d": "Tax bracket to marginal rate"},
         "a", "Sharpe = (Return − Risk-free) / Standard deviation.",
         {"b": "Unrelated metrics.", "c": "Valuation ratios.", "d": "Tax concept."}, "hard"),
        ("Dollar-cost averaging is:",
         {"a": "Investing fixed amounts at regular intervals regardless of price", "b": "Timing the market to buy only at lows", "c": "Leveraging margin to maximum always", "d": "A type of municipal bond refunding"},
         "a", "DCA reduces timing risk through consistent investing.",
         {"b": "Market timing strategy.", "c": "Different approach.", "d": "Fixed income structure."}, "easy"),
        ("Alternative investments (e.g., private equity) in client portfolios often feature:",
         {"a": "Illiquidity, higher fees, and limited transparency", "b": "Daily liquidity like money market funds always", "c": "FDIC insurance on equity stakes", "d": "No accreditation requirements ever"},
         "a", "Alts often lock capital and charge performance fees.",
         {"b": "Often multi-year lockups.", "c": "Not insured.", "d": "Often limited to accredited/qualified investors."}, "medium"),
        ("Capital gains on assets held more than one year are generally:",
         {"a": "Long-term gains taxed at preferential rates (subject to current law)", "b": "Always taxed as ordinary income at maximum bracket", "c": "Completely tax-free for all taxpayers always", "d": "Subject only to payroll tax"},
         "a", "Long-term capital gains rates are typically lower than ordinary rates.",
         {"b": "Ordinary rates apply to short-term.", "c": "Tax generally applies.", "d": "Not payroll tax."}, "easy"),
        ("Efficient frontier analysis shows:",
         {"a": "Portfolios with maximum expected return for a given risk level", "b": "Only one optimal stock for all investors", "c": "Guaranteed returns with no volatility", "d": "Insurance premium tables exclusively"},
         "a", "Efficient frontier maps optimal risk/return combinations.",
         {"b": "Diversified portfolios, not single stock.", "c": "Risk always present.", "d": "Unrelated."}, "hard"),
        ("Separately managed accounts (SMAs) differ from mutual funds because SMAs:",
         {"a": "Hold individual securities in the client's name with customization", "b": "Pool all investors into one identical portfolio with no customization", "c": "Are always FDIC insured", "d": "Cannot hold equities"},
         "a", "SMAs offer direct ownership and tax customization.",
         {"b": "That describes mutual funds.", "c": "Securities aren't FDIC.", "d": "Can hold stocks."}, "medium"),
    ])

    qs += pack(E, "tax-estate", [
        ("The annual gift tax exclusion (2024) allows an individual to gift up to approximately:",
         {"a": "$18,000 per donee without using lifetime exemption (amount indexed)", "b": "$1,000 total per year to anyone", "c": "Unlimited gifts to anyone with no reporting ever", "d": "Only gifts to charities count"},
         "a", "Annual exclusion is per recipient; amount is inflation-adjusted.",
         {"b": "Far below actual exclusion.", "c": "Large gifts use lifetime exemption/reporting.", "d": "Individuals also qualify."}, "medium"),
        ("A bypass (credit shelter) trust in estate planning helps:",
         {"a": "Use the deceased spouse's estate tax exemption while providing for surviving spouse", "b": "Eliminate all income taxes forever", "c": "Avoid probate in all jurisdictions automatically always", "d": "Replace beneficiary designations on retirement accounts"},
         "a", "Credit shelter trusts preserve exemption and benefit survivor.",
         {"b": "Income tax still applies.", "c": "Probate rules vary.", "d": "Retirement accounts need separate designations."}, "hard"),
        ("Step-up in basis at death generally means:",
         {"a": "Heirs may receive assets with basis adjusted to fair market value at death", "b": "All capital gains are taxed twice", "c": "Basis is always zero for heirs", "d": "Only applies to retirement accounts always"},
         "a", "Step-up can eliminate embedded capital gains for inherited property.",
         {"b": "Opposite effect.", "c": "Basis resets to FMV typically.", "d": "Retirement accounts have different rules."}, "medium"),
        ("A qualified charitable distribution (QCD) from an IRA allows:",
         {"a": "Direct transfers to charity satisfying RMD for eligible donors (rules apply)", "b": "Unlimited tax-free withdrawals for personal use at any age", "c": "Only donations of physical gold coins", "d": "Avoiding all RMDs permanently without conditions"},
         "a", "QCDs can count toward RMD with charitable benefit if requirements met.",
         {"b": "Must go to charity.", "c": "Cash to qualified charities.", "d": "RMD rules still apply outside QCD."}, "hard"),
        ("Community property states generally treat:",
         {"a": "Most assets acquired during marriage as owned equally by both spouses", "b": "All premarital assets as community automatically always", "c": "Only business income as separate", "d": "Estate tax as irrelevant"},
         "a", "Community property splits marital acquisitions 50/50 in those states.",
         {"b": "Premarital often separate.", "c": "Varies by asset.", "d": "Estate tax still applies."}, "medium"),
        ("Grantor trust status means:",
         {"a": "The grantor is taxed on trust income for income tax purposes in many grantor trusts", "b": "The trust is always exempt from all taxes forever", "c": "Beneficiaries control trust terms during grantor's life always", "d": "Assets cannot be removed from estate ever"},
         "a", "Grantor trusts attribute income to grantor despite separate entity.",
         {"b": "Income tax applies to grantor.", "c": "Grantor typically retains certain powers.", "d": "Estate inclusion depends on retained powers."}, "hard"),
        ("The unlimited marital deduction allows:",
         {"a": "Transfers to a U.S. citizen spouse generally free of gift/estate tax", "b": "Transfers to any nonresident without limit always", "c": "Complete avoidance of income tax on all assets", "d": "Gifts to grandchildren without generation-skipping tax ever"},
         "a", "Spousal transfers to U.S. citizen spouse are generally unlimited deduction.",
         {"b": "Non-citizen spouse needs QDOT or limits.", "c": "Income tax separate.", "d": "GST tax may apply."}, "medium"),
        ("A 1031 like-kind exchange defers gain on:",
         {"a": "Investment or business real property exchanged for qualifying like-kind property", "b": "Personal residence sales always", "c": "Stock portfolio swaps", "d": "Collectible art to cryptocurrency always"},
         "a", "1031 applies to qualifying real property held for investment/business.",
         {"b": "Primary home may use Section 121 exclusion instead.", "c": "Securities don't qualify.", "d": "Not like-kind typically."}, "medium"),
        ("Portability of the deceased spouse's unused estate tax exemption (DSUE) allows:",
         {"a": "Surviving spouse to use leftover exemption if election filed timely", "b": "Unlimited lifetime gifts without tax ever", "c": "Automatic exemption for all non-spouse beneficiaries", "d": "Avoiding all state inheritance taxes always"},
         "a", "Portability requires timely Form 706 election.",
         {"b": "Gift/estate limits remain.", "c": "Applies to surviving spouse's estate.", "d": "State taxes vary."}, "hard"),
        ("A revocable living trust primarily helps with:",
         {"a": "Probate avoidance and incapacity management while grantor is alive", "b": "Immediate estate tax elimination for all assets always", "c": "Creditor protection from grantor's debts in all states always", "d": "Replacing all beneficiary designations automatically"},
         "a", "Revocable trusts manage assets during life and at death outside probate.",
         {"b": "Grantor still taxed; estate inclusion possible.", "c": "Revocable trusts usually don't shield grantor creditors.", "d": "Retirement/life insurance need separate designations."}, "medium"),
        ("The kiddie tax taxes unearned income of certain children:",
         {"a": "At parents' marginal rate beyond a small threshold (rules apply)", "b": "At zero percent always", "c": "Only on earned wages from a job", "d": "Never applies after age 10"},
         "a", "Kiddie tax limits income-shifting to children.",
         {"b": "Tax applies above threshold.", "c": "Unearned income focus.", "d": "Applies to qualifying children under rules."}, "medium"),
        ("An irrevocable life insurance trust (ILIT) can help:",
         {"a": "Keep life insurance proceeds outside the insured's taxable estate if properly structured", "b": "Allow the insured to retain unlimited incidents of ownership always", "c": "Eliminate the need for premiums", "d": "Guarantee insurability without underwriting"},
         "a", "ILIT ownership removes proceeds from estate if no retained control.",
         {"b": "Retained control causes estate inclusion.", "c": "Premiums still required.", "d": "Underwriting still applies."}, "hard"),
        ("Capital loss carryforward rules allow individuals to:",
         {"a": "Offset future capital gains and up to $3,000 of ordinary income annually (current law)", "b": "Deduct unlimited losses against wages forever", "c": "Avoid wash-sale rules entirely", "d": "Convert losses to tax credits dollar-for-dollar always"},
         "a", "Excess capital losses carry forward with annual ordinary income limit.",
         {"b": "Ordinary offset capped.", "c": "Wash sale still applies.", "d": "Credits differ from deductions."}, "medium"),
        ("A charitable remainder trust (CRT) provides:",
         {"a": "Income to donor/beneficiaries for a term with remainder to charity", "b": "Immediate full deduction equal to entire estate value always", "c": "No tax reporting requirements ever", "d": "Only benefits to private foundations exclusively"},
         "a", "CRT splits income interest and charitable remainder.",
         {"b": "Deduction based on actuarial remainder value.", "c": "Trust files returns.", "d": "Public charities can be remaindermen."}, "hard"),
        ("Estate planning for blended families often requires:",
         {"a": "Clear documents balancing current spouse and children from prior relationships", "b": "Relying solely on intestacy laws without a will", "c": "Ignoring beneficiary designations on retirement accounts", "d": "Only oral promises without written plans"},
         "a", "Blended families need explicit trusts/wills and coordinated designations.",
         {"b": "Intestacy may not match intent.", "c": "Designations override will for those assets.", "d": "Written plan essential."}, "easy"),
    ])

    qs += pack(E, "retirement-risk", [
        ("Required Minimum Distributions (RMDs) from traditional IRAs generally begin:",
         {"a": "At the statutory RMD age under current law (e.g., 73 under SECURE 2.0 for many)", "b": "At age 18 for all accounts", "c": "Never; traditional IRAs have no RMDs", "d": "Only while still employed with current employer always"},
         "a", "RMD age has been adjusted by recent legislation; know current threshold.",
         {"b": "Too early.", "c": "Traditional IRAs have RMDs.", "d": "Still-applicable IRA rules."}, "medium"),
        ("The 4% rule in retirement withdrawal research suggests:",
         {"a": "Initial withdrawal of ~4% of portfolio adjusted for inflation historically sustainable ~30 years", "b": "Withdrawing 100% in year one always works", "c": "Never adjusting withdrawals for inflation", "d": "Only applicable to pension plans exclusively"},
         "a", "Trinity study popularized ~4% as a starting withdrawal guideline.",
         {"b": "Unsustainable.", "c": "Real spending power requires inflation adjustment.", "d": "Portfolio withdrawal concept."}, "medium"),
        ("Medicare Part B premiums are typically:",
         {"a": "Income-tested for higher earners via IRMAA surcharges", "b": "Zero for all retirees regardless of income", "c": "Paid only by employers for all retirees", "d": "Identical to Part D drug premiums always"},
         "a", "Higher Modified AGI increases Part B/D premiums via IRMAA.",
         {"b": "Base premium applies; surcharges for high income.", "c": "Retirees pay generally.", "d": "Separate parts/premiums."}, "medium"),
        ("Long-term care insurance primarily covers:",
         {"a": "Assistance with activities of daily living in nursing/home/community settings", "b": "Routine dental cleanings only", "c": "Stock market losses", "d": "Auto liability claims exclusively"},
         "a", "LTC insurance helps pay for custodial/care services.",
         {"b": "Dental is separate.", "c": "Investment risk.", "d": "Auto insurance."}, "easy"),
        ("Social Security spousal benefits may provide:",
         {"a": "Up to 50% of worker's PIA if higher than own benefit (rules apply)", "b": "Double the worker's full benefit automatically always", "c": "Benefits only if never married", "d": "Payments starting at age 55 without reduction always"},
         "a", "Spousal benefit is max 50% of worker's PIA if advantageous.",
         {"b": "Not double.", "c": "Marriage creates spousal rights.", "d": "Early claiming reduces benefits."}, "medium"),
        ("Sequence of returns risk in retirement refers to:",
         {"a": "Poor early returns when withdrawals begin can deplete portfolio faster", "b": "Guaranteed order of all future market returns", "c": "Only bond coupon payment timing", "d": "Inflation being zero always"},
         "a", "Withdrawals plus early losses compound harm to sustainability.",
         {"b": "Unknown future.", "c": "Broader portfolio effect.", "d": "Inflation varies."}, "hard"),
        ("A qualified longevity annuity contract (QLAC) in a retirement plan allows:",
         {"a": "Deferring a portion of RMDs by purchasing deferred income starting later", "b": "Unlimited penalty-free withdrawals before 59½ always", "c": "Complete avoidance of all annuity taxation forever", "d": "Only immediate lump-sum payouts"},
         "a", "QLAC rules permit RMD deferral on premium up to limits.",
         {"b": "Early withdrawal penalties may apply elsewhere.", "c": "Annuity income is taxable when received.", "d": "Deferred income feature."}, "hard"),
        ("Disability income insurance replaces:",
         {"a": "A portion of earned income if unable to work due to disability", "b": "All investment losses in a brokerage account", "c": "Property damage from fire exclusively", "d": "Retirement account RMDs automatically"},
         "a", "DI insurance protects human capital/earned income.",
         {"b": "Investment risk.", "c": "Property insurance.", "d": "RMDs are separate."}, "easy"),
        ("Umbrella liability insurance provides:",
         {"a": "Excess liability coverage above auto/home policy limits", "b": "Health insurance for routine doctor visits only", "c": "Life insurance death benefit", "d": "Coverage for stock market declines"},
         "a", "Umbrella adds high-limit personal liability protection.",
         {"b": "Health insurance.", "c": "Life insurance.", "d": "Investment risk."}, "easy"),
        ("Roth IRA contributions are:",
         {"a": "Not tax-deductible but qualified withdrawals may be tax-free", "b": "Always deductible regardless of income", "c": "Subject to RMDs during owner's lifetime always", "d": "Limited to employer match only"},
         "a", "Roth uses after-tax contributions; earnings tax-free if qualified.",
         {"b": "Income limits and deductibility differ from traditional.", "c": "Roth IRAs generally no RMD during owner life.", "d": "Individual IRA, not employer match."}, "easy"),
        ("An annuity's mortality credit comes from:",
         {"a": "Pooling longevity risk among annuitants", "b": "Stock market capital gains only", "c": "FDIC deposit insurance", "d": "Social Security payroll tax exclusively"},
         "a", "Survivors' subsidies support those living longer in pooled annuities.",
         {"b": "Insurance mechanism.", "c": "Not FDIC.", "d": "Separate program."}, "hard"),
        ("Health Savings Accounts (HSAs) require enrollment in:",
         {"a": "A high-deductible health plan (HDHP) to contribute", "b": "Any PPO without deductible always", "c": "Medicare Part A exclusively", "d": "Medicaid only"},
         "a", "HSA eligibility tied to qualifying HDHP coverage.",
         {"b": "HDHP required.", "c": "Medicare generally ends HSA contributions.", "d": "Commercial HDHP typically."}, "medium"),
        ("Life insurance needs analysis for income replacement often uses:",
         {"a": "Human life value or needs approach estimating debts, income, and goals", "b": "Only the face value of existing auto policies", "c": "Random percentage with no analysis", "d": "Mandatory minimum of $10,000 for everyone"},
         "a", "Needs analysis quantifies economic loss to dependents.",
         {"b": "Auto unrelated.", "c": "Professional standard requires analysis.", "d": "Individual calculation."}, "easy"),
        ("Inflation risk in retirement planning means:",
         {"a": "Rising prices erode purchasing power of fixed income streams", "b": "All costs decrease over time", "c": "Social Security never adjusts", "d": "Bonds have no interest-rate sensitivity"},
         "a", "Inflation reduces real value of nominal payments.",
         {"b": "Opposite.", "c": "SS has COLA adjustments.", "d": "Bonds sensitive to rates."}, "easy"),
        ("Professional liability (E&O) insurance for planners protects against:",
         {"a": "Claims of negligent advice or errors in professional services", "b": "Client stock market losses due to normal volatility always", "c": "Personal auto accidents exclusively", "d": "All investment underperformance regardless of suitability"},
         "a", "E&O covers professional negligence claims, not market risk per se.",
         {"b": "Market risk generally not covered.", "c": "Auto policy.", "d": "Suitability matters for claims."}, "medium"),
    ])

    return qs


if __name__ == "__main__":
    write_bank(E, build())
