#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "electrical-journeyman-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "nec", [
        ("NEC Article 210 covers:",
         {"a": "Branch circuits and outlets", "b": "Swimming pool chemistry exclusively always always", "c": "HVAC refrigerant types exclusively always always", "d": "Plumbing vent sizing exclusively always always"},
         "a", "Article 210 establishes branch-circuit ratings and requirements.",
         {"b": "Not NEC scope.", "c": "Mechanical code.", "d": "Plumbing code."}, "easy"),
        ("The NEC is published by:",
         {"a": "NFPA (National Fire Protection Association)", "b": "FDA exclusively always always", "c": "USDA exclusively always always", "d": "FAA exclusively always always"},
         "a", "NFPA 70 is the National Electrical Code.",
         {"b": "Food/drug agency.", "c": "Agriculture.", "d": "Aviation."}, "easy"),
        ("A continuous load runs for:",
         {"a": "3 hours or more", "b": "Exactly 30 seconds always always", "c": "Less than 1 minute always always defining continuous always always", "d": "Only during lightning storms always always"},
         "a", "NEC defines continuous load as expected 3 hours or more.",
         {"b": "Too short.", "c": "Minimum duration 3 hours.", "d": "Not weather dependent."}, "medium"),
        ("Equipment grounding conductors (EGC) provide:",
         {"a": "Fault current path to clear overcurrent devices quickly", "b": "Normal return path for load current always always exclusively always", "c": "Only lightning protection exclusively always always with no fault role ever always always", "d": "Decorative conduit support exclusively always always"},
         "a", "EGC bonds equipment to ground for safety during faults.",
         {"b": "Neutral carries normal current in some systems.", "c": "Also fault path.", "d": "Safety function."}, "medium"),
        ("Article 250 addresses:",
         {"a": "Grounding and bonding", "b": "Kitchen appliance recipes exclusively always always", "c": "Roof shingle colors exclusively always always", "d": "Window tint exclusively always always"},
         "a", "Article 250 is central grounding/bonding requirements.",
         {"b": "Unrelated.", "c": "Building finish.", "d": "Unrelated."}, "easy"),
        ("Working space about electrical equipment (110.26) requires:",
         {"a": "Clear depth, width, and height for safe operation and maintenance", "b": "Storage of combustibles in front of panels always always", "c": "Zero clearance always always acceptable always always", "d": "Only 6 inches width always always regardless of equipment always always"},
         "a", "110.26 specifies minimum clear working space by voltage condition.",
         {"b": "Prohibited storage.", "c": "Clearances mandatory.", "d": "Width at least 30 inches or equipment width."}, "medium"),
        ("GFCI protection is required for 125V, 15A and 20A receptacles in:",
         {"a": "Bathrooms, garages, outdoors, and other locations per 210.8", "b": "Only industrial 480V motor starters always always exclusively always", "c": "No locations ever always under any NEC edition always always", "d": "Only data centers always always exclusively always"},
         "a", "210.8 lists dwelling and other locations requiring GFCI.",
         {"b": "Low voltage receptacle focus.", "c": "Required in many locations.", "d": "Dwelling/commercial rules apply."}, "medium"),
        ("AFCI protection in dwelling units protects:",
         {"a": "Branch circuits from arc faults that can cause fires", "b": "Only ground faults exclusively always as AFCI function always always", "c": "Only lightning exclusively always always", "d": "Only overloads exclusively always always without arc detection ever always always"},
         "a", "AFCI devices detect dangerous arcing on circuits.",
         {"b": "GFCI is different.", "c": "Arc fault focus.", "d": "Also arc detection."}, "medium"),
        ("Box fill calculations (314.16) ensure:",
         {"a": "Conductor volume in box does not exceed box capacity", "b": "Unlimited wires in any box always always", "c": "Only box color matters always always", "d": "No splices allowed ever always in boxes always always"},
         "a", "Each conductor/stripe/device counts toward cubic inch allowance.",
         {"b": "Overfill causes overheating.", "c": "Volume calculation required.", "d": "Splices allowed with fill limits."}, "hard"),
        ("The ampacity of conductors is found in:",
         {"a": "Table 310.16 (or applicable tables) with adjustments", "b": "Only guesswork always always without tables ever always always", "c": "Plumbing code tables exclusively always always", "d": "Food calorie charts exclusively always always"},
         "a", "310.16 lists ampacities; 310.15 adjustments for temp/bundling.",
         {"b": "Code tables required.", "c": "Wrong code.", "d": "Unrelated."}, "easy"),
        ("Dedicated equipment space (110.26(E)) above panelboards:",
         {"a": "Must be kept clear of foreign systems to 6 ft above or structural ceiling", "b": "May be filled with ductwork always always without restriction always always", "c": "Only applies to battery clocks always always", "d": "Is optional always always in all occupancies always always"},
         "a", "Foreign systems cannot encroach dedicated electrical space.",
         {"b": "Ducts/piping restricted.", "c": "Panelboards/switchboards.", "d": "Mandatory rule."}, "hard"),
        ("Receptacle spacing in dwelling unit walls (210.52) generally requires:",
         {"a": "Receptacles so no point along floor line is more than 6 ft from a receptacle", "b": "One receptacle per entire house always always", "c": "Receptacles only in attic always always", "d": "No receptacles in kitchens ever always"},
         "a", "210.52(A) 6-foot rule along wall lines; specific rooms have additional.",
         {"b": "Insufficient.", "c": "Living areas need outlets.", "d": "Countertop rules apply."}, "medium"),
        ("Overcurrent protection must not exceed conductor ampacity except:",
         {"a": "Where 240.4(B) or specific exceptions allow next standard size up", "b": "Never any exception ever always under NEC always always", "c": "Always double ampacity always always as rule always always", "d": "Only for plumbing pipes always always"},
         "a", "240.4 governs OCPD sizing relative to conductor ampacity.",
         {"b": "Exceptions exist.", "c": "Not arbitrary doubling.", "d": "Electrical conductors."}, "hard"),
        ("Listed equipment means:",
         {"a": "Evaluated by recognized testing lab for safety standard compliance", "b": "Any homemade device without evaluation always always acceptable always always", "c": "Only listed in phone book always always", "d": "Approved by neighbor always always"},
         "a", "Listing (UL etc.) indicates tested to applicable standards.",
         {"b": "Must be listed/approved.", "c": "Product certification.", "d": "Authority having jurisdiction approves."}, "easy"),
        ("NEC scope (Article 90) covers:",
         {"a": "Installation of electrical conductors and equipment", "b": "Only utility transmission beyond service point always always exclusively always", "c": "Only battery manufacturing always always exclusively always", "d": "Only solar manufacturing plants always always exclusively always without installation always always"},
         "a", "NEC applies to premises wiring from service to utilization.",
         {"b": "Utility covered elsewhere often.", "c": "Broader installations.", "d": "Installations included."}, "easy"),
    ])

    qs += pack(E, "wiring", [
        ("NM-B (Romex) cable is permitted in:",
         {"a": "Dry, protected locations per 334 (typically not wet or exposed)", "b": "Underground direct burial always always without conduit ever always always", "c": "Commercial parking garage exposed always always always", "d": "Swimming pool interior always always always"},
         "a", "334 restricts NM use; not in wet/damp or subject to physical damage.",
         {"b": "UF or conduit wiring needed.", "c": "Often requires raceway.", "d": "Special pool bonding rules."}, "medium"),
        ("Conductor color: grounded (neutral) conductor is typically:",
         {"a": "White or gray", "b": "Green always always for neutral always always", "c": "Bare only always always for insulated neutral always always", "d": "Red always always for all neutrals always always"},
         "a", "200.6 identifies white/gray for grounded conductor.",
         {"b": "Green is EGC.", "c": "Insulated neutral white/gray.", "d": "Red often ungrounded."}, "easy"),
        ("Equipment grounding conductor insulation color is typically:",
         {"a": "Green or bare", "b": "White always always for EGC always always", "c": "Blue exclusively always always for all EGC always always", "d": "Orange exclusively always always for all EGC always always"},
         "a", "250.119 specifies green or bare for EGC.",
         {"b": "White is neutral.", "c": "Not standard EGC.", "d": "Not standard EGC."}, "easy"),
        ("Maximum number of 12 AWG THHN conductors in 1/2\" EMT depends on:",
         {"a": "Chapter 9 Table 1 and conductor fill (often about 9 for 40% fill)", "b": "Always unlimited always always in any conduit always always", "c": "Only conduit color always always", "d": "Only voltage always always without fill calculation ever always always"},
         "a", "Annex C tables give conductor fill limits per raceway size.",
         {"b": "Fill limits apply.", "c": "Mathematical fill.", "d": "Fill and ampacity both matter."}, "hard"),
        ("Splicing conductors must be made in:",
         {"a": "Approved box or fitting with accessible cover", "b": "Hidden inside wall without access always always always", "c": "Only with tape and no box always always as permanent always always", "d": "Under carpet always always without enclosure always always"},
         "a", "300.15 requires box for splices unless exempt equipment.",
         {"b": "Must be accessible.", "c": "Box required.", "d": "Enclosure required."}, "easy"),
        ("Voltage drop should be considered because excessive drop causes:",
         {"a": "Poor equipment performance and wasted energy", "b": "Improved motor torque always always from low voltage always always", "c": "No effect ever always on loads always always", "d": "Automatic code compliance always always regardless of length always always"},
         "a", "210.19(A) informational note suggests ~3% branch/feeder limits often used.",
         {"b": "Motors struggle on low voltage.", "c": "Performance suffers.", "d": "Design consideration."}, "medium"),
        ("Three-way switches control a load from:",
         {"a": "Two locations using traveler conductors between switches", "b": "Only one location always always exclusively always", "c": "Three locations without 4-way switches ever always always", "d": "Only with wireless magic always always without conductors ever always always"},
         "a", "Two 3-way switches and travelers allow dual control.",
         {"b": "Two locations.", "c": "More locations need 4-way switches.", "d": "Wired travelers required."}, "easy"),
        ("MC cable differs from AC cable because MC:",
         {"a": "Uses full size aluminum interlocked armor as EGC (typical) without separate thin strip", "b": "Has no metal armor ever always always", "c": "Is only for 600V DC always always exclusively always", "d": "Cannot be used indoors ever always always"},
         "a", "AC has internal bonding strip; MC armor often serves as EGC.",
         {"b": "Metal clad.", "c": "Common 120/208/240V use.", "d": "Indoor permitted."}, "hard"),
        ("Pull boxes are sized per:",
         {"a": "314.28 based on conduit trade size and number of bends/conductors", "b": "Smallest box available always always regardless of pull always always", "c": "Only aesthetic preference always always", "d": "Random choice always always"},
         "a", "314.28 requires adequate space for conductor bending radius.",
         {"b": "Minimum dimensions specified.", "c": "Code driven.", "d": "Calculated."}, "medium"),
        ("Identifying ungrounded conductors: 208Y/120V system typically uses:",
         {"a": "Black, red, blue for phases; white neutral", "b": "All white always always for every conductor always always", "c": "Pink exclusively always always for all phases always always", "d": "No identification required ever always always"},
         "a", "Common color code practice per 200.7 and local convention.",
         {"b": "Phases distinguished.", "c": "Standard colors.", "d": "Identification required."}, "easy"),
        ("Switch loops must:",
         {"a": "Provide grounded conductor to switch location per current NEC dwelling requirements", "b": "Never have neutral at switch always always in new work always always post-2011 NEC changes always always", "c": "Use only ungrounded conductors always always without exception ever always always in all cases always always", "d": "Bypass all boxes always always"},
         "a", "404.2(C) requires neutral at switch controlling loads in dwelling.",
         {"b": "Neutral now required in many switch locations.", "c": "Neutral required.", "d": "Box required."}, "hard"),
        ("Underground service lateral conductors entering building must:",
         {"a": "Be protected from physical damage and meet burial depth/raceway rules", "b": "Lie on lawn surface always always without cover always always", "c": "Use extension cords always always as permanent always always", "d": "Cross pool bottom unprotected always always"},
         "a", "300.5 specifies burial depths and raceway where required.",
         {"b": "Depth required.", "c": "Not permitted.", "d": "Hazardous."}, "medium"),
        ("Multiwire branch circuits share:",
         {"a": "Neutral with opposing ungrounded conductors on different phases", "b": "Only one ungrounded conductor always always without neutral ever always always", "c": "No common neutral ever always always in any circuit always always", "d": "Only DC power always always exclusively always"},
         "a", "Multiwire circuits reduce neutral current when loads balanced.",
         {"b": "Shared neutral typical.", "c": "Neutral shared.", "d": "AC systems."}, "medium"),
        ("Torque requirements for terminations:",
         {"a": "Should follow manufacturer specifications; 110.14 requires proper tightening", "b": "Hand tight only always always for all lugs always always", "c": "Maximum impact wrench always always without spec always always", "d": "Never inspect after tightening always always"},
         "a", "110.14(A) and listing require adequate torque for reliable connection.",
         {"b": "Listed torque values.", "c": "Over-torque damages.", "d": "Verification good practice."}, "medium"),
        ("Cable support for NM-B must occur within:",
         {"a": "12 inches of box and every 4.5 ft along run (334.30)", "b": "10 feet from every box always always exclusively always", "c": "Never supported always always", "d": "Only at panel always always one support total always always"},
         "a", "334.30 requires stapling/support intervals.",
         {"b": "12 in. and 4.5 ft rules.", "c": "Support required.", "d": "Multiple supports."}, "easy"),
    ])

    qs += pack(E, "services", [
        ("Service disconnecting means must be:",
         {"a": "Readily accessible and located per 230.70 near meter/service entrance", "b": "Hidden behind locked mystery door always always without access always always", "c": "Only operable by utility always always with no customer disconnect ever always always", "d": "Optional for all services always always under NEC always always"},
         "a", "230.70 requires main disconnect at readily accessible location.",
         {"b": "Accessibility required.", "c": "Customer disconnect required.", "d": "Mandatory."}, "easy"),
        ("Service entrance conductors are sized from:",
         {"a": "Calculated load per Article 220 and 230.42/230.82 rules", "b": "Only breaker handle size always always without calculation ever always always", "c": "Wire color preference always always", "d": "Neighbor's service size always always"},
         "a", "220 load calc determines minimum service conductor ampacity.",
         {"b": "Calculation required.", "c": "Ampacity not color.", "d": "Individual load."}, "medium"),
        ("Grounding electrode system for service includes:",
         {"a": "Rod(s), plate, concrete encased electrode, or metal underground pipe where available", "b": "Only plastic pipe always always as electrode always always", "c": "Painted drywall screw always always as sole electrode always always", "d": "No grounding ever always required always always"},
         "a", "250.52 lists acceptable grounding electrodes.",
         {"b": "Non conductive.", "c": "Inadequate.", "d": "Required."}, "medium"),
        ("Overhead service clearance from windows:",
         {"a": "Must meet 230.24(B) clearances from openings not designed for conductors", "b": "May touch window always always", "c": "No clearances ever always specified always always", "d": "Only underground rules apply always always"},
         "a", "230.24 specifies vertical/horizontal clearances from buildings.",
         {"b": "Clearance required.", "c": "Table values exist.", "d": "Overhead specific."}, "hard"),
        ("Meter socket is typically:",
         {"a": "Utility/customer demarcation point; not load center unless combined", "b": "Same as main panel always always with all branch breakers always always inside meter always always", "c": "Only for gas metering always always", "d": "Optional decoration always always"},
         "a", "Meter measures service; disconnect/panel often separate.",
         {"b": "May be combined unit.", "c": "Electrical.", "d": "Functional equipment."}, "easy"),
        ("Service lateral vs service drop:",
         {"a": "Lateral is underground; drop is overhead from utility", "b": "Identical terms always always interchangeable always always without difference ever always always", "c": "Lateral always overhead always always", "d": "Drop always underground always always"},
         "a", "NEC definitions distinguish overhead drop vs underground lateral.",
         {"b": "Different terms.", "c": "Lateral underground.", "d": "Drop overhead."}, "easy"),
        ("Parallel service conductors must:",
         {"a": "Be same length, material, size, and termination per 310.10(H)", "b": "Different sizes always always in same phase always always", "c": "Share neutral only on one pipe always always unbalanced always always", "d": "Never need equal impedance always always"},
         "a", "Parallel runs require equal current sharing characteristics.",
         {"b": "Must match.", "c": "Each phase paralleled properly.", "d": "Equal length/size."}, "hard"),
        ("230.82 lists permitted loads connected to service conductors:",
         {"a": "Supply-side connections like certain solar, MGTs per rules—not all branch loads", "b": "Every branch circuit directly always always without disconnect ever always always", "c": "Only lighting always always exclusively always", "d": "Nothing ever always connected always always"},
         "a", "Most loads connect downstream of service disconnect; limited exceptions.",
         {"b": "Disconnect required for most.", "c": "Broad loads downstream.", "d": "Service feeds equipment."}, "hard"),
        ("Neutral conductor on service carries:",
         {"a": "Unbalanced current and harmonic return on single-phase and some 3-phase", "b": "Never any current always always under balanced load always always exclusively always", "c": "Only lightning always always", "d": "Only DC always always on AC service always always"},
         "a", "Grounded conductor carries difference in phase currents.",
         {"b": "Unbalanced/harmonic current flows.", "c": "Normal load return.", "d": "AC system."}, "medium"),
        ("Service equipment rating must be at least:",
         {"a": "Calculated load but not less than minimums in 230.79 for dwelling", "b": "15 amperes for all 400A homes always always", "c": "1 amp always always maximum always always", "d": "Unlimited without calculation always always"},
         "a", "230.79: dwelling minimum often 100A (3-wire) with exceptions.",
         {"b": "100A common minimum.", "c": "Too small.", "d": "Load calc governs."}, "medium"),
        ("Utility service point demarcation determines:",
         {"a": "Who owns conductors and which code/rules apply beyond point", "b": "Only paint color always always", "c": "Only internet speed always always", "d": "Employee lunch menu always always"},
         "a", "Ownership split between utility and customer wiring.",
         {"b": "Legal/technical boundary.", "c": "Unrelated.", "d": "Unrelated."}, "medium"),
        ("Transformers supplying building separately derived systems require:",
         {"a": "Bonding and grounding per 250.30", "b": "No grounding ever always always", "c": "Only primary protection always always without secondary always always", "d": "Floating ungrounded always always without exception ever always always as mandatory always always"},
         "a", "SDS systems need grounding electrode and bonding jumper rules.",
         {"b": "Grounding required.", "c": "Secondary rules apply.", "d": "Must be grounded typically."}, "hard"),
        ("Class 160 service overcurrent device maximum for dwelling:",
         {"a": "Not standard—services typically 100A-400A; 160A may exist as equipment rating context", "b": "15A always always maximum service always always for all dwellings always always", "c": "10,000A minimum always always residential always always", "d": "No OCPD allowed always always"},
         "a", "Service OCPD sized to conductor and load; common 100-200A residential.",
         {"b": "Higher common.", "c": "Unrealistic.", "d": "Required."}, "medium"),
        ("Emergency disconnect for one- and two-family dwellings (230.85):",
         {"a": "Requires readily accessible external disconnect as of recent NEC cycles", "b": "Prohibits any disconnect always always", "c": "Only inside locked attic always always", "d": "Only for commercial always always never dwellings always always"},
         "a", "2020 NEC 230.85 added emergency disconnect requirement for dwellings.",
         {"b": "Disconnect required.", "c": "Readily accessible.", "d": "Dwelling specific."}, "hard"),
        ("Service raceway seal where underground conductors enter building:",
         {"a": "May be required to prevent gas/moisture migration per 300.5(G) and 230.8", "b": "Never sealed always always", "c": "Filled with gasoline always always", "d": "Open hole preferred always always"},
         "a", "Sealing prevents hazardous gas entry from underground ducts.",
         {"b": "Sealing often required.", "c": "Dangerous.", "d": "Seal required."}, "medium"),
    ])

    qs += pack(E, "safety", [
        ("Arc flash hazard analysis helps determine:",
         {"a": "PPE category and approach boundaries for energized work", "b": "Only wire color always always", "c": "Lunch break timing always always", "d": "Conduit paint shade always always"},
         "a", "NFPA 70E uses incident energy to select PPE.",
         {"b": "Safety study.", "c": "Unrelated.", "d": "Unrelated."}, "medium"),
        ("Lockout/tagout before electrical work:",
         {"a": "De-energize and verify absence of voltage before contact", "b": "Work hot always always as first choice always always", "c": "Only tag without locking always always sufficient always always alone always always", "d": "Ask coworker to guess always always if live always always"},
         "a", "110.13/OSHA require verified de-energization for most work.",
         {"b": "Energized work only where permitted with PPE.", "c": "Lock and verify.", "d": "Test before touch."}, "easy"),
        ("Insulated tools are rated by:",
         {"a": "ASTM/ISO standards for voltage rating (e.g., 1000V)", "b": "Weight only always always", "c": "Handle color only always always without rating ever always always", "d": "Price exclusively always always"},
         "a", "Rated insulated tools protect against accidental contact.",
         {"b": "Voltage rating matters.", "c": "Markings show rating.", "d": "Certification required."}, "medium"),
        ("First aid for electrical shock victim includes:",
         {"a": "De-energize if safe, call EMS, begin CPR if needed", "b": "Pull victim by still-energized wire always always", "c": "Ignore until lunch always always", "d": "Pour water on panel always always"},
         "a", "Ensure rescuer safety; CPR/AED if not breathing.",
         {"b": "Rescuer could be shocked.", "c": "Immediate response.", "d": "Water increases conductance."}, "easy"),
        ("Confined space with electrical equipment may have atmospheric hazards including:",
         {"a": "Low oxygen, toxic gases, or flammable vapors", "b": "Only bright lighting always always", "c": "Excess happiness always always", "d": "No hazards ever always in vaults always always"},
         "a", "Manholes/vaults require gas testing before entry.",
         {"b": "Test atmosphere.", "c": "Serious hazards possible.", "d": "Ventilation/testing."}, "medium"),
        ("Live-dead-live test sequence verifies:",
         {"a": "Tester works on known live, confirms dead, then recheck live", "b": "Only once touching bare hand always always", "c": "Meter never calibrated always always", "d": "Voltage presence ignored always always"},
         "a", "Three-point test confirms meter function and zero energy.",
         {"b": "Never touch bare conductors.", "c": "Calibrate meter.", "d": "Verification critical."}, "hard"),
        ("GFCI devices protect personnel by:",
         {"a": "Detecting imbalance between hot and neutral (~5mA trip)", "b": "Increasing voltage always always", "c": "Removing ground rod always always", "d": "Only protecting equipment not people always always exclusively always"},
         "a", "GFCI trips on ground fault current through person/equipment.",
         {"b": "Doesn't raise voltage.", "c": "Grounding still needed.", "d": "Personnel protection."}, "easy"),
        ("Approach boundary 'restricted approach' means:",
         {"a": "Only qualified persons with appropriate PPE may enter", "b": "Anyone may enter freely always always", "c": "No PPE needed always always", "d": "Only applies to plumbing always always"},
         "a", "70E boundaries define shock/arc flash limits.",
         {"b": "Qualified only.", "c": "PPE required.", "d": "Electrical safety."}, "hard"),
        ("Temporary wiring on construction sites must:",
         {"a": "Meet NEC Article 590 including protection from damage", "b": "Use frayed cords always always", "c": "Run through puddles always always unprotected always always", "d": "Ignore GFCI always always"},
         "a", "590 permits temporary power with specific requirements.",
         {"b": "Damaged cords unsafe.", "c": "GFCI often required.", "d": "Protection required."}, "medium"),
        ("Ladder safety near electrical equipment requires:",
         {"a": "Non-conductive side rails or maintain clearance from energized parts", "b": "Metal ladder touching overhead lines always always", "c": "Only one foot on ladder always always as rule always always", "d": "Paint ladder with conductive foil always always"},
         "a", "Fiberglass ladders reduce shock risk; maintain clearances.",
         {"b": "Electrocution hazard.", "c": "3-point contact rule.", "d": "Conductive increases risk."}, "easy"),
        ("Incident energy on 480V switchgear can be:",
         {"a": "Severe enough to require arc-rated suit and face shield", "b": "Always harmless always always at any fault always always", "c": "Only visible as spark never burns always always", "d": "Eliminated by wearing regular cotton always always alone always always"},
         "a", "Arc flash can cause fatal burns; PPE rated to cal/cm².",
         {"b": "Dangerous.", "c": "Thermal injury.", "d": "Special arc-rated PPE."}, "medium"),
        ("Electrical burns at entry/exit points indicate:",
         {"a": "Current passed through body causing tissue damage", "b": "Only sunburn always always", "c": "No internal injury ever always always", "d": "Allergic reaction always always exclusively always"},
         "a", "Internal damage may exceed visible skin burns.",
         {"b": "Electrical trauma.", "c": "Medical evaluation needed.", "d": "Current path injury."}, "medium"),
        ("Housekeeping in electrical rooms:",
         {"a": "Keep combustibles out of working space and equipment area", "b": "Store cardboard against transformer always always", "c": "Block disconnect access always always", "d": "Oil soaked rags near breakers always always"},
         "a", "110.26(B) prohibits storage in required working space.",
         {"b": "Fire hazard.", "c": "Access required.", "d": "Ignition risk."}, "easy"),
        ("Testing for absence of voltage uses:",
         {"a": "Properly rated test instrument contacting all conductors", "b": "Guess by sound always always", "c": "Wet finger test always always", "d": "Flip breaker randomly always always without verification always always"},
         "a", "110.13/70E require verified de-energization.",
         {"b": "Must test.", "c": "Fatal method.", "d": "Verify dead."}, "easy"),
        ("Qualified person per NEC means:",
         {"a": "One who has skills and knowledge related to construction and operation for safety", "b": "Any homeowner always always without training ever always always", "c": "Only engineer with PE always always exclusively always for all tasks always always", "d": "Person who owns multimeter always always regardless of knowledge always always"},
         "a", "Qualified = trained/experienced for equipment and hazards.",
         {"b": "Training required.", "c": "Experience may qualify.", "d": "Knowledge not just tool."}, "medium"),
    ])

    return qs


if __name__ == "__main__":
    write_bank(E, build())
