#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "life-health-insurance-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "life", [
        ("Term life insurance provides:",
         {"a": "Pure death benefit coverage for a specified period without cash value", "b": "Guaranteed cash value growth like whole life always", "c": "Only disability income benefits", "d": "Unlimited policy loans from day one always"},
         "a", "Term is temporary coverage with no savings component.",
         {"b": "Cash value is permanent product feature.", "c": "DI is separate product.", "d": "Term lacks cash value to borrow against."}, "easy"),
        ("Whole life insurance differs from term because whole life:",
         {"a": "Combines permanent death benefit with cash value accumulation", "b": "Expires after 10 years with no renewal option ever", "c": "Never pays a death benefit", "d": "Is always group coverage through an employer only"},
         "a", "Whole life is permanent with level premiums and cash value.",
         {"b": "Term expires; whole life is permanent.", "c": "Death benefit is core.", "d": "Individual whole life exists."}, "easy"),
        ("The beneficiary of a life insurance policy receives:",
         {"a": "The death benefit proceeds upon insured's death", "b": "Only dividends while insured is alive always", "c": "Automatic ownership of the insured's estate without probate rules", "d": "Premium refunds only if insured dies"},
         "a", "Beneficiary is paid death benefit per policy terms.",
         {"b": "Dividends are living benefit feature on participating policies.", "c": "Beneficiary designation avoids probate for proceeds typically.", "d": "Death benefit, not just premium refund."}, "easy"),
        ("Insurable interest must exist between:",
         {"a": "The policy owner/beneficiary and the insured at policy inception", "b": "Any stranger with no financial relationship always", "c": "Only corporations and governments", "d": "The agent and the underwriter exclusively"},
         "a", "Insurable interest prevents wagering on others' lives.",
         {"b": "Strangers generally cannot insure another's life.", "c": "Individuals also qualify with interest.", "d": "Not the required relationship."}, "medium"),
        ("A life insurance policy's incontestability clause generally limits:",
         {"a": "Insurer's ability to contest the policy after it has been in force ~2 years", "b": "Premium payments forever", "c": "Beneficiary changes after death", "d": "All medical underwriting before application"},
         "a", "After contestability period, insurer cannot void except for limited reasons.",
         {"b": "Premiums continue per contract.", "c": "Beneficiary designated while alive.", "d": "Underwriting occurs at issue."}, "medium"),
        ("Universal life insurance offers:",
         {"a": "Flexible premiums and adjustable death benefit with cash value earning current crediting rates", "b": "No death benefit component ever", "c": "Only term coverage expiring at age 65 always", "d": "Guaranteed stock market returns without risk"},
         "a", "UL separates insurance cost from cash value with flexibility.",
         {"b": "Death benefit remains.", "c": "Can be permanent.", "d": "Crediting varies; not guaranteed equity returns."}, "medium"),
        ("The Human Life Value approach to life insurance need estimates:",
         {"a": "Present value of future earnings the family would lose", "b": "Only funeral costs with no income replacement", "c": "Market value of the insured's automobile", "d": "Social Security tax paid last year only"},
         "a", "HLV quantifies economic loss from premature death.",
         {"b": "Needs approach is broader than funeral only.", "c": "Unrelated asset.", "d": "Too narrow."}, "medium"),
        ("A graded premium whole life policy features:",
         {"a": "Lower initial premiums that increase for a period then level off", "b": "Premiums that decrease to zero after one year always", "c": "No death benefit until age 100", "d": "Only accidental death coverage"},
         "a", "Graded premium helps affordability early with scheduled increases.",
         {"b": "Premiums don't vanish.", "c": "Death benefit from start.", "d": "Full life coverage typical."}, "hard"),
        ("Assignment of a life insurance policy transfers:",
         {"a": "Ownership rights (and sometimes beneficiary) to another party", "b": "Only the agent's commission", "c": "State insurance department authority", "d": "Automatic tax exemption for all transfers"},
         "a", "Absolute assignment transfers ownership; collateral assignment limited.",
         {"b": "Policy rights, not commission.", "c": "Regulatory body unrelated.", "d": "Tax depends on transaction."}, "medium"),
        ("Joint life (first-to-die) policy pays when:",
         {"a": "The first of two insureds dies", "b": "Both insureds die simultaneously only", "c": "Neither insured ever dies", "d": "The policy reaches cash value equal to face amount only"},
         "a", "First-to-die covers two lives with benefit at first death.",
         {"b": "Any first death triggers.", "c": "Death benefit requires death.", "d": "Different trigger."}, "medium"),
        ("Suicide clause in life policies typically:",
         {"a": "Limits death benefit if suicide occurs within first 1-2 years", "b": "Voids all coverage immediately upon any illness", "c": "Doubles the death benefit for suicide always", "d": "Applies only to accidental death riders"},
         "a", "Suicide exclusion period returns premiums or limited benefit early.",
         {"b": "Illness doesn't void like suicide clause.", "c": "Opposite.", "d": "Base policy provision."}, "medium"),
        ("A paid-up addition rider uses:",
         {"a": "Dividends to purchase additional paid-up whole life insurance", "b": "Loan interest to reduce death benefit only", "c": "Surrender charges to fund term coverage exclusively", "d": "State guaranty fund contributions"},
         "a", "PUA rider buys extra permanent insurance with dividends.",
         {"b": "Dividends purchase insurance.", "c": "Different mechanism.", "d": "Guaranty fund is insolvency protection."}, "hard"),
        ("Life insurance death benefits paid to named beneficiaries are generally:",
         {"a": "Income tax-free to the beneficiary (estate tax may apply if estate is owner)", "b": "Fully taxable as ordinary income always", "c": "Subject to capital gains tax as stock sales", "d": "Taxed as self-employment income"},
         "a", "IRC §101(a) generally excludes death proceeds from income tax.",
         {"b": "Income tax free typically.", "c": "Not capital transaction.", "d": "Not earned income."}, "easy"),
        ("Reduced paid-up insurance nonforfeiture option allows:",
         {"a": "Stopping premiums while keeping reduced permanent death benefit", "b": "Converting to disability insurance automatically", "c": "Eliminating all coverage with no value", "d": "Increasing death benefit without payment"},
         "a", "Reduced paid-up uses cash value to buy smaller paid-up policy.",
         {"b": "Different product.", "c": "Surrender is separate option.", "d": "Requires no additional premium for increase."}, "medium"),
        ("Second-to-die (survivorship) life insurance pays when:",
         {"a": "The second of two insureds dies, often used in estate planning", "b": "The first insured dies only", "c": "Premium payments stop", "d": "Cash value exceeds $1 million automatically"},
         "a", "Survivorship policy funds estate tax at second death.",
         {"b": "First-to-die pays earlier.", "c": "Death triggers benefit.", "d": "Not automatic trigger."}, "hard"),
    ])

    qs += pack(E, "health", [
        ("A Health Maintenance Organization (HMO) typically requires:",
         {"a": "Selection of a primary care physician and referrals for specialists", "b": "No network restrictions ever", "c": "Only out-of-network care with highest reimbursement", "d": "No premium payments by members ever"},
         "a", "HMOs emphasize PCP gatekeeping and network care.",
         {"b": "Networks are core to HMO.", "c": "In-network focus.", "d": "Premiums/cost sharing apply."}, "easy"),
        ("The Affordable Care Act essential health benefits include:",
         {"a": "Ambulatory, emergency, hospitalization, maternity, mental health, prescriptions, and preventive services", "b": "Only cosmetic surgery exclusively", "c": "Unlimited luxury spa treatments", "d": "Only dental for all adults in every plan always"},
         "a", "EHB categories must be covered in individual/small group ACA plans.",
         {"b": "Cosmetic excluded typically.", "c": "Not covered.", "d": "Adult dental not mandatory EHB."}, "medium"),
        ("COBRA continuation coverage allows:",
         {"a": "Former employees to keep group health coverage temporarily by paying full premium", "b": "Free lifetime healthcare after any job loss", "c": "Only Medicare enrollment instead of private coverage", "d": "Unlimited duration with no premium increase ever"},
         "a", "COBRA extends group coverage 18-36 months typically at employee cost.",
         {"b": "Not free.", "c": "Separate from Medicare eligibility.", "d": "Limited duration."}, "medium"),
        ("A Preferred Provider Organization (PPO) differs from HMO by:",
         {"a": "Allowing out-of-network care at higher cost sharing without PCP gatekeeper typically", "b": "Prohibiting all specialist visits", "c": "Requiring only emergency care in-network", "d": "Eliminating all deductibles always"},
         "a", "PPOs offer flexibility with network discounts and OON option.",
         {"b": "Specialists accessible.", "c": "Broader than emergency only.", "d": "Deductibles common."}, "easy"),
        ("Medicare Part A primarily covers:",
         {"a": "Inpatient hospital care", "b": "Outpatient prescription drugs exclusively", "c": "Routine dental and vision for all beneficiaries always", "d": "Long-term custodial care unlimited"},
         "a", "Part A is hospital insurance.",
         {"b": "Part D is prescriptions.", "c": "Limited dental/vision.", "d": "Custodial LTC not covered fully."}, "easy"),
        ("Medicare Part D provides:",
         {"a": "Prescription drug coverage through private plans", "b": "Physician office visits as Part B exclusively", "c": "Medigap supplement automatically", "d": "Unlimited nursing home care always"},
         "a", "Part D covers outpatient prescription drugs.",
         {"b": "Part B is medical.", "c": "Medigap is separate purchase.", "d": "Skilled vs custodial limits."}, "easy"),
        ("A deductible in health insurance is:",
         {"a": "Amount the insured pays before plan begins sharing costs", "b": "The agent's commission", "c": "Maximum out-of-pocket always", "d": "Premium tax credit from IRS exclusively"},
         "a", "Deductible is initial self-pay threshold.",
         {"b": "Agent compensation.", "c": "MOOP is separate limit.", "d": "Subsidy is different."}, "easy"),
        ("Health Savings Accounts (HSAs) offer:",
         {"a": "Triple tax advantage: deductible contributions, tax-free growth, tax-free qualified medical withdrawals", "b": "No requirement to be paired with any insurance", "c": "Mandatory use only after age 65 for non-medical without penalty always", "d": "Unlimited contributions regardless of HDHP enrollment"},
         "a", "HSA tax benefits require qualifying HDHP.",
         {"b": "HDHP required.", "c": "Non-medical after 65 taxed as income without penalty.", "d": "Annual limits apply."}, "medium"),
        ("Pre-existing condition exclusions in individual health insurance post-ACA:",
         {"a": "Are prohibited for plan years beginning on/after 2014 in compliant markets", "b": "Are mandatory for all insurers always", "c": "Apply only to Medicare Part A", "d": "Allow lifetime unlimited exclusions always"},
         "a", "ACA banned pre-existing condition exclusions in individual/small group.",
         {"b": "Opposite post-ACA.", "c": "ACA individual market rule.", "d": "Prohibited."}, "medium"),
        ("Stop-loss insurance for self-funded employer plans protects:",
         {"a": "Employer against catastrophic claim levels above specified thresholds", "b": "Employees from all copayments always", "c": "Only dental claims under $100", "d": "Insurance agents from E&O claims exclusively"},
         "a", "Specific and aggregate stop-loss cap employer exposure.",
         {"b": "Employee cost sharing remains.", "c": "Medical catastrophic focus.", "d": "Different insurance."}, "hard"),
        ("Medicaid is:",
         {"a": "Joint federal-state program for low-income eligible individuals", "b": "Identical to Medicare for all seniors automatically", "c": "Private supplemental insurance sold by agents only", "d": "Workers compensation exclusively"},
         "a", "Medicaid serves qualifying low-income populations with state variation.",
         {"b": "Medicare is age/disability program.", "c": "Government program.", "d": "WC is injury at work."}, "easy"),
        ("Coordination of Benefits (COB) determines:",
         {"a": "Which plan pays first when insured has multiple coverages", "b": "Only life insurance beneficiary order", "c": "Property insurance deductibles exclusively", "d": "Agent licensing renewal dates"},
         "a", "COB rules prevent duplicate payment and set primary payer.",
         {"b": "Health insurance context.", "c": "Different line.", "d": "Regulatory admin."}, "medium"),
        ("A capitation payment to providers means:",
         {"a": "Fixed per-member payment regardless of services rendered", "b": "Fee-for-service for each procedure only always", "c": "Payment only after hospital discharge exclusively", "d": "Commission to insurance agents per sale"},
         "a", "Capitation shifts utilization risk to provider.",
         {"b": "FFS is opposite model.", "c": "Ongoing payment model.", "d": "Agent compensation."}, "medium"),
        ("Long-term care insurance elimination period is similar to:",
         {"a": "A deductible measured in days before benefits begin", "b": "Life insurance grace period for premium", "c": "Stock market waiting period", "d": "Auto collision deductible for property damage only always"},
         "a", "Elimination period is self-pay days before LTC benefits start.",
         {"b": "Premium grace is different.", "c": "Unrelated.", "d": "LTC is care services."}, "medium"),
        ("HIPAA portability provisions primarily:",
         {"a": "Limit exclusion periods for pre-existing conditions when changing group coverage", "b": "Eliminate all health insurance premiums nationally", "c": "Replace state insurance departments", "d": "Mandate universal single-payer healthcare"},
         "a", "HIPAA improved continuity when changing jobs/group plans pre-ACA expansion.",
         {"b": "Premiums still apply.", "c": "States regulate insurance.", "d": "Not single-payer mandate."}, "hard"),
    ])

    qs += pack(E, "law", [
        ("An insurance contract is considered a contract of:",
         {"a": "Utmost good faith requiring full disclosure", "b": "Adhesion where only insurer has duties always", "c": "Bailment of physical goods exclusively", "d": "Indemnity for all lines without exception always"},
         "a", "Both parties must disclose material facts honestly.",
         {"b": "Both parties have obligations.", "c": "Not bailment.", "d": "Life insurance is not indemnity."}, "easy"),
        ("The principle of indemnity in property insurance means:",
         {"a": "Insured should not profit from a loss beyond actual financial loss", "b": "Insured always receives double the loss amount", "c": "Insurer never pays claims", "d": "Only punitive damages are covered always"},
         "a", "Indemnity restores financial position, not windfall.",
         {"b": "Profit from loss discouraged.", "c": "Claims paid per policy.", "d": "Punitive usually excluded."}, "easy"),
        ("Warranties in insurance contracts differ from representations because warranties:",
         {"a": "Are strictly complied with; breach may void coverage regardless of materiality", "b": "Never affect claim payment", "c": "Apply only to life insurance dividends", "d": "Are optional oral promises only always"},
         "a", "Warranty breach historically voids policy; representations require materiality.",
         {"b": "Warranties matter.", "c": "All lines.", "d": "Written policy terms."}, "hard"),
        ("Agency law: an insurance agent typically represents:",
         {"a": "The insurer when acting as agent of the company", "b": "Always the insured exclusively in all transactions", "c": "Only the state guaranty fund", "d": "No party in any transaction"},
         "a", "Agent of insurer binds principal insurer within authority.",
         {"b": "Broker may represent buyer; agent represents insurer.", "c": "Guaranty fund is safety net.", "d": "Agent represents insurer."}, "medium"),
        ("A binder in property-casualty insurance:",
         {"a": "Provides temporary coverage until formal policy is issued", "b": "Permanently replaces the policy without conditions", "c": "Is only used in life insurance always", "d": "Eliminates all underwriting forever"},
         "a", "Binders grant interim protection pending policy issuance.",
         {"b": "Temporary.", "c": "P&C concept mainly.", "d": "Underwriting still occurs."}, "medium"),
        ("The Fair Credit Reporting Act affects insurance by:",
         {"a": "Requiring adverse action notices if credit-based decisions negatively impact consumer", "b": "Prohibiting all use of credit in insurance always nationwide", "c": "Eliminating privacy rights for consumers", "d": "Mandating identical rates for all applicants always"},
         "a", "FCRA governs consumer reports and adverse action disclosure.",
         {"b": "Credit use allowed where permitted with notice.", "c": "Protects privacy with limits.", "d": "Underwriting varies."}, "medium"),
        ("Replacement of a life insurance policy requires:",
         {"a": "Disclosure forms comparing existing and proposed coverage per state regulations", "b": "No documentation or client acknowledgment ever", "c": "Automatic approval by prior insurer always", "d": "Only verbal consent from agent"},
         "a", "Replacement regulations protect consumers from unnecessary churn.",
         {"b": "Required notices.", "c": "New underwriting applies.", "d": "Written disclosure required."}, "medium"),
        ("Parol evidence rule in contract law means:",
         {"a": "Written contract terms generally cannot be contradicted by prior oral agreements", "b": "Oral contracts always override written policies", "c": "Insurance has no written contracts ever", "d": "Agents can unilaterally change policy language orally always"},
         "a", "Integrated written policy is primary evidence of agreement.",
         {"b": "Written policy controls.", "c": "Policies are written.", "d": "Endorsements must be written."}, "hard"),
        ("Twisting is:",
         {"a": "Inducing replacement of a policy by misrepresentation or incomplete comparison", "b": "Legal comparative shopping with full disclosure", "c": "Reinsurance between insurers only", "d": "Actuarial calculation of mortality"},
         "a", "Twisting is prohibited unfair trade practice.",
         {"b": "Proper replacement uses disclosure.", "c": "Different concept.", "d": "Actuarial science."}, "easy"),
        ("Rebating is:",
         {"a": "Returning premium or giving inducement not specified in the policy as unlawful in most states", "b": "Paying legitimate policy dividends", "c": "Standard agent commission from insurer", "d": "Claim payment to beneficiary"},
         "a", "Rebating gives unfair inducement outside policy contract.",
         {"b": "Dividends are contractual.", "c": "Commission is insurer payment.", "d": "Claim not rebate."}, "easy"),
        ("An insurable interest must exist at the time of:",
         {"a": "Application/issue for life; at time of loss for property", "b": "Only at claim payment for all lines always", "c": "Never; insurance is a wager always allowed", "d": "Policy surrender only"},
         "a", "Life: interest at inception; property: at loss (and often at inception).",
         {"b": "Timing differs by line.", "c": "Wager policies prohibited.", "d": "Unrelated timing."}, "hard"),
        ("The McCarran-Ferguson Act:",
         {"a": "Leaves insurance regulation primarily to states unless federal law specifically applies", "b": "Abolished all state insurance departments", "c": "Made insurance exclusively a federal program", "d": "Prohibited all insurance sales nationally"},
         "a", "McCarran-Ferguson preserves state regulation primacy.",
         {"b": "States still regulate.", "c": "Dual regulation reality.", "d": "Industry continues."}, "medium"),
        ("A certificate of insurance:",
         {"a": "Summarizes coverage for a party but does not amend the policy contract", "b": "Replaces the entire policy with new terms always", "c": "Is only issued by federal courts", "d": "Guarantees unlimited coverage beyond policy limits always"},
         "a", "COI is evidence of coverage; policy governs terms.",
         {"b": "Policy is contract.", "c": "Issued by insurer/agent.", "d": "Cannot expand limits."}, "easy"),
        ("Estoppel may prevent an insurer from denying coverage when:",
         {"a": "Insurer's actions or statements led insured to reasonably rely to their detriment", "b": "Insured intentionally committed fraud always", "c": "Premium was never paid and no grace period applied", "d": "Loss occurred before policy inception with no binder"},
         "a", "Equitable estoppel applies when insurer conduct creates reliance.",
         {"b": "Fraud may void policy.", "c": "Nonpayment can lapse policy.", "d": "No coverage period."}, "hard"),
        ("The Gramm-Leach-Bliley Act requires insurers to:",
         {"a": "Provide privacy notices and safeguard nonpublic personal information", "b": "Publish all client medical records publicly", "c": "Eliminate all encryption requirements always", "d": "Share data freely with any vendor without consent always"},
         "a", "GLBA privacy rules apply to financial institutions including insurers.",
         {"b": "Privacy protected.", "c": "Safeguards required.", "d": "Opt-out/notice rules apply."}, "medium"),
    ])

    qs += pack(E, "underwriting", [
        ("Mortality tables used in life insurance pricing reflect:",
         {"a": "Statistical death rates by age and sex among insured populations", "b": "Stock market returns exclusively", "c": "Only property fire loss frequencies", "d": "Agent production quotas"},
         "a", "Actuaries use mortality/morbidity tables for premium calculation.",
         {"b": "Investment separate.", "c": "P&C tables differ.", "d": "Sales metric."}, "easy"),
        ("Preferred risk classification receives:",
         {"a": "Lower premiums due to favorable health/lifestyle characteristics", "b": "Higher premiums than standard always", "c": "Automatic decline of application always", "d": "No medical underwriting ever required"},
         "a", "Better risk profile earns better rates.",
         {"b": "Standard/substandard pay more.", "c": "Preferred is approved class.", "d": "Underwriting still occurs."}, "easy"),
        ("Attending Physician Statement (APS) in underwriting is:",
         {"a": "Medical records ordered from applicant's doctor for risk assessment", "b": "The agent's sales presentation only", "c": "Proof of property ownership for homeowners", "d": "Beneficiary designation form exclusively"},
         "a", "APS provides detailed medical history from treating physician.",
         {"b": "Medical document.", "c": "P&C item.", "d": "Policy admin form."}, "easy"),
        ("Substandard (rated) policies are issued when:",
         {"a": "Applicant has health conditions increasing mortality risk above standard", "b": "Applicant is in perfect health always", "c": "Applicant requests maximum coverage at minimum premium without review", "d": "Only group cases qualify always"},
         "a", "Table ratings or flat extras cover extra mortality risk.",
         {"b": "Standard/preferred instead.", "c": "Underwriting determines class.", "d": "Individual substandard exists."}, "medium"),
        ("Morbidity tables are used primarily for:",
         {"a": "Disability and health insurance predicting sickness/injury incidence", "b": "Life insurance death benefits only always", "c": "Auto collision frequency exclusively in all cases", "d": "Investment portfolio allocation exclusively"},
         "a", "Morbidity measures illness/disability, not death alone.",
         {"b": "Mortality for life.", "c": "Actuarial auto uses claim freq/sev.", "d": "Investment separate."}, "medium"),
        ("Paramedical exam in life underwriting typically includes:",
         {"a": "Height, weight, blood pressure, blood/urine samples", "b": "Full surgical procedure always", "c": "Only credit report with no health data", "d": "Property inspection of home roof"},
         "a", "Paramed exam is brief physical and fluid collection.",
         {"b": "Non-invasive screening.", "c": "Health data collected.", "d": "P&C inspection."}, "easy"),
        ("Anti-selection occurs when:",
         {"a": "Higher-risk individuals seek insurance more than lower-risk individuals", "b": "Only healthy people buy insurance always", "c": "Insurers randomly cancel all policies annually", "d": "Agents rebate premiums legally always"},
         "a", "Adverse selection threatens pool balance without underwriting.",
         {"b": "Opposite problem.", "c": "Not random cancellation.", "d": "Rebating illegal."}, "medium"),
        ("Reinsurance allows a primary insurer to:",
         {"a": "Transfer portions of risk to another insurer to stabilize capacity", "b": "Avoid paying any claims entirely always", "c": "Eliminate state regulation completely", "d": "Sell policies without licenses always"},
         "a", "Reinsurance spreads catastrophic and large exposures.",
         {"b": "Primary remains liable to insured.", "c": "Regulation continues.", "d": "Licensing required."}, "medium"),
        ("Experience rating in group health modifies premiums based on:",
         {"a": "The group's own claims experience over time", "b": "Only national mortality with no group data ever", "c": "Agent's personal production only", "d": "Stock market index returns exclusively"},
         "a", "Large groups may be experience-rated reflecting utilization.",
         {"b": "Community rating uses broader pool.", "c": "Claims drive experience.", "d": "Unrelated."}, "hard"),
        ("Flat extra premium loading adds:",
         {"a": "Fixed dollar amount per $1,000 of coverage for extra hazard", "b": "Only a percentage decrease in death benefit always", "c": "Automatic policy cancellation in 30 days always", "d": "Commission advance to agent exclusively"},
         "a", "Flat extras cover temporary or permanent substandard risks.",
         {"b": "Premium increases, not benefit cut.", "c": "Policy remains if accepted.", "d": "Underwriting pricing tool."}, "hard"),
        ("MIB (Medical Information Bureau) report helps underwriters by:",
         {"a": "Sharing coded prior insurance application history among member insurers", "b": "Guaranteeing approval for all applicants always", "c": "Replacing all medical exams permanently", "d": "Publishing full medical records publicly"},
         "a", "MIB flags prior application disclosures for verification.",
         {"b": "Underwriting decision still required.", "c": "Exams may still be ordered.", "d": "Confidential coded data."}, "medium"),
        ("Risk classification in auto insurance may use:",
         {"a": "Driving record, territory, vehicle type, and usage", "b": "Only applicant's favorite color", "c": "Random assignment without actuarial basis always", "d": "Only life insurance mortality exclusively"},
         "a", "Auto rates reflect measurable driving and vehicle factors.",
         {"b": "Not actuarially credible.", "c": "Actuarial standards apply.", "d": "P&C factors differ."}, "easy"),
        ("Underwriting declination means:",
         {"a": "Insurer refuses to offer coverage based on risk assessment", "b": "Automatic acceptance at standard rates always", "c": "Policy issued then immediately surrendered by law", "d": "Only temporary coverage through COBRA always"},
         "a", "Decline when risk unacceptable or uninsurable.",
         {"b": "Opposite outcome.", "c": "No policy issued.", "d": "Health continuation concept."}, "easy"),
        ("Retention limit for an insurer is:",
         {"a": "Maximum loss amount the company keeps before reinsurance applies", "b": "Agent's marketing budget exclusively", "c": "Beneficiary's share of death benefit always", "d": "State premium tax rate exclusively"},
         "a", "Retention defines self-insured exposure before ceding to reinsurer.",
         {"b": "Corporate risk measure.", "c": "Policy benefit.", "d": "Tax not retention."}, "hard"),
        ("Conditional receipt in life insurance provides:",
         {"a": "Limited temporary coverage if premium paid and conditions met pending underwriting decision", "b": "Permanent coverage with no underwriting ever", "c": "Only applies after policy has been in force 10 years", "d": "Automatic waiver of all premiums forever"},
         "a", "Conditional receipt may cover if death occurs during underwriting if conditions satisfied.",
         {"b": "Underwriting still required for final issue.", "c": "Applies at application.", "d": "Premiums continue."}, "medium"),
    ])

    return qs


if __name__ == "__main__":
    write_bank(E, build())
