#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "medicare-counseling-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "medicare", [
        ("Medicare Part A primarily helps pay for:",
         {"a": "Inpatient hospital stays and skilled nursing facility care (limited)", "b": "Retail outpatient prescriptions always", "c": "Routine dental cleanings only", "d": "Auto insurance premiums"},
         "a", "Part A is hospital insurance covering inpatient hospital, SNF, hospice, some home health.",
         {"b": "Part D covers most retail drugs.", "c": "Dental generally not covered.", "d": "Unrelated."}, "easy"),
        ("Medicare Part B generally covers:",
         {"a": "Physician services, outpatient care, preventive services, and DME", "b": "Long-term custodial nursing home care only", "c": "Hearing aids in all cases fully", "d": "Veterinary services"},
         "a", "Part B is medical insurance for outpatient professional services and equipment.",
         {"b": "Custodial care not covered.", "c": "Hearing aids limited coverage historically.", "d": "Human health program."}, "easy"),
        ("Initial Enrollment Period (IEP) for Medicare typically spans:",
         {"a": "7 months around 65th birthday (3 before, month of, 3 after)", "b": "One day only on birthday", "c": "Anytime without penalty forever", "d": "Only during open enrollment Oct–Dec for Part B first time always"},
         "a", "IEP allows Part A/B enrollment around age 65 with permanent penalties if delayed without qualifying coverage.",
         {"b": "Window is months long.", "c": "Late enrollment penalties may apply.", "d": "IEP distinct from GEP/OEP."}, "medium"),
        ("Medicare Part D covers:",
         {"a": "Outpatient prescription drugs through private plans", "b": "Inpatient surgery room only", "c": "Medigap premiums automatically", "d": "Part A deductibles exclusively"},
         "a", "Part D provides drug coverage via stand-alone PDP or MA-PD plans.",
         {"b": "Part A/B scope.", "c": "Medigap separate product.", "d": "Deductibles plan-specific."}, "easy"),
        ("Medicare Advantage (Part C) is:",
         {"a": "Alternative way to receive Part A and B benefits through approved private plans", "b": "Replacement of all Medicare rights permanently by law", "c": "Only for under age 65 disabled never", "d": "Identical to Medigap always"},
         "a", "MA plans must cover Part A/B benefits, often with Part D and extra benefits.",
         {"b": "Beneficiary retains Medicare rights/appeals pathways.", "c": "Disabled under 65 may enroll.", "d": "Medigap supplements Original Medicare, not MA same way."}, "medium"),
        ("Medigap (Medicare Supplement) policies:",
         {"a": "Help pay cost-sharing in Original Medicare, standardized in most states", "b": "Include Part D drug coverage in all plans since 2006", "c": "Are sold by Medicare directly only", "d": "Replace Part A hospital entirely"},
         "a", "Medigap fills gaps like coinsurance/deductibles; separate Part D needed.",
         {"b": "Part D separate since 2006.", "c": "Private insurers sell Medigap.", "d": "Supplements not replaces Part A."}, "medium"),
        ("Part B late enrollment penalty applies when:",
         {"a": "Individual without creditable coverage delays Part B enrollment", "b": "Individual enrolls during IEP with no gaps", "c": "Individual has employer group coverage qualifying delay", "d": "Individual only has Part A free always exempt from all penalties"},
         "a", "Part B penalty increases premium 10% per full 12-month period delayed without creditable coverage.",
         {"b": "Timely enrollment avoids penalty.", "c": "Special Enrollment Period may apply with group coverage.", "d": "Part B may still need enrollment decision."}, "hard"),
        ("Creditable prescription drug coverage means:",
         {"a": "Coverage expected to pay on average at least as much as standard Part D", "b": "Any discount card without actuarial value", "c": "No drug coverage ever creditable", "d": "Only VA coverage never creditable"},
         "a", "Employer/plan must certify creditable coverage to avoid Part D late penalty.",
         {"b": "Must meet actuarial standard.", "c": "Employer coverage may be creditable.", "d": "VA may be creditable in some cases."}, "hard"),
        ("Medicare Open Enrollment Period (OEP) Jan 1–Mar 31 allows beneficiaries with Medicare Advantage to:",
         {"a": "Switch MA plans or return to Original Medicare with Part D enrollment rules", "b": "Enroll in Part A first time at any age penalty-free always", "c": "Buy Medigap guaranteed issue in all states always without rules", "d": "Cancel Medicare entirely online instantly"},
         "a", "MA OEP permits one change among MA or disenroll to Original Medicare.",
         {"b": "Part A first enrollment uses IEP/SEP.", "c": "Medigap GI limited outside certain windows.", "d": "Cannot cancel Medicare casually."}, "hard"),
        ("Annual Election Period (AEP) Oct 15–Dec 7 is used to:",
         {"a": "Change Part D, join/switch/drop MA, or return to Original Medicare effective Jan 1", "b": "Pay Part A premiums only", "c": "Enroll in Medicaid automatically always", "d": "Change Social Security retirement age"},
         "a", "AEP is primary annual window for Medicare Advantage and Part D changes.",
         {"b": "Premium payments ongoing.", "c": "Medicaid separate application.", "d": "SS retirement separate."}, "medium"),
        ("Extra Help (LIS) program assists with:",
         {"a": "Part D premiums, deductibles, and copays for limited-income beneficiaries", "b": "Medigap Plan F sales only", "c": "Long-term care insurance exclusively", "d": "Auto loan payments"},
         "a", "Low-Income Subsidy reduces Part D costs for qualifying beneficiaries.",
         {"b": "Medigap not LIS.", "c": "LTC insurance separate.", "d": "Unrelated."}, "medium"),
        ("Medicare hospice benefit focuses on:",
         {"a": "Comfort care for terminal illness with prognosis six months or less if disease runs normal course", "b": "Curative chemotherapy always covered same as active treatment without election", "c": "Only inpatient hospital unlimited years", "d": "Dental implants fully covered"},
         "a", "Hospice emphasizes palliative care; curative treatment generally stops upon hospice election with exceptions.",
         {"b": "Curative intent shifts with hospice election.", "c": "Hospice includes home and other settings.", "d": "Dental not hospice focus."}, "medium"),
        ("Part A hospital benefit period deductible:",
         {"a": "Applies per benefit period, not calendar year only", "b": "Never applies if patient has Medigap", "c": "Paid by Medicare always with no beneficiary share", "d": "Only for outpatient visits"},
         "a", "Benefit period starts when admitted and ends after 60 days without inpatient care.",
         {"b": "Medigap may cover deductible depending on plan.", "c": "Beneficiary pays deductible unless covered.", "d": "Part A inpatient deductible."}, "hard"),
        ("Special Enrollment Period (SEP) for Part B may occur when:",
         {"a": "Employer group health coverage ends", "b": "Beneficiary wants different TV channel", "c": "Any random month without reason", "d": "Neighbor suggests switching"},
         "a", "Loss of creditable employer coverage triggers SEP to enroll Part B without penalty.",
         {"b": "Irrelevant.", "c": "SEP needs qualifying event.", "d": "Not qualifying event."}, "medium"),
        ("SHIP counselor explaining Original vs Medicare Advantage should emphasize:",
         {"a": "Network, cost-sharing, drug coverage, travel, and provider access differences neutrally", "b": "One option always best for everyone", "c": "Counselor receives commission from plan chosen", "d": "Beneficiary must decide in 5 minutes without materials"},
         "a", "Neutral counseling compares options using unbiased materials without sales pressure.",
         {"b": "Individualized choice.", "c": "SHIP counselors do not sell or commission.", "d": "Take time to decide."}, "easy"),
    ])

    qs += pack(E, "rights", [
        ("Medicare Summary Notice (MSN) for Original Medicare shows:",
         {"a": "Services billed, Medicare-approved amounts, and beneficiary liability", "b": "Part D drug formulary only always", "c": "Medigap commission rates", "d": "Counselor salary"},
         "a", "MSN is quarterly statement of Part A/B claims processed, not a bill itself usually.",
         {"b": "Part D uses EOB from plan.", "c": "Irrelevant.", "d": "Irrelevant."}, "easy"),
        ("Beneficiary appeal rights for denied Medicare coverage include levels such as:",
         {"a": "Redetermination, reconsideration, ALJ hearing, and further review", "b": "No appeal ever for any denial", "c": "Only social media complaint", "d": "Single phone call final always"},
         "a", "Medicare appeals process has defined escalating levels with time limits.",
         {"b": "Appeals exist.", "c": "Formal process required.", "d": "Multiple levels available."}, "medium"),
        ("Advance Beneficiary Notice of Noncoverage (ABN) purpose is to:",
         {"a": "Inform beneficiary Medicare may not pay and obtain choice to receive service with potential liability", "b": "Guarantee Medicare payment", "c": "Replace Medicare card", "d": "Enroll in Part D automatically"},
         "a", "ABN documents informed consent when provider believes service may not be covered.",
         {"b": "Opposite effect.", "c": "Unrelated.", "d": "Separate enrollment."}, "medium"),
        ("Beneficiary privacy rights under HIPAA include:",
         {"a": "Access to records, accounting of disclosures, and complaint rights", "b": "Public posting of all diagnoses online by counselor", "c": "Mandatory sharing of SSN with marketers", "d": "No restrictions on counselor note storage ever"},
         "a", "HIPAA grants patients rights over PHI with security requirements for counselors/agencies.",
         {"b": "Prohibited.", "c": "Marketing restrictions apply.", "d": "Safeguards required."}, "easy"),
        ("Medicare Advantage member grievance differs from coverage appeal because grievance involves:",
         {"a": "Quality of care or plan service issues not strictly payment denial", "b": "Only Part A deductible amounts always", "c": "Criminal prosecution only", "d": "Changing Social Security number"},
         "a", "Grievances address complaints; appeals address organization determinations/coverage.",
         {"b": "Appeals can address payment too.", "c": "Grievance administrative process.", "d": "Unrelated."}, "hard"),
        ("Beneficiary designated representative may:",
         {"a": "Act with documented authorization in appeals and communications", "b": "Sell beneficiary Medicare number online", "c": "Enroll beneficiary in any plan without consent always", "d": "Override beneficiary decision with no paperwork ever"},
         "a", "Representative form allows helper/family member to assist with Medicare processes.",
         {"b": "Illegal.", "c": "Consent required.", "d": "Authorization required."}, "medium"),
        ("Provider balance billing in Original Medicare participating providers:",
         {"a": "Generally prohibited from charging above Medicare allowed amount", "b": "Always allowed unlimited", "c": "Required by law always", "d": "Only applies to Part D drugs at pharmacy always"},
         "a", "Participating providers accept assignment; balance billing limited with exceptions (non-participating, some services).",
         {"b": "Assignment limits balance billing.", "c": "Not required.", "d": "Part D cost-sharing different framework."}, "hard"),
        ("Beneficiary rights during hospital discharge include:",
         {"a": "Notice of discharge rights and expedited appeal of discharge if applicable", "b": "Immediate eviction without notice always", "c": "No right to receive medical record copy", "d": "Forbidden from calling SHIP counselor"},
         "a", "Important Message from Medicare and Detailed Notice of Discharge support appeal rights.",
         {"b": "Notice required.", "c": "Record access right exists.", "d": "Counselor access allowed."}, "medium"),
        ("Medicare card protects beneficiary when counselor advises:",
         {"a": "Never share Medicare number except to trusted providers/plans; treat like SSN", "b": "Post number on social media for convenience", "c": "Give to telemarketer promising free brace", "d": "Share with stranger at door for 'verification'"},
         "a", "Medicare identity theft common; guard number and review MSN for fraud.",
         {"b": "Identity theft risk.", "c": "Common scam.", "d": "Scam tactic."}, "easy"),
        ("Limited English proficiency beneficiary should receive:",
         {"a": "Meaningful language access such as interpreters and translated materials when available", "b": "English-only information without assistance always acceptable federally", "c": "Denied counseling", "d": "Higher Medicare premiums as penalty"},
         "a", "Title VI and CMS guidance support language services for meaningful access.",
         {"b": "Language access required reasonably.", "c": "Cannot deny based on language.", "d": "No such penalty."}, "medium"),
        ("Beneficiary advance directive counseling should clarify:",
         {"a": "Documents express care preferences; POLST/MOLST vary by state; not same as Medicare enrollment form", "b": "Advance directive automatically enrolls in Part C", "c": "Provider must ignore always", "d": "Only attorney can have preferences"},
         "a", "Counselors distinguish advance care planning documents from Medicare plan forms.",
         {"b": "Separate legal documents.", "c": "Providers follow valid directives.", "d": "Individuals can create directives per state law."}, "medium"),
        ("Expedited appeal for termination of Medicare-covered services requires plan/provider to:",
         {"a": "Deliver standardized notice and continue services during appeal in qualifying situations", "b": "Stop all care immediately without notice always", "c": "Charge double during appeal automatically", "d": "Ignore beneficiary request always"},
         "a", "Expedited appeals have short timeframes; continuation of services may apply.",
         {"b": "Notice rights exist.", "c": "Not automatic double charge.", "d": "Must respond to appeal."}, "hard"),
        ("Beneficiary discrimination prohibited under Medicare-related laws includes:",
         {"a": "Race, color, national origin, disability, age in federally funded programs", "b": "Choice among lawful plan options", "c": "Neutral educational counseling", "d": "Explaining appeal deadlines factually"},
         "a", "Federal civil rights laws protect beneficiaries from discrimination in healthcare programs.",
         {"b": "Lawful choice.", "c": "Permitted counseling.", "d": "Factual education."}, "easy"),
        ("When beneficiary lacks capacity, counselor should:",
         {"a": "Involve authorized representative/legal guardian per state law and document scope", "b": "Make all plan decisions alone without authority", "c": "Refuse all assistance permanently", "d": "Share PHI with unauthorized neighbor"},
         "a", "Counseling respects legal decision-making authority and privacy rules.",
         {"b": "Needs legal authority.", "c": "Assist within bounds.", "d": "Unauthorized disclosure prohibited."}, "medium"),
        ("Beneficiary right to unbiased information means counselor:",
         {"a": "Does not sell insurance or receive marketing commissions from plans", "b": "Must recommend highest commission plan", "c": "Works for single MA plan exclusively as marketer", "d": "Hides Original Medicare option intentionally"},
         "a", "SHIP and similar programs provide free neutral counseling without sales conflict.",
         {"b": "Conflict of interest prohibited.", "c": "SHIP not plan marketing.", "d": "Must present options fairly."}, "easy"),
    ])

    qs += pack(E, "fraud", [
        ("Common Medicare fraud scheme involves:",
         {"a": "Billing for services not provided or not medically necessary", "b": "Beneficiary reviewing MSN for accuracy", "c": "Counselor using CMS-approved materials", "d": "Provider documenting care appropriately"},
         "a", "Fraud includes false claims, kickbacks, and identity theft for improper payment.",
         {"b": "Beneficiary review prevents fraud.", "c": "Proper counseling.", "d": "Appropriate practice."}, "easy"),
        ("Beneficiary contacted 'Medicare will pay for back brace free' should:",
         {"a": "Treat as potential scam; never give Medicare number; report suspicious contact", "b": "Provide Medicare number and bank PIN immediately", "c": "Sign blank CMS forms", "d": "Assume all cold calls are CMS official always"},
         "a", "Durable medical equipment telemarketing scams steal identity and bill Medicare fraudulently.",
         {"b": "Never share sensitive info.", "c": "Blank forms dangerous.", "d": "Verify caller independently."}, "easy"),
        ("Counselor learning beneficiary shared Medicare card with 'helper' who ordered supplies should:",
         {"a": "Advise reporting to SMP, Medicare, and reviewing MSN for unauthorized charges", "b": "Ignore because free supplies nice", "c": "Encourage sharing number with more strangers", "d": "Tell beneficiary fraud impossible on Medicare"},
         "a", "SMP (Senior Medicare Patrol) helps report fraud; unauthorized orders harm beneficiary and program.",
         {"b": "Fraud harms program and beneficiary liability possible.", "c": "Increases fraud.", "d": "Fraud occurs frequently."}, "medium"),
        ("Kickback scheme in Medicare context is:",
         {"a": "Remuneration to induce referrals or use of services paid by federal programs", "b": "Legal discount fully compliant with AKS safe harbor when structured properly", "c": "Counselor unpaid volunteer time", "d": "Beneficiary paying Medigap premium to insurer"},
         "a", "Anti-Kickback Statute prohibits inducements for Medicare/Medicaid referrals.",
         {"b": "Compliant arrangements differ from inducements.", "c": "Volunteer counseling not kickback.", "d": "Premium payment lawful."}, "hard"),
        ("Upcoding fraud occurs when provider:",
         {"a": "Bills higher level service code than documented care supports", "b": "Documents and codes accurately", "c": "Counselor explains benefits", "d": "Beneficiary files legitimate appeal"},
         "a", "Upcoding inflates reimbursement through false severity reporting.",
         {"b": "Proper coding lawful.", "c": "Counseling not coding.", "d": "Appeals lawful."}, "medium"),
        ("Identity theft red flag on MSN shows:",
         {"a": "Services in city beneficiary never visited during that period", "b": "Expected primary care visit locally", "c": "Correct hospitalization beneficiary recalls", "d": "Zero claims all year with no services received"},
         "a", "Unknown services/locations on MSN suggest stolen Medicare number use.",
         {"b": "Expected if received care.", "c": "Consistent memory confirms.", "d": "No flag if truly no services."}, "medium"),
        ("Reporting Medicare fraud can include contacting:",
         {"a": "1-800-MEDICARE, SMP, HHS OIG hotline, or Medicare plan fraud line", "b": "Random email from unknown sender only", "c": "Social media influencer exclusively", "d": "Never report; keep secret always best"},
         "a", "Multiple official channels investigate fraud; SMP provides local assistance.",
         {"b": "Use official channels.", "c": "Not official.", "d": "Reporting protects beneficiary/program."}, "easy"),
        ("Marketing violation during Medicare sales includes:",
         {"a": "Door-to-door unsolicited contact prohibited in many MA/Part D marketing rules", "b": "Scheduled appointment after beneficiary request", "c": "Providing required plan materials at requested meeting", "d": "Compliant educational event with neutral CMS content"},
         "a", "CMS marketing rules restrict unsolicited door-to-door and certain incentives.",
         {"b": "Permitted with consent.", "c": "Required disclosures.", "d": "Educational events allowed if compliant."}, "medium"),
        ("Beneficiary asked to sign 'delivery receipt' for unrequested glucose monitor should:",
         {"a": "Refuse if not ordered; document; check MSN; report if billed", "b": "Sign to be polite always accepting liability", "c": "Give Medicare card copy as tip", "d": "Install device without doctor order always covered"},
         "a", "Unsolicited DME is common fraud; acceptance may imply consent to bill.",
         {"b": "Signature may be used fraudulently.", "c": "Card misuse.", "d": "Medical necessity required."}, "medium"),
        ("OIG exclusion list means excluded provider:",
         {"a": "Cannot participate in federal healthcare programs; billing excluded provider prohibited", "b": "Gets bonus payments", "c": "Only excluded from dental", "d": "List optional for counselors to ignore"},
         "a", "LEIE providers/entities cannot furnish services paid by Medicare/Medicaid.",
         {"b": "Opposite.", "c": "Broad federal exclusion.", "d": "Counselors should warn beneficiaries."}, "hard"),
        ("Phishing email 'Verify Medicare account or lose benefits' best response:",
         {"a": "Do not click links; contact Medicare via official phone on card/website", "b": "Enter Medicare number and bank info on link", "c": "Forward password to sender", "d": "Pay bitcoin to unlock account"},
         "a", "CMS does not threaten loss via email links; phishing steals identity.",
         {"b": "Phishing tactic.", "c": "Never share passwords.", "d": "Scam."}, "easy"),
        ("Counselor documenting suspected fraud should:",
         {"a": "Record facts objectively and refer to SMP without investigating criminally themselves", "b": "Accuse provider publicly without evidence", "c": "Share beneficiary gossip widely", "d": "Destroy MSN evidence"},
         "a", "Counselors support reporting with documentation; law enforcement investigates.",
         {"b": "Avoid defamation; use official channels.", "c": "Privacy required.", "d": "Preserve evidence."}, "medium"),
        ("Medicaid/Medicare dual eligible fraud may involve:",
         {"a": "Billing both programs improperly for same service", "b": "Lawful coordination by ethical provider", "c": "Counselor explaining QMB benefits", "d": "Beneficiary using MSP help correctly"},
         "a", "Double billing across programs is fraud; proper billing follows COB rules.",
         {"b": "Proper coordination lawful.", "c": "Education not fraud.", "d": "Assistance appropriate."}, "hard"),
        ("Gift inducement during AEP such as cash for enrolling in MA plan is:",
         {"a": "Generally prohibited beyond nominal gifts per CMS marketing rules", "b": "Required by Medicare", "c": "Unlimited if agent nice", "d": "Only illegal for Part A inpatient"},
         "a", "CMS limits marketing gifts/inducements to prevent undue influence on plan choice.",
         {"b": "Not required.", "c": "Limits apply.", "d": "Applies to MA/Part D marketing broadly."}, "medium"),
        ("Beneficiary recovery after fraud may include:",
         {"a": "Disputing charges, changing Medicare number if compromised, and plan/provider investigation", "b": "Automatic full cash refund from counselor personally always", "c": "Ignoring unauthorized bills", "d": "Paying fraudulent charges to avoid trouble"},
         "a", "Beneficiary should report, dispute, and protect identity; SMP/Medicare guide steps.",
         {"b": "Counselor not liable for fraud restitution personally.", "c": "Dispute required.", "d": "Paying validates fraud."}, "medium"),
    ])

    qs += pack(E, "counseling", [
        ("Neutral Medicare counseling session should begin with:",
         {"a": "Needs assessment and confirming counselor is not selling plans", "b": "Signing enrollment form immediately", "c": "Collecting credit card for counselor fee from all callers always", "d": "Promising largest commission plan"},
         "a", "SHIP-style counseling starts with scope, neutrality, and beneficiary-centered questions.",
         {"b": "Enrollment only when beneficiary decides.", "c": "SHIP services free to beneficiary.", "d": "Conflict of interest prohibited."}, "easy"),
        ("Motivational interviewing technique uses:",
         {"a": "Open questions, affirmations, reflective listening, and summarizing", "b": "Interrupting beneficiary constantly", "c": "Telling beneficiary they are wrong about all concerns", "d": "Refusing to listen to preferences"},
         "a", "MI supports behavior change and informed decision-making without pressure.",
         {"b": "Harmful to rapport.", "c": "Dismissive.", "d": "Preferences central."}, "medium"),
        ("When beneficiary is overwhelmed, counselor should:",
         {"a": "Prioritize issues, break information into chunks, and schedule follow-up", "b": "Dump all 100 pages at once without pause", "c": "End session abruptly without resources", "d": "Insist immediate decision on all programs today"},
         "a", "Effective counseling paces information and confirms understanding (teach-back).",
         {"b": "Cognitive overload reduces understanding.", "c": "Provide written resources/referrals.", "d": "Decisions can take time within enrollment windows."}, "easy"),
        ("Teach-back method asks beneficiary to:",
         {"a": "Explain in own words what they understood about next steps", "b": "Repeat counselor word-for-word only without understanding", "c": "Sign without reading", "d": "Skip questions to save time"},
         "a", "Teach-back verifies comprehension of coverage choices and deadlines.",
         {"b": "Understanding matters not rote repeat.", "c": "Informed consent needs comprehension.", "d": "Questions encouraged."}, "easy"),
        ("Counselor referral to State Health Insurance Assistance Program (SHIP) is appropriate when:",
         {"a": "Beneficiary needs free unbiased help comparing Medicare options", "b": "Beneficiary wants illegal fraud tips", "c": "Counselor sells Medigap and wants commission", "d": "Beneficiary needs veterinary advice"},
         "a", "SHIP provides local Medicare counseling consistent with federal/state funding.",
         {"b": "Counselors discourage fraud.", "c": "Sales conflict; refer SHIP for neutral help.", "d": "Out of scope."}, "easy"),
        ("Documentation in counseling notes should:",
         {"a": "Be factual, minimal necessary PHI, stored securely per agency policy", "b": "Include gossip about beneficiary family for entertainment", "c": "Posted on public blog", "d": "Omit all record of advice given"},
         "a", "Confidential documentation supports continuity and grant compliance with privacy safeguards.",
         {"b": "Unprofessional/privacy violation.", "c": "HIPAA violation.", "d": "Records often required for programs."}, "medium"),
        ("Beneficiary with employer coverage turning 65 should be counseled to:",
         {"a": "Compare employer plan vs Medicare timing, Part B delay rules, and spouse coverage", "b": "Drop employer coverage immediately always without analysis", "c": "Ignore Special Enrollment Period rules", "d": "Enroll Part B without checking creditable coverage status"},
         "a", "Active employment group coverage may allow Part B delay without penalty; individualized analysis needed.",
         {"b": "Employer coverage may be better temporarily.", "c": "SEP important when leaving coverage.", "d": "Creditable coverage determines penalty risk."}, "hard"),
        ("Low health literacy counseling strategy includes:",
         {"a": "Plain language, visual aids, and avoiding jargon", "b": "Complex acronyms without explanation", "c": "Assuming beneficiary reads medical policy manuals for fun", "d": "Rushing through key cost-sharing terms"},
         "a", "Plain language and visuals improve informed choice for all literacy levels.",
         {"b": "Jargon confuses.", "c": "Do not assume advanced literacy.", "d": "Cost-sharing critical to explain slowly."}, "medium"),
        ("Counselor boundaries when beneficiary offers expensive gift:",
         {"a": "Decline or follow agency policy on nominal gifts to avoid undue influence", "b": "Accept car keys gladly always", "c": "Demand payment for all future calls secretly", "d": "Sell beneficiary insurance on side"},
         "a", "Professional boundaries maintain trust and program integrity.",
         {"b": "Excessive gifts inappropriate.", "c": "Fee-for-service outside policy if prohibited.", "d": "Side sales conflict with neutrality."}, "medium"),
        ("Cultural humility in counseling means:",
         {"a": "Recognizing counselor does not know all cultural contexts and asking respectful questions", "b": "Stereotyping groups uniformly", "c": "Ignoring beneficiary values", "d": "Assuming Medicare rules differ by ethnicity illegally"},
         "a", "Humility supports respectful individualized counseling within same Medicare rules.",
         {"b": "Stereotyping harmful.", "c": "Values matter in decisions.", "d": "Rules uniform; preferences differ."}, "medium"),
        ("Follow-up plan after complex LIS and MSP application counseling should include:",
         {"a": "Checklist of documents, agency contacts, deadlines, and scheduled follow-up call", "b": "No written summary ever", "c": "Promise guaranteed approval", "d": "Tell beneficiary never call SSA/Medicaid offices"},
         "a", "Action plans with contacts reduce missed deadlines for assistance programs.",
         {"b": "Written summary helps.", "c": "Cannot guarantee approval.", "d": "Official agencies process applications."}, "medium"),
        ("Counselor faced with angry beneficiary about denied claim should:",
         {"a": "Listen, validate emotion, explain appeal path, and offer practical next steps", "b": "Hang up immediately without explanation", "c": "Yell back to assert dominance", "d": "Guarantee win on appeal falsely"},
         "a", "De-escalation with accurate appeal information supports beneficiary empowerment.",
         {"b": "Abandons beneficiary.", "c": "Unprofessional.", "d": "Cannot guarantee outcomes."}, "easy"),
        ("Screening for Medicare Savings Programs (MSP) includes asking about:",
         {"a": "Income and resources relative to state thresholds for QMB/SLMB/QI", "b": "Favorite movie only", "c": "Neighbor's income only", "d": "Stock tips"},
         "a", "MSP help with Part B premiums/cost-sharing based on income/resource limits varying by state.",
         {"b": "Irrelevant.", "c": "Beneficiary's own finances matter.", "d": "Irrelevant."}, "medium"),
        ("Group presentation vs individual counseling difference:",
         {"a": "Group educates generally; individual addresses personal eligibility and choices confidentially", "b": "Group must enroll all in same plan", "c": "Individual sessions may ignore beneficiary questions", "d": "Group allows sharing PHI of attendees publicly"},
         "a", "Education events complement but do not replace personalized counseling.",
         {"b": "Individual choice remains.", "c": "Questions central.", "d": "PHI privacy in groups."}, "easy"),
        ("Closing counseling session effectively includes:",
         {"a": "Summarize decisions/next steps, provide written resources, and confirm contact for questions", "b": "Leave beneficiary confused intentionally", "c": "Pressure signature on unknown form", "d": "Delete beneficiary phone number"},
         "a", "Closure reinforces understanding and accessible follow-up within program rules.",
         {"b": "Opposite goal.", "c": "Coercion prohibited.", "d": "Contact info needed for follow-up if permitted."}, "easy"),
    ])

    assert len(qs) == 60
    return qs


if __name__ == "__main__":
    from _common import write_bank
    write_bank("medicare-counseling-readiness-check", build())
