#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "medical-billing-specialist-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "claims", [
        ("A clean claim under Medicare generally means:",
         {"a": "Complete, accurate, timely submission with required identifiers and no missing info", "b": "Claim handwritten only", "c": "Claim missing provider NPI", "d": "Claim submitted years after service"},
         "a", "Clean claims contain all data needed for adjudication without additional information.",
         {"b": "Electronic/paper both allowed if complete.", "c": "NPI required.", "d": "Timeliness limits apply."}, "easy"),
        ("CMS-1500 form is primarily used to bill:",
         {"a": "Professional physician/outpatient services", "b": "Inpatient hospital stays only", "c": "Dental only", "d": "Property tax"},
         "a", "CMS-1500 is the professional claim form; UB-04 is institutional.",
         {"b": "Institutional uses UB-04.", "c": "Dental may use ADA form.", "d": "Unrelated."}, "easy"),
        ("Place of service (POS) code 11 indicates:",
         {"a": "Office", "b": "Inpatient hospital", "c": "Ambulance", "d": "Homeless shelter only"},
         "a", "POS 11 is office setting on professional claims.",
         {"b": "Hospital inpatient different codes.", "c": "Ambulance has specific POS.", "d": "Not POS 11 definition."}, "medium"),
        ("Claim rejection at clearinghouse for invalid subscriber ID should be:",
         {"a": "Corrected with verified insurance information and resubmitted", "b": "Ignored because payment automatic", "c": "Billed to patient without verification always first", "d": "Submitted repeatedly unchanged"},
         "a", "Rejections are pre-adjudication edits fixed by correcting data and resubmitting.",
         {"b": "Rejections stop processing.", "c": "Verify coverage first.", "d": "Duplicate rejections waste time."}, "easy"),
        ("Coordination of benefits (COB) applies when patient has:",
         {"a": "Primary and secondary coverage; primary pays first per rules", "b": "No insurance ever", "c": "Only workers' comp for unrelated cold visit always", "d": "Cash pay only"},
         "a", "COB determines order of payment when multiple payers cover the patient.",
         {"b": "COB needs multiple plans.", "c": "Unrelated injury may not be WC.", "d": "No COB with cash."}, "medium"),
        ("Timely filing limit denial means:",
         {"a": "Claim submitted after payer deadline without valid exception", "b": "Claim paid twice", "c": "Patient overpaid copay", "d": "Provider NPI valid"},
         "a", "Each payer sets filing limits; late claims deny unless appeal exception applies.",
         {"b": "Different issue.", "c": "Copay separate.", "d": "Valid NPI would not cause this denial."}, "medium"),
        ("Advance Beneficiary Notice (ABN) is used when:",
         {"a": "Medicare may not pay for service and patient chooses to proceed", "b": "Commercial HMO always pays", "c": "Patient refuses all treatment ever", "d": "Coding is always correct without discussion"},
         "a", "ABN documents patient liability when Medicare coverage unlikely.",
         {"b": "ABN is Medicare-specific tool.", "c": "Not refusal of all care.", "d": "Coverage uncertainty drives ABN."}, "hard"),
        ("Electronic remittance advice (ERA/835) provides:",
         {"a": "Explanation of payment, adjustments, and reason codes", "b": "Patient medical record", "c": "Prescription refill requests", "d": "Operating room schedule"},
         "a", "835 ERA details paid amounts, adjustments (CARC/RARC), and claim status.",
         {"b": "Clinical chart separate.", "c": "Pharmacy workflow.", "d": "Scheduling separate."}, "medium"),
        ("Duplicate claim denial often results from:",
         {"a": "Same service billed twice with same date/provider without modifier/resubmission indicator", "b": "Corrected claim with appropriate frequency code", "c": "First submission ever", "d": "Valid appeal only"},
         "a", "Payers detect duplicate service lines; use frequency/modifier for corrections/voids.",
         {"b": "Frequency 7/8 indicates replacement/void appropriately.", "c": "First sub not duplicate.", "d": "Appeal follows denial."}, "medium"),
        ("Global surgical package includes:",
         {"a": "Pre-op visit day before major surgery, surgery, and follow-up within global period per CPT", "b": "Unrelated ER visit months later", "c": "New problem visit same day always separately paid without modifier", "d": "Anesthesia always in global for all payers without rules"},
         "a", "Global periods bundle certain pre/post op services; separate billing rules apply.",
         {"b": "Unrelated services bill separately.", "c": "Same-day E/M may need modifier 25 if significant separate problem.", "d": "Anesthesia often billed separately."}, "hard"),
        ("Claim scrubber edit 'missing referring provider NPI' for specialist visit should be fixed by:",
         {"a": "Adding valid referring/ordering provider when required by payer", "b": "Deleting patient name", "c": "Changing CPT to unrelated code", "d": "Submitting without diagnosis"},
         "a", "Many plans require referring provider for specialist claims.",
         {"b": "Patient demographics required.", "c": "Code must match service.", "d": "Diagnosis required."}, "easy"),
        ("Void/correct claim process typically uses:",
         {"a": "Frequency code 8 void then new claim or frequency 7 replacement per payer rules", "b": "Same claim number forever", "c": "Phone call only without resubmission ever", "d": "Cash refund without claim adjustment"},
         "a", "Electronic claims use frequency/type codes to void or replace prior submission.",
         {"b": "Corrections need proper indicators.", "c": "Electronic correction usually required.", "d": "Claim and payment systems must align."}, "hard"),
        ("Patient statement after insurance payment should show:",
         {"a": "Service detail, insurance payments/adjustments, patient responsibility per EOB alignment", "b": "Only greeting message", "c": "Other patients' balances", "d": "Provider salary"},
         "a", "Statements reflect allowed amounts, payments, adjustments, and remaining patient liability.",
         {"b": "Detail required.", "c": "HIPAA prohibits other patients' info.", "d": "Irrelevant."}, "easy"),
        ("Workers' compensation claim billing generally requires:",
         {"a": "WC payer info, injury date, employer, and diagnosis linked to work injury", "b": "Medicare primary always for work injury", "c": "No documentation of injury", "d": "Standard copay collection always"},
         "a", "WC claims need injury-related data and often treat authorization per state.",
         {"b": "WC usually primary for work injury.", "c": "Documentation mandatory.", "d": "Copay rules differ."}, "medium"),
        ("Underbilling same service repeatedly below contracted rate by error should be:",
         {"a": "Corrected through rebilling/contract review and internal audit", "b": "Ignored as patient favor", "c": "Hidden to avoid payer attention forever", "d": "Considered fraud if intentional overbilling only—underbilling never matters"},
         "a", "Accurate billing reflects contract; patterns affect revenue and compliance audits.",
         {"b": "Accuracy required.", "c": "Concealment prevents correction.", "d": "Underbilling also reviewed in audits."}, "medium"),
    ])

    qs += pack(E, "coding-awareness", [
        ("ICD-10-CM codes primarily describe:",
         {"a": "Diagnoses, symptoms, and reasons for encounter", "b": "Procedure fees only", "c": "Provider tax ID", "d": "Patient address only"},
         "a", "ICD-10-CM captures diagnosis and clinical status supporting medical necessity.",
         {"b": "Procedures use CPT/HCPCS.", "c": "Billing identifier separate.", "d": "Demographics not ICD purpose."}, "easy"),
        ("CPT code 99213 typically represents:",
         {"a": "Established patient office visit level 3", "b": "Appendectomy", "c": "MRI brain", "d": "Dental cleaning"},
         "a", "99213 is common established patient E/M level based on MDM/time per rules.",
         {"b": "Surgery different codes.", "c": "Radiology different section.", "d": "Dental ADA codes."}, "easy"),
        ("Modifier 25 indicates:",
         {"a": "Significant, separately identifiable E/M on same day as procedure", "b": "Bilateral procedure", "c": "Cancelled procedure", "d": "Telehealth audio-only always"},
         "a", "Modifier 25 supports separate E/M with procedure same day when criteria met.",
         {"b": "Bilateral often modifier 50.", "c": "Cancelled different modifiers.", "d": "Telehealth uses 95/other per payer."}, "hard"),
        ("Upcoding means:",
         {"a": "Billing higher level service than documented/supported", "b": "Billing correct level with full documentation", "c": "Using valid ICD link", "d": "Timely filing"},
         "a", "Upcoding is fraudulent misrepresentation of service intensity.",
         {"b": "Appropriate coding.", "c": "Proper practice.", "d": "Operational requirement."}, "easy"),
        ("Medical necessity requires:",
         {"a": "Service reasonable and necessary for diagnosis/treatment supported in record", "b": "Patient preference alone without clinical indication", "c": "Marketing brochure statement", "d": "Higher reimbursement only"},
         "a", "Payers deny services not justified by diagnosis and clinical documentation.",
         {"b": "Preference insufficient.", "c": "Marketing not medical record.", "d": "Revenue motive not necessity."}, "medium"),
        ("HCPCS Level II codes often represent:",
         {"a": "Supplies, drugs, ambulance, and DME not in CPT", "b": "Only psychiatric diagnoses", "c": "Employee payroll", "d": "Facility mortgage"},
         "a", "HCPCS includes J-codes for drugs, A-codes ambulance, etc.",
         {"b": "Diagnoses are ICD.", "c": "Not HCPCS.", "d": "Not HCPCS."}, "medium"),
        ("Laterality in ICD-10 (left/right) should:",
         {"a": "Match clinical documentation specifying side when applicable", "b": "Be guessed for speed", "c": "Always unspecified if unsure without query", "d": "Omit because payers ignore"},
         "a", "Specificity including laterality improves accuracy; query provider if documentation unclear.",
         {"b": "Guessing causes denials/audit risk.", "c": "Unspecified only if truly unknown after query.", "d": "Payers require specificity."}, "medium"),
        ("NCCI edits prevent:",
         {"a": "Improper unbundling of component codes billed separately when bundled", "b": "All billing ever", "c": "Valid modifier use always", "d": "Correct coding with modifiers when allowed"},
         "a", "National Correct Coding Initiative pairs codes that should not bill together unless modifier appropriate.",
         {"b": "Billing continues with correct combos.", "c": "Modifiers may override when clinically appropriate.", "d": "Allowed combinations bill fine."}, "hard"),
        ("Principal diagnosis on inpatient claim is:",
         {"a": "Condition established after study to be chiefly responsible for admission", "b": "Any comorbidity", "c": "Billing clerk choice without coder review", "d": "Always Z code only"},
         "a", "Inpatient principal diagnosis drives DRG assignment after physician/coder validation.",
         {"b": "Secondary diagnoses additional.", "c": "Coder uses documentation.", "d": "Z codes are factors/status when applicable."}, "hard"),
        ("Evaluation and management leveling uses (2021+ office/outpatient rules emphasize):",
         {"a": "Medical decision making and/or total time on date of encounter per documentation", "b": "Room color", "c": "Patient shoe size only", "d": "Number of staff in hallway"},
         "a", "E/M levels based on MDM elements or time per current CMS/AMA guidelines.",
         {"b": "Irrelevant.", "c": "Irrelevant.", "d": "Irrelevant."}, "medium"),
        ("External cause codes (V/W/X/Y) capture:",
         {"a": "Mechanism/circumstance of injury or poisoning when documented", "b": "Primary diabetes always", "c": "Fee schedule", "d": "Provider specialty only"},
         "a", "External cause codes supplement injury/poisoning coding when documented.",
         {"b": "Diabetes E codes different chapter.", "c": "Not ICD purpose.", "d": "Specialty on claim field not external cause."}, "medium"),
        ("Unlisted CPT code requires:",
         {"a": "Description and often comparable code with documentation supporting unique service", "b": "No documentation", "c": "Automatic highest payment", "d": "Use for all routine visits"},
         "a", "Unlisted codes need report/comparison to establish value and medical necessity.",
         {"b": "Documentation essential.", "c": "Payment not automatic highest.", "d": "Routine visits have specific E/M codes."}, "medium"),
        ("Modifier 59 indicates:",
         {"a": "Distinct procedural service when no more specific modifier applies", "b": "Repeat procedure same session always", "c": "Global period only", "d": "Telephone call only"},
         "a", "59 breaks NCCI bundles when separate session/site/organ/encounter per criteria.",
         {"b": "Repeat may use 76/77.", "c": "Global separate concept.", "d": "Telephone E/M separate codes."}, "hard"),
        ("Query physician when documentation:",
         {"a": "Conflicts or lacks specificity needed for accurate code assignment", "b": "Is complete and clear", "c": "Matches nursing note only without conflict", "d": "Never; guess instead"},
         "a", "Clinical documentation improvement queries resolve ambiguity before coding.",
         {"b": "No query needed.", "c": "Agreement allows coding.", "d": "Guessing violates compliance."}, "easy"),
        ("SNOMED in EHR differs from ICD-10 on claim because:",
         {"a": "Claims require ICD-10-CM diagnosis codes; SNOMED supports clinical documentation mapping", "b": "SNOMED replaces CPT on CMS-1500", "c": "ICD-10 only for dental", "d": "They are identical always"},
         "a", "SNOMED CT is clinical terminology; billing uses ICD-10-CM mapped from documentation.",
         {"b": "CPT still procedures.", "c": "ICD-10 broad use.", "d": "Different purposes."}, "medium"),
    ])

    qs += pack(E, "payers", [
        ("Medicare Part A primarily covers:",
         {"a": "Inpatient hospital, skilled nursing (limited), hospice, some home health", "b": "Retail prescriptions always", "c": "Routine dental only", "d": "Auto insurance"},
         "a", "Part A is hospital insurance for inpatient/SNF/hospice benefits when eligible.",
         {"b": "Part D drugs.", "c": "Dental limited exceptions.", "d": "Unrelated payer."}, "easy"),
        ("Medicare Part B generally covers:",
         {"a": "Physician services, outpatient care, DME, preventive services", "b": "Inpatient room board only", "c": "Long-term custodial nursing only", "d": "Hearing aids always fully"},
         "a", "Part B is medical insurance for outpatient professional/services and DME.",
         {"b": "Part A inpatient.", "c": "Custodial care not covered.", "d": "Hearing aids generally not covered."}, "easy"),
        ("Medicare Advantage (Part C) claims are submitted to:",
         {"a": "The Medicare Advantage plan, not Original Medicare directly", "b": "Patient employer only", "c": "Social Security office paper only", "d": "Medicaid always first for all services"},
         "a", "MA plans are paid capitation; providers bill the plan per contract.",
         {"b": "Employer may not be involved.", "c": "Electronic to plan.", "d": "Primary depends on coverage."}, "medium"),
        ("Medicaid eligibility and billing vary by:",
         {"a": "State rules, managed care plans, and fee schedules", "b": "Single national identical policy everywhere", "c": "Patient hobby", "d": "Moon phase"},
         "a", "Medicaid is state-administered with federal guidelines; billing rules differ.",
         {"b": "State variation significant.", "c": "Irrelevant.", "d": "Irrelevant."}, "medium"),
        ("TRICARE is health coverage for:",
         {"a": "Uniformed service members, retirees, and families", "b": "All US tourists", "c": "Only veterans at VA exclusively always billed same", "d": "Medicare only population"},
         "a", "TRICARE serves military community; billing follows TRICARE rules distinct from VA direct care.",
         {"b": "Not general tourist.", "c": "VA and TRICARE differ.", "d": "Separate program."}, "medium"),
        ("Commercial payer prior authorization denial for MRI should prompt:",
         {"a": "Review denial reason, peer-to-peer if available, patient notification, alternative plan", "b": "Perform MRI without auth always", "c": "Bill Medicare if patient has none", "d": "Ignore patient communication"},
         "a", "Appeals and peer review may overturn; patient informed of options and liability.",
         {"b": "Unauthorized service may deny payment.", "c": "Wrong payer.", "d": "Patient communication required."}, "medium"),
        ("Medicare secondary payer (MSP) rules may make Medicare secondary when:",
         {"a": "Group health plan due to active employment over certain size/age rules or other insurance primary situations", "b": "Patient has no other coverage ever", "c": "Patient pays cash only", "d": "Service is screening always"},
         "a", "MSP provisions determine when Medicare pays secondary to other insurance.",
         {"b": "No other coverage means Medicare primary if eligible.", "c": "Cash not other insurance.", "d": "Screening has specific rules but MSP broader."}, "hard"),
        ("Capitated contract means provider:",
         {"a": "Receives fixed per-member payment and manages care within budget", "b": "Billed fee-for-service only per visit always", "c": "Paid only by patient tips", "d": "Never sees patients"},
         "a", "Capitation pays per enrolled member period regardless of visit volume.",
         {"b": "FFS different model.", "c": "Not payment model.", "d": "Still provides care."}, "medium"),
        ("Explanation of Benefits (EOB) to patient shows:",
         {"a": "What provider billed, allowed amount, plan paid, patient owes—not a bill itself usually", "b": "Legal subpoena", "c": "Prescription with refills", "d": "Provider license renewal"},
         "a", "EOB explains adjudication; provider statement may follow for patient balance.",
         {"b": "Not legal order.", "c": "Pharmacy document.", "d": "Unrelated."}, "easy"),
        ("Blue Cross plan out-of-state emergency care often:",
         {"a": "Processed under emergency/urgent rules per member contract and federal protections", "b": "Never covered", "c": "Requires pre-auth before car crash", "d": "Paid only if provider in Antarctica"},
         "a", "Emergency services have special network/payment rules under ACA and plan terms.",
         {"b": "Emergencies generally covered with cost share.", "c": "Retro auth impossible pre-crash.", "d": "Geography joke; real rules apply domestically."}, "medium"),
        ("Medicare Part D is:",
         {"a": "Prescription drug coverage through private plans", "b": "Hospital inpatient only", "c": "Dental unlimited", "d": "Provider malpractice insurance"},
         "a", "Part D plans cover outpatient drugs via PDP/MA-PD.",
         {"b": "Part A.", "c": "Not Part D scope.", "d": "Unrelated."}, "easy"),
        ("Railroad Medicare claims are processed by:",
         {"a": "Palmetto GBA or designated MAC under special Medicare rules for railroad beneficiaries", "b": "Amtrak ticket office", "c": "State Medicaid only always", "d": "Patient employer HR exclusively"},
         "a", "Railroad Retirement Board beneficiaries have Medicare processed through designated contractors.",
         {"b": "Not Amtrak.", "c": "Medicare primary if eligible.", "d": "MAC processes."}, "hard"),
        ("Self-funded employer plan claims are paid by:",
         {"a": "Employer/plan administrator often using TPA; not fully insured carrier risk", "b": "Medicare always", "c": "Patient only with no administrator", "d": "State lottery"},
         "a", "Self-funded ERISA plans use administrator; billing follows plan documents.",
         {"b": "May coordinate but employer plan primary per rules.", "c": "Administrator exists.", "d": "Unrelated."}, "hard"),
        ("HMO referral requirement means:",
         {"a": "PCP referral/authorization needed for specialist except emergencies per plan", "b": "Any provider nationwide always without ID", "c": "No primary care role", "d": "Medicare replaces HMO rules always"},
         "a", "HMOs gatekeep specialty care through PCP/referrals and network.",
         {"b": "Network limits apply.", "c": "PCP central to HMO.", "d": "MA HMO follows plan."}, "easy"),
        ("Patient eligibility verification should occur:",
         {"a": "Before service when possible and at intervals for ongoing treatment", "b": "Never; assume active coverage", "c": "Only after collections lawsuit", "d": "Once at birth only"},
         "a", "Real-time eligibility reduces denials for termed coverage or changed benefits.",
         {"b": "Coverage changes frequently.", "c": "Too late.", "d": "Ongoing verification needed."}, "easy"),
    ])

    qs += pack(E, "compliance", [
        ("HIPAA Privacy Rule requires:",
         {"a": "Safeguarding PHI, minimum necessary use/disclosure, patient rights", "b": "Posting all diagnoses publicly", "c": "Sharing SSN in waiting room aloud", "d": "No workforce training ever"},
         "a", "HIPAA mandates administrative, physical, technical safeguards and patient rights.",
         {"b": "Public posting prohibited.", "c": "Verbal PHI disclosure improper.", "d": "Training required."}, "easy"),
        ("False Claims Act exposure occurs when:",
         {"a": "Knowingly submitting false claims for government payment", "b": "Billing correct documented services", "c": "Providing free charity care policy compliant", "d": "Credentialing staff"},
         "a", "FCA imposes liability for fraudulent government healthcare claims.",
         {"b": "Proper billing protected.", "c": "Charity care lawful.", "d": "Unrelated."}, "medium"),
        ("OIG compliance program elements include:",
         {"a": "Written policies, training, auditing, enforcement, and response procedures", "b": "Ignore regulations to maximize speed", "c": "Single verbal rule only", "d": "Marketing exclusively"},
         "a", "Federal guidance expects seven elements for effective compliance programs.",
         {"b": "Opposite of compliance.", "c": "Insufficient.", "d": "Marketing not core element."}, "medium"),
        ("Stark Law generally prohibits:",
         {"a": "Physician self-referral for designated health services to entities with financial relationship absent exception", "b": "All employment of physicians ever", "c": "Billing Medicaid", "d": "Using computers"},
         "a", "Stark restricts DHS referrals where physician has financial relationship unless exception met.",
         {"b": "Employment allowed with exceptions.", "c": "Medicaid billing lawful.", "d": "Technology unrelated."}, "hard"),
        ("Anti-Kickback Statute concerns:",
         {"a": "Remuneration to induce referrals for services paid by federal programs", "b": "Paying fair market value rent with safe harbor", "c": "Normal salary to employed physician", "d": "Discounts fully compliant with safe harbor when structured properly"},
         "a", "AKS criminalizes inducements for federal healthcare referrals; safe harbors protect lawful arrangements.",
         {"b": "FMV rent safe harbor may protect.", "c": "Bona fide employment excepted.", "d": "Compliant discounts allowed."}, "hard"),
        ("Documentation retention for claims generally requires:",
         {"a": "Maintaining records supporting services billed per payer/regulatory periods (often 5–7+ years)", "b": "Destroy all records day after payment", "c": "Keep only verbal memory", "d": "Patient keeps only copy provider destroys immediately"},
         "a", "Retention policies follow CMS/state/false claims standards typically multi-year.",
         {"b": "Destruction too soon violates audit ability.", "c": "Insufficient.", "d": "Provider must retain."}, "medium"),
        ("RAC audit targets:",
         {"a": "Medicare improper payments through review of claims and medical necessity", "b": "Patient parking tickets", "c": "Employee lunch choices", "d": "Vending machine inventory only"},
         "a", "Recovery Audit Contractors identify overpayments/underpayments on Medicare claims.",
         {"b": "Unrelated.", "c": "Unrelated.", "d": "Unrelated."}, "medium"),
        ("Credit card on file for copay collection must follow:",
         {"a": "PCI-DSS security and patient authorization/disclosure policies", "b": "Storing CVV in plain text spreadsheet shared", "c": "Charging random amounts without notice", "d": "Sharing card number with marketers"},
         "a", "Payment card data requires secure processing and transparent patient consent.",
         {"b": "CVV storage prohibited generally.", "c": "Unauthorized charges illegal.", "d": "PCI/HIPAA violation."}, "medium"),
        ("Incident response for ransomware on billing system includes:",
         {"a": "Isolate systems, notify leadership/IT, assess breach notification obligations, restore from backups", "b": "Pay ransom silently without reporting always legal", "c": "Ignore and continue billing on infected machines only", "d": "Post PHI online to prove hack"},
         "a", "Cyber incidents require containment, forensic analysis, and potential HIPAA breach notification.",
         {"b": "Reporting and legal review still needed.", "c": "Continued use spreads encryption.", "d": "Aggravates breach."}, "hard"),
        ("Billing unbundled lab panels intentionally for higher pay is:",
         {"a": "Fraud/abuse if panels should be billed as panel per policy", "b": "Always required", "c": "Random choice", "d": "Patient preference only"},
         "a", "Deliberate unbundling violating NCCI/payer rules is compliance violation.",
         {"b": "Panels bill as panel when appropriate.", "c": "Must follow rules.", "d": "Not patient choice."}, "medium"),
        ("Compliance hotline purpose:",
         {"a": "Anonymous/good-faith reporting of suspected violations", "b": "Ordering lunch", "c": "Marketing surveys only", "d": "Sharing passwords quickly"},
         "a", "Hotlines support reporting without retaliation per policy.",
         {"b": "Unrelated.", "c": "Not primary purpose.", "d": "Security violation."}, "easy"),
        ("Excluded individual on OIG LEIE list:",
         {"a": "Cannot participate in federal healthcare programs; hiring/billing prohibited", "b": "Gets bonus payments", "c": "Only excluded from dental", "d": "List is optional ignore"},
         "a", "LEIE lists individuals/entities excluded from Medicare/Medicaid participation.",
         {"b": "Opposite.", "c": "Federal programs broadly.", "d": "Must screen employees/vendors."}, "hard"),
        ("Balanced Billing (surprise billing) protections under No Surprises Act generally limit:",
         {"a": "Out-of-network cost sharing in certain emergency and facility settings", "b": "All medical care worldwide forever free", "c": "In-network copays only increase", "d": "Medicare replacement entirely"},
         "a", "NSA restricts surprise OON bills in specified settings with IDR process.",
         {"b": "Overstates law.", "c": "Not NSA focus.", "d": "Medicare separate."}, "hard"),
        ("Release of information for billing to attorney requires:",
         {"a": "Patient authorization compliant with HIPAA/state law specifying scope", "b": "Verbal request from stranger", "c": "Posting records on website", "d": "Billing clerk personal decision only without form"},
         "a", "Attorney access needs valid HIPAA authorization or legal process.",
         {"b": "Insufficient.", "c": "Prohibited disclosure.", "d": "Policy/form required."}, "easy"),
        ("Regular compliance training for billing staff should document:",
         {"a": "Attendance, topics covered, and periodic updates on fraud/waste/abuse and HIPAA", "b": "Only birthday parties", "c": "Nothing; training optional forever", "d": "Personal social media handles"},
         "a", "Documented training demonstrates compliance program effectiveness to auditors.",
         {"b": "Irrelevant.", "c": "Training expected.", "d": "Irrelevant."}, "easy"),
    ])

    assert len(qs) == 60
    return qs


if __name__ == "__main__":
    from _common import write_bank
    write_bank("medical-billing-specialist-readiness-check", build())
