#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "nremt-emr-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "airway", [
        ("An unresponsive adult has gurgling respirations and vomitus in the mouth. Your first airway action is to:",
         {"a": "Insert an oropharyngeal airway without suction", "b": "Log-roll, suction the oropharynx, then reassess breathing", "c": "Begin chest compressions immediately without airway care", "d": "Place the patient supine with head hyperextended only"},
         "b", "Airway obstruction from secretions requires positioning and suction before adjuncts or ventilation.",
         {"a": "Adjuncts do not clear material; suction first.", "c": "If breathing is present after clearing, compressions are not indicated.", "d": "Hyperextension alone does not clear vomitus."}, "easy"),
        ("Which patient is the best candidate for a nasopharyngeal (NPA) airway?",
         {"a": "Semiconscious patient with intact gag reflex who needs basic airway support", "b": "Apneic patient requiring bag-mask ventilation only", "c": "Patient with suspected basilar skull fracture", "d": "Fully conscious patient refusing all care"},
         "a", "NPA is tolerated in semiconscious patients with gag reflex; OPA may trigger gagging/vomiting.",
         {"b": "BVM may be used without NPA; NPA helps maintain patency in some semiconscious patients.", "c": "NPA is contraindicated with basilar skull fracture risk.", "d": "Refusal limits intervention."}, "medium"),
        ("Proper head-tilt chin-lift is contraindicated when you suspect:",
         {"a": "Asthma exacerbation", "b": "Cervical spine injury without manual inline stabilization", "c": "Hypoglycemia", "d": "Heat exhaustion"},
         "b", "Suspected spinal injury requires jaw-thrust/manual inline stabilization instead of head-tilt.",
         {"a": "Airway opening may still be needed with spinal precautions.", "c": "Not a contraindication to airway maneuvers.", "d": "Not related to cervical precautions."}, "medium"),
        ("A conscious adult is choking, cannot speak, and has ineffective cough. You should:",
         {"a": "Give abdominal thrusts (Heimlich) until obstruction clears or patient becomes unresponsive", "b": "Start rescue breathing without attempting dislodgment", "c": "Slap the back while the patient is sitting upright only", "d": "Wait for advanced providers before any intervention"},
         "a", "Complete airway obstruction in a conscious adult warrants abdominal thrusts per AHA BLS.",
         {"b": "Breaths cannot pass a complete obstruction.", "c": "Back blows may be used in cycles but thrusts are standard for adults.", "d": "Immediate action is required."}, "easy"),
        ("When ventilating an apneic adult with a bag-valve-mask (BVM), adequate ventilation is indicated by:",
         {"a": "Visible chest rise over about 1 second per breath at 10–12 breaths/min", "b": "Gastric distention only", "c": "Rapid forceful breaths at 30/min regardless of chest rise", "d": "Ventilating without a seal because leaks are acceptable"},
         "a", "Each breath should produce visible chest rise without excessive rate or force.",
         {"b": "Gastric distention suggests excessive volume or poor seal.", "c": "Hyperventilation is harmful.", "d": "A proper mask seal is essential."}, "medium"),
        ("An oropharyngeal airway (OPA) is sized by measuring from:",
         {"a": "Earlobe to xiphoid process", "b": "Corner of the mouth to the angle of the mandible", "c": "Nose to umbilicus", "d": "Shoulder to wrist"},
         "b", "Standard OPA sizing uses mouth corner to mandibular angle.",
         {"a": "That measurement is for NPA (nostril to tragus).", "c": "Not a standard airway measurement.", "d": "Not used for airway sizing."}, "easy"),
        ("You are ventilating a patient with a BVM and resistance is high with poor chest rise. You should first:",
         {"a": "Increase ventilatory rate to 30/min", "b": "Reposition the head/jaw and confirm a mask seal", "c": "Remove the BVM and wait", "d": "Administer high-flow oxygen without ventilation"},
         "b", "Poor rise often reflects inadequate seal or airway positioning before increasing force/rate.",
         {"a": "Higher rate worsens air trapping and gastric inflation.", "c": "Apneic patients need ventilation attempts.", "d": "Oxygen alone does not ventilate apneic patients."}, "medium"),
        ("Which finding suggests partial upper airway obstruction?",
         {"a": "Silent chest with no air movement", "b": "Stridor with hoarse voice and anxiety", "c": "Normal conversational speech", "d": "Regular painless breathing at 16/min"},
         "b", "Stridor and voice changes suggest partial obstruction of the upper airway.",
         {"a": "Complete obstruction may be silent.", "c": "Normal speech suggests patent airway.", "d": "Normal breathing without distress."}, "easy"),
        ("For a trauma patient requiring spinal precautions, opening the airway is best done with:",
         {"a": "Head-tilt chin-lift alone", "b": "Jaw-thrust while maintaining manual inline stabilization", "c": "Hyperextension of the neck without stabilization", "d": "Nasotracheal intubation by the EMR"},
         "b", "Jaw-thrust minimizes cervical motion when spinal injury is suspected.",
         {"a": "Head-tilt may worsen cervical injury.", "c": "Uncontrolled extension is unsafe.", "d": "EMRs do not perform advanced airway placement."}, "medium"),
        ("A patient with COPD receiving emergency oxygen via nonrebreather at 15 L/min becomes sleepy with shallow respirations. The EMR should:",
         {"a": "Continue 15 L/min because more oxygen is always better", "b": "Reassess ventilatory effort and follow local protocol for titrated oxygen in COPD", "c": "Remove all oxygen permanently", "d": "Place an OPA in a fully conscious patient without indication"},
         "b", "COPD patients may depend on hypoxic drive; titrate per protocol and monitor ventilatory status.",
         {"a": "Uncontrolled high-flow O2 can suppress drive in some COPD patients.", "c": "Hypoxemia may still need controlled oxygen.", "d": "OPA is not indicated in fully conscious patients."}, "hard"),
        ("Suctioning the oropharynx should generally be limited to:",
         {"a": "10 seconds with reoxygenation between attempts", "b": "Continuous suction until the catheter melts", "c": "60 seconds without interruption", "d": "Never suction trauma patients"},
         "a", "Brief suction passes reduce hypoxia risk; reoxygenate between attempts.",
         {"b": "Prolonged suction causes hypoxia.", "c": "60 seconds exceeds safe limits.", "d": "Suction may be needed in trauma with secretions/vomitus."}, "easy"),
        ("Which oxygen delivery device provides the highest FiO2 when fitted properly?",
         {"a": "Nasal cannula at 2 L/min", "b": "Simple face mask at 6 L/min", "c": "Nonrebreather mask with reservoir at adequate flow", "d": "Venturi mask set to 24%"},
         "c", "A nonrebreather with reservoir and sufficient flow can deliver high FiO2.",
         {"a": "Cannula delivers lower FiO2.", "b": "Simple mask is lower than nonrebreather.", "d": "Venturi delivers fixed lower concentrations."}, "easy"),
        ("An apneic adult patient after successful ROSC from CPR should receive:",
         {"a": "No oxygen because ROSC means normal oxygenation", "b": "Oxygen and ventilatory support per protocol with pulse oximetry monitoring", "c": "Only oral glucose", "d": "Immediate discharge from scene"},
         "b", "Post-ROSC patients often need oxygen and ventilatory support with close monitoring.",
         {"a": "Post-arrest patients are often hypoxic/hypercapnic.", "c": "Glucose is assessed separately.", "d": "Transport and continued care are required."}, "medium"),
        ("When using a pocket mask with a one-way valve, the EMR should:",
         {"a": "Deliver breaths over 1 second watching for chest rise", "b": "Blow as hard and fast as possible", "c": "Skip the valve to improve flow", "d": "Use only nasal prongs attached to the mask"},
         "a", "Pocket mask ventilations follow BLS guidelines: slow breaths with visible rise.",
         {"b": "Forceful rapid breaths increase gastric inflation.", "c": "The valve prevents backflow/contamination.", "d": "Pocket masks are for mouth-to-mask ventilation."}, "easy"),
        ("Signs of worsening upper airway swelling (e.g., anaphylaxis) include:",
         {"a": "Improving voice volume and disappearing wheeze", "b": "Progressive stridor, drooling, and difficulty swallowing", "c": "Stable oxygen saturation without exam changes", "d": "Only abdominal pain without respiratory signs"},
         "b", "Stridor, drooling, and dysphagia suggest impending complete airway obstruction.",
         {"a": "Improvement would not include stridor progression.", "c": "Exam may worsen before saturation drops.", "d": "Anaphylaxis often has respiratory compromise."}, "hard"),
    ])

    qs += pack(E, "trauma", [
        ("Direct pressure fails to control severe extremity bleeding. Your next step is:",
         {"a": "Remove the tourniquet and apply a bandage", "b": "Apply a tourniquet proximal to the wound and note the time applied", "c": "Elevate the leg and wait 30 minutes", "d": "Apply ice directly inside the wound"},
         "b", "Life-threatening extremity hemorrhage uncontrolled by pressure warrants tourniquet application with time documented.",
         {"a": "Do not remove an effective tourniquet in the field without medical direction.", "c": "Elevation alone may be insufficient for arterial bleeding.", "d": "Ice does not replace hemorrhage control."}, "medium"),
        ("A helmeted motorcycle rider is awake with stable vitals after a crash. Helmet removal should occur when:",
         {"a": "Never until hospital arrival regardless of airway or breathing", "b": "Airway compromise, vomiting, or inadequate breathing cannot be managed with helmet in place", "c": "Immediately for all helmeted patients on arrival", "d": "Only if the patient requests cosmetic adjustment"},
         "b", "Helmets remain if airway is manageable; remove when airway/breathing needs require it with spinal precautions.",
         {"a": "Airway needs may require removal.", "c": "Routine immediate removal increases motion if not indicated.", "d": "Clinical indications drive removal."}, "hard"),
        ("Which patient should be immobilized on a long backboard per typical EMR protocols?",
         {"a": "Stable alert patient who walked away without complaint", "b": "Mechanism suggesting spinal injury with midline tenderness or neurologic deficit", "c": "Any patient with a sprained finger", "d": "Patient refusing all care but fully neurologically intact without tenderness"},
         "b", "Spinal motion restriction is indicated with concerning mechanism plus exam findings.",
         {"a": "Low suspicion with normal exam may not require immobilization per local protocol.", "c": "Finger sprain alone does not indicate spinal injury.", "d": "Competent refusal may limit immobilization."}, "medium"),
        ("Signs of shock from hemorrhage include:",
         {"a": "Warm dry skin with bradycardia only", "b": "Pale cool clammy skin, tachycardia, and delayed capillary refill", "c": "Hypertension with bounding pulses only", "d": "Normal mental status with no vital sign changes"},
         "b", "Hypovolemic shock often presents with tachycardia, poor perfusion, and altered mental status.",
         {"a": "Shock typically causes cool skin and tachycardia.", "c": "Late shock may drop pressure; bounding pulses are not typical early.", "d": "Shock often alters vitals and mentation."}, "easy"),
        ("An open fracture of the forearm with active bleeding should be managed by:",
         {"a": "Pushing bone back into the wound before bandaging", "b": "Covering with sterile dressing, controlling bleeding, and splinting in position found", "c": "Tourniquet applied over the fracture site distal to injury", "d": "Heat packs over the wound"},
         "b", "Do not replace exposed bone; cover, control hemorrhage, immobilize, and transport.",
         {"a": "Replacing bone increases infection and tissue damage.", "c": "Tourniquet goes proximal to wound, not over it routinely.", "d": "Heat increases bleeding."}, "medium"),
        ("When splinting a painful swollen ankle, the EMR should:",
         {"a": "Splint in the position of comfort after neurovascular check", "b": "Force the foot into anatomical neutral despite severe pain", "c": "Remove the shoe and leave the joint unsupported", "d": "Apply heat before assessment"},
         "a", "Splinting in position found after CMS check reduces movement and pain.",
         {"b": "Forcing alignment can worsen injury.", "c": "Immobilization is indicated for suspected fracture/sprain.", "d": "Heat is not initial care for acute trauma."}, "easy"),
        ("A patient impaled by a metal rod through the abdomen should receive:",
         {"a": "Immediate removal of the object to bandage the hole", "b": "Stabilization of the object in place and rapid transport", "c": "Cutting the object flush without stabilization", "d": "Oral fluids to prevent dehydration only"},
         "b", "Impaled objects remain in place unless they block airway management per medical direction.",
         {"a": "Removal can cause uncontrolled hemorrhage.", "c": "Stabilize before cutting if shortening is needed for transport.", "d": "NPO status is typical for abdominal impalement."}, "medium"),
        ("Which burn should receive priority cooling and transport consideration?",
         {"a": "Small superficial burn on the palm without respiratory symptoms", "b": "Partial-thickness burn to circumferential chest with singed nasal hairs", "c": "Minor sunburn on the back", "d": "Healed old burn scar itching"},
         "b", "Circumferential chest burns and inhalation signs suggest airway/ventilation risk.",
         {"a": "Still needs care but lower priority than inhalation injury signs.", "c": "Sunburn rarely emergent unless extensive.", "d": "Old scar is not acute burn."}, "hard"),
        ("Tension pneumothorax signs may include:",
         {"a": "Tracheal deviation away from the affected side, absent breath sounds, and shock", "b": "Bilateral equal breath sounds with normal BP", "c": "Only isolated toe pain", "d": "Bradycardia with hypertension only"},
         "a", "Tension pneumothorax causes unilateral absent sounds, JVD, hypotension, and possible tracheal shift.",
         {"b": "Equal sounds argue against unilateral tension.", "c": "Toe pain is unrelated.", "d": "Shock usually tachycardic/hypotensive."}, "hard"),
        ("During manual inline stabilization, the EMR holding the head should:",
         {"a": "Release briefly to apply a cervical collar without coordination", "b": "Maintain alignment until collar and backboard immobilization are coordinated", "c": "Hyperextend the neck to open airway without team communication", "d": "Allow the patient to sit up for comfort"},
         "b", "Inline stabilization continues until an coordinated team applies collar/board.",
         {"a": "Uncoordinated release risks movement.", "c": "Airway maneuvers use jaw thrust with stabilization.", "d": "Sitting up breaks spinal precautions."}, "medium"),
        ("A patient with an amputated finger should have the part:",
         {"a": "Discarded at scene to prevent infection", "b": "Wrapped moist in sterile gauze, placed in waterproof bag on ice (not direct ice contact)", "c": "Submerged directly in ice water for hours", "d": "Heated to preserve tissue"},
         "b", "Amputated parts are kept cool and moist without direct ice contact for possible reattachment.",
         {"a": "Preserve when possible.", "c": "Direct ice damages tissue.", "d": "Heat destroys viability."}, "medium"),
        ("The primary purpose of the primary trauma survey (ABCDE) is to:",
         {"a": "Complete full patient history before any interventions", "b": "Identify and treat immediate life threats in sequence", "c": "Obtain insurance information first", "d": "Splint all injuries before airway assessment"},
         "b", "ABCDE prioritizes life threats: airway, breathing, circulation, disability, exposure.",
         {"a": "History follows stabilization.", "c": "Insurance is secondary.", "d": "Airway comes before detailed splinting."}, "easy"),
        ("A flail chest segment may cause:",
         {"a": "Paradoxical chest wall movement and respiratory distress", "b": "Improved lung expansion", "c": "Only cosmetic deformity without breathing impact", "d": "Bradycardia from improved oxygenation"},
         "a", "Multiple rib fractures create unstable segment with paradoxical motion and hypoventilation.",
         {"b": "Flail chest impairs ventilation.", "c": "Respiratory compromise is common.", "d": "Hypoxia tends to tachycardia."}, "medium"),
        ("When assessing pulse, motor, and sensation (CMS) distal to an injury, absent distal pulse after splinting means:",
         {"a": "Success; tighter splints improve pulses", "b": "Loosen/adjust splint and reassess; prepare for rapid transport", "c": "Ignore because pain is expected", "d": "Remove all bandages and leave limb dangling"},
         "b", "Loss of distal pulse after immobilization requires adjustment and urgent transport.",
         {"a": "Absent pulse is abnormal.", "c": "Vascular compromise needs action.", "d": "Unsupported limb worsens injury."}, "medium"),
        ("Scene size-up for trauma should include:",
         {"a": "BSI, scene safety, mechanism, number of patients, and need for additional resources", "b": "Only patient name and address", "c": "Skipping PPE to save time", "d": "Moving unstable patients before stabilizing life threats"},
         "a", "Standard scene approach emphasizes safety, BSI, MOI, and resource requests.",
         {"b": "Demographics come after safety and assessment.", "c": "PPE/BSI is mandatory.", "d": "Stabilize before movement when possible."}, "easy"),
    ])

    qs += pack(E, "medical", [
        ("You find an unresponsive adult without pulse. After activating EMS and getting an AED, you should:",
         {"a": "Start chest compressions at 100–120/min allowing full recoil", "b": "Wait for the AED before any compressions", "c": "Deliver breaths only without compressions", "d": "Check blood glucose for 5 minutes first"},
         "a", "BLS for adult cardiac arrest emphasizes immediate high-quality compressions and early AED.",
         {"b": "Compressions start while AED is retrieved unless unsafe.", "c": "Compressions are primary for witnessed adult arrest.", "d": "Do not delay CPR for routine glucose check."}, "easy"),
        ("FAST stroke assessment includes checking for:",
         {"a": "Facial droop, arm drift, speech difficulty, and time of onset", "b": "Fever, asthma, seizures, and trauma only", "c": "Foot pain and ankle swelling", "d": "Blood type and allergies only"},
         "a", "Face, Arms, Speech, Time helps identify stroke and urgency for transport.",
         {"b": "Not FAST components.", "c": "Unrelated to FAST.", "d": "History items, not FAST screen."}, "easy"),
        ("A diabetic patient is confused, diaphoretic, and tremulous with a glucose of 52 mg/dL. You should:",
         {"a": "Administer oral glucose if awake and able to swallow safely", "b": "Withhold all sugar even if swallowing is intact", "c": "Give only high-dose insulin", "d": "Place in Trendelenburg for head injury"},
         "a", "Conscious hypoglycemia with intact swallow gets fast-acting oral glucose per protocol.",
         {"b": "Oral glucose is first line when safe to swallow.", "c": "Insulin would worsen hypoglycemia.", "d": "Trendelenburg is not hypoglycemia treatment."}, "medium"),
        ("Anaphylaxis with wheeze and hypotension after bee sting requires:",
         {"a": "Epinephrine auto-injector per protocol and rapid transport", "b": "Antihistamine alone without transport", "c": "Waiting to see if hives fade", "d": "Cold packs only on the sting site"},
         "a", "Anaphylaxis is treated with IM epinephrine and urgent ALS/transport.",
         {"b": "Antihistamines are adjuncts, not sole therapy.", "c": "Systemic reaction can progress rapidly.", "d": "Local care does not treat systemic anaphylaxis."}, "medium"),
        ("A patient with crushing substernal chest pain and nitroglycerin prescribed should receive NTG only if:",
         {"a": "Systolic BP is adequate per protocol and patient has not taken PDE-5 inhibitor recently", "b": "Patient is hypotensive below 90 systolic", "c": "Patient took sildenafil within 24–48 hours per drug interaction rules", "d": "Pain is clearly from ankle sprain"},
         "b", "Nitroglycerin is contraindicated in hypotension and recent PDE-5 inhibitor use.",
         {"a": "Adequate BP and no recent PDE-5 use are required.", "c": "PDE-5 interaction risks severe hypotension.", "d": "Chest pain protocol applies to suspected cardiac pain."}, "hard"),
        ("Syncope with rapid recovery in a hot environment suggests:",
         {"a": "Heat-related illness; move to cool area and assess hydration/perfusion", "b": "Immediate surgical airway", "c": "Mandatory tourniquet application", "d": "No assessment needed if patient stands up"},
         "a", "Heat exhaustion/syncope needs cooling, rest, and assessment for worsening heat stroke.",
         {"b": "Airway is not first unless compromised.", "c": "No bleeding indication.", "d": "Recurrence and complications still possible."}, "easy"),
        ("Seizure activity has stopped and the patient is postictal but breathing adequately. You should:",
         {"a": "Place in recovery position, protect from injury, monitor airway, and time transport", "b": "Restrain all four limbs tightly during postictal state", "c": "Place objects in the mouth to prevent tongue biting", "d": "Withhold oxygen despite hypoxia"},
         "a", "Post-seizure care focuses on airway, protection, oxygen if needed, and evaluation.",
         {"b": "Restraint can cause injury; protect environment instead.", "c": "Nothing goes in the mouth during seizures.", "d": "Give oxygen if indicated."}, "medium"),
        ("Which vital sign pattern suggests decompensated shock in a medical patient?",
         {"a": "Heart rate 130, BP 86/60, cool skin, altered mental status", "b": "HR 72, BP 120/80, warm skin, alert", "c": "RR 12 calm with normal mentation only", "d": "Temp 98.6°F with no other findings"},
         "a", "Tachycardia, hypotension, poor perfusion, and AMS suggest shock.",
         {"b": "Normal vitals argue against shock.", "c": "Single normal RR insufficient.", "d": "Normal temp alone does not rule out shock."}, "medium"),
        ("A patient with asthma has silent chest and exhaustion. This indicates:",
         {"a": "Improving asthma ready for discharge", "b": "Impending respiratory failure requiring urgent transport and advanced care", "c": "Need for only antihistamine PO", "d": "No oxygen because CO2 retention never occurs"},
         "b", "Silent chest and fatigue are ominous signs of severe bronchospasm/respiratory failure.",
         {"a": "Silent chest is dangerous.", "c": "Severe asthma needs bronchodilator/advanced care.", "d": "Severe asthma may need controlled O2 and ventilatory support."}, "hard"),
        ("For suspected opioid overdose with respiratory depression, EMR care includes:",
         {"a": "Airway/ventilation support, naloxone per protocol, and transport", "b": "Stimulating only without ventilatory support", "c": "High-dose opioid to prevent withdrawal", "d": "Delayed transport until patient sleeps"},
         "a", "Opioid overdose management prioritizes ventilation and naloxone when authorized.",
         {"b": "Ventilation is critical if respirations are inadequate.", "c": "More opioid worsens overdose.", "d": "Somnolence with depressed respirations is emergent."}, "medium"),
        ("Chest pain patient with aspirin allergy and no contraindications otherwise: aspirin should be:",
         {"a": "Given if protocol allows after allergy assessment", "b": "Mandatory regardless of anaphylaxis history", "c": "Replaced with high-dose insulin", "d": "Withheld and patient left without transport"},
         "a", "True aspirin allergy contraindicates; otherwise chewable aspirin may be given per protocol.",
         {"b": "Anaphylaxis history is a contraindication.", "c": "Insulin is not chest pain treatment.", "d": "Transport still required."}, "medium"),
        ("A febrile patient with altered mental status and hot dry skin may have:",
         {"a": "Heat stroke requiring rapid cooling and transport", "b": "Simple viral cold only", "c": "Hypothermia", "d": "Normal variation requiring no action"},
         "a", "Heat stroke presents with CNS dysfunction and hot skin; it is life-threatening.",
         {"b": "Altered mental status suggests severity beyond cold.", "c": "Hypothermia involves low temperature.", "d": "Requires emergency care."}, "medium"),
        ("When assisting a prescribed epinephrine auto-injector, the injection site is typically:",
         {"a": "Outer mid-thigh (vastus lateralis)", "b": "Over the heart", "c": "Into a vein only", "d": "Into the buttock subcutaneously always"},
         "a", "Auto-injectors are administered IM in the anterolateral thigh.",
         {"b": "Not an appropriate IM site for epinephrine.", "c": "Auto-injectors are IM, not IV.", "d": "Thigh is preferred over buttock for absorption."}, "easy"),
        ("Priority for a patient with severe abdominal pain and rigid abdomen includes:",
         {"a": "Keep NPO, monitor vitals, position of comfort, rapid transport", "b": "Large meal to test tolerance", "c": "Aggressive oral hydration despite vomiting", "d": "Delay transport for home remedies"},
         "a", "Acute rigid abdomen may indicate surgical emergency; NPO and urgent transport are key.",
         {"b": "NPO is standard.", "c": "Oral intake may worsen some conditions.", "d": "Surgical abdomen needs evaluation."}, "medium"),
        ("Pulse oximetry reading 88% on room air in a symptomatic patient should prompt:",
         {"a": "Oxygen per protocol and reassessment of work of breathing", "b": "Ignore because oximetry is always wrong", "c": "Discharge without transport", "d": "Only document without intervention"},
         "a", "Hypoxemia with symptoms warrants supplemental oxygen and further assessment/transport.",
         {"b": "Low reading with symptoms needs action.", "c": "88% is abnormally low.", "d": "Intervention and transport typically indicated."}, "easy"),
    ])

    qs += pack(E, "ops", [
        ("Upon arrival at a motor vehicle collision, the EMR's first priority is:",
         {"a": "Patient care before any scene safety assessment", "b": "Determine scene safety and use appropriate PPE", "c": "Interview witnesses for legal statements only", "d": "Begin triage without notifying dispatch of hazards"},
         "b", "Scene safety and BSI precede patient contact per standard EMS operations.",
         {"a": "Unsafe scenes endanger responders and patients.", "c": "Witnesses are secondary to safety and care.", "d": "Communicate hazards and request resources."}, "easy"),
        ("A competent adult refuses transport after assessment. The EMR should:",
         {"a": "Force transport against will", "b": "Explain risks, ensure understanding, document refusal, and leave contact/return instructions per protocol", "c": "Destroy all documentation to avoid liability", "d": "Threaten arrest for refusal"},
         "b", "Informed refusal requires capacity assessment, risk explanation, documentation, and medical control if needed.",
         {"a": "Forcing transport violates autonomy absent exigent circumstances.", "c": "Documentation protects patient and provider.", "d": "Refusal is not automatically illegal."}, "medium"),
        ("Protected health information (PHI) on a PCR may be shared with:",
         {"a": "Anyone on social media for education", "b": "Receiving facility and authorized personnel involved in patient care", "c": "Media without consent", "d": "Curious bystanders for updates"},
         "b", "HIPAA permits disclosure for treatment, payment, and healthcare operations on need-to-know basis.",
         {"a": "Social media disclosure violates privacy.", "c": "Media requires authorization/legal exception.", "d": "Bystanders are not entitled to PHI."}, "easy"),
        ("Standard precautions require:",
         {"a": "Gloves and hand hygiene at minimum when contact with blood/body fluids is possible", "b": "No PPE if patient looks clean", "c": "Reuse gloves between patients without cleaning", "d": "Only airborne precautions for all calls"},
         "a", "Standard precautions treat all blood/body fluids as potentially infectious.",
         {"b": "Infection risk is not visible.", "c": "Gloves are single patient use.", "d": "Standard precautions apply broadly; airborne is specific."}, "easy"),
        ("When requesting additional resources, the EMR should provide:",
         {"a": "Location, nature of incident, hazards, number of patients, and resources needed", "b": "Only patient favorite color", "c": "Personal opinions about fault", "d": "Delayed notification until all care finished without updates"},
         "a", "Clear concise radio/reporting includes location, problem, hazards, and resource needs.",
         {"b": "Irrelevant to resource allocation.", "c": "Fault determination is not dispatch priority.", "d": "Update dispatch as situation evolves."}, "easy"),
        ("Medical direction may be required for:",
         {"a": "Certain medications, protocols outside standing orders, or complex refusals per local policy", "b": "Every bandage application universally", "c": "Opening the ambulance door", "d": "Hand washing"},
         "a", "Online/offline medical control governs extensions beyond standing orders and some refusals.",
         {"b": "Basic first aid often under standing orders.", "c": "Not a medical direction issue.", "d": "Infection control standard, not MD order."}, "medium"),
        ("At a hazardous materials incident, the EMR should:",
         {"a": "Enter the hot zone to retrieve victims without training", "b": "Recognize hazard, protect self, deny entry, and request hazmat specialists", "c": "Mix unknown chemicals to neutralize them", "d": "Ignore wind direction"},
         "b", "Hazmat scenes require recognition, isolation, and specialist response beyond EMR scope.",
         {"a": "Untrained entry increases casualties.", "c": "Mixing chemicals is dangerous.", "d": "Wind/uphill/upstream positioning matters."}, "medium"),
        ("Documentation on the PCR should be:",
         {"a": "Objective, timely, and include assessment findings, interventions, and patient responses", "b": "Filled with abbreviations only you understand years later", "c": "Altered after legal review to look better", "d": "Omitted when patient refuses care"},
         "a", "Accurate objective documentation supports continuity of care and legal record.",
         {"b": "Unclear abbreviations harm communication.", "c": "Altering records is fraudulent.", "d": "Refusals must be documented."}, "easy"),
        ("During mass casualty triage, a patient with absent respirations after airway opening may be classified:",
         {"a": "Immediate (red) always regardless of resources", "b": "Expectant/black in many triage systems when resources are limited and no spontaneous respirations after opening airway", "c": "Minor/green", "d": "Delayed/yellow solely for ankle sprain"},
         "b", "START and similar systems tag non-breathing after airway maneuver as expectant when resources constrained.",
         {"a": "Without respirations after maneuver, immediate lifesaving may be futile at MCI.", "c": "Green is walking wounded.", "d": "Ankle sprain alone is not the scenario."}, "hard"),
        ("Consent for treatment of an unconscious adult is generally:",
         {"a": "Implied consent for emergency care", "b": "Never possible", "c": "Requires written contract signed while unconscious", "d": "Only from police at scene"},
         "a", "Implied consent allows emergency treatment when patient cannot consent and delay would harm.",
         {"b": "Emergency exceptions exist.", "c": "Written consent impractical in emergencies.", "d": "Police do not substitute for medical consent rules."}, "easy"),
        ("An EMR discovers possible child abuse during a call. Appropriate action includes:",
         {"a": "Report per local mandatory reporting laws and ensure child safety", "b": "Ignore unless parent admits guilt", "c": "Confront alleged abuser violently", "d": "Delete findings from PCR"},
         "a", "Mandatory reporters must notify appropriate authorities and document objective findings.",
         {"b": "Suspicion triggers reporting duty.", "c": "Violence is inappropriate.", "d": "Concealing findings is illegal/unethical."}, "medium"),
        ("Vehicle staging at a violent scene should be:",
         {"a": "Upwind/uphill at a safe distance until law enforcement secures scene when indicated", "b": "Inside the active shooter hot zone", "c": "Blocking all egress for other units unnecessarily", "d": "With lights/sirens off only after leaving jurisdiction"},
         "a", "Staging protects crews until scene is safe or escorted by law enforcement.",
         {"b": "Hot zones are unsafe without tactical coordination.", "c": "Do not impede other emergency vehicles.", "d": "Staging decisions are scene-specific."}, "medium"),
        ("After patient transfer to ALS, the EMR should:",
         {"a": "Provide concise verbal report and complete PCR including times and interventions", "b": "Leave without communication", "c": "Withhold allergy information", "d": "Discard all equipment without restocking documentation"},
         "a", "Handoff communication and complete documentation ensure continuity of care.",
         {"b": "Report is essential.", "c": "Allergies are critical handoff data.", "d": "Equipment/restocking follows service policy."}, "easy"),
        ("Which action violates ethical boundaries?",
         {"a": "Accepting a large cash gift from a patient for preferential future response", "b": "Maintaining professional demeanor", "c": "Respecting cultural preferences when safe", "d": "Declining to work while impaired"},
         "a", "Accepting gifts for preferential treatment creates conflict of interest and unethical conduct.",
         {"b": "Professionalism is expected.", "c": "Cultural respect within safety limits is appropriate.", "d": "Impaired practice is prohibited."}, "medium"),
        ("When terminating resuscitation in the field is considered (per protocol/medical direction), factors include:",
         {"a": "Downtime without ROSC, unsafe scene, valid DNR, and medical direction criteria", "b": "Responder fatigue alone without protocol", "c": "Patient shoe brand", "d": "Bystander request only without medical criteria"},
         "a", "Termination follows protocol/medical direction considering downtime, DNR, scene safety, and futility criteria.",
         {"b": "Fatigue alone is insufficient.", "c": "Irrelevant.", "d": "Medical/legal criteria govern termination."}, "hard"),
    ])

    assert len(qs) == 60
    return qs


if __name__ == "__main__":
    from _common import write_bank
    write_bank("nremt-emr-readiness-check", build())
