#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "pharmacy-technician-excpt-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "orders", [
        ("A new prescription for a controlled substance must include which element?",
         {"a": "Patient's favorite pharmacy only", "b": "Prescriber signature (electronic or wet) and DEA number when required", "c": "Technician's personal DEA number", "d": "Cash payment receipt number"},
         "b", "Valid controlled-substance prescriptions require prescriber authentication and DEA number per federal/state rules.",
         {"a": "Pharmacy preference is not a legal element.", "c": "Technicians do not have prescriber DEA numbers.", "d": "Payment receipt is not a prescription element."}, "easy"),
        ("The pharmacy receives a faxed prescription for a non-controlled drug from a known prescriber. The technician should:",
         {"a": "Dispense immediately without verification", "b": "Verify prescriber authenticity per state law and pharmacy policy before filling", "c": "Change the strength to match inventory", "d": "Add refills without prescriber authorization"},
         "b", "Faxed/electronic orders require verification of validity and prescriber authorization per state rules.",
         {"a": "Verification is required.", "c": "Changing strength is illegal without new Rx.", "d": "Refills require authorization."}, "medium"),
        ("A patient requests an early refill of a Schedule III medication. The technician should:",
         {"a": "Fill early without question", "b": "Review refill date, check state/federal early refill rules, and consult pharmacist if outside allowed window", "c": "Transfer to another state to avoid rules", "d": "Refuse all Schedule III refills permanently"},
         "b", "Controlled refills follow legal limits; pharmacist review is needed for early fills outside permitted exceptions.",
         {"a": "Early fills may violate federal/state law.", "c": "Transfer does not bypass refill rules.", "d": "Schedule III may have refills if authorized."}, "medium"),
        ("Which information is essential on a prescription label before dispensing?",
         {"a": "Patient name, drug name/strength, directions, prescriber, pharmacy contact, and Rx number", "b": "Technician home address", "c": "Prescriber's vacation plans", "d": "Insurance CEO name only"},
         "a", "Labeling must include patient identification, drug, directions, and pharmacy/prescriber identifiers per regulations.",
         {"b": "Not required on label.", "c": "Irrelevant.", "d": "Not a labeling element."}, "easy"),
        ("A prescriber calls in an emergency oral prescription for a non-controlled drug. The technician should:",
         {"a": "Document per state rules and ensure pharmacist receives/reduces to writing as required", "b": "Refuse all phone orders", "c": "Allow the technician alone to authorize unlimited refills", "d": "Skip patient allergy check"},
         "b", "Phone-in emergencies are permitted for some drugs with documentation and pharmacist involvement per state law.",
         {"a": "Many states allow phone orders with restrictions.", "c": "Refills still need authorization.", "d": "Allergy review is mandatory."}, "medium"),
        ("When transferring a prescription to another pharmacy, the technician must:",
         {"a": "Give the original paper Rx to the patient to carry if controlled (generally not permitted)", "b": "Process transfer per state law, document one-time transfer information, and void balance if applicable", "c": "Transfer without documenting refills remaining", "d": "Transfer forged prescriptions to dispose of them"},
         "b", "Transfers require communication between pharmacies, documentation of fills/refills remaining, and legal handling of controlled records.",
         {"a": "Controlled Rxs usually transfer via pharmacy-to-pharmacy communication.", "c": "Refills remaining must be tracked.", "d": "Forged Rxs are reported, not transferred."}, "hard"),
        ("A duplicate therapy alert shows two ACE inhibitors on the same profile. The technician should:",
         {"a": "Silence the alert and dispense both", "b": "Notify the pharmacist for clinical review before dispensing", "c": "Delete one medication from profile without documentation", "d": "Change one drug to OTC without approval"},
         "b", "Clinical alerts require pharmacist evaluation; technicians do not resolve therapeutic duplication independently.",
         {"a": "Duplicate therapy may harm the patient.", "c": "Profile changes need proper workflow.", "d": "Rx-to-OTC switches need prescriber/pharmacist action."}, "medium"),
        ("The day supply for '1 tablet PO daily' of a 30-tablet quantity is:",
         {"a": "30 days", "b": "7 days", "c": "90 days", "d": "1 day"},
         "a", "One tablet daily from 30 tablets equals 30-day supply.",
         {"b": "Weekly supply would be 7 tablets.", "c": "90 days would need 90 tablets.", "d": "One tablet lasts one day, but quantity covers 30 days."}, "easy"),
        ("A patient brings a prescription written for 'Coumadin 5 mg' but the prescriber intended generic warfarin. The technician should:",
         {"a": "Substitute generic if state law permits and profile allows; otherwise contact prescriber", "b": "Dispense aspirin instead", "c": "Change dose to 10 mg for convenience", "d": "Discard Rx without pharmacist knowledge"},
         "a", "Generic substitution follows state law, DAW codes, and pharmacist approval; warfarin has brand/generic considerations.",
         {"b": "Different drug class.", "c": "Dose changes need prescriber.", "d": "Proper workflow required."}, "medium"),
        ("Prior authorization is pending for a brand-only drug. The technician should:",
         {"a": "Bill insurance anyway without PA", "b": "Inform patient/pharmacist, explore covered alternatives, and follow PA workflow", "c": "Give drug free without documentation", "d": "Cancel patient profile permanently"},
         "b", "PA status affects dispensing/billing; communicate options and follow third-party rules.",
         {"a": "Claim may reject without PA.", "c": "Free goods need policy/compliance.", "d": "Profile remains active."}, "medium"),
        ("An e-prescription with 'Dispense as written' (DAW 1) means:",
         {"a": "Mandatory generic substitution", "b": "Dispense the brand product as written; generic substitution not permitted unless prescriber changes", "c": "Patient chooses any product", "d": "Technician selects cheapest item regardless"},
         "b", "DAW 1 indicates prescriber requires brand as written.",
         {"a": "DAW 0 or blank often allows substitution where legal.", "c": "Prescriber/product specified.", "d": "Substitution rules follow DAW and law."}, "hard"),
        ("When entering directions '2 tsp PO QID PRN pain,' the technician should:",
         {"a": "Translate accurately using standard abbreviations/sigs per pharmacy policy and verify with pharmacist if unclear", "b": "Change to 'take all at once daily'", "c": "Omit PRN because it complicates billing", "d": "Leave directions blank"},
         "a", "Accurate sig translation ensures safe use; unclear orders need pharmacist clarification.",
         {"b": "Altering directions is unsafe/illegal.", "c": "PRN is clinically important.", "d": "Directions are required."}, "easy"),
        ("A prescription expiration date for a non-controlled drug is typically governed by:",
         {"a": "State law and time from issue date (often 6–12 months)", "b": "Technician birthday", "c": "Forever if patient wants it", "d": "Only the color of ink used"},
         "a", "Non-controlled prescriptions expire per state rules, commonly within one year of writing.",
         {"b": "Irrelevant.", "c": "Expired Rxs cannot be filled legally.", "d": "Ink color does not set expiration."}, "easy"),
        ("The technician notices the prescriber's NPI is missing on a third-party claim. Best action:",
         {"a": "Proceed without prescriber ID", "b": "Obtain valid prescriber NPI/ID required by payer before billing", "c": "Use a random NPI", "d": "Bill as OTC always"},
         "b", "Claims require valid prescriber identifiers; fictitious IDs constitute fraud.",
         {"a": "Claim will reject or fail audit.", "c": "Fraudulent.", "d": "Rx drugs are not OTC."}, "medium"),
        ("A patient requests partial fill of a Schedule II prescription. The technician should:",
         {"a": "Partial fill per federal/state rules with pharmacist approval and documentation", "b": "Partial fill anytime without documentation", "c": "Add refills to Schedule II", "d": "Split one Rx into multiple unauthorized new Rxs"},
         "a", "Schedule II partial fills are tightly regulated with specific documentation and time limits.",
         {"b": "Documentation and rules apply.", "c": "Schedule II generally has no refills.", "d": "Creating unauthorized Rxs is illegal."}, "hard"),
    ])

    qs += pack(E, "inventory", [
        ("When receiving a drug shipment, the technician should first:",
         {"a": "Stock shelves without checking invoice", "b": "Verify shipment against purchase order/invoice, check for damage, and confirm lot/expiry", "c": "Discard outer packaging before counting", "d": "Store controlled substances on open counter"},
         "b", "Receiving requires matching order, inspecting condition, and recording lot/expiration for traceability.",
         {"a": "Verification prevents errors and shortages.", "c": "Packaging may contain lot info needed.", "d": "Controlled drugs require secure storage."}, "easy"),
        ("FIFO (first-in, first-out) inventory rotation means:",
         {"a": "Use oldest acceptable stock with nearest expiration first", "b": "Always use newest stock and discard older", "c": "Random selection from shelf", "d": "Store all drugs at room temperature regardless of label"},
         "a", "FIFO reduces waste and expired product dispensing.",
         {"b": "Older stock would expire unused.", "c": "Random rotation risks expired drugs.", "d": "Storage follows label/requirements."}, "easy"),
        ("A drug recall notification identifies lot ABC123. The technician should:",
         {"a": "Ignore if only one bottle affected", "b": "Quarantine affected lot, notify pharmacist, check stock/patient records per recall class", "c": "Sell recalled lot at discount", "d": "Move lot to front shelf for faster sale"},
         "b", "Recalls require quarantine, identification of affected inventory/dispensed product, and follow-up per FDA/class.",
         {"a": "Even one bottle may be dispensed to patients.", "c": "Recalled product must not be sold.", "d": "Opposite of quarantine."}, "medium"),
        ("Minimum/maximum (min/max) inventory levels help the pharmacy:",
         {"a": "Maintain adequate stock without excessive carrying cost or outages", "b": "Eliminate all ordering", "c": "Hide shrinkage", "d": "Avoid counting forever"},
         "a", "Min/max systems trigger ordering before stockouts while limiting overstock.",
         {"b": "Ordering still occurs at thresholds.", "c": "Inventory controls detect shrinkage.", "d": "Periodic counts still required."}, "easy"),
        ("Temperature-sensitive vaccines arriving warm should be:",
         {"a": "Frozen immediately without protocol", "b": "Segregated, documented, and referred to pharmacist/manufacturer guidance; likely not dispensed", "c": "Dispensed quickly before they spoil more", "d": "Mixed with room-temp stock"},
         "b", "Cold chain breaks require quarantine and assessment; compromised vaccines may need discard.",
         {"a": "Freezing may ruin refrigerated vaccines.", "c": "Potency may be unknown.", "d": "Segregation prevents cross-contamination."}, "medium"),
        ("Cycle counts are performed to:",
         {"a": "Reconcile physical inventory with computer records on a scheduled basis", "b": "Replace annual inventory entirely in all states", "c": "Skip controlled substance accountability", "d": "Increase discrepancies intentionally"},
         "a", "Cycle counting identifies discrepancies early and supports accurate perpetual inventory.",
         {"b": "Full inventories may still be required.", "c": "Controlled drugs need strict accountability.", "d": "Discrepancies trigger investigation."}, "medium"),
        ("A generic is therapeutically equivalent when FDA assigns:",
         {"a": "AB rating for generic substitution in many cases", "b": "No rating ever", "c": "Only cosmetic color rating", "d": "Technician initials"},
         "a", "FDA therapeutic equivalence codes (e.g., AB) guide generic substitution eligibility.",
         {"b": "Ratings exist in Orange Book.", "c": "Not the equivalence system.", "d": "Not an FDA code."}, "hard"),
        ("Short-dated product received with 30 days until expiration should typically be:",
         {"a": "Accepted without note if cheaper", "b": "Evaluated against turnover; return or use quickly per policy to avoid waste", "c": "Hidden behind newer stock indefinitely", "d": "Given to patients without disclosure"},
         "b", "Short dating increases expiration risk; policy may require return or prioritized dispensing.",
         {"a": "Cost does not override expiry risk.", "c": "FIFO prevents hiding short dates.", "d": "Patients may need counseling on dating."}, "medium"),
        ("Perpetual inventory for controlled substances requires:",
         {"a": "Running balance updated with each receipt and dispense", "b": "Annual guess of quantities", "c": "No records if pharmacist is present", "d": "Shared log without individual identification"},
         "a", "Controlled substance records maintain continuous accurate balances and audit trail.",
         {"b": "Continuous records are federal requirement.", "c": "Records always required.", "d": "Accountability identifies responsible personnel."}, "medium"),
        ("Damaged in-house stock (crushed tablets) should be:",
         {"a": "Dispensed at half price", "b": "Documented and disposed/returned per policy and DEA/state rules if controlled", "c": "Repackaged without label change", "d": "Sent home with staff"},
         "b", "Damaged drugs are quarantined and disposed/returned with proper documentation.",
         {"a": "Damaged drugs must not be dispensed.", "c": "Repackaging requires compliance.", "d": "Diversion risk."}, "easy"),
        ("Ordering via primary wholesaler outage should prompt:",
         {"a": "Secondary vendor ordering per contract and pharmacist approval", "b": "Buying from unlicensed online sellers without verification", "c": "Compounding commercial product without license", "d": "Borrowing patient medications"},
         "a", "Secondary suppliers must be licensed; pharmacist oversees purchasing decisions.",
         {"b": "Unverified sources risk counterfeit product.", "c": "Compounding has strict scope limits.", "d": "Patient meds cannot be re-dispensed."}, "medium"),
        ("The technician finds a 10-unit discrepancy in a C-II perpetual count. Next step:",
         {"a": "Adjust count silently", "b": "Notify pharmacist immediately and begin discrepancy investigation per policy", "c": "Order 10 extra units to hide error", "d": "Wait until next year"},
         "b", "Controlled discrepancies require immediate pharmacist notification and documented investigation.",
         {"a": "Silent adjustment violates law.", "c": "Covering up is diversion/fraud risk.", "d": "Immediate action required."}, "hard"),
        ("Hazardous drug (e.g., oral cyclophosphamide) storage may require:",
         {"a": "Segregation and labeling per USP <800> pharmacy practices", "b": "Open bowl on counter", "c": "Food refrigerator shared with lunches", "d": "No PPE ever for staff"},
         "a", "HDs require designated storage, labeling, and handling to reduce exposure.",
         {"b": "Open storage increases exposure.", "c": "Food fridges are inappropriate.", "d": "PPE/handling per HD level."}, "hard"),
        ("Return-to-stock of unopened dispensed product is allowed when:",
         {"a": "Pharmacy policy, state law, and integrity/sealed conditions are met with pharmacist approval", "b": "Always after any patient touch", "c": "Never under any circumstance universally", "d": "Patient returns half-used inhaler"},
         "b", "RTS is restricted to unopened/unused product per policy; used partials generally cannot return.",
         {"a": "Patient contact often prohibits RTS.", "c": "Some sealed returns allowed.", "d": "Partial use cannot RTS."}, "medium"),
        ("Automated dispensing cabinet (ADC) restocking should include:",
         {"a": "Verification of drug, strength, lot, expiry, and location scan per policy", "b": "Loading any similar-looking bottle", "c": "Skipping barcode scan to save time", "d": "Leaving expired meds in ADC"},
         "a", "ADC restock requires barcode verification and expiry checks to prevent wrong-pocket errors.",
         {"b": "Look-alike errors are common.", "c": "Scanning is safety step.", "d": "Expired drugs must be removed."}, "easy"),
    ])

    qs += pack(E, "safety", [
        ("Look-alike/sound-alike (LASA) errors are best prevented by:",
         {"a": "Tall-man lettering, separate storage, and independent double-checks", "b": "Storing hydralazine and hydroxyzine adjacent without labels", "c": "Rushing during peak hours", "d": "Disabling barcode scanning"},
         "a", "LASA strategies include tall-man letters, shelf separation, and verification steps.",
         {"b": "Adjacent storage increases errors.", "c": "Rushing increases errors.", "d": "Barcodes reduce wrong drug errors."}, "easy"),
        ("When compounding a non-sterile suspension, the technician should:",
         {"a": "Follow master formula, use calibrated equipment, label beyond-use date, and document", "b": "Estimate ingredients by eye", "c": "Omit beyond-use dating", "d": "Skip cleaning to save time"},
         "a", "Non-sterile compounding requires formula adherence, accurate measurement, BUD, and documentation.",
         {"b": "Estimation causes potency errors.", "c": "BUD is required.", "d": "Cleaning prevents cross-contamination."}, "medium"),
        ("A patient reports hives after taking amoxicillin dispensed today. The technician should:",
         {"a": "Tell patient to take another dose", "b": "Alert pharmacist immediately, document, and initiate adverse event workflow", "c": "Delete allergy from profile", "d": "Recommend higher dose"},
         "b", "Suspected allergic reaction requires pharmacist assessment, documentation, and possible reporting.",
         {"a": "Re-dosing is dangerous.", "c": "Allergy should be added, not removed.", "d": "Higher dose worsens reaction."}, "easy"),
        ("High-alert medications such as insulin require:",
         {"a": "Independent double-check of drug, dose, and patient before dispensing", "b": "No verification if busy", "c": "Storage with OTC vitamins only", "d": "Removal of strength from label"},
         "a", "ISMP high-alert meds need additional verification to prevent harm.",
         {"b": "Busy periods need more vigilance.", "c": "Insulin needs secure appropriate storage.", "d": "Strength must be clear on label."}, "medium"),
        ("Cleaning the laminar airflow hood before sterile compounding includes:",
         {"a": "Disinfecting work surface with appropriate agent per USP <797> schedule before session", "b": "Using household furniture polish", "c": "Compounding first then cleaning never", "d": "Leaving prior day's supplies uncapped overnight routinely"},
         "a", "ISO-classified spaces require scheduled disinfection before compounding sessions.",
         {"b": "Non-pharmacy cleaners may leave residues.", "c": "Cleaning precedes compounding.", "d": "Open containers increase contamination."}, "hard"),
        ("A near-miss where wrong strength was caught at verification should be:",
         {"a": "Ignored because no patient harm", "b": "Documented in internal quality system to prevent recurrence", "c": "Hidden to protect technician", "d": "Posted publicly with patient name"},
         "b", "Near-miss reporting drives process improvement and is standard quality practice.",
         {"a": "Near misses reveal system weaknesses.", "c": "Quality systems are non-punitive for reporting.", "d": "HIPAA prohibits public PHI."}, "medium"),
        ("Pediatric liquid dosing should be measured with:",
         {"a": "Oral syringe calibrated in mL, not household teaspoons alone", "b": "Kitchen tablespoon", "c": "Parent guess", "d": "IV bag without labeling"},
         "a", "Oral syringes in milliliters provide accurate pediatric dosing per best practice.",
         {"b": "Household spoons vary in size.", "c": "Guessing is unsafe.", "d": "Wrong device and labeling."}, "easy"),
        ("Chemotherapy spill in pharmacy requires:",
         {"a": "Spill kit, PPE, ventilation considerations, and trained personnel per HD protocol", "b": "Mop with bare hands quickly", "c": "Ignore small spills", "d": "Continue compounding in spill area"},
         "a", "HD spills need designated kits, PPE, and decontamination procedures.",
         {"b": "Bare-hand contact risks exposure.", "c": "All spills need response.", "d": "Area must be decontaminated first."}, "hard"),
        ("The technician is asked to counsel on a new complex medication. Appropriate response:",
         {"a": "Refer patient to pharmacist for counseling", "b": "Provide detailed clinical counseling beyond scope", "c": "Refuse to notify pharmacist", "d": "Guess about off-label uses"},
         "a", "Clinical counseling is pharmacist duty; technicians may provide administrative info per state law.",
         {"b": "Clinical counseling exceeds technician scope.", "c": "Pharmacist must counsel when required.", "d": "Off-label advice is pharmacist/clinician role."}, "easy"),
        ("Barcode scanning at dispensing primarily prevents:",
         {"a": "Wrong drug/strength/form dispensed to wrong patient", "b": "All drug interactions automatically without pharmacist", "c": "Need for labels", "d": "Insurance billing entirely"},
         "a", "Bar-code assisted dispensing verifies product against Rx and patient record.",
         {"b": "Interactions still need pharmacist review.", "c": "Labels still required.", "d": "Billing is separate workflow."}, "easy"),
        ("Beyond-use date (BUD) on repackaged amber vials is determined by:",
         {"a": "Stability data, USP standards, and pharmacy policy", "b": "Technician preference only", "c": "Manufacturer expiry of source container always equals BUD without assessment", "d": "Infinite if refrigerated visually"},
         "a", "BUD considers USP chapters, stability, and cannot exceed manufacturer dating without data.",
         {"b": "Policy/data driven.", "c": "Repackaging often shortens BUD.", "d": "BUD is finite."}, "hard"),
        ("When a patient cannot swallow tablets and prescriber approves crushing, the technician should:",
         {"a": "Confirm drug is safe to crush (not ER/chemo/certain capsules) with pharmacist", "b": "Crush all extended-release products", "c": "Crush enteric-coated tablets always", "d": "Crush without prescriber approval"},
         "a", "Many formulations must not be crushed; pharmacist confirms safety and alternatives.",
         {"b": "Crushing ER causes dose dumping.", "c": "Enteric coating destruction irritates stomach/reduces efficacy.", "d": "Prescriber approval needed for alteration."}, "medium"),
        ("Fire extinguisher PASS technique stands for:",
         {"a": "Pull, Aim, Squeeze, Sweep", "b": "Push, Attack, Spray, Stop", "c": "Pause, Ask, Skip, Save", "d": "Pull, Analyse, Store, Sell"},
         "a", "Standard fire extinguisher use: Pull pin, Aim at base, Squeeze handle, Sweep side to side.",
         {"b": "Incorrect acronym.", "c": "Incorrect.", "d": "Incorrect."}, "easy"),
        ("A medication error reaches the patient but causes no apparent harm. Required action includes:",
         {"a": "Internal report, pharmacist notification, patient communication, and possible external reporting per policy", "b": "No documentation to avoid liability", "c": "Only fix next time silently", "d": "Blame patient for not checking"},
         "a", "Errors require disclosure per policy, documentation, and quality improvement even without harm.",
         {"b": "Non-reporting violates policy/law.", "c": "Silent fixes fail to improve systems.", "d": "Providers are accountable."}, "medium"),
        ("Proper hand hygiene in pharmacy requires:",
         {"a": "Washing/sanitizing before compounding, after gloves, and after contamination", "b": "Gloves replace all hand hygiene", "c": "Only at end of shift", "d": "Never after handling money then touching stock"},
         "a", "Hand hygiene is required before/after patient contact, compounding, and contamination events.",
         {"b": "Gloves do not replace hand hygiene.", "c": "Multiple times per shift.", "d": "Contamination requires hand hygiene."}, "easy"),
    ])

    qs += pack(E, "law", [
        ("Schedule II controlled substances generally:",
         {"a": "Allow unlimited refills", "b": "Require original prescription (with e-Rx exceptions) and have no refills unless partial fill rules apply", "c": "May be dispensed without prescription", "d": "Are OTC in all states"},
         "b", "Federal rules limit Schedule II: no refills, strict prescription requirements.",
         {"a": "No refills except partial fill provisions.", "c": "Prescription required.", "d": "Not OTC."}, "easy"),
        ("HIPAA allows pharmacy staff to discuss PHI with:",
         {"a": "Patient's authorized caregiver/designee when documented and necessary for care", "b": "Any neighbor asking at pickup", "c": "Social media followers", "d": "Employer of technician without patient permission always"},
         "a", "Minimum necessary PHI disclosure to those involved in care or with patient authorization.",
         {"b": "Unauthorized disclosure violates HIPAA.", "c": "Social media disclosure prohibited.", "d": "Employer access requires authorization/need."}, "medium"),
        ("A forged prescription is suspected. The technician should:",
         {"a": "Fill it quickly to avoid confrontation", "b": "Notify pharmacist, refuse fill, document, and contact authorities per policy", "c": "Charge higher copay", "d": "Give partial controlled amount as compromise"},
         "b", "Suspected forgery requires refusal, documentation, and possible law enforcement notification.",
         {"a": "Dispensing forged Rx is illegal.", "c": "Copay irrelevant.", "d": "Partial dispensing still illegal."}, "medium"),
        ("The Omnibus Budget Reconciliation Act (OBRA '90) requires pharmacists to:",
         {"a": "Offer to counsel Medicaid patients on new prescriptions (technician supports workflow)", "b": "Eliminate all counseling", "c": "Dispense without patient profiles", "d": "Prohibit generic substitution nationwide"},
         "a", "OBRA mandates Medicaid counseling offers and patient profile reviews by pharmacists.",
         {"b": "Opposite of OBRA.", "c": "Profiles required.", "d": "Generics allowed where law permits."}, "medium"),
        ("Technician scope of practice is defined by:",
         {"a": "State board of pharmacy regulations and supervising pharmacist", "b": "Personal preference only", "c": "Store manager without pharmacy license", "d": "Patient vote"},
         "a", "Scope varies by state; pharmacist supervises and delegates permitted tasks.",
         {"b": "Law defines scope.", "c": "Pharmacist oversight required.", "d": "Not patient determined."}, "easy"),
        ("Selling pseudoephedrine products requires:",
         {"a": "Compliance with federal/state log limits, ID, and quantity restrictions", "b": "No ID ever", "c": "Unlimited bulk sales to one person daily", "d": "Prescription always in all states"},
         "a", "Combat Meth Act and state laws regulate PSE sales with logging and limits.",
         {"b": "ID/logging required.", "c": "Daily limits apply.", "d": "OTC with restrictions in most states."}, "medium"),
        ("Pharmacy technicians may not:",
         {"a": "Perform final clinical verification independently where prohibited by state law", "b": "Accept prescriptions from patients", "c": "Operate cash register in all states", "d": "Restock OTC shelves where allowed"},
         "a", "Final verification/clinical check is pharmacist responsibility in most jurisdictions.",
         {"b": "Intake is commonly permitted.", "c": "Register tasks often allowed.", "d": "Restock often allowed."}, "easy"),
        ("DEA Form 222 (or CSOS electronic order) is used for:",
         {"a": "Ordering Schedule I and II controlled substances from suppliers", "b": "Ordering OTC vitamins only", "c": "Patient insurance claims", "d": "Vacation requests"},
         "a", "C-I and C-II wholesale orders require DEA order forms or CSOS.",
         {"b": "OTC not controlled.", "c": "Billing form different.", "d": "Not HR form."}, "hard"),
        ("A confidential patient question at the counter should be handled by:",
         {"a": "Moving to private counseling area and lowering voice/minimum necessary disclosure", "b": "Answering loudly so line hears", "c": "Posting answer on public screen with full name", "d": "Refusing all privacy"},
         "a", "HIPAA and professionalism require reasonable privacy for PHI discussions.",
         {"b": "Public disclosure violates privacy.", "c": "Public PHI display prohibited.", "d": "Privacy must be offered."}, "easy"),
        ("Expired controlled substances must be:",
         {"a": "Disposed through authorized reverse distributor or DEA take-back per regulations", "b": "Flushed in toilet always", "c": "Given to employees", "d": "Sold as discount"},
         "a", "Controlled disposal follows DEA/disposal rules; sewer disposal generally prohibited.",
         {"b": "Flushing restricted for many drugs environmentally.", "c": "Diversion risk.", "d": "Illegal sale."}, "medium"),
        ("Reporting suspected diversion by a coworker is:",
         {"a": "Ethical/legal obligation to notify pharmacist/owner and possibly board/DEA", "b": "Optional gossip only", "c": "Protected if ignored", "d": "Always fireable offense for reporter universally"},
         "a", "Diversion must be reported through proper channels; many states protect good-faith reporters.",
         {"b": "Mandatory reporting duty.", "c": "Ignoring enables harm.", "d": "Many policies protect reporters."}, "medium"),
        ("A prescription for a veterinary patient filled at retail pharmacy requires:",
         {"a": "Valid veterinarian prescription meeting state/federal requirements", "b": "No prescription if pet is cute", "c": "Human prescriber DEA only always", "d": "Technician diagnosis"},
         "a", "Veterinary Rx must be issued by licensed veterinarian within scope.",
         {"b": "Rx still required.", "c": "Veterinarian prescriber, not random MD.", "d": "Diagnosis is veterinarian role."}, "medium"),
        ("Maximum technician-to-pharmacist ratio, where regulated, is set by:",
         {"a": "State board of pharmacy", "b": "Individual technician", "c": "Payer insurance company exclusively", "d": "FDA exclusively for all staffing"},
         "a", "Staffing ratios are state-specific board rules when they exist.",
         {"b": "Not technician set.", "c": "Insurance does not set ratio.", "d": "FDA does not set pharmacy staffing ratios."}, "hard"),
        ("Offering inducements (free gifts) to switch prescriptions may violate:",
         {"a": "Anti-kickback and state unfair trade/ethics rules", "b": "Nothing; always encouraged federally", "c": "Only OSHA", "d": "Building fire codes exclusively"},
         "a", "Inducements to change prescriptions can violate fraud/abuse and state pharmacy laws.",
         {"b": "Federal/state restrictions apply.", "c": "Not OSHA primary issue.", "d": "Unrelated."}, "hard"),
        ("Patient requests copy of their prescription records. The pharmacy should:",
         {"a": "Provide access per HIPAA/state law with identity verification and reasonable process", "b": "Deny all access always", "c": "Charge unlimited random fee without policy", "d": "Send records to unauthorized third party without authorization"},
         "a", "HIPAA grants patients access rights with verification and permitted fees/process.",
         {"b": "Access is a patient right.", "c": "Fees must follow regulation.", "d": "Authorization required for third parties."}, "easy"),
    ])

    assert len(qs) == 60
    return qs


if __name__ == "__main__":
    from _common import write_bank
    write_bank("pharmacy-technician-excpt-readiness-check", build())
