#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "plumbing-journeyman-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "dwv", [
        ("DWV stands for:",
         {"a": "Drain, waste, and vent", "b": "Direct water valve exclusively always always", "c": "Dual wall voltage exclusively always always", "d": "Dry vent only exclusively always always"},
         "a", "DWV system removes sewage and provides venting.",
         {"b": "Not plumbing acronym.", "c": "Electrical.", "d": "Incomplete."}, "easy"),
        ("Minimum slope for horizontal drainage pipe (typical IPC) is:",
         {"a": "1/4 inch per foot for 3 inch and smaller; 1/8 inch per foot for 4 inch and larger", "b": "Level with no slope always always acceptable always always", "c": "12 inches per foot always always minimum always always", "d": "Slope upward toward fixture always always"},
         "a", "Proper slope ensures self-scouring flow toward stack/building drain.",
         {"b": "Stagnation risk.", "c": "Excessive.", "d": "Flows by gravity down."}, "medium"),
        ("A plumbing vent's primary purpose is to:",
         {"a": "Protect trap seals and allow air into drainage system", "b": "Supply hot water always always", "c": "Increase water pressure always always on supply always always", "d": "Filter drinking water always always"},
         "a", "Vents equalize pressure so traps retain water seal.",
         {"b": "Supply piping separate.", "c": "Pressure from supply main.", "d": "Treatment separate."}, "easy"),
        ("Trap seal depth is typically about:",
         {"a": "2 inches minimum (varies by code)", "b": "12 feet always always", "c": "Zero always always acceptable always always", "d": "Only 1/4 inch always always maximum always always"},
         "a", "Trap retains water barrier preventing sewer gas entry.",
         {"b": "Too deep impractical.", "c": "Must have seal.", "d": "2 in common minimum."}, "easy"),
        ("Wet venting allows:",
         {"a": "One pipe to serve as drain and vent for multiple fixtures per code limits", "b": "No venting ever always always", "c": "Only storm drain always always to serve as vent always always", "d": "Vent connected downstream of all traps only always always without rules ever always always"},
         "a", "Wet vents combine functions where code permits sizing/layout.",
         {"b": "Venting required.", "c": "Sanitary vent rules.", "d": "Specific conditions."}, "hard"),
        ("Cleanout placement requirements ensure:",
         {"a": "Access for rodding drainage system at changes of direction and intervals", "b": "No access ever always to pipes always always", "c": "Only decorative caps always always without function ever always always", "d": "Sealed permanently always always never opened always always"},
         "a", "Cleanouts required at base of stack, changes, and long runs.",
         {"b": "Maintenance access needed.", "c": "Functional access.", "d": "Removable plugs."}, "medium"),
        ("Studor (AAV) air admittance valve:",
         {"a": "Admits air when drainage draws vacuum; seals when not needed", "b": "Replaces all vent piping through roof always always in all jurisdictions always always without exception ever always always", "c": "Heats water always always", "d": "Backflows sewage into fixture always always as function always always"},
         "a", "AAV allows localized venting where permitted by code.",
         {"b": "Code restrictions apply.", "c": "Not heater.", "d": "Prevents siphonage."}, "medium"),
        ("Building drain connects:",
         {"a": "Branch drains to building sewer outside foundation", "b": "Only water supply mains always always", "c": "Gas lines always always", "d": "Electrical panels always always"},
         "a", "Building drain collects waste within structure to sewer connection.",
         {"b": "Supply system.", "c": "Fuel gas separate.", "d": "Electrical."}, "easy"),
        ("S-traps are generally prohibited because:",
         {"a": "They can lose seal by siphonage without venting", "b": "They are too efficient always always", "c": "Required in all modern codes always always", "d": "They improve venting always always"},
         "a", "S-traps prone to siphon; P-traps with vent preferred.",
         {"b": "Problematic design.", "c": "Prohibited not required.", "d": "Poor venting."}, "medium"),
        ("Maximum fixture units on a 3-inch horizontal drain (typical tables) is roughly:",
         {"a": "Based on IPC/UPC drain sizing tables (~42 FU for 3\" at 1/4\"/ft slope)", "b": "Unlimited always always without calculation ever always always", "c": "Zero always always—3 inch cannot serve fixtures ever always always", "d": "Exactly one fixture always always maximum always always"},
         "a", "DFU tables size drains by load and slope.",
         {"b": "Tables limit load.", "c": "Common branch size.", "d": "Many fixtures possible."}, "hard"),
        ("Vent terminal must terminate:",
         {"a": "Open to outdoor air, typically through roof with proper clearance", "b": "Inside sealed attic always always without opening ever always always", "c": "In occupied bedroom always always", "d": "Underground always always"},
         "a", "Vent exhausts sewer gases outdoors away from openings.",
         {"b": "Must vent outside.", "c": "Prohibited location.", "d": "Above roof/open air."}, "easy"),
        ("Backflow in DWV context refers to:",
         {"a": "Reverse flow of wastewater into fixtures", "b": "Forward supply flow always always exclusively always", "c": "Only gas line reversal always always", "d": "Air conditioning condensate definition only always always"},
         "a", "Proper venting/traps prevent backflow and siphonage.",
         {"b": "Drainage issue.", "c": "Different system.", "d": "May drain to DWV but term is reverse flow."}, "medium"),
        ("Cast iron vs PVC DWV:",
         {"a": "CI is durable/quiet; PVC is lightweight with solvent weld joints", "b": "Identical in all properties always always", "c": "PVC cannot be used underground ever always always", "d": "CI always prohibited always always in all areas always always"},
         "a", "Material choice depends on code, building type, noise.",
         {"b": "Different characteristics.", "c": "PVC DWV common underground.", "d": "CI still used."}, "easy"),
        ("Combination waste and vent systems are limited to:",
         {"a": "Specific flat vent configurations on floor drains/sinks per code", "b": "All high-rise stacks always always without restriction ever always always", "c": "Potable water mains always always", "d": "Natural gas venting always always"},
         "a", "Combination systems allowed only where code permits sizing rules.",
         {"b": "Restricted application.", "c": "Sanitary drainage.", "d": "Fuel gas separate."}, "hard"),
        ("Test plug for DWV system test:",
         {"a": "Used to air or water test system before concealment", "b": "Permanent flow restriction always always left in place always always", "c": "Decorative only always always", "d": "Installed in vent terminal permanently always always blocking vent always always"},
         "a", "Rough-in testing verifies leak-free installation.",
         {"b": "Removed after test.", "c": "Functional test.", "d": "Vent must remain open."}, "easy"),
    ])

    qs += pack(E, "water", [
        ("Water hammer is caused by:",
         {"a": "Sudden valve closure creating pressure surge in piping", "b": "Slow faucet drip always always exclusively always", "c": "Low water temperature always always exclusively always", "d": "Air in vent stack always always exclusively always as sole cause always always"},
         "a", "Hydraulic shock from quick flow stoppage; hammer arrestors mitigate.",
         {"b": "Different issue.", "c": "Unrelated.", "d": "Vent air different symptom."}, "medium"),
        ("Backflow preventer on domestic water service protects:",
         {"a": "Potable supply from contamination due to cross-connection", "b": "Only drain lines always always", "c": "Gas piping always always", "d": "Electrical service always always"},
         "a", "Devices like RPZ/double check stop reverse flow.",
         {"b": "Supply side protection.", "c": "Fuel gas.", "d": "Electrical."}, "easy"),
        ("Copper tube Type L vs Type M:",
         {"a": "Type L has thicker wall than Type M", "b": "Type M is always thicker always always", "c": "Identical wall thickness always always", "d": "Only used for gas always always exclusively always"},
         "a", "L is medium-heavy; M is lighter; K is heaviest.",
         {"b": "L thicker.", "c": "Different walls.", "d": "Water supply common."}, "easy"),
        ("PEX tubing advantages include:",
         {"a": "Flexibility, corrosion resistance, and fewer fittings in some layouts", "b": "Cannot bend ever always always", "c": "Rusts like steel always always", "d": "Only for DWV always always exclusively always"},
         "a", "PEX common for water distribution; requires proper fittings/support.",
         {"b": "Flexible.", "c": "Plastic no rust.", "d": "Supply not DWV."}, "easy"),
        ("Water pressure reducing valve (PRV) is installed when:",
         {"a": "Street pressure exceeds safe fixture/equipment limits (~80 psi typical max)", "b": "Pressure is always zero always always", "c": "Only to increase pressure always always regardless of incoming always always", "d": "On vent stacks always always exclusively always"},
         "a", "PRV lowers incoming pressure to protect system.",
         {"b": "PRV needs supply pressure.", "c": "Reduces high pressure.", "d": "Supply piping."}, "medium"),
        ("Thermal expansion tank on water heater prevents:",
         {"a": "Excessive pressure from heated water with closed system/backflow preventer", "b": "All heating always always", "c": "Drain clogs always always", "d": "Gas leaks always always"},
         "a", "Closed systems need expansion accommodation when water heats.",
         {"b": "Heater still heats.", "c": "DWV issue.", "d": "Fuel gas."}, "medium"),
        ("Dielectric union is used to:",
         {"a": "Separate dissimilar metals to reduce galvanic corrosion", "b": "Increase electrical conductivity between copper and steel always always as goal always always", "c": "Only decorate pipes always always", "d": "Vent sewer gases always always"},
         "a", "Plastic/isolation prevents galvanic cell at copper-steel junction.",
         {"b": "Isolates not connects electrically.", "c": "Functional.", "d": "Venting."}, "medium"),
        ("Minimum burial depth for water service (typical cold climate IPC) is often:",
         {"a": "Below frost line per local code (e.g., 12 inches to several feet)", "b": "On surface always always", "c": "Exactly 1 inch always always everywhere always always", "d": "Above roof always always"},
         "a", "Depth prevents freezing; local amendments apply.",
         {"b": "Must bury.", "c": "Varies by climate.", "d": "Underground service."}, "medium"),
        ("Shower valve pressure balancing/thermostatic mixing valve prevents:",
         {"a": "Scalding from pressure/temperature fluctuations", "b": "All water flow always always", "c": "Drain venting issues always always", "d": "Electrical grounding always always"},
         "a", "Mixing valves limit outlet temp and compensate pressure changes.",
         {"b": "Flow continues.", "c": "Supply fixture.", "d": "Plumbing not electrical."}, "easy"),
        ("Water meter is typically installed:",
         {"a": "At service entrance to measure usage", "b": "Inside every fixture trap always always", "c": "Only on vent pipe always always", "d": "After every faucet always always exclusively always"},
         "a", "Utility meter at service entry records consumption.",
         {"b": "Single point.", "c": "Supply not vent.", "d": "One meter per service."}, "easy"),
        ("Recirculation pump for hot water:",
         {"a": "Reduces wait time by circulating hot water loop", "b": "Cools water intentionally always always as primary goal always always", "c": "Replaces water heater always always", "d": "Installs on DWV stack always always exclusively always"},
         "a", "Recirc systems deliver faster hot water; need insulation/controls.",
         {"b": "Delivers hot.", "c": "Heater still required.", "d": "Supply system."}, "medium"),
        ("Soldering copper joints requires:",
         {"a": "Clean, fluxed fittings heated until solder wicks into joint", "b": "Cold pipe with no flux always always as best practice always always", "c": "Only glue always always on copper always always", "d": "Painting over leak always always as seal always always"},
         "a", "Proper prep and heat ensure watertight solder joint.",
         {"b": "Flux and heat needed.", "c": "Solder alloy.", "d": "Not durable."}, "easy"),
        ("Water softener uses ion exchange to:",
         {"a": "Replace hardness ions with sodium/potassium", "b": "Add calcium always always increasing hardness always always", "c": "Disinfect with chlorine always always as primary function always always", "d": "Remove vent air always always"},
         "a", "Softeners regenerate resin with brine flushing hardness.",
         {"b": "Removes hardness.", "c": "May have separate treatment.", "d": "Supply treatment."}, "medium"),
        ("Indirect waste receptor receives discharge from:",
         {"a": "Equipment drains that must not connect directly to sanitary (e.g., some appliances)", "b": "Only potable mains always always", "c": "Natural gas condensate into potable always always without air gap ever always always", "d": "Roof gutters into drinking tap always always"},
         "a", "Air gap/indirect waste prevents backflow from fixtures.",
         {"b": "Waste drainage.", "c": "Air gap required.", "d": "Cross-connection prohibited."}, "hard"),
        ("Flow rate for showerheads is limited federally to about:",
         {"a": "2.5 gpm at 80 psi (with some regional/WaterSense lower)", "b": "50 gpm always always minimum always always", "c": "0 gpm always always", "d": "1000 gpm residential always always"},
         "a", "Energy Policy Act 1992 set 2.5 gpm max for showers.",
         {"b": "Conservation limit.", "c": "Must flow.", "d": "Unrealistic."}, "medium"),
    ])

    qs += pack(E, "fixtures", [
        ("Water closet (toilet) rough-in distance is typically:",
         {"a": "12 inches from finished wall to center of closet flange (common)", "b": "36 inches always always standard always always without variation ever always always", "c": "Measured to ceiling always always", "d": "Zero clearance always always"},
         "a", "12\" rough-in common; 10\" and 14\" exist.",
         {"b": "12 standard.", "c": "Floor dimension.", "d": "Clearances apply."}, "easy"),
        ("Lavatory supply stops and traps require:",
         {"a": "Accessible shutoff valves and P-trap with proper height", "b": "No shutoff ever always always", "c": "S-trap preferred always always in new work always always", "d": "Direct connection without trap always always"},
         "a", "Fixtures need traps and individual stops for service.",
         {"b": "Stops required.", "c": "P-trap with vent.", "d": "Trap required."}, "easy"),
        ("Dishwasher drain connection typically uses:",
         {"a": "High loop or air gap before connection to drain/garbage disposal", "b": "Direct cross-connection to potable supply always always", "c": "Connection to gas vent always always", "d": "No drain needed always always"},
         "a", "High loop/air gap prevents backflow into dishwasher.",
         {"b": "Drains to DWV.", "c": "Sanitary drain.", "d": "Drain required."}, "medium"),
        ("Floor drain trap primer:",
         {"a": "Maintains trap seal in seldom-used drains by adding water", "b": "Removes all water from trap always always", "c": "Heats floor always always exclusively always", "d": "Vents gas line always always exclusively always"},
         "a", "Trap primers drip water to prevent evaporation of seal.",
         {"b": "Maintains seal.", "c": "Plumbing function.", "d": "Sanitary vent separate."}, "hard"),
        ("Shower pan/liner in tile shower:",
         {"a": "Must be waterproof before tile installation", "b": "Optional always always tile grouts waterproof always always without liner ever always always", "c": "Installed above tile always always", "d": "Same as roof shingle always always exclusively always"},
         "a", "Membrane or prefab pan prevents leakage to structure.",
         {"b": "Tile/grout not waterproof alone.", "c": "Under tile.", "d": "Shower receptor."}, "medium"),
        ("Garbage disposal requires:",
         {"a": "Electrical connection and drain tie-in with proper trap/vent", "b": "Only gas piping always always", "c": "No trap always always", "d": "Connection to water main without valve always always"},
         "a", "Disposal is appliance on sink branch with standard drainage.",
         {"b": "Electric motor.", "c": "Trap required.", "d": "Stops needed."}, "easy"),
        ("Bidet or washlet installation needs:",
         {"a": "Hot/cold supply and GFCI-protected electrical outlet nearby per code", "b": "Only vent stack always always", "c": "No backflow protection ever always", "d": "Direct sewer open pipe always always without fixture always always"},
         "a", "Fixtures need supply, drain, and applicable electrical safety.",
         {"b": "Water/electrical.", "c": "Backflow considerations.", "d": "Trapped fixture."}, "medium"),
        ("Carrier system supports:",
         {"a": "Wall-hung fixtures like lavatories and water closets", "b": "Only roof shingles always always", "c": "Electrical transformers always always exclusively always", "d": "Underground water main always always exclusively always"},
         "a", "Commercial carriers mount wall toilets/lavs on steel frame.",
         {"b": "Plumbing support.", "c": "Structural for fixtures.", "d": "In-wall support."}, "medium"),
        ("Temperature limit stop on tub/shower valve sets:",
         {"a": "Maximum handle rotation to cap hot water temperature", "b": "Minimum pressure always always to zero always always", "c": "Drain size always always", "d": "Vent terminal height always always"},
         "a", "Limit stops scald protection during valve installation.",
         {"b": "Temperature focus.", "c": "Drain separate.", "d": "Vent separate."}, "easy"),
        ("Wall-mounted faucet requires:",
         {"a": "Correct rough-in dimensions and solid backing/blocking in wall", "b": "No support always always", "c": "Only glue to drywall always always without reinforcement ever always always", "d": "Installation after tile without planning always always always"},
         "a", "Blocking prevents movement; rough specs from manufacturer.",
         {"b": "Blocking required.", "c": "Insufficient support.", "d": "Rough before finish."}, "medium"),
        ("Urinal flushometer systems use:",
         {"a": "High-pressure water from flush valve to cleanse fixture", "b": "Only gravity tank like residential WC always always exclusively always", "c": "No water ever always", "d": "Compressed air from vent stack always always exclusively always"},
         "a", "Flushometers common in commercial urinals.",
         {"b": "Different flush type.", "c": "Water powered.", "d": "Supply pressure."}, "medium"),
        ("Washing machine box provides:",
         {"a": "Recessed supply boxes with shutoffs and drain connection", "b": "Only electrical panel always always", "c": "Gas meter always always", "d": "Roof vent terminal always always"},
         "a", "Washer box recesses valves/hose connections in wall.",
         {"b": "Plumbing fixture.", "c": "Water supply.", "d": "Drain/standpipe."}, "easy"),
        ("Accessibility (ADA) lavatory requirements include:",
         {"a": "Clear knee space, height limits, and lever handles often required", "b": "Only pedestal sinks always always in all cases always always", "c": "No clearance ever always", "d": "Maximum height 60 inches always always for all fixtures always always without exception ever always always"},
         "a", "ADA/ANSI A117.1 specify accessible fixture dimensions.",
         {"b": "Wall-hung with clearance common.", "c": "Clear floor space required.", "d": "Specific heights vary by fixture."}, "hard"),
        ("Silcock (hose bibb) frost-free type:",
         {"a": "Shuts water inside heated space to prevent freezing", "b": "Keeps water in exterior wall always always", "c": "Has no valve always always", "d": "Only for natural gas always always"},
         "a", "Frost-free sillcock stem long; seat indoors.",
         {"b": "Valve seat indoors.", "c": "Integrated valve.", "d": "Water fixture."}, "medium"),
        ("Fixture rough-in inspection occurs:",
         {"a": "Before walls close to verify layout, slope, and connections", "b": "After building demolition always always", "c": "Never required always always", "d": "Only after final paint always always exclusively always"},
         "a", "Rough inspection confirms code compliance before concealment.",
         {"b": "During construction.", "c": "AHJ inspection.", "d": "Before cover."}, "easy"),
    ])

    qs += pack(E, "code", [
        ("IPC stands for:",
         {"a": "International Plumbing Code", "b": "Internal Pipe Commission exclusively always always", "c": "International Power Code exclusively always always for plumbing always always", "d": "Indoor Pool Club exclusively always always"},
         "a", "IPC is common model plumbing code from ICC.",
         {"b": "Not acronym.", "c": "Electrical NEC.", "d": "Unrelated."}, "easy"),
        ("UPC is published by:",
         {"a": "IAPMO (International Association of Plumbing and Mechanical Officials)", "b": "NFPA exclusively always always as UPC publisher always always", "c": "USDA exclusively always always", "d": "FAA exclusively always always"},
         "a", "UPC is alternative model code to IPC.",
         {"b": "IAPMO publishes UPC.", "c": "Unrelated.", "d": "Unrelated."}, "easy"),
        ("Authority Having Jurisdiction (AHJ) is:",
         {"a": "Local official/office enforcing code and issuing permits", "b": "Any homeowner always always", "c": "Product manufacturer always always exclusively always", "d": "Social media forum always always"},
         "a", "AHJ interprets and enforces adopted code locally.",
         {"b": "Official role.", "c": "May list products but not AHJ.", "d": "Not official."}, "easy"),
        ("Permit is required for plumbing work because:",
         {"a": "Ensures code compliance and inspection for public health/safety", "b": "Only to increase fees with no safety purpose ever always always", "c": "Never required anywhere always always", "d": "Only for paint color always always"},
         "a", "Permitting and inspection protect water/sanitary systems.",
         {"b": "Safety purpose.", "c": "Most jurisdictions require.", "d": "Construction work."}, "easy"),
        ("Cross-connection control program is mandated to:",
         {"a": "Prevent potable water contamination", "b": "Increase contamination always always", "c": "Eliminate all backflow devices always always", "d": "Only regulate paint always always"},
         "a", "Plumbing codes adopt backflow prevention rules.",
         {"b": "Protect health.", "c": "Devices required.", "d": "Water quality."}, "medium"),
        ("Approved materials in plumbing code means:",
         {"a": "Listed/accepted for specific use by code or testing standard", "b": "Any random material always always acceptable always always", "c": "Only gold pipe always always exclusively always", "d": "Homemade unlisted always always without testing ever always always"},
         "a", "Codes reference standards (ASTM, ASSE, NSF) for materials.",
         {"b": "Must be approved.", "c": "Common materials copper/PEX/PVC.", "d": "Listing required."}, "easy"),
        ("Vent pipe minimum size for single bathroom group often starts at:",
         {"a": "1-1/2 inches (check local code table)", "b": "6 inches always always minimum always always for all vents always always", "c": "1/2 inch always always", "d": "No minimum ever always always"},
         "a", "Vent sizing tables base on fixture units; 1.5\" common small branch.",
         {"b": "Smaller sizes used.", "c": "Too small for main.", "d": "Minimums exist."}, "medium"),
        ("Water pipe sizing uses:",
         {"a": "Fixture unit method and developed length/pressure available", "b": "Random guess always always", "c": "Only pipe color always always", "d": "Number of windows in building always always exclusively always"},
         "a", "Water supply sizing tables account for WSFU and friction loss.",
         {"b": "Engineered calculation.", "c": "Irrelevant.", "d": "Load based."}, "medium"),
        ("Gray water systems (where permitted) must:",
         {"a": "Meet code for separation, filtration, and approved uses", "b": "Connect directly to drinking faucet always always", "c": "Bypass all health rules always always", "d": "Use only blackwater always always as gray always always"},
         "a", "Gray water reuse regulated for irrigation/toilet flush etc.",
         {"b": "Potable separation.", "c": "Health codes apply.", "d": "Gray is lightly used water."}, "hard"),
        ("Isometric plumbing drawings show:",
         {"a": "3D-like view of pipe routing for layout understanding", "b": "Only electrical circuits always always", "c": "Food menu always always", "d": "Roof truss engineering exclusively always always without pipes ever always always"},
         "a", "Isometrics help visualize DWV and supply runs.",
         {"b": "Plumbing plan.", "c": "Unrelated.", "d": "Pipe routes."}, "easy"),
        ("Health department may regulate:",
         {"a": "Plumbing in food establishments and public health facilities", "b": "Only aviation always always", "c": "Stock trading always always", "d": "Nothing related to plumbing ever always always"},
         "a", "Food service plumbing has additional health code requirements.",
         {"b": "Public health.", "c": "Unrelated.", "d": "Regulates facilities."}, "medium"),
        ("ASSE standards often cover:",
         {"a": "Backflow preventers and plumbing devices", "b": "Only roofing shingles always always", "c": "Computer software always always exclusively always", "d": "Automotive tires always always exclusively always"},
         "a", "ASSE 1016/1017 etc. device performance standards.",
         {"b": "Plumbing devices.", "c": "Unrelated.", "d": "Unrelated."}, "medium"),
        ("Local code amendments may:",
         {"a": "Modify model code for regional conditions (e.g., frost depth)", "b": "Never exist always always identical to model always always everywhere always always", "c": "Eliminate all plumbing rules always always", "d": "Apply only in one house always always not jurisdiction always always"},
         "a", "Jurisdictions adopt IPC/UPC with local changes.",
         {"b": "Common to amend.", "c": "Still regulated.", "d": "Jurisdiction-wide."}, "easy"),
        ("Pressure testing DWV system common method:",
         {"a": "10 ft head of water or 5 psi air for 15 minutes with no drop", "b": "No test ever always always", "c": "Visual only always always without pressure ever always always", "d": "Fill with concrete always always as test always always"},
         "a", "Codes specify water or air test pressures and duration.",
         {"b": "Test required.", "c": "Pressure test standard.", "d": "Would block system."}, "medium"),
        ("Journeyman plumber license typically requires:",
         {"a": "Years of experience/apprenticeship and passing trade exam", "b": "Online quiz only with no experience ever always always in all states always always", "c": "No training ever always always", "d": "Only homeownership always always"},
         "a", "States license plumbers through experience and examination.",
         {"b": "Rigorous requirements.", "c": "Apprenticeship common.", "d": "Professional credential."}, "easy"),
    ])

    return qs


if __name__ == "__main__":
    write_bank(E, build())
