#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "praxis-special-education-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "development", [
        ("Piaget's sensorimotor stage (birth to ~2) is characterized by:",
         {"a": "Learning through senses and motor actions; object permanence develops", "b": "Abstract hypothetical reasoning exclusively", "c": "Formal operational thought about algebra always", "d": "Industry vs inferiority psychosocial crisis primarily"},
         "a", "Infants explore world physically; object permanence emerges late in stage.",
         {"b": "Formal operational is adolescence.", "c": "Too advanced.", "d": "Erikson industry stage is school age."}, "medium"),
        ("A student with autism may benefit from:",
         {"a": "Visual schedules, predictable routines, and explicit social skills instruction", "b": "Constant unpredictable changes to reduce anxiety always", "c": "Withholding all visual supports always", "d": "Only group work with no individual accommodations ever"},
         "a", "Structure and visual supports reduce anxiety and clarify expectations.",
         {"b": "Unpredictability increases stress.", "c": "Visual supports commonly help.", "d": "Individualized supports often needed."}, "easy"),
        ("Developmental delay means a child performs substantially below age expectations in:",
         {"a": "One or more developmental domains", "b": "Only athletic ability exclusively always for legal eligibility always", "c": "Adult employment history always", "d": "College coursework exclusively always"},
         "a", "Delay affects domains such as cognitive, communication, motor, social, adaptive.",
         {"b": "Broader than athletics.", "c": "Early childhood focus.", "d": "Not college."}, "easy"),
        ("Theory of Mind difficulties may appear in students who:",
         {"a": "Struggle to understand others' perspectives and beliefs", "b": "Always exceed peers in social cognition automatically always", "c": "Never have communication challenges ever", "d": "Only struggle with physical education exclusively always"},
         "a", "Theory of mind involves inferring others' mental states; common in ASD.",
         {"b": "Often challenged.", "c": "Communication often affected.", "d": "Cognitive/social domain."}, "medium"),
        ("Adolescents with intellectual disability still need instruction in:",
         {"a": "Transition planning for post-school living, work, and community participation", "b": "Only preschool-level colors with no functional skills ever always", "c": "Exclusively abstract calculus with no life skills ever always", "d": "Nothing after age 14 by federal law always"},
         "a", "IDEA requires transition services by age 16 (some states earlier).",
         {"b": "Age-appropriate functional curriculum needed.", "c": "Individualized to ability.", "d": "Services continue if eligible."}, "medium"),
        ("Early intervention services under Part C serve:",
         {"a": "Infants and toddlers with disabilities or developmental delays", "b": "Only adults in vocational rehab exclusively always", "c": "College students exclusively always", "d": "Only gifted students without disabilities always"},
         "a", "Part C (IDEA) supports birth through age 2 (state variation in extend to 3).",
         {"b": "VR is different program.", "c": "Early childhood.", "d": "Disability/delay eligibility."}, "medium"),
        ("Executive function skills include:",
         {"a": "Working memory, inhibitory control, and cognitive flexibility", "b": "Only rote spelling of random words exclusively always", "c": "Maximum running speed exclusively always", "d": "Memorizing state capitals only without application ever always"},
         "a", "Executive functions manage goal-directed behavior and self-regulation.",
         {"b": "Academic skill not EF definition.", "c": "Motor fitness.", "d": "Content knowledge."}, "medium"),
        ("Attachment theory suggests consistent responsive caregiving:",
         {"a": "Supports secure attachment and emotional development", "b": "Has no effect on child development ever according to research always", "c": "Should be eliminated in all schools always", "d": "Only matters after age 18 exclusively always"},
         "a", "Secure attachment correlates with emotional regulation and exploration.",
         {"b": "Research shows impact.", "c": "Caregiving matters early.", "d": "Early years critical."}, "easy"),
        ("A student with ADHD may demonstrate:",
         {"a": "Inattention, hyperactivity, and/or impulsivity affecting functioning", "b": "Guaranteed superior focus in all settings always", "c": "No need for organizational supports ever always", "d": "Only physical disability with no cognitive impact ever always"},
         "a", "ADHD symptoms must impair functioning in multiple settings for diagnosis.",
         {"b": "Inattention is hallmark.", "c": "Supports often help.", "d": "Neurodevelopmental condition."}, "easy"),
        ("Language development milestones: by 12 months many children:",
         {"a": "Use one or few words and understand simple requests", "b": "Read chapter books fluently always", "c": "Write five-paragraph essays always", "d": "Have adult conversational grammar fully always"},
         "a", "First words typically emerge around first birthday (wide variation).",
         {"b": "Years later.", "c": "School age.", "d": "Develops over years."}, "easy"),
        ("Sensory processing differences may lead a student to:",
         {"a": "Seek or avoid certain sounds, textures, or lights", "b": "Never react to any sensory input ever always", "c": "Only affect math computation exclusively always", "d": "Eliminate need for any IEP services always automatically"},
         "a", "Sensory over- or under-responsivity affects participation and regulation.",
         {"b": "Hyper/hypo responses occur.", "c": "Cross-domain impact.", "d": "May need accommodations."}, "medium"),
        ("Zone of Proximal Development (Vygotsky) refers to:",
         {"a": "Tasks a learner can do with guidance but not yet independently", "b": "Tasks always impossible even with help always forever", "c": "Only tasks mastered years ago always exclusively", "d": "Adult workplace tasks exclusively in kindergarten always"},
         "a", "ZPD is space between independent and assisted performance.",
         {"b": "Scaffolding targets ZPD.", "c": "Already mastered.", "d": "Age appropriate."}, "medium"),
        ("Down syndrome is caused by:",
         {"a": "Trisomy 21 (extra copy of chromosome 21)", "b": "Bacterial infection during school hours exclusively always", "c": "Poor teaching exclusively as sole cause always", "d": "Lack of homework exclusively always genetically"},
         "a", "Most cases involve three copies of chromosome 21.",
         {"b": "Genetic not infectious.", "c": "Not caused by instruction.", "d": "Genetic condition."}, "easy"),
        ("Prerequisite skills for reading include:",
         {"a": "Phonological awareness, letter knowledge, and vocabulary", "b": "Only calculus readiness exclusively always", "c": "Advanced driving skills exclusively always", "d": "No oral language exposure ever beneficial always"},
         "a", "Early literacy builds on sound awareness, print concepts, language.",
         {"b": "Math advanced skill.", "c": "Unrelated.", "d": "Oral language foundation critical."}, "easy"),
        ("Trauma-informed practice in schools emphasizes:",
         {"a": "Safety, trust, choice, collaboration, and empowerment", "b": "Punishing all behavioral reactions without context always", "c": "Ignoring student history entirely always", "d": "Removing all routines to increase chaos always"},
         "a", "Trauma-informed care prioritizes physical/emotional safety and relationships.",
         {"b": "Reactive punishment may retraumatize.", "c": "Context matters.", "d": "Predictability helps."}, "hard"),
    ])

    qs += pack(E, "planning", [
        ("An IEP must include:",
         {"a": "Present levels, measurable annual goals, services, and placement", "b": "Only the student's favorite color always", "c": "Teacher salary information exclusively always", "d": "Unlimited promises without services defined ever always"},
         "a", "IDEA requires specific IEP components documented annually.",
         {"b": "Not IEP element.", "c": "Personnel info not IEP content.", "d": "Services must be described."}, "easy"),
        ("Least Restrictive Environment (LRE) means:",
         {"a": "Educating students with disabilities alongside nondisabled peers to maximum appropriate extent", "b": "Always placing every student in separate school always without consideration ever", "c": "Eliminating all specialized instruction always instantly always", "d": "Only educating students at home always without team decision ever always"},
         "a", "LRE presumes inclusion with supplementary aids/services as needed.",
         {"b": "More restrictive only when necessary.", "c": "Specialized instruction may be required.", "d": "Team determines placement."}, "easy"),
        ("Accommodations differ from modifications because accommodations:",
         {"a": "Change how a student accesses content without altering grade-level standards", "b": "Always lower grade-level expectations always by definition always", "c": "Eliminate all assessment ever always", "d": "Are only for general education students never special education ever always"},
         "a", "Accommodations adjust access; modifications change what is taught/expected.",
         {"b": "That describes modifications.", "c": "Assessment continues.", "d": "Both populations may use accommodations."}, "medium"),
        ("A BIP (Behavior Intervention Plan) should be based on:",
         {"a": "Functional Behavioral Assessment identifying function of behavior", "b": "Random penalties without data always", "c": "Only academic grades in unrelated subjects always exclusively", "d": "Parent preference alone without assessment ever always sufficient always"},
         "a", "FBA informs function-based positive interventions in BIP.",
         {"b": "Data-driven required.", "c": "Behavior focus.", "d": "Team assessment needed."}, "medium"),
        ("Progress monitoring for IEP goals should be:",
         {"a": "Frequent, standardized or curriculum-based, and used to adjust instruction", "b": "Collected only once at graduation exclusively always", "c": "Based solely on teacher intuition without records ever always", "d": "Hidden from parents always by law always"},
         "a", "Regular progress data informs whether goals are met and services effective.",
         {"b": "Ongoing required.", "c": "Documentation required.", "d": "Parents receive progress reports."}, "medium"),
        ("Co-teaching models may include:",
         {"a": "One teach/one assist, station teaching, parallel teaching, alternative teaching, team teaching", "b": "Only one teacher leaving the room always exclusively always", "c": "Special educator never collaborating with general educator always always", "d": "Students teaching exclusively with no adult ever always in all sped classes always"},
         "a", "Friend & Cook co-teaching approaches vary by lesson purpose.",
         {"b": "Collaborative models involve both.", "c": "Collaboration is core.", "d": "Adult instruction required."}, "hard"),
        ("Extended School Year (ESY) services are provided when:",
         {"a": "Regression/recoupment data show significant skill loss over breaks", "b": "Any parent requests summer camp always automatically qualifies always", "c": "Student is gifted without disability always qualifies always", "d": "Never documented in IDEA ever always"},
         "a", "ESY eligibility based on regression, recoupment, critical skills, etc.",
         {"b": "Team decision with data.", "c": "Disability-related need.", "d": "ESY in IDEA case law/regs."}, "hard"),
        ("Universal Design for Learning (UDL) promotes:",
         {"a": "Multiple means of engagement, representation, and action/expression", "b": "One fixed worksheet for all learners always exclusively always", "c": "Eliminating all technology always as UDL principle always", "d": "Teaching only through lecture without variation ever always"},
         "a", "UDL reduces barriers proactively through flexible options.",
         {"b": "Opposite of universal design.", "c": "Technology can support UDL.", "d": "Multiple modalities encouraged."}, "medium"),
        ("Related services on an IEP may include:",
         {"a": "Speech-language therapy, occupational therapy, and transportation if required", "b": "Only varsity athletics exclusively always as related service always automatically", "c": "Luxury vacations for families always funded by district always", "d": "Unrelated cosmetic services always"},
         "a", "IDEA lists related services that assist benefit from special education.",
         {"b": "Not related service.", "c": "Not educational.", "d": "Medically unnecessary cosmetic."}, "easy"),
        ("Prior Written Notice must be given when:",
         {"a": "District proposes or refuses to change identification, evaluation, or placement", "b": "Student completes homework on time always", "c": "Cafeteria menu changes always", "d": "Daily attendance is taken always without any decision ever always"},
         "a", "PWN documents proposed/refused actions and parental rights.",
         {"b": "Routine event.", "c": "Not special education decision.", "d": "Specific decisions trigger PWN."}, "medium"),
        ("SMART IEP goals are:",
         {"a": "Specific, Measurable, Achievable, Relevant, Time-bound", "b": "Secret, Mandatory, Arbitrary, Random, Temporary always as acronym always officially", "c": "Only social goals never academic ever allowed always", "d": "Optional under IDEA always without measure ever always"},
         "a", "Measurable goals with clear criteria and timelines are required.",
         {"b": "Not SMART definition.", "c": "Academic and functional goals allowed.", "d": "Measurable annual goals required."}, "easy"),
        ("Differentiated instruction for diverse learners includes:",
         {"a": "Adjusting content, process, product, or environment based on student need", "b": "Identical task for everyone regardless of readiness always always", "c": "Tracking solely by age with no data ever always", "d": "Eliminating all scaffolding always as best practice always always"},
         "a", "Tomlinson's differentiation responds to readiness, interest, profile.",
         {"b": "Differentiation varies task.", "c": "Assessment informs.", "d": "Scaffolds support access."}, "medium"),
        ("Manifestation determination reviews occur when:",
         {"a": "Disciplinary removal exceeds 10 consecutive days or constitutes pattern", "b": "Student earns honor roll always", "c": "Parent attends conference always without discipline ever always", "d": "Never required under IDEA ever always"},
         "a", "Team determines if conduct caused by or related to disability.",
         {"b": "Not disciplinary trigger.", "c": "Discipline-specific.", "d": "IDEA discipline protections."}, "hard"),
        ("Transition services in the IEP focus on:",
         {"a": "Postsecondary education, employment, and independent living skills", "b": "Only elementary recess activities exclusively always", "c": "Retirement planning at age 10 exclusively always", "d": "Eliminating all community-based instruction always always"},
         "a", "Transition planning prepares for life after secondary school.",
         {"b": "Secondary/adult focus.", "c": "Begins by age 16 typically.", "d": "Community experiences often included."}, "medium"),
        ("Assistive technology on an IEP:",
         {"a": "Must be considered for every student with a disability", "b": "Is prohibited under IDEA always", "c": "Replaces special education entirely always automatically always", "d": "Only includes motorized vehicles always exclusively always"},
         "a", "IDEA requires AT consideration; range from low to high tech.",
         {"b": "AT mandated consideration.", "c": "Supplements instruction.", "d": "Includes simple devices too."}, "easy"),
    ])

    qs += pack(E, "assessment", [
        ("Norm-referenced tests compare a student's performance to:",
         {"a": "A representative sample of peers (norm group)", "b": "Only the student's prior day mood exclusively always", "c": "An arbitrary score with no reference group ever always", "d": "Teacher's personal opinion exclusively always without data ever always"},
         "a", "Norm-referenced scores (percentiles, standard scores) reference peer distribution.",
         {"b": "Standardization sample required.", "c": "Norm group essential.", "d": "Standardized administration."}, "medium"),
        ("Criterion-referenced assessment measures:",
         {"a": "Performance against a defined skill standard or criterion", "b": "Only relative standing among national peers exclusively always without skill definition ever always", "c": "Stock market indices exclusively always", "d": "Random guessing exclusively always as design always"},
         "a", "Criterion-referenced shows mastery of specific objectives.",
         {"b": "That is norm-referenced emphasis.", "c": "Unrelated.", "d": "Valid assessment has criteria."}, "medium"),
        ("A standard score of 100 on an IQ test typically represents:",
         {"a": "The mean of the norm sample", "b": "Maximum possible gifted score always", "c": "Failure always", "d": "Grade equivalent of kindergarten always exclusively always"},
         "a", "IQ tests standardize mean=100, SD=15 (most tests).",
         {"b": "Average performance.", "c": "Average not failure.", "d": "Different metric."}, "easy"),
        ("Curriculum-Based Measurement (CBM) is useful because it:",
         {"a": "Provides frequent, brief probes to track academic progress", "b": "Requires full-day testing weekly always exclusively always", "c": "Cannot be graphed over time ever always", "d": "Only measures behavior never academics ever always"},
         "a", "CBM (e.g., oral reading fluency) enables progress monitoring graphs.",
         {"b": "Brief timed probes.", "c": "Graphed routinely.", "d": "Academic skills focus."}, "medium"),
        ("Assessment bias should be minimized by:",
         {"a": "Using culturally fair procedures and interpreting scores cautiously", "b": "Ignoring student language background always always", "c": "Testing only in non-native language always without support ever always as policy always", "d": "Assuming all tests are perfectly fair without review ever always"},
         "a", "Evaluators consider language, culture, disability in interpretation.",
         {"b": "Language matters.", "c": "Appropriate language/testing conditions required.", "d": "Professional judgment needed."}, "hard"),
        ("A discrepancy model for SLD identification compares:",
         {"a": "Achievement to cognitive ability (historically; many states shifting)", "b": "Shoe size to height exclusively always as federal requirement always", "c": "Only attendance records exclusively always", "d": "Parent income exclusively always as sole criterion always federally always"},
         "a", "IQ-achievement discrepancy was common; RTI now emphasized in many states.",
         {"b": "Not assessment model.", "c": "Academic data needed.", "d": "Not eligibility criterion."}, "hard"),
        ("Response to Intervention (RTI) uses:",
         {"a": "Tiered increasingly intensive instruction with progress monitoring", "b": "Only retention without intervention always always", "c": "Single test on one day to label student permanently always always", "d": "Elimination of all general education support always always"},
         "a", "RTI provides data-based tiers before/during special education evaluation.",
         {"b": "Intervention core.", "c": "Multiple data points.", "d": "Gen ed interventions at tier 1/2."}, "medium"),
        ("Dynamic assessment examines:",
         {"a": "Learning potential during mediated teaching rather than static performance only", "b": "Only memorized facts without teaching during test ever always exclusively always", "c": "Physical fitness exclusively always", "d": "Parent survey exclusively always without student interaction ever always exclusively always"},
         "a", "Dynamic testing measures responsiveness to instruction during assessment.",
         {"b": "Mediation is key.", "c": "Cognitive focus.", "d": "Student performance central."}, "hard"),
        ("Ecological assessment gathers information from:",
         {"a": "Multiple environments such as classroom, home, and community", "b": "Only standardized clinic with no context ever always exclusively always", "c": "A single multiple-choice item always sufficient always", "d": "Historical documents from 1800 exclusively always only always"},
         "a", "Ecological approach observes behavior across settings.",
         {"b": "Context needed.", "c": "Multiple sources.", "d": "Contemporary settings."}, "medium"),
        ("Portfolio assessment includes:",
         {"a": "Collected work samples showing growth over time", "b": "Only one test score from one day always exclusively always", "c": "Random deletion of all student work always as practice always", "d": "Exclusive use for college admissions always in lieu of IEP always always federally always"},
         "a", "Portfolios document performance and progress authentically.",
         {"b": "Multiple artifacts.", "c": "Preserves work.", "d": "IEP uses various measures."}, "easy"),
        ("Inter-rater reliability refers to:",
         {"a": "Consistency of scoring across different evaluators", "b": "Student mood on one day exclusively always", "c": "Test length in pages exclusively always", "d": "Cost of testing materials exclusively always"},
         "a", "High inter-rater reliability means scorers agree on observations/scores.",
         {"b": "Measurement property.", "c": "Not reliability definition.", "d": "Psychometric concept."}, "medium"),
        ("A functional behavioral assessment collects data on:",
         {"a": "Antecedents, behavior, and consequences (ABC)", "b": "Only student eye color exclusively always", "c": "District budget exclusively always", "d": "Unrelated standardized math norms exclusively always without behavior observation ever always"},
         "a", "ABC analysis identifies triggers and maintaining consequences.",
         {"b": "Irrelevant.", "c": "Behavior focus.", "d": "Direct observation needed."}, "medium"),
        ("Testing accommodations on state assessments may include:",
         {"a": "Extended time, separate setting, or read-aloud per IEP/504", "b": "Changing scored content always illegally always", "c": "Providing answers to student always as accommodation always always", "d": "Eliminating participation always for all disabled students always always federally always"},
         "a", "Accommodations change access not what is measured (unless alternate assessment).",
         {"b": "Modifications differ.", "c": "Not valid accommodation.", "d": "Participation required with accommodations."}, "medium"),
        ("Age equivalent scores are often discouraged because:",
         {"a": "They imply uniform skills at an age and can mislead about scatter", "b": "They are always the most precise metric always preferred always always", "c": "They replace standard scores legally always always", "d": "They measure only behavior never achievement ever always"},
         "a", "Age equivalents oversimplify profile and vary by subtest scatter.",
         {"b": "Standard scores preferred.", "c": "Not replacement.", "d": "Achievement can use age equiv."}, "hard"),
        ("Parent consent is required before:",
         {"a": "Initial special education evaluation", "b": "Every daily lunch choice always", "c": "Routine fire drill always as evaluation always", "d": "Homework assignment in general education always as sped evaluation always always"},
         "a", "IDEA requires informed consent for initial evaluation.",
         {"b": "Routine activity.", "c": "Safety drill.", "d": "Not evaluation."}, "easy"),
    ])

    qs += pack(E, "foundations", [
        ("IDEA stands for:",
         {"a": "Individuals with Disabilities Education Act", "b": "International Development Education Association exclusively always", "c": "Integrated Daily Exercise Activity exclusively always federally always", "d": "Internal District Employment Agreement exclusively always always"},
         "a", "IDEA is federal special education law (formerly EHA).",
         {"b": "Incorrect expansion.", "c": "Not the law.", "d": "Not federal statute name."}, "easy"),
        ("FAPE under IDEA means:",
         {"a": "Free Appropriate Public Education tailored to student needs", "b": "Free Athletic Programs exclusively for all students always always", "c": "Fully Advanced Private Education paid for all always without limits always", "d": "Optional services only if district chooses always without requirement ever always"},
         "a", "FAPE requires special education and related services at no cost to parents.",
         {"b": "Not FAPE.", "c": "Public not private mandate generally.", "d": "Mandatory if eligible."}, "easy"),
        ("Section 504 of the Rehabilitation Act prohibits:",
         {"a": "Disability discrimination in programs receiving federal funds", "b": "All homework assignments nationally always", "c": "Use of any accommodations ever always", "d": "Parent involvement always exclusively always"},
         "a", "504 provides accommodations for qualifying disabilities; differs from IDEA.",
         {"b": "Unrelated.", "c": "504 plans include accommodations.", "d": "Parent rights exist."}, "medium"),
        ("Child Find requires schools to:",
         {"a": "Identify, locate, and evaluate children who may need special education", "b": "Wait until parents request services at age 21 only always exclusively always", "c": "Exclude private school children entirely always without exception ever always", "d": "Only serve students with physical disabilities always always exclusively always"},
         "a", "Child Find is ongoing obligation to find eligible children.",
         {"b": "Birth through 21 if eligible.", "c": "Some services for parentally placed private.", "d": "All disability categories."}, "medium"),
        ("Zero reject principle means:",
         {"a": "No eligible child with a disability is denied access to public education", "b": "Students may be permanently expelled without education always always", "c": "Only top academic performers receive services always always", "d": "Districts may refuse evaluation always without reason ever always"},
         "a", "IDEA requires education for all eligible children regardless of severity.",
         {"b": "Opposite.", "c": "Eligibility not merit-based.", "d": "Child Find and evaluation rights."}, "easy"),
        ("Procedural safeguards notice must inform parents of:",
         {"a": "Rights to consent, due process, and dispute resolution", "b": "Cafeteria prices exclusively always only always", "c": "Teacher dress code exclusively always only always", "d": "Athletic team rankings exclusively always only always"},
         "a", "Parents receive rights information annually and at key points.",
         {"b": "Not procedural safeguards content.", "c": "Unrelated.", "d": "Unrelated."}, "easy"),
        ("Due process hearing may be requested when:",
         {"a": "Parents and district disagree on identification, evaluation, placement, or FAPE", "b": "Student prefers one lunch item always", "c": "Weather cancels recess always", "d": "Teacher assigns seating alphabetically always without dispute always always"},
         "a", "Impartial hearing resolves IDEA disputes.",
         {"b": "Not dispute subject.", "c": "Routine.", "d": "Not FAPE issue."}, "medium"),
        ("NCLB/ESEA reauthorizations influenced special education by:",
         {"a": "Emphasizing accountability and participation of students with disabilities in assessments", "b": "Eliminating all testing for students with IEPs always permanently always", "c": "Removing LRE requirement always always", "d": "Transferring IDEA to local parks departments always always"},
         "a", "Accountability laws address inclusion in state testing with accommodations.",
         {"b": "Participation required with accommodations/alternate.", "c": "IDEA LRE remains.", "d": "IDEA federal ED."}, "hard"),
        ("Brown v. Board of Education (1954) is foundational because it:",
         {"a": "Declared separate educational facilities inherently unequal", "b": "Established IDEA exclusively in 1954 always historically inaccurate always", "c": "Eliminated all special education always always", "d": "Mandated standardized testing exclusively always in 1954 always always"},
         "a", "Brown ended legal segregation; influenced inclusion movements.",
         {"b": "IDEA enacted 1975.", "c": "Separate issue.", "d": "Later policy."}, "medium"),
        ("PL 94-142 (1975) established:",
         {"a": "Right to education for children with disabilities (precursor to IDEA)", "b": "Mandatory military service in high school always always", "c": "Elimination of parent participation always always", "d": "Private-only education funding always always"},
         "a", "EHA/PL 94-142 guaranteed FAPE in LRE.",
         {"b": "Unrelated.", "c": "Parent participation required.", "d": "Public education."}, "medium"),
        ("Confidentiality of student records under FERPA means:",
         {"a": "Personally identifiable information is protected with limited disclosure", "b": "Records posted publicly always without consent always", "c": "Teachers may share IEP with anyone always without permission always", "d": "Parents may never access records always always"},
         "a", "FERPA protects education records; parents have access rights.",
         {"b": "Protected.", "c": "Need consent or legitimate interest.", "d": "Parents have rights."}, "medium"),
        ("Professional ethical practice for special educators includes:",
         {"a": "Maintaining competence, confidentiality, and advocating for students", "b": "Disclosing student disabilities publicly to all classmates always always", "c": "Ignoring colleagues in collaboration always always", "d": "Using restraint without training always as first option always always"},
         "a", "CEC ethical codes emphasize dignity, collaboration, evidence-based practice.",
         {"b": "Confidentiality required.", "c": "Collaboration essential.", "d": "Restraint only when trained and necessary."}, "easy"),
        ("Inclusive education research generally shows:",
         {"a": "Students with disabilities benefit academically and socially with supports", "b": "Segregation always produces superior outcomes always for everyone always without exception always", "c": "Peers never benefit from inclusion always always research shows opposite trends often always", "d": "Inclusion eliminates need for specialized instruction always always instantly always"},
         "a", "Inclusion with supports benefits many; specialized instruction continues.",
         {"b": "LRE research supports inclusion when appropriate.", "c": "Peer modeling benefits.", "d": "Specialized services still needed."}, "medium"),
        ("Cultural and linguistic diversity in evaluation requires:",
         {"a": "Assessments in native language when feasible and nondiscriminatory tools", "b": "Assuming low scores always reflect disability without considering language always always acceptable always", "c": "Ignoring interpreter use always always", "d": "Using only one monolingual test always without documentation ever always always"},
         "a", "Evaluators distinguish language difference from disability.",
         {"b": "Bias violates practice.", "c": "Qualified interpreters needed.", "d": "Multiple measures/languages."}, "hard"),
        ("Mediation in special education disputes is:",
         {"a": "Voluntary facilitated negotiation before or instead of due process", "b": "Mandatory binding arbitration always without parent consent always always federally always required always", "c": "Unavailable under IDEA always always", "d": "Only for general education grading disputes always always exclusively always"},
         "a", "IDEA offers mediation as confidential dispute resolution option.",
         {"b": "Voluntary not mandatory binding.", "c": "IDEA provides mediation.", "d": "IDEA disputes."}, "medium"),
    ])

    return qs


if __name__ == "__main__":
    write_bank(E, build())
