#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "praxis-elementary-education-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "reading", [
        ("Phonemic awareness refers to a student's ability to:",
         {"a": "Recognize and manipulate individual sounds in spoken words", "b": "Multiply multi-digit numbers fluently", "c": "Identify states on a map exclusively", "d": "Conduct chemical titration experiments"},
         "a", "Phonemic awareness is auditory manipulation of phonemes before print.",
         {"b": "Math skill.", "c": "Geography.", "d": "Science lab."}, "easy"),
        ("The alphabetic principle means students understand:",
         {"a": "Written letters represent spoken sounds in systematic ways", "b": "All words must be memorized as whole units with no letter-sound connection", "c": "Numbers correspond to alphabet order always", "d": "Only uppercase letters have sounds"},
         "a", "Alphabetic principle links graphemes to phonemes for decoding.",
         {"b": "Sight words supplement but don't replace phonics.", "c": "Unrelated.", "d": "Both cases represent sounds."}, "easy"),
        ("A student who reads 'house' as 'home' on the page may be:",
         {"a": "Using context/guessing rather than decoding accurately", "b": "Demonstrating advanced syllabication always", "c": "Applying correct phonics for all letters", "d": "Reading with perfect fluency automatically"},
         "a", "Miscue substitution suggests reliance on meaning over print.",
         {"b": "Not syllabication issue.", "c": "Letters differ.", "d": "Accuracy error."}, "medium"),
        ("Guided reading groups are most effective when texts are:",
         {"a": "At instructional level where students need some support", "b": "Far above grade level with no scaffolding always", "c": "Identical for every student regardless of readiness", "d": "Only worksheets with no connected text"},
         "a", "Instructional level balances challenge and support in small groups.",
         {"b": "Frustration level impedes learning.", "c": "Differentiation needed.", "d": "Connected text supports comprehension."}, "medium"),
        ("Main idea of a paragraph is best identified by asking:",
         {"a": "What is this mostly about? What point does the author make?", "b": "How many adjectives appear in sentence three only?", "c": "What font size is used in the heading?", "d": "Which character appears first alphabetically?"},
         "a", "Main idea is the central message supported by details.",
         {"b": "Surface detail.", "c": "Format not content.", "d": "Irrelevant."}, "easy"),
        ("Explicit instruction in vocabulary should include:",
         {"a": "Definitions, examples, non-examples, and practice in context", "b": "Only copying dictionary pages without discussion", "c": "Avoiding any student talk about word meanings", "d": "Teaching only words students already know"},
         "a", "Direct vocabulary instruction uses multiple exposures and contexts.",
         {"b": "Passive copying insufficient.", "c": "Discussion aids retention.", "d": "Stretch words needed."}, "medium"),
        ("Fluency includes accuracy, rate, and:",
         {"a": "Prosody (expression appropriate to meaning)", "b": "Only handwriting speed on unrelated tasks", "c": "Memorization of multiplication tables exclusively", "d": "Silent avoidance of all oral reading always"},
         "a", "Reading fluency combines accurate, automatic, expressive reading.",
         {"b": "Motor skill separate.", "c": "Math skill.", "d": "Oral reading assesses fluency."}, "easy"),
        ("A graphic organizer for compare-contrast might use:",
         {"a": "A Venn diagram or T-chart listing similarities and differences", "b": "Only a number line for fractions", "c": "A periodic table of elements exclusively", "d": "A map scale bar only"},
         "a", "Venn/T-chart structures relational thinking about two texts/topics.",
         {"b": "Math tool.", "c": "Science reference.", "d": "Geography tool."}, "easy"),
        ("When assessing reading comprehension, open-ended questions that require text evidence:",
         {"a": "Reveal deeper understanding beyond recall", "b": "Should always be yes/no only", "c": "Eliminate the need for any reading", "d": "Measure only decoding speed exclusively always"},
         "a", "Evidence-based responses show inferential and analytical comprehension.",
         {"b": "Limited format.", "c": "Must read text.", "d": "Comprehension beyond rate."}, "medium"),
        ("Morphological awareness helps students understand:",
         {"a": "How prefixes, suffixes, and roots change word meaning", "b": "Only the order of planets from the sun", "c": "Temperature conversion formulas exclusively", "d": "Musical note frequencies only"},
         "a", "Morphology links word parts to meaning (e.g., un-, -ful, struct).",
         {"b": "Science content.", "c": "Math/science.", "d": "Music."}, "medium"),
        ("A running record during oral reading allows the teacher to:",
         {"a": "Analyze miscues and self-correction strategies", "b": "Grade only penmanship on unrelated writing", "c": "Measure jump rope speed in PE", "d": "Administer standardized state tests exclusively always"},
         "a", "Running records code errors and inform instructional next steps.",
         {"b": "Different domain.", "c": "PE metric.", "d": "Informal assessment tool."}, "medium"),
        ("Close reading of a complex text typically involves:",
         {"a": "Multiple readings focusing on structure, vocabulary, and author's purpose", "b": "Skimming once without re-reading ever", "c": "Replacing the text with a video always without print", "d": "Ignoring text structure entirely"},
         "a", "Close reading revisits text to deepen analysis.",
         {"b": "Insufficient depth.", "c": "Print literacy remains goal.", "d": "Structure aids comprehension."}, "hard"),
        ("High-frequency irregular words (e.g., 'said') are often taught through:",
         {"a": "Multisensory practice and repeated exposure because some spellings don't follow regular patterns", "b": "Only phonics rules that always apply perfectly to every word", "c": "Avoiding any flashcard or game activities always", "d": "Waiting until middle school exclusively"},
         "a", "Heart words combine phonics where possible and memorization where needed.",
         {"b": "Irregular parts need direct teaching.", "c": "Games aid engagement.", "d": "Early grades need sight words."}, "medium"),
        ("Summarizing a fiction text should include:",
         {"a": "Key characters, setting, problem, and resolution concisely", "b": "Every dialogue line copied verbatim", "c": "Only the book cover illustration description", "d": "Unrelated personal opinions with no reference to plot"},
         "a", "Summary captures essential story elements without excess detail.",
         {"b": "Too long/not summary.", "c": "Cover not plot.", "d": "Must reflect text."}, "easy"),
        ("Differentiating reading instruction for English learners may include:",
         {"a": "Visual supports, cognates when applicable, and structured oral language practice", "b": "Withholding all native language resources regardless of policy", "c": "Assuming literacy in L1 is irrelevant always", "d": "Only assigning texts two grade levels above without support"},
         "a", "Scaffolded supports build comprehension while developing English.",
         {"b": "Translanguaging may help per policy.", "c": "L1 literacy transfers.", "d": "Frustration level inappropriate."}, "hard"),
    ])

    qs += pack(E, "math", [
        ("Which number sentence is true?",
         {"a": "3/4 = 6/8", "b": "3/4 = 3/8", "c": "3/4 = 1/8", "d": "3/4 = 4/3"},
         "a", "Multiply numerator and denominator by 2: 3/4 = 6/8.",
         {"b": "Denominator changed incorrectly.", "c": "Not equivalent.", "d": "Reciprocal not equal."}, "easy"),
        ("A rectangle 5 cm by 8 cm has area:",
         {"a": "13 cm²", "b": "40 cm²", "c": "26 cm²", "d": "80 cm²"},
         "b", "Area = length × width = 5 × 8 = 40 cm².",
         {"a": "Perimeter mistake (13 is 5+8).", "c": "Doubled sum not area.", "d": "Calculation error."}, "easy"),
        ("Place value: in 4,306 the digit 3 represents:",
         {"a": "3 ones", "b": "3 tens", "c": "3 hundreds", "d": "3 thousands"},
         "c", "3 is in the hundreds place.",
         {"a": "Ones place is 6.", "b": "Tens would be 30.", "d": "Thousands digit is 4."}, "easy"),
        ("Which shape has exactly four equal sides and four right angles?",
         {"a": "Rhombus without right angles necessarily", "b": "Square", "c": "Trapezoid always", "d": "Circle"},
         "b", "Square has four equal sides and four 90° angles.",
         {"a": "Rhombus may lack right angles.", "c": "Trapezoid has one pair parallel.", "d": "No sides."}, "easy"),
        ("24 ÷ 6 = ?",
         {"a": "3", "b": "4", "c": "5", "d": "6"},
         "b", "24 divided by 6 equals 4.",
         {"a": "6×3=18.", "c": "6×5=30.", "d": "6×6=36."}, "easy"),
        ("A number line shows 0, 1/2, 1. Where would 3/4 fall?",
         {"a": "Between 0 and 1/2", "b": "Between 1/2 and 1", "c": "At exactly 0", "d": "Beyond 1 always"},
         "b", "3/4 = 0.75, between 1/2 (0.5) and 1.",
         {"a": "Too low.", "c": "Zero is less.", "d": "3/4 < 1."}, "easy"),
        ("Word problem: 47 stickers, give away 19. How many left?",
         {"a": "66", "b": "28", "c": "38", "d": "26"},
         "b", "47 − 19 = 28.",
         {"a": "Added instead of subtracted.", "c": "Arithmetic error.", "d": "Close but wrong."}, "easy"),
        ("Perimeter of a square with side 7 inches is:",
         {"a": "14 inches", "b": "28 inches", "c": "49 inches", "d": "7 inches"},
         "b", "P = 4 × side = 4 × 7 = 28 inches.",
         {"a": "2 × side only.", "c": "Area calculation.", "d": "One side only."}, "medium"),
        ("Which fraction is greatest?",
         {"a": "1/3", "b": "1/2", "c": "1/4", "d": "1/8"},
         "b", "Larger unit fractions with same numerator: 1/2 > 1/3 > 1/4 > 1/8.",
         {"a": "Smaller than 1/2.", "c": "Smaller.", "d": "Smallest."}, "easy"),
        ("Arrays model multiplication because:",
         {"a": "Rows and columns show equal groups visually", "b": "They measure liquid volume exclusively always", "c": "They replace the need for number sense entirely", "d": "They only work for division never multiplication"},
         "a", "Array rows × columns represents multiplication of factors.",
         {"b": "Volume uses different models.", "c": "Number sense still essential.", "d": "Arrays show both operations."}, "medium"),
        ("Rounding 687 to the nearest hundred gives:",
         {"a": "600", "b": "700", "c": "690", "d": "680"},
         "b", "87 ≥ 50, so round up to 700.",
         {"a": "Would round down if tens were 0-49.", "c": "Nearest ten not hundred.", "d": "Not standard hundred rounding."}, "medium"),
        ("A bar graph best displays:",
         {"a": "Categorical data compared across groups", "b": "Continuous temperature change over every minute for a year exclusively always better in line graph", "c": "Exact molecular structures", "d": "Random unlabeled pictures only"},
         "a", "Bar graphs compare discrete categories.",
         {"b": "Line graphs often better for continuous time series.", "c": "Chemistry diagrams.", "d": "Needs labels/data."}, "medium"),
        ("If one pencil costs 25 cents, 4 pencils cost:",
         {"a": "$0.75", "b": "$1.00", "c": "$1.25", "d": "$4.25"},
         "b", "4 × $0.25 = $1.00.",
         {"a": "3 pencils.", "c": "5 pencils.", "d": "Added dollar incorrectly."}, "easy"),
        ("Congruent figures have:",
         {"a": "Same size and same shape", "b": "Same shape only with different sizes always", "c": "Different shapes and sizes always", "d": "Only the same color"},
         "a", "Congruence means identical shape and size.",
         {"b": "Similar not congruent.", "c": "Not congruent.", "d": "Color irrelevant."}, "easy"),
        ("Estimating 298 + 512 by rounding to nearest hundred:",
         {"a": "700", "b": "800", "c": "810 exactly always required", "d": "600"},
         "b", "300 + 500 = 800 estimate.",
         {"a": "Under-estimate.", "c": "Estimate not exact sum.", "d": "Too low."}, "medium"),
    ])

    qs += pack(E, "social", [
        ("The three branches of U.S. government are:",
         {"a": "Legislative, executive, judicial", "b": "Federal, state, local only as branches", "c": "Army, navy, air force exclusively", "d": "City, county, township as national branches"},
         "a", "Separation of powers: Congress, President, Courts.",
         {"b": "Levels of government, not branches.", "c": "Military not branches.", "d": "Local divisions."}, "easy"),
        ("Primary sources in history include:",
         {"a": "Letters, diaries, and photographs from the time period studied", "b": "Modern textbooks summarizing events only always", "c": "Fictional novels with no historical basis always classified primary", "d": "Teacher-made worksheets exclusively always"},
         "a", "Primary sources are firsthand evidence from the period.",
         {"b": "Secondary sources interpret primary.", "c": "Fiction is not primary evidence.", "d": "Worksheets are not period artifacts."}, "medium"),
        ("A map scale of 1 inch = 10 miles helps students:",
         {"a": "Convert map distances to real-world distances", "b": "Measure temperature in Celsius exclusively", "c": "Calculate chemical moles always", "d": "Determine reading fluency rates"},
         "a", "Scale relates map units to ground distance.",
         {"b": "Weather metric.", "c": "Chemistry.", "d": "Reading assessment."}, "easy"),
        ("Goods and services: a haircut is an example of:",
         {"a": "A service", "b": "A good only always", "c": "Natural resource extraction exclusively", "d": "Import tariff"},
         "a", "Services are intangible actions; goods are physical products.",
         {"b": "Not a tangible good.", "c": "Not extraction.", "d": "Trade policy."}, "easy"),
        ("The Constitution's Preamble begins 'We the People,' indicating:",
         {"a": "Government derives authority from the governed", "b": "Only landowners could ever participate in government always historically and today without change", "c": "States have no role in the union", "d": "Judges write all laws exclusively"},
         "a", "Popular sovereignty is a founding principle.",
         {"b": "Participation expanded over time.", "c": "Federal system includes states.", "d": "Legislature makes laws."}, "medium"),
        ("Urban, suburban, and rural communities differ mainly in:",
         {"a": "Population density and land use patterns", "b": "Only the language spoken always", "c": "Presence of gravity exclusively", "d": "Number of days in a year"},
         "a", "Community types reflect density, jobs, and environment.",
         {"b": "Language varies independently.", "c": "Physical law same.", "d": "Calendar constant."}, "easy"),
        ("Supply and demand: if lemonade is popular on a hot day, price may:",
         {"a": "Increase because demand rises", "b": "Always fall to zero automatically", "c": "Become unrelated to buyers' interest always", "d": "Be set only by weather satellites exclusively"},
         "a", "Higher demand with limited supply tends to raise equilibrium price.",
         {"b": "Opposite typical effect.", "c": "Demand affects price.", "d": "Market forces/local sellers."}, "medium"),
        ("A responsibility of citizenship includes:",
         {"a": "Obeying laws and participating in community when appropriate", "b": "Ignoring all elections always", "c": "Refusing jury duty without any civic context ever for everyone always", "d": "Only consuming goods without community engagement"},
         "a", "Civic responsibilities include lawful behavior and participation.",
         {"b": "Voting/participation encouraged.", "c": "Jury service may be duty.", "d": "Engagement matters."}, "easy"),
        ("Timelines help historians and students:",
         {"a": "Sequence events chronologically to see cause and effect", "b": "Randomize dates without order always", "c": "Eliminate geography from study always", "d": "Measure liquid volume exclusively"},
         "a", "Chronology clarifies relationships among events.",
         {"b": "Timelines impose order.", "c": "History uses geography too.", "d": "Math/science measure."}, "easy"),
        ("The Bill of Rights refers to the first:",
         {"a": "Ten amendments to the U.S. Constitution", "b": "Three articles of the Constitution only", "c": "Fifty state constitutions collectively always", "d": "Presidential executive orders exclusively"},
         "a", "Amendments 1-10 protect individual liberties.",
         {"b": "Original articles structure government.", "c": "State docs separate.", "d": "Not Bill of Rights."}, "medium"),
        ("Geography: hemispheres divide Earth by:",
         {"a": "Equator and prime meridian into northern/southern and eastern/western", "b": "Only mountain ranges exclusively always", "c": "Population count only", "d": "Ocean salinity exclusively always"},
         "a", "Equator (0° lat) and Prime Meridian (0° long) define hemispheres.",
         {"b": "Physical features don't define hemispheres.", "c": "Demographic not hemispheric.", "d": "Salinity unrelated."}, "easy"),
        ("Cultural diversity in the classroom should be addressed by:",
         {"a": "Including diverse perspectives and respectful discussion in curriculum", "b": "Ignoring student backgrounds entirely always", "c": "Stereotyping groups for simplicity always", "d": "Prohibiting any mention of culture ever"},
         "a", "Inclusive curriculum validates identities and builds understanding.",
         {"b": "Backgrounds matter for learning.", "c": "Stereotypes harmful.", "d": "Appropriate cultural content helps."}, "medium"),
        ("Local government services often include:",
         {"a": "Police, fire protection, parks, and public schools (depending on district)", "b": "Printing currency for the entire nation exclusively always", "c": "Declaring war on foreign nations exclusively", "d": "Operating the International Space Station exclusively always"},
         "a", "Municipalities provide community services and infrastructure.",
         {"b": "Federal Treasury/Fed roles.", "c": "Federal war powers.", "d": "NASA/federal."}, "easy"),
        ("An election in a democracy allows citizens to:",
         {"a": "Choose representatives and influence policy", "b": "Eliminate all laws permanently by voting once", "c": "Avoid all civic duties forever after one vote always", "d": "Replace courts with personal decisions exclusively always"},
         "a", "Voting is a key democratic participation mechanism.",
         {"b": "Laws persist through institutions.", "c": "Ongoing citizenship.", "d": "Rule of law remains."}, "easy"),
        ("A secondary source in social studies might be:",
         {"a": "A historian's textbook chapter analyzing the Civil War", "b": "A soldier's original 1863 diary entry always classified secondary", "c": "An unlabeled photograph with no context always primary without question", "d": "A raw census record from 1880 always secondary always"},
         "a", "Secondary sources interpret/analyze primary evidence.",
         {"b": "Diary is primary.", "c": "Period photo can be primary with context.", "d": "Census record is primary data."}, "hard"),
    ])

    qs += pack(E, "science", [
        ("States of matter include solid, liquid, and:",
         {"a": "Gas", "b": "Sound", "c": "Light", "d": "Energy only as a fourth state always exclusively"},
         "a", "Common three states; plasma is fourth at higher level.",
         {"b": "Sound is vibration.", "c": "Light is radiation.", "d": "Energy not a state of matter."}, "easy"),
        ("Plants make food through photosynthesis using:",
         {"a": "Sunlight, water, and carbon dioxide", "b": "Only rocks and metal exclusively always", "c": "Oxygen alone as the only input always", "d": "Moonlight exclusively without chlorophyll ever"},
         "a", "Photosynthesis converts light energy to chemical energy in glucose.",
         {"b": "Not plant nutrients.", "c": "CO₂ and H₂O needed; O₂ is product.", "d": "Sunlight/chlorophyll needed."}, "easy"),
        ("The water cycle includes evaporation, condensation, and:",
         {"a": "Precipitation", "b": "Fermentation exclusively always", "c": "Subduction of tectonic plates only in all water cycle diagrams always", "d": "Combustion of fossil fuels as the only step always"},
         "a", "Water cycles through evaporation, condensation, precipitation, collection.",
         {"b": "Biological process.", "c": "Geology separate.", "d": "Human activity not sole step."}, "easy"),
        ("A food chain shows flow of:",
         {"a": "Energy from producers to consumers", "b": "Money in an economy exclusively always", "c": "Electric current in circuits only always in ecology units always", "d": "Votes in elections exclusively always"},
         "a", "Energy transfers between trophic levels; much lost as heat.",
         {"b": "Economics.", "c": "Physics context.", "d": "Civics."}, "easy"),
        ("Magnets attract objects made of:",
         {"a": "Iron, nickel, and cobalt (magnetic materials)", "b": "All plastics universally always", "c": "Only wood exclusively always", "d": "Pure water always strongly"},
         "a", "Ferromagnetic materials respond strongly to magnets.",
         {"b": "Most plastics not magnetic.", "c": "Wood not magnetic.", "d": "Water weakly diamagnetic not attracted."}, "easy"),
        ("Living things share characteristics including:",
         {"a": "Growth, reproduction, response to environment, and use of energy", "b": "Permanent unchanging size always", "c": "No need for water ever", "d": "Inability to adapt in any way always"},
         "a", "Life processes include metabolism, growth, reproduction, adaptation.",
         {"b": "Organisms grow.", "c": "Water essential for life.", "d": "Adaptation occurs."}, "easy"),
        ("Weather differs from climate because weather is:",
         {"a": "Short-term atmospheric conditions; climate is long-term patterns", "b": "Always identical worldwide daily always", "c": "Measured only in centuries for a single hour always", "d": "Unrelated to temperature or precipitation ever"},
         "a", "Weather is day-to-day; climate is average over decades.",
         {"b": "Varies locally.", "c": "Weather is short-term.", "d": "Both involve temperature/precip."}, "medium"),
        ("Simple machines include a lever, pulley, and:",
         {"a": "Inclined plane", "b": "Battery exclusively always as a simple machine always", "c": "Microscope always classified as simple machine always", "d": "Computer processor chip exclusively always"},
         "a", "Classic six simple machines include inclined plane, wedge, screw, lever, pulley, wheel and axle.",
         {"b": "Energy source not simple machine.", "c": "Compound optical instrument.", "d": "Electronic device."}, "medium"),
        ("An ecosystem consists of:",
         {"a": "Living organisms and their nonliving environment interacting", "b": "Only abiotic rocks with no organisms ever always", "c": "Laboratory glassware exclusively always", "d": "Historical documents exclusively always"},
         "a", "Ecosystem = biotic + abiotic components in an area.",
         {"b": "Biotic part essential.", "c": "Equipment.", "d": "Social studies."}, "easy"),
        ("The skeleton supports the body and:",
         {"a": "Protects internal organs and works with muscles for movement", "b": "Produces all plant food through photosynthesis always in humans always", "c": "Pumps blood as its primary function exclusively always", "d": "Filters air in the lungs exclusively always"},
         "a", "Bones support, protect, store minerals, enable movement via muscles.",
         {"b": "Plants photosynthesize.", "c": "Heart pumps blood.", "d": "Lungs gas exchange."}, "medium"),
        ("Conductors of electricity include:",
         {"a": "Metals like copper", "b": "Dry rubber as best conductor always in all cases always", "c": "Pure distilled water often without ions as excellent conductor always", "d": "Glass typically as superior conductor to copper always"},
         "a", "Metals have free electrons facilitating current flow.",
         {"b": "Rubber insulates.", "c": "Pure water poor conductor.", "d": "Glass insulates."}, "medium"),
        ("The Sun appears to move across the sky because:",
         {"a": "Earth rotates on its axis", "b": "The Sun orbits Earth each day exclusively in modern science model always", "c": "Moon blocks the Sun continuously always", "d": "Stars push the Sun across daily always"},
         "a", "Daily apparent motion is due to Earth's rotation.",
         {"b": "Heliocentric model: Earth rotates.", "c": "Moon phase not continuous block.", "d": "Not causal."}, "medium"),
        ("A hypothesis is:",
         {"a": "A testable explanation for an observation", "b": "A proven scientific law always after one trial always", "c": "An opinion with no evidence ever allowed always", "d": "The final conclusion after many replicated studies always exclusively"},
         "a", "Hypothesis is proposed explanation tested by experiment.",
         {"b": "Laws/theories require extensive evidence.", "c": "Science uses evidence.", "d": "That's theory/law status."}, "easy"),
        ("Recycling reduces waste by:",
         {"a": "Reusing materials to decrease resource extraction and landfill use", "b": "Increasing landfill volume always as primary goal always", "c": "Eliminating all energy use globally always instantly", "d": "Preventing decomposition entirely in all ecosystems always"},
         "a", "Recycling conserves resources and reduces pollution.",
         {"b": "Opposite goal.", "c": "Recycling uses some energy.", "d": "Decomposition natural."}, "easy"),
        ("Inherited traits in animals come from:",
         {"a": "Genes passed from parents to offspring", "b": "Only learned behaviors with no biological basis always exclusively always", "c": "Weather on the day of birth exclusively always", "d": "Teacher instruction in classroom exclusively always biologically"},
         "a", "Heredity transmits genetic information for traits.",
         {"b": "Learned vs inherited differ.", "c": "Not genetic mechanism.", "d": "Learning not inheritance."}, "medium"),
    ])

    return qs


if __name__ == "__main__":
    write_bank(E, build())
