#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "series-79-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "valuation", [
        ("A DCF valuation discounts projected free cash flows using:",
         {"a": "The risk-free rate only", "b": "A discount rate reflecting the risk of the cash flows (often WACC for enterprise value)", "c": "The prime rate without adjustment", "d": "Historical book value growth"},
         "b", "DCF uses a risk-adjusted discount rate; WACC is common for unlevered FCF to firm value.",
         {"a": "Ignores business and financial risk.", "c": "Prime is not a standard DCF discount rate.", "d": "Book value is accounting, not cash-flow valuation."}, "medium"),
        ("Enterprise Value is typically calculated as:",
         {"a": "Market cap minus net debt", "b": "Market cap plus net debt (and sometimes minority interest/preferred)", "c": "Revenue times P/E", "d": "EBITDA only"},
         "b", "EV = equity value + net debt (and other claims as applicable).",
         {"a": "Subtracting debt gives equity, not EV.", "c": "Mixes unrelated multiples.", "d": "EBITDA is a metric, not EV definition."}, "easy"),
        ("In comparable company analysis, the peer group should:",
         {"a": "Include only the target company", "b": "Reflect similar business models, size, growth, and risk profiles", "c": "Exclude all public companies", "d": "Use only companies in bankruptcy"},
         "b", "Comps require genuinely comparable operating and financial characteristics.",
         {"a": "Single-company group is not comparative.", "c": "Public comps are standard.", "d": "Distressed peers skew multiples unless that is the thesis."}, "easy"),
        ("EV/EBITDA is often preferred over P/E when comparing firms because EBITDA:",
         {"a": "Eliminates all capital structure effects on the multiple", "b": "Is before interest and often used to compare firms with different leverage", "c": "Equals free cash flow exactly", "d": "Is always audited net income"},
         "b", "EV/EBITDA neutralizes some leverage/tax differences vs equity multiples.",
         {"a": "EV still embeds capital structure in the numerator.", "c": "FCF requires capex and working capital.", "d": "EBITDA is non-GAAP earnings proxy."}, "medium"),
        ("Terminal value in a DCF often uses the Gordon Growth model: TV = FCF × (1+g) / (WACC − g). If g exceeds WACC:",
         {"a": "The model is mathematically invalid (denominator negative)", "b": "The company is worth zero", "c": "Terminal value equals zero automatically", "d": "WACC must be ignored"},
         "a", "Perpetual growth must be less than the discount rate or TV explodes/negative.",
         {"b": "Not the defined outcome.", "c": "Formula breaks, not zero.", "d": "WACC is essential."}, "hard"),
        ("Precedent transaction multiples typically include a control premium because:",
         {"a": "Buyers pay for 100% control and expected synergies", "b": "Public trading prices always exceed deal prices", "c": "Sellers never negotiate", "d": "Debt is excluded from all deal math"},
         "a", "Control transactions often price above minority trading levels.",
         {"b": "Usually opposite: deals often at premium to unaffected price.", "c": "False.", "d": "Deal EV includes assumed debt."}, "medium"),
        ("Net Working Capital in M&A models usually excludes:",
         {"a": "Accounts receivable", "b": "Cash and short-term debt (often treated separately in definitions)", "c": "Inventory", "d": "Accounts payable"},
         "b", "Cash/debt often carved out; NWC definitions vary but cash is frequently excluded from operating NWC.",
         {"a": "AR is typically operating NWC.", "c": "Inventory is operating.", "d": "AP is operating."}, "hard"),
        ("A 10% increase in projected terminal growth rate, all else equal, generally:",
         {"a": "Decreases DCF value", "b": "Increases DCF value (sometimes materially)", "c": "Has no effect on value", "d": "Only affects the income statement"},
         "b", "Higher perpetual growth raises terminal value and total DCF.",
         {"a": "Opposite effect.", "c": "Terminal value is sensitive to g.", "d": "Valuation impact is direct."}, "medium"),
        ("Liquidation valuation is most appropriate when:",
         {"a": "The company is a going concern with strong growth", "b": "Assets are sold piecemeal and the firm ceases operations", "c": "Public comps trade at premium multiples", "d": "Management plans a dividend recap only"},
         "b", "Liquidation values assets at disposal, not ongoing operations.",
         {"a": "Going concern uses DCF/comps.", "c": "Unrelated.", "d": "Recap is different scenario."}, "easy"),
        ("Beta in CAPM measures:",
         {"a": "Total firm risk including diversifiable risk only", "b": "Systematic risk relative to the market", "c": "Credit spread on bonds", "d": "Inventory turnover"},
         "b", "Beta captures market-related (systematic) equity risk.",
         {"a": "Diversifiable risk is not priced in CAPM.", "c": "Different concept.", "d": "Operating metric."}, "easy"),
        ("Sum-of-the-parts valuation is used when:",
         {"a": "A conglomerate's segments have different risk/peer sets", "b": "Only one product line exists", "c": "Debt cannot be measured", "d": "Taxes are always zero"},
         "a", "SOTP values divisions separately then aggregates.",
         {"b": "Single segment usually uses one comp set.", "c": "Debt is still considered at corporate level.", "d": "Taxes matter."}, "medium"),
        ("Unlevered free cash flow is also called:",
         {"a": "Free cash flow to the firm (FCFF) before financing costs", "b": "Dividends paid only", "c": "Net income after interest only", "d": "Cash from financing activities"},
         "a", "FCFF/UFCF is available to all capital providers before financing flows.",
         {"b": "Equity cash flow subset.", "c": "Levered measure.", "d": "CFF is financing section."}, "medium"),
        ("A football field chart in an pitch book displays:",
         {"a": "Only one valuation method", "b": "Ranges from multiple valuation methodologies side by side", "c": "Historical stock prices only", "d": "Employee org chart"},
         "b", "Football fields summarize DCF, comps, precedents, and other ranges visually.",
         {"a": "Purpose is comparison across methods.", "c": "May include but not sole purpose.", "d": "Unrelated."}, "easy"),
        ("If net debt is $200M and market cap is $800M, Enterprise Value is approximately:",
         {"a": "$600M", "b": "$1,000M", "c": "$200M", "d": "$800M"},
         "b", "EV ≈ $800M + $200M = $1,000M.",
         {"a": "Subtracting debt gives equity-like math.", "c": "Debt alone is not EV.", "d": "That is equity value only."}, "easy"),
        ("Sensitivity analysis in a DCF model primarily helps bankers:",
         {"a": "Guarantee the exact transaction price", "b": "Show how value changes with key assumptions (WACC, growth, margins)", "c": "Eliminate the need for comps", "d": "Replace legal due diligence"},
         "b", "Sensitivities illustrate assumption risk and valuation range.",
         {"a": "Valuation is a range, not guarantee.", "c": "Comps still inform market.", "d": "Legal DD is separate."}, "easy"),
    ])

    qs += pack(E, "mna", [
        ("In a stock-for-stock merger, dilution to the acquirer's EPS occurs when:",
         {"a": "The target's earnings contribution per new share issued is less than the acquirer's pre-deal EPS", "b": "The deal is 100% cash", "c": "Synergies are always zero", "d": "The target has no shares outstanding"},
         "a", "Accretion/dilution compares incremental EPS from the target vs cost of new shares.",
         {"b": "Cash deals don't issue stock.", "c": "Synergies affect outcome but aren't the definition.", "d": "Stock deals require target shares."}, "medium"),
        ("A material adverse change (MAC) clause in an M&A agreement typically:",
         {"a": "Allows either party to walk away if a defined catastrophic change occurs", "b": "Guarantees closing regardless of conditions", "c": "Sets the exchange ratio permanently", "d": "Replaces all antitrust review"},
         "a", "MAC/MAE clauses define extraordinary events permitting termination.",
         {"b": "Conditions still apply.", "c": "Different provision.", "d": "Regulatory review remains."}, "medium"),
        ("Synergies in merger models are often discounted because:",
         {"a": "They may not be fully realized and timing is uncertain", "b": "Regulators require zero synergies", "c": "Synergies always exceed purchase price", "d": "They are tax penalties"},
         "a", "Execution risk leads banks to haircut synergy values in presentations.",
         {"b": "False.", "c": "Not always.", "d": "Synergies can be cost or revenue."}, "easy"),
        ("A tender offer differs from a negotiated merger because:",
         {"a": "It directly offers to buy shares from public holders, often bypassing target board negotiation initially", "b": "It can only buy bonds", "c": "It never requires SEC filings", "d": "It is always friendly"},
         "a", "Tender offers are direct purchases, sometimes hostile.",
         {"b": "Equity focused.", "c": "Schedule TO and other filings apply.", "d": "Can be hostile."}, "medium"),
        ("Purchase price allocation after an acquisition assigns excess purchase price primarily to:",
         {"a": "Goodwill and identifiable intangible assets per acquisition accounting", "b": "Daily operating expenses only", "c": "Treasury stock automatically", "d": "Accounts payable exclusively"},
         "a", "ASC 805/IFRS 3 require fair value of assets and goodwill for excess.",
         {"b": "Not expensed immediately as operating.", "c": "Different concept.", "d": "Too narrow."}, "hard"),
        ("A break-up fee (termination fee) in a merger agreement:",
         {"a": "Compensates a party if the deal fails under specified circumstances", "b": "Is paid to all shareholders daily", "c": "Replaces the exchange ratio", "d": "Eliminates shareholder votes"},
         "a", "Break fees allocate cost of failed transactions contractually.",
         {"b": "Not a dividend.", "c": "Separate term.", "d": "Votes may still be required."}, "easy"),
        ("Due diligence in sell-side M&A typically covers:",
         {"a": "Only marketing slogans", "b": "Financial, legal, tax, operational, and commercial review of the target", "c": "Employee vacation schedules only", "d": "Nothing if the buyer is strategic"},
         "b", "Comprehensive DD reduces surprise liabilities and supports valuation.",
         {"a": "Insufficient.", "c": "HR may be included but not sole focus.", "d": "DD always matters."}, "easy"),
        ("A reverse merger occurs when:",
         {"a": "A private company merges into a public shell to become public", "b": "Two identical companies combine", "c": "Only debt is exchanged", "d": "The acquirer delists voluntarily always"},
         "a", "Reverse mergers use public shells for listing without traditional IPO.",
         {"b": "Not the definition.", "c": "Equity structure change.", "d": "Outcome varies."}, "medium"),
        ("Regulatory HSR filing in the U.S. is primarily concerned with:",
         {"a": "Antitrust/competition review for qualifying transactions", "b": "Securities registration of all bonds", "c": "Environmental permits only", "d": "Insider trading of target officers only"},
         "a", "Hart-Scott-Rodino governs premerger notification for large deals.",
         {"b": "SEC registration is separate.", "c": "May be part of broader DD.", "d": "Not HSR's core."}, "medium"),
        ("An earnout structure pays additional consideration if:",
         {"a": "Post-closing performance milestones are met", "b": "The buyer defaults on debt", "c": "Stock market falls 10%", "d": "Employees resign on day one"},
         "a", "Earnouts bridge valuation gaps using future performance metrics.",
         {"b": "Default is credit event.", "c": "Not typical trigger.", "d": "Unrelated."}, "easy"),
        ("In a leveraged buyout, returns to sponsors are driven primarily by:",
         {"a": "Debt paydown, EBITDA growth, and exit multiple", "b": "Only dividend policy of unrelated firms", "c": "Elimination of all operating risk", "d": "Government grants only"},
         "a", "LBO returns come from deleveraging, growth, and multiple expansion/contraction.",
         {"b": "Too narrow.", "c": "Risk remains.", "d": "Not primary driver."}, "medium"),
        ("A fairness opinion is typically provided by:",
         {"a": "The target's board financial adviser regarding consideration fairness from a financial point of view", "b": "Any employee without qualifications", "c": "The IRS exclusively", "d": "Retail shareholders individually"},
         "a", "Fairness opinions support board fiduciary decisions.",
         {"b": "Requires qualified financial adviser.", "c": "Tax authority doesn't issue fairness opinions.", "d": "Board-level document."}, "easy"),
        ("Covenants in acquisition financing may restrict:",
         {"a": "Additional debt, asset sales, and dividends to protect lenders", "b": "Only office paint colors", "c": "All revenue growth", "d": "Buyer integration planning always"},
         "a", "Credit agreements include maintenance/incurrence covenants.",
         {"b": "Nonsense.", "c": "Growth isn't banned.", "d": "Integration continues."}, "medium"),
        ("A spin-off creates value for shareholders partly by:",
         {"a": "Allowing separate valuation of distinct businesses", "b": "Eliminating all public reporting", "c": "Combining unrelated conglomerates", "d": "Mandatory delisting"},
         "a", "Sum-of-parts unlock often motivates spin-offs.",
         {"b": "Spin-offs remain public often.", "c": "Opposite of separation.", "d": "Many spin-offs are listed."}, "medium"),
        ("Pro forma combined financial statements in a merger model show:",
         {"a": "Historical results only of the acquirer", "b": "Adjusted combined results as if the transaction occurred at a specified date", "c": "Only the target's balance sheet alone", "d": "Cash flow with no adjustments"},
         "b", "Pro forma reflects combined entity with purchase accounting adjustments.",
         {"a": "Too narrow.", "c": "Combined view needed.", "d": "Adjustments are central."}, "easy"),
    ])

    qs += pack(E, "products", [
        ("In an IPO, the greenshoe (overallotment) option allows underwriters to:",
         {"a": "Sell up to 15% additional shares if demand exceeds the offering", "b": "Cancel the registration statement permanently", "c": "Avoid SEC review", "d": "Pay no commissions"},
         "a", "Greenshoe stabilizes pricing by covering short position or issuing extra shares.",
         {"b": "Registration continues.", "c": "SEC review still required.", "d": "Compensation still applies."}, "medium"),
        ("A follow-on offering by an already public company is called:",
         {"a": "An initial public offering", "b": "A secondary/follow-on offering (primary or secondary shares depending on structure)", "c": "A private placement to one investor only always", "d": "A tender offer for control always"},
         "b", "Follow-ons raise additional equity after listing.",
         {"a": "IPO is first public sale.", "c": "Can be broadly marketed registered offering.", "d": "Different transaction type."}, "easy"),
        ("High-yield bond offerings are primarily sold to:",
         {"a": "Retail bank depositors with FDIC insurance", "b": "Institutional investors accepting higher credit risk for yield", "c": "Only municipal issuers", "d": "Federal Reserve discount window"},
         "b", "HY bonds target institutional buyers seeking yield over IG credit.",
         {"a": "Not bank deposits.", "c": "Corporate issuers.", "d": "Not applicable."}, "easy"),
        ("A convertible bond gives holders:",
         {"a": "The option to convert into common stock at a set ratio/price", "b": "Voting rights without conversion", "c": "FDIC insurance", "d": "Mandatory immediate conversion at issuance always"},
         "a", "Convertibles combine debt with equity conversion option.",
         {"b": "Conversion is optional typically.", "c": "Not insured.", "d": "Usually optional conversion."}, "easy"),
        ("Rule 144A offerings allow U.S. issuers to sell securities to:",
         {"a": "Qualified institutional buyers without full SEC registration in many cases", "b": "Any retail investor without disclosure", "c": "Only foreign governments", "d": "Unaccredited investors freely"},
         "a", "144A is a common private placement exemption for QIBs.",
         {"b": "Retail requires registration or other exemption.", "c": "Broader QIB market.", "d": "Accredited/QIB limits apply."}, "medium"),
        ("In a bought deal, underwriters:",
         {"a": "Commit to purchase securities from the issuer and resell them", "b": "Only act as agents with no capital risk", "c": "Never price the offering", "d": "Avoid all disclosure"},
         "a", "Bought deals shift risk to underwriters vs best efforts.",
         {"b": "That is best efforts.", "c": "Underwriters set price.", "d": "Disclosure still required."}, "medium"),
        ("A PIPE transaction typically involves:",
         {"a": "Private investment in public equity, often at a discount with registration rights", "b": "Only municipal general obligation bonds", "c": "IPO roadshow marketing only", "d": "Retail branch banking deposits"},
         "a", "PIPEs sell registered/unregistered equity privately to institutions.",
         {"b": "Equity not munis.", "c": "Different from IPO marketing.", "d": "Unrelated."}, "medium"),
        ("Investment-grade debt is commonly rated:",
         {"a": "BBB-/Baa3 and above by major agencies ( nomenclature varies slightly )", "b": "CCC and below only", "c": "Unrated always", "d": "Only by equity analysts"},
         "a", "IG threshold is roughly BBB-/Baa3 and higher.",
         {"b": "That is high yield.", "c": "Many IG bonds are rated.", "d": "Credit ratings agencies."}, "easy"),
        ("A shelf registration (S-3) allows issuers to:",
         {"a": "Register securities in advance and offer them over time as market conditions allow", "b": "Avoid all future SEC filings forever", "c": "Sell only to employees", "d": "Issue unlimited unregistered stock without limits"},
         "a", "Shelf offerings provide flexibility for timely capital raises.",
         {"b": "Ongoing reporting continues.", "c": "Can be broader.", "d": "Still regulated."}, "medium"),
        ("Bookbuilding in an equity offering refers to:",
         {"a": "Collecting institutional indications of interest to set final price/allocation", "b": "Physical printing of stock certificates only", "c": "Auditing historical financials only", "d": "Filing Form 10-K annually"},
         "a", "Bookbuilding gathers demand to price and allocate shares.",
         {"b": "Legacy process, not definition.", "c": "Part of prep but not bookbuilding.", "d": "Annual report filing."}, "easy"),
        ("A rights offering gives existing shareholders:",
         {"a": "The pro rata right to purchase additional shares, often at a discount", "b": "Mandatory sale of all holdings", "c": "No choice in participation ever", "d": "Only bond conversion rights"},
         "a", "Rights offerings protect dilution by offering shares to existing holders.",
         {"b": "Voluntary participation typical.", "c": "Can renounce or exercise.", "d": "Equity issuance."}, "medium"),
        ("Mezzanine financing in LBOs often sits:",
         {"a": "Between senior debt and equity in the capital structure", "b": "Above senior secured bank debt in priority always", "c": "Only as common stock", "d": "As government grants"},
         "a", "Mezz is subordinated debt or preferred with equity-like features.",
         {"b": "Usually junior to senior.", "c": "Debt/preferred hybrid.", "d": "Private capital."}, "medium"),
        ("A block trade is:",
         {"a": "A large sale of stock arranged quickly, often at a discount to market", "b": "A small retail order", "c": "Only an IPO allocation", "d": "A municipal refunding exclusively"},
         "a", "Blocks facilitate large holder liquidity off-market or accelerated.",
         {"b": "Size distinguishes blocks.", "c": "Secondary market tool too.", "d": "Different product."}, "easy"),
        ("Regulation S offerings are directed at:",
         {"a": "Offshore non-U.S. persons with distribution compliance periods", "b": "Only U.S. retail investors", "c": "Federal employee retirement accounts only", "d": "Unregistered insider trades"},
         "a", "Reg S provides safe harbor for offshore offerings.",
         {"b": "U.S. persons restricted during compliance period.", "c": "Too narrow.", "d": "Illegal if insider MNPI."}, "hard"),
        ("Underwriting spread is:",
         {"a": "The difference between what underwriters pay the issuer and the public offering price", "b": "The stock's beta", "c": "The company's tax rate", "d": "Interest on bank lines only"},
         "a", "Spread compensates underwriters for risk and distribution.",
         {"b": "Risk metric.", "c": "Tax concept.", "d": "Different from equity spread."}, "easy"),
    ])

    qs += pack(E, "regulations", [
        ("FINRA Series 79 qualifies individuals to participate in:",
         {"a": "Investment banking representative activities including M&A and underwriting", "b": "Real estate brokerage only", "c": "Insurance variable annuity sales only", "d": "Medical licensing"},
         "a", "Series 79 is the Investment Banking Representative exam.",
         {"b": "Different license.", "c": "Series 6/7 territory.", "d": "Unrelated."}, "easy"),
        ("Section 5 of the Securities Act of 1933 generally requires:",
         {"a": "Registration or valid exemption before interstate sale of securities", "b": "No disclosure ever", "c": "Only oral offers without documentation", "d": "State insurance approval for all stocks"},
         "a", "Securities must be registered or exempt to be sold legally.",
         {"b": "Disclosure is core.", "c": "Prospectus rules apply.", "d": "Securities regulators, not insurance."}, "medium"),
        ("Regulation D Rule 506(b) offerings:",
         {"a": "Permit unlimited accredited investors and up to 35 sophisticated non-accredited with no general solicitation", "b": "Allow broad advertising to all retail investors", "c": "Require SEC registration always", "d": "Prohibit any sales to institutions"},
         "a", "506(b) is private placement without general solicitation.",
         {"b": "506(c) allows general solicitation with verified accredited.", "c": "Exempt offering.", "d": "Institutions often participate."}, "hard"),
        ("The Securities Exchange Act of 1934 primarily regulates:",
         {"a": "Secondary market trading and ongoing reporting of public companies", "b": "Only initial public offerings exclusively", "c": "Agricultural commodities exclusively", "d": "Bank deposit insurance"},
         "a", "1934 Act covers exchanges, broker-dealers, and periodic reporting.",
         {"b": "1933 Act focuses more on primary offerings.", "c": "Broader securities.", "d": "FDIC domain."}, "medium"),
        ("Insider trading liability under classical theory requires:",
         {"a": "Trading on material nonpublic information in breach of a duty", "b": "Trading only after press release with public information", "c": "Buying only index funds", "d": "Disclosing all trades to FINRA examiners daily"},
         "a", "Classical insider trading: MNPI plus duty breach.",
         {"b": "Public info is permitted.", "c": "Not the test.", "d": "Reporting rules differ."}, "medium"),
        ("A Form S-1 registration statement includes:",
         {"a": "Prospectus disclosures about business, risks, and financials for an IPO", "b": "Only the CEO's biography without financials", "c": "Trade secrets without any risk factors", "d": "Insurance policy applications"},
         "a", "S-1 is the standard IPO registration with comprehensive disclosure.",
         {"b": "Financial statements required.", "c": "Risk factors mandatory.", "d": "Unrelated."}, "easy"),
        ("FINRA Rule 2241 governs:",
         {"a": "Conflicts of interest related to equity research and public offerings", "b": "Plumbing code inspections", "c": "Aircraft maintenance logs", "d": "Hospital HIPAA privacy exclusively"},
         "a", "2241 restricts tying research to investment banking compensation.",
         {"b": "Unrelated.", "c": "Unrelated.", "d": "HIPAA is healthcare."}, "hard"),
        ("Quiet period after an IPO registration generally restricts:",
         {"a": "Issuer and syndicate comments that could hype the offering beyond the prospectus", "b": "All trading on exchanges forever", "c": "Audited financial statement preparation", "d": "Employee hiring"},
         "a", "Gun-jumping rules limit pre-offering publicity beyond filed materials.",
         {"b": "Trading begins after offering.", "c": "Audits continue.", "d": "Operations continue."}, "medium"),
        ("Beneficial ownership reporting for >5% holders often uses:",
         {"a": "Schedule 13D or 13G under Exchange Act Section 13(d)", "b": "Form 1040 only", "c": "Blue sky insurance forms only", "d": "NOI to EPA exclusively"},
         "a", "13D/G disclose active/passive >5% positions.",
         {"b": "Personal tax form.", "c": "State securities may add but SEC uses 13D/G.", "d": "Environmental."}, "medium"),
        ("Underwriter due diligence defense under Section 11 relates to:",
         {"a": "Reasonable investigation of registration statement disclosures", "b": "Guaranteed stock price performance", "c": "Avoiding all liability regardless of fraud", "d": "Only municipal bond defaults"},
         "a", "Due diligence can mitigate Section 11 liability for underwriters.",
         {"b": "No performance guarantee.", "c": "Fraud still actionable.", "d": "Section 11 applies to registered offerings broadly."}, "hard"),
        ("Regulation FD requires issuers to:",
         {"a": "Disclose material information broadly when selectively disclosed to certain parties", "b": "Never communicate with investors", "c": "File only paper documents", "d": "Pay dividends monthly by law"},
         "a", "FD prevents selective disclosure; public dissemination required.",
         {"b": "Communication allowed with fairness.", "c": "Electronic filing standard.", "d": "No such mandate."}, "medium"),
        ("A broker-dealer acting as underwriter in a firm commitment offering:",
         {"a": "May hold unsold securities on its balance sheet temporarily", "b": "Never takes capital risk", "c": "Is exempt from FINRA membership", "d": "Cannot distribute to institutions"},
         "a", "Firm commitment underwriters buy and resell, bearing risk.",
         {"b": "That is best efforts.", "c": "FINRA membership typically required.", "d": "Institutions are key buyers."}, "easy"),
        ("Blue sky laws are:",
         {"a": "State securities registration and anti-fraud regulations", "b": "Federal aviation rules", "c": "International maritime treaties only", "d": "OSHA workplace standards exclusively"},
         "a", "States regulate securities offerings and sales within their borders.",
         {"b": "FAA.", "c": "Not primary definition.", "d": "OSHA."}, "easy"),
        ("Section 16(b) short-swing profit rule applies to:",
         {"a": "Officers, directors, and 10%+ shareholders trading within six months", "b": "All retail investors daily", "c": "Only foreign sovereign funds exempt always", "d": "Municipal bond issuers exclusively"},
         "a", "Insiders must disgorge profits on opposite trades within six months.",
         {"b": "Not all investors.", "c": "Insiders subject if covered.", "d": "Equity insiders."}, "hard"),
        ("FINRA membership is generally required for firms that:",
         {"a": "Engage in securities business with the U.S. public as broker-dealers", "b": "Only manufacture consumer goods with no securities activity", "c": "Operate hospitals exclusively", "d": "Sell groceries only"},
         "a", "Broker-dealers in the U.S. typically must join FINRA.",
         {"b": "No securities activity, no BD registration.", "c": "Unrelated.", "d": "Unrelated."}, "easy"),
    ])

    return qs


if __name__ == "__main__":
    write_bank(E, build())
