#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "series-99-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "ops", [
        ("A registered operations professional's primary day-to-day function is:",
         {"a": "Approving IPO prospectuses for the SEC", "b": "Opening, maintaining, and supervising customer accounts and processing transactions", "c": "Setting Federal Reserve interest rates", "d": "Auditing public company financial statements as CPA"},
         "b", "Series 99 covers ops professionals handling account maintenance, transactions, and related supervisory tasks.",
         {"a": "Investment banking/SEC filing roles differ.", "c": "Federal Reserve role.", "d": "External audit role."}, "easy"),
        ("Good delivery of customer securities generally requires:",
         {"a": "Proper endorsement, registration match, and transfer procedures per industry rules", "b": "Verbal promise only", "c": "Customer social security card taped to street sign", "d": "Physical certificate always mandatory in modern markets"},
         "a", "Ops ensures securities transfers meet DTC, transfer agent, and firm requirements.",
         {"b": "Documentation required.", "c": "Not valid delivery.", "d": "Book-entry common; rules still apply."}, "medium"),
        ("ACATS transfer of a brokerage account involves:",
         {"a": "Standardized electronic transfer process between broker-dealers", "b": "Customer moving cash only at ATM", "c": "Unilateral deletion of cost basis always by delivering firm without rules", "d": "Only mutual funds never securities"},
         "a", "Automated Customer Account Transfer Service standardizes inter-firm account transfers.",
         {"b": "Broader than cash.", "c": "Cost basis rules apply.", "d": "Securities and other assets transfer."}, "medium"),
        ("Trade settlement for standard equities is currently T+1, meaning:",
         {"a": "Trade settles one business day after trade date", "b": "Settlement occurs same instant as order entry always", "c": "Settlement after 30 calendar days standard", "d": "No settlement ever required"},
         "a", "US equities moved to T+1 settlement cycle reducing counterparty risk.",
         {"b": "Settlement follows trade date rules.", "c": "Not standard equity cycle.", "d": "Settlement mandatory."}, "easy"),
        ("Corporate action voluntary tender offer requires operations to:",
         {"a": "Notify customers, track instructions, and submit elections by deadline", "b": "Auto-tender all accounts without disclosure", "c": "Ignore issuer notices", "d": "Delete positions from system"},
         "a", "Voluntary actions need client communication and timely election processing.",
         {"b": "Requires client authorization.", "c": "Must process notices.", "d": "Positions remain until settled."}, "medium"),
        ("Restricted stock from employer plan deposited to brokerage needs:",
         {"a": "Proper restriction coding, legend compliance, and release tracking", "b": "Immediate unrestricted sale always without review", "c": "No documentation of acquisition date", "d": "Transfer to unrelated third party anonymously always allowed"},
         "a", "Restricted securities require ops controls on legends, Rule 144, and release events.",
         {"b": "Sale may require compliance approval.", "c": "Tax/lot data required.", "d": "Transfer rules and AML apply."}, "hard"),
        ("Mutual fund trade cut-off times mean:",
         {"a": "Orders received before fund deadline priced at that day's NAV", "b": "All orders anytime get prior month NAV", "c": "Cut-offs irrelevant for funds", "d": "Crypto priced like mutual funds always same day"},
         "a", "Fund ops must timestamp orders relative to prospectus cut-off for NAV pricing.",
         {"b": "Incorrect pricing rule.", "c": "Cut-offs fundamental.", "d": "Different products/rules."}, "medium"),
        ("Reorganization of a mandatory stock merger typically requires ops to:",
         {"a": "Exchange old shares for merger consideration per terms on payable date", "b": "Let customers keep old ticker indefinitely", "c": "Convert all accounts to cash without notice", "d": "Skip issuer announcement review"},
         "a", "Mandatory reorganizations applied firm-wide per issuer instructions.",
         {"b": "Ticker retired post merger.", "c": "Cash/stock per terms.", "d": "Announcements drive processing."}, "medium"),
        ("Failed trade in equities may result from:",
         {"a": "Short sale without locate, insufficient securities, or counterparty fail", "b": "Customer logging into app", "c": "Reading research report", "d": "Paying advisory fee"},
         "a", "Fails require buy-in procedures and regulatory reporting in some cases.",
         {"b": "Unrelated.", "c": "Unrelated.", "d": "Unrelated."}, "hard"),
        ("Customer check deposit to brokerage account requires:",
         {"a": "Hold funds per Regulation CC and firm policy until cleared", "b": "Immediate full release for all checks always day zero", "c": "No endorsement verification", "d": "Deposit to unrelated account if faster"},
         "a", "Funds availability schedules and holds manage check fraud risk.",
         {"b": "Holds may apply.", "c": "Endorsement review standard.", "d": "Must deposit to customer's account."}, "medium"),
        ("Options exercise assignment processing occurs:",
         {"a": "On expiration for American options when holder exercises or is assigned", "b": "Only when customer requests stock certificate art", "c": "Never for index options", "d": "Automatically for all OTM options beneficially always"},
         "a", "Ops handles exercise/assignment, stock delivery, and cash settlement per OCC.",
         {"b": "Irrelevant.", "c": "Index options cash settled.", "d": "OTM options typically expire worthless."}, "hard"),
        ("Address of record change on account should trigger:",
         {"a": "Verification procedures and possible hold on disbursements per fraud protocols", "b": "Immediate wire to new address without verification", "c": "No documentation", "d": "Closure of all accounts automatically"},
         "a", "Address changes are common fraud vector; firms verify before outbound funds.",
         {"b": "Verification prevents fraud.", "c": "Documentation required.", "d": "Not automatic closure."}, "easy"),
        ("Prime brokerage vs retail ops difference includes:",
         {"a": "Prime serves institutional clients with complex financing/custody needs", "b": "Prime only handles piggy banks", "c": "Retail never settles trades", "d": "Identical processes always"},
         "a", "Prime brokerage ops supports hedge funds with margin, short locates, and reporting.",
         {"b": "Nonsense.", "c": "Retail settles trades.", "d": "Processes differ."}, "medium"),
        ("SIPC protection primarily covers:",
         {"a": "Missing customer securities/cash if broker-dealer fails, within limits", "b": "Market losses on stock decline", "c": "All crypto losses worldwide", "d": "Guaranteed investment performance"},
         "a", "SIPC replaces missing assets in liquidation, not market value declines.",
         {"b": "Market risk not covered.", "c": "Crypto coverage limited/evolving.", "d": "Not performance guarantee."}, "medium"),
        ("End-of-day reconciliation in operations ensures:",
         {"a": "Internal records match clearing firm, depositories, and general ledger", "b": "Ignore breaks until annual audit only", "c": "Delete unmatched trades silently", "d": "Only reconcile cash never positions"},
         "a", "Daily recon identifies breaks in trades, cash, and positions for timely resolution.",
         {"b": "Daily recon standard.", "c": "Breaks must be investigated.", "d": "Positions and cash both reconciled."}, "easy"),
    ])

    qs += pack(E, "regs", [
        ("FINRA Rule 4512 requires firms to maintain:",
         {"a": "Customer account information including identity and contact details", "b": "Only marketing brochures", "c": "Employee lunch orders exclusively", "d": "Competitor trade secrets"},
         "a", "4512 governs customer account recordkeeping content and updates.",
         {"b": "Broader customer records.", "c": "Irrelevant.", "d": "Prohibited."}, "easy"),
        ("Regulation T governs:",
         {"a": "Credit extended by brokers/dealers for securities purchases (margin)", "b": "Airline baggage fees", "c": "Hospital HIPAA privacy", "d": "Municipal bond underwriting approval only"},
         "a", "Reg T sets initial/maintenance margin from Federal Reserve Board.",
         {"b": "Unrelated.", "c": "HIPAA separate.", "d": "MSRB governs muni dealer activities differently."}, "medium"),
        ("Bank Secrecy Act requires broker-dealers to:",
         {"a": "Implement AML program, file SARs, and verify customer identity", "b": "Ignore large cash transactions", "c": "Share SAR details publicly", "d": "Accept anonymous accounts without CIP"},
         "a", "BSA/AML rules mandate CIP, monitoring, reporting suspicious activity confidentially.",
         {"b": "CTR/SAR obligations exist.", "c": "SAR confidential.", "d": "CIP required."}, "medium"),
        ("Customer Identification Program (CIP) under Patriot Act requires:",
         {"a": "Reasonable procedures to verify identity when opening account", "b": "No ID for all online accounts ever", "c": "Copy of passport sent to unrelated vendor always publicly", "d": "Verification only after account closed"},
         "a", "Firms must verify name, DOB, address, ID number with documentary/non-documentary methods.",
         {"b": "Online accounts still require CIP.", "c": "Protect PII.", "d": "At opening."}, "easy"),
        ("Reg BI (Regulation Best Interest) applies to:",
         {"a": "Recommendations of securities transactions and investment strategies to retail customers", "b": "Purely operational wire processing with no recommendation", "c": "Setting property tax rates", "d": "All commercial banking loans"},
         "a", "Reg BI imposes care, disclosure, conflict, and compliance obligations on recommendations.",
         {"b": "Ops processing alone not recommendation.", "c": "Unrelated.", "d": "Different regulatory regime."}, "medium"),
        ("MSRB rules apply primarily to:",
         {"a": "Municipal securities dealers and advisors", "b": "Only equity day traders exclusively always", "c": "FDA drug approvals", "d": "Insurance property claims adjusters only"},
         "a", "MSRB regulates muni market professional activities and disclosures like G-32.",
         {"b": "Equities under FINRA/SEC other rules.", "c": "Unrelated.", "d": "Unrelated."}, "hard"),
        ("Pattern day trader rule requires minimum equity of:",
         {"a": "$25,000 in margin account for day trading activity meeting definition", "b": "$500", "c": "$0 always", "d": "$1 million for all accounts"},
         "a", "FINRA margin rule requires $25k minimum for pattern day traders.",
         {"b": "Too low.", "c": "Minimum applies.", "d": "Too high for rule."}, "medium"),
        ("Customer complaint reporting to FINRA may be required when:",
         {"a": "Complaints meet regulatory reporting thresholds per Rule 4530", "b": "Customer dislikes market direction", "c": "Any positive feedback", "d": "Employee birthday complaint"},
         "a", "4530 defines qualifying complaints reported quarterly in regulatory filings.",
         {"b": "Not complaint.", "c": "Not complaint.", "d": "Not qualifying complaint."}, "hard"),
        ("Paying for order flow disclosure relates to:",
         {"a": "Broker routing equity orders to venues that pay for flow with best execution obligations", "b": "Mailing paper statements only", "c": "Office rent payments", "d": "Customer birthday gifts unlimited"},
         "a", "SEC/FINRA require disclosure and best execution review of PFOF arrangements.",
         {"b": "Unrelated.", "c": "Unrelated.", "d": "Gifts limited by rules."}, "hard"),
        ("Regulation SHO close-out requirements address:",
         {"a": "Failures to deliver in short sale positions", "b": "Mutual fund marketing", "c": "Insurance annuities", "d": "Real estate closings"},
         "a", "SHO includes locate, marking, and close-out of FTDs for short sales.",
         {"b": "Unrelated.", "c": "Unrelated.", "d": "Unrelated."}, "hard"),
        ("OFAC sanctions compliance requires firms to:",
         {"a": "Screen customers and transactions against blocked persons/country lists", "b": "Process payments to SDN list entities knowingly", "c": "Ignore geographic red flags", "d": "Only check sanctions at account close"},
         "a", "Office of Foreign Assets Control prohibits dealings with sanctioned parties.",
         {"b": "Prohibited.", "c": "Screening ongoing.", "d": "At onboarding and transactions."}, "medium"),
        ("Email retention under SEC Rule 17a-4 requires:",
         {"a": "WORM/non-rewriteable format for specified communications retention", "b": "Delete all emails daily", "c": "Personal Gmail only without capture", "d": "No retention policy ever"},
         "a", "17a-4 mandates books and records retention including electronic communications.",
         {"b": "Prohibited.", "c": "Firm must capture business communications.", "d": "Policy required."}, "medium"),
        ("Gift and gratuity rules under FINRA limit:",
         {"a": "Non-cash gifts from vendors to associated persons beyond de minimis thresholds", "b": "All salaries", "c": "Customer trade confirmations", "d": "Office lease payments to landlord at FMV always prohibited"},
         "a", "Rules prevent improper influence through excessive entertainment/gifts.",
         {"b": "Salaries separate.", "c": "Confirmations required.", "d": "FMV business payments allowed."}, "medium"),
        ("Proxy voting responsibilities for beneficial owners are handled by:",
         {"a": "Firm ops/proxy department forwarding materials and processing instructions per policy", "b": "Customer never receives proxy", "c": "Firm votes arbitrarily without disclosure when customer delegated", "d": "SEC votes for all shareholders"},
         "a", "Ops distributes proxy materials and records customer voting instructions.",
         {"b": "Required delivery.", "c": "Policy/disclosure governs discretionary voting.", "d": "Shareholders vote."}, "medium"),
        ("Insider trading prohibitions apply to operations staff who:",
         {"a": "Possess material nonpublic information from firm processing activities", "b": "Only research analysts exclusively always", "c": "Never see trade flow", "d": "Work only in unrelated industries always exempt"},
         "a", "Ops may see MNPI on mergers/corp actions; personal trading restricted.",
         {"b": "Ops also covered.", "c": "Ops sees account activity.", "d": "Securities employees covered."}, "easy"),
    ])

    qs += pack(E, "books", [
        ("General ledger entry for customer cash deposit credits:",
         {"a": "Debit cash/asset, credit customer payable/liability", "b": "Debit customer liability only without cash", "c": "No entry needed modern brokerage", "d": "Credit revenue immediately as firm income"},
         "a", "Customer cash is firm liability owed to customer; asset increases on deposit.",
         {"b": "Double entry requires both sides.", "c": "Accounting required.", "d": "Not revenue until earned fees."}, "medium"),
        ("Customer statement must reflect:",
         {"a": "Positions, balances, activity, and fees for the period accurately", "b": "Only logo art", "c": "Other customers' trades for comparison", "d": "Projected future returns guaranteed"},
         "a", "Periodic statements are regulatory requirement showing account snapshot and activity.",
         {"b": "Insufficient.", "c": "Confidentiality violation.", "d": "Cannot guarantee returns."}, "easy"),
        ("Cost basis reporting on Form 1099-B includes:",
         {"a": "Proceeds and basis where reported for covered securities", "b": "Only customer birthday", "c": "Medical history", "d": "Guaranteed tax advice binding IRS always"},
         "a", "1099-B reports sales proceeds; basis reported for covered securities per rules.",
         {"b": "Irrelevant.", "c": "Irrelevant.", "d": "Tax advice not on form."}, "medium"),
        ("Suspense account in operations holds:",
         {"a": "Transactions pending identification or resolution", "b": "Permanent customer investments intentionally", "c": "Employee payroll only forever", "d": "Marketing budget exclusively"},
         "a", "Suspense clears when breaks resolved; should not be long-term holding.",
         {"b": "Temporary use.", "c": "Wrong account type.", "d": "Wrong purpose."}, "medium"),
        ("Segregation of customer fully paid securities under SEC Customer Protection Rule requires:",
         {"a": "Possession or control procedures protecting customer securities", "b": "Commingling with firm proprietary assets freely", "c": "No inventory counts", "d": "Customer securities as firm collateral always without consent"},
         "a", "Rule 15c3-3 protects customer assets through possession/control and reserve formula.",
         {"b": "Commingling prohibited.", "c": "Counts/reconciliations required.", "d": "Customer ownership protected."}, "hard"),
        ("Trade blotter records should capture:",
         {"a": "Order details, timestamps, execution prices, and account identifiers", "b": "Only weather notes", "c": "Personal opinions about customer intelligence", "d": "Deleted after one hour always"},
         "a", "Blotters support best execution, audits, and dispute resolution.",
         {"b": "Irrelevant.", "c": "Inappropriate.", "d": "Retention required years."}, "easy"),
        ("ACAT residual credit balance transfer includes:",
         {"a": "Transferring remaining cash after securities moved per customer request", "b": "Stealing cash as firm revenue", "c": "Ignoring small balances always legally", "d": "Transferring only margin debt without authorization"},
         "a", "Residual balances follow transfer process; unclaimed property laws may apply later.",
         {"b": "Theft/ violation.", "c": "Balances owed to customer.", "d": "Needs authorization."}, "medium"),
        ("Wash sale rule affects:",
         {"a": "Loss deduction when substantially identical security repurchased within 30 days", "b": "All gains automatically tax-free", "c": "Only bonds never equities", "d": "Operations trade settlement timing only"},
         "a", "Tax reporting may flag wash sales; ops may track for customer reporting tools.",
         {"b": "Loss deferral not exemption from gains.", "c": "Applies to stocks/options etc.", "d": "Tax concept though ops may support reporting."}, "hard"),
        ("Escheatment process for dormant accounts involves:",
         {"a": "Reporting and remitting unclaimed property to state after dormancy period", "b": "Firm keeping all dormant cash permanently", "c": "Deleting account history illegally", "d": "Immediate donation to employee parties"},
         "a", "States require escheat of unclaimed balances per statutory dormancy timelines.",
         {"b": "Illegal retention.", "c": "Records retained.", "d": "Misappropriation."}, "medium"),
        ("Lot relief method FIFO on sale means:",
         {"a": "First shares purchased are first shares sold for gain/loss calculation", "b": "Highest cost always sold first automatically without election", "c": "Random lot always", "d": "No lot tracking in brokerage systems ever"},
         "a", "Default method may be FIFO unless customer elects specific identification/other.",
         {"b": "HIFO/spec ID are alternatives.", "c": "Systems track lots.", "d": "Lot accounting standard."}, "medium"),
        ("Journal entry moving cash between customer accounts requires:",
         {"a": "Authorized transfer matching customer instruction and AML review", "b": "Ops personal discretion without documentation", "c": "Automatic transfer on email from unknown address without verification", "d": "Transfer to firm proprietary account as gift"},
         "a", "Internal journals need authentication and audit trail like external transfers.",
         {"b": "Documentation mandatory.", "c": "Fraud risk.", "d": "Misappropriation."}, "easy"),
        ("Fails charge in prime brokerage statement reflects:",
         {"a": "Costs associated with securities borrowing/lending or settlement fails per agreement", "b": "Monthly gym membership", "c": "Customer shoe size fee", "d": "Guaranteed profit share always"},
         "a", "Prime clients see financing, borrow, and fail-related charges per contracts.",
         {"b": "Irrelevant.", "c": "Irrelevant.", "d": "Not guaranteed profit."}, "hard"),
        ("Books and records inspection by regulators requires firm to:",
         {"a": "Produce required records promptly and accurately", "b": "Destroy records before exam always legal", "c": "Hide email archives", "d": "Provide only verbal summaries always sufficient"},
         "a", "SEC/FINRA examination authority includes access to required books and records.",
         {"b": "Destruction illegal if obstructive.", "c": "Obstruction violation.", "d": "Written records required."}, "easy"),
        ("Customer free credit balance is:",
         {"a": "Cash payable to customer on demand subject to holds", "b": "Firm's retained earnings", "c": "Margin loan automatically", "d": "Accrued interest owed by customer always"},
         "a", "Free credit balances are customer liabilities representing cash owed.",
         {"b": "Firm equity different.", "c": "Debit balance is loan.", "d": "Credit balance owed to customer."}, "medium"),
        ("Reconciling dividend receivable after record date ensures:",
         {"a": "Firm will receive and pass through dividend to entitled accounts", "b": "Customer loses dividend always if long on ex-date wrong", "c": "No entitlement rules exist", "d": "Dividends paid only to firm proprietary account"},
         "a", "Ops tracks record date entitlements and incoming issuer payments.",
         {"b": "Long holders entitled if record date met.", "c": "Rules exist.", "d": "Passed to customers."}, "medium"),
    ])

    qs += pack(E, "risk", [
        ("Operational risk in brokerage includes:",
         {"a": "Failed processes, systems outages, fraud, and human error", "b": "Only market price movement of customer portfolio", "c": "Sunrise time", "d": "Competitor advertising colors"},
         "a", "Ops risk is non-market risk from inadequate/failed internal processes, people, systems.",
         {"b": "Market risk separate.", "c": "Irrelevant.", "d": "Irrelevant."}, "easy"),
        ("Red flag for account takeover fraud:",
         {"a": "Password reset, new bank link, and large wire to new payee same day", "b": "Customer reading statement", "c": "Regular dividend credit", "d": "Long-term buy-and-hold pattern only"},
         "a", "Multiple account changes plus outbound funds trigger enhanced verification.",
         {"b": "Normal activity.", "c": "Normal activity.", "d": "Not suspicious alone."}, "medium"),
        ("Supervisor review of ops exception reports should:",
         {"a": "Verify timely resolution and escalate unresolved aged items", "b": "Delete exceptions to reduce count", "c": "Ignore until customer complains years later", "d": "Approve all without reading"},
         "a", "Supervisory procedures require monitoring exceptions and aging breaks.",
         {"b": "Concealment violation.", "c": "Timely resolution required.", "d": "Negligent supervision."}, "medium"),
        ("Business continuity plan for operations center must address:",
         {"a": "Alternate site, data backup, staffing, and communication during disruption", "b": "Only pizza delivery vendor", "c": "Permanent shutdown on any snowflake", "d": "Single employee knowledge with no documentation"},
         "a", "BCP ensures critical ops continue after disaster with tested recovery.",
         {"b": "Trivial.", "c": "Overreaction not plan.", "d": "Documentation essential."}, "easy"),
        ("Credit risk in margin accounts arises when:",
         {"a": "Account equity falls below requirements and customer fails to meet calls", "b": "Customer pays cash in full always", "c": "Account holds only US Treasuries with no leverage ever impossible", "d": "Customer reads prospectus"},
         "a", "Margin credit risk is customer default on debit balance after liquidations insufficient.",
         {"b": "Cash accounts different risk profile.", "c": "Margin accounts have credit exposure.", "d": "Unrelated."}, "medium"),
        ("Market risk for firm inventory (not customer) affects:",
         {"a": "Proprietary trading desk holdings subject to price changes", "b": "Customer fully paid cash securities segregated", "c": "Office furniture depreciation only in ops context", "d": "Employee payroll timing exclusively"},
         "a", "Firm risk management monitors proprietary positions; customer assets segregated.",
         {"b": "Customer assets not firm market risk if segregated.", "c": "Not primary ops trading risk.", "d": "Unrelated."}, "medium"),
        ("Duplicate KYC information conflict (address mismatch) should:",
         {"a": "Trigger enhanced due diligence and hold on disbursements pending resolution", "b": "Auto-approve wire anyway", "c": "Ignore mismatch", "d": "Close market globally"},
         "a", "AML/KYC inconsistencies require investigation before high-risk transactions.",
         {"b": "Fraud risk.", "c": "Red flag.", "d": "Disproportionate."}, "medium"),
        ("Error account usage is intended for:",
         {"a": "Temporary placement of trade errors until allocated correctly", "b": "Permanent hiding of customer assets", "c": "Employee bonus pool", "d": "Marketing expenses exclusively forever"},
         "a", "Error accounts resolve breaks quickly with supervisory oversight.",
         {"b": "Prohibited misuse.", "c": "Misappropriation.", "d": "Wrong use."}, "hard"),
        ("Settlement risk (Herstatt risk) reduced by:",
         {"a": "Shorter settlement cycles and central clearing (T+1, CCP)", "b": "Longer indefinite settlement always", "c": "Verbal-only trades without confirmation", "d": "Avoiding all confirmations"},
         "a", "Reduced settlement exposure through T+1 and cleared markets.",
         {"b": "Longer increases risk.", "c": "Confirmations required.", "d": "Confirmations reduce risk."}, "hard"),
        ("Insider threat mitigation in operations includes:",
         {"a": "Least privilege access, logging, segregation of duties, and background checks", "b": "Shared passwords for speed", "c": "Single person controls wire and reconciliation with no review", "d": "Disable audit logs to save disk"},
         "a", "Controls limit unauthorized access and detect suspicious ops activity.",
         {"b": "Password sharing prohibited.", "c": "Segregation of duties key.", "d": "Logs required."}, "medium"),
        ("Customer complaint trending analysis helps ops leadership:",
         {"a": "Identify systematic process failures requiring remediation", "b": "Ignore root causes", "c": "Punish all complainants", "d": "Hide data from compliance"},
         "a", "Trending complaints signal control weaknesses in statements, transfers, or fees.",
         {"b": "Analysis purpose is improvement.", "c": "Retaliation prohibited.", "d": "Compliance needs data."}, "easy"),
        ("Limit order stuck unfilled due to ops routing error creates:",
         {"a": "Best execution and liability exposure requiring prompt correction", "b": "No firm responsibility ever", "c": "Automatic SEC registration revocation next day", "d": "Customer must ignore"},
         "a", "Routing errors may breach best execution and require trade correction/damage review.",
         {"b": "Firm may be liable.", "c": "Extreme overstatement.", "d": "Customer should be made whole if error."}, "hard"),
        ("Key risk indicator (KRI) for ops might track:",
         {"a": "Aged fail percentage, break rate, and STP straight-through processing rate", "b": "Office plant height only", "c": "Random lottery numbers", "d": "Employee zodiac signs"},
         "a", "KRIs quantify operational health for management dashboards.",
         {"b": "Irrelevant.", "c": "Irrelevant.", "d": "Irrelevant."}, "medium"),
        ("Third-party vendor risk for cloud back-office provider requires:",
         {"a": "Due diligence, contract SLAs, and ongoing monitoring", "b": "No review because vendor promises security", "c": "Share customer passwords with vendor informally", "d": "Skip BCP testing entirely"},
         "a", "Outsourcing does not outsource regulatory responsibility; vendor oversight mandatory.",
         {"b": "Due diligence required.", "c": "Secure credential management required.", "d": "BCP testing needed."}, "medium"),
        ("When suspicious activity report (SAR) is filed, associated persons must:",
         {"a": "Not tip off customer that SAR filed (no tipping off)", "b": "Tell customer immediately to avoid anger", "c": "Post SAR on website", "d": "Cancel SAR by customer request always"},
         "a", "Confidentiality of SAR filing is legally protected; tipping off prohibited.",
         {"b": "Tipping off illegal.", "c": "Confidential.", "d": "FinCEN not customer-controlled."}, "easy"),
    ])

    assert len(qs) == 60
    return qs


if __name__ == "__main__":
    from _common import write_bank
    write_bank("series-99-readiness-check", build())
