#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "shrm-scp-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "people", [
        ("Workforce planning at the strategic level should align with:",
         {"a": "Business strategy, future skill needs, and demographic trends", "b": "Only next week's shift schedule", "c": "Random headcount targets without revenue link", "d": "Eliminating all training budgets permanently"},
         "a", "Strategic workforce planning connects talent supply to long-term organizational goals.",
         {"b": "Tactical scheduling is operational.", "c": "Headcount must tie to strategy.", "d": "Training supports capability."}, "easy"),
        ("A key metric for employee engagement effectiveness is:",
         {"a": "Trends in engagement survey scores linked to turnover and productivity", "b": "Number of parking spaces only", "c": "CEO travel miles", "d": "Office plant count"},
         "a", "Engagement metrics should correlate with retention, performance, and business outcomes.",
         {"b": "Irrelevant.", "c": "Irrelevant.", "d": "Irrelevant."}, "easy"),
        ("Succession planning for critical roles requires:",
         {"a": "Identifying high-potential talent and development plans for readiness", "b": "Assuming external hire always cheaper without analysis", "c": "Keeping plans secret from all leaders", "d": "Waiting until incumbent exits unexpectedly only"},
         "a", "Effective succession identifies roles, competencies, and development pipelines proactively.",
         {"b": "Build vs buy analysis needed.", "c": "Leaders need appropriate visibility.", "d": "Reactive-only planning is risky."}, "medium"),
        ("Total rewards strategy integrates:",
         {"a": "Compensation, benefits, recognition, and career opportunities", "b": "Base pay only ignoring benefits", "c": "Stock price exclusively for hourly staff always", "d": "Punitive deductions as primary motivator"},
         "a", "Total rewards framework balances financial and non-financial value propositions.",
         {"b": "Incomplete view.", "c": "Rewards mix varies by workforce.", "d": "Punitive approach harms engagement."}, "medium"),
        ("Diversity, equity, and inclusion (DEI) at SCP level should:",
         {"a": "Embed in talent processes, leadership accountability, and measurable outcomes", "b": "Be a one-time poster campaign only", "c": "Focus only on legal minimum without strategy", "d": "Exclude data collection entirely"},
         "a", "Strategic DEI integrates into hiring, development, pay equity, and culture with metrics.",
         {"b": "Sustainability requires systems change.", "c": "Compliance floor not strategy ceiling.", "d": "Metrics guide progress."}, "medium"),
        ("High-potential program design should avoid:",
         {"a": "Bias by using clear criteria, diverse slate review, and transparent process", "b": "Using solely manager friendship networks", "c": "Linking to business-critical competencies", "d": "Rotational assignments for development"},
         "a", "HiPo selection needs objective criteria and governance to prevent bias.",
         {"b": "Nepotistic selection undermines DEI and capability.", "c": "Competencies appropriate.", "d": "Rotations develop leaders."}, "hard"),
        ("Employee value proposition (EVP) differentiation means:",
         {"a": "Articulating why target talent chooses and stays with the organization", "b": "Copying competitor pay exactly only", "c": "Promising unlimited remote with no business case always", "d": "Hiding culture from candidates"},
         "a", "EVP communicates unique employment experience aligned with workforce segments.",
         {"b": "Pay is one element.", "c": "EVP must be authentic and sustainable.", "d": "Transparency attracts fit."}, "medium"),
        ("Talent analytics for retention might examine:",
         {"a": "Regrettable turnover by role, tenure, manager, and exit interview themes", "b": "Only annual revenue", "c": "Office temperature exclusively", "d": "Random social media likes"},
         "a", "People analytics identifies drivers of regrettable loss for targeted interventions.",
         {"b": "Financial metric alone insufficient.", "c": "Minor factor.", "d": "Not valid HR metric alone."}, "medium"),
        ("Executive coaching ROI is best demonstrated by:",
         {"a": "Behavior change, leadership 360 improvements, and business unit outcomes over time", "b": "Coach invoice amount only", "c": "Number of coffee meetings", "d": "Immediate stock price day one"},
         "a", "Coaching impact measured through leadership behaviors and downstream results.",
         {"b": "Cost not outcome.", "c": "Activity metric weak.", "d": "Stock has many drivers."}, "hard"),
        ("Global mobility policy for long-term assignment should address:",
         {"a": "Tax, immigration, compensation COLA, family support, and repatriation", "b": "Only flight ticket", "c": "Ignore host country employment law", "d": "No contract in writing"},
         "a", "Strategic mobility requires comprehensive support and compliance framework.",
         {"b": "Incomplete.", "c": "Local law applies.", "d": "Written agreements essential."}, "hard"),
        ("Performance management modernization often shifts toward:",
         {"a": "Continuous feedback, goal agility, and development focus vs annual rank-only", "b": "Forced ranking without calibration ever", "c": "Eliminating all goals", "d": "Secret ratings never shared"},
         "a", "Modern performance systems emphasize ongoing coaching and aligned goals.",
         {"b": "Forced ranking alone can harm culture.", "c": "Goals still matter.", "d": "Feedback should be transparent."}, "medium"),
        ("Labor market analysis for scarce skills should include:",
         {"a": "Competitor pay, pipeline data, geographic differentials, and time-to-fill trends", "b": "Guesswork only", "c": "Only internal pay without external benchmark", "d": "Ignoring unemployment rate in sector"},
         "a", "Market intelligence informs comp strategy and sourcing channels.",
         {"b": "Data-driven approach required.", "c": "External market context needed.", "d": "Labor market conditions matter."}, "medium"),
        ("Employee listening strategy combines:",
         {"a": "Surveys, focus groups, stay/exit interviews, and action planning with accountability", "b": "Annual survey with no follow-up", "c": "Monitoring personal social media secretly always legal", "d": "Ignoring frontline feedback"},
         "a", "Listening systems require closure loops demonstrating leadership response.",
         {"b": "No action erodes trust.", "c": "Covert monitoring raises legal/ethics issues.", "d": "Feedback drives improvement."}, "easy"),
        ("Skills-based hiring at scale requires HR to:",
         {"a": "Redesign job architecture, assessments, and manager enablement away from degree-only filters", "b": "Keep legacy reqs unchanged", "c": "Eliminate interviews entirely", "d": "Hire randomly for diversity without competency"},
         "a", "Skills-based approaches need job profiles, validated assessments, and bias mitigation.",
         {"b": "Process redesign essential.", "c": "Interviews still useful.", "d": "Diversity with competency both required."}, "hard"),
        ("Internal talent marketplace benefits include:",
         {"a": "Retention, skill deployment, and reduced time-to-productivity on projects", "b": "Guaranteed external hiring increase", "c": "Eliminating all L&D", "d": "Blocking lateral moves entirely"},
         "a", "Marketplaces match employees to gigs/projects developing careers and agility.",
         {"b": "Often reduces external need.", "c": "L&D still needed.", "d": "Lateral moves encouraged."}, "medium"),
    ])

    qs += pack(E, "organization", [
        ("Organizational design for a post-merger integration should prioritize:",
         {"a": "Clarity of reporting, decision rights, and critical role retention", "b": "Immediate elimination of all HR policies day one", "c": "Duplicating every function without analysis", "d": "Hiding structure from employees indefinitely"},
         "a", "Integration design aligns structure, governance, and talent retention to synergy goals.",
         {"b": "Policy harmonization planned.", "c": "Synergy analysis guides duplication removal.", "d": "Transparency reduces uncertainty."}, "medium"),
        ("Change readiness assessment measures:",
         {"a": "Stakeholder impact, capacity for change, and risks to adoption", "b": "Only logo color preference", "c": "Office square footage", "d": "Number of printers"},
         "a", "Readiness diagnostics guide communication, training, and sponsorship investments.",
         {"b": "Irrelevant.", "c": "Irrelevant.", "d": "Irrelevant."}, "easy"),
        ("HR metrics dashboard for CHRO should include leading indicators such as:",
         {"a": "Quality of hire, internal fill rate, and time-to-productivity", "b": "Only lagging turnover after damage done exclusively", "c": "Coffee consumption", "d": "Random anecdote count"},
         "a", "Leading metrics predict future workforce performance; balance with lagging outcomes.",
         {"b": "Leading and lagging both needed.", "c": "Irrelevant.", "d": "Anecdotes supplement not replace data."}, "medium"),
        ("Agile organization principles in HR service delivery include:",
         {"a": "Iterative releases, cross-functional squads, and customer feedback loops", "b": "Waterfall-only multi-year projects without pilots", "c": "Silos preventing data sharing", "d": "Avoiding employee input entirely"},
         "a", "Agile HR uses sprints, MVPs, and continuous improvement on employee experience.",
         {"b": "Agile contrasts with rigid waterfall-only.", "c": "Silos hinder agility.", "d": "Employee input central."}, "medium"),
        ("Job evaluation for global pay equity may use:",
         {"a": "Consistent job leveling framework with local market pricing", "b": "Different unrelated levels per country secretly", "c": "Title inflation without criteria", "d": "Pay set by manager mood only"},
         "a", "Global grading with local comp bands supports equitable structure.",
         {"b": "Inconsistent framework undermines equity.", "c": "Inflation distorts comparisons.", "d": "Governance needed."}, "hard"),
        ("Shared services center implementation success factor:",
         {"a": "Executive sponsorship, SLAs, change management, and technology enablement", "b": "Moving work without process redesign", "c": "No service standards", "d": "Ignoring customer experience metrics"},
         "a", "SSC requires process standardization, governance, and employee/manager communication.",
         {"b": "Redesign precedes scale.", "c": "SLAs define performance.", "d": "Experience metrics track success."}, "medium"),
        ("Scenario planning for recession workforce action should:",
         {"a": "Model multiple options with impact on capability, DEI, and employer brand", "b": "Default to layoffs only without analysis", "c": "Ignore legal obligations in EU/countries with consultation", "d": "Announce via rumor mill"},
         "a", "Strategic workforce reductions consider alternatives, compliance, and long-term talent.",
         {"b": "Multiple levers exist.", "c": "Legal consultation mandatory many jurisdictions.", "d": "Official communication required."}, "hard"),
        ("Culture assessment after rapid growth identifies:",
         {"a": "Values drift, decision bottlenecks, and inclusion gaps", "b": "Only desk layout", "c": "Nothing; culture static always", "d": "Only financial fraud"},
         "a", "Scaling strains culture; diagnostics inform leadership and HR interventions.",
         {"b": "Superficial.", "c": "Culture evolves.", "d": "Broader cultural factors matter."}, "medium"),
        ("HR technology roadmap alignment requires:",
         {"a": "Integration architecture, data governance, and user adoption planning", "b": "Buying point solutions without strategy", "c": "Duplicate systems per region forever", "d": "No security review"},
         "a", "HRTech strategy connects stack to processes, analytics, and employee experience.",
         {"b": "Strategy prevents sprawl.", "c": "Integration reduces friction.", "d": "Security/privacy essential."}, "medium"),
        ("Business partnership model for HRBPs emphasizes:",
         {"a": "Consulting on workforce implications of business decisions with data", "b": "Transaction processing only", "c": "Avoiding executive meetings", "d": "Enforcing rules without context"},
         "a", "Strategic HRBPs co-create workforce plans tied to business outcomes.",
         {"b": "Transactional work often centralized.", "c": "Executive engagement core.", "d": "Contextual judgment required."}, "easy"),
        ("Knowledge management for retiring experts includes:",
         {"a": "Documentation, mentoring, and phased transition plans", "b": "Immediate exit with no transfer", "c": "NDA preventing any handoff", "d": "Ignoring subject matter loss"},
         "a", "Critical knowledge transfer reduces operational risk from demographic shifts.",
         {"b": "Creates capability gap.", "c": "Handoff compatible with IP protection.", "d": "Risky for operations."}, "medium"),
        ("Organizational network analysis (ONA) can reveal:",
         {"a": "Informal influencers and collaboration bottlenecks", "b": "Only formal org chart lines", "c": "Payroll tax rates", "d": "Building HVAC capacity"},
         "a", "ONA maps relationships to inform change, inclusion, and innovation initiatives.",
         {"b": "ONA supplements chart.", "c": "Unrelated.", "d": "Unrelated."}, "hard"),
        ("Restructuring communication principle:",
         {"a": "Timely, empathetic, consistent messages with manager talking points", "b": "Leak to press first", "c": "Silent until rumors peak", "d": "Different story to each team intentionally"},
         "a", "Clear coordinated communication reduces anxiety and misinformation.",
         {"b": "Uncontrolled leak harmful.", "c": "Delay increases rumor harm.", "d": "Inconsistency destroys trust."}, "easy"),
        ("Center of excellence (CoE) for compensation should:",
         {"a": "Set standards, provide expert consulting, and govern pay programs", "b": "Eliminate all manager involvement in offers", "c": "Operate without audit trail", "d": "Ignore market data entirely"},
         "a", "CoEs enable scale through expertise, templates, and governance while partnering with HRBPs.",
         {"b": "Managers still involved within guardrails.", "c": "Documentation required.", "d": "Market data central."}, "medium"),
        ("Operating model for global HR often uses:",
         {"a": "Centers of excellence, HRBPs, and shared services with defined RACI", "b": "Every country fully duplicate without coordination", "c": "No global policies ever", "d": "CEO as only HR contact"},
         "a", "Three-tier models balance global standards with local compliance and business partnering.",
         {"b": "Inefficient duplication.", "c": "Global standards with local adaptation.", "d": "Not scalable."}, "medium"),
    ])

    qs += pack(E, "workplace", [
        ("Title VII prohibits employment discrimination based on:",
         {"a": "Race, color, religion, sex, and national origin", "b": "Only shoe size", "c": "Performance issues documented fairly", "d": "Lawful job requirements with accommodation process"},
         "a", "Title VII protected classes listed; legitimate performance/requirements with ADA process differ.",
         {"b": "Not protected class.", "c": "Legitimate nondiscriminatory reason if documented.", "d": "BFOQ/accommodation analysis may apply."}, "easy"),
        ("ADA reasonable accommodation process requires:",
         {"a": "Interactive dialogue to identify effective accommodation unless undue hardship", "b": "Automatic grant of any request without assessment", "c": "Immediate termination on request", "d": "Ignoring medical documentation always"},
         "a", "Employers engage in good-faith interactive process with documentation as appropriate.",
         {"b": "Not all requests granted without analysis.", "c": "Retaliation illegal.", "d": "Limited medical inquiry permitted."}, "medium"),
        ("FMLA eligibility for private employer generally requires:",
         {"a": "50+ employees within 75 miles, 12 months service, 1250 hours worked", "b": "Any employee day one at two-employee company always", "c": "Only executives", "d": "No documentation ever allowed"},
         "a", "FMLA has employer size, tenure, and hours thresholds.",
         {"b": "Small employer exemption.", "c": "Broad eligibility if thresholds met.", "d": "Certification permitted."}, "medium"),
        ("Workplace harassment prevention at SCP level includes:",
         {"a": "Policy, training, investigation protocol, and leadership accountability", "b": "Optional reporting channel only", "c": "Retaliating against reporters", "d": "Ignoring repeat offenders with revenue excuse"},
         "a", "Effective programs combine prevention, reporting, impartial investigation, and corrective action.",
         {"b": "Multiple channels needed.", "c": "Retaliation illegal.", "d": "Revenue does not excuse harassment."}, "easy"),
        ("Pay equity analysis should examine:",
         {"a": "Comp gaps controlling for role, level, experience, and performance where valid", "b": "Raw averages only without controls", "c": "Only one gender company-wide average", "d": "Exclude bonuses always without reason"},
         "a", "Regression or cohort analysis identifies unexplained pay disparities.",
         {"b": "Raw gaps misleading.", "c": "Intersectional and role-specific analysis needed.", "d": "Total comp includes variable pay."}, "hard"),
        ("OSHA general duty clause requires employers to:",
         {"a": "Provide workplace free from recognized serious hazards", "b": "Ignore ergonomic risks always", "c": "Block all OSHA inspections without cause", "d": "Punish injury reporting"},
         "a", "General duty covers hazards without specific standard if recognized and serious.",
         {"b": "Ergonomic hazards may be cited in some cases.", "c": "Inspection rights exist.", "d": "Retaliation for reporting prohibited."}, "medium"),
        ("Union organizing activity protected by NLRA means employer cannot:",
         {"a": "Threaten, surveil, or discriminate for protected concerted activity", "b": "Share factual information about unionization with rules", "c": "Hold mandatory meetings about union process within legal bounds", "d": "Follow lawful campaign guidelines"},
         "a", "Unfair labor practices include interference with organizing rights.",
         {"b": "Permitted communications if lawful.", "c": "Captive audience meetings regulated but not always prohibited.", "d": "Lawful guidance allowed."}, "hard"),
        ("Remote work policy for multi-state US employees should address:",
         {"a": "Tax, wage/hour, workers' comp, and benefits jurisdiction issues", "b": "Assume single HQ state rules only always", "c": "No written agreement ever", "d": "Ignore IP/security requirements"},
         "a", "Multi-state remote work triggers compliance complexity requiring legal review.",
         {"b": "Employee work location often governs.", "c": "Written policies essential.", "d": "Security policies still apply."}, "hard"),
        ("Workplace violence prevention program includes:",
         {"a": "Risk assessment, reporting, training, and coordination with security/law enforcement", "b": "Arming all employees mandatorily without policy", "c": "Ignoring threats", "d": "Publishing confidential reporter identity"},
         "a", "WVPP identifies hazards, trains response, and protects reporters.",
         {"b": "Weapon policies highly regulated.", "c": "Threats must be assessed.", "d": "Confidentiality protects reporters."}, "medium"),
        ("Investigation of discrimination complaint should:",
         {"a": "Be prompt, impartial, documented, and lead to appropriate action", "b": "Be conducted by accused's best friend", "c": "Promise absolute anonymity to all parties impossible legally always", "d": "Delay months without reason"},
         "a", "Investigations follow consistent protocol with limited need-to-know confidentiality.",
         {"b": "Conflict of interest.", "c": "Confidentiality limited; retaliation prohibited.", "d": "Promptness required."}, "medium"),
        ("Age Discrimination in Employment Act (ADEA) protects employees age:",
         {"a": "40 and older", "b": "18 and younger only", "c": "65 only", "d": "No age protection in US"},
         "a", "ADEA prohibits age discrimination against individuals 40+.",
         {"b": "Other laws protect minors differently.", "c": "Broader than 65.", "d": "ADEA exists."}, "easy"),
        ("Accommodating religious dress at work typically requires:",
         {"a": "Reasonable accommodation unless undue hardship to business", "b": "Automatic ban of all head coverings", "c": "Forcing conversion", "d": "No interactive process"},
         "a", "Title VII religious accommodation similar undue hardship standard to ADA concept.",
         {"b": "Blanket bans often unlawful.", "c": "Discriminatory.", "d": "Dialogue required."}, "medium"),
        ("Whistleblower protections for reporting safety violations mean:",
         {"a": "Retaliation prohibited; reports should go through defined channels", "b": "Reporter can be fired immediately for reporting", "c": "Only oral anonymous threats allowed", "d": "Reports must be public social media only"},
         "a", "OSHA and other laws protect good-faith safety/legal compliance reporting.",
         {"b": "Retaliation illegal.", "c": "Formal channels exist.", "d": "Internal/legal channels preferred."}, "medium"),
        ("Employee assistance program (EAP) strategic value includes:",
         {"a": "Early intervention for mental health/substance issues reducing absenteeism and turnover", "b": "Replacement for ADA accommodation", "c": "Surveillance tool for termination only", "d": "Mandatory disclosure of all sessions to manager always"},
         "a", "EAP supports wellbeing confidentially; not substitute for accommodation or performance management.",
         {"b": "Separate obligations.", "c": "Confidentiality core to EAP.", "d": "Confidential with limited exceptions."}, "easy"),
        ("Work authorization verification (Form I-9) requires:",
         {"a": "Examining acceptable documents within required timeframe without national origin discrimination", "b": "Citizenship preference in hiring", "c": "Keeping I-9 with public website", "d": "Reuse of expired documents knowingly"},
         "a", "I-9 process verifies identity and work authorization uniformly.",
         {"b": "Citizenship discrimination prohibited.", "c": "I-9 stored securely.", "d": "Valid unexpired documents required."}, "easy"),
    ])

    qs += pack(E, "leadership", [
        ("SHRM SCP competency of ethical leadership requires:",
         {"a": "Modeling integrity, transparency, and accountability in HR decisions", "b": "Hiding policy violations from board", "c": "Favoritism for high revenue units only", "d": "Using HR data for personal gain"},
         "a", "Senior HR leaders set ethical tone and ensure fair governance.",
         {"b": "Board disclosure may be required.", "c": "Consistency required.", "d": "Misuse of data unethical/illegal."}, "easy"),
        ("Influencing C-suite on workforce investment, HR should:",
         {"a": "Translate people metrics into business risk and ROI narratives", "b": "Use HR jargon without business linkage", "c": "Avoid data entirely", "d": "Threaten resignation only tactic"},
         "a", "Executive influence connects talent initiatives to revenue, risk, and strategy.",
         {"b": "Business language required.", "c": "Data strengthens case.", "d": "Not professional influence."}, "medium"),
        ("Board reporting on human capital should include:",
         {"a": "Turnover, leadership bench strength, culture indicators, and DEI progress", "b": "Only office supply costs", "c": "Individual employee medical records", "d": "Gossip about executives' personal lives"},
         "a", "Boards increasingly oversee human capital as intangible asset with risk implications.",
         {"b": "Immateral at board level.", "c": "PHI prohibited.", "d": "Unprofessional/inappropriate."}, "medium"),
        ("Crisis leadership during layoffs emphasizes:",
         {"a": "Compassionate communication, compliance, outplacement support, and survivor care", "b": "Mass email Friday 5 PM without manager training only always best", "c": "Violating WARN where applicable", "d": "Ignoring remaining employee morale"},
         "a", "Thoughtful execution reduces legal risk and protects employer brand.",
         {"b": "Timing/training matter; context dependent.", "c": "WARN/legal obligations apply.", "d": "Survivor engagement critical."}, "hard"),
        ("Strategic HR risk register might include:",
         {"a": "Critical skill gaps, compliance failures, and culture/ reputational threats", "b": "Only coffee brand preference", "c": "Personal vendettas", "d": "Competitor stock price exclusively"},
         "a", "Enterprise risk management integrates workforce-related operational and compliance risks.",
         {"b": "Trivial.", "c": "Unprofessional.", "d": "Partial external signal only."}, "medium"),
        ("Coaching executives through toxic behavior pattern requires:",
         {"a": "Clear expectations, consequences, and alignment with board if behavior persists", "b": "Ignoring because revenue high forever", "c": "Public shaming in all-hands", "d": "Transfer problem to HR admin to ignore"},
         "a", "Senior leaders accountable; documented performance improvement or separation may be needed.",
         {"b": "Revenue does not excuse toxicity indefinitely.", "c": "Confidential corrective action preferred.", "d": "SCP must address with governance."}, "hard"),
        ("Global leadership development for emerging markets should:",
         {"a": "Include cross-cultural competence, local mentorship, and inclusive cohort design", "b": "Export HQ program unchanged without adaptation", "c": "Exclude local leaders from pipeline", "d": "Assume English-only always sufficient"},
         "a", "Global programs adapt content, facilitators, and examples to regional context.",
         {"b": "Localization needed.", "c": "Local talent essential.", "d": "Language/culture considerations matter."}, "medium"),
        ("HR's role in ESG (environmental, social, governance) reporting includes:",
         {"a": "Supplying verified human capital metrics for social disclosures", "b": "Fabricating diversity data", "c": "Avoiding all metrics", "d": "Only environmental data HR owns"},
         "a", "Social pillar covers workforce diversity, safety, training, and labor practices.",
         {"b": "Fraudulent reporting illegal.", "c": "Investors expect data.", "d": "HR owns social metrics."}, "medium"),
        ("Decision-making under uncertainty in HR strategy uses:",
         {"a": "Scenario analysis, pilot programs, and staged investment with KPIs", "b": "All-or-nothing rollout without metrics", "c": "Copy competitor without context", "d": "Delay all decisions indefinitely"},
         "a", "Strategic leaders test hypotheses and measure before scaling.",
         {"b": "Risky approach.", "c": "Context matters.", "d": "Paralysis fails business."}, "medium"),
        ("Building coalition for culture transformation requires:",
         {"a": "Executive sponsors, manager enablement, and employee champions", "b": "HR acting alone without leadership", "c": "One email announcement", "d": "Punishing resistors immediately without listening"},
         "a", "Culture change needs aligned leadership behaviors and sustained reinforcement.",
         {"b": "Leadership must model change.", "c": "Insufficient.", "d": "Listen and address concerns."}, "easy"),
        ("Conflicting priorities between CFO cost cut and CEO growth, HR should:",
         {"a": "Present workforce scenarios showing tradeoffs in capability and risk", "b": "Side secretly with one executive only", "c": "Ignore both", "d": "Implement cuts without analysis"},
         "a", "Strategic HR facilitates data-driven workforce planning balancing cost and growth.",
         {"b": "Maintain credibility with balanced analysis.", "c": "Abdication of role.", "d": "Analysis required."}, "hard"),
        ("Succession for CHRO role board should evaluate:",
         {"a": "Business acumen, ethics, global/compliance expertise, and culture leadership", "b": "Only payroll certification", "c": "Personal friendship with CEO only", "d": "Lowest cost candidate exclusively"},
         "a", "CHRO is strategic partner requiring broad enterprise leadership competencies.",
         {"b": "Too narrow.", "c": "Governance requires objective criteria.", "d": "Cost not sole factor."}, "medium"),
        ("Psychological safety at leadership level means:",
         {"a": "Team members can raise concerns without fear of retaliation", "b": "No accountability for performance", "c": "Avoiding all difficult conversations", "d": "Agreeing with CEO always"},
         "a", "Psychological safety enables innovation and issue surfacing with performance standards intact.",
         {"b": "Accountability remains.", "c": "Difficult conversations needed.", "d": "Dissent can be constructive."}, "easy"),
        ("M&A cultural due diligence assesses:",
         {"a": "Leadership styles, decision norms, and integration risk to talent retention", "b": "Only building lease terms HR ignores", "c": "Office art exclusively", "d": "Assume cultures identical always"},
         "a", "Culture clash drives deal failure; HR assesses alignment and integration plan.",
         {"b": "HR participates in diligence.", "c": "Superficial.", "d": "Cultures often differ."}, "hard"),
        ("Personal leadership resilience for senior HR includes:",
         {"a": "Boundaries, peer support, and continuous learning to sustain effectiveness", "b": "24/7 availability without recovery always required", "c": "Isolating from business leaders", "d": "Avoiding all stress by delegating ethics away"},
         "a", "Sustainable leadership practices prevent burnout and support sound judgment.",
         {"b": "Recovery enables performance.", "c": "Partnership requires engagement.", "d": "Ethics cannot be delegated away."}, "easy"),
    ])

    assert len(qs) == 60
    return qs


if __name__ == "__main__":
    from _common import write_bank
    write_bank("shrm-scp-readiness-check", build())
