#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "veterinary-technician-vtne-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "pharm", [
        ("A prescription reads 'Canine: Carprofen 75 mg PO q12h.' Before dispensing, the technician should:",
         {"a": "Verify species, weight-based dosing, and label with client/patient instructions per DVM order", "b": "Substitute insulin without calling DVM", "c": "Skip weight check because all dogs same size", "d": "Add extra tablets for stock"},
         "a", "NSAIDs require species/weight verification and accurate labeling under veterinarian supervision.",
         {"b": "Different drug class.", "c": "Dosing is weight-dependent.", "d": "Inventory theft/diversion."}, "easy"),
        ("Controlled substance log in veterinary hospital must record:",
         {"a": "Date, client/patient, drug, amount dispensed/administered, balance, and responsible personnel", "b": "Only weather that day", "c": "Technician guesses without signature", "d": "Nothing if DVM present"},
         "a", "DEA/state rules require perpetual inventory and documentation for controlled drugs.",
         {"b": "Irrelevant.", "c": "Signatures/accountability required.", "d": "Records always required."}, "medium"),
        ("Extra-label drug use (ELDU) in animals means:",
         {"a": "Using drug in manner not on label (species, dose, route) under valid VCPR with oversight", "b": "Using only human OTC without DVM", "c": "Always illegal without exception", "d": "Same as discarding expired drugs"},
         "a", "ELDU is permitted under AMDUCA with veterinarian direction and food withdrawal rules when applicable.",
         {"b": "Requires veterinarian.", "c": "ELDU legal with conditions.", "d": "Unrelated."}, "hard"),
        ("Calculate volume: Dose 0.02 mg/kg, concentration 0.5 mg/mL, patient 10 kg. Volume needed:",
         {"a": "0.4 mL", "b": "2.5 mL", "c": "0.04 mL", "d": "10 mL"},
         "a", "Dose = 0.02×10 = 0.2 mg; volume = 0.2/0.5 = 0.4 mL.",
         {"b": "Math error.", "c": "Decimal error.", "d": "Excessive volume."}, "medium"),
        ("Insulin U-100 10 units for dog requires syringe:",
         {"a": "U-100 insulin syringe with correct unit marking", "b": "3 mL luer slip syringe without unit calibration for insulin", "c": "TB syringe in mL only without conversion knowledge", "d": "Oral syringe in teaspoons"},
         "a", "Insulin must be measured with appropriate U-100 syringe to avoid dosing errors.",
         {"b": "Wrong calibration risks overdose.", "c": "Requires insulin syringe or careful conversion.", "d": "Insulin not oral."}, "easy"),
        ("Compounding omeprazole suspension for cat should include:",
         {"a": "Flavor/formulation suitable for species and beyond-use dating per pharmacist/DVM protocol", "b": "Xylitol sweetener always safe in cats", "c": "Human alcohol-based elixir without adjustment", "d": "No label because cat cannot read"},
         "a", "Veterinary compounding considers species toxicity (e.g., avoid xylitol in dogs) and stability.",
         {"b": "Xylitol toxic to dogs; species matters.", "c": "Alcohol may be inappropriate.", "d": "Label required for client."}, "medium"),
        ("Drug storage: reconstituted injectable antibiotic typically:",
         {"a": "Refrigerated with labeled beyond-use date per manufacturer", "b": "Left at room temp indefinitely after mixing", "c": "Frozen after mixing always", "d": "Mixed weeks in advance without dating"},
         "a", "Follow manufacturer stability after reconstitution; label BUD.",
         {"b": "Stability limited.", "c": "Freezing may inactivate.", "d": "BUD required."}, "medium"),
        ("Dispensing phenobarbital refill requires:",
         {"a": "Valid prescription within refill limits and controlled drug accountability", "b": "Client verbal request only without record", "c": "Unlimited refills without DVM", "d": "Transfer to human pharmacy without Rx"},
         "a", "Schedule IV controlled anticonvulsant requires prescription compliance and logs.",
         {"b": "Documentation required.", "c": "Refills per Rx only.", "d": "Requires veterinary Rx workflow."}, "medium"),
        ("Topical flea product labeled dogs only applied to cat may cause:",
         {"a": "Permethrin/pyrethrin toxicity in cats if dog-only product", "b": "Improved feline hair shine only", "c": "No risk ever across species", "d": "Automatic immunity"},
         "a", "Many canine spot-ons contain permethrin toxic to cats; species labeling critical.",
         {"b": "Can cause seizures/death in cats.", "c": "Species differences significant.", "d": "False."}, "hard"),
        ("Medication error: wrong drug given to patient. Immediate step:",
         {"a": "Notify DVM immediately, monitor patient, document, initiate adverse event protocol", "b": "Hide error from client", "c": "Wait until next week", "d": "Give another random drug to cancel"},
         "a", "Rapid notification and supportive care reduce harm; full documentation required.",
         {"b": "Concealment unethical/illegal.", "c": "Delay harmful.", "d": "Compounds risk."}, "easy"),
        ("Route IM injection in small animal often preferred site:",
         {"a": "Quadriceps or lumbar epaxial muscles per clinic protocol", "b": "Intravenous only always for all IM orders", "c": "Subcutaneous same as IV bolus always", "d": "Oral route for injectable only"},
         "a", "IM sites include quadriceps/epaxial with aspiration per policy.",
         {"b": "IM not IV.", "c": "Different routes.", "d": "Injectable not oral."}, "medium"),
        ("Antibiotic compliance counseling for client includes:",
         {"a": "Complete full course even if pet looks better unless DVM directs stop", "b": "Stop when half pills remain for savings", "c": "Share leftovers with neighbor's pet", "d": "Double dose if one dose missed always"},
         "a", "Incomplete courses promote resistance; consult DVM if dose missed.",
         {"b": "Premature stop risks relapse/resistance.", "c": "Sharing illegal/unsafe.", "d": "Doubling without DVM unsafe."}, "easy"),
        ("Handling chemotherapeutic waste in clinic requires:",
         {"a": "Segregation, PPE, and disposal per hazardous drug protocol", "b": "Regular trash bin", "c": "Drain disposal always", "d": "Client home compost"},
         "a", "Chemo agents require HD waste containers and staff protection.",
         {"b": "Regulated waste.", "c": "Environmental prohibition typically.", "d": "Improper disposal."}, "hard"),
        ("Microchip pre-medication is not a substitute for:",
         {"a": "Proper anesthetic protocol when surgery/dental performed", "b": "Patient identification", "c": "Medical record", "d": "Client communication"},
         "a", "Microchips identify pets; anesthesia requires full assessment and protocols.",
         {"b": "Microchip aids ID.", "c": "Records still needed.", "d": "Communication still needed."}, "easy"),
        ("Drug interaction: NSAID plus corticosteroid increases risk of:",
         {"a": "GI ulceration and renal injury", "b": "Improved joint healing always", "c": "Lower bleeding risk", "d": "No interaction"},
         "a", "Concurrent NSAID/steroid raises GI/renal adverse event risk; DVM weighs benefit.",
         {"b": "Healing not improved.", "c": "Bleeding risk increases.", "d": "Known interaction."}, "hard"),
    ])

    qs += pack(E, "nursing", [
        ("Normal heart rate for resting adult dog is approximately:",
         {"a": "60–140 bpm depending on size", "b": "10–20 bpm", "c": "300–400 bpm always", "d": "Identical to human 60 always"},
         "a", "Canine HR varies with size; smaller dogs tend higher end.",
         {"b": "Too low for resting dog.", "c": "Too high resting.", "d": "Varies by size."}, "easy"),
        ("Mucous membranes pink and moist with CRT <2 sec suggest:",
         {"a": "Adequate perfusion/hydration baseline", "b": "Shock always", "c": "Hyperthermia always", "d": "Anemia impossible"},
         "a", "Pink moist MM and quick CRT indicate good perfusion in stable patient.",
         {"b": "Shock shows pale/tacky prolonged CRT.", "c": "Not specific to fever alone.", "d": "Anemia may still show pink early."}, "easy"),
        ("Restraint for jugular blood draw in cat often uses:",
         {"a": "Towel wrap (burrito) with minimal stress handling", "b": "Full choke collar tension", "c": "No restraint speeding poke", "d": "Hanging by scruff alone always sufficient for all cats"},
         "a", "Low-stress feline handling with towel restraint improves safety and sample quality.",
         {"b": "Airway compromise risk.", "c": "Unsafe for staff/patient.", "d": "Scruff alone often insufficient; combine techniques."}, "medium"),
        ("Maintenance fluid rate for dog often calculated as:",
         {"a": "40–60 mL/kg/day (rough estimate) adjusted for losses", "b": "500 mL total for any size", "c": "10 mL/kg/hr always regardless of size without assessment", "d": "Oral water only for surgical patient NPO"},
         "a", "Maintenance estimates vary; surgical/NPO patients need IV fluids per DVM.",
         {"b": "Size dependent.", "c": "Requires individual calculation.", "d": "NPO surgical patients need IV typically."}, "medium"),
        ("Bandage check after limb surgery includes:",
         {"a": "Swelling, odor, moisture, bandage position, and distal perfusion", "b": "Ignore until removal date", "c": "Tighten if swelling increases", "d": "Allow patient to chew if bored"},
         "a", "Bandage complications cause ischemia/infection; monitor CMS and cleanliness.",
         {"b": "Daily checks required.", "c": "Swelling may require loosen/remove.", "d": "Chewing removes protection."}, "medium"),
        ("Nutritional support for anorexic cat at risk of hepatic lipidosis may require:",
         {"a": "Timely enteral feeding plan per DVM", "b": "Starvation until appetite returns weeks", "c": "Dog food only for convenience", "d": "Only water for 7 days"},
         "a", "Cats hepatic lipidosis risk with prolonged anorexia; feeding tubes/plans needed.",
         {"b": "Prolonged starvation dangerous.", "c": "Species-appropriate nutrition required.", "d": "Extended fast harmful."}, "hard"),
        ("Isolation for parvovirus puppy includes:",
         {"a": "Separate housing, PPE, disinfection with appropriate virucidal agents", "b": "Free roam waiting room", "c": "Shared bedding with healthy puppies", "d": "No hand hygiene"},
         "a", "Parvo highly contagious; strict isolation and bleach-compatible disinfection required.",
         {"b": "Contagion risk.", "c": "Fomite transmission.", "d": "Hand hygiene essential."}, "medium"),
        ("Pain assessment in non-verbal animal uses:",
         {"a": "Behavior, posture, appetite, vocalization, palpation response (pain scales)", "b": "Human pain score verbally only", "c": "Assume no pain if sleeping", "d": "Ignore because animals feel no pain myth"},
         "a", "Validated pain scales and behavior observation guide analgesia.",
         {"b": "Animals cannot verbalize.", "c": "Sleep can be pain response.", "d": "Animals experience pain."}, "easy"),
        ("Temperature 103.8°F in dog at rest suggests:",
         {"a": "Fever/hyperthermia warranting evaluation", "b": "Normal always", "c": "Hypothermia", "d": "Error never recheck"},
         "a", "Canine normal ~99.5–102.5°F; elevation suggests infection/inflammation/heat.",
         {"b": "Above normal.", "c": "Hypothermia is low temp.", "d": "Recheck and assess."}, "easy"),
        ("Elizabethan collar purpose:",
         {"a": "Prevent self-trauma to wounds/incisions", "b": "Fashion accessory only", "c": "Replace anesthesia", "d": "Improve hearing"},
         "a", "E-collars protect surgical sites from licking/chewing.",
         {"b": "Medical purpose.", "c": "Not anesthetic.", "d": "Unrelated."}, "easy"),
        ("Urinary catheter care includes:",
         {"a": "Closed system, clean prep, monitor output and kinking", "b": "Open drainage on floor", "c": "No output recording", "d": "Reuse without sterilization between patients"},
         "a", "Catheter-associated UTI prevention uses closed sterile technique and monitoring.",
         {"b": "Contamination risk.", "c": "Output guides fluid plan.", "d": "Single patient sterile use."}, "medium"),
        ("Zoonotic concern with diarrheic puppy includes:",
         {"a": "Salmonella/Campylobacter transmission with PPE and hygiene", "b": "No human risk ever", "c": "Share bed with immunocompromised owner recommended", "d": "Skip handwashing for speed"},
         "a", "GI pathogens zoonotic; PPE and hand hygiene protect staff/clients.",
         {"b": "Zoonoses exist.", "c": "Unsafe for immunocompromised.", "d": "Handwashing mandatory."}, "medium"),
        ("Post-op incision redness with purulent discharge should:",
         {"a": "Be documented and reported to DVM promptly", "b": "Be ignored until suture removal", "c": "Be treated by client with essential oils only without call", "d": "Hidden from DVM"},
         "a", "Purulent discharge suggests infection/dehiscence needing veterinary assessment.",
         {"b": "Needs timely intervention.", "c": "Essential oils not substitute.", "d": "Withholding info harms patient."}, "easy"),
        ("Large breed deep chested dog post-op bloat risk monitoring includes:",
         {"a": "Abdominal distention, unproductive retching, restlessness", "b": "Only tail wagging", "c": "Ignore GI signs", "d": "Feed large meal immediately"},
         "a", "GDV signs are emergency; prophylactic protocols may apply peri-op.",
         {"b": "Insufficient monitor.", "c": "GI signs critical.", "d": "Feeding protocol per DVM."}, "hard"),
        ("Client education on subcutaneous fluids at home should emphasize:",
         {"a": "Sterile needle/site rotation, rate/volume per DVM, and when to call", "b": "Reuse needles indefinitely", "c": "IV into vein at home without training", "d": "Any fluid bag expired OK"},
         "a", "Home SQ fluids require aseptic technique and clear stop signs.",
         {"b": "Single use needles.", "c": "IV at home requires advanced training.", "d": "Expired fluids unsafe."}, "medium"),
    ])

    qs += pack(E, "diagnostics", [
        ("Blood sample for CBC with EDTA tube requires:",
         {"a": "Gentle mix after draw; run within stability window", "b": "Hemolysis from vigorous shaking encouraged", "c": "Serum separator tube instead always", "d": "Leave at hot car dashboard days"},
         "a", "EDTA purple top for CBC; gentle inversion prevents hemolysis/clotting errors.",
         {"b": "Hemolysis invalidates results.", "c": "Serum tube for chemistries typically.", "d": "Stability limited."}, "easy"),
        ("Fecal flotation test detects:",
         {"a": "Many intestinal parasite ova", "b": "Fractured femur", "c": "Blood glucose", "d": "Heart murmur grade"},
         "a", "Flotation concentrates parasite eggs in feces.",
         {"b": "Radiology.", "c": "Blood test.", "d": "Auscultation."}, "easy"),
        ("Radiograph personnel safety relies on:",
         {"a": "ALARA principles, collimation, PPE, and distance/time limits", "b": "Holding beam on without PPE daily", "c": "Pregnancy no extra precautions ever", "d": "Digital means zero radiation"},
         "a", "As low as reasonably achievable with lead aprons, thyroid shields, and distance.",
         {"b": "Unsafe practice.", "c": "Pregnant staff limit exposure.", "d": "Digital still emits radiation."}, "medium"),
        ("Fine needle aspirate sample handling:",
         {"a": "Prepare slides immediately or place in appropriate transport medium per lab", "b": "Leave syringe in sun hours", "c": "Freeze all cytology always", "d": "Discard if blood present always without DVM review"},
         "a", "Rapid slide prep or fluid transfer preserves cytology quality.",
         {"b": "Degradation occurs.", "c": "Cytology usually not frozen fresh smears.", "d": "Blood may be present; DVM interprets."}, "medium"),
        ("Heartworm antigen test false negatives may occur with:",
         {"a": "Low worm burden or timing before antigenemia", "b": "Guaranteed detection of one larva always", "c": "All cats identical to dogs sensitivity", "d": "Testing while on preventive always invalid"},
         "a", "Antigen tests detect adult female antigen; early/low infections may miss.",
         {"b": "Sensitivity not 100%.", "c": "Feline heartworm testing differs.", "d": "Preventives don't always invalidate screening."}, "hard"),
        ("Urine specific gravity 1.010 in dog suggests:",
         {"a": "Poor concentrating ability/isosthenuria range warranting evaluation", "b": "Perfect health always", "c": "Dehydration always", "d": "Not measurable in dogs"},
         "a", "Persistently low USG may indicate renal disease or other pathology.",
         {"b": "Context needed.", "c": "Dehydration usually raises USG.", "d": "Measurable."}, "hard"),
        ("Snap test invalid result line missing control should be:",
         {"a": "Repeated with new device; invalid not interpreted", "b": "Called positive anyway", "c": "Called negative to save cost", "d": "Photoshopped in record"},
         "a", "In-house tests require valid control line before result interpretation.",
         {"b": "Invalid unusable.", "c": "Cannot assume negative.", "d": "Fraudulent."}, "easy"),
        ("Microscope oil immersion objective requires:",
         {"a": "Drop of immersion oil between slide and 100x objective", "b": "Water on dry 4x only", "c": "No cover slip ever", "d": "Cleaning never after use"},
         "a", "Oil couples 100x lens to slide; clean after use to prevent damage.",
         {"b": "Wrong lens/fluid.", "c": "Thin smears use cover slip.", "d": "Oil must be wiped."}, "medium"),
        ("Reference lab sample submission needs:",
         {"a": "Correct tube, fasting status noted, patient ID, and shipping temperature requirements", "b": "Unlabeled tube in envelope", "c": "Hemolyzed sample without note", "d": "Weekend delay at room temp for unstable test always OK"},
         "a", "Lab rejection occurs with wrong tube, hemolysis, or improper transport.",
         {"b": "ID required.", "c": "Note hemolysis; may recollect.", "d": "Some tests require refrigeration."}, "medium"),
        ("Blood glucose meter in clinic should be:",
         {"a": "Calibrated/quality controlled per manufacturer for species if applicable", "b": "Human meter on bird without validation", "c": "Never cleaned", "d": "Shared lancet between all patients"},
         "a", "QC checks and species-appropriate meters improve accuracy.",
         {"b": "Species differences affect readings.", "c": "Cleaning prevents contamination.", "d": "Single-use lancets prevent disease spread."}, "medium"),
        ("Ultrasound gel purpose:",
         {"a": "Coupling transducer to skin eliminating air artifacts", "b": "Sterilizing surgical field", "c": "Oral rehydration", "d": "Radiation shielding"},
         "a", "Gel transmits sound waves; warm if needed for patient comfort.",
         {"b": "Not antiseptic primary.", "c": "Not ingestible.", "d": "Not radiation related."}, "easy"),
        ("Cytology of sebaceous adenoma typically shows:",
         {"a": "Clusters of sebaceous cells often with basaloid proliferation per pathologist read", "b": "Malaria parasites", "c": "Red blood cells only always malignant", "d": "Plant pollen only means cancer"},
         "a", "Sebaceous tumors have characteristic cytology; pathologist confirms.",
         {"b": "Unrelated.", "c": "Not automatic malignancy.", "d": "Pollen contamination possible benign."}, "hard"),
        ("ELISA heartworm test positive should prompt:",
         {"a": "DVM interpretation, confirmatory testing if indicated, and staging before treatment", "b": "Immediate melarsomine without evaluation always at home", "c": "Ignore if asymptomatic", "d": "Client internet treatment only"},
         "a", "Adulticide therapy requires staging, microfilaria status, and complication assessment.",
         {"b": "Treatment protocol complex.", "c": "Asymptomatic still needs plan.", "d": "Unsafe without DVM."}, "hard"),
        ("Skin scraping deep enough for demodex should:",
         {"a": "Cause capillary ooze sampled from several sites", "b": "Be superficial hair only always", "c": "Use oil or liquid on slide per technique", "d": "Never examine under microscope"},
         "a", "Deep scrapings to blood with mineral oil help recover Demodex mites.",
         {"b": "Superficial misses mites.", "c": "Oil aids mite recovery.", "d": "Microscopy essential."}, "medium"),
        ("Quality assurance in lab includes:",
         {"a": "Control runs, maintenance logs, and proficiency testing when applicable", "b": "Skipping controls to save money", "c": "One calibration at install forever", "d": "Hide QC failures"},
         "a", "QA documents accuracy/reliability of diagnostic equipment and processes.",
         {"b": "Controls required.", "c": "Periodic calibration needed.", "d": "Failures must be addressed."}, "easy"),
    ])

    qs += pack(E, "surgery-dentistry", [
        ("Preoperative fasting in dog typically aims to:",
         {"a": "Reduce aspiration risk under anesthesia", "b": "Improve coat shine only", "c": "Allow full meal 1 hour before always", "d": "Eliminate need for IV fluids"},
         "a", "NPO guidelines reduce regurgitation/aspiration during induction/recovery.",
         {"b": "Unrelated.", "c": "Recent food increases risk.", "d": "Fluids still often given."}, "easy"),
        ("Sterile surgical field break occurs when:",
         {"a": "Non-sterile item touches gown, glove, or field", "b": "Scrubbed person maintains hands above waist in field", "c": "Closed pack opened aseptically", "d": "Sterile drape applied after prep"},
         "a", "Any contamination requires discarding affected supplies or re-scrub as policy dictates.",
         {"b": "Correct sterile behavior.", "c": "Proper opening technique.", "d": "Appropriate sequence."}, "medium"),
        ("Anesthetic monitoring includes:",
         {"a": "Heart rate, respiratory rate, BP/perfusion, temperature, depth of anesthesia", "b": "Only nail polish color", "c": "Client opinion only", "d": "No monitoring until recovery"},
         "a", "Multimodal monitoring detects hypotension, hypothermia, and hypoventilation early.",
         {"b": "Insufficient.", "c": "Objective monitoring required.", "d": "Intra-op monitoring mandatory."}, "medium"),
        ("Dental prophy ultrasonic scaler use requires:",
         {"a": "Water flow, proper tip, and post-op radiographs policy per DVM", "b": "Dry scaling without suction always", "c": "No PPE for aerosols", "d": "Extract all teeth routinely"},
         "a", "Dental aerosols require PPE; scaling followed by polishing and assessment.",
         {"b": "Coolant/suction needed.", "c": "Eye/mouth protection important.", "d": "Extractions case-specific."}, "medium"),
        ("Surgical hand scrub prior to gloving includes:",
         {"a": "Mechanical cleaning of nails, hands, forearms per protocol time", "b": "Quick rinse only", "c": "Perfume application", "d": "Reuse previous day's gloves unwashed"},
         "a", "Surgical antisepsis follows timed scrub or approved alcohol-based protocol.",
         {"b": "Inadequate.", "c": "Not antiseptic.", "d": "Gloves require hand antisepsis each case."}, "easy"),
        ("Post-op pain management multimodal approach may combine:",
         {"a": "Local blocks, NSAIDs (if safe), opioids as DVM orders", "b": "No analgesia because animals hide pain myth only", "c": "Human acetaminophen routinely in cats", "d": "Alcohol rub on incision"},
         "a", "Balanced analgesia improves recovery; species-safe drugs only.",
         {"b": "Pain control standard of care.", "c": "Acetaminophen toxic to cats.", "d": "Harmful to tissue."}, "medium"),
        ("Autoclave sterility indicator strip failure means:",
         {"a": "Pack not sterile—do not use; reprocess", "b": "Use anyway if busy", "c": "Indicator cosmetic only", "d": "Freeze pack instead"},
         "a", "Biological/chemical indicators confirm cycle efficacy.",
         {"b": "Unsafe.", "c": "Indicators validate sterilization.", "d": "Freezing not sterilization."}, "easy"),
        ("Endotracheal tube cuff pressure should be:",
         {"a": "Enough to seal without excessive pressure causing tracheal necrosis", "b": "Maximal inflation always", "c": "Zero inflation always leaking", "d": "Not monitored ever"},
         "a", "Cuff manometry or minimal occlusive volume prevents airway leak and pressure injury.",
         {"b": "Overinflation damages trachea.", "c": "Some seal needed.", "d": "Monitoring recommended."}, "hard"),
        ("Surgical count policy for sponges/instruments:",
         {"a": "Initial and final counts documented; discrepancy resolved before closure", "b": "Counts optional for speed", "c": "Add extra sponge if short", "d": "Ignore if patient small"},
         "a", "Retained foreign bodies prevented by systematic counts.",
         {"b": "Standard of care requires counts.", "c": "Search if discrepancy.", "d": "Size irrelevant."}, "medium"),
        ("Dental radiograph in cat reveals tooth resorption. Treatment decided by:",
         {"a": "DVM based on staging and pain", "b": "Technician alone without DVM", "c": "Ignore unless loose", "d": "Always wait until jaw fracture"},
         "a", "Tooth resorption painful; extraction or treatment per veterinary dental guidelines.",
         {"b": "DVM treatment plan.", "c": "Hidden pain may exist.", "d": "Proactive care before fracture."}, "hard"),
        ("Patient warming after anesthesia prevents:",
         {"a": "Hypothermia prolonging recovery and coagulopathy", "b": "All pain forever", "c": "Need for monitoring", "d": "Shivering only in humans"},
         "a", "Perioperative hypothermia common; warm air blankets/fluids help.",
         {"b": "Pain separate issue.", "c": "Monitoring still required.", "d": "Animals shiver too."}, "easy"),
        ("Scrub cap and mask in surgery reduce:",
         {"a": "Contamination from hair and droplet spread", "b": "Hearing permanently", "c": "Need for sterile gloves", "d": "Anesthetic gas use entirely"},
         "a", "PPE minimizes surgical site infection risk.",
         {"b": "Temporary adjustment.", "c": "Gloves still required.", "d": "Gas still used."}, "easy"),
        ("Extracting deciduous tooth retained alongside adult tooth requires:",
         {"a": "DVM extraction to prevent malocclusion/disease", "b": "Client tug at home", "c": "Ignore until abscess only", "d": "Human pediatric dentist"},
         "a", "Retained deciduous teeth cause periodontal issues; professional extraction indicated.",
         {"b": "Unsafe.", "c": "Early intervention better.", "d": "Veterinary dental care."}, "medium"),
        ("Laser surgery smoke evacuation important because:",
         {"a": "Plume contains harmful particulates/bacteria/viable HPV in human literature; use evacuation", "b": "Smoke improves visibility only", "c": "Blow toward open door at staff", "d": "No PPE needed ever"},
         "a", "Surgical plume hazardous; evacuation and masks protect staff.",
         {"b": "Health hazard primary concern.", "c": "Unsafe exposure.", "d": "PPE recommended."}, "hard"),
        ("Recovery from anesthesia monitoring includes:",
         {"a": "Airway patency, temperature, pain, and extubation timing when swallow reflex returns", "b": "Immediate unattended kennel exit", "c": "Pull ET tube mid-anesthetic depth without swallow", "d": "No observation until next day"},
         "a", "Recovery is critical phase for airway obstruction and hypothermia.",
         {"b": "Supervision required.", "c": "Extubate when swallowing present.", "d": "Continuous early recovery monitoring."}, "medium"),
    ])

    assert len(qs) == 60
    return qs


if __name__ == "__main__":
    from _common import write_bank
    write_bank("veterinary-technician-vtne-readiness-check", build())
