#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "water-treatment-operator-1-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "treatment", [
        ("Coagulation in water treatment primarily:",
         {"a": "Destabilizes colloidal particles so they can aggregate", "b": "Disinfects water by killing all pathogens instantly always", "c": "Removes dissolved oxygen entirely always as primary goal always", "d": "Softens water by ion exchange exclusively always in all plants always"},
         "a", "Coagulants like alum neutralize charges on fine particles for flocculation.",
         {"b": "Disinfection is separate step.", "c": "Not primary coagulation purpose.", "d": "Softening is different process."}, "easy"),
        ("Flocculation follows coagulation and provides:",
         {"a": "Gentle mixing to form settleable floc particles", "b": "High-speed mixing to break apart all particles always always", "c": "Final chlorination exclusively always during flocculation always always", "d": "Filtration through anthracite exclusively always as flocculation definition always always"},
         "a", "Slow mixing allows particle collision and floc growth.",
         {"b": "Gentle not destructive mixing.", "c": "Separate process step.", "d": "Filtration follows settling."}, "easy"),
        ("Sedimentation basins remove particles primarily by:",
         {"a": "Gravity settling of floc to the basin floor", "b": "Boiling water at 212°F exclusively always in basin always always", "c": "Magnetic attraction exclusively always for all particles always always", "d": "Reverse osmosis exclusively always in conventional basin always always"},
         "a", "Quiescent zones allow floc to settle as sludge.",
         {"b": "Not boiling treatment.", "c": "Gravity process.", "d": "RO is separate membrane process."}, "easy"),
        ("Rapid sand filters remove:",
         {"a": "Remaining suspended particles after sedimentation", "b": "All dissolved minerals completely always in one pass always always", "c": "Only pathogens by UV exclusively always inside sand always always", "d": "Only taste and odor with no particle removal ever always always"},
         "a", "Filtration captures floc and fine particles; some bacteria reduction.",
         {"b": "Dissolved solids need other treatment.", "c": "Physical straining/adsorption.", "d": "Particle removal primary."}, "easy"),
        ("Chlorine disinfection effectiveness depends strongly on:",
         {"a": "Contact time and residual concentration (CT concept)", "b": "Only water color exclusively always", "c": "Ambient air pressure exclusively always without water chemistry ever always", "d": "Filter media depth exclusively always as sole factor always always"},
         "a", "CT (concentration × time) must meet requirements for pathogen inactivation.",
         {"b": "Chemistry and contact time matter.", "c": "Water quality factors.", "d": "Disinfection separate from filtration."}, "medium"),
        ("A breakpoint chlorination curve shows:",
         {"a": "Chlorine demand consumed until free residual appears", "b": "Instant free chlorine from first drop always without demand ever always", "c": "Only fluoride addition effects exclusively always always", "d": "Sludge volume exclusively always always"},
         "a", "Initial chlorine reacts with reducing substances until breakpoint free Cl₂ forms.",
         {"b": "Demand must be satisfied first.", "c": "Different chemical.", "d": "Different process."}, "hard"),
        ("Hard water contains elevated:",
         {"a": "Calcium and magnesium ions", "b": "Only sodium chloride exclusively always as hardness always always", "c": "Dissolved oxygen exclusively always defining hardness always always", "d": "Suspended clay exclusively always as hardness definition always always"},
         "a", "Hardness measures Ca²⁺ and Mg²⁺ concentration.",
         {"b": "Sodium not hardness.", "c": "Gas not hardness.", "d": "Suspended not dissolved hardness."}, "easy"),
        ("Ion exchange softening replaces hardness ions with:",
         {"a": "Sodium (or potassium) on resin beads", "b": "Iron filings exclusively always permanently always", "c": "Chlorine gas exclusively always in resin always always", "d": "Silica sand exclusively always without resin ever always always"},
         "a", "Cation exchange resin swaps Ca/Mg for Na during service cycle.",
         {"b": "Not mechanism.", "c": "Not exchange product.", "d": "Resin media required."}, "medium"),
        ("Activated carbon filters are especially effective for:",
         {"a": "Removing taste, odor, and many organic compounds", "b": "Adding hardness minerals always as primary function always always", "c": "Generating chlorine residual exclusively always always", "d": "Increasing turbidity intentionally always always"},
         "a", "GAC adsorbs organic micropollutants affecting taste/odor.",
         {"b": "Does not add hardness.", "c": "May remove chlorine.", "d": "Reduces contaminants."}, "medium"),
        ("Lime-soda ash softening precipitates hardness by:",
         {"a": "Raising pH to form calcium carbonate and magnesium hydroxide precipitates", "b": "Lowering pH to dissolve all minerals always always as softening method always always", "c": "Filtering through paper exclusively always always", "d": "Boiling exclusively always in all municipal plants always always as only method always always"},
         "a", "Chemical precipitation softening uses lime/soda ash.",
         {"b": "Raises not lowers pH.", "c": "Chemical not paper.", "d": "One of several methods."}, "hard"),
        ("Membrane processes like reverse osmosis remove:",
         {"a": "Dissolved ions and many small molecules", "b": "Only large floating debris exclusively always with no ion removal ever always", "c": "Only chlorine taste exclusively always without TDS reduction ever always always", "d": "Air exclusively always always"},
         "a", "RO membranes reject dissolved salts and many contaminants.",
         {"b": "Fine filtration/ionic rejection.", "c": "Reduces TDS.", "d": "Liquid phase."}, "medium"),
        ("Fluoridation in public water supplies aims to:",
         {"a": "Reduce dental caries at optimal concentration (~0.7 mg/L target historically adjusted)", "b": "Disinfect water as primary purpose always replacing chlorine always always", "c": "Increase water hardness always as fluoride goal always always", "d": "Remove all minerals always always"},
         "a", "Fluoride strengthens enamel; dose carefully controlled.",
         {"b": "Disinfection is chlorine/chloramine.", "c": "Unrelated.", "d": "Not demineralization."}, "easy"),
        ("Corrosion control often adjusts pH and alkalinity to:",
         {"a": "Form protective scale and minimize lead/copper leaching from pipes", "b": "Maximize pipe corrosion always as goal always always", "c": "Eliminate all chlorine residual always always", "d": "Increase turbidity always always"},
         "a", "Orthophosphate or pH/alkalinity adjustment reduces metal leaching.",
         {"b": "Opposite goal.", "c": "Maintains disinfectant often.", "d": "Clear water goal."}, "medium"),
        ("Sludge from sedimentation basins is:",
         {"a": "Thickened and dewatered before disposal", "b": "Returned directly to finished water always without treatment ever always always", "c": "Sold as drinking water always always", "d": "Pumped into distribution mains always always as standard practice always always"},
         "a", "Sludge handling includes thickening, dewatering, and proper disposal.",
         {"b": "Not returned to product.", "c": "Waste stream.", "d": "Separate waste handling."}, "easy"),
        ("Jar tests in a treatment plant laboratory simulate:",
         {"a": "Optimal coagulant dose and pH for floc formation", "b": "Customer billing cycles exclusively always always", "c": "Fire pump flow exclusively always always", "d": "Employee scheduling exclusively always always"},
         "a", "Jar testing determines best chemical doses on raw water samples.",
         {"b": "Operational lab test.", "c": "Fire system.", "d": "Administrative."}, "medium"),
    ])

    qs += pack(E, "labs", [
        ("Turbidity is measured in:",
         {"a": "Nephelometric Turbidity Units (NTU)", "b": "Degrees Fahrenheit exclusively always for turbidity always always", "c": "Milligrams of chlorine exclusively always always", "d": "Volts exclusively always always"},
         "a", "NTU quantifies light scatter from suspended particles.",
         {"b": "Temperature unit.", "c": "Concentration not turbidity.", "d": "Electrical unit."}, "easy"),
        ("Coliform bacteria testing indicates:",
         {"a": "Potential pathway for pathogens; sanitary quality indicator", "b": "Exact count of viruses always precisely always from coliform alone always always", "c": "Water hardness exclusively always always", "d": "Fluoride concentration exclusively always always"},
         "a", "Total coliform/E. coli are indicator organisms for contamination.",
         {"b": "Indicators not pathogen ID.", "c": "Different test.", "d": "Different analyte."}, "medium"),
        ("pH measurement using a meter requires:",
         {"a": "Regular calibration with buffer solutions", "b": "No calibration ever according to best practice always always", "c": "Only distilled oil as buffer always always", "d": "Measurement only once per year always always regardless of use always always"},
         "a", "Electrodes drift; buffers at known pH verify accuracy.",
         {"b": "Calibration essential.", "c": "Standard pH buffers used.", "d": "Daily/shift calibration common."}, "easy"),
        ("Total chlorine residual includes:",
         {"a": "Free available chlorine plus combined chlorine", "b": "Only fluoride always always", "c": "Only dissolved iron always always", "d": "Only turbidity always always"},
         "a", "Total = free Cl₂ + chloramines/combined forms.",
         {"b": "Different parameter.", "c": "Metal analysis.", "d": "Clarity measure."}, "medium"),
        ("Grab sample vs composite sample:",
         {"a": "Grab is single point in time; composite combines over time/flow", "b": "Grab always averages a week automatically always always without collector ever always", "c": "Composite is always one second only always always", "d": "Both identical always always"},
         "a", "Composite samples represent average conditions over interval.",
         {"b": "Single moment.", "c": "Composite is time/flow weighted.", "d": "Different purposes."}, "medium"),
        ("Chain of custody documentation ensures:",
         {"a": "Sample integrity and traceability from collection to lab analysis", "b": "Samples can be altered without record always always", "c": "No identification of sampler required ever always always", "d": "Results need not be reported always always"},
         "a", "Chain of custody logs transfers and prevents tampering questions.",
         {"b": "Accountability required.", "c": "Identification required.", "d": "Reporting mandatory."}, "easy"),
        ("Alkalinity in water measures capacity to:",
         {"a": "Neutralize acid (buffering capacity)", "b": "Conduct electricity exclusively always defining alkalinity always always", "c": "Float oil exclusively always always", "d": "Measure chlorine exclusively always always"},
         "a", "Alkalinity reflects bicarbonate/carbonate/hydroxide buffering.",
         {"b": "Conductivity different.", "c": "Unrelated.", "d": "Separate test."}, "medium"),
        ("BOD (Biochemical Oxygen Demand) indicates:",
         {"a": "Organic pollution consuming oxygen over incubation period", "b": "Total dissolved solids exclusively always always", "c": "Free chlorine exclusively always always", "d": "Radioactivity exclusively always always"},
         "a", "BOD5 measures oxygen depleted by microbial oxidation of organics.",
         {"b": "TDS separate.", "c": "Disinfectant residual.", "d": "Different hazard."}, "hard"),
        ("Membrane filter technique for coliforms uses:",
         {"a": "Filtering sample through membrane then incubating on selective media", "b": "Boiling sample until all bacteria explode visibly always always", "c": "Weighing sludge on truck scale exclusively always always", "d": "Tasting sample for sweetness exclusively always always"},
         "a", "MF method counts colony-forming units on m-Endo or similar media.",
         {"b": "Not valid method.", "c": "Lab scale filtration.", "d": "Unsafe/invalid."}, "medium"),
        ("Standard Methods for Examination of Water and Wastewater is:",
         {"a": "Authoritative reference for approved analytical procedures", "b": "Novel fiction exclusively always always", "c": "Employee handbook for vacation only always always", "d": "Pipe fitting catalog exclusively always always"},
         "a", "Standard Methods published jointly by AWWA/APHA/WEF.",
         {"b": "Technical reference.", "c": "Analytical manual.", "d": "Equipment may be referenced."}, "easy"),
        ("Colorimetric chlorine test (DPD method) measures:",
         {"a": "Free or total chlorine by color intensity compared to standards", "b": "Hardness exclusively always with DPD always always", "c": "Turbidity exclusively always with DPD always always", "d": "Bacteria count directly always with DPD always always"},
         "a", "DPD reagent produces color proportional to chlorine concentration.",
         {"b": "Different reagents for hardness.", "c": "Turbidimeter used.", "d": "Microbiological method separate."}, "easy"),
        ("Preservation of samples for metals analysis often requires:",
         {"a": "Acidification to pH <2 to prevent precipitation/adsorption", "b": "Adding sugar to feed bacteria always always", "c": "Heating to boiling always always before shipping always always", "d": "Leaving uncapped in sunlight always always as preservation always always"},
         "a", "HNO₃ preservation keeps dissolved metals stable for analysis.",
         {"b": "Contaminates sample.", "c": "May precipitate metals.", "d": "Degrades sample."}, "hard"),
        ("QA/QC in the laboratory includes:",
         {"a": "Blanks, duplicates, spikes, and control charts", "b": "Only random guessing always always", "c": "Deleting outlier data without documentation always always as policy always always", "d": "Avoiding calibration always always"},
         "a", "Quality assurance verifies accuracy and precision of results.",
         {"b": "Systematic QC required.", "c": "Must document.", "d": "Calibration required."}, "medium"),
        ("Conductivity increases with:",
         {"a": "Higher concentration of dissolved ions", "b": "Pure distilled water with no ions always always highest conductivity always always", "c": "Lower temperature always increasing conductivity without exception always always in all waters always always", "d": "Removal of all salts always increasing conductivity always always"},
         "a", "Conductivity approximates TDS from ionic content.",
         {"b": "Pure water low conductivity.", "c": "Temperature effect varies.", "d": "Fewer ions lower conductivity."}, "medium"),
        ("Reporting MCL violations requires:",
         {"a": "Notification to state agency and public per regulations", "b": "No action ever always hiding results always always", "c": "Only verbal notice to one employee always always sufficient always always federally always always", "d": "Destroying records always always"},
         "a", "Safe Drinking Water Act requires public notification tiers.",
         {"b": "Illegal.", "c": "Formal public notice required.", "d": "Records retained."}, "medium"),
    ])

    qs += pack(E, "safety", [
        ("Chlorine gas leaks require operators to:",
         {"a": "Evacuate upwind, notify emergency response, use SCBA for entry", "b": "Enter immediately without respiratory protection always always", "c": "Hide leak from supervisors always always", "d": "Use only dust mask for chlorine always always as adequate always always"},
         "a", "Cl₂ is toxic; trained response with respiratory protection and wind awareness.",
         {"b": "Extremely dangerous.", "c": "Must report immediately.", "d": "Insufficient protection."}, "easy"),
        ("Confined space entry at tanks requires:",
         {"a": "Permit, atmospheric testing, ventilation, and attendant", "b": "Solo entry without testing always always", "c": "Only flashlight without gas monitor always always", "d": "Opening hatch and jumping in always always sufficient always always"},
         "a", "OSHA confined space rules mandate testing and rescue planning.",
         {"b": "Never alone.", "c": "Multi-gas monitor required.", "d": "Permit space protocol."}, "medium"),
        ("Lockout/tagout (LOTO) protects workers by:",
         {"a": "Isolating energy sources during maintenance", "b": "Speeding up repairs without shutting equipment always always", "c": "Removing all guards permanently always always", "d": "Working on live pumps without procedure always always"},
         "a", "LOTO prevents accidental energization during service.",
         {"b": "Safety requires isolation.", "c": "Guards required.", "d": "Procedure mandatory."}, "easy"),
        ("Sodium hydroxide (caustic soda) spills should be:",
         {"a": "Neutralized and cleaned with appropriate PPE avoiding skin/eye contact", "b": "Ignored because harmless always always", "c": "Mixed with acid without ventilation always always casually always always", "d": "Tasted to confirm identity always always"},
         "a", "Caustic causes severe burns; dilute/neutralize per SDS procedures.",
         {"b": "Highly corrosive.", "c": "Controlled neutralization with ventilation.", "d": "Never taste chemicals."}, "medium"),
        ("Hydrogen sulfide (H₂S) at wastewater facilities:",
         {"a": "Is toxic, flammable, and detected by rotten egg odor at low levels", "b": "Is safe to breathe in any concentration always always", "c": "Only occurs in finished drinking water always always", "d": "Has no odor ever always making detection impossible always always"},
         "a", "H₂S causes rapid olfactory fatigue; monitor with detectors.",
         {"b": "IDLH at high ppm.", "c": "Raw/sewer contexts.", "d": "Distinct odor initially."}, "medium"),
        ("Personal protective equipment for acid handling includes:",
         {"a": "Face shield, chemical goggles, gloves, and apron", "b": "Open-toed sandals always always", "c": "No gloves to improve grip on acid always always", "d": "Only hearing protection always always"},
         "a", "Acids require splash protection and resistant gloves.",
         {"b": "Foot protection needed.", "c": "Chemical gloves required.", "d": "Eye/face primary."}, "easy"),
        ("Material Safety Data Sheet / Safety Data Sheet (SDS) provides:",
         {"a": "Hazards, handling, PPE, and emergency measures for chemicals", "b": "Customer water bills exclusively always always", "c": "Only stock prices always always", "d": "Pipe diameter exclusively always always"},
         "a", "SDS (GHS) details chemical safety information.",
         {"b": "Billing document.", "c": "Financial.", "d": "Engineering spec maybe separate."}, "easy"),
        ("Rotating equipment guards must:",
         {"a": "Remain in place during operation to prevent entanglement", "b": "Be removed for normal operation always always", "c": "Only protect equipment not people always always", "d": "Be optional if operator is experienced always always per OSHA always always"},
         "a", "Machine guarding is OSHA requirement.",
         {"b": "Guards mandatory.", "c": "Worker protection purpose.", "d": "Not optional."}, "easy"),
        ("Electrical panels in wet areas require:",
         {"a": "GFCI protection and appropriate NEMA enclosures", "b": "Open panels for cooling always always", "c": "Standing water contact encouraged always always", "d": "No grounding ever always"},
         "a", "Wet locations need watertight enclosures and shock protection.",
         {"b": "Enclosed for safety.", "c": "Electrocution hazard.", "d": "Grounding required."}, "medium"),
        ("Backflow prevention protects:",
         {"a": "Potable water from contamination via cross-connections", "b": "Only fire hydrant paint always always", "c": "Filter media exclusively always always from chlorine always always", "d": "Employee parking always always exclusively always"},
         "a", "Backflow devices stop reverse flow from non-potable sources.",
         {"b": "Public health function.", "c": "Distribution protection.", "d": "Unrelated."}, "medium"),
        ("Heat stress prevention on outdoor jobs includes:",
         {"a": "Hydration, shade/rest breaks, and acclimatization", "b": "Avoiding all water intake always always", "c": "Maximum exertion at noon always always", "d": "Heavy chemical suits without breaks always always in heat always always"},
         "a", "Water, rest, shade reduce heat illness risk.",
         {"b": "Hydration critical.", "c": "Schedule work cooler hours.", "d": "PPE balance needed."}, "easy"),
        ("A near-miss report should:",
         {"a": "Be documented to prevent future incidents", "b": "Be ignored because no injury occurred always always", "c": "Punish reporter always always as policy always always", "d": "Never be shared with safety committee always always"},
         "a", "Near-miss analysis improves safety culture proactively.",
         {"b": "Learning opportunity.", "c": "Non-punitive reporting encouraged.", "d": "Review improves practice."}, "easy"),
        ("Emergency eyewash stations must be:",
         {"a": "Accessible within 10 seconds of chemical splash areas (general industry guidance)", "b": "Located only in administrative office always always far from chemicals always always", "c": "Used monthly as drinking fountain always always", "d": "Frozen shut in winter always always acceptable always always"},
         "a", "ANSI Z358.1 requires accessible eyewash/showers.",
         {"b": "Near hazard zones.", "c": "Potable separate.", "d": "Must function."}, "medium"),
        ("Excavation trench safety requires:",
         {"a": "Sloping, shoring, or trench box per OSHA when depth exceeds 5 feet", "b": "Vertical walls always without protection always always at any depth always always", "c": "Workers inside during cave-in always always", "d": "No atmospheric testing in deep trenches ever always always"},
         "a", "OSHA 1926 Subpart P protects from collapse.",
         {"b": "Protection required.", "c": "Evacuate on instability.", "d": "May need testing."}, "hard"),
        ("Hearing conservation program triggers when noise exceeds:",
         {"a": "OSHA action level 85 dBA TWA with monitoring and PPE", "b": "20 dBA always always for all workplaces always always", "c": "Only jet engine levels always always without measurement ever always always", "d": "Never in water plants always always regardless of equipment always always"},
         "a", "Pumps/blowers may exceed action level requiring program.",
         {"b": "Too low.", "c": "Measurement determines.", "d": "Industrial noise possible."}, "hard"),
    ])

    qs += pack(E, "regs", [
        ("Safe Drinking Water Act (SDWA) is administered primarily by:",
         {"a": "EPA setting standards and overseeing states", "b": "Local grocery stores exclusively always always", "c": "Federal Reserve exclusively always always", "d": "Private bottled water companies exclusively always always as regulators always always"},
         "a", "EPA establishes MCLs and primacy states enforce.",
         {"b": "Not regulatory role.", "c": "Financial regulator.", "d": "FDA regulates bottled water differently."}, "easy"),
        ("Maximum Contaminant Level (MCL) is:",
         {"a": "Legally enforceable limit on contaminant concentration in public water", "b": "Suggested goal with no enforcement always always for all parameters always always", "c": "Operator salary cap exclusively always always", "d": "Pipe pressure exclusively always always"},
         "a", "MCLs are binding; MCLGs are non-enforceable health goals.",
         {"b": "MCLG differs.", "c": "Unrelated.", "d": "Hydraulic not water quality."}, "medium"),
        ("Public water system annual Consumer Confidence Report (CCR):",
         {"a": "Informs customers of water sources and detected contaminants", "b": "Is secret from public always always", "c": "Only lists employee names always always", "d": "Replaces all monitoring always always"},
         "a", "CCR (water quality report) required for community systems.",
         {"b": "Public document.", "c": "Water quality data.", "d": "Monitoring continues."}, "easy"),
        ("Operator certification requirements are typically set by:",
         {"a": "State environmental or health agencies", "b": "International Space Station exclusively always always", "c": "Individual customers exclusively always always", "d": "Social media polls exclusively always always"},
         "a", "States certify water/wastewater operators by class and system type.",
         {"b": "State primacy.", "c": "Regulatory authority.", "d": "Formal process."}, "easy"),
        ("Coliform MCL under Total Coliform Rule reflects:",
         {"a": "No more than 5% monthly samples positive (with conditions)", "b": "100% samples must be positive always always", "c": "Zero monitoring required always always", "d": "Only taste criteria always always"},
         "a", "TCR uses presence/absence and E. coli follow-up triggers.",
         {"b": "Positive indicates problem.", "c": "Regular monitoring.", "d": "Microbiological standard."}, "hard"),
        ("Lead and Copper Rule requires:",
         {"a": "Corrosion control treatment and tap sampling at customer sites", "b": "No sampling ever always always", "c": "Only source water sampling always always without tap monitoring ever always always", "d": "Replacing all pipes overnight always always as only option always always"},
         "a", "LCR focuses on corrosion control and consumer tap monitoring.",
         {"b": "Tap sampling required.", "c": "Both source and tap.", "d": "Action levels trigger response."}, "medium"),
        ("Stage 2 Disinfection Byproducts Rule limits:",
         {"a": "TTHM and HAA5 based on locational running annual averages", "b": "Only fluoride always always as DBP always always", "c": "Only turbidity always always as DBP always always", "d": "Employee hours always always"},
         "a", "DBPs form when disinfectants react with NOM; LRAA compliance.",
         {"b": "Halogenated organics.", "c": "Particle measure.", "d": "Unrelated."}, "hard"),
        ("Under EPA definition, a community water system serves:",
         {"a": "At least 25 year-round residents or 15 service connections", "b": "Only one mobile home always always regardless of connections always always", "c": "Only industries always always with zero residents always always as community always always", "d": "Only bottled water always always"},
         "a", "CWS serves residents; NTNCWS and TNCWS differ.",
         {"b": "Threshold matters.", "c": "Community serves residents.", "d": "PWS pipe delivery."}, "medium"),
        ("Sanitary survey evaluates:",
         {"a": "Source, treatment, distribution, and compliance of PWS", "b": "Only office décor exclusively always always", "c": "Stock market exclusively always always", "d": "Operator uniform color exclusively always always"},
         "a", "State/EPA surveys assess technical/managerial/financial capacity.",
         {"b": "Technical review.", "c": "Unrelated.", "d": "Operational focus."}, "medium"),
        ("Variance or exemption from MCL:",
         {"a": "May be granted under strict SDWA conditions with public notice", "b": "Automatic for any utility requesting always always", "c": "Available for all contaminants without limits always always", "d": "Granted by social media vote always always"},
         "a", "Variances/exemptions limited by statute and monitoring.",
         {"b": "Rare and regulated.", "c": "Not universal.", "d": "Formal regulatory process."}, "hard"),
        ("Cross-connection control program is required to:",
         {"a": "Prevent backflow contamination in distribution system", "b": "Increase cross-connections always always", "c": "Eliminate all backflow preventers always always", "d": "Only protect wastewater plant always always not drinking always always"},
         "a", "State/local rules mandate backflow prevention testing.",
         {"b": "Prevent not increase.", "c": "Devices required.", "d": "Potable system focus."}, "medium"),
        ("AWWA standards primarily address:",
         {"a": "Water industry materials, design, and practice", "b": "Aviation safety exclusively always always", "c": "Medical licensing exclusively always always", "d": "Securities trading exclusively always always"},
         "a", "American Water Works Association publishes industry standards.",
         {"b": "Water focus.", "c": "Unrelated.", "d": "Finance."}, "easy"),
        ("Tier 1 public notice is required for:",
         {"a": "Immediate acute health risk violations (e.g., certain microbial)", "b": "Minor paperwork delays only always always as tier 1 always always", "c": "No violations ever always always", "d": "Annual picnic announcement always always as tier 1 always always"},
         "a", "Tier 1 requires notice within 24 hours for acute risks.",
         {"b": "Lower tiers for lesser risks.", "c": "Violation triggered.", "d": "Not public notice tier."}, "medium"),
        ("Log inactivation in disinfection credit refers to:",
         {"a": "Log₁₀ reduction of pathogens (1 log = 90% reduction)", "b": "Paper log book pages exclusively always always", "c": "Employee login password exclusively always always", "d": "Wood logging exclusively always always"},
         "a", "Surface Water Treatment Rule uses log removal/inactivation credits.",
         {"b": "Microbial math.", "c": "IT unrelated.", "d": "Forestry."}, "hard"),
        ("Primacy agency in SDWA context is:",
         {"a": "State (or EPA region) authorized to enforce drinking water rules", "b": "Private bottled water vendor exclusively always always", "c": "Local restaurant exclusively always always", "d": "Fire department exclusively always always for all SDWA always always"},
         "a", "States with primacy implement SDWA; EPA oversees.",
         {"b": "FDA bottled water.", "c": "Not primacy.", "d": "May assist emergencies not primacy."}, "medium"),
    ])

    return qs


if __name__ == "__main__":
    write_bank(E, build())
