#!/usr/bin/env python3
"""Build the locally authored LEED Green Associate readiness-check bank."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SLUG = "leed-green-associate-readiness-check"
TOPICS = {
    "integrative-process": [
        ("Why should a project team hold an early sustainability charrette?", "It brings key disciplines together before major design decisions limit options."),
        ("What is the primary purpose of the Owner's Project Requirements document?", "It records the owner's functional, performance, and sustainability goals."),
        ("What does the Basis of Design describe?", "How the design team intends to meet the Owner's Project Requirements."),
        ("During integrative analysis, why are energy and water systems considered together?", "A decision in one system can change loads and opportunities in the other."),
        ("Which phase offers the greatest opportunity to influence a building's life-cycle impacts?", "Pre-design and early design, before fundamental choices are fixed."),
        ("What is systems thinking in a green building project?", "Evaluating how building components interact rather than optimizing each in isolation."),
        ("Why would a team analyze site conditions before selecting a building orientation?", "Sun, wind, vegetation, and access can shape passive design opportunities."),
        ("What is a useful output of preliminary energy analysis?", "A comparison of massing, orientation, envelope, and HVAC options."),
        ("What is a useful output of preliminary water analysis?", "A strategy for reducing potable demand and identifying nonpotable sources."),
        ("Why should the landscape architect participate in early project discussions?", "Site, drainage, habitat, and water decisions affect the entire project."),
        ("What is the benefit of setting measurable sustainability goals early?", "The team can evaluate alternatives against agreed project priorities."),
        ("How does an integrative process help control cost?", "It finds synergistic strategies before changes become expensive."),
        ("Why is feedback from operations staff valuable during design?", "They can identify maintainability and operational constraints before construction."),
        ("What does a whole-building approach seek to avoid?", "A single-system improvement that creates an unintended problem elsewhere."),
        ("Why can a smaller HVAC system be a result of good envelope design?", "Reduced heating and cooling loads can reduce equipment capacity needs."),
        ("What is the role of a project scorecard during design?", "It tracks potential prerequisites and credits as decisions evolve."),
        ("Why should financial analysis accompany sustainable design options?", "It helps compare first cost, operating cost, and long-term value."),
        ("What is life-cycle cost?", "The total cost of owning, operating, maintaining, and replacing an asset over time."),
        ("Why are assumptions documented in an integrative analysis?", "The team can revisit and verify the basis for important decisions."),
        ("What is a trade-off analysis?", "A comparison of alternatives that identifies benefits, costs, and interactions."),
        ("Why might a team reconsider glazing area during early modeling?", "Window area affects daylight, views, heat gain, heat loss, and HVAC sizing."),
        ("What is the value of defining project goals by category?", "It makes priorities for site, water, energy, materials, and health explicit."),
        ("Why involve the commissioning authority early?", "Early involvement can help align systems, testing, and owner expectations."),
        ("What is an example of a passive design strategy?", "Using orientation and shading to reduce unwanted solar heat gain."),
        ("Why is climate analysis important before choosing an HVAC approach?", "Local temperature, humidity, and solar conditions determine appropriate responses."),
        ("What should happen when a proposed strategy conflicts with a key owner need?", "The team should evaluate alternatives and document the trade-off."),
        ("Why are iterative analyses useful in early design?", "Each result can improve the next design decision as information develops."),
        ("What is the difference between a goal and a LEED credit?", "A goal expresses project intent, while a credit has defined LEED requirements."),
        ("Why is an integrated design team broader than an architect and engineer?", "Specialists and stakeholders contribute knowledge that affects building performance."),
        ("What is the purpose of documenting design decisions?", "It preserves the rationale and supports coordination, commissioning, and operations."),
        ("Why can daylighting decisions affect energy performance?", "Daylight can reduce electric lighting while also changing cooling and glare conditions."),
        ("What is a key benefit of evaluating water use by end use?", "It identifies the largest opportunities for targeted conservation."),
        ("Why should renewable energy be considered with efficiency measures?", "Reducing loads can make the renewable system smaller and more cost-effective."),
        ("What is an integrated project delivery behavior?", "Sharing information across disciplines to solve project problems collaboratively."),
        ("Why is a site walk valuable before design begins?", "It reveals existing conditions that maps and assumptions may miss."),
        ("What should a team do after selecting a sustainability strategy?", "Assign responsibility, document it, and verify it through later project phases."),
        ("Why are future adaptability and resilience discussed in early planning?", "Early choices can help the building remain useful under changing conditions."),
        ("What is a design charrette?", "A focused collaborative workshop used to generate and evaluate project ideas."),
        ("Why should a team consider occupant behavior in its analysis?", "Actual use patterns strongly influence energy, water, and indoor environmental outcomes."),
        ("What is the value of comparing a proposed design to a baseline?", "The comparison shows the relative improvement produced by the strategy."),
        ("Why may reducing parking affect stormwater planning?", "Less pavement can reduce runoff and create room for landscape strategies."),
        ("What is a common reason to revisit the Owner's Project Requirements?", "A change in scope or priorities may require the design basis to be updated."),
        ("Why is communication among disciplines essential during schematic design?", "Early coordination prevents incompatible decisions from becoming embedded."),
        ("What does integrated analysis of materials consider?", "Embodied impacts, durability, health, cost, and end-of-life implications together."),
        ("Why should a team identify constraints as well as opportunities?", "Realistic strategies must work within budget, code, schedule, and site limits."),
        ("What is an operational performance goal?", "A target for how the completed building should perform in use."),
        ("Why can building form influence water use?", "Roof area, landscape area, and drainage patterns affect collection and irrigation options."),
        ("What is the benefit of including the contractor in sustainability discussions early?", "Constructability, sequencing, and procurement risks can be identified before bidding."),
        ("Why is an integrative process not a one-time meeting?", "Project decisions and analyses need coordination throughout design and construction."),
        ("What outcome best indicates successful integrative design?", "A coordinated solution that meets owner goals with fewer unintended trade-offs."),
    ],
    "location-transportation": [
        ("What is the environmental benefit of locating a project near daily services?", "It can reduce vehicle trips by allowing occupants to walk or bicycle to destinations."),
        ("Why does LEED value access to quality transit?", "Transit access can reduce reliance on single-occupancy vehicles."),
        ("What is a benefit of redeveloping a previously developed site?", "It can limit pressure to develop undeveloped land."),
        ("Why are bicycle storage facilities included in transportation strategies?", "They make bicycling a more practical commuting option."),
        ("What is the purpose of preferred parking for low-emitting vehicles?", "It encourages use of vehicles with lower tailpipe emissions."),
        ("How can a project reduce parking-related environmental impacts?", "Provide no more parking than needed and support alternative transportation."),
        ("Why is an infill site often advantageous for LEED?", "Existing infrastructure and nearby uses can reduce new land disturbance and driving."),
        ("What does walkability describe?", "How safely and conveniently people can reach destinations on foot."),
        ("Why can mixed-use development reduce transportation impacts?", "Homes, jobs, and services are closer together, reducing trip length."),
        ("What is a transportation demand management strategy?", "A program that reduces single-occupancy driving through alternatives and incentives."),
        ("Why are shower facilities useful in an office building?", "They support employees who commute by bicycle or on foot."),
        ("What is a likely benefit of carpool parking spaces?", "They encourage shared trips that can reduce the number of vehicles traveling to the site."),
        ("Why does LEED discourage development on sensitive land?", "Development can damage habitat, water resources, and ecological functions."),
        ("What is the advantage of using an existing building rather than building on a greenfield?", "It can conserve land and make use of existing infrastructure."),
        ("Why should a project team study neighborhood connectivity?", "Connected streets and paths can make walking, bicycling, and transit access more feasible."),
        ("What is an electric vehicle charging station intended to support?", "The use of plug-in vehicles with lower operational emissions than conventional vehicles."),
        ("Why might a project provide real-time transit information?", "It makes transit use easier to plan and more convenient for occupants."),
        ("What is the role of safe pedestrian crossings near a building?", "They improve access to transit and nearby destinations for people walking."),
        ("Why can excessive parking be a sustainability concern?", "It consumes land, adds impervious surface, and can encourage driving."),
        ("What type of site is generally preferable to an isolated site without services?", "A location with nearby amenities and transportation options."),
        ("Why are short-term bicycle spaces useful?", "They serve visitors making brief trips to the building."),
        ("Why are long-term bicycle spaces useful?", "They provide secure storage for regular building occupants."),
        ("What can a shared parking arrangement accomplish?", "It can reduce the total number of spaces when different users peak at different times."),
        ("Why does access to basic services matter in site selection?", "Nearby services can reduce the need for vehicle trips."),
        ("What is a potential benefit of a compact development pattern?", "It uses land more efficiently and can support transit and walkability."),
        ("Why should a team consider transit service frequency, not only distance?", "Infrequent service may not be a practical alternative to driving."),
        ("What does a complete street typically support?", "Safe travel for pedestrians, cyclists, transit users, and drivers."),
        ("Why can a pedestrian entrance near a transit stop be beneficial?", "It shortens and simplifies the walk between transit and the building."),
        ("What is a likely advantage of locating jobs near housing?", "It can reduce commuting distance and associated emissions."),
        ("Why does a LEED project assess surrounding density?", "Density can indicate whether services and transit can realistically support less driving."),
        ("What transportation benefit can telework infrastructure provide?", "It can reduce the number of commuting trips made to the building."),
        ("Why are ride-sharing and carpool programs relevant to LEED?", "They can reduce single-occupancy vehicle travel."),
        ("What is a benefit of reserving spaces for carpools near an entrance?", "Convenient placement provides an incentive for shared commuting."),
        ("Why might a project provide an on-site car-share vehicle?", "It can reduce the need for occupants to own or drive personal vehicles."),
        ("What is the benefit of connecting a site to an existing bicycle network?", "It gives cyclists a continuous route to destinations beyond the project boundary."),
        ("Why should site access routes be evaluated for people with mobility limitations?", "Equitable access is needed for transportation choices to be practical."),
        ("What does a greenfield site describe?", "Land that has not been previously developed."),
        ("Why can greenfield development have higher infrastructure impacts?", "New roads, utilities, and services may be required to support it."),
        ("What is a benefit of adaptive reuse in Location and Transportation terms?", "It can retain a well-located building and avoid new land consumption."),
        ("Why do LEED transportation strategies focus on occupant trips?", "Commuting and visitor travel can be a significant source of project-related emissions."),
        ("What can wayfinding signs contribute to a walkable site?", "They help people locate safe routes to entrances, transit, and nearby services."),
        ("Why can shaded sidewalks support active transportation?", "More comfortable walking conditions can make trips on foot more appealing."),
        ("What is the purpose of a transportation survey?", "It helps a project understand how occupants travel and identify improvement opportunities."),
        ("Why might an employer subsidize transit passes?", "Lowering the cost of transit can encourage employees to drive less."),
        ("What is a low-emitting vehicle?", "A vehicle designed to produce lower exhaust emissions than a conventional comparable vehicle."),
        ("Why should loading areas be separated from pedestrian paths?", "Separation improves pedestrian safety and reduces conflicts with trucks."),
        ("What does transit-oriented development emphasize?", "Compact development around reliable public transportation."),
        ("Why can proximity to a school or grocery store be relevant to LEED?", "It indicates that everyday needs may be reached without a car."),
        ("What is a likely outcome of better bicycle infrastructure?", "More occupants may consider cycling for some trips."),
        ("Why is location considered before building systems in LEED?", "A site's context can shape transportation, land-use, and infrastructure impacts for decades."),
    ],
    "sites-water": [
        ("What is the purpose of a rain garden?", "It captures and infiltrates stormwater runoff through planted soil areas."),
        ("Why is permeable pavement used on a LEED site?", "It allows water to pass through the surface and can reduce runoff."),
        ("What does heat island effect describe?", "Higher temperatures in developed areas caused by heat-absorbing surfaces."),
        ("How can a high-reflectance roof help a project?", "It absorbs less solar heat and can reduce roof surface temperature."),
        ("Why are native or adapted plants valuable in landscaping?", "They generally need less irrigation and are suited to local conditions."),
        ("What is a key goal of outdoor water use reduction?", "Use less potable water for irrigation."),
        ("Why is irrigation zoning important?", "It applies water according to plant needs instead of treating all areas the same."),
        ("What is a smart irrigation controller designed to do?", "Adjust watering based on weather or soil conditions."),
        ("Why are low-flow plumbing fixtures installed?", "They reduce indoor potable water use."),
        ("What does a WaterSense-labeled fixture indicate?", "It meets water-efficiency criteria established by the EPA program."),
        ("What is a benefit of collecting rainwater for irrigation?", "It can replace potable water for an appropriate nonpotable use."),
        ("Why should stormwater be managed close to where it falls?", "Local infiltration and storage can reduce runoff volume and pollution."),
        ("What does erosion control protect during construction?", "Soil and nearby waterways from sediment carried by runoff."),
        ("Why are construction site entrances stabilized?", "They help prevent soil from being tracked onto public roads and into drains."),
        ("What is the benefit of restoring native habitat on a site?", "It can support biodiversity and improve ecological function."),
        ("Why should a project limit disturbance of existing vegetation?", "Mature vegetation can provide habitat, shade, and stormwater benefits."),
        ("What is open space intended to provide?", "An outdoor area that supports ecological function or human use."),
        ("Why are shade trees valuable over paved areas?", "They reduce solar heating of hardscape and improve outdoor comfort."),
        ("What is a vegetated roof?", "A roof assembly that supports growing media and plants."),
        ("How can a vegetated roof help stormwater management?", "It retains and slows rainfall before it leaves the roof."),
        ("Why should a site plan minimize impervious cover?", "Less impervious surface can reduce runoff and allow more infiltration."),
        ("What is a bioswale?", "A landscaped channel that slows, filters, and infiltrates stormwater."),
        ("Why are soil restoration practices used after construction?", "Compacted soils need improvement to support plants and absorb water."),
        ("What is a benefit of protecting a waterbody buffer?", "It helps filter runoff and protect aquatic habitat near the waterbody."),
        ("Why is potable water a concern for cooling towers?", "Cooling towers can consume substantial water through evaporation and blowdown."),
        ("What is the purpose of cooling-tower water treatment?", "It helps control minerals and biology so water can be used efficiently."),
        ("Why might a project install submeters for irrigation?", "They help track outdoor water use and identify leaks or waste."),
        ("What does a water budget show?", "How much water different building or landscape uses are expected to require."),
        ("Why should leaks be repaired promptly in a water-efficient building?", "A leak can erase the savings expected from efficient fixtures."),
        ("What is the advantage of dual-flush toilets?", "They provide different flush volumes for liquid and solid waste."),
        ("Why can compost improve a planted site's performance?", "It can improve soil structure, water retention, and plant health."),
        ("What is the goal of light pollution reduction?", "Limit unnecessary nighttime light that affects people, wildlife, and the night sky."),
        ("Why are shielded exterior light fixtures used?", "They direct light where needed and reduce spill and glare."),
        ("What is the benefit of using drought-tolerant plants?", "They reduce irrigation demand during dry periods."),
        ("Why should irrigation be avoided during rain or high wind?", "Water applied in those conditions is often wasted or poorly distributed."),
        ("What is a graywater system used for?", "Reusing appropriately treated wastewater for approved nonpotable purposes."),
        ("Why must nonpotable water systems be clearly identified?", "Clear labeling prevents accidental cross-connections with drinking water."),
        ("What is an on-site stormwater detention system?", "A system that temporarily stores runoff and releases it more slowly."),
        ("Why can cisterns support both water and site goals?", "They store rainwater for reuse while reducing peak runoff."),
        ("What is the benefit of reducing turf grass area?", "It can lower mowing, fertilizer, and irrigation needs."),
        ("Why do LEED projects consider pesticide use in landscape management?", "Some chemicals can harm water quality, ecosystems, and human health."),
        ("What is integrated pest management?", "A strategy that prevents and controls pests with the least harmful practical methods."),
        ("Why should rooftop runoff be directed away from building foundations?", "It helps prevent moisture damage while allowing stormwater to be managed safely."),
        ("What can a flow sensor reveal in an irrigation system?", "Unexpected water use that may indicate a leak or malfunction."),
        ("Why are efficient commercial kitchen fixtures relevant to water efficiency?", "Food-service operations can be a major source of indoor water use."),
        ("What does water reuse mean?", "Using captured or treated water again for a suitable nonpotable purpose."),
        ("Why is regional rainfall data useful in stormwater design?", "It helps size strategies for local storm intensity and seasonal patterns."),
        ("What is the benefit of minimizing site disturbance during construction?", "It preserves existing soils, vegetation, and drainage functions."),
        ("Why is outdoor thermal comfort considered in site design?", "Shade, vegetation, and surface choices affect whether outdoor areas are usable."),
        ("What is a practical first step for reducing a building's water use?", "Measure major uses so the team can target the largest opportunities."),
    ],
    "energy-atmosphere": [
        ("What is the purpose of fundamental commissioning?", "Verify that building systems are installed and operate as intended."),
        ("Why is a whole-building energy meter useful?", "It tracks total energy consumption for ongoing management."),
        ("What does energy benchmarking involve?", "Comparing a building's energy performance with similar buildings or past performance."),
        ("Why is a refrigerant management plan important?", "Refrigerants can contribute to ozone depletion or climate change if released."),
        ("What does a building energy model estimate?", "Expected energy use based on the proposed design and operating assumptions."),
        ("Why is an efficient building envelope important?", "It reduces heating and cooling loads before equipment is selected."),
        ("What is the purpose of air sealing?", "Reduce unintended air leakage through the building enclosure."),
        ("Why are high-efficiency lighting controls installed?", "They reduce lighting energy when daylight or occupancy makes full output unnecessary."),
        ("What does occupancy sensing do?", "It turns lights down or off when spaces are unoccupied."),
        ("Why are variable-speed drives used on motors?", "They allow equipment to use less energy at part-load conditions."),
        ("What is the benefit of preventive maintenance for HVAC systems?", "It helps preserve efficiency and detect problems before performance declines."),
        ("Why should a project set an energy performance target?", "A clear target guides design choices and later performance tracking."),
        ("What does demand response encourage?", "Reducing or shifting electricity use during periods of high grid demand."),
        ("Why is renewable energy considered after efficiency measures?", "Lower demand can reduce the renewable capacity needed to meet a goal."),
        ("What is on-site renewable energy?", "Energy generated at the project, such as solar electricity produced on the building site."),
        ("What is green power?", "Electricity generated from eligible renewable sources and supplied through the grid or certificates."),
        ("Why are solar panels often paired with energy efficiency strategies?", "Efficiency reduces the building load that solar generation must offset."),
        ("What does an ENERGY STAR score generally indicate?", "A building's comparative energy performance using a recognized benchmarking method."),
        ("Why is a cooling load calculation needed?", "It helps size cooling equipment for expected heat gains."),
        ("What can excessive equipment sizing cause?", "Short cycling, higher first cost, and reduced operational efficiency."),
        ("Why are economizers used in suitable climates?", "They use favorable outdoor air conditions to reduce mechanical cooling."),
        ("What is heat recovery ventilation?", "A system that transfers heat between exhaust and incoming air streams."),
        ("Why are high-performance windows selected?", "They can reduce heat transfer while maintaining useful daylight and views."),
        ("What does solar heat gain coefficient describe?", "How much solar radiation passes through a window as heat."),
        ("Why is insulation installed continuously where practical?", "It reduces thermal bridging and unwanted heat flow through the enclosure."),
        ("What is a thermal bridge?", "A part of the enclosure that conducts heat more readily than surrounding materials."),
        ("Why are energy use intensity values useful?", "They normalize energy consumption by floor area for comparison."),
        ("What does submetering provide?", "Separate energy-use data for selected systems or end uses."),
        ("Why might a project submeter a data center?", "Its high energy use can be tracked and managed separately from other loads."),
        ("What is the benefit of a building automation system?", "It can monitor and control equipment schedules and operating conditions."),
        ("Why should equipment schedules match occupancy schedules?", "Running equipment only when needed reduces wasted energy."),
        ("What does retro-commissioning address?", "Improving performance of existing building systems through investigation and corrections."),
        ("Why are refrigerant leaks a climate concern?", "Many refrigerants have high global warming potential."),
        ("What is global warming potential?", "A measure of how much heat a gas traps compared with carbon dioxide."),
        ("Why is refrigerant selection part of LEED energy and atmosphere?", "Different refrigerants have different ozone and climate impacts."),
        ("What is the benefit of daylight-responsive dimming?", "Electric lights can use less energy when daylight provides sufficient illumination."),
        ("Why are plug loads considered in energy planning?", "Computers and appliances can be a significant part of building energy use."),
        ("What does load shedding mean?", "Temporarily reducing noncritical electrical demand during peak conditions."),
        ("Why should an owner receive systems training at handover?", "Operators need to understand how to run efficient systems as designed."),
        ("What is measurement and verification?", "Using data to confirm whether building performance meets expectations."),
        ("Why compare actual energy use with a modeled prediction?", "The comparison can reveal operational issues or incorrect assumptions."),
        ("What is the advantage of LED lighting?", "It delivers light using less energy and generally lasts longer than older technologies."),
        ("Why are boiler and chiller efficiencies important?", "Central plant equipment can account for a large share of building energy use."),
        ("What does a low-emitting refrigerant strategy seek to reduce?", "Damage to the ozone layer and contribution to climate change."),
        ("Why is utility data review an ongoing practice?", "Trends can identify unusual consumption and opportunities to improve operations."),
        ("What is a peak demand charge?", "A utility charge based on the highest rate of electricity use during a billing period."),
        ("Why can window shading reduce cooling energy?", "It blocks unwanted solar heat before it enters the building."),
        ("What is the purpose of a commissioning report?", "Document testing results, deficiencies, and corrective actions for the owner."),
        ("Why should energy conservation measures be prioritized by impact and feasibility?", "The team can focus resources on the most practical, meaningful savings."),
        ("What is the central objective of Energy and Atmosphere credits?", "Reduce energy-related environmental impacts while improving building performance."),
    ],
    "materials-ieq": [
        ("What does an environmental product declaration communicate?", "Verified information about a product's environmental impacts over its life cycle."),
        ("Why are life-cycle assessments used in material decisions?", "They compare environmental impacts across a product or building's life stages."),
        ("What is embodied carbon?", "Greenhouse gas emissions associated with making, transporting, and installing materials."),
        ("Why is construction waste management planned before work begins?", "Early planning identifies how materials can be reduced, reused, recycled, or salvaged."),
        ("What is source reduction in construction?", "Preventing waste by ordering and using materials efficiently."),
        ("Why is material reuse valuable?", "It extends the useful life of existing products and can avoid new manufacturing impacts."),
        ("What does recycled content mean?", "A product includes material recovered from a previous use or manufacturing stream."),
        ("Why is responsible wood sourcing important?", "It supports forest practices that protect ecosystems and communities."),
        ("What does a material ingredient disclosure provide?", "Information about chemicals or substances contained in a product."),
        ("Why are low-emitting materials selected?", "They reduce indoor exposure to harmful volatile organic compounds and other pollutants."),
        ("What are volatile organic compounds?", "Carbon-containing chemicals that can be emitted from many indoor products."),
        ("Why is indoor air quality management needed during construction?", "Construction dust and pollutants can contaminate finishes and HVAC systems."),
        ("What is flush-out in an indoor air quality strategy?", "Ventilating a completed building to remove accumulated indoor pollutants before occupancy."),
        ("Why are entryway systems used in buildings?", "They capture dirt and pollutants before they are tracked into occupied spaces."),
        ("What does thermal comfort address?", "Whether indoor temperature, humidity, and air movement are acceptable to occupants."),
        ("Why are operable windows valued in appropriate projects?", "They can give occupants direct control over fresh air and thermal comfort."),
        ("What is daylighting?", "Using natural light to illuminate interior spaces."),
        ("Why must daylighting be balanced with glare control?", "Too much direct sunlight can make work areas uncomfortable and unusable."),
        ("What is a view-quality strategy intended to support?", "Occupant connection to the outdoors through useful, comfortable views."),
        ("Why is acoustic performance important in an office?", "Noise can interfere with concentration, speech privacy, and occupant satisfaction."),
        ("What does sound transmission control help achieve?", "Less noise transfer between rooms or spaces."),
        ("Why are walk-off mats installed at main entrances?", "They reduce dirt, moisture, and pollutants carried into the building."),
        ("What is a green cleaning policy?", "A plan to use cleaning products and practices with lower health and environmental impacts."),
        ("Why should cleaning chemical storage be ventilated?", "Ventilation helps limit buildup of fumes from stored products."),
        ("What is occupant comfort feedback used for?", "It identifies indoor environmental problems that may need correction."),
        ("Why can a high-performance HVAC filter improve indoor air quality?", "It removes more particles from supply air before occupants breathe it."),
        ("What does minimum indoor air quality performance establish?", "A baseline level of ventilation intended to support healthy indoor conditions."),
        ("Why is outdoor air ventilation necessary?", "It dilutes indoor pollutants and supplies fresh air to occupants."),
        ("What is the benefit of monitoring carbon dioxide in densely occupied spaces?", "It can indicate whether ventilation is keeping pace with occupancy."),
        ("Why are smoking restrictions relevant to indoor environmental quality?", "Environmental tobacco smoke exposes occupants to harmful pollutants."),
        ("What is an integrated pest management approach indoors?", "Preventing pests through sanitation and targeted low-toxicity controls."),
        ("Why are durable materials considered sustainable?", "Longer service life can reduce replacement, waste, and resource use."),
        ("What is a product's service life?", "The period it performs its intended function before replacement is needed."),
        ("Why can salvaged materials support LEED goals?", "They reuse existing resources and can reduce waste sent to landfill."),
        ("What does a construction waste diversion rate measure?", "The share of construction debris kept out of landfill or incineration through recovery."),
        ("Why is separating construction waste on site helpful?", "Separated materials are easier to recycle or reuse than mixed debris."),
        ("What is a materials inventory used for in a renovation?", "It identifies existing products that may be retained, reused, or responsibly removed."),
        ("Why should adhesives and sealants be low emitting?", "They can release indoor pollutants after installation."),
        ("What is the purpose of a daylight simulation?", "It predicts daylight availability and potential glare before construction."),
        ("Why are individual lighting controls useful?", "They let occupants adjust light levels for tasks and comfort."),
        ("What is task lighting?", "Localized lighting provided where a specific activity is performed."),
        ("What is an environmental quality concern with moisture intrusion?", "Moisture can support mold growth and damage building materials."),
        ("Why is a building flush-out scheduled after finishes are installed?", "Many finish materials emit pollutants most strongly soon after installation."),
        ("What is the benefit of an indoor air quality assessment after construction?", "It can verify that key contaminants are at acceptable levels before occupancy."),
        ("Why should furniture be included in an indoor air quality plan?", "Furniture and furnishings can emit VOCs and other indoor pollutants."),
        ("What does material transparency enable?", "Informed selection based on a product's ingredients and environmental attributes."),
        ("Why do LEED projects consider both material and human-health impacts?", "A material can affect ecosystems during its life cycle and occupants indoors."),
        ("What is the purpose of a construction indoor air quality plan?", "Protect ducts, manage pollutants, and keep the building clean during construction."),
        ("Why should outdoor air intakes be protected during construction?", "They can otherwise draw dust and contaminants into HVAC equipment and occupied areas."),
        ("What is the central goal of Materials and Indoor Environmental Quality strategies?", "Reduce life-cycle material impacts while supporting healthier, more comfortable interiors."),
    ],
}

def make_question(topic, index, pair, answers):
    prompt, correct = pair
    alternatives = [answer for answer in answers if answer != correct]
    # Rotation preserves four substantive, topic-relevant choices without predictable answer position.
    wrongs = [alternatives[(index * 7 + step * 13) % len(alternatives)] for step in range(3)]
    ordered = wrongs[:]
    correct_index = index % 4
    ordered.insert(correct_index, correct)
    ids = "abcd"
    correct_id = ids[correct_index]
    return {
        "topicId": topic,
        "prompt": prompt,
        "options": [{"id": option_id, "text": text} for option_id, text in zip(ids, ordered)],
        "correctOptionId": correct_id,
        "explanation": f"{correct} This is the LEED Green Associate concept tested by the question.",
        "distractorExplanations": {
            option_id: "This is a valid sustainability concept, but it addresses a different requirement than the one asked."
            for option_id in ids if option_id != correct_id
        },
        "difficulty": ("easy", "medium", "hard")[index % 3],
    }

def main():
    all_questions = []
    output_dir = ROOT / "scripts/local-banks"
    output_dir.mkdir(parents=True, exist_ok=True)
    for topic, pairs in TOPICS.items():
        if len(pairs) != 50:
            raise ValueError(f"{topic}: expected 50 questions, found {len(pairs)}")
        answers = [answer for _, answer in pairs]
        questions = [make_question(topic, index, pair, answers) for index, pair in enumerate(pairs)]
        filename = output_dir / f"leed-ga-{topic}-001-050.json"
        filename.write_text(json.dumps(questions, indent=2) + "\n")
        for index, question in enumerate(questions, 1):
            all_questions.append({
                "id": f"{SLUG}-{topic}-{index:03d}",
                "examSlug": SLUG,
                **question,
                "sourceNote": "Locally authored original LEED Green Associate readiness-check question.",
            })
    if len(all_questions) != 250:
        raise ValueError(f"expected 250 questions, found {len(all_questions)}")
    target = ROOT / f"src/data/mock-exams/{SLUG}.json"
    target.write_text(json.dumps(all_questions, indent=2) + "\n")

if __name__ == "__main__":
    main()
