#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "enrolled-agent-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "individuals", [
        ("For most individual taxpayers, which form is the primary U.S. individual income tax return?",
         {"a": "Form 1065", "b": "Form 1040", "c": "Form 1120", "d": "Form 990"},
         "b", "Individuals generally file Form 1040 (with schedules as needed).",
         {"a": "Partnership return.", "c": "C corporation.", "d": "Exempt organization."}, "easy"),
        ("Qualified dividends and long-term capital gains are often taxed at:",
         {"a": "Ordinary income rates only, always", "b": "Preferential capital gains rates (0%/15%/20% tiers, subject to rules)", "c": "A flat 37% regardless of income", "d": "Payroll tax rates only"},
         "b", "LTCG/qualified dividends use preferential rate schedules when requirements are met.",
         {"a": "Not always ordinary.", "c": "Not flat 37% for these.", "d": "FICA is separate."}, "medium"),
        ("The standard deduction:",
         {"a": "Is claimed instead of itemizing Schedule A deductions when it's larger/beneficial", "b": "Is the same as the personal exemption (pre-TCJA reinstatement myth)", "c": "Can never be used by married couples", "d": "Applies only to corporations"},
         "a", "Taxpayers take the greater of standard deduction or itemized deductions.",
         {"b": "Personal exemptions were suspended under TCJA for years.", "c": "MFJ has a standard deduction.", "d": "Individuals."}, "easy"),
        ("A taxpayer's filing status is generally determined by:",
         {"a": "Their employer's fiscal year only", "b": "Marital status and household situation as of year-end (with specific rules)", "c": "Whether they own municipal bonds", "d": "Their state only, never federal rules"},
         "b", "Filing status follows Code rules on marriage/dependents/household as of Dec 31 (with nuances).",
         {"a": "Irrelevant.", "c": "Investment choice.", "d": "Federal status is federal."}, "easy"),
        ("An above-the-line deduction (adjustment to income) example is often:",
         {"a": "Charitable gifts only via Schedule A always", "b": "Deductible IRA contribution or student loan interest (when eligible)", "c": "State income tax only on Schedule A", "d": "Home mortgage interest only on Schedule A"},
         "b", "Certain adjustments reduce AGI before itemizing/standard deduction.",
         {"a": "Charity is typically itemized (with limited above-the-line exceptions in some years).", "c": "Itemized.", "d": "Itemized."}, "medium"),
        ("The Child Tax Credit is primarily for:",
         {"a": "Qualifying children meeting age/relationship/support/residency tests (subject to phaseouts)", "b": "Any roommate over age 40", "c": "Only nonresident aliens with no SSN ever", "d": "C corporations exclusively"},
         "a", "CTC has specific qualifying child and identification requirements.",
         {"b": "Doesn't qualify.", "c": "Identification/SSN rules apply; residency matters.", "d": "Individual credit."}, "easy"),
        ("Self-employment tax generally covers:",
         {"a": "Only federal income tax", "b": "Social Security and Medicare taxes on net earnings from self-employment", "c": "Only property taxes", "d": "Only AMT"},
         "b", "SE tax approximates employee+employer FICA on SE income.",
         {"a": "Income tax is separate.", "c": "Local/property.", "d": "AMT is different."}, "easy"),
        ("Basis of purchased stock is generally:",
         {"a": "Current market value every day", "b": "Cost (including commissions) adjusted for certain events", "c": "Always zero", "d": "The company's book value only"},
         "b", "Cost basis starts with purchase price plus acquisition costs, then adjusts.",
         {"a": "Mark-to-market not default for most investors.", "c": "False.", "d": "Not investor basis."}, "easy"),
        ("A capital loss on stocks for individuals can generally:",
         {"a": "Never offset capital gains", "b": "Offset capital gains and then up to $3,000 of ordinary income per year ($1,500 MFS), with carryforward", "c": "Offset unlimited ordinary income in the year realized", "d": "Only be used against municipal bond interest"},
         "b", "Net capital loss deduction against ordinary income is limited annually; excess carries forward.",
         {"a": "Can offset gains.", "c": "Limited to $3k/$1.5k.", "d": "False."}, "medium"),
        ("The kiddie tax rules can apply to:",
         {"a": "A child's unearned income above thresholds, taxed at parents' rates/under special rules", "b": "Only wages from a paper route", "c": "Corporate AMT exclusively", "d": "Estate tax portability"},
         "a", "Kiddie tax targets unearned income of certain children.",
         {"b": "Earned income treated differently.", "c": "Wrong regime.", "d": "Estate topic."}, "hard"),
        ("An eligible educator can deduct certain unreimbursed classroom expenses:",
         {"a": "As an above-the-line educator expense deduction up to the annual limit", "b": "Only as a business bad debt", "c": "Never, after TCJA for all teachers", "d": "Only on Form 1120S"},
         "a", "Educators get a limited above-the-line deduction for qualified expenses.",
         {"b": "Wrong category.", "c": "The educator expense deduction remains (itemized misc. 2% were limited).", "d": "S corp form."}, "medium"),
        ("Taxable Social Security benefits depend on:",
         {"a": "Provisional income / combined income thresholds", "b": "Only the taxpayer's age at retirement", "c": "Whether they filed Schedule C ever", "d": "A flat 100% inclusion always"},
         "a", "Up to 85% of SS may be taxable based on combined income formulas.",
         {"b": "Age alone doesn't set inclusion %.", "c": "Not the test.", "d": "Not always 100%."}, "medium"),
        ("A traditional IRA distribution before age 59½ is often subject to:",
         {"a": "No tax ever", "b": "Ordinary income tax plus 10% additional tax unless an exception applies", "c": "Only capital gains rates", "d": "Self-employment tax on the full distribution"},
         "b", "Early distributions are taxable and may face the 10% additional tax with listed exceptions.",
         {"a": "Generally taxable.", "c": "Ordinary rates typically.", "d": "Not SE tax on IRA distributions."}, "medium"),
        ("The American Opportunity Credit is generally available for:",
         {"a": "Qualified education expenses for an eligible student in the first four years of postsecondary education (subject to limits/phaseouts)", "b": "Graduate school only exclusively", "c": "Kindergarten tuition only", "d": "Gym memberships"},
         "a", "AOTC targets undergraduate years with specific expense and phaseout rules.",
         {"b": "Lifetime Learning is more flexible for grad; AOTC is undergrad-focused.", "c": "K-12 not AOTC.", "d": "Not qualified."}, "medium"),
        ("Estimated tax payments for individuals are generally due:",
         {"a": "Only on April 15 for the entire year always", "b": "In quarterly installments (Apr/Jun/Sep/Jan dates, with nuances)", "c": "Never if self-employed", "d": "Only when filing an extension"},
         "b", "Pay-as-you-go via withholding/estimates; quarterly due dates apply.",
         {"a": "Annualizing/quarterly needed for many.", "c": "SE often must estimate.", "d": "Extension is for filing, not payment."}, "easy"),
    ])

    qs += pack(E, "businesses", [
        ("A partnership generally files:",
         {"a": "Form 1040 only", "b": "Form 1065 and issues Schedule K-1s to partners", "c": "Form 1120-C exclusively", "d": "Form 706"},
         "b", "Partnerships are pass-through entities filing 1065 with K-1s.",
         {"a": "Partners report on 1040.", "c": "C corp.", "d": "Estate tax."}, "easy"),
        ("An S corporation's income generally:",
         {"a": "Is taxed at the entity at progressive corporate rates only", "b": "Passes through to shareholders (with basis/AAA and employment tax nuances for wages)", "c": "Is never reported to shareholders", "d": "Is exempt from all tax forever"},
         "b", "S corps are pass-throughs; reasonable compensation rules matter for shareholder-employees.",
         {"a": "C corp model.", "c": "K-1s report.", "d": "False."}, "medium"),
        ("A C corporation files:",
         {"a": "Form 1120 and pays entity-level tax", "b": "Only Form 1065", "c": "Only Schedule C", "d": "Form 1041 exclusively"},
         "a", "C corps are separate taxable entities on Form 1120.",
         {"b": "Partnership.", "c": "Sole prop on 1040.", "d": "Trust/estate income."}, "easy"),
        ("Section 179 expensing allows eligible taxpayers to:",
         {"a": "Expense the cost of qualifying property up to annual limits instead of depreciating over time", "b": "Ignore capitalization forever for inventory", "c": "Deduct personal living expenses", "d": "Exempt all meals at 100% always"},
         "a", "§179 permits immediate expensing of qualifying asset costs within limits/taxable income limits.",
         {"b": "UNICAP/inventory rules still apply.", "c": "Nondeductible personal.", "d": "Meals limited."}, "medium"),
        ("Qualified Business Income (QBI) deduction under §199A generally:",
         {"a": "Applies to specified service trades/businesses without limit for all incomes", "b": "May allow up to 20% deduction of QBI for eligible pass-throughs, subject to thresholds/limitations", "c": "Applies only to C corporations", "d": "Is a payroll tax credit"},
         "b", "199A provides a potential 20% QBI deduction with wage/UBIA and SSTB limitations.",
         {"a": "SSTB limitations apply above thresholds.", "c": "C corps don't get 199A.", "d": "Income tax deduction."}, "hard"),
        ("Depreciation of business equipment typically uses:",
         {"a": "MACRS methods/lives under the Code", "b": "Only fair market value each year as a deduction", "c": "Personal residence percentage always", "d": "Municipal bond amortization exclusively"},
         "a", "MACRS is the primary federal depreciation system for most tangible property.",
         {"b": "Not the method.", "c": "Home office has separate rules.", "d": "Bond premium/tax-exempt rules differ."}, "easy"),
        ("A sole proprietor reports business profit/loss on:",
         {"a": "Schedule C (Form 1040)", "b": "Form 1120S only", "c": "Form 1065 only", "d": "Form 990-T only"},
         "a", "Sole props use Schedule C; SE tax via Schedule SE.",
         {"b": "S corp.", "c": "Partnership.", "d": "Exempt org UBTI."}, "easy"),
        ("Meals for business are generally:",
         {"a": "100% deductible always after TCJA", "b": "Subject to 50% limitation in many cases (with exceptions)", "c": "Never deductible", "d": "Deductible only if lavish"},
         "b", "Business meals are often 50% deductible when ordinary/necessary and substantiated; rules have varied.",
         {"a": "Not always 100%.", "c": "Often partially deductible.", "d": "Lavish can be disallowed."}, "medium"),
        ("An LLC with one individual owner, by default for federal tax, is typically:",
         {"a": "A disregarded entity taxed as a sole proprietorship (unless corporate election)", "b": "Always a C corporation", "c": "Always a partnership", "d": "Tax-exempt automatically"},
         "a", "Single-member LLCs are disregarded by default; Form 8832/2553 elections can change classification.",
         {"b": "Only if elected/default corporate in rare cases.", "c": "Needs 2+ members for partnership default.", "d": "False."}, "medium"),
        ("Payroll tax deposits for employers are generally:",
         {"a": "Optional if the business is profitable", "b": "Required on IRS schedules (monthly/semiweekly, etc.) based on lookback", "c": "Paid only with the annual Form 1040", "d": "The same as estimated taxes for investors only"},
         "b", "Employment tax deposits follow deposit schedules; Forms 941/940 report.",
         {"a": "Not optional.", "c": "Employment taxes have their own returns.", "d": "Different regime."}, "medium"),
        ("At-risk rules and passive activity loss rules can:",
         {"a": "Limit current deductibility of losses", "b": "Increase the standard deduction", "c": "Convert C corps to S corps automatically", "d": "Eliminate estimated taxes"},
         "a", "§465/§469 can defer loss utilization until at-risk/passive tests are met.",
         {"b": "Unrelated.", "c": "Election needed.", "d": "False."}, "hard"),
        ("A corporation's charitable contribution deduction is generally limited to:",
         {"a": "Unlimited amounts", "b": "A percentage of taxable income (commonly 10% before special rules/elections)", "c": "Only $300", "d": "Zero if it has NOLs ever"},
         "b", "Corporate charity deductions face taxable income percentage limits (with carryovers).",
         {"a": "Limited.", "c": "Individual above-the-line concepts differ.", "d": "NOLs interact but don't auto-zero charity."}, "hard"),
        ("Cost of goods sold is most relevant for:",
         {"a": "Businesses with inventory (gross receipts minus COGS = gross profit)", "b": "W-2 employees with no side activity", "c": "Only municipal bond investors", "d": "Estate tax portability elections"},
         "a", "Inventory businesses compute COGS under accounting/tax inventory methods.",
         {"b": "No COGS typically.", "c": "Investments.", "d": "Estate."}, "easy"),
        ("Reasonable compensation for S corporation shareholder-employees is important because:",
         {"a": "Wages are subject to employment taxes while distributions generally are not", "b": "Distributions are always subject to SE tax", "c": "S corps cannot pay wages", "d": "It increases the corporate AMT credit only"},
         "a", "IRS expects reasonable wages before profit distributions to avoid employment tax avoidance.",
         {"b": "Distributions generally not SE tax.", "c": "They can/should pay wages when working.", "d": "Wrong focus."}, "hard"),
        ("Start-up and organizational costs are generally:",
         {"a": "Fully deductible in year one without limit always", "b": "Subject to capitalization with limited immediate expensing and amortization rules", "c": "Nondeductible forever", "d": "Treated as capital losses on Schedule D only"},
         "b", "§195/§248 provide limited expensing plus amortization of the rest.",
         {"a": "Limits apply.", "c": "Recoverable under rules.", "d": "Not Schedule D capital loss treatment."}, "medium"),
    ])

    qs += pack(E, "representation", [
        ("An Enrolled Agent is authorized to practice before the IRS by:",
         {"a": "State bar membership only", "b": "IRS enrollment (Special Enrollment Exam or qualifying IRS experience) and Circular 230 status", "c": "CPA license exclusively", "d": "Real estate broker license"},
         "b", "EAs are federally authorized tax practitioners under Circular 230.",
         {"a": "Attorneys have separate path.", "c": "CPAs also practice; EA is its own credential.", "d": "Irrelevant."}, "easy"),
        ("Form 2848 is used to:",
         {"a": "Elect S corporation status", "b": "Appoint a power of attorney to represent a taxpayer before the IRS", "c": "Report foreign gifts only", "d": "Claim the EITC exclusively"},
         "b", "2848 authorizes representation for specified tax matters/periods.",
         {"a": "2553.", "c": "3520 themes.", "d": "Credit on the return."}, "easy"),
        ("Form 8821 authorizes:",
         {"a": "Full advocacy representation like 2848", "b": "Tax information authorization (inspection/receipt of information) without full representation powers", "c": "A corporation's bylaws", "d": "Payroll deposit frequency changes only"},
         "b", "8821 is TIA—information access, not the same as POA representation.",
         {"a": "2848 is POA.", "c": "False.", "d": "Too narrow."}, "medium"),
        ("In an IRS examination, a representative should generally:",
         {"a": "Destroy unfavorable records", "b": "Respond timely, provide relevant records, and advocate within Circular 230 ethics", "c": "Ignore information document requests", "d": "Coach the client to fabricate receipts"},
         "b", "Competent, ethical representation includes timely responses and honest submissions.",
         {"a": "Obstruction.", "c": "Harms client/can escalate.", "d": "Fraud."}, "easy"),
        ("A collection due process (CDP) hearing request is typically filed on:",
         {"a": "Form 12153 (within the stated deadline after NFTL/levy notice)", "b": "Form 1040-X only", "c": "Form 2553", "d": "Form 3115 only"},
         "a", "CDP rights are exercised via Form 12153 within the 30-day period generally.",
         {"b": "Amended return.", "c": "S election.", "d": "Accounting method change."}, "hard"),
        ("An Offer in Compromise (OIC) is a request to:",
         {"a": "Change filing status after the fact without criteria", "b": "Settle a tax debt for less than the full amount based on doubt as to collectibility/liability or effective tax administration", "c": "Automatically abate all penalties forever", "d": "Elect mark-to-market trading"},
         "b", "OIC is a collection alternative under specific IRS standards.",
         {"a": "Not OIC.", "c": "Penalty relief is separate (FTA, reasonable cause).", "d": "§475 election."}, "medium"),
        ("Innocent spouse relief is claimed on:",
         {"a": "Form 8857", "b": "Form 1065", "c": "Form 1099-NEC", "d": "Form W-4 only"},
         "a", "Form 8857 requests innocent spouse / separation of liability / equitable relief.",
         {"b": "Partnership.", "c": "Info return.", "d": "Withholding."}, "medium"),
        ("A statutory notice of deficiency (90-day letter) generally allows the taxpayer to:",
         {"a": "Petition the U.S. Tax Court within 90 days (150 if addressed outside the U.S.)", "b": "Only pay immediately with no rights", "c": "File bankruptcy as the sole remedy", "d": "Ignore it safely forever"},
         "a", "The SNOD opens Tax Court jurisdiction if petitioned timely.",
         {"b": "Rights exist.", "c": "Not sole remedy.", "d": "Dangerous."}, "hard"),
        ("Power of attorney authority ends when:",
         {"a": "It is revoked, withdrawn, superseded, or the matter/period concludes as specified", "b": "Never, under any circumstances", "c": "The practitioner changes email providers", "d": "The client buys municipal bonds"},
         "a", "POAs can be revoked/withdrawn and are limited to specified matters/periods.",
         {"b": "False.", "c": "Irrelevant.", "d": "Irrelevant."}, "easy"),
        ("CAF (Centralized Authorization File) numbers identify:",
         {"a": "IRS-recognized representatives on authorizations", "b": "County assessor parcels only", "c": "EIN verification for employees only", "d": "PTIN for software vendors exclusively"},
         "a", "CAF tracks POA/TIA authorizations for practitioners.",
         {"b": "Property tax.", "c": "EIN is entity ID.", "d": "PTIN is preparer tax ID."}, "medium"),
        ("During Appeals, the goal is typically to:",
         {"a": "Litigate immediately in district court only", "b": "Resolve disputes fairly considering hazards of litigation without new enforcement by Appeals", "c": "Increase penalties automatically", "d": "Bypass all administrative remedies forever"},
         "b", "IRS Independent Office of Appeals seeks case resolution considering litigation hazards.",
         {"a": "Appeals is pre-litigation forum often.", "c": "Not the mission.", "d": "Exhaustion concepts vary."}, "medium"),
        ("A taxpayer interview with the IRS when represented:",
         {"a": "Must exclude the representative always", "b": "May proceed with the authorized representative present/handling communications per the authorization", "c": "Requires a Form 706 filing", "d": "Is illegal under Circular 230"},
         "b", "Authorized representatives may handle IRS contacts within the POA scope.",
         {"a": "Opposite.", "c": "Estate tax return.", "d": "False."}, "easy"),
        ("Penalty abatement for first-time abate (FTA) generally requires:",
         {"a": "Meeting IRS criteria (compliance history, specific penalties, etc.)", "b": "Owning a home", "c": "Being an EA", "d": "Filing only on paper"},
         "a", "FTA is an administrative waiver with eligibility conditions.",
         {"b": "Irrelevant.", "c": "Taxpayer eligibility, not practitioner credential.", "d": "Filing method not the test."}, "medium"),
        ("A closing agreement (Form 866/906 contexts) is used to:",
         {"a": "Finally determine tax liability for specific matters when appropriate", "b": "Elect S status", "c": "Report tip income only", "d": "Request a PTIN"},
         "a", "Closing agreements finally resolve specified tax matters when executed.",
         {"b": "2553.", "c": "Tip reporting forms differ.", "d": "PTIN application."}, "hard"),
        ("Third-party authorization via checkbox on the return (designee):",
         {"a": "Gives full POA for all years automatically", "b": "Allows IRS to discuss return processing issues with a designated person for a limited purpose/period", "c": "Replaces Form 2848 for audits of all prior years", "d": "Authorizes bank account seizures"},
         "b", "The third-party designee is narrow (processing), not a general POA.",
         {"a": "Too broad.", "c": "2848 still needed for representation.", "d": "False."}, "medium"),
    ])

    qs += pack(E, "practices", [
        ("Circular 230 governs:",
         {"a": "Only state sales tax audits", "b": "Practice before the IRS by attorneys, CPAs, EAs, and others eligible to practice", "c": "SEC broker advertising only", "d": "FINRA arbitration exclusively"},
         "b", "Circular 230 is the Treasury regulation for IRS practice standards.",
         {"a": "State tax separate.", "c": "Securities.", "d": "Securities disputes."}, "easy"),
        ("A PTIN is required for:",
         {"a": "Anyone who prepares or assists in preparing all or substantially all of a federal tax return for compensation", "b": "Only EAs", "c": "Only taxpayers filing their own returns", "d": "Only corporate officers"},
         "a", "Paid preparers generally must have a PTIN.",
         {"b": "All paid preparers (with rules).", "c": "Self-preparers don't need PTIN.", "d": "Too narrow."}, "easy"),
        ("Under Circular 230, a practitioner who knows of a client's omission on a prior return should:",
         {"a": "Advise the client promptly of the omission and its consequences", "b": "Hide it from the client", "c": "Always resign without saying anything", "d": "Amend without client knowledge"},
         "a", "Duty to inform the client; cannot amend without authorization.",
         {"b": "Violates standards.", "c": "Must advise.", "d": "Unauthorized."}, "medium"),
        ("Contingent fees for preparing an original return are generally:",
         {"a": "Broadly permitted in all cases under Circular 230", "b": "Restricted; contingent fees are limited to specific circumstances (e.g., certain IRS examinations/challenges)", "c": "Required by the IRS", "d": "The same as a refund anticipation loan"},
         "b", "Circular 230 limits contingent fees for return preparation.",
         {"a": "Not broadly permitted.", "c": "False.", "d": "Different product."}, "hard"),
        ("Due diligence for EITC/CTC/AOTC (paid preparers) includes:",
         {"a": "Completing Form 8867 and applying knowledge/inquiry standards", "b": "Skipping questions if the refund is large", "c": "Accepting any document without review", "d": "Avoiding PTIN use"},
         "a", "Paid preparer due diligence rules require Form 8867 and specific checklists/inquiries.",
         {"b": "Opposite of diligence.", "c": "Must make reasonable inquiries.", "d": "PTIN required."}, "medium"),
        ("Client confidentiality for tax practitioners means:",
         {"a": "Never disclose client tax information except as authorized or legally required", "b": "Posting returns on social media for marketing", "c": "Selling client lists with SSNs freely", "d": "Discussing client details at a conference without consent"},
         "a", "IRC §7216/privacy rules and ethics restrict disclosure of tax return information.",
         {"b": "Prohibited.", "c": "Illegal/unethical.", "d": "Needs consent/exception."}, "easy"),
        ("A practitioner's written tax advice should:",
         {"a": "Be based on reasonable factual/legal assumptions and not be misleading", "b": "Guarantee audit-proof results always", "c": "Ignore contrary authorities knowingly", "d": "Be unsigned to avoid responsibility"},
         "a", "Circular 230 competence/diligence standards apply to advice.",
         {"b": "Cannot guarantee.", "c": "Must not mislead.", "d": "Accountability remains."}, "medium"),
        ("Records submitted to the IRS should be:",
         {"a": "Altered to improve the facts", "b": "Accurate copies/originals as appropriate; do not submit known false documents", "c": "Destroyed after mailing", "d": "Backdated routinely"},
         "b", "Submitting false documents is criminal/ethical violation.",
         {"a": "Fraud.", "c": "Keep copies.", "d": "Falsification."}, "easy"),
        ("Advertising as an Enrolled Agent must not:",
         {"a": "State the EA credential truthfully", "b": "Claim IRS employee status or guaranteed results deceptively", "c": "List contact information", "d": "Mention enrollment"},
         "b", "Practitioners cannot falsely imply government employment or guarantee outcomes.",
         {"a": "Allowed if true.", "c": "Allowed.", "d": "Allowed if accurate."}, "easy"),
        ("Conflict of interest under Circular 230 generally requires:",
         {"a": "Ignoring the conflict if fees are high", "b": "Informed consent in writing when representation of conflicting interests is otherwise permitted, or declining representation", "c": "Automatic dual representation without notice", "d": "Referral kickbacks"},
         "b", "Conflicts need waiver/consent meeting Circular 230 conditions or withdrawal.",
         {"a": "Fees don't cure.", "c": "Consent required.", "d": "Unrelated/illegal in tax prep contexts often."}, "medium"),
        ("Electronic filing fraud schemes should be reported/prevented by preparers through:",
         {"a": "Strong ID verification, secure systems, and not participating in refund fraud", "b": "Sharing EFPINs on forums", "c": "Allowing clients to use the preparer's credentials", "d": "Disabling multi-factor authentication always"},
         "a", "Security and due diligence combat stolen-identity refund fraud.",
         {"b": "Security failure.", "c": "Credential sharing is improper.", "d": "Weakens security."}, "medium"),
        ("A tax preparer penalty under §6694 can apply for:",
         {"a": "Understatements due to unreasonable positions / willful/reckless conduct", "b": "Filing on time with correct positions", "c": "Using tax software", "d": "Obtaining a PTIN"},
         "a", "§6694 penalizes preparers for unreasonable positions and reckless/willful understatements.",
         {"b": "Compliance.", "c": "Software ok.", "d": "Required."}, "hard"),
        ("Best practice for engagement letters includes:",
         {"a": "Defining scope, responsibilities, deadlines, and fee arrangements in writing", "b": "Avoiding any written terms", "c": "Promising specific refund amounts", "d": "Authorizing the preparer to sign for the taxpayer without Form 8879/alternative e-file auth"},
         "a", "Engagement letters reduce misunderstandings and document scope.",
         {"b": "Risky.", "c": "Improper guarantee.", "d": "E-file auth still required."}, "easy"),
        ("Return of client records upon request:",
         {"a": "Practitioners must return client-provided records; may retain copies of their work product subject to rules/fee disputes nuances", "b": "May keep original client records permanently as ransom", "c": "Never need to return anything", "d": "Only applies to attorneys"},
         "a", "Circular 230 addresses return of client records; holding originals for unpaid fees is restricted.",
         {"b": "Improper.", "c": "False.", "d": "Applies to practitioners broadly."}, "medium"),
        ("Competence under Circular 230 means a practitioner should:",
         {"a": "Take only matters they can handle competently or become competent through study/consultation", "b": "Accept any matter regardless of knowledge", "c": "Rely solely on the client's legal conclusions without evaluation", "d": "Avoid continuing education forever"},
         "a", "Competence requires knowledge/skill or acquiring it appropriately.",
         {"b": "Violates competence.", "c": "Must exercise diligence.", "d": "CE required for EAs."}, "easy"),
    ])

    return qs


if __name__ == "__main__":
    write_bank(E, build())
