#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "mortgage-loan-originator-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "origination", [
        ("A mortgage loan originator (MLO) primarily:",
         {"a": "Appraises property value independently for the lender only", "b": "Takes a residential mortgage application and/or offers/negotiates terms for compensation", "c": "Issues title insurance policies", "d": "Sets the Federal Reserve discount rate"},
         "b", "SAFE Act definitions center on taking applications and offering/negotiating terms for compensation.",
         {"a": "Appraiser role.", "c": "Title agent/underwriter role.", "d": "Monetary policy."}, "easy"),
        ("A borrower's debt-to-income (DTI) ratio generally compares:",
         {"a": "Home equity to purchase price only", "b": "Monthly debt obligations to gross monthly income", "c": "Credit score to LTV only", "d": "Property taxes to HOA fees only"},
         "b", "DTI = monthly debts ÷ gross monthly income (front-end/back-end variants exist).",
         {"a": "LTV/equity concepts.", "c": "Different metrics.", "d": "Expense components, not DTI."}, "easy"),
        ("Loan-to-value (LTV) is calculated as:",
         {"a": "Loan amount ÷ lesser of purchase price or appraised value (typical purchase)", "b": "Income ÷ debts", "c": "Credit score ÷ 850", "d": "Closing costs ÷ prepaid interest only"},
         "a", "LTV measures loan size relative to property value.",
         {"b": "That is DTI-related.", "c": "Nonsense.", "d": "Closing cost items."}, "easy"),
        ("PITI typically includes:",
         {"a": "Principal, interest, taxes, and insurance", "b": "Only points and title fees", "c": "Only HOA and utilities", "d": "Only PMI without taxes"},
         "a", "PITI is the standard housing payment stack used in underwriting.",
         {"b": "Closing costs.", "c": "Not the PITI acronym.", "d": "Incomplete."}, "easy"),
        ("A purchase contract contingency for financing generally allows a buyer to:",
         {"a": "Skip the appraisal forever", "b": "Exit or renegotiate if they cannot obtain specified financing", "c": "Force the seller to pay all closing costs by law", "d": "Avoid disclosing income to the lender"},
         "b", "Financing contingencies protect buyers if loan approval fails under stated terms.",
         {"a": "Appraisal is separate.", "c": "Not automatic by law.", "d": "Income disclosure is required for underwriting."}, "medium"),
        ("An underwriter's primary job is to:",
         {"a": "Market the loan on TikTok", "b": "Evaluate credit, capacity, collateral, and compliance risk against guidelines", "c": "Set county property tax rates", "d": "Record the deed as county clerk"},
         "b", "Underwriting assesses whether the loan meets program and risk standards.",
         {"a": "Sales/marketing.", "c": "Tax authority.", "d": "Recording office."}, "easy"),
        ("A rate lock typically:",
         {"a": "Guarantees closing will occur", "b": "Protects the quoted interest rate for a stated period if conditions are met", "c": "Eliminates the need for an appraisal", "d": "Is illegal under RESPA"},
         "b", "Locks hold a rate/points for a window; closing is not guaranteed by the lock alone.",
         {"a": "Lock ≠ closing guarantee.", "c": "Appraisal still needed typically.", "d": "Locks are common/legal."}, "medium"),
        ("Front-end DTI focuses on:",
         {"a": "Housing payment (often PITI) relative to income", "b": "All revolving debt only excluding housing", "c": "Only student loans", "d": "Only investment property cash flow"},
         "a", "Front-end (housing) ratio compares housing costs to income.",
         {"b": "That's closer to other debt components of back-end.", "c": "Too narrow.", "d": "Not the definition."}, "medium"),
        ("A conventional loan that is not government-insured/guaranteed is typically sold to:",
         {"a": "Only the IRS", "b": "GSEs like Fannie Mae/Freddie Mac if it meets conforming guidelines (among other investors)", "c": "Only local pawn shops", "d": "The FDIC as insurer of the note"},
         "b", "Conforming conventional loans often sell to GSEs when within limits/guidelines.",
         {"a": "False.", "c": "False.", "d": "FDIC insures deposits, not mortgages as GSE buyer."}, "medium"),
        ("Pre-approval vs pre-qualification: pre-approval generally means:",
         {"a": "A casual verbal estimate with no credit check ever", "b": "A more verified underwriting review of credit/income/assets (still not a final commitment)", "c": "Final clear-to-close", "d": "An appraisal waiver forever"},
         "b", "Pre-approval is stronger than pre-qual but is not the same as a final loan commitment.",
         {"a": "Sounds like soft pre-qual.", "c": "CTC is later.", "d": "Appraisal decisions are separate."}, "medium"),
        ("Occupancy type 'primary residence' generally means the borrower:",
         {"a": "Will never live in the property", "b": "Intends to occupy the property as their main home", "c": "Must rent it on day one", "d": "Can only buy commercial warehouses"},
         "b", "Primary occupancy is the borrower's principal residence.",
         {"a": "Investment/second home.", "c": "Would conflict with primary intent.", "d": "Residential mortgage context."}, "easy"),
        ("Gift funds for a down payment typically require:",
         {"a": "No documentation", "b": "A gift letter and evidence of transfer/sourcing per program rules", "c": "That gifts come only from the listing agent", "d": "That gifts be repaid monthly like a loan without disclosure"},
         "b", "Agencies require gift documentation and paper trail; repayment may recharacterize as a loan.",
         {"a": "Docs required.", "c": "Donor rules are specific; agents are conflicted.", "d": "If repaid, it's debt."}, "medium"),
        ("A jumbo loan is generally:",
         {"a": "Any FHA loan", "b": "A loan amount above conforming loan limits", "c": "A loan with zero interest", "d": "A HELOC that never has a credit limit"},
         "b", "Jumbo = above conforming limits (investor overlays apply).",
         {"a": "FHA has its own limits/insurance.", "c": "False.", "d": "HELOC is different product."}, "easy"),
        ("Credit inquiries for mortgage shopping within a short window are often treated as:",
         {"a": "Always each a separate permanent score hit forever", "b": "A single inquiry for scoring purposes under common scoring model rules", "c": "Illegal under ECOA", "d": "Proof of fraud"},
         "b", "Rate-shopping windows commonly collapse multiple mortgage inquiries.",
         {"a": "Overstates the hit.", "c": "Shopping isn't illegal.", "d": "Not proof of fraud."}, "medium"),
        ("Clear-to-close means:",
         {"a": "The borrower can skip signing", "b": "Underwriting conditions are satisfied and the loan may proceed to closing", "c": "The property tax bill is waived forever", "d": "The MLO becomes the title insurer"},
         "b", "CTC indicates conditions are met for closing (final walk-through/funding still matter).",
         {"a": "Signing still required.", "c": "False.", "d": "False."}, "easy"),
    ])

    qs += pack(E, "products", [
        ("An FHA loan is distinctive because it is:",
         {"a": "Uninsured and only for investment condos", "b": "Insured by the Federal Housing Administration, often allowing lower down payments", "c": "Only available to veterans", "d": "Always a 15-year interest-only product"},
         "b", "FHA provides mortgage insurance enabling flexible credit/down-payment profiles.",
         {"a": "FHA is insured.", "c": "VA is for eligible veterans.", "d": "Not the definition."}, "easy"),
        ("VA loans are generally available to:",
         {"a": "Any first-time buyer worldwide", "b": "Eligible veterans, service members, and certain surviving spouses", "c": "Only cash investors", "d": "Only borrowers with 50% down"},
         "b", "VA guaranty programs serve eligible military-related borrowers.",
         {"a": "Eligibility required.", "c": "False.", "d": "Often $0 down if entitlement allows."}, "easy"),
        ("Private mortgage insurance (PMI) on conventional loans is typically required when:",
         {"a": "LTV is above roughly 80%", "b": "The loan is a HELOC", "c": "The borrower pays cash", "d": "The property is commercial only"},
         "a", "Conventional PMI commonly applies when equity is below 20%.",
         {"b": "Different product.", "c": "No loan.", "d": "Residential conventional context."}, "easy"),
        ("A fixed-rate mortgage keeps:",
         {"a": "The interest rate constant for the life of the loan (payment may still change with escrow)", "b": "The escrow taxes forever at zero", "c": "No amortization schedule", "d": "A rate that resets monthly by statute"},
         "a", "Fixed-rate locks the note rate; PITI can change if taxes/insurance change.",
         {"b": "Escrow can change.", "c": "Amortizing loans have schedules.", "d": "That's ARM-like."}, "easy"),
        ("An adjustable-rate mortgage (ARM) interest rate:",
         {"a": "Never changes", "b": "Can adjust based on an index plus margin after an initial fixed period", "c": "Is set only by the county assessor", "d": "Must be interest-only forever"},
         "b", "ARMs adjust per note terms: index + margin, caps, etc.",
         {"a": "Fixed loans.", "c": "False.", "d": "Not required."}, "easy"),
        ("A USDA rural development loan generally targets:",
         {"a": "Luxury urban condos only", "b": "Eligible borrowers in qualifying rural/suburban areas meeting income limits", "c": "Only commercial farms with no residence", "d": "Cash-out unlimited investor flips"},
         "b", "USDA SFH programs have geography and income eligibility rules.",
         {"a": "Opposite focus.", "c": "Different USDA farm programs exist; SFH is residential.", "d": "Not the product focus."}, "medium"),
        ("Interest-only loans during the IO period typically:",
         {"a": "Amortize principal aggressively", "b": "Require payment of interest only, so principal may not decline", "c": "Eliminate default risk", "d": "Are identical to biweekly biweekly principal prepay mandates"},
         "b", "IO payments do not reduce principal unless extra principal is paid.",
         {"a": "Opposite.", "c": "Risk remains/can rise.", "d": "Different feature."}, "medium"),
        ("A HELOC is best described as:",
         {"a": "A closed-end purchase money first mortgage only", "b": "A revolving line of credit secured by home equity", "c": "An unsecured credit card", "d": "FHA upfront MIP exclusively"},
         "b", "HELOCs are revolving junior (or sometimes first) liens against equity.",
         {"a": "That's a closed-end mortgage.", "c": "Unsecured.", "d": "FHA fee."}, "easy"),
        ("Discount points are typically paid to:",
         {"a": "Reduce the interest rate", "b": "Increase the rate", "c": "Pay the appraiser's travel only", "d": "Cancel homeowners insurance"},
         "a", "Points are prepaid interest/fees used to buy down the rate.",
         {"b": "Opposite.", "c": "Appraisal fee is separate.", "d": "False."}, "easy"),
        ("A balloon mortgage features:",
         {"a": "Fully amortizing payments with no large final payment", "b": "A large principal balance due at a stated maturity before full amortization", "c": "No interest ever", "d": "Only monthly interest that never ends by contract"},
         "b", "Balloons leave a lump-sum balance at term.",
         {"a": "Fully amortizing.", "c": "False.", "d": "Not the balloon definition."}, "medium"),
        ("Loan-level price adjustments (LLPAs) primarily affect:",
         {"a": "County recording fees only", "b": "Pricing/cost based on risk factors like FICO, LTV, product type", "c": "Property tax millage rates", "d": "HOA bylaws"},
         "b", "LLPAs adjust secondary-market pricing for risk attributes.",
         {"a": "Different fees.", "c": "Taxes.", "d": "HOA."}, "hard"),
        ("A construction-to-permanent loan is designed to:",
         {"a": "Finance building then convert to a permanent mortgage", "b": "Only refinance credit cards", "c": "Fund stock purchases", "d": "Replace title insurance permanently"},
         "a", "Construction financing transitions into a long-term mortgage.",
         {"b": "Unsecured refinance.", "c": "Securities.", "d": "Title is separate."}, "medium"),
        ("Negative amortization occurs when:",
         {"a": "Payments are insufficient to cover accruing interest, so balance rises", "b": "The borrower prepays principal aggressively", "c": "The loan is paid off early", "d": "Escrow is waived"},
         "a", "If interest exceeds payment, unpaid interest is added to principal.",
         {"b": "Reduces balance.", "c": "Payoff.", "d": "Unrelated."}, "medium"),
        ("QM (Qualified Mortgage) ability-to-repay rules are most associated with:",
         {"a": "Ignoring income documentation", "b": "Underwriting standards designed to assess ability to repay under ATR/QM framework", "c": "Only commercial CMBS", "d": "Setting the Fed funds rate"},
         "b", "ATR/QM is a consumer-protection underwriting framework for closed-end consumer mortgages.",
         {"a": "Opposite intent.", "c": "Consumer mortgage focus.", "d": "Monetary policy."}, "hard"),
        ("Mortgage credit certificates (where available) generally provide:",
         {"a": "A federal tax credit related to mortgage interest for eligible borrowers", "b": "Free homeowners insurance", "c": "Automatic PMI cancellation day one", "d": "VA funding fee waivers for all civilians"},
         "a", "MCCs can provide a tax credit on a portion of mortgage interest (program-specific).",
         {"b": "False.", "c": "False.", "d": "VA rules differ; MCC is separate."}, "hard"),
    ])

    qs += pack(E, "fed-law", [
        ("RESPA primarily addresses:",
         {"a": "Truthful advertising of APR only", "b": "Settlement costs, servicing disclosures, and prohibitions on kickbacks/unearned fees", "c": "Equal credit without regard to race only (that's ECOA/FHA fair lending)", "d": "Margin requirements for stocks"},
         "b", "RESPA (Reg X) covers settlement process and anti-kickback rules.",
         {"a": "Closer to TILA.", "c": "Fair lending statutes.", "d": "Securities."}, "medium"),
        ("TILA/Reg Z is most associated with:",
         {"a": "Kickback bans only", "b": "Truthful disclosure of credit terms/APR and certain advertising/ability-to-repay rules", "c": "Title insurance premiums set by HUD", "d": "Appraisal licensing only"},
         "b", "TILA focuses on cost-of-credit disclosures and related consumer protections.",
         {"a": "RESPA.", "c": "Not TILA's role.", "d": "Appraiser regulation separate."}, "medium"),
        ("TRID (Know Before You Owe) integrates:",
         {"a": "Loan Estimate and Closing Disclosure timing/content rules", "b": "Only HMDA reporting", "c": "Only BSA SARs", "d": "Only Flood insurance maps"},
         "a", "TRID combines TILA/RESPA disclosures into LE/CD.",
         {"b": "HMDA is different.", "c": "AML.", "d": "Flood."}, "easy"),
        ("ECOA (Reg B) prohibits discrimination based on:",
         {"a": "Credit score only", "b": "Protected characteristics such as race, color, religion, national origin, sex, marital status, age (with limits), and receipt of public assistance", "c": "LTV only", "d": "Whether the borrower uses a Realtor"},
         "b", "ECOA bars credit discrimination on listed prohibited bases.",
         {"a": "Score can be a legitimate factor.", "c": "Risk factor, not ECOA basis.", "d": "Not a protected basis."}, "easy"),
        ("The Fair Housing Act prohibits discrimination in housing-related transactions based on:",
         {"a": "Credit utilization only", "b": "Race, color, religion, sex, handicap, familial status, national origin (among others as applied)", "c": "Whether PMI is paid", "d": "Loan amount above jumbo"},
         "b", "FHA fair housing protected classes govern housing discrimination.",
         {"a": "Credit factor.", "c": "Product feature.", "d": "Not a protected class."}, "easy"),
        ("HMDA requires covered institutions to:",
         {"a": "Report specified mortgage application/loan data", "b": "Set interest rates nationally", "c": "Appraise every property for free", "d": "Provide free legal counsel at closing"},
         "a", "HMDA (Reg C) is a data reporting statute for fair lending analysis/transparency.",
         {"b": "False.", "c": "False.", "d": "False."}, "medium"),
        ("The SAFE Act requires MLOs to:",
         {"a": "Avoid all licensing", "b": "Be licensed/registered via NMLS as applicable and meet education/testing standards", "c": "Work only for GSEs as employees", "d": "Never take continuing education"},
         "b", "SAFE Act created nationwide licensing/registration standards through NMLS.",
         {"a": "Opposite.", "c": "False.", "d": "CE is required."}, "easy"),
        ("GLBA privacy rules require financial institutions to:",
         {"a": "Share all NPI freely without notice", "b": "Provide privacy notices and limit sharing of nonpublic personal information per the rule", "c": "Publish Social Security numbers online", "d": "Ignore opt-out rights"},
         "b", "GLBA Privacy Rule governs notice and NPI sharing.",
         {"a": "Violates GLBA.", "c": "Illegal/unsafe.", "d": "Opt-outs matter where applicable."}, "medium"),
        ("The Red Flags Rule (identity theft) requires many creditors to:",
         {"a": "Have a written identity theft prevention program", "b": "Charge higher rates to all seniors", "c": "Skip CIP entirely", "d": "Destroy loan files weekly"},
         "a", "Red Flags programs detect/respond to identity theft red flags.",
         {"b": "ECOA issue.", "c": "CIP is BSA/AML related and still needed.", "d": "Retention rules exist."}, "medium"),
        ("A Loan Estimate must generally be provided:",
         {"a": "Within 3 business days of application (TRID timing)", "b": "Only after closing", "c": "Never if the loan is conventional", "d": "Only if APR exceeds 25%"},
         "a", "TRID requires LE within 3 business days of application.",
         {"b": "Too late.", "c": "Applies broadly to covered closed-end consumer mortgages.", "d": "False."}, "easy"),
        ("A Closing Disclosure must generally be received by the consumer:",
         {"a": "At least 3 business days before consummation (with limited exceptions)", "b": "One year after funding", "c": "Only if they ask verbally", "d": "Never for purchase loans"},
         "a", "CD timing is a core TRID consumer protection.",
         {"b": "False.", "c": "Required delivery.", "d": "Applies to covered transactions."}, "easy"),
        ("Steering a borrower to a loan that pays the MLO more while harming the borrower can violate:",
         {"a": "Best practices only with no legal risk", "b": "TILA anti-steering/LO compensation rules and fair dealing standards", "c": "Only the Uniform Commercial Code Article 9 exclusively", "d": "Only flood zone mapping"},
         "b", "LO compensation/anti-steering rules target harmful steering for compensation.",
         {"a": "Legal risk exists.", "c": "Wrong body of law focus.", "d": "Unrelated."}, "hard"),
        ("Appraisals for many higher-priced mortgage loans require:",
         {"a": "No appraisal ever", "b": "Compliance with appraisal independence and HPML appraisal rules where applicable", "c": "That the MLO write the appraisal value", "d": "Verbal values only"},
         "b", "HPML and AIR rules add appraisal/independence protections.",
         {"a": "False.", "c": "Conflicts with independence.", "d": "Written appraisals required when mandated."}, "hard"),
        ("Flood insurance is generally required when:",
         {"a": "The property is in a Special Flood Hazard Area and the loan is secured by that improved real estate from a regulated lender", "b": "The borrower has excellent credit", "c": "The loan is a HELOC under $100 only", "d": "The property is never near water by borrower statement alone"},
         "a", "Mandatory flood insurance applies to SFHA properties with designated loans.",
         {"b": "Credit irrelevant.", "c": "Wrong threshold logic.", "d": "Maps/determinations control."}, "medium"),
        ("The Bank Secrecy Act/AML framework for mortgage lenders typically includes:",
         {"a": "Ignoring suspicious activity", "b": "Customer identification, monitoring, and SAR filing where required", "c": "Publishing SARs to social media", "d": "Banning all cash down payments forever"},
         "b", "BSA/AML programs include CIP, monitoring, and SARs.",
         {"a": "Violates AML.", "c": "SARs are confidential.", "d": "Cash can be sourced; not a blanket ban."}, "medium"),
    ])

    qs += pack(E, "ethics", [
        ("Charging a borrower a fee for which no service is performed is:",
         {"a": "A RESPA-permitted courtesy", "b": "An unearned fee / potential RESPA Section 8 violation", "c": "Required by TILA", "d": "Always allowed if disclosed in tiny print"},
         "b", "RESPA prohibits unearned fees and kickbacks.",
         {"a": "Not permitted.", "c": "False.", "d": "Disclosure doesn't legalize kickbacks."}, "easy"),
        ("A kickback for referring settlement business is:",
         {"a": "Encouraged under RESPA", "b": "Generally prohibited under RESPA Section 8", "c": "Required for affiliated business arrangements", "d": "Only illegal if over $10"},
         "b", "Section 8 bans referral fees/kickbacks for settlement services.",
         {"a": "Opposite.", "c": "AfBAs have disclosure/safe harbor rules, not kickback requirements.", "d": "No such de minimis excuse as stated."}, "easy"),
        ("Misrepresenting a loan as having 'no closing costs' when costs are rolled into the rate/price without clarity can be:",
         {"a": "Best practice", "b": "Deceptive advertising / UDAAP risk", "c": "Required by HMDA", "d": "A form of flood determination"},
         "b", "Misleading cost claims create UDAAP and advertising law risk.",
         {"a": "Not best practice.", "c": "HMDA is reporting.", "d": "Unrelated."}, "medium"),
        ("Dual compensation where a loan originator receives both borrower-paid and lender-paid compensation on the same loan is generally:",
         {"a": "Always required", "b": "Restricted/prohibited under LO compensation rules", "c": "The definition of a discount point", "d": "A TRID tolerance cure"},
         "b", "LO Comp Rule restricts dual compensation structures.",
         {"a": "False.", "c": "Points are different.", "d": "Tolerances are disclosure cures."}, "hard"),
        ("Appraiser independence rules generally prohibit:",
         {"a": "Ordering appraisals", "b": "Coercing or influencing appraisers to hit a target value", "c": "Providing the purchase contract to the appraiser when allowed", "d": "Using AMC platforms"},
         "b", "AIR/TILA independence bans coercion for predetermined values.",
         {"a": "Ordering is normal.", "c": "Often permitted/required info.", "d": "AMCs are common."}, "easy"),
        ("Ethics require an MLO who discovers a material misstatement on an application to:",
         {"a": "Ignore it if the loan will close", "b": "Address it; do not submit known false information", "c": "Increase the loan amount quietly", "d": "Delete the credit report"},
         "b", "Submitting false information is fraud/ethics violation.",
         {"a": "Complicity.", "c": "Worsens issue.", "d": "Improper."}, "easy"),
        ("Discrimination against a borrower because of familial status violates:",
         {"a": "Only the Uniform Standards of Professional Appraisal Practice exclusively", "b": "Fair Housing / fair lending laws", "c": "Only the SAFE Act education hours", "d": "Only GLBA notices"},
         "b", "Familial status is a Fair Housing protected class.",
         {"a": "USPAP is appraisal standards.", "c": "Licensing education.", "d": "Privacy."}, "easy"),
        ("An affiliated business arrangement (AfBA) disclosure is needed when:",
         {"a": "A referral is made to an affiliate settlement provider", "b": "The borrower pays cash for a car", "c": "The MLO changes NMLS password", "d": "The Fed raises rates"},
         "a", "AfBA disclosures inform consumers of affiliate relationships on referrals.",
         {"b": "Unrelated.", "c": "Security hygiene.", "d": "Macro."}, "medium"),
        ("Bait-and-switch advertising of a teaser rate not actually available is:",
         {"a": "Acceptable if the website looks premium", "b": "Unethical and potentially illegal deceptive advertising", "c": "Required by RESPA Section 8", "d": "A form of best execution"},
         "b", "Advertising must be truthful and available as represented.",
         {"a": "Looks don't legalize deceit.", "c": "Section 8 is kickbacks.", "d": "Securities/advice concept."}, "easy"),
        ("Using a borrower's NPI for personal marketing without authorization can violate:",
         {"a": "GLBA privacy/safeguards expectations and ethics", "b": "Only the yellow pages code", "c": "HMDA exclusively", "d": "Flood rules exclusively"},
         "a", "Nonpublic personal information is protected under GLBA and ethical standards.",
         {"b": "False.", "c": "HMDA is data reporting.", "d": "Flood is insurance."}, "medium"),
        ("Splitting a fee with an unlicensed person for taking applications can be a problem because:",
         {"a": "Licensing/SAFE Act and compensation rules may be violated", "b": "It always increases FICO", "c": "It is required for jumbo loans", "d": "It replaces the CD"},
         "a", "Only properly licensed/registered individuals may engage in MLO activity for compensation.",
         {"b": "Nonsense.", "c": "False.", "d": "False."}, "medium"),
        ("Encouraging a borrower to lie about occupancy (occupancy fraud) is:",
         {"a": "A common harmless tip", "b": "Mortgage fraud / ethics violation", "c": "Required for investment properties", "d": "A TRID cure"},
         "b", "False occupancy is material mortgage fraud.",
         {"a": "Not harmless.", "c": "Investment should be disclosed truthfully.", "d": "Not a cure."}, "easy"),
        ("Providing the same assistance and information to similarly situated applicants regardless of protected class is part of:",
         {"a": "Fair lending / ECOA compliance", "b": "Setting LLPAs", "c": "Choosing a flood zone arbitrarily", "d": "Calculating LTV only"},
         "a", "Consistent, non-discriminatory treatment is core fair lending.",
         {"b": "Pricing adjustments.", "c": "Flood determination process.", "d": "Math metric."}, "easy"),
        ("A 'straw buyer' scheme typically involves:",
         {"a": "A legitimate gift letter", "b": "Someone posing as the buyer to obtain a loan for another party, often fraudulently", "c": "A standard rate lock extension", "d": "An AfBA disclosure"},
         "b", "Straw buyers conceal the true purchaser/borrower—classic fraud pattern.",
         {"a": "Legitimate gifts differ.", "c": "Normal process.", "d": "Disclosure form."}, "medium"),
        ("UDAAP stands for practices that are:",
         {"a": "Unfair, deceptive, or abusive acts or practices", "b": "Uniform deed and appraisal protocols", "c": "USDA annual accounting procedures", "d": "Underwriter desk audit appraisal premiums"},
         "a", "UDAAP is a core consumer protection standard (Dodd-Frank/CFPB).",
         {"b": "Acronym mash.", "c": "False.", "d": "False."}, "easy"),
    ])

    return qs


if __name__ == "__main__":
    write_bank(E, build())
