#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "nclex-rn-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "safe-care", [
        ("A nurse is assigning tasks. Which task is appropriate to delegate to an experienced UAP?",
         {"a": "Evaluate a new wound for infection", "b": "Ambulate a stable client to the bathroom", "c": "Teach insulin self-injection", "d": "Interpret ABG results"},
         "b", "UAPs may assist stable clients with ambulation; assessment, teaching, and interpretation remain RN responsibilities.",
         {"a": "Wound evaluation is assessment.", "c": "Teaching is an RN function.", "d": "ABG interpretation requires RN/clinical judgment."}, "easy"),
        ("Which client should the RN see first after handoff?",
         {"a": "Client requesting a snack", "b": "Client with new confusion and SpO2 88% on room air", "c": "Client due for routine morning meds in 1 hour", "d": "Client waiting for discharge teaching"},
         "b", "Airway/breathing and acute mental status change are highest priority (ABCs).",
         {"a": "Comfort need is lower priority.", "c": "Routine meds can wait briefly.", "d": "Discharge teaching is important but not emergent."}, "medium"),
        ("Before applying wrist restraints, the nurse's priority action is to:",
         {"a": "Document after 8 hours", "b": "Obtain a provider order and attempt least-restrictive alternatives", "c": "Tie restraints to the side rails", "d": "Apply restraints to all four limbs immediately"},
         "b", "Restraints require an order (except emergencies per policy) and least-restrictive measures first.",
         {"a": "Documentation is required sooner and ongoing.", "c": "Never secure to moving side rails.", "d": "Use minimum necessary restriction."}, "medium"),
        ("Which action best prevents catheter-associated UTI?",
         {"a": "Routine daily catheter irrigation with antibiotics", "b": "Maintain a closed drainage system and keep the bag below the bladder", "c": "Change the catheter every 8 hours", "d": "Disconnect tubing for specimen collection without asepsis"},
         "b", "Closed system and dependent bag placement reduce CAUTI risk.",
         {"a": "Routine antibiotic irrigation is not standard prevention.", "c": "Unnecessary catheter changes increase risk.", "d": "Breaks in closed system increase infection risk."}, "easy"),
        ("A client refuses a prescribed medication. The nurse should first:",
         {"a": "Hide the medication in food", "b": "Explore the client's concerns and document refusal after education", "c": "Force administration", "d": "Ignore the refusal and chart as given"},
         "b", "Competent adults may refuse; assess understanding, educate, notify provider as needed, and document.",
         {"a": "Covert administration violates rights.", "c": "Forcing meds is assault.", "d": "Falsifying the record is unethical/illegal."}, "easy"),
        ("Which finding after a fall requires immediate notification of the provider?",
         {"a": "Small bruise on the forearm", "b": "New unequal pupils and decreasing LOC", "c": "Client embarrassment", "d": "Request for ice pack"},
         "b", "Neurologic deterioration after fall suggests possible head injury — urgent evaluation.",
         {"a": "Minor soft-tissue injury still needs assessment but is less urgent.", "c": "Psychosocial, not physiologic emergency.", "d": "Symptom relief request is lower acuity."}, "medium"),
        ("Sterile technique is broken when the nurse:",
         {"a": "Keeps sterile gloves above the waist", "b": "Turns their back to the sterile field", "c": "Opens packages away from the body", "d": "Holds sterile items in view"},
         "b", "Turning away means the field is out of sight and considered contaminated.",
         {"a": "Above-waist is correct sterile practice.", "c": "Opening away reduces contamination risk.", "d": "Keeping items in view is correct."}, "easy"),
        ("Which assignment is appropriate for a float RN unfamiliar with the unit's specialty pumps?",
         {"a": "Manage multiple novel IV chemo protocols alone", "b": "Care for stable clients with tasks matching general RN competencies, with orientation to unit equipment", "c": "Supervise without any orientation", "d": "Take only charge nurse duties immediately"},
         "b", "Float nurses should receive orientation and be assigned within verified competencies.",
         {"a": "High-risk unfamiliar technology is unsafe.", "c": "Orientation is required.", "d": "Charge requires unit familiarity."}, "medium"),
        ("A visitor asks for a client's diagnosis. The nurse should:",
         {"a": "Share details because family always may know", "b": "Confirm the client authorized disclosure before sharing PHI", "c": "Post the diagnosis on the door", "d": "Discuss loudly at the nurses' station"},
         "b", "HIPAA requires authorization (or legal exception) before disclosing PHI.",
         {"a": "Family status alone is insufficient.", "c": "Public posting violates privacy.", "d": "Loud discussion risks breach."}, "easy"),
        ("The nurse reviews new orders. Which order should the nurse question before administering?",
         {"a": "Acetaminophen 650 mg PO q6h PRN pain", "b": "Morphine 50 mg IV push now for a opioid-naive adult", "c": "Normal saline 100 mL/hr IV", "d": "Incentive spirometry q1h while awake"},
         "b", "50 mg IV morphine is an extreme dose for an opioid-naive adult and must be clarified.",
         {"a": "Standard dosing range.", "c": "Common maintenance rate.", "d": "Appropriate pulmonary toilet order."}, "hard"),
        ("Fire on the unit: the nurse's first action for a client in the room is to:",
         {"a": "Gather charting supplies", "b": "Rescue/remove the client from immediate danger (RACE)", "c": "Finish the medication pass", "d": "Call family first"},
         "b", "RACE begins with Rescue from danger, then Alarm, Contain, Extinguish/Evacuate.",
         {"a": "Equipment is secondary.", "c": "Delaying rescue is unsafe.", "d": "Notification follows safety actions."}, "easy"),
        ("Which client is the best candidate for early discharge teaching today?",
         {"a": "Client in acute respiratory distress", "b": "Stable post-op day 2 client asking about activity limits", "c": "Client actively seizing", "d": "Client with new chest pain and diaphoresis"},
         "b", "Teaching is most effective when the client is stable and ready to learn.",
         {"a": "Stabilize first.", "c": "Emergency care first.", "d": "Rule out ACS first."}, "easy"),
        ("After a medication error that reached the client with no harm, an incident report should be:",
         {"a": "Mentioned in the medical record as 'incident report filed'", "b": "Objective, factual, and completed per facility policy (usually not referenced in the chart narrative)", "c": "Used to blame staff", "d": "Delayed until discharge"},
         "b", "Incident reports are risk-management tools with objective facts; charting focuses on assessment/care without naming the report form.",
         {"a": "Typically do not reference the form in the chart.", "c": "Purpose is safety improvement, not blame.", "d": "Complete promptly."}, "medium"),
        ("Which PPE is required for a client on airborne precautions (e.g., suspected TB)?",
         {"a": "Surgical mask only at the door", "b": "N95 (or higher) respirator when entering the room", "c": "Gloves only", "d": "No PPE if the client is asleep"},
         "b", "Airborne precautions require a fit-tested respirator such as an N95.",
         {"a": "Surgical masks are insufficient for airborne TB.", "c": "Gloves alone do not protect airways.", "d": "PPE is based on transmission risk, not sleep status."}, "medium"),
        ("Priority nursing action before blood transfusion is to:",
         {"a": "Start transfusion without verification if the client looks pale", "b": "Verify client identity and blood product with a second qualified person per policy", "c": "Warm the unit in a microwave", "d": "Add medications to the blood bag"},
         "b", "Two-person verification of client and product is a core transfusion safety step.",
         {"a": "Never skip verification.", "c": "Improper warming can damage blood.", "d": "Never add meds to the blood bag."}, "medium"),
    ])

    qs += pack(E, "health-promo", [
        ("A pregnant client at 28 weeks asks about kick counts. The nurse teaches to report:",
         {"a": "Normal fetal movement patterns for that client with sudden marked decrease", "b": "Any movement at all", "c": "Movement only after meals", "d": "Movement only at night"},
         "a", "Clients should know their baby's baseline and report a significant decrease in fetal movement.",
         {"b": "Movement is expected; change from baseline matters.", "c": "Meals may increase movement but aren't the only time.", "d": "Patterns vary; teach individualized monitoring."}, "medium"),
        ("Which vaccine is generally contraindicated in pregnancy?",
         {"a": "Inactivated influenza", "b": "Tdap during pregnancy as recommended", "c": "Live attenuated MMR", "d": "COVID-19 vaccine when indicated per current guidance"},
         "c", "Live vaccines such as MMR are contraindicated in pregnancy.",
         {"a": "Inactivated flu is recommended in pregnancy.", "b": "Tdap is recommended each pregnancy (timing per guidance).", "d": "COVID vaccination is recommended when indicated."}, "medium"),
        ("Anticipatory guidance for a 2-month-old includes:",
         {"a": "Rear-facing car seat and tummy time when awake/supervised", "b": "Honey for constipation", "c": "Cow's milk as sole nutrition", "d": "No immunizations until age 2"},
         "a", "Safe sleep/car seat practices and supervised tummy time are standard early infancy guidance.",
         {"b": "Honey is unsafe under age 1 (botulism risk).", "c": "Cow's milk is not appropriate as infant primary nutrition.", "d": "Immunizations begin in early infancy per schedule."}, "easy"),
        ("A client starting a new antihypertensive should be taught to:",
         {"a": "Stop the drug when BP feels normal", "b": "Rise slowly and report dizziness/syncope", "c": "Double doses if one is missed", "d": "Avoid all follow-up visits"},
         "b", "Orthostatic precautions and reporting symptoms improve safety with antihypertensives.",
         {"a": "Do not stop abruptly without guidance.", "c": "Do not double doses unless instructed.", "d": "Follow-up is essential."}, "easy"),
        ("Screening mammography teaching for average-risk adults should emphasize:",
         {"a": "Follow age-based guidelines and discuss personal risk with a provider", "b": "Only screen after symptoms appear", "c": "Never screen if family history is negative", "d": "One lifetime mammogram is sufficient"},
         "a", "Screening intervals follow guidelines and shared decision-making based on risk.",
         {"b": "Screening aims to find disease before symptoms.", "c": "Average-risk people still need screening plans.", "d": "Periodic screening is typically needed."}, "easy"),
        ("A client with osteoporosis should be taught that weight-bearing exercise:",
         {"a": "Worsens bone density always", "b": "Can help bone health when cleared by the provider", "c": "Must be avoided completely", "d": "Replaces all medication forever"},
         "b", "Weight-bearing activity is often encouraged as part of osteoporosis management if safe.",
         {"a": "Appropriate exercise can support bone health.", "c": "Total avoidance is usually not advised.", "d": "Exercise complements, not always replaces, therapy."}, "easy"),
        ("Postpartum teaching: when should a client notify the provider about lochia?",
         {"a": "Lochia that saturates a pad in 1 hour or has large clots/foul odor", "b": "Light spotting only", "c": "Any pink discharge on day 3", "d": "Never; bleeding is always normal"},
         "a", "Heavy bleeding, large clots, or foul odor may indicate hemorrhage or infection.",
         {"b": "Light spotting can be expected.", "c": "Lochial color changes can be normal; quantity/odor matter.", "d": "Abnormal bleeding needs evaluation."}, "medium"),
        ("A school-age child with type 1 diabetes should learn to:",
         {"a": "Skip snacks during sports always", "b": "Check glucose and manage carbs/insulin around activity per plan", "c": "Stop insulin on sick days automatically", "d": "Ignore ketones when ill"},
         "b", "Activity requires planned glucose monitoring and insulin/carb adjustments.",
         {"a": "Activity often needs fuel/monitoring.", "c": "Sick-day rules usually continue insulin with guidance.", "d": "Ketone monitoring is important when ill."}, "medium"),
        ("Which statement about smoking cessation is correct?",
         {"a": "Counseling plus pharmacotherapy when appropriate improves quit rates", "b": "Willpower alone is the only evidence-based method", "c": "NRT is always forbidden", "d": "Quitting has no health benefit after age 40"},
         "a", "Combination behavioral support and approved meds/NRT improves success.",
         {"b": "Support and meds help many clients.", "c": "NRT is commonly used when appropriate.", "d": "Benefits occur at many ages."}, "easy"),
        ("A client asks about colorectal cancer screening. The nurse's best response is:",
         {"a": "Screening options and starting age depend on guidelines and personal risk", "b": "Only colonoscopy exists", "c": "Screening is unnecessary if stool looks normal", "d": "Start only after age 80"},
         "a", "Discuss guideline-based options (stool tests, colonoscopy, etc.) and risk factors.",
         {"b": "Multiple modalities exist.", "c": "Screening finds asymptomatic disease.", "d": "Starting age is typically much earlier for average risk."}, "easy"),
        ("Discharge teaching for a newborn caregiver about infant safe sleep should include:",
         {"a": "Supine on a firm surface, no soft bedding/loose objects", "b": "Prone with thick pillows", "c": "Side-lying with blankets over the face", "d": "Co-sleeping on soft couches"},
         "a", "Back-to-sleep on a firm, clear surface reduces SIDS risk.",
         {"b": "Prone and soft bedding increase risk.", "c": "Face covering is unsafe.", "d": "Unsafe sleep surfaces increase risk."}, "easy"),
        ("A client on warfarin for AF should be taught to:",
         {"a": "Eat wildly varying amounts of leafy greens without INR follow-up", "b": "Keep vitamin K intake consistent and keep INR monitoring appointments", "c": "Stop warfarin for any bruise", "d": "Take double doses after missed appointments"},
         "b", "Consistency of vitamin K and scheduled INR checks stabilize anticoagulation.",
         {"a": "Large intake swings affect INR.", "c": "Report significant bleeding; don't self-stop without advice.", "d": "Do not double without instructions."}, "medium"),
        ("Menopause teaching: which symptom warrants prompt evaluation?",
         {"a": "Mild hot flashes", "b": "Postmenopausal vaginal bleeding", "c": "Occasional night sweats", "d": "Interest in lifestyle changes"},
         "b", "Postmenopausal bleeding needs evaluation to rule out pathology.",
         {"a": "Common vasomotor symptom.", "c": "Common; still discuss management.", "d": "Positive engagement, not an emergency."}, "medium"),
        ("A teenager starting isotretinoin must understand:",
         {"a": "Pregnancy prevention requirements are critical due to teratogenicity", "b": "It is safe in pregnancy", "c": "No lab monitoring is ever needed", "d": "It treats bacterial meningitis"},
         "a", "Isotretinoin is highly teratogenic; pregnancy prevention programs are mandatory.",
         {"b": "Contraindicated in pregnancy.", "c": "Monitoring is often required.", "d": "Used for severe acne, not meningitis."}, "hard"),
        ("Community teaching for heat wave safety includes:",
         {"a": "Encourage hydration and cooling for older adults and outdoor workers", "b": "Advise complete fluid restriction", "c": "Recommend heavy dark clothing at midday", "d": "Ignore early heat exhaustion signs"},
         "a", "High-risk groups need hydration, shade, and early symptom recognition.",
         {"b": "Dehydration worsens heat illness.", "c": "Light, loose clothing is preferred.", "d": "Early signs need action."}, "easy"),
    ])

    qs += pack(E, "psychosocial", [
        ("Best therapeutic response to 'I feel like a burden' is:",
         {"a": "You shouldn't feel that way", "b": "Tell me more about what's making you feel like a burden", "c": "Everyone feels that sometimes—it'll pass", "d": "Let's talk about the weather"},
         "b", "Open-ended exploration validates feelings and gathers assessment data.",
         {"a": "Dismisses feelings.", "c": "Minimizes.", "d": "Changes subject."}, "easy"),
        ("A client with alcohol withdrawal is at highest risk for:",
         {"a": "Improved sleep without monitoring", "b": "Seizures and autonomic instability", "c": "Immediate lifelong immunity to alcohol", "d": "No need for CIWA assessment"},
         "b", "Alcohol withdrawal can cause seizures, delirium tremens, and autonomic hyperactivity.",
         {"a": "Sleep may be disrupted; monitoring is required.", "c": "False.", "d": "Structured assessment guides treatment."}, "medium"),
        ("Priority nursing action for a client with active suicidal ideation and a plan is to:",
         {"a": "Leave the client alone to rest", "b": "Ensure safety (1:1/observation per protocol) and remove means", "c": "Argue that suicide is wrong", "d": "Promise total secrecy from the team"},
         "b", "Safety first: observation and means restriction; share information with the care team.",
         {"a": "Isolation increases risk.", "c": "Judgment blocks communication.", "d": "Safety overrides secrecy promises."}, "medium"),
        ("The nurse suspects elder abuse during a home visit. The priority action is to:",
         {"a": "Ignore unless there is a confession", "b": "Report per mandatory reporting laws and ensure immediate safety", "c": "Confront the abuser alone in private without a plan", "d": "Document nothing"},
         "b", "Nurses are mandatory reporters; protect the client and follow reporting statutes.",
         {"a": "Suspicion often triggers reporting duties.", "c": "Unsafe confrontation can escalate harm.", "d": "Document objectively."}, "medium"),
        ("A client with schizophrenia says, 'The TV is sending me messages.' Best response:",
         {"a": "That's true; I hear them too", "b": "I don't hear those messages, but it sounds frightening—you're safe here", "c": "Stop lying", "d": "Ignore the client completely"},
         "b", "Do not reinforce delusions; acknowledge feelings and provide reality/safety.",
         {"a": "Colluding reinforces delusion.", "c": "Accusatory.", "d": "Therapeutic engagement is needed."}, "medium"),
        ("SSRIs: which teaching is essential early in therapy?",
         {"a": "Mood improves instantly in 1 hour for everyone", "b": "Report worsening mood/suicidality, especially early in treatment", "c": "Combine freely with St. John's wort without advice", "d": "Stop abruptly when feeling better"},
         "b", "Early treatment can increase agitation/suicidality risk; teach reporting and follow-up.",
         {"a": "Onset is usually weeks.", "c": "Serotonin syndrome risk with some combinations.", "d": "Taper under guidance."}, "medium"),
        ("Grief: which statement suggests complicated grief needing further evaluation?",
         {"a": "I cry sometimes when I see photos", "b": "It's been a year and I can't function, sleep, or leave the house at all", "c": "I miss them on holidays", "d": "I'm seeing a support group"},
         "b", "Prolonged severe functional impairment suggests complicated grief/depression evaluation.",
         {"a": "Normal grief expression.", "c": "Common anniversary reaction.", "d": "Adaptive coping."}, "easy"),
        ("A client with anxiety is hyperventilating. Priority intervention:",
         {"a": "Leave them alone in a locked room", "b": "Coach slow breathing and stay with the client in a calm environment", "c": "Have them breathe into a plastic bag without assessment", "d": "Administer insulin"},
         "b", "Calm presence and controlled breathing reduce acute hyperventilation/anxiety.",
         {"a": "Abandonment increases panic.", "c": "Rebreathing methods need proper assessment/technique.", "d": "Not indicated for anxiety hyperventilation."}, "easy"),
        ("Therapeutic communication technique of reflecting means:",
         {"a": "Giving advice immediately", "b": "Mirroring the client's feelings to deepen understanding", "c": "Changing the subject", "d": "Promising outcomes"},
         "b", "Reflection clarifies emotion and encourages elaboration.",
         {"a": "Advice may block exploration.", "c": "Avoidance.", "d": "False reassurance."}, "easy"),
        ("A client taking lithium reports symptoms. Early signs of lithium toxicity include:",
         {"a": "Improved concentration only", "b": "Nausea, vomiting, diarrhea, tremor, ataxia", "c": "Bright red rash that always is harmless", "d": "No symptoms ever"},
         "b", "GI symptoms, tremor, and neurologic changes suggest rising lithium levels.",
         {"a": "Not a toxicity hallmark.", "c": "Rash needs evaluation but classic lithium toxicity is neuro/GI.", "d": "Toxicity is symptomatic."}, "hard"),
        ("A client with PTSD has a flashback on the unit. Best initial action:",
         {"a": "Restrain immediately without assessment", "b": "Ensure safety, use calm voice, orient to present, reduce stimuli", "c": "Yell to snap them out", "d": "Leave quietly"},
         "b", "Safety, grounding, and decreased stimulation help during flashbacks.",
         {"a": "Restraints are last resort.", "c": "Escalates fear.", "d": "Stay and support unless unsafe."}, "medium"),
        ("Which nurse action is an inappropriate professional boundary crossing?",
         {"a": "Refusing personal gifts of large monetary value per policy", "b": "Sharing personal phone number for after-hours dating", "c": "Maintaining professional demeanor", "d": "Using therapeutic touch when culturally appropriate/consented"},
         "b", "Dual relationships/personal contact violate professional boundaries.",
         {"a": "Policy-compliant.", "c": "Appropriate.", "d": "May be appropriate with consent/culture."}, "easy"),
        ("For a client admitted with anorexia nervosa, the nurse's priority concern is:",
         {"a": "Fashion preferences", "b": "Electrolyte imbalance and cardiac risk from malnutrition", "c": "Choosing dessert flavors", "d": "Social media likes"},
         "b", "Physiologic instability from malnutrition is the priority.",
         {"a": "Not physiologic priority.", "c": "Irrelevant to crisis care.", "d": "Not ABC priority."}, "medium"),
        ("Client hearing command hallucinations to harm staff. Priority:",
         {"a": "Ask what the voices are saying and implement safety precautions", "b": "Whisper so voices can't hear", "c": "Agree the voices are real external people", "d": "Discharge immediately"},
         "a", "Assess content of commands and protect client/others.",
         {"b": "Ineffective.", "c": "Do not reinforce false reality.", "d": "Unsafe."}, "hard"),
        ("Motivational interviewing spirit emphasizes:",
         {"a": "Confronting and shaming", "b": "Partnership, evoking client's own reasons for change", "c": "Ordering lifestyle change without listening", "d": "Ignoring ambivalence"},
         "b", "MI elicits intrinsic motivation through collaborative conversation.",
         {"a": "Shame reduces engagement.", "c": "Directive lecturing often fails.", "d": "Ambivalence is explored, not ignored."}, "easy"),
    ])

    qs += pack(E, "physio", [
        ("A client with heart failure has sudden 2-kg weight gain and dyspnea. Priority assessment is:",
         {"a": "Favorite meal preferences", "b": "Lung sounds, SpO2, and fluid status", "c": "Hair color", "d": "TV channel choice"},
         "b", "Acute fluid overload threatens gas exchange; assess respiratory/fluid status first.",
         {"a": "Not priority.", "c": "Irrelevant.", "d": "Irrelevant."}, "easy"),
        ("Potassium 2.8 mEq/L: the nurse anticipates risk of:",
         {"a": "No ECG changes ever", "b": "Dysrhythmias and muscle weakness", "c": "Immediate hypercalcemia only", "d": "Improved digoxin safety always"},
         "b", "Hypokalemia causes weakness and dangerous dysrhythmias; digoxin toxicity risk rises.",
         {"a": "ECG changes are common.", "c": "Not the primary related imbalance.", "d": "Hypokalemia increases digoxin toxicity risk."}, "medium"),
        ("Order: heparin 1000 units/hr. Supply 25,000 units/250 mL. mL/hr is:",
         {"a": "5 mL/hr", "b": "10 mL/hr", "c": "25 mL/hr", "d": "100 mL/hr"},
         "b", "25,000/250 = 100 units/mL; 1000 units/hr ÷ 100 = 10 mL/hr.",
         {"a": "Half the required rate.", "c": "Would deliver 2500 units/hr.", "d": "Would deliver 10,000 units/hr."}, "hard"),
        ("Post-op client with PCA morphine is hard to arouse, RR 8. Priority action:",
         {"a": "Give another bolus", "b": "Stop PCA, stimulate, support airway/oxygen per protocol, notify provider", "c": "Ignore and recheck in 4 hours", "d": "Give oral opioids instead"},
         "b", "Opioid-induced respiratory depression requires stopping the opioid and supporting ventilation.",
         {"a": "Worsens depression.", "c": "Dangerous delay.", "d": "Does not address acute depression."}, "medium"),
        ("Hypoglycemia treatment for a conscious client who can swallow:",
         {"a": "IV 50% dextrose as first step always", "b": "15 g fast carbs, recheck glucose ~15 minutes", "c": "NPH insulin immediately", "d": "Skip treatment if slightly symptomatic"},
         "b", "Rule of 15 for conscious hypoglycemic clients.",
         {"a": "IV dextrose if severe/unable to swallow.", "c": "Insulin worsens hypoglycemia.", "d": "Treat symptomatic hypoglycemia."}, "easy"),
        ("COPD client: which oxygen teaching is correct?",
         {"a": "Use oxygen exactly as prescribed; report worsening dyspnea", "b": "Set oxygen as high as possible for comfort", "c": "Stop oxygen during meals forever", "d": "Share oxygen tubing between family members"},
         "a", "Titrate per order; excessive O2 can be harmful in some COPD phenotypes—follow prescription.",
         {"b": "Unprescribed high flow can be harmful.", "c": "May need O2 with meals if ordered.", "d": "Infection risk."}, "medium"),
        ("Blood transfusion reaction (fever, back pain, chills): first action:",
         {"a": "Speed up the transfusion", "b": "Stop the transfusion and keep IV open with NS per protocol", "c": "Give the rest then chart", "d": "Take no vital signs"},
         "b", "Stop transfusion immediately, maintain IV access with NS, assess, notify.",
         {"a": "Worsens reaction.", "c": "Unsafe.", "d": "Vitals are essential."}, "medium"),
        ("A client with diabetic ketoacidosis (DKA) typically presents with:",
         {"a": "Low glucose and metabolic alkalosis", "b": "High glucose, dehydration, and metabolic acidosis", "c": "Normal glucose always", "d": "Hypertension only without other signs"},
         "b", "DKA: hyperglycemia, ketosis/acidosis, volume depletion.",
         {"a": "Opposite pattern.", "c": "Glucose is elevated.", "d": "Multiple systemic findings."}, "medium"),
        ("NG tube placement confirmation before first feeding is best done by:",
         {"a": "Air bolus auscultation alone as sole method", "b": "Radiographic confirmation or facility-approved evidence-based method", "c": "Client report of 'feeling fine'", "d": "Measuring only the tape leftover"},
         "b", "X-ray (or approved method) confirms placement; air bolus alone is unreliable.",
         {"a": "Insufficient alone.", "c": "Not confirmation.", "d": "External length is not definitive."}, "hard"),
        ("Chest tube: continuous bubbling in water-seal chamber suggests:",
         {"a": "Normal intermittent bubbling with cough only always", "b": "Possible air leak that needs assessment of system/client", "c": "That the tube should be clamped for hours routinely", "d": "No action ever"},
         "b", "Continuous bubbling in water seal often indicates an air leak to troubleshoot.",
         {"a": "Intermittent with cough can be expected early; continuous needs evaluation.", "c": "Routine prolonged clamping is dangerous.", "d": "Requires assessment."}, "hard"),
        ("Client on IV vancomycin: report which finding promptly?",
         {"a": "Mild thirst", "b": "Tinnitus, oliguria, or rash/anaphylaxis signs", "c": "Hunger", "d": "Request for water"},
         "b", "Vancomycin toxicities include ototoxicity, nephrotoxicity, and hypersensitivity.",
         {"a": "Nonspecific.", "c": "Not drug toxicity hallmark.", "d": "Offer fluids if allowed."}, "medium"),
        ("Normal sinus rhythm characteristics include:",
         {"a": "Rate 150 with chaotic P waves", "b": "Rate ~60–100, regular, P before each QRS, consistent PR", "c": "No QRS complexes", "d": "Sawtooth flutter waves only"},
         "b", "NSR has regular rhythm with normal rate and 1:1 P-QRS relationship.",
         {"a": "Suggests tachyarrhythmia/AF features.", "c": "Asystole/other.", "d": "Atrial flutter pattern."}, "easy"),
        ("Post-thyroidectomy emergency: client with stridor and neck swelling. Priority:",
         {"a": "Offer ice chips and leave", "b": "Airway support and notify provider/rapid response for possible hematoma/obstruction", "c": "Give oral antibiotics first", "d": "Increase pillow height only and wait hours"},
         "b", "Airway compromise from hematoma/edema is a surgical emergency.",
         {"a": "Delays care.", "c": "Does not open airway.", "d": "Dangerous delay."}, "hard"),
        ("The nurse assesses a peripheral IV site. Signs of infiltration include:",
         {"a": "Cool, swollen, pale site with pain", "b": "Red streak ascending the vein only always meaning perfect placement", "c": "Blood return always proves no problems", "d": "No assessment needed if pump beeps"},
         "a", "Infiltration: swelling, coolness, discomfort; stop IV and follow protocol.",
         {"b": "May suggest phlebitis.", "c": "Blood return doesn't exclude all complications.", "d": "Assess the site."}, "easy"),
        ("Client with chronic kidney disease should generally avoid:",
         {"a": "Prescribed phosphate binders with meals when ordered", "b": "Unprescribed NSAIDs that can worsen kidney function", "c": "Blood pressure monitoring", "d": "Following fluid restrictions when ordered"},
         "b", "NSAIDs can reduce renal perfusion and are often avoided in CKD.",
         {"a": "Binders are often part of care.", "c": "BP control is important.", "d": "Fluid limits may be required."}, "medium"),
    ])

    return qs


if __name__ == "__main__":
    write_bank(E, build())
