#!/usr/bin/env python3
from __future__ import annotations

from _common import pack, write_bank

E = "series-65-readiness-check"


def build() -> list[dict]:
    qs: list[dict] = []

    qs += pack(E, "economics", [
        ("If the Federal Reserve conducts open-market purchases of Treasuries, the most likely near-term effect is:",
         {"a": "Higher short-term rates as reserves shrink", "b": "Increased bank reserves and downward pressure on short-term rates", "c": "Immediate statutory tax cuts", "d": "Guaranteed stock market gains"},
         "b", "OMOs that buy securities inject reserves and tend to ease short-term rates.",
         {"a": "Purchases expand, not shrink, reserves.", "c": "Fiscal policy, not Fed OMOs.", "d": "Markets are not guaranteed."}, "medium"),
        ("GDP that is adjusted for inflation is called:",
         {"a": "Nominal GDP", "b": "Real GDP", "c": "M1 money supply", "d": "Current account only"},
         "b", "Real GDP removes price-level changes to show volume of output.",
         {"a": "Nominal is in current dollars.", "c": "Money supply measure.", "d": "Trade balance component."}, "easy"),
        ("In a normal yield curve, longer-term Treasury yields are typically:",
         {"a": "Lower than short-term yields", "b": "Higher than short-term yields", "c": "Exactly zero", "d": "Unrelated to maturity"},
         "b", "A normal (upward-sloping) curve pays more for longer maturity.",
         {"a": "That describes inversion.", "c": "False.", "d": "Maturity is a key driver."}, "easy"),
        ("Which is a leading economic indicator example?",
         {"a": "Average duration of unemployment (often lagging)", "b": "Building permits / new orders (often leading)", "c": "CPI confirmed after the fact only", "d": "Corporate bond defaults after recession trough only"},
         "b", "Permits and new orders often turn before the broad economy.",
         {"a": "Unemployment duration tends to lag.", "c": "CPI is more coincident/lagging in practice discussions.", "d": "Defaults often lag."}, "medium"),
        ("Stagflation refers to:",
         {"a": "High growth and low inflation", "b": "Stagnant growth with high inflation and often high unemployment", "c": "Deflation with boom employment", "d": "Only a bull market in bonds"},
         "b", "Stagflation combines weak growth with elevated inflation.",
         {"a": "Opposite mix.", "c": "Not stagflation.", "d": "Incomplete."}, "medium"),
        ("The present value of a future cash flow rises when:",
         {"a": "The discount rate increases", "b": "The discount rate decreases", "c": "Time to receipt increases (holding rate constant)", "d": "Cash flow becomes zero"},
         "b", "Lower discount rates increase PV.",
         {"a": "Higher rates lower PV.", "c": "More time lowers PV at positive rates.", "d": "Zero CF has zero PV."}, "medium"),
        ("Systematic risk is best described as:",
         {"a": "Risk eliminable by owning one stock", "b": "Market-wide risk that diversification cannot remove", "c": "Only fraud risk", "d": "Risk unique to one firm's warehouse fire"},
         "b", "Systematic (market) risk remains after diversification.",
         {"a": "Unsystematic can be diversified.", "c": "Too narrow.", "d": "Idiosyncratic/unsystematic."}, "easy"),
        ("Beta of 1.2 suggests a stock historically:",
         {"a": "Moved less than the market", "b": "Moved about 20% more than the market on average", "c": "Has no market risk", "d": "Is risk-free"},
         "b", "Beta > 1 implies higher average sensitivity to market moves.",
         {"a": "That would be beta < 1.", "c": "False.", "d": "Equities aren't risk-free."}, "easy"),
        ("Fiscal policy tools include:",
         {"a": "Government spending and taxation", "b": "Only open-market operations", "c": "Only reserve requirements", "d": "Only the discount rate"},
         "a", "Fiscal policy is taxing/spending by government.",
         {"b": "Monetary tool.", "c": "Monetary.", "d": "Monetary."}, "easy"),
        ("CPI measures:",
         {"a": "Producer inventory only", "b": "Price changes for a basket of consumer goods/services", "c": "Corporate earnings yields only", "d": "Gold reserves at the Fed"},
         "b", "CPI tracks consumer price inflation for a defined basket.",
         {"a": "Different metrics.", "c": "Valuation concept.", "d": "Balance sheet item."}, "easy"),
        ("An inverted yield curve has often been watched as:",
         {"a": "A possible recession warning signal", "b": "Proof inflation is always zero", "c": "Evidence stocks cannot fall", "d": "A requirement to buy only munis"},
         "a", "Inversion has historically preceded many U.S. recessions (not a guarantee).",
         {"b": "False.", "c": "False.", "d": "Unrelated mandate."}, "medium"),
        ("Opportunity cost is:",
         {"a": "The value of the next-best alternative forgone", "b": "Always an accounting depreciation entry", "c": "Only brokerage commissions", "d": "A type of put option"},
         "a", "Economics defines opportunity cost as the forgone alternative.",
         {"b": "Accounting ≠ opportunity cost definition.", "c": "Too narrow.", "d": "Derivative."}, "easy"),
        ("In the expansion phase of the business cycle, typically:",
         {"a": "Unemployment falls and production rises", "b": "GDP collapses", "c": "Only bankruptcies soar by definition", "d": "Interest rates are irrelevant"},
         "a", "Expansions feature rising activity and usually improving employment.",
         {"b": "Contraction.", "c": "Not definitional.", "d": "Rates matter but aren't the definition."}, "easy"),
        ("Purchasing power risk is most associated with:",
         {"a": "Unexpected inflation eroding real returns", "b": "A single company's product recall only", "c": "Exchange-traded option expiration Friday only", "d": "Call risk on mortgages only"},
         "a", "Inflation reduces purchasing power of fixed cash flows/returns.",
         {"b": "Business-specific.", "c": "Timing/technical.", "d": "Prepayment/call is different."}, "medium"),
        ("Weakening U.S. dollar, all else equal, tends to:",
         {"a": "Make U.S. exports less competitive abroad", "b": "Make U.S. exports more competitive abroad", "c": "Eliminate currency risk for all investors", "d": "Set the Fed funds rate by law"},
         "b", "A weaker dollar makes U.S. goods cheaper in foreign currency terms.",
         {"a": "Opposite.", "c": "False.", "d": "Fed sets policy rates, not the dollar level by statute."}, "medium"),
    ])

    qs += pack(E, "products", [
        ("A key advantage of mutual funds for retail investors is:",
         {"a": "Guaranteed principal", "b": "Professional management and diversification at relatively low minimums", "c": "No market risk", "d": "FDIC insurance on equity funds"},
         "b", "Funds pool money for diversified, managed portfolios (risk remains).",
         {"a": "Not guaranteed.", "c": "Market risk remains.", "d": "Equity funds aren't FDIC-insured."}, "easy"),
        ("ETFs typically differ from traditional open-end mutual funds because ETFs:",
         {"a": "Never track an index", "b": "Trade intraday on exchanges at market prices", "c": "Cannot hold stocks", "d": "Are always actively managed hedge funds"},
         "b", "ETFs trade throughout the day like stocks; many are index-based.",
         {"a": "Many are index trackers.", "c": "They can hold equities.", "d": "Most are not hedge funds."}, "easy"),
        ("TIPS are designed primarily to protect against:",
         {"a": "Credit default of municipalities only", "b": "Inflation eroding purchasing power", "c": "Currency devaluation of bitcoin", "d": "Call risk on corporates"},
         "b", "Treasury Inflation-Protected Securities adjust with inflation.",
         {"a": "TIPS are Treasuries.", "c": "Not their design.", "d": "Different risk."}, "easy"),
        ("An American-style call option buyer has the right to:",
         {"a": "Sell the stock at any time", "b": "Buy the stock at the strike before expiration", "c": "Force dividends to increase", "d": "Avoid all losses always"},
         "b", "Calls give the right to buy at the strike; American style allows exercise before expiry.",
         {"a": "That is a put right.", "c": "No.", "d": "Options can expire worthless."}, "easy"),
        ("Investment-grade corporate bonds, relative to junk bonds, generally have:",
         {"a": "Higher credit risk and higher yields", "b": "Lower credit risk and usually lower yields", "c": "No interest-rate risk", "d": "Equity voting rights always"},
         "b", "Higher ratings imply lower credit risk and typically lower yield spreads.",
         {"a": "Opposite of IG vs HY.", "c": "Duration/rate risk remains.", "d": "Bonds don't grant common voting rights."}, "medium"),
        ("A zero-coupon bond's primary return comes from:",
         {"a": "Quarterly dividends", "b": "Accretion/purchase discount to face value", "c": "Stock split premiums", "d": "Insurance premiums paid by the holder"},
         "b", "Zeros pay no periodic coupons; return is the discount to par.",
         {"a": "Bonds don't pay stock dividends.", "c": "Equity event.", "d": "Not applicable."}, "medium"),
        ("REITs primarily provide exposure to:",
         {"a": "Real estate cash flows via a pooled security", "b": "Treasury-only portfolios", "c": "FDIC-insured CDs", "d": "Municipal general obligation taxes only"},
         "a", "REITs own/finance real estate and pass through income characteristics.",
         {"b": "Different asset.", "c": "Bank products.", "d": "Munis are different."}, "easy"),
        ("Preferred stock typically:",
         {"a": "Has priority over common for dividends but usually limited/no voting", "b": "Is identical to Treasury bills", "c": "Must convert to bonds annually", "d": "Has no dividend features ever"},
         "a", "Preferred sits above common for dividends; voting is often limited.",
         {"b": "False.", "c": "Not a requirement.", "d": "Dividends are a key feature."}, "medium"),
        ("Money market instruments generally are:",
         {"a": "Long-duration junk equities", "b": "Short-term, high-quality debt instruments", "c": "30-year zero-coupon municipals only", "d": "Physical commodities in a warehouse"},
         "b", "Money markets: short maturities, high credit quality.",
         {"a": "Opposite characteristics.", "c": "Long munis aren't MM.", "d": "Not money markets."}, "easy"),
        ("A municipal bond's tax advantage for many investors is:",
         {"a": "Interest often exempt from federal income tax (and sometimes state)", "b": "Guaranteed by the FDIC", "c": "Always higher yield than corporates of equal risk", "d": "No credit risk ever"},
         "a", "Muni interest is frequently federally tax-exempt (state rules vary).",
         {"b": "Not FDIC.", "c": "Taxable-equivalent yield analysis needed.", "d": "Credit risk exists."}, "medium"),
        ("Variable annuities' investment risk is primarily borne by:",
         {"a": "The insurance company always for market returns", "b": "The contract owner for subaccount market performance", "c": "FINRA personally", "d": "The Federal Reserve"},
         "b", "VA subaccounts expose the owner to market risk (guarantees vary by rider).",
         {"a": "Market risk sits with owner unless a guarantee applies.", "c": "False.", "d": "False."}, "medium"),
        ("Duration is a measure most useful for estimating:",
         {"a": "A stock's P/E", "b": "Bond price sensitivity to interest-rate changes", "c": "Option open interest only", "d": "GDP growth next quarter precisely"},
         "b", "Duration approximates interest-rate price sensitivity of bonds.",
         {"a": "Equity multiple.", "c": "Options metric.", "d": "Macro forecast."}, "medium"),
        ("An ADR represents:",
         {"a": "A U.S. depositary receipt for a foreign company's shares", "b": "A Treasury inflation swap", "c": "A municipal pre-refunding escrow only", "d": "A money market mutual fund share class exclusively"},
         "a", "ADRs facilitate U.S. trading of foreign equities.",
         {"b": "Different instrument.", "c": "Muni structure.", "d": "Too narrow/wrong."}, "easy"),
        ("Callable bonds expose investors primarily to:",
         {"a": "The issuer calling when rates fall, forcing reinvestment at lower yields", "b": "Unlimited upside exactly like common stock", "c": "No interest-rate risk", "d": "Mandatory conversion to crypto"},
         "a", "Call risk: bonds called in declining-rate environments.",
         {"b": "Bond upside is capped near call/par dynamics.", "c": "False.", "d": "False."}, "medium"),
        ("Hedge funds, relative to mutual funds, typically feature:",
         {"a": "Identical retail liquidity daily always", "b": "More flexible strategies, higher fees, and often accredited-investor eligibility", "c": "FDIC insurance", "d": "No use of leverage ever by definition"},
         "b", "Hedge funds are less regulated in structure, often illiquid/fee-heavy, and limited to eligible investors.",
         {"a": "Liquidity often restricted.", "c": "Not FDIC.", "d": "Many may use leverage."}, "hard"),
    ])

    qs += pack(E, "client", [
        ("A fiduciary investment adviser must:",
         {"a": "Put the client's interests ahead of their own", "b": "Maximize firm revenue regardless of client impact", "c": "Only follow suitability, never loyalty", "d": "Avoid written disclosures always"},
         "a", "Fiduciary duty includes loyalty and care for the client.",
         {"b": "Conflicts must be managed/disclosed; client first.", "c": "IA fiduciary exceeds mere suitability.", "d": "Disclosures are core."}, "easy"),
        ("Asset allocation's primary purpose is to:",
         {"a": "Eliminate all risk", "b": "Balance risk/return across asset classes aligned to goals and risk tolerance", "c": "Time the market daily", "d": "Avoid equities forever"},
         "b", "Allocation matches portfolio mix to objectives and constraints.",
         {"a": "Risk cannot be eliminated.", "c": "Allocation ≠ day trading.", "d": "Depends on client."}, "easy"),
        ("A 28-year-old with a long horizon and high risk tolerance is often suited to:",
         {"a": "100% short-term T-bills only by rule", "b": "A higher equity allocation than a retiree needing income soon", "c": "Only collectible art", "d": "Margin day-trading as the IPS default"},
         "b", "Longer horizons can typically bear more equity risk (client-specific).",
         {"a": "Too rigid.", "c": "Concentrated alternative.", "d": "Usually inappropriate default."}, "easy"),
        ("Tax-efficient placement often suggests holding:",
         {"a": "High-turnover taxable bond funds in taxable accounts and ignoring IRAs", "b": "Tax-inefficient assets in tax-advantaged accounts when appropriate", "c": "All munis inside a traditional IRA for maximum benefit always", "d": "Never using asset location"},
         "b", "Asset location: put tax-inefficient exposures in sheltered accounts when it helps.",
         {"a": "Opposite intuition often applies.", "c": "Muni tax exemption is wasted in a traditional IRA.", "d": "Location can add value."}, "hard"),
        ("Required minimum distributions (RMDs) generally apply to:",
         {"a": "Roth IRA contributions in the year made", "b": "Traditional IRAs/401(k)s after the applicable RMD age (rules evolve)", "c": "Taxable brokerage cash always monthly", "d": "529 plans at age 18 by federal mandate"},
         "b", "RMDs apply to most pre-tax retirement accounts starting at the statutory age.",
         {"a": "Roth IRA RMDs generally not during owner lifetime.", "c": "No.", "d": "No federal RMD like that."}, "medium"),
        ("An IPS (investment policy statement) should include:",
         {"a": "Only the adviser's lunch preferences", "b": "Goals, constraints, risk tolerance, and allocation guidelines", "c": "Guaranteed returns", "d": "A promise to beat the S&P every quarter"},
         "b", "IPS documents objectives, constraints, and process.",
         {"a": "Irrelevant.", "c": "Cannot guarantee.", "d": "Unrealistic promise."}, "easy"),
        ("Dollar-cost averaging is:",
         {"a": "Investing a fixed dollar amount at regular intervals", "b": "Buying only at market bottoms with perfect foresight", "c": "Avoiding equities entirely", "d": "A type of municipal pre-refunding"},
         "a", "DCA invests steadily regardless of short-term price moves.",
         {"b": "Market timing myth.", "c": "Not the definition.", "d": "Unrelated."}, "easy"),
        ("A client needing funds in 12 months for a house down payment should prioritize:",
         {"a": "Concentrated small-cap growth", "b": "Capital preservation and liquidity over high expected return", "c": "Leveraged volatility ETFs", "d": "Illiquid private equity lockups"},
         "b", "Short-horizon goals favor safety and liquidity.",
         {"a": "High risk of shortfall.", "c": "Inappropriate.", "d": "Illiquid."}, "medium"),
        ("Modern portfolio theory emphasizes that diversification can:",
         {"a": "Remove all systematic risk", "b": "Reduce unsystematic risk by combining imperfectly correlated assets", "c": "Guarantee alpha", "d": "Eliminate the need for an IPS"},
         "b", "Diversification reduces idiosyncratic risk; market risk remains.",
         {"a": "Systematic remains.", "c": "No guarantee.", "d": "IPS still needed."}, "medium"),
        ("When assessing risk tolerance, an adviser should consider:",
         {"a": "Only the client's age by a rigid formula", "b": "Willingness and ability to take risk, plus goals/constraints", "c": "Only the adviser's favorite sector", "d": "Ignoring liquidity needs"},
         "b", "Ability + willingness + circumstances drive suitable risk.",
         {"a": "Age is one factor, not sole.", "c": "Conflict.", "d": "Liquidity is key."}, "easy"),
        ("A progressive tax system means:",
         {"a": "Marginal rates rise as taxable income rises", "b": "Everyone pays the same flat dollar tax", "c": "Only capital gains are taxed", "d": "Interest is never taxed"},
         "a", "Progressive brackets tax additional income at higher marginal rates.",
         {"b": "Flat/head tax idea.", "c": "False.", "d": "False."}, "easy"),
        ("Rebalancing a portfolio typically:",
         {"a": "Sells winners and buys laggards to restore target weights", "b": "Abandons the IPS permanently", "c": "Is illegal for advisers", "d": "Only happens once in a lifetime"},
         "a", "Rebalancing restores strategic weights after drift.",
         {"b": "Opposite of discipline.", "c": "Common practice.", "d": "Usually periodic."}, "easy"),
        ("Behavioral bias: loss aversion means investors often:",
         {"a": "Feel losses more strongly than equivalent gains", "b": "Ignore prices entirely", "c": "Always maximize taxes owed", "d": "Prefer only foreign bonds"},
         "a", "Prospect theory: losses hurt more than similar gains please.",
         {"b": "False.", "c": "False.", "d": "False."}, "medium"),
        ("For a tax-sensitive taxable account, which is often more tax-efficient?",
         {"a": "High-turnover active trading each week", "b": "Low-turnover index equity exposure", "c": "Frequent short-term gain harvesting for fun", "d": "Ignoring wash-sale rules while day-trading the same security"},
         "b", "Low turnover reduces realized capital gains drag.",
         {"a": "Creates taxable events.", "c": "Increases taxes.", "d": "Wash sales disallow losses."}, "medium"),
        ("ERISA fiduciary standards (for plan fiduciaries) emphasize:",
         {"a": "Acting solely in the interest of plan participants/beneficiaries", "b": "Maximizing revenue-sharing without disclosure always", "c": "Selecting the highest-cost share class deliberately without analysis", "d": "Ignoring diversification"},
         "a", "ERISA fiduciaries must act for participants with prudence/loyalty.",
         {"b": "Conflicts problematic.", "c": "Inconsistent with prudence.", "d": "Diversification is a core concept."}, "hard"),
    ])

    qs += pack(E, "ethics", [
        ("Under the Advisers Act, an advertisement generally may not:",
         {"a": "Include fair and balanced presentations", "b": "Contain untrue statements of material fact or be otherwise misleading", "c": "Disclose conflicts", "d": "Describe the adviser's methods accurately"},
         "b", "Ads cannot be false or misleading; marketing rule sets detailed standards.",
         {"a": "Allowed if not misleading.", "c": "Often required.", "d": "Allowed if accurate."}, "easy"),
        ("Soft-dollar arrangements, when permitted, must primarily benefit:",
         {"a": "The adviser's personal vacation", "b": "Clients through research/brokerage services", "c": "Only the broker's marketing department", "d": "Unrelated office furniture always"},
         "b", "Soft dollars must provide lawful and appropriate assistance to advisory services for clients.",
         {"a": "Personal benefit is improper.", "c": "Client benefit required.", "d": "Typically not qualifying research."}, "medium"),
        ("Custody of client assets triggers:",
         {"a": "No extra rules", "b": "Additional Advisers Act custody rule requirements (e.g., qualified custodian, notices, surprise exam in many cases)", "c": "Automatic SIPC coverage for advice fees", "d": "Exemption from fiduciary duty"},
         "b", "Custody increases compliance obligations under Rule 206(4)-2 themes.",
         {"a": "False.", "c": "SIPC is about brokerage failures, not advice fees.", "d": "Duty remains."}, "hard"),
        ("An adviser trading ahead of client orders for personal benefit is an example of:",
         {"a": "Best execution", "b": "Front-running / breach of duty", "c": "Soft-dollar research", "d": "Qualified custodianship"},
         "b", "Using advance knowledge of client trades for personal gain is prohibited.",
         {"a": "Opposite of best execution ethics.", "c": "Different concept.", "d": "Custody topic."}, "easy"),
        ("Form ADV Part 2 brochure delivery is important because it:",
         {"a": "Is optional forever", "b": "Provides clients with material disclosures about the advisory business, fees, and conflicts", "c": "Replaces the need for any suitability analysis", "d": "Is filed only with state insurance departments"},
         "b", "The brochure is a key client disclosure document.",
         {"a": "Required in specified circumstances.", "c": "Doesn't replace care/fiduciary analysis.", "d": "SEC/state securities regulators."}, "medium"),
        ("Performance advertising that shows only the best accounts without disclosure is typically:",
         {"a": "Always acceptable", "b": "Misleading cherry-picking", "c": "Required by ERISA", "d": "A form of custody"},
         "b", "Selective performance without proper presentation is misleading.",
         {"a": "Not acceptable.", "c": "False.", "d": "Unrelated."}, "easy"),
        ("A solicitor arrangement generally requires:",
         {"a": "No disclosures", "b": "Required disclosures/agreements under applicable solicitor/marketing rules", "c": "Cash payments only in crypto", "d": "Avoiding written records"},
         "b", "Paid solicitation typically needs documented disclosures and compliance.",
         {"a": "False.", "c": "Nonsense.", "d": "Records are needed."}, "medium"),
        ("Insider trading involves trading on:",
         {"a": "Public SEC filings", "b": "Material nonpublic information in breach of a duty", "c": "Yesterday's closing prices", "d": "CPI releases after public announcement"},
         "b", "Classic illegal insider trading: MNPI + duty breach.",
         {"a": "Public info.", "c": "Public.", "d": "Public after release."}, "easy"),
        ("Best execution requires advisers to seek:",
         {"a": "The lowest advertised commission only, ignoring quality", "b": "The most favorable total execution quality reasonably available under the circumstances", "c": "Always the slowest venue", "d": "Only after-hours dark pools"},
         "b", "Best execution is about overall quality, not solely sticker commission.",
         {"a": "Too narrow.", "c": "False.", "d": "Not a rule."}, "medium"),
        ("Principal trades with a client generally require:",
         {"a": "No consent", "b": "Disclosure and client consent as required under Advisers Act rules", "c": "Automatic approval by FINRA exam staff", "d": "Avoiding confirmations"},
         "b", "Principal transactions need consent/disclosure under applicable rules.",
         {"a": "False.", "c": "Not how it works.", "d": "Confirms matter."}, "hard"),
        ("An adviser borrowing money from a retail client is generally:",
         {"a": "Encouraged without limits", "b": "Prohibited/highly restricted except narrow circumstances (e.g., certain broker-dealers/affiliates) under NASAA model themes", "c": "Required annually", "d": "The same as soft dollars"},
         "b", "Borrowing from clients creates severe conflicts and is largely prohibited.",
         {"a": "False.", "c": "False.", "d": "Different issue."}, "medium"),
        ("Custody can be created when an adviser:",
         {"a": "Only gives impersonal market commentary", "b": "Has authority to withdraw client fees/funds or holds client securities", "c": "Uses a third-party custodian exclusively with no fee deduction authority and no possession", "d": "Files Form ADV Part 1 only"},
         "b", "Authority over client assets/fees or possession can constitute custody.",
         {"a": "Not custody.", "c": "Properly structured can avoid custody.", "d": "Filing ≠ custody."}, "hard"),
        ("Testimonials in adviser advertising under the modern marketing rule:",
         {"a": "Are always banned without exception", "b": "May be used if conditions/disclosures are met", "c": "Require no disclosures ever", "d": "Apply only to commodity pools"},
         "b", "The marketing rule permits testimonials with required conditions.",
         {"a": "Old blanket bans changed.", "c": "Disclosures required.", "d": "Advisers Act marketing."}, "medium"),
        ("A conflict of interest should be:",
         {"a": "Hidden if profitable", "b": "Identified, disclosed, and mitigated/eliminated as appropriate", "c": "Ignored if the client doesn't ask", "d": "Resolved by increasing fees quietly"},
         "b", "Fiduciary process: disclose and manage conflicts.",
         {"a": "Violation.", "c": "Duty is proactive.", "d": "Worsens conflict."}, "easy"),
        ("Books and records for advisers must generally be:",
         {"a": "Kept for required periods and available for inspection", "b": "Destroyed weekly", "c": "Stored only on personal phones without backup", "d": "Optional if AUM is high"},
         "a", "Recordkeeping rules mandate retention and accessibility.",
         {"b": "Violates retention.", "c": "Inadequate controls.", "d": "AUM doesn't waive rules."}, "easy"),
    ])

    return qs


if __name__ == "__main__":
    write_bank(E, build())
